### ISSUE TITLE
请问如何在首次载入数据的时候主动触发 pullup or pulldown？

### ISSUE THREAD

**Issue by think2011** [airyland/vux#1001]
我观察 饿了么 手机端的列表场景是这样的

1. 首次访问，顶部开始动画跳动（就像是上拉刷新），一会第一屏数据列表出现了
2. 用户开始下拉页面查看列表，拉到底部时，下拉加载的动画开始转动，一会数据加载完毕，可以继续查看了

然后我在使用 vux 时也想实现如上的使用场景 

但关于第一步我没有找到主动触发 pulldown 的接口
于是我翻阅源码，找到了触发 loading 事件的办法 `this.$refs.scroller.pulldown.trigger('loading')`，但仅仅只是发起了请求，页面并没有出现想要的效果 

请问我该如何实现呢，或者我并没有理解使用方法？

**Comment by wg5945** [comment]
将pulldownStatus 默认值设为'loading'

进入页面后调用接口获取数据，成功后再调用组件的donePulldown()方法

大致是这样的吧

**Comment by airyland** [comment]
不支持，需要自行实现。你可以直接在那里放个loading按钮，加载完就隐藏。

**Comment by think2011** [comment]
@wg5945  我再验证了一下，默认值设置为 loading，页面并没有对应变化

@airyland 明白了，谢谢

**Comment by wg5945** [comment]
哦，不好意思，应该是按照作者所说的

我看了下之前的代码，的确在scroller上面加了一个Loading框，忘记了 - -
