### ISSUE TITLE
import md5 will throw error

### ISSUE THREAD

**Issue by zack24q** [airyland/vux#1007]
### Version
vux ```2.1.1-rc.4```
webpack ```2.2.1```
vux-loader ```1.0.44```
### Platform
chrome 56
### My Codes
``` js
import { md5 } from 'vux'
```
### Steps to reproduce the problem
import md5 from vux will cause browser throw this error
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

**Comment by zack24q** [comment]
很可能是在windows系统下，webpack打包不能在js文件中混用import以及module.exports

**Comment by airyland** [comment]
上次改漏了，下午发个小版本。

**Comment by zack24q** [comment]
issue答复好快，我找到原因后正打算写个PR
