### ISSUE TITLE
umd文件引入报错

### ISSUE THREAD

**Issue by jy05568536** [airyland/vux#1009]
![image](https://cloud.githubusercontent.com/assets/5037606/23390993/8ab7c4ac-fdac-11e6-82c9-3d27af0beeec.png)

**Comment by jy05568536** [comment]
![image](https://cloud.githubusercontent.com/assets/5037606/23405128/bc94341e-fdf3-11e6-85c4-e5f024716ead.png)
直接build报错了

**Comment by airyland** [comment]
你node版本太低了吧。直接更新到7.6.0吧。
