### ISSUE TITLE
toast type: warn

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#1016]
type为warn 颜色依然是白色的

**Comment by lichunqiang** [comment]
具体的复现环境是怎么样的？demo中的是正常的。

**Comment by jsonviewer** [comment]
```
      this.$vux.toast.show({
        type: 'warn',
        width: '7.6em',
        text: '无网络服务',
        position: 'middle',
        time: 50000,
      });
```
插件形式调用，审查样式，.weui-toast_forbidden的样式被覆盖了 @lichunqiang @airyland 
![image](https://cloud.githubusercontent.com/assets/22734724/23459769/dcd61566-febc-11e6-8962-175d71be1214.png)

**Comment by jsonviewer** [comment]
图标依然是白色 @airyland 
![image](https://cloud.githubusercontent.com/assets/22734724/23498250/c4fe520a-ff61-11e6-97b7-7466c9956b2a.png)

**Comment by airyland** [comment]
:sweat: 你应该上个截图的。我以为只有文字变白色，你上面的审查截图也只有文字颜色。

**Comment by jsonviewer** [comment]
好吧。。下回描述清楚点

**Comment by jsonviewer** [comment]
這个问题貌似还没有解决。。@airyland
