### ISSUE TITLE
XIcon直接使用报未注册组件的错误

### ISSUE THREAD

**Issue by fengjiankang** [airyland/vux#1018]
for example, the code: x-icon(type="ios-arrow-up")  in version vux  "2.1.1-rc.5", vux-loader "^1.0.43", I see the source code , the introduce tell me I don't need import

**Comment by transtone** [comment]
就是XIcon该怎么用，
```js
  import { XIcon } from 'vux';

  export default {
    components: {
     XIcon
    },
}
```
这样会报错：
```js
This module was not found:

* vux/undefined in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/BookOrders.vue

To install it, you can run: npm install --save vux/undefined
```

**Comment by airyland** [comment]
upgrade vux-loader to v1.0.46, then you can use:

``` html
<x-icon type="ios-arrow-up"></x-icon>
```

**Comment by Tiacx** [comment]
我想问一下，引用图标的时候出现xml和DOCTYPE头，是我下载错了么（从 ionic 官网下的），还是要怎么处理？我尝试手动清了svg文件里的xml和DOCTYPE头，能是能显示，但不能控制图标大小
![image](https://cloud.githubusercontent.com/assets/14041306/23692022/28bfdbf2-0407-11e7-963f-00059636d9ce.png)

**Comment by airyland** [comment]
@TTT1231 没下错，svg 里有 width 和 height，更改一下就可以了。
`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"`

**Comment by Tiacx** [comment]
@airyland 那它为什么显示出了 xml和DOCTYPE头，要手动删掉吗？

**Comment by airyland** [comment]
@Tiacx 😓 当然要删掉。

**Comment by Tiacx** [comment]
@airyland 好吧，这样子好像挺麻烦的，图标那么多。还有一个， 要在 svg 里直接改大小的话，x-icon 上的size 属性不能用了吗？那样的话，如果多个地方用同一个图标的话，大小不好控制

**Comment by airyland** [comment]
@Tiacx 你不是直接下载图标吗，为什么又变成了引用x-icon。x-icon 的 size 就是帮你直接修改 svg 里的width height大小的。

**Comment by Tiacx** [comment]
@airyland  使用 x-icon 不是需要自己下载 icons 文件放 /node_modules/vux/src/icons 里吗？不然的话会报 ENOENT: no such file or directory, open 'x:\xxxx\vue\node_modules\vux\src\icons\ios-ionic-outline.svg'

**Comment by airyland** [comment]
@Tiacx 你版本不对。

**Comment by fudanglp** [comment]
@airyland 
@Tiacx  说的没错，你看看vux-loader/src/libs/parse-x-icon.js line 11-14
    
let svgPath = path.resolve(config.options.projectRoot, `node_modules/vux/src/icons/${type}.svg`)
    if (config.options.vuxDev) {
      svgPath = path.resolve(config.options.projectRoot, `src/icons/${type}.svg`)
    }

**Comment by airyland** [comment]
@fudanglp 没看出问题。 node_modules/vux/src/icons 里是有图标的。

**Comment by fudanglp** [comment]
@airyland  他的意思是他想要加一个自己的svg作为icon，就只能塞到 node_modules/vux/src/icons 里了。我也遇到这个问题，所以找到这里了。

**Comment by airyland** [comment]
@fudanglp 这个没必要啊，既然知道自己要用哪个 icon，直接放项目下引用 svg 就行了，放到 node_modules 里已经不能管理了。

**Comment by fudanglp** [comment]
@airyland 写成x-icon不是比较简洁吗，维护起来好一点

**Comment by airyland** [comment]
@fudanglp 这样的话，这些图标没法维护了啊。。vux 版本一更新不就把这些自己加的图标覆盖没了，node_modules 里的东西一般不进版本库，这样的话，你总不能让另一个协作的同事自已下个 icon 拷贝到 node_modules 吧。。

**Comment by fudanglp** [comment]
@airyland 我的建议是vux的图标不动，
`if (config.options.vuxDev) {`
加个fallback,改成
`if(config.options.vuxDev||svgPath==null)`

**Comment by fudanglp** [comment]
@airyland  我的建议是vux的图标不动，
`if (config.options.vuxDev) {`
加个fallback,改成
`if(config.options.vuxDev||fs.existsSync(svgPath)==false)`

我自己加的图标名字和ion的区别开就行了。
