### ISSUE TITLE
Cell组件高度问题

### ISSUE THREAD

**Issue by QiDa-007** [airyland/vux#1019]
hello，在Group中使用Cell发现他的高度很高
![image](https://cloud.githubusercontent.com/assets/11505520/23455159/9e3e6aaa-fea9-11e6-9474-46433649ea7b.png)

依赖使用的是最新的：
"dependencies": {
    "vue-resource": "^1.0.3",
	  "vux": "2.1.1-rc.5",
    "fastclick": "^1.0.6",
    "vuex-i18n": "^1.3.1",
    "vuex": "^2.1.1",
    "vue": "^2.1.10",
    "vue-router": "^2.2.0"
  },

**Comment by wuxushun** [comment]
我也遇到这个问题了，怎么解决

**Comment by Przeblysk** [comment]
样式加上 a{
      text-decoration: none;
    }
    p{
      margin: 0;
      padding: 0;
    }

**Comment by brahmachen** [comment]
```css
```

**Comment by brahmachen** [comment]
```css
<style lang="less">
	@import '~vux/src/styles/reset.less';
</style>

```
