### ISSUE TITLE
iphone5s 访问二级页面，空白页。

### ISSUE THREAD

**Issue by hareboy** [airyland/vux#102]

**Comment by airyland** [comment]
浏览器是哪个。二级页面是所有demo页面看不到？

**Comment by hareboy** [comment]
所有的都看不到，iphone5s － 微信，我用chrome试了一下。iphone5也不好使，iphone6就好使。

**Comment by airyland** [comment]
@hareboy  iphone5s 用chrome试了一下，然后呢，还是空白？

**Comment by hareboy** [comment]
chrome不好使，微信好使了，好像有些不稳定。

**Comment by airyland** [comment]
@hareboy 听你的描述，还是看不明白 :sweat:  会不会是网络原因呢？

**Comment by hareboy** [comment]
你看看http://chuantu.biz/t3/8/1460431190x1035372901.png

**Comment by airyland** [comment]
@hareboy 看到了，是路由的问题，你应该是直接进入了demo列表或者在demo列表刷新了，导致路由多了一级。

**Comment by hareboy** [comment]
呃呃呃。明白了。

**Comment by airyland** [comment]
代码上也做了处理。
