### ISSUE TITLE
插件形式调用组件的一个疑问

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#1023]
开发中遇到這么个问题，我在好几个地方用了alert，如:

```
 app.$vux.alert.show({
      title: '提示',
      content: '请求超时，请稍后重新尝试!!',
});
```
当我又调用alert的时候，增加了一个onHide方法，如:
```
    app.$vux.alert.show({
      title: '提示',
      content: '数据上传成功!',
      onHide() {
        app.$router.go(-1);
      },
    });
```
由于只有一个alert实例，我得再去找到其他的alert，增加一个onHide() {}空方法，如果多了可能还找不全，出现一些诡异的现象，使用toast的时候這个现象尤其明显，增加一个属性就得去其他toast里面再增加。

**Comment by airyland** [comment]
看起来是参数没有重置导致的。

**Comment by jsonviewer** [comment]
上回我问过有关這个的问题 #870 我的意思是重新调用的时候能不能默认重置，這样可能会比较好

**Comment by jsonviewer** [comment]
现在是所有插件形式调用的组件，传参都不用手动重置了吗？是的话我就把我的代码改一下 @airyland
