### ISSUE TITLE
x-input如何修改placeholder样式？

### ISSUE THREAD

**Issue by Sangakuki** [airyland/vux#1026]
### Your Codes 
``` html
 <group label-width="4em" label-margin-right="2em" label-align="right">
    <x-input title="充值金额" :placeholder="holder"></x-input>
 </group>

  input::-webkit-input-placeholder {
    color: lightskyblue;
  }
  x-input::-webkit-input-placeholder {
    color: lightskyblue;
  }
```

### Expected behavior and actual behavior.
我想更改x-input的placeholder样式，如靠右显示、颜色什么的，但是没有变化。
但是H5的<input>就可以。
### Steps to reproduce the problem
请问我要如何将x-input的placeholder居右显示。

**Comment by lichunqiang** [comment]
https://css-tricks.com/almanac/selectors/p/placeholder-shown/

http://codepen.io/anon/pen/KWzRLM

**Comment by airyland** [comment]
参考 @lichunqiang 的链接。另外如果你使用了 scoped，样式将无法生效。

**Comment by nongzhenli** [comment]
@airyland  正好请教一个问题：
在项目开发中，难免会使用scoped，但是发现一些el（元素）是由vux组件生成的吧。

> 关于在scoped中无法去修改 vux组件生成元素的样式

请问有什么解决办法吗？

> 我个人目前就是只能在当前模板下再另外新建一个style 不加scoped属性

**Comment by wg5945** [comment]
@bigheiqin 

升级vue-loader到最新版

新增了 >>> 的用法

less和sass的话使用 /deep/

https://github.com/vuejs/vue-loader/releases
