### ISSUE TITLE
popup-picker华为mate9 自带浏览器下显示不正常

### ISSUE THREAD

**Issue by huncent** [airyland/vux#1032]
### Version
官方例子：https://vux.li/#/zh-CN/demos/popup-picker
### Android or iOS
华为Mate9 android 7.0

页面可以显示，但点那些下拉选择时遮罩层遮住了，无法进行选择！

![wechatimg1](https://cloud.githubusercontent.com/assets/32548/23597447/e3096032-026d-11e7-9a28-70f73304a4fa.jpeg)

**Comment by lichunqiang** [comment]
手头没有此机型，方便定位下问题吗?

**Comment by airyland** [comment]
之前出现此问题的只有 Safari，难道是华为或者 Android 7 向 iOS 学习了 😅

**Comment by huncent** [comment]
airyland既然碰到，估计也知道问题所在😅
如果有思路，我可以帮忙测试，手上正好有华为的机子

**Comment by airyland** [comment]
@huncent 有空再测试下这个demo

**Comment by huncent** [comment]
还是一样的效果，我试过360浏览器没问题，微信里也没问题，应该还是跟浏览器标志判断有关系！
![wechatimg3](https://cloud.githubusercontent.com/assets/32548/23732565/bd58ed2e-04ae-11e7-9c79-5e35c1f431cb.jpeg)
![wechatimg2](https://cloud.githubusercontent.com/assets/32548/23732564/bd0bd886-04ae-11e7-8644-79f3645eac51.jpeg)

**Comment by airyland** [comment]
然而现在代码里没有做任何判断。这应该是特定浏览器的问题了。没有这个机型，所以暂时不能怎么测试了。

**Comment by huncent** [comment]
可否提供下思路，我fork对应代码本地测试看看

**Comment by airyland** [comment]
@huncent 只能靠修改比如z-index，overflow等定位相关的属性来确定哪里的问题

**Comment by huncent** [comment]
奇怪的问题，我自己复制
https://github.com/airyland/vux/blob/v2/src/demos/PopupPicker.vue
源码跑了正常，@airyland 
官方例子还是不正常

**Comment by airyland** [comment]
@huncent 那么应该是100%布局导致的问题。你试一下像demo一样限定100%宽高。

**Comment by HeySeven** [comment]
这个问题可以三方面考虑原因：
1.position定位z-index导致
2.css3的transform   3d转换影响层级关系
3.内容体如果设置 -webkit-overflow-scrolling: touch;也会出现这个问题，不过组件里有用添加class类vux-fix-safari-overflow-scrolling做处理，可以参考解决

**Comment by airyland** [comment]
@hucent 做了个大调整，默认使用 transfer-dom，麻烦帮忙测试一下 demo 页面。

**Comment by huncent** [comment]
@airyland 经测试，新的demo在华为浏览器显示正常😊

**Comment by airyland** [comment]
普天同庆

**Comment by josephmax** [comment]
我的解决方式是把你写的popup picker拷了出来自己改了一点。。。
个人觉得所有弹出层还是应该在dom结构的最外层，这样组织z-index比较方便。

代码如下：

```html
<popup v-model="showValue" class="vux-popup-picker" :id="'vux-popup-picker-'+uuid" ref="picker"
           @on-hide="onPopupHide" @on-show="$emit('on-show')">
      <div class="vux-popup-picker-container">
        <div class="vux-popup-picker-header">
          <flexbox>
            <flexbox-item class="vux-popup-picker-header-menu" @click.native="onHide(false)">{{cancelText ||
              $t('cancel_text')}}
            </flexbox-item>
            <flexbox-item class="vux-popup-picker-header-menu vux-popup-picker-header-menu-right" @click.native="onHide(true)">{{confirmText || $t('confirm_text')}}
            </flexbox-item>
          </flexbox>
        </div>
        <picker
          :data="data"
          v-model="tempValue"
          @on-change="onPickerChange"
          :columns="columns"
          :fixed-columns="fixedColumns"
          :container="'#vux-popup-picker-'+uuid"></picker>
    </div>
 </popup>
```
........

```javascript
export default {
    mounted () {
      this.$nextTick(() => {
        document.body.appendChild(this.$refs.picker.$el)
      })
    }
}

```

**Comment by airyland** [comment]
@josephmax 解决方式和你是一样的，现在是使用 v-transfer-dom 来实现。
