### ISSUE TITLE
2.1.0的cell组件is-link箭头无效

### ISSUE THREAD

**Issue by hzfhhh** [airyland/vux#1033]
如题，2.1.0的cell组件is-link箭头无效，查了一下没找到`.weui-cell_access`对应的样式，不知是不是这个问题导致的

**Comment by lichunqiang** [comment]
最新的Demo是没有问题的，要不你升级下到最新的版本。

**Comment by cluod** [comment]
<cell style="background: white;"
            :title="11"
            is-link
            :border-intent="false"
            :arrow-direction="showContent001 ? 'up' : 'down'"
            @click.native="showContent001 = !showContent001"></cell>

          <template v-if="showContent001">
            <cell-box :border-intent="false" class="sub-item" is-link>content 001</cell-box>
            <cell-box class="sub-item" is-link>content 001</cell-box>
            <cell-box class="sub-item" is-link>content 001</cell-box>
我的也没有用，用的2.3.1版本，不是版本的问题吧
