### ISSUE TITLE
按需加载，npm run build 页面空白

### ISSUE THREAD

**Issue by jianchengwang** [airyland/vux#1034]
### npm run build 页面显示空白

路由设置为按需加载的话，npm run build 就显示空白，npm run dev可以正常显示

之前这样可以
`import MeCoupons from '../page/MeCoupons.vue'
import MeLoves from '../page/MeLoves.vue'
`

现在这样
`
    {
      path: '/regist',
      component: function (resolve) {
        require(['../page/Regist.vue'], resolve)
      }
    },
`
npm run dev 是根目录 /
npm run build 生成dist目录，我将它改成mall名字，放在服务器的根目录下，显示一片空白

**Comment by airyland** [comment]
I don't think it's vux's issue.
