### ISSUE TITLE
vue脚手架生成的webpack项目引入vux后运行不起来

### ISSUE THREAD

**Issue by liutao0532** [airyland/vux#1037]
我项目是用vuecli 生成的webpack项目
之前开发好用 想引入vux 然后cnpm install 以后就提示我缺好多文件
These dependencies were not found:

* object-assign in ./~/.npminstall/vux/2.1.1-rc.6/vux/src/plugins/locale/index.j
s, ./~/.npminstall/vux/2.1.1-rc.6/vux/src/directives/transfer-dom/index.js and 3
 others
* babel-runtime/helpers/typeof in ./~/.npminstall/babel-loader/6.3.2/babel-loade
r/lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=script&i
ndex=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/checker/checker-item.vu
e, ./~/.npminstall/babel-loader/6.3.2/babel-loader/lib!./~/.npminstall/vue-loade
r/11.1.4/vue-loader/lib/selector.js?type=script&index=0!./~/.npminstall/vux/2.1.
1-rc.6/vux/src/components/picker/index.vue
* babel-runtime/core-js/json/stringify in ./~/.npminstall/babel-loader/6.3.2/bab
el-loader/lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=
script&index=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/checker/checker
-item.vue, ./~/.npminstall/babel-loader/6.3.2/babel-loader/lib!./~/.npminstall/v
ue-loader/11.1.4/vue-loader/lib/selector.js?type=script&index=0!./~/.npminstall/
vux/2.1.1-rc.6/vux/src/components/checklist/index.vue and 5 others
* babel-runtime/core-js/object/keys in ./~/.npminstall/babel-loader/6.3.2/babel-
loader/lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=scr
ipt&index=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/checklist/index.vu
e, ./~/.npminstall/babel-loader/6.3.2/babel-loader/lib!./~/.npminstall/vue-loade
r/11.1.4/vue-loader/lib/selector.js?type=script&index=0!./~/.npminstall/vux/2.1.
1-rc.6/vux/src/components/datetime/index.vue and 2 others
* photoswipe/dist/photoswipe in ./~/.npminstall/babel-loader/6.3.2/babel-loader/
lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=script&ind
ex=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/previewer/index.vue
* photoswipe/dist/photoswipe-ui-default in ./~/.npminstall/babel-loader/6.3.2/ba
bel-loader/lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type
=script&index=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/previewer/inde
x.vue
* qr.js/lib/QRCode in ./~/.npminstall/babel-loader/6.3.2/babel-loader/lib!./~/.n
pminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=script&index=0!./~/.
npminstall/vux/2.1.1-rc.6/vux/src/components/qrcode/index.vue
* qr.js/lib/ErrorCorrectLevel in ./~/.npminstall/babel-loader/6.3.2/babel-loader
/lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=script&in
dex=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/qrcode/index.vue
* validator/lib/isEmail in ./~/.npminstall/babel-loader/6.3.2/babel-loader/lib!.
/~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=script&index=0!
./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/x-input/index.vue
* validator/lib/isMobilePhone in ./~/.npminstall/babel-loader/6.3.2/babel-loader
/lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=script&in
dex=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/x-input/index.vue
* vux-xscroll/build/cmd/xscroll.js in ./~/.npminstall/babel-loader/6.3.2/babel-l
oader/lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=scri
pt&index=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/scroller/index.vue
* vux-xscroll/build/cmd/plugins/pulldown in ./~/.npminstall/babel-loader/6.3.2/b
abel-loader/lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?typ
e=script&index=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/scroller/inde
x.vue
* vux-xscroll/build/cmd/plugins/pullup in ./~/.npminstall/babel-loader/6.3.2/bab
el-loader/lib!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector.js?type=
script&index=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/scroller/index.
vue
* array-filter in ./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/picker/chain
.js
* array-from in ./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/swiper/swiper.
js
* -!../../../../../../css-loader/0.26.2/css-loader/index.js?{"minimize":false,"s
ourceMap":false}!photoswipe/dist/photoswipe.css in ./~/.npminstall/css-loader/0.
26.2/css-loader?{"minimize":false,"sourceMap":false}!./~/.npminstall/vue-loader/
11.1.4/vue-loader/lib/style-rewriter.js?{"id":"data-v-9ec0c244","scoped":false,"
hasInlineConfig":true}!./~/.npminstall/vue-loader/11.1.4/vue-loader/lib/selector
.js?type=styles&index=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/components/previe
wer/index.vue
* -!../../../../../../css-loader/0.26.2/css-loader/index.js?{"minimize":false,"s
ourceMap":false}!photoswipe/dist/default-skin/default-skin.css in ./~/.npminstal
l/css-loader/0.26.2/css-loader?{"minimize":false,"sourceMap":false}!./~/.npminst
all/vue-loader/11.1.4/vue-loader/lib/style-rewriter.js?{"id":"data-v-9ec0c244","
scoped":false,"hasInlineConfig":true}!./~/.npminstall/vue-loader/11.1.4/vue-load
er/lib/selector.js?type=styles&index=0!./~/.npminstall/vux/2.1.1-rc.6/vux/src/co
mponents/previewer/index.vue

To install them, you can run: npm install --save object-assign babel-runtime/hel
pers/typeof babel-runtime/core-js/json/stringify babel-runtime/core-js/object/ke
ys photoswipe/dist/photoswipe photoswipe/dist/photoswipe-ui-default qr.js/lib/QR
Code qr.js/lib/ErrorCorrectLevel validator/lib/isEmail validator/lib/isMobilePho
ne vux-xscroll/build/cmd/xscroll.js vux-xscroll/build/cmd/plugins/pulldown vux-x
scroll/build/cmd/plugins/pullup array-filter array-from -!../../../../../../css-
loader/0.26.2/css-loader/index.js?{"minimize":false,"sourceMap":false}!photoswip
e/dist/photoswipe.css -!../../../../../../css-loader/0.26.2/css-loader/index.js?
{"minimize":false,"sourceMap":false}!photoswipe/dist/default-skin/default-skin.c
ss
> Listening at http://localhost:8080
怎么破

**Comment by airyland** [comment]
你依赖都没安装完整吧。

**Comment by liutao0532** [comment]
依赖是要我自己一个一个安装不是自动个关联安装的吗？

**Comment by airyland** [comment]
不用一个一个安装。尝试删除node_modules后重新安装。
