### ISSUE TITLE
swiper/picker组件不支持鼠标事件

### ISSUE THREAD

**Issue by michael829** [airyland/vux#1039]
呃..不要打我..因为希望webapp支持手机+PC都能打开正常使用...在不考虑适配PC的情况下希望能实现相同的功能...所以我是用PC测试DEMO链接的..手机上已经测试完了...

问题:
https://vux.li/demos/v2/?x-page=v2-doc-home#/component/swiper
https://vux.li/demos/v2/?x-page=v2-doc-home#/component/picker
https://vux.li/demos/v2/?x-page=v2-doc-home#/component/popup-picker
所有用到swiper/picker的组件都无法拖拽进行选择操作..应该是用了touch事件吧..因为其它组件都能够正常布局和交互.所以这里是否能考虑也支持一下mouse事件?非常感谢!~~!

平台:
MAC 10.12 + CHROME 55

**Comment by airyland** [comment]
组件本来就是定位于手机端使用的，PC端可能用到的场景只有在微信客户端里吧。

**Comment by michael829** [comment]
感谢回复...的确是用于手机端webapp的..但是其它组件都是完整能够使用的..就这几个关于拖拽手势操作的组件在PC上失效蛮可惜的...这种需求挺尴尬的..做两套界面适配不同场景太耗费精力和成本..做一套移动端webapp项目又碰上这几个关键组件用不了还无法替代...呵呵...至少有fallback方案也能接受呢...暂时先做着..期待后面的更新...

**Comment by airyland** [comment]
很快会支持。支持用鼠标拖动，但不会支持 mousewheel。

**Comment by airyland** [comment]
swiper 没有必要支持 PC。PC上也没有这种拖动轮播图来切换的交互。
