### ISSUE TITLE
v0.1发布前的任务

### ISSUE THREAD

**Issue by airyland** [airyland/vux#104]
+ [x] 统一所有事件为`on-*`
+ [x] 统一所有支持object的表单列表数据格式为 `{key: 'key', value: 'value'}`
    + [x] Radio
    + [x] Checklist
    + [x] Selector
+ [x] 重构完`calendar`
    + [x] Inline-calendar
    + [x] Calendar = Popup + Inline-calendar
+ [ ] x-form
+ [ ] class namespace `vux-`
+ [ ] 检查完所有文档
+ [x] 所有构建的文件放到 `dist`目录

**Comment by doasp** [comment]
good job

**Comment by terranc** [comment]
想问1.0的预计时间大概什么时候？

**Comment by xiaolongyuan** [comment]
+1

**Comment by xiaolongyuan** [comment]
看起来还有很多事 61能完成么

**Comment by airyland** [comment]
@xiaolongyuan :sweat_smile:  其实就是文档花时间。。

**Comment by xiaolongyuan** [comment]
哈哈 是的 目前用都是对着源码用的

**Comment by xiaolongyuan** [comment]
今天能发布？
