### ISSUE TITLE
swipeout-button 点击事件无效.  官方demo里可以重现(chrome-56.0.2924.87 (64-bit))

### ISSUE THREAD

**Issue by tangtaoit** [airyland/vux#1044]
swipeout-button 点击事件无效.  官方demo里可以重现(chrome-56.0.2924.87 (64-bit))

补充:
chrome需要在DEBUG里开启手机调试模式
而且在android手机上问题照样存在
![cc46dbfe-611e-43da-80c0-961167bc6f62](https://cloud.githubusercontent.com/assets/3895878/23647082/eba6b5d2-034e-11e7-9fc2-29703c3c22dc.png)

**Comment by airyland** [comment]
官方demo不能重现。检查是否是因为网页缓存导致的。

**Comment by tangtaoit** [comment]
chrome需要在DEBUG里开启手机调试模式
而且在android手机上问题照样存在

**Comment by airyland** [comment]
我这边 chrome 不开启手机模拟也是正常的。多刷新页面几次看看？

**Comment by tangtaoit** [comment]
不开启是正常的  开启是不正常的

**Comment by tangtaoit** [comment]
这样是正常的, 开启手机模式就点击无效. android手机（锤子手机）上一样点击无效 
![6a6f820a-087c-43cb-ba4a-ac6e5d8e8b27](https://cloud.githubusercontent.com/assets/3895878/23647197/80b15c4a-034f-11e7-81e6-eedefa0d36cf.png)

**Comment by airyland** [comment]
:sweat: 

不开启

![image](https://cloud.githubusercontent.com/assets/559179/23647215/9bc7c4d8-034f-11e7-8945-fee574850824.png)


开启

![image](https://cloud.githubusercontent.com/assets/559179/23647224/a5d773f6-034f-11e7-8f49-c4fa86a14977.png)

**Comment by tangtaoit** [comment]
靠 ..  那这是啥情况.  我这边试了几遍都是这样. 缓存都刷新了. 你chrome是啥版本的？

**Comment by tangtaoit** [comment]
Safari 和 火狐都没问题 但是我chrome跟 android手机上都存在这问题

**Comment by airyland** [comment]
Chrome 版本 56.0.2924.87

**Comment by tangtaoit** [comment]
chrome版本一模一样.  会不会父类事件覆盖掉了子类按钮的事件. 事件没有穿透到子类？主要是其他浏览器又都可以 搞不懂了。。

**Comment by airyland** [comment]
你是本地不行，demo也不行么？有另一同学发现没有引入fastclick时无法触发。

**Comment by tangtaoit** [comment]
demo跟本地都不行 已经引入了fastclick

**Comment by lmasdata** [comment]
@tangtaoit 发现点击事件在安卓手机上无效，请问找到办法解决了么

**Comment by airyland** [comment]
@tangtaoit  @lmasdata 下午发个小版本解决。

**Comment by DearVikki** [comment]
hhh找到了一个workaround...用touchstart事件替代还是可以触发的 /机智
