### ISSUE TITLE
如果把 range 嵌套在 scroller 里，scroller区域会被拖动影响

### ISSUE THREAD

**Issue by think2011** [airyland/vux#1045]
### Version
2.1.1-rc.6

### 重现
![222](https://cloud.githubusercontent.com/assets/3961388/23640115/7160950e-0326-11e7-846b-7e378b71014a.gif)

如果把 range 嵌套在 scroller 里，scroller区域会被拖动影响

**Comment by airyland** [comment]
不支持scroller里有其他手势操作组件。

**Comment by think2011** [comment]
@airyland 恩， 明白了
