### ISSUE TITLE
在main.js里引用了WechatPlugin ，但是在组件里引用wx.config的方法的时候，报wx is not definded,并签名成功了，这是怎么回事？

### ISSUE THREAD

**Issue by winglau14** [airyland/vux#1048]
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```

**Comment by airyland** [comment]
组件里当然不存在wx了。参考文档：

![image](https://cloud.githubusercontent.com/assets/559179/23647848/f7f3b282-0352-11e7-8297-60118312aef3.png)
