### ISSUE TITLE
使用datetime时引入的picker作用域问题

### ISSUE THREAD

**Issue by NeeTail** [airyland/vux#1050]
vux版本号：2.1.1-rc.6
vux-loader版本号：1.0.41

直接按照官网例子写datetime时，picker组件内的scroller.js、animate.js两个文件内使用const声明的变量在对外放出的函数内全部报未找到，在文件内却可以找到。使用let也是同样。只有将const改成var才能访问到。

```vue
<group :title="'test'">
    <datetime v-model="limitHourValue" :start-date="startDate" :end-date="endDate" format="YYYY-MM-DD HH:mm" @on-change="change" year-row="{value}年" month-row="{value}月" day-row="{value}日" hour-row="{value}时" minute-row="{value}分" :title="'test'"></datetime>
</group>
```

```js
import { Datetime, Group } from 'vux'
```

```js
data() {
  return {
     limitHourValue:'',
     ddd: '2015-11-12',
     startDate: '2017-03-07',
     endDate: '2017-03-20'
  }
}
```

![l e 9 47s573ermm _q8c](https://cloud.githubusercontent.com/assets/19653252/23650000/7afb3350-035b-11e7-9ab4-c19a060e179d.png)

**Comment by airyland** [comment]
无法重现，如果你按照demo来报错，而demo并没有报错。那应该是你使用上的问题。node版本呢？

**Comment by NeeTail** [comment]
发现问题了，是vux-loader忘记去写配置了。
但是我想问一下，为什么没有加入loader时作用域会这样，有些想不明白。

**Comment by airyland** [comment]
js 是要经过babel编译的。vux-loader中配置了这一步。
