### ISSUE TITLE
初次使用搭建vux的问题

### ISSUE THREAD

**Issue by maojindao55** [airyland/vux#1051]
npm 版本 3.10.3
node 版本 v6.3.0

按照文档安装－快速开始
vue init airyland/vux2 projectPath
cd projectPath
npm install --registry=https://registry.npm.taobao.org
安装构建成功

找到src/main.js文件
将
```
import Home from './components/HelloFromVux'
```
修改为
```
import Home from './components/Alert'
```
从官方demos文件下Alert.vue 拷贝到 我项目的 components/ 文件目录下

执行npm run dev 打开网页报错

`TypeError: _vm.$t is not a function`

**Comment by airyland** [comment]
那就把$t去掉。
