### ISSUE TITLE
vux.li中的预览,在苹果手机上的safari下不显示

### ISSUE THREAD

**Issue by tiger8888** [airyland/vux#1054]
vux.li中的预览,在苹果手机上的safari下不显示

**Comment by airyland** [comment]
你上一个issue说的是自己本地不显示，这条issue说的是vux.li的demo，那么到底是你本地有问题还是线上有问题？

**Comment by airyland** [comment]
写代码的就不要用“不显示”这一类模糊没有任何作用的词了。

**Comment by tiger8888** [comment]
都不显示啊,我是菜鸟,请见谅

**Comment by tiger8888** [comment]
你用苹果手机试试不就知道了......

**Comment by airyland** [comment]
维护这个项目这么久，我当然试过在我手机上没有任何问题。况且你也并没有说明你哪个型号。

**Comment by tiger8888** [comment]
手机1: iOS版本9.0.2
手机2:iOS版本10.2.1
也应该不是网络的问题,我用公司wifi,和4G都不显示

**Comment by airyland** [comment]
还是上面的问题，不显示表现为什么，是白屏还是有报错还是显示其他问题。如果你本地是白屏，在代码里加上 onerror alert 下报错看看。

**Comment by tiger8888** [comment]
![15aa12aa-d49d-45a8-b9cc-4b0f9c078aaa](https://cloud.githubusercontent.com/assets/1930815/23693474/9c2b010e-040f-11e7-9f8a-ca07abf11006.png)

**Comment by tiger8888** [comment]
![e00d3cb9-7a18-42c5-a4cb-673a0ee30bac](https://cloud.githubusercontent.com/assets/1930815/23693591/2112f318-0410-11e7-8bd7-124b84dce928.png)

**Comment by airyland** [comment]
你是不是用隐身窗口了？

**Comment by tiger8888** [comment]
没有在 iPhone 上开启 “无痕浏览”

**Comment by tiger8888** [comment]
我的问题,手机上阻止cookie了,奇怪的是两个手机 上都 阻止了..... ,我晕.. 浪费你的时间 了....

**Comment by airyland** [comment]
😅
