### ISSUE TITLE
XInput组件绑定v-model类型为数组时出现BUG

### ISSUE THREAD

**Issue by didashine** [airyland/vux#1055]
源码Xinput组件代码197行 value: [String, Number] 少加Array导致绑定Array类型时会报下面错误
![740488604957399256](https://cloud.githubusercontent.com/assets/19238613/23693995/60d2bb44-0412-11e7-904e-f211dd87a3a7.jpg)

**Comment by airyland** [comment]
不支持绑定数组。用户输入字符串也转不回数组吧。
