### ISSUE TITLE
checklist 是否支持slot

### ISSUE THREAD

**Issue by jianchengwang** [airyland/vux#1056]
看demo右边面板只显示简单的文本信息，接受一个key,value的 options 数组，但是比如我要显示复杂的图文信息，比如购物车之类，有商品的图片，规格描述，价钱等，是否支持。

**Comment by airyland** [comment]
使用 `checker` 。checklist 的数据参数是数组而不是 checklist-item，无法在模板中为每个 item 增加 slot。
