### ISSUE TITLE
官网的demo样式出现问题，（datetime，calendar）

### ISSUE THREAD

**Issue by mehooo** [airyland/vux#1057]
![qq 20170308190524](https://cloud.githubusercontent.com/assets/26275004/23701586/4dea6dcc-0432-11e7-9997-03f6cec65fcc.png)
这是官网提供的demo，展示的样式，
![qq 20170308190719](https://cloud.githubusercontent.com/assets/26275004/23701656/95474ab4-0432-11e7-872c-6159b951f309.png)
我的本地通过airyland/vux2安装的 "vux": "^2.1.0-rc.28"版本，这个样式也有问题，因为font-sizewe为0，所以日期显示不出来，
还有能发提供一个rangedate，范围选择时间的，在手持上面放2个时间选择感觉很怪异。

**Comment by airyland** [comment]
错别字也太多了 😿

**Comment by airyland** [comment]
组件并没有使用到 .weui-cells_form 这个类名。检查是否你自己使用了这个类名。
