### ISSUE TITLE
Popup打包后无法弹出

### ISSUE THREAD

**Issue by erguotou520** [airyland/vux#1060]
http://www.xingshifu.com/travels/2017030519512900
这个是打包后的，点击"立即预定"或"出发日期"，应该可以弹出日历的popup，但是并没有.
![image](https://cloud.githubusercontent.com/assets/7945757/23711913/30c65f1a-045c-11e7-859d-9003fde0dbf1.png)

`v-model`绑定的值已经是true了，但是`popup`的`value`还没变

**Comment by airyland** [comment]
你是说开发时正常？

**Comment by erguotou520** [comment]
对，开发时没用问题

**Comment by airyland** [comment]
就这些信息我也无法重现问题。而且为什么页面还有大量的<style> 。

**Comment by erguotou520** [comment]
好像每个页面的css打包后都是这样的，难道我哪里弄错了？

**Comment by airyland** [comment]
一般都会抽取到一个css文件。

**Comment by erguotou520** [comment]
这个配置
```
// extract css into its own file
new ExtractTextPlugin(utils.assetsPath('css/[name].[contenthash].css'))
```
我也有，但是好像只对app有效，难道是我一直以来的构建姿势都不对？
我看了下demo也是一大堆style啊 😄

**Comment by erguotou520** [comment]
这个props失效可能是什么问题？

**Comment by erguotou520** [comment]
发现好几个地方都不行，只要是用到`v-model`的

**Comment by airyland** [comment]
你得自己检查了。我本地无法重现，没有思路。
demo的样式哪里有一堆style？

**Comment by erguotou520** [comment]
尴尬地发现是因为vue版本问题，之前使用的staticfile的cdn，vue的版本为2.1.6，就是这个导致的... 😅

**Comment by airyland** [comment]
😅  你可以睡个好觉了

**Comment by erguotou520** [comment]
![image](https://cloud.githubusercontent.com/assets/7945757/23714315/b21e0318-0463-11e7-9037-35de496a707a.png)

**Comment by erguotou520** [comment]
睡觉

**Comment by airyland** [comment]
你上面截图的应该是异步加载页面组件导致的。不同页面的样式没有抽取出来，改天再看看。

**Comment by erguotou520** [comment]
对啊，就是异步组件的css没有独立出来啊

**Comment by erguotou520** [comment]
如果弄好了 艾特我下
