### ISSUE TITLE
vux的$t未找到问题

### ISSUE THREAD

**Issue by NeeTail** [airyland/vux#1066]
vux版本号2.1.1-rc.7
vux-loader版本号1.0.46

我项目中未使用i18n，所以并没有$t未找到的问题。
但是在使用PopupPicker组件时会报$t未找到，vux源码中这个组件的index.vue使用了i18n。

![9hi i8j5gadmi d lt kv4](https://cloud.githubusercontent.com/assets/19653252/23737284/0fd4f458-04cd-11e7-8f73-0c7725149356.png)

我试图在vux-loader配置的plugins中添加i18n

```javascript
{
 name: 'i18n',
 vuxStaticReplace: true,
 vuxLocale: 'en'
}
```
这样会报path问题
![wg gs4 s y 745lwe x](https://cloud.githubusercontent.com/assets/19653252/23737267/e731d32c-04cc-11e7-82dd-a92b5c570bc6.png)

请问我该如何配置？像vux demo页面那样还需要特意写一套yml么？

**Comment by airyland** [comment]
![image](https://cloud.githubusercontent.com/assets/559179/23737354/80ece592-04cd-11e7-90e2-2189fb9b01fb.png)

**Comment by NeeTail** [comment]
![fo2kb tsxwv_qj](https://cloud.githubusercontent.com/assets/19653252/23737442/10971a46-04ce-11e7-82e8-5e16a6c2ddf9.png)
请问是这样配置么？我在官网上查阅了很久，你截图的那里我也看到了，但是我怎么试都报错....

**Comment by airyland** [comment]
你并没有使用i18n，问题是cnpm引起的。不需要在vux-loader里配置i18n。直接重装依赖。
