### ISSUE TITLE
微信内置浏览器返回无效

### ISSUE THREAD

**Issue by DWangHua** [airyland/vux#1070]
苹果IOS8 微信6.5.5 内置浏览器中使用vux开发webapp，window.location.href 跳转到https://mp.weixin.qq.com/类似地址，跳转成功，但是不能返回，一直刷新当前页

**Comment by airyland** [comment]
window.location.href 跟 VUX 嘛关系?!

**Comment by DWangHua** [comment]
是我错了，跳转地址那边有个hash导致要点两次才能回去
