### ISSUE TITLE
IOS中使用了过渡(转场动画)，在左划返回时动画会再重复，文档说是暂时无解，官方DEMO中却无此问题？求解

### ISSUE THREAD

**Issue by xheartx** [airyland/vux#1079]
### 官方 [DEMO](https://vux.li/demos/v2/?x-page=v2-doc-home#/)

![DEMO](http://7xvjap.com1.z0.glb.clouddn.com/QQ图片20170312214638.png)

> 但我自己使用却还是会有IOS下使用屏幕边缘滑动返回时，页面滑动效果会被触发两次的问题，使用的版本是
``` html
<!--package.json-->
 "dependencies": {
    "vue": "^2.1.10",
    "vuex": "^2.0.0",
    "vux": "^2.1.0",
    "vue-router": "^2.2.0",
    "vuex-router-sync": "^4.1.2",
    "fastclick": "^1.0.6",
    "vue-wechat-title": "^2.0.0"
  }
```

### 文档中的说明

![文档](http://7xvjap.com1.z0.glb.clouddn.com/QQ图片20170312215404.png)

**Comment by airyland** [comment]
依然会重复。你是进入哪个页面动画不会执行第二次？浏览器是哪个？

**Comment by xheartx** [comment]
不好意思没说清楚浏览器，我用的iphone6s微信内置浏览器，就是底部tab切换啊，刚才又研究了下，
确实在Safari上还是执行两次，但是在微信里如果把过渡时间设置为0.3s，就看不到第二次切换了
``` html
<!--package.json-->
 /**
* vue-router transition
*/
.router-view {
  width: 100%;
  animation-duration: 0.3s;
  animation-fill-mode: both;
  backface-visibility: hidden;
}
```

**Comment by airyland** [comment]
实测改了时间也是会执行两次的。

**Comment by wujunchuan** [comment]
为什么官方DEMO中没有这个问题呢?

**Comment by airyland** [comment]
@wujunchuan #2259

**Comment by PLQin** [comment]
#####  \# 我的问题是   
vue 在 ios safari，右滑返回首页时页面先变空白，接着展示上一个页面的内容，最后出现首页的内容  ；

另外 ： 并不仅仅是返回首页时才有这个问题， 其他页面也存在这个现象 


#####  \# 我是如何解决的   
放弃使用 vue transition ， emmm  太难了


#####  \# 参考       
- [iOS Safari renders blank page](https://github.com/vuejs/vue/issues/5533)
