### ISSUE TITLE
Scroller组件官方文档提供的是上拉刷新，是否能够实现infinite scroll load 的效果呢？

### ISSUE THREAD

**Issue by hinadong** [airyland/vux#1080]
### 移动端『翻页』加载效果

>一般来说，翻页加载主要有上拉加载或无限滚动加载二种效果，都是比较常见的做法，我看了下文档和代码，scroller组件好像是基于XScroll 这个JS库，不知道是否可以适当配置就可以实现无限滚动加载呢？

**Comment by airyland** [comment]
scroller 上不会再做更新。后面会有另外的组件来代替 scroller 组件，包含 recycle list 和 infinite load。
