### ISSUE TITLE
关于ios下PopupPicker的问题

### ISSUE THREAD

**Issue by sixiakun** [airyland/vux#1083]
### ios
popuppicker 点击出现里面的值会先显示最后一个值 再向下滚动到显示第一个值

**Comment by sixiakun** [comment]
描述有误 并不是滚动 而是刚开始下面的值没有加遮罩，已经加载出来了才加遮罩 看起来像是滚动了一样

**Comment by airyland** [comment]
是有这个体验问题，一直忘了处理 😅

**Comment by sixiakun** [comment]
处理问题是真速度，赞！
问题是我更新到 vux 2.1.1-rc.10,使用popupPicker报错，去掉这个引用就好了，应该不是个例。。
![image](https://cloud.githubusercontent.com/assets/20946763/23883125/0451ab40-08a0-11e7-9855-c6220f3188dc.png)

**Comment by sixiakun** [comment]
经测，vux 2.1.1-rc.5没有这个问题，从2.1.1-rc.6开始出现，问题是你昨晚改我提的遮罩bug时应该也开了应用吧 =，怎么没这个问题是我的依赖有误么 我的vue@2.2.4 vux-loader@1.0.54
![image](https://cloud.githubusercontent.com/assets/20946763/23883437/dead025c-08a1-11e7-8e29-06ea12804b9d.png)
![image](https://cloud.githubusercontent.com/assets/20946763/23883556/b27ee974-08a2-11e7-97ce-c3d7e186229d.png)

**Comment by sixiakun** [comment]
值得一提的是 退出引用的页面时，会报错
![image](https://cloud.githubusercontent.com/assets/20946763/23884129/e51f564a-08a5-11e7-8e19-e034504a6529.png)

**Comment by airyland** [comment]
建议你建个简单的 repo 给个链接或者打个包给我。怀疑是依赖的问题。

**Comment by sixiakun** [comment]
升级到 2.1.1-rc.11 问题没有了  给力！！

**Comment by 651471872** [comment]
"刚开始下面的值没有加遮罩，已经加载出来了才加遮罩",  你的demo上还是有这个问题的。
vux-version vux@2.4.0
ios微信

**Comment by airyland** [comment]
@651471872 微信内会出现， 直接 safari 打开倒是不会，这个尝试解决未果。
