### ISSUE TITLE
datetieme组件的开始时间和结束时间，是否应该具体到分或者秒？

### ISSUE THREAD

**Issue by greedying** [airyland/vux#1086]
现在遇到的问题是，我想设定datetime的可选时间，两个条件
1、精确到分钟 2、大于当前时间。
然后发现实现不了。

另外一个问题是，可否设置显示的时间和v-model里的时间不同？显示一个格式，实际传值是另外的格式。

谢谢

**Comment by airyland** [comment]
原本就不支持秒。也没有必要，实际没有这个要精确到秒的场景。
精确到分也就是精确到小时分钟，我也觉得没有必要。因为只有开始日期和结束会有所限制，其他都是24小时，60秒。想象一下用户在选择时，分钟已经过了刚才的那一分钟或者刚才的小时，那是不是还得动态重新渲染一下列表。如果支持秒，那画面就难以想象了。。

这个暂时不会做，但是欢迎 PR。

第二个问题，你是想和 popup-picker 一样支持 display-format吧，这个可以支持。

**Comment by justnowanna** [comment]
@airyland 有精确到秒的需求啊，选择到秒并不是实时选择当前的秒，比如这次双11，在某一个时间段出现了多笔订单，其中有几笔异常的，如果选择分钟，可能都会查出来上百笔订单了，这样的场景并不少，有时候就是需要根据订单创建时间去查询那一笔或者几笔订单的。我们现在是把PC端的系统做到手机端，而且打包成APP，之前的接口都是到秒的。。。

**Comment by airyland** [comment]
@justnowanna 没看明白，datetime format 本就支持到秒，`YYYY-MM-DD HH:mm:ss`。这个 issue 是指开始结束时间的限制，不是指组件不支持到秒。

**Comment by yoyo0926** [comment]
同求到分啊，不能如果有默认时间，就限制到时分吗，没有秒就算了，好歹也要到分嘛

**Comment by airyland** [comment]
@yoyo0926 可 pr。时分也仅对开始日期和时分和结束日期的时分有效，中间日期不也是24小时，60秒？
`如果有默认时间，就限制到时分吗` 没看明白你究竟是什么场景？
