### ISSUE TITLE
TabbarItem图标使用<i>标签，图标字体的时候图标位置下移

### ISSUE THREAD

**Issue by hezhongfeng** [airyland/vux#1087]
```
      <tabbar-item selected link="/main/home">
        <img slot="icon" src="../assets/logo.png">
        <span slot="label">Home</span>
      </tabbar-item>
      <tabbar-item link="/main/message">
        <i slot="icon" class="iconfont icon-home" style="font-size:27px;"></i>
        <span slot="label">Message</span>
      </tabbar-item>
```
使用<i>的时候图标的位置不对，如图，跟大小没有关系
![qq 20170314094654](https://cloud.githubusercontent.com/assets/12163050/23882386/37b73176-089b-11e7-9245-c81b594bcef0.png)
![qq 20170314094844](https://cloud.githubusercontent.com/assets/12163050/23882415/7222e544-089b-11e7-8b38-65b88dd8b9ee.png)

**Comment by airyland** [comment]
使用 iconfont 的情况需要自行调整位置。比如使用 position: relative, top: -*px

**Comment by hezhongfeng** [comment]
get
谢谢
