### ISSUE TITLE
Search 在body高度大于屏幕高度的页面里，会有一条黑线~

### ISSUE THREAD

**Issue by mukaiu** [airyland/vux#109]
### Version
0.0.105
### Android or iOS, which browser?
All
### Your Codes 

``` html
<div>
    <Search cancel-text="取消" @change="getResult" :results="results" :value.sync="value">
        <Search>
</div>
```

### Steps to reproduce the problem
![image](https://cloud.githubusercontent.com/assets/7746790/14523916/7a3a742a-0268-11e6-9afe-d6bc96ca6ee7.png)

.weui_search_bar:after{bottom:0;border-bottom:1px solid #c7c7c7;
此条样式导致~

**Comment by airyland** [comment]
这是在focus的情况下出现的吗？search主体没看到

**Comment by mukaiu** [comment]
![image](https://cloud.githubusercontent.com/assets/7746790/14580118/0b000cac-03f6-11e6-9b1f-82f54547bb34.png)

demo 里添加一个高度比较大的div就会出现~

**Comment by airyland** [comment]
目测是weui 0.4.0存在的问题，目前vux更新到weui@0.4.1已经修复这个问题，明天发布的0.0.106就是正常的了

https://github.com/weui/weui/commit/169e18a

**Comment by mukaiu** [comment]
呵呵，还没有发布

**Comment by airyland** [comment]
呵呵，你行你来开发

**Comment by mukaiu** [comment]
这么好的东东必须回馈代码~
