### ISSUE TITLE
VUX 开发者调查及意见汇总

### ISSUE THREAD

**Issue by airyland** [airyland/vux#1090]
VUX 已经开源了一年，发个问卷做个简单的一些调查，遇到的问题、意见、建议、吐槽都可以填，感谢大家。

https://wj.qq.com/s/1170299/9518/

## 需要一个社区

- [ ] 计划中， **有意向当管理员的请踊跃举爪**

## 官方文档不够细致
- [ ] 尽快改进

## 文档说明和 demo 不在同一页面，要跳转
- [ ] 尽快改进

##  picker 底层实现比较冗余
后面有时间改进

## 浅封装插件有性能问题
这个不大明白，欢迎发 PR。

## 长列表优化方案
- [ ] 计划实现中

## 组件：drawer
- [ ]  计划实现中

##  自定义性有点弱
不大明白，欢迎补充说明

## vux-loader 是个门槛

如果只是调用一个 merge 方法都是门槛，那么 `webpack` 更是一个门槛了。
如果没有 vux-loader 按需使用，主题也无法使用了，到时又抱怨不能定制，按需使用门槛高了。
况且有模板可以直接使用，何来门槛？

## 组件不够丰富

现在已经基本满足要求了，太业务性的组件不会做。

## 给了3分还选会给朋友推荐是啥心态

感觉这是把朋友推进坑

## 十分担心会不维护

要么捐赠，要么贡献，任何支持都没就别瞎担心了。

**Comment by shijunti19** [comment]
不错，我觉得单独开个社区吧，把这个项目搞的又全又大，我都不想安装其他组件进去了！全部都用你的

**Comment by lichunqiang** [comment]
不必很键盘侠计较。不忘初心就好 keep fighting

**Comment by brandonxiang** [comment]
我在想 为啥 不做成一个plugin，`vue.use(vux)`，把所有的组件加进去呢？

**Comment by airyland** [comment]
@brandonxiang 你考虑过你手机的感受嘛，况且组件也在增加。如果是 PC 组件倒是无所谓。

**Comment by brandonxiang** [comment]
@airyland 饿了么的[Mint-UI](https://github.com/ElemeFE/mint-ui/blob/master/src/index.js)就是这么做的，它也是移动端，这样效率真的会变低吗？

**Comment by airyland** [comment]
@brandonxiang 这个问题真没有问的必要，你觉得按需使用加载 20k js+2k css 的组件代码和直接加载 600k js+80k css 会没有差别么，无论是加载速度和性能影响？随着组件迭代和增加，你可能要在移动端加载 1M 以上的 VUX 代码了，更何况还要加上 vue vue-router vuex axios 等代码库，gzip 和 cdn 作用变得十分有限了。

另外它本身也是支持按需加载的。

**Comment by chenxinglin94** [comment]
大哥好，我正在学习vux，关于样式覆盖这方面遇到一些问题。
我想修改.weui-grid这个类属性 padding: 10px 0px;在每个组件里在通过scoped可以修改成功。
但是我如果在app.vue文件里进行统一样式覆盖掉，但是发现做不到，浪费大哥几分钟的时间帮忙解答一下我的疑惑。谢谢

**Comment by xiaolongyuan** [comment]
为什么用的全是 px 做单位呢？

**Comment by vFire** [comment]
这个应该是weui的锅 我也觉得用像素不太好 但一般应用也没问题
