### ISSUE TITLE
rm不是内部命令，也不是可执行程序，怎么破？

### ISSUE THREAD

**Issue by docikaci** [airyland/vux#1091]
windows7   64位
运行yarn run build  或者npm run build 
都是报错， 谢谢
![image](https://cloud.githubusercontent.com/assets/7788102/23939603/7718b7d4-099c-11e7-919f-cc9e2fa52b3b.png)

**Comment by airyland** [comment]
在 windows 上使用 git bash。

**Comment by docikaci** [comment]
npm run build
报这个错呢？  能看出来哪儿的问题吗？
非常感谢
![image](https://cloud.githubusercontent.com/assets/7788102/23940925/b268ee08-09a1-11e7-8bd4-94c52d6e2aad.png)

**Comment by airyland** [comment]
docs  下没有相应的 demos/v2 和 demos/temp 目录。因为我没在 windows 上开发，因此不报错。大概是 windows 上不存在就报错。你可以手动先建立相应目录。

**Comment by huan51025** [comment]
我也出现了同样的问题

**Comment by huan51025** [comment]
我也出现了同样的问题，建立目录后还是不行

**Comment by CHINAPANDAGZX** [comment]
> npm run build 报这个错呢？ 能看出来哪儿的问题吗？ 非常感谢 ![image](https://cloud.githubusercontent.com/assets/7788102/23940925/b268ee08-09a1-11e7-8bd4-94c52d6e2aad.png)

大佬牛逼啊，感谢你解决了我的问题，找了很多地方都没有找到这个问题，谢谢

**Comment by CHINAPANDAGZX** [comment]
> 在 windows 上使用 git bash。

大佬牛逼啊，感谢你解决了我的问题，找了很多地方都没有找到这个问题，谢谢

**Comment by ExecuteMyExecution** [comment]
> 在 windows 上使用 git bash。

膜拜大佬

**Comment by chenoh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
