### ISSUE TITLE
datetime 不能选2000年之前的年份？

### ISSUE THREAD

**Issue by transtone** [airyland/vux#1092]
直接扫 demo 示例，点击进入 datetime，所有年份最近是 2000 年。这是遇到了千年虫问题？

**Comment by airyland** [comment]
不是，只是没有设置 min-year，默认就是2000年开始。

**Comment by transtone** [comment]
设置了 min-year 无效，所以发此 issue，我再测一下。

不好意思，没有仔细看文档。
