### ISSUE TITLE
建议将swiper里面swiper-item在每次切换后不可见的item都display：none！

### ISSUE THREAD

**Issue by linsywu** [airyland/vux#1093]
建议swiper中swiper-item在每一次切换后不可见的display:none掉。这样子item的布局就可以不使用position:ablsolute，也就不会出现一定要指定高度的问题。现在的问题就是在里面内容不确定的情况下，swiper-item无法根据内容自动撑开，在很多配合tab使用的情况下不合理。
可以参考bootstrap里面标签页的实现情况。
![image](https://cloud.githubusercontent.com/assets/15061856/23978494/456b6388-0a2f-11e7-8794-a941e4ca8471.png)

**Comment by airyland** [comment]
swiper 本质上不是为这种不定高的场景设计的。暂时不支持，但是欢迎 pr。
