### ISSUE TITLE
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead

### ISSUE THREAD

**Issue by shijunti19** [airyland/vux#1094]
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead

PulldownPullup.vue提示的
好像废弃了要修改吧

**Comment by airyland** [comment]
应该是 spinner 的关系，不过在我的浏览器里没有提示。非 bug 后面有空再更新。
