### ISSUE TITLE
x-dialog嵌套scroller

### ISSUE THREAD

**Issue by q757571446** [airyland/vux#1096]
您好，请问x-dialog嵌套scroller的情况，中间内容不能滚动，该怎么处理。x-dialog里面部分内容是个列表

**Comment by airyland** [comment]
内部禁用scroll的情况只会在设置 scroll = false 时出现。

然后它只是个 dialog 啊，没有必要上 scroller，一个 div overflow: scroll 再加上 Safari 的 overflow-scrolling: touch 就解决滚动问题了。
