### ISSUE TITLE
Datetime组件能否设置分钟取值精确度

### ISSUE THREAD

**Issue by F-loat** [airyland/vux#1099]
目前有一个应用场景，相当于是需要用户设置收货时间之类的，要求精确到每刻钟，即分钟一栏只显示0，15，30，45这四个值，请问有什么办法可以实现吗？或者是否可以添加这个功能？

**Comment by airyland** [comment]
使用 popup-picker 可破。可以参照 datetime-range 源码，把分钟改成你需要的刻度值。

**Comment by F-loat** [comment]
Thanks
