### ISSUE TITLE
地址数据有误

### ISSUE THREAD

**Issue by sinceow** [airyland/vux#1101]
[最新县及县以上行政区划代码](http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201608/t20160809_1386477.html)

![image](https://cloud.githubusercontent.com/assets/4105018/24027841/63f0d802-0b05-11e7-9992-c63dc362dfb6.png)

460101 是 `市辖区`， `china_address_v1.json` 和 `china_address.json` 里都没有这个地址

---

![image](https://cloud.githubusercontent.com/assets/4105018/24027892/bfe9cd3a-0b05-11e7-8fef-5618c19dd53a.png)

```json
{
    "name": "北京市市辖区",
    "value": "110100",
    "parent": "110000"
}
```
正确的是`北京市-市辖区` 而不是 `北京市-北京市市辖区`

**Comment by airyland** [comment]
北京市-北京市市辖区这个可以改。

但是如果把市里的市辖区放出来，那么会有很多城市都会有多出市辖区，但是我看了下各大电商网站的地址管理，都并没有市辖区这个项。

**Comment by sinceow** [comment]
[最新县及县以上行政区划代码（截止2016年7月31日）](http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201703/t20170310_1471429.html) 这个是最新的地地址库。

还有一个问题， 那就是如`广东省-中山市`这种没有第三级区域的地地址在 value2name 会报错。我觉得应该在 value2name 自动为 x-address 中的空值自动赋 `--`

**Comment by airyland** [comment]
这个我记得貌似之前有处理过的样子。

**Comment by Hfengxiang** [comment]
请问我需要替换你们的china_address.json数据需要遵守哪些规则?后台已帮我按照你们的格式,即每个地址节点都包含"name","value","parent"3个字段,将所有数据写在了一个json数组中,但是替换之后不能用,请问我还需要遵守哪些别的替换规则?附带传上替换后的json数据
