### ISSUE TITLE
X-input type="passwrod"失效

### ISSUE THREAD

**Issue by silverWolf818** [airyland/vux#1104]
代码如下：`<x-input v-model="password" title="密码" type="password" name="password" placeholder="请输入密码"></x-input>`
vux版本2.1.0

**Comment by airyland** [comment]
显示明文？

**Comment by silverWolf818** [comment]
是的显示明文

**Comment by silverWolf818** [comment]
我需要升级版本吗？

**Comment by lichunqiang** [comment]
咋不按issue template 来， 报下vux版本，这个之前解决了

**Comment by airyland** [comment]
你的版本得灰常老，低于 2.1.0，更新下吧。
