### ISSUE TITLE
XHeader组件引入引发Vue JS错误，不能正常解析XHeader

### ISSUE THREAD

**Issue by alosin** [airyland/vux#1105]
Chrome（版本：55.0.2883.87）调试错误如下：
Property or method "$t" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <XHeader> at D:\AlosinWork\WebStormWorkSpace\PhoneGame\node_modules\vux\src\components\x-header\index.vue)

**Comment by airyland** [comment]
又是这个问题。先用 npm 重装依赖吧。

**Comment by alosin** [comment]
全部重装?

**Comment by alosin** [comment]
npm 重装依赖,重装Vux还是一样错误

**Comment by airyland** [comment]
我就想问你你是不是没配置 vux-loader。。

**Comment by alosin** [comment]
vux-loader肯定有装啊，其它vux组件都正常使用的。
代码：
<style>
</style>
<template>
    <div>
        <x-header>用户登陆</x-header>
    </div>
</template>
<script>
    import {XHeader} from 'vux'
    export default {
        components: {XHeader},
    }
</script>
这是最简单的代码了

**Comment by airyland** [comment]
打个包给我研究

**Comment by alosin** [comment]
import Register from './views/register/register.vue'
new Vue({
    store,
    el: '#app',
    components: {Register},
    router: router,
});
index.html
<div id="app" style="height: 100%;">
    <register></register>
</div>

register.vue里面就一个XHeader组件，这样应该可以重现错误了

**Comment by Sapphire2k** [comment]
安装 yaml-loader 以正确进行语言文件读取

`npm install yaml-loader --save-dev`

这个装了吗？
我是单独引入的 所以每次都是报 `$t`
然后我就每次都直接删掉😄

**Comment by alosin** [comment]
装了的，所以是语言文件那里出错，不知道为什么

**Comment by airyland** [comment]
看代码当然是没有任何问题的。不打个包看一下可能找不到问题了。我即使直接从模板初始化也不会报这个错误。

**Comment by kaneruan** [comment]
昨天还能运行，今天重装了node_modules，出现一样的错误 $t is not defined
vscode
npm@3.10.10

**Comment by airyland** [comment]
@githubmann 按照你的描述，vux 并没有更新，应该就是依赖问题了。参照文档说明。
奇怪的是我本地从来不会出现问题。使用 yarn 试试。
