### ISSUE TITLE
scroller在列表滚动过程中容易点到a标签的链接进行页面跳转

### ISSUE THREAD

**Issue by micheal-death** [airyland/vux#1106]
### Version
2.1.1-rc.11
### Android or iOS
iOS
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<scroller height="-96" lock-x scrollbar-y ref="scroller">
    <router-link :to="{name: 'NewsDetail', params: {id: item.id}}"
                 v-for="item in newsList"></router-link>
</scroller>
```

### Expected behavior and actual behavior.
一个类似新闻列表的长列表，列表项都是带链接的，在快速滚动的过程中因为列表项是可以点击的，所以经常出现滚着滚着就点到链接进行页面切换了。所以能否给scroller加一个配置选项让scroller在滚动的过程中使滚动的内容不可点击，在滚动的动画结束后才能点击。

**Comment by micheal-death** [comment]
研究了一下这个问题应该是fastclick造成的，[FastClick#42](https://github.com/ftlabs/fastclick/issues/42)。暂时没有研究出好的解决方案，这里有一个折中的方法是在scroller容器的子元素中的touchstart事件触发时给子元素添加needsclick类来阻止使用fastclick进行链接跳转，但是移除了fastclick也意味着在scroller中点击链接会存在300ms的延迟，[FastClick#119](https://github.com/ftlabs/fastclick/issues/119)。或者监听scroller的scroll事件，对于scroller的content设置point-event: none，这样会比较吃性能。

**Comment by airyland** [comment]
由于 scroller 无法满足灵活复杂的需求决定不再维护，该 issue 关闭了。
