### ISSUE TITLE
inline manifest的使用，希望能更加详细说明

### ISSUE THREAD

**Issue by cheneyweb** [airyland/vux#1111]
### Version

> 
> npm版本号：4.1.2
> node版本号：7.7.2
> vux版本号：2.x
> vux-loader版本号：^1.0.56
> 

### Android or iOS

> Android,IOS,浏览器

> **疑问是关于inline manifest的使用，虽然文档上给了说明，但是有一点的疑问，文档上说明需要在“vux-loader配置中加入inline-manifest插件”，是需要在以下这部分代码中添加吗？**

```
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui', 'progress-bar', 'duplicate-style']
})
```

> **文档上说明加入插件**

```
{
  name: 'inline-manifest'
}
```

### Your Codes 

> 我是这样加入（如下所示），正确吗？

```
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui', 'progress-bar', 'duplicate-style', 'inline-manifest']
})
```

> 或者是应该如下：

```
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui', 'progress-bar', 'duplicate-style']
},{name: 'inline-manifest'})
```

> 我的理解应该是前者，但是不知道为什么文档上写的是

```
{
  name: 'inline-manifest'
}
```

> 另外文档上说明第一步是需要在`</body>`前添加：

`<%=htmlWebpackPlugin.files.webpackManifest%>`

> 我是这样添加的：直接在index.html中添加：

```
<body>
    <div id="app-box"></div>
    <!-- built files will be auto injected -->

    <%=htmlWebpackPlugin.files.webpackManifest%>
</body>
```

因为对vux-loader还是不是很了解，可能是我理解错了：）希望能得到解惑

**Comment by airyland** [comment]
你前面的理解是对的，写法作用是一样的，只是提供了快捷方式，文档没有更新。

```
[{
  name: 'vux-ui'
},{
  name: 'inline-manifest'
}]
```

等同于

`['vux-ui', 'inline-manifest']`
