### ISSUE TITLE
scroller组件height问题

### ISSUE THREAD

**Issue by sixiakun** [airyland/vux#1112]
需求

### Version

 目前scroller组件只支持传入写死的height，:height无法支持，目前项目在pc开发时是有头部的，而在容器中是没有头部的，这就导致height不能写死，需要动态计算后传入，考虑组件的易用性，这个动态传入比较好些应该=_=

**Comment by airyland** [comment]
height 是支持动态设置的。

**Comment by sixiakun** [comment]
感觉上也应该是支持的，毕竟默认该是支持的。。
只是每次动态传入都导致 scroller的高度为0..

**Comment by airyland** [comment]
上个最简单能重现的 demo 代码。

**Comment by sixiakun** [comment]
![image](https://cloud.githubusercontent.com/assets/20946763/24088028/a6777034-0d60-11e7-8112-d81c16fd474c.png)
![image](https://cloud.githubusercontent.com/assets/20946763/24088034/aca2650e-0d60-11e7-9979-308c7e59794e.png)
不用改变值，你试试这样行不 我这里这样写 ，出来的scroller的高度就是0，当然你写过了记得刷新下，不然可能不会重载

**Comment by airyland** [comment]
额，貌似这个属性接受的是 string 而不是数字。

**Comment by sixiakun** [comment]
脸红。。我刚看到提示，不好意思，浪费你的时间了。。

**Comment by airyland** [comment]
你先试下正不正常，文档可能后面的 -40 有误导性。

**Comment by sixiakun** [comment]
no problem! very powerful!!
