### ISSUE TITLE
升级问题

### ISSUE THREAD

**Issue by 1025623017** [airyland/vux#1116]
### Version
npm 4.2.0
node 6.9.5

### 升级问题

![qq 20170320175138](https://cloud.githubusercontent.com/assets/13571820/24094958/ecd2aeec-0d95-11e7-8504-cec3e9ecd49d.jpg)
![qq 20170320175148](https://cloud.githubusercontent.com/assets/13571820/24094965/f5c279e2-0d95-11e7-9b5e-b455902c0e97.jpg)

在使用npm install vux --save更新之后，npm run dev将会报出这样的错误，如何解决？

**Comment by 1025623017** [comment]
![image](https://cloud.githubusercontent.com/assets/13571820/24095135/9c498120-0d96-11e7-87ef-4e882526aad2.png)
当我把页面路由全部注释掉之后，npm run dev将正常运行。

**Comment by airyland** [comment]
vux-loader 安装配置没

**Comment by airyland** [comment]
为什么不看文档？

https://vux.li/#/zh-CN/upgrade-to-2
