### ISSUE TITLE
Actionsheet菜单栏在UC浏览器和QQ浏览器上缺少分割线

### ISSUE THREAD

**Issue by Richar-Dada** [airyland/vux#1122]
### Version
"vux": "^2.1.1-rc.11"
### Android or iOS
Android
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```

### Steps to reproduce the problem
正常引用actionsheet,在一些浏览器,Actionsheet菜单栏的菜单项之间的分隔没没有了

**Comment by airyland** [comment]
issue 没有按照 template 来。这类“一些浏览器”对解决问题没有任何帮助，还浪费时间。
特意拿了个小米开 UC 和 QQ 没有任何问题。建议用有问题的机子排查一下发 PR 解决。该 issue 关闭了。
