### ISSUE TITLE
Dialog 异步请求成功才关闭

### ISSUE THREAD

**Issue by zlab** [airyland/vux#1124]
# 能不能原生支持这个特性呢
![v2-621236135023f068df913aa55fa2ac24_b](https://cloud.githubusercontent.com/assets/2288630/24178574/e798f490-0ee4-11e7-90ff-19a95989220e.png)

**Comment by airyland** [comment]
XDialog v-model 绑定的是否显示的变量是由你自己控制的，不存在不支持手动关闭的问题。

**Comment by zlab** [comment]
@airyland 标题写错了，不是Xdialog，是confirm组件

**Comment by zlab** [comment]
![_20170322101628](https://cloud.githubusercontent.com/assets/2288630/24179207/a41e862c-0ee8-11e7-802a-815d1da8efb6.png)

**Comment by wg5945** [comment]
这种复杂类型的还是自己用x-dialog画个吧

其实你看下confirm的源码就知道怎么做了，很简单的
