### ISSUE TITLE
表单验证如何使用？

### ISSUE THREAD

**Issue by felixjing** [airyland/vux#1126]
点击提交按钮后验证并弹出错误消息
看到<x-input>组件里都有写，但是小白不知如何调用。

**Comment by airyland** [comment]
表单组件暂时没有统一的验证方式，这个还在研究中。需要自己判断绑定的表单值在提交时进行验证。

**Comment by dmlzj** [comment]
@airyland
[一个验证插件](https://github.com/yiminghe/async-validator) 是不是可以考虑把这个集成进去啊

**Comment by FlappyHeart** [comment]
恐怕要先去掉内置的验证器了。楼上说的验证插件很好用，element就是用的这个，上手不难，功能强大。

**Comment by ly303550688** [comment]
都快3.0了还是没有想好怎么验证吗？
