### ISSUE TITLE
新版本 webpack 的配置，直接引入第三方库会报错

### ISSUE THREAD

**Issue by yhZhouYh** [airyland/vux#1127]
会报 诸如 此类错误TypeError: __WEBPACK_IMPORTED_MODULE_1__assets_lib_alloy_touch__.default is not a constructor
    at VueComponent.eval (eval at <anonymous> (app.js:1083), <anonymous>:65:27)
    at Array.eval (eval at <anonymous> (app.js:765), <anonymous>:506:20)
    at nextTickHandler (eval at <anonymous> (app.js:765), <anonymous>:455:16)

但是 运行时 指定window对象不会报错
 _this.touch = new window.AlloyTouch(options)

引入方式：import AlloyTouch from '../../../assets/lib/alloy_touch'

**Comment by airyland** [comment]
这显然不是 VUX 的问题了，alloy touch 不是一个标准的模块吧。

**Comment by yhZhouYh** [comment]
if (typeof module !== 'undefined' && typeof exports === 'object') {
        module.exports = AlloyTouch;
    } else {
        window.AlloyTouch = AlloyTouch;
    }  这是 库 最后封装的。。 没看出什么问题， 之前引也没有问题， 使用 vux 脚手架 生成的 不知道 是不是babel 哪里配置的问题

**Comment by airyland** [comment]
把这些全删了换成 export default AlloyTouch 试试

**Comment by yhZhouYh** [comment]
Module build failed: SyntaxError: I:/project/realreal/src/assets/lib/alloy_touch.js: 'import' and 'export' may only appear at the top level (341:4)

**Comment by yhZhouYh** [comment]
babellrc 中配置： 这样写可以正常运行
["env", {
      "es2015": { "modules": false }
    }],
直接down下来 是这样的：
["env", { "modules": false }],
