### ISSUE TITLE
vux的组件演示demo，页面切换的转场的效果是怎么做的？可以给一个实现思路吗？

### ISSUE THREAD

**Issue by Desever** [airyland/vux#1128]
vux的组件演示demo，页面切换的转场的效果是怎么做的？可以给一个实现思路吗？

**Comment by airyland** [comment]
https://github.com/airyland/vux/blob/v2/src/App.vue

**Comment by Desever** [comment]
你们的dmo源码我看了一遍了，但不是很熟悉vux，所以，还望指点一下

**Comment by wg5945** [comment]
可以先去看看vue过渡效果那段，再过来看demo源码

[http://cn.vuejs.org/v2/guide/transitions.html](url)

**Comment by airyland** [comment]
就是 vue 的 transition，路由变化前判断是前进还是后退，设置不同的 transition name 就行了。

**Comment by Desever** [comment]
我看你们貌似用了vuex来管理路由状态，所以这里没有理解清楚

**Comment by airyland** [comment]
vue-router 文档也有例子看那个吧。https://router.vuejs.org/zh-cn/advanced/transitions.html

**Comment by Desever** [comment]
好的，我进去看看，多谢您了
