### ISSUE TITLE
组件scroller的问题

### ISSUE THREAD

**Issue by sixiakun** [airyland/vux#1130]
文档上好像没讲太细，就是我使用pullup时，需要怎么设置才能使用户不用一定拉到最底部才能刷新，设置了height和pullupheight及autorefresh,都没找到合适的，只好来打扰作者大大了。。

**Comment by airyland** [comment]
你指的是距离一定距离自动加载吧，这个特性并未支持。

**Comment by sixiakun** [comment]
就是这个意思，未支持就不试了，先这样好了那
