### ISSUE TITLE
新版本 webpack 的配置报错

### ISSUE THREAD

**Issue by lmasdata** [airyland/vux#1134]
![image](https://cloud.githubusercontent.com/assets/8501594/24277706/eb8663d0-1079-11e7-8658-86e7e28d0b14.png)

**Comment by airyland** [comment]
缺少重现步骤。

**Comment by airyland** [comment]
https://github.com/vuejs-templates/webpack/issues/619
https://github.com/vuejs-templates/webpack/issues/617
依赖的问题。建议降级 vue-loader 或者 升级 vue-loader。
