### ISSUE TITLE
swipeout bugs

### ISSUE THREAD

**Issue by wg5945** [airyland/vux#1139]
### Version
2.1.1-rc.13
### Android or iOS
all

1、没有left-menu时，来回多次滑动中间部分，左侧会滑出空白
![image](https://cloud.githubusercontent.com/assets/5310295/24283808/d19ba0ba-10a2-11e7-8f13-7ca1c391b0d2.png)

2、因为有个背景图片，设计图要求swipeout-content的背景色为透明
设置`@swipeout-content-bg-color: transparent;`
在follow模式下，按住中间部分向上，再往左滑动，right-menu会展示出来，但中间部分并没有滚动，如下图所示
![image](https://cloud.githubusercontent.com/assets/5310295/24283949/9629196c-10a3-11e7-9960-d7470c84940f.png)

原demo是因为swipeout-content-bg-color为白色，覆盖了right-menu，所以看不出来问题

待会提个pr

**Comment by lichunqiang** [comment]
Closed via 77a6e22cc31a0bafe61d947d1ff5d93d24cdc7e1
