### ISSUE TITLE
vux 多个组件如何 组合，我是一个个vue文件分开的，如果写到一个vue文件，很难维护

### ISSUE THREAD

**Issue by zhidd** [airyland/vux#1145]
组件下面有有我写好的1.vue,2.vue,怎么把他们合并在一个，如果每个vue都写上自己需要的组件，岂不是重复了吗

**Comment by airyland** [comment]
看不明白你在说什么。

**Comment by airyland** [comment]
在 webpack 的打包机制下，同样路径的组件并不会重复打包。你实在有强迫症就把要用到的组件都先在 main.js 里注册。

**Comment by zhidd** [comment]
官网有很多component，我随便找3个component，分别在component文件下下面写了1.vue   2,vue  3.vue, 我怎么灵活地把他们组合在一起使用，我现在是在1个index.vue文件把1和2的内容都写在一起，然后在路由引入index.vue,这样工程很大，给点建议
