### ISSUE TITLE
官网有很多component，我随便找3个component，分别在component文件下下面写了1.vue 2,vue 3.vue, 我怎么灵活地把他们组合在一起使用，我现在是在1个index.vue文件把1和2的内容都写在一起，然后在路由引入index.vue,这样工程很大，给点建议

### ISSUE THREAD

**Issue by zhidd** [airyland/vux#1146]
官网有很多component，我随便找3个component，分别在component文件下下面写了1.vue 2,vue 3.vue, 我怎么灵活地把他们组合在一起使用，我现在是在1个index.vue文件把1和2的内容都写在一起，然后在路由引入index.vue,这样工程很大，给点建议

**Comment by airyland** [comment]
sorry，一看不懂，二这也不是 VUX 的问题。建议到 VUE 相关论坛提问。
