### ISSUE TITLE
2.1.1-rc.14 源码内没有x-icon的组件

### ISSUE THREAD

**Issue by colmugx** [airyland/vux#1149]
![image](https://cloud.githubusercontent.com/assets/21327913/24338666/be24471a-12d9-11e7-9552-87893c37fddb.png)

截图在这。

`To install it, you can run: npm install --save vux/undefined`

**Comment by airyland** [comment]
目录并不存在这个组件。这个组件会在调用时被 vux-loader 转换成 svg 代码。如果出错就是你没按照文档来。
