### ISSUE TITLE
search 属性设置bug

### ISSUE THREAD

**Issue by qinxg** [airyland/vux#1153]
### Version
2.1.1-RC.12
### Android or iOS
WEB
> For Android issues, please specify the brand, model and browser

### Your Codes 
官方示例
``` html
  <search @result-click="resultClick"
    @on-change="getResult" :results="results" v-model="value"
    position="absolute" auto-scroll-to-top top="46px" @on-focus="onFocus" @on-cancel="onCancel"></search>
```

### Expected behavior and actual behavior.

此处如果不设置:placeholder 与:cancel-text 会出错。
根据console提示，发现是$t的问题。查看了组件代码发现如下调用：

```html
 <span>{{placeholder || $t('placeholder')}}</span>

{{cancelText || $t('cancel_text')}}

```
### Steps to reproduce the problem

不设置:placeholder 与:cancel-text 会出错

**Comment by airyland** [comment]
出错时提问答务必带上出错信息。如果提示 $t 不存在，文档里已经写了解决方法了。
