### ISSUE TITLE
<Tab> custom-bar-width 属性不起任何作用

### ISSUE THREAD

**Issue by zColdWater** [airyland/vux#1154]
官方demo直接搬下来代码，引入Tab相关组件，更改下custom-bar-width值如下，没有任何作用，其他属性可以使用，我仅设置了下width，没有任何改变。

### Version
"vuex": "^2.1.1"
"vue": "^2.1.10"

### Your Codes 

    <tab :line-width="1" custom-bar-width="10px">
      <tab-item selected>已发货</tab-item>
      <tab-item>未发货</tab-item>
      <tab-item>全部订单</tab-item>
    </tab>

**Comment by zColdWater** [comment]
：custom-bar-width 绑定方法的话，方法没有被调用。

**Comment by airyland** [comment]
你倒是写个具体版本号啊。。

**Comment by zColdWater** [comment]
"vux": "^2.1.0"
 @airyland  不好意思 写错了刚才，这个版本。

**Comment by airyland** [comment]
文档里有标注相应的版本要求的。

![image](https://cloud.githubusercontent.com/assets/559179/24343560/b8676a58-12f9-11e7-9e58-7a3a859f1625.png)

**Comment by zColdWater** [comment]
嗯哼。 谢谢了。
