### ISSUE TITLE
如何在页面初始化的时候让vux的下拉刷新主动触发一次？

### ISSUE THREAD

**Issue by Pasoul** [airyland/vux#1155]
情况说明：
我希望刚进入app的时候，首页主动触发一次下拉刷新，刷新完成之后，切换路由的时候除非用户手动触发，不再主动触发刷新

**Comment by airyland** [comment]
做不到。下拉刷新是用户手势触发的。建议你直接放个 loading 图标数据加载后隐藏就可以。

**Comment by dmlzj** [comment]
created里面写一次是否可以?
