### ISSUE TITLE
为什么我在created里面设置popup显示show=true的时候不起作用？

### ISSUE THREAD

**Issue by zhangwei900808** [airyland/vux#1159]
为什么我在父组件created里面设置子组件popup显示show=true的时候不起作用？

**Comment by airyland** [comment]
``` js
mounted () {
    this.$nextTick(() => {
      this.show = true
    })
}
```

**Comment by zhangwei900808** [comment]
@airyland 解决了，谢谢你的及时回复，要不然今晚都不一定搞得定，还有个问题：为什么放到created里面不行呢？一定要放到mouted里面吗

**Comment by airyland** [comment]
popup 为了全局共享一个 mask 实现方式比较特殊，在 created 时内部相关的处理还没初始化。其实组件改一改 value 的 watch 部分为 imediate: true 是可以实现直接显示弹窗的，但是会看不到 mask了。。所以还是需要在正确的时机来修改显示状态。

**Comment by zhangwei900808** [comment]
哦哦，这样阿，好的，谢谢你哈
