### ISSUE TITLE
"2.1.1-rc.11"版本下，scroller完全按着文档实例进行，但是无法正常滚动？

### ISSUE THREAD

**Issue by linsywu** [airyland/vux#1163]
![image](https://cloud.githubusercontent.com/assets/15061856/24392789/e9f22fe4-13c7-11e7-8700-946032075aa0.png)
代码如上，但是在微信上打开总是滚动会复位，就是滚动之后松手，又复原了，不知道是不是姿势不对，请大神帮看。
版本号："2.1.1-rc.11"

**Comment by linsywu** [comment]
@airyland

**Comment by airyland** [comment]
代码不完整。内容是 v-for 渲染的，也没看到你有 reset。
