### ISSUE TITLE
scrop组件滚动-手动往下滚，scrop组件自己强制往上重置，麻烦分析下

### ISSUE THREAD

**Issue by zhidd** [airyland/vux#1164]
`<template>
  <div style="height:100%; width:100%; ">
    
    <flexbox>
      <flexbox-item :span="3">
        <scroller lock-x      >
      <div class="flex-demo1">
        <ul>  
          <li   v-for="(item, index) in items" @click="selectStyle (item, item.id)" :class="[style, { active: item.active, unactive: !item.active }]">
                 {{ item.name }}
          </li>
          <li style="height:120px; background-color: #fff;"></li>
       </ul></div>
   
      </scroller>
     </flexbox-item>

      <flexbox-item>
      <scroller lock-x scrollbar-y    ref="scrollerEvent"  >
      <div class="flex-demo2">
             <ul >
                <li class="li2" v-for="(item2, index2) in gridData">
                  <a :href="'http://ok0ovr7ng.bkt.clouddn.com/jy/'+ item2.id + '.png'"><img class="img-35" slot="icon" :src="'http://ok0ovr7ng.bkt.clouddn.com/jy/'+ item2.img + '.png'"></a>
                  <p>{{ item2.title }}</p>
                  <p>{{ item2.price }}</p>
                </li>
                
             </ul>  
              <div style="height:120px; background-color: #fff;"></div>
      </div>
       </scroller>
      </flexbox-item>
    </flexbox>
    
  </div>
</template>`
问题：一个页面有左右两个滚动，左边的滚动手动往下滚，程序自己强制往上重置，右边也是。麻烦帮忙分析下，感谢
现象：在线查看实例 http://119.129.212.192:81/#/a2
qq：1727503992

**Comment by zhidd** [comment]
在线查看实例 http://119.129.212.192:81/#/a2

**Comment by zhidd** [comment]
`<template>
  <div style="height:100%; width:100%; ">
    
    <flexbox>
      <flexbox-item :span="3">
        <scroller lock-x      >
      <div class="flex-demo1">
        <ul>  
          <li   v-for="(item, index) in items" @click="selectStyle (item, item.id)" :class="[style, { active: item.active, unactive: !item.active }]">
                 {{ item.name }}
          </li>
          <li style="height:120px; background-color: #fff;"></li>
       </ul></div>
   
      </scroller>
     </flexbox-item>

      <flexbox-item>
      <scroller lock-x scrollbar-y    ref="scrollerEvent"  >
      <div class="flex-demo2">
             <ul >
                <li class="li2" v-for="(item2, index2) in gridData">
                  <a :href="'http://ok0ovr7ng.bkt.clouddn.com/jy/'+ item2.id + '.png'"><img class="img-35" slot="icon" :src="'http://ok0ovr7ng.bkt.clouddn.com/jy/'+ item2.img + '.png'"></a>
                  <p>{{ item2.title }}</p>
                  <p>{{ item2.price }}</p>
                </li>
                
             </ul>  
              <div style="height:120px; background-color: #fff;"></div>
      </div>
       </scroller>
      </flexbox-item>
    </flexbox>
    
  </div>
</template>

 
  import { Scroller, Flexbox, FlexboxItem } from 'vux'
  export default {
    data () {
      return {
        items: [],
        active3: false,
        style: 'li1',
        scrollTop: 0,
        gridData: []
      }
    },
    components: {
      Flexbox,
      FlexboxItem,
      Scroller
    },
    mounted: function () {
      this.$http.get('http://weixin.ipahoo.com/m_category.php').then((response) => {
        console.log('99999999')
        console.log(response.data)
        this.items = response.data
        this.$nextTick(function () {
          console.log(this.gridData)
        })
      })
        .catch(function (res) {
          console.log('fail')
        })
    },

    methods: {
      selectStyle (item, gid) {
        console.log(this)
        this.$refs.scrollerEvent.reset({top: 0})
        var that = this
        this.items.forEach(function (item) {
          that.$set(item, 'active', false)
        })
        this.$set(item, 'active', true)
        this.$http.get('http://weixin.ipahoo.com/m_goods.php', {params: {cid: gid}}).then((response) => {
          console.log('success')
          console.log(gid)
          console.log(response.data)
          this.gridData = response.data
          this.$nextTick(function () {
            console.log(this.gridData)
          })
        })
        .catch(function (res) {
          console.log('fail')
          console.log(that.gridData)
        })
      },
      onScroll (pos) {
        console.log('on scroll', pos)
        this.scrollTop = pos.top
      }
    }
  }
 

 
@import '~vux/src/styles/1px.less';
@import '~vux/src/styles/center.less';
html,body{height:100%; width:100%;   margin:0; padding:0;}
ul{
  list-style-type:none;
  height:auto;width:100%;overflow:hidden;
}
.li1 {
  border-bottom:1px #cccccc solid;
  border-right:1px #cccccc solid;
  text-align:center;
  padding:5px;
}

.li2 {
  float:left;width:40%;padding:5px;
  list-style-type: none;
  text-align: center;
  height: auto;
}
.dddd{
  border-bottom:1px #cccccc solid;
  height:100%;width:100%;overflow:hidden;
}


.flex-demo1{
   height:auto;
  width:100%;
}
.flex-demo2{
  border-left:1px #cccccc solid;
  height:auto;
  width:100%;
}
.img-35 {
  width:100px;
  height:100px;
}
.active{
  color: rgb(252, 55, 140) !important;
  border-right:0;

}
.unactive{
  color: rgb(0, 0, 0) !important;

}

 
 
`

**Comment by linsywu** [comment]
我也遇到同样的问题，貌似用文档中的例子又是没问题的

**Comment by zhidd** [comment]
加个qq一起互相进步

**Comment by linsywu** [comment]
870249274

**Comment by airyland** [comment]
把代码格式化好，简化代码把业务代码去掉再 reopen。
