### ISSUE TITLE
如何修改group 组件中weui-cells的:before和:after?

### ISSUE THREAD

**Issue by zhangwei900808** [airyland/vux#1165]
我现在在group写一个class，然后通过这个class设置before和after不起作用，请问这个问题如何解决？

**Comment by zhangwei900808** [comment]
![Uploading QQ截图20170328171138.png…]()

**Comment by airyland** [comment]
Are you serious? You didn't even finish uploading the image.

**Comment by zhangwei900808** [comment]
![Uploading QQ截图20170328171138.png…]()

**Comment by zhangwei900808** [comment]
wo pian ni gan ma

**Comment by zhangwei900808** [comment]
.weui-cells:before,
  .weui-cells:after{
    border:none;
  }

**Comment by zhangwei900808** [comment]
@airyland 就算直接这样设置都不起作用
