### ISSUE TITLE
建议 Demos 页中的列表按首字母顺序排列，方便查看。

### ISSUE THREAD

**Issue by tianyong90** [airyland/vux#117]

**Comment by airyland** [comment]
按字母也不合理，毕竟是中文文档，现在分类不够清晰，不过也是按照类型来，比如表单组件，布局组件等

**Comment by tianyong90** [comment]
@airyland 我的意思是，同一类型下再排序。看了下列表里大部分就是直接与控件名 相关的嘛。
比如：alert,button,countdown,countup……之类的，这样也源码里的文件夹顺序也能大致对应起来。

**Comment by airyland** [comment]
了解 今天就改改

**Comment by tianyong90** [comment]
@airyland :+1:
