### ISSUE TITLE
tab tab-item在iPhone6s的safari消失以及路由切换无效

### ISSUE THREAD

**Issue by Ignorantforce** [airyland/vux#1172]
问题描述：
1、当tabitem多的时候，按照官方的代码去使用

```html
<div style="width: 100%;overflow:scroll;-webkit-overflow-scrolling:touch;">
      <tab style="width:500px;">
        <tab-item :selected="demo1 === '分类1'" @click="demo1 = '分类1'">已发货</tab-item>
        <tab-item :selected="demo1 === '分类2'" @click="demo1 = '分类2'">未发货</tab-item>
        <tab-item :selected="demo1 === '分类3'" @click="demo1 = '分类3'">全部订单</tab-item>
        <tab-item :selected="demo1 === '分类4'" @click="demo1 = '分类4'">全部订单</tab-item>
        <tab-item :selected="demo1 === '分类5'" @click="demo1 = '分类5'">全部订单</tab-item>
      </tab>
    </div>
```
发现在PC端浏览器点击tab没有问题，在安卓机（小米3S）也没有问题。
但是在iPhone6s（10.1.1）情况下会出现tabitem都消失，触发方式大概是当点击tabitem的同时滑动，整个tab都消失掉。
2、配合router-link的时候，有时候点击无法切换页面（概率出现）

**Comment by airyland** [comment]
1.消失这个问题过于神奇，建议 build 个页面放出来我们看看。
2.组件 click 事件要使用 click.native
3. 无法切换页面不稳定重现的也没法解决，如果是使用 router-link，那么这个问题就不归 vux 管了。

**Comment by Ignorantforce** [comment]
不好意思，前几天没空，因为第一次使用vue技术栈的一套内部信贷系统在准备上线。
1、关于Build个页面出来，可能也需要等完成整个第一期的时候，我试试单独拎出来看看。
2、click.native这个用法我知道
3、确实是配合使用router-link会出现点击跳转路由的时候，并没有跳转过去，后来取消了使用tab这个组件，改为普通html写的tab。
另外很感谢你这个vux，让我们省了一部分UI的事，因为我们并没有专业的前端去做这一块，都是后端人员开发，遇到很多事情都很懵逼，谢谢。
