### ISSUE TITLE
通过webpack合并压缩代码时出错（版本：2.1.1-rc.14）

### ISSUE THREAD

**Issue by esioncao** [airyland/vux#1173]
ERROR in static/js/vendor.5580b6279c0db441be09.js from UglifyJs
Unexpected character '`' [./~/.2.1.1-rc.14@vux/src/libs/router.js:14,0][static/js/vendor.5580b6279c0db441be09.js:791,11]

**Comment by lichunqiang** [comment]
为啥不按issue template 来呢？

报下你的node版本？

**Comment by esioncao** [comment]
@lichunqiang 
node版本号 v6.9.1！！！！！
麻烦大神了 这个问题困扰我好几天了 实在是急啊 不好意思没有按照模版来 望谅解！！！！

**Comment by airyland** [comment]
没有按照模板来，要手动配置 babel 编译 vux 的 js 文件。或者按照文档正确配置好 vux-loader。
