### ISSUE TITLE
组件scroller

### ISSUE THREAD

**Issue by sixiakun** [airyland/vux#1175]
###vux 2.1.1-rc.12
发现从使用了scroller的页面到其他页面有时候会报错，不知道是不是组件的问题，发上来给看下，不是的可能也是有的，不影响功能，不过控制台飘红总是心里不舒服，^_^
![image](https://cloud.githubusercontent.com/assets/20946763/24446450/0b5ca410-14a0-11e7-8125-442acb3ecee5.png)
![image](https://cloud.githubusercontent.com/assets/20946763/24446481/24297dec-14a0-11e7-8037-6a081c6b9547.png)

**Comment by Pasoul** [comment]
scroller的lock-y属性可以动态设置嘛，比如两秒之后设置为true

**Comment by yuebo** [comment]
我也遇到类似的，模拟方法是在scroller组件页面上跳转另一页面后修改窗口大小(触发window.resize事件)，然后就会出来一堆这个错误了

**Comment by sixiakun** [comment]
二楼的兄弟，你说的这个能解决这个报错的问题么

**Comment by airyland** [comment]
@yuebo 感谢，按你的方法可以重现。

**Comment by sixiakun** [comment]
@yuebo @airyland 。。为啥我这不用改变窗口大小即可重现，作者大大一直没回复，以为你这段时间有事忙，原来也在关注，辛苦

**Comment by airyland** [comment]
直接升级 vux-xscroll 试试。
