### ISSUE TITLE
初始化，会出现乱码;有的依赖没找到

### ISSUE THREAD

**Issue by yaoyuande** [airyland/vux#1176]
npm -v : 6.2
vue -v : 2 ( 最新  )
![image](https://cloud.githubusercontent.com/assets/17507151/24446560/7cc62306-14a0-11e7-8f2b-1d853576b76b.png)
乱码：（‘git’+********************）

**Comment by yaoyuande** [comment]
![image](https://cloud.githubusercontent.com/assets/17507151/24447005/19061356-14a2-11e7-8b45-c6743f10dda8.png)

blur.vue中的代码
![image](https://cloud.githubusercontent.com/assets/17507151/24447031/2a1ca8b2-14a2-11e7-9792-1114055085ba.png)

**Comment by lichunqiang** [comment]
怎么像都没初始化完成，你的git装了？是不是能通过git直接clone呢？

```
$ git clone git@github.com:airyland/vux2.git
```
然后自己执行安装依赖试试。

**Comment by yaoyuande** [comment]
多谢了，就是git的原因，我以前没安装git,只用的npm和vue。现在好了。多谢多谢
