### ISSUE TITLE
关于toast的一个小疑问

### ISSUE THREAD

**Issue by CR-pcs** [airyland/vux#1177]
是这样的，在使用data操纵toast时候，异步修改它的属性，发现只有time没有跟随变化，value、type等都是正常的，应该不是操作的问题；
所以请教一下，这个问题该如何解决？
代码如下：

`<toast v-model="toastShow" :text="$t('文字')" :type="toastType" :time="toastTime"></toast>`

this.toastShow=true;
      this.toastType='success';
      this.toastTime=12000;
      var self = this;
      setTimeout(function () {
        self.toastShow=true;
        self.toastType='warn';
        self.toastTime=1000;
      },2000);

**Comment by airyland** [comment]
在 show=true 时开始计时，你在 show=true 后才修改的 time 并不会修改已经显示的 toast 的时间。
