### ISSUE TITLE
关于scroller组件和tab组件组合使用的问题

### ISSUE THREAD

**Issue by Pasoul** [airyland/vux#1178]
描述：
我使用tab组件实现选项卡，每个swiper-item选项卡里面嵌套一个scroller组件实现下拉刷新和上拉加载，问题是当我上下滚动的时候也可以左右滑动选项卡，这样会感觉页面很飘。

期望：
我希望上下滚动的时候禁止左右滑动效果，滚动结束了开启左右滑动效果，同样的，当我左右滑动选项卡时，禁止上下滚动，滑动结束后开启上下滚动

代码：
这是tab选项卡：
<tab :line-width=2 active-color='#fc378c' v-model="index" :custom-bar-width="getBarWidth">
	<tab-item class="vux-center" :selected="demo2 === item" v-for="(item, index) in list" @click="demo2 = item" :key="index">{{item}}</tab-item>
</tab>
这是我的swiper,里面每个swiper-item嵌套一个可以上下滚动的scroller
<swiper v-model="index" height="100%" :show-dots="false">
		        <swiper-item>
	          		<scroller  lock-x scrollbar-y use-pulldown @on-pulldown-loading="load1" ref="scroller" v-model="status1" :pulldown-config="{content:'',downContent:'',upContent:'',loadingContent:''}">			  
		          		<div class="preferred-wrapper">
		          			<preferredActv></preferredActv>
		          			 
					      <div slot="pulldown" class="xs-plugin-pulldown-container xs-plugin-pulldown-down" style="position: absolute; width: 100%; height: 0.6rem; line-height: 0.6rem; top: -1rem; text-align: center;">
					        <span v-show="status1.pulldownStatus === 'default'"></span>
					        <span class="pulldown-arrow" v-show="status1.pulldownStatus === 'down' || status1.pulldownStatus === 'up'" :class="{'rotate': status1.pulldownStatus === 'up'}">↓</span>
					        <span v-show="status1.pulldownStatus === 'loading'"><spinner type="ios-small"></spinner></span>
					      </div>
					      <div style="height: 2.29rem;"></div>
		          		</div>
			        </scroller>
		        </swiper-item>
</swiper>

**Comment by airyland** [comment]
1. 代码正确格式化是一种基本尊重
2. 文档写了

> 不要在swiper里嵌套scroller，在web上过于复杂化而且手势会有冲突，相关Issue将不会处理。

**Comment by Pasoul** [comment]
好的，不好意思，我下次注意
