### ISSUE TITLE
scroller 滚动时跳转控制台报错

### ISSUE THREAD

**Issue by yuebo** [airyland/vux#1187]
组件版本
 "vue-router": "^2.2.0",
 "vuex": "^2.2.1",
 "vux": "^2.1.1-rc.14"
问题描述
经测试，在有scroller组件页面，当用户触发滚动且滚动尚未结束时按返回，控制台后端会报错误**Uncaught TypeError: Cannot read property 'getScrollTop' of null.**

![image](https://cloud.githubusercontent.com/assets/9998927/24533092/fe00d9d6-15f7-11e7-9360-8dec1d11431c.png)
代码不贴了，官方例子里就可以重现。

**Comment by wh-Coder** [comment]
哈哈，我也遇到了这个报错
