### ISSUE TITLE
scroller嵌套的组件使用了previewer，显示图片的时候出现了滚动条，这个怎么解决？

### ISSUE THREAD

**Issue by zhangwei900808** [airyland/vux#1190]
![image](https://cloud.githubusercontent.com/assets/4385154/24538090/a4a14f3e-1619-11e7-8bb1-d472a91e743c.png)

**Comment by zhangwei900808** [comment]
@airyland @fundon @blue5tar @gzlboy @ZoeyYoung 你们都不回答我只好叫你们所有人了，抱歉打扰了，不过这个问题怎么解决哈

**Comment by chunecai** [comment]
我的也是，有scroller就有问题了。
我的直接是滚动长屏。

需要滚动到下面才x显示。

**Comment by chunecai** [comment]
我的已经解决了，把previewer 放到 scroller外面就好了。

**Comment by airyland** [comment]
因实际需求复杂 scroller 不再维护，该 issue 关闭。

**Comment by wangchaolonglls** [comment]
@zhangwei900808 
`该问题我也遇到了，还是写法的问题   一定要在div 中增加v-transfer-dom  @这个关键字，否则会出现描述的问题`
 ```js
  <div v-transfer-dom>
                     <previewer :list="item.list" ref="previewer" :options="options"></previewer>
                 </div>
```
