### ISSUE TITLE
inline-calender逻辑问题

### ISSUE THREAD

**Issue by greedying** [airyland/vux#1192]
### Version
最新版本

### Android or iOS
都是

### Your Codes 
官网demo

### Expected behavior and actual behavior.
比如现在是3月份，这时候就不能选择4月的日期，一定要把月份切换到4月才能选择4月的日期。
这种逻辑是否有些问题。

百度一下万年历，会发现一般逻辑，是点击四月份日期，会选中日期，并且自动切换到四月份

**Comment by greedying** [comment]
另外，start-date 与disable-past 官网文档说可以同时使用，相比各自使用，同时使用有什么特殊的用处么？ 

谢谢

**Comment by airyland** [comment]
关于 start-date + disable-past 没有什么特殊的，两个都在时取较大值为 start-date。
同理 end-date + disable-future， 取较小值为 end-date
