### ISSUE TITLE
今天更新后发现demos里的Alert.vue以插件方式调用弹出的content为空白

### ISSUE THREAD

**Issue by xiangxisheng** [airyland/vux#1195]
今天更新后发现demos里的Alert.vue以插件方式调用弹出的content为空白
后来找到/src/plugins/alert/index.js里的
if (options.content) {
  $vm.$el.querySelector('.weui-dialog__bd').innerHTML = options['content']
}
这部分的代码被删除了

**Comment by airyland** [comment]
上代码后 reopen.

**Comment by airyland** [comment]
check 了一下，这一个更新的源码没有提交完全。
