### ISSUE TITLE
popup-picker省市区第三级没有数据会报错

### ISSUE THREAD

**Issue by Z-wave** [airyland/vux#1196]
![image](https://cloud.githubusercontent.com/assets/16026552/24574811/096e2f2a-16cb-11e7-987c-6462a6f55ada.png)

点击确定第三级会取上一级里面的数据，在没有第三级的，应该为空

**Comment by airyland** [comment]
你是自己的数据源么，要保证有三级数据，不然组件无法正确处理。
Address 组件是手动为第三级空白的地址添加了 -- 这样的脏数据。

**Comment by airyland** [comment]
你期望组件来怎么处理？

**Comment by Z-wave** [comment]
@airyland 没有数据就为空不做处理

**Comment by Hfengxiang** [comment]
我们这些数据在设计之初不太规范,有些省份只有两级,有的只有一级.
如果你们能够该组件,没有数据就给默认值{name:"-",value:"-1",parent:"它的父节点的vuale"}
或者像Z-wave说的不做处理也行@airyland

**Comment by airyland** [comment]
这样组件内部挺难处理，这是个三级联动，却可以赋值长度为2甚至长度为1的数组值。。

**Comment by Hfengxiang** [comment]
那好吧,我跟后台协商,让它那边填充缺省值,把数据变为三级,这样应该就可以了把?

**Comment by Hfengxiang** [comment]
我把别的数据全删了,只留下安徽省的数据,是三级的,但是点击控件后popup选择面板没弹出来,是什么原因啊@airyland
[Uploading replace.txt…]()




[Uploading log.png…]()

**Comment by Hfengxiang** [comment]
我把别的数据全删了,只留下安徽省的数据,是三级的,但是点击控件后popup选择面板没弹出来,是什么原因啊@airyland
图片和json实在是传不上来,具体的现象是点击选择地址的时候,弹出的popup层只能看到cancel_text和confirm_text

**Comment by airyland** [comment]
既然数据不多，你直接帖上来。

**Comment by Hfengxiang** [comment]
`[
  {
    "name": "安徽省",
    "parent": "None",
    "value": "ah"
  },
  {
    "name": "滁州市",
    "parent": "ah",
    "value": "ah550"
  },
  {
    "name": "琅琊区",
    "parent": "ah550",
    "value": "ah55001"
  },
  {
    "name": "全椒县",
    "parent": "ah550",
    "value": "ah55002"
  },
  {
    "name": "天长市",
    "parent": "ah550",
    "value": "ah55004"
  },
  {
    "name": "合肥市",
    "parent": "ah",
    "value": "ah551"
  },
  {
    "name": "瑶海区",
    "parent": "ah551",
    "value": "ah55101"
  },
  {
    "name": "肥东县",
    "parent": "ah551",
    "value": "ah55102"
  },
  {
    "name": "肥西县",
    "parent": "ah551",
    "value": "ah55103"
  },
  {
    "name": "蚌埠市",
    "parent": "ah",
    "value": "ah552"
  },
  {
    "name": "蚌山区",
    "parent": "ah552",
    "value": "ah55201"
  },
  {
    "name": "五河县",
    "parent": "ah552",
    "value": "ah55202"
  },
  {
    "name": "怀远县",
    "parent": "ah552",
    "value": "ah55203"
  },
  {
    "name": "芜湖市",
    "parent": "ah",
    "value": "ah553"
  },
  {
    "name": "无为县",
    "parent": "ah553",
    "value": "ah55106"
  },
  {
    "name": "镜湖区",
    "parent": "ah553",
    "value": "ah55301"
  },
  {
    "name": "芜湖县",
    "parent": "ah553",
    "value": "ah55302"
  },
  {
    "name": "淮南市",
    "parent": "ah",
    "value": "ah554"
  },
  {
    "name": "凤台县",
    "parent": "ah554",
    "value": "ah55107"
  },
  {
    "name": "田家庵区",
    "parent": "ah554",
    "value": "ah55401"
  },
  {
    "name": "潘集区",
    "parent": "ah554",
    "value": "ah55402"
  },
  {
    "name": "马鞍山市",
    "parent": "ah",
    "value": "ah555"
  },
  {
    "name": "雨山区",
    "parent": "ah555",
    "value": "ah55501"
  },
  {
    "name": "当涂县",
    "parent": "ah555",
    "value": "ah55502"
  },
  {
    "name": "花山区",
    "parent": "ah555",
    "value": "ah55503"
  },
  {
    "name": "安庆市",
    "parent": "ah",
    "value": "ah556"
  },
  {
    "name": "宜秀区",
    "parent": "ah556",
    "value": "ah55601"
  },
  {
    "name": "太湖县",
    "parent": "ah556",
    "value": "ah55602"
  },
  {
    "name": "枞阳县",
    "parent": "ah556",
    "value": "ah55603"
  },
  {
    "name": "宿州市",
    "parent": "ah",
    "value": "ah557"
  },
  {
    "name": "埇桥区",
    "parent": "ah557",
    "value": "ah55701"
  },
  {
    "name": "灵璧县",
    "parent": "ah557",
    "value": "ah55704"
  },
  {
    "name": "泗县",
    "parent": "ah557",
    "value": "ah55705"
  },
  {
    "name": "阜阳市",
    "parent": "ah",
    "value": "ah558"
  },
  {
    "name": "颍州区",
    "parent": "ah558",
    "value": "ah55801"
  },
  {
    "name": "阜南县",
    "parent": "ah558",
    "value": "ah55803"
  },
  {
    "name": "界首市",
    "parent": "ah558",
    "value": "ah55806"
  },
  {
    "name": "黄山市",
    "parent": "ah",
    "value": "ah559"
  },
  {
    "name": "屯溪区",
    "parent": "ah559",
    "value": "ah55901"
  },
  {
    "name": "歙县",
    "parent": "ah559",
    "value": "ah55902"
  },
  {
    "name": "祁门县",
    "parent": "ah559",
    "value": "ah55903"
  },
  {
    "name": "亳州市",
    "parent": "ah",
    "value": "ah560"
  },
  {
    "name": "谯城区",
    "parent": "ah560",
    "value": "ah56001"
  },
  {
    "name": "利辛县",
    "parent": "ah560",
    "value": "ah56002"
  },
  {
    "name": "涡阳县",
    "parent": "ah560",
    "value": "ah56003"
  },
  {
    "name": "淮北市",
    "parent": "ah",
    "value": "ah561"
  },
  {
    "name": "相山区",
    "parent": "ah561",
    "value": "ah56101"
  },
  {
    "name": "濉溪县",
    "parent": "ah561",
    "value": "ah56102"
  },
  {
    "name": "杜集区",
    "parent": "ah561",
    "value": "ah56105"
  },
  {
    "name": "铜陵市",
    "parent": "ah",
    "value": "ah562"
  },
  {
    "name": "郊区",
    "parent": "ah562",
    "value": "ah56201"
  },
  {
    "name": "铜陵县",
    "parent": "ah562",
    "value": "ah56202"
  },
  {
    "name": "铜官山区",
    "parent": "ah562",
    "value": "ah56203"
  },
  {
    "name": "宣城市",
    "parent": "ah",
    "value": "ah563"
  },
  {
    "name": "宣州区",
    "parent": "ah563",
    "value": "ah56301"
  },
  {
    "name": "泾县",
    "parent": "ah563",
    "value": "ah56302"
  },
  {
    "name": "郎溪县",
    "parent": "ah563",
    "value": "ah56303"
  },
  {
    "name": "六安市",
    "parent": "ah",
    "value": "ah564"
  },
  {
    "name": "金安区",
    "parent": "ah564",
    "value": "ah56401"
  },
  {
    "name": "舒城县",
    "parent": "ah564",
    "value": "ah56402"
  },
  {
    "name": "寿县",
    "parent": "ah564",
    "value": "ah56403"
  },
  {
    "name": "池州市",
    "parent": "ah",
    "value": "ah566"
  },
  {
    "name": "贵池区",
    "parent": "ah566",
    "value": "ah56601"
  },
  {
    "name": "青阳县",
    "parent": "ah566",
    "value": "ah56602"
  },
  {
    "name": "东至县",
    "parent": "ah566",
    "value": "ah56603"
  }
]
`
这个是json数据,但是点击选择地点时展示不出来地址列表

**Comment by airyland** [comment]
第一栏，`"parent": "None" ` 删掉，或者值设为0。

**Comment by Hfengxiang** [comment]
解决了,谢谢大神^_^

**Comment by shiyingxin-s** [comment]
省市区，市为空时，区也为空不做处理。例如台湾省，没有市区。

**Comment by shiyingxin-s** [comment]
[{"name":"河北省","districts":[{"name":"唐山市","districts":[{"name":"路南区","districts":[],"id":"130202","level":"district","parentId":"130200"},{"name":"路北区","districts":[],"id":"130203","level":"district","parentId":"130200"},{"name":"古冶区","districts":[],"id":"130204","level":"district","parentId":"130200"},{"name":"开平区","districts":[],"id":"130205","level":"district","parentId":"130200"},{"name":"丰南区","districts":[],"id":"130207","level":"district","parentId":"130200"},{"name":"丰润区","districts":[],"id":"130208","level":"district","parentId":"130200"},{"name":"曹妃甸区","districts":[],"id":"130209","level":"district","parentId":"130200"},{"name":"滦县","districts":[],"id":"130223","level":"district","parentId":"130200"},{"name":"滦南县","districts":[],"id":"130224","level":"district","parentId":"130200"},{"name":"乐亭县","districts":[],"id":"130225","level":"district","parentId":"130200"},{"name":"迁西县","districts":[],"id":"130227","level":"district","parentId":"130200"},{"name":"玉田县","districts":[],"id":"130229","level":"district","parentId":"130200"},{"name":"遵化市","districts":[],"id":"130281","level":"district","parentId":"130200"},{"name":"迁安市","districts":[],"id":"130283","level":"district","parentId":"130200"}],"id":"130200","level":"city","parentId":"130000"}],"id":"130000","level":"province","parentId":"100000"},{"name":"香港特别行政区","districts":[],"id":"810000","level":"province","parentId":"100000"},{"name":"甘肃省","districts":[{"name":"兰州市","districts":[{"name":"城关区","districts":[],"id":"620102","level":"district","parentId":"620100"},{"name":"七里河区","districts":[],"id":"620103","level":"district","parentId":"620100"},{"name":"西固区","districts":[],"id":"620104","level":"district","parentId":"620100"},{"name":"安宁区","districts":[],"id":"620105","level":"district","parentId":"620100"},{"name":"红古区","districts":[],"id":"620111","level":"district","parentId":"620100"},{"name":"永登县","districts":[],"id":"620121","level":"district","parentId":"620100"},{"name":"皋兰县","districts":[],"id":"620122","level":"district","parentId":"620100"},{"name":"榆中县","districts":[],"id":"620123","level":"district","parentId":"620100"}],"id":"620100","level":"city","parentId":"620000"},{"name":"嘉峪关市","districts":[],"id":"620200","level":"city","parentId":"620000"},{"name":"金昌市","districts":[{"name":"金川区","districts":[],"id":"620302","level":"district","parentId":"620300"},{"name":"永昌县","districts":[],"id":"620321","level":"district","parentId":"620300"}],"id":"620300","level":"city","parentId":"620000"},{"name":"白银市","districts":[{"name":"白银区","districts":[],"id":"620402","level":"district","parentId":"620400"},{"name":"平川区","districts":[],"id":"620403","level":"district","parentId":"620400"},{"name":"靖远县","districts":[],"id":"620421","level":"district","parentId":"620400"},{"name":"会宁县","districts":[],"id":"620422","level":"district","parentId":"620400"},{"name":"景泰县","districts":[],"id":"620423","level":"district","parentId":"620400"}],"id":"620400","level":"city","parentId":"620000"},{"name":"天水市","districts":[{"name":"秦州区","districts":[],"id":"620502","level":"district","parentId":"620500"},{"name":"麦积区","districts":[],"id":"620503","level":"district","parentId":"620500"},{"name":"清水县","districts":[],"id":"620521","level":"district","parentId":"620500"},{"name":"秦安县","districts":[],"id":"620522","level":"district","parentId":"620500"},{"name":"甘谷县","districts":[],"id":"620523","level":"district","parentId":"620500"},{"name":"武山县","districts":[],"id":"620524","level":"district","parentId":"620500"},{"name":"张家川回族自治县","districts":[],"id":"620525","level":"district","parentId":"620500"}],"id":"620500","level":"city","parentId":"620000"},{"name":"武威市","districts":[{"name":"凉州区","districts":[],"id":"620602","level":"district","parentId":"620600"},{"name":"民勤县","districts":[],"id":"620621","level":"district","parentId":"620600"},{"name":"古浪县","districts":[],"id":"620622","level":"district","parentId":"620600"},{"name":"天祝藏族自治县","districts":[],"id":"620623","level":"district","parentId":"620600"}],"id":"620600","level":"city","parentId":"620000"},{"name":"张掖市","districts":[{"name":"甘州区","districts":[],"id":"620702","level":"district","parentId":"620700"},{"name":"肃南裕固族自治县","districts":[],"id":"620721","level":"district","parentId":"620700"},{"name":"民乐县","districts":[],"id":"620722","level":"district","parentId":"620700"},{"name":"临泽县","districts":[],"id":"620723","level":"district","parentId":"620700"},{"name":"高台县","districts":[],"id":"620724","level":"district","parentId":"620700"},{"name":"山丹县","districts":[],"id":"620725","level":"district","parentId":"620700"}],"id":"620700","level":"city","parentId":"620000"},{"name":"平凉市","districts":[{"name":"崆峒区","districts":[],"id":"620802","level":"district","parentId":"620800"},{"name":"泾川县","districts":[],"id":"620821","level":"district","parentId":"620800"},{"name":"灵台县","districts":[],"id":"620822","level":"district","parentId":"620800"},{"name":"崇信县","districts":[],"id":"620823","level":"district","parentId":"620800"},{"name":"华亭县","districts":[],"id":"620824","level":"district","parentId":"620800"},{"name":"庄浪县","districts":[],"id":"620825","level":"district","parentId":"620800"},{"name":"静宁县","districts":[],"id":"620826","level":"district","parentId":"620800"}],"id":"620800","level":"city","parentId":"620000"},{"name":"酒泉市","districts":[{"name":"肃州区","districts":[],"id":"620902","level":"district","parentId":"620900"},{"name":"金塔县","districts":[],"id":"620921","level":"district","parentId":"620900"},{"name":"瓜州县","districts":[],"id":"620922","level":"district","parentId":"620900"},{"name":"肃北蒙古族自治县","districts":[],"id":"620923","level":"district","parentId":"620900"},{"name":"阿克塞哈萨克族自治县","districts":[],"id":"620924","level":"district","parentId":"620900"},{"name":"玉门市","districts":[],"id":"620981","level":"district","parentId":"620900"},{"name":"敦煌市","districts":[],"id":"620982","level":"district","parentId":"620900"}],"id":"620900","level":"city","parentId":"620000"},{"name":"庆阳市","districts":[{"name":"西峰区","districts":[],"id":"621002","level":"district","parentId":"621000"},{"name":"庆城县","districts":[],"id":"621021","level":"district","parentId":"621000"},{"name":"环县","districts":[],"id":"621022","level":"district","parentId":"621000"},{"name":"华池县","districts":[],"id":"621023","level":"district","parentId":"621000"},{"name":"合水县","districts":[],"id":"621024","level":"district","parentId":"621000"},{"name":"正宁县","districts":[],"id":"621025","level":"district","parentId":"621000"},{"name":"宁县","districts":[],"id":"621026","level":"district","parentId":"621000"},{"name":"镇原县","districts":[],"id":"621027","level":"district","parentId":"621000"}],"id":"621000","level":"city","parentId":"620000"},{"name":"定西市","districts":[{"name":"安定区","districts":[],"id":"621102","level":"district","parentId":"621100"},{"name":"通渭县","districts":[],"id":"621121","level":"district","parentId":"621100"},{"name":"陇西县","districts":[],"id":"621122","level":"district","parentId":"621100"},{"name":"渭源县","districts":[],"id":"621123","level":"district","parentId":"621100"},{"name":"临洮县","districts":[],"id":"621124","level":"district","parentId":"621100"},{"name":"漳县","districts":[],"id":"621125","level":"district","parentId":"621100"},{"name":"岷县","districts":[],"id":"621126","level":"district","parentId":"621100"}],"id":"621100","level":"city","parentId":"620000"},{"name":"陇南市","districts":[{"name":"武都区","districts":[],"id":"621202","level":"district","parentId":"621200"},{"name":"成县","districts":[],"id":"621221","level":"district","parentId":"621200"},{"name":"文县","districts":[],"id":"621222","level":"district","parentId":"621200"},{"name":"宕昌县","districts":[],"id":"621223","level":"district","parentId":"621200"},{"name":"康县","districts":[],"id":"621224","level":"district","parentId":"621200"},{"name":"西和县","districts":[],"id":"621225","level":"district","parentId":"621200"},{"name":"礼县","districts":[],"id":"621226","level":"district","parentId":"621200"},{"name":"徽县","districts":[],"id":"621227","level":"district","parentId":"621200"},{"name":"两当县","districts":[],"id":"621228","level":"district","parentId":"621200"}],"id":"621200","level":"city","parentId":"620000"},{"name":"临夏回族自治州","districts":[{"name":"临夏市","districts":[],"id":"622901","level":"district","parentId":"622900"},{"name":"临夏县","districts":[],"id":"622921","level":"district","parentId":"622900"},{"name":"康乐县","districts":[],"id":"622922","level":"district","parentId":"622900"},{"name":"永靖县","districts":[],"id":"622923","level":"district","parentId":"622900"},{"name":"广河县","districts":[],"id":"622924","level":"district","parentId":"622900"},{"name":"和政县","districts":[],"id":"622925","level":"district","parentId":"622900"},{"name":"东乡族自治县","districts":[],"id":"622926","level":"district","parentId":"622900"},{"name":"积石山保安族东乡族撒拉族自治县","districts":[],"id":"622927","level":"district","parentId":"622900"}],"id":"622900","level":"city","parentId":"620000"},{"name":"甘南藏族自治州","districts":[{"name":"合作市","districts":[],"id":"623001","level":"district","parentId":"623000"},{"name":"临潭县","districts":[],"id":"623021","level":"district","parentId":"623000"},{"name":"卓尼县","districts":[],"id":"623022","level":"district","parentId":"623000"},{"name":"舟曲县","districts":[],"id":"623023","level":"district","parentId":"623000"},{"name":"迭部县","districts":[],"id":"623024","level":"district","parentId":"623000"},{"name":"玛曲县","districts":[],"id":"623025","level":"district","parentId":"623000"},{"name":"碌曲县","districts":[],"id":"623026","level":"district","parentId":"623000"},{"name":"夏河县","districts":[],"id":"623027","level":"district","parentId":"623000"}],"id":"623000","level":"city","parentId":"620000"}],"id":"620000","level":"province","parentId":"100000"}]

**Comment by a15218378694** [comment]
> 省市区，市为空时，区也为空不做处理。例如台湾省，没有市区。

现在展示有问题, 有什么办法么
![image](https://github.com/airyland/vux/assets/29919045/17014bec-02d8-4a38-b083-4bbde6a129b2)
