### ISSUE TITLE
scroller无法滚动到底部，已经有reset ,页面无报错，但松开后又返回原来位置

### ISSUE THREAD

**Issue by jinghaonode** [airyland/vux#1197]
<template>

    <div class="pagemain graybg  home-page">
        <scroller lock-x scrollbar-y use-pullup height="-50" @on-pullup-loading="LoadMore" v-model="status"
                  ref="scroller">
            
 
            
            <div class="clear"></div>
            <div class="bbs-list">

                <ul>
                    
                    <li v-for="item in threadList">
                        <router-link :to="{name: 'detail', query: { id: item.aid}}">
                            <div class="t">
                                <i v-for="tag in item.tag">{{tag}}</i>
                                <span>{{item.title}}</span>
                            </div>
                            
                        </router-link>
                       
                    </li>

                </ul>
                <div slot="pullup" class="xs-plugin-pullup-container xs-plugin-pullup-up"
                     style="position: relative; width: 100%; height: 50px; text-align: center;">
                    <span v-show="status.pullupStatus === 'loading'"><spinner type="ios-small"></spinner>加载中</span>
                    <span v-show="endTips"> 没有更多了</span>
                </div>

            </div>
            
        </scroller>

     
    </div>

</template>

    import {Swiper} from 'vux'
    export default {
        components: {
            Swiper
        },
        data () {
            return {
                pageshow: false,
                focusImgList: [],   // 幻灯片
                navList: [],       // 分类导航
                navCurrentId: 1,  // 分类导航当前选中值标示 
                threadList: [], // 帖子列表
                showAllNav: false, // 是否展示全部分类
                page: 0,
                limit: 20,
                loadMoreIco: false,
                isLoad: false, // 标示现在是否正在加载数据，还没加载完
                endTips: false,
                status: {
                    pullupStatus: 'default',
                    pulldownStatus: 'default'
                },
                navMoreBtn: true,
                navCloseBtn: false,
                navWidth: 0,
                time: 100
            }
        },
        activated(){
            console.log('组件已经激活')
            this.$refs.scroller.reset()
        },
        mounted(){
            this.onRefresh();   // 加载初始化数据
            this.pageScroll(); //监听滚动
            this.navWidth = $(".home-page .topnav .list").width();
        },
        beforeRouteEnter(to, from, next) {
            if (from.name !== 'detail') {
                window.sessionStorage.scrollTop = 0
            }
            next();
        },
        beforeRouteLeave(to, from, next) {
            window.sessionStorage.scrollTop = $(window).scrollTop();
            next();
        },
        methods: {
            onRefresh () {
                let _this = this
                this.$pageload.show()
                this.$axios.get('/home', {
                    params: {}
                }).then(result => {
                    this.$pageload.hide()
                    console.log(result.data)
                    // 帖子列表
                    this.threadList = result.data.thread
                })
            },
 
            LoadMore (name, isClear){
                console.log('上拉加载更多' + isClear)
                this.page++
                let _this = this
                // 上拉加载更多
                if (!isClear) {
                    this.loadMoreIco = true
                }
                this.$axios.get('/home', {
                    params: {
                        tid: _this.navCurrentId,
                        page: this.page
                    }
                }).then(result => {
                    this.loadMoreIco = false
                    this.$loading.hide();
                    var datas = result.data
                    console.log(datas)
                    if (!datas.length) {
                        this.endTips = true;
                        return
                    }
                    if (isClear) {
                        //  isClear标示切换分类后原来内容先清空
                        this.threadList = [];
                        this.threadList = this.threadList.concat(datas);
                        console.log('push新内容' + datas)
                        this.$nextTick(() => {
                            _this.page++
                             _this.$refs.scroller.reset()
                            _this.$refs.scroller.donePullup()
                        })
                    } else {
                        this.threadList = this.threadList.concat(datas);
                        console.log('追加' + this.threadList);
                        this.$nextTick(() => {
                            _this.page++
                            _this.$refs.scroller.reset()
                            _this.$refs.scroller.donePullup()
                        })
                    }
                    this.isLoad = false;
                })
            }
        }
    }

**Comment by jinghaonode** [comment]
问题已经解决，原因是<scroller></scroller>中间包含的内容必须用一个大div包起来，里面可以再包含div，但不可以多个div并列，具体不知道为什么有这样的要求，难道是性能？还是难以计算中间几个div的总高度，作者大神要是看到还是请指点一二，不胜感激，总之VUX用来来还是蛮爽的

**Comment by airyland** [comment]
高度不好计算，事件绑定和位移都麻烦。
