### ISSUE TITLE
Range: enable selecting start number and end number?

### ISSUE THREAD

**Issue by airyland** [airyland/vux#12]

**Comment by airyland** [comment]
![image](https://cloud.githubusercontent.com/assets/559179/13518499/84d33392-e209-11e5-91c1-a93de6a7a1e5.png)

**Comment by airyland** [comment]
Moved to #32

**Comment by GITleonine1989** [comment]
跟alert同样的方法，一个行，一个不行，代码都贴了，我估计你看到失败了三个字 就没看了，我也可以理解你遇到太多失败了什么的问题，所以看到这个就恼火。我下次会描述的更好一点。烦请打开评论，我还有些问题要提。
