### ISSUE TITLE
引用vux，在打包时候报错

### ISSUE THREAD

**Issue by leiluochenjian** [airyland/vux#1202]
1.vux的版本 ^2.1.1-rc.14"
2.环境是vue-cli vue ^2.2.2
3.报错截图
![image](https://cloud.githubusercontent.com/assets/16258214/24584544/7680c8a6-17a3-11e7-92cc-4d848e1d2656.png)
4.报错源码代码截图 
![image](https://cloud.githubusercontent.com/assets/16258214/24584569/2c9161f0-17a4-11e7-9556-5bca16959871.png)
5.尝试
![image](https://cloud.githubusercontent.com/assets/16258214/24584800/597bfe66-17ac-11e7-96d4-308fa61f5fb7.png)
结果又出另外一种错
![image](https://cloud.githubusercontent.com/assets/16258214/24584796/29a58fa4-17ac-11e7-9c97-06c1358196cc.png)

**Comment by airyland** [comment]
用的是 vux2 模版吗？

**Comment by leiluochenjian** [comment]
是，还用vux-loader，难道没有是因为vux-loader配好，不应该呀，应该没有关系

**Comment by airyland** [comment]
如果你用 vux2 模版应该不会报错才对。

**Comment by leiluochenjian** [comment]
![image](https://cloud.githubusercontent.com/assets/16258214/24585446/37b84936-17bd-11e7-8f58-90adae0b090f.png)
应该不需要弄什么东西吧

**Comment by airyland** [comment]
vux-loader 有没有正确配置？

**Comment by leiluochenjian** [comment]
这个是在webpack.dev.conf.js
![image](https://cloud.githubusercontent.com/assets/16258214/24585561/73c893ec-17c0-11e7-9690-837a70636de2.png)

**Comment by airyland** [comment]
base 不配置？还是 prod 没有配置？

**Comment by leiluochenjian** [comment]
不好意思，是没有vux-loader配置好，没有在打包配置文件引用

**Comment by airyland** [comment]
配置 base 就好了，其他两个都是基于 base。
