### ISSUE TITLE
[提议] 关于让x-input/x-textarea支持lazy修饰符的建议

### ISSUE THREAD

**Issue by mistkafka** [airyland/vux#1203]
原生vuejs对input跟textarea的v-model支持[“lazy”修饰符](https://vuejs.org/v2/guide/forms.html#lazy)

 x-input与x-textarea能否也支持lazy修饰符？

按照v-model关于lazy修饰符的说明，当使用v-model.lazy的时候，监听事件由原先的"input"变为“change”。所以按理之需要在blur的时候抛出"change"事件。但是我试了一下，不work，请问vux改造过v-model的行为吗？我找不到相关代码。

**Comment by airyland** [comment]
x-input  和 x-textarea 都是封装组件，.lazy 参数无法应用在封装组件上且也并不能透传到内部的 input 和 textarea。如果直接为内部 input 和 textarea 使用 .lazy，又不能符合不需要 .lazy 用户的需求。目前你只能直接使用 @on-blur 事件来处理。
