### ISSUE TITLE
$vm.$el.querySelector is not a function

### ISSUE THREAD

**Issue by jinchaoxiang** [airyland/vux#1206]
### Version
vux 2.1.1-rc.14
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```
import  { AlertPlugin } from 'vux'
Vue.use(AlertPlugin)
              this.$vux.alert.show({
                title: 'Vux is Cool',
                content: 'Do you agree?'
              })
### Steps to reproduce the problem
Uncaught TypeError: $vm.$el.querySelector is not a function

**Comment by jinchaoxiang** [comment]
vendor.js:1360 [Vue warn]: Property or method "$t" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <Root>)1.warn @ vendor.js:13601.warnNonPresent @ vendor.js:2269get @ vendor.js:2310module.exports.render @ rlstudy.js:29610Vue._render @ vendor.js:4405updateComponent @ vendor.js:2958get @ vendor.js:3267Watcher @ vendor.js:3250mountComponent @ vendor.js:29621.Vue$3.$mount @ vendor.js:80421.Vue$3.$mount @ vendor.js:10091Vue._init @ vendor.js:4558VueComponent @ vendor.js:4712install @ rlstudy.js:78355Vue.use @ vendor.js:4660(anonymous function) @ rlstudy.js:10068__webpack_require__ @ vendor.js:692fn @ vendor.js:111(anonymous function) @ rlstudy.js:79615__webpack_require__ @ vendor.js:692webpackJsonpCallback @ vendor.js:24(anonymous function) @ rlstudy.js:1
vendor.js:1360 [Vue warn]: Error in render function: 
(found in <Root>)1.warn @ vendor.js:1360handleError @ vendor.js:2245Vue._render @ vendor.js:4407updateComponent @ vendor.js:2958get @ vendor.js:3267Watcher @ vendor.js:3250mountComponent @ vendor.js:29621.Vue$3.$mount @ vendor.js:80421.Vue$3.$mount @ vendor.js:10091Vue._init @ vendor.js:4558VueComponent @ vendor.js:4712install @ rlstudy.js:78355Vue.use @ vendor.js:4660(anonymous function) @ rlstudy.js:10068__webpack_require__ @ vendor.js:692fn @ vendor.js:111(anonymous function) @ rlstudy.js:79615__webpack_require__ @ vendor.js:692webpackJsonpCallback @ vendor.js:24(anonymous function) @ rlstudy.js:1
vendor.js:2249 TypeError: _vm.$t is not a function(…)
还有这个问题 vux-loader里已经加入    {
      name: 'i18n',
      vuxStaticReplace: true,
      vuxLocale: 'en'
    }

**Comment by airyland** [comment]
按照文档写的方法重装依赖试试。

**Comment by jinchaoxiang** [comment]
用的是npm 也试过重装了

**Comment by jinchaoxiang** [comment]
求大神解答下

**Comment by airyland** [comment]
没有思路，你得建个简单的 repo 来重现。

**Comment by jinchaoxiang** [comment]
请问怎么建repo

**Comment by jinchaoxiang** [comment]
那$vm.$el.querySelector is not a function有遇到过吗

**Comment by airyland** [comment]
是让你建个可以重现的版本库发个链接上来。不然猜不出问题。

**Comment by jinchaoxiang** [comment]
您好 之前是我把plugins错写成plugin了 改成这正确的之后 webpack构建的时候报ERROR in ./~/vue-loader/lib/template-compiler?{"id":"data-v-2c7e5590","preserveW
hitespace":false}!./~/vux-loader/src/template-loader.js!./~/vue-loader/lib/selec
tor.js?type=template&index=0!./src/components/empty/empty.vue
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at D:\work\egg-example\rl-study\node_modules\vux-loader\src\template-loader.
js:147:29
    at Array.forEach (native)
    at Object.module.exports (D:\work\egg-example\rl-study\node_modules\vux-load
er\src\template-loader.js:123:18)
 @ ./src/components/empty/empty.vue 9:2-269
 @ ./~/buble-loader!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selec
tor.js?type=script&index=0!./src/components/main/elective.vue
 @ ./src/components/main/elective.vue
 @ ./~/buble-loader!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selec
tor.js?type=script&index=0!./src/components/tab.vue
 @ ./src/components/tab.vue
 @ ./src/router/index.js
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3001 webpack/hot/dev-server
./src/app.js

**Comment by jinchaoxiang** [comment]
import  empty  from 'components/empty/empty.vue'
貌似我自己引入自己的组件都报错了 用了vux-loader的plugins后

**Comment by airyland** [comment]
建议你直接用 vux2 模板吧。看你描述根本猜不出问题。
