### ISSUE TITLE
x-number 组件提示$t未定义

### ISSUE THREAD

**Issue by esioncao** [airyland/vux#1207]
vux 版本号2.1.1-rc.14

报错提示如下截图

![Uploading image.png…]()

**Comment by airyland** [comment]
![image](https://cloud.githubusercontent.com/assets/559179/24699145/a04061ae-1a25-11e7-961d-f0e177c40218.png)

**Comment by Jesonhu** [comment]
@esioncao  这个问题解决了吗，我就是用官网的方法也遇到了这个问题

**Comment by esioncao** [comment]
@Jesonhu  解决了 根据 airland 的回答用npm 从新下载包 问题解决了
