### ISSUE TITLE
Vux2.2.0版本 脚手架构建错误，提示文件缺失

### ISSUE THREAD

**Issue by YoRolling** [airyland/vux#1214]
### Windows
`package.json` 中声明依赖为 `"vux": `"^2.1.1-rc.11"`，通过 `npm up` 之后为 `2.2.0`，在运行 `npm run dev` 时候出现构建错误。

错误信息如下：

>  ERROR  Failed to compile with 1 errors                                                                     16:46:52
> This relative module was not found:
> \* ./src/plugins/title/index.js in ./~/vux/index.js
> Listening at http://localhost:8080

通过进入`Vux` 目录中查找并未发现 `title` 目录文件。 而将 `index.js` 文件中的  一下两处注释之后则构建通过

    L104      import TitlePlugin from './src/plugins/title/index.js'
    L230      TitlePlugin,

麻烦确认一下是否是我本地的代码出现问题抑或提交时候少文件了。tks！

**Comment by airyland** [comment]
vux/index.js 这个文件仅用于 IDE 提示，正常来说是不会被调用的。

**Comment by airyland** [comment]
刚试了下，并不能重现，建议删除 node_modules 重装依赖。

**Comment by YoRolling** [comment]
OK ,tks,我试下先。

**Comment by linyasa** [comment]
我也遇到这个问题。 

补充下，好像是windows下系统 才会出现这个问题。 

@YoRolling 请问你的问题解决了吗？

**Comment by crper** [comment]
+1 window必然报这个错，其他系统不会(mac)

**Comment by crper** [comment]
@airyland

**Comment by YoRolling** [comment]
@linyasa  按照作者说的 删除Node_modules 目录重新安装就解决了 。。。

**Comment by crper** [comment]
@YoRolling   不管是原生的npm 还是cnpm，还是yarn都试过了。。依旧报这个错。。win10

**Comment by YoRolling** [comment]
@crper  昨天按照作者的说法，我把node_modules 目录全部删掉了 然后通过`npm i` 重新安装依赖，之后再次构建就OK了。

你尝试一下 清理一下npm 的缓存之后再重装。看是否成功。

BTW：我手边没Mac，无法判别是否只是Windows 系统上存在这个问题。

**Comment by linyasa** [comment]
@YoRolling  好的，我试试。

**Comment by airyland** [comment]
@crper @linyasa 这个问题我一直没有遇到过所以没有去看具体原因。可以完整打包一份到我邮箱，我研究看看是什么问题。i#mao.li

**Comment by linyasa** [comment]
@airyland  已经发送一个demo。

**Comment by airyland** [comment]
如果是直接使用 vue 的 webpack 模板当然会报错了。。
文档已经写得很清楚了，必须配合 vux-loader。
不想使用 vux2 模板怎么配置也有，按照文档来。
