### ISSUE TITLE
没有配置 i18n 的情况下 组件内的 $t 在开发环境下报错

### ISSUE THREAD

**Issue by josephvong** [airyland/vux#1216]
### Version
版本号如下： 
    "vuex": "^2.2.1",
    "vuex-i18n": "^1.3.3",
    "vux": "^2.1.1-rc.5",
    "vux-loader": "^1.0.45",
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 
webpack.base.conf 配置文件中，没有配置i18n 的插件：
module.exports = vuxLoader.merge(webpackConfig,{
  options:{},
  plugins:[
    {name:'vux-ui'},
  ]
})
在调用 vux 组件 如 x-header 时，控制台报错如下：
Property or method "$t" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <XHeader> at F:\joseph\envir\vue\project\MyVueCase\node_modules\.2.2.0@vux\src\components\x-header\index.vue)
 
``` html
<!--put your code here-->
```

**Comment by airyland** [comment]
https://vux.li/#/?id=%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
