### ISSUE TITLE
使用datatime组件弹出时不显示时间

### ISSUE THREAD

**Issue by Pasoul** [airyland/vux#1218]
问题：点击group组件，可以正确弹出，但是datetime组件里面的时间不显示，只显示上方的cancle和ok字段

### Your Codes 
`<template>`
 `   <div class="cell">`
 `        <group> `
              `<datetime v-model="value1" @on-change="change</datetime>`
           `</group>`
     `</div>`
`</template>`
`import { Datetime,Group } from 'vux'`
`export default { `
` components:{`
 `    Datetime,`
  `  Group`
 `},`
` data () {`
	`return {`
	      	`value1: "2015-12-15"`
	`}`
` },`
`methods: {`
    ` change (value) {`
	     ` console.log('change', value)`
    `}`
 `}`
`}`

```

### Expected behavior and actual behavior.

### Steps to reproduce the problem

**Comment by Pasoul** [comment]
补充一下，我是在微信浏览器运行的，在谷歌浏览器调试运行没问题

**Comment by airyland** [comment]
描述下什么是 “不显示时间”？
至少我看到的是标签不全 `<datetime v-model="value1" @on-change="change</datetime>`

另外格式化不是这么格式化的啊。

**Comment by Pasoul** [comment]
不好意思，我刚学会格式化
重新描述不显示时间：弹出来的时间选择器只有取消和确认这两个字样，下方的时间全部都是空白，这是我用草料二维码生成器，把当前的网页生成一个二维码，然后再微信浏览器打开，出现这样的情况，在本地谷歌浏览器上面浏览是没有问题的，下面的时间显示出来了，也可以进行选择。
```
`<template>
	<div class="cell">
		<group>
	      <datetime title="生日*" v-model="value" @on-change="showBirthady" confirm-text="确认" cancel-text="取消"></datetime>
	    </group>
	</div>
</template>
<script>
import { Datetime,Group } from 'vux'
export default {
	components: {
		Datetime,
		Group
	},
	data () {
		return {
			value:'',
		}
	},
	methods : {
		showBirthady (value) {
			console.log(value)
		}
	}
}
</script>`
```

**Comment by airyland** [comment]
无法重现。补充下被你直接忽略掉的 issue template 需要的信息再 reopen 当前 issue吧。

**Comment by Pasoul** [comment]
谢谢，找到原因了，一个是scroller-mask的z-index低的原因，第二个就是flex布局微信浏览器不认识，我改成了box布局

**Comment by airyland** [comment]
flex 布局微信是支持的，你大概要看看 autoprefix 配置。
