### ISSUE TITLE
badge 动态绑定后，红色圆圈不再是正圆？

### ISSUE THREAD

**Issue by bulolo** [airyland/vux#1223]
当不是动态绑定的时候：
![image](https://cloud.githubusercontent.com/assets/10026498/24823248/dace497a-1c2e-11e7-90aa-289bd329fc4b.png)
```
<badge text="2"></badge>
```
动态绑定的时候：
![image](https://cloud.githubusercontent.com/assets/10026498/24823253/e8f5483c-1c2e-11e7-92f8-3c889e3267a6.png)
```
<badge :text="cart.items.length"></badge>
```

很奇怪，为何红色圆圈不再正圆？

**Comment by airyland** [comment]
数字类型有逻辑问题。
当前版本你可以转为字符串 `:text="cart.items.length + ''"`
