### ISSUE TITLE
XNumber 的意见

### ISSUE THREAD

**Issue by bulolo** [airyland/vux#1224]
![image](https://cloud.githubusercontent.com/assets/10026498/24824191/b3ba7c72-1c39-11e7-94b3-5316ec1a4302.png)
```
 <x-number title="title" v-model="value"></x-number>
```
目前XNumber的使用发现，XNumber是始终类似 cell的样式，带有一长条，而一般使用场景只需要后面红色框的数量选择器，而并没办法单独使用这个数量选择器。
是否能改进

**Comment by airyland** [comment]
暂不支持，可以 pr
