### ISSUE TITLE
iconfont不能正常显示的问题

### ISSUE THREAD

**Issue by lavyun** [airyland/vux#1227]
所有iconfont均显示为一个方框框

vux用yarn安装的，版本号为2.2.0

vux-loader配置：

```js
module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [{
    name: 'vux-ui'
  },{
    name: 'less-theme',
    path: 'src/assets/css/theme.less'
  }]
})
```

![image](https://cloud.githubusercontent.com/assets/22797898/24827051/3202c774-1c76-11e7-8100-267e146301c1.png)

**Comment by airyland** [comment]
原因应该是你自己把样式重置了。
检查下 i 标签的 font 

![image](https://cloud.githubusercontent.com/assets/559179/24828167/2169acac-1c8a-11e7-9053-8e95e4e4fdae.png)
