### ISSUE TITLE
Scroller组件报错：TypeError: Cannot assign to read only property 'isFunction' of object '#<Object>'

### ISSUE THREAD

**Issue by MallTo-Silence** [airyland/vux#1229]
通过按需加载组件import到页面中，出现TypeError: Cannot assign to read only property 'isFunction' of object '#<Object>'的错误。
![c5d3b801-4484-41b0-9665-17b1f5e4b4c7](https://cloud.githubusercontent.com/assets/16772834/24827547/6e967dcc-1c7e-11e7-956f-4cf7fb117677.png)

vue版本：2.0
vux版本：2.2.0

``` html
<template lang="html">
  <div class="record">
    <scroller>
      <div></div>
    </scroller>
  </div>
</template>

<script>
import Scroller from 'vux/src/components/scroller';

export default {
  components: {
    Scroller,
  },
  data() {
    return {};
  },
};
</script>
```

**Comment by airyland** [comment]
并不能重现。建议你按照 vux2 模板来初始化。或者建个 repo 以方便重现。
