### ISSUE TITLE
从vux导入XInput，input组件不能正常使用

### ISSUE THREAD

**Issue by susan-github** [airyland/vux#123]
**Version 0.0.103**

**PC chrome**

组件不是分开导入，而是从vux import的话，XInput还有其他一些组件没办法用，是我打开方式有问题么？XButton又是可以的`
**js**
```
<script>
    import { Group, Cell, XButton, XInput } from 'vux'
    export default {
        name: 'HomeView',
        components: {
            Group,
            Cell,
            XButton,
            XInput
        }
    }
</script>
```
**html**
```
<template>
    <div>
        <group>
            <cell title="vue" value="cool"></cell>
            <x-button type="primary">primary</x-button>
        </group>
        <x-input title="message" placeholder="I'm placeholder"></x-input>
    </div>
</template>
```
**Chrome error log**
vue.common.js?e881:987 [Vue warn]: Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by airyland** [comment]
:sweat: issue template 里的提示都被忽略了。请至少说明版本号，代码放在 ``` html 里！

**Comment by airyland** [comment]
try updating vux to the latest.

**Comment by susan-github** [comment]
我的错，我的错~~~表示不太会用这个:laughing:

**Comment by susan-github** [comment]
可以啦可以啦！:thumbsup: :dancers:

**Comment by nian1123** [comment]
如何解决呀

**Comment by susan-github** [comment]
很早之前用的，印象里，是升级一下vux就好了，你使用的是什么版本？ @nian1123
