### ISSUE TITLE
popup问题

### ISSUE THREAD

**Issue by sixiakun** [airyland/vux#1232]
###vux 2.1.1-rc.14
我在弹出组件中又弹出了一个组件，结果点击遮罩层两个弹出框都会关闭，请问支持点击时只关闭一个吗

**Comment by sixiakun** [comment]
意思就是我使用了两个popup呗，结果点击遮罩层两个popup都会关闭。。

**Comment by sixiakun** [comment]
我自己搞下好了 这个场景也不常见

**Comment by sixiakun** [comment]
不行呀哥，调用两个popup，原来共用一个遮罩层。。

**Comment by sixiakun** [comment]
看了下你的实现，我采用动态修改hideOnBlur也不行，因为你这个没有一直监听，得重新生成实例才行。。

**Comment by airyland** [comment]
不清楚你的具体场景，如果 popup 满足不了，建议自行根据需要实现。

**Comment by sixiakun** [comment]
恩，自己加了层遮罩控制下
