### ISSUE TITLE
代码报错缺少文件 (ScriptLoaderPlugin和IndexBar)

### ISSUE THREAD

**Issue by mymmoonoa** [airyland/vux#1234]
### 我已经下载源码检查确认了

/index.js line89  import ScriptLoaderPlugin from './src/plugins/script-loader/index.js' 在对应目录下文件没有提交
/index.js line58 import IndexBar from './src/components/index-bar/index.vue' 也找不到对应文件

yarn更新到 vux2.2.1-rc.2有同样问题

@airyland

**Comment by airyland** [comment]
try rc.3
