### ISSUE TITLE
关于Xinput内置验证valid的问题

### ISSUE THREAD

**Issue by howyhuang** [airyland/vux#1235]
版本："vux": "^2.2.1-rc.1"

当启用了is-type，此时input值为空的时候valid的值是true，感觉开启验证时input值为空或错误 valid的值都返回false
![image](http://olkv99nmi.bkt.clouddn.com/error/WechatIMG6.jpeg)
![image](http://olkv99nmi.bkt.clouddn.com/error/WechatIMG12.jpeg)
![image](http://olkv99nmi.bkt.clouddn.com/error/WX20170410-221538@2x.png)
![image](http://olkv99nmi.bkt.clouddn.com/error/WX20170410-221733@2x.png)

**Comment by muei** [comment]
加入`required`属性
