### ISSUE TITLE
postcss-import 作用到了previewer, 导致css-loader报错

### ISSUE THREAD

**Issue by evanyangg** [airyland/vux#1238]
错误是这样的:
```
Module build failed: Error: Failed to find '~photoswipe/dist/photoswipe.css'
    in [ 
        /Users/sun/Documents/jujiang/shop/node_modules/vux/src/components/previewer
    ]
    at /Users/sun/Documents/jujiang/shop/node_modules/postcss-import/lib/resolve-id.js:61:11
```
我查看了一下previewer的源码,在style这块是这样的:
```
<style>
@import '~photoswipe/dist/photoswipe.css';
@import '~photoswipe/dist/default-skin/default-skin.css';
</style>
```
这里您引入了两个css,并且默认了css-loader,因为我的项目里面默认postcss去解析css的,所以这里的@import 被认为是postcss-import中的, 导致引入失败.
我看您用了photoswipe组件,并引入了对应的css.
所以现在基本确定是postcss-import 扫到node_modules中的文件了,
这个是在vux源码通知 还是控制postcss-import呢?

**Comment by airyland** [comment]
看得不大明白，phontoswipe 本来就是在 node_modules 里。
这个问题是构建问题和 vux 组件无关。
另外看你描述我也不知道你是如何配置，建议上个可以重现的 repo 链接。

**Comment by evanyangg** [comment]
<img width="662" alt="default" src="https://cloud.githubusercontent.com/assets/22952321/24903457/13240c66-1ee0-11e7-8943-d82f00ab15f5.png">
<img width="504" alt="default" src="https://cloud.githubusercontent.com/assets/22952321/24903548/502798ee-1ee0-11e7-93f6-bde255d39e7f.png">
这里是关于postcss-import的一个说明
# Options
### -root
`
Type: String
Default: process.cwd() or dirname of the postcss from
Define the root where to resolve path (eg: place where node_modules are). Should not be used that much.
Note: nested @import will additionally benefit of the relative dirname of imported files.
`
### 具体地址在这里https://github.com/postcss/postcss-import
### 应该是previewer里面的style 默认lang为css 所以走了postcss-import,如果限定lang="less" 应该不会走postcss了
#### 不知道您在style中的@import 是css的 import  还是less的import, 不清楚区别在哪里.
vux的配置是没问题的.

**Comment by evanyangg** [comment]
@airyland 请您帮我看一看

**Comment by airyland** [comment]
抱歉，因为不是 vux 本身的问题，建议到 vue 相关 repo 提问 https://github.com/vuejs-templates/webpack

如果没有不得不这样配置的理由，直接使用 vux2 模板吧。

**Comment by ccode-code** [comment]
~ 前缀的路径有问题，不能配合postcss-import

vux库less文件没有添加css3前缀，我们采用postcss-import插件自动添加。

但是postcss-import和vux 的@import "~/**/*"  冲突，不能正确找到文件


为什么不  @import "photoswipe/**/*"  这样子导入文件呢

@airyland

**Comment by airyland** [comment]
@imcoka 这样写会找不到文件，`css-loader` 要用 ~ 来标识去 node_modules 里找。

**Comment by ccode-code** [comment]
明白了，非常感谢

**Comment by ccode-code** [comment]
@evanyangg    把 postcss-import 换成 postcss-easy-import 解决

**Comment by fdjiangwu** [comment]
@evanyangg 请问下这个问题最后是怎么解决的？
