### ISSUE TITLE
Select组件的一些建议

### ISSUE THREAD

**Issue by ruiyong-lee** [airyland/vux#1239]
截图：
![image](https://cloud.githubusercontent.com/assets/12726826/24903644/95d74a1a-1ee0-11e7-8a64-3d68c20f327a.png)

其实和组件本身没太大关系，我的意思只是页面上，左边label区域和右边的输入、点击区域不能很好的区分开来，用户会有疑惑。

**Comment by airyland** [comment]
你是第一个提这个问题的。。我大概理解你的意思，默认 105px 占据了比较大的空间，而 label 可能只有两个字。你的建议是？

事实上 select 在 iOS 上存在一些问题，可能会考虑封装一个新的 popup-selector 组件来代替原生组件。

**Comment by agileago** [comment]
@lry210  难道开发的时候不考虑适配屏幕么？ 我一般都会在页面上加上 
```html
<meta name="viewport" content="width=375, user-scalable=no">
```
来做适配的，设计图是多少就写多少px

**Comment by ruiyong-lee** [comment]
@airyland 我的意思不是默认105px 太大，我的label也是4个字，屏幕小也是我举得例子，以为会更好理解，却误导了上面的朋友，给一个客户用，5.7寸华为手机，他也是拼命点左边的label，发现点不开下拉，我是开发者的角度我当然知道要点右边区域，但是他们客户的角度一进去，狂点左边是很有可能的，至少我碰到很多，我现在改成placeholder了，这样整行都能点击，缺点是标题没了。
**总结：其实和组件本身没太大关系，我的意思只是页面上，左边label区域和右边的输入、点击区域不能很好的区分开来，用户会有疑惑。**

**Comment by airyland** [comment]
@lry210 明白了，但是在保留标题的情况下这个没有解决方法，因为原生的 select 不能通过其他元素来触发打开。可以解决的方式是不使用 selector 而是使用 popup 封装一个 radio，这样整行都可以点击。
