### ISSUE TITLE
可否再添加几个组件

### ISSUE THREAD

**Issue by liniu** [airyland/vux#124]
Cards ，参考http://materializecss.com/cards.html
Collections 参考http://materializecss.com/collections.html
Side-nav 参考http://materializecss.com/side-nav.html 
Collapsible 参考http://materializecss.com/collapsible.html
还有类似 Tags ，Badges ，Select2 等
是不是要求太多:)，只是觉得都是挺实用的，能一套方案解决最好

**Comment by airyland** [comment]
1.Card 似乎不好通用
2.collection 不知道这个应用在哪里
3.select2 这个更适合PC端，移动端这个似乎用处不大

**Comment by liniu** [comment]
card 类似微信的推文 或者产品的展示页面，bootstrap4也加入了这个组件，http://v4.bootcss.com/components/card/
collection 就是bootstrap 的collapse ，运用场景比如只显示条目，而明细的内容折叠起来，不如产品的明细介绍，http://v4.bootcss.com/components/collapse/

**Comment by airyland** [comment]
看了bootstrap4更觉得不能通用了，比较大家的样式布局需求都不一样啊，组件化出来一堆选项，相当于更繁琐了。

**Comment by ericxin1982** [comment]
如果想自定义一个自己需要的组件，如何开始？

**Comment by airyland** [comment]
@ericxin1982 从看vue vue-loader 文档开始

**Comment by airyland** [comment]
@liniu 
Bootstrap偏重于PC, 一些组件不适合手机端，侧边栏和Badge组件在计划中。
其他暂时不考虑。如果有实际使用这些组件的网站或者App可以截个图上来评估一下要不要加。
