### ISSUE TITLE
如何兼容ios8

### ISSUE THREAD

**Issue by yew30** [airyland/vux#1241]
最近实现了一套个人项目，发现其他都很好，除了标题的这一点。
主要情形就是，在ios8.1环境下，所有style为display:flex的显示都不能按心愿所想的那样显示，不过在ios10下却是一切正常的。
查资料发现是flex的兼容性问题。但是如果把所有display:flex;处都补上
“display: box;display: -webkit-box;display: -moz-box;display: -ms-flexbox;”能解决一些问题，但是不能解决全部，比如tab,tabor等组件还是存在错位的问题。
官方是否有比较优美的解决办法？

**Comment by airyland** [comment]
一般配置好 autoprefix  iOS8 问题都可以解决。文档也有注明推荐用什么配置。
