### ISSUE TITLE
已经参照官方文档建议,删除i18n的相关依赖和引入,然后重新npm install 后仍然报$t错误

### ISSUE THREAD

**Issue by Hfengxiang** [airyland/vux#1242]
_node v6.10.2,npm v3.10.10, cnpm v4.5.0_

_以下是程序报的错误日志,程序界面上的表现是Xheader无法显示了_
`
vue.common.js?3b6d:560 [Vue warn]: Error in render function: 
(found in <XHeader> at D:\MobileWeb\CRM_Mobile1\demovux\node_modules\._vux@2.2.1-rc.3@vux\src\components\x-header\index.vue)
warn @ vue.common.js?3b6d:560
handleError @ vue.common.js?3b6d:1445
Vue._render @ vue.common.js?3b6d:3611
updateComponent @ vue.common.js?3b6d:2158
get @ vue.common.js?3b6d:2469
run @ vue.common.js?3b6d:2539
flushSchedulerQueue @ vue.common.js?3b6d:2331
(anonymous) @ vue.common.js?3b6d:507
nextTickHandler @ vue.common.js?3b6d:456
vue.common.js?3b6d:1449 TypeError: _vm.$t is not a function
    at Proxy.render (eval at <anonymous> (app.js:4293), <anonymous>:23:76)
    at VueComponent.Vue._render (eval at <anonymous> (app.js:723), <anonymous>:3609:22)
    at VueComponent.updateComponent (eval at <anonymous> (app.js:723), <anonymous>:2158:21)
    at Watcher.get (eval at <anonymous> (app.js:723), <anonymous>:2469:25)
    at Watcher.run (eval at <anonymous> (app.js:723), <anonymous>:2539:22)
    at flushSchedulerQueue (eval at <anonymous> (app.js:723), <anonymous>:2331:13)
    at Array.eval (eval at <anonymous> (app.js:723), <anonymous>:507:20)
    at nextTickHandler (eval at <anonymous> (app.js:723), <anonymous>:456:16)
handleError @ vue.common.js?3b6d:1449
Vue._render @ vue.common.js?3b6d:3611
updateComponent @ vue.common.js?3b6d:2158
get @ vue.common.js?3b6d:2469
run @ vue.common.js?3b6d:2539
flushSchedulerQueue @ vue.common.js?3b6d:2331
(anonymous) @ vue.common.js?3b6d:507
nextTickHandler @ vue.common.js?3b6d:456
localhost/:1 GET http://localhost:8080/__webpack_hmr net::ERR_CONNECTION_RESET
:8080/__webpack_hmr:1 GET http://localhost:8080/__webpack_hmr net::ERR_CONNECTION_REFUSED
:8080/__webpack_hmr:1 GET http://localhost:8080/__webpack_hmr net::ERR_CONNECTION_REFUSED
:8080/__webpack_hmr:1 GET http://localhost:8080/__webpack_hmr net::ERR_CONNECTION_REFUSED
:8080/__webpack_hmr:1 GET http://localhost:8080/__webpack_hmr net::ERR_CONNECTION_REFUSED
:8080/__webpack_hmr:1 GET http://localhost:8080/__webpack_hmr net::ERR_CONNECTION_REFUSED
:8080/__webpack_hmr:1 GET http://localhost:8080/__webpack_hmr net::ERR_CONNECTION_REFUSED`

_事情的经过是这样的:之前代码一直没问题也没有重装依赖,但是XAddress的确认与取消提示文本是英文的,初步断定是i18n的问题,于是删除了这个依赖和相关的引用然后重新npm install,结果报了一堆错,提示fsevents安装跳过的警告,以及node-pre-gyp ERR!相关的错误,没有理会它,直接npm run dev结果程序崩了提示相关的依赖没有找到,但是斌没有提示是哪个依赖,然后看了官方的pakage.json将vux和vux-loader改为最新版本再删除node_moduals重新npm install让然报错,在github npm上找了一堆的方案都没解决,后来重装了node也没有,最后又回到官方的pakag.json发现官方多了一个 ```
"peerDependencies": {
    "vux-loader": "^1.0.50"
  } 的依赖,我在项目中加了这个依赖最终程序通过了编译,但是报了现在的这个bug
```_

**Comment by airyland** [comment]
保留最简单代码建个可以重现的 repo。不然难以解决问题。
