### ISSUE TITLE
建议升级weixin-jssdk

### ISSUE THREAD

**Issue by evanyangg** [airyland/vux#1244]
咱们vux提供了weixin-js-skd的引入,但是发现这个weixin-js-sdk还是1.0.0的.
现在官网已经1.2.0了 , 为了更好的开发 希望您升级一下jssdk版本
https://mp.weixin.qq.com/wiki
谢谢

**Comment by airyland** [comment]
哪里看到是 1.0.0? 

https://github.com/airyland/vux/blob/v2/package.json#L59

**Comment by evanyangg** [comment]
sorry 看错了.weixin-js-sdk 我以为是github上面的那个项目
