### ISSUE TITLE
swipeout和group-cell结合的问题

### ISSUE THREAD

**Issue by yuch321** [airyland/vux#1246]
第一次使用vux,需要swipeout结合group-cell做一个滑动的事件，正常情况下需要在每个cell后都有自己的一个滑动事件.但是结果变成这样了.
http://img.bbs.csdn.net/upload/201704/11/1491899852_63950.png
代码如下:

>  <group >
        <swipeout>
            <swiperout-item   :right-menu-width="240" :sensitivity="15">
                <div slot="right-menu">
                    <swipeout-button  @click.native="deleteClick(item.id)" type="warn">删除</swipeout-button>
                    <swipeout-button  @click.native="setTopClick(item.id)" type="default">置顶</swipeout-button>
                </div>
                    <cell slot="content"  v-for="item in list" :title="item.title"
                           :inline-desc="item.publishTime"
                           is-link>
                        <span slot="after-title" class="icon-font new-icon"  v-if="item.isNew==true">&#xe667;</span>
                        
                    </cell>
            </swiperout-item>
        </swipeout>
    </group>

后来检查一下，以为自己粗心了，应该把right-menu放在cell里面，所以修改了一下如下：

>  <group >
        <swipeout>
            <swiperout-item   :right-menu-width="240" :sensitivity="15">
                   <cell slot="content"  v-for="item in list" :title="item.title"
                           :inline-desc="item.publishTime"
                           is-link>
                        <span slot="after-title" class="icon-font new-icon"  v-if="item.isNew==true">&#xe667;</span>
                      <div slot="right-menu">
                          <swipeout-button  @click.native="deleteClick(item.id)" type="warn">删除</swipeout-button>
                          <swipeout-button  @click.native="setTopClick(item.id)" type="default">置顶</swipeout-button>
                      </div>
                  </cell>
            </swiperout-item>
        </swipeout>
    </group>

但是改完后发现，已经无法滑动。想请教一下,swiperout和group-cell该怎么结合。感激不尽

**Comment by airyland** [comment]
你这明显理解错误，一个 swiper-item 内就应该是只一个  cell。
组件开发时是想脱离 cell 使用的，和 cell 一起要做一些适配。

**Comment by yuch321** [comment]
可以问一下要做哪些适配吗？因为是第一次使用，我看那个Swipeout的demo源码里好像没有，所以才来问一下。谢谢了

**Comment by yuch321** [comment]
自己摸索出来了，谢谢作者！

**Comment by liaocaiming** [comment]
swipeout的x-button如果是一个删除功能,   删除后按钮无法自动回去

**Comment by liaocaiming** [comment]
swipeout的swipeout-button如果是一个删除功能, 删除后按钮无法自动回去

**Comment by airyland** [comment]
@liaocaiming 请不要在不相关 issue 下提另一个问题，这类问题会被直接删除。

**Comment by PlusLius** [comment]
可以问一下怎么解决的吗?我也遇到了这样的问题

**Comment by yuch321** [comment]
@PlusLius  把v-for写在swiperout-item里

**Comment by PlusLius** [comment]
可以问下cell的箭头怎么控制让他上下翻转吗？
