### ISSUE TITLE
Range组件，maxValue设置过大后导致step失效！

### ISSUE THREAD

**Issue by InvictusNightmares** [airyland/vux#1248]
在开发过程中，把range的maxValue设置过大，step就不起效果。
@airyland 
如图我设置的minValue为100，maxValue为13000
<img width="761" alt="2017-04-12 2 42 38" src="https://cloud.githubusercontent.com/assets/15864222/24946655/2e94ac7e-1f96-11e7-9f3e-8771b35bc5b2.png">
<img width="355" alt="2017-04-12 2 44 14" src="https://cloud.githubusercontent.com/assets/15864222/24946669/364e7d8c-1f96-11e7-9698-57622eee3d65.png">

**Comment by airyland** [comment]
确定组件宽度是否在拖动过程中发生了变化。

**Comment by InvictusNightmares** [comment]
没有，range的宽度就是默认的100%。

**Comment by InvictusNightmares** [comment]
我在vuxDemo项目里面改了，也是同样的问题。
<img width="866" alt="2017-04-12 4 38 28" src="https://cloud.githubusercontent.com/assets/15864222/24948986/b1e5afa8-1f9e-11e7-8a1f-dbc70a3eb5ed.png">
<img width="375" alt="2017-04-12 4 38 17" src="https://cloud.githubusercontent.com/assets/15864222/24949009/c2d7a456-1f9e-11e7-9f84-afeca148631c.png">

**Comment by airyland** [comment]
demo 里不一样，因为左边 value is 那一行变大时导致右边宽度会发生变化。

**Comment by InvictusNightmares** [comment]
解决了，谢谢！

**Comment by liuestc** [comment]
@InvictusNightmares 怎么解决的，我也遇到了相同问题，拖动会不精准，不按step来

**Comment by liuestc** [comment]
```
<cell title="价格" :inline-desc="'预定天数: '+data" primary="content">
        <range v-model="data" :min="100" :max="800" :step="100"></range>
</cell>
```
但滑动不是按整百来的

左边value我设置了固定宽度还是不行，怎么破？

**Comment by airyland** [comment]
@liuestc 看你写的代码， inline-desc 宽度你确定不会随着 data 变化么

**Comment by InvictusNightmares** [comment]
@liuestc  把你的range宽度也固定一下。
