### ISSUE TITLE
Tab 可否增加一个左侧位置模式

### ISSUE THREAD

**Issue by liniu** [airyland/vux#125]
Tab 可否增加一个左侧位置模式，适应于类别比较多的情况，比如点餐网站

**Comment by airyland** [comment]
上个示意图

**Comment by airyland** [comment]
这个布局不是tab, 你需要的是不是这个
https://vux.li/#!/component/scroller/full

**Comment by liniu** [comment]
对，就是这个，太好了，我还以为是个tab，谢谢您。
