### ISSUE TITLE
VUX+vue-cli 打包出来非常大，很多没用到的组件被打包进JS

### ISSUE THREAD

**Issue by xuyangqiao** [airyland/vux#1251]
VUX版本："^2.1.1-rc.6"
"vue": "^2.2.1"

打包后app.js，和vendor.js体积非常大，没有使用图片预览和ｓｃｒｏｌｌ组件，地址组件，但是ＪＳ中存在相关代码

上一张分析图
http://i4.buimg.com/567571/5401f42d080057a5.png

如图，为什么会打包进入２个地址2个地址JSON，还有图片预览JS。

**Comment by airyland** [comment]
要么没有配置 vux loader 要么依赖安装出错。

**Comment by liyahui** [comment]
按照官网配置了vux loader，没有用到地址选择，为什么打包后的js有大量地址数据？

**Comment by airyland** [comment]
整个 VUX 都打包进去了，说明配置错了。上个可以重现的 repo 链接或者自行排查。

**Comment by xuyangqiao** [comment]
在win10系统下，非常容易失败，用的vux2模板，不做任何修改，安装依赖也很容易报错，我至少安了十多遍，把代码一个一个文件拷过来，心累啊。。。npm淘宝链接，翻墙用原生的地址都是同样的。
