### ISSUE TITLE
建议Checklist和Radio增加disabled属性

### ISSUE THREAD

**Issue by lmasdata** [airyland/vux#1254]
建议Checklist和Radio增加disabled属性
业务场景：用于问卷调查，已经填写后的展示

![image](https://cloud.githubusercontent.com/assets/8501594/24988594/8ad5ea2c-2039-11e7-94d4-b60b781c3273.png)

**Comment by evenlai** [comment]
您好！checklist组件目前的禁用逻辑是this.currentValue.indexOf(key) === -1 && this.currentValue.length === this._max，能否增加属性控制组件完全不能修改选项的选中状态（与选中数和最大选中数无关）？谢谢！
