### ISSUE TITLE
打包后发现用了scroller的页面都会有一个hammerjs。

### ISSUE THREAD

**Issue by w2819** [airyland/vux#1255]
如题，可以配置只引用一次么，这样可以减小包的整体大小

**Comment by airyland** [comment]
？ 一个组件无论引用多少次打包时只会打包一次。但是如果你使用了代码分割，每个页面分别引入，那么会被打包多次。如果你是这种情况，你可以在 main.js 里全局注册，不再在单独路由里再引入。
