### ISSUE TITLE
npm run build 报Module build failed: Can't resolve '../../styles/1PX.less' 错误

### ISSUE THREAD

**Issue by w2819** [airyland/vux#1256]
npm run dev运行没有问题，run build以后会报这个错

` throw new Error("Module build failed: Can't resolve '../../styles/1PX.less' in '/node_modules/vux/src/components/popup-picker'\n @ /vux/src/components/popup-picker/index.vue (line 205, column 0)\n near lines:\n   @import '../../styles/variable.less';\n   @import '../../styles/1PX.less';\n   ")`

**Comment by airyland** [comment]
源码看不到你贴的 1PX.less，确定你本地是大写路径？

https://github.com/airyland/vux/blob/v2/src/components/popup-picker/index.vue#L210

**Comment by w2819** [comment]
哦，我用了“after-less-parser”和“style-parser”这两个vuxLoader工具导致的

**Comment by airyland** [comment]
try  

.replace(/px(?!\.less)/gi, 'PX')

**Comment by w2819** [comment]
好的谢谢
