### ISSUE TITLE
CheckIcon 这个组件怎么用

### ISSUE THREAD

**Issue by BarryZhan** [airyland/vux#1257]
业务上只是想用check图标做选择和全选，其他的checkList之类的都太复杂了，偶然发现有CheckIcon这个组件。
![image](https://cloud.githubusercontent.com/assets/11763811/24994899/637a07f8-205f-11e7-966f-bc13bc747c80.png)
样式上是没有什么问题的，但是选择以后会报错
![image](https://cloud.githubusercontent.com/assets/11763811/24994928/82fb6f68-205f-11e7-8937-b7192ffc3619.png)

**Comment by BarryZhan** [comment]
感觉好多表单组件都不能单独开来，比如xNumber 必须要在group里用。但是我想要的是单独的数量框

**Comment by airyland** [comment]
x-number 即将拆出来。
