### ISSUE TITLE
您好，我想提供一个城市联动的json数据

### ISSUE THREAD

**Issue by lavyun** [airyland/vux#1258]
我在使用城市联动时，花了一点时间整理了一份适配popupPicker的城市三级联动的数据，是国家统计局最新的数据。如果vux需要的话，我可以提供给您。

**Comment by airyland** [comment]
这个 x-address 已经有内置数据，你这个是多了一级？

https://github.com/airyland/china-area-data

**Comment by lavyun** [comment]
抱歉，不知道有这个x-address组件。
