### ISSUE TITLE
rater组件 打包后disabled失效

### ISSUE THREAD

**Issue by fanly** [airyland/vux#126]
rater组件 打包后disabled失效

**Comment by airyland** [comment]
打包工具导致的问题不是vux的问题哦。你试试更新相关的vue-loader等依赖

**Comment by airyland** [comment]
我翻了记录，disabled的问题我一个月前在vue提了issue，是在vue修复，不是在loader修复的 https://github.com/vuejs/vue-loader/issues/182 或许你用的vue是旧版本？
