### ISSUE TITLE
不需要group,只需要一个datepicker,如果调用vux里的日期选择器

### ISSUE THREAD

**Issue by deronendless** [airyland/vux#1260]

**Comment by airyland** [comment]
如果有触发元素，直接使用 slot 覆盖。

``` js
<datetime>
     <x-button>点我弹出</x-button>
</datetime>
```

**Comment by airyland** [comment]
已经支持引入 DatetimePlugin 插件调用，下个版本发布。

**Comment by deronendless** [comment]
项目里自己做了屏幕适配，就是rem，和vux里面的冲突了怎么办呢？

**Comment by airyland** [comment]
不明白冲突什么意思，具体需要 vux 怎么配合可以提出。

**Comment by deronendless** [comment]
就是我的布局是用rem写的，结果引入vux以后，alert组件的样式变得很宽很高，这个原因是由于vux 也是使用rem做的适配，所以造成的，请教该怎么解决这种冲突呢

**Comment by airyland** [comment]
vux 依赖于 WeUI 并没有使用 rem。

**Comment by deronendless** [comment]
我使用rem动态改变了html的fontSize，然后vux 的组件样式就变了。

**Comment by airyland** [comment]
然而 vux 基本是 px 像素，怎么会变 :thinking:

**Comment by airyland** [comment]
你是不是用插件把 vux 的 px 单位转成 rem 了？

**Comment by deronendless** [comment]
没有啊，没用别的插件，如果vux的基本单位是px的话，我再研究下，稍后探讨。
