### ISSUE TITLE
x-switch和confirm冲突问题

### ISSUE THREAD

**Issue by thedayisantherday** [airyland/vux#1262]
当x-switch值改变时，弹出confirm对话框。点击取消按钮，将x-switch的值置为false，问题出现了：x-switch状态改变了，confirm对话框的mask消失，但是confirm对话框未消失。问题已经描述的很清楚了，不用纠结代码

**Comment by airyland** [comment]
1. 提 issue 请正确格式化
2. onCancel 里的 this 指向不对吧？此时 this 已经不是当前 vm了。

**Comment by airyland** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by airyland** [comment]
假如你没有帖代码根本猜不到问题，哪里叫描述得很清楚。
