### ISSUE TITLE
"2.2.1-rc.4"版本 Cell 一直有文字false，要强制赋值value=“”才没有

### ISSUE THREAD

**Issue by huangzhenxian** [airyland/vux#1264]
版本:"vux": "2.2.1-rc.4",
组件:Cell

问题：
更新到2.2.1-rc.4 后，cell组件右边全自带一个false展示 要每个设置 value=“”才可以 ，

![h 4 5p2rx9 s_nxgof22n](https://cloud.githubusercontent.com/assets/8416974/25032892/c10a27da-210a-11e7-83fd-59f9e7a6ce0b.png)

![rx qsfzn f3dy j isq x](https://cloud.githubusercontent.com/assets/8416974/25032894/c2c29d14-210a-11e7-9c88-1676af369b5d.png)

**Comment by airyland** [comment]
昨晚发布失误，没有先合并代码。请更新到 rc.5。
