### ISSUE TITLE
npm run dev报错 ReferenceError: originalConfig is not defined

### ISSUE THREAD

**Issue by zf329398320** [airyland/vux#1266]
const vuxLoader = require('vux-loader')
const webpackConfig = originalConfig // 原来的 module.exports 代码赋值给变量 webpackConfig

module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui']
})

这个 originalConfig   是干什么的？    在哪里引入的？

**Comment by airyland** [comment]
要我们一行一行教你看文档吗？

![image](https://cloud.githubusercontent.com/assets/559179/25034588/3c5288f6-211a-11e7-8c32-74f53f7fb39c.png)

不会配置你用快速入门啊。
