### ISSUE TITLE
XDiaglog组件中不能使用Scroller组件？

### ISSUE THREAD

**Issue by mymmoonoa** [airyland/vux#1267]
@airyland 打扰了

请问下: Xdialog组件中是不是不能直接使用Scroller组件， 我试验了一直有问题，然后看demo/Xdialog样例里，滚动是用的 overflow:scroll样式来实现的。
![image](https://cloud.githubusercontent.com/assets/650114/25040706/ac03b10c-213d-11e7-987a-697fe07ae159.png)

我是不是该放弃Xdialog中使用Scroller的尝试？
我在所有close的问题里搜了下也没找到相关话题，不知道是不是搜索姿势不正确。

**Comment by airyland** [comment]
一个 div 能搞定的事不就要上 scroller 了。

**Comment by mymmoonoa** [comment]
因为我想使用水平Scroller， 所以是暂时用不了的意思吗？

**Comment by airyland** [comment]
水平用 overflow 一样能搞定。暂时来说存在一些问题还没去解决。

**Comment by mymmoonoa** [comment]
好的 多谢指点。

**Comment by airyland** [comment]
这个问题短期内不会去解决，先关闭。
