### ISSUE TITLE
Scroller确实有bug滚动点击触发2次

### ISSUE THREAD

**Issue by shijunti19** [airyland/vux#1268]
最近做完功能突然发现有这个bug
点击一次他就触发2次
Scroller里面循环输出，然后每个item写click事件，事件会触发2次
https://vux.li/demos/v2/#/component/scroller
这个页面你，点击这个按钮，我遨游浏览器触发2次了！
![image](https://cloud.githubusercontent.com/assets/5392211/25041662/0d735522-2144-11e7-937a-e7de271d125c.png)

**Comment by airyland** [comment]
速度解决？你当我客服，欠你的啊？SB。

**Comment by shijunti19** [comment]
我只是急了点又不是骂人的话，我只是急了点，希望你早点看下而已，你这个人态度也太差了吧

**Comment by airyland** [comment]
你没有权力要求我“速度解决”，我也没有义务帮你“速度解决”。

你情商低就别怪我怼你了。

提问题前先学会尊重人。

![image](https://cloud.githubusercontent.com/assets/559179/25045981/853d73c2-2161-11e7-944c-9fa9da9a9134.png)
