### ISSUE TITLE
vux 0.1.3 => 2.2.1-rc.5 升级遇到问题  Error: Cannot resolve module 'vux/undefined' 

### ISSUE THREAD

**Issue by smallos** [airyland/vux#1269]
今天升级老项目vuex遇到问题，搜索了issues与文档后还是一头莫展。麻烦看一下，谢谢
"vue": "^2.2.6",
"vue-router": "^2.4.0",
"vux": "^2.2.1-rc.5"
"vue-template-compiler": "^2.2.6",
"vue-loader": "^11.1.0",
"vux-loader": "^1.0.57",
![image](https://cloud.githubusercontent.com/assets/12025733/25045416/d2365822-215e-11e7-812e-957274da25c8.png)
![image](https://cloud.githubusercontent.com/assets/12025733/25045442/fd75838c-215e-11e7-8d71-f36b057a1fe8.png)

**Comment by smallos** [comment]
引用方式 >>>
![image](https://cloud.githubusercontent.com/assets/12025733/25045771/774d6084-2160-11e7-8514-2de74f6b7407.png)

**Comment by airyland** [comment]
https://vux.li/#/zh-CN/upgrade-to-2

建议你直接使用 airyland/vux2 模板初始化一个空白项目再把相应代码复制过来，因为不只 vux，开发依赖什么的更新也比较大。

**Comment by smallos** [comment]
大概又看了下代码。有一些组建被删除了，比如loding等。删除之后这块错误暂时消除。希望对别的tx有帮助。

**Comment by airyland** [comment]
Loading 并没有删除。

**Comment by smallos** [comment]
是的，loding还在，可能还有别的吧，我清理了这个几个页面共有的组件后就可以运行了。
