### ISSUE TITLE
x-input中type=“number”在移动端无效

### ISSUE THREAD

**Issue by richey07** [airyland/vux#1270]
vux2.2.0，手机端safari浏览器x-input中type=“number”无效，不能限制数字输入，在PC端chrome浏览器有效，只能输入数字和小数点，但可以输入多个小数点。

> 代码如下：

      <x-input title="活体时价（元/千克）："
               v-model.number="currentPrice"
               type="number"></x-input>

**Comment by airyland** [comment]
type=number 是系统组件，多个小数点这个行为组件控制不了，可以使用 type = "tel"。
并不能重现 type = number 无效的情况。

**Comment by brahmachen** [comment]
type="number" 在钉钉的webview里，自动显示数字键盘，左下角有返回按钮，返回后，可以输入英文及汉字，但是提交时没有绑定到数据中
