### ISSUE TITLE
npm install --save babel-runtime/helpers/typeof --- has error

### ISSUE THREAD

**Issue by Jesonhu** [airyland/vux#1272]
i use window7 operation ;
npm run dev ;
npm notice:
This dependency was not found:
* babel-runtime/helpers/typeof in ./~/vux/src/libs/router.js

so i use: npm install --save babel-runtime/helpers/typeof

npm ERR! addLocal Could not install E:\web\vuejs2\vux\vux1\babel-runtime\helpers\typeof
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "babel-runtime/helpers/typeof"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path E:\web\vuejs2\vux\vux1\babel-runtime\helpers\typeof
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'E:\web\vuejs2\vux\vux1\babel-runtime\helpers\typeof'
npm ERR! enoent ENOENT: no such file or directory, open 'E:\web\vuejs2\vux\vux1\babel-runtime\helpers\typeof'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Please include the following file with any support request:
npm ERR!     E:\web\vuejs2\vux\vux1\npm-debug.log

i cant't find the reason to solve the problem

**Comment by airyland** [comment]
Sorry, npm installing problem is not vux's issue. You have to solve it by yourself. Try removing node_modules and install again.

**Comment by Jesonhu** [comment]
i listen your advise and solve the problem ; feel great this moment; i will to study the Vux ; i have the another problem, i from china , for example ,if i have the another issue ,i use chinese or english to talk about it?

**Comment by airyland** [comment]
If you can express the issue clearly in English, then use English.
