### ISSUE TITLE
把loading组件优化成vuex有问题，是不行的

### ISSUE THREAD

**Issue by fuXiangRong** [airyland/vux#1277]
优化
       页面切换显示loading
<loading v-model="isLoading"></loading>
import { Loading } from 'vux'
import { mapState } from 'vuex'

export default {
  components: {
    Loading
  },
  computed: {
    ...mapState({
      isLoading: state => state.vux.isLoading
    })
  }
}

上面组件中把vuex状态绑定到 v-model是什么情况？ 没有效果吧 ....

**Comment by airyland** [comment]
1.代码请格式化
2.你的store呢
3.没有效果这个描述没卵用

**Comment by fuXiangRong** [comment]
优化

页面切换显示loading

移动端如果使用异步组件加载那么还是需要一点等待时间的，在网络慢时等待时间会更长。显示Loading状态缓解一下用户等待情绪就十分重要。

如果你使用vue-router和vuex，那么可以很容易实现。

首先，注册一个module来保存状态

const store = new Vuex.Store({}) // 这里你可能已经有其他 module

store.registerModule('vux', { // 名字自己定义
  state: {
    isLoading: false
  },
  mutations: {
    updateLoadingStatus (state, payload) {
      state.isLoading = payload.isLoading
    }
  }
})
然后使用vue-router的beforeEach和afterEach来更改loading状态

router.beforeEach(function (to, from, next) {
  store.commit('updateLoadingStatus', {isLoading: true})
  next()
})

router.afterEach(function (to) {
  store.commit('updateLoadingStatus', {isLoading: false})
})
在App.vue里使用loading组件并从vuex获取isLoading状态

<loading v-model="isLoading"></loading>
import { Loading } from 'vux'
import { mapState } from 'vuex'

export default {
  components: {
    Loading
  },
  computed: {
    ...mapState({
      isLoading: state => state.vux.isLoading
    })
  }
}

以上代码来自https://vux.li/#/zh-CN/README?id=%E9%A1%B5%E9%9D%A2%E5%88%87%E6%8D%A2%E6%98%BE%E7%A4%BAloading

上面组件中把vuex状态绑定到 v-model是什么情况？ 没有效果吧 ....

**Comment by fuXiangRong** [comment]
我明明格式化了  geihub  怎么又给缩成那样了 ....

**Comment by airyland** [comment]
上你的代码，哪个文件写了什么代码，你复制文档过来有什么用。

**Comment by Sapphire2k** [comment]
@fuXiangRong 
然后使用vue-router的beforeEach和afterEach来更改loading状态
```
router.beforeEach(function (to, from, next) {
    store.commit('updateLoadingStatus', {isLoading: true})
    next()
})
router.afterEach(function (to) {
    store.commit('updateLoadingStatus', {isLoading: false})
})
```
路由切换的时候
`commit` 调用了函数 `updateLoadingStatus ()`
```
updateLoadingStatus (state, payload) {
    state.isLoading = payload.isLoading
}
```
 改变 vuex里的 `isLoading`
－－－－－－－－－－－－－－－－－－
Anyway, 评论的时候 👉有栏叫做 Preview
