### ISSUE TITLE
【求助】华为mate8自带浏览器不兼容

### ISSUE THREAD

**Issue by Z-wave** [airyland/vux#1278]
在华为mate8自带浏览器下面所有组件显示位置都不正常，并且没有动画，如图：
![qq 20170418173944](https://cloud.githubusercontent.com/assets/16026552/25124725/2c8902fe-245f-11e7-9a92-7c3494b402b9.jpg)

但是访问demo是对的，我把vux卸载，重新安装demo的**v2.2.1-rc.7**版本依然不行！
请问是什么原因造成的？

**Comment by airyland** [comment]
检查 autoprefix 配置。
