### ISSUE TITLE
XDialog窗体最大宽度不能满足要求

### ISSUE THREAD

**Issue by mymmoonoa** [airyland/vux#1282]
XDialog现在窗体的宽度依赖于 .weui-dialog的设定
`.weui-dialog {
    position: fixed;
    z-index: 5000;
    width: 80%;
    max-width: 300px;`

能不能把X-Dialog的width和max-width改成可以用户自定义的，要不然限制太大了

**Comment by mymmoonoa** [comment]
我看Demo中的XDialog.vue中style部分有
`.dialog-demo {
  .weui-dialog{
    border-radius: 8px;
    padding-bottom: 8px;
  }...`
但没起作用，如果能直接覆盖样式的话，组件就可以非常灵活了。

**Comment by xiangxisheng** [comment]
可以覆盖的，我用CSS代码添加到App.vue的style标签里即可解决
.weui-dialog{
  width: 95%;
  max-width: 100%;
}

**Comment by mymmoonoa** [comment]
真可以覆盖，但是style 不能用scoped限制。。

**Comment by F-loat** [comment]
.vue文件里可以写两个style标签的
``` html
<style>
/*覆盖用样式*/
</style>

<style scoped>
/*组件内样式*/
</style>
```
