### ISSUE TITLE
使用官方组件cell和官方demo下拉箭头点击没有反应

### ISSUE THREAD

**Issue by PlusLius** [airyland/vux#1283]
![1](https://cloud.githubusercontent.com/assets/23534665/25178984/9552f638-253a-11e7-94c8-e088c0a017b7.png)

`
<template>
  <div>
    <group>
      <cell :title="'My Account'" :value="'Protected'" @click.native="onClick"></cell>
      <cell :title="'Money'" @click.native="onClick" :is-loading="!money" :value="money"></cell>
    </group>

    <group :title="'use is-link to show arrow'">
      <cell :title="'Notifications'" is-link></cell>
      <cell :title="'Privacy'" is-link></cell>
      <cell :title="'General'" is-link>
        <img slot="icon" width="20" style="display:block;margin-right:5px;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC4AAAAuCAMAAABgZ9sFAAAAVFBMVEXx8fHMzMzr6+vn5+fv7+/t7e3d3d2+vr7W1tbHx8eysrKdnZ3p6enk5OTR0dG7u7u3t7ejo6PY2Njh4eHf39/T09PExMSvr6+goKCqqqqnp6e4uLgcLY/OAAAAnklEQVRIx+3RSRLDIAxE0QYhAbGZPNu5/z0zrXHiqiz5W72FqhqtVuuXAl3iOV7iPV/iSsAqZa9BS7YOmMXnNNX4TWGxRMn3R6SxRNgy0bzXOW8EBO8SAClsPdB3psqlvG+Lw7ONXg/pTld52BjgSSkA3PV2OOemjIDcZQWgVvONw60q7sIpR38EnHPSMDQ4MjDjLPozhAkGrVbr/z0ANjAF4AcbXmYAAAAASUVORK5CYII=">
      </cell>
    </group>

    <group :title="'Collapse'">
      <cell
      :title="'Title 001'"
      is-link
      :border-intent="false"
      :arrow-direction="showContent001 ? 'up' : 'down'"
      @click.native="showContent001 = !showContent001"></cell>

      <template v-if="showContent001">
        <cell-box :border-intent="false" class="sub-item" is-link>content 001</cell-box>
        <cell-box class="sub-item" is-link>content 001</cell-box>
        <cell-box class="sub-item" is-link>content 001</cell-box>
      </template>

      <cell
      :title="'Title 002'"
      is-link
      :border-intent="false"
      :arrow-direction="showContent002 ? 'up' : 'down'"
      @click.native="showContent002 = !showContent002"></cell>

      <template v-if="showContent002">
        <cell-form-preview :border-intent="false" :list="list"></cell-form-preview>
      </template>

      <cell
      :title="'Title 003'"
      is-link
      :border-intent="false"
      :arrow-direction="showContent003 ? 'up' : 'down'"
      @click.native="showContent003 = !showContent003"></cell>

      <template v-if="showContent003">
        <cell-box :border-intent="false" class="sub-item">I'm content 003</cell-box>
      </template>

      <cell
      :title="'Animated'"
      is-link
      :border-intent="false"
      :arrow-direction="showContent004 ? 'up' : 'down'"
      @click.native="showContent004 = !showContent004"></cell>

      <p class="slide" :class="showContent004?'animate':''">blablabla...<br/>blablabla...<br/>blablabla...<br/>blablabla...</p>

    </group>

    <group>
      <cell :title="'Notifications'" :value="'Enabled'"></cell>
    </group>

    <group :title="'use slot for complexed content'">
      <cell :title="'slot content'">
        <div slot="value">
          <span style="color: green">{{'Hi, I\'m Vux.'}}</span>
        </div>
      </cell>
    </group>

    <group :title="'isLink is set to true when link exists'">
      <cell :title="'Go to Radio Demo'" link="/component/radio" inline-desc='link="/component/radio"'></cell>
      <cell :title="'Go to Demo'" :link="{path:'/demo'}" inline-desc=':link={path:"/demo"}'></cell>
      <cell :title="'http link'" link="https://vux.li" inline-desc='link="https://vux.li"'></cell>
    </group>
  </div>
</template>

<script>
import { Cell, CellBox, CellFormPreview, Group } from 'vux'

export default {
  mounted () {
    setTimeout(() => {
      this.money = -1024
    }, 2000)
  },
  components: {
    Group,
    Cell,
    CellFormPreview,
    CellBox
  },
  methods: {
    onClick () {
      console.log('on click')
    }
  },
  data () {
    return {
      list: [{
        label: 'Apple',
        value: '3.29'
      }, {
        label: 'Banana',
        value: '1.04'
      }, {
        label: 'Fish',
        value: '8.00'
      }],
      money: null,
      showContent001: false,
      showContent002: false,
      showContent003: false,
      showContent004: false
    }
  }
}
</script>

<style scoped>
.sub-item {
  color: #888;
}
.slide {
  padding: 0 20px;
  overflow: hidden;
  max-height: 0;
  transition: max-height .5s cubic-bezier(0, 1, 0, 1) -.1s;
}
.animate {
  max-height: 9999px;
  transition-timing-function: cubic-bezier(0.5, 0, 1, 0);
  transition-delay: 0s;
}
</style>
`

**Comment by PlusLius** [comment]
![image](https://cloud.githubusercontent.com/assets/23534665/25179380/38104cc6-253c-11e7-97a9-6f760c7e8faa.png)

**Comment by PlusLius** [comment]
@airyland 使用后下拉小箭头没反应

**Comment by airyland** [comment]
版本没有说明。箭头是最近一两个版本才支持的。

**Comment by PlusLius** [comment]
![image](https://cloud.githubusercontent.com/assets/23534665/25181964/bda586fe-2545-11e7-8fb2-f0ac9c8e1ff6.png)

**Comment by PlusLius** [comment]
@airyland  vux 2.2.0 vuex-i18n1.3.1支持吗?

**Comment by airyland** [comment]
文档有写，自行确认。

**Comment by PlusLius** [comment]
@airyland 非常感谢!已经解决了~很感谢!

**Comment by vFire** [comment]
同样碰到这个问题了，直接升级到2.2.0，依然不行。。。求解决方法
