### ISSUE TITLE
scroller控件在安卓模拟上点击失效。

### ISSUE THREAD

**Issue by zn3051644** [airyland/vux#1284]
scroller里嵌套任何可点击的按钮或者其他 点击都会失效不激发，官网的也是如此，用iPhone模拟是可以的。下面是截图
![qq 20170419195330](https://cloud.githubusercontent.com/assets/8720771/25179200/6cbc8a4e-253b-11e7-8da7-be31ad57f41b.png)

**Comment by zn3051644** [comment]
等等在传图。。。 传不上去

**Comment by zn3051644** [comment]
@airyland 传上去了  可以看图了

**Comment by airyland** [comment]
设置  `:prevent-default="false"` 试试

**Comment by zn3051644** [comment]
可以了，谢谢！

**Comment by airyland** [comment]
考虑到实际使用情况，下个版本 prevent-default 会默认为 false
