### ISSUE TITLE
vux弹出的alert不能用回车或者空格来关闭

### ISSUE THREAD

**Issue by xiangxisheng** [airyland/vux#1285]
vux弹出的alert没有把focus自动移到“确认”按钮上，所以不能用“回车键”或者“空格键”来关闭。

解决方案1：可以通过修改vux的源码来解决。
方法是：在弹出alert框的时候，自动设置$('.weui-dialog__btn_primary').focus();，
另外按tab键的时候没有固定在alert弹出来的dialog范围内的话可以用onblur解决这个问题。

解决方案2：在github里发起issue联系作者一起来解决这个问题。
解决方案3：自己研究好提供代码让作者添加上来
解决方案4：自己研究好后fork出来发布一个vux3.0在github

**Comment by airyland** [comment]
额，移动端的回车和空格键来关闭？那么得弹出键盘？

**Comment by xiangxisheng** [comment]
虽然说vux只是一个移动端UI，但在电脑里打开支持HTML5的浏览器也是可以用的。
在人力资源紧缺的时候，可以暂时只发布移动端，以缓解项目压力。

**Comment by airyland** [comment]
sorry，VUX 只会支持移动端，没有完全支持 PC 的想法。你倒是可以尝试自己处理，监听键盘事件把 show 设为 false 就搞定了。

**Comment by xiangxisheng** [comment]
我能将这部分兼容PC端的代码修正后贡献到vux项目中来吗？

**Comment by airyland** [comment]
这个暂时不会接受，毕竟 PC 端支持不是开发目标。

**Comment by xiangxisheng** [comment]
看来我又得自己去造轮子了Orz

**Comment by xxfroot** [comment]
alert能不能不要遮罩层?总是在弹出alert后再弹出遮罩层
