### ISSUE TITLE
npm install vux 版本问题

### ISSUE THREAD

**Issue by initmo** [airyland/vux#1287]
不好意思在issues请教一个初级问题，用 **npm install vux** 命令安装的 vux 版本中仍没有scroller 组件的  **Support duration and easing for reset function** ，我该如何安装才能更新到这个版本。

**Comment by airyland** [comment]
确定当前版本是哪个，在 https://vux.li/#/zh-CN/changes 里看下需要的特性是在哪个版本增加，直接安装该版本或者用最新版本。

**Comment by initmo** [comment]
@airyland 看了下changelog ，  **支持在滚回顶部时设置时间和缓动 #1240**  这项内容是在在 **v2.2.1-rc.4** 这个版本更新的，但是我我执行 npm install vux 后 package.json 配置已经自动更新为 **"vux": "^2.2.0"**，应该是当前最新版本了，但是我翻看了下 node-modules 目录中的源码，仍旧是旧版本的内容。
