### ISSUE TITLE
datetime 组件初始化问题

### ISSUE THREAD

**Issue by Garfield-yin** [airyland/vux#1288]
版本：2.2.1-rc.7 
引用datetime 组件，每次页面初始化渲染都会触发on-change事件，并且初始化value等于当前时间，但是如果一个页面完成整个操作需要切换到其他页面完成输入选择，再切换回来之前选择的时间又被初始化覆盖了，有好的解决办法吗？只能将选择时间也放到不同页面？

**Comment by zackteng** [comment]
这个不算组件问题 可以用vuex把数据放到store里 或者不想引入放到localstorage里 或者放到一个全局变量里 组件载入时读取 组件销毁时设置

**Comment by Garfield-yin** [comment]
把时间放到vuex store里面，然后切换到其他页面进行输入操作，操作结束后返回这个页面组件又触发on-chage 把这个vuex store中存储的值覆盖为初始值。

**Comment by williambryan777** [comment]
能否做到初始状态下表单一个值都没有，然后弹出选择框的时候指定一个特定的日期值呢，类似popup-picker都缺乏这个功能。目前是必须有一个初始值才能弹出的时候定位到那个想要的值

**Comment by goweiaiyue** [comment]
怎么控制datetime的现实隐藏呢？

**Comment by airyland** [comment]
目前初始化时不会 emit on-change 事件，并且可以使用 `:show.sync` 来控制显示。
