### ISSUE TITLE
如何修改 系统 自带组件样式

### ISSUE THREAD

**Issue by litoxy** [airyland/vux#1291]
比如 默认的panel组件 
我想在加一个type为4的
样式 自定义 
是直接修改 node_modules/vux/src/components/panel/index.vue添加代码吗？
或者有其他方法

求不喷

**Comment by lichunqiang** [comment]
https://vux.li/#/?id=%E5%8F%AF%E9%85%8D%E7%BD%AE%E9%A2%9C%E8%89%B2

**Comment by airyland** [comment]
VUX 提供了部分样式 Less 变量，但是对于不是通用的样式或者自定义的组件，可以直接复制源码自行修改，VUX 组件基本是独立的。
