### ISSUE TITLE
请问怎么在vue-cli 里怎么使用vux中 umd 格式的文件

### ISSUE THREAD

**Issue by jlianphoto** [airyland/vux#1295]
请问怎么在vue-cli 中使用vux中 umd 格式的文件 , 已经通过systemJS把 需要的组件引过来了 , 但是在注册的时候 , 由于异步的原因无法在组件渲染之前就注册 , 因为需要将vux的组件放到静态文件服务器上 , 供多个项目同时使用 , 需要更改一个组件, 所有项目都会跟着改变 , 研究了好久 , 但还没研究出来 ...

**Comment by airyland** [comment]
sorry，不推荐 webpack 里使用 umd。只解答 webpack 引用源码的问题。不清楚你想实现什么，将 vux 直接作为依赖，每个项目按需更新版本有何不可，为什么还要这样复杂操作。
