### ISSUE TITLE
Cell组件的标题对点击事件的响应

### ISSUE THREAD

**Issue by vFire** [airyland/vux#1296]
先表明一下态度，非常喜欢VUX，愿意捐赠，求捐赠渠道和进圈（之前在某个版本的readme中看到过）
---------------------------------------------------------
然后提问啦：<div class="weui-cell" :class="{'vux-tap-active': isLink || !!link, 'weui-cell_access': isLink || !!link}" @click="onClick">
我在vux的组件cell中找到对应的click事件的代码，但是发现标题title部分点击是不会触发的，相信应该是故意这么设计的，本身cell应该是用作右侧设置用，但我用cell比较顺手，而且布局比card貌似要简单干净，所以我需要整个cellbox点击触发事件，现在触发不了，求解决方法或者求指点title对click免疫的代码所在位置，多谢多谢！

**Comment by vFire** [comment]
![2017-04-22_121253](https://cloud.githubusercontent.com/assets/15304028/25301285/4b14a784-2755-11e7-9b1f-8aac2cabf2a9.png)

设置了@click.native之后整个cell，就主标题部分点击无效。

**Comment by vFire** [comment]
不好意思，粗心了，github首页就有捐赠链接，已买咖啡给作者，多谢！

**Comment by airyland** [comment]
感谢慷慨的捐赠 😃 

在 cell 上用 click.native 理论上是可以实现点击整个 cell 任意地方触发事件的。
你可以看下 demo 这里，https://vux.li/demos/v2/#/component/cell， 第一个栗子，点击标题 console 出来。

``` html
<cell :title="$t('My Account')" :value="$t('Protected')" @click.native="onClick"></cell>
```

对于  cell-box 同理，不应该会出现点击无效的情况。cell 和 cell-box 源码里的 click 事件仅仅是为了处理 link 不会和绑定的原生点击事件 click.native 有所冲突。

你可以帖下你的代码看看。

**Comment by vFire** [comment]
嗯，我也在手机上测试demo了，确实可以的，但我搞不明白为什么我这个不行了。以下是我的代码，没什么特别的，我把多余的slot全部去掉也一样触发不了，麻烦帮忙看一下，多谢！

引用代码失败，显示出来格式不对，无奈，贴图吧

![2017-04-23_202702](https://cloud.githubusercontent.com/assets/15304028/25313565/62625b2a-2863-11e7-8464-7a251bb2fc60.png)

**Comment by vFire** [comment]
还有，右侧的这个“right”箭头按照官网demo修改，也没有效果，貌似我看到是最新版本才支持，但我已经更新了最新版本到^2.2.0，似乎也是一样，检查了dom，确实官网的dom和我本地的表现不一样，我本地的是
有个direction的attribute，而官网的是通过class变更，所以应该是版本的原因，但我不清楚如何才能和官网一样，多谢啦~

**Comment by vFire** [comment]
顺便吐槽一下github发图老是不成功，非得通过vpn才行。。。

**Comment by vFire** [comment]
在chrome浏览器下，pc模式debug可以正常触发，但是切换到mobile模式就和手机表现一样，标题那个地方触发不了。

**Comment by vFire** [comment]
不用劳烦作者了。。。我折腾好了。。。升级到2.2.1-rc.8问题解决。。。昏迷。。。我直接在package指定的这个版本号，升级完成就好了。。。

**Comment by airyland** [comment]
你上面有两个问题，都没问题了？

**Comment by vFire** [comment]
对的，都解决了。。。我看到package中主版本号跟这个一致，以为会自动升级，update了没用，强制指定更新的，然后就好了。。。咔咔，有空的时候在demo文档中备注一下吧。
再提一个小意见，能不能让自定义的标签比如.custom-class 然后可以在scoped的情况下，改写weui里面的默认样式，这样就会很方便了，现在自定义虽然可以，但经常会对原生组件做小量定制，全部用全局css去改写就体现不出这个scoped的优势了，如果能再一个vue文件中全部搞定，那整个项目结构就非常完美了。期待能改进~ 谢谢！

**Comment by airyland** [comment]
scoped 情况下无法覆盖内部的 class 这是 vue-loader 的支持问题，只能等 vue-loader 来实现。在 [vue-loader issue](https://github.com/vuejs/vue-loader/issues/) 里有多个此类问题。

如果再过一段时间官方未有动作，将在 vux-loader上 尝试做支持。

**Comment by vFire** [comment]
感谢！另外有内部支持圈吗？求加入~~~

**Comment by airyland** [comment]
将有社区以及社区 Pro，开发中。

**Comment by airyland** [comment]
将有社区以及社区 Pro，开发中。
