### ISSUE TITLE
tabbarItem组件的selected与link在路由返回时不匹配。

### ISSUE THREAD

**Issue by nali946** [airyland/vux#1297]
需要获取$route.path或者route.matched去匹配有点小麻烦啊，这两个参数有没有办法合二为一啊？？

**Comment by airyland** [comment]
TabbarItem 不超过5个，这个成本基本可以忽略不计了。事实上一个 TabbarItem 可以对应多个路由，可能是 match path 也可能是需要 match query，在组件内如果限定 router 完全匹配 link 就会造成更大的问题。所以最好的方法还是现在这样，不干涉 selected 具体逻辑。
