### ISSUE TITLE
search组件有没有编程触发焦点的方法

### ISSUE THREAD

**Issue by initmo** [airyland/vux#1299]
search组件有没有编程触发焦点的方法，如setFocus()、setCancel() 等

**Comment by vFire** [comment]
`setTimeout(function () {
          $this.$refs.searchbar.$refs.input.focus()
        }, 500)`

这样可以触发，不过呢，简单测试了一下在ios的safari浏览器中，键盘没有唤出~ 等作者添加这个methods吧~ @airyland

**Comment by airyland** [comment]
浏览器限制了 focus 能触发的条件，必须在用户点击(tap)事件后才能触发 focus，所以你这代码显然是无法生效的。

**Comment by vFire** [comment]
那也就是说在普通webapp环境下，除了人工的tap之外，不可能通过methods去触发这个事件了对吗？

**Comment by greedying** [comment]
安卓下可以触发， ios下，尤其是safari，够呛。好像也没什么特别好的方法

**Comment by vFire** [comment]
嗯 明白了 估计只有一种办法 伪装search或input成icon 点击icon就是触发了focus 来达到一次点击就focus 只是要专门写伪装比较不爽

**Comment by airyland** [comment]
setCancel 是什么需求场景？

**Comment by initmo** [comment]
@airyland 比如首页有个search 组件框作为搜索入口，输入搜索关键字点击submit之后在下个页面展示搜索结果，首页是keep-alive 缓存的，因此在搜索结果页返回到首页的时候，首页搜索框显示的仍旧是输入状态，这样不太好看，希望能在submit之后让search 组件恢复到初始状态
