### ISSUE TITLE
InlineCalendar 为什么点击下个月的日期不会直接渲染下个月的日历了

### ISSUE THREAD

**Issue by xuyangqiao** [airyland/vux#1301]
InlineCalendar 为什么点击下个月的日期不会直接渲染下个月的日历了，
完全复制示例的demo,但是在自己的项目中不能实现点击下个月的日期直接渲染第二个月的日历，而官网demo可以，请问是怎么回事

`<inline-calendar
        class="office-date"
        :show.sync="true"
        v-model="value"
        start-date="2016-04-01"
        end-date="2018-05-30"
        :highlight-weekend="true"
        :return-six-rows="true"
        :hide-header="false"
        :weeks-list="['日', '一', '二', '三', '四', '五', '六 ']"
        :render-on-value-change="true">
      </inline-calendar>
`
没有禁用选择以前和未来日期

**Comment by airyland** [comment]
这种情况不就是版本问题吗，不能自己先 check 一下？
