### ISSUE TITLE
关于alert按钮和事件的问题。

### ISSUE THREAD

**Issue by yuch321** [airyland/vux#1302]
想做一个删除的提示，点击删除按钮后出现弹窗，弹窗有确定和取消两个选择。点击确定，删除信息，点击取消返回，看了一下demo好像都只有一个按钮，想问一下可以设置两个按钮吗？并且两个按钮分别绑定一个事件.谢谢了，代码很简单，不过还是贴一下 如下:
 `  <alert button-text="确定"  :content="content" v-model="show"></alert>`

**Comment by airyland** [comment]
使用 confirm 组件来做。或者  x-dialog 自己实现逻辑。

**Comment by yuch321** [comment]
@airyland 不好意思，没仔细看全部组件，不知道还有confirm，想当然以为是alert了。3q
