### ISSUE TITLE
i18n的block不显示中文

### ISSUE THREAD

**Issue by noikiy** [airyland/vux#1303]
首先vux是成功引入进来了。
贴下vux-loader的配置
![image](https://cloud.githubusercontent.com/assets/977243/25328135/4ef6eb22-2909-11e7-8592-0a59f5cdc5ed.png)

>Hello.vue
![image](https://cloud.githubusercontent.com/assets/977243/25328154/69044992-2909-11e7-9448-42ca10c7ea02.png)

执行npm run dev时有报错
![image](https://cloud.githubusercontent.com/assets/977243/25328191/8a868f8a-2909-11e7-997f-a5746680378a.png)

**Comment by airyland** [comment]
yml 格式不对

http://www.ruanyifeng.com/blog/2016/07/yaml.html

**Comment by noikiy** [comment]
@airyland 
我直接复制的这个文件
https://github.com/airyland/vux/blob/v2/src/demos/Msg.vue

**Comment by airyland** [comment]
那你复制错了，源码有明显的空格缩进。

**Comment by noikiy** [comment]
@airyland 谢谢。我的问题。复制的时候，IDE直接把空格清除了。不过现在编译又报另外的错误了。
![image](https://cloud.githubusercontent.com/assets/977243/25328722/8dbced32-290b-11e7-841b-5939d251da41.png)

**Comment by airyland** [comment]
重启过 vux-loader 没有？检查这个文件是否存在，一般来说 vux-loader 会根据你的配置创建这个文件，如果没有，你手动创建也可以。

**Comment by noikiy** [comment]
@airyland 是会自动创建的，但是由于src目录下没有locales这个文件夹，所以不能新建。需要手动创建个文件夹先。

**Comment by airyland** [comment]
那么手动创建后还有问题吗？

**Comment by noikiy** [comment]
@airyland 手动创建后没问题了。但是显示的还是英文。是不是还有别的选项？

**Comment by airyland** [comment]
补充下 main.js 代码吧，你设置了哪个默认语言？

**Comment by noikiy** [comment]
`import Vue from 'vue';
import Vuex from 'vuex';
import vuexI18n from 'vuex-i18n';
import { LocalePlugin } from 'vux';
import App from './App';
import router from './router';

Vue.config.productionTip = false;
Vue.use(Vuex);
Vue.use(vuexI18n);

const store = new Vuex.Store({
  modules: {
    i18n: vuexI18n.store,
  },
});

Vue.use(vuexI18n.plugin, store);
Vue.use(LocalePlugin);

const nowLocale = Vue.locale.get();
console.log(nowLocale); // zh-CN
if (/zh/.test(nowLocale)) {
  Vue.i18n.set('zh-CN');
} else {
  Vue.i18n.set('en');
}`

**Comment by airyland** [comment]
话说你都没有把语言配置添加到 vuex-i18n 吧。。

**Comment by noikiy** [comment]
@airyland 你的意思是这段？
![image](https://cloud.githubusercontent.com/assets/977243/25329733/a1dffd96-290f-11e7-866b-f910c667e07c.png)

**Comment by airyland** [comment]
vux-loader 只是帮你抽取语言文件，你要自己添加到 vuex-i18n 里。
