### ISSUE TITLE
基于VUX目前的TAB做的横滚和下拉增强

### ISSUE THREAD

**Issue by vFire** [airyland/vux#1304]
这个不算问题啦，只是简单Share一下经验，以前拿IONIC的时候也干过类似的事情，其实只要在VUX的TAB基础上做一些小的调整就可以实现，由其CSS调整比较关键。贴一下基础代码，供大家参考!
![video_2017-04-24_194150_2017424194520](https://cloud.githubusercontent.com/assets/15304028/25335882/8392400c-2927-11e7-8352-bf730027f36d.gif)
![2017-04-24_194945](https://cloud.githubusercontent.com/assets/15304028/25335894/9a293f1e-2927-11e7-8966-00c6929b199b.png)
![2017-04-24_195017](https://cloud.githubusercontent.com/assets/15304028/25335899/9df1402e-2927-11e7-8a3e-34e22b8c894a.png)
![2017-04-24_195036](https://cloud.githubusercontent.com/assets/15304028/25335901/9fa3be60-2927-11e7-887b-44e6b1feaa74.png)

**Comment by vFire** [comment]
这种我倒觉得样式都有差异，既然可以比较简单的实现，封不封装倒也没关系了，当然，能写的更好的大家分享也是极好的，我对VUE不熟悉，勉强凑合能用，暂时在Chrome，safari，微信测试都可以没问题。
动画效果我就用的animate.css做的，勉强够看了。

**Comment by airyland** [comment]
话说下面居然有那么密集的 tabbar。。

**Comment by vFire** [comment]
哈哈，那是在测试期间，所以全部展现出来了~：）

**Comment by airyland** [comment]
下周官网会上 gist 功能鼓励大家分享实际使用例子，这条 issue 我先关掉，到时你就可以直接帖到 gist 那边了。

**Comment by vFire** [comment]
收到~
