### ISSUE TITLE
XHeader的需求

### ISSUE THREAD

**Issue by vFire** [airyland/vux#1305]
刚好逮到作者了。。。求XHEADER多一个slot，就是左边这个，跟右侧的slot一样，能不能让人完全自己独立定制，XICON的样式比较少，而且不太好用，我自己有ICON类，还有XHEADER上面的图标可点击区域太少了，这是原来WEUI的锅，但是体验不好，如果应用较扁的图标，不太点的到，我用CSS虽然可以搞定，但左边这个BACK图标用的不是字体，不能自定义的话，CSS要写两种……强迫症不能忍。。。

求作者更新一下XHEADER，增加个LEFT SLOT吧！！！

你看左边这个现在。。。
![2017-04-24_200008](https://cloud.githubusercontent.com/assets/15304028/25336147/c147fd8c-2928-11e7-9dca-8ddd220f0e0e.png)

修改CSS后可点击区域明显增大
![2017-04-24_200029](https://cloud.githubusercontent.com/assets/15304028/25336153/ce337ed6-2928-11e7-8626-48f5b6d8f591.png)

**Comment by airyland** [comment]
文档漏写了，是有 slot:left 的。你直接试试看。

**Comment by vFire** [comment]
嗯，我试过，但是似乎没有覆盖左侧的back icon和文字，需要在Xheader中用配置先把这些去掉，有点怪，代码不干净…… 强迫症。。。见谅~

**Comment by airyland** [comment]
你是想直接覆盖原来的左侧部分么？
