### ISSUE TITLE
屏幕翻转后的布局问题

### ISSUE THREAD

**Issue by vFire** [airyland/vux#1306]
简单做了一些测试，翻转后布局会出现问题，scroll无法撑满啦，viewbox的问题啦，同志们怎么解决的，resize触发后scroller reset吗？

**Comment by airyland** [comment]
问题请具体说明。

**Comment by lsvih** [comment]
我就是这么做的，你说的方法可以解决你说的问题

**Comment by vFire** [comment]
好滴，多谢多谢，后期再尝试。
