### ISSUE TITLE
希望loading组件show和hide方法能增加方法参数

### ISSUE THREAD

**Issue by Kyncc** [airyland/vux#1308]
在组件开始或者关闭的时候，可能需要做其他的附属操作。例如： 有一个接口正在发送，loading中，这时候用户点击了返回键，路由返回上到上一页，我希望这时候能够取消loading的效果，然后取消这个接口发起请求。

**Comment by airyland** [comment]
没看出哪里需要加参数？路由返回时你直接用 hide 函数关闭，然后取消你的请求不是已经解决了么？请求和 Loading 没有什么关系，一个是 UI 一个是请求是互相独立的操作。

**Comment by Kyncc** [comment]
主要是 在loading的过程中，如果能注入方法，监听到用户返回键的操作，然后根据用户操作去处理。
loading取消了，我在取消这个事件监听

**Comment by airyland** [comment]
返回键这个监听不了，只有 App 能做到。
