### ISSUE TITLE
代码直接在html里面写，模仿Calendar.vue里的代码，但运行后选择不了日期，请问如下代码有问题吗？谢谢

### ISSUE THREAD

**Issue by 99937272** [airyland/vux#131]
<html>
<head>
  <meta charset="utf-8">
 <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
  <link rel="stylesheet" href="../../vux.css">
  <script src="../../examples/vue.min.1.0.18.js"></script>
  <title></title>	
</head>
<body>

<script type="text/x-template" id="master-template">
<div>
    <group title="English">
      <cell title="Default" primary="content">
        <calendar slot="value" :value.sync="demo1"></calendar>
      </cell>
      <cell title="select hours" primary="content">
        <calendar slot="value" :value.sync="demo2" hours></calendar>
      </cell>
      <cell title="disable past date" primary="content">
        <calendar slot="value" :value.sync="demo3" disable-past></calendar>
      </cell>
    </group>
    <group title="中文">
      <cell title="中文星期" primary="content">
        <calendar slot="value" :value.sync="demo4" :date-list="dateList" disable-past></calendar>
      </cell>
    </group>
  </div>
</script>
<script type="text/javascript" src="../../components/group/index.js"></script>
<script type="text/javascript" src="../../components/calendar/index.js"></script>
<script type="text/javascript" src="../../components/cell/index.js"></script>
<master-template></master-template>
<script>
Vue.component('group', vuxGroup);
Vue.component('calendar', vuxCalendar);
Vue.component('cell', vuxCell);

Vue.component('master-template', {
	  template: '#master-template'
});
</script>

<script>

new Vue({
	el: 'body',
	data () {
	    return {
	      demo1: 'Select date',
	      demo2: 'date and hour',
	      demo3: 'Select date',
	      demo4: '请选择',
	      dateList: ['日', '一', '二', '三', '四', '五', '六']
	    }
	  }
});
</script>

</body>
</html>

**Comment by airyland** [comment]
代码没问题，是组件本身的bug，该组件正在重构中，周末会更新。
