### ISSUE TITLE
datetime组件希望增加设置max-minutes和min-minutes

### ISSUE THREAD

**Issue by qiangguoguo** [airyland/vux#1311]
小时可以设置范围，分钟希望也可以设置，谢谢

**Comment by airyland** [comment]
具体场景是？因为觉得分钟没有使用场景才没有加的。

**Comment by qiangguoguo** [comment]
需求是只能选择从现在到之前的时间

**Comment by qiangguoguo** [comment]
不限制分钟的话，就会超过当前的时间

**Comment by airyland** [comment]
问题是设定分钟范围也满足不了你的要求吧。你现在设定分钟范围 0-45，意味着上个小时也选择不了 45-59这个分钟段了。

**Comment by qiangguoguo** [comment]
嗯 有道理 谢谢啦

**Comment by airyland** [comment]
小时分钟的范围校验逻辑建议在提交时进行。start-date 和 end-date 目前只会支持年月日。
