### ISSUE TITLE
tabbar-item 的 on-item-click 事件中的参数传递问题

### ISSUE THREAD

**Issue by vFire** [airyland/vux#1315]
`<tabbar-item @on-item-click="clickTabbar">`

tabbar-item的click事件默认传的是index索引值（1,2,3,4……），请问一下能不能在clickTabbar函数中，直接把tabbar-item自己获取到，就和原生button click="pass(this)" 这个this一样，免得还需要通过refs去获取元素。

多谢！

**Comment by airyland** [comment]
获取这个元素的作用是？
