### ISSUE TITLE
使用了Vue.use(vux) vux2.0

### ISSUE THREAD

**Issue by nieyulin112** [airyland/vux#1317]
1.Cannot resolve module 'vux/lib/style.css'
2.Cannot resolve module 'vux/lib'

**Comment by nieyulin112** [comment]
这个是怎么解决的，安装了vux

**Comment by airyland** [comment]
并没有这个使用方法。

**Comment by myfreax** [comment]
@airyland 为什么不这么做？

**Comment by airyland** [comment]
@huangyanxiong01 你会在移动端加载所有组件？
