### ISSUE TITLE
必须重新run dev 才能查看修改的代码吗？

### ISSUE THREAD

**Issue by GaoDemen** [airyland/vux#1319]
run dev后调不起页面。手动打开8080端口页面没有问题 也没有报错，之后修改代码，页面无变动，需要重新run dev之后才能查看代码改动后的页面。是我这设置的问题么？  表示如果不用vux 一切正常啊，谢谢了

**Comment by airyland** [comment]
没有说明是用模板创建还是自己配置，解决不了，请自行检查问题。
