### ISSUE TITLE
XIcon不支持 :type的写法？

### ISSUE THREAD

**Issue by joy-yu** [airyland/vux#1320]
像这样：
`<x-icon :type="followFlag?'android-add':'android-done'"></x-icon>`

版本：
`
"vux": "^2.2.0", 
"vux-loader": "^1.0.58",
`

**Comment by airyland** [comment]
不支持，x-icon 是特殊的一个组件，渲染时已经被替换成 svg 了，所以动态 type 不会生效。建议你使用 v-show 来切换两个不同的 x-icon。
