### ISSUE TITLE
更新版本到2.2.1 ，使用button-tab 出现绿色边框 

### ISSUE THREAD

**Issue by chunecai** [airyland/vux#1322]
使用官网的https://vux.li/#/zh-CN/demos/button-tab demo一样的。
都出现绿色边框；
  "vux": "^2.2.1", 
![image](https://cloud.githubusercontent.com/assets/7912599/25425674/37ea833e-2a9f-11e7-9420-1a2c4310f299.png)

**Comment by chunecai** [comment]
所有之前使用到button-tab的都出现了绿色的边框，不能平滑升级。 难道每个使用到的都需要重新编写样式覆盖吗？

**Comment by airyland** [comment]
原来没有边框？

**Comment by chunecai** [comment]
原来的不是绿色边框，原来的跟demo里面展示的一样。
![image](https://cloud.githubusercontent.com/assets/7912599/25429654/472b3048-2aac-11e7-8064-3516843469e7.png)

**Comment by graysheeep** [comment]
demo一切正常
