### ISSUE TITLE
swiper组件的点击多次出发和延迟触发问题

### ISSUE THREAD

**Issue by Pasoul** [airyland/vux#1323]
情景：在swiper组件增加点击事件，轮播停留时长为默认的3000ms，结果点击一次没有立即触发，而是切换轮播后才触发事件，而且在此之后每切换一次轮播都自动触发一次事件

代码：
`<swiper :list="img_list" auto loop  height="3.75rem" dots-class="custom" @on-index-change="clickbanner"></swiper>`
```
methods : {
  clickbanner () {
      console.log(1) // 每次切换轮播都打印1
  }
},
```
关联的img_list:
```
let imgList = res.data.list
this.img_list = imgList.map((item, index) => ({
  url: 'javascript:;',
  img: item.banner_path,
}));
```

**Comment by airyland** [comment]
on-index-change 不是点击事件，在当前图片次序改变时触发。

**Comment by py419569317** [comment]
那如何给我的swiper增加点击事件呢，我用自己的方法给每个vux-swiper-item都增加了data-type属性，想通过点击事件获取到这个属性值，从而知道我要调到哪个页面去

**Comment by airyland** [comment]
list 是支持 url 属性的
或者
使用 swiper-item  绑定  click.native 事件

**Comment by Pasoul** [comment]
好的，明白了，是我自己的理解问题
