### ISSUE TITLE
打包时候报错

### ISSUE THREAD

**Issue by yhZhouYh** [airyland/vux#1325]
ERROR in static/js/vendor.b7f70d05973f0725bb63.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/muse-ui/src/internal/scroll.js:5,0][static/js/vendor.b7f70d05973f0725bb63.js:20574,14]

**Comment by airyland** [comment]
I don't think it's VUX's issue.

**Comment by MadratJerry** [comment]
参见 https://github.com/webpack/webpack/issues/5858

vue-cli template 中也有相关注释
https://github.com/airyland/vux2/blob/610f7ca6b4e778a304a3f9c20c279d2f7afb9762/template/build/webpack.prod.conf.js#L36
