### ISSUE TITLE
XInput 如果类型为number 字符长短无法限制

### ISSUE THREAD

**Issue by muei** [airyland/vux#1328]
版本：`"vuex": "^2.1.1",`
*code*, 模板用的是`pug`:
```html
  x-input(
    type="number"
    required
    v-bind:min="6"
    v-bind:max="6"
  )
```
如上当`type="number"`，实际输入时`max`限制将无效，即当输入超过6个字符了还可以输

**Comment by airyland** [comment]
目前 max 相当于 maxlength，该属性默认行为限制不了 type = number。

**Comment by muei** [comment]
嗯！我觉得这种可能就需要vux来辅助完善了！

**Comment by airyland** [comment]
#1549
