### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by iusn** [airyland/vux#1329]
![image](https://cloud.githubusercontent.com/assets/11364258/25471233/b55a5f38-2b58-11e7-9e58-00c8ee95601f.png)

node version：v7.8.0
  "vux": "^2.2.1",
  "vux-loader": "^1.0.58"

vue.esm.js?65d7:558 [Vue warn]: Error in render function: 
(found in <Loading> at /Users/nero/Work/uTruckWeb/driverHomePage/node_modules/vux/src/components/loading/index.vue)
warn @ vue.esm.js?65d7:558
handleError @ vue.esm.js?65d7:1443
Vue._render @ vue.esm.js?65d7:3609
updateComponent @ vue.esm.js?65d7:2156
get @ vue.esm.js?65d7:2467
Watcher @ vue.esm.js?65d7:2450
mountComponent @ vue.esm.js?65d7:2160
Vue$3.$mount @ vue.esm.js?65d7:7250
Vue$3.$mount @ vue.esm.js?65d7:9299
init @ vue.esm.js?65d7:2929
createComponent @ vue.esm.js?65d7:4654
createElm @ vue.esm.js?65d7:4597
createChildren @ vue.esm.js?65d7:4722
createElm @ vue.esm.js?65d7:4630
patch @ vue.esm.js?65d7:5053
Vue._update @ vue.esm.js?65d7:2033
updateComponent @ vue.esm.js?65d7:2156
get @ vue.esm.js?65d7:2467
Watcher @ vue.esm.js?65d7:2450
mountComponent @ vue.esm.js?65d7:2160
Vue$3.$mount @ vue.esm.js?65d7:7250
Vue$3.$mount @ vue.esm.js?65d7:9299
init @ vue.esm.js?65d7:2929
createComponent @ vue.esm.js?65d7:4654
createElm @ vue.esm.js?65d7:4597
createChildren @ vue.esm.js?65d7:4722
createElm @ vue.esm.js?65d7:4630
patch @ vue.esm.js?65d7:5053
Vue._update @ vue.esm.js?65d7:2033
updateComponent @ vue.esm.js?65d7:2156
get @ vue.esm.js?65d7:2467
Watcher @ vue.esm.js?65d7:2450
mountComponent @ vue.esm.js?65d7:2160
Vue$3.$mount @ vue.esm.js?65d7:7250
Vue$3.$mount @ vue.esm.js?65d7:9299
init @ vue.esm.js?65d7:2929
createComponent @ vue.esm.js?65d7:4654
createElm @ vue.esm.js?65d7:4597
patch @ vue.esm.js?65d7:5089
Vue._update @ vue.esm.js?65d7:2033
updateComponent @ vue.esm.js?65d7:2156
get @ vue.esm.js?65d7:2467
Watcher @ vue.esm.js?65d7:2450
mountComponent @ vue.esm.js?65d7:2160
Vue$3.$mount @ vue.esm.js?65d7:7250
Vue$3.$mount @ vue.esm.js?65d7:9299
Vue._init @ vue.esm.js?65d7:3766
Vue$3 @ vue.esm.js?65d7:3847
(anonymous) @ main.js?1c90:14
(anonymous) @ app.js:2007
__webpack_require__ @ app.js:658
fn @ app.js:86
(anonymous) @ app.js:5462
__webpack_require__ @ app.js:658
(anonymous) @ app.js:707
(anonymous) @ app.js:710
vue.esm.js?65d7:1447 TypeError: _vm.$t is not a function
    at Proxy.render (eval at <anonymous> (app.js:3942), <anonymous>:25:25)
    at VueComponent.Vue._render (eval at <anonymous> (app.js:721), <anonymous>:3608:22)
    at VueComponent.updateComponent (eval at <anonymous> (app.js:721), <anonymous>:2157:21)
    at Watcher.get (eval at <anonymous> (app.js:721), <anonymous>:2468:25)
    at new Watcher (eval at <anonymous> (app.js:721), <anonymous>:2451:12)
    at mountComponent (eval at <anonymous> (app.js:721), <anonymous>:2161:17)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:721), <anonymous>:7251:10)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:721), <anonymous>:9300:16)
    at init (eval at <anonymous> (app.js:721), <anonymous>:2930:13)
    at createComponent (eval at <anonymous> (app.js:721), <anonymous>:4655:9)

**Comment by airyland** [comment]
请附上重现步骤。

**Comment by iusn** [comment]
@airyland 你好 这是我的demo
https://github.com/iusn/Vux-Loading-Error-Demo
HomePage.vue 里用的Toast
Hello.vue 里用的 Loading
都有上面的问题 vue新手 麻烦你了

**Comment by airyland** [comment]
文档不是写了，必须使用 vux-loader 吗？
如果你非要自己配置，文档也写了如何配置。
新手直接使用 airyland/vux2 模板创建。
