### ISSUE TITLE
search组件，搜索结果列表无法滚动

### ISSUE THREAD

**Issue by hpf-jk** [airyland/vux#1332]
在搜索框里输入东西之后，显示出的结果列表无法滚动。我试了官网那几个使用案例（就一堆二维码那里，随便扫了一个进去），也不行啊。

**Comment by muei** [comment]
@hpf-jk 你这样提问！就是神仙也帮不了你啊

**Comment by s949492225** [comment]
Search组件输入后，弹出的匹配列表无法滚动，描述应该清楚，请查验

**Comment by hpf-jk** [comment]
我的描述很清楚了吧。。就把官网的代码复制下来，就是这种情况了。 情况就是楼上描述的那样。。匹配的结果列表无法滚动

**Comment by graysheeep** [comment]
fixed #1540
