### ISSUE TITLE
Loading冲突

### ISSUE THREAD

**Issue by noikiy** [airyland/vux#1340]
基本情况：
main.js引用LoadingPlugin，App.vue引用Loading
router的钩子也写在main.js里面
![image](https://cloud.githubusercontent.com/assets/977243/25524004/5475f496-2c3b-11e7-9288-6e591223535e.png)
插件形式是可以调用Loading的。
但是用vuex的方式就走不通。

**Comment by airyland** [comment]
代码不完整，补充 App.vue 代码重开。

**Comment by airyland** [comment]
并没看到 App 里有 isLoading 这个变量。按照文档，要把 isLoading 使用 mapState 挂载进来。

**Comment by airyland** [comment]
自己调试下吧，main.js 代码也没有。
把 isLoading 放出来调试下，切换 router 时是否会变化值。

**Comment by noikiy** [comment]
![image](https://cloud.githubusercontent.com/assets/977243/25551241/b48c994c-2cb4-11e7-95ea-3bf5b3495f27.png)
App里是有isLoading这个变量的。
我注意到在router的before跟after之后，store内的数据并没有变化。
![image](https://cloud.githubusercontent.com/assets/977243/25551267/f0c07b0e-2cb4-11e7-815c-a2b06b79776c.png)

**Comment by airyland** [comment]
如果你解决不了，就建个 repo 来重现吧。提问时就应该把所有信息都列出来，而不是一点点贴代码。
