### ISSUE TITLE
Loading跟LoadingPlugin是不是会冲突？

### ISSUE THREAD

**Issue by noikiy** [airyland/vux#1341]
App.vue
![image](https://cloud.githubusercontent.com/assets/977243/25524341/bb64ce2e-2c3c-11e7-9306-ee6fb174a00b.png)
main.js
![image](https://cloud.githubusercontent.com/assets/977243/25524353/c71bd546-2c3c-11e7-9fa5-3247f1c1203f.png)
然后main.js里调用形式只有一种有效果
Vue.$vux.loading.show();可以
store.commit('updateLoadingStatus', { isLoading: true });不可以

**Comment by airyland** [comment]
Please don't create duplicate issue. You can reopen the old one.
