### ISSUE TITLE
search组件在submit后无法自动取消焦点

### ISSUE THREAD

**Issue by nali946** [airyland/vux#1342]
由于search组件获取到焦点之后会弹出键盘，键盘弹出后会影响到页面的fixed定位。我的处理方法是获取到焦点后跳转另外一个不存在fixed定位属性的单独一个搜索页。提交搜索之后再跳转回原本的页面，但是跳转回来的时候焦点依然在search中，也就是键盘仍保留在在页面中。必须点击页面才消失。而我找不到在跳转页面之前取消焦点的方法。是否有更加简便的方法可以使用，或者是添加一个手动取消焦点的方法。

**Comment by airyland** [comment]
看起来你的场景下完全没有必要 fix，使用 :auto-fixed="false" 禁止 fix 定位。

**Comment by nali946** [comment]
我是search组件与tabbar组件共存在一个页面中，获取焦点之后会把tabbar撑起来。search组件本身的fixed定位并没有问题。而且我在安卓4.1版本中测试，键盘存在的时候进行路由跳转也会影响到目标路径的scroller组件的height属性。

**Comment by airyland** [comment]
search 组件已支持 `setBlur` 方法。
