### ISSUE TITLE
Scroller控件横向滚动时，触摸点在Scroller的内容时整个网页不能上下滚动

### ISSUE THREAD

**Issue by s949492225** [airyland/vux#1344]
问题：Scroller控件横向滚动时，触摸点在Scroller的内容时整个网页不能上下滚动。
建议：希望滑动方向锁定后，不要拦截未锁定方向的滑动事件。
对比：android/ios原生控件以及淘宝H5版均不会出现此种情况。
目标：希望能够正确的处理滚动的方向的拦截问题。

谢谢

**Comment by airyland** [comment]
Scroller 已经废弃，so issue 关闭了。
