### ISSUE TITLE
提示demos/XNumber第五行报错

### ISSUE THREAD

**Issue by FlowerBoot** [airyland/vux#1345]
### 运行dev的报错日志

"D:\App\IntelliJ IDEA 2017.1\bin\runnerw.exe" D:\App\node\node.exe D:\App\node\node_modules\npm\bin\npm-cli.js run dev

> vux@2.2.1 dev D:\Code\vux-2
> node build/dev-server.js

 ERROR  Failed to compile with 1 errors11:38:13

 error  in ./src/demos/XNumber.vue

Syntax Error: Assigning to rvalue (108:8)

 @ ./src/demos/XNumber.vue 5:2-233
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080

 WAIT  Compiling...11:38:14

 ERROR  Failed to compile with 1 errors11:38:16

 error  in ./src/demos/XNumber.vue

Syntax Error: Assigning to rvalue (108:8)

 @ ./src/demos/XNumber.vue 5:2-233
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

###  运行buid的报错日志

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\App\\node\\node.exe',
1 verbose cli   'D:\\App\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vux@2.2.1~prebuild: vux@2.2.1
6 silly lifecycle vux@2.2.1~prebuild: no script for prebuild, continuing
7 info lifecycle vux@2.2.1~build: vux@2.2.1
8 verbose lifecycle vux@2.2.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle vux@2.2.1~build: PATH: D:\App\node\node_modules\npm\bin\node-gyp-bin;D:\Code\vux-2\node_modules\.bin;D:\app\color\product\11.2.0\client_1\bin;F:\app\color\product\11.2.0\client_1\bin;F:\app\color\product\11.2.0\dbhome_1\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\App\Java\jdk1.8.0_101\bin;D:\App\apache-maven-3.3.9-bin\apache-maven-3.3.9\bin;D:\App\sdk\platform-tools;D:\App\sdk\tools;C:\Program Files (x86)\Git\cmd;D:\App\node;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;D:\App\phantomjs\bin;C:\Users\color\AppData\Roaming\npm;C:\Users\color\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\color\AppData\Local\Programs\Python\Python36\;C:\Users\color\AppData\Local\Microsoft\WindowsApps;C:\Users\color\AppData\Roaming\npm\node_modules
10 verbose lifecycle vux@2.2.1~build: CWD: D:\Code\vux-2
11 silly lifecycle vux@2.2.1~build: Args: [ '/d /s /c',
11 silly lifecycle   'node build/build.js && rimraf docs/demos/v2/ && mkdirp docs/demos/v2 && cp -r docs/demos/temp/* docs/demos/v2/' ]
12 silly lifecycle vux@2.2.1~build: Returned: code: 1  signal: null
13 info lifecycle vux@2.2.1~build: Failed to exec build script
14 verbose stack Error: vux@2.2.1 build: `node build/build.js && rimraf docs/demos/v2/ && mkdirp docs/demos/v2 && cp -r docs/demos/temp/* docs/demos/v2/`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\App\node\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\App\node\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vux@2.2.1
16 verbose cwd D:\Code\vux-2
17 error Windows_NT 10.0.14393
18 error argv "D:\\App\\node\\node.exe" "D:\\App\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error vux@2.2.1 build: `node build/build.js && rimraf docs/demos/v2/ && mkdirp docs/demos/v2 && cp -r docs/demos/temp/* docs/demos/v2/`
22 error Exit status 1
23 error Failed at the vux@2.2.1 build script 'node build/build.js && rimraf docs/demos/v2/ && mkdirp docs/demos/v2 && cp -r docs/demos/temp/* docs/demos/v2/'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vux package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/build.js && rimraf docs/demos/v2/ && mkdirp docs/demos/v2 && cp -r docs/demos/temp/* docs/demos/v2/
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vux
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vux
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by airyland** [comment]
第五行是 template 不可能报这个错。并且 demo 站点也并没有报该错误。
另外，你使用的是 VUX 源码，如果你想做二次开发建议在 Mac 或者 Linux 下。

**Comment by zss007** [comment]
WAIT  Compiling...                                                           10:46:28 PM


Build completed in 0.377s



 ERROR  Failed to compile with 1 errors                                       10:46:28 PM

 error  in ./src/demos/XNumber.vue

Syntax Error: Assigning to rvalue (108:8)


 @ ./src/demos/XNumber.vue 5:2-233
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
我的也是报这个错，是在Mac上跑npm run dev

**Comment by zss007** [comment]
删掉demo_list.json里面的Calendar、XNumber、InlineCalendar就可以编译成功了，我今天尝试了下

**Comment by ganyusheng520** [comment]
ERROR  Failed to compile with 1 errors                                                                                                                      10:39:06 AM

 error  in ./src/demos/XNumber.vue

Syntax Error: Assigning to rvalue (108:8)


 @ ./src/demos/XNumber.vue 5:2-257
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

mac下运行npm run dev 报了这个错误，并且会陷入编译的死循环
在v2的分枝上

**Comment by airyland** [comment]
神奇的问题，本地暂时没有重现，帮忙排查一下？

**Comment by airyland** [comment]
只有在 cnpm 安装依赖的情况下能重现。删掉最后的 demo 就不会报错了，旧 demo 里 value.sync 导致的。
