### ISSUE TITLE
npm run dev的时候报错,报错如下

### ISSUE THREAD

**Issue by s949492225** [airyland/vux#1349]
error  in ./~/vux/src/components/popup-radio/index.vue

Syntax Error: Unexpected token (31:4)

  29 |   props: {
  30 |     placeholder: String,
> 31 |     ...cellProps(),
     |     ^
  32 |     ...radioProps()
  33 |   },
  34 |   methods: {

**Comment by airyland** [comment]
补充重现步骤，babel 配置后 reopen 当前 issue>

**Comment by woodytang** [comment]
我这边也是这个问题啊，是这样配置的 http://larabase.com/post/167 ~还是会报这个错

**Comment by airyland** [comment]
报错问题麻烦帖个 repo，信息不足以重现。
