### ISSUE TITLE
找不到 x-header 组件

### ISSUE THREAD

**Issue by silverd** [airyland/vux#135]
通过 npm install vux@dev 获取的代码，在 node_modules/vux/src/components 文件夾找不到 x-header 组件。但在您的 master 分支里却有，请问怎样通过 npm install 获取最新代码？

**Comment by airyland** [comment]
版本多少

**Comment by airyland** [comment]
更新到0.0.111可用

**Comment by silverd** [comment]
解决了，多谢
要用 npm install vux 来安装

README.md 里写的是 npm install vux@dev 这个就获取不到

**Comment by airyland** [comment]
@silverd 我的锅，前面确实是发布到dev，后面逐渐稳定就直接默认了。
