### ISSUE TITLE
scroller中的loadingContent配置能自定义标签或者组件进去吗？

### ISSUE THREAD

**Issue by xlkit456852** [airyland/vux#1351]
scroller中的loadingContent配置能自定义标签或者组件进去吗？比如我想在里面放一个spinner组件显示加载中图标应该如何配置？

**Comment by lichunqiang** [comment]
配合Slot实现。有demo的。https://github.com/airyland/vux/blob/v2/src/demos/PulldownPullup.vue#L4-L14

**Comment by xlkit456852** [comment]
感谢~
