### ISSUE TITLE
请问有把上拉、下拉刷新组件单独出来的计划吗？解放scroller组件

### ISSUE THREAD

**Issue by xlkit456852** [airyland/vux#1353]
如题，最近在做上拉、下拉刷新功能，由于业务需求关系，无可避免在scroller中有各种布局，也无可避免地出现各种问题，也看过很多相关的issue，也了解到作者对于这个问题也焦头烂额，准备停止维护scroller，我想如果可以有更专注于上拉、下拉刷新的组件，那就完美了，不知道作者有这个计划吗？

**Comment by airyland** [comment]
确实焦头烂额，其实目前可以考虑用其他第三方组件的。

**Comment by WM520** [comment]
上拉、下拉刷新有什么控件可用呢，这边好多问题

**Comment by z-z-k** [comment]
谁有空用finger-mover来实现一套scroller呢?现在vux里面的scroller除了体积太大没什么其他问题

**Comment by airyland** [comment]
@z-z-k finger-move 我也有在关注，文档齐全，功能基本也有。如果作者本身封装一个 vue 组件的话， VUX 就不做封装了。现在它还是相对早期开发中，再观望观望。
