### ISSUE TITLE
Tab组件 滚动条问题

### ISSUE THREAD

**Issue by Kyncc** [airyland/vux#1354]
安卓4.4.2 
Tab存在可看到滚动条 ,其他得安卓版本 没有此现象
Vux: V2.2.1
![image](https://cloud.githubusercontent.com/assets/22955719/25649466/5720ab8e-3008-11e7-8744-82e735ea74e7.png)

**Comment by Perry001-source** [comment]
我就这个tab组件还有一个问题，就是结合swiper组件的时候，当tab-item 比较多，可以左右滑动，当swiper滑动的时候怎么能把对应的tab-item显示在视图中，不用手动去滑来查看当前的swiper对应的是哪个tab-item

**Comment by ChristianYeap** [comment]
@zhaozhaoduan 求助个相关的问题，tab组件结合swipe组件的时候，怎么能让swiper-item内容的高度为自适应而不是写死呢？

**Comment by NameJie** [comment]
@zhaozhaoduan 

你可以给tab和swiper的v-mode绑定一个变量，然后swiper滑动一下，tab-item就激活了

**Comment by ghost** [comment]
@zhaozhaoduan 自动滑动tab-item，我做了一个。仿照你的tab组件源码做的。
<img width="292" alt="qq20170515-155917 2x" src="https://cloud.githubusercontent.com/assets/12068304/26047855/6d215cf2-3987-11e7-9cb0-2f5060724537.png">

**Comment by ghost** [comment]
@ChristianYeap 用CSS或者script去计算屏幕高度。

**Comment by Perry001-source** [comment]
@NameJie 能分享一下您自动滑动的demo吗？

**Comment by ChristianYeap** [comment]
@NameJie 两天前搞定了，计算高度并在切换时重新赋值，话说要是高度能自适应就方便了。。
