### ISSUE TITLE
Scroller组件中reset方法的疑问？？？

### ISSUE THREAD

**Issue by WWR1234567** [airyland/vux#1355]
Scroller组件中reset方法在官方文档中可以有三个参数(position, duration, easing)，但是实际上，为什么只作用了一个有人说明这是为什么吗？

**Comment by airyland** [comment]
没版本号没代码还错别字实在不想跟你说明为什么！！！

**Comment by ruijielou** [comment]
> 
> 
> Scroller组件中reset方法在官方文档中可以有三个参数(position, duration, easing)，但是实际上，为什么之作用了一个有人说明这是为什么吗？

![图片](https://user-images.githubusercontent.com/17963731/63256507-4c30b480-c2aa-11e9-85c2-93a52b77d77b.png)
