### ISSUE TITLE
如何根据现有tab组件实现左侧tab效果？

### ISSUE THREAD

**Issue by tiandao-dongguan** [airyland/vux#1356]
vux的tab组件是上下的，如何根据现有组件调整为左侧的呢？求指点。如图所示的效果：
![qq 20170504012548](https://cloud.githubusercontent.com/assets/12928741/25673244/40b3512e-3069-11e7-99bd-100bdd889b3a.png)

**Comment by airyland** [comment]
本来就不是一个东西，不要强求组件能这样扩展。自行根据需求实现。

**Comment by tiandao-dongguan** [comment]
@airyland 别关闭的这么快啊，老兄，我想看看大家伙是怎么实现的啊....

**Comment by airyland** [comment]
issue 不是拿来讨论业务实现的，既然不是组件问题没有一直开着的必要。

**Comment by tiandao-dongguan** [comment]
@airyland 需要一个论坛或者板块来交流业务问题了~

**Comment by airyland** [comment]
很快上线。
