### ISSUE TITLE
使用popup-picker, 在点击确定选择后再次打开picker，点击遮罩关闭时closeType仍为true

### ISSUE THREAD

**Issue by iwindfly** [airyland/vux#1357]
打开popup-picker,选择完一个item后点击确定，popup-picker关闭，再次打开popup-picker，点击后面遮罩关闭popup-picker，调用on-hide函数时，所传的closeType仍旧为true，导致业务逻辑出错。版本为2.2.0

**Comment by airyland** [comment]
https://github.com/airyland/vux/releases/tag/v2.2.1-rc.1
https://github.com/airyland/vux/issues/1209
