### ISSUE TITLE
datetime组件设置起始时间（低于2000年）不生效

### ISSUE THREAD

**Issue by cpxGithub** [airyland/vux#1358]
附上代码<datetime :start-date="startDate" :end-date="endDate" v-model="brith" @on-change="onBrith" title="请输入生日" confirm-text="确认"
        cancel-text="取消">
设置startDate小于2000不生效，初步定位_makeData函数年份取最小错误。ps能否提供点击其他按钮显示时间组件的prop，因为目前有这样的需求。

**Comment by airyland** [comment]
第一个问题，你可以先试着把 min-year 调小。因为存在两个时间范围，取交集。
第二个问题，看不懂你说的 prop 是想怎么用， 你可以用 slot:default 覆盖默认的样式。

**Comment by cpxGithub** [comment]
第一个问题目前我已经这样处理，第二个类似PopupPicker 组件props里面设置了一个show用于控制显示。
