### ISSUE TITLE
Cell组件加链接，能使用绝对地址吗？

### ISSUE THREAD

**Issue by LS1231** [airyland/vux#136]
### Version
npm 5.10.1

### Android or iOS, which browser?
ios

### Your Codes 

``` html
<cell title="关于我们" is-link v-link="{ path: 'http://www.baidu.com/'}"></cell>
```

**Comment by airyland** [comment]
Vux version?

**Comment by LS1231** [comment]
vux@0.0.108

**Comment by airyland** [comment]
cell是不处理链接的逻辑的，主要是为了方便不同需求。
v-link似乎是不能正常处理绝对路径的。你可以这样处理，一是用@click事件，手动设置location.href,  二是如果你这种路径多，还是这样用，但是在vue-router的beforeEach里判断是否有http, 若是手动设置location.href。

**Comment by LS1231** [comment]
好的。感谢
