### ISSUE TITLE
关于Previewer 中图片宽高的问题

### ISSUE THREAD

**Issue by zhangmin2020** [airyland/vux#1360]
我想使用 Previewer时 显示的图片是宽高不是固定死的  而是 能随着照片的宽高大小不同而不同
例如：
<div>
    <img class="previewer-demo-img" v-for="(item, index) in list" :src="item.src" width="100" 
        `@click="show(index)">`
    <previewer :list="list" ref="previewer" :options="options"></previewer>
  </div>
data () {
    return {
      list: [{
        src: `'https://placekitten.com/800/400',`
        w: 600,
        h: 400
      },
      {
        src: 'https://placekitten.com/1200/900',
        w: 1200,
        h: _900_
      }]
      }
    }

其中 list 数据中 宽:w 和 高:h  是必须项吗 ？  我不填 宽w 只填高h 时 图片是占满整个屏幕而且图片切换不了， 而只填 宽w 不填 高h `或者宽高都不填的情况下回报错，`

![_20170504220649](https://cloud.githubusercontent.com/assets/23025188/25707414/0597cb62-3116-11e7-8c2d-89a8260334c8.png)

请问 该如何解决   谢谢；

**Comment by Rockergmail** [comment]
+1 
https://github.com/airyland/vux/issues/1426

**Comment by Garfield-yin** [comment]
目前我的解决方法：重新自己实现previewer组件，增加一个photoswipe事件监听：
```  
        this.photoswipe.listen('gettingData', function(index, item) {
                if (item.w < 2 || item.h < 2) { // unknown size
                var img = new Image();
                img.onload = function() { // will get size after load
                    item.w = this.width; // set image width
                    item.h = this.height; // set image height
                   self.photoswipe.invalidateCurrItems(); // reinit Items
                   self.photoswipe.updateSize(true); // reinit Items
                }
                img.src = item.src; // let's download image
            }
        });
```

**Comment by hms181231** [comment]
能否在previewer组件里面集成这段代码  要不然每次都要自己重写这段代码.

**Comment by zhangmin2020** [comment]
@godfrey-yin  不好意思  这么久才看到回复。。我已解决这个问题。我觉得你写的方法的思路和我应该是差不多的吧。 不过我的解决方法是获取图片的宽高 然后放进 previewer 这个组件所需要的数据中。代码如：
`<previewer :list="filesList" ref="previewer"></previewer>`


``` js
props: {
      files: Array
    },
computed: {
      filesList() {
        let arr = []
        if(this.files) {
          this.files.forEach((item, index) => {
            let obj = {}
            obj.url = item.url + `?x-oss-process=image/resize,m_fill,h_${this.h * 2},w_${this.w * 2}`
            obj.src = item.url + `?x-oss-process=image/resize,w_750/auto-orient,0`
            let image = document.createElement('img')
            image.src = obj.src
            image.onload = function () {
              obj.h = image.height
              obj.w = image.width 
            }
            arr.push(obj)
          })
        }
        return arr
      }
}
```
