### ISSUE TITLE
InlineCalendar组件的render-function日期英文命名问题

### ISSUE THREAD

**Issue by mymmoonoa** [airyland/vux#1361]
第三个参数对象的日期英文不正确 
`day:10
disabled:false
isBetween:true
isCurrent:""
isToday:false
month:4
month_str:5
year:2017`
day是用来表示一周的某一天(0-6)。如Monday, Tuesday
date使用来表示一个月的某一天(1-31)。

**Comment by airyland** [comment]
有道理，不过涉及到命名问题改的话会有兼容问题

**Comment by mymmoonoa** [comment]
功能优先，命名有时间可以修正

**Comment by mymmoonoa** [comment]
@airyland 提个不是建议的疑问。 
在源代码 vux/src/components/x-dialog/index.vue中的`created ()`函数可以直接删掉的吧？我没看出来有什么作用。我本地实验这种方法父子组件互相传递改变数据时，没有created(), 功能都是ok的。
要是有什么用意的话，方便简单解释下不？
