### ISSUE TITLE
import vux 中的组件会出错

### ISSUE THREAD

**Issue by leftyhand** [airyland/vux#1363]
作者你好，我现在出现了使用vux的问题，当我import XInput组件的时候，在template 中使用，会出现Unexpected token =这种错了，能问一下这种问题怎么解决？

**Comment by airyland** [comment]
建议你直接建个 repo 发个链接重现。

1.上个 issue 我说了，**麻烦提个好问题**。
2.使用有问题先帖使用代码
3.报错请帖详细信息
