### ISSUE TITLE
scroller 组件中的a标签会失效问题?

### ISSUE THREAD

**Issue by WWR1234567** [airyland/vux#1364]
version: 2.2.1
question: 在scroller 中的这个a标签会失效，偶尔会出现第一次点击会成功跳转到百度，然后按浏览器返回建，返回，再次点击又失效了。(不知道怎么粘贴代码进来，请见谅)
代码如下;
```
<template>
  <div class="designList">
  	<a href="http://www.baidu.com">去百度？</a>
		<scroller lock-x >
			<div class="" style="height: 1900px;">
				<a href="http://www.baidu.com">去百度？</a>
			</div>
		</scroller>
  </div>
</template>
<script>
  import { Scroller } from 'vux'
 export default {
    name: 'designList',
    components: { 
      Scroller
    }
  }
</script>
```

**Comment by xlkit456852** [comment]
将你的代码前后用三个`包着，我也出现这个问题，但有的机型可以跳转，有的机型不能跳转，等大大回答。。

**Comment by xlkit456852** [comment]
在scroller加上:prevent-default="false"试试~我刚刚成功了~

**Comment by WWR1234567** [comment]
我这个加上：prevent-default = false <strong>也不行</strong> 
等待大大的回到。。。

**Comment by cjq38679093** [comment]
我之前也遇到点击href="tel:xxxxx"失效。。最后还是用@click调用事件..(url) {location.href=url}

至少能先解决当前问题

**Comment by airyland** [comment]
你上面的代码有一个 div 标签未闭合。用你的代码在一台 iPhone和一台红米 上测试都是正常的。不正常的机型是哪个？

**Comment by WWR1234567** [comment]
chrome浏览器手机调试模式，微信浏览器。
