### ISSUE TITLE
china_address未压缩就打包在app.js中

### ISSUE THREAD

**Issue by ckdlbc** [airyland/vux#1365]
Analyzer返回的结果，china_address这几个文件均未压缩
![image](https://cloud.githubusercontent.com/assets/20680413/25734519/95bd731a-3196-11e7-86a0-54c90199dda4.png)

**Comment by airyland** [comment]
你这是整个组件库打包了吧，确定有配置 vux-loader?

**Comment by ckdlbc** [comment]
webpack.base.conf.js里已经配置了vux-loader
![image](https://cloud.githubusercontent.com/assets/20680413/25734708/592bd2c8-3198-11e7-8f23-4f5244ff55d6.png)

**Comment by ckdlbc** [comment]
找到原因了，import{ AlertPlugin } from 'vux'，这里的花括号与import之间少了空格，导致打包入app.js
![image](https://cloud.githubusercontent.com/assets/20680413/25735524/90176f76-319e-11e7-9010-dd0a8b68e175.png)

**Comment by ckdlbc** [comment]
@airyland 谢谢！

**Comment by airyland** [comment]
建议开启 eslint 来规范代码，不过没有空格的情况在 vux-loader@1.0.61 已经支持了。
