### ISSUE TITLE
组件重复打包，vux组件如何单独打包

### ISSUE THREAD

**Issue by cjq38679093** [airyland/vux#1368]
**Version**
"vux": "^2.2.0"

**Android or iOS**

不涉及

**Your Codes**
业务组件有用到scroller, 业务组件中引入代码：
```
import {
  Scroller,
  Swiper,
  SwiperItem,
  Group,
  Cell,
  CellBox,
  Flexbox,
  FlexboxItem
} from 'vux'
```

每个业务组件引用到的vux组件都单独打包到业务组件了。这样明显加大了包大小。怎么样才能把那些共用的vux组件打成一个独立包？谢谢！

![analyze1](https://cloud.githubusercontent.com/assets/23032426/25770557/002857b8-326b-11e7-8802-58ae34221e7e.PNG)

**Comment by cjq38679093** [comment]
通过在main.js里注册成全局组件解决了。

**Comment by airyland** [comment]
是的，code split 会导致不同路由依赖重复打包。3.0 将优化成无声明使用自动全局注册使用多次的组件。

**Comment by shanjixiaboss** [comment]
up一人吃力
