### ISSUE TITLE
提示组件引用路径不对

### ISSUE THREAD

**Issue by ignaciozhuzhu** [airyland/vux#1369]
你好,本地运行demo后,如在src/demos/ 下面再添加一层文件夹路径,之后再写组件页面(xx.vue)
import { Selector, Group } from 'vux'
会导致错误提示路径不对.

These relative modules were not found:

* ../components/selector/index.vue in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/demos/demo01/List.vue
* ../components/group/index.vue in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/demos/demo01/List.vue

--------------------------------------------------------------------------------------------------------------------
尝试后发现如将src下的components和style文件夹复制到src/demos文件夹下,该问题可解决.

请问,有没有办法可以做配置,以达到在demos文件夹下不管几层都可以直接引用到vux?
不知道我这样表述是否清楚.

**Comment by airyland** [comment]
你初始化个新项目怎么引用都可以，这是源码，目录结构不会修改。

**Comment by ignaciozhuzhu** [comment]
谢谢。仔细检查源码后发现是因为vux-loader 把文件路径写死了。
vux-loader/blob/master/src/script-loader.js
 ` const isVuxComponent = this.resourcePath.replace(/\\/g, '/').indexOf('/vux/src/components') > -1`
而我本地已经把vux文件夹改名为v。
所以我去改了这行代码为获取当前src上级解决。
