### ISSUE TITLE
图片上传有计划添加进来吗？

### ISSUE THREAD

**Issue by bulolo** [airyland/vux#137]
http://weui.github.io/weui/#/cell
这个里面的图片上传有计划添加进来吗？

**Comment by airyland** [comment]
你是指纯布局还是把图片预览上传也做了？

**Comment by bulolo** [comment]
纯布局，官方是直接放到cell

**Comment by bulolo** [comment]
当然，要是图片预览上传有的话最好啦。哈哈哈。

**Comment by airyland** [comment]
上传要配合JS SDK，而且JS SDK其实不支持这样的进度显示。如果用原生上传，Android下又用不了了。

所以暂时就只支持布局吧 :joy:

**Comment by bulolo** [comment]
安卓微信刚更新了X5内核。不知道会不会解决这些问题。http://mp.weixin.qq.com/s?__biz=MjM5NDAxMDg4MA==&mid=2650959241&idx=1&sn=e1b69161311fc0f0442911420f1b35de&scene=1&srcid=0425rqoTlHXGaFzl8kGRYVaT#wechat_redirect

**Comment by airyland** [comment]
不能上传不是浏览器内核问题，是Android内核的问题。Android 4.4+移除了webview的文件上传功能。
:sweat:

**Comment by unclay** [comment]
是4.4，4.4.1，4.4.2的webview移除了文件上传功能，被别人鄙视后4.4.3又加回来，所以目前只有4.4，4.4.1，4.4.2三个版本不支持文件上传

**Comment by airyland** [comment]
@unclay 这样的情况更复杂了，想要兼容所有版本只能统一用JS SDK，但是对于非微信外的浏览器又得用另一套上传，:sad:

**Comment by progrape** [comment]
@airyland X5 内核帮忙补了这个坑，如果使用场景只是在微信内的话，可以放心使用 `<input type="file"/>`

**Comment by ohohco** [comment]
我觉得挺好的，建议可以整合dropzone。这个基本都会用到

**Comment by airyland** [comment]
@ohohco 醒醒，移动端哪来的拖拽上传？

**Comment by ohohco** [comment]
@airyland 我桌面也用vux，虽然有些桌面不能用。因为内部系统，要求不需要那么高。http://www.dropzonejs.com/ 是说的这个

**Comment by airyland** [comment]
@ohohco 我知道，vux是完全不考虑PC端的，会导致体积变大，不会支持拖拽上传。

**Comment by airyland** [comment]
目前WeUI的样式少了一个删除操作，因为允许上传多张而且会有上传失败的情况，那么应该允许用户删除某些不想要的图片。

**Comment by airyland** [comment]
Moved to #139
