### ISSUE TITLE
x-textarea组件max

### ISSUE THREAD

**Issue by zss007** [airyland/vux#1372]
原先组件的currentValue方法用newVal(字符串)和max(数字)进行对比，应该改成`if (this.max && newVal && newVal.length > this.max) {`吧，不然如果初始化页面的时候传入字符串长度超过最大长度就没有长度限制了。

currentValue (newVal) {
      if (this.max && newVal > this.max) {
        this.currentValue = newVal.slice(0, this.max)
      }
      this.$emit('input', this.currentValue)
      this.$emit('on-change', this.currentValue)
    }

**Comment by airyland** [comment]
可 pr

**Comment by lichunqiang** [comment]
Merged #1373
