### ISSUE TITLE
cell-box里面包一层 div 影响自由度

### ISSUE THREAD

**Issue by terranc** [airyland/vux#1375]
不是很明白现有的 cell-box 里在 slot 外层包一个 div 是意义是什么？导致里面的元素先要写样式把这个 div 置100%宽。

**Comment by greedying** [comment]
这个确实如此。所以我当时以为是忘记加那个class了

**Comment by lanrain** [comment]
这个确实如此，导致一致要覆盖，建议去掉吧

**Comment by terranc** [comment]
vux 一路用下来，发现有很多地方都有这些不知道用途是什么的 div，才做了两个项目，不知道是不是有自己没有考虑到的原因，也不敢轻易 PR，求解救啊。

**Comment by graysheeep** [comment]
看了下代码
`.vux-cell-box > div {
  padding-right: 13px;
}`
是为了加个padding吧

**Comment by terranc** [comment]
@greedying 那这一句样式也更有问题了啊，为什么一定认为有`padding-right`呢，这是为了与右侧箭头保持一定距离，现在这样没有箭头，内容也必定有间隔在。

应该改写下 css 一样能达到目的吧：
```css
.weui-cell_access.vux-cell-box {
    padding-right: 26px;
}
```



![image](https://user-images.githubusercontent.com/224353/26862543-c566eb62-4b7e-11e7-8a16-081e94ce3113.png)
