### ISSUE TITLE
hash模式下，微信jssdk分享失败

### ISSUE THREAD

**Issue by easonzhuyi** [airyland/vux#1378]
偶现问题，jssdk调试模式有时监听不到签名成功或者失败，点击分享会直接关闭pannel，刷新页面就会配置成功，求助

**Comment by easonzhuyi** [comment]
网络原因定位不了：4g环境分享ok，切到wifi，再分享也是ok的。在当前wif连接的状态，直接关闭，重新登陆进去，分享就不行了。

**Comment by airyland** [comment]
明显和 VUX 无关。如果你用的是内置的 WechatPlugin 该插件也是基于官方 jssdk 代码。

分享有问题应该是微信客户端的问题，不过这种问题是无法找到微信团队去解决的。。
