### ISSUE TITLE
请问为什么less文件的修改无法影响界面样式

### ISSUE THREAD

**Issue by ChristianYeap** [airyland/vux#1379]
如题，
比如我要修改一个选中时的颜色，
通过修改某个less文件后颜色值，
界面并没有如期展示我修改后的颜色，
相反的，样式表都找不到这个修改内容。。
目前我的解决方式是在界面的vue文件里，
编写关联性更强的样式来进行重写...
虽说解决了问题，但还是一脸懵逼，
求老司机解答怎样修改less才能生效。。

**Comment by airyland** [comment]
说明下你具体如何修改重开当前 issue。

**Comment by ChristianYeap** [comment]
@airyland 我需要修改的样式为
`.weui-tabbar__item.weui-bar__item_on .weui-tabbar__label`
是一个颜色值，默认是微信绿，希望能改成红色
于是我查找styles文件夹，发现颜色定义为
`@tabbar-text-active-color`
并在variable.less 找到这个定义值
修改后为我需要的红色，
但是界面并没有生效，
并且通过审查元素查看是，
颜色值依然为 微信绿。。
