### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by mpersonal** [airyland/vux#138]
git clone下来后，npm run dev及npm run build都报错

ERROR in ./src/filters/friendly-time.js

  error  camelcase  Identifier 'day_diff' is
  C:\code\vux\src\filters\friendly-time.js:4
    let day_diff = Math.floor(diff / 86400)

ERROR in ./src/components/popup/popup.js

  error  camelcase  Identifier 'F_tap' is not in camel case
  C:\code\vux\src\components\popup\popup.js:2:5
  var F_tap = require('./tap')

**Comment by airyland** [comment]
麻烦执行下 npm ls， 把结果发给我，怀疑是依赖升级后的问题。

**Comment by mpersonal** [comment]
UNMET PEER DEPENDENCY phantomjs@>=1.9

npm ERR! peer dep missing: phantomjs@>=1.9, required by karma-phantomjs-launcher
@0.2.3

**Comment by airyland** [comment]
感谢反馈，已经修复
