### ISSUE TITLE
请问less文件怎么修改才会生效

### ISSUE THREAD

**Issue by ChristianYeap** [airyland/vux#1380]
我需要修改的样式为
.weui-tabbar__item.weui-bar__item_on .weui-tabbar__label
是一个颜色值，默认是微信绿，希望能改成红色
于是我查找styles文件夹，发现颜色定义为
@tabbar-text-active-color
并在variable.less 找到这个定义值
修改后为我需要的红色，
但是界面并没有生效，
并且通过审查元素查看是，
颜色值依然为 微信绿。。

现在虽然找到了解决办法：
在APP.vue中，通关样式的重写来进行修改。
但是没有解决根本问题。。
是我改的地方不对还是配置有问题，求解答
VUX版本是 2.2.1

**Comment by airyland** [comment]
reopen 是 reopen 不是让你重开 issue。

文档有颜色配置的说明，为什么不先按照文档来操作？
你修改 vux 源码以后升级怎么办，重新修改一次源码么？

**Comment by ChristianYeap** [comment]
@airyland 我先改回来，然后按着文档操作一遍吧。。
