### ISSUE TITLE
ActionSheet组件，可能需要在文档中，稍微提示一下配置menus不要用非主流的key

### ISSUE THREAD

**Issue by wwz348627642** [airyland/vux#1381]
如酱紫配置（谷歌浏览器），将导致循环的列表展示不是预期的样子，应该是不同浏览器for in 循环解析不同引起
 menus: {
     '0.noop': '性别修改',
     '1': '保密',
     '2': '男',
     '3': '女'	
}
最终展现出来的列表为
<ul>
  <li>保密</li>
  <li>男</li>
  <li>女</li>
  <li>性别修改</li>
</ul>

“性别修改”本来是想作为title存在.

**Comment by airyland** [comment]
所以在非 Chrome 下是正常的？

**Comment by wwz348627642** [comment]
IOS，微信中也不正确

**Comment by airyland** [comment]
支持 slot:header，这样方便使用 html。
