### ISSUE TITLE
sroll里面包含一个轮播图下面列表数据显示不全

### ISSUE THREAD

**Issue by zhenghuochao** [airyland/vux#1383]
<template>
  <div>
    <scroller :lock-x="true" height="-100"  use-pulldown :use-pullup="true">
      <div >
        <swiper :list="demo02_list"  :show-desc-mask="false"   dots-position="center">  
        </swiper>
        <h1>我是首页</h1>
        <ul>
          <li v-for="i in 100">{{i}}</li>
        </ul>
      </div>
    </scroller>
  </div>
</template>

**Comment by lichunqiang** [comment]
这。。。你觉得应该改怎么帮你解决呀。。。
