### ISSUE TITLE
tab/tab-item $parent.updateIndex undefined报错

### ISSUE THREAD

**Issue by yuezheng2006** [airyland/vux#1387]
首先报错如下
![image](https://cloud.githubusercontent.com/assets/16177642/25811744/c8b950e2-3446-11e7-93f7-ac4b948851e2.png)

使用代码如下：
```
<template>
  <div class="main" :class="isShare?'padding-share':''">
    <div style="width: 100%;overflow:scroll;-webkit-overflow-scrolling:touch;">
      <tab style="width:100%;" bar-active-color="#fc378c" active-color='#fc378c' :line-width="4">
        <tab-item>我是tab1</tab-item>
        <tab-item selected>我是tab2</tab-item>
      </tab>
    </div>
  </div>
</template>
<script>
  import {
    Tab,
    TabItem
  } from 'vux'

  export default {
    components: {
      Tab,
      TabItem
    },
    data() {
      return {
        // isShare: true,
        // dataObj: {}
      }
    },
    filters: {},
    methods: {

    }
  }
</script>
```
自己项目中vux-loader使用和不适用两种情况都试了,都是报这个错误 
具体原因自己没有查到 问下各位有遇到这种情况的么？

**Comment by lichunqiang** [comment]
你的代码本地运行了下，没有报错。

首先你自己应该先尝试debug进去，查下为啥报 `$parent.updateIndex is not a function`

**Comment by yuezheng2006** [comment]
![image](https://cloud.githubusercontent.com/assets/16177642/25834036/e74256ec-34a7-11e7-80ae-146ccffd4bdb.png)
我这里debug显示tab-item 的this.$parent找到的却是最外层<div class="main">这个el

**Comment by lichunqiang** [comment]
把vux什么的版本号报一下吧。确实本地按照你贴出来的代码是无法复现的。

**Comment by airyland** [comment]
`console.log(Tab)`  看看 Tab。你确定只有一个报错？

**Comment by yuezheng2006** [comment]
我更新了vux版本 现在没有问题了  我刚log了Tab和TabItem内容  mixins挂载都没有问题  我本地搭建环境没找出啥问题  我后续会将我的工程目录结构开放出来  感谢各位大神帮助！
