### ISSUE TITLE
配置vux-loader的less-theme插件来替换颜色

### ISSUE THREAD

**Issue by XfLoops** [airyland/vux#1392]
鉴于现有的issues中没有一个issue清楚地介绍怎么配置less-theme插件来配置颜色，作为刚接触vux的我来讲，看完一遍issue，以及一点带过的官网上的教程，还是一脸懵:fearful:。现在知道怎么做了，就发一个详细的教程贴，如果有错误的话还请指正。

#### 准备工作： 新建theme.less
![qq20170510-123019](https://cloud.githubusercontent.com/assets/7624050/25883351/84f6d014-357c-11e7-8b82-e7aca1d44c7c.png)

#### 第1步
![qq20170510-113310](https://cloud.githubusercontent.com/assets/7624050/25882237/a88d5ef6-3574-11e7-887a-94961c3a829b.png)

#### 第2步
![qq20170510-113410](https://cloud.githubusercontent.com/assets/7624050/25882241/ada54840-3574-11e7-83bb-9428100d8417.png)
第2步说明：如果不在App.vue（或者其他vue组件）中引入theme.less的话，当theme.less中有改动时，页面中的颜色不会发生变化，需要重新运行`npm run dev`颜色才会生效。而进行了第2步之后，当theme.less中有改动时，页面会自动改变的。

需要配置颜色的同学，试试看是不是这样就行了？我这里是行了通了......

**Comment by airyland** [comment]
没有相关 issue 是因为大家没有遇到和你一样的问题吧。。

本地测试是不需要第2步的，而且第一步相对根目录地址就行。

**Comment by XfLoops** [comment]
@airyland  如你所说：

#### 1.  把path改为相对路径  
如果把path改为相对路径(尝试过多种写法)，如下：
```
// 配置颜色
let lessTheme = {
  name: 'less-theme',
  path: path.relative(__dirname, '../src/assets/theme.less')       //  写法一，报错
  // path: path.relative(__dirname, './src/assets/theme.less')     //  写法二，报错
  // path: path.relative(__dirname, 'src/assets/theme.less')       //  写法三，报错
  // path: path.relative(__dirname, '../../src/assets/theme.less') //  写法四，报错
  // path: path.resolve(__dirname, '../src/assets/theme.less')     //  绝对路径写法，正确
}
```
会报找不到文件的错误，如下所示：
![qq20170510-124224](https://cloud.githubusercontent.com/assets/7624050/25883562/30c5d36c-357e-11e7-80a7-a36c8957034d.png)

行不通哇。 咋回事呢？

#### 2.  本地测试是不需要第2步的

行不通。因为如果不在组件中引入theme.less，那么改动theme.less中的颜色之后，页面上颜色并没有发生变化，除非重新运行`npm run dev`。我这里是在 App.vue中引入的，这样theme.less中的变化会及时反应到页面上。

- 先在组件中引入theme.less
![qq20170510-113410](https://cloud.githubusercontent.com/assets/7624050/25883786/eb2cc692-357f-11e7-8bfd-b4bdc058f11d.png)
-  改变颜色
![qq20170510-130443](https://cloud.githubusercontent.com/assets/7624050/25883944/4084f69a-3581-11e7-9278-3722c2ff49ed.png)
-  页面及时变化
![qq20170510-130113](https://cloud.githubusercontent.com/assets/7624050/25883909/e985822e-3580-11e7-9f2c-41b771163d67.png)




综上：你说的这2点在我这里并不起作用。。是不是我哪里用错了？:dizzy_face::dizzy_face::dizzy_face:

**Comment by airyland** [comment]
路径直接相对根目录路径

```
{
    name: 'less-theme',
    path: 'src/theme.less'
}
```

第二点在 vux-loader 里已经加到 webpack 的 dependency 里了，理论上应该会在修改时触发 recompile

https://github.com/airyland/vux-loader/blob/master/src/index.js#L82

**Comment by jessguo** [comment]
我在 src/styles/theme.less 声明了变量
在另一个组件
·
.abc  {
    color: @blue;
·
然后就报错了 配置和报错如下  路径没错 loader也都安装了 什么原因啊
`
var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')
var vuxLoader = require('vux-loader')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

let lessTheme = {
    name: 'less-theme',
    path: 'src/styles/theme.less'
}

const originalConfig = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src')
    }
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}
const webpackConfig = originalConfig 
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui',lessTheme]
})
`

`
ERROR in ./~/_css-loader@0.28.4@css-loader?{"minimize":false,"sourceMap":false}!./~/_vue-loader@12.2.2@vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4a399704","scoped":false,"hasInlineConfig":false}!./~/_less-loader@4.0.5@less-loader/dist/cjs.js?{"sourceMap":false}!./~/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=styles&index=0!./src/components/vux.vue
Module build failed: 

.abc  {
    color: @blue;
         ^
Variable @blue is undefined
      in C:\Users\Administrator\Desktop\test\mytest\src\components\vux.vue (line 23, column 11)
 @ ./~/_vue-style-loader@3.0.1@vue-style-loader!./~/_css-loader@0.28.4@css-loader?{"minimize":false,"sourceMap":false}!./~/_vue-loader@12.2.2@vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4a399704","scoped":false,"hasInlineConfig":false}!./~/_less-loader@4.0.5@less-loader/dist/cjs.js?{"sourceMap":false}!./~/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=styles&index=0!./src/components/vux.vue 4:14-466 13:3-17:5 14:22-474
 @ ./src/components/vux.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
`

**Comment by saint816** [comment]
谢谢，完美解决
