### ISSUE TITLE
webpack配置vux-loader报错

### ISSUE THREAD

**Issue by ArthurFree** [airyland/vux#1393]
您好，
    我在配置的webpack中的webpack.base.conf.js文件中加入了
```
const vuxLoader = require('vux-loader');
module.exports = vuxLoader.merge(webpackBaseConfig, {
    plugins: ['vux-ui'],
});
```

这段代码后，会报如下错误：

## 报错信息
![image](https://cloud.githubusercontent.com/assets/9547013/25882176/27d521a4-3574-11e7-87be-95f7c8167904.png)

## 复现步骤

项目地址： https://github.com/ArthurFree/vue-template-boilerplate

执行如下命令：
```
npm install
npm install vux --save
npm install vux-loader --save-dev
```

在`build/webpack.base.conf.js`文件中添加
```
const vuxLoader = require('vux-loader');
module.exports = vuxLoader.merge(webpackBaseConfig, {
    plugins: ['vux-ui'],
});
```

执行`npm run dev`后，终端中会报出图上的错误。

这个项目是照着vue-cli造的轮子
其间，我尝试了直接使用vue-cli直接生成项目模板，然后添加vux以及vux-laoder，未报错
使用vux的项目模板生成的项目也不会报错，怀疑可能是自己配置有问题，但是没有找到问题所在
不明白图上这个报错是因为什么导致的

**Comment by airyland** [comment]
把 webpack.base  里的 babel-loader  的 options 删掉试试。原因未知，但是babel 配置尽量写到 .babelrc 里。

**Comment by ArthurFree** [comment]
恩恩，删掉以后就可以了，非常感谢
