### ISSUE TITLE
range组件 动态改变min、max报错

### ISSUE THREAD

**Issue by MaxBlackk** [airyland/vux#1394]
动态改变range组件的min和max值时报错：
[Vue warn]: Error in callback for watcher "min": 
(found in <Range> at /xxx/node_modules/vux/src/components/range/index.vue)

vue.esm.js?65d7:1447 TypeError: Cannot read property 'reInit' of undefined

**Comment by airyland** [comment]
VUX version, please.

**Comment by 1165506270** [comment]
range组件change事件不生效`<range  :value="percent" @change="playChange" class="palyRange"></range>`

**Comment by airyland** [comment]
As document says, use `on-change` instead of `change`.

**Comment by MaxBlackk** [comment]
"vux": "^2.2.1-rc.5" @airyland

**Comment by MaxBlackk** [comment]
在第一个range组件的input事件里动态改变的第二个range组件的min @airyland

**Comment by airyland** [comment]
<del>range 没有 input 事件。</del>有问题上代码。demo 里就有动态改变 min 的例子并不会出错。

**Comment by MaxBlackk** [comment]
min和max的问题已解决，应该是我用法错了。
range的change事件我试了@on-change不起作用，就用的@input。
range不支持动态step么？当我滑动改变curMoney时，step值变化了，但是滑动的时候仍然是按的原来的step，如下图：
![image](https://raw.githubusercontent.com/wyyyyn/test/master/WX20170510-192516%402x.png)
![image](https://raw.githubusercontent.com/wyyyyn/test/master/WX20170510-193140%402x.png)

**Comment by WM520** [comment]
能实时改变min的数据么，和看视频的播放条一样

**Comment by airyland** [comment]
@WM520 看视频 min 都是 0 哪来的实时改变？况且 min max 本来就支持动态设置。

**Comment by WM520** [comment]
我用range组件，@on-change 方法不调用，
<img width="369" alt="01203b04-79d1-491f-93d4-06274ccae48e" src="https://cloud.githubusercontent.com/assets/16432354/26232456/ebb3c10a-3c88-11e7-9ae4-5eee455d0bdb.png">
是不是我上次在这组件把试试把源码这里的 var 改成 let

文件：src/components/range/range/lib/main.js原因

**Comment by WM520** [comment]
版本是2.2.1

**Comment by WM520** [comment]
![Uploading 529CC516-6577-46F6-B2BB-2E263DC0FD1B.png…]()
这个官网的demo，这方法在input value 变化的时候，并没有走啊

**Comment by WM520** [comment]
@on-change的方法

**Comment by WM520** [comment]
研究你源码半天了，这组件貌似在2.2.1没有用on-change 像外面发事件呢

**Comment by WM520** [comment]
觉得在这边少个代码

在src range文件夹，index.vue，96行，添加this.$emit('on-change', val)

**Comment by airyland** [comment]
@WM520 我看了下，官网 demo 是正常的

![snip20170519_1](https://cloud.githubusercontent.com/assets/559179/26243407/5cf9fca0-3cbe-11e7-80d5-4e93d9776ebd.png)

**Comment by WM520** [comment]
ok
