### ISSUE TITLE
popup，在ios的微信webview上点击遮罩层时出现白色的背景一闪而过的现象

### ISSUE THREAD

**Issue by Mageenz** [airyland/vux#1396]
公司网速太慢了，传不上gif，等会再传上来。

如果在遮罩层上长按，则弹出javascript的对话框，这是我哪里用错了吗？

**Comment by airyland** [comment]
用你有问题的手机访问 vux.li 的 popup demo，看有没有问题。

长按出现对话框应该是遮罩是 a 元素的原因。这个后面可以改。

**Comment by Mageenz** [comment]
@airyland 访问demo倒是没问题，的确是a元素的原因，但是我的使用方式跟demo里的也是一样的呢，怎么会出现这样的情况。怎么解决呢？

![11](https://cloud.githubusercontent.com/assets/17400576/25902590/930769a2-35cc-11e7-829e-9fa9d0659319.gif)

**Comment by machao1990** [comment]
![11](https://cloud.githubusercontent.com/assets/17400576/25902699/e6e7c18e-35cc-11e7-914f-f94db3803d71.gif)

**Comment by airyland** [comment]
版本多少？有没有用 v-transfer-dom

**Comment by Mageenz** [comment]
@airyland  vux@2.2.1版本，之前是没有用v-transfer-dom,我现在加上了v-transfer-dom，结果也是一样的。

这是我这个有问题的链接：
http://www.youtenet.com/chayinjiushui/3728.htm

**Comment by airyland** [comment]
手机上可以重现。不过页面元素复杂不好排查，你最好简化一下代码帖个可以本地重现的代码。

**Comment by Mageenz** [comment]
@airyland 感谢你的持续关注。我刚才回头看了一下我这边的css，发现问题了，有个a:active{background-color:#fff;}，去掉就没问题了，真是不好意思啊😓😓
