### ISSUE TITLE
Search组件里面的搜索字样及放大镜的icon 不上下居中对齐

### ISSUE THREAD

**Issue by hipi** [airyland/vux#1397]
vux版本```"vux": "^2.2.1"```
```<search position="absolute" auto-scroll-to-top top="0"  ref="search"></search>```

![image](https://cloud.githubusercontent.com/assets/22478003/25895247/abbd517a-35b1-11e7-9a26-5840e5433a5f.png)

**Comment by airyland** [comment]
缺少重现环境说明。
