### ISSUE TITLE
$t没有报错，但是一直undefined

### ISSUE THREAD

**Issue by haishengXie0712** [airyland/vux#1400]
组件的代码是拷贝下面地址的
[https://github.com/airyland/vux/blob/v2/src/demos/Actionsheet.vue](url)
然后在代码中并没有发生错误，但是$t没有报错，但是都是undefined。
我已经用了npm install,然后根据文档
1.如果你只是调用中文语言的vux组件，那么你不需要做任何配置。
然后配置改成了

`module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [{
    name: 'vux-ui'
  }]
})`

**Comment by airyland** [comment]
既然没有用 i18n，就不要在代码里使用 $t，不要直接复制代码。你是不是也复制了 main.js 的代码？

**Comment by haishengXie0712** [comment]
main.js的我没有复制，我想用i18n，但是我查看文档配置里面说
1.如果你只是调用中文语言的vux组件，那么你不需要做任何配置。
所以我就没有写配置，而且写了配置也不行

**Comment by airyland** [comment]
我看不懂你想做什么，你想用国际化，那就需要配置。文档写得很清楚，不需要配置说明你不需要国际化，然而你上面又说你要用 i18n。

你没有任何配置又复制了 $t 函数，居然也没有报错。

开个 repo 来重现吧，这样说不清楚。

**Comment by haishengXie0712** [comment]
@airyland 我要的很简单，就是在vux里面拷贝的demo代码，直接拷贝到我的组件里面是可以用，就是直接就有文字的，而不是一个个的undefined就好了。哪怕他只有中文，不需要国际化的

**Comment by airyland** [comment]
那么你直接把 $t 干掉，前面的 : 也删掉就好了。

**Comment by haishengXie0712** [comment]
这样显示出来就都是英文的，这里我还想她是中文的，和文档里面的一样

**Comment by airyland** [comment]
那么你把英文改成中文就好了。。
