### ISSUE TITLE
[checklist] @checklist-icon-active-color：#3cafff 修改样式不生效

### ISSUE THREAD

**Issue by hipi** [airyland/vux#1403]
发现是图中第一个样式覆盖了
![image](https://cloud.githubusercontent.com/assets/22478003/25931596/bf03f156-363f-11e7-989c-1664defe16b8.png)

**Comment by hipi** [comment]
后面颜色我强制改了
![image](https://cloud.githubusercontent.com/assets/22478003/25935047/a49eb5f8-3653-11e7-8b52-cc5a630a48bb.png)
如何更改后面的icon 为```<icon type="success-circle"></icon>```

**Comment by ChristianYeap** [comment]
@chenyeah 去看下官方文档里的 “ 颜色配置 ” 这块，照着走一遍会有收获的
