### ISSUE TITLE
关于tabbar在iphone上的一些问题

### ISSUE THREAD

**Issue by 563325028** [airyland/vux#1407]
我的网页使用了tabbar 在安卓上很正常 一直在最下面 网页拉下也没事 但是在苹果端tabbar只会固定在初始大小的最下面 网页往下一拉tabbar不会固定在屏幕最下面 而是往下拉就不见了 想问一下这个会跟vux版本有关么 我的版本可能有点低 但是暂时没法更新

**Comment by Mageenz** [comment]
我觉得你至少得提供一下版本号

**Comment by 563325028** [comment]
2.0.13

**Comment by airyland** [comment]
tabbar 的定位默认是 absolute，适合 viewbox 这类 100% 高的布局。你可以试试直接覆盖样式用 fixed 定位。
