### ISSUE TITLE
如何结合第三方的验证插件使用

### ISSUE THREAD

**Issue by zhangqxiaoqi** [airyland/vux#1408]
vux内置了一些验证，效果很棒，但有时候我需要更丰富的验证，可以通过第三方来验证么？可否告知使用方式

**Comment by airyland** [comment]
暂时没有研究过。你希望使用哪个第三方？

**Comment by zhangqxiaoqi** [comment]
大神回复好快，感谢回复。
研究了下市面上vue的验证，由于VUX已经封装了，很难控制里面的dom。我想了下，我可以写个公共方法用来处理页面里的$refs判断是否通过验证。
另外，大神可否使XTextarea同样具备X-Input 的验证能力，是否开启为空验证，因为表单验证，textarea也是常备的，这样整个表单的验证体验就一致了。

**Comment by airyland** [comment]
Move to #1346
