### ISSUE TITLE
关于tabbar位置的建议

### ISSUE THREAD

**Issue by tianyong90** [airyland/vux#141]
个人觉得，tabbar一般用于手机页面询问菜单，其默认位置应该固定于屏幕询问为好，而不是像现在的样式中position: absolute;

**Comment by airyland** [comment]
tabbar是直接封装weui的，用 fixed 时会存在不好处理的问题

见这里 https://github.com/weui/weui/issues/262 用absolute的好处应该就是为了规避这样的问题。

**Comment by tianyong90** [comment]
@airyland 明白了。看来是用心良苦啊。

**Comment by airyland** [comment]
@tianyong90 是的，如果这个定位在实际使用中有出现其他问题再反馈一下~
