### ISSUE TITLE
通过路由跳转到有scroller组件的页面时，在android机上会有内容高度被挤压的情况

### ISSUE THREAD

**Issue by MarkQH** [airyland/vux#1415]
原因是前一个页面弹出了手机软键盘使容器受到挤压；
想了几个方法：一个是给scroller设置定高或页面加载完的时候设置成设备高度，但是貌似就不能滑动了；或者是延迟跳转路由：让软键盘收起后再跳转路由，但是仍有一部分android机会出现这种问题。所以想问问有没有更好的方法

**Comment by airyland** [comment]
请给出重现方式。
手机上的软键盘是什么意思？

**Comment by MarkQH** [comment]
在android5.0+，6.0+，7.0的手机上都出现这一情况，一个有input表单的页面，点击表单手机会弹出输入键盘，在键盘没收起来的情况下通过路由跳转到有scroller组件的页面，就会出现scroller容器被挤压的情况，布局改变了。

**Comment by airyland** [comment]
用户在弹出键盘时还再点击链接到其他页面？这个交互就比较奇怪了。
上张截图吧，不理解你说的挤压，布局改变是什么意思。

**Comment by MarkQH** [comment]
![-1](https://cloud.githubusercontent.com/assets/16751118/26023073/400dde26-37e7-11e7-9811-ddb8492679f7.png)
点击搜索跳转后：
![-2](https://cloud.githubusercontent.com/assets/16751118/26023084/55f60362-37e7-11e7-948b-f1e2a105cfa9.png)

**Comment by MarkQH** [comment]
暂时没环境重现就画了简图：
![qq 20170513142544](https://cloud.githubusercontent.com/assets/16751118/26023122/07286486-37e8-11e7-87c8-b1b35ec84c71.png)
点击搜索跳转后：
![qq 20170513142534](https://cloud.githubusercontent.com/assets/16751118/26023129/1bc2206c-37e8-11e7-83c8-06107f84dbf6.png)

**Comment by z-z-k** [comment]
我也遇到了这个问题,scroller不能自动适应页面高度变化
比如切换横屏,软键盘等改变页面大小

**Comment by airyland** [comment]
这类情况下需要自行设定高度了。不设置高度默认就是可用高度，所以目前组件内部逻辑没什么问题。

**Comment by z-z-k** [comment]
居然这么快就回复了
问题是已经设置了高度用"-40"
这种自动计算的应该要监听页面改变吧

**Comment by airyland** [comment]
@z-z-k 这种情况应该可以处理一下。

**Comment by z-z-k** [comment]
就算我监听onresize 重新设置-40 也不会有用,因为没有变化.除非先设置--41 再-40
只能自己计算高度

**Comment by airyland** [comment]
翻转可以用 orientationchange 事件，键盘弹出，收起估计只能用定时器检测。

**Comment by MarkQH** [comment]
@airyland 测试的时候用了一部华为的手机(android7.0)，设置定时器貌似依然无法解决（换了另外的一部三星的android6.0测试就暂时解决了，不清楚是不是手机性能的原因）

**Comment by nali946** [comment]
我试过一种方法,是存一个全局变量$clientHeight为设备高度固定值,scroller组件的height设为$clientHeight-40+'px'

**Comment by airyland** [comment]
鉴于 VUX 决定放弃 scroller 组件，这个 issue 关闭了。 :smile_cat:
