### ISSUE TITLE
scroller中点击事件会被触发两次

### ISSUE THREAD

**Issue by 54leibo** [airyland/vux#1416]
接：#1414
用法：
<ul @click="acceptQuestion($event)">
...
</ul>

**Comment by 54leibo** [comment]
<x-button @click.native="acceptQuestion">12312132</x-button>
这种用法也是触发了两次
环境：chrome调试模式iphone5模拟器下

**Comment by 54leibo** [comment]
<x-button @click.native="acceptQuestion">12312132</x-button>
这种用法也是触发了两次
环境：chrome调试模式，iphone5模拟器

**Comment by airyland** [comment]
重新确认下 vux vux-xscroll 版本吧。

**Comment by 54leibo** [comment]
sorry,之前木有认真检查，vux-xscroll由3.1.08升级到3.1.10问题就没有了
