### ISSUE TITLE
去除tabbar-item里<span slot="label">的点击事件怎么做

### ISSUE THREAD

**Issue by cloook** [airyland/vux#1417]
<tabbar-item show-dot>
          <icon name="profile-o" :scale="3" slot="icon" index="4" :currentIndex="current"  @click.native="switchTo(4)" ></icon>
          <span slot="label">个人</span>
        </tabbar-item>

![image](https://cloud.githubusercontent.com/assets/17813028/26031519/70d5d884-38a9-11e7-8b91-8e349abc3a8b.png)

**Comment by airyland** [comment]
不支持。说明一下具体场景？
