### ISSUE TITLE
Scorller在一个列表里用div包起图片不计算图片高度

### ISSUE THREAD

**Issue by zhenghuochao** [airyland/vux#1419]
```

 <scroller lock-x scrollbar-y height="-99px">
              <div class="box2">
                <ul>
                    <li v-for="i in 100" style="width:180px;">
                        <h4 >标题{{i}}</h4>
                        <div>
                            <img src="/static/img/banner_03.7b0b026.png" alt="" >
                        </div>
                    </li>
                </ul>
            </div>


    </scroller>
```

    
![qq 20170514231209](https://cloud.githubusercontent.com/assets/24648408/26035198/17d89080-38fb-11e7-9b2a-7d8e21e18227.png)
循环100次只显示1/4

**Comment by airyland** [comment]
当然不行，图片并非同步加载，未加载成功计算不了准确高度。自行为图片窗口设个高度，或者在合适时机 reset。

**Comment by danielCuiyang** [comment]
就上面这位兄弟的问题，该怎么为其解决，我也有相同疑惑

**Comment by danielCuiyang** [comment]
//detail 是包含所有img的大Div  找到下面所有的img 监听load事件即可解决
let self = this
                setTimeout(()=>{
                    let imgs = document.getElementById("detail").getElementsByTagName("img")
                    for (let i in imgs) {
                        if (typeof imgs[i] === 'object'){
                            imgs[i].onload = function () {
                                console.log('img onloaded')
                                self.$refs.scroller.reset()
                            }
                        }
                    }
                    this.$refs.scroller.reset()
                },100)
