### ISSUE TITLE
Scroller 里的 a标签会自动被加上javascript:void(0)

### ISSUE THREAD

**Issue by huanglei1991** [airyland/vux#1420]
之前用旧的xScroller的时候 不会有这样的问题 新版本的时候会出现
![image](https://cloud.githubusercontent.com/assets/25176774/26040848/30211c10-395b-11e7-8bc6-79b7eeed3003.png)
点击a标签以后
![image](https://cloud.githubusercontent.com/assets/25176774/26040862/44c89e5e-395b-11e7-99c0-2bda26e59286.png)

**Comment by airyland** [comment]
最近版本没有修改这个逻辑，发现这个逻辑其实一直都存在，意义不明 :sweat: 
可能是上次修改两次触发引出的另一个问题 :sweat: 
xscroll 已经不迭代，这是个大坑。

**Comment by airyland** [comment]
试试 3.1.12

**Comment by huanglei1991** [comment]
![image](https://cloud.githubusercontent.com/assets/25176774/26041679/56ed2662-3961-11e7-809d-cfa0b6cfc9af.png)
问题在 vux-xscroll/build/cmd/simulate-scroll.js  _unPreventHref和_preventHref 方法 我看了不懂这么处理是干嘛用的...只是在切换href

**Comment by huanglei1991** [comment]
嗯 3.1.12 我看见你把那两个注释掉 就没事了 这个好坑 我之前更新了下vux-xscroll 就被吓死了 一些链接不能跳

**Comment by airyland** [comment]
不想维护 xscroll 了，心累 :sweat_smile:

**Comment by huanglei1991** [comment]
目前 vux和 一些rem 的自适应方案什么的搭配不起来 我都是直接拷贝你的源码然后改改样式啥的 感觉还是搭配css 模块化 把class当参数传递覆盖可能 扩展性能好点.
因为 我是用scss的  还有把你的less改成scss 心累~  (题外话 如果自己用你源码css文件太分散会导致复制困难希望能考虑下源码党感受)

**Comment by airyland** [comment]
css 样式是 WeUI 的，这个没办法再怎么整理了。
