### ISSUE TITLE
XInput组件缺少手动blur方法。

### ISSUE THREAD

**Issue by joy-yu** [airyland/vux#1422]
focus方法有了为什么没blur。。

**Comment by airyland** [comment]
什么需求要手动 blur?
可以用 $refs.xinput.$refs.input 取得 input。

**Comment by joy-yu** [comment]
谢谢。类似于帖子回复，点击相应楼层的帖子，输入框focus，scroller滚动的时候我需要把输入框blur，否则一直处于focus状态，滚动完毕输入法会一直跳出来。
