### ISSUE TITLE
Scroller 组件 div 内的 list 出现无法滑动到最后一个

### ISSUE THREAD

**Issue by ghost** [airyland/vux#1423]
<img width="831" alt="qq20170515-144309 2x" src="https://cloud.githubusercontent.com/assets/12068304/26045535/4dd4073c-397d-11e7-9ada-f66b6f477482.png">
<img width="1078" alt="qq20170515-144401 2x" src="https://cloud.githubusercontent.com/assets/12068304/26045536/4dea5c58-397d-11e7-9734-a8145365d83d.png">

`如图无法滚动到最后一个`

**Comment by airyland** [comment]
既然数据是异步的，reset 没有？

**Comment by ghost** [comment]
v-for='i in 10'，这样的时候没问题。但是如果是v-for='i in goodList',就出现无法滑动到最后面一个了。调用reset也一样

**Comment by airyland** [comment]
看你的布局，考虑一下是不是因为图片未加载前尺寸不对，给图片设置一个尺寸。

测试一下，setTimeout 几秒后 reset，如果正常说明确实是尺寸的原因。

**Comment by NameJie** [comment]
给图片设置了尺寸 30%

**Comment by ghost** [comment]
<img width="404" alt="qq20170515-150245 2x" src="https://cloud.githubusercontent.com/assets/12068304/26046018/867a3316-397f-11e7-8960-8d486fe56114.png">
<img width="778" alt="qq20170515-150327 2x" src="https://cloud.githubusercontent.com/assets/12068304/26046053/a93eb99e-397f-11e7-83c3-1869e7717040.png">
<img width="364" alt="qq20170515-150338 2x" src="https://cloud.githubusercontent.com/assets/12068304/26046052/a937a6c2-397f-11e7-8577-e234c0c2ca47.png">

**Comment by ghost** [comment]
以上是less和使用reset后的源码

**Comment by airyland** [comment]
额， 帖文字代码吧。

**Comment by ghost** [comment]
稍等，别跑。。我复制

**Comment by ghost** [comment]
### HTML
```
<scroller height="-81" ref="scrollerBox">
        <div class="googs-list">
          <router-link to="/goodsDetaill" class="goods-item" v-for="(item,index) in goodsList" :key="index">
            <img :src="item.img" alt="">
            <div class="col">
              <p>景田百岁山348ml</p>
              <p>即时价：¥2.0</p>
              <p>次日价：¥1.5</p>
            </div>
            <i class="iconfont">&#xe613;</i>
          </router-link>
        </div>
      </scroller>
```
### SCRIPT
```
mounted () {
      this.$nextTick(() => {
        this.$refs.scrollerBox.reset()
      })
    }
```
### LESS
```
.googs-list {
        width: 100%;

        .goods-item {
          padding: 10px 10px 10px 0;
          border-bottom: 1px solid #eeeeee;
          display: flex;
          align-items: center;
          font-size: 12px;

          img {
            width: 30%;
          }

          .col {
            margin: 0 10px;

            p:nth-child(1) {
              color: #444444;
              display: -webkit-box;
              -webkit-box-orient: vertical;
              -webkit-line-clamp: 1;
              overflow: hidden;
            }
            p:nth-child(2) {
              color: #f95d43;
            }
            p:nth-child(3) {
              color: #aaaaaa;
            }
          }

          .iconfont {
            font-size: 20px;
            color: #03c3f6;
          }
        }
      }
```

**Comment by ghost** [comment]
我另启一个页面试下

**Comment by ghost** [comment]
问题还挺多的，我另启一个页面发现另外一个问题。算了。不用这个组件了

**Comment by ghost** [comment]
@airyland 刚才看了下源码然后实践了一下，发现reset后如果不刷新浏览器就能够拉到最底部，如果刷新页面就不能拉到最后一个了。请问怎么解决。

不想自己写一个，想偷个懒。大神我们一起来想想办法，哈哈
