### ISSUE TITLE
tabbar-item 点击问题 

### ISSUE THREAD

**Issue by niechengren** [airyland/vux#1424]
点击tabbar-item 点击第一次回到第一个  点击两次才被 active
如图 
![image](https://cloud.githubusercontent.com/assets/16233278/26046504/c40a6226-3981-11e7-9d29-3600f43c6eb3.png)

**Comment by niechengren** [comment]
点击一次  就是回到 第一个

**Comment by airyland** [comment]
按照你的代码，第一个你设置了 selected 已经是永久 active 了。

**Comment by niechengren** [comment]
我理解源码，这selected 是默认选中 ， 不过我把selected 去掉  也是一个效果

**Comment by airyland** [comment]
截图或者录屏吧。selected 已经默认选中了，永久 active 状态了无论你怎么跳都一样的 active，不理解你说的。

**Comment by ghost** [comment]
我昨天看了下组件的源码，你点击第一次的时候是跳转到那个页面去，然后再次点击依然是在那个页面，所以组件不会再次调用，而此时触发了active，所以在那个地方active算激活。


这个组件不能这样使用。你可以和我一样。tabbar单独建立一个vue然后子vue全部属于children的vue。


我这样描述，能明白吗 @airyland @niechengren

**Comment by ghost** [comment]
### template
```
<template>
  <view-box>
    <!-- 页面视图 -->
    <router-view></router-view>
    <!-- 底部标签 -->
    <div class="tabbar" slot="bottom">
      <router-link class="tabbar-item" to="home">
        <div class="icon-home"></div>
        <div class="label">首页</div>
      </router-link>
      <router-link class="tabbar-item" to="this">
        <div class="icon-light"></div>
        <div class="label">即时达</div>
      </router-link>
      <router-link class="tabbar-item" to="next">
        <div class="nextday">
          <div class="icon-nextday"></div>
          <div class="label">次日达</div>
        </div>
      </router-link>
      <router-link class="tabbar-item" to="cart">
        <div class="icon-cart"></div>
        <div class="label">购物车</div>
      </router-link>
      <router-link class="tabbar-item" to="user">
        <div class="icon-user"></div>
        <div class="label">我的</div>
      </router-link>
    </div>
  </view-box>
</template>
```
### router
```
{
      /* Tabbar页面 */
      path: '/tabbar',
      component: require('../pages/Tabbar'),
      children: [
        {
          /* 首页 */
          path: 'home',
          component: require('../pages/Home')
        },
        {
          /* 即时达 */
          path: 'this',
          component: require('../pages/This')
        },
        {
          /* 次日达 */
          path: 'next',
          component: require('../pages/Next')
        },
        {
          /* 次日达 */
          path: 'user',
          component: require('../pages/User')
        },
        {
          path: ':name',
          component: {template: '<p>{{$route.params.name}} template</p>'}
        }
      ]
}
```
<img width="439" alt="qq20170515-154400 2x" src="https://cloud.githubusercontent.com/assets/12068304/26047332/554387e2-3985-11e7-91a5-9989824a2f54.png">
<img width="417" alt="qq20170515-154413 2x" src="https://cloud.githubusercontent.com/assets/12068304/26047331/55352c42-3985-11e7-86ef-69b04d6d880b.png">


@niechengren

**Comment by niechengren** [comment]
@NameJie 你这是自己写的把

**Comment by ghost** [comment]
是啊。不过是参照他组件源码写的。哈哈

**Comment by niechengren** [comment]
@airyland 
![image](https://cloud.githubusercontent.com/assets/16233278/26047607/70fd1c90-3986-11e7-8f60-8ac221d92a8d.png)
点击一次 订单 页面跳到订单页 但是tabbar 却跳到 第一个了 
![image](https://cloud.githubusercontent.com/assets/16233278/26047649/94e3b47a-3986-11e7-8555-62b8dfb72883.png)
再次点击  页面不重新加载 只是 tabber 更新到 订单选项了

**Comment by niechengren** [comment]
@NameJie vux还是不错的 既然用了 尊重人家写好的组件 并大家一维护好  以后快速搭个小页面不也快么

**Comment by airyland** [comment]
tabbar 适合放在 App.vue 里公用，根据路由来设置哪个是 active 状态。如果你多个页面使用多个 tabbar，就只能手动分别设置了。

**Comment by ghost** [comment]
@niechengren 能用肯定 用啊，我还省事呢。问题是UI设计的效果不一样，我只能自己写了。

**Comment by niechengren** [comment]
@airyland 我知道什么问题了 谢谢

**Comment by NameJie** [comment]
当时的

**Comment by jiyuyu** [comment]
我也遇到了这样的问题，怎么解决的呢？

**Comment by luo-wenfeng** [comment]
遇到同样的问题，请问是怎么解决的呢？ @niechengren

**Comment by niechengren** [comment]
@lovenphone 就是tabbar 适合放在 App.vue 里公用，如果写在多个页面每个页面加载会重新初始化。应该懂吧。我的解决方法是 写在App.vue。然后其他页面如果不需要就display：none 掉

**Comment by luo-wenfeng** [comment]
@niechengren  明白了，知道问题在哪了， 谢谢 ！
