### ISSUE TITLE
关于x-input或x-textarea如何自动获取焦点

### ISSUE THREAD

**Issue by caiyawen** [airyland/vux#1429]
如： `<input autofocus="autofocus">`是可以自动获取到input框的焦点，但`<x-input :autofocus="autofocus"></x-input>`这样写却无效，因为autofocus属性没有写在textarea里，请问后者应该如何修改呢？

**Comment by wg5945** [comment]
ios下限制了，必须在用户操作之后，才能获取焦点

**Comment by airyland** [comment]
autofocus 在 Safari 上测试不可用，该 issue 关闭了。
