### ISSUE TITLE
Masker组件能支持渐变类型的遮罩吗？

### ISSUE THREAD

**Issue by LS1231** [airyland/vux#143]
### Version
vux@0.0.111

### Android or iOS, which browser?
iOS
### Your Codes 

``` html
<!--put your code here 代码没有正确格式化的issue直接关闭-->
```

**Comment by airyland** [comment]
什么样的渐变，给个栗子

**Comment by LS1231** [comment]
![image](https://cloud.githubusercontent.com/assets/5620625/14853031/5868cb86-0cbc-11e6-8d0d-f9dd457eca13.png)
类似图上这种

**Comment by airyland** [comment]
@LS1231 这个只要一个样式就能搞定的，用masker来实现大材小用了，代码体积还大 😅 。
