### ISSUE TITLE
按照官方文档步骤，npm run dev的时候报错

### ISSUE THREAD

**Issue by hery-sysu** [airyland/vux#1433]
error  in ./~/vux/src/components/icon/index.vue

Module build failed: TypeError: loaderUtils.getOptions is not a function
    at getOptions (/home/hery/桌面/skyworth/xplan-wechat-web/node_modules/less-loader/dist/getOptions.js:15:24)
    at Object.lessLoader (/home/hery/桌面/skyworth/xplan-wechat-web/node_modules/less-loader/dist/index.js:10:17)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-69b6a3c7","scoped":false,"hasInlineConfig":false}!./~/vux-loader/src/after-less-loader.js!./~/less-loader/dist?{"sourceMap":false}!./~/vux-loader/src/style-loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/vux/src/components/icon/index.vue 4:14-444 13:3-17:5 14:22-452
 @ ./~/vux/src/components/icon/index.vue
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-input/index.vue
 @ ./~/vux/src/components/x-input/index.vue
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/Register.vue
 @ ./src/views/Register.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by airyland** [comment]
无从重现。建议建个 repo 来方便重现。
