### ISSUE TITLE
表单验证，多个input的required状态如何关联到提交按钮

### ISSUE THREAD

**Issue by Desever** [airyland/vux#1434]
表单验证，多个input的required状态如何关联到提交按钮

**Comment by airyland** [comment]
绑定 disabled 属性吗，那直接  `:disabled="!value1 || !value2"`

**Comment by Desever** [comment]
是的，绑定 disabled 属性，value1和value2指的的input的v-model绑定的变量？

**Comment by airyland** [comment]
对。

**Comment by Chenberg** [comment]
v-model绑定的变量，只要输入了就为true了，但关联多个字段完整的校验怎么做呢？
用this.$refs.field.valid，会报undefined!
