### ISSUE TITLE
官网Demo-previewer 在iOS的激活状态下,Xheader依然显示

### ISSUE THREAD

**Issue by WangShayne** [airyland/vux#1439]
iOS有问题
![_20170517143334](https://cloud.githubusercontent.com/assets/17644818/26141319/de3bb428-3b0d-11e7-8565-d97b6b7162e9.jpg)

Android没有问题
![_20170517142829](https://cloud.githubusercontent.com/assets/17644818/26141337/f249b4c4-3b0d-11e7-9cbc-c95246ff6abe.png)

Chrome也是没问题的
![image](https://cloud.githubusercontent.com/assets/17644818/26141353/0aa9ff92-3b0e-11e7-8632-318c37be4ba1.png)

**Comment by airyland** [comment]
不在 body 下，受 webkitOverflowScrolling 影响，使用 v-transfer-dom 解决。
