### ISSUE TITLE
中文文档正文中demo失效

### ISSUE THREAD

**Issue by ChanceAroundYou** [airyland/vux#1441]
正文中所有(至少我看到的所有)展示demo都失效了，显示Nginx的404页面
手机端访问  电脑没试
仅举一例
[https://vuxjs.gitbooks.io/vux/content/layout/flexbox.html](url)

文档最开头的demo可以正常访问
估计是url有问题

**Comment by airyland** [comment]
为什么不访问官网文档。这已经是 0.x 的旧文档了，不再维护。

**Comment by ChanceAroundYou** [comment]
抱歉抱歉
之前从其他地方链接进来的  官网文档也打开了
大概是切换标签的时候没有注意关错了吧

感谢作者秒回
