### ISSUE TITLE
scroll插件上拉刷新和下拉加载两行文字一直紧贴内容,能不能让他固定在头部和尾部

### ISSUE THREAD

**Issue by zhuangbb** [airyland/vux#1442]
刚进入页面没有数据的时候也会出现上拉加载这几个字

**Comment by airyland** [comment]
依赖于 xscroll，组件不会再作迭代了。欢迎 PR。大部分情况下没有必要使用上拉加载，建议使用第三方的底部自动加载插件(组件)。

**Comment by zhuangbb** [comment]
没有找到xscroll,有文档吗

**Comment by airyland** [comment]
xscroll.github.io
