### ISSUE TITLE
inline-calendar 组件多选问题

### ISSUE THREAD

**Issue by mengkeys** [airyland/vux#1446]
需求：移动电商，在线订房系统开发， 需要用到日历渲染余量,售价等信息,支持点选选中多天,支持disabled等,

问题： 看了inline-calendar的DEMO以及文档,发现并不支持多选,项目已经是用vux开发到后期了,请问inline-calendar组件支持多选吗?

**Comment by airyland** [comment]
暂不支持。

**Comment by mengkeys** [comment]
好吧，那只能寻求别的途径了,谢谢！

**Comment by airyland** [comment]
如果你是在已有组件上实现的话也欢迎 PR 回来。

**Comment by xiaolongyuan** [comment]
yoyo 一样的问题  把源码copy 改下

**Comment by xiaolongyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/3142363/26385476/9704cb48-4072-11e7-9c00-369d1bbe4518.png)

![image](https://cloud.githubusercontent.com/assets/3142363/26385502/c67e0d30-4072-11e7-9c86-a70729385af4.png)
![image](https://cloud.githubusercontent.com/assets/3142363/26385523/db864332-4072-11e7-9e62-c6dcb552a196.png)

**Comment by xiaolongyuan** [comment]
需要PR么

**Comment by airyland** [comment]
@xiaolongyuan 欢迎

**Comment by xiaolongyuan** [comment]
https://github.com/airyland/vux/pull/1467
