### ISSUE TITLE
建议停止推荐 fastclick 

### ISSUE THREAD

**Issue by hao-li** [airyland/vux#1448]
[ftlabs/fastclick](https://github.com/ftlabs/fastclick) 已经很久没有更新，貌似已经不再维护了

调查 iOS 版 wechat 上的某报错时发现该错误长期存在
在有人给出解决方案建议后仍未被修复
参考：https://github.com/ftlabs/fastclick/issues/358

有人推荐 [hammer-time](https://github.com/hammerjs/hammer-time)替代

**Comment by airyland** [comment]
久未更新是个问题，但是看这个新库并没有多少人用，因为少人用肯定有些问题还未暴露出来，不想引入一个新库带入新问题。目前 fastclick 的一些报错更多是在 pc 调试的时候，实际上并非影响到正常使用交互。

**Comment by airyland** [comment]
相比于引入新库，更倾向于 fork fastclick 把现有问题解决。

**Comment by tennessine** [comment]
是啊，不想换个没说什么人用的
