### ISSUE TITLE
dev 时报错

### ISSUE THREAD

**Issue by dengdan99** [airyland/vux#1450]
![image](https://cloud.githubusercontent.com/assets/6008719/26241572/b230d682-3cb7-11e7-8fb9-0f73c6410716.png)

这个不是经常出现 但是一旦出现后，就再次 run dev 也是同样的错误  
重启后可以解决！

本地做了host 127.0.0.1 xxx.xx.x 调试需要启用的是80 端口（并未被占用）
本地dns做了清除刷新 还是没用
mac上目前没发现类似情况

不知道是vux 的问题 还是 webpack 的问题？

**Comment by airyland** [comment]
vux-loader 会向 vux.li 发送匿名统计，看你的情况是你网络是访问不到 vux.li 的？

**Comment by dengdan99** [comment]
ok  知道原因了
