### ISSUE TITLE
XInput组件有无可能加入原生事件或者keyup?

### ISSUE THREAD

**Issue by nali946** [airyland/vux#1456]
例如有个需求是这样子,输入的密码的时候点击键盘的确认按钮直接登录.

**Comment by airyland** [comment]
移动端没有 keyup 事件吧？

**Comment by nali946** [comment]
有的,我试过了

**Comment by nali946** [comment]
后来我这样子弄,感觉有点小麻烦.
this.$refs.pwd.$refs.input.onkeyup=function(e){
  console.log(e.keyCode);
if(e.keyCode=='13') self.login()
}

**Comment by nali946** [comment]
需要在mounted钩子里

**Comment by airyland** [comment]
那么 emit 个 on-keyup 事件出来能满足要求？

**Comment by nali946** [comment]
应该是可以的,如果作者有时间的话支持一下enter修饰符就更爽了

**Comment by graysheeep** [comment]
已支持enter事件 #1539
