### ISSUE TITLE
swiper循环模式的bug #1161  复现

### ISSUE THREAD

**Issue by 86chenjie** [airyland/vux#1458]
https://github.com/airyland/vux/issues/1161 复现了这个issue的问题。
测试发现：loop=false的时候，显示第一个项目，loop=true的时候，却显示了第二个项目
(loop=true + 使用自定义SwiperItem 时会复现这个问题)
测试文件如下：

[QuestionContainer.zip](https://github.com/airyland/vux/files/1019174/QuestionContainer.zip)

**Comment by F-loat** [comment]
+1，vux版本为2.3.2，swiper开启循环时渲染顺序会出错，数据为读取本地数据后又使用异步数据替换，去掉加载本地数据的环节并且使用list属性而不是swiper-item就没问题了

**Comment by Yakima-Teng** [comment]
也发现了这个bug，但是不知道怎么解决。。我通过chrome的vue插件查看数据，传给swiper组件的列表数据里的图片顺序是对的，但是它显示的就是错的顺序。我碰到的情况，其复现方法为点击第一个swiper跳转到第二个页面，再按返回键回到第一个有swiper的页面，显示顺序就不对了。我也用loop属性开启了循环模式。
