### ISSUE TITLE
datetime popup 等body下的组件无法在router keep-alive的状态下切换消失

### ISSUE THREAD

**Issue by easonzhuyi** [airyland/vux#1462]
rt,无keep-alive会回收dom，但是组件也没有暴露关闭隐藏的接口，如何处理？

**Comment by airyland** [comment]
不明白你的场景。有弹窗的话用户当然会先关闭再切换页面。

**Comment by devinRex** [comment]
如果popup出来的框中含有路由切换的按钮，点击这个按钮会根据不同的情况有不同的影响：
1.添加了transformdom：切换路由以后就直接会盖在新路由的页面上
2.不添加transformdom：切换路由，遮罩层会盖在新路由的页面上

**Comment by airyland** [comment]
@devinRex 这种情况当然是要手动处理关闭了。
