### ISSUE TITLE
 Vue.wechat.scanQRCode成功回调函数只执行第一句代码后面的不执行

### ISSUE THREAD

**Issue by PlusLius** [airyland/vux#1464]
版本号:"vux": "^2.2.1-rc.7"
![image](https://cloud.githubusercontent.com/assets/23534665/26353881/fc04e696-3ff4-11e7-9072-eecd354bc570.png)

**Comment by airyland** [comment]
这和 VUX 没有关系了, VUX 仅仅是将 jssdk 包装起来而已，没有做任何修改。不信你去掉这个模块，自己在 index.html 引入官方的 cdn 脚本。

但是从代码上，合理应该是会执行到的。
