### ISSUE TITLE
[Checker]关于Checker组件在SKU应用中的问题

### ISSUE THREAD

**Issue by yumcc-com** [airyland/vux#1468]
在商城项目中用到Checker组件来做商品规格的选择，类似淘宝的实现方式，发现Radio模式下再次选择无法取消，有解决方案吗？由于功能的需求是每次点击后通过选中的model值来遍历判断哪些规格需要show哪些规格需要disabled。至此提出这个问题。目前用@on-item-click触发改变v-model数组的值，存在就清空对象，不存在就添加对象，虽然前者清空对象成功，但是之前选中的dom样式却没清除，而再次点击就添加不了了。下图为淘宝的截图

![12](https://cloud.githubusercontent.com/assets/18699401/26386881/0a807b2c-407c-11e7-99c1-2aeb10a64486.png)

**Comment by airyland** [comment]
supported on v2.3.2

**Comment by yumcc-com** [comment]
感谢解决，npm目前还是2.3.1版本

**Comment by airyland** [comment]
:sweat: Forgot to publish..
