### ISSUE TITLE
cell的is-link属性加上，没有箭头显示

### ISSUE THREAD

**Issue by cluod** [airyland/vux#1469]
<cell style="background: white;"
            :title="11"
            is-link
            :border-intent="false"
            :arrow-direction="showContent001 ? 'up' : 'down'"
            @click.native="showContent001 = !showContent001"></cell>

          <template v-if="showContent001">
            <cell-box :border-intent="false" class="sub-item" is-link>content 001</cell-box>
            <cell-box class="sub-item" is-link>content 001</cell-box>
            <cell-box class="sub-item" is-link>content 001</cell-box>

**Comment by airyland** [comment]
既然 demo 没问题，出问题就是你自己的使用问题了。
上面并没有任何可以帮助解决问题的线索。建议你对照下官网 demo 审查下样式吧。

**Comment by zhwaner** [comment]
可能是因为没有加Group组件的原因

**Comment by zhwaner** [comment]
可能是因为外层没有加上Group组件

**Comment by zhouwencn** [comment]
遇到了同样的问题，没有任何办法，我都无语了

**Comment by happydan** [comment]
这是来自1977130605邮箱的自动回复邮件。我将尽快给您回复。
