### ISSUE TITLE
x-header 组件  使用 x-icon 自定义左侧的图标  怎么添加click事件  

### ISSUE THREAD

**Issue by yuyuyu19** [airyland/vux#1470]
`<x-header slot="header" style="width:100%;position:absolute;left:0;top:0;z-index:100;"
                :title="getTitle"
                :left-options="{preventGoBack:true}"
                :right-options="{showMore: true}"
                >
        <x-icon slot="overwrite-left" type="navicon" size="35" style="fill:#fff;position:relative;top:-8px;left:-3px;"></x-icon>
      </x-header>`
x-header 组件
怎么给左侧的自定义图标添加一个click  事件

**Comment by airyland** [comment]
`<x-icon  @click="handler"></x-icon>`
因为虚拟组件的特殊性，在最新 vux-loader 里加不加 native 都一样。
