### ISSUE TITLE
关于demo用的css和下载完成的css的问题

### ISSUE THREAD

**Issue by 563325028** [airyland/vux#1472]
我现在的cell插件和搜索插件的css属性在一些手机上有问题 不过看官网demo 的时候是正常的 然后我看了一下css好像有一点差距 我想问问demo的css和安装完的css是一样的么？

**Comment by airyland** [comment]
当然是一样。检查样式冲突什么的吧。

**Comment by 563325028** [comment]
作者大大我多问一下 如果我只想覆盖插件的样式之类的 我是不是在github上下载然后把vux覆盖了就可以？ 不用使用npm下载了把

**Comment by airyland** [comment]
使用 npm 下载管理吧，Github 上是开发版。样式覆盖你可以用 less 变量或者直接写样式覆盖。

**Comment by 563325028** [comment]
好的谢谢作者 我试一试

**Comment by 563325028** [comment]
再多问一下  是不是插件的样式都在node_modules的vux里面 其他的有关系吗？ 我昨天把vux里面的less都覆盖了好像没生效

**Comment by airyland** [comment]
文档写了，less 变量你直接写当然是没法生效的。要用 vux-loader 的 less-theme 插件。
