### ISSUE TITLE
XHeader返回点击事件

### ISSUE THREAD

**Issue by dmlzj** [airyland/vux#1474]
XHeader组件放在App.vue里面，作为统一的头部，默认都是返回上一页，如何在子组件更改这个的返回点击事件，我在子组件里面通过store全局设置了left-options.preventGoBack=true，但是不知道怎么写代码才能让App.vue里面的这个返回事件生效！

**Comment by dmlzj** [comment]
可以做个例子放在demo上吗，谢谢哦！

**Comment by airyland** [comment]
你反过来设置  preventGoBack = false 不可以吗？

**Comment by dmlzj** [comment]
那样设置的话，点击返回就是返回上一页，有时候不是返回上一页，我是想点击返回能返回到一个别的页面

**Comment by Sapphire2k** [comment]
@dmlzj 
XHeader:
Events：
`on-click-back` 当left-options.preventGoBack为true,点击左边返回时触发。
这里的回调函数 你可以放到store里，也可以直接扩展vue实现。
－－－－－－－－－－－－
我应该没理解错吧 ＝。＝

**Comment by dmlzj** [comment]
对的，就是能自己修改这个返回事件到任何一个页面就可以哦！APP.vue里面这样写：
 <x-header :left-options="{preventGoBack: true}" @on-click-back="back">
因为我把header作为统一的头部了；
然后在App.vue这个组件或者别的组件里面可以直接写back函数来跳转不同的页面就可以了。但是我现在写了都不起作用
@Sapphire2k

**Comment by dmlzj** [comment]
@airyland 
这个问题在帮我解决啊？

**Comment by airyland** [comment]
上面 @Sapphire2k 都已经给出解决方法了，况且这是业务实现和  VUX 无关。

**Comment by FrankFan** [comment]
@Sapphire2k 
XHeader:
Events：
on-click-back 当left-options.preventGoBack为true,点击左边返回时触发。
这里的回调函数 你可以放到store里，也可以直接扩展vue实现。
－－－－－－－－－－－－

能详细说说 如何把回调函数放到 `store` 里么？

谢谢

**Comment by FrankFan** [comment]
@dmlzj 
你好， 我的场景和你描述的这个一模一样，也遇到了同样的问题。
请问你最后是怎么解决的？
我查了好多资料都没有解决，快奔溃了。。。

跪谢

**Comment by bigfool-cn** [comment]
自定义的right图标没有触发事件吗？
