### ISSUE TITLE
[Checker]关于Checker组件在SKU应用中的问题

### ISSUE THREAD

**Issue by yumcc-com** [airyland/vux#1479]
再提一个问题，Radio模式下，对【选中】的checker进行disabled操作，对应的model值清除，样式由selected-item-class转为disabled-item-class。可否做成这样，支持这个的话，Checker配合算法就能完整实现淘宝SKU这种功能了

**Comment by airyland** [comment]
看描述有点看不明白，checker-item 设置  disabled = true，那么这个 item 应该已经会是 disabeld 样式了。

**Comment by yumcc-com** [comment]
checker-item 设置 disabled = true 后，这个 item 是 disabeld 了。
但是当这个 checker-item 是【选中】的时候再设置这个item的 disabled = true ，结果这个 item 一样是 disabeld ，只是之前选中的样式却没清除。
