### ISSUE TITLE
X-header  自定义左边的图片  在IOS（10.3）真机不显示   

### ISSUE THREAD

**Issue by yuyuyu19** [airyland/vux#1480]
```
<view-box ref="viewBox" body-padding-top="66px" body-padding-bottom="55px">
      <x-header slot="header" style="width:100%;position:absolute;left:0;top:20px;z-index:100;"
                :title="getTitle"
                :left-options="{preventGoBack:true}"
                :right-options="{showMore: true}"
                @on-click-more="changeTab"
      >
        <x-icon @click="changeShow" slot="overwrite-left" type="navicon" size="35" style="fill:#fff;position:relative;top:-8px;left:-3px;"></x-icon>
      </x-header>
</view-box>
```

这是Chrome：
![image](https://cloud.githubusercontent.com/assets/16248989/26483774/5813c172-4221-11e7-8993-b431852cbb7a.png)

这是IOS 真机 10.3版本：
![image](https://cloud.githubusercontent.com/assets/16248989/26483829/96f8042a-4221-11e7-85f3-0535d089ecce.png)

**Comment by yuyuyu19** [comment]
再请问下    x-header   和IOS真机顶部的   信息重合了   应该怎么处理
我目前是设置  x-header  的style 中  top:20px   效果不是很好   请问有什么其他处理办法

![image](https://cloud.githubusercontent.com/assets/16248989/26484476/eba5a4a2-4224-11e7-9f0d-70b855b691dc.png)

**Comment by airyland** [comment]
这很神奇啊。看起来就像是你在 iOS 上看的版本和 chrome 上用的 VUX 版本不是同一个，也就中不支持这个 overwrite-left slot。

**Comment by yuyuyu19** [comment]
@airyland     同事打包APP时没有升级vux 的版本   所以出现了这个问题   升级之后没有问题    不好意思
