### ISSUE TITLE
vux/src/datas目录下的china_address.json

### ISSUE THREAD

**Issue by dmlzj** [airyland/vux#1482]
vux/src/datas目录下的china_address.json里面有4个版本是不是留下v3版本就可以，别的都删掉啊？
这个地方打包出来，都重复了，文件瞬间大了好多！

**Comment by airyland** [comment]
打包都是按需打包，怎么会把没用到的打包了呢。
检查 vux-loader 配置。

**Comment by dmlzj** [comment]
vux-loader配置我没有动，哪个组件会调用到这几个文件啊？

**Comment by dmlzj** [comment]
```js
  import { Card } from 'vux'
//  import { XInput } from 'vux'
```
这样在引入一个组件的下面引入任何一个vux的组件或者注释掉都会加载那4个文件
```js
import { Card } from 'vux'
或者
import { Card， XInput } from 'vux'
```
都没问题，好奇怪的问题！！！！
@airyland

**Comment by airyland** [comment]
写成一行
