### ISSUE TITLE
参考了viewbox 布局，但是出现中间区域不能滚动bug

### ISSUE THREAD

**Issue by yhZhouYh** [airyland/vux#1483]
默认进入页面高度 如果高于中间滚动区域高度，页面滚动正常，但是 当我增加慢慢增加内容，超过滚动区域高度，页面不能正常滚动，只在移动端出现，web端模拟都正常

**Comment by yhZhouYh** [comment]
刷新一下页面 重新处理 正常，单页切换过来 处理，就有这个问题。

**Comment by suclu** [comment]
我也遇到了这个问题  请问你是怎么解决的

**Comment by weineel** [comment]
我也遇到这个问题
@yhZhouYh 解决了吗？
