### ISSUE TITLE
swiper循环模式下点击事件无效

### ISSUE THREAD

**Issue by Pasoul** [airyland/vux#1484]
场景：
有两个轮播图，加上loop实现循环播放，发现只有带有vux-swiper-item-clone的图片点击事件无效

代码：
`<swiper :list="img_list" auto  loop height="3.75rem"  @clickItem="clickbanner"></swiper>`

**Comment by Pasoul** [comment]
补充：在大于两张图片的时候无问题，暂时的解决方法是把swiper.js里面的_loopTwoItems方法注释掉

**Comment by airyland** [comment]
@unclay 有空来帮忙看看

**Comment by unclay** [comment]
pull出了点问题，明天再看看

**Comment by Pasoul** [comment]
谢谢，用了下代码是可行的，但是得加上const me = this，不然会报错me undefined @unclay

**Comment by Mapz** [comment]
我也出现这个问题了，哈哈

**Comment by airyland** [comment]
#1499

**Comment by gyj19890413** [comment]
这个是图片的点击事件嘛？为什么我用@clickItem  没反应    
![image](https://user-images.githubusercontent.com/18460849/41147664-a0688542-6b39-11e8-8009-36ddd20a5bd9.png)

**Comment by JiangMengQing** [comment]
使用@click.native点击事件能生效

**Comment by gy2986589** [comment]
在swiper中 用 Previewer组建怎么不好用。。。。
