### ISSUE TITLE
关于search跳转到另一个网页的问题

### ISSUE THREAD

**Issue by 563325028** [airyland/vux#1485]
作者您好 我给search插件的onSubmit绑定了一个跳转的方法 但是我跳到那个页面后 再点击x-head头部的那个返回  回到第一个页面的时候好像并不执行mounted里的this.load=false 而且search也还是那种可以输入的状态 安卓没有问题 只有ios有 导致页面一直在执行load 请问这该怎么办 要在onSubmit里面加入什么吗

**Comment by airyland** [comment]
你这是使用了  keep-alive 吧。

**Comment by 563325028** [comment]
我用的是axios调的接口 是不是自动使用keep-alive？  别的地方没使用过keep-alive  pc和安卓都可以 就是ios不行

**Comment by airyland** [comment]
keeyp-alive 是组件和 axios 无关了。mounted 里代码不执行和 vux 也无关了。信息比较模糊难以重现，建议建个 repo。
