### ISSUE TITLE
Search组件在微信浏览器下，用 auto-scroll-to-top 在 absolute 下弹出键盘时有概率无法看到 input

### ISSUE THREAD

**Issue by Mapz** [airyland/vux#1487]
环境：微信浏览器 ios版本 6.5.8
重现方式：官网 search demo
输入法：ios自带输入法，百度输入法
现象：点击输入框后，输入框在顶部滚到屏外，被挡出
出现频率：有概率出现

**Comment by graysheeep** [comment]
能给个截图吗
