### ISSUE TITLE
引用了少量几个组件打包后多了很多莫名其妙的东西

### ISSUE THREAD

**Issue by yyman001** [airyland/vux#1488]
1.webpack配置没修改过,之前打包正常的,换成异步加载组件打包后,引用的组件出现奇怪的js文件(第三方依赖?)
1.1
```cmd
//异步组件 文件大小`17KB`
   {
    path: '/integral/',
    name: 'Integral',
    component: function (resolve) {
      require(['@/components/integral/index.vue'], resolve);
    }
  }
```
2.文件引用了vux的`import { XInput,TransferDom, Popup, Group, XButton , Countup } from 'vux'`这些模块
![image](https://cloud.githubusercontent.com/assets/5688485/26517951/fc7d603c-42d6-11e7-8df5-5cc68b5b21d0.png)
3.打包后的js文件`1.2M`,之前没引用组件24K
![image](https://cloud.githubusercontent.com/assets/5688485/26517937/7e60b280-42d6-11e7-8e5e-a9596f52a898.png)
地区插件的文件都打包进去了?
![image](https://cloud.githubusercontent.com/assets/5688485/26517940/9aff4bf4-42d6-11e7-96cc-c56bbaa253d4.png)

不知道是什么原因导致?把组件注册到全局会不会少点?

**Comment by airyland** [comment]
建个 repo 来重现吧。

**Comment by yyman001** [comment]
@airyland 不知道是不是配置坏了还是怎么了.另外一个页面单独引入`import { LoadMore } from 'vux';测试环境的js达到7.2m,看里面好像也是整个打包了.不引用的话js文件42k.这很尴尬.完全不知道问题出在哪里.

**Comment by airyland** [comment]
所以你建个 repo  来看看，这样描述的话不知道怎么重现。

**Comment by yyman001** [comment]
@airyland 翻到了这个文档,https://vuxjs.gitbooks.io/vux/content/install/umd.html 
说是
```cmd
// 不推荐的方式，会打包所有vux模块
方式1:
import { Group, Cell } from 'vux'

// 推荐的方式，按需加载需要的组件
方式2:
import Group from 'vux/dist/components/group'
import Cell from 'vux/dist/components/cell'
```
换成下面的那个方式好像不会把文件都打包进去了,这有可能是vux-loader造成的?
因为我有些页面是用`方式1`并不会全部把组件全部打包...而是有些页面会.很奇怪= =

**Comment by airyland** [comment]
sorry，我已经建议你建个 repo 来重现了。你再怎么描述我也不能重现你的问题，关闭了。
上面的文档是 0.x 的文档了，不再更新。并且 vux 根本没有 dist 文件夹。

**Comment by jinchaoxiang** [comment]
我也是这样
