### ISSUE TITLE
history 关于前进后退的direction 问题

### ISSUE THREAD

**Issue by 3vand0ng** [airyland/vux#1489]
我应用VUX 在项目里，如果导航路由比较深，例如3、4级，home->list->detail->other...
在other 页面刷新后，按后退按钮的时候就是forward 的效果。
https://vux.li/demos/v2/?x-page=v2-doc-home#/
dome 页顺序点下面3个导航，到donate 刷新页面，再回退就会出现direction 的问题

**Comment by airyland** [comment]
是会这样，入口页不是首页会有问题。建议不要直接复制 demo 的代码，根据业务路由的级别来设置方向。

**Comment by 3vand0ng** [comment]
@airyland 有没有思路，搞不懂这个😂
