### ISSUE TITLE
marquee 组件在初始化的时候 height 为0

### ISSUE THREAD

**Issue by ykx456654** [airyland/vux#1490]
直接在文档上复制过来的，组件初始化成功，但是高度为0，打印了一下 ，
` init () {
      this.destroy()

      if (this.cloneNode) {
        this.$refs.box.removeChild(this.cloneNode)
      }

      this.cloneNode = null
      let firstItem = this.$refs.box.firstElementChild
      if (!firstItem) {
        return false
      }
      this.length = this.$refs.box.children.length  
      this.height = firstItem.offsetHeight    //**这里出问题了 ，**

      if (this.direction === 'up') {
        this.cloneNode = firstItem.cloneNode(true)
        this.$refs.box.appendChild(this.cloneNode)
      } else {
        this.cloneNode = this.$refs.box.lastElementChild.cloneNode(true)
        this.$refs.box.insertBefore(this.cloneNode, firstItem)
      }
      return true
    },`

**Comment by airyland** [comment]
麻烦给完整使用代码，即使你复制过来也不能保证你复制正确了。
