### ISSUE TITLE
scroller.js    Uncaught ReferenceError: members is not defined

### ISSUE THREAD

**Issue by 531431988** [airyland/vux#1491]
![uc 20170527171430](https://cloud.githubusercontent.com/assets/8703951/26520197/8d17d5cc-4300-11e7-91f4-1abcf9071410.png)
装了无数次，一直报这个错，其他电脑都可以，就一台电脑不行？求解，试了各种方法

**Comment by airyland** [comment]
我也无解。无从重现。建议进源码 debug。

**Comment by gengxuelei** [comment]
@531431988 你解决了吗，我也碰到这个问题了：
![image](https://cloud.githubusercontent.com/assets/11707936/26674208/3a8afc6c-46f2-11e7-8a7e-f783100bb331.png)
```
<template>
  <div>
    <group>
      <datetime v-model="value5" placeholder="选择日期" :min-year=2000 :max-year=2016 format="YYYY-MM-DD HH" @on-change="change" :title="'123456'" year-row="{value}年" month-row="{value}月" day-row="{value}日" hour-row="{value}点" confirm-text="完成" cancel-text="取消"></datetime>
    </group>
  </div>
</template>
```
```
<script>
import {
  Group,
  Datetime
} from 'vux';
</script>

```
单独引入这两个组件会在某些浏览器出现这个问题，其中包括上图的qq浏览器
最新版的chrome和Edge浏览器没有问题，vux.li的官方demo也没这个问题
会报这个错误:
![image](https://cloud.githubusercontent.com/assets/11707936/26674365/d4b1af52-46f2-11e7-96fd-bfa65d2b3dcc.png)

追溯源码找到这一行：
![image](https://cloud.githubusercontent.com/assets/11707936/26674425/0845bd68-46f3-11e7-9cc0-bdaef0840cb3.png)
在for循环之前打印members这个对象会报上面的错误

**Comment by airyland** [comment]
这很神奇啊，明明上面一行是定义了 members，下面一行就 undefined 了？

**Comment by gengxuelei** [comment]
@airyland 
如果调试这样写：
![image](https://cloud.githubusercontent.com/assets/11707936/26675603/2763eb6c-46f7-11e7-9e8c-0886e9d79cf5.png)
然后s就undefined了，神奇吧！
我猜测是webpack的问题，打包出了错，也可能是配置不对，因为vux.li的demo是没问题的
我用的是[cooking](https://cookingjs.github.io/zh-cn/index.html)，不知道怎么配置vux-loader
但是有的浏览器是好的，有的不行……

**Comment by QingWei-Li** [comment]
@gengxuelei 你先换成 webpack 的配置调试下，如果有问题再来问，没问题就正好切换到 webpack 🌚

**Comment by gengxuelei** [comment]
@QingWei-Li 现在项目着急上线，只能先暂时不使用vux了，cooking的源码读了很多遍了，写的很好，这个工具也很好用，毕竟webpack的配置确实有点繁琐。但是很多项目是基于webpack的那三个配置文件写的，cooking只用add、remove、resolve这几个方法貌似有点没办法应对复杂的情况。如果cooking能做一些社区的推广，感觉能像yarn对npm一样，吸引一些用户过来。不过如果cooking后期不准备维护的话，我也是准备把项目迁移回webpack的。
