### ISSUE TITLE
建议 Actionsheet 增加一个点击遮罩事件

### ISSUE THREAD

**Issue by wengcd** [airyland/vux#1496]
我现在使用 `vuex` 来控制 `actionsheet的显示`
点击菜单有事件可以执行 `actions`
但点击遮罩组件会尝试强制改变 `value`或`v-model`上绑定的变量，`vuex`上变量是只读的，只允许`actions`来触发改变

**Comment by airyland** [comment]
可 pr。

**Comment by gy2986589** [comment]
怎么才能 actionsheet中增加confirm。。。。。
