### ISSUE TITLE
关于i18 block翻译的问题

### ISSUE THREAD

**Issue by lyj505** [airyland/vux#1497]
我在vux-config.js里,
定义了
  {
      name: 'i18n',
      vuxStaticReplace: false, //配置了静态替换为true 的时候,则没有报错,但是i18 block内无法翻译。
      staticReplace: false,
      extractToFiles: 'src/locales/components.yml',
      localeList: ['en', 'zh-CN']
    },
main.js也按照配置了,vuxStaticReplace配置成false,就会报错:
Property or method "$t" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
Error in render function: "TypeError: _vm.$t is not a function".......
我把 vuxStaticReplace 改成true,一切就正常了...不会报错了,,也可以进行中英文的切换,当然是根据
components.yml 进行翻译转换的。。。但是无法再页面内通过i18 block翻译....而且把
vuxStaticReplace设置成false,就报错了....尴尬。
我讲node_modules 清空了,重新npm install 还是不行。。。不造哪里出问题了。。

**Comment by lyj505** [comment]
我想好像是没有加载到src/locales/components.yml这个文件,
应该是我配置vuxStaticReplace等于false的时候,就报错了,后面的配置没有执行了。。
难道是我i18配置的问题,,,问题来了,,就算i18配置错误...现在设置vuxStaticReplace 也可以动态切换英文中文..........只是不能block,不能自定义,vux是从哪里取得文件。。。

**Comment by airyland** [comment]
我看得晕。建个 repo 来看看，这是需要 main.js 里代码来读取抽取的语言文件的。

**Comment by lyj505** [comment]
@airyland 
神奇的问题来了。。
我把'Vue.use(vuexI18n.plugin, store)'放在前面。。就没报错了$t未定义的错了
`Vue.use(Vuex)

import vuexI18n from 'vuex-i18n'

//const store = new Vuex.Store();
let store = new Vuex.Store({
  modules: {
    i18n: vuexI18n.store
  }
})

Vue.use(vuexI18n.plugin, store)


Vue.use(AjaxPlugin)
Vue.use(VueRouter)
Vue.use(AlertPlugin)
Vue.use(ToastPlugin)
`
,然后现在的问题就是,还是无法在xxxxxxxpage.VUE使用i18 block标签,,
我vux-config 里面是这样配置的有没有问题?
`
module.exports = {
  options: {
    //  vuxDev: !argv.simulate, // true
    // vuxSetBabel: argv.simulate, // false
    //vuxWriteFile: false,
     env: 'dev'
    //env 非必选，定义当前环境变量，只在vux-loader里使用，
  },
  plugins: [
    'vux-ui', 'inline-manifest', 'progress-bar', 'duplicate-style',
    {
      name: 'i18n',
      vuxStaticReplace: false, //
      staticReplace: false, //
      extractToFiles: 'src/locales/components.yml',
      localeList: ['en', 'zh-CN']
    },
`

就是我更改了i-18 block 文件 我观察 component.yml 里面发生了变化....但是页面上没有变化...
依然是以前的文字。。。而用你官方的demo 。。。就没问题。。~~~

**Comment by airyland** [comment]
语言文件要手动合并引入

https://github.com/airyland/vux/blob/v2/src/main.js#L98-L111

**Comment by lyj505** [comment]
@airyland  
貌似我找到原因了。。。
这个文件我也加载了的,,,,但是是加载的是node_modules\vux\src\locales\all.yml
。。。应该就是require的路径出问题了。。
请问一下,这个需要更改其他的webpack配置吗?或者需要什么...它老师加载node_modules里的文件....所以我i18其实更新了....它加载的文件没改！~~~原因找到了

**Comment by lyj505** [comment]
我这里解决了。。。不知道webpack的配置还是哪里出了问题。。。

将官方的demo的
 // const vuxLocales = require('json-loader!yaml-loader!vux/src/locales/all.yml')里面的vux/ 去掉了就可以加载了....
我猜想应该是配置问题导致加载的路径问题.....优先加载...唉。。没找到根本原因。。

 const vuxLocales =        require('json-loader!yaml-loader!src/locales/all.yml')
const componentsLocales = require('json-loader!yaml-loader!src/locales/components.yml')
const globalLocales = require('json-loader!yaml-loader!src/locales/global_locales.yml') || {en: {}, 'zh-CN': {}}

**Comment by airyland** [comment]
你确定么。。去掉  vux，那么 vux 的语言文件就不会加载了。如果后面解决不了就建个 repo 吧。

**Comment by Jiiiiiin** [comment]
请问：
插件配置中的【extractToFiles】
`{
      name: 'i18n',
      vuxStaticReplace: false,
      staticReplace: false,
      extractToFiles: 'src/locales/components.yml',
      localeList: ['en', 'zh-CN']
    },`
和【语言文件要手动合并引入】
两者之间的联系是什么？

**Comment by Jiiiiiin** [comment]
请问：
插件配置中的【extractToFiles】
```js
  {
      name: 'i18n',
      vuxStaticReplace: false,
      staticReplace: false,
      extractToFiles: 'src/locales/components.yml',
      localeList: ['en', 'zh-CN']
    },
```
和【语言文件要手动合并引入】
两者之间的联系是什么？

**Comment by airyland** [comment]
@Jiiiiiin 抽取出来就是为你让你可以任何第三方的 i18n 插件来加载语言配置。

**Comment by shdxiang** [comment]
@airyland components.yml 是需要自己写，还是 webpack 会生成的？我配置了 webpack
```
{
      name: 'i18n',
      vuxStaticReplace: false,
      staticReplace: false,
      extractToFiles: 'src/locales/components.yml',
      localeList: ['en', 'zh-CN']
}
```
但是 npm run dev 没有发现生成这个文件

**Comment by airyland** [comment]
@shdxiang 提供 repo 才能看是什么问题。

**Comment by ansonhorse** [comment]
遇到跟@shdxiang一样的问题，配置了但没有生成components.yml。webpack并没有任何警告错误，更奇怪的是，我发现webpack的plugins乱写都不会提示错误，比如`name: 'i18n'`，写成`name: 'i19n'`，webpack也会处之泰然。

**Comment by shdxiang** [comment]
@ansonhorse 我最后是手动增加的。

**Comment by ansonhorse** [comment]
@shdxiang 可以指点一下是什么步骤么？

**Comment by shdxiang** [comment]
@ansonhorse 直接把需要的翻译写在 `components.yml` 里：
```
en:
  vux.actionsheet.cancel: 'Cancel'
  vux.alert.button_text: 'OK'
  ...
zh-CN:
  vux.actionsheet.cancel: '取消'
  vux.alert.button_text: '确定'
  ...
```

然后在 `main.js` 中：
```
import vuxLocales from './locales/components.yml'
import appLocales from './locales/apps.yml'

...

const finalLocales = {
  'en': objectAssign(vuxLocales['en'], appLocales['en']),
  'zh-CN': objectAssign(vuxLocales['zh-CN'], appLocales['zh-CN'])
}

for (let i in finalLocales) {
  Vue.i18n.add(i, finalLocales[i])
}
```

`apps.yml` 里是我自己程序使用到的字符串的翻译。

**Comment by ansonhorse** [comment]
@shdxiang 谢谢

**Comment by Riant** [comment]
```
{
      name: 'i18n',
      vuxStaticReplace: false,
      staticReplace: false,
      extractToFiles: 'src/locales/components.yml',
      localeList: ['en', 'zh-CN']
}
```
这个配置看起来是把 组件里边的 `<i18n></i18n>` 里边的配置抽取出来放在文件 `src/locales/components.yml` 里边，是吗？

但是 `npm run dev` 之后确实没看到生成的这个文件，导致 `main.js` 里边 import 报错，于是有需要手动创建这个文件，是吗？那么上边的  loader 插件配置的 `extractToFiles: 'src/locales/components.yml',` 是在什么时候怎么生效的呢？他和手动创建的 `'src/locales/components.yml'` 有什么关系呢？

---------
经过尝试，更新一下，貌似  `'src/locales/components.yml'` 这个文件是需要手动创建的，不过，里边不能留空，否则 在 main.js 里边 import 导出会为 undefined 吧，初始化时候取其属性会出错，可以录入一些初始化数据，比如：
```
zh-CN:
en:
```
在开发过程中，如果保存的文件里边包含 i18n 块，会实时解析之后追加到这个文件。

建议还是文档里边说明一下，不然光看示范代码确实会有困惑。
