### ISSUE TITLE
搜索界面位置问题

### ISSUE THREAD

**Issue by williambao** [airyland/vux#15]
刚看到走了边demo.
在搜索页面里, 当focus到input后, 整个页面看不到搜索框了, 应该是键盘弹出后把搜索框挤到上面去了,
当输入一个字符后变回正常. 
![5 pic](https://cloud.githubusercontent.com/assets/779521/13520382/d3adece4-e21a-11e5-8447-fbd99a85484c.jpg)

**Comment by airyland** [comment]
多谢反馈，尽快修复
