### ISSUE TITLE
请问能获取Scroller组件滚动时候的实时位置吗

### ISSUE THREAD

**Issue by nowui** [airyland/vux#150]
我想获取Scroller组件滚动时候的位置，路由跳转之后再设置到以前的位置。这个应该怎么做啊？谢谢啦！

**Comment by airyland** [comment]
可以 使用ref取得组件引用 调用组件的_xscroll对象的方法 具体方法看xscroll文档

你是用于什么需求场景？

**Comment by airyland** [comment]
看到了，刚手机上没看到。这个实现可能要用定时器每隔一段时间记录位置

**Comment by nowui** [comment]
场景是：一个列表页面（scroller组件），一个详细页面。
问题解决了。
之前列表页面是用div布局，vue-router设置了saveScrollPosition：true，还是需要手动记录div滚动的位置。
现在列表页面换成scroller组件，不用任何操作就可以保存之前的滚动位置。
不知道有没有描述清楚。
谢谢你啊。

**Comment by nowui** [comment]
额，还没有解决 ，还是需要手动记录滚动位置的，因为和列表同一级的页面之间跳转，scroller组件会重新置顶

**Comment by airyland** [comment]
saveScrollPosition 只能用在history模式下，你是不是用hash模式了？

保存scroller的滚动位置不是每个场景都能使用，比较适合于列表条数不多的情况，数据多时比如说翻了多页，你要restore到这个位置就必须加载完前面的所有页(当然也可以手动缓存服务器数据)。

这里还有一个问题是你没法很准确地知道这个页面是不是后退回来时打开的，需要做一些判断。

**Comment by nowui** [comment]
我是用history模式。现在我用ref获取组件里的_xscroll，在beforeDestroy时候记录滚动的位置，再跳转回来在ready时候在设置scrollTop。
我是打算手动存列表的数据（包括翻页的数据），下拉刷新才更新数据。
