### ISSUE TITLE
datetime组件设置了start-date和end-date，format="YYYY-MM"时出的问题

### ISSUE THREAD

**Issue by HarryQQ** [airyland/vux#1503]
datetime组件设置了start-date和end-date，format="YYYY-MM"时出的问题,
如: 
`<datetime
                v-model="birthday"
                start-date="2013-01-01"
                end-date="2017-09-01"
                format="YYYY-MM">
</datetime>`
如选中2016年，这时月份也会被限制到最多只能选9月
文档中有说“限定最小日期，注意该限制只能限定到日期”，那只限制年月的有什么办法能解决？

**Comment by airyland** [comment]
start-date end-date 限制的是年月日，目前应该是需要至少完全包含年月日的格式：YYYY-MM-DD 才能完全正常限制。

**Comment by airyland** [comment]
#1528

**Comment by saint3347** [comment]
![image](https://user-images.githubusercontent.com/7347133/29610017-849c39c2-882b-11e7-9521-6bdeb7068713.png)
跟你一样的问题/(ㄒoㄒ)/~~，没办法解决

**Comment by airyland** [comment]
@saint3347 这个应该已经解决了。
