### ISSUE TITLE
关于ios系统中过场动画的一点问题

### ISSUE THREAD

**Issue by santiini** [airyland/vux#1504]
> 系统：ios;
> 浏览器：微信浏览器;
> 关键词：侧滑到上一页
> 详细描述：利用ios的侧滑返回上一页时，会触发上一页的过场动画，导致不自然的抖动。

**Comment by wg5945** [comment]
暂时无解，无法得知用户是点击后退按钮还是侧滑来返回上一页，如果有好的方法，欢迎pr

**Comment by santiini** [comment]
那能够禁用ios的侧滑返回功能或是在侧滑回调中直接关闭页面吗？

**Comment by wg5945** [comment]
那是native的功能，除非jssdk提供接口支持

不然的话，只能判断下，如果是在微信中打开，就禁止过场动画

**Comment by santiini** [comment]
嗯  只能这样了
