### ISSUE TITLE
PopupRadio的value问题

### ISSUE THREAD

**Issue by wangmh1990** [airyland/vux#1505]
使用PopupRadio时，如果options采用的是key-value模式，含有icon，怎么预选中目标选项。
html:
`<group label-align="left">
      <popup-radio title="支付方式" :options="payMode" v-model="currentPayMode">
        <p slot="popup-header" class="vux-1px-b popup-header">选择支付方式</p>
      </popup-radio>
    </group>`

data:
`payMode: [{
          icon: '**.png',
          key: '001',
          value: '中国工商银行'
        }, {
          icon: '**.png',
          key: '002',
          value: '中国银行'
        }
        ],
        currentPayMode: '中国银行'`

想要的效果，第一次点开PopupRadio的时候，勾选了‘中国银行’。
请问下，现在有这个功能吗，是不是我没找到方法？

**Comment by wg5945** [comment]
try
`currentPayMode: '002'`
