### ISSUE TITLE
PopupRadio的item能不能显示两行文字

### ISSUE THREAD

**Issue by wangmh1990** [airyland/vux#1508]
在使用PopupRadio的时候，发现每一条选项，显示只能有一个icon和一个label。
我有一个需求是，左边是一个较大的icon，右边有两行文字，这样的样式。
现在没有找到什么办法能做到这样。

或者有没有方法，我只用PopupRadio这种弹框交互，里面的内容我自己来定义。

**Comment by airyland** [comment]
你可以用 popup + radio 组合。radio 组件已经支持 slot:each-item，下个小版本发布。
