### ISSUE TITLE
PopupPiker 标题错乱

### ISSUE THREAD

**Issue by wangbagang** [airyland/vux#1509]
浏览器：谷歌最新版
版本：最新版2.3.4，
描述：设置PopupPiker的title后发现title在到页面的左上角位置
期望：在popuppicker顶部中间位置

**Comment by wangbagang** [comment]
需要什么细节？还描述的不够清楚吗？

**Comment by airyland** [comment]
为了说明具体呈现，你得上个截图吧？
为了让我可以重现，你得上代码吧？
