### ISSUE TITLE
Prepare for Vue@2.0

### ISSUE THREAD

**Issue by airyland** [airyland/vux#151]
- [ ] no `$dispatch` and `$broadcast`
- [ ] use v-html instead of {{{

**Vue@2.0正式版本出来时两周内支持**

**Comment by transtone** [comment]
2.0已经beta了。加油。

**Comment by transtone** [comment]
Feature of 2.0已经100%完成了！

**Comment by musicformellons** [comment]
Does this mean Vux can now be used with Vue 2.0 ?

**Comment by airyland** [comment]
@musicformellons not yet. I'm still working on it.

**Comment by fundon** [comment]
去掉双向绑定了，子组件的 value 要想更新到父组件的 value 要使用 Events 驱动。

**Comment by nicklv** [comment]
Vux can now be used with Vue 2.0 ?

**Comment by kael777** [comment]
nope

**Comment by blomdahldaniel** [comment]
Is  there any guess on when there might be?

**Comment by zhenyong** [comment]
@airyland 有支持 vue2.x 的 Roadmap（组件移植进度） 么，我们项目也用了 vux，想要贡献的话有什么参考说明吗？

**Comment by greedying** [comment]
@airyland  上次说推迟到元旦前了。 今天29号了哦~~~~~~
