### ISSUE TITLE
PopupPicker 设置标题后位置错乱

### ISSUE THREAD

**Issue by wangbagang** [airyland/vux#1510]
在文档根部放置
`<popup-picker :show="picker.show"  :title="picker.title" :data="picker.data"
                  @on-show="picker.onShow" @on-hide="picker.onHide" @on-change="picker.onChange"
                  v-model="picker.value"></popup-picker>`
设置标题后，弹出的picker标题跑到页面左上角去了，而且被阴影遮挡，查看dom后发现包含标题的class=‘vux-cell-box’ dom和 class=‘v-transfer-dom’的dom不再一个div里面

**Comment by airyland** [comment]
拜托去除业务代码，给出实际 title 值，上截图，并正确格式化代码。

**Comment by wangbagang** [comment]
我这样子设置的：

 >   this.CHANGE_PICKER({
          title: '请选择分量',
          data: [['小米1', 'iPhone1', '华为1', '情怀1', '三星1', '其他1', '不告诉你1']],
          show: true,
          value: []
        })
          
图片上传不成功，试了很多次，就是标题“请选择分量”在页面的最左上角位置

**Comment by airyland** [comment]
先传到这里，再帖链接
https://sm.ms/

**Comment by wangbagang** [comment]
麻烦您看看，因为你们的demo没有设置title的例子，所以我暂时找不到问题。
https://ooo.0o0.ooo/2017/06/02/59312ecfd5315.png

**Comment by airyland** [comment]
好像是你没有用 group 组件把 popup-picker 包起来吧？

**Comment by wangbagang** [comment]
你好，按照你说的，我添加了group组件，但是还是不行
https://ooo.0o0.ooo/2017/06/02/593131f200a50.png
https://ooo.0o0.ooo/2017/06/02/593131f626916.png

**Comment by airyland** [comment]
我不知道你想实现什么，你这里看起来就是你代码里的定位问题了。

**Comment by wangbagang** [comment]
哎，就是picker上那个title位置不对，与我的代码样式没有啥关系的，我看了就是你们组件的样式，但是现在那个title被挡住了啊，你能给我一个正常的title的截图吗？

**Comment by wangbagang** [comment]
难道你没发现你们的demo上的title全部都没有出现吗？
