### ISSUE TITLE
PupopPicker 标题错乱的问题

### ISSUE THREAD

**Issue by wangbagang** [airyland/vux#1514]
这是问题和我的代码，我已经问了第三次了，请问标题“请选择分量”为什么被遮挡，另外关闭picker后不消失？
https://ooo.0o0.ooo/2017/06/02/5931377fd8df9.png
https://ooo.0o0.ooo/2017/06/02/5931377fdd2c3.png
https://ooo.0o0.ooo/2017/06/02/5931377fe2635.png
https://ooo.0o0.ooo/2017/06/02/5931377fe854e.png
另外你们的demo的PupopPicker的title为什么没有显示出来？

**Comment by airyland** [comment]
这就是 title 

![image](https://cloud.githubusercontent.com/assets/559179/26721257/d6619210-47bd-11e7-8ec2-495a27bcaf9b.png)

你问了3次你哪一次有说清楚你到底是要什么显示效果。
