### ISSUE TITLE
苹果手机微信支付问题

### ISSUE THREAD

**Issue by mengkeys** [airyland/vux#1516]
使用WechatPlugin调用微信支付
版本： 2.1.1-rc.9
问题：调用微信支付，Android手机可以正常支付，IOS系统微信检测支付路径错误, 微信相关设置均正确，在发起支付，通过服务端获取签名等参数后，微信客户端调用微信支付时，提示URL没有注册，但当前页面的路径与微信客户端识别后提示的路径不一致，Android客户端没有问题，只是IOS出现此问题，求助！

**Comment by airyland** [comment]
和 vux 没有关系，vux 仅仅把 jssdk 包装成模块。

**Comment by userfhy** [comment]
也遇到了同样的问题 
在 url 中 #号前加 ? 号 类似：
/index.html?#/
