### ISSUE TITLE
在Popup中使用PopupPicker，两者的mask是同一个，点击mask两个popup都会关闭

### ISSUE THREAD

**Issue by fmwww** [airyland/vux#1517]
在弹出的Popup中放置PopupPicker，然后点击PopupPicker，发现弹出PopupPicker没有遮罩层，点击Popup的遮罩层，两个都会关闭

**Comment by graysheeep** [comment]
不建议在popup中再放置一个popuppicker，可以先关闭第一个popup再打开一个popuppicker
