### ISSUE TITLE
[suggestion] Panel component add a URL attribute,

### ISSUE THREAD

**Issue by ph2-cst** [airyland/vux#152]
I think it is  very convenient.

**Comment by airyland** [comment]
It's hard to satisfy all the situations here. Some may want to use `href`, while others may want to use `v-link`.

**Comment by ph2-cst** [comment]
Oh.
But press and open in new tab, it does not open expectant url if href is not set

**Comment by airyland** [comment]
@ph2-cst Ok, Will be supported in next patch version.

+ if not using `vue-router`, will use `location.href` for redirection
+ if using `vue-router`, will use `this.$router.go` for redirection
+ if the url is start with `http`, still use `location.href` for redirection
+ for other people wanting to handle redirection by themselves, use event:`on-click-item`

**Comment by airyland** [comment]
See https://github.com/airyland/vux/blob/master/src/demos/Panel.vue#L26
