### ISSUE TITLE
Swiper 组件 数据有且只有两条时，第二幅图 配置的 url 跳转无效 。

### ISSUE THREAD

**Issue by yangbiaoit** [airyland/vux#1520]
Swiper 组件 数据有且只有两条时，第二幅图 配置的 url 跳转无效 。

**Comment by wg5945** [comment]
<a href="https://vux.li/demos/v2/#/component/swiper">https://vux.li/demos/v2/#/component/swiper</a>

官网demo的最后一个貌似就是你这种情况，应该是可以跳转的

请贴出你的测试代码

**Comment by yangbiaoit** [comment]
<template>
    <div class="container">
        <search-item @inputChange="keywordChange"
                     @inputFocus="inputFocus"
                     v-model="keywords"
                     :pathName="pathName"
                     :isScrolling="isScrolling"
        ></search-item>
        <scroller ref="horizontalScroller" lock-y :scrollbar-x=false class="channel-scroller">
            <div class="channel-scroll-box" :style="{width: horizontalWidth}">
                <channel-item v-for="(item, index) in channelList"
                              :key="item.id"
                              :item="item"
                              :on-select="handleChannelSelect"
                              :selected="!currChannel ? (!!keywords ? false : false) : (currChannel == item.id)"
                ></channel-item>
            </div>
        </scroller>

        <scroller ref="scroller" lock-x class="list-scroller"
                  :pulldown-config="pulldownconfig"
                  :pullup-config="pullupconfig"
                  use-pullup
                  use-pulldown
                  @on-scroll="onScroll"
                  @on-pulldown-loading="pullDownLoading"
                  @on-pullup-loading="pullUpLoading"
                  v-model="status">

            <div class="scroll-box">
              
                <div v-if="articleList.length==0 && !advertise">
                    <no-content ></no-content>
                </div>
                <div v-else="articleList.length>0 || advertise" >
                    <swiper loop auto :list="swiperList"
                            :index="swiper_index"
                            @on-index-change="swiper_onIndexChange"
                            :aspect-ratio="328/750"
                            dots-position="center"
                            v-show="sort===1"
                    ></swiper>
                    <article-item v-for="(item, index) in articleList"
                                  :index="index"
                                  :advertise="advertise"
                                  :item="item"
                                  :key="item.id"
                                  :is-last="index === articleList.length - 1"
                    ></article-item>
                    <div v-if="articleList.length<3 && advertise" >
                        <ad-item :is-last="false" :advertise="advertise"></ad-item>
                    </div>
                </div>
            </div>

        </scroller>

    </div>
</template>




是的 官网最后一个例子就是我这种情况。我使用过程中只是将swiper  嵌到了scroller 中。

**Comment by wg5945** [comment]
如果只是将swiper 嵌到了scroller 中的话，请参考代码

https://github.com/airyland/vux/blob/v2/src/demos/ScrollerSwiper.vue

**Comment by yangbiaoit** [comment]
ok 了 ，多谢！
