### ISSUE TITLE
AjaxPlugin的post请求报404问题

### ISSUE THREAD

**Issue by wangmh1990** [airyland/vux#1523]
没有设置proxyTable
请求代码：
`this.$http.post('/static/data/getOrderInfo.json')
        .then(function (data) {
          console.log(data);
        }, function (error) {
          console.log(error);
        });`
getOrderInfo.json是本地json对象。
post的时候报404
如果改为get则正常。
我是要配置什么吗？

**Comment by airyland** [comment]
业务问题不在解决范围内。ajax 基于 axios 参照相关文档。
