### ISSUE TITLE
引入reset.less报错。请问怎么解决

### ISSUE THREAD

**Issue by city8866** [airyland/vux#1525]
in ./~/_css-loader@0.28.4@css-loader?{"minimize":false,"sourceMap":false}!./~/_vux@2.3.4@vux/src/styles/weui/base/reset.less
Module build failed: Unknown word (24:5)

  22 | a {
  23 |     text-decoration: none;
> 24 |     .setTapColor();
     |     ^
  25 | }

 @ ./~/_css-loader@0.28.4@css-loader?{"minimize":false,"sourceMap":false}!./~/_vux@2.3.4@vux/src/styles/reset.less 3:10-134
 @ ./~/_css-loader@0.28.4@css-loader?{"minimize":false,"sourceMap":false}!./~/_vue-loader@11.3.4@vue-loader/lib/style-compiler?{"id":"data-v-52d1181f","scoped":false,"hasInlineConfig":false}!./~/_vux-loader@1.0.63@vux-loader/src/style-loader.js!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
 @ ./~/_vue-style-loader@2.0.5@vue-style-loader!./~/_css-loader@0.28.4@css-loader?{"minimize":false,"sourceMap":false}!./~/_vue-loader@11.3.4@vue-loader/lib/style-compiler?{"id":"data-v-52d1181f","scoped":false,"hasInlineConfig":false}!./~/_vux-loader@1.0.63@vux-loader/src/style-loader.js!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by airyland** [comment]
确认 less less-loader 已经安装。如果还不行，建一个 repo 重现。
