### ISSUE TITLE
怎么获取循环出来的Rater值

### ISSUE THREAD

**Issue by 563325028** [airyland/vux#1526]
是这样的 现在是有个评价功能 假如我要评价3个商品 那么就应该一个商品对应一个rater 可是我不知道该怎么取到每一个的rater的值 求问该怎么办  如果设置了v-model那就都同步了 代码跟下面差不多
```
<div v-for="i in shangpin">

<rater  slot="value" active-color="#771ec8" star="★"></rater>
</div>
```

**Comment by graysheeep** [comment]
data中放置一个数组val[]存放每一个rater的值，不要用v-model绑定，手写value=val[n],然后在onChange中更改数组中对应的值
