### ISSUE TITLE
【BUG】DateTime 组件 月份选择BUG

### ISSUE THREAD

**Issue by showbestriven** [airyland/vux#1528]
**代码：**
`<datetime v-model="endTime" start-date="2016-06" end-date="2017-06" format="YYYY-MM" title="结束时间" confirm-text="确认" cancel-text="取消" placeholder="请选择申请日期"></datetime>`

**问题**
当值显示年月的时候 2016年6月以后的月份没有了！ 2016年和2017年均只能选择 1 到 6 月份的月份  正常应该是 2016年 6 7  9 10 11 12 月 到 2017年 1  2 3 4 5 6月

**Comment by showbestriven** [comment]
![image](https://user-images.githubusercontent.com/25165547/26915455-a7dc2668-4c58-11e7-8be8-e06fed588657.png)
![image](https://user-images.githubusercontent.com/25165547/26915471-b6b99080-4c58-11e7-867f-99627b09a6c7.png)

**Comment by airyland** [comment]
vux@2.3.7-beta.1

**Comment by showbestriven** [comment]
感谢作者的及时修复　但是ＮＰＭ上目前没有２.３.７版本

**Comment by airyland** [comment]
有的。vux@beta 里。
