### ISSUE TITLE
在Popup中使用 Scroller 无法滚动

### ISSUE THREAD

**Issue by wjs** [airyland/vux#153]
### Version
0.0.110 和 0.0.111 都有这个问题

### Android or iOS, which browser?
所有浏览器

### Your Codes 

``` html
<popup height="50%" :show.sync="show">
  <scroller lock-x height="200px">
     <div class="box2">
       <p v-for="i in 80">placeholder {{i}}</p>
     </div>
  </scroller>
</popup>
```

### Expected behavior and actual behavior.
希望能够正常滚动，现在横向和纵向都不能正常滚动。

### Steps to reproduce the problem
只要在Popup中使用 scroller 就会出现。

**Comment by airyland** [comment]
Will be fixed in v0.0.113

**Comment by wjs** [comment]
@airyland  请问大大 v0.0.113 啥时候发布呀，因为在公司项目中使用了，所以希望知道一下发布时间（本周能否发布？）。  
如果发布时间比较晚，希望能提示一下临时解决方案。看了一下源码觉得大致是那个`touchmove` 的问题，所以想问一下有什么比较好的临时解决方案么？
```javascript
PickerDialog.prototype._bindEvents = function () {
  var _this = this

  function triggerClick (e) {
    _this.hide()
    _this.emit('close')
  }
  Tap.tap(this.mask, triggerClick)
  this.container.addEventListener('touchmove', function (e) {
    e.stopPropagation()
    e.preventDefault()
    return false
  }, false)
  return this
}
```

**Comment by airyland** [comment]
@wjs Plan to release Before Thursday

**Comment by wjs** [comment]
👍  thanks a lot 😄

**Comment by sandysong** [comment]
遇到同样问题，盼修复

**Comment by sandysong** [comment]
作者大大你优先把这个bug修了呗，我再请你喝杯咖啡

**Comment by airyland** [comment]
我忘了这周一是放假，预计发布时间早了一天，喝咖啡也治不了我感冒啊。

**Comment by wjs** [comment]
>_< 临时方案我直接改 popup 源码和overflow: auto 了，后面再重构吧。大大你好好养病吧

**Comment by airyland** [comment]
@wjs 在popup里你用来显示什么内容需要滚动的？我收集下应用场景。

**Comment by wjs** [comment]
其实 popup 我希望可以加个配置想，可以从上往下划出来，所以我自己封装了个popdown -，-
使用场景其实就是 列表页的搜索筛选项，筛选项是动态加载的；纵向可以滚动，点击之后动态加载二级子菜单，子菜单纵向也可以滚动；子菜单还有可能继续展开，所以横向也是可以滚动的。（其实这个交互就挺反人类的。。。）

**Comment by airyland** [comment]
@wjs 听起来好复杂，是不是和电商网站列表页面顶部的筛选栏一样的功能。

**Comment by airyland** [comment]
我想了想这个问题其实临时解决起来也挺简单，在popup出现时reset一下scroller应该就解决了。

`this.$refs.scroller.reset()`

为了节省操作，会在popup上提供`on-first-show`事件用于首次render

**Comment by wjs** [comment]
@airyland 对的，场景不算太通用。所以我建议就是 popup 可以加个参数变成 popdown 之类的，然后就是让它可以 touchumove 。   
而像这种具体场景的就不太好弄成通用组件，因为 props 根据具体情况。像我现在直接自己包一层，然后滚动直接使用 overflow: auto 感觉也还可以。如果后面 scroller 用起来更加丝滑而且没有问题的滑，或许也会换上。

**Comment by airyland** [comment]
@wjs popdown 能否截个图看看？

**Comment by wjs** [comment]
原来是popup出现时候 reset额，上次我试的是在筛选项加载完之后reset好像没起作用，可能姿势不对。  
popdown 就是 popup 从上往下出现，然后 picker-dialog 在上方，我自己包一层的时候，内部直接使用了popup，然后改了动画和css而已 -，-

**Comment by airyland** [comment]
http://vux.mao.li/#!/component/popup

**Comment by wjs** [comment]
👍
