### ISSUE TITLE
关于index文件里引入manifest

### ISSUE THREAD

**Issue by lyj505** [airyland/vux#1531]
### 在目录文件里面的index.html 里加入了<%=htmlWebpackPlugin.files.webpackManifest%> 之后,通过命令行编译打包在dist文件之后,会在新生成的index.html 里 增加 代码...为什么不直接引用dist/js/manifest 文件呢...一定要这么配置....不知道为啥~~求解答.....

**Comment by airyland** [comment]
文档应该写了，这只是为了省掉一个js请求。

**Comment by lyj505** [comment]
3k....没注意看官文~~,那如果要引入的话,需要把vux-loader 里面的 配置 {
  name: 'inline-manifest'
}  删掉然后将index.html 里面这段代码删掉了就行了吧?.........

**Comment by airyland** [comment]
yes.

**Comment by lyj505** [comment]
@airyland  十分感谢~~~搞了几天...没搞懂...以后还是得学习webpack的配置~
