### ISSUE TITLE
Range控件step导致死循环,数组无限增大,造成浏览器内存不足

### ISSUE THREAD

**Issue by Microanswer** [airyland/vux#1532]
Vux版本: 2.3.4
文档中range的step默认是1,但是源代码中默认却是0.
![image](https://user-images.githubusercontent.com/19423902/26924157-2ec3e95e-4c77-11e7-9f66-2bcd33ec4b0b.png)

导致Powerange.prototype.step方法中part和interval变量均为0,
for (let i = 0; i <= dimension; i += interval) {
    steps.push(i)
  }
这个循环就死了.steps数组无限增大导致内存不足.

开发者解决方案: 在使用range控件的时候,显示的指定:step="1"

**Comment by graysheeep** [comment]
fixed #1534
