### ISSUE TITLE
一次性注册vux所有组件

### ISSUE THREAD

**Issue by RenShine** [airyland/vux#1533]
main.js中这一段

![image](https://user-images.githubusercontent.com/6385962/26931945-b13f9f28-4c94-11e7-8915-c90033fa97e3.png)

可不可以改成export default  

方便使用者直接
`import vux from 'vux'; Vue.use(vux)`
避免每个组件都要经常性的引入vux

**Comment by airyland** [comment]
在移动端这样做你考虑过用户感受嘛。
你不想在每个组件引入，你就在 main.js 全局注册要使用到的组件就好了。

**Comment by RenShine** [comment]
如果不愿意直接全部引入的话也同样是可以import { message } from 'vux' 这样的吖
