### ISSUE TITLE
ButtonTabItem在ios cordova下卡顿

### ISSUE THREAD

**Issue by cinos1** [airyland/vux#1535]
使用cordova对vux进行打包，在android下一切正常，在ios的微信或safari浏览器也表现正常，但是打包后，点击按钮明显感觉卡顿，大约响应时间在0.5秒左右。没找到具体原因。

**Comment by huangzhenxian** [comment]
ios使用wkwebview试一试
https://github.com/ionic-team/cordova-plugin-wkwebview-engine

**Comment by cinos1** [comment]
嗯，感谢回复，应该不是这个原因，刚才我试了试，直接用git下载的官方完整demo打包，在ios上运行非常流畅。我自己按照教程写了一个简单页面反而不行。是不是官方demo引入了某些打开web硬件加速的插件或者选项？

**Comment by airyland** [comment]
@cinos1 demo 没有黑科技，和教程写出来的是一致的。你可以上个 repo 看看。

**Comment by cinos1** [comment]
@airyland 确实如此，我刚才重新更新了下cordova最新版，打包后一切正常，button效果切换也很流畅，可能是我原来的环境使用xcode7.3所致。感谢。
