### ISSUE TITLE
JS IOS/iPhone的Safari不兼容Javascript中的Date()

### ISSUE THREAD

**Issue by LikeDege** [airyland/vux#1536]
日期字符串转成Date类型，在ios下有兼容性问题，不能使用new Date('20170/01/01')，在datetime组件发现有使用

相关链接，亲测确实如此
http://www.cnblogs.com/yiven/p/6053872.html

**Comment by airyland** [comment]
哪一行代码？

**Comment by LikeDege** [comment]
@airyland   datetimepicker.js

  if (typeof this.config.startDate === 'string') {
    this.config.startDate = new Date(this.config.startDate.replace(/-/g, '/'))
  }

  if (typeof this.config.endDate === 'string') {
    this.config.endDate = new Date(this.config.endDate.replace(/-/g, '/'))
  }

**Comment by LikeDege** [comment]
@airyland datetimepicker.js

```
if (typeof this.config.startDate === 'string') {
this.config.startDate = new Date(this.config.startDate.replace(/-/g, '/'))
}

if (typeof this.config.endDate === 'string') {
this.config.endDate = new Date(this.config.endDate.replace(/-/g, '/'))
}

```

**Comment by airyland** [comment]
iOS 是支持  `2017/01/01` 这种格式的。

**Comment by LikeDege** [comment]
@airyland IOS webview使用new Date('2017/01/01') 是会报invalid date的，真不是瞎说
