### ISSUE TITLE
sticky无法正常运行

### ISSUE THREAD

**Issue by echozhangzy8888** [airyland/vux#1543]
项目 package.json内容
  "dependencies": {
    "axios": "^0.16.1",
    "highcharts": "^5.0.10",
    "jsonp": "^0.2.1",
    "swiper": "^3.4.2",
    "vee-validate": "^2.0.0-rc.2",
    "vue": "^2.2.2",
    "vue-router": "^2.3.0",
    "vux": "^2.3.6"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.2.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.10.0",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "less-loader": "^4.0.3",
    "node-sass": "^4.5.2",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.1.0",
    "rimraf": "^2.6.0",
    "sass-loader": "^6.0.3",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "url-loader": "^0.5.8",
    "vue-loader": "^11.1.4",
    "vue-style-loader": "^2.0.0",
    "vue-template-compiler": "^2.2.4",
    "vux-loader": "^1.0.57",
    "webpack": "^2.2.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1"
  },

问题描述：将vux里的sticky的demo代码原封不动复制进来 运行
浏览器 错误提示 
`sticky.js?1f43:62 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at eval (eval at 319 (21.js:29), <anonymous>:60:16)
​`
 scrollBox.addEventListener('scroll', scrollHandler)
这句报错

**Comment by airyland** [comment]
不要直接复制。看清楚参数，如果指定了滚动容器而你那边并没有当然会报错。
