### ISSUE TITLE
webpack.base.conf引入vux-loader 报错：A valid query string passed to parseQuery should begin with '?'

### ISSUE THREAD

**Issue by wuxingtao** [airyland/vux#1546]
vue2 引入vux-loader webpack报错
流程：
npm install vux --save
npm install vux-loader --save-dev

修改配置：webpack.base.conf.js 
将原module.exports 赋值给webpackConfig
npm run dev
```
//报错
Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
    at Object.parseQuery (...\node_modules\_loader-utils@1.1.0@loader-utils\lib\parseQuery.js:13:9)
    at Object.module.exports (...\node_modules\vux-loader\src\index.js:63:21)

 @ ./src/router/index.js 4:0-38
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

更新babel-loader,vue-loader,url-loader还是无效。
```
    "vue": "^2.3.3",
    "vue-router": "^2.3.1",
    "vuex": "^2.3.1",
    "vux": "^2.3.6"
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-merge": "^4.1.0"
```
求解

**Comment by airyland** [comment]
并不能猜出你具体怎么配置的， 麻烦上 repo 再 reopen。

**Comment by wuxingtao** [comment]
使用ncu将包全部升级了一下，重新安装好使了，我可能某个包出问题了

**Comment by yuemeimei** [comment]
我报的错和你不一样，
//报错
\wechat\wechat\node_modules\_vux-loader@1.1.1@vux-loader\src\index.js:341
      const hasVueLoader = rule.use && rule.use.length && rule.use.filter(function(one) {
                                                                   ^

TypeError: rule.use.filter is not a function
    at D:\wechat\wechat\node_modules\_vux-loader@1.1.1@vux-loader\src\index.js:341:68
    at Array.forEach (native)
    at Function.module.exports.merge (D:\wechat\wechat\node_modules\_vux-loader@1.1.1@vux-loader\src\index.js:340:30

//配置
![image](https://user-images.githubusercontent.com/23489614/28048679-12714a18-6625-11e7-8e96-2d95ca9aac8e.png)

//webpack.base.config.js 配置
var  vuxLoader = require('vux-loader')
const  webpackConfig = {...}
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui']
});

**Comment by yuemeimei** [comment]
![image](https://user-images.githubusercontent.com/23489614/28048826-039bd994-6626-11e7-9472-23a219e036be.png)
