### ISSUE TITLE
使用vux构建后的项目 很大

### ISSUE THREAD

**Issue by rainbowzx** [airyland/vux#1548]
能不能让我们自己调用想要的模块  
const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [{
    name: 'vux-ui'
  }]
})
这一步是不是把所有组件都加载进来了

**Comment by airyland** [comment]
信息完全不足以重现，请建个 repo 重现。
