### ISSUE TITLE
x-input 设置max无效

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#1549]
```
    <group title="固话缴费">
      <x-input placeholder="请输入固话号码" type="number" :max="11" class="weui-input-custom"></x-input>
      <p class="tip">区号 + 电话号码</p>
    </group>
```
超过设置最大长度还能够继续输入

**Comment by wg5945** [comment]
改成tel吧， maxlength不能用于number

**Comment by jsonviewer** [comment]
@wg5945 tel可以输入字母

**Comment by wg5945** [comment]
你那个不是11位手机号码么，用tel就可以了

如果非要用number的话，估计只能手动slice了

**Comment by airyland** [comment]
@wg5945 这里也可以在组件里处理，值变化时直接 cut 掉超过长度的数字，但是有没有必要这样做？不只一个用户提出这个问题。

**Comment by jsonviewer** [comment]
@wg5945 我是说用tel 可以输入字母，我想让只输入数字

**Comment by jsonviewer** [comment]
@airyland tel目前能够输入字母，不知道是不是个bug

**Comment by wg5945** [comment]
`
<x-input placeholder="请输入固话号码" type="tel" :max="11" class="weui-input-custom"></x-input>
`

你这么写的话只能输入字母？

are you sure?

**Comment by jsonviewer** [comment]
@wg5945 可能sure，我是说可以输入字母不是说只能输入字母，我想只输入数字，电话不应该有字母吧。。
![image](https://user-images.githubusercontent.com/22734724/27071139-4c3c46f4-504e-11e7-901c-4e993c933425.png)

**Comment by wg5945** [comment]
你是在pc上的吧，在mobile上试试

**Comment by jsonviewer** [comment]
@wg5945 ok

**Comment by hashdrinker** [comment]
把 type="number" 改成 keyboard="number"
