### ISSUE TITLE
tabbar在微信浏览器上无法固定在底部

### ISSUE THREAD

**Issue by 530140303** [airyland/vux#1550]
此处为源码
<template>
  <view-box>
    <swiper loop auto :list="swiperImgList"></swiper>
    <product-list-item v-for="obj in dataList" :key="obj.pid" :obj="obj"></product-list-item>
    <my-footer></my-footer>
  </view-box>
</template>
my-footer为公共的tabbar组件
在微信浏览器上滑动时无法固定在底部。

**Comment by airyland** [comment]
这代码好歹格式下。
如果你使用 view-box，你应该注意到要用 slot。

``` js
<tabbar slot="bottom"></tabbar>
```
