### ISSUE TITLE
使用XNumber v-model 时会报错

### ISSUE THREAD

**Issue by lynnnnnnnn** [airyland/vux#1554]
Invalid prop: custom validator check failed for prop "value"

found in

---> <XNumber> at D:\Work\Vue2 Project\vmicro-mall\client\mobile-vux\node_modules\vux\src\components\x-number\index.vue

**Comment by lynnnnnnnn** [comment]
增加数值时会 v-model 的值类型会变成字符串

**Comment by woodytang** [comment]
我也遇到一样的问题，@airyland  为什么要关闭

**Comment by airyland** [comment]
因为修复了 https://vux.li/#/zh-CN/changes
