### ISSUE TITLE
PopupPicker  show默认为true时 mask 没有显示

### ISSUE THREAD

**Issue by finefun55** [airyland/vux#1555]
![issue](https://user-images.githubusercontent.com/6128731/27066987-af926774-503a-11e7-85ca-45ddbd8b95b1.png)
<popup-picker
                :title="data.title"
                :data="data.list"
                :columns="2"
                :show="true"
                v-model="data.value"
                @on-change="onChange"
                :display-format="returnName"
                ref="picker">
        </popup-picker>

vux：2.1.1
vue：2.2.0
chrome：版本 61.0.3128.0（正式版本）canary （64 位）

**Comment by airyland** [comment]
v2.3.7-beta.2
