### ISSUE TITLE
组件缺少样式引用

### ISSUE THREAD

**Issue by huaxinjiayou** [airyland/vux#1561]
![image](https://user-images.githubusercontent.com/1059680/27095260-9192c0f6-509f-11e7-9ac8-63baf23d74a4.png)
使用上面的组件写了个简单的页面，页面的显示如下，审查后发现没有引用字体图标的样式
![image](https://user-images.githubusercontent.com/1059680/27095302-c00e3794-509f-11e7-8697-8e000408071d.png)

随便加个XInput，在页面进行使用，字体图标的样式就加载进来了，显示正常
![image](https://user-images.githubusercontent.com/1059680/27095392-0e3975f0-50a0-11e7-934c-777aba0ef074.png)
![image](https://user-images.githubusercontent.com/1059680/27095424-251568b0-50a0-11e7-9d7b-9942958af068.png)

不知道是不是Checklist组件没有引用到 weui_icon_font.less

同样的问题也发生在PopupPicker组件中，如果只用Group+PopupPicker，打包后是缺少`.vux-cell-primary{flex: 1;}`这个样式的，导致无法左右排列

版本vux 2.3.5，vux-loader 1.0.63，配置都是使用说明的配置=。=

**Comment by airyland** [comment]
checklist 默认是有引入  icon 的，无法重现。
popup-picker 昨天刚好补充了样式。
