### ISSUE TITLE
ViewBox 组件文档介绍错误

### ISSUE THREAD

**Issue by ghost** [airyland/vux#1563]
<img width="956" alt="qq20170614-141444 2x" src="https://user-images.githubusercontent.com/12068304/27118057-0cbb093e-510c-11e7-8cd0-7f028f856a34.png">

如图 body-padding-top 与 body-padding-bottom 属于 props 不属于 slot，且 body-padding-top 为顶部内边距，不为底部

我是看组件源码才发现问题的

**Comment by airyland** [comment]
然而其他人没发现 😅

**Comment by ghost** [comment]
没发现，说明没人用或者没看。。。这么明显不可能发现不了
