### ISSUE TITLE
InlineCalendar【一个不太友好的小BUG】

### ISSUE THREAD

**Issue by showbestriven** [airyland/vux#1564]
![image](https://user-images.githubusercontent.com/25165547/27127586-2f40d58e-512e-11e7-961e-29e56689e727.png)

show-last-month 和  show-next-month 为false时 即不显示上下月的日期时 隐藏了 但是还可以点击空白出 切换页面  这样不友好
虽然这个可以通过设置 start-date 和 end-date 配合 disable-past 和 disable-future 解决 
但是显得有点繁琐
 
//而且建议作者可以加上个万年历 还有假期配置选项 作为可选模块 ~~

**Comment by airyland** [comment]
万年历和假期配置可以通过 slot:each-day 来定义每一项，毕竟我并不知道具体怎么显示。

**Comment by showbestriven** [comment]
嗯嗯 这个我知道！
