### ISSUE TITLE
疑似vux-loader问题导致 run build后 js体积过大

### ISSUE THREAD

**Issue by greedying** [airyland/vux#1565]
### 现象
使用vux插件的时候，如果后面注释内有对vux插件的引用，最后run build后的vendor.js和app.js体积比正常大几百K。
推测是vux-loader问题，但并没有去求证。

### 复现
+ 新建 `airyland/vux2`项目，yarn 
+ 将以下代码放入 `src/main.js`中，npm run build 

```javascript
import { AlertPlugin } from 'vux'
Vue.use(AlertPlugin)

// import { xxx } from 'vux'
```

**Comment by airyland** [comment]
可以再试试 vux-loader@1.0.67

**Comment by greedying** [comment]
的确可以了。

**Comment by lanrain** [comment]
这优化后的体积相当震撼啊
