### ISSUE TITLE
关于表单验证的问题

### ISSUE THREAD

**Issue by zhanfenghai** [airyland/vux#1566]
需求如下:
我有一个表单页,其中有很多的表单项,根据表单项的各类验证设置,最后全部完成并且校验成功后提交按钮才会高亮且可以触发

**Comment by wg5945** [comment]
设置button的disabled属性即可

**Comment by airyland** [comment]
同楼上，一般就是 disabled 关联各个字段的验证状态

**Comment by zhanfenghai** [comment]
@airyland 这样的话相当于是手动去判断了,一旦表单项增多,工作量无疑会加重

**Comment by airyland** [comment]
@zhanfenghai 是的，目前没有做 group 子组件的统一验证，主要是还没有想好。

**Comment by airyland** [comment]
Moved to #1346
