### ISSUE TITLE
vux打包后的文件体积过大

### ISSUE THREAD

**Issue by RenShine** [airyland/vux#1567]
我代码中使用到vux的地方只有2处

第一处是这里
![image](https://user-images.githubusercontent.com/6385962/27173266-ad5ade9e-51ea-11e7-838b-c497672fde53.png)

第二处是这里：

![image](https://user-images.githubusercontent.com/6385962/27173226-8a34b3cc-51ea-11e7-970e-770291489d58.png)

用webpack打包后的依赖报表如下：

![image](https://user-images.githubusercontent.com/6385962/27173296-c6d0ef30-51ea-11e7-96ee-f236ecec262c.png)

其中尤以这个datas为最  有800多K

这里大部分的组件我都没用使用到   要怎样才能不打包到我的文件里面来？

**Comment by greedying** [comment]
哈哈，这不是我昨天提的那个问题么-

**Comment by RenShine** [comment]
@greedying   看了一下你昨天的issue  果然是同一个问题。。   升级一下vuxloader就可以了。。。   谢谢。。。

**Comment by nongzhenli** [comment]
@RenShine 请问你这个报表是用什么工具实现的？还有，我升级了vux-loader.....好像打包出来还是很大。。。一个简单的页面就有 1.4M.....

**Comment by RenShine** [comment]
@bigheiqin  https://www.npmjs.com/package/webpack-bundle-analyzer  不好意思回复晚了
