### ISSUE TITLE
地址json 如何引入

### ISSUE THREAD

**Issue by yhZhouYh** [airyland/vux#157]

**Comment by lichunqiang** [comment]
直接import就好

```
import Cell from 'vux/src/components/address/list.json'
```

**Comment by yhZhouYh** [comment]
@lichunqiang  谢谢

**Comment by lichunqiang** [comment]
解决了就关闭issue吧

**Comment by yhZhouYh** [comment]
@lichunqiang 我第一种方式单独引入的打完包 还有500多K vue-cli 生成的项目 加了vue-router 和vue-recource

**Comment by lichunqiang** [comment]
不用担心，你可以看看https://vux.li/ ，把所有的组件都打包到一个文件了，你看看多大

**Comment by airyland** [comment]
@yhZhouYh 第一种方式是指？ 理论上不应该有500多k才对

**Comment by yhZhouYh** [comment]
@airyland 就是直接引你components 下的

**Comment by airyland** [comment]
@yhZhouYh 地址信息比较大，有180多k，加上vue vue-resource vue-router 和模块代码什么的应该确实有500k。地址库建议异步加载。

**Comment by yhZhouYh** [comment]
@airyland 还没引。地址就500多K。 我在想是不是打包什么地方出了问题。项目还没完成 =。=！

**Comment by airyland** [comment]
@yhZhouYh 你确定你引入的包总大小没有500多k么
