### ISSUE TITLE
关于fis3集成vux

### ISSUE THREAD

**Issue by rainwalkerhu** [airyland/vux#1571]
你好，我们项目在一开始的时候就使用了vux，我在一开始搭建该项目的时候用的是webpack,由于公司使用的平台是fis3,所以现在需要从webpack迁移到fis3,但是由于没有相关loader导致fis3无法正确打包，自身能力有限还没找到解决办法，特意来求助（本人有意愿学习开发或者迁移vux-loader,如能给予指点感激不尽），另外感谢大神对开源世界的贡献

**Comment by airyland** [comment]
建议直接用 webpack。

vux-loader 不是一个独立的插件它是需要配合 vue-loader 使用的，而 vue-loader 也不是一个单独脚本，它依赖了 n 多的 webpack loader，所以要迁移到 fis3 会特别特别麻烦。不建议这样折腾。因为你是第一次提出适配 fis 的，说明使用 fis 的用户不多 😅 。。

vue-loader 有官方在持续维护，我看了下 fis 并没有官方维护的 vue 插件，因此 vux 也不计划支持 fis 。。

**Comment by rainwalkerhu** [comment]
好的，感谢

**Comment by rainwalkerhu** [comment]
好的，感谢 @airyland
