### ISSUE TITLE
希望group组件的label-align能做个两端对齐

### ISSUE THREAD

**Issue by lavyun** [airyland/vux#1574]
现在只有left和right选项，希望能有个 justify 两端对齐的选项。

**Comment by airyland** [comment]
其实一开始有尝试实现过，存在兼容问题没有完全解决。

**Comment by lavyun** [comment]
我这里有个小demo，不知道是否有用

[https://jsfiddle.net/b0h4xx99/](https://jsfiddle.net/b0h4xx99/)
