### ISSUE TITLE
InlineCalendar组件缺少选择后触发时间

### ISSUE THREAD

**Issue by tongjh2** [airyland/vux#1575]
inline-calendar组件缺少change事件，当选定时间后需要change事件来触发后续动作，目前只有监听v-model的数据改变，目前是在watch中去发ajax，希望官方整个change事件

```
watch:{
        cdate(val,oldVal){
            console.log(val,oldVal)
        }
}
```

**Comment by airyland** [comment]
使用 `on-change` 事件。

**Comment by tongjh2** [comment]
谢谢，我看了源码确实有on-change、input事件,只是文档中没写
