### ISSUE TITLE
有没有办法在Datetime组件中保留placeholder的情况下，设置popup picker的初始值？

### ISSUE THREAD

**Issue by git9527** [airyland/vux#1576]
``` html
 <datetime title="转正日期" placeholder="请选择转正日期" v-model="convertDay" :min-year=1960 :max-year=2017 confirm-text="完成" cancel-text="取消"></datetime>
```

如上代码所示，转正日期在1960-2017之间，有没有办法在保留placeholder的情况下，设置popup picker的初始值为2000-01-01?

**Comment by airyland** [comment]
场景？

**Comment by git9527** [comment]
<datetime title="转正日期" placeholder="请选择转正日期" v-model="convertDay" :min-year=1960 :max-year=2017 confirm-text="完成" cancel-text="取消"></datetime>

**Comment by git9527** [comment]
在资料填写页面，需要用户选择自己的转正日期，时间范围是1960-2017，既想保留给用户的提示，又想给popup一个初始值，减少大部分人的滑动次数，取个稍微折中的值2000-01-01

**Comment by airyland** [comment]
明白了。但是你这里的初始值实际是初始显示值，除非用户点确定，否则不同步到 v-model 值对吧。

**Comment by git9527** [comment]
嗯，一旦同步到v-model，placeholder就没了

**Comment by airyland** [comment]
try vux@2.4.1-beta.1

**Comment by git9527** [comment]
2.4.1-beta.1确实OK了

**Comment by git9527** [comment]
碰到了奇怪的事情，官网的demo中显示用的是2.4.0版本的vux，但从github的tag来看，2.4.0并没有包含这个feature？
![image](https://user-images.githubusercontent.com/4514520/27286802-04100d76-5534-11e7-9e41-58f13cf2fcef.png)

**Comment by airyland** [comment]
我的错，beta 是不会写到 package.json 里的，demo 永久是最新代码。。

**Comment by git9527** [comment]
好吧，我还以为demo是当前最新的release版。。。
