### ISSUE TITLE
组件没有name字段，具体如下

### ISSUE THREAD

**Issue by ccode-code** [airyland/vux#1577]
因为引入多个框架组件，所有的都是按需引入，统一建立了一个component.js用于集合组件。

vux部分组件没有name字段，我下了如下图处理，但是太多，这样书写太麻烦，JS还不能反射变量。

![image](https://user-images.githubusercontent.com/10229333/27273108-2497feb6-5500-11e7-88d9-c085a277087b.png)

建议在组件增加name字段。感谢@airyland

**Comment by airyland** [comment]
可以尝试最新 vux@beta
