### ISSUE TITLE
x-address只想选择省或者只想选择市的时候该怎么选择

### ISSUE THREAD

**Issue by zhuangbb** [airyland/vux#1578]

**Comment by airyland** [comment]
并不支持这样，x-address 组件是联动组件。只选择市组件如何知道你要选择哪个省？
所以如果你的需求是分别选择省市，需要自己实现。

**Comment by zhuangbb** [comment]
我知道  我意思是只选择省   或者只选择省 市  或者选择省 市 区  ,,有个需求是需要客户是省代理或者市级代理

**Comment by airyland** [comment]
hide-district 可以只显示省市。只显示省这个暂时没有。

**Comment by CodLee** [comment]
x-address应用了popuppicker组件，那么可以使用该组建的display-format进行转化，建立一个数据list只包含省份，在选择后进行display-format转化即可实现只选择省份。
