### ISSUE TITLE
npm update 之后 vux-loader 警告

### ISSUE THREAD

**Issue by wengcd** [airyland/vux#1579]
> VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
```
├── vux@2.4.0
└── vux-loader@1.0.67
```
为什么 npm update 之后出现这个，配置跟以前不是一样吗？eslint 也开启了
```
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui']
});
```

**Comment by airyland** [comment]
说明本来配置或者代码写法也是有点问题的。这个警告存在于包含了所有组件的 index.js 入口。

**Comment by wengcd** [comment]
```
const vuxLoader = require('vux-loader');
```

```
import {
  XSwitch,
  Popup,
  Group,
  Confirm,
  LoadMore
} from 'vux';
```

```
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui']
});
```

这样会有问题？

**Comment by airyland** [comment]
try vux-loader@^1.0.68

**Comment by wengcd** [comment]
@airyland 还是一样的问题

**Comment by airyland** [comment]
帖个 repo 看看。

**Comment by huaganshang** [comment]
https://github.com/huaganshang/vux-demo.git

我也遇到这个问题。
"vuex": "^2.3.1",
"vux-loader": "^1.0.68"


辛苦您指导一下，谢谢；

**Comment by wengcd** [comment]
当时问题找到了，是团队项目其他人一个文件代码（不规范？或是引用了某个组件）导致问题的。
当时不知道是这个原因，当时我Review了之后改良的代码结果就没警告了
