### ISSUE TITLE
「建议」样式中px可否改成使用rem？

### ISSUE THREAD

**Issue by acmeid** [airyland/vux#158]
### 建议
样式中px可否改成使用rem？

**Comment by airyland** [comment]
这影响巨大，weui的样式都要改。建议先到weui提意见。

**Comment by acmeid** [comment]
项目中是直接使vendors目录下 weui的min版样式吗？这样我自己试试改一下吧

**Comment by airyland** [comment]
@acmeid 是的。如果你引用了vux.css，你需要自己打个包。

**Comment by acmeid** [comment]
好的，谢谢！

**Comment by zwsf** [comment]
@acmeid 改写weui的px到rem的效果如何

**Comment by acmeid** [comment]
@zwsf 最终我几乎没有采用开源的vue 组件库，我是参考开源的组件库自己写了一套基于rem的，效果就是多了个自适应屏幕。
