### ISSUE TITLE
step下step-item如果是根据请求后端返回的数据，显示不正常。

### ISSUE THREAD

**Issue by lijun1314** [airyland/vux#1580]
在step内通过$children去迭代判断当前step-item的状态，如果step内的step-item是通过调用异步请求去生成的，编译step的时候，ste-item的数据还没有得到，所以最后child.currentStatus是undefined，导致step-item显示不正常

**Comment by wg5945** [comment]
请贴出你的实现代码

**Comment by lijun1314** [comment]
<template>
  <div>
    <step v-model="step" background-color='#fbf9fe'>
      <step-item v-for="item in stepObj" :key="item.id" :title="item.title"></step-item>
    </step>
  </div>
</template>

<script>
import httpConfig from '../../config/axiosConfig'
import lbmPlugin from '../../config/lbmConfig.js'
import sysConfig from '../../config/sysConfig.js'
import {AjaxPlugin, Step, StepItem} from 'vux'
export default {
  data () {
    return {
      // stepObj : [{},{}],
      stepObj : [],
      step: 0
    }
  },
  components: {
    Step,
    StepItem
  },
  beforeRouteEnter: (to, from, next) => {
    //获取业务配置 YG003340
    let tempObj = [
      {title:'资料录入',path:'generalBusiness'}
    ]
    let bus_data = {};
    bus_data.BUSI_CODE = to.params.busiCode;
    let data = lbmPlugin.$lbm.REQ_URL_DATA("YG003340",bus_data);
    AjaxPlugin.$http.post('/',data,httpConfig)
    .then((response) => {
      if(response.data.Code == "0") {
        //判断是否增加影像节点
        if(response.data.Data[0].IMG_NODE == "1") {
          tempObj.push({title:'影像采集',path:'imageAcquisition'});
          next(vm => {
            vm.stepObj = tempObj
          })
        }
      }
    })
    .catch(() => {
      next(vm => {
        vm.stepObj = tempObj
      })
    })
  },
}
</script>

**Comment by lijun1314** [comment]
@wg5945 

![image](https://user-images.githubusercontent.com/6966527/27377534-d352f0c0-56a7-11e7-9fa8-c68e18ed5f26.png)
![image](https://user-images.githubusercontent.com/6966527/27377552-db800706-56a7-11e7-8864-d77d9f2926e7.png)
如图所示：
StepItem子组件是根据请求的数据获取的，所以在渲染step时，step下的$children为空，导致计算currentStatus是undefined

**Comment by wg5945** [comment]
不好意思，忘了看你的回复

你这种情况应该是加个v-if判断吧，请求成功后再展示step

**Comment by lijun1314** [comment]
@wg5945
您好，我用v-if试了一下，没有成功，我设置了一个变量，在data里面初始为false，请求成功后设置为true，页面没有重新渲染，所以step的页面不会显示出来。

![image](https://user-images.githubusercontent.com/6966527/27480573-ff3edfa6-584a-11e7-8c51-6b0cd2c29313.png)
![image](https://user-images.githubusercontent.com/6966527/27480580-06979054-584b-11e7-98cc-9ee5c88ff89c.png)

**Comment by wg5945** [comment]
看上去应该是没有问题的，能否建一个repro，重现一下？

**Comment by lijun1314** [comment]
改一下vux里step的demo即可重现！用setTimeout函数模拟请求延时，就会出现问题，提交不了.vue文件，我把后缀改为txt了，代码如下：

[stepDemo.txt](https://github.com/airyland/vux/files/1104100/stepDemo.txt)

**Comment by wg5945** [comment]
看不到你的文件，我本地试了下，貌似没什么问题

```
<template>
  <div style="width: 95%;margin: 0 auto;">
    <br>
    <step v-model="step1" background-color='#fbf9fe' v-if="list">
      <step-item v-for="(item,index) in list" :key="index" :title="item.title" :description="item.description">
      </step-item>
    </step>
  </div>
</template>

<script>
  import { Step, StepItem } from 'vux'

  export default {
    components: {
      Step,
      StepItem
    },
    data () {
      return {
        step1: 1,
        list: null
      }
    },
    created () {
      setTimeout(() => {
        this.list = [{
          title: '步骤1',
          description: 'step1'
        }, {
          title: '步骤2',
          description: 'step2'
        }, {
          title: '步骤3',
          description: 'step3'
        }]
      }, 1000)
    }
  }
</script>

```

**Comment by lijun1314** [comment]
非常抱歉，浪费了您的这么长时间，拿你的代码跟我的对了一下，发现我的代码写的有问题，我 data里定义的list是list:[]  ,不是null，所以引起的问题。
