### ISSUE TITLE
demo上的CheckIcon和Sticky存在问题

### ISSUE THREAD

**Issue by flsho** [airyland/vux#1581]
感觉你这个VUX开发的很漂亮，组件也很完善，每个组件我都体验了一下，基本都很通用美观，然后发现一点小小的瑕疵，就是点击CheckIcon这个组件想要进去看发现路由页面没跳转，这个应该是空的吧？所有设备都没办法进入该链接路由。
还有就是Sticky这个组件在PC端和安卓端一切正常，但是在ios设备上没办法运行，具体表现是滚动的时候那两个tab不会固定在顶部，我用的设备是iphone6s。
希望VUE越来越好吧，哈哈，感觉作者好厉害

**Comment by airyland** [comment]
checkIcon 的问题是昨天引入的 bug，修复了。

**Comment by flsho** [comment]
感谢，另外这个Sticky这个组件我搜了下，貌似也没有合适的解决方法。不管他了。。
