### ISSUE TITLE
Swiper组件使用swiper-item，loop值为true时存在问题

### ISSUE THREAD

**Issue by gxt19940130** [airyland/vux#1582]
在swiper组件内使用swiper-item，swiper的loop属性值为true时候，组件切换时是从index = 1的swiper-item开始循环播放的，index = 0 的swiper-item会被放在最后一个，对应的dots顺序就会混乱
如下代码：
当第一个dots高亮显示时，文字展示的却是第二个item的"你无处可藏
![qq20170620-132341](https://user-images.githubusercontent.com/17588631/27317898-02f170fa-55bc-11e7-9444-2db7e31fa2cc.png)
"
`<swiper auto loop height="100px">
        <swiper-item class="black"><h2 class="title fadeInUp animated">它无孔不入</h2></swiper-item>
        <swiper-item class="black"><h2 class="title fadeInUp animated">你无处可藏</h2></swiper-item>
        <swiper-item class="black"><h2 class="title fadeInUp animated">不是它可恶</h2></swiper-item>
        <swiper-item class="black"><h2 class="title fadeInUp animated">而是它不懂你</h2></swiper-item>
        <swiper-item class="black"><h2 class="title fadeInUp animated">我们试图</h2></swiper-item>
        <swiper-item class="black"><h2 class="title fadeInUp animated">做些改变</h2></swiper-item>
      </swiper>`

**Comment by wg5945** [comment]
这个问题我之前应该处理过了 #1458

你升级到最新版本试试看呢

**Comment by gxt19940130** [comment]
好，我试试
