### ISSUE TITLE
DatetimePlugin使用问题

### ISSUE THREAD

**Issue by tongjh2** [airyland/vux#1583]
在main.js中注入DatetimePlugin
import {DatetimePlugin} from 'vux'
Vue.use(DatetimePlugin)
编译时会提示
* vux/undefined in ./src/main.js

To install it, you can run: npm install --save vux/undefined

页面中也无法使用DatetimePlugin
        this.$vux.datetime.show({
                cancelText:'取消',
                confirmText:'确定',
                format:'YYYY-MM-DD HH',
                value:'2017-05-20'
            })

**Comment by tongjh2** [comment]
之前2.2.1，我下载最新版的查看源码后发现plugins下多了datetime，原来是版本问题，升级2.4.0后可以使用DatetimePlugin了，感谢作者

**Comment by jslq** [comment]
你好，问下怎么注册$vux的
