### ISSUE TITLE
PopupPicker data的value中间存在空格控制台会报"SyntaxError: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by gt333** [airyland/vux#1584]
当PopupPicker组件 data属性值为这种格式时[{name:'例子',value:'例子 123'}]data-value在节点中显示 
`<div class="scroller-item" data-value="{"value":"例子" 123"}="">例子 </div>`这个样子；控制台会报"SyntaxError: Unexpected end of JSON input" 
造成这个问题的原因已经找到组件 picker 目录下面 scroller.js 50行生成的节点 `<div class="scroller-item" data-value={"value":"例子 123"}>例子 </div>`是这个样子用data-value少了单引号包裹。导致节点出问题了。我把50行源码改成这样`html += '<div class="' + self.options.itemClass + '" data-value=\'{\"value\":\"'+ row.value + '\"}\'>' + row.name + '</div>'`就好了。辛苦作者大佬改进下。。

**Comment by wg5945** [comment]
thx，采用json的方式是因为之前有人提出value值可能是数值型，会导致匹配不上
