### ISSUE TITLE
webpack3.0目前是不支持吧？

### ISSUE THREAD

**Issue by huangzhenxian** [airyland/vux#1588]
webpack3.0目前是不支持吧？我更新到webpack3.0，vux也是最新版本2.4.0，swiper组件无法使用

**Comment by wg5945** [comment]
据官方说是无需修改什么，具体还没有尝试

**Comment by huangzhenxian** [comment]
@wg5945 配置是不用修改，我的项目跑起来是正常的，但是vux组件有问题了

**Comment by airyland** [comment]
不要用“无法使用”“有问题”这类对于解决问题没有任何帮助的描述。
