### ISSUE TITLE
vux.css跟组件样式重复

### ISSUE THREAD

**Issue by ph2-cst** [airyland/vux#159]
### 0.0.111

有的组件内部没有写有样式
所以，在 页面入口js使用 `require('vux/vux.css')` 引入
但，有的组件内部写有样式，这样就有两份样式了

有方法解决吗？

**Comment by airyland** [comment]
是的，目前的引用方式是比较浪费的。这个在未来计划中。要真正实现理想的按需引入，就需要把weui不同组件css也拆分出来。

**Comment by ph2-cst** [comment]
So good job.
看了新的版本，二个月过去，变得这么多，作者好努力
