### ISSUE TITLE
sticky组件拓展

### ISSUE THREAD

**Issue by zss007** [airyland/vux#1591]
如果sticky组件上部元素可显示隐藏(即sticky组件的offsetTop属性动态改变)等，页面会异常，还是固定原先的距离进行吸附。
建议index.vue的mounted周期代码提取到一个方法中(比如bindSticky)，每次sticky组件的offsetTop属性动态改变时调用该方法，同时mounted也调用该方法。
如下：
```
   mounted () {
      this.bindSticky();
    }, 
    methods: {
      bindSticky(){
        this.$nextTick(() => {
          sticky(this.$el, {
            scrollBox: this.scrollBox,
            offset: this.offset,
            checkStickySupport: typeof this.checkStickySupport === 'undefined' ? true : this.checkStickySupport
          })
        })
      }
    },
```
sticky组件的offsetTop属性动态改变时父元素调用：
```
this.$nextTick(() => {
     this.$refs.sticky.bindSticky();
});
```

**Comment by wanghaijuan** [comment]
直接按照模板使用方式使用 
出现报错:sticky.js?1f43:62 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at eval (eval at <anonymous> (app.js:1485), <anonymous>:60:16)
该如何解决？
