### ISSUE TITLE
x-input设置type为number后在iphone6上无法输入小数点

### ISSUE THREAD

**Issue by chen-jiajian** [airyland/vux#1594]
x-input组件 设置type为number，在iphone6上只能输入数字，小数点无法输入（只有数字键盘），在安卓机上可以

**Comment by wg5945** [comment]
提供一下ios版本吧，我这边是正常的

你可以尝试下`<input type="number">`在你手机上的效果

**Comment by chen-jiajian** [comment]
之前测试不足，现在控件问题是设置type=number是只能输入数字和符号对吧，但是在安卓上只能输入数字和符号，在ios上可以输入中文呢和英文字符

**Comment by wg5945** [comment]
这和vux有什么关系呢？看下我上面的回复
