### ISSUE TITLE
The address component's expansibility is bad

### ISSUE THREAD

**Issue by frehaiku** [airyland/vux#1595]
[which component?](https://github.com/airyland/vux/blob/v2/src/components/x-address/index.vue)

### Why

The address component depends on `popup-picker`.The [`popup-picker`](https://github.com/airyland/vux/blob/v2/src/components/popup-picker/index.vue) consists of `ceil` components. When I don't need the ceil, I must manually modify the coding.It redundant with it.

Please rebuild the `address` component.

**Comment by airyland** [comment]
Actually most people need the cell. VUX cannot sove all people's problems.
you can just use `picker` and a custom popup div to make you own address component.

**Comment by frehaiku** [comment]
What are situations people need the cell? Can you say your opinion?

In some forms component, I have same question. 
Why not extract common `x-cell` section? For instance: [In this file](https://github.com/airyland/vux/blob/v2/src/components/x-input/index.vue), Why not write below:

```javascript
// x-input/index.vue
<x-cell>
  <div slot="right">
     <input />
  </div>
</x-cell>
```

**Comment by airyland** [comment]
Form components provide a way to quickly create a form including input, textarea, address, so cell is needed for display. Also no other people say that they don't need cell.

The reason is No Time.
Of course You can PR for what you say.
