### ISSUE TITLE
popup-picker控件在iphone6上，滑动背景跟着动

### ISSUE THREAD

**Issue by chen-jiajian** [airyland/vux#1596]
popup-picker控件在iphone6上，滑动控件时，背面-也就是主页会动，在安卓上不会（建议多试几次就能重现bug）

**Comment by wg5945** [comment]
貌似是在popup-picker-header上滑动可以使背景滚动，我来加个touchmove.prevent吧

**Comment by chen-jiajian** [comment]
请问我只要更新就可以了吗

**Comment by wg5945** [comment]
等新版本发布吧

你可以先试试首页的demo是不是没有问题了

**Comment by chen-jiajian** [comment]
我试了一下demo没有问题了，都说vux的作者很勤奋，果然哈哈，那想问下新版本大概什么时候发布呢？
