### ISSUE TITLE
Popup组件中使用range组件，初始化popup关闭，按钮出发显示后，此情况下range组件拖动异常。

### ISSUE THREAD

**Issue by jiangchengshi** [airyland/vux#1599]
在popup组件中使用range组件，并且popup初始化v-model绑定值为false，按钮触发绑定值为true时，拖动range组件时，只能拖到最大值。  若popup初始化v-model绑定值为true，则拖动正常。

附代码: https://jsfiddle.net/k3ovf03k/

**Comment by wg5945** [comment]
的确会出现这样的情况，range组件增加个v-if="show.progress"吧

**Comment by jiangchengshi** [comment]
嗯。 目前就是这么实现， 希望以后修正啊，感谢。

**Comment by Leungkingman** [comment]
能不能尽快修复这个bug，同样面临这个问题，用v-if都不能解决

**Comment by wg5945** [comment]
这个我感觉也算不上是个bug，应该算是多个组件混合使用的一些注意事项，暂时先这么处理吧
