### ISSUE TITLE
在安卓上x-input在底部的点击会被弹出键盘挡住

### ISSUE THREAD

**Issue by chen-jiajian** [airyland/vux#1600]
在安卓上点击位于底部的x-input，弹出的键盘会挡住控件，（在ios上则是x-input跳动到键盘上方）

**Comment by airyland** [comment]
这个是系统浏览器的行为了，和组件应该没问题。

**Comment by chen-jiajian** [comment]
但是我试过原生的input在安卓上是默认跳到键盘上方，我建议你可以试试

**Comment by airyland** [comment]
挡住控件的页面布局是 100% 的布局吗？

**Comment by chen-jiajian** [comment]
是的

**Comment by mkgsac** [comment]
页面高度设置成100%，滚动设置为auto试试

**Comment by graysheeep** [comment]
这个问题暂时无解 我们目前有个不算完美的方案 在input的focus事件中给页面增加300的padding-bottom，blur事件中删除这个属性
