### ISSUE TITLE
XInput组件的max在iOS上有兼容性问题

### ISSUE THREAD

**Issue by hashdrinker** [airyland/vux#1601]
```
<x-input :max="18" type="text"></x-input>
```
上面的代码在 Android 是没有任何问题的，字符超出 18 就无法输入。在 iOS 上，输入 18 个字符后不能继续输入，这是正常的，但是此时把光标移到前面，还是可以继续输入
![wechatimg232](https://user-images.githubusercontent.com/5600837/27427448-930b2710-5771-11e7-9cb7-10fa08518440.jpeg)

**Comment by airyland** [comment]
并不能在最新 iOS 系统上重现，并且 max 在实现上只是简单地赋值给了 maxlength，所以这看起来是浏览器的问题。

**Comment by hashdrinker** [comment]
我在公司同事多个 iOS 上测试了，这是 input 标签的 maxlength 属性在 iOS 浏览器中的坑，比如下面的一行代码，输入5个字符，不能再输入，此时把光标从最后移到前面，注意**不能是最前面、不能是最前面、不能是最前面**，比如可以把光标移到第一个字符后面，你会发现，还可以再输入4个字符，maxleng指的是光标前有maxleng个字符
```
<input type="text" maxlength="5">
```
