### ISSUE TITLE
当Datetime组件没有给value，弹出日期选择框时，能否让日期停在指定的日期？

### ISSUE THREAD

**Issue by hashdrinker** [airyland/vux#1604]
比如下图，虽然没有`value`，但是打开日期选择器时，并不是停在今天的日期，而是我们指定的日期
![wechatimg232](https://user-images.githubusercontent.com/5600837/27443019-75b63280-57a4-11e7-9bc7-a36326600cc9.jpeg)

可以这样实现
```
// 添加个属性
defaultValue: {
  type: String,
  default: ''
}
...
pickerOptions () {
  const options = {
    // 如果没有value，就使用我们指定的默认值
    value: this.currentValue || this.defaultValue
```

**Comment by airyland** [comment]
现在是有这个 defaultSelectedValue 属性的

https://github.com/airyland/vux/blob/v2/src/components/datetime/index.vue#L108

**Comment by hashdrinker** [comment]
多谢，我最近可能有点瞎
