### ISSUE TITLE
建议 XSwitch 的 onchange 事件改为人工干预行为

### ISSUE THREAD

**Issue by wengcd** [airyland/vux#1606]
## 场景问题
点击 `x-switch`，触发状态更改，执行某一类验证，将此状态更改失效。
一般操作就是 `this.status = !changedValue`
但是这样会导致又触发验证，验证又通不过，形成死循环。

## 建议
只监听人工点击/滑动触发的状态更改
状态本身的更改可以由`watcher`来实现

**Comment by wg5945** [comment]
有点绕，能否提供个repro

**Comment by airyland** [comment]
没有这个场景，大致理解一下，就是：
点击时仅 emit 一个 on-click 事件，用户自行判断是否要更改状态来改变 value？

**Comment by wengcd** [comment]
@wg5945 
用户点击更改按钮 => 触发更改事件（请求 ajax update api）=> 结果返回没有权限修改（需要更改value）=> 手动更改value => 又回触发更改事件
陷入了死循环

提供的建议是，事件`onchange` 改为`on-click`

**Comment by wg5945** [comment]
我觉得这是你业务逻辑的问题吧，正常流程应该是

```
先进行判断权限
  │ 
  │ 
  └───有权限：触发下一步操作
  │ 
  │ 
  └───无权限：禁止用户操作或者弹出提示等
```

而不是先进行下一步操作，然后再反过来告诉他，你不能进行下一步

**Comment by airyland** [comment]
你这里的循环更像是业务相关的了，假设服务端已经返回一次无权限了，就可以忽略后面请求了。。

**Comment by wengcd** [comment]
但撇开业务逻辑。。也有请求失败的时候啊。。比如500错误，或者断网，告诉用户切换失败，同样也要改回来

**Comment by airyland** [comment]
目前的实现并不能阻止点击时不修改状态和值。倒是可以提供一个 `prevent-default` 属性，在操作按钮上面覆盖一层，使用者在 on-click 事件里自行决定是否要修改值。

**Comment by wengcd** [comment]
> 你这里的循环更像是业务相关的了，假设服务端已经返回一次无权限了，就可以忽略后面请求了。。

我目前是这么做的。。。设了个flag，无权限就设成false，忽略请求了再设成true，下次再切换才会请求

**Comment by greedying** [comment]
这个逻辑，还是在组件外实现比较好。 你可以在组件外定义两个变量。一个绑定x-switch，另外一个根据情况决定是不是绑定switch。

**Comment by ynioba** [comment]
怎么说，我们做企业系统的时候，很多2G的用户，他在点击switch的时候，switch已经是选中了，但是，菊花不停的走啊走，忽然提示操作失败了，这个时候，只能让菊花false回来。

还有一种情况是全选的情况。
