### ISSUE TITLE
Vux中组件依赖问题

### ISSUE THREAD

**Issue by bluemsn** [airyland/vux#161]
@airyland  你好，最近一断时间也一直在开发基于Vue的组件体系，借鉴了很多Vux【主要不(bu)想(tai)依(xi)赖(huan)WeUI】，开发过程中遇到了一个问题，你也在Vue的issues中回答过我了。 可能当时我没有表述太清楚。

问题是这样的：比如 Dialog组件，实现完成一个最基础的Dialog架子，然后开发Alert组件，组件依赖中使用了Dialog, 即包装了一次，但在demo中，总是报 Dialog 组件找不到？ 一直找不到原因。我把demo上传到了 `https://github.com/bluemsn/vc` 打开后，找到alert组件的 demo,能看到错误

**Comment by airyland** [comment]
一定是你代码姿势错误。有空再看一下。

**Comment by bluemsn** [comment]
恩。 好的， 多谢~  Coffee 送上  ^_^

**Comment by airyland** [comment]
你里面槽点太多啊，一个组件里不要引用vue啊，如果你单个打包的话，会带上vue源码。

组件源代码不要从components里引用啊，单个打包出来等于打包了所有组件了。你components里export了Alert,Dialog, 而Alert里又引用了components里的Dialog这样循环引用必定是有问题的。

````
// import { Dialog, Button } from 'components'
import Dialog from '../dialog/dialog'
import Button from '../button/'
````

然后button不要直接用button,跟原生button标签冲突了，后面会出现问题的。建议和vux一样加前缀用x-button。

**Comment by bluemsn** [comment]
@airyland  恩恩。 多谢。 的确是由于组件的循环引用引起来的。在 dialog 中引用其它组件时，使用相对路径即可解决，再次感谢~
另外：我看了你在组件之间的实现都是不互相依赖的，相对比较独立。但是实际上有些组件之间是会有依赖关系的。  比如 `dialog` 与 `alert` `confirm` 两者实现的在骨架上是一致的， dialog更加通用， alert做了一些限制，但 `alert` `confirm`的实现可以由 `dialog` 提供的骨架来实现呢？ 多了一些重用？这样不好吗？是否会有新的问题呢

 button的问题后续也弄一个前缀吧<vue>

**Comment by airyland** [comment]
@bluemsn 理想状态是希望组件都能重用的，只是一开始为了快实现就没有追求重用。实际上vux里popup和flexbox也算是一些组件的依赖。
