### ISSUE TITLE
关于在 X-dialog 组件中，dialog-transition 弹窗动画的使用，求解

### ISSUE THREAD

**Issue by nongzhenli** [airyland/vux#1610]
`dialog-transition	 String	    vux-dialog		弹窗动画`

开发中我使用x-dialog组件做了一个满屏的弹窗效果。但是，原vux-dialog的弹窗动画不能满足需求
SO，想做一些按需的改动：

> 在使用dialog-transition 值为 通过@keyframes 定义的动画名称，但是为什么达不到效果

看了天组件的dmeo源码，发现并没有对此属性的案例。。。

> code

```
<x-dialog class="set-dialog" v-model="isEmail" dialog-transition="dialogAnimation">

@keyframes dialogAnimation {
  from {
    width: 0; height: 0;
    transform: scale(0, 0);
    opacity: 0;
    transition: all 1s;    
  }
  top {
    width: 100%; height: 100%;
    transform: scale(1, 1);
    opacity: 1;
    transition: all 1s;
  }
}
```

**Comment by airyland** [comment]
dialog-transition 定义的是 vue 的 transition 需要的 name，所以你要按照 vue 的要求来：
https://cn.vuejs.org/v2/guide/transitions.html#CSS-过渡

**Comment by nongzhenli** [comment]
@airyland 原来如此，感激不尽谢谢！
