### ISSUE TITLE
install后构建出错

### ISSUE THREAD

**Issue by jcto** [airyland/vux#1611]
ERROR in static/js/8.d7bde46735ffc8e99efd.js from UglifyJs
SyntaxError: Unexpected token: name (Actionsheet) [./~/vux/index.js:5,0]

平时一直使用都ok，新install后再build就出错了
版本：
 "vux": "^2.4.0",
 "vux-loader": "^1.0.68",

**Comment by jcto** [comment]
{
        test: /\.vue$/,
         loader: 'vue'
      }
改为
  {
        test: /\.vue$/,
        loader: 'vux!vue'
      },
就ok了
奇怪了，以前都没问题的，重新install下模块依赖就嘎嘣了

**Comment by jcto** [comment]
使用vux-loader版本"1.0.36" 就可以了，请官方review下什么问题

**Comment by airyland** [comment]
信息量太少，看不出什么问题。

**Comment by airyland** [comment]
@jcto 没有什么严重保密的东西的话，去除大部分业务代码，然后打包发我邮箱看看。
