### ISSUE TITLE
x-dialog和x-switch组合使用时的问题

### ISSUE THREAD

**Issue by yuch321** [airyland/vux#1612]
在x-dialog中有一些信息需要确认或者选择，其中使用到了x-switch组件。x-switch中:inline-desc显示的位置应该是在左边，但是在使用时却出现在了中间，导致页面的样式有问题。
代码如下:
`<x-dialog v-model="update" >
<group>
            <x-switch v-model="switchVal"  title="方向" :inline-desc="switchVal == true ? '买'+'':'卖'+''" ></x-switch>
        </group>
</x-dialog>`
在单独使用x-switch时，没有出现显示错误的问题，所以估计是不是在和x-dialog配合使用时有什么地方写错了。有大神知道的麻烦解决下，万分感谢！

**Comment by wg5945** [comment]
样式问题，覆盖下原有的吧
```
    .weui-cell__bd {
      text-align: left;
    }
```

**Comment by yuch321** [comment]
@wg5945 
刚想着是不是这个问题，正在找vux的样式，感谢大神的回复！
