### ISSUE TITLE
怎么将vux注册到vue中？

### ISSUE THREAD

**Issue by jslq** [airyland/vux#1613]
项目用的不是vux构建的，用的途中需要使用vux的datetime插件，所以引用了vux，vux-loader配置也没问题，如何在项目中使用$vux

**Comment by graysheeep** [comment]
什么场景需要用$vux? 如果是datetime插件直接import不就行了

**Comment by airyland** [comment]
用 Vue.use 来使用插件，相关插件就会被注册到 this.$vux 里。
