### ISSUE TITLE
popup滑动到底时背景会滑动

### ISSUE THREAD

**Issue by klter** [airyland/vux#1615]
popup滑动到底时背景会滑动，官网上demo没有问题，是否未更新？

重现：新建项目使用demo中的Popup.vue即可。

**Comment by wg5945** [comment]
如果官网的demo没有问题的话，请更新vux到最新版本

**Comment by klter** [comment]
@wg5945  已更新至2.4.1

**Comment by wg5945** [comment]
最新的还不行么？建个repro看看呗

**Comment by wg5945** [comment]
暂且先关闭了，如果还有问题再开吧
