### ISSUE TITLE
Tabbar组件不会置底

### ISSUE THREAD

**Issue by acwind** [airyland/vux#1616]
Tabbar组件在页面打开的时候会置底，但是随着页面的上下滚动，它就不置底了，指定了了slot为bottom

demo 页面 http://m.acwind.net

**Comment by airyland** [comment]
自行设置 position fixed 吧，默认是 absolute 定位，要用在 100% 布局上，明显你的网页并不是。

**Comment by acwind** [comment]
搞定了，谢谢
