### ISSUE TITLE
alert 组件 如何能添加一个取消按钮呢？demo只可以设置一个按钮？

### ISSUE THREAD

**Issue by NickBang** [airyland/vux#1617]
RT vux 感觉很强大，可是 aleat 组件为什么只有一个按钮呢？如何添加一个按钮？我在api中也没找到对应的方法。

**Comment by airyland** [comment]
alert 的作用是提示，那么就只有一个确定按钮了。confirm 才有确定，取消。

**Comment by NickBang** [comment]
sorry 刚看到。谢谢作者！
