### ISSUE TITLE
Previewer查看大图时，图片列表有两张或者以上   但是imgList只显示两张小图，查看第三张大图时没问题，但是变为小图就报错“Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined”

### ISSUE THREAD

**Issue by zhuangbb** [airyland/vux#1618]
@fundon @airyland @blue5tar @gzlboy @naifen00

**Comment by airyland** [comment]
Code, please.

**Comment by zhuangbb** [comment]
<previewer :list="previewImg[item.id]" ref="previewer" :options="options" v-for="(item, index) in data" :key="item.id"></previewer>
    <div>
      <scroller height="-98"  @on-pullup-loading="pullupHandle" @on-pulldown-loading="pulldownHandle" :value="scrollStatus" lock-x scrollbar-y  ref="scroller" use-pulldown use-pullup :pulldown-config="pulldownConfig" :pullup-config="pullupConfig">
        <group>
          <ul class="houseItem" ref="itemWrap" v-if="data&&data.length">
            <li class="itemList itemListHook" ref="item" v-for="(item, index) in data">
              <p class="desc">
                <span>{{item.title}}</span>
                <span class="type" v-text="showStatus(item.type)"></span>
                <span class="name"><span v-text="showUserType(item.userType)"></span>:{{item.realName}}</span>
              </p>
              <p class="time">
                <span class="date">{{item.createTime | formatDate}}</span>
                <span v-if="item.kilometre">{{item.kilometre}}m</span>
              </p>
              <p class="title">{{item.content}}</p>
              <div class="imgList">
                <img v-if="item.images.length>0" class="previewer-img img" :src="$store.state.fileUrl + item.images[0].imageUrl + '_150x150.jpg'" @click="show(index,0)">
                <img v-if="item.images.length>1" class="previewer-img img" :src="$store.state.fileUrl + item.images[1].imageUrl + '_150x150.jpg'" @click="show(index,1)">
              </div>
            </li>
          </ul>
          <div v-else>
            <nullData></nullData>
          </div>
        </group>
      </scroller>
    </div>
