### ISSUE TITLE
x-dialog组件在火狐下不显示

### ISSUE THREAD

**Issue by hashdrinker** [airyland/vux#1619]
简略代码如下，`show`为`true`是，在火狐下不显示
```
<x-dialog v-model="show" hide-on-blur>
</x-dialog>
```
并且控制台出错如下
![2017-06-27 10 42 10](https://user-images.githubusercontent.com/5600837/27593598-20244e76-5b8a-11e7-9d6f-96beafce47c0.png)

其他浏览器都正常显示

**Comment by graysheeep** [comment]
ff不在兼容考虑范围之内
