### ISSUE TITLE
datetime 插件形式调用报错 property 'datetime' of undefined

### ISSUE THREAD

**Issue by maplehsu** [airyland/vux#1621]
版本："vux": "^2.2.1"
 在使用插件形式调用的时候 点击显示报错
 Cannot read property 'datetime' of undefined

  showPlugin () {
      this.$vux.datetime.show({
        cancelText: '取消',
        confirmText: '确定',
        format: 'YYYY-MM-DD HH',
        value: '2017-05-20 18',
        onConfirm (val) {
          console.log('plugin confirm', val)
        },
        onShow () {
          console.log('plugin show')
        },
        onHide () {
          console.log('plugin hide')
        }
      })
      setTimeout(() => {
        this.$vux.datetime.hide()
      }, 2000)
    }

**Comment by airyland** [comment]
确定你在 main.js 里引入了？

**Comment by graysheeep** [comment]
在main.js中 import { DatetimePlugin } from 'vux'
