### ISSUE TITLE
升级到最近的vue-loader后还提示   VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因

### ISSUE THREAD

**Issue by Jon-fantic** [airyland/vux#1622]
之前还是好的，换了个电脑，重新装了下，就出现   VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)，然后升级vux到2.4.1，loader从1.0.57升级到了1.0.69，还是有这个问题。还有报错[Vue warn]: The computed property "errors" is already defined in data.

**Comment by WalterZou** [comment]
同样出现这个问题，还有$t报错

**Comment by WalterZou** [comment]
我这边是由于 vue-loader  升级到 1.13.0 带来的 breaking changes 导致的

**Comment by airyland** [comment]
vue warn 不是 vux 的提示了，我看一下是不是重复定义了。
vux-loader 升级到 vux-loader@^1.0.70 长期试试。
vue-loader 最近的升级这几天适配一下。

**Comment by huaganshang** [comment]
https://github.com/huaganshang/vux-demo.git
我也遇到这个问题。 "vuex": "^2.3.1", "vux-loader": "^1.0.68"
辛苦您指导一下，谢谢；

**Comment by airyland** [comment]
@huaganshang 你没理解合并配置是什么意思，是合并 config 而不是要合并一个 compiler。。而且为什么要在这里 export。。直接在 base.js 里来使用 vux-loader merge吧。

``` js
var compiler = webpack(config);

const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(compiler, {
```
另外，用着 webpack2 还用 webpack1 的写法。建议还是用 airyland/vux2 来初始化项目吧。

**Comment by huaganshang** [comment]
@airyland 好的，谢谢；

**Comment by hsir05** [comment]
@huaganshang 你是怎么解决的啊
