### ISSUE TITLE
构建的模块超大问题

### ISSUE THREAD

**Issue by jcto** [airyland/vux#1623]
vux-loader版本1.0.69生成的模块体积很大，1M多，
vux-loader版本1.0.66生成的模块体积才200K左右

webpack2的环境构建，
烦请作者review下，看看什么问题。
构建是命令行信息：
1.0.69版本：
                      static/img/myintegral.b3dee5e.png    22.4 kB          [emitted]
                          static/img/pic_QR.fc8ab95.jpg    62.3 kB          [emitted]
                          static/img/userbg.99e17ef.png     235 kB          [emitted]
                    static/js/0.65374d5bfc2ed5dee5cf.js     116 kB       0  [emitted]
                    static/js/1.de6f6e9d1c6444ad2789.js     1.7 MB       1  [emitted]  [big]
                    static/js/2.b037b41d22df85f36062.js    1.69 MB       2  [emitted]  [big]

1.0.66版本：
        static/img/pic_QR.fc8ab95.jpg    62.3 kB          [emitted]
                          static/img/userbg.99e17ef.png     235 kB          [emitted]
                    static/js/0.8f1ccc37ba73d49fb155.js     116 kB       0  [emitted]
                    static/js/1.e3aa474c61b5279fffd4.js     241 kB       1  [emitted]
                    static/js/2.c6d9c24005df575b2684.js     151 kB       2  [emitted]
                    static/js/3.af6b23829d8bd96180d9.js    36.8 kB       3  [emitted]

**Comment by airyland** [comment]
可能解析时有边缘条件没正确解析，你给个从 vux 引入模块的原始代码我看看。

**Comment by greedying** [comment]
qq群里也有人反馈这个问题，看来真是有没查出的bug

**Comment by airyland** [comment]
来来来，试试 vux-loader@^1.0.70。

**Comment by airyland** [comment]
@greedying 麻烦你让有问题的同学试试升级  vux-loader。
