### ISSUE TITLE
vux 能否重写所有样式

### ISSUE THREAD

**Issue by youngwind** [airyland/vux#1627]
hi，airyland：
     我是梁少峰，最近在看你维护的 vux ，觉得非常不错，想尝试在团队内推广使用。但是有一个问题：**我该如何方便地重写所有的样式呢？**
虽然你在文档中提到可以通过重写 variable 这种方法来定制主题，但是，我希望的是能够高度定制样式，也就是重写所有的样式，而不是改改主题。
**有什么办法能达到我这个目标吗？**
我的想法是：如果 vux 能够 build 出单独的 CSS 和 单独的 JS，那么，我只需要引入 vux 的 JS 文件
和我自己编写的 CSS 文件，便可以做到完全覆盖原有样式。这样做的另一个好处是，当你们在迭代维护 vux 的时候，我也能通过及时更新代码，重新构建 JS 文件的方式来解决最新的 Bug。**然而，我并未发现 vux 有 build 出单独的 JS 和单独的 CSS。** 当然，你提供了 umd 的分离方式，但是这对于我使用 webpack 来说并不方便。
   如果能做到下面这样就太好了！
```js
import vux from 'vux';    // vux 本身不包含 CSS 代码
import 'vux/styles/index.css';   // 单独引入 CSS
```
这样如果我想高度自定义样式的话，那么我只需要不引入 vux 的样式，引入我自己写的样式就好了。
不知道我这个想法是否成熟？如果有想的不对的地方，还望不吝赐教。

PS：本来是给你发邮件的，但是你没有回，我就来这儿发 issue 了，不便之处，还望见谅。

**Comment by airyland** [comment]
样式是主要是 WeUI 的，并且分拆到了各种组件里。其实要高度自定义这个重写成本还是挺高的。而且如果组件 class 名在维护过期中变更了，你还得相应地做修改。因为 UI 现在都是比较通用，哪些需要自定义可以提个 pr 加个变量更好维护。

> 并未发现 vux 有 build 出单独的 JS 和单独的 CSS

不是很明白这句话，vux 的 umd 打包是会打包出单独 js 和 css 的(不过打包脚本久未维护可能有 bug)。

如果你要的不是 umd 方式而是希望 import 进来的组件不带样式，理论上这也是很容易做到的，vux-loader 可以实现引用时把源码里的样式全部干掉。

**Comment by youngwind** [comment]
1. 你说的类名更改问题，这个我确实之前没考虑到。
2. umd 的问题可以忽略，因为我不打算用这种方式。
3. 对，我想要的，就是 import 组件的时候不带样式，请问该如何操作呢？

**Comment by airyland** [comment]
可以这样处理，在 vux-loader 里添加 style-parser 插件，检查是否是 vux 的组件源码，是的话，把样式清空。没有具体测试过，理论上是可行的。

``` js

{
  name: 'style-parser',
  fn: function (source) {
    if (this.resourcePath.replace(/\\/g, '/').indexOf('/vux/src/components') > -1) {
      source = ''
    }
    return source
  }
}
```

**Comment by youngwind** [comment]
你说的原理我大概明白了，但是我翻看 vux-loader 的源码，并不知道该把你这段代码加到哪个文件中，能说得再详细一些吗？

**Comment by F-loat** [comment]
@youngwind 加在vuxLoader.merge配置参数的plugins数组中，我是放在webpack.base.conf.js这个文件最后的

**Comment by airyland** [comment]
同 @F-loat 上面说的，直接写在 vux-loader 的插件配置里。
