### ISSUE TITLE
buttonTab active圆角问题

### ISSUE THREAD

**Issue by w-mf** [airyland/vux#1628]
![image](https://user-images.githubusercontent.com/17610023/27718993-26506d26-5d82-11e7-8e90-7651358b1e79.png)，
选中项的圆角和边框的圆角度数不一致，多了1倍。查看样式发现是边框缩小了一半，导致圆角也缩小了一半

**Comment by graysheeep** [comment]
未发现此问题 什么手机？什么环境？

**Comment by w-mf** [comment]
安卓，小米默认浏览器，微信，pc chrome等，所有浏览器都有这个状况

**Comment by graysheeep** [comment]
我是小米5 微信上看上去一切正常。

**Comment by w-mf** [comment]
https://w-mf.github.io/vuxDome/index.html#/coupon    
这是配置的值
![image](https://user-images.githubusercontent.com/17610023/27725574-8d98e5ae-5da9-11e7-8d51-4e86f6371c34.png)

**Comment by wg5945** [comment]
border-radius一般不用rem这类，建议使用具体值
