### ISSUE TITLE
希望新增 button Disabled 颜色less变量 

### ISSUE THREAD

**Issue by w-mf** [airyland/vux#1630]
在最新版本中查看vux代码发现 Primary、warn这两个样式的按钮没定义less变量，希望能和Default一样可以自定义
![image](https://user-images.githubusercontent.com/17610023/27724313-f9922974-5da3-11e7-9907-a11b373f8e3f.png)

**Comment by wg5945** [comment]
这个是支持的吧

![image](https://ooo.0o0.ooo/2017/07/03/5959eb7d08425.png)

**Comment by wg5945** [comment]
哦，看错了，Disabled，稍等加一下
