### ISSUE TITLE
tabbar的问题？为何会出现横向滚动条？

### ISSUE THREAD

**Issue by amourz** [airyland/vux#1631]
见截图，用的文档里的代码。发现出现了横向滚动条，还有文字label那里也出现了下划线。
谢谢
![2345 20170630153852](https://user-images.githubusercontent.com/12887480/27725932-105052ba-5dab-11e7-8fde-11e809061ada.png)

**Comment by airyland** [comment]
既然 demo 没问题而你使用有问题先检查样式冲突，检查有没有 reset 吧。

**Comment by amourz** [comment]
谢谢大大，引入了reset后css已经正常了
