### ISSUE TITLE
使用模板初始化项目失败

### ISSUE THREAD

**Issue by QiDa-007** [airyland/vux#1634]
你好，
      我按照文档中快速入门，进行到第二步时，不能进行任何操作，麻烦请问下这是什么原因
![image](https://user-images.githubusercontent.com/11505520/27745236-25a0e3ec-5df5-11e7-8eda-820e722b5570.png)

**Comment by airyland** [comment]
这个无法重现，并且是属于 Vue 官方工具  vue-cli 的问题，麻烦到相应  repo 提 issue: https://github.com/vuejs/vue-cli

**Comment by QiDa-007** [comment]
已经解决了，是node版本太高了，降到8.0就可以了
