### ISSUE TITLE
请问，打包之后app.js里面有6万行的地理数据是怎么来的？

### ISSUE THREAD

**Issue by ynioba** [airyland/vux#1638]
我的项目只用到了下述几个组件，但是打包之后，发现app.js里面有个近6万行的地理数据。
import {Group,Cell,Divider,Tabbar, TabbarItem, XInput,XTextarea,Box,Datetime, Selector} from 'vux'

请问，是因为我是from ‘vux'的情况，所以，会把所有的组件都打包了吗？？？

第二个问题是，按照首页介绍，异步加载是否会解决这个问题？？但是，首页的异步加载是加载自己写的组件的，vux的按需异步加载是如何配置？？

**Comment by airyland** [comment]
一般配置了 vux-loader 后都会变成按需加载。如果你是已经配置了 vux-loader 还出现这种情况，可以发个包到我邮箱我检查一下具体是什么原因单模块解析失败。

**Comment by ynioba** [comment]
我使用的是，vux的全家桶工具生成的项目，非常的棒，之前用的是mint，花了2个通宵，全部转到了vux。唯一的就是发现打包出来的app.js有1.4M，压缩了之后还有900K。我怎么把整个项目发送给您呢？

**Comment by airyland** [comment]
@ynioba <del>升级到 vux-loader@^1.0.70 应该可以解决，有问题再反馈。</del>

看错了，你应该已经发过给我了。

**Comment by xiaolongyuan** [comment]
+1 这个问题解决了么？ @ynioba
