### ISSUE TITLE
search组件里的result结果列表如何修改样式？

### ISSUE THREAD

**Issue by wangchaolonglls** [airyland/vux#1640]
您好，项目中用到search组件，并且想把不同的结果返回值在result结果列表中用不到的颜色样式区分下。
该需求是否可以实现，劳请大神指教~
如下图效果
![image](https://user-images.githubusercontent.com/5821661/27782954-f407f528-6006-11e7-8af6-2914b7a26c8c.png)

**Comment by graysheeep** [comment]
暂时无法实现 如有需要请自行修改search组件 源码也只有一个文件 自己拉出来改循环列表的dom结构就行
