### ISSUE TITLE
AjaxPlugin组件，无法通过 Vue.http.create 进行创建

### ISSUE THREAD

**Issue by helei112g** [airyland/vux#1641]
代码
```
Vue.use(AjaxPlugin)

const http = Vue.http.create({
  baseURL: process.env.API_URL,
  timeout: 1000,
  headers: {'D-REQUEST-FROM': 'wap'}
})
```
在组件内可正常使用 `this.$http` ，但是这里的初始化配置的 baseURL 没有生效。请求的时候，还是基于当前的url进行网络请求

**Comment by graysheeep** [comment]
你console.log(process.env.API_URL)能输出正确的值么

**Comment by helei112g** [comment]
可以输出正确的值。但是只能在 main.js 中直接通过 http访问有效。

在其它组件通过 this.$http 访问时，配置没有效果

**Comment by graysheeep** [comment]
Vue.http并不在原型链上 尝试Vue.prototype.$http.create({})试下

**Comment by graysheeep** [comment]
或者直接
`
Vue.use({
  install (_Vue) {
    _Vue.prototype.$http = axios.create({xxx})
  }
})
`

**Comment by airyland** [comment]
看起来这里你仅仅是在 main.js 里新建了一个实例并不会影响到组件里 this.$http 的默认配置。你可以自己写一个方法 Vue.prototype.$$http，不使用默认的 this.$http，甚至直接调用  axios 就行了。
或者使用 defaults 来设置默认参数。

没有具体测试过，参考一下。

**Comment by tangyuanhaha** [comment]
我是个刚学vue的，使用import { AjaxPlugin } from 'vux';就报
 VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
我的vux-loader版本是最新版了，我用import flexbox from 'vux/src/components/flexbox/flexbox';就能正常使用，请问ajax是怎么引用进来呀，我单独使用axios是可以的，代码为：
import Vue from 'vue';
import flexbox from 'vux/src/components/flexbox/flexbox';
import { AjaxPlugin } from 'vux';
import App from './App';
import router from './router';
Vue.use(flexbox);
console.log(flexbox);
Vue.use(AjaxPlugin);
