### ISSUE TITLE
无法使用 confirm组件  show-input 参数无效，input 框没出来（^2.3.1）

### ISSUE THREAD

**Issue by proc07** [airyland/vux#1642]
confirm组件 无法使用 show-input 参数无效（^2.3.1）

![image](https://user-images.githubusercontent.com/16809535/27794860-762a49fa-6036-11e7-8300-eca24abaec6e.png)
![image](https://user-images.githubusercontent.com/16809535/27794872-7ed0516c-6036-11e7-81ae-21cf12dff230.png)

**Comment by proc07** [comment]
![image](https://user-images.githubusercontent.com/16809535/27795188-b80e3bd2-6037-11e7-8188-daad8e5b2706.png)

案列中的确是这样的啊？ 源码中我看了也没什么问题的

**Comment by airyland** [comment]
Sorry，支持该特性的版本并未发布(大概这两天发布)，文档已更新版本说明。

**Comment by proc07** [comment]
那我可以直接将 当前confirm 组件的代码复制到我的本地文件中吗？有没有需要注意什么文件修改过的。我现在就需要这个组件编写代码的
