### ISSUE TITLE
在测试环境没问题  在正式环境下   是在微信页面打开的  第一次修改时间change事件没有调用

### ISSUE THREAD

**Issue by zhuangbb** [airyland/vux#1643]
change (value) {
      alert(value)
      console.log(value)
      let timestamp = (Date.parse(new Date(value)))
      this.changeServerTime(timestamp)
      alert(timestamp)
    },
第一次修改没有东西弹出来  第二次及以后才弹出

**Comment by airyland** [comment]
1.虽然我知道你在说 datetime，但是提问题时请描述清楚，方便管理也方便其他人可以搜索出来
2.既然测试环境没问题，那就不是组件的问题了。不知道具体问题，但是提醒一下 iOS 下中划线分隔的时间字符用 new Date 会有问题。
3.代码请格式化
