### ISSUE TITLE
关于datetime在iphone6p上面的bug

### ISSUE THREAD

**Issue by iyangce** [airyland/vux#1644]
移动端引入datetime组件，在iphone6p横屏出现样式显示不全的bug。

**Comment by graysheeep** [comment]
能给个图吗 我模拟器里一切正常

**Comment by iyangce** [comment]
![qq 20170704101448](https://user-images.githubusercontent.com/19756079/27812460-b38620ce-60a1-11e7-92c8-e3faf4577ac7.png)

**Comment by airyland** [comment]
是不是你修改样式导致的，至少 datetime 是没有透明度的。

**Comment by iyangce** [comment]
查看官网demo也会出现这种问题

**Comment by airyland** [comment]
用 6s 测试没有任何问题，理论上和 6p 应该没差别。系统也是 10.3.2。

**Comment by iyangce** [comment]
![qq 20170704101448](https://user-images.githubusercontent.com/19756079/27814426-d923bd34-60ae-11e7-9154-3b14ab1c7af6.png)

**Comment by iyangce** [comment]
复现手机是6ps，系统10.2.1。和样式有关

**Comment by airyland** [comment]
没有这个机型可以复现，欢迎帮忙排查问题 pr。
