### ISSUE TITLE
在ios的webview中会出现滚动受阻的问题，这个该怎么解决呢？

### ISSUE THREAD

**Issue by petersmu** [airyland/vux#1645]
当页面滚动到边界的时候，会触发webview的弹性滚动，这个时候会拦截页面内部的滚动。

如图所示，我的内部页面还没有滚动到顶部，但页面已经无法滚动了，webview直接判定我滚到了边界，把黑边给拉出来了。

初步确定是html高度100%的问题，当html高度自适应为页面内容高度的时候就不会出现这种问题

![image](https://user-images.githubusercontent.com/12507715/27811646-3bb5e738-609b-11e7-885a-29456961d648.png)

**Comment by airyland** [comment]
目测你的页面没必要用 100%，直接改成自动高度就好了。100% 在 iOS 下有时候容器会无法滚动。

**Comment by petersmu** [comment]
这种方式我试过，但我有个页面是要全屏居中显示，这个怎么处理呢

**Comment by airyland** [comment]
没看明白，都已经是全屏了，怎么会有居中的说法?

**Comment by petersmu** [comment]
我想偏了，已经解决了。

所以viewbox组件就不能在ios里面用了吗

**Comment by airyland** [comment]
具体问题得具体分析，我遇到的问题一般只会在滚动时操作过快才会出现无法滚动的情况，所以不影响使用 viewbox。整体 webview 下移这个暂时我没遇到。
