### ISSUE TITLE
X-Input中如何使用 blur 来触发自定义的验证

### ISSUE THREAD

**Issue by YikaJ** [airyland/vux#1648]
version: 2.4.1
现在触发自定义验证的感觉就像是 onChange 就触发了，就是输一个字，立刻标红。希望可以做成像内置的 email 验证，是 blur 之后才标红的。
在 Issues 和文档中没找到相关内容，就来问一下，谢谢。

**Comment by YikaJ** [comment]
想结合 debounce 使用也可以缓解一下问题，但是似乎 debounce 在验证这里并不生效

**Comment by graysheeep** [comment]
暂时不做支持 欢迎pr
