### ISSUE TITLE
swiper组件报错

### ISSUE THREAD

**Issue by xuxiaoxiao312** [airyland/vux#1649]
之前用可以跑起来，但是今天再打开发现报错
实验发现官方示例的demo也会报错
报错内容：
TypeError: Cannot assign to read only property 'length' of function 'function from() { [native code] }'
版本号：2.4.1

**Comment by airyland** [comment]
用 Chrome 看了一下并没有报错，哪个浏览器报的错？报错代码是具体哪一行？

**Comment by xuxiaoxiao312** [comment]
用的是chrome，没有显示具体哪一行错，测试是slot部分有错
![image](https://user-images.githubusercontent.com/24541297/27845310-cea743e6-6160-11e7-8b26-d285b0bb2802.png)

**Comment by xuxiaoxiao312** [comment]
推测应该是arrayFrom函数出错。将源码中的arrayFrom相关函数注释掉，只将arrayFrom(me.$items)打印出来，如图所示，会报上面的错，全部注释且不打印则不会报错

![image](https://user-images.githubusercontent.com/24541297/27845593-312ac810-6163-11e7-8481-cc6c2f822b71.png)

**Comment by airyland** [comment]
如果这里那么是 array-from 这个模块的问题，但是我 chrome 58, chrome 59 重现不了。

**Comment by xuxiaoxiao312** [comment]
已经解决，应该是打包的时候出了问题，把node_modules情空，重新安装所有插件就没有问题了

**Comment by sinceow** [comment]
同样遇到这个问题
Chrome59 (64位)
"vux": "2.5.0",
"vue": "2.3.4",
"vux-loader": "1.1.0",
"vue-loader": "13.0.0"

@xuxiaoxiao312 我也清空了 node_modules 还是没用

**Comment by airyland** [comment]
@sinceow 可以打包发我研究一下。

**Comment by sinceow** [comment]
@xuxiaoxiao312 @airyland 这不是Vux 的问题， 是由 webpack 3 引起的 [#5135](https://github.com/webpack/webpack/issues/5135), 可以用以下方式解决
> Although we can set module.strictThisContextOnImports = true to prevent the problem.

**Comment by airyland** [comment]
@sinceow 原来如此，VUX 还没有更新到 webpack3。

**Comment by airyland** [comment]
vux@2.5.1-beta.2
