### ISSUE TITLE
Group组件中after-title的slot位置

### ISSUE THREAD

**Issue by git9527** [airyland/vux#1650]
感觉上group的after-title应当和title在同一行，但现在这个slot的却和title分布在两个div中
![image](https://user-images.githubusercontent.com/4514520/27836149-c8aad0b6-6110-11e7-8ab1-b935749dc730.png)

**Comment by airyland** [comment]
早期的某个需求导致的这样设计。上面 title 是用  `v-html` 导致也不可能再在里面加一个 slot 了。
这里看来得在上面的 title 下面增加一个 slot=title 。
