### ISSUE TITLE
localhost启动如何配置成域名

### ISSUE THREAD

**Issue by hanwsscan** [airyland/vux#1653]
localhost启动如何配置成域名，感谢！折腾了一下午，也查了之前的issues，没找到，添麻烦了

**Comment by graysheeep** [comment]
hosts里面配置的吧
www.xxx.com localhost这个样子

**Comment by hanwsscan** [comment]
感谢解答，可能是我没说清楚，安装整个项目后，npm run dev，默认localhost 可以访问。

**hosts配置**  

127.0.0.1 a.wodeyuming.com

**我在 nginx 下面配置了，**

server {
        listen  80;
	     server_name  a.wodeyuming.com;
	     location ~* \.(ttf|ttc|otf|eot|woff|)$ {
             add_header Access-Control-Allow-Origin *;
        }
        index  index.html index.shtml index.htm;
        root   E:/aaaa/vux;
        access_log  C:/nginx-1.11.4/logs/static_access.log  main;
        expires 1h;
		charset utf-8;
    }

想通过 a.wodeyuming.com 访问项目....

**Comment by airyland** [comment]
一般是 npm run build 构建到 dist 后，nginx 的 root 指向 dist 文件夹。

该问题和 VUX 组件无关，关闭了。
