### ISSUE TITLE
关于vux弹出框组件的建议，希望加个z-index属性设置

### ISSUE THREAD

**Issue by iewgnahz** [airyland/vux#1656]
### 项目中可能使用多个vux弹出框组件，可能同一个页面同时弹出多个弹出框 ，比如，注册页面弹出框使用了选择地区弹出框，同时本地页面也使用了一个底部悬浮菜单，这时候就要控制好它们的层叠关系，否则可能出现相互遮罩的问题，基于这个现象，我希望vux的弹出框组件可以设置个zIndex属性，自动控制它的大小，方便操作

**Comment by airyland** [comment]
下版本支持  popup-style
