### ISSUE TITLE
关于适用于移动端的简、小富文本编辑器的建议。  扩展 XTextarea ？

### ISSUE THREAD

**Issue by iguojing** [airyland/vux#1658]
能否新增一个控件， 或 对 XTextarea 进行扩展，使其具移动端图文编排能力。
1、可全屏
2、可配置工具栏，最多占据 1 行。可固化或配置几个常用的即可， 加粗、大小、列表、颜色、表情、插图等。

**Comment by airyland** [comment]
没有这个计划，在移动端做富文本编辑器这个不是常规需求，耗费的维护成本也会挺大，你可以找找第三方实现。
