### ISSUE TITLE
插件方式调用datetime报错

### ISSUE THREAD

**Issue by deronendless** [airyland/vux#1659]
报TypeError: Cannot read property 'classList' of undefined是什么意思，我是少引入什么文件吗

**Comment by airyland** [comment]
下个版本修复

**Comment by deronendless** [comment]
下个版本在什么时候啊，项目现在着急用到了这个datetime。

**Comment by airyland** [comment]
你可以先试试直接把组件 datetime import 进项目，但是不使用。

**Comment by deronendless** [comment]
嗯，引入vux的时候除了需要引入reset.less以外还需要什么依赖什么css文件吗？

**Comment by airyland** [comment]
v2.5.1 发布了。
其他样式不用了，样式是在组件里的。

**Comment by akkuan** [comment]
TypeError: Cannot read property 'classList' of undefined 依旧这个报错,最新的vux版本 2.7.7

**Comment by akkuan** [comment]
@airyland

**Comment by airyland** [comment]
@DearAKuan 这个问题在 v2.8.1 解决。
