### ISSUE TITLE
移动端屏幕适配处理

### ISSUE THREAD

**Issue by Jiunsr** [airyland/vux#1661]
我用js设置了viewport缩放，我用rem单位布局没问题，问题就是有写vux提供的组件里的样式em单位也变了，组件的样式可以换成rem单位吗?

**Comment by airyland** [comment]
暂时并不会用 rem，另一种做法，如果你是用插件实现 rem 转换，是可以避免 vux 源码样式被转换的。

https://github.com/airyland/vux/issues/932
