### ISSUE TITLE
Tabbar在没有过渡动画切换的时候， <tabbar-item>里的内容会有卡顿现象

### ISSUE THREAD

**Issue by LarsAlexand** [airyland/vux#1662]
Tabbar在没有过渡动画切换的时候， <tabbar-item>里的内容会有卡顿现象

**Comment by LarsAlexand** [comment]
demo里面tabbar是加了过渡动画的，取消过渡动画后，tab间的切换会随机导致内容有白屏的情况

**Comment by airyland** [comment]
? tabbar 组件本身是没有过渡动画的。

**Comment by LarsAlexand** [comment]
就是在没有加<transition></transition>的时候会随机出现这种情况，比如从tab1切换到tab2的时候，tab2的内容会白屏一下，然后内容才会从下面顶上来

**Comment by airyland** [comment]
既然是你的 tab 内容，和 tabbar 就没有关系了。
包括白屏，从下面显示上来这都是你自己的项目的设置，并不是组件的问题。
