### ISSUE TITLE
Datetime 插件方式调用的一个 BUG

### ISSUE THREAD

**Issue by teli5200** [airyland/vux#1663]
//          startDate: '2017-07-01',
//          endDate: '2017-07-11',

设置了上面两项后会报错 Cannot read property 'value' of undefined

错误位置为 this.yearScroller.value ：  

const { minMonth, maxMonth } = getMonths(this.config.startDate, this.config.endDate, this.yearScroller.value * 1)

**Comment by airyland** [comment]
不能重现，请帖完整调用参数。

``` js
this.$vux.datetime.show({
    startDate: '2017-07-01',
    endDate: '2017-07-11'
})
```

**Comment by teli5200** [comment]
showPlugin () {
        var currentTime = moment().format('MM-DD hh:mm');
        console.log('The time is ', currentTime);
        this.$vux.datetime.show({
          cancelText: '取消',
          confirmText: '确定',
          format: 'MM-DD HH:mm',
          startDate: '2017-07-01',
          endDate: '2017-07-11',
          onConfirm (val) {
            var currentTime = moment().year() + '-' + val;
            console.log('plugin confirm', currentTime);
          }
        });
      },


JS头：

  import { DatetimePlugin, Datetime} from 'vux';
  import moment from 'moment';
  import Vue from 'vue';
  Vue.use(DatetimePlugin);

**Comment by airyland** [comment]
@teli5200 YYYY 必须存在，否则组件判断不了当前哪一年，并且也无法处理跨年的日期了。
