### ISSUE TITLE
switch相关内容

### ISSUE THREAD

**Issue by Topthinking** [airyland/vux#1664]
能否给switch的内容也可以点击，点击触发switch的状态变化，在移动端，触点小的话，不是很友好的响应

**Comment by airyland** [comment]
整个 cell 可点击？

**Comment by YiGuaIn** [comment]
爲什麽XSwitch組件不能正常顯示呀，其他組件都正常，就唯獨這個XSwitch

![qq 20170709150250](https://user-images.githubusercontent.com/18462494/27991901-d9c85e4a-64b7-11e7-811d-6cf215823c7c.png)

**Comment by airyland** [comment]
@YiGuaIn  
1.请不要 issue 里提其他问题。
2.提问题请附上完整信息和你尝试解决此问题做了什么努力。显示不正常第一时间请自行检查是不是样式冲突，对比官方 demo 样式，尝试解决无果再提问。
