### ISSUE TITLE
请教下不用scroller组件，做上拉加载

### ISSUE THREAD

**Issue by helei112g** [airyland/vux#1665]
在不使用 scroller 的情况下，如何做 `pullup` 功能呢？

我在本想自己设置 `window.addEventListener('scroll', this.handleScroll);` 但是发现vux中这样设置后，并无法触发 scroll 事件。

有部分人说是因为顶级设置了 `overflow:auto` 的缘故导致的，但是我修改后，依然无效。

所以，我该怎么获取滑动到底部这一事件呢？

**Comment by airyland** [comment]
如何实现功能不是 vux 组件相关的就不在 issue 讨论了，毕竟这不是 js 论坛。vux 组件并不影响你如何使用 js 实现其他功能。

另外，上面的不触发 scroll 事件可能是你使用 100% 布局导致的，因为滚动容器不是 body 了，而是 div，你应该监听 div 滚动容器。
