### ISSUE TITLE
一个很奇怪的问题 Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by cnlinjie** [airyland/vux#1666]
版本：
"vux": "^2.5.0"
"vux-loader": "^1.1.0",

其他相关：
"vue": "^2.1.8",
"webpack": "^2.6.1",

很奇怪，如果之前有遇到过望提点下。

按照官网的教程，要使用VuxLoader配合使用，所以在webpack.base.conf.js 加入

```
let  vuxLoader = require('vux-loader')
...
```

```
module.exports = vuxLoader.merge(webpackBaseConf, {
  plugins: ['vux-ui']
})
```

然后运行 npm run dev 的时候 就会报这个错误
```
Failed to mount component: template or render function not defined.
```

如果去掉这个，vux可以正常使用，但就是js文件2M大小左右。我知道vuxLoader的作用，所以今天调试了一整天，网上的说法都是需要加
```
resolve: {
alias: {
'vue$':'vue/dist/vue.js'
 }
}
```
但这本来都有的，我的：
```
resolve: {
        extensions: ['.js', '.vue','.json'],
        alias: {
            'vue$': 'vue/dist/vue.js',
            '@': resolve('src'),
            'src': resolve('src'),
            'assets': resolve('src/assets')
        }
    }
```
所以应该不是这个问题。

**Comment by airyland** [comment]
判断不了，建个可以重现的 repo。

**Comment by cnlinjie** [comment]
https://github.com/cnlinjie/vux-repo

@airyland  谢谢，我建立了一个repo ，目前这个是正常的，我注释了
```js
module.exports = vuxLoader.merge(webpackBaseConf, {
  plugins: ['vux-ui']
})
```

**Comment by airyland** [comment]
vux-loader 对配置的解析没有考虑到你贴心地为 vue-loader 使用 `use` 的情况，升级到 vux-loader@^1.1.1 试试。

**Comment by cnlinjie** [comment]
非常感谢，已经可以正常使用了。真心谢谢

**Comment by Stevenzwzhai** [comment]
这个问题怎么解决的。我的vux-loader用的1.1.5
我是用了happypack，去掉就好了

**Comment by decemberLi** [comment]
出现了同样的问题，
使用的是
"dependencies": {
    "axios": "^0.19.2",
    "core-js": "^3.6.5",
    "echarts": "^4.8.0",
    "element-ui": "^2.13.2",
    "v-charts": "^1.19.0",
    "vue": "^2.6.11",
    "vue-router": "^3.4.3",
    "vux": "^2.9.4"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "less": "^3.12.2",
    "less-loader": "^6.2.0",
    "vue-template-compiler": "^2.6.11",
    "vux-loader": "^1.2.9",
    "yaml-loader": "^0.6.0"
  },
