### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by ohohco** [airyland/vux#167]
`import {Group, Cell} from 'vux/src/components/'` this will error: 
`index.js?7df5:1 Uncaught SyntaxError: Unexpected token import`

**Comment by airyland** [comment]
Did you use babel?

**Comment by ohohco** [comment]
yes！

**Comment by airyland** [comment]
Actually I don's think this is vux's issue.  Please provide more information.

**Comment by xiadd** [comment]
this way to import is wrong
```
import { Group } from 'vux'//true
```

**Comment by airyland** [comment]
@xiadd you are right, I didn't notice the error path.
