### ISSUE TITLE
Cell的link为电话号码的时候无法识别

### ISSUE THREAD

**Issue by shoyuf** [airyland/vux#1672]
`<cell is-link :title="elDetail.tel" :link="'tel:'+elDetail.tel"></cell>`
执行结果为url加上'tel:'+elDetail.tel而不是正常（router-link）的a标签跳转方式

**Comment by airyland** [comment]
其实你直接  router-link 写这类链接也是无效的，所以不知道你说的 router-link 正常是什么意思？

``` html
<router-link to="tel:2343332">dddrr</router-link>
```

**Comment by shoyuf** [comment]
嗯，是我记错了，在mint-ui中<Cell :to="'tel:10086'"></Cell>兼容实现了拨打电话的跳转，因为cell里面拨打电话还是比较常见的。  见谅。
