### ISSUE TITLE
popup弹出，body被覆盖。

### ISSUE THREAD

**Issue by zhump** [airyland/vux#1673]
版本：2.2.1
浏览器：iphone,andriod浏览器，pc浏览器没问题。
拷贝了官网例子的代码
预计出现：
与官网显示一致。
实际出现：
body消失。
经调试，是z-index改变后，覆盖了本来的body。可是pc却又是好的。官网提供的demo没问题。
![3](https://user-images.githubusercontent.com/7962067/28002619-5bd7cd4c-6569-11e7-9c8d-c652b5210f0f.gif)

**Comment by airyland** [comment]
这会已经到了 2.5.x 版本了，升级试试。

**Comment by zhump** [comment]
升级了 2.5.1，手机上还是这样，可是我down了demo的项目，在本地跑起来，又是好好的。吐血了。

**Comment by zhump** [comment]
找到原因了。 #1275，根据这个提示我加上了
```
html, body {
  height: 100%;
  width: 100%;
}
```
造成的这个问题。去掉就好了。
更神奇的是，我去掉这个代码，dialog的scroll也好了。本来有这个代码，dialog的scroll才生效的。晕了。

**Comment by airyland** [comment]
额，但是 demo 本身也是 100% 的布局，没有出现问题。

**Comment by zhump** [comment]
我没有大神你提供的脚手架了，重新vue webpack xx了一份 目前没有这些问题了。多谢了。🙏
