### ISSUE TITLE
panel 组件的更新

### ISSUE THREAD

**Issue by cnlinjie** [airyland/vux#1674]
目前我们vux的**panel**组件demo：

![image](https://user-images.githubusercontent.com/3601638/28006133-92864dca-6580-11e7-95f2-1146b9f98e95.png)

目前weui.io官网新增加的: 

![image](https://user-images.githubusercontent.com/3601638/28006116-7eda1f4a-6580-11e7-9cf4-8d362e775ed4.png)

我看了下weui.io的这个新加的这个，在vux 的css好像都有。
我没有引进css，直接用vux的样式实现的如图

![image](https://user-images.githubusercontent.com/3601638/28006091-69ec9a04-6580-11e7-9bd8-5411308d5058.png)

大神有时间更新吗? 如果没有时间，我晚点参考vux项目发一个PR 。

**Comment by airyland** [comment]
欢迎 PR。

**Comment by cnlinjie** [comment]
@airyland  好的，那我晚点，下班回去fork一份整一整看看。

**Comment by cnlinjie** [comment]
@airyland  已经提交PR了
