### ISSUE TITLE
popup-radio编译时有问题

### ISSUE THREAD

**Issue by imfengzi** [airyland/vux#1677]
我尝试做了一个自己的组件需要用到微信插件
import CommonFunction from './src/plugins/CommonFunction/index.js'
import TransitPlugin from './src/plugins/Transit/index.js'
import { WechatPlugin } from 'vux'
import Vue from 'vue'

Vue.use(WechatPlugin)
export {
  CommonFunction,
  TransitPlugin
}

在项目引入插件后编译，会报如下错误，强制删除.._cellProps,  ...radioProps() 后功能正常

 error  in ./~/vux/src/components/popup-radio/index.vue

Syntax Error: Unexpected token (50:4)

  48 |     placeholder: String,
  49 |     readonly: Boolean,
> 50 |     ..._cellProps,
     |     ^
  51 |     ...radioProps()
  52 |   },
  53 |   computed: {

**Comment by airyland** [comment]
你上面说你用到 WechatPlugin，但是这跟 popup-radio 有什么关系。。

js 语法不支持，检查 babel 配置。
