### ISSUE TITLE
popup-radio编译时报错

### ISSUE THREAD

**Issue by imfengzi** [airyland/vux#1678]
单独做一个插件A，插件A里如果引入vux中的Plugin，在项目使用插件A的时候就会报错
error  in ./~/vux/src/components/popup-radio/index.vue
Syntax Error: Unexpected token (50:4)

  48 |     placeholder: String,
  49 |     readonly: Boolean,
> 50 |     ..._cellProps,
     |     ^
  51 |     ...radioProps()
  52 |   },
  53 |   computed: {

**Comment by airyland** [comment]
不要重复发 issue 可以吗
在 #1677 不是让你查 babel 配置吗
