### ISSUE TITLE
AjaxPlugin 请求之后then的回调函数，里面的this并不是指向当前vue实例

### ISSUE THREAD

**Issue by ycycorona** [airyland/vux#1679]
例如在created钩子中    
created(){
        this.$http.post('/xxx')
        .then(function (res) {
          console.log(this);     //  在AjaxPlugin中此处为undefined  ,而在vue-resource@1.3.4中测试this指向当前vue实例   
        })
    },

**Comment by airyland** [comment]
这是js 基础问题。 请使用**箭头函数**。

**Comment by ycycorona** [comment]
sorry for bother!!!

**Comment by ycycorona** [comment]
刚刚试了一下，匿名函数可用（this指向当前实例），箭头函数不可用···· 可能是我太菜了

**Comment by ycycorona** [comment]
感觉vue已经自动hack了，匿名函数的作用域问题，所以使用箭头函数会弄巧成拙，并不会得到外层函数的this引用。。。。

**Comment by ycycorona** [comment]
感觉vue已经自动hack了，匿名函数的上下文问题，所以使用箭头函数会弄巧成拙，反而不会得到外层函数的this引用。。。。

**Comment by airyland** [comment]
帖下具体代码吧，vue 并没有做其他处理。

**Comment by ycycorona** [comment]
created(){
      console.log(this);
      this.testContext1();  
      this.testContext2();
      this.testContext3(); 
    },
    methods: {
      testContext1(){
        console.log("testContext1",this);   //Vue实例
      },
      testContext2:()=>{
        console.log("testContext2",this);  //不是vue实例
      },
      testContext3:function(){
        console.log("testContext3",this);    // Vue实例
      },
      requsetData(searchPara){
        console.log(this);    // Vue实例
       
        this.$http.post('/api/getMockList',{'fileName':searchPara})
        .then((res)=>{
          console.log(this);   // Vue实例,开始这里没用箭头函数，this不是指向vue实例
          this.studyFileList = res.data.busData;
        })
        .catch(function (code) {
          console.log('获取数据时与后台通讯失败',code);
        });
      },
  }

其实你说的没错，开始我理解有点问题。。。。现在大概就是这样

**Comment by airyland** [comment]
这是对的，这里不要用箭头函数了。作为对象的一个项，再用箭头函数 this 指向当然就不对了。

```
testContext1 () {
    console.log("testContext1",this);   //Vue实例
  },
```
