### ISSUE TITLE
XNumber v-model 绑定

### ISSUE THREAD

**Issue by echozhangzy8888** [airyland/vux#1680]
"dependencies": {
    "axios": "^0.16.1",
    "highcharts": "^5.0.10",
    "jsonp": "^0.2.1",
    "swiper": "^3.4.2",
    "vee-validate": "^2.0.0-rc.2",
    "vue": "^2.2.2",
    "vue-highcharts": "0.0.10",
    "vue-router": "^2.3.0",
    "vux": "^2.3.6"
  },
该配置环境下，  当用XNumber 组件 绑定参数 进行增加的时候  报：
Invalid prop: custom validator check failed for prop "value".

**Comment by shijunti19** [comment]
数值必须数字，不然就提示的
