### ISSUE TITLE
search组件，修改背景颜色后发现有两条白线

### ISSUE THREAD

**Issue by jijiecong** [airyland/vux#1682]
在通过配置search组件的背景颜色@search-bg-color后，出现的效果是搜索框上下各有一条横线，查看css后发现，.weui-search-bar这个class里面有一个before和一个after，导致出现一个border，而这个border的颜色在可配置颜色里是没有的。可否新增这个颜色配置项，还有就是没明白这个before和after的作用是什么？
不知为什么上传不了图片，只能文字讲述了，不知道我说的好不好理解。。。

**Comment by airyland** [comment]
到这里传图片复制链接过来 https://sm.ms/

**Comment by jijiecong** [comment]
https://ooo.0o0.ooo/2017/07/11/5964a78cd52cc.png
https://ooo.0o0.ooo/2017/07/11/5964a78ce9606.png

**Comment by wg5945** [comment]
这是weui的样式哦，不用的话就自行覆盖掉吧

```
  .weui-search-bar {
    &:before, &:after {
      display: none;
    }
  }
```
