### ISSUE TITLE
你好，在使用【页面切换显示loading】这个功能时出现问题

### ISSUE THREAD

**Issue by city8866** [airyland/vux#1683]
你好，按照你的教程去操作切换页面现实loading动画时，出现一个问题，问题如下:

vue.esm.js?a588:434 [Vue warn]: Error in render function: "TypeError: Cannot read property 'state' of undefined"

found in

---> <App> at f:\vue\cgj-demo\src\App.vue
       <Root>warn @ vue.esm.js?a588:434handleError @ vue.esm.js?a588:519Vue._render @ vue.esm.js?a588:3905updateComponent @ vue.esm.js?a588:2439get @ vue.esm.js?a588:2778Watcher @ vue.esm.js?a588:2761mountComponent @ vue.esm.js?a588:2443Vue$3.$mount @ vue.esm.js?a588:7570Vue$3.$mount @ vue.esm.js?a588:9669init @ vue.esm.js?a588:3358createComponent @ vue.esm.js?a588:4901createElm @ vue.esm.js?a588:4844patch @ vue.esm.js?a588:5342Vue._update @ vue.esm.js?a588:2316updateComponent @ vue.esm.js?a588:2439get @ vue.esm.js?a588:2778Watcher @ vue.esm.js?a588:2761mountComponent @ vue.esm.js?a588:2443Vue$3.$mount @ vue.esm.js?a588:7570Vue$3.$mount @ vue.esm.js?a588:9669Vue._init @ vue.esm.js?a588:4010Vue$3 @ vue.esm.js?a588:4095(anonymous function) @ main.js?1c90:67(anonymous function) @ app.js:1242__webpack_require__ @ app.js:660fn @ app.js:86(anonymous function) @ app.js:2618__webpack_require__ @ app.js:660(anonymous function) @ app.js:709(anonymous function) @ app.js:712
vue.esm.js?a588:523
 TypeError: Cannot read property 'state' of undefined(…)

提示state未定义。请问这是怎么回事，请解决下，谢谢。

**Comment by city8866** [comment]
vue.esm.js?a588:434 [Vue warn]: Error in render function: "TypeError: Cannot read property 'state' of undefined"

found in

---> at ...
TypeError: Cannot read property 'state' of undefined(…)

就这段

**Comment by city8866** [comment]
在App.vue里使用loading组件并从vuex获取isLoading状态

<loading v-model="isLoading"></loading>
import { Loading } from 'vux'
import { mapState } from 'vuex'

export default {
  components: {
    Loading
  },
  computed: {
    ...mapState({
      isLoading: state => state.vux.isLoading
    })
  }
}

在App.vue里提示 Error in render function: "TypeError: Cannot read property 'state' of undefined"
TypeError: Cannot read property 'state' of undefined(…),
所有代码按照你的代码写的。

**Comment by city8866** [comment]
![image](https://user-images.githubusercontent.com/24402516/28104555-43cb8788-670e-11e7-9404-1360432a0695.png)
看图

**Comment by airyland** [comment]
1. 代码麻烦拜托请格式化，不会用的话请搜索 markdown 中如何格式化代码
2. 麻烦帖上所有相关代码，main.js 的代码呢？

请补充代码后 reopen 当前 issue。

**Comment by city8866** [comment]
`
import Vue from 'vue'
// 引用路由
import VueRouter from 'vue-router'
import Vuex from 'vuex'
import vuexI18n from 'vuex-i18n'
import axios from  'axios'


Vue.use(VueRouter)
Vue.use(Vuex)

axios.defaults.timeout = 5000;
axios.defaults.headers.post['Content-Type'] = 'application/json';
axios.defaults.headers.put['Content-Type'] = 'application/json';
axios.defaults.headers.delete['Content-Type'] = 'application/json';
axios.defaults.baseURL = 'http://api.cgj.com/v1';

// 入口文件为 src/App.vue 文件 所以要引用
import App from './App.vue'
// 引用路由配置文件
import routes from './router/routes'
import { cookie } from 'vux'

/**
 * you can add your module here
 */
let store = new Vuex.Store({
    modules: {
        i18n: vuexI18n.store
    }
})

store.registerModule('vux', {
    state: {
        demoScrollTop: 0,
        isLoading: false,
        direction: 'forward'
    },
    mutations: {
        updateDemoPosition (state, payload) {
            state.demoScrollTop = payload.top
        },
        updateLoadingStatus (state, payload) {
            state.isLoading = payload.isLoading
        },
        updateDirection (state, payload) {
            state.direction = payload.direction
        }
    },
    actions: {
        updateDemoPosition ({commit}, top) {
            commit({type: 'updateDemoPosition', top: top})
        }
    }
})

Vue.use(vuexI18n.plugin, store)

/*store.registerModule('vux', { // 名字自己定义
    state: {
        isLoading: false,
        orderList:[{orderno:'423244',productName:'apple'}]
    },
    mutations: {
        updateLoadingStatus (state, payload) {
            state.isLoading = payload.isLoading
        }
    }
})*/

const router = new VueRouter({ routes })

router.beforeEach((to,from,next) => {
    if(to.meta.requireAuth){
      if(typeof (cookie.get('token')) == 'undefined'){
          store.commit('updateLoadingStatus', {isLoading: true})
          next({
              path:'/user/login',
              query: {redirect: to.fullPath}  // 将跳转的路由path作为参数，登录成功后跳转到该路由
          })
      }else{
          store.commit('updateLoadingStatus', {isLoading: true})
        next();
      }
    }else{
        store.commit('updateLoadingStatus', {isLoading: true})
        next();
    }
})

router.afterEach(function (to) {
    store.commit('updateLoadingStatus', {isLoading: false})
})

Vue.prototype.$ajax = axios

// 跑起来吧
new Vue({
  router,
  el: '#app',
  render: (h) => h(App)
})
`
不好意思。这是main.js的全部代码。
`<template>
  <div>
    <router-view
            class="view"
            keep-alive
            transition
            transition-mode="out-in">
    </router-view>
    {{ cunt }}
    <loading v-model="isLoading"></loading>
  </div>
</template>
<script>
    import { Loading } from 'vux'
    import { mapState, mapActions } from 'vuex'

    export default {
        data(){
            return{

            }
        },
        components: {
            Loading,
        },
        computed: {
                ...mapState({
                route: state => state.route,
                path: state => state.route.path,
                deviceready: state => state.app.deviceready,
                demoTop: state => state.vux.demoScrollTop,
                isLoading: state => state.vux.isLoading,
                direction: state => state.vux.direction
            })
        },
        mounted(){

        }
    }
</script>
<style lang="less">
@import '~vux/src/styles/reset.less';
@import '~vux/src/styles/1px.less';
@import '~vux/src/styles/tap.less';
</style>
`
这是App.vue全部代码。
执行结果如上图所示。

**Comment by airyland** [comment]
依然没有格式化。

store 并没有挂载到 vue 实例上。

``` js
new Vue({
  store,
  router,
```

**Comment by city8866** [comment]
ok,谢谢大神，给你打赏了。

**Comment by s641135196** [comment]
厉害了，我竟然也是这问题

**Comment by kufei88** [comment]
哈哈，我也是这个问题，store没有挂到vue实例上
