### ISSUE TITLE
popup-picker cancel_text

### ISSUE THREAD

**Issue by thedayisantherday** [airyland/vux#1689]
编译报错：Cannot read property 'vux.popup-picker.cancel_text' of undefined
```
<template>
  <div>
    <popup-picker :title="'手机'" :data="[['小米', '苹果']]" ></popup-picker>
  </div>
</template>

<script>
  import Vue from 'vue'
  import popupPicker from 'vux/src/components/popup-picker/index.vue'
  export default {
    name: 'test',
    data () {
      return {}
    },
    components: {
      popupPicker
    }
  }
</script>

```

**Comment by airyland** [comment]
请配置 vux-loader。

**Comment by thedayisantherday** [comment]
按照文档的配置，可以正常使用了

vux2必须配合vux-loader使用, 请在build/webpack.base.conf.js里参照如下代码进行配置：
const vuxLoader = require('vux-loader')
const webpackConfig = originalConfig // 原来的 module.exports 代码赋值给变量 webpackConfig

module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui']
})
