### ISSUE TITLE
vux ^2.3.1 , previewer组件 未设置 w 、h 变量时，点击打开后报错。

### ISSUE THREAD

**Issue by proc07** [airyland/vux#1691]
未设置 w、h 时
![image](https://user-images.githubusercontent.com/16809535/28168341-60057054-6811-11e7-8cfd-13a57a80cba8.png)

**Comment by proc07** [comment]
![image](https://user-images.githubusercontent.com/16809535/28169043-b08f7ee6-6813-11e7-95a8-9e19337a7102.png)

并且我设置w、h 时，当前点击第1张图片时，滚动到第三张图片时，在第3张往上推上去，消失。
但是访问的位置是第1张图片的位置。我看到你们的例子中是没有问题的，但是我这里是奇了怪

**Comment by proc07** [comment]
调用查看图片的全部代码：
![image](https://user-images.githubusercontent.com/16809535/28169202-2f0cf672-6814-11e7-8d73-5f59e8f61483.png)
![image](https://user-images.githubusercontent.com/16809535/28169219-3aea54e4-6814-11e7-92ba-3496a61f43d0.png)
// 这2段是获取w、h
![image](https://user-images.githubusercontent.com/16809535/28169234-4515fad6-6814-11e7-81ce-04c51ce437bf.png)
// this.$parent.$emit('previewerData', objImages, index, obj.srcElement);
![image](https://user-images.githubusercontent.com/16809535/28169269-5f093534-6814-11e7-872c-a3508fbfca8b.png)
// 配置
![image](https://user-images.githubusercontent.com/16809535/28169289-6b10e02a-6814-11e7-9b1b-eee874df20bd.png)

**Comment by airyland** [comment]
建 repo 重现吧。

**Comment by proc07** [comment]
@airyland   我没用过 repo

**Comment by jxZhangLi** [comment]
![image](https://user-images.githubusercontent.com/16809535/28194524-71160596-6877-11e7-8f72-c90420986b88.png)

我把你的代码 复制过来放在我这里还是报错。

**Comment by airyland** [comment]
？ 在你的 Github 下面建一个可以重现你的问题的 repository(版本库)。

**Comment by proc07** [comment]
我已经找到问题了！ 在这个配置地方，获取当前图片的位置坐标，我之前是点击图片时用event.srcElement 的DOM元素，复制到 thumbnail 变量上的，现在按照你这种 document 获取元素的就没问题！（奇怪的是不都是DOM元素吗？怎么会出现这种问题）
![image](https://user-images.githubusercontent.com/16809535/28197242-24d4cdd2-6888-11e7-8745-f5e5dc8358ca.png)

**Comment by airyland** [comment]
坐标位置是跟 index 相关的，你上面这个截图获取位置没有关联到 index 吧

![image](https://user-images.githubusercontent.com/559179/28198371-59027ebc-6890-11e7-8108-b75f3a79d413.png)

**Comment by proc07** [comment]
这个是点击图片的Dom对象
