### ISSUE TITLE
官方API文档关于XInput的参数说明有误

### ISSUE THREAD

**Issue by pecasha** [airyland/vux#1692]
https://vux.li/#/zh-CN/components?id=xinput

props的is-type文档中说明自定义校验函数需要返回一个包含valid的对象，按文档中的描述，应该是valid值等于true时验证通过，等于false时验证不通过并返回错误原因。
但是实际使用中发现是反过来的，返回true时是验证不通过，返回false时则验证通过了。

**Comment by wg5945** [comment]
你看官网的demo
```
      be2333: function (value) {
        return {
          valid: value === '2333',
          msg: 'Must be 2333'
        }
      },
```
的确是当valid为true时，验证通过的啊，没发现有什么问题

**Comment by pecasha** [comment]
@wg5945 是我错了，valid等于false的时候是必须有msg的，我都没有传
