### ISSUE TITLE
UMD方式单独引入组件，报错Failed to mount component

### ISSUE THREAD

**Issue by littlebaozi** [airyland/vux#1694]
UMD方式单独引入组件会报错：`Failed to mount component: template or render function not defined`。
example文件夹下面umd_component_include_single.html也是同样问题
直接使用vux.min.js时没有问题。

**Comment by wg5945** [comment]
vux2之后就不建议使用引入script的方式了，请使用webpack

**Comment by cejpo001** [comment]
我也是碰到这个情况,请问你的这个问题解决了吗?
