### ISSUE TITLE
check-icon 组件代码疑问

### ISSUE THREAD

**Issue by cnlinjie** [airyland/vux#1695]
check-icon 组件里面的js代码有如下:
```js
 updateValue () {
      this.$emit('update:value', !this.value)
    }
```
引用这个这个监听事件的时候，得用 @update:value 否则监听不到
按照其他组件都是用`-` 做间隔，独独这里用了`:`，功能没问题，就是IDE会报红~，是本来就这样的吗？

IDEA会报这样
![image](https://user-images.githubusercontent.com/3601638/28204128-3a051884-68af-11e7-8704-36d110ba9885.png)

**Comment by cnlinjie** [comment]
有看到官方有例子这样写了，我就关了这个。

**Comment by airyland** [comment]
这是双向绑定的更新语法，demo 里并没有 `@update:value` 这样的写法，值绑定用 `:value.sync`

**Comment by cnlinjie** [comment]
@airyland  是的，我想用来监听事件，将多选变为单选。
