### ISSUE TITLE
PopupPicker和XTextarea貌似有冲突

### ISSUE THREAD

**Issue by crowscc** [airyland/vux#1696]
如果我通过路由跳转 vue-router
访问了一个页面中包含XTextarea的页面后返回再访问一个包含PopupPicker的页面 PopupPicker的样式就有一点点问题
如果我不通过路由跳转不会出现这种情况
![开始](http://i.imgur.com/2XbEMDJ.png)
![访问页面](http://i.imgur.com/p2VXrnS.png)
![变成这样](http://i.imgur.com/DFslx3M.png)

**Comment by airyland** [comment]
这样描述大概是无法重现的。
你应该先尝试检查问题，对比一下正常情况下和异常情况下，popup-picker 左边的 label 样式有什么不同。

**Comment by crowscc** [comment]
奇怪的是css样式里多了一个
.weui-label  正常情况下我直接访问是没有这个style的 这个样式固定了width 所以显示有问题
 我在想是不是路由跳转过程中缓存出现了问题
![](http://i.imgur.com/CAvRg5S.png)

**Comment by airyland** [comment]
也有可能是组件加载顺序导致的样式覆盖，我检查一下。
