### ISSUE TITLE
tab  bar动画条位置错乱bug

### ISSUE THREAD

**Issue by wcldyx** [airyland/vux#1697]
tab-item 没有固定宽度，bar条的位置就乱了，且宽度跟选择的tab-item不相等
![default](https://user-images.githubusercontent.com/26700595/28235909-06358b0a-694b-11e7-81dc-485802c1a0e0.png)

**Comment by wcldyx** [comment]
这个问题会不会解决啊，我怎么查看呢

**Comment by lsw1990** [comment]
示例里面都有这个问题
