### ISSUE TITLE
关于x-input  number限制最大字符的问题

### ISSUE THREAD

**Issue by 563325028** [airyland/vux#1699]
在issues里面搜了一下 有说用keyboard="number" 但是我试了一下还是不行限制最大字符数量 想问一下现在有办法解决在只能输入数字的情况下限制最大数量限制么

**Comment by wg5945** [comment]
如果仅仅是keyboard="number"的话，可以使用max控制最大字符
`<x-input title="手机号码" keyboard="number" :max="11"></x-input>`

**Comment by 563325028** [comment]
keyboard="number" 试了 不过没法只输入数字  只能用js进行判断删减了

**Comment by wg5945** [comment]
keyboard="number" 在某些安卓手机上的确不能很好地限制，可以换成 type="tel"

反正不管键盘是什么样的，最后输入结果的校验还是要做一下的

**Comment by 563325028** [comment]
好的
