### ISSUE TITLE
关于 popup-picker 的选中显示show-name的问题

### ISSUE THREAD

**Issue by ideaspace** [airyland/vux#1700]
结构如下
<popup-picker :placeholder="title.prod" :data="prodList" v-model="product" @on-change="onChange" value-text-align="left" show-name></popup-picker>

1、声明 prodList 为 []
2、数据为异步请求
```
if (r.data.code === 0) {
    const temp = []
    r.data.records.forEach(v => {
          temp.push({
                name: v.itemName,
                value: v.itemId
          })
     })
    this.prodList.push(temp)
}
```
选中后，无法显示对应的 itemName
3、无奈 onChange 使用 loadsh/find 手动赋值，也无法显示

万般无奈，只能求助

**Comment by airyland** [comment]
格式化代码是提问礼貌。

:data 是一个数组里多个子数组

``` js
this.prodList.push([temp1, temp2])
```

**Comment by ideaspace** [comment]
对不起，下次注意。谢谢
