### ISSUE TITLE
x-address组件引入时发生错误

### ISSUE THREAD

**Issue by pecasha** [airyland/vux#1701]
引入x-address组件，运行时发生错误，错误发生在/vux/src/components/flexbox/flexbox.vue，看了代码之后发现flexbox.vue中的style写了lang="less"，将lang="less"去除后即可正常运行

**Comment by airyland** [comment]
less 的预处理器就是 less。确定你 **按照文档** 安装了 less less-loader。

另外，发生错误却完全不帖错误信息的问题我们不会再处理。

**Comment by ChenArno** [comment]
我也是这样，请问怎么解决的
` error  in ./~/vux/src/components/flexbox/flexbox.vue

Module build failed: 


@theme-color: #DF4F45;@opacity-disabled: 0.5;@actionsheet-label-primary-color: #1AAD19;@actionsheet-label-warn-color: #E64340;@actionsheet-label-default-color: #000;@actionsheet-label-disabled-color: #ccc;@datetime-header-item-font-color: @theme-color;@datetime-header-item-cancel-font-color: #828282;@datetime-header-item-confirm-font-color: @datetime-header-item-font-color;@tabbar-text-active-color: #DF4F45;@tab-text-disabled-color: #ddd;@tab-text-default-color: #666;@tab-text-active-color: @theme-color;@tab-bar-active-color: @theme-color;@dialog-button-text-primary-color: #0BB20C;@dialog-button-text-default-color: #353535;@number-button-font-color: #3cc51f;@number-input-font-color: #666;@number-button-enabled-border-color: #ececec;@number-square-button-enabled-border-color: @number-button-enabled-border-color;@number-round-button-enabled-border-color: @number-button-font-color;@number-button-disabled-border-color: @number-button-enabled-border-color;@number-round-button-disabled-border-color: @number-button-enabled-border-color;@checkbox-icon-color-checked: #09BB07;@check-icon-color-checked: @checkbox-icon-color-checked;@cell-label-color: #000;@cell-font-size: 17px;@cell-tips-font-size: 14px;@cell-default-arrow-color: #C8C8CD;@cell-disabled-arrow-color: #e2e2e2;@cell-default-arrow-border-width: 2px;@cell-default-arrow-width: 6px;@dialog-mask-background: rgba(0, 0, 0, .6);@range-disabled-opacity: @opacity-disabled;@range-bar-default-color: #a9acb1;@range-bar-active-color: @theme-color;@tabbar-index: 100;@header-background-color: #FFF;@header-title-color: #333333;@header-text-color: #333333;@header-arrow-color: #333333;@timeline-item-bg-color: @theme-color;@switch-checked-bg-color: @theme-color;@switch-checked-border-color: @theme-color;@switch-disabled-opacity: 0.6;@button-global-border-radius: 5px;@button-global-font-color: #FFFFFF;@button-global-margin-top: 15px;@button-global-height: 42px;@button-global-disabled-font-color: rgba(255,255,255,.6);@button-global-active-font-color: rgba(255,255,255,.6);@button-global-font-size: 18px;@button-warn-bg-color: #E64340;@button-warn-active-color: #CE3C39;@button-warn-disabled-bg-color: #EC8B89;@button-default-bg-color: #F8F8F8;@button-default-font-color: #000000;@button-default-active-bg-color: #DEDEDE;@button-default-disabled-font-color: rgba(0,0,0,.3);@button-default-disabled-bg-color: #F7F7F7;@button-default-active-font-color: rgba(0,0,0,.6);@button-primary-bg-color: #DF4F45;@button-primary-active-bg-color: #FE8A81;@button-primary-disabled-bg-color: #9ED99D;@swipeout-button-primary-bg-color: @button-primary-bg-color;@swipeout-button-warn-bg-color: @button-warn-bg-color;@swipeout-button-default-bg-color: #c8c7cd;@swipeout-content-bg-color: #FFF;@swipeout-button-font-color: #FFF;@cell-body-label-color: #000;@badge-bg-color: #f74c31;@popover-bg-color: #35495e;@popover-font-color: #fff;@popover-border-radius: 3px;@popover-border-width: 5px;@button-tab-border-width: 1px;@button-tab-border-radius: 5px;@button-tab-border-color: @theme-color;@button-tab-default-border-color: @button-tab-border-color;@button-tab-active-border-color: @button-tab-border-color;@button-tab-default-background-color: #fdfdfd;@button-tab-active-background-color: @theme-color;@button-tab-active-text-color: @button-tab-active-font-color;@button-tab-default-text-color: @theme-color;@button-tab-height: 30px;@button-tab-line-height: 31px;@swiper-indicator-active-color: @theme-color;@checklist-icon-active-color: #09BB07;@popup-picker-header-text-color: @theme-color;@popup-picker-header-bg-color: #fbf9fe;@popup-picker-header-font-size: 16px;@popup-picker-header-cancel-text-color: #828282;@popup-background-color: #eee;@popup-header-height: 44px;@popup-header-bg-color: #fbf9fe;@popup-header-font-size: 16px;@popup-header-left-text-color: #828282;@popup-header-right-text-color: @theme-color;@popup-header-title-text-color: #222;@popup-header-left-text-padding: 15px;@popup-header-right-text-padding: 15px;@form-preview-button-primary-color: #0BB20C;@load-more-line-color: #E5E5E5;@sticky-zindex: 500;@group-title-margin-top: .77em;@group-title-margin-bottom: .3em;@toast-content-font-size: 16px;@toast-top: 180px;@toast-position-top-offset: 10px;@toast-position-bottom-offset: 10px;@toast-z-index: 5000;@icon-success-color: #09BB07;@calendar-arrow-color: @theme-color;@calendar-highlight-color: #E59313;@calendar-selected-bg-color: @theme-color;@calendar-disabled-font-color: #c0c0c0;@calendar-today-font-color: @theme-color;@calendar-date-item-font-size: 16px;@search-cancel-font-color: @theme-color;@search-bg-color: #EFEFF4;@search-placeholder-font-color: #9B9B9B;@radio-checked-icon-color: #09BB07;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ^
Variable @button-tab-active-font-color is undefined
      in /Users/century/vue/dingdong/node_modules/vux/src/components/flexbox/flexbox.vue (line 75, column 3278)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4ab4f503","scoped":false,"hasInlineConfig":false}!./~/vux-loader/src/after-less-loader.js!./~/less-loader/dist/cjs.js?{'modifyVars':{'theme-color':'#DF4F45','opacity-disabled':'0.5','actionsheet-label-primary-color':'#1AAD19','actionsheet-label-warn-color':'#E64340','actionsheet-label-default-color':'#000','actionsheet-label-disabled-color':'#ccc','datetime-header-item-font-color':'@theme-color','datetime-header-item-cancel-font-color':'#828282','datetime-header-item-confirm-font-color':'@datetime-header-item-font-color','tabbar-text-active-color':'#DF4F45','tab-text-disabled-color':'#ddd','tab-text-default-color':'#666','tab-text-active-color':'@theme-color','tab-bar-active-color':'@theme-color','dialog-button-text-primary-color':'#0BB20C','dialog-button-text-default-color':'#353535','number-button-font-color':'#3cc51f','number-input-font-color':'#666','number-button-enabled-border-color':'#ececec','number-square-button-enabled-border-color':'@number-button-enabled-border-color','number-round-button-enabled-border-color':'@number-button-font-color','number-button-disabled-border-color':'@number-button-enabled-border-color','number-round-button-disabled-border-color':'@number-button-enabled-border-color','checkbox-icon-color-checked':'#09BB07','check-icon-color-checked':'@checkbox-icon-color-checked','cell-label-color':'#000','cell-font-size':'17px','cell-tips-font-size':'14px','cell-default-arrow-color':'#C8C8CD','cell-disabled-arrow-color':'#e2e2e2','cell-default-arrow-border-width':'2px','cell-default-arrow-width':'6px','dialog-mask-background':'rgba(0, 0, 0, .6)','range-disabled-opacity':'@opacity-disabled','range-bar-default-color':'#a9acb1','range-bar-active-color':'@theme-color','tabbar-index':'100','header-background-color':'#FFF','header-title-color':'#333333','header-text-color':'#333333','header-arrow-color':'#333333','timeline-item-bg-color':'@theme-color','switch-checked-bg-color':'@theme-color','switch-checked-border-color':'@theme-color','switch-disabled-opacity':'0.6','button-global-border-radius':'5px','button-global-font-color':'#FFFFFF','button-global-margin-top':'15px','button-global-height':'42px','button-global-disabled-font-color':'rgba(255,255,255,.6)','button-global-active-font-color':'rgba(255,255,255,.6)','button-global-font-size':'18px','button-warn-bg-color':'#E64340','button-warn-active-color':'#CE3C39','button-warn-disabled-bg-color':'#EC8B89','button-default-bg-color':'#F8F8F8','button-default-font-color':'#000000','button-default-active-bg-color':'#DEDEDE','button-default-disabled-font-color':'rgba(0,0,0,.3)','button-default-disabled-bg-color':'#F7F7F7','button-default-active-font-color':'rgba(0,0,0,.6)','button-primary-bg-color':'#DF4F45','button-primary-active-bg-color':'#FE8A81','button-primary-disabled-bg-color':'#9ED99D','swipeout-button-primary-bg-color':'@button-primary-bg-color','swipeout-button-warn-bg-color':'@button-warn-bg-color','swipeout-button-default-bg-color':'#c8c7cd','swipeout-content-bg-color':'#FFF','swipeout-button-font-color':'#FFF','cell-body-label-color':'#000','badge-bg-color':'#f74c31','popover-bg-color':'#35495e','popover-font-color':'#fff','popover-border-radius':'3px','popover-border-width':'5px','button-tab-border-width':'1px','button-tab-border-radius':'5px','button-tab-border-color':'@theme-color','button-tab-default-border-color':'@button-tab-border-color','button-tab-active-border-color':'@button-tab-border-color','button-tab-default-background-color':'#fdfdfd','button-tab-active-background-color':'@theme-color','button-tab-active-text-color':'@button-tab-active-font-color','button-tab-default-text-color':'@theme-color','button-tab-height':'30px','button-tab-line-height':'31px','swiper-indicator-active-color':'@theme-color','checklist-icon-active-color':'#09BB07','popup-picker-header-text-color':'@theme-color','popup-picker-header-bg-color':'#fbf9fe','popup-picker-header-font-size':'16px','popup-picker-header-cancel-text-color':'#828282','popup-background-color':'#eee','popup-header-height':'44px','popup-header-bg-color':'#fbf9fe','popup-header-font-size':'16px','popup-header-left-text-color':'#828282','popup-header-right-text-color':'@theme-color','popup-header-title-text-color':'#222','popup-header-left-text-padding':'15px','popup-header-right-text-padding':'15px','form-preview-button-primary-color':'#0BB20C','load-more-line-color':'#E5E5E5','sticky-zindex':'500','group-title-margin-top':'.77em','group-title-margin-bottom':'.3em','toast-content-font-size':'16px','toast-top':'180px','toast-position-top-offset':'10px','toast-position-bottom-offset':'10px','toast-z-index':'5000','icon-success-color':'#09BB07','calendar-arrow-color':'@theme-color','calendar-highlight-color':'#E59313','calendar-selected-bg-color':'@theme-color','calendar-disabled-font-color':'#c0c0c0','calendar-today-font-color':'@theme-color','calendar-date-item-font-size':'16px','search-cancel-font-color':'@theme-color','search-bg-color':'#EFEFF4','search-placeholder-font-color':'#9B9B9B','radio-checked-icon-color':'#09BB07'},'sourceMap':true}!./~/vux-loader/src/style-loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/vux/src/components/flexbox/flexbox.vue 4:14-5388 13:3-17:5 14:22-5396
 @ ./~/vux/src/components/flexbox/flexbox.vue
 @ ./~/vux/src/components/flexbox/index.js
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/popup-picker/index.vue
 @ ./~/vux/src/components/popup-picker/index.vue
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/sysExhib/module/bind.vue
 @ ./src/views/sysExhib/module/bind.vue
 @ ./src/router/sysExhib.js
 @ ./src/views/sysExhib/sysExhib.js
 @ multi ./build/dev-client ./src/views/sysExhib/sysExhib.js

> Listening at http://localhost:8080/views/index.html



 WAIT  Compiling...                                                                                                                                                                                                                                             15:23:26



 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                         15:23:27

 error  in ./src/views/sysExhib/module/bind.vue

Module build failed: 


@theme-color: #DF4F45;@opacity-disabled: 0.5;@actionsheet-label-primary-color: #1AAD19;@actionsheet-label-warn-color: #E64340;@actionsheet-label-default-color: #000;@actionsheet-label-disabled-color: #ccc;@datetime-header-item-font-color: @theme-color;@datetime-header-item-cancel-font-color: #828282;@datetime-header-item-confirm-font-color: @datetime-header-item-font-color;@tabbar-text-active-color: #DF4F45;@tab-text-disabled-color: #ddd;@tab-text-default-color: #666;@tab-text-active-color: @theme-color;@tab-bar-active-color: @theme-color;@dialog-button-text-primary-color: #0BB20C;@dialog-button-text-default-color: #353535;@number-button-font-color: #3cc51f;@number-input-font-color: #666;@number-button-enabled-border-color: #ececec;@number-square-button-enabled-border-color: @number-button-enabled-border-color;@number-round-button-enabled-border-color: @number-button-font-color;@number-button-disabled-border-color: @number-button-enabled-border-color;@number-round-button-disabled-border-color: @number-button-enabled-border-color;@checkbox-icon-color-checked: #09BB07;@check-icon-color-checked: @checkbox-icon-color-checked;@cell-label-color: #000;@cell-font-size: 17px;@cell-tips-font-size: 14px;@cell-default-arrow-color: #C8C8CD;@cell-disabled-arrow-color: #e2e2e2;@cell-default-arrow-border-width: 2px;@cell-default-arrow-width: 6px;@dialog-mask-background: rgba(0, 0, 0, .6);@range-disabled-opacity: @opacity-disabled;@range-bar-default-color: #a9acb1;@range-bar-active-color: @theme-color;@tabbar-index: 100;@header-background-color: #FFF;@header-title-color: #333333;@header-text-color: #333333;@header-arrow-color: #333333;@timeline-item-bg-color: @theme-color;@switch-checked-bg-color: @theme-color;@switch-checked-border-color: @theme-color;@switch-disabled-opacity: 0.6;@button-global-border-radius: 5px;@button-global-font-color: #FFFFFF;@button-global-margin-top: 15px;@button-global-height: 42px;@button-global-disabled-font-color: rgba(255,255,255,.6);@button-global-active-font-color: rgba(255,255,255,.6);@button-global-font-size: 18px;@button-warn-bg-color: #E64340;@button-warn-active-color: #CE3C39;@button-warn-disabled-bg-color: #EC8B89;@button-default-bg-color: #F8F8F8;@button-default-font-color: #000000;@button-default-active-bg-color: #DEDEDE;@button-default-disabled-font-color: rgba(0,0,0,.3);@button-default-disabled-bg-color: #F7F7F7;@button-default-active-font-color: rgba(0,0,0,.6);@button-primary-bg-color: #DF4F45;@button-primary-active-bg-color: #FE8A81;@button-primary-disabled-bg-color: #9ED99D;@swipeout-button-primary-bg-color: @button-primary-bg-color;@swipeout-button-warn-bg-color: @button-warn-bg-color;@swipeout-button-default-bg-color: #c8c7cd;@swipeout-content-bg-color: #FFF;@swipeout-button-font-color: #FFF;@cell-body-label-color: #000;@badge-bg-color: #f74c31;@popover-bg-color: #35495e;@popover-font-color: #fff;@popover-border-radius: 3px;@popover-border-width: 5px;@button-tab-border-width: 1px;@button-tab-border-radius: 5px;@button-tab-border-color: @theme-color;@button-tab-default-border-color: @button-tab-border-color;@button-tab-active-border-color: @button-tab-border-color;@button-tab-default-background-color: #fdfdfd;@button-tab-active-background-color: @theme-color;@button-tab-active-text-color: @button-tab-active-font-color;@button-tab-default-text-color: @theme-color;@button-tab-height: 30px;@button-tab-line-height: 31px;@swiper-indicator-active-color: @theme-color;@checklist-icon-active-color: #09BB07;@popup-picker-header-text-color: @theme-color;@popup-picker-header-bg-color: #fbf9fe;@popup-picker-header-font-size: 16px;@popup-picker-header-cancel-text-color: #828282;@popup-background-color: #eee;@popup-header-height: 44px;@popup-header-bg-color: #fbf9fe;@popup-header-font-size: 16px;@popup-header-left-text-color: #828282;@popup-header-right-text-color: @theme-color;@popup-header-title-text-color: #222;@popup-header-left-text-padding: 15px;@popup-header-right-text-padding: 15px;@form-preview-button-primary-color: #0BB20C;@load-more-line-color: #E5E5E5;@sticky-zindex: 500;@group-title-margin-top: .77em;@group-title-margin-bottom: .3em;@toast-content-font-size: 16px;@toast-top: 180px;@toast-position-top-offset: 10px;@toast-position-bottom-offset: 10px;@toast-z-index: 5000;@icon-success-color: #09BB07;@calendar-arrow-color: @theme-color;@calendar-highlight-color: #E59313;@calendar-selected-bg-color: @theme-color;@calendar-disabled-font-color: #c0c0c0;@calendar-today-font-color: @theme-color;@calendar-date-item-font-size: 16px;@search-cancel-font-color: @theme-color;@search-bg-color: #EFEFF4;@search-placeholder-font-color: #9B9B9B;@radio-checked-icon-color: #09BB07;
                                                                                                                                                                                                    `
