### ISSUE TITLE
无法正常引入json文件

### ISSUE THREAD

**Issue by pecasha** [airyland/vux#1703]
我设置了别名vux$指向vux的datas目录
`alias : {
            'vue$' : 'vue/dist/vue.esm.js',
            'vux$' : 'vux/src/datas',
            'vux@' : 'vux/src/components',
            '@' : resolve('src/components'),
            '%' : resolve('src/pages'),
            '#' : resolve('src/controllers'),
            '#pages' : resolve('src/controllers/pages'),
            '#components' : resolve('src/controllers/components'),
            '*' : resolve('src/styles'),
            '*pages' : resolve('src/styles/pages'),
            '*components' : resolve('src/styles/components')
        }`
然后在页面中单独引入china_address_v3.json
`import ChinaAddressV3Data from "vux$/china_address_v3.json";`

运行之后报错，我用相同的方式引入vux组件是没有问题
**ERROR  Failed to compile with 1 errors16:18:26

This dependency was not found:

vux$/china_address_v3.json in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./src/controllers/pages/instalments/bank-card-bind.js

To install it, you can run: npm install --save vux$/china_address_v3.json**

**Comment by airyland** [comment]
请不要重复发 issue。
