### ISSUE TITLE
实现按需引入组件

### ISSUE THREAD

**Issue by xiadd** [airyland/vux#171]
### Version
0.0116

### Android or iOS, which browser?
chrome
### Your Codes 

``` js
//import { InlineCalendar, Range, Group, Cell, XInput, XButton, XTextarea, Toast,Panel } from 'vux'
  import InlineCalendar from 'vux/components/inline-calendar'
  import Range from 'vux/components/range'
  import Group from 'vux/components/group'
  import Cell from 'vux/components/cell'
  import XInput from 'vux/components/x-input'
  import XButton from 'vux/components/x-button'
  import XTextarea from 'vux/components/x-textarea'
  import Toast from 'vux/components/toast'
  import Panel from 'vux/components/panel'
```

### Expected behavior and actual behavior.
可以看下下面的比较，两种不同的引入f方式，下面不是完全引入的，注释的部分是整个引入的,大小差了很多，加载时有点慢，我记得之前用react组件的时候没出现这种情况，有打算解决吗
![image](https://cloud.githubusercontent.com/assets/8351437/15092055/95e409cc-1490-11e6-9adc-6c2d3d8391b4.png)

**Comment by airyland** [comment]
现在README里已经没有 import from vux 的写法了，这个相当于把整个vux库加载了。现在就只是推荐单个引入。不知道你说的解决是解决什么？

**Comment by xiadd** [comment]
@airyland 好的，多谢
