### ISSUE TITLE
iphone7 中selector 的使用bug

### ISSUE THREAD

**Issue by GemVinci** [airyland/vux#1711]
结构如下
`<div class="cell_select">
						<img slot="icon" style="width: .6rem;margin-right: .2rem;" src="../assets/img/tu1.png">
						<selector title="角色" :options="role" v-model="RoleID"></selector>
					</div>`
`<div class='cell_select'>
						<img slot="icon" style="width: .6rem;margin-right: .2rem;" src="../assets/img/tu10.png">
						<selector title="审批状态" :options="list" v-model='SacStatus '></selector>
					</div>`
在安卓以及iphone7以外都没有问题，但是iphone7中轻触角色selector 
会跳到审批状态selector ，如果点击就不会，（轻触指的是很快的点击一下）

**Comment by GemVinci** [comment]
`<div class="cell_title">
						<cell title="其他">
							<img slot="icon" style="width: .06rem;margin-right: .2rem;" src="../assets/img/tu0.png">
						</cell>
					</div>
					<div class="cell_select">
						<img slot="icon" style="width: .6rem;margin-right: .2rem;" src="../assets/img/tu1.png">
						<selector title="角色" :options="role" v-model="RoleID"></selector>
					</div>
					<div class='cell_select cell_time'  style="position: relative;">
						<img slot="icon" style="width: .6rem;margin-right: .2rem;" src="../assets/img/tu2.png">
						<span style="font-size: .28rem;display: inline-block;vertical-align: text-bottom;width:2rem">时间</span>
						<datetime title='' class="no_arrow" v-model="StartDate" ></datetime>
						<span class="wave">~</span>
						<datetime title='' v-model="EndDate" ></datetime>
					</div>
					<div class='cell_select'>
						<img slot="icon" style="width: .6rem;margin-right: .2rem;" src="../assets/img/tu10.png">
						<selector title="审批状态" :options="list" v-model='SacStatus '></selector>
					</div>
					<div class="vinput">
						<img slot="icon" style="width: .6rem;margin-right: .2rem;" src="../assets/img/tu9.png">
						<x-input title="关键字" placeholder="带看人姓名/房间地址" v-model='KeyWord '></x-input>
					</div>`

**Comment by GemVinci** [comment]
发现问题了，是fastclick的问题

**Comment by masktim** [comment]
遇到同样的问题，请问是怎么解决的呢？

**Comment by masktim** [comment]
@GemVinci

**Comment by GemVinci** [comment]
@masktim  你把fastclick取消了

**Comment by masktim** [comment]
@GemVinci 只是取消select的fastclick? 取消后用户是不是要长按select控件超过150ms才行？？

**Comment by GemVinci** [comment]
@masktim  取消了，也不是长按吧，单点就行了，就是有延迟

**Comment by masktim** [comment]
怎么取消呢？对select 加class = needsclick?

**Comment by GemVinci** [comment]
main.js  中有一句 FastClick.attach(document.body)   你直接删掉

**Comment by masktim** [comment]
晕。
