### ISSUE TITLE
新建的项目，Vux版本与npm上面的版本不一致

### ISSUE THREAD

**Issue by laznrbfe** [airyland/vux#1713]
### 我的创建步骤(参照[文档](https://vux.li/#/?id=%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8))
```
vue init airyland/vux2 myproject
cd myproject
yarn install
```

### 版本对比
* [npm](https://www.npmjs.com/package/vux)上面显示最新版本:`2.5.3`
* `package.json`上`"vuex": "^2.1.1"`

### 开发环境
* node: v7.6.0
* vue-cli: 2.8.2

**Comment by wg5945** [comment]
vuex和vux不是一家

**Comment by gam80** [comment]
不管装的是哪个，明白“^”的意思就可以。eg. ^2.1.1 := >=2.1.1-0 <3.0.0-0

**Comment by laznrbfe** [comment]
@wg5945 复制错了。是`"vux": "^2.2.1",`
@gam80 谢谢提醒。
