### ISSUE TITLE
tabbar 建议添加 @tabchange 这类事件钩子

### ISSUE THREAD

**Issue by Astroinist** [airyland/vux#1715]
目前tabbar 从api上看只在 TabbarItem上提供了on-item-click，这个样有两个问题：
1是无法统一的在一个地方做tabchange的事件处理（必须每个TabbarItem 分别绑定handler）
2是此事件必须是在item被click时才会触发（tabbar的index改变时也不会触发该事件）

在tabbar 组件上添加如：on-tabChange(from,to,...)这样的事件钩子，可以解决上面两个问题，同时也增加了组件的灵活性

**Comment by wg5945** [comment]
tabbar是支持v-model的形式的，文档上有写
```
<tabbar v-model="tab">
</tabbar>
```
你可以通过监听绑定的model值来实现
