### ISSUE TITLE
Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data optio

### ISSUE THREAD

**Issue by liuhuanhui** [airyland/vux#1717]
有些组件使用之后，右键在审查元素的时候弹出错误：
[Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <XImg> at node_modules\_vux@2.5.2@vux\src\components\x-img\index.vue
       <FlexboxItem> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox-item.vue
         <Flexbox> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox.vue
           <Forhere> at src\pages\shop\forhere.vue
             <Shop> at src\pages\shop\Shop.vue
               <App> at src\App.vue
                 <Root>

**Comment by liuhuanhui** [comment]
比如swiper 和ximg

**Comment by liuhuanhui** [comment]
我发现了 使用html5的标签会有问题 比如 header  or footer

**Comment by airyland** [comment]
看不出和组件有什么关系，组件并没有使用 toJSON 这个非 js 原生方法。

**Comment by zhuichen** [comment]
@liuhuanhui 我也遇到这个问题，你是怎么解决的？

**Comment by liuhuanhui** [comment]
@zhuichen wepack版本问题
