### ISSUE TITLE
如何实现返回时，还显示整个网页

### ISSUE THREAD

**Issue by aq82** [airyland/vux#172]
我现在有个场景：
1、刚刚进入的一个查询页面（search.html）中，默认是没有内容；
2、当执行点击“查询”时，则执行“searchData”方法，并加载内容到页面中；
3、选择其中一条数据并进入页面（zhutiye.html）后，这时候，点击“返回”按键到查询页面（search.html）
4、这时候，查询页面（search.html）则没有显示刚才查询的结果。

要如何实现，返回时还能看到原先查询的结果？

完整的页面代码如下 ：
<!DOCTYPE html>
<html lang="zh-cmn-Hans">

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
		<title>WeUI</title>
		<link rel="stylesheet" href="style/vux.css" />
		<link rel="stylesheet" href="style/Style.css" />
	</head>

	<body ontouchstart>
		<div id="app">
			<div>
				<div style="position: fixed; width: 100%; top:0;z-index: 99;">
				<div class="weui_search_bar weui_search_focusing" id="search_bar">
					<form class="weui_search_outer">
						<div class="vux-search-mask" style="display: none;"></div>
						<div class="weui_search_inner"> <i class="weui_icon_search"></i>
							<input type="text" class="weui_search_input" id="search_input" autocomplete="off" required="" placeholder="Search">
							<a href="javascript:" class="weui_icon_clear" id="search_clear"></a>
						</div>
						<label for="search_input" class="weui_search_text" id="search_text"> <i class="weui_icon_search"></i> <span>Search</span> </label>
					</form>
					<a @click="searchData" class="weui_search_cancel">确定</a> </div>
				<div class="vux-tab">
					<div class="vux-tab-item vux-tab-selected" data-index="0" style="border: none; color: rgb(4, 190, 2);"> 主题 </div>
					<div class="vux-tab-item" data-index="1" style="border: none; color: rgb(102, 102, 102);"> 文章 </div>
					<div class="vux-tab-item" data-index="2" style="border: none; color: rgb(102, 102, 102);"> 用户 </div>
					<div class="vux-tab-item" data-index="3" style="border: none; color: rgb(102, 102, 102);"> 我的 </div>
					<div class="vux-tab-ink-bar vux-tab-ink-bar-transition-forward" style="display: block; height: 2px; left: 0%; right: 75%; background-color: rgb(4, 190, 2);"></div>
				</div>
				</div>
				
				<div class="weui_cells weui_cells_access search_show" id="search_show" style="margin: 80px 0px 10px 0px">
					<div v-for="item in items" class="weui_cell search_result" @click="gotoURL(item.subjectID)">

						<div>
							<img style="border-radius:10px;width: 50px;height: 50px;" src="https://o3e85j0cv.qnssl.com/tulips-1083572__340.jpg">
						</div>
						<div style="line-height: 18px;">
							<span class="zhuti_result_spanText1">{{item.subjectName}}</span>
							<br>
							<span class="zhuti_result_spanText2">123文章</span>

						</div>
						<div @click="diyue(item.subjectID)"  v-bind:class="{ 'search_nodingyue': item.dyStatus==0, 'search_yidingyue': item.dyStatus==1 }" ></div>
					</div>
				
				<div @click="loadData" class="weui_panel_ft"  style=" text-align:center;width: 100%;border-top:1px solid #e5e5e5">
					查看更多>>>
				</div>	
				</div>
				
			<div id="loadingToast" class="weui_loading_toast" style="display:none;">
			<div class="weui_mask_transparent"></div>
			<div class="weui_toast">
				<div class="weui_loading">
					<div class="weui_loading_leaf weui_loading_leaf_0"></div>
					<div class="weui_loading_leaf weui_loading_leaf_1"></div>
					<div class="weui_loading_leaf weui_loading_leaf_2"></div>
					<div class="weui_loading_leaf weui_loading_leaf_3"></div>
					<div class="weui_loading_leaf weui_loading_leaf_4"></div>
					<div class="weui_loading_leaf weui_loading_leaf_5"></div>
					<div class="weui_loading_leaf weui_loading_leaf_6"></div>
					<div class="weui_loading_leaf weui_loading_leaf_7"></div>
					<div class="weui_loading_leaf weui_loading_leaf_8"></div>
					<div class="weui_loading_leaf weui_loading_leaf_9"></div>
					<div class="weui_loading_leaf weui_loading_leaf_10"></div>
					<div class="weui_loading_leaf weui_loading_leaf_11"></div>
				</div>
				<p class="weui_toast_content">加载中...........</p>
			</div>
			</div>
			</div>
		</div>
		<script type="text/javascript" src="js/vue.js"></script>
		<script type="text/javascript" src='js/vue-resource.min.js'></script>
		<script>
		var items = []
		document.getElementById('search_clear').addEventListener('click', function() {
			document.getElementById("search_input").value="";
		}, false);
		new Vue({
			el: '#app',
			ready: function() {
				//alert("ready");
				//this.loadData();
			},
			methods: {
			searchData:function()
			{
				document.getElementById("loadingToast").style.display="";
	        	this.$http.get('test/searchzhuti.json', function(data) {
					this.$set('items', data);
					
				}).success(function() {
					document.getElementById("loadingToast").style.display="none";
				})
				.error(function(data, status, request) {
					//console.log('fail' + status + "," + request);
					document.getElementById("loadingToast").style.display="none";
				}) 
			},
			gotoURL:function(subjectID){
				//alert(subjectID);
				window.location.href='zhutiye.html?subjectID='+subjectID;
			},
			diyue:function(subjectID){
				alert("我要订阅"+subjectID);
			},
	        loadData: function () {
	        	document.getElementById("loadingToast").style.display="";
	        	this.$http.get('test/searchzhuti.json', function(data) {
					//this.$set('items', data);
					//alert("aaa");
					for (var i=0;i<=data.length-1;i++) { 
						//this.items.unshift(data);
						//alert(data.length);
						this.items.push(data[i]);
					}
				}).success(function() {
					document.getElementById("loadingToast").style.display="none";
				})
				.error(function(data, status, request) {
					//console.log('fail' + status + "," + request);
					document.getElementById("loadingToast").style.display="none";
				})
	        	}
	      	},
			data: {
				items: items
			},
		});
	</script>
	</body>

</html>

**Comment by varHarrie** [comment]
1、vue-router + keep-alive
2、pass url param, search again when you enter the page

**Comment by airyland** [comment]
这是vue-router的使用问题了，相关的一些方法楼上已经给出了，而且代码并没有使用vux，不适合在这里提问，建议到vue-router或者vue社区提问。
