### ISSUE TITLE
大佬，好像npm 里面的包不是最新版的

### ISSUE THREAD

**Issue by rainwalkerhu** [airyland/vux#1725]
github上的checklist组件代码和npm2.5.3版本不一致

**Comment by rainwalkerhu** [comment]
github上的checklist组件代码和npm2.5.3版本不一致

**Comment by zwldev** [comment]
今天是不是更新了什么东西啊，同样的代码以前一直没问题，今天一直报$t的错

**Comment by airyland** [comment]
@zwldev 
有问题请先检查自己做了什么操作。

@rainwalkerhu 
请说明哪里不同。

**Comment by rainwalkerhu** [comment]
![277](https://user-images.githubusercontent.com/17560391/28507489-bfd9dcac-7065-11e7-92dd-9301de3861c6.png)
如图所示的插槽npm包里面的代码是没有的

**Comment by airyland** [comment]
try v2.5.4

**Comment by rainwalkerhu** [comment]
好的，感谢大佬

**Comment by rainwalkerhu** [comment]
另外vux好像并没有针对300ms延迟做特殊处理，大佬有考虑过吗？我这边本打算用fastclick打个补丁，但是感觉这玩意儿还是太大，也不靠谱，最后就自己搞了个tap指令，但是对于vux就没有什么好办法优化了
