### ISSUE TITLE
关于XInput组件的一点建议

### ISSUE THREAD

**Issue by showbestriven** [airyland/vux#1727]
`<x-input title="姓名：" v-model="value" placeholder="请输入"></x-input>`
`<x-input title="手机号码：" v-model="value" placeholder="请输入"></x-input>`

比如上述情况， 有时候为了美观，会让 ‘姓名’ 和 '手机号码' 等宽,填充空格进去
`<x-input title="姓&ensp;&ensp;&ensp;&ensp;名：" v-model="value" placeholder="请输入"></x-input>`

但是@airyland，您title的宽度是根据字数设置的  字数 + 1 em的宽度。 有点不合理   应该过滤掉  `&ensp; ` 
`&nbsp;` `&gt;` `&lt; `等等一些HTML特殊字符

**Comment by airyland** [comment]
可以在 group 上设置 label-align 为 justify。
