### ISSUE TITLE
Alert组件的弹出位置

### ISSUE THREAD

**Issue by git9527** [airyland/vux#1729]
如下图所示，当整个页面很长时，点了投票之后的Alert总是出现在上方不可见区域，可以设置Alert的出现位置么？
![image](https://user-images.githubusercontent.com/4514520/28496080-a24f70c4-6f94-11e7-8c4a-73149dda5e08.png)

**Comment by airyland** [comment]
alert 默认就是 fixed 定位，不可能出现在不可见区域。提供可重现 demo 代码重开当前 issue。
