### ISSUE TITLE
drawer控件的文档不全

### ISSUE THREAD

**Issue by mike8625** [airyland/vux#1731]
https://vux.li/#/zh-CN/demos/drawer
没有代码示例,貌似是没有写全.最好写个简单的,说明应该详细点.比如draw应该是个容器,包在外面,然后里面放其他的元素

**Comment by mike8625** [comment]
顺便问一句有没有什么qq群之类的,比如我想问个类似 "能不能在某个全局文件中import一次xheader 就能在所有组件都可以使用" 的问题在哪提问比较好

**Comment by airyland** [comment]
示例就在 app.vue 里了，因为要把 router-view 放在 drawer 组件里。
没有 qq 群。你这个问题在 main.js 里全局注册就好了，是 vue 问题不是 vux 的使用问题。

**Comment by stt04521** [comment]
drawer 在app里面 对第一次 使用 vux的人 感觉不是很友好，要脱离其他的东西 单独实现这个功能，很费劲

**Comment by airyland** [comment]
@stt04521 文档有注明已经相当友好了。这不是 vux 的问题了，使用过 vue-router 的人都知道 router-view 是什么。
