### ISSUE TITLE
Range组件在Popup组件中的问题

### ISSUE THREAD

**Issue by vFire** [airyland/vux#1732]
默认Popup没有开启，之后手动触发弹开Popup，range组件在按住拖动的时候提示出错：
`Invalid prop: type check failed for prop "value". Expected Number, got String.`
测试了一下，放到popup组件之外，显示正常。

**Comment by vFire** [comment]
刚刚查到已有其他人发了这个issue，但是貌似并没有解决就关闭了，我就开着这个，push一下作者了~

**Comment by wg5945** [comment]
在 #1599 里面我已经说过了，类似这样吧

```
   <div v-transfer-dom>
      <popup v-model="show13">
        <cell title="Default" :inline-desc="'value: '+data1" primary="content">
          <range v-model="data1" v-if="show13"></range>
        </cell>
      </popup>
    </div>
```

就算要修改源码的话，也会是提供一个render方法，然后在popup 显示的时候手动调用，我觉得也差不多
