### ISSUE TITLE
drawer点击mask时候关闭draw的属性没有写在文档里面

### ISSUE THREAD

**Issue by mike8625** [airyland/vux#1733]
点击mask无法关闭drawer. 看了源码才发现,有个点击事件里面emit了一个 update:show, 加上以后点击mask才能关闭,希望在文档里面加上这个说明.

**Comment by airyland** [comment]
点击 mask 是可以关闭 drawer 的，你看到的是 vue@2.3.3 引入的 .sync 的语法糖，请检查 vue 版本。

**Comment by mike8625** [comment]
https://github.com/airyland/vux/blob/v2/src/components/drawer/index.vue
这里面也是这么写的啊 这个应该是最新的吧,第9行和第63行,里面也有update:show.  这个和vue没什么关系吧, 这是你们代码里面的东西,子组件emit一个东西,父组件不需要处理自己就能关上mask?

**Comment by airyland** [comment]
我上面说了2.3 版本 .sync 双向绑定就是这个作用，不需要手动处理。你先告诉你到底用的是哪个版本的 vue？

**Comment by mike8625** [comment]
我是2.4.1,换成2.3就行了?
