### ISSUE TITLE
i18n使用中的一些疑惑，希望作者有时间帮忙解答，谢谢。

### ISSUE THREAD

**Issue by Jiiiiiin** [airyland/vux#1735]
请问：
插件配置中的【extractToFiles】

  {
      name: 'i18n',
      vuxStaticReplace: false,
      staticReplace: false,
      extractToFiles: 'src/locales/components.yml',
      localeList: ['en', 'zh-CN']
    },
和【语言文件要手动合并引入】：

```js
//... 省略一些配置
const componentsLocales = require('json-loader!yaml-loader!@/locales/global_locales.yml')

const finalLocales = {
  'en': Object.assign({}, componentsLocales['en']),
  'zh-CN': Object.assign({}, componentsLocales['zh-CN'])
}

for (let i in finalLocales) {
  Vue.i18n.add(i, finalLocales[i])
}
const nowLocale = Vue.locale.get()
if (/zh/.test(nowLocale)) {
  Vue.i18n.set('zh-CN')
} else {
  Vue.i18n.set('en')
}
//... 省略一些配置
```

两者之间的联系是什么？

我测试了一下，如果没有【Vue.i18n.add(i, finalLocales[i])】这一行，那么.vue中的$t就不起作用，尽管我的【...!@/locales/global_locales.yml'】文件为空文件，因为我想目前的需求，仅仅需要在业务组件里面直接使用：

```vue
<template>
  <div id="phone-Home">
    <grid :rows="4">
      <grid-item-any :label="$t('I want to purchase')" link="/Phone/Private/Interbus/PurchaseAGreement">
        <i class="iconfont yn-gouhui" slot="content"></i>
      </grid-item-any>
</template>

<i18n>
  I want to purchase:
    zh-CN: 我要购汇
</i18n>
```
的方式去使用；

以外，我测试了一下：

```js
<i18n>
  I want to purchase:
    zh-CN: 我要购汇
    en: xxxx
</i18n>
```

上面的i18n block中的【    en: xxxx】，尽管我mian.js中强制设置了【  Vue.i18n.set('en')】还是不生效，而是直接显示了【:label="$t('I want to purchase')" 】，$t函数中的参数原文。

麻烦作者有时间帮忙解惑一下，十分感谢！

**Comment by airyland** [comment]
Vue.i18n.add 这和 vux 没有什么关系了，这是第三方插件 https://github.com/dkfbasel/vuex-i18n，按照文件，你得把语言文件载入才能实现语言切换吧。

你不需要和 demo 一样有 global_locales, 这仅仅是为了举例可以实现覆盖默认的 vux 组件默认语言配置而已。

最后 i18n block 是 yml 格式，意味着你这样写应该是错误的，不要有缩进。参照 demo 里的格式。

``` html
<i18n>
I want to purchase:
  zh-CN: 我要购汇
  en: xxxx
</i18n>
```

**Comment by Jiiiiiin** [comment]
@airyland 谢谢
