### ISSUE TITLE
vuxLoader的一个小问题，还望指导一下

### ISSUE THREAD

**Issue by zj0715zh** [airyland/vux#1738]
![image](https://user-images.githubusercontent.com/8474484/28518325-10418f30-709a-11e7-8414-bd14585b9346.png)
使用最新版的vuxLoader之后，页面一直报template or render function not defined这个错误，依赖包都已经升级，webpack用的3.1版本

**Comment by zj0715zh** [comment]
![image](https://user-images.githubusercontent.com/8474484/28518422-66043206-709a-11e7-90cc-ee3657b8ff2a.png)
这个已经配置

**Comment by airyland** [comment]
提供的信息过少，无法判断问题。请建一个 repo 来重现。
