### ISSUE TITLE
panel 组件里图片支持相对路径么，官网示例的是绝对路径，webpack做了图片打包，用panel组件相对路径没有被编译过来，只是前面加了域名，项目中img标签下是可以编译

### ISSUE THREAD

**Issue by guiter** [airyland/vux#1740]
{
                        url: 'javascript:',
                        img: '../../assets/images/icon/default-homebn.jpg',
                    }, {
                        url: 'javascript:',
                        img: 'https://static.vux.li/demo/3.jpg',
                    }

**Comment by airyland** [comment]
作为变量传递不支持相对路径的编译。但是你可以先 require 再传进列表。

``` js
const homeBtn = require('../../assets/images/icon/default-homebn.jpg')

{
  url: 'javascript:',
  img: homeBtn
}, {
  url: 'javascript:',
  img: 'https://static.vux.li/demo/3.jpg',
}
```

**Comment by guiter** [comment]
已解决，非常感谢
