### ISSUE TITLE
swipeout$t问题

### ISSUE THREAD

**Issue by sasaluo** [airyland/vux#1741]
最近有到左右滑动删除的需求，在网上找到vux,安装官网上安装之后，配置OK了，报如下错：vue.esm.js?65d7:459 [Vue warn]: Error in render function: "TypeError: _vm.$t is not a function"

官网上说“ 如果你遇到 $t 报错问题，请不要开 issue，升级 vux-loader >= 1.0.58”，我的vux-loader版本是1.1.3，求指点

**Comment by wg5945** [comment]
如果不需要多语言，直接删除$t即可

如果需要使用，请阅读使用文档 https://vux.li/#/zh-CN/vux-loader?id=i18n

**Comment by sasaluo** [comment]
many thanks
