### ISSUE TITLE
利用vue-init airyland/vux2 命令建立的项目 热更新报错

### ISSUE THREAD

**Issue by JL-Code** [airyland/vux#1743]
利用vue-init airyland/vux2 命令建立的项目 热更新报错？
![image](https://user-images.githubusercontent.com/14163944/28559505-6167a642-7149-11e7-849d-bf4da9706eef.png) @airyland

**Comment by wg5945** [comment]
8080端口是否被占用？

**Comment by airyland** [comment]
麻烦建个 repo 来重现。

**Comment by JL-Code** [comment]
[](https://github.com/JL-Code/vux_hmr_error ) 利用vue-init airyland/vux2 命令建立的项目 热更新报错

**Comment by JL-Code** [comment]
利用vue-init airyland/vux2 命令建立的项目 热更新报错   https://github.com/JL-Code/vux_hmr_error

**Comment by airyland** [comment]
在 win 和 Mac 均无法重现。

``` bash
vux@2.5.6, vux-loader@1.1.4, webpack@2.7.0, node@7.7
```

**Comment by JL-Code** [comment]
这就尴尬了，但是我本地用这个真的就报错了。。难道是我开了vpn？本机windows   node8.0 npm5.0 其他 webpack全局3.0 项目2.2.1  vux vux-loader和你一致
