### ISSUE TITLE
想请教下 confirm 里的input 我想输入完之后点击确认按钮  就清空 需要怎么做呢 ？

### ISSUE THREAD

**Issue by hackerslizc** [airyland/vux#1746]
想请教下 confirm 里的input，我想输入完之后，点击确认按钮就清空Input，但是不需要关闭confirm，需要怎么做呢 ？我在API 里也没看到有相关设置，请指出一下呗。

**Comment by graysheeep** [comment]
什么场景需要确认清空input但是不关闭？

**Comment by wg5945** [comment]
这种复杂的场景建议使用x-dialog自行实现，confirm这种比较基础的组件不可能满足所有复杂的业务场景

**Comment by airyland** [comment]
因为 confirm 上已经有实现了可以输入，所以还是可以实现对输入值的控制，貌似可以实现直接用 .sync 来绑定？

**Comment by tong3jie** [comment]
直接把value置为空不可用吗？

**Comment by hackerslizc** [comment]
解决办法  并没有用 prompt  这样方式， 是弹窗之后  内容我插入了一个 input 然后每次点击 按钮 设置完值之后就清空  input  继续下一个赋值。
解释下业务：是因为有列表 我需要对列表内的每一项设置数值，但是每次都是( 点击 -> 弹出键盘 -> 输入 -> 点击键盘完成 -> 点击确定关闭弹窗） 这个流程太长了。 所以优化了下，改为了（ 点击 -> 弹窗 -> 输入 -> 点击下一个 切换 -> 输入 -> 点击下一个····  -> 确定【关闭弹窗】）完成业务
