### ISSUE TITLE
vux.Drawer组件使用$emit错误报告

### ISSUE THREAD

**Issue by webignorant** [airyland/vux#1747]
```
[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers."

Error: [vuex] Do not mutate vuex store state outside mutation handlers.
```
我看了drawer的源码，确实通过$emit通知上层修改值。

能否识别如果使用Vuex.store，则走提交mutation的路子呢？

**Comment by webignorant** [comment]
当前由于x-header放置在view-router内，所以需要使用vuex来存储显示状态。

**Comment by airyland** [comment]
识别 vuex 这个应该做不到也不会在组件里这样处理。不直接绑定 state，而是绑定另一变量通过监听变量变化来修改呢？

https://vuex.vuejs.org/zh-cn/forms.html

**Comment by webignorant** [comment]
@airyland 正解，虽然使用watch就丢失了vuex的特性，但目前可以先这样。
后续我fork尝试改进一下。
麻烦close issues

**Comment by airyland** [comment]
ok，其实你也可以关闭 issue 的。
