### ISSUE TITLE
vux2.3.1+vue2.2.6+webpack2.7.0报错，跪求指导

### ISSUE THREAD

**Issue by zj0715zh** [airyland/vux#1748]
![image](https://user-images.githubusercontent.com/8474484/28600832-35312122-71e7-11e7-8db4-c521fe629952.png)
这是我的packge.json文件，npn run dev时报
![image](https://user-images.githubusercontent.com/8474484/28600885-813574ce-71e7-11e7-881c-97df45df7ede.png)
是不是现在vux不支持webpack2.X版本

**Comment by airyland** [comment]
默认支持 webpack2 的，麻烦建一个 repo 来重现。
