### ISSUE TITLE
datetime的min-hour 能不能做到大于当前日期不做控制，等于当前日期时min-hour为当前时间的小时数

### ISSUE THREAD

**Issue by esioncao** [airyland/vux#1749]
datetime的min-hour 能不能做到大于当前日期不做控制，等于当前日期时min-hour为当前时间的小时数

**Comment by airyland** [comment]
说明下场景。

**Comment by esioncao** [comment]
@airyland 比如说我现在要去订酒店，小于今天的小时数应该不让选的，但是我滑到明天时所有的小时数都应该可以选，但是现在对min-hour做限制就控制了所有日期hour的选择，但是在on-change去对min-hour去做动态改变，已经来不及了

**Comment by airyland** [comment]
因为 hour 这一列不能设为空，也就是说要实现的话这个逻辑只适用于开始时间为当天的情况，日期为当天时小时从 `max(当前小时, min-hour)` 开始，其他情况为 `min-hour ~ 23`

**Comment by esioncao** [comment]
@airyland 如果实现这种方式 对之前的组件有没有影响？看能不能设一个开关 默认还是取min-hour， 如果开关打开则日期为当天小时从max（当前小时，min-hour）开始

**Comment by esioncao** [comment]
@airyland 这种场景还是很多的 预订类的应用应该都有这种需要

**Comment by airyland** [comment]
如果不做开关，而是指供小时生成器呢，每次日期变化时使用该函数计算小时列表，这样虽然使用略麻烦一点点，但是会更灵活，类似如下：

``` html
:compute-hours-function="getHours"
```

``` js
data () {
  return {
    getHours (date, isToday, generateRange) {
      if (isToday) {
        const currentHour = new Date().getHours()
        return generateRange(currentHour, 23)
      } else {
        return generateRange(0, 23)
      }
    }
  }
}
```

**Comment by esioncao** [comment]
@airyland 嗯 这种方式就灵活很多，可以满足不同的场景，期待大牛的更新

**Comment by airyland** [comment]
在下版本发布前，可用 vux@beta 测试。

**Comment by esioncao** [comment]
@airyland ok

**Comment by vviolin** [comment]
分钟的也能添加这种功能不？
