### ISSUE TITLE
android中使用scroller滑动非常卡顿

### ISSUE THREAD

**Issue by li-yinan** [airyland/vux#175]
### ANDROID

``` html
<gk-scroller v-ref:scroller lock-x scrollbar-y use-pullup @pullup:loading="load" :pullup-config="pullupConfig" :autoRefresh="true" class="gk-scroller”>

<div>

一个很长的列表

</div>

 </gk-scroller>
```

scroller组件在android的微信和手机百度内滚动十分卡顿，请问有没有办法解决？我希望能够使用上拉加载数据的功能，非常感谢

**Comment by airyland** [comment]
很长的列表有多少数据，手机型号是？

**Comment by li-yinan** [comment]
其实长度很短，只有十几项，但是每一项是一个vue的组件，里面类似一个贴吧的帖子，结构不复杂，每一项高度大概为100px。
手机用的是锤子坚果，我用米note测试就非常流畅，我怀疑是我的手机比较低端，transform没有使用硬件加速导致的，请问有什么解决办法在这样的手机上依然保持流畅吗？

**Comment by airyland** [comment]
没用过锤子，我在两年前用的小米2A上依然足够流畅。如果是硬件性能差的问题，我觉得可能很难解决，如果只有坚果这样卡，可能不会花时间去调试，因为似乎用坚果的用户很少量。。

**Comment by li-yinan** [comment]
好吧，我再找找主流机型测试一下，如果大部分都ok我觉得也没问题。非常感谢您高效的回复。
