### ISSUE TITLE
求助 view-box 如何使用 scrollTo 滑动到指定的位置显示

### ISSUE THREAD

**Issue by jjjachyty** [airyland/vux#1750]

**Comment by airyland** [comment]
设定 ref，调用 ref 的 scrollTo 函数。

**Comment by jjjachyty** [comment]
@airyland  后面怎么传值呢？this.$refs.viewBox.scrollTo( ？？？？)

**Comment by airyland** [comment]
this.$refs.viewBox.scrollTo(100)

**Comment by jjjachyty** [comment]
@airyland 测试了 好像不生效 查看viewBoxBody的scrollTop 为0

**Comment by airyland** [comment]
上 repo 吧，信息量太少，我都不知道你是否按照 100% 布局来使用 view-box 了。

**Comment by jjjachyty** [comment]
@airyland 高度100%的问题 好了 Thanks
