### ISSUE TITLE
 popup component 的bug

### ISSUE THREAD

**Issue by hivandu** [airyland/vux#1751]
iOS上开启`-webkit-overflow-scrolling: touch`之后，popup组件的层级就不对了。mask遮罩层挡在了弹出层之前，使得弹出层无法点击。

![error](http://doolink.qiniudn.com/1501053874.png)

**Comment by Hideer** [comment]
是这个原因么

**Comment by Hideer** [comment]
@hivandu  经过测试确实是这个属性的原因，麻烦请问你最后的解决方案是什么呢
