### ISSUE TITLE
npm run dev的时候报错，cannot find module 'node_modules\vux\package.json'

### ISSUE THREAD

**Issue by xsfirst** [airyland/vux#1753]
npm install的时候没有报错，但是在npm run dev的时候出现下面的错误，请问下是哪里错了？

`ERROR in ./src/main.js
Module build failed: Error: Cannot find module 'D:\work\msp++++++++++++++++\test\src\node_modules\vux\package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.module.exports (D:\work\msp++++++++++++++++\test\node_modules\vux-loader\src\js-loader.js:51:22)
 @ multi ./build/hot-reload ./src/main.js`

package.json里的版本是"vux": "^2.5.4"，"vux-loader": "^1.1.4",

**Comment by airyland** [comment]
你在 src 下运行 run dev?

**Comment by xsfirst** [comment]
是在D:\work\msp++++++++++++++++\test 目录下运行的npm run dev

**Comment by xsfirst** [comment]
之前安装运行的时候都是对的，就是昨天重新弄了一个测试目录，npm install之后npm run dev之后就报错了

**Comment by airyland** [comment]
麻烦进入 vux-loader/src/js-loader 51行左右调试一下路径问题，没有具体的代码排查不了。

**Comment by xsfirst** [comment]
好的谢谢

**Comment by xsfirst** [comment]
是webpack.base.conf.js里的LoaderOptionsPlugin的配置问题，因为原先版本的没有调用这里的配置所以没有报错，感谢帮助~
