### ISSUE TITLE
这些警告怎么消除？谢谢

### ISSUE THREAD

**Issue by onefuyun** [airyland/vux#1754]
[VUX] 提 Issue 时麻烦附上以下版本信息以及必要的显示截图、重现步骤、代码(代码请不要截图)。 
[VUX] vux@2.5.4, vux-loader@1.1.3, webpack@2.6.1, node@6.11
[VUX] 建议反馈请访问 https://github.com/airyland/vux/issues
是我的这些工具的版本太高了，还是怎么回事

**Comment by airyland** [comment]
只是提示不是警告，方便反馈问题。
