### ISSUE TITLE
DatetimePlugin 插件形式引用报错

### ISSUE THREAD

**Issue by skyshirt** [airyland/vux#1757]
`import {DatetimePlugin} from 'vux'`
`Vue.use(DatetimePlugin)`
版本: vux@2.5.4

报错信息:

 ERROR  Failed to compile with 1 errors10:19:52

This relative module was not found:

* ../../components/datetime/style.less in ./~/vux/src/plugins/datetime/index.js

**Comment by airyland** [comment]
无法重现，请建 repo 重现。

**Comment by skyshirt** [comment]
[https://github.com/skyshirt/vux-test](https://github.com/skyshirt/vux-test)
麻烦了
![image](https://user-images.githubusercontent.com/18375810/28655064-ab381990-72cb-11e7-9943-b410a74c9beb.png)

**Comment by airyland** [comment]
为什么要 copy  vux 源码来开发，干干净净的脚手架为什么不用？

**Comment by airyland** [comment]
把这个文件改回来吧，不知道你改了是想实现什么，显然把 less 相关的改没了。
https://github.com/airyland/vux2/blob/master/template/build/utils.js

**Comment by skyshirt** [comment]
如果用vux-config跟webpackconfig合并后，会报错，所以把demo的这段复制过来了
后来我改成动态添加路由require组件，同样可以实现动态加载模块
主要目的是这个。见笑了。。
灰常感谢，已打赏
