### ISSUE TITLE
popup+scroller组件误点击

### ISSUE THREAD

**Issue by sandysong** [airyland/vux#176]
popup+scroller组件，scroller内容绑定click事件很容易被触发。
测试代码：http://shop.test.5ixmm.com/vux/dist/#!/component/popup
在vux的popup+scroller组件demo基础上加上了click事件，可以体会一下。

**Comment by sandysong** [comment]
补充：ios下可以稳定重现

**Comment by sandysong** [comment]
把popup组件popup.js中的下面这段注释掉问题解决，但不知道是否会引入其他问题
`    Tap.tap(this.mask, triggerClick)
    /*this.container.addEventListener('touchmove', function (e) {
        e.stopPropagation()
        e.preventDefault()
        return false
    }, false)*/
`

**Comment by airyland** [comment]
昨天看了你的demo没看到scroller里有什么点击事件。误点击不明白是什么意思。popup里现在是禁止了任何touch事件。

**Comment by sandysong** [comment]
误点击就是滑动的时候，特别容易触发click事件，你在列表里加个click事件就知道了。

``` html
<popup :show.sync="show2" height="200px" @on-first-show="resetScroller">
      <scroller height="100px" lock-x style="border:1px solid red;" v-ref:scroller>
        <div>
          <p v-for="i of 10" @click='foo'>{{i}}</p>
        </div>
      </scroller>
    </popup>

```

**Comment by airyland** [comment]
下个小版本会移除touchmove preventDefault相关代码。
