### ISSUE TITLE
微信浏览器里，pullup组件bug

### ISSUE THREAD

**Issue by LS1231** [airyland/vux#177]
### Version

vux@0.0.111

### Android or iOS, which browser?

微信浏览器

### Your Codes 

``` html

<scroller lock-x
              scrollbar-y
              use-pulldown
              use-pullup
              :pulldown-status.sync="pulldownStatus"
              :pullup-status.sync="pullupStatus"
              :pulldown-config="pulldownConfig"
              :pullup-config="pullupConfig"
              @pulldown:loading="doRefresh"
              @pullup:loading="loadMore">
      <order-item :list="productList"></order-item>
    </scroller>

```

### Steps to reproduce the problem

在微信浏览器中，上拉加载下一页数据，手指一直按住往上拖拽至屏幕外边界，页面会卡在屏幕中间，不会自动回到正常位置，即页面底边并不会贴近屏幕底边

**Comment by LS1231** [comment]
![image](https://cloud.githubusercontent.com/assets/5620625/15143593/0f94cca4-16dd-11e6-82fb-b6913c23505e.png)

bug效果如这样图所示

**Comment by airyland** [comment]
这个操作出现的问题能否在vux.li的demo页面重现？

**Comment by LS1231** [comment]
可以的。你只要上拉手指一直拖动至手机屏幕外，bug立马出现

**Comment by LS1231** [comment]
Safari浏览器无此现象，只有微信浏览器是这样的。之前用ionic的时候，同样有这个问题

**Comment by airyland** [comment]
我刚才只在Safari上看了，看来是微信webview有缺陷啊，滑到屏幕外不会自动触发touchend。但是这样的操作是不是比较极端，就是滑动距离如此的长？

**Comment by LS1231** [comment]
恩，那就我自己处理吧

**Comment by airyland** [comment]
@LS1231 有没有比较合适的处理方法？

**Comment by transtone** [comment]
是这个bug吗： http://forum.vuejs.org/topic/3745/在微信中-滑动使vue双向绑定失效

**Comment by airyland** [comment]
@transtone 不是的，这是微信的另一个问题了。包含这一个已经有3个微信webview的相关问题了。

https://github.com/airyland/vux/issues?q=is%3Aissue+label%3A%22not+vux%27s+issue%22+is%3Aclosed

**Comment by airyland** [comment]
Related problem: https://segmentfault.com/q/1010000002943205
