### ISSUE TITLE
ActionSheet组件如何实现为循环的每个按钮点击menu传不同的值

### ISSUE THREAD

**Issue by dingbo1028** [airyland/vux#1772]
# 需求
- 假设需要循环显示列表，每个item有一个button
- 点击item的button，会显示ActionSheet，假设有`操作1`、`操作2`两个menu
- 点击不同的menu会触发相应的method，然后会把item的index值传给method

# 疑问
- 如何实现不同的`ActionSheet` 的 `on-click-menu`内调用相同的方法且能传递一个自定义的参数index呢?

**Comment by airyland** [comment]
设置一个 index 变量，点击 item 的 button 时设置这个变量为当前 item index，那么 menu 点击时直接取 index 就行了。

你也可以等下个版本(2.5.5)，支持将原始的 menu 对象附带到事件的第二个参数，因此你可以在菜单定义加上自己需要的属性。

``` js
[{
  label: 'Primary',
  type: 'primary',
  value: 'primary',
  otherProp: 'hey'
}]
```

`on-click-menu(key, menuItem)`
