### ISSUE TITLE
x-address等基于Popup的组件，切换路由页面后不能自动隐藏

### ISSUE THREAD

**Issue by catsshow** [airyland/vux#1774]
**问题：**
x-address等基于Popup的组件，如果是显示的状态，在路由切换后，仍会保留显示，这就尴尬了。

**需求：**
建议增加像hideOnBlur这样的参数选项，让用户选择切换路由后是否自动关闭。

**Comment by airyland** [comment]
组件并不知道是否路由做了切换，是否自身位于被关闭的 router-view 内，得考虑一下能怎么实现。

**Comment by catsshow** [comment]
可以暴露一个方法，让用户选择在什么时机关闭（比如在路由切换后）。

**Comment by airyland** [comment]
如何重现切换显示? 我试了下比如 popup, 打开一个 popup，然后切换路由当前 popup 会被关闭掉。

**Comment by catsshow** [comment]
@airyland 我开发直接用的Vux的Demo源码（路由使用的keep-alive），项目在IOS版微信公众号中访问。其中一个新增地址的页面使用了x-address组件选择区域，打开选择区域后不做操作，点击微信左上角的返回按钮进入前一个页面，区域选择x-address组件仍然显示。如果需要，我把工程传给你分析下。

**Comment by airyland** [comment]
可以在 keep-alive 下重现了，我看看怎么处理。

**Comment by airyland** [comment]
下个版本(2.5.5)支持：在 deactivated 事件时自动关闭，可以使用 hide-on-deactivated 来禁用这一行为。
