### ISSUE TITLE
webpack@3.x版本已废弃 query参数, vux-loaders 可对应修改为 options, 或做下兼容

### ISSUE THREAD

**Issue by smat0096** [airyland/vux#1775]
[VUX] vux@2.5.4, vux-loader@1.1.4, webpack@3.4.0, node@6.11
首先感谢作者大大分享, 环境如上, vux-loader的index.js 第375行对应的 query 参数 可修改为 options, 或做下兼容

**Comment by airyland** [comment]
可 pr。
webpack@3.x 当前貌似还存在无法 hmr 的问题，比如 vux 开发依赖已经升级到了 3 但是 hmr 失效。

**Comment by smat0096** [comment]
已pr至vux-loader,谢谢

**Comment by airyland** [comment]
https://github.com/airyland/vux-loader/pull/25 merged.
