### ISSUE TITLE
x-address  可否支持 on-change事件？

### ISSUE THREAD

**Issue by zhump** [airyland/vux#1778]
x-address  可否支持 on-change事件？我有个需求，列表滑动发生变化时，值就是实时发生变化。没有onchage，就无法实现。

**Comment by airyland** [comment]
on-change 事件只用于最终确定 value 值，picker 值变化下个版本支持 on-shadow-change 事件。

**Comment by zhump** [comment]
嗯嗯，下个版本有计划时间吗？

**Comment by ytudt** [comment]
请问on-shadow-change中是否可以获取滑动框中的值？

**Comment by chenquan1992** [comment]
页面一加载完成，@on-shadow-change就自动调用了，还有一个默认值["110000", "110100", "110101"]，请问可以怎么避免吗？
