### ISSUE TITLE
time and date plugins can not click to select a certain selection in android brower?

### ISSUE THREAD

**Issue by ChacesXia** [airyland/vux#178]
I has tried in different devices; it doesn't work!
please fix it ! 
thanks
![image](https://cloud.githubusercontent.com/assets/15275744/15183784/35841d5a-17c5-11e6-9ee3-cb2790ae46fb.png)

**Comment by airyland** [comment]
`Calendar` is deprecated now and a new version is about to be released based on `inline-calendar`.
