### ISSUE TITLE
Clocker 可以支持传入倒计时开始时间么？

### ISSUE THREAD

**Issue by w2819** [airyland/vux#1780]
倒计时与服务器设定倒计时有时间差，想传入一个服务器时间作为倒计时开始时间。

**Comment by airyland** [comment]
既然知道时间差，那么修改一下倒计时结束时间不就好了。

**Comment by w2819** [comment]
倒计时结束时间是服务器时间，开始时间是客户端时间，时间差是这个导致的，两个时间都应该以服务器时间为准

**Comment by airyland** [comment]
两个时间看起来是没必要的。开始时间的时间差和结束时间的时间差可以认为一致的，既然你可以得到服务器时间，跟当前客户端时间比较快了2s，那么将服务端返回的结束时间减去 2s 就可以解决问题了。
