### ISSUE TITLE
vux2.5.5 actionsheet cancel按钮点击报错

### ISSUE THREAD

**Issue by rxhluck** [airyland/vux#1782]
![image](https://user-images.githubusercontent.com/22884883/28854238-7c098748-7768-11e7-8096-00e12110ed35.png)
点击取消按钮会报错
![image](https://user-images.githubusercontent.com/22884883/28854310-f81af27c-7768-11e7-81ee-8b68b3613bc9.png)
报错item为undefined

**Comment by airyland** [comment]
感谢反馈，可以更新到 2.5.6

**Comment by rxhluck** [comment]
好的，vux更新很及时，组件很好用，加油
