### ISSUE TITLE
请问在radio组件里怎么获取label的值？

### ISSUE THREAD

**Issue by bigbigbigbear** [airyland/vux#1783]
`<group gutter="0">
      <radio :selected-label-style="{color:'#F56839'}" :options="cityList" @on-change="change"></radio>
 </group>`
**项目开发中需要使用到radio组件，代码如上，cityList是一个数组对象，change方法里只能获取key的值，请问怎么获取value的值呢？**
`cityList:[
    {key: '001',
     value: '深圳'
    },
    {key: '002',
     value: '上海'}
]`

**Comment by airyland** [comment]
目前事件参数只支持 key, label 你可以从 cityList 匹配一下。下个版本支持 label 参数。

**Comment by bigbigbigbear** [comment]
好的，谢谢
