### ISSUE TITLE
引入组件出错问题

### ISSUE THREAD

**Issue by onepieceASL** [airyland/vux#1789]
我在src目录下新建了views的文件夹，views文件夹下新建bmap文件夹，在bmap文件夹下新建baidumap.vue文件，结构如：src/views/bmap/baidumap.vue
然后把app.vue里的
import { Radio} from 'vux'   复制到 baidumap.vue里，就出现如下错误

./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/bmap/baidumap.vue
Module not found: Error: Can't resolve '../components/radio/index.vue' in 'C:\Users\Administrator\Desktop\vue\vux-2\src\views\bmap'
 @ ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/bmap/baidumap.vue 3:0-50
 @ ./src/views/bmap/baidumap.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

但是如果我把baidumap.vue直接放到views下，就不会出现这种错误。
或者，我用这种方式单个引入
import    Card   from 'src/components/card/index'
也不会出错，想请教下，我该怎么做才能一次引入多个组件
如：import { Radio，Flexbox} from 'vux'  
并且我不愿把所有文件都放在views目录下

**Comment by airyland** [comment]
无法重现，无论你源码在哪个位置，都是解析到 node_modules/vux 。若无法解决，请建一个 Repo 来重现。

**Comment by onepieceASL** [comment]
谢谢大大抽空回答^_^

**Comment by greedying** [comment]
他这是直接把vux 复制了一份放到自己项目目录里了吧

**Comment by onepieceASL** [comment]
我是下了vux，然后在vux的src目录下加代码的

**Comment by airyland** [comment]
:sweat_smile: 还是用脚手架新建个干净的项目吧，vux 源码为了实现源码和 demo 同库是做了一些内部处理的，包括路径什么的，你这种情况得自己改 vux-loader 适配，复杂化了也难以维护。

**Comment by onepieceASL** [comment]
好的
