### ISSUE TITLE
能否完善html+标签+js的应用示例，npm+vue文件+webpack这种方式对于windows程序员而言太复杂了

### ISSUE THREAD

**Issue by surfsky** [airyland/vux#179]
如题，能否完善html+标签+js的应用示例。
npm+vue文件+webpack这种开发方式虽然很帅，但学习曲线太陡峭了，对于windows程序员而言也太复杂了，开发环境也要重新学习，调试环境也不熟悉，不利于推广。

**Comment by airyland** [comment]
没看到有什么多大成本，习惯使用的不一定是效率高的。使用vue-cli开发项目事实上节省了开发打包压缩部署维护的成本。

另外windows和Mac上是完全一致的开发方式，没有所谓的windows程序员。

建议学习一下，接受一下新的开发方式，看一下vue-loader文档，就几句命令行而已，不要还没使用就被吓到了。

**Comment by dangyuluo** [comment]
有时候并不是程序员不愿意去使用新技术，而是工作环境（包括合作开发者）情况复杂，不可能全盘改用webpack+vue-loader。不过如果是新项目的话，还是会使用较为先进的前端工程开发工具的。

**Comment by airyland** [comment]
@dangyuluo 旧项目完全可以理解，所以至少Vux提供了script全局引入，并没有强制用vue loader。

**Comment by dangyuluo** [comment]
@airyland 顺便问一句，我现在就是用requirejs来分别引入各components的js，但css总是有点问题。

有些组件如search.js，同目录下还有style.css。应该怎么优雅的引入呢？我现在是使用requirejs的css加载插件，将该style.css设置为search.js组件的依赖，但是觉得不是正途。

**Comment by airyland** [comment]
@dangyuluo scripts引入没想到适合的方法，webpack倒是会出一个插件，只需要引用插件，有样式的会自动引入。

可能可以这样，直接全部一次引入vux.css，然后写个工具根据引用到的组件，合并需要的组件css。
