### ISSUE TITLE
selector组件是否可以让用户手动输入？

### ISSUE THREAD

**Issue by cinos1** [airyland/vux#1792]
我现在的需求是想让用户选择一些常用的地址，如不存在则让用户手动输入，不知是否可以通过selector来支持，谢谢

**Comment by airyland** [comment]
不会在 selector 里增加输入，毕竟加一个输入框把组件变太复杂了。

建议这样处理：selector 项可以有一项为 手动输入，监听 on-change 事件，选择这一项时，你把手动输入的 x-input 显示出来就行了，或者显示一个 confirm 来输入。

考虑你说的是地址信息，那么其实一个 x-input 也是满足不了需求的。
