### ISSUE TITLE
popup picker `value` updates error

### ISSUE THREAD

**Issue by magicdawn** [airyland/vux#1793]
popup picker 里 watch 的 `value`, 去更新 `tempValue`
但是没有更新 `currentValue`
https://github.com/airyland/vux/blob/v2/src/components/popup-picker/index.vue#L209

下一次, onHide(true), 会将 `currentValue` 赋值给 `tempValue`
而且, currentValue 的初始值 = value, 后期 value 更新后, currentValue 没有更新

value 变更步骤
1. 设置 `value = ["110000", "110100", "110102"`
2. 设置 `value = ["420000", "421100", "421126"]`

然后下面截图三组数据分别是

1. 开启 popup 之前
2. 开启 popup 之后, 没有变化
3. 点击上方透明背景后的值, 可以看到 tempValue 是旧值110102, 正确的情况应该是更新的值 421126

![image](https://user-images.githubusercontent.com/4067115/28920342-ef75806c-7883-11e7-954e-a0c8d191a4a2.png)

这个tempValue 错误的现象是, 没有默认选中了.
整个现象是, 默认数据是 110102 那一组, 然后拿接口更新值为 421126 那一组, 然后打开 popup 什么都不做关掉, 默认选中的值不是接口更新的值了

有 value 为啥要使用 currentValue 了??? 不是很理解...

**Comment by airyland** [comment]
要实现双向绑定，又不能直接对 prop 做更新，当然现在有 sync 可以进一步简化。

下版本更新，可以用 vux@beta 测试。
