### ISSUE TITLE
咨询下variable.less是放在开发目录下和theme.less平级还是copy里面的代码放到theme.less里面？

### ISSUE THREAD

**Issue by bigbigbigbear** [airyland/vux#1794]
你好，问下variable.less是放在开发目录下和theme.less平级还是copy里面的代码放到theme.less里面？就是怎么让variable.less里的代码生效？感谢~

**Comment by airyland** [comment]
variable.less 只是变量索引，在源码里已经被引用，你不需要引用这个文件。theme.less 按照文档配置即可。
