### ISSUE TITLE
自定义主题的变量无法作用于Datetime组件

### ISSUE THREAD

**Issue by zynthium** [airyland/vux#1797]
在自定义主题`theme.less`里定义 
```less
@datetime-header-item-confirm-font-color: #000;
```
vux-loader配置正确，其他组件已经生效，但是datetime组件的样式依然没有改变。

**Comment by airyland** [comment]
并不能重现。

![image](https://user-images.githubusercontent.com/559179/28982124-37ca279c-7987-11e7-9470-5adc3eb3600d.png)
