### ISSUE TITLE
[Loading Component]Loading组件的v-model设计是否不合理？

### ISSUE THREAD

**Issue by Plortinus** [airyland/vux#1798]
1. `vue`在`2.4.2`版本中给`computed`里的属性加了限制，详见[assigning to a computed property without setter does not fail](https://github.com/vuejs/vue/issues/6078)
2. 项目将vue升级之后，配合vux官网的[页面切换显示loading](https://vux.li/#/?id=%E9%A1%B5%E9%9D%A2%E5%88%87%E6%8D%A2%E6%98%BE%E7%A4%BAloading)代码，会报错`[Vue warn]: Computed property "isLoading" was assigned to but it has no setter.`
3. 在[vue的issue](https://github.com/vuejs/vue/issues/6078)里问了一下，是因为`Loading`组件绑定值的时候用的`v-model`导致的，改成`:value="isLoading"`那个warn就不会出现了。
4. 想了一下这个Loading组件的作用，又看了一下[Element设计的Loading组件](https://github.com/ElemeFE/element/blob/dev/packages/loading/src/loading.vue)，我认为Loading组件的这个是否显示的属性不需要用v-model绑定
5. 用v-model来实现数据的双向绑定，在Loading这个组件里，没看到什么用处，是否还有别的场景会需要用v-model来实现呢？

**Comment by airyland** [comment]
这是不得已为之，vue2 废弃了 sync，只有 v-model 才能直接实现双向绑定，而 2.3 又把 sync 放回来，2.4 加了进一步的限制。所以这里组件代码又要改了。使用 v-model 在当时是为了统一绑定方式预留可能存在的内部状态更改实现的可能性。

**Comment by eggbucket** [comment]
什么时候更新vux呢？

**Comment by q27488** [comment]
刚好项目遇到了这个报错，查了下，确实是因为在 loading组件使用v-model去绑定 vuex的值。
导致报错：
`Computed property "alertShow" was assigned to but it has no setter.`
目前该如何解决？
（虽然报错，但是功能还是能用的）

**Comment by airyland** [comment]
@q27488 这个问题已经修复很久了，提问时请先看看版本吧。
