### ISSUE TITLE
vux文档 版本问题

### ISSUE THREAD

**Issue by JL-Code** [airyland/vux#1800]
![image](https://user-images.githubusercontent.com/14163944/28994583-4738f71c-7a04-11e7-9669-229a440deb03.png)

vux的文档版本是否和代码发布版本保持一致，我该如何查看官方的api文档的版本确保api文档所讲的内容的版本和vux版本保持一致？

**Comment by JL-Code** [comment]
我看到vux的发布版最新版是2.5.7 。vux的文档没有同步更新到2.5.7吗？

**Comment by airyland** [comment]
文档是同步的。哪里看得出没有同步？
