### ISSUE TITLE
通过vue router异步加载的页面中vux组件样式不渲染

### ISSUE THREAD

**Issue by wendux** [airyland/vux#1802]
你好，我用vue-router以同步方式导入的页面，vux的组件样式可以正常渲染，但是以异步方式加载的页面，则不会正常渲染。
 同步：
`import Payment from '../components/Payment'`
Payment中的vux组件样式可以正常渲染。
异步：
`const Payment = resolve => require(['../components/Payment.vue'], resolve);`
Payment中的vux组件样式不能正常渲染。

**Comment by airyland** [comment]
Radio 组件？

**Comment by wendux** [comment]
x-header

**Comment by airyland** [comment]
截个图看下

**Comment by wendux** [comment]
<img width="370" alt="wx20170807-153821 2x" src="https://user-images.githubusercontent.com/20411648/29016796-8c595926-7b86-11e7-9070-e0ef6605cc39.png">
另：测试环境下(热替换)是正常的，build之后就不行了，对比了一下发现是build之后没有vux-header样式

**Comment by wendux** [comment]
补充：发现只要是异步加载的，vux组件都有问题

**Comment by airyland** [comment]
用 vux2 模板创建的吗？

**Comment by airyland** [comment]
无法重现，麻烦给一个可重现 repo。

**Comment by wendux** [comment]
项目是用vux模版创建的，我今天重新创建了一个项目也无法重现，但我原来项目依然不行，应该不是必现。但是我发现有好几个类似的issue, 如issue #1807  所述，我把extract强制设为false后，也就正常了,怀疑是vux-loader处理css的问题，还有就是我之前遇到的一个相似问题:build之后发现autoprefixer没起作用，导致transfrom没有加webkit前缀，动画失效（浏览器的版本配置没有问题）；还有issue #1651 , 也是异步加载时样式丢失的问题。  我对比了正常情况和异常情况下build后生成的代码，发现异步组件的js有所不同：
正常情况下：
<img width="801" alt="normal" src="https://user-images.githubusercontent.com/20411648/29054568-8d832f90-7c29-11e7-906b-d09420150940.png">
有两部分
异常情况下：
<img width="758" alt="sad" src="https://user-images.githubusercontent.com/20411648/29054585-a1a6a5ba-7c29-11e7-942e-60529a0edeb6.png">
只有一部分。
貌似是webpack打包时没有将vux组件内的样式打进去。

**Comment by airyland** [comment]
是不是有配置差异？无法重现的话就难以处理了。
