### ISSUE TITLE
新下载配置的vux无法跑起来

### ISSUE THREAD

**Issue by AjiMIde** [airyland/vux#1804]
你好，我今天使用 npm （淘宝镜像）折腾一个新的 vue + vux 项目，步骤如下：
`npm install vux --save`

此时成功下载 vux，但无安装 vux-loader，此时我又安装了 vux-loader
`npm install vux-loader --save-dev`

此时也成功下载了vux-loader，此时我配置了 vux-loader 的相关（官网例子）
**webpack.base.conf.js**
![qq 20170807175333](https://user-images.githubusercontent.com/9972650/29022080-6fd00cc8-7b9a-11e7-9596-17a52ed31c22.png)

到此配置结束，我又按照官网例子，做了一个 vux 的 group, title 的组件示例
```
<template>
  <group>
    <title title="title" value="test vux"></title>
  </group>
</template>

<script>
import { Group, Cell } from 'vux'
export default {
  components: {
    Group,
    Cell
  }
}
</script>
```
配置正常的路由并跑了起来，然而并没有正常显示并提示我提 issue，相关信息如下：
**[VUX] 提 Issue 时麻烦附上以下版本信息以及必要的显示截图、重现步骤、代码(代码请不要截图)。**
**[VUX] vux@2.5.7, vux-loader@1.1.4, webpack@2.7.0, node@6.9**
**[VUX] 建议反馈请访问 https://github.com/airyland/vux/issues**

如果这确实是一个bug并能对您的项目起作用则好，如是我的操作问题或哪里处理不当耽误您的时间真是抱歉。谢谢！

**Comment by airyland** [comment]
1. 你写错代码了, 请把下面的 title 标签换成 cell

```
<title title="title" value="test vux"></title>
```

2. 那是 tip 不是 warning，是为了方便提 issue 显示在开发模式下的。

**Comment by AjiMIde** [comment]
果然是我眼瞎，诚惶诚恐写下 issue，浪费您时间真是抱歉！~_~
