### ISSUE TITLE
使用vux-cli安装的时候报错，请问怎么解决呢？

### ISSUE THREAD

**Issue by jonnykay** [airyland/vux#1805]
在windows上使用vux-cli安装的时候报错
使用的步骤是
1.vue init airyland/vux2 VuxDemo
2.cd VuxDemo
3.npm install 
环境nodejs 8.2.1  npm 5.3.0
具体错误如下
[报错信息.txt](https://github.com/airyland/vux/files/1204512/dd.txt)
这个要怎么解决

**Comment by airyland** [comment]
npm 的模块下载问题需要自己解决啊，看起来是网络问题导致的，也试试 cnpm 安装。
