### ISSUE TITLE
样式不能重新定义

### ISSUE THREAD

**Issue by eric1121** [airyland/vux#1806]
![image](https://user-images.githubusercontent.com/24478669/29025668-7ac9807c-7baa-11e7-87aa-f185e9942ee1.png)
![image](https://user-images.githubusercontent.com/24478669/29025690-8da1150c-7baa-11e7-9b63-b38af0d42ca9.png)
为什么这些样式不能编辑成功呢？
还有
![image](https://user-images.githubusercontent.com/24478669/29025717-bc4501e8-7baa-11e7-9963-42267bd0e566.png)
width和height也不能修改。。

**Comment by airyland** [comment]
上下文不完整，也并非 vux 问题，如果使用了 scope 请参照 vue-loader 文档。
