### ISSUE TITLE
自定义@keyframes动画在打包之后就消失了

### ISSUE THREAD

**Issue by nali946** [airyland/vux#1807]
用的是vux2模板, 项目中有文字滚动的需求,我自定义了一个@keyframes动画,dev环境下正常运行,build后动画不执行,我猜测是css处理的问题,当我将build目录下的vue-loader.conf.js文件的extract: isProduction强制赋值为false后打包就正常运行了,我不太清楚这个参数的具体作用,可能与下面的issues是同一个问题,不太确定,所以另开了一个issues,见谅,谢谢!重现如下:(只改动模板中的HelloFromVux.vue文件,vue-cli无此bug)

``` html
<template>
  <div>
    <div style="animation: moveText 10s"> 滚动的文字</div>
  </div>
</template>

<script>
import { Group, Cell } from 'vux'

export default {
  components: {
    Group,
    Cell
  },
  data () {
    return {
      msg: 'Hello World!'
    }
  }
}
</script>

<style>
.vux-demo {
  text-align: center;
}
.logo {
  width: 100px;
  height: 100px
}
@keyframes moveText{
  100% {
    transform: translateX(500px)
  }
}
</style>
```

**Comment by nali946** [comment]
@airyland 复制粘贴的,已经格式化好了,有空看一下,确实是有这个问题的

**Comment by wendux** [comment]
我之前遇到的一个相似问题:build之后发现autoprefixer没起作用，导致transfrom没有加webkit前缀，动画失效（浏览器的版本配置没有问题）,你可以看看build之后的样式是否加了前缀。奇怪的是，我今天新建了一个工程，却无法重现你的问题。我最后的解决办法是把util.js中的options里面的压缩选项注释掉了
```javascript
  var cssLoader = {
    loader: 'css-loader',
     //options: {
     //  minimize: process.env.NODE_ENV === 'production',
     // sourceMap: options.sourceMap
    }
  }
```
这样就好了。然而我发现生成的css依旧是压缩了的，估计是vux-loader中又压缩了。现在来看，解决的办法就是把vux-loader的 extract设置为false，不要抽取公共css就不会有问题。我现在新建的工程复现不了，没办法还原， 还请作者能够关注一下@airyland

**Comment by airyland** [comment]
@nali946 看起来这是 duplicate-style 的压缩结果，因为你并没有在 css 里使用到到这个 `@keyframes moveText`，所以认为是无用代码默认被压缩掉了，你可以使用 class 来引用或者配置`安全选项`来避免此类`激进`压缩，下个版本的 vux-loader 默认 safe 将设为 true。

> Note that cssnano enables aggressive optimisations by default, which might not
always be what you want. Set `options.safe` to `true` if you want to disable
this. In future versions, only safe options will be enabled by default, starting
from [version 4][v4].


``` js
{
    name: 'duplicate-style',
    options: {
      cssProcessorOptions: {
        safe: true
      }
    }
  }
```

@wendux 无法重现的我也没法解决。

**Comment by nali946** [comment]
修改后已解决,感谢!

**Comment by zhuyuanwen** [comment]
请问这段配置应该添加在哪个文件里面？@airyland

**Comment by airyland** [comment]
@zhuyuanwen 默认 safe 就是 true，不需要修改。在 webpack vux-loader 相关配置里修改。

**Comment by zhuyuanwen** [comment]
我发现问题在于，打包以后在vendor.css文件里有一个@-webkit-keyframes，名称是a。而我自己写的css动画@-webkit-keyframes fadeIn {...}，打包以后名字也变成了a。然后，vendor.css里面的a后加载，覆盖了我写的动画。 @airyland 

vendor.css中的动画a：
`@-webkit-keyframes a{0%{opacity:0;-webkit-transform:translateX(150px);transform:translateX(150px)}to{opacity:1;-webkit-transform:translateX(0);transform:translateX(0)}}`

`@keyframes a{0%{opacity:0;-webkit-transform:translateX(150px);transform:translateX(150px)}to{opacity:1;-webkit-transform:translateX(0);transform:translateX(0)}}`

**Comment by airyland** [comment]
@zhuyuanwen 这个问题比较奇怪无法重现，方便时给个 repo 重现。

**Comment by GalinaGao123** [comment]
@zhuyuanwen 你说的这个问题我也遇到了。 也是打包以后变成 a。但是内容不一样，我是rotate。重新起了个demo 没有复现。 好奇怪。

**Comment by ytxbnahn** [comment]
@zhuyuanwen 问题得到解决了吗 很想知道答案

**Comment by zhuyuanwen** [comment]
更新了版本以后打包就正常了

**Comment by reef007** [comment]
请问该问题解决了嘛，我的是编译完以后自定义动画名称就变成a了，目前vux的版本是2.9.2

**Comment by pengfu** [comment]
我也是在其他地方，webpack把我的动画名称改成了a，不知道怎么回事？

**Comment by chandq** [comment]
> 我发现问题在于，打包以后在vendor.css文件里有一个@-webkit-keyframes，名称是a。而我自己写的css动画@-webkit-keyframes fadeIn {...}，打包以后名字也变成了a。然后，vendor.css里面的a后加载，覆盖了我写的动画。 @airyland
> 
> vendor.css中的动画a：
> `@-webkit-keyframes a{0%{opacity:0;-webkit-transform:translateX(150px);transform:translateX(150px)}to{opacity:1;-webkit-transform:translateX(0);transform:translateX(0)}}`
> 
> `@keyframes a{0%{opacity:0;-webkit-transform:translateX(150px);transform:translateX(150px)}to{opacity:1;-webkit-transform:translateX(0);transform:translateX(0)}}`

我最近也遇到这种问题，不管是在css还是less文件中自定义的keyframes动画名称都被改成了a，经过查阅资料和验证，最终发现是cssnano（功能是压缩和清理css）这个css插件瞎搞导致的，禁用后立即恢复中正常了，或许你们可以试试这种方法
