### ISSUE TITLE
ViewBox 使用不明白

### ISSUE THREAD

**Issue by sunsunyongjiu** [airyland/vux#1808]
在index写好ViewBox之后具体的router页面里怎么触发scrollTo滚动到想去的位置？

**Comment by airyland** [comment]
已经提供了滚动到特定位置的函数，至于什么时候触发，这个不是组件能做的了，当然是你代码来实现滚动。

**Comment by sunsunyongjiu** [comment]
刚开始学着使用，我的意思是routerview外套着viewbox，进入到具体的路由页面后，滚动了一段距离，这时候想点击一个回到顶部的按钮，触发了click事件，在事件里怎么调用viewbox的scroto

**Comment by airyland** [comment]
设定 ref="viewbox"，就可以用 this.$refs.viewbox 来调用函数了。

**Comment by sunsunyongjiu** [comment]
我在首页调用他是没问题的，但是具体的router页里，调用他调用不到的

**Comment by airyland** [comment]
这不是 vux 的问题了，具体里的 routes 里当然调用不到其他页面组件，你可以用 vuex 等方式来传递参数操作。
