### ISSUE TITLE
怎么支持动态加载主题？一套应用同时支持微信和支付宝

### ISSUE THREAD

**Issue by qiliux** [airyland/vux#1809]
目标：同一个应用，根据不同的访问URL加载不同的主题？

从文档来看，可以通过下面的代码，来配置颜色

```
{
  name: 'less-theme',
  path: 'src/styles/theme.less'
}
```
但是这样是静态的，用了那个主题就是那个主题。

**Comment by airyland** [comment]
组件内是做不到这个功能的，需要用 webpack 使用不同配置分别打包。

**Comment by qiliux** [comment]
发现build后的index.html直接引用对应的js、css代码，能否用下面的方案解决？
是不是可以这样理解你说的不同配置打包。保存不同时刻的代码。使用了django作为后台服务，利用其渲染的机制，根据不同的URL渲染不同的index-*.html？？理论可行？
```
使用默认主题
npm run build
保存当前index.htm和生成的js和css，可将index.htm命名为index-default.html。
对于应用的访问URL1，渲染index-default.html
```

```
使用定制主题，增加主题配置。
{
  name: 'less-theme',
  path: 'src/styles/theme.less'
}
然后进行build生成
npm run build
保存当前index.htm和生成的js和css，可将index.htm命名为index-dingzhi.html。
对于应用的访问URL2，渲染index-dingzhi.html
```

**Comment by airyland** [comment]
你说是的如何渲染的问题，是可以和你说的方式处理的。
webpack 是支持同个配套文件 exports 多个 webpack 配置的，你可以直接修改 prod 配置来实现打包。
