### ISSUE TITLE
希望添加一个收货地址的组件

### ISSUE THREAD

**Issue by LiangFuzhi** [airyland/vux#181]
类似这样的样式
![s60512-170156](https://cloud.githubusercontent.com/assets/17739890/15209492/e66555aa-1863-11e6-84e2-d9244fced15d.jpg)

**Comment by airyland** [comment]
这个列表布局看起来不通用。

**Comment by LiangFuzhi** [comment]
包含 收货人名字   电话  和详细地址，是与其他不通用

**Comment by airyland** [comment]
@LiangFuzhi 因为vux组件库考虑的是可通用组件 ，所以暂时就不支持这样的布局了，它太过于业务相关了。
