### ISSUE TITLE
npm install 出现错误

### ISSUE THREAD

**Issue by didianV5** [airyland/vux#1811]
![image](https://user-images.githubusercontent.com/20223304/29066931-5d022bb6-7c63-11e7-8e64-f9e87604319b.png)

**Comment by airyland** [comment]
npm 的问题我也无解。
https://github.com/pierreinglebert/node-zopfli/issues/87
问题在于这个依赖的下载地址挂了： https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v51-darwin-x64.tar.gz

**Comment by didianV5** [comment]
哦哦 ，谢谢
