### ISSUE TITLE
如何在vux中实现prerender-spa-prerender-spa-plugin插件

### ISSUE THREAD

**Issue by notCoolBean** [airyland/vux#1812]
#我是一个新手，对框架不是怎么很熟悉希望能给我点指点帮我看一下如何在vux中使用webpack的预加载插件如何实现，我试过好多次就是不行，求指点

**Comment by wg5945** [comment]
目前还不支持ssr

**Comment by notCoolBean** [comment]
@wg5945 我的意思不是说直接在您的框架上用，我的意思是如何结合您的框架使用，我真的是有点摸不着头脑，看您能不能帮我

**Comment by airyland** [comment]
`好多次就是不行`，我们猜不出是什么原因，报了什么错，是不是你配置的问题，是不是 vux 的问题。所以，无解。
