### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by haishengXie0712** [airyland/vux#1813]
使用插件使用Toast时，
`this.$vux.toast.show({text: 'XXXXX',type: 'cancel',isShowMask: true})`
isShowMask这个属性无法生效，我想问一下怎么用插件调用可以使用。
版本:vux@2.5.6, vux-loader@1.1.4, webpack@2.7.0, node@8.2。

**Comment by airyland** [comment]
mask 是透明的，目的是阻止用户可以点击其他元素，所以并不能目测出有没有显示 mask。

**Comment by haishengXie0712** [comment]
@airyland 但是再出现toast时，我还可以点及其他元素，并且还是可以触发

**Comment by airyland** [comment]
“再”？本地测试过并没有问题。

**Comment by haishengXie0712** [comment]
@airyland 好的，谢谢

**Comment by airyland** [comment]
![image](https://user-images.githubusercontent.com/559179/29102990-94f5c9d8-7cef-11e7-895c-f4b175543f6e.png)

**Comment by ysjhnuitanfei** [comment]
怎么把toast组件提出来在utils的注册全局方法
`import Vue from 'vue'

function toast (content, time) {
  Vue.$vux.toast.show({
    type: 'text',
    text: content,
    position: 'bottom',
    time: 2000
  })
}
export default toast`
我这样写不行，会报这个toast undefined错
