### ISSUE TITLE
2.5.4版本内存泄漏问题

### ISSUE THREAD

**Issue by cinos1** [airyland/vux#1814]
目前项目用的2.5.4版本，发现一个问题，当vue页面中引入了一个组件，但实际并未用到此组件时，编译时会生成一个很大的js文件，大约是从50k的数量级膨胀到6-9m吧。
后来排查发现是因为引入未使用组件导致，如
`import { ViewBox } from 'vux'`
且在组件中声明，但实际并未使用

**Comment by airyland** [comment]
1.你代码引入了组件当然要打包出来。但是只要你配置了 vux-loader 是支持按需引入的。请给出 repo 重现。
2.看不出这和内存泄漏有什么关系。

**Comment by cinos1** [comment]
@airyland 稍等，我摘除下无关代码

**Comment by cinos1** [comment]
@airyland 重现的代码已经提交git，地址为：
https://github.com/cinos1/vuxdemo
在readme中给出了实际运行的截图，方便查看，提交的代码是注释掉多余组件部分的正常代码，请您查看是什么原因导致的，我在另外一个无子路由的项目中未重现这种情况，似乎是嵌套路由中才会出现

**Comment by airyland** [comment]
解析存在 bug，把这一行提到其他 import 语句上面貌似可以暂时解决，具体的问题将在 vux-loader 下个版本修复。
