### ISSUE TITLE
search组件autoFixed问题

### ISSUE THREAD

**Issue by onepieceASL** [airyland/vux#1815]
版本是刚下的最新版本，
autoFixed默认是true的，我不想固定到顶部，在search里增加了
:autoFixed="false"，这样就不会固定到顶部了，但是搜索结果赋值给results后，不会显示出来，
然后我下了vux项目单独跑，在search的demo里加上:autoFixed="false"，demo的results也不会显示出来了，
这算Bug吗

**Comment by airyland** [comment]
不固定在顶部，不会显示结果。

**Comment by onepieceASL** [comment]
好吧，打搅了

**Comment by airyland** [comment]
非 fixed情况下不适合显示结果，更适合跳转到新界面显示。

**Comment by Mango-chen** [comment]
修改样式
