### ISSUE TITLE
vux打包出现错误 

### ISSUE THREAD

**Issue by nosillytrying** [airyland/vux#1818]
![Uploading 11.png…]()

**Comment by nosillytrying** [comment]
ERROR in static/js/vendor.59f65b4e77620d3e45aa.js from UglifyJs
Unexpected character '`' [./~/vux/src/libs/router.js:18,0][static/js/vendor.59f65b4e77620d3e45aa.js:835,11] 错误就是这样的

**Comment by airyland** [comment]
请不要把 issue 当论坛。

打包问题非 vux 组件问题，可以 google 相关问题。也可以重新用模板初始化基础依赖和文件。
