### ISSUE TITLE
vux模板不支持多层目录的热更新?

### ISSUE THREAD

**Issue by shuiRong** [airyland/vux#1819]
`/components/test/Header.vue`

用  **airyland/vux2**  生成的项目 当Header.vue文件的更新时,不会产生热更新.必须restart项目才能看到更新的效果.

> 这个有点坑啊,花了1个小时,才找到原因.

**Comment by airyland** [comment]
请重现。
hmr 不是 VUX 实现的，有问题也是 webpack 、插件或者配置的问题。

**Comment by shuiRong** [comment]
无法重现,关掉了.
