### ISSUE TITLE
demo 中 calendar 的行为好像不符合使用习惯

### ISSUE THREAD

**Issue by ph2-cst** [airyland/vux#182]
### Version
Maybe v0.0.117

### Android or iOS, which browser?
Android 

### Expected behavior and actual behavior.
一般的操作习惯是按返回键， 日历弹出框消失，现在是按返回键， 页面返回，日历弹出框还在

**Comment by airyland** [comment]
当前calendar是废弃的，demo里有写着deprecated, 等新版本。
