### ISSUE TITLE
框架为什么不能像framework7那样集成页面切换动画效果呢?

### ISSUE THREAD

**Issue by oliwenfly** [airyland/vux#1823]
看了下demo的源码，发现页面切换实现起来好麻烦，而且新手很容易折腾错，以前用过framework7，感觉这个UI框架实现的切换动画蛮流畅的，不知道为什么vux不集成这个最基本的功能呢？
建议可以参考一下，望能尽快做的简单易学!

**Comment by airyland** [comment]
其实 demo 也是用 vue 自带的 transition 功能，实际上考虑到大家需求不一样，因此没有提供。
如果你比较了解 transition 实际上很好实现。
framework7 不像 vux，他基本所有东西都是自己实现了一套，因此内置容易，当然修改也可能不灵活。
当然也是有计划内置一些切换动画，这个要到后面的版本了。

**Comment by oliwenfly** [comment]
framework7也有vue版本的，只是文档不是很全，就没有选用，自己用transition虽然可以实现这样的效果，但是对于我们这样的新手，兼容性以及性能是一个非常头痛的问题，希望官方能给出一个相对简单实用的功能，万分期待！
