### ISSUE TITLE
2.0.5版本直接升级到2.5有变化吗

### ISSUE THREAD

**Issue by ytudt** [airyland/vux#1828]
您好我之前老项目用的vue2.1.0 vux用的2.0.5 现在想用一些vux新特性，请问直接升级到最新版本会有问题吗?项目在线上跑着，不敢大意。

**Comment by airyland** [comment]
有。2.1 升级了 WeUI 依赖，class 命名方式变更，如果你项目里存在使用类名来覆盖样式的话会影响到。

2.1 可以直接升级到 2.5。

![image](https://user-images.githubusercontent.com/559179/29205607-91cb1fe8-7eb0-11e7-9de9-3a14c4cf3373.png)
