### ISSUE TITLE
confirm组件，:input-attrs="{type: number}"，报错

### ISSUE THREAD

**Issue by oliwenfly** [airyland/vux#1829]
[Vue warn]: Property or method "number" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

这个是报错的内容，x-input设置成number，同样也会报这个错误，请问怎么解决？

ps: 文档中对于新增的input-attrs属性没有说明object的格式，望能补充完整!

**Comment by airyland** [comment]
number 确实未定义吧。

``` js
{
  type: 'number'
}
````

**Comment by oliwenfly** [comment]
参照demo写的，也出错，所以改了下，还是有错误
Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

**Comment by airyland** [comment]
这个是 fastclick 的问题，应该只在 PC 上出现，后面才会解决。
