### ISSUE TITLE
datetime组件在IOS8下样式错乱无法使用

### ISSUE THREAD

**Issue by chenjiangsong** [airyland/vux#183]
### Version
0.0.110
### Android or iOS, which browser?
IOS 8
### Your Codes 
```
<date-time title="认购日期"  confirm-text="完成" cancel-text="取消" :value.sync="submitInfo.bookDate"></date-time>
```

### Expected behavior and actual behavior.
在iOS8下点击组件，弹出popup-picker，选项全为空，『取消』和『完成』按钮挤到一块去了。IOS9和IOS7正常

**Comment by airyland** [comment]
手头没有iOS8的机子，除了datetime，其他组件有问题吗？

**Comment by chenjiangsong** [comment]
其他的popup-picker组件没问题，感觉是datetimepicker.js有问题

**Comment by airyland** [comment]
@chenjiangsong 看描述像是布局不兼容，有没有截图

**Comment by chenjiangsong** [comment]
![3 pic](https://cloud.githubusercontent.com/assets/14155079/15421077/f63d5ac2-1ea3-11e6-9626-dbc238e70d27.jpg)

**Comment by airyland** [comment]
有没有试过在其他浏览器打开？

**Comment by airyland** [comment]
好不容易找了个古董机重现了，稍等。

**Comment by chenjiangsong** [comment]
3q!!!
