### ISSUE TITLE
popup iphone 6 滑动整个背景滑动

### ISSUE THREAD

**Issue by mengao89** [airyland/vux#1830]
滑动截图中选中对应区域，整个页面背景都会跟随滑动，官网的demo可以复现
![qq 20170811214728](https://user-images.githubusercontent.com/3873232/29215884-589f5732-7edf-11e7-9f34-4a8f4ac76c70.png)

**Comment by wg5945** [comment]
thx，下个版本修复

**Comment by wangjiao1** [comment]
想问一下，这个解决了吗？

**Comment by YeWenjun** [comment]
请问背景滑动问题解决了吗

**Comment by SaltedFishYuto** [comment]
解决了吗,大佬

**Comment by liaotup** [comment]
官方Demo是好了 但是我这边使用仍然有问题  遮罩层不会穿透滑动，但是在popup里面的内容会穿透滑动

**Comment by mengao89** [comment]
> 解决了吗,大佬

解决了，应该是自己样式问题

**Comment by killertao** [comment]
> > 解决了吗，大佬
> 
> 解决了，应该是自己样式问题
https://www.jianshu.com/p/3c3dbc7ab142
