### ISSUE TITLE
XImg 图片在 Popup 中无法展示问题

### ISSUE THREAD

**Issue by browneyedape** [airyland/vux#1833]
图片无法展示问题
--------------------------------------------- 
[VUX] vux@2.5.7, vux-loader@1.1.4, webpack@2.7.0, node@8.1

--------------------------------------------
下面这个vue文件作为插件 内嵌在 popup组件内
```
<template>
  <div>
    <card>
      <x-img slot="header" :src="url"  style="width:100%"/>
      <div slot="content" class="card-padding">
      </div>
      <div slot="footer">
      </div>
    </card>
  </div>
</template>

<script>
import { Card, XImg } from 'vux'

export default {
  name: 'item',
  components: {
    Card,
    XImg
  },
  data () {
    return {
       url: 'https://img.alicdn.com/imgextra/i3/3064741329/TB258iSqmVmpuFjSZFFXXcZApXa_!!3064741329.jpg'
    }
  }
}

</script>

<style scoped>
.card-padding {
  margin-top:-7px;
  padding: 5px 10px 15px 10px;
}
</style>
```
![Uploading Untitled.png…]()

**Comment by airyland** [comment]
这个比较麻烦，默认 popup 是隐藏的所以不会显示。XImg 监听的是滚动事件，你这里用在 popup 里至少要设定一个 container，但是还需要通知到 XImg 容器已经显示出来，执行相关的逻辑。需要再考虑一下怎么处理合适。

**Comment by browneyedape** [comment]
那请问，通知时如何实现的

**Comment by browneyedape** [comment]
blazy.js 里面包含一个 load 的公开方法，可否使用在此？ @airyland

**Comment by airyland** [comment]
可以使用 BusPlugin 在 Popup 第一次显示时广播一个事件，参照这里 https://github.com/airyland/vux/blob/16334d01a0b208b63a2d1eb307c8fb69cb19bb9f/src/demos/XImgPopup.vue  

确保已经在 main.js 里已经引入了 BusPlugin

``` js
import { BusPlugin } from 'vux'
Vue.use(BusPlugin)
```

demo: https://vux.li/demos/v2/#/demo/x-img-popup
