### ISSUE TITLE
ios上点击高亮

### ISSUE THREAD

**Issue by eric1121** [airyland/vux#1835]
![image](https://user-images.githubusercontent.com/24478669/29270319-cfc732e4-8128-11e7-8e20-60b5b8eb6361.png)

我在
为什么iOS上点击高亮，只有点击title的时候会在iOS上出现当前行（灰色）高亮，然后跳转，用
<meta name="msapplication-tap-highlight" content="no">无效果

**Comment by airyland** [comment]
重新编辑下再 reopen 吧，至少让看到这个 issue 的人读起来流畅一些。

**Comment by eric1121** [comment]
![image](https://user-images.githubusercontent.com/24478669/29270770-dea79b58-812a-11e7-9b58-290f0deaed64.png)
![image](https://user-images.githubusercontent.com/24478669/29270817-0f9667bc-812b-11e7-9c83-e8a0d8cf0d72.png)

我做的钉钉微应用，在苹果手机上打开钉钉的这个界面，点击title部分会出现点击部位的当前行高亮，其他地方都没问题，用<meta name="msapplication-tap-highlight" content="no">也没有效果，我要的效果是点击group内的任何元素都没有高亮色，或者整个group高亮背景色都一样，而不是一块。
