### ISSUE TITLE
timeline 没有正确响应改动

### ISSUE THREAD

**Issue by sciooga** [airyland/vux#184]
### Version
v0.0.117

``` html
<timeline>
  <timeline-item v-for="item in list">{{item.xxx}}</timeline-item>
</timeline>
``` 

如果 list 在后期有改动的话，每个 timeline-item 都被判断成第一个元素 isFirst = true，各个 timeline-item 间也不会有连线，如下：
![image](https://cloud.githubusercontent.com/assets/9958281/15314812/acc631f2-1c46-11e6-89cf-dc606219b12b.png)
只有当调用 timeline 组件的 setChildProps() 时才能正确渲染
![image](https://cloud.githubusercontent.com/assets/9958281/15314842/d34b56c2-1c46-11e6-8860-d10dbe7e5608.png)

**Comment by airyland** [comment]
召唤 @graysheeep

**Comment by graysheeep** [comment]
...给我个表现的机会好吗 @airyland

**Comment by airyland** [comment]
@graysheeep 机会有的是，我就按照规范整理了一下代码。。

**Comment by airyland** [comment]
@graysheeep 我来催稿了，把step交出来

**Comment by graysheeep** [comment]
@airyland 这两天就给你，新公司刚入职事情比较多

**Comment by airyland** [comment]
@graysheep 看你时间，我就这么偶尔催一下。

**Comment by graysheeep** [comment]
@airyland 在下说到做到好吧
