### ISSUE TITLE
当使用vux组件时报错，没有使用时配置vux-loader是可以进入页面的

### ISSUE THREAD

**Issue by qq175074872** [airyland/vux#1840]
This dependency was not found:
* vux/undefined in ./~/_babel-loader@7.1.1@babel-loader/lib!./~/_vux-loader@1.1.5@vux-loader/src/script-loader.js!./~/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script&index=0

**Comment by airyland** [comment]
1.组件名写错了
2.版本太低了

信息太少，按照上面建议自行解决。
