### ISSUE TITLE
FlexBox的垂直属性在IPONE5s上失效

### ISSUE THREAD

**Issue by ManorNotMaNong** [airyland/vux#1841]
![tim 20170815161238](https://user-images.githubusercontent.com/24819542/29308748-8ba78a1c-81d9-11e7-901b-2379bf434905.png)
ios7系统,代码引用的官方示例,  autoprefix 设置 bowsers: ['iOS >= 7', 'Android >= 4.1'] 无效

**Comment by airyland** [comment]
iOS7 版本也太低了，目测是系统不支持，非代码层面的问题。
