### ISSUE TITLE
在iOS上高亮显示关闭不了

### ISSUE THREAD

**Issue by eric1121** [airyland/vux#1842]
![image](https://user-images.githubusercontent.com/24478669/29311166-5146d7e2-81e3-11e7-9bbf-38ccedb8e392.png)

![image](https://user-images.githubusercontent.com/24478669/29311101-077a759c-81e3-11e7-858d-f7cba50bae2c.png)

我做的钉钉微应用，在苹果手机上打开钉钉的这个界面，点击title部分会出现点击部位的当前行高亮，其他地方都没问题，用也没有效果，我要的效果是点击group内的任何元素都没有高亮色，或者整个group高亮背景色都一样，而不是一块。

**Comment by airyland** [comment]
请帖完整可以直接拿来重现的文字代码。
