### ISSUE TITLE
Radio组件的item checked是怎么触发的？

### ISSUE THREAD

**Issue by zhuyuanwen** [airyland/vux#1843]
犹豫我的单选内容不是简单的lable文字，而是一个音乐列表，需要点击播放按钮来试听，另外点击item来触发item选中。因为我可能需要自己加event.stopPropagation()事件。

**Comment by airyland** [comment]
看不懂需求。checked 就是点击触发的。

**Comment by zhuyuanwen** [comment]
@airyland 稍等 我截个图给你

**Comment by zhuyuanwen** [comment]
![](https://user-images.githubusercontent.com/12319327/29312817-b2cf0b0a-81e9-11e7-83d6-65de8d543fd8.png)

**Comment by zhuyuanwen** [comment]
@airyland 抱歉，我只会这样截图。。 我想知道你的radio的click事件，就是我点击某个item的时候，item被选中。但是我也需要可以点击播放按钮来播放音乐

**Comment by airyland** [comment]
其实看起来不用 Radio 组件直接自己写一个更方便 :sweat_smile: 
目测也只能像你上面说的，在点击时阻止冒泡试试。

组件层面上不好设计以支持这种情况。

**Comment by zhuyuanwen** [comment]
@airyland 好吧😂   纠结了2天。。 
那你的Radio组件是通过哪个函数来控制项目被选中的？

**Comment by airyland** [comment]
直接设置绑定的值就行了。
