### ISSUE TITLE
使用滚动条下拉刷新时报错

### ISSUE THREAD

**Issue by qq175074872** [airyland/vux#1844]
vue.esm.js?71e4:479 [Vue warn]: Error in render function: "TypeError: _vm.$t is not a function"
found in
---> <Cart> at D:\vue\test\src\pages\cart.vue
       <App> at D:\vue\test\src\App.vue
         <Root>
warn @ vue.esm.js?71e4:479
handleError @ vue.esm.js?71e4:562
Vue._render @ vue.esm.js?71e4:4130
updateComponent @ vue.esm.js?71e4:2538
get @ vue.esm.js?71e4:2881
Watcher @ vue.esm.js?71e4:2870
mountComponent @ vue.esm.js?71e4:2542
Vue$3.$mount @ vue.esm.js?71e4:7863
Vue$3.$mount @ vue.esm.js?71e4:10066
init @ vue.esm.js?71e4:3501
createComponent @ vue.esm.js?71e4:5147
createElm @ vue.esm.js?71e4:5090
patch @ vue.esm.js?71e4:5570
Vue._update @ vue.esm.js?71e4:2414
updateComponent @ vue.esm.js?71e4:2538
get @ vue.esm.js?71e4:2881
Watcher @ vue.esm.js?71e4:2870
mountComponent @ vue.esm.js?71e4:2542
Vue$3.$mount @ vue.esm.js?71e4:7863
Vue$3.$mount @ vue.esm.js?71e4:10066
init @ vue.esm.js?71e4:3501
createComponent @ vue.esm.js?71e4:5147
createElm @ vue.esm.js?71e4:5090
createChildren @ vue.esm.js?71e4:5218
createElm @ vue.esm.js?71e4:5123
createChildren @ vue.esm.js?71e4:5218
createElm @ vue.esm.js?71e4:5123
patch @ vue.esm.js?71e4:5570
Vue._update @ vue.esm.js?71e4:2414
updateComponent @ vue.esm.js?71e4:2538
get @ vue.esm.js?71e4:2881
Watcher @ vue.esm.js?71e4:2870
mountComponent @ vue.esm.js?71e4:2542
Vue$3.$mount @ vue.esm.js?71e4:7863
Vue$3.$mount @ vue.esm.js?71e4:10066
init @ vue.esm.js?71e4:3501
createComponent @ vue.esm.js?71e4:5147
createElm @ vue.esm.js?71e4:5090
patch @ vue.esm.js?71e4:5606
Vue._update @ vue.esm.js?71e4:2414
updateComponent @ vue.esm.js?71e4:2538
get @ vue.esm.js?71e4:2881
Watcher @ vue.esm.js?71e4:2870
mountComponent @ vue.esm.js?71e4:2542
Vue$3.$mount @ vue.esm.js?71e4:7863
Vue$3.$mount @ vue.esm.js?71e4:10066
Vue._init @ vue.esm.js?71e4:4236
Vue$3 @ vue.esm.js?71e4:4321
(anonymous) @ main.js?1c90:94
(anonymous) @ app.js:875
__webpack_require__ @ app.js:660
fn @ app.js:86
(anonymous) @ app.js:1556
__webpack_require__ @ app.js:660
(anonymous) @ app.js:709
(anonymous) @ app.js:712
vue.esm.js?71e4:566 TypeError: _vm.$t is not a function
    at Proxy.render (cart.vue?3e0e:20)
    at VueComponent.Vue._render (vue.esm.js?71e4:4128)
    at VueComponent.updateComponent (vue.esm.js?71e4:2538)
    at Watcher.get (vue.esm.js?71e4:2881)
    at new Watcher (vue.esm.js?71e4:2870)
    at mountComponent (vue.esm.js?71e4:2542)
    at VueComponent.Vue$3.$mount (vue.esm.js?71e4:7863)
    at VueComponent.Vue$3.$mount (vue.esm.js?71e4:10066)
    at init (vue.esm.js?71e4:3501)
    at createComponent (vue.esm.js?71e4:5147)
handleError @ vue.esm.js?71e4:566
Vue._render @ vue.esm.js?71e4:4130
updateComponent @ vue.esm.js?71e4:2538
get @ vue.esm.js?71e4:2881
Watcher @ vue.esm.js?71e4:2870
mountComponent @ vue.esm.js?71e4:2542
Vue$3.$mount @ vue.esm.js?71e4:7863
Vue$3.$mount @ vue.esm.js?71e4:10066
init @ vue.esm.js?71e4:3501
createComponent @ vue.esm.js?71e4:5147
createElm @ vue.esm.js?71e4:5090
patch @ vue.esm.js?71e4:5570
Vue._update @ vue.esm.js?71e4:2414
updateComponent @ vue.esm.js?71e4:2538
get @ vue.esm.js?71e4:2881
Watcher @ vue.esm.js?71e4:2870
mountComponent @ vue.esm.js?71e4:2542
Vue$3.$mount @ vue.esm.js?71e4:7863
Vue$3.$mount @ vue.esm.js?71e4:10066
init @ vue.esm.js?71e4:3501
createComponent @ vue.esm.js?71e4:5147
createElm @ vue.esm.js?71e4:5090
createChildren @ vue.esm.js?71e4:5218
createElm @ vue.esm.js?71e4:5123
createChildren @ vue.esm.js?71e4:5218
createElm @ vue.esm.js?71e4:5123
patch @ vue.esm.js?71e4:5570
Vue._update @ vue.esm.js?71e4:2414
updateComponent @ vue.esm.js?71e4:2538
get @ vue.esm.js?71e4:2881
Watcher @ vue.esm.js?71e4:2870
mountComponent @ vue.esm.js?71e4:2542
Vue$3.$mount @ vue.esm.js?71e4:7863
Vue$3.$mount @ vue.esm.js?71e4:10066
init @ vue.esm.js?71e4:3501
createComponent @ vue.esm.js?71e4:5147
createElm @ vue.esm.js?71e4:5090
patch @ vue.esm.js?71e4:5606
Vue._update @ vue.esm.js?71e4:2414
updateComponent @ vue.esm.js?71e4:2538
get @ vue.esm.js?71e4:2881
Watcher @ vue.esm.js?71e4:2870
mountComponent @ vue.esm.js?71e4:2542
Vue$3.$mount @ vue.esm.js?71e4:7863
Vue$3.$mount @ vue.esm.js?71e4:10066
Vue._init @ vue.esm.js?71e4:4236
Vue$3 @ vue.esm.js?71e4:4321
(anonymous) @ main.js?1c90:94
(anonymous) @ app.js:875
__webpack_require__ @ app.js:660
fn @ app.js:86
(anonymous) @ app.js:1556
__webpack_require__ @ app.js:660
(anonymous) @ app.js:709
(anonymous) @ app.js:712

vue.esm.js?71e4:479 [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'reset' of undefined"
found in
---> <Cart> at D:\vue\test\src\pages\cart.vue
       <App> at D:\vue\test\src\App.vue
         <Root>
warn @ vue.esm.js?71e4:479
handleError @ vue.esm.js?71e4:562
(anonymous) @ vue.esm.js?71e4:703
nextTickHandler @ vue.esm.js?71e4:648
vue.esm.js?71e4:566 TypeError: Cannot read property 'reset' of undefined
    at VueComponent.eval (cart.vue?4b55:31)
    at Array.eval (vue.esm.js?71e4:701)
    at nextTickHandler (vue.esm.js?71e4:648)
    at <anonymous>
handleError @ vue.esm.js?71e4:566
(anonymous) @ vue.esm.js?71e4:703
nextTickHandler @ vue.esm.js?71e4:648
vue.esm.js?71e4:479 [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'reset' of undefined"

found in

---> <Cart> at D:\vue\test\src\pages\cart.vue
       <App> at D:\vue\test\src\App.vue
         <Root>
warn @ vue.esm.js?71e4:479
handleError @ vue.esm.js?71e4:562
(anonymous) @ vue.esm.js?71e4:703
nextTickHandler @ vue.esm.js?71e4:648
vue.esm.js?71e4:566 TypeError: Cannot read property 'reset' of undefined
    at VueComponent.eval (cart.vue?4b55:34)
    at Array.eval (vue.esm.js?71e4:701)
    at nextTickHandler (vue.esm.js?71e4:648)
    at <anonymous>

**Comment by airyland** [comment]
这是你提的第二个完全不合格不尊重本项目维护者的 issue，不会处理，自行解决。
