### ISSUE TITLE
TabbarItem组件 的 link 怎样写才能没有历史记录

### ISSUE THREAD

**Issue by Ruanyang2015** [airyland/vux#1845]
TabbarItem组件 的 link 怎样写才能没有历史记录,文档上也没给对应的 Demo

**Comment by airyland** [comment]
使用 vue-router path 形式，并且  `replace: true`

``` html
:link="{path: '/demo', replace: true}"
```

**Comment by llsy** [comment]
![image](https://user-images.githubusercontent.com/18343441/30851310-da38c052-a2da-11e7-9c18-e7dde1d3c2be.png)
为什么这样写无效？

**Comment by airyland** [comment]
@llsy 功能又不是在所有版本有效，为什么不说个版本号？

**Comment by llsy** [comment]
@airyland 
"vux": "^2.4.0"
"vue": "^2.3.4"

查到了更新版本在2.5.5，忽略- -
