### ISSUE TITLE
loading组件props属性错误

### ISSUE THREAD

**Issue by ClassEve** [airyland/vux#1849]
![](https://user-images.githubusercontent.com/22854594/29355619-59d63800-82a4-11e7-8280-342e03342fe3.png)
![](https://user-images.githubusercontent.com/22854594/29355640-6c1b4492-82a4-11e7-8b3d-681d0baa85af.png)

demo里的显示加载使用的是show属性，但是组件里对外接口只有value，没有show，在开发中只能使用value属性控制是否显示，与demo不一致，下面的this.show = this.value 逻辑不对了

**Comment by bibiuc** [comment]
v-model="show"

**Comment by airyland** [comment]
更新下版本吧。

![image](https://user-images.githubusercontent.com/559179/29356795-ff7c38ce-82a7-11e7-89d0-5030b499de9a.png)

**Comment by ClassEve** [comment]
好的，辛苦了
