### ISSUE TITLE
表格样式问题

### ISSUE THREAD

**Issue by xwg2015** [airyland/vux#1851]
![image](https://user-images.githubusercontent.com/19931311/29366385-7aa9f670-82cc-11e7-9777-5506bfa9c7a8.png)

默认th和td都设置了定位，导致给th添加背景色把边框覆盖了，如上图所示
虽然我使用了z-index解决 但是会导致th,td里面的元素点击事件触发不了。

**Comment by airyland** [comment]
请帖代码。

**Comment by xwg2015** [comment]
![image](https://user-images.githubusercontent.com/19931311/29395646-df25c11a-8344-11e7-83b5-9d60ed46d801.png)

![image](https://user-images.githubusercontent.com/19931311/29395659-f53b9286-8344-11e7-84b5-a7844fd6a106.png)

原本我用了多个thead和tbody 后面改成这样还是会有这个问题

**Comment by airyland** [comment]
哎，帖代码是为了方便直接拿来重现。不要截图！不要截图！不要截图！
等有空我再来重现。

**Comment by xwg2015** [comment]
好的，等我忙完有空贴上代码。
