### ISSUE TITLE
上啦刷新 真难用

### ISSUE THREAD

**Issue by peng-yin** [airyland/vux#1856]

**Comment by airyland** [comment]
文档写了，该组件已经废弃。
爱用不用，别发垃圾，SB。

**Comment by 623023808** [comment]
这些提问的真是好扯啊。。。。，我之前用的饿了么的mint的上拉刷新，后来放弃mint改用vux的时候，没注意作者标注该组件已废弃，所以刚开始用了，感觉该组件设计的还是很不错，就是性能不行。后来改用better-scroll了，很好用
