### ISSUE TITLE
为什么XDialog有prop scroll 然而confirm组件缺没有

### ISSUE THREAD

**Issue by xwg2015** [airyland/vux#1858]
比较好奇 同样都是弹出来的弹框  comfirm组件触发时  body如何禁止滑动呢？

查找了一下貌似是移动端滑动穿透问题

**Comment by wg5945** [comment]
可以自行查看源码的哦

XDialog我记得好像是阻止了touchmove事件

**Comment by airyland** [comment]
原来的 scroll 并没有实现阻止滑动，设置该属性后是弹窗也无法滚动了。从下个版本开始使用全局配置 $layout 来为 100% 布局实现。
