### ISSUE TITLE
Vux Showcase

### ISSUE THREAD

**Issue by airyland** [airyland/vux#186]
Comment here if you are using Vux or will use Vux.

**Comment by iflamed** [comment]
We use Vux, and you can scan this qrcode with wechat to try our auction system.

![Uploading subscribe_qrcode_860.jpg…](掌物志拍卖平台)

**Comment by qiubcym** [comment]
a pretty application using vux

**Comment by airyland** [comment]
@iflamed Nice. PR is always welcome if you found some component could be better.

**Comment by deboyblog** [comment]
GuJi Using Vux 0.0.111 
![qq 20160524085742](https://cloud.githubusercontent.com/assets/11410323/15488904/968ddae2-218d-11e6-9f51-2fe933a07c0c.png)

**Comment by lymanlai** [comment]
@iflamed ios app不是vux的吧？

**Comment by airyland** [comment]
c
