### ISSUE TITLE
DateTime当设置format为YYYY时，滑动出现错误

### ISSUE THREAD

**Issue by koucxz** [airyland/vux#1861]
当从vux@2.2.2升级至如下版本时，选择年的datetime组件，在滑动时，发生如下错误
![image](https://user-images.githubusercontent.com/24607191/29507235-d34c73c6-8681-11e7-8af9-985dfb6c356c.png)

版本：vux@2.5.8, vux-loader@1.1.5, webpack@2.7.0, node@6.10

    <datetime v-model="time" format="YYYY" title="时间"></datetime>
    data:{
      return {
        time:''
      }
    }

**Comment by airyland** [comment]
Thanks for your feedback.
