### ISSUE TITLE
升级问题v2.21到v2.5.8

### ISSUE THREAD

**Issue by thinkido** [airyland/vux#1863]
![](http://cdn.d7game.com/time_tlog/2017-08-23_0L7QAMR.png)
     http://cdn.d7game.com/time_tlog/2017-08-23_1910vux升级问题z39.mp4
1、新系统的代码引入报错 2、原来的系统代码，不知道如何引入使用。路由关系是怎样的？
我希望让原来的系统可以正常运行.
起因是需要用到DateTime 是新版本，从而升级的过程.

## 以下信息只是个人解决问题的过程，不需要查看. 留给后面的人，解决问题时参考
点击按钮，无法像电脑那样弹出时间选择框，发现需要vue2.3新版本; 这个如何做升级;
     查看node_modules 下vue目录 package.json 文件中有 "raw": "vue@^2.3.0", 18:36
     更新 vux vue版本后, 项目报错 Computed property "isLoading" was assigned 18:41
     下载官方最新代码，搜索isLoading发现相关代码看起来一样，没有修改，编剧运行官方项目代码，可以正常运行，那问题在什么地方呢？ 重新启动自己的项目，isLoading的错误似乎消失了. 18:53
     切换到其他页面模块就报错isLoading，感觉像是模块加载出了问题，经过测试发现确实是文件加载问题.
     先修改模块，加载方式，后面再解决这个问题，.19:10
     错误解决之后，依然不能正常弹出 时间选择框; 19:16
     把官方页面的代码，整个页面直接复制过来，不能运行代码。问题不是在这个页面，在其他什么地方？
     main.js 中确实有 DatetimePlugin , 添加过后运行项目又报错. 尝试删除node_modules并等待删除完成.  19:30
     现在版本是vux@2.2.1 ,最新v2.5.8  19:35
     npm start 已经启动报错npm ERR! missing script: start.那为什么 vux项目可以运行.  19:44
     发现node_modules中没有vux,为什么安装失败. 19:48
     重启电脑试试.
     ![](http://cdn.d7game.com/markdown/2017-08-22_CPTVDS[WY52.png)
     项目依然无法启动. 20:16
      Make sure you have the latest version of node.js and npm installed. 20:18
      npm install npm -g 或者  npm -g install npm@5.3.0
      http://jingyan.baidu.com/article/ac6a9a5e60a44f2b653eac85.html
     升级npm后报错信息变了. 20:25
     报错信息Module build failed: Error: Couldn't find preset "env" relative to directory 20:29
     ![](http://cdn.d7game.com/markdown/2017-08-22_61TK15X.png)
     ![](http://cdn.d7game.com/markdown/2017-08-22_YUFHTQ.png)
     代码结构发生了很大变化,查看新版本代码。 21:04
     功能也有很大变化, 感觉使用了直接加载读取vue运行程序. 21:09
     1、报错 2、路由关系没明白。 22:25
     查看官方vux版本更新记录. 22:47
     感觉需要加vux 作者咨询.  查找作者信息,转款二维码转账并找到微信号.发起添加,希望对方能通过. 23:01 
     再次添加作者微信成功. 17-08-23 09:15
     微信沟通后，作者回复"微信这里不提供技术支持，可以直接到 Github 提 issue" 09:28
     出现些问题github 如何提issue ? 09:29
     GitHub中Issue的使用 http://www.jianshu.com/p/5ba1e7f5ad70  
     查看链接中的介绍，发现使用很简单，其中内容到编辑描述是markdown格式.自己已经很熟练 09:34

**Comment by airyland** [comment]
从 v2.2.1 到 v2.5.8 是可以直接升级的。vux demo 引用的组件是同目录的，只是在 vux-loader 做了特殊处理，这里你应该不用关心。也不要直接复制 vux 源码来用，可以用脚手架来做。

建议你建个可以重现的 repo 解决更快。

**Comment by thinkido** [comment]
npm install vue-cli -g  升级成功 vue-cli@2.8.2
     vue init airyland/vux2 vuxtest   报错 vue-cli · Failed to download repo airyland/vux2: Response code 500 20:58
