### ISSUE TITLE
手机屏幕为奇数时的confirm弹窗文字模糊问题

### ISSUE THREAD

**Issue by shawnan** [airyland/vux#1865]
比如iPhone6 是375*667的，则文字模糊很严重。
<img src="http://7xlvsv.com1.z0.glb.clouddn.com/%E6%A8%A1%E7%B3%8A.png">
找到了一种解决办法是采用flex布局，但是在body上使用的话会影响我页面上的其他布局，希望可以在vux-x-dialog这个元素上进行flex布局。实测效果是可以的，但是vux-x-dialog的z-index属性需要在显示和隐藏的时候进行控制，如果在onConfirm和onCancel方法实现的话，就需要去操作dom，与vue是思想背道而驰，所以希望作者能采用这种布局方式解决模糊的问题。
<img src="http://7xlvsv.com1.z0.glb.clouddn.com/%E6%B8%85%E6%99%B0.png">
`.vux-x-dialog{
    position: fixed;
    z-index: -1;
    top: 0;
    right: 0;
    left: 0;
    bottom: 0;
    display: flex;
    align-items: center;
    justify-content: center;
  }

var confirmDialog = document.querySelector(".vux-x-dialog");
confirmDialog.style.zIndex = 999;

this.$vux.confirm.show({
  onCancel () {
    confirmDialog.style.zIndex = -1;
  },
  onConfirm () {
    confirmDialog.style.zIndex = -1;
   }
});
`

**Comment by airyland** [comment]
拿 demo 在模拟器看的话，并不能重现你说的严重模糊的问题，无论是 window 还是 Mac。

**Comment by shing952** [comment]
我出现这种问题
![image](https://user-images.githubusercontent.com/23016067/36070055-10f7c5a6-0f2e-11e8-8974-9006c834a72f.png)
正常情况下是
![image](https://user-images.githubusercontent.com/23016067/36070059-4f8c2726-0f2e-11e8-97fd-77a1e3ae6b5e.png)

**Comment by brahmachen** [comment]
确定在手机上会出现这种问题？
