### ISSUE TITLE
x-address 能否支持配置popup的header 文字

### ISSUE THREAD

**Issue by zhump** [airyland/vux#1866]
虽然有popup-header  这个组件，但是好像只能在popup中使用，现在有需求功能是，希望可以在x-address  的popup -header 配置说明文字，可以支持下吗？

**Comment by airyland** [comment]
下个版本支持。

**Comment by sdliuzhen** [comment]
x-address好像不能用把

**Comment by airyland** [comment]
@sdliuzhen 不能用你不帖报错不帖代码就跑到两个不相关的 issue 下发垃圾，有意思？浪费所有接收到这个消息的人的时间。
