### ISSUE TITLE
大神帮忙看看  以前没这样的问题

### ISSUE THREAD

**Issue by smallrig** [airyland/vux#1869]
如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)\

**Comment by airyland** [comment]
升级 vux-loader 试试。

**Comment by smallrig** [comment]
还是不行哦 ，目前版本最新是1.1.5.  还有其他原因吗？  

const vuxLoader = require('vux-loader')
let webpackConfig = {}

module.exports = vuxLoader.merge(webpackConfig, {
  plugins: [
    {
      name: 'vux-ui'
    },
    {
      name: 'duplicate-style'
    }
  ]
})
我的引用 如下:

import { XButton }from 'vux'

**Comment by airyland** [comment]
```
let webpackConfig = {}
```
为什么要用空对象呢，这里是原来的 webpack 配置啊。

**Comment by airyland** [comment]
https://github.com/airyland/vux2/blob/master/template/build/webpack.base.conf.js

**Comment by smallrig** [comment]
是原来的对象哦！ 我把原来的对象赋给了webpackConfig

**Comment by airyland** [comment]
``` js
import { XButton }from 'vux'
```

是不是少了空格？

``` js
import { XButton } from 'vux'
```

**Comment by wuxingtao** [comment]
问题解决：我之前用vux-loader@rc1.  也出现了这个错误。
这个需要你更新vux-loader包，我的是"vux-loader": "^1.1.18",
更新后包不会马上替换，删干净vux-loader@rc。重启项目
