### ISSUE TITLE
Popup 高度设置100%,在IOS上滚动条失效

### ISSUE THREAD

**Issue by hemuqiu** [airyland/vux#1871]

**Comment by hemuqiu** [comment]
没人遇到这种情况吗？

**Comment by airyland** [comment]
code, please

**Comment by hemuqiu** [comment]
<template>
	<popup v-model="showPopup" height="100%" poistion="bottom">
		<div class="atWhoWrap selectPersonWrap" :style="{height: winHeight+ 'px'}">
		</div>
	</popup>
</template>

<script>
import { Popup } from 'vux'

**Comment by airyland** [comment]
😓  帖个 import 对解决问题没任何作用，完整代码再 reopen 吧。
