### ISSUE TITLE
XHeader 高度比原生导航栏高度少20像素然后看起来很难看怎么办?

### ISSUE THREAD

**Issue by Ruanyang2015** [airyland/vux#1873]
XHeader 高度比原生导航栏高度少20像素然后看起来很难看怎么办?

**Comment by airyland** [comment]
不上截图如何让人理解你说的难看？

**Comment by Ruanyang2015** [comment]
XHeader 高度比原生导航栏高度少20像素然后看起来很难看怎么办?
--



![image](https://user-images.githubusercontent.com/13889247/29663356-3bd465e8-88fd-11e7-900f-490e5e2fe42e.png)
就像这样

**Comment by airyland** [comment]
这是用 cordova 封装成 App? 你的建议是可以设置高度？

**Comment by Ruanyang2015** [comment]
我没有用 cordova, 只是 APP上 引用链接而已;建议可以设高度,以为直接用Xheader作为导航栏确实丑了点

**Comment by liaotup** [comment]
设置高度并没有作用阿，它增加了下方高度而已
![image](https://user-images.githubusercontent.com/10844117/46066401-276db300-c1a7-11e8-92b5-ab2704ebe053.png)

**Comment by Ruanyang2015** [comment]
很简单你在XHeader外面 套个 div ,给 div 设置一个 paddingTop 20 就可以啦,剩下的样式你想怎么调就怎么调!

**Comment by zhangshaohao** [comment]
导航栏能整体拉宽吗？如果设置x-header的高度，只有下方会拉长，里面的内容还是原来的样子
