### ISSUE TITLE
datetime插件的placeholder颜色跟真实值的颜色是一致的。

### ISSUE THREAD

**Issue by zhump** [airyland/vux#1874]
datetime插件的placeholder颜色跟真实值的颜色是一致的，跟正常popup-picker显示的不一致。如下图，
![image](https://user-images.githubusercontent.com/7962067/29661842-dbe521f4-88f7-11e7-82ef-d41254531b65.png)
能否调整成有区分的？和popup-picker、address一致的。

**Comment by airyland** [comment]
值默认为灰色，下个版本支持 `@cell-value-color` 和 `@cell-placeholder-color` 自定义。
