### ISSUE TITLE
升级vux-loader,使用懒加载报错Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by jianchengwang** [airyland/vux#1875]
升级了下vux-loader的版本，然后发现不能异步加载组件
`const Home = r => require.ensure([], () => r(require('@/views/home/Home')), 'Home') 或者 const Home = resolve => require(['@/views/home/Home'], resolve)`

控制台出现如下错误
[VUX] 提 Issue 时麻烦附上以下版本信息以及必要的显示截图、重现步骤、代码(代码请不要截图)。 
[VUX] vux@2.5.8, vux-loader@1.1.5, webpack@3.5.5, node@6.10
[VUX] 建议反馈请访问 https://github.com/airyland/vux/issues
4:480 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <App> at src/App.vue... (1 recursive calls)
         <Root>

而用import 是可以引入组件，用不过原生weui css样式写的组件就没有样式效果，用vux组件就有样式效果

**Comment by airyland** [comment]
请建个 repo 重现。vux-loader 并不会解析异步加载的相关代码。
