### ISSUE TITLE
建议。datetime组件赋初始值时，并不会根据format格式化，预期的时间格式。

### ISSUE THREAD

**Issue by zhump** [airyland/vux#1876]
`  <datetime v-model="date" format="YYYY年MM月DD日"></datetime>`

当date为1999-11-11时，预期希望组件展示就是  1999年11月11日
可是组件选择上的时间，是错误的。[bug]

而且实际组件时发生选择后，才会格式化之后的数据，当然我们可以通过赋值之前，就格式化好数据为1999年11月11日，可是希望组件可以再智能好用些。[建议]

**Comment by airyland** [comment]
1. datetime format 只支持固定连接符 `YYYY-MM-DD HH:mm:ss`，不支持这类自定义字符。
2. 没看懂。

**Comment by zhump** [comment]
明白了
如果datetime format  只支持固定连接符 YYYY-MM-DD HH:mm:ss
那2就没问题了。
2的意思是预期，data的时间会自动根据format，格式化好，但是只支持 YYYY-MM-DD HH:mm:ss，当然就无法格式化成 format="YYYY年MM月DD日"


  <popup-picker placeholder="请选择性别" :data="sexList" v-model="sex" show-name></popup-picker>

**Comment by airyland** [comment]
在组件选择器内是无法这样 format 的，但是是可以定义值的显示格式的，用 `display-format`
