### ISSUE TITLE
使用 iPhone Confirm 组件的滚动条问题

### ISSUE THREAD

**Issue by Bloom2036** [airyland/vux#1877]
https://vux.li/#/zh-CN/demos/confirm

![image](https://user-images.githubusercontent.com/18345542/29700927-047a5bb8-899b-11e7-98f1-5c0f18e83c76.png)

如官方示例

iPhone 用 safari 打开官方示例网页， 当 confirm 显示的时候滑动屏幕， 遮罩层后的内容依然可以滚动。
请问我应该怎么避免这个事情的发生？

**Comment by airyland** [comment]
#1858
