### ISSUE TITLE
关于组件的css重复引入的问题

### ISSUE THREAD

**Issue by travelk** [airyland/vux#1878]
我在审查css的时候发现会有组件的css被不停的覆盖，请问这些css有没有办法共用，看着太难受了
这是在官网demo看到的
![default](https://user-images.githubusercontent.com/14837035/29702368-9fa8a77c-89a3-11e7-9ac5-16225f16e06f.png)

**Comment by airyland** [comment]
不使用异步加载的方式。

**Comment by ron0115** [comment]
貌似全局引入也有这个问题？

**Comment by airyland** [comment]
@ron0115  dev 下有是正常的，vux-loader 上开启 duplicate style 插件，build 后应该是没有的。
