### ISSUE TITLE
scroller上拉加载两次

### ISSUE THREAD

**Issue by eric1121** [airyland/vux#1879]
用scroller首次进入数据都请求到了，但是上拉查看的时候只能看一屏然后就触发了上拉事件，重新加载的还是第一页的数据，所以我的第一页的数据就加载了2次，再上拉滚动就没问题了。。
![image](https://user-images.githubusercontent.com/24478669/29703992-79ac2cea-89aa-11e7-83b9-f8c7d4465685.png)
![image](https://user-images.githubusercontent.com/24478669/29704019-921a8826-89aa-11e7-8b42-0ac166cb4a0e.png)
![image](https://user-images.githubusercontent.com/24478669/29704123-fece8486-89aa-11e7-84d4-df0f1dfbfb73.png)
现在项目紧，大神看看是哪里的问题，如果实在改不了的话我就得改用插件了

**Comment by airyland** [comment]
scroller 组件不再维护，所以不再处理相关 issue了。
加载同一页这个问题看起来是你实现逻辑的问题并不是组件的问题。

**Comment by gantoday** [comment]
@airyland scroller 组件是很常用的组件，请问为什么不维护了呢？

**Comment by airyland** [comment]
@gantoday 我不确定用户会在 scroller 里放什么，放列表当然没问题，但是大多数用户当成 div 来用了，里面各种手势控件，无法一一适配，焦头烂额，决定放弃。
