### ISSUE TITLE
calendar在移动端无法点击选择日期

### ISSUE THREAD

**Issue by LiangFuzhi** [airyland/vux#188]
[calendar在移动端日期点击不了，在pc端就可以选择。]
demo (https://vux.li/?x-page=github_readme#!/component/calendar) 也是同样问题

**Comment by airyland** [comment]
大概今天有个小版本修复这个问题。

**Comment by LiangFuzhi** [comment]
还发现一些问题，1.年份和月份是以加2的方式选择的，例如当前是5月点击下一月变成了7月。2.当前日期的绿色的圆圈标识没有标到当前选择日。

**Comment by airyland** [comment]
@LiangFuzhi 组件已经重构了，还没发布，这些都会在新的组件修复掉。

**Comment by LiangFuzhi** [comment]
好的，期待
