### ISSUE TITLE
popup-picker 使用对象数据时，show-name属性下，组件无法正常使用。

### ISSUE THREAD

**Issue by zhump** [airyland/vux#1880]
`
 <popup-picker placeholder="请选择性别" :data="sexList" v-model="sex" show-name></popup-picker>`

`sexList:[[{ name: '男', value: 1 }, { name: '女', value: 0 }]]`

` sex: [0]`

此时popup-picker 组件无法正常发生切换和赋值。是我的用法有问题吗？后台传来的数据就是1或0。保存的时候也是1或0。
![4](https://user-images.githubusercontent.com/7962067/29706015-f4a84cb4-89b2-11e7-836f-2823ccc50cd9.gif)

**Comment by airyland** [comment]
value 用字符串

**Comment by zhump** [comment]
瞬间解决，多谢。
