### ISSUE TITLE
众多ui框架中农vux组件是最多的，但是少了一个重要组件

### ISSUE THREAD

**Issue by algesthesiah** [airyland/vux#1882]
类似于mint-ui的index-list 如果有的话vux会更好的吧 👍

**Comment by Jiiiiiin** [comment]
恩 我们项目也是自己手鲁的，这个和scroll插件很相关。

**Comment by algesthesiah** [comment]
可以推荐下类似这种组件么？或者官方打算做一个这种组件么？

**Comment by wg5945** [comment]
@axy541877028 

可以先使用mint ui的，源码也比较简单，直接扒下来用

http://elemefe.github.io/mint-ui/#/index-list

**Comment by airyland** [comment]
Moved to #139
