### ISSUE TITLE
在view-box控件中使用不了document.documentElement.scrollTop

### ISSUE THREAD

**Issue by s641135196** [airyland/vux#1883]
有这么一个需求，商品搜索页后的结果，点击进入详细页，返回的时候还需要在原来的位置。 不是默认的回到顶部。 可我使用 document.body.scrollTop = 100；document.documentElement.scrollTop = 100; 想滚动到指定的位置，可不起作用。  找了好久发现是view-box中的overflow:hidden导致的。可我什么也做不了，请问大神有什么办法让页面滚动到指定坐标 或者能满足我上面的需求也好?
精简代码如下，参考了vux官网Demo：
<view-box ref="viewBox"  body-padding-top="46px"    body-padding-bottom="55px">
     <router-view></router-view>
     ....
</view-box>

**Comment by airyland** [comment]
容器不是 document 了，所以提供了 scrollTo 方法。

**Comment by s641135196** [comment]
谢了，已经可以了，以后会注意代码格式化！

**Comment by jiangyi215** [comment]
你好，请问你能实时获取滚动距离吗？能教一下吗QQ791758820
