### ISSUE TITLE
proxy代理报错 400错误504网关超时等

### ISSUE THREAD

**Issue by JL-Code** [airyland/vux#1884]
`<html><head><title>400 Bad Request</title></head><body><h1>Bad Request</h1><per>ERR_BAD_REQUEST:
GET /api/OpportunityAndFollowList?salemanGUID=A8A4D18D-9AF5-E611-8CC0-8CDCD450DC4B&projGUID=5D76B0AD-BF28-E711-9038-8CDCD450DC4B&isuppull=1&limit=15&createdon=2099-12-30%2000:00:00 HTTP/1.1
cookie: _ga=GA1.1.930913905.1503669734; _gid=GA1.1.2010047589.1503669734
accept-language: zh-CN,zh;q=0.8,en;q=0.6
accept-encoding: gzip, deflate, br
referer: http://localhost:8080/
user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Mobile Safari/537.36
accept: application/json, text/plain, */*
connection: close
host: meunsc.oicp.net

</per></body></html>`
![image](https://user-images.githubusercontent.com/14163944/29739788-2baa9cf0-8a79-11e7-8c46-1bd3b8eff36c.png)
![image](https://user-images.githubusercontent.com/14163944/29739799-62f2faae-8a79-11e7-8edc-a2830531b95b.png)

代理报400错误，当代理域名的时候会报错，如果是同局域网的localhost:port则不会报错。希望知道的各位兄弟提供下解决方法。

**Comment by airyland** [comment]
非 vux 组件问题。并且这是业务问题了，需要自行排查。
