### ISSUE TITLE
marquee  height计算结果为0的问题

### ISSUE THREAD

**Issue by xiongmingwu** [airyland/vux#1885]
非常感谢作者贡献这么好框架，万分感激！在实践过程中发现marquee 插件存在如下问题：
正常图片：
![image](https://user-images.githubusercontent.com/31282628/29749124-dd075eaa-8b57-11e7-8403-be15e5344067.png)
异常图片：
![image](https://user-images.githubusercontent.com/31282628/29749119-b09f51ba-8b57-11e7-9f8e-191a53c7cd61.png)

我猜测是由于初始化时 我通过v-show属性隐藏了改控件，导致该控件在初始化时offsetHeight为0,。代码如下：
&lt;flexbox :gutter=&quot;0&quot; class=&quot;app-index-marquee&quot; v-show=&quot;$route.path !== '/my'&quot;&gt;
  &lt;flexbox-item :span=&quot;1/8&quot; style=&quot;flex: 0 0 30px;text-align: center;&quot;&gt;
	&lt;i class=&quot;iconfont icon-notification&quot;&gt;&lt;/i&gt;
  &lt;/flexbox-item&gt;
  &lt;flexbox-item style=&quot;margin-right: 8px;&quot;&gt;
	&lt;marquee&gt;
	  &lt;marquee-item v-for=&quot;i in 2&quot; :key=&quot;i&quot;&gt;
		{{i}}不支持一件代发，若发现存在一件代发，您的账号可能会被禁用！爱库存只为代购服务，只发货给代购。谢谢！
	  &lt;/marquee-item&gt;
	&lt;/marquee&gt;
  &lt;/flexbox-item&gt;
&lt;/flexbox&gt;
代码图片，git老是上传失败，等下补上。
建议该控件添加参数height进行控制,若未传则动态计算，若传了至该参数则直接使用传过来的参数。
还有一个问题，若滚动内容的长度不一致初始化计算的height也是有问题的！烦请您给点建议如何处理该问题.谢谢！

**Comment by xiongmingwu** [comment]
不好意思，图片还是上传不了。这个问题应该容易复现。如果无法复现问题 请您联系我。

**Comment by airyland** [comment]
标题改一下？

**Comment by xiongmingwu** [comment]
以下为控制台打印内容：
[VUX] 提 Issue 时麻烦附上以下版本信息以及必要的显示截图、重现步骤、代码(代码请不要截图)。 
[VUX] vux@2.5.8, vux-loader@1.1.5, webpack@2.7.0, node@6.9
[VUX] 建议反馈请访问 https://github.com/airyland/vux/issues
[vue-devtools] Ready. Detected Vue v2.4.2

**Comment by xiongmingwu** [comment]
@airyland 该问题能否给点建议？ 或者什么时候方便优化该问题。

**Comment by airyland** [comment]
先用 v-if 试试。

**Comment by xiongmingwu** [comment]
非常感谢！
