### ISSUE TITLE
main.js中 引入 DatetimePlugin 报错

### ISSUE THREAD

**Issue by pper2024** [airyland/vux#1886]
main.js中 引入 DatetimePlugin 报错,其他所有组都能使用正常,Datetime以components方式使用也没有问题,
报错截图,如下:

![image](https://user-images.githubusercontent.com/6078193/29750294-9fef90b0-8b6f-11e7-947e-2ee120a8f3b0.png)

**Comment by airyland** [comment]
涉及到 webpack，并且没有其他人遇到这个问题，麻烦建个可以重现的 repo 吧。
