### ISSUE TITLE
previewer组件的扩展需求

### ISSUE THREAD

**Issue by cinos1** [airyland/vux#1888]
希望可以为平previewer组件中增加goto方法。
翻看代码发现平reviewer封装了photoswipe组件，然而并没有实现官方的goTo(index)方法，现在我们项目中需要在打开图片预览后点击下方按钮跳页。希望官方支持一下吧，以免我们抽出这部分功能自己再做一遍，3x。
代码部分如下：
```javascript
 goto(index){
      this.photoswipe.goTo(index);
    }
```

**Comment by airyland** [comment]
可以添加，但是不明白你这里怎么交互的，打开预览后是 100% 遮罩覆盖，下方按钮在哪里？

**Comment by cinos1** [comment]
@airyland 我们做的是房地产项目，这里做的是房源图片预览，下方是分类按钮如：效果图、户型图、样板间等。目前是使用css 的fixed进行绝对定位，将z-index设置为2000，强制在遮罩上层，屏幕下方固定显示的；因此在点击这些按钮的时候需要进行图片定位。

**Comment by airyland** [comment]
下个版本支持，你也可以使用 this.$refs.previewer.photoswipe.method 来直接调用。

**Comment by code-admin** [comment]
> 下个版本支持，你也可以使用 this.$refs.previewer.photoswipe.method 来直接调用。

你说的就像wxSDK 那样？ wx.previewImage(params);

我自己把 Previewer 包了一下，然后注册到全局插件里面去了 实现了全局调用

**Comment by m2maomao** [comment]
我也遇到了同样的问题，图片上面需要显示标题，而组件只提供了before,after,都是在顶部显示的，更要命的是标题可以点击跳转到其他页面，我看photoswipe支持html但是previwer只支持src传图，下个版本会支持吗？
