### ISSUE TITLE
loading组件过度的瞬间层级不对。

### ISSUE THREAD

**Issue by w2819** [airyland/vux#1892]
![rm29njf _ 1iv4 vyxz 6w](https://user-images.githubusercontent.com/8953012/29817791-f7393830-8ceb-11e7-8e5a-10d7d684f04d.png)
经测试是 name="vux-mask"这个动画导致。版本2.2.0

**Comment by airyland** [comment]
目测动画并没有修改 zIndex 值，升级到最新版本或者上个重现代码看看。

**Comment by Qiuziscorpio** [comment]
请问解决了吗？
