### ISSUE TITLE
当swipe的swiper-item设置为2个时，loop跟swiper-item设置为3时表现不一致

### ISSUE THREAD

**Issue by arssam** [airyland/vux#1894]
版本： "vux": "^2.5.8"

当swipe的swiper-item设置为2个，第二张跳到第一张时，不是向右滑动到第一张，而是向左滑动到第一张，这种一会左，一会右给人感觉很不好。希望能修复这个bug。

代码：
![image](https://user-images.githubusercontent.com/18626836/29868978-98a876be-8db3-11e7-99d7-aa78194b4b1d.png)

**Comment by airyland** [comment]
使用 list 时是支持两个循环的，使用 swiper-item 因为实现的原因暂时无法循环。现在你可以直接渲染两次 swiper-item 来实现循环，并且把 dot 隐藏。

**Comment by airyland** [comment]
因为实现的原因至少3个 swiper-item 才能循环，该 issue 关闭。
