### ISSUE TITLE
scroller 组件滚动不了，滚动后会弹回初始状态

### ISSUE THREAD

**Issue by hemuqiu** [airyland/vux#1895]
![image](https://user-images.githubusercontent.com/20644383/29904803-33e4c6a8-8e3d-11e7-8214-874fe931a684.png)

设置横向滚动，滚动完后会自动弹回，要怎么处理呢？

**Comment by airyland** [comment]
抱歉，已不维护。可以用第三方来代替 https://github.com/HcySunYang/finger-mover

**Comment by hemuqiu** [comment]
好的，谢谢
