### ISSUE TITLE
XInput加上type后，max限制长度输入无效

### ISSUE THREAD

**Issue by txl1123** [airyland/vux#1896]
`<x-input title="联系电话" v-model="json.userTel" placeholder="必填，您的重要联络信息" is-type="china-mobile" type="number"  :max="11" ></x-input>`
加上type=“number”后，max限制输入无效。虽然能验证超过了长度，但是并不能限制输入

**Comment by airyland** [comment]
max 在组件内部相当于 maxlength，而 html 属性 maxlength 并不会限制 number 类型长度。。

**Comment by txl1123** [comment]
噢。我还以为是有js控制的

**Comment by wg5945** [comment]
之前考虑过，但是并不能很好的实现

参考这个pr：https://github.com/airyland/vux/pull/1603

手机号码的话直接使用 type="tel" 吧
