### ISSUE TITLE
Calendar组件选中的日期，再点击该日期就自动取消了，并且值为空

### ISSUE THREAD

**Issue by txl1123** [airyland/vux#1897]
Calendar组件选中的日期，再点击该日期就自动取消了，并且值为空。
但是我试过demo，点击已选中的日期并不会出现这个问题。所以我不知道是哪个属性引起的
`<calendar title="出发日期" placeholder="选择出发日期" :start-date="datetimeRange.startDate" :end-date="datetimeRange.endDate" v-model="json.startDate" :weeks-list="weeklst" :highlight-weekend="true" :return-six-rows="false" @on-change="changeDate"></calendar>`
这是我的代码。公司网络上传不了图片，如果有QQ群可以加一下讨论

**Comment by airyland** [comment]
请查看 v2.5.9 changelog

https://vux.li/#/zh-CN/changes
