### ISSUE TITLE
官方演示站的range错误

### ISSUE THREAD

**Issue by yeahTibbers** [airyland/vux#190]
### 描述：

1. 样式好像不怎么对，都没有对齐 
2. 拖动range圆圈基本不动，有一定几率会动，就算动了也只能动一格

### Steps to reproduce the problem
![0uzy g dhtp6 x 6 286 r](https://cloud.githubusercontent.com/assets/10751521/15415978/3fbd0ace-1e79-11e6-96cd-b72d81430f66.png)

**Comment by airyland** [comment]
感谢反馈，已修复。
