### ISSUE TITLE
swipeout的问题：按照官方文档写的demo，发现当已经打开一个按钮菜单后，再去点击另外一行不会关闭之前打开的按钮菜单，导致可以同时打开多行的按钮菜单

### ISSUE THREAD

**Issue by youngthinker** [airyland/vux#1900]
![img20170831_182712](https://user-images.githubusercontent.com/3690138/29918983-0d2c44a4-8e7a-11e7-93bf-6c2fdc3dab3c.png)

**Comment by airyland** [comment]
学习下 markdown 用法吧。代码不要截图，难以重现。
