### ISSUE TITLE
关于组件Search使用出现$t的问题。

### ISSUE THREAD

**Issue by city8866** [airyland/vux#1903]
你好。本来问这个问题是做了一些工作。但是还是没有解决。首先vux-loader是大于1.0.58（最新版）,其实看到有人已经问过这个问题。我也重新使用npm 安装vux,vux-loader。但是当我使用search组件是还是报错。希望能解决下。报错截图了。
[
![new](https://user-images.githubusercontent.com/24402516/29963008-e3d8935a-8f37-11e7-91d9-34ed2fb9c1f9.png)
](url)

**Comment by airyland** [comment]
你配置 i18n 吗，如果你配置了多语言，而没有引入 i18n 插件，比如  vuex-i18n 会报错。

**Comment by city8866** [comment]
看了一下你的Search组件的源码，其中有一段是
` <form class="weui-search-bar__form" @submit.prevent="$emit('on-submit', value)" action=".">
        <div class="vux-search-mask" @click="touch" v-show="!isFixed && autoFixed"></div>
        <div class="weui-search-bar__box">
          <i class="weui-icon-search"></i>
          <input type="search" class="weui-search-bar__input" :id="`search_input_${uuid}`" :placeholder="placeholder" autocomplete="off" :required="required" v-model="currentValue" ref="input"
          @focus="onFocus"
          @blur="onBlur"/>
          <a href="javascript:" class="weui-icon-clear" @click="clear" v-show="currentValue"></a>
        </div>
        <label :for="`search_input_${uuid}`" class="weui-search-bar__label" v-show="!isFocus && !value">
          <i class="weui-icon-search"></i>
          <span>{{placeholder || $t('placeholder')}}</span>
        </label>
      </form>`
有一个search_input_${uuid}这个引入i18n了，这个怎么修改呢
