### ISSUE TITLE
关于loading的方法报错问题

### ISSUE THREAD

**Issue by eric1121** [airyland/vux#1904]
![image](https://user-images.githubusercontent.com/24478669/29962952-a576feee-8f37-11e7-85be-4fb7b629ba5c.png)
![image](https://user-images.githubusercontent.com/24478669/29962974-bebaf202-8f37-11e7-9f76-7fdd176df6e5.png)
![image](https://user-images.githubusercontent.com/24478669/29962986-d07f69dc-8f37-11e7-8119-416f56ecd649.png)
![image](https://user-images.githubusercontent.com/24478669/29963023-f32b47d0-8f37-11e7-8a6d-0b5747d67e20.png)
求解

**Comment by airyland** [comment]
console 一下 this.$vux 看看里面有没有你引入的插件。
