### ISSUE TITLE
自己封装组件使用用原生的weui css样式没有效果

### ISSUE THREAD

**Issue by jianchengwang** [airyland/vux#1909]
发现现在官方的组件是用less重写了weui,然后在封装的组件上引入重写的样式，如果我想用原生的weui封装组件，是不是要自己另外引入weui的css样式，记得之前可以直接使用weui样式的。

**Comment by airyland** [comment]
VUX 把 WeUI 样式打散到各个组件了，所以你需要自行引入，可以直接从 src/styles 里找到相应的文件引入。
