### ISSUE TITLE
使用Sticky时无效并报错

### ISSUE THREAD

**Issue by txl1123** [airyland/vux#1912]
Vux@2.5.8
template代码
`<template>
  <div>

		<sticky scrollBox="vux_view_box_body" :check-sticky-support="false" :offset="46">
			<tab :line-width="1">
				<tab-item :selected="demo4 === item" v-for="(item, index) in list4" @click="demo4 = item" :key="index">{{item}}</tab-item>
			</tab>
		</sticky>
		<div v-for="i in 40 ">{{i}}</div>
	</div>
</template>`
js代码

```’ import{ Tab, TabItem, Sticky, Divider} from 'vux'
export default {
  components: {
    Tab,
    TabItem,
    Sticky,
    Divider,
  },
  data () {
    return {
      list4: ['正在放映', '即将上映'],
      demo4: '即将上映',
      demoDisabled: 'A',
      index: 0,
      getBarWidth: function (index) {
        return (index + 1) * 22 + 'px'
      }
    }
  }
}```

```if (typeof scrollBox === 'string') {
    scrollBox = document.getElementById(scrollBox)
  }```
执行完scrollBox=null;导致报错

![default](https://user-images.githubusercontent.com/9738404/30017973-b6fb28fe-918d-11e7-903a-e3fdb6426992.png)
![default](https://user-images.githubusercontent.com/9738404/30018893-3da0b286-9191-11e7-803e-720d76fd8e7e.png)

**Comment by airyland** [comment]
`scrollBox="vux_view_box_body"`

话说区域是否真的是在这个容器内？如果并不是而是 body 请按照文档说明不要配置。

**Comment by txl1123** [comment]
的确是按照文档写的。就按照demo写的，之前用的时候也是这样

**Comment by airyland** [comment]
建 个 repo 吧。

**Comment by shiLinQing407** [comment]
不要照着demo 复制黏贴，还不如看看文档
`<div id="content">
    <div style="height:44px">
      <sticky scroll-box="content" ref="sticky" :check-sticky-support="false">
        <tab>
          <tab-item selected @on-item-click="selectStatus(4)">未使用</tab-item>
          <tab-item @on-item-click="selectStatus(5)">已使用</tab-item>
          <tab-item @on-item-click="selectStatus(6)">已过期</tab-item>
        </tab>
      </sticky>
    </div>
     <div class="scroller">scroll-content</div>
</div>`
