### ISSUE TITLE
头部无法固定

### ISSUE THREAD

**Issue by xfcgaga** [airyland/vux#1913]
以下代码已经很精简了，为什么头部还是无法固定，求解答，谢谢！

`<template>
  <div style="height:100%;">
   <view-box ref="viewBox" body-padding-top="46px" body-padding-bottom="0px">
     <x-header slot="header" style="position:absolute; width:100%; left:0; top:0; z-index:100;"></x-header>
     <p v-for="i in 100" v-text="i"></p>
   </view-box>
 </div>
</template>

<script>
import { ViewBox, XHeader } from 'vux'

export default {
  components: {
    ViewBox,
    XHeader
  }
}
</script>

<style lang="less">
html, body {
  height: 100%;
  width: 100%;
  overflow-x: hidden;
}
</style>
`

- view-box 外层的 div 已经设置 height:100%；
- html, body 已经设置 height:100%；
- x-header 已经设置 position:absolute

**Comment by airyland** [comment]
body 和 view-box 外层之前是不是还有一个 div?

**Comment by xfcgaga** [comment]
原来是这样，谢谢。vux.li 文档里的所有 demo 都省略了 XHeader ／ view-box 代码，所以不是很了解，建议不必省略。

**Comment by dujinyu** [comment]
这个样子，我如果有很多个div，岂不是每一个都要设置？
