### ISSUE TITLE
vue-cli创建的项目，引入vux，run 正常，build报错。

### ISSUE THREAD

**Issue by SkyGrass** [airyland/vux#1915]
项目创建好之后，我随意引入的组件。官网的配置，我也做了。
```
import { AlertPlugin, ToastPlugin } from 'vux'

Vue.use(AlertPlugin)
Vue.use(ToastPlugin)
```
cnpm run dev 是正常的。
cnpm run build的时候，会报下面的错误
Unexpected token name «i», expected punc «;»
我查下了下源码路径，发现是 let语法的位置。
貌似是不识别 for 循环的里的let
请问下：我还需要加入配置，使得项目能够build成功? 感谢。

**Comment by airyland** [comment]
请使用 airyland/vux2 模板，如果不是该模板请确保已经配置了 vux-loader。

**Comment by SkyGrass** [comment]
```
const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui', 'duplicate-style']
})
```
为什么能run，不能build 呢？

**Comment by airyland** [comment]
更可能的是 webpack 的问题而不是组件的问题了。

**Comment by airyland** [comment]
出错的代码是哪个文件哪一行

**Comment by SkyGrass** [comment]
文件：vux/src/libs/plugin_helper.js
```
for (let i in $vm.$options.props) {
    if (i !== 'value') {
      defaults[i] = $vm.$options.props[i].default
    }
  }
  const _options = objectAssign({}, defaults, options)
  for (let i in _options) {
    $vm[i] = _options[i]
  }
```
for 循环里的let , 我尝试改为 var 就不报....，我怀疑是我配置有问题。

**Comment by airyland** [comment]
不能确定问题，打个包给我看看吧。 i#mao.li

**Comment by SkyGrass** [comment]
我在oschina 里上传了报错项目。github执行了导入。
您有时间可以看下。http://git.oschina.net/593582402/vuecliwithvuxbuilderror

**Comment by qc963430178** [comment]
我下载了 demo也是 run dev ok build 报错 不行 不知道什么原因
![image](https://user-images.githubusercontent.com/11779275/30052351-ba349e54-9257-11e7-822b-e1194a98e99d.png)



0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vux@2.5.10~prebuild: vux@2.5.10
6 info lifecycle vux@2.5.10~build: vux@2.5.10
7 verbose lifecycle vux@2.5.10~build: unsafe-perm in lifecycle true
8 verbose lifecycle vux@2.5.10~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\dev\html\replay\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\qc963430178\AppData\Local\Microsoft\WindowsApps;C:\Users\qc963430178\AppData\Roaming\npm
9 verbose lifecycle vux@2.5.10~build: CWD: E:\dev\html\replay
10 silly lifecycle vux@2.5.10~build: Args: [ '/d /s /c',
10 silly lifecycle   'node build/build.js && rimraf docs/demos/v2/ && mkdirp docs/demos/v2 && cp -r docs/demos/temp/* docs/demos/v2/' ]
11 silly lifecycle vux@2.5.10~build: Returned: code: 1  signal: null
12 info lifecycle vux@2.5.10~build: Failed to exec build script
13 verbose stack Error: vux@2.5.10 build: `node build/build.js && rimraf docs/demos/v2/ && mkdirp docs/demos/v2 && cp -r docs/demos/temp/* docs/demos/v2/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid vux@2.5.10
15 verbose cwd E:\dev\html\replay
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error vux@2.5.10 build: `node build/build.js && rimraf docs/demos/v2/ && mkdirp docs/demos/v2 && cp -r docs/demos/temp/* docs/demos/v2/`
22 error Exit status 1
23 error Failed at the vux@2.5.10 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by SkyGrass** [comment]
@qc963430178  你和我报错还不一样，你这个报错我见过，但是能完成build，我报错直接是 build error.

**Comment by airyland** [comment]
@SkyGrass 升级 vux-loader 然后在 webpack base 里把 symlink 改为 true 吧，居然在一周前这个地方配置修改了。没猜错你是用 cnpm 安装的，如果用 yarn 应该不会报错。

**Comment by airyland** [comment]
@qc963430178 报错很明显吧，cp 命令不存在，和组件没有问题，用 git bash 或者其他命令行工具吧。

**Comment by SkyGrass** [comment]
@airyland 果然OK了。十分感谢。 我是用的cnpm。
