### ISSUE TITLE
iOS10 datetime 以插件形式调用显示

### ISSUE THREAD

**Issue by jkllx** [airyland/vux#1916]
```
<div id="headtop">
      <group >
        <x-button type="primary" @click.native="showPlugin">{{ date }}</x-button>
      </group>
</div>
```

```
 showPlugin()

 {
        let self = this;
        let startDate = (new Date()).getFullYear() - 1;
        let date = new Date();
        let year = date.getFullYear();
        let month = date.getMonth() + 1;
        month = (month < 10 ? "0" + month : month);
        let endDate = (year.toString() + '-' + month.toString());
        this.$vux.datetime.show({
          cancelText: '取消',
          confirmText: '确定',
          format: 'YYYY-MM',
          yearRow: '{value}年',
          startDate: startDate.toString(),
          endDate: endDate,
          monthRow: '{value}月',
          value: this.date,
          onConfirm(val) {
            self.date = val;
            self.getTable();
            self.$nextTick(function () {
              self.setScroll();
            });
          },
          onShow() {
          },
          onHide() {
          }
        })
      },
```
andorid是正常的
![image](https://user-images.githubusercontent.com/17638732/30043743-d47945d4-922b-11e7-94c7-3fe1a71ceb93.png)
ios就有问题了
![image](https://user-images.githubusercontent.com/17638732/30043931-241a92c2-922d-11e7-9bcb-35496be57fbc.png)

**Comment by airyland** [comment]
代码请拜托格式化。
两个手机的浏览器环境不提一下？

**Comment by jkllx** [comment]
好的，浏览器都用的QQ浏览器

**Comment by airyland** [comment]
访问 VUX demo 会有问题吗？

**Comment by jkllx** [comment]
demo访问没有问题，那我找找我代码的原因

**Comment by airyland** [comment]
也试试检查下 autoprefix 配置。

**Comment by jkllx** [comment]
好的

**Comment by shiLinQing407** [comment]
@452394856 你好，我也遇到这个问题，请问解决了吗？

**Comment by jkllx** [comment]
@shiLinQing407 还没有，我的ios设备放在家了，我晚上回去再试，弄好了我会告诉你的

**Comment by shiLinQing407** [comment]
@452394856  me too

**Comment by shiLinQing407** [comment]
[https://www.oschina.net/news/85794/vux-2-3-7](url)
v2.3.7 更新内容：

Datetime

[feature] 可以使用 :show.sync 来控制控件显示 #1358

[fix] 修复格式为 YYYY-MM 时的日期范围错误 #1528

我的是"vux": "^2.5.11"  "vux-loader": "^1.1.5", 准备试一下2.3.7版本···

**Comment by airyland** [comment]
@shiLinQing407 picker 底层基本没有调整过，样式也没有调整，出问题的浏览器访问 demo 也没问题，所以更可能是使用问题。

**Comment by shiLinQing407** [comment]
我是个新手， 代码是这样的：
template:
`<datetime title="日期" format="YYYY年MM月" :start-date="startDate" :end-date="endDate" v-model="date" clear-text="清空" @on-clear="clearDate"></datetime>`

script:
`  import {Group, Datetime} from 'vux';`
```
export default{
data(){
        date: '',
        startDate: '',
        endDate : '',
},
 created() {
   this.setNowYear();
 },
 methods{
   setNowYear(){
        let now = new Date();
        let year = now.getFullYear();
        let month = now.getMonth() + 1;
        this.$data.startDate = year +'-1';
        this.$data.endDate = year +'-'+ month;
      },
}`
```
使用 QQ浏览器：
在浏览器上&Android上显示没有问题。在iphone7上显示不行。

**Comment by shiLinQing407** [comment]
可能跟我代码执行的先后有关，导致组件没获取到我的配置。

**Comment by airyland** [comment]
和问题无关的：为什么要用 this.$data. 来设值？
为什么 startDate, endDate 用年-月，不用年-月-日？

**Comment by shiLinQing407** [comment]
为什么要用 this.$data. 来设值？
A: 看网络教程学的 兴许不够规范，能用就没去多想了。

为什么 startDate, endDate 用年-月，不用年-月-日？
A: 因为业务需求， 只需筛选到月份， 不考虑具体日期。

**Comment by airyland** [comment]
@shiLinQing407 你理解错了，start-date end-date 是开始结束日期，必须为固定 年月日，这和你渲染格式无关。
另外 format 不支持特殊字符。。`format="YYYY年MM月"` 这个支持不了，只能为 YYYY-MM-DD HH:mm:ss 这样的固定格式。

**Comment by shiLinQing407** [comment]
多谢指教。

那有办法只渲染年月格式的吗？

**Comment by airyland** [comment]
上面的固定格式是指可以指定一截，比如  YYYY-MM

**Comment by jkllx** [comment]
我也找到原因了，就是start-date end-date的原因，必须指定为年月日，不然再ios上就有问题，android可以

**Comment by shiLinQing407** [comment]
是的，我只需要到月份为止 ；所以我打算换个组件

**Comment by jkllx** [comment]
@shiLinQing407 你没有明白意思，start-date end-date必须是年月日，但是显示你可以指定格式，比如说YYYY-MM，绝对可以满足你的需求

**Comment by shiLinQing407** [comment]
原来如此 下午试试看。谢谢
