### ISSUE TITLE
使用tabbar的问题

### ISSUE THREAD

**Issue by kufei88** [airyland/vux#1919]
使用tabbar做为导航栏,vue-router当路由,页面效果如下
https://segmentfault.com/q/1010000011038025
我把问题提到segmentfault上面了,这个上面我不知道怎么加图片,能帮忙看一下吗

**Comment by airyland** [comment]
非 100% 布局要自行改为 fixed 定位。

**Comment by kufei88** [comment]
谢谢你,搞定了,这个问题搞了两天了

**Comment by airyland** [comment]
对于定位，文档没有详细说明，已经更新。

**Comment by fengshengxie** [comment]
改为fixed 定位后，chrome模拟手机的正常的，但是用手机打开，实际情况，还是跟着走，官方的例子，加上<br />换行也是这样的情况，iphone7
sticky改为这个可以解决。
