### ISSUE TITLE
filter friendly-time 替换 TZ ?

### ISSUE THREAD

**Issue by ph2-cst** [airyland/vux#192]
filter [friendly-time](https://github.com/airyland/vux/blob/master/src/filters/friendly-time.js#L2)

```javascript
let date = (typeof time === 'number') ? new Date(time) : new Date((time || '').replace(/-/g, '/').replace(/[TZ]/g, ' '))
```

请问基于什么考虑，替换掉 `T` `Z`

这样， `Fri, 20 May 2016 11:00:35 GMT` `Fri May 20 2016 19:00:14 GMT+0800` 会有问题

**Comment by airyland** [comment]
额，历史代码，原因已经不可考究。。

**Comment by airyland** [comment]
发个PR吧。

**Comment by ph2-cst** [comment]
话说time是 `undefined`，会返回 NaN-NaN..... 感觉不太好

**Comment by airyland** [comment]
time有格式要求，不传规范的参数当然不能得到预期的效果。

**Comment by ph2-cst** [comment]
返回空串呢

**Comment by airyland** [comment]
为什么会有这个传空参数的需求？

**Comment by ph2-cst** [comment]
只是出于出错时显示NaN给用户不好的体验
不过这样也好 强制程序做错误处理

**Comment by ph2-cst** [comment]
不过
这样就要加多 `v-show="!date"` 如果返回 `''` 好像就不用额外的判断

**Comment by airyland** [comment]
出错时说明开发者使用有误，我觉得这个问题的处理方式不应该是程序内部来显示一个空串。空字符串事实上也不是良好的体验。虽然可以throw一个error, 但是觉得没必要。总结：这个问题将不做处理。

你只要确保有传入正确参数就行了，为什么要考虑v-show的问题？

**Comment by ph2-cst** [comment]
嗯 这个问题无关重要
时间有错要隐藏起来 总不能显示当前或者NaN吧 
不能保证后台返回的数据总是正确吧

**Comment by airyland** [comment]
`不能保证后台返回的数据总是正确吧`
连接口数据格式都不能保证，那么团队开发也相当没有规范吧。。

**Comment by airyland** [comment]
如果确实有问题，`v-if="serverData" `就行了，其实跟这个filter是无关的。

**Comment by ph2-cst** [comment]
是的
