### ISSUE TITLE
按照官方文档下载了脚手架之后， 改变路由就报错，

### ISSUE THREAD

**Issue by 554512097** [airyland/vux#1922]
因为官方下载的文档路由是写在main.js里面的， 我把路由写入router 文件下的 index.js 里面之后就报错

import Vue from 'vue'
import Router from 'vue-router'
import home from '@/components/home'
Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'home',
      component: home
    }
  ]
})
这是我router 文件的js 代码，还是下载下来的代码，只是改了个名称

/ The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import FastClick from 'fastclick'
import VueRouter from 'vue-router'
import App from './App'
// import Home from './components/home'

Vue.use(VueRouter)

/*
const routes = [{
  path: '/',
  component: Home
}]

const router = new VueRouter({
  routes
})
*/

FastClick.attach(document.body)

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  router,
  render: h => h(App)
}).$mount('#app-box')
这是main.js 改动后的代码，  不知道哪里错了

**Comment by airyland** [comment]
报错不帖报错信息那么这个世界上没人能帮你了，自行解决吧，再见。
