### ISSUE TITLE
如何处理panel，swiper等组件内image加载失败后显示默认图

### ISSUE THREAD

**Issue by guiter** [airyland/vux#1923]
看了组件源码，img标签似乎没有添加error指令及参数，请问有什么解决方案可以解决图片加载失败后显示默认图

**Comment by airyland** [comment]
暂时未实现。

**Comment by 623023808** [comment]
可以用vueLazyLoad

**Comment by guiter** [comment]
vueLazyLoad 使用需要在img标签加指令吧，跟vux组件结合不了

**Comment by 623023808** [comment]
那就自己打开vux组件代码绑定error事件啦，可以自己改的，很方便

**Comment by guiter** [comment]
嗯，目前是这样处理，但是不好维护，期待后续vux会加上
