### ISSUE TITLE
Andriod 使用WechatPlugin 问题

### ISSUE THREAD

**Issue by guoquan913** [airyland/vux#1924]
最近在Andriod 测试的时候发现调用微信JSSDK时候，不成功。 必须在右上角的下拉中菜单（三个点）点击刷新才行？ 又没有遇到过? 期待回复

**Comment by airyland** [comment]
这个和组件没什么关系了，组件仅仅封装了 jssdk 代码。有问题试试直接引入官方 cdn 链接。
