### ISSUE TITLE
如何获取表单的值呢？貌似在文档里面没有找到啊

### ISSUE THREAD

**Issue by xiangjin-shen** [airyland/vux#1930]

**Comment by airyland** [comment]
组件 v-model 绑定的值不就是表单值。

**Comment by xiangjin-shen** [comment]
@airyland 对，我刚刚也发现了，思维定式了 ，之前以为可以像jquery一样的 用 类似 $("#XXXX").val()这种方式获取的，不过事实证明   v-model  用起来更方便
