### ISSUE TITLE
Previewer只支持一组图片放大预览吗？请问假如有两组图片 怎么配置

### ISSUE THREAD

**Issue by suizhiwen** [airyland/vux#1931]
如题，Previewer只支持一组图片放大预览吗？请问假如有两组或者多组图片 怎么配置，谢谢，哪位朋友帮忙解答一下

**Comment by wg5945** [comment]
https://github.com/airyland/vux/issues/1625#issuecomment-311945241

你要的是这个么

**Comment by airyland** [comment]
使用基本是一致的，只是分成两个 Previewer，分别用不同的 ref 而已。

**Comment by HongHaiyang** [comment]
我是这样做的，Previewer 组件还是只用一次，第二组图片点击触发的时候把 Previewer 组件绑定的数组替换成新一组图片的信息就行了。
