### ISSUE TITLE
一个奇怪的问题，组件位置错乱

### ISSUE THREAD

**Issue by simphp** [airyland/vux#1933]
正常图:
![1](https://user-images.githubusercontent.com/4106797/30203204-f55b02fc-9446-11e7-801b-629dfe3b6122.png)

错乱的:
![2](https://user-images.githubusercontent.com/4106797/30203213-01b27224-9447-11e7-8b24-93fa56216804.png)

demo链接 : http://mp6wdillq.weshare.jscss.com/weshare_test

测试手机：小米手机 微信浏览器

UA:
`You are using WeChat 6.5.13.1100 on a Xiaomi Mi 5 running Android 7.0
Mozilla/5.0 (Linux; Android 7.0; MI 5 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043507 Safari/537.36 MicroMessenger/6.5.13.1100 NetType/WIFI Language/zh_CN`

出现情况：第一次进去正常，连续切换多次路由后，就会出现错乱。奇怪的是这种现象并不能稳定的重现，多次切换后基本上都会出现，没有发现什么规律。

最新发现的情况是 1.进入页面 2.切上面的Tab到"网址"或"公众号"3.切换下面的Tabbar到"我",4.切换Tabbar到"植入"，此时多数情况下Tab和ButtonTab组件已经错乱了。

Chrome模拟并未出现过这种情况.

**Comment by airyland** [comment]
可以调试到错乱的 div 嵌套或者样式异常吗？这看着像是浏览器的问题。

**Comment by simphp** [comment]
没有发现异常。这个问题困扰了好久，能不能帮助看下。

**Comment by RenShine** [comment]
@simphp  你可以考虑用微信开发者工具看看能不能重现到BUG  这种CSS问题有F12调试就好方便定位很多

**Comment by simphp** [comment]
@RenShine chrome和微信开发者工具都正常,只有在手机微信浏览器才出现这种情况.

**Comment by Evansy** [comment]
@simphp 安卓机的话。微信开启debug模式，下次重现，不要动它，可以通过chrom连接设备的remote device调试来查看。

**Comment by Evansy** [comment]
@simphp 目测是样式错乱，进入我，上面的样式就略有变形了。
![2017-09-18 16 24 52](https://user-images.githubusercontent.com/17985050/30533837-fc1d22b0-9c8d-11e7-8e77-cbbfa983423e.png)
