### ISSUE TITLE
有没有类似 起点 最近阅读的悬浮 和最近阅读的侧边弹出方式

### ISSUE THREAD

**Issue by gandyf** [airyland/vux#1934]
有没有类似 起点手机版 最近阅读的悬浮 
点击最近阅读 他的弹出层是侧边弹出方式是满屏就左边有50的黑边 点击黑边就消失
谢谢

**Comment by airyland** [comment]
#139 请到这里提，并且给出界面截图。

**Comment by gandyf** [comment]
最近阅读
![qq 20170908221911](https://user-images.githubusercontent.com/31764781/30216228-e0e8117c-94e4-11e7-8188-b3150fbd75c5.png)

点击 最近阅读的效果
![qq 20170908221941](https://user-images.githubusercontent.com/31764781/30216149-9d15b80a-94e4-11e7-8455-09be6646cc46.png)
