### ISSUE TITLE
swiper组件list本地图片该如何写，谢谢

### ISSUE THREAD

**Issue by gandyf** [airyland/vux#1937]
按照作者您的范例，我的写法如下：

const imgList = [
  '../assets/img/IMG_0205'
]

const demoList = imgList.map((one,index) => ({
    url: 'javacript:',
    img: one
}))
图片路径能找到，但是图片无法加载出来，求解，谢谢

**Comment by agileago** [comment]
你可以试试这样    

```javascript
const imgList = [
  require('../assets/img/IMG_0205')
]
```
