### ISSUE TITLE
circle组件容器宽度小于组件内默认view-box宽度会被截取

### ISSUE THREAD

**Issue by wulucxy** [airyland/vux#194]
### Version
0.0.117

### Android or iOS, which browser?
all

### Your Codes 

``` html
<div class="progressCircle" style="width:44px;height:44px;">
       <circle :percent="percent1" :stroke-width=10 stroke-color=#04BE02>
               <span>{{item.percent}}</span>
      </circle>
 </div>
```

### Expected behavior and actual behavior.
当我执行circle组件时，如果外围组件width和height小于默认的100的话，view-box会截取展示一部分，这个不符合我们的需求。最好是view-box可以动态符合容器的比例，而不是限制死0 0 100 100尺寸

### Steps to reproduce the problem
只需要设置外围容器宽度和高度小于100就必现

**Comment by wulucxy** [comment]
@Airyland 麻烦帮忙看看，本身对svg不是特别熟悉。看下是不是我的描述有问题

**Comment by airyland** [comment]
PR is welcome~
