### ISSUE TITLE
关于以插件形式调用 ConfirmPlugin , 会导致提示Vux打包过大的问题

### ISSUE THREAD

**Issue by cnlinjie** [airyland/vux#1940]
vux 和vux-loader版本:
```js
"vux": "^2.5.0"
"vux-loader": "^1.1.1",
```
目前已经在webpack.base.js 里面配置:
```js
module.exports = vuxLoader.merge(webpackBaseConf, {
  plugins: ['vux-ui','progress-bar', 'duplicate-style']
})

```
已经生效，开发了一个月多月一直没什么问题。
今天想使用ConfirmPlugin 插件时，发现在单独一个页面引入的会失败，后在根据文档示例
```js
import  { ConfirmPlugin } from 'vux'
Vue.use(ConfirmPlugin)
```
 
然后在页面调用
```js
this.$vux.confirm.show({
                    title: 'title',
                    content: 'content。',
                    onConfirm () {
                       alert('yes');
                    }
                });
```
则可以使用，但是会console 会提示

![image](https://user-images.githubusercontent.com/3601638/30239128-60736da8-9588-11e7-8194-b2232f937456.png)

**Comment by airyland** [comment]
在哪个文件引入

**Comment by cnlinjie** [comment]
想在单页（.vue)引进，没成功，提示 confirm 不存在
现在是在main.js 里面引入 @airyland

**Comment by airyland** [comment]
插件要在 main.js 里引入，否则 Vue 实例可能都不是同一个了。
尝试升级 vux-loader 看看。如果不行可以建个 repo 重现。

**Comment by cnlinjie** [comment]
好的，我再试一试，不行我建立一个repo

**Comment by cnlinjie** [comment]
升级了vux-loader 之后再运行之后依然如故，不知道是什么影响了，建立了一个简单的repo，感谢 @airyland 。

https://github.com/cnlinjie/vux-confirm

**Comment by airyland** [comment]
主要是配置兼容问题，把 babel-loader 的 use 改成  `loader: 'babel-loader'` 或者直接升级 vux-loader 到 1.1.7 可以解决。

**Comment by cnlinjie** [comment]
感谢，速度很快。 @airyland
