### ISSUE TITLE
css方面的建议

### ISSUE THREAD

**Issue by 2609974827** [airyland/vux#1943]
```
希望可以将weui的样式统一引入，组件内只放置组件特殊样式。
原因：
一：修改样式的时候可以直接修改weui
二：将项目全局样式有个把控
三：使用异步组件的方式会尽可能少的出现样式的重复
建议：
weui的样式可以通过webpack的配置使用
```
谢谢作者的无私奉献

**Comment by airyland** [comment]
拆分是为了减少单个组件的代码量，加个 duplicate-style 可以在构建时进行重复代码清除。
因为组件内部没有用 scoped，所以你在任何地方改 weui 样式也是修改了 weui 全局样式。

`组件内只放置组件特殊样式` 这个很难做到。

`weui的样式可以通过webpack的配置使用`，比如？

**Comment by 2609974827** [comment]
首先，谢谢作者的回答！

针对问题：
`weui的样式可以通过webpack的配置使用`

我的想法比较简单
组件不引入weui样式
就是通过webpack配置weui样式的地址，全局一次性引入。
这样我就可以将weui开发目录直接引入，样式和组件的耦合也比较低
目录寻址修改的时候找起来也比较简单
我也可以针对性的修改部分样式
也有利于缓存

想法比较简单。

**Comment by airyland** [comment]
无法做到。这样引入完全无法配置 less 变量了。如果你仅仅是要用 weui 样式那直接引入 weui 样式就行了，反正最终也可以清除重复样式。

如果你很依赖于 weui 样式来实现自己的页面模板，那么其实也没必要用 vux 了。

**Comment by 2609974827** [comment]
谢谢指点，由于全是自学可能认识上存在误差，感谢您的指正。我会认真思考你的建议的。
