### ISSUE TITLE
xtable无法对齐重现代码

### ISSUE THREAD

**Issue by Samsara0329** [airyland/vux#1946]
![234](https://user-images.githubusercontent.com/26599122/30247662-d567e6c0-964b-11e7-90fc-30f63e9cfe5c.png)

代码如下：
<template>
    <div>
        <group title="材料详情">

        <x-table :cell-bordered="true" :content-bordered="true" :full-bodered="true" style="background-color:#fff;">
            <thead>
                <tr style="background-color: #F7F7F7">
                    <th>产品</th>
                    <th>库存</th>
                    <th>用量</th>
                    <th>总量</th>
                </tr>
                <tbody>
                    <tr>
                        <td>水泥</td>
                        <td>50</td>
                        <td>30</td>
                        <td>100</td>
                    </tr>
                    <tr>
                        <td>钢筋</td>
                        <td>50</td>
                        <td>30</td>
                        <td>100</td>
                    </tr>
                </tbody>
            </thead>
        </x-table>
        </group>
    </div>
</template>

<script>
import { Group, XTable } from 'vux'

export default {
    components: {
        Group,
        XTable
    },
    data() {
        return {    
        }
    }
}
</script>

**Comment by airyland** [comment]
仔细检查标签嵌套吧， `thead` 怎么会包含 `tbody` 呢?
