### ISSUE TITLE
There are multiple modules with names that only differ in casing. This can lead to unexpected behavior when compiling on a filesystem with other case-semantic. Use equal casing.

### ISSUE THREAD

**Issue by tong233** [airyland/vux#1949]
[HMR] bundle has 53 warnings(其中一个)
./~/Vux/src/components/loading/index.vue
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\WorkSpace\app\node_modules\vux-loader\src\index.js!D:\WorkSpace\app\node_modules\vue-loader\index.js??ref--0-1!D:\WorkSpace\app\node_modules\Vux\src\components\loading\index.vue
    Used by 2 module(s), i. e.
    D:\WorkSpace\app\node_modules\Vux\index.js
求帮忙

**Comment by airyland** [comment]
目测和 vux 没什么关系，路径不可能是首字母大写 `Vux`。npm 安装完依赖应该是纯小写 vux 不可能是 `node_modules/Vux`

**Comment by tong233** [comment]
@airyland 是我的错，有一个引入写成from ‘Vux’了
