### ISSUE TITLE
airyland 您好，刚刚接触vux请教您一个问题

### ISSUE THREAD

**Issue by itHulk** [airyland/vux#1950]
swiper-item不能自定义内容高度吗？  现在被默认的180px高度搞了好久，设置aspect-ratio="1"也不行，不能被内容撑开

**Comment by airyland** [comment]
不能，swiper 是用于固定高度的内容显示，比如轮播图，不适合用来做不可预知高度的内容容器。aspect-ratio 用于根据宽度计算高度，不是用于自适应的。

**Comment by itHulk** [comment]
好吧，因为移动端很多需求是做选项卡，并且可以滑动，我看demo演示的有这种选项卡。谢谢您的回复

**Comment by airyland** [comment]
移动端  web 和 App 还是不一样，这里难以完美实现，可能会出各种手势、点击问题，并且也会被要求实现下拉刷新，下拉加载，无限加载等需求，所以暂不做支持。
你可以去 awesome-vue 看看有没有合适的其他组件。

**Comment by shanjixiaboss** [comment]
@itHulk  我是先用js获取你的高度，然后提供css继承高度，把`180px`覆盖掉，不知道能不能符合你的需求

**Comment by DusuWen** [comment]
@shanjixiaboss 我也是先获取swiper-item的高度，然后回头覆盖掉swiper的高度，现在swiper-item的高度获取到了，但是swiper的高度却覆盖不掉

**Comment by shanjixiaboss** [comment]
@DusuWen 那你swipe不写高度，可以用swiper-item的高度撑起来试试

**Comment by yuyuxingchen** [comment]
> @DusuWen 你实现了吗？我也遇到了这样的问题
