### ISSUE TITLE
XInput 的 required 属性只有在失去焦点的时候才会显示感叹号图标吗？

### ISSUE THREAD

**Issue by shiLinQing407** [airyland/vux#1951]
如题
`<x-input title="姓名" :name="field.field_type.toString()" placeholder="必需是中文或英文" :min="1" :max="10" is-type="china-name" :required="field.is_notnull === 1"></x-input>`

**Comment by shiLinQing407** [comment]
能不能像datatime 那样 默认就显示感叹号？
![qq20170911-141340](https://user-images.githubusercontent.com/17386293/30260729-ae82777c-96fb-11e7-9840-3a53b2e2add8.png)

**Comment by airyland** [comment]
😅  其实 datetime 那里一直想改掉，等 dirty 时才变化的。。

**Comment by shiLinQing407** [comment]
好吧 ，其实我是想查找表单中是否还存在【必填项】未填写。
思路是：
查找icon-warn 的style.display 是否等于none 来判断。

而Xinput 是要等获得焦点再失去焦点后才显示出【感叹号图标】的，所以要是一开始就不点击输入框，就无法确定他是否填写了。

我还是老老实实用数据做判断吧。

**Comment by airyland** [comment]
验证这部分是有计划做统一验证的，暂时还没动手去做。

**Comment by shiLinQing407** [comment]
暂时没见过哪个框架有的，期待vux更新。

**Comment by OptimuS-zxj** [comment]
x-input 执行reset方法 之后右边的错误图标为什么会出来，有什么办法么？

**Comment by lutop** [comment]
x-input 执行reset方法 之后右边的错误图标为什么会出来，有什么办法么？
