### ISSUE TITLE
有没有<script></script>这种引入就开搞的方式啊

### ISSUE THREAD

**Issue by ammm56** [airyland/vux#1952]
什么包管理头都搞大了，我只需要vux做界面，直接用已有的组件就行，不用重头写样式。有没有<script></script>这种方式

**Comment by airyland** [comment]
webpack + .vue 单文件开发是效率高维护方便打包方便的形式，不如尝试接受下新的形式，迁移一下也不需要多少时间。

现在不发布 umd 包了，你可以在文档找到自行构建的方法，不过每发一个版本你就得构建一次。

**Comment by qazse41** [comment]
我按文档的方式构建下 然后引入对应的组件js  Failed to mount component: template or render function not defined.

**Comment by Kelichao** [comment]
估计不支持吧

在 2018-06-18 21:04:33，"liming" <notifications@github.com> 写道：


我按文档的方式构建下 然后引入对应的组件js 提示Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option. 怎么破https://doc.vux.li/zh-CN/install/umd.html是不是这个方式

**Comment by cejpo001** [comment]
我也是碰到这个情况,请问你的这个问题解决了吗?

**Comment by yangkun2197** [comment]
不是说  vux 3.0 以后才不支持 umd的么？  怎么2.0 已经不支持啦？
