### ISSUE TITLE
src 目录以软链接方式设置，并且以插件形式调用 ConfirmPlugin , 会导致提示 Vux 打包过大的问题

### ISSUE THREAD

**Issue by mice33** [airyland/vux#1955]
vux 和 vux-loader版本:
```
"vux": "^2.5.12"
"vux-loader": "^1.1.7"
```

配置和调用方法和 https://github.com/airyland/vux/issues/1940 中一样

复现方法
```
运行 npm run dev 之前，先在 project 目录中运行 setSrc.bat (Win) 或 setsrc.sh (OS X) 设置 src 目录软链接
不用软链接方式设置 src 目录不会存在这个问题
```

repo : https://github.com/mice33/bigtest

**Comment by airyland** [comment]
~~软链接目录的名字是不是非 vux。~~

可能是判断是否要解析的路径判断问题。没看明白 src 应该是什么文件

**Comment by mice33** [comment]
软目录是设置下面的 src 目录
```
webpack.base.conf.js


  entry: {
    app: './project/src/main.js'
  }
```

**Comment by airyland** [comment]
project/src  目录链接到 code/trunk/src 然后 src 里就是现在的那几个文件对吧。。

**Comment by mice33** [comment]
对的，然后以插件形式调用 ConfirmPlugin 就会提示 Vux 打包过大

**Comment by airyland** [comment]
webpack 的 babel-loader 条目的 include 加上 `resolve('project/code/trunk')`，目测 webpack 路径针对的是最终地址，不指定软链接目录不会解析，也导致了 vux-loader 无法进行解析。

**Comment by mice33** [comment]
谢谢 @airyland 提供思路，找到另外的解决办法 [https://webpack.js.org/configuration/resolve/#resolve-symlinks](https://webpack.js.org/configuration/resolve/#resolve-symlinks)，设置 symlinks 参数也能解决此问题
```
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('project/src')
    },
    symlinks: false
  }
```
