### ISSUE TITLE
怎么把默认的打印信息关掉

### ISSUE THREAD

**Issue by AllenZho** [airyland/vux#1956]
[VUX] 提 Issue 时麻烦附上以下版本信息以及必要的显示截图、重现步骤、代码(代码请不要截图)。 
[VUX] vux@2.5.12, vux-loader@1.1.7, webpack@2.7.0, node@6.10
[VUX] 建议反馈请访问 https://github.com/airyland/vux/issues

**Comment by airyland** [comment]
更新 vux-loader@^1.1.8

``` js
options: {
  showVuxVersionInfo: false
},
plugins: ['vux-ui', 'progress-bar']
```

**Comment by AllenZho** [comment]
thanks
