### ISSUE TITLE
PopupPicker显示时会将Tabbar顶起来

### ISSUE THREAD

**Issue by lianghuilin** [airyland/vux#1958]
抱歉，我又来提issue了……

PopupPicker是个功能很强大的组件，但如果页面同时使用Tabbar的话，就会出现如下情况：
请问如何解决比较好？调整z-index吗？

![qq 20170912161715](https://user-images.githubusercontent.com/31031351/30315485-b3f39e80-97d6-11e7-88b6-22514424169a.png)
![qq 20170912161739](https://user-images.githubusercontent.com/31031351/30315491-b9428400-97d6-11e7-8487-1cee4cbc78e8.png)

**Comment by airyland** [comment]
既然 demo 没问题那就是你的使用问题，而你并没有帖代码，无法重现的问题无法解决。
