### ISSUE TITLE
请问：tabbar点击某一个可以改变本地图标的颜色吗？如果可以的话；请问有demo可以参考吗？谢谢啦

### ISSUE THREAD

**Issue by fooller** [airyland/vux#1959]
![image](https://user-images.githubusercontent.com/29966012/30321935-5e4867ea-97ea-11e7-84e8-9726858c6c50.png)

**Comment by airyland** [comment]
这是 vue 使用问题不是 vux 的问题。

**Comment by airyland** [comment]
多看下文档或者 demo 也可以找到你的答案
