### ISSUE TITLE
刚接触.vue这种方式，配置vux时出现这种错误请问是哪里的问题

### ISSUE THREAD

**Issue by ammm56** [airyland/vux#1963]
`ERROR in ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vux/src/components/cell/index.vue
Module not found: Error: Can't resolve '../inline-desc' in '\vue\node_modules\vux\src\components\cell'
 @ ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vux/src/components/cell/index.vue 35:0-40
 @ ./node_modules/vux/src/components/cell/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/vuxtesta.vue
 @ ./src/vuxtesta.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js`

![image 1](https://user-images.githubusercontent.com/31843130/30360092-e3c828c8-9881-11e7-82a3-84ed7f26c803.png)

**Comment by airyland** [comment]
刚接触就用脚手架吧。

![image](https://user-images.githubusercontent.com/559179/30361467-c08bf012-9889-11e7-9bb1-b2a6c471a36d.png)
