### ISSUE TITLE
arrow-direction以及XAddress更细化的问题

### ISSUE THREAD

**Issue by QiDekang** [airyland/vux#1968]
Cell提供了arrow-direction，但是Selector、PopupPicker、XAddress等等组件却没有提供。当组件宽度不是100%时，向下的箭头会更适用一些。

另外，XAddress目前只细化到区县一级，但为了给顾客提供更好的服务，地址细化到街道一级的需求也越来越多。

能否优化一下呢？万分感谢。

**Comment by airyland** [comment]
cell 组件可以点击展示更多信息，这是 arrow-direction 存在的目的，而 Selector、PopupPicker、XAddress 这些组件本身是选择组件，没有这种需求。

地址细化使用 popup-picker 自定义数据源即可，XAddress 也是直接封装自 PopupPicker。

**Comment by QiDekang** [comment]
@airyland 谢谢，居然这么快就回复了，给力。

**Comment by airyland** [comment]
另外，地址不细化到街道的另一个原因是不想维护一个街道数据。

**Comment by QiDekang** [comment]
@airyland 理解，感谢指导。另外，向下箭头主要是为了好看些，几个Selector并排放置在一行，向右的箭头感觉怪怪的，不如向下的箭头好看。
