### ISSUE TITLE
vux和表单验证插件vee-validate有冲突？

### ISSUE THREAD

**Issue by liub1934** [airyland/vux#1970]
如图，引入vee-validate后添加了个input，就报错了，不添加input不会
[Vue warn]: The computed property "errors" is already defined in data.

![qq 20170913204757](https://user-images.githubusercontent.com/29849550/30378170-dd709242-98c4-11e7-9078-92ed71e4e42e.png)
![image](https://user-images.githubusercontent.com/29849550/30378201-fa5c8802-98c4-11e7-95e0-0d366fcd23cf.png)
![image](https://user-images.githubusercontent.com/29849550/30378226-144f19b4-98c5-11e7-9d67-b62d0e39d34c.png)

**Comment by airyland** [comment]
大概这个插件定义的属性和 XInput 的属性重名了。这个不应该算是 VUX 的问题，全局混入的插件属性名字应该有命名空间才对。

**Comment by ifu25** [comment]
我理解的是双方都有命名空间是不会有问题的。
如果有问题，也说明两者都没有命名空间。
双方都应该修改才是。
不知道理解的对不对。今天我也遇到这个问题了，无解。
