### ISSUE TITLE
进入和离开页面的时候actionsheet会显示在顶部

### ISSUE THREAD

**Issue by ljjsimon** [airyland/vux#1972]
这个应该不是bug。
我直接拿了demo 里的页面切换效果
```
    <view-box ref="viewBox">
      <transition
      @after-enter="$vux.bus && $vux.bus.$emit('vux:after-view-enter')" 
      :name="'vux-pop-' + (direction === 'forward' ? 'in' : 'out')">
        <router-view></router-view>
      </transition>
    </view-box>
```
actionsheet 也是直接放在大div里面。
```
<template>
  <div>
    ...
    <actionsheet :show.sync="asShow" :menus="asMenu" v-on:on-click-menu="clickActionSheet" show-cancel></actionsheet>
  </div>
</template>
```
应该是有些设置我没有做，但是我已经尽可能和demo 一样了。请问为什么会这样？
切换页面的时候截图如下
![wx20170913-214502](https://user-images.githubusercontent.com/1535231/30380868-57b36f54-98cd-11e7-9f3e-8067b1b90ed5.png)

**Comment by airyland** [comment]
这类问题还是上 repo 吧，具体代码都看不到也了解不到你所说的 `但是我已经尽可能和demo 一样了`。
先尝试用 v-transfer-dom，不行就建个 repo 吧。

**Comment by ljjsimon** [comment]
@airyland 
repo 地址是：https://github.com/questionlin/vuxtest
问题描述已经写在 README 里了。问题应该不是出在 actionsheet 上，但我实在找不出来问题出在哪。烦请看一下，谢谢。

**Comment by airyland** [comment]
项目代码的 eslint babel 配置都缺失了。

**Comment by ljjsimon** [comment]
@airyland 已经加上了

**Comment by ljjsimon** [comment]
我知道了，最外层的 div 加上 height: 100%就行了
