### ISSUE TITLE
cell右边箭头不显示

### ISSUE THREAD

**Issue by zszone** [airyland/vux#1976]
![image](https://user-images.githubusercontent.com/17527793/30420848-7ca80266-996d-11e7-80bd-8e7b51e70b0b.png)
cell中写了is-link
但是在加载后未显示箭头,看了下代码,
![image](https://user-images.githubusercontent.com/17527793/30420917-a5fda008-996d-11e7-9e5b-49a7b5510f2b.png)
:after并未加载出来,
点到其他界面再返回此界面后箭头又出来了,是样式覆盖了?还是什么问题呢?

**Comment by airyland** [comment]
对比官方demo和本地看下样式区别，无法解决的话建个 repo 来重现。
