### ISSUE TITLE
 _vm.$t is not a function

### ISSUE THREAD

**Issue by dzlishen** [airyland/vux#1978]
初次使用vux，使用alert组件，上来就报 _vm.$t is not a function。

然后在main.js中添加以下代码：

import vuexI18n from 'vuex-i18n'
let store = new Vuex.Store({
    modules: {
        i18n: vuexI18n.store
    }
})
Vue.use(vuexI18n.plugin, store)

import { AlertPlugin } from 'vux'
Vue.use(AlertPlugin);
结果就报这个错了："TypeError: Cannot read property 'split' of null"

**Comment by airyland** [comment]
如果你不需要使用 i18n 多语言，就不要配置多语言。
在 import AlertPlugin 前设置 i18n 的默认语言试试。
