### ISSUE TITLE
关于flexible适配模式下picker组件的单位转换

### ISSUE THREAD

**Issue by petersmu** [airyland/vux#1979]
目前项目中用到了flexible的适配处理，大部分的css都能正常从px转到相应rem，但昨天使用Picker组件时发现滚动部分的样式并没有转换为rem，手动强行修改css也只能改尺寸大小，但js的滚动距离部分还是存在问题，滚动位置是按px来计算的，导致滚动位置不准确。
我看了antd-mobile的picker，他们对这个滚动做了适配，单位依然是px，但会根据dpr来改变滚动距离，比如dpr=2时每一格是68px，dpr=3时每一格就是102px，这种适配能否加入到VUX中来呢？
问题样式如图：
![image](https://user-images.githubusercontent.com/12507715/30424343-433f7dbe-9978-11e7-9645-255c69d7e0c7.png)

**Comment by airyland** [comment]
可以建个简单能重现的 repo，我具体看看怎么解决。

**Comment by wg5945** [comment]
参考 #1796 下的一些解决方案试试看呢

**Comment by petersmu** [comment]
我改动了一下你的组件代码可以解决这个问题了，就是在picker创建的时候根据dpr来计算滚动距离，能把我写的这段代码加入到你的代码里面吗？对于不使用flexible的项目来说不会有什么影响的。
![image](https://user-images.githubusercontent.com/12507715/30535479-1d55898e-9c95-11e7-8139-bead648cc9a6.png)
![image](https://user-images.githubusercontent.com/12507715/30535483-2000d580-9c95-11e7-9b33-e88cf546d4ac.png)
![image](https://user-images.githubusercontent.com/12507715/30535485-22fa8286-9c95-11e7-938b-6ab3bfec00da.png)

**Comment by airyland** [comment]
@petersmu v2.6.2 加了

**Comment by GreatAuk** [comment]
@petersmu 请问下，使用flexible做移动端的适配，vux所有组件的宽高样式是不是都要重写覆盖

**Comment by petersmu** [comment]
@GreatAuk 是的，webpack打包的时候做转换

**Comment by wapelee** [comment]
@petersmu 请问如何在webpack打包的时候转换所有的pxtorem，且按指定的比例，感谢
