### ISSUE TITLE
好像文档很少的样子

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#198]
Demo里的app.js都是经过混淆的。
不知道0.1发布的时候会不会一并发布比较详尽的文档，形如：
http://t.amazeui.org/#/docs?_k=xrez8k
http://alloyui.com/tutorials/
谢谢。

**Comment by airyland** [comment]
那是build fille 源码看src/demo

**Comment by airyland** [comment]
文档正在编写，跟0.1一起发布

**Comment by dangyuluo** [comment]
请最好介绍一下AMD加载方式

**Comment by airyland** [comment]
有UMD组件文件。UMD已经是全兼容的了。
