### ISSUE TITLE
search 组件内容不对齐

### ISSUE THREAD

**Issue by ManorNotMaNong** [airyland/vux#1980]
![tim 20170914182511](https://user-images.githubusercontent.com/24819542/30425055-7cb81c70-997a-11e7-87d7-03dc746cbcd6.png)
![tim 20170914182534](https://user-images.githubusercontent.com/24819542/30425053-7cb4dad8-997a-11e7-9633-cbd3ca27881c.png)
![tim 20170914182601](https://user-images.githubusercontent.com/24819542/30425054-7cb5d4b0-997a-11e7-9aed-223c28bd8d5b.png)
对比官方Demo差距较大,不知道原因出在哪?代码源自官方示例也就不贴了,

**Comment by airyland** [comment]
。。这种问题当然是自己检查样式，看哪里冲突了。先尝试解决问题再提 issue。

**Comment by ManorNotMaNong** [comment]
可能确实是有自己未发现的样式冲突,打扰了
