### ISSUE TITLE
项目迁移后重新安装依赖报./~/_vux@2.5.12@vux/src/components/calendar/index.vue下41行语法错误

### ISSUE THREAD

**Issue by Hfengxiang** [airyland/vux#1982]
项目在本地跑的好好的，现在需要将源代码转交给同事，除node_moduals目录以及自动生成文件，其余全放到svn上由他checkout下来，他npm install后依赖全部装上了，一执行npm run dev就报：
./~/_vux@2.5.12@vux/src/components/calendar/index.vue下41行语法错误
**具体错误如下**
` ERROR  Failed to compile with 1 errors

 error  in ./~/_vux@2.5.12@vux/src/components/calendar/index.vue

Syntax Error: Unexpected token (41:2)

  39 |
  40 | const Props = {
> 41 |   ...props(),
     |   ^
  42 |   title: {
  43 |     type: String,
  44 |     required: true

 @ ./~/_vux@2.5.12@vux/src/components/calendar/index.vue 4:0-192
 @ ./~/_babel-loader@7.1.2@babel-loader/lib!./~/_vux-loader@1.1.9@vux-loader/src/script-loader.js!./~/_vue-loader@13.0.4@vue-loader/lib/selector.js?type=script&index=0!./src/pages/collect/Collect.vue
 @ ./src/pages/collect/Collect.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080`
**我做了以下尝试**
参照官方文档的package.json文件，将错误中提到的babel-loader，vux-loader以及vue-loader版本改成和vux源码中的一样，但是仍然报这个错，后来觉得报的错貌似和对象展开符有关就把babel相关的所以依赖版本都改成和官方一致，但仍然报这个错，希望作者能看出问题所在给个解决方案，谢谢！

**Comment by airyland** [comment]
报语法错误应该是 babel 的问题，检查 .babelrc 和 webpack 相关配置。无法解决时建个简单可重现的 repo。

**Comment by Hfengxiang** [comment]
嗯，问题解决了，主要是我纳入svn管理时把..babelrc 给忽略了，导致同事checkout后缺少这个文件报错，现在ok了，谢谢
