### ISSUE TITLE
关于~vux/src/styles/reset.less

### ISSUE THREAD

**Issue by haishengXie0712** [airyland/vux#1986]
我想问一下怎么在全局写一个绝对路径的less，就想~vux/src/styles/reset.less这种一样

**Comment by airyland** [comment]
没看明白。如果是依赖，用 `~` 来说明是从 npm 依赖加载。如果不是依赖就用相对路径。

**Comment by wg5945** [comment]
你是指的alias的运用么？

可以搜一下 webpack alias

**Comment by haishengXie0712** [comment]
@wg5945 这个可以支持less的引用的吗？我用了@作为路径，发现less文件不可以识别。
