### ISSUE TITLE
XIcon 里vue原生的v-if和v-show 如果是表达式的话失效

### ISSUE THREAD

**Issue by 245432007** [airyland/vux#1987]
`<x-icon  type="arrow-up-b" size="10" `v-show="true"></x-icon>`//it work

`<x-icon  type="arrow-up-b" size="10" v-if="0 == 0"></x-icon>`//should show but hidden
额。。v-if也是同样的问题，只通过对第一个值进行判断，表达式失效。

**Comment by airyland** [comment]
这里 vux-loader 有个编译转换为 svg 的过程，暂时你可以把条件写在它的上层。下个版本修复 。

**Comment by airyland** [comment]
测试并不能重现，表达式没有发现问题，升级到最新版本的 vux-loader 试试。

**Comment by travelk** [comment]
同样遇到了 确实会有这个问题 升级最新的vux-loader并没有用 @airyland

**Comment by airyland** [comment]
确认是 bug 在最新版本已经修复。
