### ISSUE TITLE
弹出 x-dialog 导致页面滚回顶部

### ISSUE THREAD

**Issue by notzheng** [airyland/vux#1988]
### 问题
弹出 x-dialog 时，页面滚回顶部

### 问题展示
（图片大小约 4 M）
![demo 展示](https://user-images.githubusercontent.com/13414731/30495049-0f05db40-9a10-11e7-801d-5fa91924df70.gif)

### 描述：
使用 panel 组件展示一个列表，点击 item 会触发弹框。弹框出现时整个页面滚回顶部。

其中，panel 的内容异步加载，dialog 的内容在点击事件时异步加载。

#### vux Version

^2.2.1

#### Android or iOS
 
PC端Chrome, firefox 浏览器, Android5.1.1 Chrome, 均出现该问题

尝试以下多种方法，均未解决：
1.添加 v-transfer-dom，无效

2.去掉
```
import { ConfigPlugin } from 'vux'

Vue.use(ConfigPlugin, {
  $layout: 'VIEW_BOX'
})
```
无效

3.去掉
```
  html{
    position: relative;
    min-height: 100%;

  }
  body {
    background-color: #fbf9fe;
    padding-bottom: 4.5rem;
  }
```
无效

4.去掉 x-header 与 tabbar ，无效

5.将 dialog 的内容设置为静态内容，无效。

6.build 项目测试，无效

7.将整个页面改为文档提供的 demo 代码，无效

补充：
设置 x-dialog 绑定的 v-model 为 true 之后，弹窗显示之前，调用：
```
var e = window.pageYOffset
          || document.documentElement.scrollTop
          || document.body.scrollTop
          || 0;
console.log(e)
```
为正常滚动值，当弹窗显示之后再次调用为0.

将 x-dialog 换成 alert 也一样的问题

代码如下：
```
<template>
  <div class="getlist">
    <x-header>"{{msg}}"的搜索结果<a type="button" slot="right" @click="showsearchbar = !showsearchbar">结果中搜索</a></x-header>

    <div v-if="showsearchbar">
      <search placeholder="在结果中搜索"></search>
      <checker id="chooseclass"
               v-model="s_text2"
               default-item-class="searchclass"
               selected-item-class="searchclass-selected"
      >
        <checker-item value="title">按书名</checker-item>
        <checker-item value="author">按作者</checker-item>
        <checker-item value="publisher">按出版社</checker-item>
      </checker>
    </div>


    <panel :list="panellist" @on-click-item="showmarcno" type="4"></panel>

    <loading :show="loading" text="搜索中"></loading>

    <alert v-model="nobook" buttonText="返回搜索" @on-hide="$router.replace({ name: 'Search' })" title="啊哦！什么也没有搜到">
      可能你记错书名了？<br/>换个关键词搜一下吧～
    </alert>

    <x-dialog v-model="show_detail">

      <p v-if="bookdetail.length == 0 ">获取中……</p>
      <div>
        <group title="馆藏列表（展开获取详细定位）">
          <cell
            v-if="bookdetail.length!=0" v-for="d in bookdetail"
            :key="d.barcode"
            :title="d.barcode"
            is-link
            :border-intent="true"
            :arrow-direction="showloc ? 'up' : 'down'"
            @click.native="showloc = !showloc"
            style="text-align: left"
          >
            <div slot="inline-desc" style="font-size:80%;">{{d.location}}</div>
            <div slot="default">
              <span v-if="d.status!='可借'" style="font-size:80%;margin-right: 5px">{{d.status}}</span>
              <span v-if="d.status=='可借'" style="color: green;margin-right: 5px">{{d.status}}</span>
            </div>
          </cell>


        </group>


      </div>


      <div @click="show_detail=false">
        <span class="vux-close"></span>
      </div>
    </x-dialog>

  </div>

</template>
```

**Comment by airyland** [comment]
上面的 vux 版本 ^2.2.1 并不能知道具体版本，建议先升级到最新的 2.6.0 试试。问题也可能是涉及到布局方面导致的，可以简化一下建个 repo 看看。

**Comment by notzheng** [comment]
@airyland 问题大概解决了。
通过设置 100% 布局。这样，既没有自动滚到顶部的问题，也没有使用 `import { ConfigPlugin } from 'vux'` 就阻止了body 滚动。

```
 html,body {
    height: 100%;
    width: 100%;
    overflow-x: hidden;
  }
```
问题出在这里：
之前由于想解决 tabbar 遮挡页面底部内容的问题，这样设置的。这样没有自动滚到顶部的问题，但是body会随着 xdialog 滚动。然后通过 `import { ConfigPlugin } from 'vux'` 阻止滚动，就出现了这个问题。

```

 html,body {
   min- height: 100%;
  
  }

  body {
    background-color: #fbf9fe;
    padding-bottom: 4.5rem;  /*避免tabbar遮挡底部内容*/
  }

```

另外请问，tabbar 遮挡 body 的一部分内容有其他好的解决方法吗？我看了一下 demo 原始页面也存在这个问题。

现在我的解决方式是，App.vue 里面，给`router-view`加个 padding-bottom

```
<template>
  <div id="app">
    <router-view style="padding-bottom: 4.5rem"></router-view>
    <lib-tabbar></lib-tabbar>
  </div>
</template>
```

谢谢回复～

**Comment by airyland** [comment]
ConfigPlugin 的配置是为了解决在 100% 布局(ViewBox 组件)下， XDialog 滑动时 body 也会滚动以及 Popup 滑动时 body 会滚动的问题。所以如果你不是 100% 布局而配置了 $layout=VIEW_BOX 必定会出问题。

但是上面奇怪的是 100% 布局下你不用配置 $layout=VIEW_BOX 也能阻止 body 滚动。

tabbar 或者 header 遮挡 body 只能设置 padding 了，ViewBox 组件其实就是用于 100% 的布局，也有相关属性。https://vux.li/#/zh-CN/components?id=viewbox

**Comment by notzheng** [comment]
嗯嗯，我也觉得奇怪。
我仅仅在 App.vue 里使用了：
```
  html,body {
    height: 100%;
    width: 100%;
    overflow-x: hidden;
  }
```
并没有在任何地方使用 ViewBox 组件。
刚才试了以下，在此基础上如果再配置  $layout=VIEW_BOX，在弹出 x-dialog 的同时，底部 tabbar 会诡异的消失。
不过现在问题算是完美解决，谢谢作者的及时、耐心解答。

**Comment by airyland** [comment]
大概可能是因为你没用 ViewBox 组件导致的，弹出时做的 body 和容器(ViewBox 内容容器)样式更改在这里 https://github.com/airyland/vux/blob/v2/src/mixins/prevent-body-scroll.css 

如果有其他问题再反馈，这个 issue 我关闭。
