### ISSUE TITLE
DatetimeView组件无法渲染及报错

### ISSUE THREAD

**Issue by webignorant** [airyland/vux#1991]
@airyland 

先贴上错误表现
![2017-09-16_193640](https://user-images.githubusercontent.com/4382159/30511981-eab136a6-9b16-11e7-9ebc-2aa006325bf4.png)

控制台输出
![2017-09-16_193611](https://user-images.githubusercontent.com/4382159/30511983-fb92d132-9b16-11e7-8181-6b09818cc9ca.png)

代码
```js
<template>
    <div>
        <datetime-view v-model="value1" ref="datetime" :format="format"></datetime-view>
        <p class="info">current value: {{ value1 }}</p>
    </div>
</template>

<script>
import { DatetimeView } from 'vux';

export default {
    components: {
        DatetimeView
    },
    data() {
        return {
            value1: '2017-10-11',
            format: 'YYYY-MM-DD'
        };
    },
    methods: {
    }
};
</script>

<style lang="sass">
</style>
```

求解？

**Comment by airyland** [comment]
进入 datetime/datetimepicker.js 调试，第一行 `import Scroller from '../picker/scroller'
` 之后 console.log(Scroller) 这里如果 Scroller 不存在，那么也应该不是组件的问题，建个 repo 重现。

**Comment by airyland** [comment]
用脚手架创建项目并复制你上面代码并不能重现。

**Comment by webignorant** [comment]
@airyland 
目前看来没法正常import，当前Sources显示没有加载../picker/scroller。
看来不是组件问题，我调试一下。Thanks
![2017-09-16_200942](https://user-images.githubusercontent.com/4382159/30512157-18db92c0-9b1b-11e7-9e94-99d7e0b93dd3.png)

**Comment by airyland** [comment]
问题解决否？如果还有问题建个 repo 研究一下。
