### ISSUE TITLE
datatime里面有自定义显示时间分钟列表，怎么没有自定义日期列表？

### ISSUE THREAD

**Issue by whdeairen** [airyland/vux#1992]
:hour-list="['09', '10', '11', '12', '13', '14', '15', '16']"
 :minute-list="['00', '15', '30', '45']" 
如题，我想用他实现我指定只有某几天可以点，比如5,8,17这样不连续的日期，但是找不到自定义日期列表，请教一下怎么弄

**Comment by airyland** [comment]
暂未支持。这是应用于什么具体需求？

**Comment by whdeairen** [comment]
医院挂号，一周只有某几天有号，现在小时分钟都是ok的，就日期了

**Comment by whdeairen** [comment]
电脑端那种日历是没问题的，移动端因为用的vue，所以选了vux框架，发现移动端datatime picker无法禁用不用的天数或者不显示非指定的天数，能否按照小时分钟自定义列表的方法封装一下自定义day？拜谢大神

**Comment by airyland** [comment]
2.6.1 支持属性 `compute-days-function` 根据年月参数动态返回日期列表

**Comment by whdeairen** [comment]
# **it‘s very cool！**
或许是为了更多方面的使用，我觉得案例当中 days会随着月份的改变而改变有点不方便，
computeDaysFunction (options, generateRange) {
        return [options.month] // if current month is n, days are [n]
}
另外方法写在data中，传值不是很方便，我是这样实现的，data当中定义一个日期数组days，在methods中写出该方法，方便动态传值
computeDaysFunction(option) {		
	return this.days
},
 另外提醒下老大，下列路径下136行的打印没有去掉，☺☺☺☺☺☺
webpack:///node_modules/vux/src/components/datetime/index.vue?

**Comment by airyland** [comment]
主要是为了灵活，因为你是固定只显示某几天，而有部分用户是需要根据年月来显示某些天。兼容一下就是这样了。demo 只是一个功能示例。
