### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by falltodis** [airyland/vux#1993]
```
┌─────────────┐
│    Header   │
├─────────────┤
│             │
│ Scroll Area │
│             │
├─────────────┤
│    Footer   │
└─────────────┘
```
页面的结构如上，在`ios`中拖动 `scroll area`会带着`Footer`一起拖动（只有在接近底部的时候），触发`bounce`效果，导致`Footer`暂时会影藏一下。

目前定位的结果：如果`Footer`和`Scroll Aera`同级，则Footer在拖动的时候不会被隐藏，不触发`bounce`，然而因为某些原因，`Scolle Aera`必须包含`Footer`，则会触发`bounce`效果，请问如何在这种情况下取消`footer`的`bounce`效果

**Comment by airyland** [comment]
据我所知， Safari 并没有这种设置，你只能另寻方法比如使用第三方的模拟 scrolle 的组件。
