### ISSUE TITLE
CheckList能否提供一个单选功能

### ISSUE THREAD

**Issue by Hfengxiang** [airyland/vux#1996]
目前CheckList通过props属性中的max来控制选择item的个数，当max设置为1时能实现只选一个，但是要选择别的item必须将当前item取消勾选才能选择别的，能否提供一个props实现类似不需要取消当前item即可切换勾选的功能？

**Comment by airyland** [comment]
为什么不用 Radio

**Comment by Hfengxiang** [comment]
ok换成ratio了

**Comment by airyland** [comment]
下个版本针对  max = 1 的情况也做了优化，当成 Radio 用也没问题。
