### ISSUE TITLE
Previewer组件能否增加自定义操作按钮

### ISSUE THREAD

**Issue by z-wings** [airyland/vux#2002]
![image](https://user-images.githubusercontent.com/17632172/30573943-4ff99b8e-9d29-11e7-858b-914992981222.png)

这里能否开放出来，可以自己增加操作按钮

![image](https://user-images.githubusercontent.com/17632172/30573971-7f5a178c-9d29-11e7-8193-8f38106dc903.png)

**Comment by airyland** [comment]
这个昨天刚好加了两个 slot button-after 和 button-before，并且不小心发布了一个版本。你可以用最新版本试试。

**Comment by code-admin** [comment]
图片预览的时候 ，为什么我的自定义按钮 点击会触发图片稍微放大的效果？！
![image](https://user-images.githubusercontent.com/43529409/51244230-7beba700-19bf-11e9-8d81-12c63ecdf6d4.png)

**Comment by code-admin** [comment]
![image](https://user-images.githubusercontent.com/43529409/51244178-62e2f600-19bf-11e9-9886-a45298ae6b13.png)

**Comment by hushuishui** [comment]
点击会触发图片稍微放大的效果，这个有解决吗，求告知，遇到了同样的问题。

**Comment by lhwtyu** [comment]
> 点击会触发图片稍微放大的效果，这个有解决吗，求告知，遇到了同样的问题。

你好，这个问题有解决了吗？

**Comment by micjason** [comment]
同求这个问题，感觉像双击了一样，事件无法阻止传递

**Comment by micjason** [comment]
> > 点击会触发图片稍微放大的效果，这个有解决吗，求告知，遇到了同样的问题。
> 
> 你好，这个问题有解决了吗？

你解决了么
