### ISSUE TITLE
previewer组件button-before上click事件绑不上去

### ISSUE THREAD

**Issue by z-wings** [airyland/vux#2005]
用了slot="button-before" 后，直接用@click绑不上事件，用@click.native也绑不上

是不是photoswipe插件中dom处理问题？

![image](https://user-images.githubusercontent.com/17632172/30584331-fcb26590-9d5b-11e7-9217-0409509c4746.png)

![image](https://user-images.githubusercontent.com/17632172/30584490-7a64800e-9d5c-11e7-8889-257b9806a1b2.png)

**Comment by airyland** [comment]
不确定。你换个标签试试，如果其他标签可以，那么这里 photoswiper 是对 button 做了处理。

**Comment by z-wings** [comment]
sorry   谢谢回复
我调了3个小时，没搞定。
我什么代码都没改，莫名的好了。
我也很蒙蔽。。。
