### ISSUE TITLE
使用scoller在transition中使用问题

### ISSUE THREAD

**Issue by luhf** [airyland/vux#2006]
使用scoller在transition中切换的时候会产生页面闪烁漂浮，感觉是在进入下一个页面的时候scoller的top先恢复成0在进入下一个页面。

**Comment by airyland** [comment]
抱歉，该组件已经不再维护，建议使用社区其他 scroller 类似组件。

**Comment by mrzhouxu** [comment]
我刚才也遇到这个问题了，多个scroller之间切换的时候页面漂浮。找了一下午没有什么好的解决办法。
最终这样，感觉勉强能用，不知道还有没有更好的解决办法：            
            tabbar_change(value){
                this.tabbar_val = value
                this.$nextTick(() => {
                    this.$refs.scroller.reset({
                        top: 0
                    })
                })
            },
