### ISSUE TITLE
previewer组件中使用_init方法与vue实例方法冲突

### ISSUE THREAD

**Issue by LXTyr** [airyland/vux#2007]
![image](https://user-images.githubusercontent.com/12163867/30588786-b0aefb22-9d6a-11e7-9e2c-9c06378f07aa.png)

**Comment by LXTyr** [comment]
经排查发现是previewer组件中使用的_init方法导致vue报错

**Comment by z-wings** [comment]
问题已经提过了，下个版本会修复

![image](https://user-images.githubusercontent.com/17632172/30590598-e1e32676-9d71-11e7-8396-1c04e640a2c0.png)
