### ISSUE TITLE
请教xinput里面is-type自定义函数检测输入内容问题

### ISSUE THREAD

**Issue by mitboy1983** [airyland/vux#2009]
xinput表单验证里面 is-type 看文档可以自己定义函数来检测输入的内容是否满足要求，例子里面写的 be2333 这个 返回 return  {valid:false, msg:错误信息}, 想请教一下 这个 msg 的 错误信息 怎么显示？
我看例子demo 输入内容不合要求的 只有一个 红色的 icon 在右边，如何给出合理的错误提示呢？

**Comment by airyland** [comment]
就现在的 UI 来说错误提示不大适合放在 cell 里，placeholder 上加个提示应该基本能让用户理解吧，最终怎么做合理可能得咨询你们设计了，业务不同这里的考虑也不一样吧。

**Comment by airyland** [comment]
在 v2.6.3 优化了下，点击右侧错误图标会 toast 一个错误信息。

**Comment by YikaJ** [comment]
错误提示对齐 we-ui 的话，应该不是一个 Toast，这里有官方的错误提示。https://weui.io/#input
![image](https://user-images.githubusercontent.com/8725110/31984615-c5876f8e-b994-11e7-948a-b33040568df5.png)
