### ISSUE TITLE
Swiper组件下有v-if 时显示出现偏移

### ISSUE THREAD

**Issue by lvsuming** [airyland/vux#2011]
源码：
`<swiper-item v-for="(item, index) in eventTypeList" :key="index">`
    `<div class="tab-swiper vux-center">`
        `<SpecialTypeEvents v-if="index === 0"></SpecialTypeEvents>`
        `<OrdinaryTypeEvents v-else></OrdinaryTypeEvents>`
    `</div>`
`</swiper-item>`
渲染后：
选择第一个tab时，第二个vux-swiper-item标签的style：“transform: translate3d(1500px, 0px, 0px); transition: 300ms;”
选择第二个tab时，第二个vux-swiper-item标签的style：“transform: translate3d(1125px, 0px, 0px); transition: 300ms;”
实测发现，此时transform中translate3d首个值为0时才可正常显示

**Comment by airyland** [comment]
这个组件叫 Swiper 不叫 Tab 吧？

**Comment by lvsuming** [comment]
是Swiper，我是和tab配合使用的，通过切换tab来切换Swiper

**Comment by airyland** [comment]
请去除业务代码给出可重现代码。

格式化多行代码用  ``` html

**Comment by lvsuming** [comment]
`<div>`
      `<tab :line-width=2 v-model="demoIndex">`
        `<tab-item class="vux-center" :selected="demo === item" v-for="(item, index) in demoList" :key="index">{{item}}</tab-item>`
       `</tab>`
        `<swiper v-model="demoIndex" height="100px" :show-dots="false">`
        `<swiper-item v-for="(item, index) in demoList" :key="index">`
          `<div class="tab-swiper vux-center">`
            `  <div v-if="index === 0">{{'000'}}</div>`
            `  <div v-else>{{'111'}}</div>  <!--重点：此处为字符串时正常，为子组件时异常-->`
          `</div>`
        `</swiper-item>`
`</div>`
选择第二个tab后，下图红线标识处应为0时，否则显示偏移
![qq 20170920115401](https://user-images.githubusercontent.com/17267557/30626142-766205e6-9dfa-11e7-87a3-af93c8f2d23f.png)

**Comment by airyland** [comment]
重新格式化吧，关闭标签也缺失。v-model 都不一样也看不出你怎样控制的。请给出完全的包含 script 部分在内的代码。

补充后再重开当前 issue 吧。
