### ISSUE TITLE
为什么不能按需引入组件

### ISSUE THREAD

**Issue by jjskay** [airyland/vux#2013]
最近在弄vue ssr的移动端项目，看到vux的组件还是比较好的，就拿来用，打包进去竟然2.7M,为什么没有用的组件也打包进去了？以下是vux警告
VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。

**Comment by airyland** [comment]
首先提个好问题，你不说你怎么用的，没人能解决你的问题。
其次警告已经写得很清楚了。
