### ISSUE TITLE
Android 4.4.2页面空白

### ISSUE THREAD

**Issue by haishengXie0712** [airyland/vux#2017]
版本:vux@2.5.8, vux-loader@1.1.5, webpack@2.7.0, node@8.2
在android 4.4.2下发现页面空白问题.
我引用了
npm install --save babel-polyfill
npm install --save babel-runtime
`import 'babel-polyfill';`
问题依旧没有解决。
在4.4.4以上都没有问题

**Comment by airyland** [comment]
线索太少，无法帮你解决，如果你用这台机子访问官方 demo 无问题那就是业务代码的问题，和组件无关了。
