### ISSUE TITLE
1px在group上左边框会被遮挡

### ISSUE THREAD

**Issue by qxzm** [airyland/vux#2019]
```
<template>
    <div>
        <group class="b vux-1px-l vux-1px-r">
            <x-input class="" is-type="china-mobile" label-width="3" title="手机号" placeholder="请输入手机号"></x-input>
            <x-input type="password" label-width="3" title="密码" placeholder="请输入密码"></x-input>
        </group>

        <x-button type="primary" v-on:click.native="go" class="a">提交</x-button>
    </div>
</template>
```

为了展示我把左右边线都给了一个30px的宽度，如下

![image](https://user-images.githubusercontent.com/13436569/30678638-2ed0c2a4-9ec6-11e7-97dd-06b6d573839d.png)

**Comment by airyland** [comment]
这里需要加一个 z-index，因为担心影响其他，所以暂时不直接在 vux-1px 方案里加 z-index 了。

``` css
<style scoped>
.vux-1px-l:before {
  z-index: 1;
}
</style>
```

**Comment by qxzm** [comment]
嗯， 这个是可以的，另外右边框为什么可以不用加z-index就显示嘞

**Comment by airyland** [comment]
左边框 - 内容 - 右边框，你可以理解为中间内容覆盖了它，你可以试试把中间 cell 用 z-index:-1 试试应该也可以让左边框显示出来，而右边框在内容后相当于叠加所以可以显示。

**Comment by qxzm** [comment]
按照before ->  content  ->  after这样的DOM加载顺序从而导致after元素可以显示在content上 这个理解的话。
我不太明白的一个点是：如果只是应用了.vux-1px的时候, 会只添加了一个before元素，设定了所有的border，但是left， top是不可以显示，right， bottom 的 border是可以显示的。

**Comment by qxzm** [comment]
我测试了下，使用vue-1px的时候，确实是before元素，是会被content容器遮挡的。
只不过before元素使用的content-box，等比例缩小的时候是给before元素的长宽多了1px，在transform-origin：left top的情况下，content容器的外部可以显示bottom 和 right的边框。

明白啦，十分谢谢！
