### ISSUE TITLE
Scroller too high

### ISSUE THREAD

**Issue by reinvanoyen** [airyland/vux#202]
### Version
0.0.118-rc1

### Android or iOS, which browser?
Desktop, Chrome
ios, Safari

### Your Codes

``` html
	<x-header>{{ title }}</x-header>
	<scroller lock-x scrollbar-y use-pulldown @pulldown:loading="refresh">
		<panel :list="list"></panel>
	</scroller>
```

### Expected behavior and actual behavior.

It seems the Scroller is taking on the height of the viewport, which in the case of having an XHeader before it, is too high. This is a minor issue and just feels a bit clumsy and messy, but it would be awesome to have some insight in how this is supposed to work together. I imagine this should be better done with flexbox?

Should I throw in my own divs with custom styling? Or is there some sort of "ContentPane" component? If not, would it be nice to have it...Just throwing some ideas around.

**Comment by airyland** [comment]
If height is not specified, the scroller's height will be set to viewport's height. Now you have to set the height to `viewportHeight - XHeaderHeight` to make it work.

But actually I did consider another easier way for setting height:
<scroller height="VIEWPORT-250"></scroller>

**Comment by reinvanoyen** [comment]
Ok, thanks for your reply. Wouldn't it be convenient to make a wrapping component which fits the items together in a smart way. Flexbox is totally capable of doing that. Just throwing in my two cents, I'm fairly new to SPA development and Vue.

**Comment by airyland** [comment]
Yeah, It's a cool way and I will try it. PR is welcome.

**Comment by airyland** [comment]
Found it not that easy to achieve what I want by flexbox in a vertical layout.  https://bl.ocks.org/jfsiii/5380802
