### ISSUE TITLE
checklist取何获取value信息

### ISSUE THREAD

**Issue by dzlishen** [airyland/vux#2022]
<checklist title="" label-position="left" :options="projectManagerList" v-model="pmValue" @on-change="pmChange"></checklist>               
如何获取到checklist中选中项的文字信息呢？

**Comment by airyland** [comment]
最新版的 on-change 里第二个参数为 Label。但是没有获取文字信息的方法，为什么有这个需求？

**Comment by dzlishen** [comment]
我在做一个页面用到一个弹出的多选列表，选中后文字想回显到页面上的。

**Comment by airyland** [comment]
暂时可以自行根据值和列表 match 到相应 labels，下个版本支持 getFullValue 方法。
