### ISSUE TITLE
以插件形式调用alert和confirm，如果未点击确认或者取消，返回后弹框依然会存在

### ISSUE THREAD

**Issue by whdeairen** [airyland/vux#2025]
今天发现这个问题，在main。js路由当中可以关闭，但是感觉不是很好，反馈一下，这是官网的例子，打开也是一样的情况！ 图片如下：
![image](https://user-images.githubusercontent.com/30415157/30734287-233b223a-9fad-11e7-89c2-a0e94dfcfa9a.png)

**Comment by airyland** [comment]
这个问题最合适的做法是，在有调用插件的页面里的 destroy 或者  deactivated 事件里自行关闭。
当然也可以提供一个 plugin，负责在路由切换时关闭所有插件。。

**Comment by whdeairen** [comment]
为了方便全局使用才用的，如果每个调用的页面都加入事件自行关闭的话，也比较繁琐，目前我在main.js路由事件里面调用关闭的方法，期待有更好的办法 ╰(￣▽￣)╭

**Comment by CHENLiver** [comment]
@whdeairen 你是怎么在main.js路由事件里面调用关闭的方法的

**Comment by airyland** [comment]
没有更好的方法了，这个之前也考虑过，只能提供一个插件负责在路由切换时关闭所有弹窗。

**Comment by whdeairen** [comment]
@CHENLiver  router.beforeEach 里面调用  Vue.$vux.confirm.hide();

**Comment by airyland** [comment]
下个版本添加了一个新插件，可以这样使用：

``` js
 import { CloseDialogsPlugin } from 'vux'
Vue.use(CloseDialogsPlugin, router)
```
也可以直接拿源码用：

``` js
export default {
  install (Vue, router) {
    router.beforeEach((to, from, next) => {
      const list = ['alert', 'confirm', 'toast', 'loading', 'datetime']
      list.forEach(one => {
        if (Vue.$vux[one]) {
          Vue.$vux[one].hide && Vue.$vux[one].hide()
        }
      })
      next()
    })
  }
}
```

**Comment by CHENLiver** [comment]
@airyland 下个版本大概什么时候发布

**Comment by whdeairen** [comment]
@CHENLiver  Don't wait for ,  you can use it like this , so easy!

main.js
router.beforeEach((to, from, next) => {
	
	const list = ['alert', 'confirm', 'toast', 'loading', 'datetime']
	list.forEach(one => {
	  if (Vue.$vux[one]) {
		Vue.$vux[one].hide && Vue.$vux[one].hide()
	  }
	})
	next();
  })

**Comment by airyland** [comment]
v2.6.4

**Comment by Camellia55** [comment]
页面切换时调用的main.js里hide()方法，能不执行上个页面的alert的hide()的回调函数吗？

**Comment by lovernull** [comment]
神神道道

**Comment by lovernull** [comment]
小白表示看不明白

**Comment by Camellia55** [comment]
我是提一个新的问题。。就是页面切换时在mian.js中统一调用hide虽然可以关闭窗口，但是同时也会执行hide回调函数的。特别是alert组件没有提供点击事件，而只有onHide的事件。如果我的确定按钮是调到百度去的话，关闭窗口的同时就会跳转了

**Comment by pzPangZhen** [comment]
怎么添加取消的按钮？
