### ISSUE TITLE
[Swiper]组件设置auto自动轮播后，如何手动暂停？

### ISSUE THREAD

**Issue by Plortinus** [airyland/vux#2027]
需求是只自动轮播一次就暂停，想到的解决方案是轮播到最后一个slide的时候手动停止这个自动轮播。找了一下文档没有找到相关属性代码可用。

**Comment by wg5945** [comment]
Swiper组件提供了render()方法

可以重设auto=false
然后调用render()

**Comment by airyland** [comment]
下一版本 auto 绑定值设为 false 时会暂停播放。

**Comment by kentpan** [comment]
截止到2.9.4，还是没有提供通过更改auto属性开始/停止自动轮播的控制，不过可以通过swiper提供的方法间接实现：

`setAutoPlay(status) {
            this.autoPlay = status;
            this.$refs.swiperHandler.swiper._options.auto = this.autoPlay;
            this.$refs.swiperHandler.swiper._auto();
 }`
