### ISSUE TITLE
支付宝支付密码框组件不知道有没有

### ISSUE THREAD

**Issue by mitboy1983** [airyland/vux#2028]
请教一下vux里面有这种类似输入 6位密码框的组件么？

支付场景貌似用的还挺多的，不知道有没有这种组件

![1506146502530](https://user-images.githubusercontent.com/31514741/30770627-16367dee-a068-11e7-9fdb-8dc1a9760dcc.jpg)

**Comment by airyland** [comment]
文档看不到的就是没有。 #139

**Comment by travelk** [comment]
https://travelk.github.io/tool/pwd_box/ 很久之前写了一个 不过不是vue的插件

**Comment by airyland** [comment]
@travelk 可以来贡献贡献。在移动端这个组件其实配合一个虚拟数字键盘更合适。
