### ISSUE TITLE
popup的zIndex可以变,但是如何改变mask的zIndex

### ISSUE THREAD

**Issue by 525729985** [airyland/vux#2029]
一个页面有两个popup,一个弹出来时需要漏出标题,一个弹出时则要遮住标题,popup-style只能改变popup的zIndex,mask的zIndex不会跟着涨。
    "vuex": "^2.4.0"

**Comment by wg5945** [comment]
你的标题指的是什么？
最好给个示意图

**Comment by airyland** [comment]
目前 mask 是共享模式，听起来你是想一个 popup 带一个 mask 遮住已经弹出来的 popup

**Comment by 525729985** [comment]
所有popup共享一个mask倒是没什么问题。不过如果弹出新的popup的时候设置了zIndex，mask的zIndex能跟跟着popup的zIndex减1，感觉能更灵活点。

**Comment by nicoleXue1** [comment]
怎么解决？？？popup嵌套popup mack盖住某一个popup  能解决吗
