### ISSUE TITLE
关于swiper组件修改current值

### ISSUE THREAD

**Issue by wg5945** [airyland/vux#203]
### Version
0.0.118-rc1

### Android or iOS, which browser?
ios

### Your Codes 

``` html
<!--put your code here-->
```

### Expected behavior and actual behavior.
swiper组件能否提供设置current的方法？

现在swiper和tab组件混合使用，只能实现滑动swiper来改变tab的active
希望能通过点击tab也能改变swiper组件的current值

或者再封装个支持滑动的tab？

**Comment by airyland** [comment]
这个在实现中。下个版本支持。

**Comment by wg5945** [comment]
好的，谢谢~~
