### ISSUE TITLE
x-input的number属性在苹果手机上的bug

### ISSUE THREAD

**Issue by fooller** [airyland/vux#2030]
x-input标签的number属性，在安卓和电脑上是可以避免输入汉字的，但是在苹果手机上可以输入汉字；

**Comment by airyland** [comment]
x-input 无 number 属性。

**Comment by wg5945** [comment]
number会直接编译成`<input type="number" />`

我记得iPhone中会优先显示数字键盘，但不是强制，如果要强制的话，可以使用tel

**Comment by airyland** [comment]
数字输入的问题，用虚拟数字键盘才能完全解决，后面会在 x-input 上支持。

**Comment by fooller** [comment]
thanks for everybody's views
