### ISSUE TITLE
..._cellProps 这种语法，编译不通过

### ISSUE THREAD

**Issue by ccode-code** [airyland/vux#2031]
props: {
    placeholder: String,
    readonly: Boolean,
    ..._cellProps,
    ...radioProps()
  }
![image](https://user-images.githubusercontent.com/10229333/30788900-170f588a-a167-11e7-9403-9b56ce60c7fd.png)

编译不通过，不支持这种语法，我升级node版本至8.1.0，但是node-sass又不能运行，
老大qiu'ji求解决

**Comment by ccode-code** [comment]
@airyland

**Comment by wg5945** [comment]
请检查babel配置

**Comment by ccode-code** [comment]
@wg5945 
![image](https://user-images.githubusercontent.com/10229333/30789067-83105092-a168-11e7-8041-5f2f877f8acb.png)

这是我的babel配置，用的webpack 3.5.5

**Comment by wg5945** [comment]
你可以和官方脚手架的配置进行对比

非vux的问题最好不要在issues中提问，请谅解

**Comment by ccode-code** [comment]
感谢提供意见。

**Comment by airyland** [comment]
也可以参照 vue 官方模板  https://github.com/vuejs-templates/webpack/tree/develop/template/build

**Comment by imcoka** [comment]
依旧无效，我的配置如下

{
      test: /\.js$/,
      include: resolve('src'),
      use: [{
        loader: 'babel-loader',
        options: {
          cacheDirectory: true,
          comments: false,
          presets: [
            ['env', {
              modules: false,
              targets: {
                browsers: checkVersion.BROWSERS
              }
            }],
            'stage-2'
          ],
          plugins: ['transform-runtime'],
          env: {
            local: {
              plugins: ['istanbul']
            }
          }
        }
      }]
    }

**Comment by ccode-code** [comment]
仍然无法解决
![image](https://user-images.githubusercontent.com/10229333/30794672-376bb48e-a18f-11e7-95e4-4ef258c9b303.png)

**Comment by airyland** [comment]
用 babelrc 的文件配置试试。

**Comment by ccode-code** [comment]
可以了，非常感谢老大
