### ISSUE TITLE
pancel组件在华为平板上出现的兼容性问题，仔细看，文字显示不全

### ISSUE THREAD

**Issue by fooller** [airyland/vux#2037]
![173230131476432053](https://user-images.githubusercontent.com/29966012/30799350-28cdc734-a20f-11e7-84cb-c58eea8cbfcf.jpg)

**Comment by fooller** [comment]
如果华为平板 不方便，调试人员可以去uc浏览器，在uc浏览器上也会出现这样的情况

感谢！！！ 祝好！！！

**Comment by airyland** [comment]
这类诡异的显示问题暂不处理，尤其是华为的问题。VUX 样式依赖于 WeUI 麻烦到 WeUI 提 issue。

**Comment by fooller** [comment]
好的
