### ISSUE TITLE
怎么调起微信的jssdk

### ISSUE THREAD

**Issue by khongshao** [airyland/vux#2038]
我根据文档和github上的代码配置好了，接口数据格式也是伪造预览地址上的接口。但是没有生效，我不知道是不是因为测试号的源故
然后不知道微信支付或是微信硬件的sdk这类的是否建议在生产环境上使用？

**Comment by airyland** [comment]
非组件问题，内置插件仅仅是封装了 jssdk 而已。这里无法解决也解决不了你的测试问题，相关问题参考微信官方文档。

**Comment by khongshao** [comment]
谢谢答复，我再看看，能不能解决吧
