### ISSUE TITLE
请问 x-input 如何同时使用mask="999 9999 9999"和keyboard="number" is-type="china-mobile"？

### ISSUE THREAD

**Issue by KarnaughK** [airyland/vux#2040]
有什么方法么。。。同时使用mask="999 9999 9999"和keyboard="number" is-type="china-mobile"

**Comment by airyland** [comment]
如文档所写，不能使用 china-mobile 验证了，暂时只能在提交时自行验证。keyboard 貌似不冲突。

**Comment by KarnaughK** [comment]
好的，谢谢
