### ISSUE TITLE
Search组件在结果列表滑动的时候展示不正常

### ISSUE THREAD

**Issue by ManorNotMaNong** [airyland/vux#2042]
代码:
官方示例
机器:
华为荣耀
截图如下:
![_20170926171501](https://user-images.githubusercontent.com/24819542/30852631-06e378fa-a2df-11e7-9b49-6d84e98eb132.jpg)
![_20170926171507](https://user-images.githubusercontent.com/24819542/30852634-06e79d90-a2df-11e7-878e-9bbb7b6027fe.jpg)
![_20170926171511](https://user-images.githubusercontent.com/24819542/30852632-06e3cecc-a2df-11e7-9a22-973ed5e3e572.jpg)
![_20170926171514](https://user-images.githubusercontent.com/24819542/30852633-06e4caca-a2df-11e7-8283-7f6a7f0bf464.jpg)

**Comment by graysheeep** [comment]
fixed #2054
