### ISSUE TITLE
神奇的bug

### ISSUE THREAD

**Issue by KarnaughK** [airyland/vux#2046]
我使用 PopupPicker
```
<popup-picker :show.sync="showTimePicker"
                      :show-cell="false"
                      :data="timeData"
                      v-model="selectTime">
</popup-picker>
```
这是我的数据

```
timeData: [
          [{name: "今天", value: 0}, {name: "明天", value: 1}],
          ['00点', '01点', '02点', '03点', '04点', '05点', '06点', '07点', '08点', '09点',
            '10点', '11点', '12点', '13点', '14点', '15点', '16点', '17点', '18点', '19点',
            '20点', '21点', '22点', '23点'],
          ['00分', '15分', '30分', '45分']
        ],
selectTime: [],
```

然后我监测`selectTime`的变化时发现，如果弹出框不去动第一列，那么`selectTime`的第一个item会是一个object。。。。
![image](https://user-images.githubusercontent.com/13878673/30894012-b1e7f30e-a373-11e7-809a-eccdc24e069d.png)

如果动了第一列，就成字符串了。。。。
![image](https://user-images.githubusercontent.com/13878673/30894055-ebdb7478-a373-11e7-9b36-032ce171d9f7.png)

PS：我试过`timeData`里的item全用{name,value}的形势，结果一样

**Comment by KarnaughK** [comment]
补充：只要动过第一列，以后的就都是字符串了

**Comment by joy-yu** [comment]
请确保列表项的value值是字符串，使用数字会出错。

**Comment by KarnaughK** [comment]
@joy-yu 

还真是这样。。。。

好吧，这就有点蛋疼了。。因为我这`PopupPicker`设置的`“今天”、“明天”`，展示的时候也要是`“今天”、“明天”`，最后取值的时候却需要一个日期。。

所以我想到的另起一个`timeConvert:[{date:'2017-9-27',dateText:'今天'}]`这样的数组，然后将`PopupPicker`的`value`设置成`timeConvert`的`index`，到时候在`timeConvert`里头去取要用的值。。。。

**Comment by airyland** [comment]
文档有注明，目前只支持字符串值。至于取值和展示值确实需要自行转换了。
