### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by CuityMiko** [airyland/vux#2047]
你好，问一下，我按照如下方式配置的webpack.base.conf.js
const vuxLoader = require('vux-loader')
const vuxConfig = require('./vux-config')
module.exports = vuxLoader.merge(webpackConfig, vuxConfig)
在npm run build后，运行编译的dist目录会报“webpackJsonp is not defined”这个错，是怎么回事呢，麻烦给解决一下吧，谢谢

**Comment by airyland** [comment]
问题不清不楚，无法解决。另外 webpack 问题和组件无关，不给解决。
