### ISSUE TITLE
confirm组件确定和取消按钮快速点击会连续触发回调函数

### ISSUE THREAD

**Issue by fuerpeng** [airyland/vux#2048]
官网的链接：
https://vux.li/#/zh-CN/demos/confirm
图片如吓：
![bug](https://user-images.githubusercontent.com/24818415/30904766-7e90bb30-a3a5-11e7-8bd0-eb963a895548.gif)

**Comment by ccw-kevin** [comment]
为什么confirm 插件 只用插件形式调用会出现如下问题呢?
<img width="466" alt="2017-09-27 6 12 48" src="https://user-images.githubusercontent.com/32184471/30908229-949df6ee-a342-11e7-930b-60d5cd90fc48.png">

<img width="779" alt="2017-09-27 6 13 51" src="https://user-images.githubusercontent.com/32184471/30908294-ca5e59ae-a342-11e7-99d9-633b8e88a169.png">


这是什么原因?

**Comment by see311** [comment]
你有没有注册全局插件

**Comment by airyland** [comment]
@ccw-kevin this 问题，请看文档。
![image](https://user-images.githubusercontent.com/559179/30947083-44c3c1aa-a43a-11e7-95c6-6e39c55c59eb.png)

**Comment by ccw-kevin** [comment]
请问在哪里注册全局组件?
