### ISSUE TITLE
同一页面同时弹出多个popup的问题。

### ISSUE THREAD

**Issue by tianyong90** [airyland/vux#205]
### Android

同一页面同时弹出多个popup，关闭其中一个后，空白部分的半透明遮罩会消失，而且点击空白部分也没法关闭popup层了。

**Comment by airyland** [comment]
这部分没有做优化。是什么样的场景需要弹出多个popup?

**Comment by tianyong90** [comment]
@airyland 自己项目里有个页面。一个弹出层里显示checklist用于从从已有数据库选择，而下面有个新增按钮，点击后弹出另一个popup层，用于在里面填写数据进行新增操作，保存后关闭。
普通的H5页面，非单页应用，也没用什么vue-router啥的。我想像这种使用场景应该还是该考虑的。

**Comment by airyland** [comment]
@unclay  这里还需要一个设置，允许点击遮罩时不关闭popup, 由popup内部自行提供关闭按钮或者实现逻辑。在一些需要强制用户做操作的场景时很有用，也用于防止用户误点击触发了关闭导致未保存的数据丢失。

```
  hideOnBlur {
    type: Boolean,
    default: true
  }
```

**Comment by airyland** [comment]
@tianyong90 在移动端弹出多个popup不是很好的方式，可以考虑一下支付宝的交互方式，一个popup里如果想显示另一个窗口，向右滑出一个带有返回按钮窗口，操作后会可以滑动回前一个或者自动滑动回一个，减少交互的复杂度，并且也很有引导性。

**Comment by tianyong90** [comment]
@airyland :ok_hand: 多谢！
