### ISSUE TITLE
覆盖原样式的问题

### ISSUE THREAD

**Issue by RickCole21** [airyland/vux#2050]
如何在vue文件的style标签内，覆盖组件原样式，并不需要去掉`scoped`,现在支持了吗

**Comment by keepfool** [comment]
这是vue-loader的问题，要重写子组件的样式，请用 `>>>`。
参考：[https://github.com/vuejs/vue-loader/issues/661](https://github.com/vuejs/vue-loader/issues/661)

**Comment by RickCole21** [comment]
@keepfool 多谢解答

现在将如下样式，直接写入style内即可生效：
```
<style scoped>
  .my-component-parent >>> .my-component-child {
    color: #000
  }
</style>
```
但是将如上样式通过@import引入之后，便无法生效，请问有解决办法吗，谢谢~

**Comment by RickCole21** [comment]
使用`/deep/`可以解决引用的问题，多谢

**Comment by Adele0** [comment]
> 使用`/deep/`可以解决引用的问题，多谢

你现在遇到浏览器提示： 废弃警告没|？？【[Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.】
