### ISSUE TITLE
关于Picker组件DPR适配之后的BUG修改

### ISSUE THREAD

**Issue by petersmu** [airyland/vux#2051]
我之前提过一次Picker的组件修改自适应，已经在2.6.2版本更新了，[#1979](https://github.com/airyland/vux/issues/1979)

目前项目中出现了问题，在给一个初始值的时候会发生选择不准确的情况，比如截图中显示的时间选择，当天时间是2017年9月27日，但picker选择的是26日：
![image](https://user-images.githubusercontent.com/12507715/30910957-53635364-a3b9-11e7-9238-433c3619a90d.png)

经排查是scroller.js里面的问题，我在scrollTo方法这里打印出数值如下：
![image](https://user-images.githubusercontent.com/12507715/30910809-dcf384a6-a3b8-11e7-9556-a824ebdb47d3.png)
![image](https://user-images.githubusercontent.com/12507715/30910826-ea7c89f6-a3b8-11e7-8eaf-04087e4c8e3d.png)

其实根本原因不在这里，而是从最开始计算__minScrollTop等数值的时候就出现了这种长浮点数问题，不过最终影响选择的地方在这里，所以我在这里加了一个取一位小数的方法：
``` javascript
top = Math.round((top / self.__itemHeight).toFixed(1)) * self.__itemHeight
```

这样修改之后就没有出现选择错误的问题了，但这样会出现另一个问题，滚动到最后一个选项的时候不会回弹：
![image](https://user-images.githubusercontent.com/12507715/30912292-9845dc68-a3be-11e7-8ede-0348d766fddd.png)
看打印结果发现是这样的：
![image](https://user-images.githubusercontent.com/12507715/30912357-c153115c-a3be-11e7-8119-d378f7b3f3ef.png)
最后一个选项本身计算的值就是临界与.5的，所以为了区分最后一个和中间的选项，我将取小数位数改为5位，这样就不会把最后一个选项的计算值四舍五入到.5了。

所以只需要把scroller.js文件中的 
``` javascript
top = Math.round(top / self.__itemHeight) * self.__itemHeight
```
替换成
``` javascript
top = Math.round((top / self.__itemHeight).toFixed(5)) * self.__itemHeight
```
就可以了，我在不使用dpr的页面中试过，不会产生影响，你可以自己试一下，如果没问题的话希望能在下个版本中修改这个问题，谢谢！

**Comment by airyland** [comment]
可以发个 PR

**Comment by petersmu** [comment]
PR已提交了， @airyland 看一下吧，谢谢！

**Comment by petersmu** [comment]
@airyland 这个PR最后一步检查报错了是什么意思？
![image](https://user-images.githubusercontent.com/12507715/31000226-b1f58d3a-a50c-11e7-9806-e30a641320ef.png)
