### ISSUE TITLE
老问题啦，打包体积过大，这次webpack3.6

### ISSUE THREAD

**Issue by ccode-code** [airyland/vux#2056]
贴一下我的配置

![image](https://user-images.githubusercontent.com/10229333/30959285-47f406c6-a405-11e7-8d53-ac3b025653e3.png)
![image](https://user-images.githubusercontent.com/10229333/30959296-50885e54-a405-11e7-945a-79998c923f51.png)
![image](https://user-images.githubusercontent.com/10229333/30959302-56982a04-a405-11e7-97ae-cd6c37a124ea.png)
![image](https://user-images.githubusercontent.com/10229333/30959246-244a50c2-a405-11e7-89d7-1bddf76b1d56.png)
"vux": "^2.6.4"
"vux-loader": "^1.1.9"
"webpack": "^3.6.0"
开启eslint

代码分块：
![image](https://user-images.githubusercontent.com/10229333/30959377-8ea8688c-a405-11e7-8f68-0d6903cf9b58.png)

老大帮我一下，翻遍vux vux-loader 的issues  以前的方法依旧无法解决。
好闹心啊，大神同解，参拜

**Comment by ccode-code** [comment]
@airyland 老大

**Comment by airyland** [comment]
建个 repo 看看。

**Comment by ccode-code** [comment]
@airyland http://....

npm run test 
其他命令暂时没有做

src/service/component
src/service/pulgin

这两个文件引入了vux

**Comment by airyland** [comment]
babel 解析的问题，升级  vux-loader 试试。

**Comment by ccode-code** [comment]
感谢，升级1.1.10问题解决。
