### ISSUE TITLE
Adding programmable scrolling control. 

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#206]
I'm wondering if it's possible to scroll the page by giving an offset Y, or scroll to a specific element. Thus it can be used as an in-page location.

**Comment by dangyuluo** [comment]
Like [iScroller](https://github.com/cubiq/iscroll#scrolling-programmatically)

**Comment by airyland** [comment]
Scroller is base on http://xscroll.github.io/, so technically speaking it supports scrolling by offset. You can get the scroller Component by ref and call the function on `_xscroll`.

https://github.com/airyland/vux/blob/master/src/components/scroller/index.vue#L141
