### ISSUE TITLE
fixed布局与输入框在uc浏览器页面错乱

### ISSUE THREAD

**Issue by XIAOGUIGUI** [airyland/vux#2061]
![image](https://user-images.githubusercontent.com/8243283/30998052-906cdd0c-a4fe-11e7-95c2-ff38c9023113.png)

**Comment by airyland** [comment]
看不懂怎么重现错乱。另外看你截图是 iPhone，浏览器本身没问题，仅在UC 本身导致的问题是不会处理的。
