### ISSUE TITLE
动态生成多个x-number,如何同时知道是哪个x-number发生了变化及变化的值

### ISSUE THREAD

**Issue by kufei88** [airyland/vux#2065]
```
<div  v-for="item in list" >
    <x-number  v-model="item.value" @on-change="change(item.id)"></x-number>
</div>
```

- 如上面这样，把id放进去的话，change事件里面就只能得到id，而得不到value了，不加id的话，又不知道怎么知道是哪一个x-number发生了变化

- 还有一个问题就是我这个是一个组件，父组件把list传给它，它里面的x-number改变了之后，父窗体要得到改变之后的值，应该用哪种方法

**Comment by xiaolinui** [comment]
@on-change="value => change(item.id, value)" 吧

**Comment by kufei88** [comment]
楼上的可以，谢谢
