### ISSUE TITLE
inline-calendar组件，render-function属性，每次点击日期时都会触发，设置:render-on-value-change="false"无效

### ISSUE THREAD

**Issue by zqinmiao** [airyland/vux#2066]
## vux版本：: 2.2.1

```
<inline-calendar :render-on-value-change="false" :render-function="render"></inline-calendar>
```

js代码：
```
methods:{
  render(){
     console.log(1)
  }
}
```

### 问题描述：
点击日期时，每点击一次，就会触发render方法。设置了```render-on-value-change```属性为“false”，依然无效。

请问，```render-function```属性，应该是首次渲染时触发，还是每次日期改变时触发呢？烦请答疑，谢谢

**Comment by nikitakhokhlov** [comment]
Hello. We introduce a blockchain-powered software platform for flying vehicles. We give people affordable and spectacular way to avoid traffic jams in big cities
If you’re interested and excited about future that is already today you can contact these guys:
http://promo.mcfly.aero?utm_source=vux.li&utm_medium=reply&utm_term=3&utm_content=about&utm_campaign=mcfly
