### ISSUE TITLE
统一一下组件内的样式规范吧

### ISSUE THREAD

**Issue by flynntsc** [airyland/vux#207]
1.src/components/ 内的组件样式何不统一一下？如全部使用less + scoped,避免样式重名问题。
2. vue-loader带有autoprefixing功能，无需自己加浏览器前缀，若标准有变或者无需前缀了，到时autoprefixing自动处理就好。

**Comment by airyland** [comment]
不觉得scope有必要，因为现在在进行namespace的规范，用`vux-`作前缀。目前也并没有加前缀的组件吧？之前已经处理过一遍，欢迎指出，或者直接PR。

**Comment by xiaolongyuan** [comment]
全局注册呢？ 一个个引入很麻烦哦

**Comment by xiaolongyuan** [comment]
https://github.com/JosephusPaye/Keen-UI/blob/master/src/index.js

**Comment by xiaolongyuan** [comment]
```
import './helpers/modality';

import UiAlert from './UiAlert.vue';

const Keen = {
    UiAlert,

    install(Vue) {
        Vue.component('ui-alert', UiAlert);
    }
};

module.exports = Keen;

```

**Comment by unclay** [comment]
全局注册太笨重了吧，自己引入自己需要的，这样才能达到最轻

**Comment by airyland** [comment]
xiaolongyuan 你不会想在移动端一次性引入这n个组件吧？

**Comment by xiaolongyuan** [comment]
我做的是 hybrid ...

**Comment by airyland** [comment]
你可以这样，引入vux.js，然后遍历一下注册，就一个循环的事。

**Comment by xiaolongyuan** [comment]
还是不偷懒好了 哈哈

**Comment by xiaolongyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/3142363/15601840/56a17af8-2424-11e6-8472-57cc225926b9.png)
这种组件呢  ？

**Comment by xiaolongyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/3142363/15601853/6775467a-2424-11e6-9d63-c67687c077cc.png)
 是个链接或者别的  checklist 不行

**Comment by airyland** [comment]
这个不会封装，不过我有考虑左边的check按钮做一个小组件。

**Comment by flynntsc** [comment]
个人喜好偏向：less + scoped > .vux-前缀

**Comment by xiaolongyuan** [comment]
加前缀风格统一也蛮好的

**Comment by xiaolongyuan** [comment]
省的 这样  
```
{
vuxAlert:Alert
}
```

**Comment by airyland** [comment]
@xiaolongyuan 这是啥意思？

**Comment by xiaolongyuan** [comment]
如果要使用 vux- 前缀不就得这样加入组件中么

**Comment by airyland** [comment]
@xiaolongyuan  vux-针对css样式。 vux前缀只是在umd文件中使用，怎么用也不会像你这样用。。

```
Vue.component('alert', vuxAlert)
```

**Comment by xiaolongyuan** [comment]
纳尼 
![image](https://cloud.githubusercontent.com/assets/3142363/15602095/cba15e4e-2425-11e6-82a4-654f01286515.png)

**Comment by flynntsc** [comment]
less + scoped方案主要是参考React里用的css modules方案，最大化避免样式冲突问题。

.vux-*方案是否就要严格规定所有class均要加前缀（.weui-除外），不可出现如下情况

```
.dp-time{...} //无前缀

.vux-thing .ipt{} // .ipt无前缀
```

整个项目下来，就只能是.vux-和.weui-的样式存在（以及部分scoped）

**Comment by airyland** [comment]
scoped 方案其实也避免不了样式被覆盖，而组件设计时却要考虑到要方便使用者可以覆盖部分样式。

**Comment by flynntsc** [comment]
@xiaolongyuan vux-针对css样式，对引用组件时的写法无影响。

**Comment by xiaolongyuan** [comment]
你两接着讨论吧 我参合进去 好像不在一个概念上   匿了

**Comment by airyland** [comment]
@xiaolongyuan 你这个项目上线时拿出来瞧瞧。

**Comment by xiaolongyuan** [comment]
ok

**Comment by flynntsc** [comment]
既然现在已经进行namespace的规范，用vux-作前缀，是否如.weui-那样的标准？

```
// 正确
  .vux-dp-time{...}
  .vux-dp-time .vux-dp-day{...}

// 不允许
  .dp-time{...}
  .dp-time .dp-day{...}
  .vux-dp-time .dp-day{...}
```

确认下规范/标准，好提PR。

**Comment by airyland** [comment]
@flynntsc yes! 全部会规范成这样。

**Comment by flynntsc** [comment]
@airyland 

OK! 我尝试下！
