### ISSUE TITLE
Qrcode在后台数据加载完成前，因没有this.value报错

### ISSUE THREAD

**Issue by shiLinQing407** [airyland/vux#2070]
`
                  <qrcode :value="member_data.card_no" :size="160" type="img"></qrcode>
               `

:value 绑定后台加载过来的数据。在模板渲染时，因为数据还未加载完成，所以Qrcode/index.vue文件中：
第70行：
`qrcode.addData(this.value)` 
value值为undefined，导致报错

vue.common.js?e881:481 [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'length' of undefined"

请教大佬们有什么办法能不报错吗？（虽然不影响使用，反正有数据后会重新渲染一次）

**Comment by airyland** [comment]
暂时可以用 `v-if` 实现在有值时渲染。

**Comment by shiLinQing407** [comment]
多谢指教！
