### ISSUE TITLE
图片预览

### ISSUE THREAD

**Issue by Diamondjcx** [airyland/vux#2072]
<template v-if="submitTaskInfo.TaskDeliverImg">
							<img class="previewer-demo-img" v-for="(item, index) in list" :src="item.src" width="100" height="100" @click.stop.prevent="show(index)" :key="index">
							<div v-transfer-dom>
								<previewer :list="list" ref="previewer" :options="options"></previewer>
							</div>
</template>

这是options配置
options: {
				getThumbBoundsFn(index) {
					let thumbnail = document.querySelectorAll('.previewer-demo-img')[index]
					let pageYScroll = window.pageYOffset || document.documentElement.scrollTop
					let rect = thumbnail.getBoundingClientRect()
					return { x: rect.left, y: rect.top + pageYScroll, w: rect.width }
				}
这是方法
	show(index) {
			debugger
			this.$refs.previewer.show(index)
		},

求指导

**Comment by airyland** [comment]
代码没有格式化(面对这样的问题详情你自己也会头疼吧。不会格式化？麻烦 google 一下)
问题没有描述清楚，不知道你想表达什么
代码不要有业务逻辑(不然，我不还要看懂你业务逻辑来添加测试数据，帮维护者省点时间吧)

**Comment by Diamondjcx** [comment]
sorry,我重新粘一下~
