### ISSUE TITLE
Scroller的位置如何在tab切换时不要相互影响，而是独立的

### ISSUE THREAD

**Issue by gdutwyg** [airyland/vux#2077]
有三个tab， tab下面对应的内容时用scroller包着的，如果当tab1切换到tab2时，tab内容显示的位置应该是tab2内容显示的位置，而不是tab1内容显示的位置的高度，就是说scroller内容显示的是当前tab滚动的位置，而不是之前tab滚动的位置
![scroller](https://user-images.githubusercontent.com/11848087/31584239-628f9690-b1dd-11e7-9b5d-09600229d3e7.png)

**Comment by airyland** [comment]
scroller 已经不再维护，另外这里你嵌套了 scroller 具体的位置逻辑实现不可能在 scroller 上能实现。
