### ISSUE TITLE
vue-router "saveScrollPosition: true" not working when list page use Scroller component

### ISSUE THREAD

**Issue by wjs** [airyland/vux#208]
### Version
vux@0.0.118-rc1

### Android or iOS, which browser?
All browser

### Your Codes 

``` html
<scroller lock-x scrollbar-y use-pullup use-pulldown
            @pullup:loading="loadMore"
            @pulldown:loading="refresh"
            v-ref:scroller>
            <div>
                <list-item :item="item" v-for="item in items"></list-item>
            </div>
</scroller>
```

### Expected behavior and actual behavior.
when back to list page from the detail page, the scoller can scroll to the previous position.

### Steps to reproduce the problem
- vue-router with confing `history: true` and `saveScrollPosition: true`;  
- a list page use scroller component; 
- a detail page

**Comment by airyland** [comment]
vue-router doesn't support vux's scroller. It's complexed especially when you fetch datas from server.

**Comment by wjs** [comment]
An alternative: [mint-loadmore](https://github.com/mint-ui/mint-loadmore)

**Comment by airyland** [comment]
Does this component solve the your position problem?

**Comment by wjs** [comment]
No, just working on the first page. 😂
