### ISSUE TITLE
Module build failed: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Jason2048** [airyland/vux#2080]
按照文档增加以下配：
{
 name: 'i18n',
 vuxStaticReplace: true,
 vuxLocale: 'en'
}

然后报错：
error  in ./src/App.vue

Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /Users/tiangang/workspace/bigbear_platform/node_modules/vux-loader/src/template-loader.js:148:26
    at Array.forEach (native)
    at Object.module.exports (/Users/tiangang/workspace/bigbear_platform/node_modules/vux-loader/src/template-loader.js:125:17)

 @ ./src/App.vue 10:0-467
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

查看源码发现这个参数extractToFiles不能为undefined，如下
{
	name: 'i18n',
	vuxStaticReplace: true,
	vuxLocale: 'en',
	extractToFiles: ''
}

**Comment by airyland** [comment]
临时加个文件，下个版本修复。

**Comment by airyland** [comment]
vux-loader@1.1.15 已经修复
