### ISSUE TITLE
about vux import component warning ‘ 如果你看到这一行，说明 vux-loader 配置有问题’

### ISSUE THREAD

**Issue by Evansy** [airyland/vux#2081]
Today I  run my object, But it throw some warnings ' 如果你看到这一行，说明 vux-loader 配置有问题....',

I upgrade vux & vux-loader, but not fix it,

And then I change `import { Swiper, SwiperItem } from "vux"` to `import { Swiper, SwiperItem } from 'vux'`(change double quote "vux" to single quote 'vux'), it fixed...;

I can't understand why...

**Comment by airyland** [comment]
vux-loader version?

**Comment by Evansy** [comment]
@airyland 
"vue": "^2.4.2",
"vux": "^2.6.5",
"vux-loader": "^1.1.13",

**Comment by yhZhouYh** [comment]
appeared like yours

**Comment by airyland** [comment]
fixed on vux-loader@1.1.15
