### ISSUE TITLE
A problem in my project when using the component of Datetime .

### ISSUE THREAD

**Issue by weixisheng** [airyland/vux#2082]

**Comment by weixisheng** [comment]
```html
       <group>
          <datetime title="开始日期：" v-model="date1" placeholder="选择日期"></datetime>
          <datetime title="结束日期：" v-model="date2" placeholder="选择日期"></datetime>          
        </group>
```
![qq 20171016155805](https://user-images.githubusercontent.com/16042305/31601386-44c3528c-b28c-11e7-8a76-83ec6b67e729.png)

**Comment by airyland** [comment]
date1 值为什么？

**Comment by weixisheng** [comment]
```javascript
data() {
       return {
            date1: '',
            date2: ''

    }
}

```
就是普通初始化，空值

**Comment by airyland** [comment]
那么上面也没有说明重现步骤吧? 
先选中一个值关闭后再打开，中间一列消失，对应年日位置不对？是我描述这样吗，不是的话麻烦请一次性补充完整。

**Comment by weixisheng** [comment]
抱歉。
1、一开始什么都没有，然后点击cell，弹出datetime组件
![qq 20171016165930](https://user-images.githubusercontent.com/16042305/31603671-72fa654e-b293-11e7-9c0e-84f5740f2ca5.png)

2、滑动开始选择日期
![qq 20171016170033](https://user-images.githubusercontent.com/16042305/31603715-92f90580-b293-11e7-9245-0ef1dfc30498.png)
3、点击确定之后能显示一个时间，但不是之前选中的日期
![qq 20171016170055](https://user-images.githubusercontent.com/16042305/31603744-b1c466a8-b293-11e7-950d-da4079e85f9d.png)

**Comment by airyland** [comment]
浏览器是 Chrome?，官方 demo 有没有能重现的？

**Comment by weixisheng** [comment]
浏览器信息：版本 63.0.3218.0（正式版本） （64 位）
vux信息：@2.6.5，官方demo中没有重现的。
重新初始化了一个新的项目，也没什么问题。
【备注：出现问题的项目同时使用了其他的UI库，按道理应该不至于冲突】
![qq 20171017093443](https://user-images.githubusercontent.com/16042305/31642754-3b168ed2-b31f-11e7-8285-7e14ed61a9f7.png)

**Comment by airyland** [comment]
本地无法重现，目测就是和其他组件出现了冲突。可以审查下相关样式检查一下，如果不行，帖个 repo 看看。

**Comment by weixisheng** [comment]
## 1、这是正常的情况，日期2017-10-19
![qq 20171019095401](https://user-images.githubusercontent.com/16042305/31750632-cfce2342-b4b3-11e7-91b0-08fc363d9918.png)
![qq 20171019095448](https://user-images.githubusercontent.com/16042305/31750634-d5a45f16-b4b3-11e7-9259-61230656e0e3.png)
## 2、这是异常的情况，日期2017-10-19
![qq 20171019095459](https://user-images.githubusercontent.com/16042305/31750636-d5d8e240-b4b3-11e7-862a-545fe62e8fe9.png)
![qq 20171019095557](https://user-images.githubusercontent.com/16042305/31750637-d60c97b6-b4b3-11e7-9ed1-b0fe8a3a104c.png)
## 3、对比发现异常的情况下，translateY的值是正常情况下的两倍。为了避免异常，我暂时跳过vux的datetime组件

**Comment by airyland** [comment]
html 上的属性 data-dpr 导致的。上次是有用户反馈应该根据 dpr 设置距离因此有了这个问题。考虑下怎么解决。
