### ISSUE TITLE
使用了fastclick后，点击延迟解决了，但在IOS设备中会出现事件反馈延迟2s左右

### ISSUE THREAD

**Issue by stonemakers** [airyland/vux#2083]
# 问题代码

``` javascript
<a href="#" :class="colorStyle" @click="alert('点击总是延迟1-2s才弹出')" >点击一下</a>
``` 

### 在main.js 中把fastclick禁用后，点击才能恢复正常。。求解

@fundon @airyland @blue5tar @gzlboy @naifen00

**Comment by airyland** [comment]
抱歉，回复比较晚。fastclick 支持加个特定类名忽略元素。

https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick

`<a class="needsclick">Ignored by FastClick</a>`
