### ISSUE TITLE
能否为picker增加一个控制当data变化时的回弹动画的是否显示的prop？

### ISSUE THREAD

**Issue by wangshantao** [airyland/vux#2084]
在使用地址选择插件的时候，使用的自己的数据。由于采用异步加载数据，每次用更新data时，picker都会抖动一下（picker的Demo里set Lists也会这样，不过我的是滚动时触发），体验很不好。 
![123](https://user-images.githubusercontent.com/14883268/31606942-20a26544-b29d-11e7-8323-196f91d444c1.gif)
vux@2.6.5, vux-loader@1.1.6, webpack@2.7.0, node@6.11

**Comment by airyland** [comment]
暂时无法支持，数据变化时是重新渲染，并不是局部更新。Picker 目前不支持你说的滚动时[安静]更新数据。
