### ISSUE TITLE
vux swiper 图片点击如何使用vue-router进行跳转

### ISSUE THREAD

**Issue by krisQT** [airyland/vux#2088]

**Comment by krisQT** [comment]
const urlList = baseList.map((item, index) => ({
    url: 'http://m.baidu.com',
    img: item.img,
    fallbackImg: item.fallbackImg,
    title: `(可点击)${item.title}`
  }));

怎么将dome的url换成vue-router

**Comment by airyland** [comment]
直接用 vue-router 的路由语法即可。比如  `/path/dir`, 或者对象 `{path: '/path', query: {}}`。

**Comment by YuFy1314** [comment]
> 直接用 vue-router 的路由语法即可。比如 `/path/dir`, 或者对象 `{path: '/path', query: {}}`。

这个是怎么个写法, 

数据一一放进来, 放进来的url要怎么样才能在点击的时候把地址和参数传给路由

**Comment by YuFy1314** [comment]
![image](https://user-images.githubusercontent.com/24446694/59009882-ebc0d800-8861-11e9-91a0-2724459d0594.png)
数据一一放进来, 放进来的url要怎么样才能在点击的时候把地址和参数传给路由
