### ISSUE TITLE
使用vue 2.5版本后，控制台出现关于vux的警告。

### ISSUE THREAD

**Issue by pi-ka-qiu** [airyland/vux#2089]
warning  in ./~/vux/src/components/popup-radio/index.vue

(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.

 @ ./~/vux/src/components/popup-radio/index.vue 9:2-272
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/Home/children/Match/Match.vue
 @ ./src/views/Home/children/Match/Match.vue
 @ ./src/views/Home/children/Match/index.js
 @ ./src/router/Home/index.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 warning  in ./~/vux/src/components/x-address/index.vue

(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.

 @ ./~/vux/src/components/x-address/index.vue 5:2-272
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/Home/children/Match/Match.vue
 @ ./src/views/Home/children/Match/Match.vue
 @ ./src/views/Home/children/Match/index.js
 @ ./src/router/Home/index.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by skyshirt** [comment]
同上，一样的问题，element-ui已经全局把业务代码替换成slot-scope
vux有更新了吗

**Comment by airyland** [comment]
考虑兼容，并不想一下子把 vue 依赖版本提到 2.5.0，先用几天 2.4 吧，这几天更新。

**Comment by airyland** [comment]
可以使用最新 vux-loader 解决这个警告。
