### ISSUE TITLE
当有popup显示时，toast可能被其遮挡而不可见。

### ISSUE THREAD

**Issue by tianyong90** [airyland/vux#209]
### 0.0.117

问题题。当一个页面中有popup弹出，此时使用toast提示时提示层被popup层遮挡而不可见。

**Comment by tianyong90** [comment]
继查样式后发现vux.css中weui_toast的z-index值仅为3，可考虑适当增大以解决该问题。

**Comment by airyland** [comment]
这个交互有点奇怪，使用toast来表示成功，那么popup应该是已经关闭了才对？

**Comment by tianyong90** [comment]
@airyland 我用来提示失败信息，此时popup层不关闭

**Comment by airyland** [comment]
失败应该用Alert, 或者直接在popup里提示，弹两个东西不是很科学。

**Comment by tianyong90** [comment]
用法可能是不科学。但这z-index:3，显示不应该是一个弹层性质的元素应该有的……

**Comment by xiaolongyuan** [comment]
+1
