### ISSUE TITLE
动态依赖组件时，会将import的css代码打包在js里面，不动态依赖时，会打包在css里面。

### ISSUE THREAD

**Issue by zhuguibiao** [airyland/vux#2092]

**Comment by airyland** [comment]
这是 webpack 相关 issue，暂时无法在 vux 或者  vux-loader 上解决。

**Comment by airyland** [comment]
配置 extractTextPlugin 的 allChunks 为 true 可以实现 css 抽离，该 issue 关闭。
https://doc.vux.li/zh-CN/faq/dupicate-style.html
