### ISSUE TITLE
swiper+上拉加载组件，swiper的高度不能自适应

### ISSUE THREAD

**Issue by zjtt** [airyland/vux#2093]

**Comment by zjtt** [comment]
swiper+上拉加载组件高度不能自适应

**Comment by airyland** [comment]
如果你所谓的上拉加载组件是 scroller 的话：

- scroller 不再维护
- swiper 文档里说明了 swiper 不适用于复杂的嵌套场景，高度并不会自适应
- scroller 文档里写了不再维护，issue 不会处理
- issue template 写了不要提 scroller 的 issue

![image](https://user-images.githubusercontent.com/559179/31752979-788bb9a2-b4c0-11e7-8564-b2435cf82151.png)

![image](https://user-images.githubusercontent.com/559179/31752996-88d2e952-b4c0-11e7-825f-5dec94a2bb33.png)

![image](https://user-images.githubusercontent.com/559179/31753027-b97f36c8-b4c0-11e7-89da-eefda1837572.png)
