### ISSUE TITLE
PopupPicker

### ISSUE THREAD

**Issue by qazse41** [airyland/vux#2095]
PopupPicker  这个组件选中值时 不能获取数组下标
```
[{value:1,id:2},{value:3,id:4}]
````
我想获得选中的id

**Comment by qazse41** [comment]
大佬 说下呗
`
 @on-shadow-change="typeChange"
 typeChange(ids,value){
      console.log('typeChange==>',ids)
      console.log('typeChange==>',value)
    }
`
这个ids和value一模一样

PopupPicker的api返回的结果都是value  想获取对应的id只能遍历  不想遍历 有别的获取方法吗

**Comment by wg5945** [comment]
这个？

https://github.com/airyland/vux/blob/9beee8e87152243b4a7475df6adc8adb5712ee62/src/demos/PopupPicker.vue#L27

**Comment by qazse41** [comment]
这个也是获取value  而选中项是value 绑定的值也是value

**Comment by airyland** [comment]
popup-picker 绑定的数据格式是没有 id 这个 key 的，支持的是  name 和 value，你将 id 换成 name 试试。

**Comment by tong3jie** [comment]
绑定的data类型为数组套数组，为啥还报 Invalid prop: type check failed for prop "value". Expected Array, got String.

**Comment by airyland** [comment]
@tong3jie 避免浪费大家时间，提问题至少上个代码吧。提醒一下，对象类型请使用 v-bind 或者  `:value`。

**Comment by tong3jie** [comment]
<popup-picker class="fontsize" title="银行" :data="banklists" v-model="bank" @on-change="bankChange" placeholder="请选择您的开户行"></popup-picker>

data() {
    return {
      banklists: [['工商银行', '中国银行', '农业银行', '建设银行', '招商银行', '兴业银行', '浦发银行', '中信银行', '华夏银行', '民生银行', '交通银行', '广大银行', '广发银行', '平安银行', '邮储银行']],
  },

**Comment by airyland** [comment]
@tong3jie 没有看到 bank 的定义，至少要把 bank 初始化为数组吧。

``` js
data () {
  return {
    bank: []
  }
}
```

**Comment by tong3jie** [comment]
@airyland 
抱歉抱歉，文档还没有吃透。
