### ISSUE TITLE
运行项目 出现如下警告

### ISSUE THREAD

**Issue by yhZhouYh** [airyland/vux#2096]
version: vux:2.6.5 vux-loader:1.1.13 vue: 2.4.2

Compiled with 3 warnings                                                                                                                  15:47:40

 warning  in ./node_modules/vux/src/components/X-input/index.vue

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic...........

**Comment by airyland** [comment]
比较奇怪，`X-input` 源码应该没有这样大写字母开头的目录。

**Comment by tong233** [comment]
和我之前遇到的一样，有地方引"vux"写成大写的了

**Comment by airyland** [comment]
尝试重新 npm 安装，可以肯定的是发布的代码是没有大写目录的。
