### ISSUE TITLE
关于 previewer 组件

### ISSUE THREAD

**Issue by brahmachen** [airyland/vux#2097]
你好，希望 previewer 组件可以添加图片切换时的事件比如 onChange，参数的话传一个 index 就行啦，谢谢

**Comment by brahmachen** [comment]
你好，暂时不用了，已经通过其他方式解决

**Comment by so2bin** [comment]
@brahmachen 请问怎么解决?

**Comment by brahmachen** [comment]
@so2bin 通过photoswipe的api解决的
