### ISSUE TITLE
pull2refresh component

### ISSUE THREAD

**Issue by fangjj** [airyland/vux#21]

**Comment by fangjj** [comment]
可以增加上拉刷新，下拉加载更多吗

**Comment by airyland** [comment]
@fangjj 已添加到0.1.0计划中

**Comment by hq5544** [comment]
但是我觉得，下拉刷新不应该加入到vux里面，毕竟微信没有下拉刷新，weui也没有。单独一个项目实现可能更好理解。

**Comment by airyland** [comment]
@hq5544 开发上的想法是这样的，vux并不是完全为微信webview开发的，理论上也可以封装成App，而在一个完整的App里下拉刷新还是常见的需求。

**Comment by hq5544** [comment]
@airyland 秒回啊。。。是的哦，可以做成一个工具集。
