### ISSUE TITLE
npm 安装的vux代码有问题

### ISSUE THREAD

**Issue by LiangFuzhi** [airyland/vux#210]
Version

0.0.117

Android or iOS, which browser?

Android and iOS

Your Codes

用npm命令安装的vux里面的swiper组件代码有问题 
npm安装是这样的
`<template> <div class="slider"> <div class="swiper" :style="swiperStyle"> <slot></slot> <div class="item" v-for="item in list" @click="clickListItem(item)"> <a :href="item.url"> <div class="img" :style="{backgroundImage: buildBackgroundUrl(item.img)}"></div> <p class="desc">{{item.title}}</p> </a> </div> </div> <div class="indicator" v-show="show_dots && list.length > 1"> <a href="javascript:" v-for="(index, item) in list"> <i class="icon_dot" :class="{'active':index === current}"></i> </a> </div> </div> </template>`
原版是
`<template> <div class="vux-slider"> <div class="vux-swiper" :style="{height: xheight}"> <slot></slot> <div class="vux-swiper-item" v-for="item in list" @click="clickListItem(item)"> <a :href="item.url"> <div class="vux-img" :style="{backgroundImage: buildBackgroundUrl(item.img)}"></div> <p class="vux-swiper-desc">{{item.title}}</p> </a> </div> </div> <div :class="['vux-indicator', 'vux-indicator-' + dotsPosition]" v-show="showDots && list.length > 1"> <a href="javascript:" v-for="(index, item) in list"> <i class="vux-icon-dot" :class="{'active':index === current}"></i> </a> </div> </div> </template>`
所以使用后生成的代码
`<div class="slider" _v-7ddb9602=""> <div class="swiper" style="height: auto;"> <div class="item"> <a href="javascript:void(0)"> <div class="img" style="background-image: url(&quot;static/a48833af9331bfa3c782ba48a4cadfc9.jpg&quot;);"></div> <p class="desc">电产品类</p> </a> </div><div class="item"> <a href="javascript:void(0)"> <div class="img" style="background-image: url(&quot;static/5a88d2a8fa9de03ab24915d93a2a919b.jpg&quot;);"></div> <p class="desc">水产品类</p> </a> </div> </div> <div class="indicator"> <a href="javascript:"> <i class="icon_dot"></i> </a><a href="javascript:"> <i class="icon_dot active"></i> </a> </div> </div>`

显示是空白的

**Comment by airyland** [comment]
重新安装试试。
