### ISSUE TITLE
x-switch和calendar的建议

### ISSUE THREAD

**Issue by tong233** [airyland/vux#2104]
x-switch能传key,value形式就好了，后台让传'0','1'，拿回来也要转换不太方便。
calendar和cell类型组件放在一个group没有上下边框，不太美观。

**Comment by airyland** [comment]
x-switch 有考虑这个功能，还没有时间做。
calendar 和 cell 放在 group 中没有边框不知道什么情况，截图一下？

**Comment by tong233** [comment]
![image](https://user-images.githubusercontent.com/21073132/31871239-6aaafff0-b7e5-11e7-8f48-e115194b8c1d.png)

**Comment by tong233** [comment]
@airyland ↑
