### ISSUE TITLE
求 calendar 组件添加个禁用周末的功能

### ISSUE THREAD

**Issue by Muyv** [airyland/vux#2105]
禁用某些日期是十分有必要的，希望可以增强一下目前的日历组件，添加禁用周末和禁用指定日期的功能

**Comment by Muyv** [comment]
66666666，inline-calendar 有了，不过 calendar 似乎还没有

**Comment by airyland** [comment]
@Muyv 漏了，props 是同享的，但是忘了 template 绑定了。下个小版本更新。

**Comment by Muyv** [comment]
@airyland 好滴，还发现个小问题， disabled 后的周末虽然是灰的，但依旧可以选中，这个也请顺带看一下吧
