### ISSUE TITLE
npm "less": "^3.0.0-alpha.3 会导致 vux 引入less出错，因为没有加.less的后缀

### ISSUE THREAD

**Issue by lion-git** [airyland/vux#2110]

**Comment by lion-git** [comment]
目前只能按照 less2.X 版本

**Comment by airyland** [comment]
~~get。下个版本解决。~~

**Comment by airyland** [comment]
看起来这是 bug 并不是 feature，因此 less 相关代码暂不会变化，等待 less 更新。
暂时请使用 less@2.x 版本。

https://github.com/less/less.js/issues/3113
