### ISSUE TITLE
loading, loadMore,alert 组件样式有时候正常，有时候错乱

### ISSUE THREAD

**Issue by chechengpeng** [airyland/vux#2116]
1. ![正常情况](https://ooo.0o0.ooo/2017/10/24/59ee8a132fc4c.png)
2. ![不正常](https://ooo.0o0.ooo/2017/10/24/59ee8a7cccd5e.png)
- 如图所示，有时候样式能正常，有时候不正常，没有修改过原生样式，也没有重名的 class 类
- 不知为啥图片出不来，贴图片地址吧
1. https://ooo.0o0.ooo/2017/10/24/59ee8a132fc4c.png
2. https://ooo.0o0.ooo/2017/10/24/59ee8a7cccd5e.png

**Comment by airyland** [comment]
Sorry，无法重现的，无法解决。至少你得给个可重现 repo 吧。
