### ISSUE TITLE
FormBuilder 模版

### ISSUE THREAD

**Issue by kitkimwong** [airyland/vux#2117]
請問能否基於以下的form generator做一個模版？
https://github.com/icebob/vue-form-generator

場景：
很多時候應用需要接受用戶提交多張表單，這時如果能有一個JSON to form 并帶VUX的樣式就太好了。

**Comment by airyland** [comment]
暂时没有计划，有时间再考虑，目前可以根据要的组件做一个配置来实现列表渲染就好了。
