### ISSUE TITLE
prevent-scroll-body.js文件中的css引入错误

### ISSUE THREAD

**Issue by travelalife** [airyland/vux#2118]
npm错误信息： 
ERROR  Failed to compile with 1 errors                                                                         11:19:57

This relative module was not found:

* ./prevent-body-scroll.css in ./~/_vux@2.6.5@vux/src/mixins/prevent-body-scroll.js

**Comment by airyland** [comment]
目测这个版本下这个文件是存在的。请上 repo 重现。

**Comment by travelalife** [comment]
![default](https://user-images.githubusercontent.com/12226635/31983177-c70c0668-b98e-11e7-92fc-03ea34b93fc8.png)
我检查了一下确实是有这个文件的，而且代码也没错，但是就是说找不到
