### ISSUE TITLE
更新了一下组件，构建的时候直接报错，版本2.6.5

### ISSUE THREAD

**Issue by sunshinebutterfly** [airyland/vux#2119]
ERROR  Failed to compile with 1 errors                                                                                                                                                             11:33:47

 error  in ./~/vux/src/components/flexbox/flexbox.vue

Module build failed: variable @button-tab-active-font-color is undefined
 @ /Users/sum/Product/spa_kd/node_modules/vux/src/components/flexbox/flexbox.vue (line 80, column 3273)
 near lines:

**Comment by airyland** [comment]
flexbox.vue 源码并不会出现 @button-tab-active-font-color ，请确定问题具体位置。或者上 repo 重现。

**Comment by sunshinebutterfly** [comment]
顺便更新了一下 vux-loader 就好了。 谢谢
