### ISSUE TITLE
cell的优化问题

### ISSUE THREAD

**Issue by liufeics** [airyland/vux#2124]
cell控件由于引入title直接用{{}}所以无法加入样式，希望所有的title都能保持统一 能直接加入样式

**Comment by airyland** [comment]
使用 `slot=title` 来解决样式问题。

**Comment by liufeics** [comment]
那你PopupRadio等引用了cell的控件呢？除了修改源码 没找到能修改的地方

**Comment by airyland** [comment]
那你就 pr 吧

**Comment by yqf** [comment]
2.73这个版本，在编译使用时页面上报 VM15149:34 [Vue warn]: Unknown custom element: <v-no-ssr> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
