### ISSUE TITLE
请教vux2.x编译时出现的问题 

### ISSUE THREAD

**Issue by glows** [airyland/vux#2126]
错误代码：
(node:416) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
 ERROR  Failed to compile with 1 errors16:48:08

 error  in ./node_modules/_vux@2.7.0@vux/src/components/popup-radio/index.vue

Syntax Error: Unexpected token (59:4)

  57 |     placeholder: String,
  58 |     readonly: Boolean,
> 59 |     ..._cellProps,
     |     ^
  60 |     ...radioProps()
  61 |   },
  62 |   computed: {

 @ ./node_modules/_vux@2.7.0@vux/src/components/popup-radio/index.vue 7:2-177
 @ ./node_modules/_babel-loader@6.4.1@babel-loader/lib!./node_modules/_vux-loader@1.1.18@vux-loader/src/script-loader.js!./node_modules/_vue-loader@10.3.0@vue-loader/lib/selector.js?type=script&index=0!./src/components/pay/pay.vue
 @ ./src/components/pay/pay.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by airyland** [comment]
babel 配置问题，确认项目目录下有  .babelrc 
参考相关 issue #1982

**Comment by glows** [comment]
问题已解决，多谢
