### ISSUE TITLE
使用 vue-cli 工具和 airyland/vux2 模板快速初始化项目卡死

### ISSUE THREAD

**Issue by ruoru** [airyland/vux#2129]
按照文档的快速构建

输入`Project vue init airyland/vux2 projectPath` 命令后，出现了输入 name 和 description，问题在这个，description无法输入，并且直接按下回车整个控制台都会卡，只有强制关闭。
```shell
➜  Project vue init airyland/vux2 projectPath

? Project name vuxdemo
? Project description (A Vue.js project)
```

**Comment by airyland** [comment]
非 vux 的问题，可以试试 vue init webpack projectPath 是不是也不正常。如果也不正常，说明是工具的问题。或者确认下 Github 能否正常访问。

**Comment by ruoru** [comment]
重新安装node好了。

**Comment by xiaonan132142** [comment]
node 版本是多少
