### ISSUE TITLE
模块化

### ISSUE THREAD

**Issue by fundon** [airyland/vux#213]
目前所有的 vux 组建都集成到 vux 中，我想，我们是否可以把这些组件模块分开注册 npm package,
使用者按需安装？

**Comment by airyland** [comment]
其实现在从 components/里引入也是按需安装。
不过，真有计划分别发布，不过需要写一个批量发布工具，由于实在没有时间所以没有做。

**Comment by fundon** [comment]
嗯 分开确实维护成本会变高，但好处也是显而易见的

**Comment by airyland** [comment]
@fundon 其实我设想的不是分开维护，源代码依然在vux里，而单独分发的npm包只是dist文件，不会有源代码。

**Comment by fundon** [comment]
嗯，可行

**Comment by fundon** [comment]
@airyland 不急的话，我一有空就填坑 哈哈

**Comment by donlzx** [comment]
Needs to address dependencies more nicely.  A possible scheme:

1) vux-base: including/corresponding to most of WeUI components, minimal dependencies.
2) vux-extended: Vux original components in VueJS style, without any large external dependencies.
3) vux-{individual-large-compoents}: Application level components with large external dependencies, such as calendar, scroll, swipe, etc.

**Comment by airyland** [comment]
@donlzx I don't think the category is necessary. I choose a component because I need it not because how big the size is.
And Actually I don't think Calendar is a large component.
