### ISSUE TITLE
ios微信浏览器中使用右划返回上一页会产生两次返回上一页的行为影响了页面切换动画

### ISSUE THREAD

**Issue by zjtt** [airyland/vux#2140]
ios微信浏览器中使用右划返回上一页会产生两次返回上一页的行为影响了页面切换动画，这个可以优化吗？是不是因为页面序号存到sessionStorage中的原因？

**Comment by wg5945** [comment]
因为无法判断用户是点击后退按钮后退还是使用手势后退，暂时没有什么好的解决方案

**Comment by zjtt** [comment]
禁止页面滑动返回怎么样?

**Comment by wg5945** [comment]
不可能禁用原生事件，实在无法接受的话，只能禁用main.js里面的转场动画

**Comment by zjtt** [comment]
好的，谢谢
