### ISSUE TITLE
【版本2.6.4】Selector的 placeholder 没有效果

### ISSUE THREAD

**Issue by johnscliang** [airyland/vux#2141]
selector已经放在group下
1.已经设置v-model，值是一个未定义的变量，会出现placeholder，但是vue报错，变量没定义。
2.把v-model设置正确，这时候placeholder就不见了。

很奇怪，麻烦有空改一下？

**Comment by airyland** [comment]
code, please.

**Comment by LanceCong** [comment]
<template>
  <div class="main">

    <group title="">

      <div>
        <selector placeholder="省份" v-model="addressForm.province" title="省份" :options="list" @on-change="onChange"></selector>
        <selector placeholder="城市" v-model="addressForm.city" title="城市" :options="list" @on-change="onChange"></selector>
        <selector placeholder="区域" v-model="addressForm.county" title="区" :options="list" @on-change="onChange"></selector>
      </div>

    </group>
  </div>

</template>

<script>

  import { XInput, Group, Selector, XButton,Cell,ChinaAddressV3Data,Value2nameFilter as value2name  } from 'vux'
  import API from '../api/API'
  import util from '../utils/util'
  let mThat = null
  let mCallback = null

  let mCounting = false

  export default{
    data () {
      return {
        addressForm: {
          province: null,
          city: null,
          county: null
        },
        list: [{key: 'gd', value: '广东'}, {key: 'gx', value: '广西'}]


      }
    },
    components: {
      XInput, Group, XButton,Cell,Selector
    },
    methods: {
      onChange(val){
        console.log('val',val)
      }
    }
  }

</script>

**Comment by johnscliang** [comment]
```
<template>
  <div class="main">

    <group title="">

      <div>
        <selector placeholder="省份" v-model="addressForm.province" title="省份" :options="list" @on-change="onChange"></selector>
        <selector placeholder="城市" v-value="aaaa" v-model="addressForm.city" title="城市" :options="list" @on-change="onChange"></selector>
        <selector placeholder="区域" v-model="addressForm.aaa" title="区" :options="list" @on-change="onChange"></selector>
      </div>

    </group>
  </div>

</template>

<script>

  import { XInput, Group, Selector, XButton,Cell,ChinaAddressV3Data,Value2nameFilter as value2name  } from 'vux'
  import API from '../api/API'
  import util from '../utils/util'
  let mThat = null
  let mCallback = null

  let mCounting = false

  export default{
    data () {
      return {
        addressForm: {
          province: null,
          city: null,
          county: null
        },
        list: [{key: 'gd', value: '广东'}, {key: 'gx', value: '广西'}]


      }
    },
    components: {
      XInput, Group, XButton,Cell,Selector
    },
    methods: {
      onChange(val){
        console.log('val',val)
      }
    }
  }

</script>


```

**Comment by LanceCong** [comment]
```
import { XInput, Group, Selector, XButton,Cell,ChinaAddressV3Data,Value2nameFilter as value2name  } from 'vux'
  import API from '../api/API'
  import util from '../utils/util'
  let mThat = null
  let mCallback = null

  let mCounting = false

  export default{
    data () {
      return {
        addressForm: {
          province: null,
          city: null,
          county: null
        },
        list: [{key: 'gd', value: '广东'}, {key: 'gx', value: '广西'}]


      }
    },
    components: {
      XInput, Group, XButton,Cell,Selector
    },
    methods: {
      onChange(val){
        console.log('val',val)
      }
    }
  }
```

**Comment by wg5945** [comment]
貌似并不能重现，官方的demo中有个demo01设的就是null，也没有出现报错

**Comment by johnscliang** [comment]
@wg5945 可能是你的vue的设置，你用开发版本试试。

**Comment by airyland** [comment]
vue 报错具体？
关于 null 值的处理可以更新 vux 到 2.7.0 试试。 #2101

**Comment by johnscliang** [comment]
@wg5945 demo01可以设置是null，但是不能不存在demo01，我改了上面代码，你再试试

**Comment by johnscliang** [comment]
@airyland 代码效果报错如图。是我没表达清楚，不是null报错，是undefined错误
[图片](http://wx1.sinaimg.cn/large/8f8f5f45gy1fl0c0ckttlj218b0gf0ue.jpg)

**Comment by johnscliang** [comment]
更新版本2.7.0之后可以了，谢谢

**Comment by airyland** [comment]
v-value="aaaa" 这个是有问题的，一是默认并没有  v-value 这个 directive，二是 aaaa 在 data 里是必须定义的。

**Comment by johnscliang** [comment]
确实第二个例子是我写的有问题，可以看第一个和第三个selector，都没写错，但是一个有效果一个没有。
升级版本之后可以了，谢谢，作者回复神速，赞一个
