### ISSUE TITLE
页面刷新后，direction效果错乱

### ISSUE THREAD

**Issue by Photokeep** [airyland/vux#2142]
- 在demo里，先从首页一步步进入到这个页面层级深一点的页面 如：

 home->scroller->pullup

- 然后浏览器刷新

-  开始后退 pullup->scroller->home

- 回到首页后

- home->scroller->pullup

 整个过程direction效果错乱太明显

**Comment by Photokeep** [comment]
@airyland 我在实际项目里也遇到了 然后测试demo也是一样 希望老师能给个解决方法 虽然是单页面应用，但是平时也习惯性的会刷新页面 恳请老师指点一二

**Comment by airyland** [comment]
scroller 已经废弃不维护了，就是因为解决不了 n 多的实际使用问题。麻烦使用第三方的 scroll 组件。

**Comment by Photokeep** [comment]
老大不是指scroller组件 上面的只是样例（为了方便测试页面层级） 其他页面只要刷新后 direction也是错的

**Comment by Photokeep** [comment]
- home->actionsheet

- 刷新actionsheet

- actionsheet->home

- home->actionsheet

@airyland

**Comment by airyland** [comment]
噢， 没看清楚，你说的是路由的切换顺序吧。

**Comment by airyland** [comment]
没看清楚你上面附的，刷新 actionsheet 后退回到 Home,  前进到 actionsheet 貌似没什么问题？

**Comment by Photokeep** [comment]
direction的farward与reverse效果不对 你仔细感受下

**Comment by Photokeep** [comment]
@airyland

**Comment by airyland** [comment]
主要问题是刷新后原来本地保存的路径顺序就会被清除。相当于从当前页面向其他页面 forward 了。可以加上具体业务逻辑，强制从二级到一级为 reverse，从一级到二级为 forward。

**Comment by Photokeep** [comment]
额 谢谢 那意思就是在定义路由时候 就要定义好路由的级别了 ？ 希望能用最小的代码把它解决了  但是我又不是很精 😅😇🤣

**Comment by Photokeep** [comment]
对了  如果路由级别很深呢？
