### ISSUE TITLE
vux安装2.6.0以上版本，部分插件引用在启动时会报错，如XDialog插件

### ISSUE THREAD

**Issue by CaiJW13** [airyland/vux#2144]
vux安装2.6.0以上版本，部分插件引用在启动时会报错，如XDialog插件 

D:\svnNew\Web_developer\Project\web\BlueButterfly>npm run dev

> y@1.0.0 dev D:\svnNew\Web_developer\Project\web\BlueButterfly
> node build/dev-server.js

> Starting dev server...
 ERROR  Failed to compile with 1 errors                                 10:54:50
 error  in ./~/_vux@2.6.4@vux/src/mixins/prevent-body-scroll.css

Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../_css-loader@0.28.7@css-loader/index.js?{
\"minimize\":false,\"sourceMap\":false}!./prevent-body-scroll.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../../_vue-style-loader@3.0.1@vue-style-loader/l
ib/addStylesClient.js")("b9b010f2", content, false);

 @ ./~/_vux@2.6.4@vux/src/mixins/prevent-body-scroll.css 4:14-217 18:2-22:4 19:2
0-223
 @ ./~/_vux@2.6.4@vux/src/mixins/prevent-body-scroll.js
 @ ./~/_babel-loader@7.1.2@babel-loader/lib!./~/_vux-loader@1.1.15@vux-loader/sr
c/script-loader.js!./~/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script
&index=0!./~/_vux@2.6.4@vux/src/components/x-dialog/index.vue
 @ ./~/_vux@2.6.4@vux/src/components/x-dialog/index.vue
 @ ./~/_babel-loader@7.1.2@babel-loader/lib!./~/_vux-loader@1.1.15@vux-loader/sr
c/script-loader.js!./~/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script
&index=0!./src/components/DynamicPage.vue
 @ ./src/components/DynamicPage.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
![928697439-59f14eeb18cd6_articlex](https://user-images.githubusercontent.com/33218303/32162302-76b4a55e-bd93-11e7-902b-2152d0341f2a.png)

**Comment by airyland** [comment]
sorry，没有重现 repo 的猜不出原因也无法处理。
