### ISSUE TITLE
ChinaAddressV4Data版本地址显示，县不全，我用到的是河北省保定市，北市区没有，其他的不清楚，希望能得到作者的尽快处理，谢谢

### ISSUE THREAD

**Issue by meggieUP** [airyland/vux#2145]

**Comment by airyland** [comment]
国家统计局数据并不存在 北市区 

http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201703/t20170310_1471429.html

**Comment by airyland** [comment]
查了下，北市区，南市区在 15年 就已经撤消了。
http://hebei.ifeng.com/detail_2015_05/15/3898165_0.shtml
