### ISSUE TITLE
datetime组件为什么没有min-minute和max-minute属性呢？

### ISSUE THREAD

**Issue by Plortinus** [airyland/vux#2148]
datetime组件精确到分钟了，为什么没有控制分钟的`min-minute`属性和`max-minute`属性呢？

**Comment by airyland** [comment]
直接用 `minute-list` 比给出两个属性更灵活。

**Comment by colin1015** [comment]
min-hour 不能根据设置值的变化而变化

**Comment by weineel** [comment]
@airyland  `minute-list`不能根据设置值的变化而变化。
