### ISSUE TITLE
datetime组件设置minMonth、minDay、maxMonth等完全无效

### ISSUE THREAD

**Issue by VinceXie** [airyland/vux#215]
### Version
0.0.117
### Android or iOS, which browser?
all

希望组件能直接设置最小日期或最大日期，后改用另外的方法间接实现但发现minMonth、minDay、maxMonth等即使设置了也无效。

**Comment by airyland** [comment]
本来就没有minMonth minDay maxMonth。。这个问题的复杂性在于日月年是联动的，不可能提供最小最大月的选项。

**Comment by airyland** [comment]
而minDate startDate 的修改成本很高，一直没有时间做，建议在用户选择后进行有效性提示。

**Comment by airyland** [comment]
Moved to #48

**Comment by Lonefy** [comment]
@airyland 用户选择后进行有效性提示的话，如何通过代码还原datetime的时间呢？是否可以在change事件里修改datetime的值？
