### ISSUE TITLE
demo出现比较小恐怖的layer问题

### ISSUE THREAD

**Issue by deepkolos** [airyland/vux#2155]
![tim 20171101233903](https://user-images.githubusercontent.com/12824616/32282932-f1b11212-bf5d-11e7-8240-2ca4be3d8a34.png)

**Comment by airyland** [comment]
具体？

**Comment by deepkolos** [comment]
是0.5px的实现方案导致的


![2017-11-02_083143](https://user-images.githubusercontent.com/12824616/32304239-ca231182-bfa8-11e7-9692-049633bd5406.png)

![2017-11-02_083311](https://user-images.githubusercontent.com/12824616/32304249-da2dd922-bfa8-11e7-99a2-746ae0cdc80a.png)

**Comment by airyland** [comment]
感谢，我研究一下。

**Comment by SteveWinsAll** [comment]
demo
