### ISSUE TITLE
datetime无法仅限制end

### ISSUE THREAD

**Issue by alvawu** [airyland/vux#2157]
当只提供end-date，不提供start-date时，组件无法限制到end-date所指定的时间
场景是想让用户只可以选择过去的时间，
谢谢！

**Comment by airyland** [comment]
格式化代码。代码显示空白，我没有义务帮你格式化。
格式化代码。代码显示空白，我没有义务帮你格式化。
格式化代码。代码显示空白，我没有义务帮你格式化。
格式化代码。代码显示空白，我没有义务帮你格式化。
格式化代码。代码显示空白，我没有义务帮你格式化。
格式化代码。代码显示空白，我没有义务帮你格式化。
格式化代码。代码显示空白，我没有义务帮你格式化。
格式化代码。代码显示空白，我没有义务帮你格式化。

**Comment by alvawu** [comment]
先别急着closed啊- -
我这不是在补了
> <datetime v-model="comeTime" placeholder="请选择到场时间" format="YYYY-MM-DD HH:mm" :end-date="now" required></datetime>

**Comment by alvawu** [comment]
&lt;datetime v-model="comeTime" placeholder="请选择到场时间" format="YYYY-MM-DD HH:mm" :end-date="now" required&gt;</datetime&gt;

你别辣么急着closed啦，都是为了完善才提的，我是看了你的代码才确认来提issue的。

**Comment by airyland** [comment]
``` html
<datetime v-model="comeTime" placeholder="请选择到场时间" format="YYYY-MM-DD HH:mm" :end-date="now" required></datetime>
```

正确的格式化是这样。只是个 markdown 标记而已。

**Comment by alvawu** [comment]
骚瑞，markdown因为用得还不熟，我适应下，谢谢哈！麻烦帮忙确认下是否是个issue~ :)

**Comment by airyland** [comment]
Duplicate of #2158
