### ISSUE TITLE
请问 calendar组件多选后可以初始化吗？

### ISSUE THREAD

**Issue by CaiJW13** [airyland/vux#2160]
现在calendar组件多选后，没有命令初始化，直接让v-model绑定的值为空也不会重新渲染，这种情况当需要公用calendar组件的时候就会很麻烦。

**Comment by airyland** [comment]
不明白你要怎样初始化，返回当前月视图？

**Comment by CaiJW13** [comment]
![a45378e80111c44980d92ba543149cf8](https://user-images.githubusercontent.com/33218303/32362731-834e8404-c0a6-11e7-96e7-75afe6a38cae.png)

我使用的是多选功能
图一，为初次调用时的界面


![00b](https://user-images.githubusercontent.com/33218303/32362953-bfc67a76-c0a7-11e7-8289-abedc15e91d4.png)

图二，为选取日期后界面。

当再次调用时,界面还是保持图二的状态，系统有提供方法可以回到图一的状态吗？

**Comment by airyland** [comment]
将 v-model 绑定值重置没效果么？

**Comment by CaiJW13** [comment]
试过，不行。具体情况是：再次调用时，在methods中将 v-model 绑定值赋值为空数组[]，生成的界面没有清空数据，如图一


![63692b7da546ef41a9a17c94f2cba577](https://user-images.githubusercontent.com/33218303/32366177-f7c55dc4-c0b7-11e7-8853-a5707c61f695.png)



然后，点击图一区域触发弹起日历表，界面为图二：


![8f3d35e8fc6fe6448bbe60aa5df67af1](https://user-images.githubusercontent.com/33218303/32366199-10bd00ca-c0b8-11e7-99c9-75b2ec0036f1.png)


但是在这种情况下会出现bug：弹出的日历表（图二）点击取消按钮，图一的值会重新渲染到日历表上，只有点击确定按钮才可以真正实现清空界面。是否是取消按钮触发的事件另外存储了一组数据，导致不能通过清空v-model的值来实现初始化。
