### ISSUE TITLE
PopupPicker适配dpr不生效的问题

### ISSUE THREAD

**Issue by webLiu** [airyland/vux#2161]
import { ConfigPlugin } from 'vux'
Vue.use(ConfigPlugin, {
  $picker: {
    respectHtmlDataDpr: true
  }
});
适配dpr配置了这个datetimepicker转换成了rem，但是PopupPicker不生效，请问还需要配置什么吗？

**Comment by airyland** [comment]
1.这个并不会帮你转成 rem
2.作用只是配置移动距离要不要使用 data-dpr 作为倍数而已。
3.不生效这样的描述根本难以理解，请建个 repo 吧。
