### ISSUE TITLE
x-switch @on-click 無法傳自訂義參數

### ISSUE THREAD

**Issue by kitkimwong** [airyland/vux#2162]
``` html
<x-switch
v-for="( result, index ) in myPym " :key="result.itemname"
:value-map="['0', '1']"
v-model="result.verify_free"
prevent-default
@on-click="onClickVer(result)"
></x-switch>
```

如果寫成 @on-click="onClickVer" 在函數中可以取得newVal和oldVal
但如果要傳送自訂參數，寫成 @on-click="onClickVer(result)" 或@on-click="onClickVer( newVal , oldVal ,result)"則參數只能取得result，不能取得newVal和oldVal

**Comment by airyland** [comment]
``` js
@on-click="onClickVer(result, $event)"
```
这样可以取得 result 及 $event(相当于 newVal)，oldVal 直接取反就可以了。

**Comment by kitkimwong** [comment]
謝謝解說，但 @airyland 
那問題就來了，若$event返回的不是click event而是一個bool，那我怎麼對event進行操作（例如阻止冒泡）？
比如說： 我現在要在x-switch中要區分開二個行為： 
![image](https://user-images.githubusercontent.com/11818108/32405927-8e1e4ae0-c13c-11e7-9b1e-0873444d970b.png)
一個是右邊按toggle按鈕的行為，一個是左邊按item本身的on-click事件。 所以同時注冊了
`@on-click="onClickToggle(result, $event)"` 和
`v-on:click.native="onClickItem(result, $event)"`

然後在 onClickToggle 中進行 $event.stopPropagation() 這樣我就能區分開點擊左邊區域和右邊區域的行為(利用冒泡事件阻止響應onClickItem方法)：
```
onClickToggle(result , $event){
  doLogic(result);
  .....
  $event.stopPropagation();
}
```
但是現在不能，因為$event 只是一個boolean value，所以我點擊右邊的switch會同時響應 `onClickToggle` 和 `onClickItem` 方法。

**請問怎麼取得原生的on-click event 而不是newVal？**

**Comment by airyland** [comment]
你可以通过 onClickItem 的 $event 来判断当前点击 target 是哪个。

**Comment by kitkimwong** [comment]
我現在就是這樣處理的。但感覺有點暴力。。。並不優雅
