### ISSUE TITLE
Search组件在失去焦点的情况下不会回到默认状态

### ISSUE THREAD

**Issue by ty850454** [airyland/vux#2165]
步骤1，点击Search组件，进入文本输入状态
步骤2，清空内容
步骤3，点空白区域

Search组件依然在最上方，demo中就是如此

**Comment by airyland** [comment]
点空白区域并不会改变定位，这是设计如此。点取消才会恢复状态。

**Comment by MrChen2016-08-27** [comment]
在自定义slot搜索结果的情况下，点击搜索结果列表无法回到默认状态，这种情况应该怎么解决呢

**Comment by GreenyZD** [comment]
同问

**Comment by GreenyZD** [comment]
同问

**Comment by hzc315579049** [comment]
> 步骤1，点击Search组件，进入文本输入状态
> 步骤2，清空内容
> 步骤3，点空白区域
> 
> Search组件依然在最上方，demo中就是如此

官方没提供此逻辑，但是你可以看下源码，其实你可以用 this.$refs.search.handleResultClick(item)来hack这个需求
