### ISSUE TITLE
 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。

### ISSUE THREAD

**Issue by wjryours** [airyland/vux#2168]
刚刚新建了一个项目，是用`vue-cli`初始化项目的，然后我要引入`vux`,发现`vue-cli`中的`webpack.base.conf`的配置和官网配置的`webpack.base.conf`的不同，里面并不存在`webpackConfig`，于是我在`webpack.prod.conf`中配置了下，
`//引入vux
const vuxLoader = require('vux-loader')
const originalConfig = webpackConfig
module.exports = vuxLoader.merge(originalConfig, { plugins: ['vux-ui'] })
// module.exports = webpackConfig
`
然后这样也算是引入成功了,我也可以调用vux提供的一些组件，但是就会出现如标题所示的警告，
`"vux-loader": "^1.1.20"`我的vux-loader也是最新的，请问是配置的问题，对于最新的vue-cli初始化的项目应该怎么配置呢

**Comment by airyland** [comment]
既然是首次使用，就用 vue-cli 和模板 airyland/vux2 来初始化吧。如果不行，单凭这样的描述解决不了问题，上 repo 吧。

**Comment by wjryours** [comment]
刚刚遇到个问题，这个引入vux中的loading组件会报错
`[Vue warn]: Property or method "$t" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Loading> at node_modules\vux\src\components\loading\index.vue
       <Knowledge> at src\components\knowledge.vue
         <App> at src\App.vue
           <Root>`
vux-loader我是最新的

**Comment by airyland** [comment]
上面已经说了，要么你用 airyland/vux2 来初始化要么你建个 repo 来重现。请遵照建议做再重开 issue，谢谢。
