### ISSUE TITLE
vux 中的previewer组件 可以不设宽高吗

### ISSUE THREAD

**Issue by Zoeyzhou** [airyland/vux#2169]
vux使用的是2.5.2版本，但是imglist仍需设置宽高 否则报错
photoswipe.js?558d:510 Uncaught TypeError: Cannot read property 'x' of undefined
但是文档里有说到2.4.0版本后是不需要设的

**Comment by airyland** [comment]
请给出重现代码。

**Comment by Zoeyzhou** [comment]
感谢回复！我重新install了一遍了后 已经没有报错，试图在同事仍是2.5.2版本的电脑上再复现，仍然没有问题，目前问题已经解决，只是不明白在重新install之前的为何一直需要设宽高😂

**Comment by FLanvendar** [comment]
我的好像第一次加载的时候报错 后面那就不报错了
