### ISSUE TITLE
希望作者能够添加vux-loader对x-icon的换行支持

### ISSUE THREAD

**Issue by wolfstark** [airyland/vux#2172]
![image](https://user-images.githubusercontent.com/15010463/32487298-41533054-c3e4-11e7-9dce-45c838c370f8.png)
目前出现多个x-icon 属性时换行会出错，这对于开发来讲是十分不友好的，我经常不小心格式化了有大量x-con的组件出现问题，简直就是灾难
![image](https://user-images.githubusercontent.com/15010463/32487412-95003d78-c3e4-11e7-856b-24206785484a.png)
目前vue官方的风格指南也指出用多行分隔对象的多个属性是很常见的最佳实践，希望作者尽快支持：）

**Comment by airyland** [comment]
vux-loader@^1.1.21 已经支持

**Comment by li-yechao** [comment]
vux-loader 1.2.1

```
<x-icon type="ios-arrow-left" /> 报错
[Vue warn]: Unknown custom element: <x-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```
只能像下面使用
```
 <x-icon type="ios-arrow-left"></x-icon>
```

**Comment by airyland** [comment]
@unordered  收到，即将支持。

**Comment by airyland** [comment]
已经支持。

**Comment by Jiiiiiin** [comment]
请问老大，为什么当时没有考虑使用，https://github.com/ant-design/babel-plugin-import
而是手撸呢?

**Comment by airyland** [comment]
@Jiiiiiin 它只能解决一个自动分包载入的问题，不能解决最主要的使用 .vue 源码分发的问题，不能解决主题变量的问题，不能解决运行时编译修改 vue 源码功能。vux 可能是唯一一个使用源码引入的 vue 库。事实上 vux-loader 也有使用统计功能，过阵子可以分享一下近一年来 vux 的使用情况，城市分布，操作系统分布，实时在线调试人数等。使用 vux-loader 有很多可以实现扩展的，计划中的还有很多功能没有时间实现，而 babel-pluign-import 过于局限了。

**Comment by Jiiiiiin** [comment]
@airyland 这段评论建议更新到doc中，再次说明我们选着跟着vux是一个明智之举，现在我已经总结经验，vue-loader的升级不能盲目，起码要看到vux-loader也更新了:smile:
也再次说明我等小白的肤浅，真去有机会让公司赞助一下你们，十分感谢:ghost:
还有老大是男是女呀?

**Comment by airyland** [comment]
@Jiiiiiin 最近在重构文档站了，会补充完善一些说明。

**Comment by li-yechao** [comment]
@airyland 我说更新了还不支持你们信吗？😂

**Comment by airyland** [comment]
@unordered  确认下 vux-loader 版本。

**Comment by li-yechao** [comment]
node_modules/vux-loader/package.json
```
"version": "1.2.2"
```

index.vue
```
      <x-icon type="ios-arrow-right"></x-icon> // 正常

      <x-icon type="ios-arrow-right" /> // 报错，错误如下
```
```
[Vue warn]: Unknown custom element: <x-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in
<Index> at src/views/home/index.vue
       <Index> at src/components/main/index.vue
         <App> at src/app.vue
           <Root>
```

**Comment by airyland** [comment]
unordered 我的错，有个逻辑漏了，更新到 1.2.3 试试。

**Comment by li-yechao** [comment]
thanks a lot! 🙏
