### ISSUE TITLE
popup-picker、cell如何做必填验证

### ISSUE THREAD

**Issue by dzlishen** [airyland/vux#2175]
如何对popup-picker做必选验证，以及对cell的value做必填的验证呢？
<popup-picker title="项目名称:" 
                :data="projects" 
                v-model="project"  
                @on-change="onChange" 
                placeholder="请选择"
                :show-name="showName"></popup-picker>
<cell title="支出类型:" is-link :value="payType" @click.native="showPayType = true"></cell>

**Comment by airyland** [comment]
组件内暂时不支持不显示提示 icon，只能在提交时检查值并弹出提示。

**Comment by dzlishen** [comment]
@airyland  您好，我在使用popup-picker做了一个表单页面，提交后再查看表单内容的时候，这个popup-picker组件中的name如何回显出来呢？
