### ISSUE TITLE
关于i18n的配置

### ISSUE THREAD

**Issue by ChenArno** [airyland/vux#2177]
大神，你好：
  我这边进行了i18n 的配置，
在webpack.base.conf.js进行了如下配置，
`module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [{
    name: 'vux-ui'
  }, {
    name: 'i18n',
    vuxStaticReplace: false,
    staticReplace: false,
    extractToFiles: 'src/locales/components.yml',
    localeList: ['zh-CN', 'en']
  }, {
    name: 'less-theme',
    path: 'src/assets/theme/theme.less'
  }]
});`

在一个vue界面当中进行了如下配置
`<i18n>
setting:
  zh-CN:设置
Server Settings:
  zh-CN:服务器设置
</i18n>`
我发现生成出来的components.yml
的结果是中英文一样的
`zh-CN:
  setting: setting
  Server Settings: Server Settings
en:
  setting: setting
  Server Settings: Server Settings
`
请问一下是少配置了哪一步吗

**Comment by airyland** [comment]
参考  app.js 配置 vuex-i18n

**Comment by ChenArno** [comment]
app.js是在哪里，能不能指明一下，谢谢哈

**Comment by airyland** [comment]
写错，main.js https://github.com/airyland/vux/blob/v2/src/main.js

**Comment by ChenArno** [comment]
这个我参考了，我能跑通没问题的，就是在生成components.yml这个文件的时候，他生成的中英文都是一样的

**Comment by airyland** [comment]
比较奇怪，可能你要建个 repo 来看看。

**Comment by ChenArno** [comment]
恩，我搭一个demo看看

**Comment by heke2929** [comment]
@ChenArno 我也遇到这个问题, 后来发现是`zh-CN`写成了`zh-cn`😭
