### ISSUE TITLE
calendar设置readonly无效

### ISSUE THREAD

**Issue by tong233** [airyland/vux#2178]
版本2.70，calendar设置readonly还能弹出popup
inline-calendar禁用周末还能选中,demo里也是这样

**Comment by airyland** [comment]
并无 readonly 属性，无论是 inline-calendar 还是 calendar。

**Comment by tong233** [comment]
@airyland 考虑添加readonly吗？或者我有什么办法禁止弹出，还有我第二个问题被你忽略了呀，inline-calendar禁用周末还能选择是本身设计成这样吗

**Comment by airyland** [comment]
禁用周末的问题我再看下。
