### ISSUE TITLE
Uncaught ReferenceError: ClassList is not defined

### ISSUE THREAD

**Issue by travellerwjoe** [airyland/vux#2181]
在按照文档配置`vux-loader`后，webpack及node服务器能够正常启动，但当在vue组件中引入后
`import {xxx} from 'vux' `及抛出异常`Uncaught ReferenceError: ClassList is not defined`，请麻烦答复一下可能造成的原因或是解决方案，谢谢。
![Uploading image.png…](http://img.microbu.com/2017/0917/93599586591172_1200x1200.png)

**Comment by airyland** [comment]
建议直接用 airyland/vux2 来初始化项目。自行配置出现的问题只能建个 repo 来重现。

**Comment by travellerwjoe** [comment]
已找到原因，是配置的缘故，感谢！
