### ISSUE TITLE
rater支持unicode字符

### ISSUE THREAD

**Issue by zhump** [airyland/vux#2182]
```
 <rater v-model="data5" star="&#xe603;" active-color="#FF9900" :margin="1"></rater>
```
star传的是字符串

如果用v-html支持传入的star，就可以用字体图标来实现了。

```
  <span class="vux-rater-inner" v-html="star">
```

但是改节点下还有
```
 <span class="vux-rater-outer" :style="{color: activeColor, width: cutPercent + '%'}" v-if="cutPercent > 0 && cutIndex === i-1">{{star}}</span>
```

可能要调整一下结构了。

**Comment by airyland** [comment]
可 pr

**Comment by zhump** [comment]
#2183 就改了一行代码。不知道
```
Some checks were not successful
```
啥意思。哪里不对吗

**Comment by virus578** [comment]
1.使用unicode字符
![image](https://user-images.githubusercontent.com/39006992/45067605-86835f00-b0f6-11e8-8e45-d409fa40caad.png)
这样他是会占位不会显示
2.用了楼主说的 v-html 也会有问题
![image](https://user-images.githubusercontent.com/39006992/45067557-5c31a180-b0f6-11e8-9b48-6aaee09894de.png)
依旧不显示
3.试试用icon-font字体图标就成功了
![image](https://user-images.githubusercontent.com/39006992/45067496-1e347d80-b0f6-11e8-8fea-256e2857cfee.png)
待我去看看源码 先占坑
