### ISSUE TITLE
XInput组件，数字键盘的小数点问题？

### ISSUE THREAD

**Issue by kevinchung1026** [airyland/vux#2188]
XInput组件，当type="number"和keyboard="number"时，如果是安卓原生输入法或任意系统装了搜狗输入法的，都是带小数点的数字键盘。但是，苹果手机并且只有原生输入法，弹出的数字键盘没有小数点按钮，请问如何解决？

**Comment by airyland** [comment]
这个问题的解决方法是实现一个虚拟数字键盘，vux 后面会发布一个。

**Comment by oopoop** [comment]
虚拟数字键盘什么时候发布呀
