### ISSUE TITLE
Calendar组件disable-date-function返回false无效

### ISSUE THREAD

**Issue by tong233** [airyland/vux#2189]
按照文档的返回false表示不禁用,但是没有把disable-weekend或者disable-future的禁用改成可选,有些假期需要调休。

**Comment by airyland** [comment]
还是上代码来说明吧。

**Comment by tong233** [comment]
```javascript
<template>
<div>
  <group>
    <calendar
    title="开始时间："
    v-model="stdate"
    :disable-weekend="true"
    :disable-date-function="disableDateFunction">
    </calendar>
  </group>
</div>
</template>

<script>
import { Calendar, Group } from 'vux'

export default {
  data () {
    return {
      stdate: '',
      disableDateFunction (date) {
        if (date.formatedDate === '2017-11-18') { // 不禁用11-18
          return false
        }
      }
    }
  },
  components: {
    Calendar,
    Group
  }
}
</script>
````
![image](https://user-images.githubusercontent.com/21073132/32708080-fe038532-c862-11e7-8ab9-8d1907cfaee7.png)

**Comment by airyland** [comment]
在最新版本已经修复了。

**Comment by lianshengxing** [comment]
我是同时用到两个日历选择框，起始日期和截止日期，当选择了起始日期后，截止日期最多往后推一个年，所以我在on-change事件中调用disableDateFunction，报错 Cannot read property 'formatedDate' of undefined"

`<calendar
          :value="param.rqq"
          format="YYYY-MM-DD"
          @on-change="changeq"        
          title="起时间" style="width:50%;float:left;font-size:14px"></calendar>
        <calendar
          :value="param.rqz"
          format="YYYY-MM-DD"
          :disable-date-function="disableDateFunction"
          title="止时间" style="width:50%;float:right;font-size:14px"></calendar>


disableDateFunction (date) {
      if(date.formatedDate){
        if (new Date(date.formatedDate)>new Date(this.maxDate)) {
          return true
        }
      }
    },`

**Comment by yanxiaoyao** [comment]
如何把特定日期改为变值

**Comment by YJHecho** [comment]
如果按照 tong233 他说的话 那就一定要禁止周末或者以后所有的日期 但是我又不想禁止周末 同时也想实现禁止某个日期 怎么办？

**Comment by YJHecho** [comment]
If you follow tong233, then you must ban weekends or all future dates. But I don't want to ban weekends. I also want to prohibit a certain date. What should I do?
