### ISSUE TITLE
XDialog 关闭动画卡顿

### ISSUE THREAD

**Issue by magicdawn** [airyland/vux#2192]
https://github.com/airyland/vux/blob/v2/src/styles/transition.less#L25

在关闭的时候, 由 `scale(1.0)` 到 `scale(0.85)` 花掉了 300ms, 看起来和卡了一样...
建议调小 0.85 到一个小值

项目中修改到 scale(0.1) 效果效果还好. 酱

**Comment by Liuhuifeng** [comment]
我也关注这个issue

https://github.com/airyland/vux/issues/2199
这个动画在安卓上确实体验不好，IOS中非常流畅，建议fix
