### ISSUE TITLE
x-input如何允许输入小数

### ISSUE THREAD

**Issue by travelalife** [airyland/vux#2195]
<x-input title="数量" name="amount" type="number" placeholder="请输入数量" show-clear></x-input>
在提交表单时如果输入的是小数会出现HTML5的“请输入有效值，两个最接近的值分别是...和...”的警告，在x-input标签里添加step="0.1"属性也没有用，请问x-input有没有输入小数的解决方法？

**Comment by travelalife** [comment]
抱歉漏了代码
`<x-input title="数量" name="amount" type="number" placeholder="请输入数量" show-clear></x-input>`
另外，问题应该是x-input  type为number时输入小数的解决方法

**Comment by kitkimwong** [comment]
type 設成text，is-type 再用正則

**Comment by travelalife** [comment]
@kitkimwong ，谢谢，这样的话就相当于自己写校验规则了对吧，我以为vux会有自带的金额输入框之类的type
