### ISSUE TITLE
previewer组件崩溃

### ISSUE THREAD

**Issue by cfabregas** [airyland/vux#2196]
2.6.5版本，在项目中使用该插件，预览大图后再缩小回去的时候，会有一定概率卡死，然后点什么都没有反应，需要刷新页面才有反应。
不方便给出源码，图片的高宽设置的是img.width和image.height，不知道是不是这个的问题。

**Comment by airyland** [comment]
Android 还是 iOS, 哪个浏览器？
图片多大，缩略图多大？

没有重现代码，不方便重现，无法判断问题。
