### ISSUE TITLE
请问一下有类似像小程序weui的控件永远固定在底部的控件吗

### ISSUE THREAD

**Issue by git-cncoder** [airyland/vux#2198]
效果图，红色框中的。
![image](https://user-images.githubusercontent.com/22268505/32776956-4abb50dc-c96f-11e7-9e95-b1fe4b35f95e.png)

```
        <view class="weui-footer weui-footer_fixed-bottom">
            <view class="weui-footer__links">
                <navigator url="" class="weui-footer__link">WeUI首页</navigator>
            </view>
            <view class="weui-footer__text">Copyright © 2008-2016 weui.io</view>
        </view>
```

[代码地址](https://github.com/Tencent/weui-wxss/blob/master/src/example/footer/footer.wxml)

**Comment by wg5945** [comment]
这只不过是个css样式，可以使用fixed或者flex实现，自己写一个即可

**Comment by git-cncoder** [comment]
@wg5945   谢谢您的指导，android 学 前端，学习中~
