### ISSUE TITLE
弹窗组件在Android上卡顿

### ISSUE THREAD

**Issue by Liuhuifeng** [airyland/vux#2199]
Confirm, Alert, Popup 之类的组件，在安卓上有卡顿现象，在IOS中非常流畅。

不是低端机，其实也不是卡，是动画不是非常流畅

vue-router切换动画我也用了，并没有这种现象

看之前有一个类似的issue，没有解决方案被关闭了

现在有在解决这个问题吗？这个问题很影响页面整体的流畅度，希望大家能提供些方案。

**Comment by airyland** [comment]
感觉 Android 的不流畅问题得由系统来解决了。

**Comment by kitkimwong** [comment]
@airyland @Liuhuifeng 
https://stackoverflow.com/questions/15605731/jerky-css-transform-transition-in-chrome
https://www.w3cplus.com/css3/introduction-css-will-change-property.html
可以參考這篇，andriod 用transform 而不用transitions
然後css再加上will-change
我現在就是這樣 效果不錯的

**Comment by Liuhuifeng** [comment]
@kitkimwong thanks,随后试试

**Comment by hookbin** [comment]
@airyland 麻烦作者能够维护一下这个BUG

**Comment by airyland** [comment]
欢迎来 pr
