### ISSUE TITLE
selector组件点击出现黑色，下拉文字找不到

### ISSUE THREAD

**Issue by luchanan** [airyland/vux#2202]
测试环境是在QQ浏览器，模拟手机情况下Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.3538.400 QQBrowser/9.6.12501.400

![image](http://7qn7ih.com1.z0.glb.clouddn.com/2017-11-15_103027.png)

**Comment by airyland** [comment]
应该是浏览器的问题。
测试一下，在可重现环境随便写一个 select，如果效果同样，那么就非组件问题了。
