### ISSUE TITLE
vux 现在只能使用less语法，后期会不会出sass语法

### ISSUE THREAD

**Issue by liuxingzhijian1320** [airyland/vux#2205]
公司本来决定用vux，但是发现只能用less，就放弃这个ui了

**Comment by airyland** [comment]
不会。

vux 用 less 又完全不影响你项目用 sass，事实上你也不能用 less 来修改 vux 源码。你们公司考虑问题的真是开发吗？

你已经发过一个 issue #2203 ，重复水这么一条有意义吗？
