### ISSUE TITLE
在ios 11.1.1的微信下所有弹出的效果都会有闪烁的情况

### ISSUE THREAD

**Issue by jonnykay** [airyland/vux#2207]
在ios 11.1.1的微信里使用vux，所有的弹出效果，比如alert组件，xdialog组件，在弹出和关闭时都会出现闪烁的情况(包括官网上的示例)，ios的其他系统没有这个问题，android也没有这个问题。 这个要怎么解决

**Comment by wg5945** [comment]
我在6sp 11.1 上面貌似很正常

**Comment by jonnykay** [comment]
是11.1.1  不是11.1

**Comment by wg5945** [comment]
哦，刚升级了下，也没发现什么异常，你可以用别人的手机再试试

**Comment by airyland** [comment]
试试重启手机，这个版本的 iOS 可能会有一个问题，开机一段时间就会有页面 transition 闪烁的问题，不止是 vux，重启可破。。
