### ISSUE TITLE
设置路由切换loading无效

### ISSUE THREAD

**Issue by wangyubin1992** [airyland/vux#2208]
![195887a402158641e4c498e9e6d35b3](https://user-images.githubusercontent.com/24265937/32879487-234c0254-cae5-11e7-84ec-d232fa019925.png)

![5cd8df2d0c82b0086c08e2579f78f4c](https://user-images.githubusercontent.com/24265937/32879482-1eb59cd2-cae5-11e7-9c07-14da9d8298d4.png)按照官网文档的写法写入 但是路由切换时loading不会触发 处于隐藏状态 看了下 好像是用vuex进行状态管理··不太懂那个 像知道是缺啥什么配置吗 另外 源码里面的vuex下面的store.js也照搬了··还是没效果

**Comment by wg5945** [comment]
你应该先理解一下官网的demo为什么会触发loading效果，而不是单纯的去“抄”

**Comment by wangyubin1992** [comment]
按理说应该是isloading没有变化 一直是false···但是vuex的代码是跟作者一样的 我想知道遗漏了什么 除了app.vue和main.js以外

**Comment by wangyubin1992** [comment]
是要加载vuex-router-sync来进行同步处理吗··

**Comment by airyland** [comment]
建个可以重现的 repo。

**Comment by wangyubin1992** [comment]
检查了一下 router.beforeEach 里面的处理触发的 isloading成为false  但是router.afterEach里面的store.commit没有触发 打了console  有结果 说明执行了路由结束函数 但是store的函数没触发或者状态没有更新改变

**Comment by wangyubin1992** [comment]
是缺少什么类似更新状态的函数吗··

**Comment by wangyubin1992** [comment]
说反了··是router.beforeEach没触发 router.afterEach触发了

**Comment by wangyubin1992** [comment]
已经提交代码了··在我的仓库quesition

**Comment by airyland** [comment]
no package.json?
no build config?
no babel config?

Please add those files and reopen this issue.

**Comment by wangyubin1992** [comment]
恩 第一次弄github  不太熟练 这次上传完啦··

**Comment by airyland** [comment]
并不是无效，而是你并没有使用异步路由，切换时间短到 loading 不会显示出来。

``` js
setTimeout(() => {
    store.commit('updateLoadingStatus', {isLoading: false})
}, 1000) 
```

**Comment by wangyubin1992** [comment]
乌龙了···非常感谢！
