### ISSUE TITLE
Scroller android微信端卡顿问题

### ISSUE THREAD

**Issue by may00235** [airyland/vux#221]
### Version

0.0.117
### Android or iOS, which browser?

android ios 微信浏览器
### Your Codes

``` html
<scroller lock-x scrollbar-y
                            use-pulldown
                            :use-transition="useTransition"
                            :pulldown-status.sync="pulldownStatus"
                            @pulldown:loading="load"
                            class="scroller-div"
                            :pulldown-config=pulldownConfig
                            enable-horizontal-swiping
                            :height="scrollHeight +'px'">

                                <div class="scroller-container" >
                                         <div class="swiper-container">...</div>
                                         <div class="content">页面块内容 默认加载数据有两屏左右</div>
                                </div>
                              <div slot="pulldown" class="xs-plugin-pulldown-container xs-plugin-pulldown-down" style="position: absolute; width: 100%; height: 60px; line-height: 60px; top: -60px; text-align: center;">
                                    <span v-show="pulldownStatus === 'default'"></span>
                                    <span class="pulldown-arrow" v-show="pulldownStatus === 'down' || pulldownStatus === 'up'" :class="{'rotate': pulldownStatus === 'up'}">↓</span>
                                    <span v-show="pulldownStatus === 'loading'"><spinner type="ios-small"></spinner></span>
                              </div>
</scroller>
```
### 在不同终端机器的微信测试

ios
iphone6 6s 微信里打开滚动效果很顺畅

android 
华为荣耀 6 华为荣耀 6+  锤子坚果 在微信里打开出现卡顿情况，一卡一卡的体验不好

android但用UC浏览器打开，卡顿效果不太强烈，可以正常滚动，但还是有点卡

尝试看了一下xscroll的代码，是通过simulate-scroll处理的滚动效果的，但不确定里面的transform是否有webkit浏览器处理，个人猜测是不是要加上webkitTransform translate的处理就ok了？

**Comment by airyland** [comment]
上面的Android是否是低端配置？

**Comment by may00235** [comment]
中端机，华为现在占的市场份额很高。
也用华为的P9高端机测试过，微信webkit与浏览器打开都没问题，很顺畅。

**Comment by lagolas** [comment]
我的华为的，Android5 微信打开demo卡顿。。。
就是从demo也点进去具体的组建演示的过程卡

**Comment by airyland** [comment]
@lagolas 首次进入卡，还是每次进入都卡？

**Comment by airyland** [comment]
@may00235 没有足够的测试机不能做出结论，我用两三年前的小米2都不会有一卡一卡的状态，不过系统是5.0.2的。

**Comment by lagolas** [comment]
@airyland 我再多测试下

**Comment by lagolas** [comment]
@airyland  每次都卡，例如我从demo页点第一个“address”,要大概3秒才能出现这个组件的页面，然后点“返回”，要大概2秒钟才能返回到demo页，我测试很多个其他组件，也是同样的，只不过有的稍微快一点，但是也是明显的感觉卡，都是要等待至少2秒才出现页面

**Comment by lagolas** [comment]
我使用opera浏览器打开，比在微信里还要明显

**Comment by lagolas** [comment]
手机是华为畅享5，Android5.0 新手机，配置还不算太烂

**Comment by airyland** [comment]
@lagolas  进入scroller的demo, 左右上下滚动卡吗？

**Comment by lagolas** [comment]
@airyland  不卡，非常流畅！！！

**Comment by lagolas** [comment]
我还没仔细研究你的代码，不知道是不是东西加载的太多导致的。
谢谢，准备在项目改版中使用vux

**Comment by airyland** [comment]
@lagolas 里面每个例子都不卡对吧？难道是因为打包后的app.js过大，webview执行大文件会有卡顿？

**Comment by lagolas** [comment]
@airyland  我又仔细测试了几遍，里面的例子都很流畅，只有**日历选择**的那个不太好，点击之后要延迟一些才会有效果。其他的都很流畅。

**Comment by airyland** [comment]
@lagolas Calendar 这个延迟问题应该可以解决。

**Comment by lagolas** [comment]
@airyland 捐助1元以表支持，表嫌少，谢谢

**Comment by airyland** [comment]
@lagolas 哈哈，1分也是爱啊 😸

**Comment by lagolas** [comment]
@airyland 后续使用的时候遇到问题在向你请教，谢谢你的奉献。

**Comment by airyland** [comment]
@lagolas 欢迎反馈，欢迎PR.

**Comment by bammoo** [comment]
有没有想过换成更流畅的 scroll 库？比如这个：https://github.com/pbakaus/scroller

**Comment by airyland** [comment]
@bammoo 这是个大坑，你有足够多的测试机证明它更流畅咩？

**Comment by daviswei** [comment]
https://vuxjs.gitbooks.io/vux/content/ 这里好像都没有更新有组件card的文档，感谢无私奉献

**Comment by lichunqiang** [comment]
@daviswei 稍后会写出来

**Comment by hubinjie** [comment]
安卓 的微信 上面只要用了scroller 就卡顿，没有用scoller的反而比较流畅,IOS上面都可以

**Comment by airyland** [comment]
@hubinjie 不是所有场景都要用scroller的吧，能不用scroller就不用scroller。

**Comment by hubinjie** [comment]
@airyland 不是所有都用，之所以用这个主要是用到了这个上拉和下拉 功能

**Comment by airyland** [comment]
@hubinjie 现在想来不少用户是因为scroller有上拉下拉刷新才用的scroller，而实际上采用已有的社区组件也可以不用scroller就实现上拉下拉刷新。scroller作为一个特殊的组件，在里面的元素都需要特殊处理。

**Comment by bammoo** [comment]
我本地已经在用 https://github.com/pbakaus/scroller，有空封装一下

**Comment by hubinjie** [comment]
@airyland  另外一点用这个scroller 我用vue-route 中 keep-alive 支持比较好，会记住上次的位置，总体来说这个组件还不错，不过现在确实用在微信的安卓上面滑动里面比较卡

**Comment by hubinjie** [comment]
@airyland  我先从加载的图片上面优化一下再看看

**Comment by airyland** [comment]
@hubinjie 你的机型是？

**Comment by hubinjie** [comment]
@airyland 华为 荣耀6， 荣耀6PLUS也卡

**Comment by airyland** [comment]
@hubinjie 我感觉最老出问题的都是华为呢。。

**Comment by hubinjie** [comment]
@airyland  其他安卓机型也一样，scroller也是比较卡

**Comment by hubinjie** [comment]
@airyland  这个是我待上线和版本 ，请用微信扫一扫

<img src="https://sp0.baidu.com/5aU_bSa9KgQFm2e88IuM_a/micxp1.duapp.com/qr.php?value=http%3A%2F%2Fweixin.meihu365.com" />

麻烦有空看一下，安卓比较卡，麻烦提点意见，全部控件使用VUX

**Comment by xiaolongyuan** [comment]
卡 很卡

**Comment by hubinjie** [comment]
商品详细页未使用 scroller 滑动很快，比较顺

**Comment by hubinjie** [comment]
@airyland  我的几台安卓版本 4.4.2 ，4.4.4

**Comment by airyland** [comment]
@hubinjie 感觉首页问题比较多
- swiper 的loading不居中
- swiper左右滑动时触发了scroller上下滑动，这个应该可以通过swiper的minDistince来解决，见swiper的demo
- 中间的横向scroller左右滑动时也触了上下滑动
- 边框线大小不一，有的是1px，有的是2px
- toast 只显示文字时有点问题，这应该是vux的bug

**Comment by hubinjie** [comment]
@airyland 感谢

**Comment by docikaci** [comment]
@hubinjie  微信扫一扫打开后，来回切换下面菜单，微信直接崩溃了。chrome崩溃，Safari也是

iPhone 5  ios 8.0

我写个demo，使用scroller 也会崩溃。
