### ISSUE TITLE
Swipeout在ios中的使用问题

### ISSUE THREAD

**Issue by itHulk** [airyland/vux#2210]
你好,airyland,首先很荣幸使用VUX，在使用Swipeout组件中，我遇到了如下问题，需要删除的记录，也需要可以点击进入详情页面，但是在ios中系统中（ios系统中，UC浏览器和微信环境都测试过），click事件和Swipeout的滑动（滑动的时候，手指触碰屏幕的时候会触发click事件）删除冲突了，想要滑动删除的时候，会触发click进入详情页的事件，请问我该如何解决？如下图
![image](https://user-images.githubusercontent.com/22711051/32890490-98c8fc90-ca94-11e7-804b-3a91a4c02fab.png)

**Comment by airyland** [comment]
请上代码。看你描述也不知道你所说的 click 绑定在哪个元素上。

**Comment by itHulk** [comment]
代码如下，click事件加在了content上，点击可进入详情页面
<img width="949" alt="_922919b3-333e-4107-80ee-d9cc7b1e88cd" src="https://user-images.githubusercontent.com/22711051/32924470-6dd31840-cb02-11e7-9bd9-410428dde24c.png">

**Comment by airyland** [comment]
在微信里，Safari 里测试并不能重现，滑动不会触发点击事件。

**Comment by ycxian** [comment]
请问解决了吗？我也遇到了

**Comment by Rryeyu** [comment]
我遇到了在微信环境下测试ios12以下的版本滑动不了 我没写任何代码，直接复制过去滑动组件就不好用

**Comment by Opportunitie** [comment]
我遇到了在微信环境下测试ios12以下的版本滑动不了 我没写任何代码，直接复制过去滑动组件就不好用

**Comment by Opportunitie** [comment]
ios 10.3.3测试过，滑不动

**Comment by sunsipeng** [comment]
IOS 13.5.1 滚动页面会误触左滑展开菜单事件，导致页面无法滚动。
