### ISSUE TITLE
企业微信单独出了个"weui for work"

### ISSUE THREAD

**Issue by JunLiangW** [airyland/vux#2212]
https://work.weixin.qq.com/api/doc#12146

应该可以简单的修改以兼容,以下是官方原话

 注：除了加载的 CSS 文件不一样，使用 WeUI for Work 与使用 WeUI 无 HTML 结构上的变化。企业微信开发者如果早前使用的是 WeUI v1.x 版本，更换相关 CSS 文件为 WeUI for Work 的样式文件即可无缝切换到适配企业微信的风格界面。

**Comment by airyland** [comment]
WeUI 样式目前是蓝色的主题，不能同时支持另外的色调主题，最多只能通过 vux 已经有的 less-theme 来兼容，不知道你说的简单修改是怎么修改？另外，这个更希望有需求的用户来 pr，目前自身没有这个需求也看不到这个需求的通用性，因此不会直接支持。
