### ISSUE TITLE
x-table组件body内容如何自适应

### ISSUE THREAD

**Issue by Samsara0329** [airyland/vux#2215]
表头：产品、数量、预售价、操作，长度分配不一致，是否可以设置表格各列长度，谢谢
![qq 20171119111520](https://user-images.githubusercontent.com/26599122/32987069-3be77f22-cd1b-11e7-93a8-89daec46a4fb.png)

**Comment by airyland** [comment]
XTable 仅仅是封装，原来 table 是怎么设置宽度的就怎么设置宽度。
