### ISSUE TITLE
非单文件组件下，按需引用失效导致打包文件过大。

### ISSUE THREAD

**Issue by rhymedys** [airyland/vux#2216]
vux、vux-loader、webpack版本号
![image](https://user-images.githubusercontent.com/15199335/32987770-48708982-cd2f-11e7-865a-ef64ea366867.png)
webpack里面已经是按要求配置好vux-loader的
![image](https://user-images.githubusercontent.com/15199335/32987763-311527e8-cd2f-11e7-9b0b-94ca9ac937f3.png)
以某一组件servicePage为例 ，引用XSwitch,Picker两个控件
![image](https://user-images.githubusercontent.com/15199335/32987729-9e58ccd4-cd2e-11e7-8c96-99c4e61e9561.png)
![image](https://user-images.githubusercontent.com/15199335/32987733-a89a5708-cd2e-11e7-9602-39876e2878fe.png)
在非单文件组件下（如下图引用js方式为例），
![image](https://user-images.githubusercontent.com/15199335/32987735-b65f097e-cd2e-11e7-8fc9-447125673ca9.png)
然后进行一次打包，打包之后发现servicePage包含了很多其他组件等等的东西
![image](https://user-images.githubusercontent.com/15199335/32987775-5a3ee62c-cd2f-11e7-8487-7c4d72470f00.png)
结果就是：按需引用失效了。
如果是按照单文件组件的方式进行编码，再进行一次打包图如下：那么结果是：按需引用又正常了
![image](https://user-images.githubusercontent.com/15199335/32987812-44a30112-cd30-11e7-9446-ff30a39ca128.png)

**Comment by airyland** [comment]
测试并不能重现。可能跟 webpack 原配置有关，麻烦建个简单 repo。

**Comment by rhymedys** [comment]
@airyland repro地址： https://github.com/rhymedys/Helloworld   在以下这个组件
![image](https://user-images.githubusercontent.com/15199335/32989342-3e054878-cd4f-11e7-9c31-658103b66086.png)

**Comment by rhymedys** [comment]
@airyland

**Comment by airyland** [comment]
升级到最新 vux-loader 应该可以解决。
