### ISSUE TITLE
Previewer组件大图在safari内长按无法保存

### ISSUE THREAD

**Issue by JayWii** [airyland/vux#2218]
如题，该组件点击打开的大图在微信浏览器内长按可以弹出保存图片的选项，但在safari内长按无效，请问是否有办法可以解决？

**Comment by airyland** [comment]
看起来是 photoswipe 的问题 https://github.com/dimsemenov/PhotoSwipe/issues/1440
但是 Safari 可以，微信 webview 又可以就不知道是什么原因导致的了。

**Comment by airyland** [comment]
曲折的实现方法是按照 photoswipe 文档，可以启用分享按钮，然后点击分享按钮会出现一个下载按钮。

``` js
shareEl: true,
shareButtons: [
  {id: 'download', label: 'Download image', url: '{{raw_image_url}}', download: true}
],
```

![image](https://user-images.githubusercontent.com/559179/33107094-3d298f6a-cefb-11e7-88e2-7bd4c31314c8.png)

**Comment by JayWii** [comment]
@airyland 由于这个曲折的办法用户体验实在有点糟糕，我最终还是决定直接对photoswipe源码下手，解决了长按不能保存的问题，然后又借（co）鉴（py）你的代码，自己单独实现了一个预览组件，解决了问题。特此来感谢你！

**Comment by airyland** [comment]
@JayWii 可以来分享一下处理方法
