### ISSUE TITLE
在引用组件js的方式下如何自定义组件样式

### ISSUE THREAD

**Issue by Hao-Wu** [airyland/vux#222]
没有使用es6+webpack, 而是直接引用的目标组件的js和样式。比如tab和tab-item, 现在想要自定义tab和tab-item的字体颜色、背景颜色等样式，那么如何修改比较方便？

**Comment by airyland** [comment]
tab-item支持html，所以你可以用html定义样式而不是纯文本。
其他的你可以覆盖样式。
具体class名可以审核一下或者见源码 https://github.com/airyland/vux/blob/master/src/components/tab/tab.vue

**Comment by airyland** [comment]
属性支持部分样式，见 https://vux.li/doc/layout/tab.html

**Comment by Hao-Wu** [comment]
终于看到文档，是否还未正式发布呢，非常有帮助。

**Comment by airyland** [comment]
@Hao-Wu 基本写完了，还不更新出去。
