### ISSUE TITLE
Datetime为啥不能以DatetimePlugin的形式引入

### ISSUE THREAD

**Issue by wangqihang** [airyland/vux#2226]
`this.$vux.datetime.show({
        cancelText: '取消',
        confirmText: '确定',
        format: 'YYYY-MM-DD HH',
        value: '2017-05-20 18',
        onConfirm (val) {
          console.log('plugin confirm', val)
        },
        onShow () {
          console.log('plugin show')
        },
        onHide () {
          console.log('plugin hide')
        }
      })`
这种形式不能使用

**Comment by airyland** [comment]
不能使用是什么意思？报什么错？你有没有在入口处引用？
无法帮助，请自行解决。
