### ISSUE TITLE
popup-picker的关闭问题

### ISSUE THREAD

**Issue by lmasdata** [airyland/vux#2227]
你好，
有个业务场景，会在popup-picker显示的时候调用接口，如果没有数据的话会关闭popup-picker。
请问，哪个方法可以触发popup-picker的关闭

**Comment by airyland** [comment]
使用 :show.sync 来控制：

https://github.com/airyland/vux/blob/c897d427569644be0b1e87884132bb48b1baddc1/src/demos/PopupPicker.vue#L41-L43
