### ISSUE TITLE
如何在nuxt.js中使用vux

### ISSUE THREAD

**Issue by duqigit** [airyland/vux#2232]
我安装了vux 如图

请问在nuxt.confg.js中如何使用
![2edda17ad5d7a3dad2adc05af93f9e2](https://user-images.githubusercontent.com/25985156/33162378-3ca0dd04-d064-11e7-924c-9da61e7d3a61.png)
但是出现了如图
![332a1ed5e6d2bd30014e580ce1bc753](https://user-images.githubusercontent.com/25985156/33162427-6e639980-d064-11e7-9a6a-9b98efa8fb71.png)
请问我需要怎么jiejue解决 谢谢

**Comment by TheSixer** [comment]
请问你知道怎么在Nuxt 中配置vux 了吗？

**Comment by vmvz** [comment]
我也想知道,,,

**Comment by airyland** [comment]
#2490
