### ISSUE TITLE
vux在electron-vue这个vue-cli工具中不能加载使用

### ISSUE THREAD

**Issue by fanjiangwei7** [airyland/vux#2233]
在electron-vue脚手架构建的工程中加入vux作为界面使用的时候，在配置了vux-loader后。不能正常工作。
<img width="342" alt="105cf604-75e3-4833-b8fd-8cdd8e3207f8" src="https://user-images.githubusercontent.com/17830397/33173726-35cda774-d090-11e7-8e50-530084f03c56.png">

electron-vue工程模板使用了webpack进行打包但是生产的webpack文件不是webpack.base.conf.js、webpack.dev.conf.js和wepack.prod.conf.js文件，而是生成了electron环境下的webpack.main.config.js、webpack.renderer.config.js和webpack.web.config.js三个文件，我参照webpack.base.cong.js的vux-loader的加载实现，尝试在webpack.renderer.config.js的实现中加入vux-loader，但是运行时总是提示失败。

现在只能使用工程文件静态直接加载组件的方式来加载。静态加载的时候由于没有源代码路径下的src/styles文件夹，现在显示的时候缺少css相关组件。

请问现在vux有对electron-vue这个vue-cli工具支持的计划嘛？

**Comment by airyland** [comment]
非 Vue 官方 repo，暂没有时间去看什么原因。没看懂什么是静态加载，src/styles 在 npm 包里是存在的。另外 electron 是桌面端应用，用 VUX 感觉不大合适。

**Comment by GitYonglin** [comment]
@fanjiangwei7 

- "vux": "^2.7.4"
- "vux-loader": "^1.1.27"

我也遇到了一样的问题，不过我可以加载成功，
~~a.在webpack.web.config.js 文件中添加vux-loader配置(这个不需要配置)~~
### 只要在webpack.renderer.config.js 文件中添加一个白名单
```
let whiteListedModules = ['vue', 'vux']
```
这样可以添加成功，就是有下面的错误！！！
出现了以下错误：

1. $t
2. clocker 组件需要升级 vux-loader 到最新版本才能正常使用
3. VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
4. 当前组件[cell]要求更新依赖 vux-loader@latest
## 看来是vux-loader配置的问题。我按照官网的配置在webpack.renderer.config.js中配置就会报错vue模板没有定义，
    - [Vue warn]: Failed to mount component: template or render function not defined.

在单独vue项目中手动添加按照官网的配置是没有问题的。
应该electron-vue项目webpack配置的问题，我的项目是要在平板上使用所以觉得vux比较适合。希望能有办法可以解决。
