### ISSUE TITLE
x-header组件能否实现路由返回自定义

### ISSUE THREAD

**Issue by holiyo** [airyland/vux#2234]

**Comment by airyland** [comment]
`left-options.preventGoBack` 设为 true，监听事件 `on-click-back` 来处理。

**Comment by codingwesley** [comment]
@airyland  可以监听返回事件，但是，现在又需要返回页面怎么写

**Comment by choukui** [comment]
我也遇到同样的需求，如果是直接打开详情页，那么点击返回首页，如果从其页面点进来的，那么返回其他页面。请问怎自定义，返回事件没有参数，无法判断。

**Comment by bnlwl** [comment]
用router的钩子函数afterEach。

**Comment by bnlwl** [comment]
用router的钩子函数afterEach + storage

**Comment by bnlwl** [comment]
> 用router的钩子函数afterEach + storage

vue.$router.back()也可以做到
