### ISSUE TITLE
this.$vux.confirm.show方式如何为弹框添加样式

### ISSUE THREAD

**Issue by linsphone** [airyland/vux#2237]
this.$vux.confirm.show方式如何为弹框添加样式 。弹框按钮的顺序是否可以配置顺序 
比如确定 取消  ，取消 确定

**Comment by airyland** [comment]
样式覆盖。
不可以，这是符合正常交互的顺序，不支持修改。非要修改的话，直接用 x-dialog 来封装一个弹窗。
