### ISSUE TITLE
IOS下PopupPicker弹出时，弹层背景色会有一瞬间的闪烁，官方DEMO中也存在该问题

### ISSUE THREAD

**Issue by grsghh** [airyland/vux#2239]
如题，PopPicker被触发显示时，弹层主区域的背景色一个由灰到白的闪烁过程，在PC端则没有该问题。
本人机型：iphone 6sp 
IOS版本：10.3.2

![test](https://user-images.githubusercontent.com/22166573/33226666-34a631b0-d1ce-11e7-90c2-57ddd74c0996.gif)

**Comment by simple-lu** [comment]
me,too,我是iphone7... 貌似苹果手机都有这毛病

**Comment by wzc0x0** [comment]
-webkit-tap-highlight-color: transparent;

**Comment by airyland** [comment]
iOS 11 似乎无法重现，暂时关闭了。

**Comment by webduchang** [comment]
此组件在定制的情况下。如pinker背景是深色，被点击后，会出现闪白，而且有的手机点一下，闪一下，有的手机随机闪白。大家有没有遇到这个bug？？？谢谢指导
