### ISSUE TITLE
ios左滑返回动画

### ISSUE THREAD

**Issue by agileago** [airyland/vux#2241]
之前在某个issue听你说过ios无法判断是点击导航返回还是手势拖动返回，导致ios用手势返回的时候会有返回动画再执行一下，但今天我在刷微博的时候看到微博竟然实现了这个功能，有点神奇，但他们的代码是压缩的，debug了一会，没太看懂他们是如何判断是`手势返回`和`导航返回`,你有空的时候可以瞧瞧，共同探讨一下。地址： http://shop.sc.weibo.com/h5/goods/index?iid=110060376871210003440842 (可能需要先登录微博),  拉到下面有个进入橱窗，点击进入
![image](https://user-images.githubusercontent.com/11799110/33231299-9e305cdc-d22d-11e7-80ac-5a4c77d64c16.png)
路由会变，也有进入动画， 然后你手势返回的时候他就没有执行任何动画，但当你点击导航栏返回的时候，就有进入退出动画了，有点神奇

**Comment by agileago** [comment]
https://codepen.io/agileago/pen/OOBvgp

写了一个demo, 基本实现了Ios左滑返回不执行动画，具体原理就是左滑返回的时候会触发一次 `touchend`事件，记录一下触发的时间，然后在 `beforeEach`里面判断当前时间和最后一次`touchend`时间的差值小于377(我也不太确定这个时间是怎么定的),就不执行动画

```javascript
var isPush = false
    var endTime = Date.now()
    var routes = [
      {
        path: '/',
        redirect: '/a'
      },
      {
        path: '/a',
        component: {
          template: `<div class="page a">i am a page <router-link to="/b">跳转到B</router-link></div>`
        }
      },
      {
        path: '/b',
        component: {
          template: `<div class="page b">i am B page</div>`
        }
      }
    ]
    var router = new VueRouter({
      routes
    })
    var vm = new Vue({
      router,
      el: '#app',
      data: {
        direction: 'in'
      }
    })
    var push = router.push.bind(router)
    router.push = function () {
      isPush = true
      push.apply(null, arguments)
    }
    router.beforeEach((to, from, next) => {
      var a = Date.now() - endTime
      console.log(a)
      console.log(isPush)
      if (!isPush && a < 377) {
        vm.direction = ''
        next()
        return
      }
      if (to.path == '/b') {
        vm.direction = 'in'
      } else {
        vm.direction = 'out'
      }
      next()
    })
    router.afterEach((to, from) => {
      isPush = false
    })
    document.addEventListener('touchend', e => {
      endTime = Date.now()
      console.log(endTime)
    })
```

**Comment by agileago** [comment]
![qq20171129-160917](https://user-images.githubusercontent.com/11799110/33364539-d9c51f04-d51f-11e7-9f7c-b3de4af80425.gif)

有时候会有闪屏出现

**Comment by zjtt** [comment]
之前那个issue是我提的，你这个方法能解决问题吗？

**Comment by agileago** [comment]
已经解决了啊，官网demo现在已经更新上去了，你可以看看

**Comment by agileago** [comment]
#2259

**Comment by imtns** [comment]
@agileago 套用了你们的代码，现在左滑返回动画不会再次执行了，但是右滑前进还是会再次执行一次动画
