### ISSUE TITLE
Radio 和 PopUp Radio的 Value 應該像Selector那樣支援Object

### ISSUE THREAD

**Issue by kitkimwong** [airyland/vux#2242]
查看代碼 Selector的 prop之value是
`value: [Boolean, String, Number, Object],`

而Radio和 Popup-Radio 是沒有Object的
希望Radio能支持像Selector那樣送Object

而Popup radio因為是有用到Cell的，所以希望Cell和Radio都能支持Object

**Comment by airyland** [comment]
举个例子，Object 用于什么需求？

**Comment by laopeng** [comment]
接口返回的数据不一定按照key value的方式返回，因此需要支持Object @airyland

**Comment by yin-xie** [comment]
@airyland 比如我选择了某一项 这条数据的很多我都要用到不仅仅是key，需要都返回
