### ISSUE TITLE
官网的demo演示一片空白

### ISSUE THREAD

**Issue by Adar-Li** [airyland/vux#2243]
![default](https://user-images.githubusercontent.com/13981812/33247177-0c42318a-d357-11e7-90b7-a02101df0aca.png)
请帮忙看一下，谢谢！

**Comment by wzc0x0** [comment]
官网炸了

**Comment by Adar-Li** [comment]
@wzc0x0 beng 崩 beng 崩 beng 崩 ~~~

**Comment by hujindo123** [comment]
me too

**Comment by yys1105** [comment]
me too

**Comment by lirahalu** [comment]
很急很关键

**Comment by ckaiCp** [comment]
有点让人沮丧。毕竟大家都是在深度使用的。

**Comment by lhcpig** [comment]
看不了demo了···

**Comment by kai-chan-cp** [comment]
me too。

**Comment by DaDiaoShuai** [comment]
加油喔老铁@airyland

**Comment by zarkin404** [comment]
+1

**Comment by Sapphire2k** [comment]
大家莫慌，直接下demo本地跑即可😄

**Comment by airyland** [comment]
公告一下：请别老他妈的发1分钱来骂我，或者发1分钱来催我把 demo 修好行不？暂时不修了。
