### ISSUE TITLE
dateTime通过插件形式引入，报Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by need93** [airyland/vux#2249]
vue: "^2.5.8" 
vux: "^2.7.4"
node:" v8.4.0"
引入
![_fa5796fb-2285-476d-a08a-a819b15612d2](https://user-images.githubusercontent.com/34022821/33256760-8346acd4-d38e-11e7-8332-6b135952da58.png)

调用
![_1aa06a89-72c8-4149-8ff8-dae46ddedec4](https://user-images.githubusercontent.com/34022821/33256740-65dcbe22-d38e-11e7-82e2-e3c5e108776f.png)

出现此问题操作是对vue、vux、vux-loader进行了全面版本更新导致
vue 2.3.3->2.5.8
vux 2.5.9->2.7.4
vux-loader 1.1.5->1.1.27

**Comment by lyh2668** [comment]
@need93 2.65版本也无该问题，升级到2.75版本的时候出现了同样的问题，`plugins`方式引入的无法正常弹出`datetime-picker`组件，我在尝试定位出现的原因

**Comment by lzcrwxl** [comment]
我这边也遇到同样的问题，用的是2.75版本的

**Comment by lyh2668** [comment]
@lzcrwxl 
- #2302 
- [解决方案](https://juejin.im/post/5a3266fc51882503dc53bc11)

**Comment by need93** [comment]
感谢"lyh2668"提供解决方案，根据个人项目情况，为了防止本地打包构建下载最先vux版本冲掉自己手动改的vux文件，将vux/src/components/datetime/style.less'文件放到开发项目下进行引入（对应的文件中引入其他的less文件，可视情况处理，本人手动替换），将来vux对该bug进行修复后删除对应引入即可。

**Comment by gino543** [comment]
为了防止本地打包构建下载最先vux版本冲掉自己手动改的vux文件，将vux/src/components/datetime/style.less'文件放到开发项目下进行引入（对应的文件中引入其他的less文件，可视情况处理，本人手动替换）

请教一下，这个应该如何做
