### ISSUE TITLE
初次使用vux 一直报_vm.$t is not a function 错误。在main.js里面加了Vue.use(vuei18n) 也不行！

### ISSUE THREAD

**Issue by BestSu0921** [airyland/vux#2250]
**main.js**
`import Vue from 'vue'
import App from './App'
import router from './router'
import vuei18n from 'vue-i18n' 
// import vux from 'vux' 

Vue.config.productionTip = false

/* eslint-disable no-new */
// Vue.use(vux)
Vue.use(vuei18n)

new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})`

**.Vue文件**
`<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <h2>Essential Links</h2>

    <h2>Ecosystem</h2>
    <group>
      <cell title="ooo">1111222111222111</cell>
    </group>
    
  </div>
</template>’

‘<script>
  import { Group, Cell } from 'vux'
  export default {
    components: {
      Group,
      Cell
    },
    name: 'HelloWorld',
    data () {
      return {
        msg: 'Welcome to Your Vue.js App'
      }
    }
  }
</`

报错说：vue.esm.js?efeb:574 [Vue warn]: Error in render: "TypeError: _vm.$t is not a function"
              VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。

**刚安装的vux-loader怎么说不说最新的？**

**Comment by airyland** [comment]
不如文档再看一下再来提问？
