### ISSUE TITLE
popup-picker如何使用popup-style强制指定 z-index

### ISSUE THREAD

**Issue by igoodzp** [airyland/vux#2253]

**Comment by wangluyu** [comment]
:popup-style="{zIndex: 502}"

**Comment by mingtail** [comment]
最好是用TransferDom, 解决 z-index 问题

**Comment by netfere** [comment]
在使用drawer的情况下，popup会被遮挡信，无论设置zIndex为多少，都被<a class="vux-popup-mask vux-popup-show" data-uuid=",i7xoe" href="javascript:void(0)" style="z-index: 500;"></a>挡住。

**Comment by netfere** [comment]
在使用drawer的情况下，popup会被遮挡信，无论设置zIndex为多少，都被挡住。
`<a class="vux-popup-mask vux-popup-show" data-uuid=",i7xoe" href="javascript:void(0)" style="z-index: 500;"></a>`
