### ISSUE TITLE
有的时候代码格式化会报 import  from 'vux/undefined'

### ISSUE THREAD

**Issue by mumudev** [airyland/vux#2255]
当在component里面这样引入的时候
![image](https://user-images.githubusercontent.com/16707612/33305799-8cd11002-d44a-11e7-9e68-bdce84c4ee11.png)
最后个逗号会被识别，并生成个undefined的component引入，如果方便的话，可以顺便修复下。

**Comment by mumudev** [comment]
![image](https://user-images.githubusercontent.com/16707612/33305817-abd9bd1e-d44a-11e7-9f5c-d056097a0053.png)
会报错

**Comment by airyland** [comment]
之前已经修复过了。更新到最新版本吧。
