### ISSUE TITLE
timepicker在Safari下 渐变效果在首次打开窗口时失效 切换后正常

### ISSUE THREAD

**Issue by maoqxxmm** [airyland/vux#226]
平台：Safari 9.1

![image](https://cloud.githubusercontent.com/assets/18388484/15699293/6690d322-27fe-11e6-8c84-3ad0ec03a2ea.png)

这是timepicker窗口第一次被打开时的状态，可以看到渐变没有效果

![image](https://cloud.githubusercontent.com/assets/18388484/15699320/a303477c-27fe-11e6-897f-7f88f7afe0b6.png)

这是按下右下角的切换以后，渐变效果出现

窝还在找这个问题的原因。。。

**Comment by airyland** [comment]
我有注意到还没有去查原因。欢迎PR。

**Comment by maoqxxmm** [comment]
http://stackoverflow.com/questions/27749767/css-background-image-not-appearing-in-safari
这里有个解决方案 我试了下可以
设置scroller-content的z-index为-1（目前为1）

**Comment by airyland** [comment]
:+1:  
注意到样式和默认的不一样，你是自己做了组件的样式改造吗？

**Comment by maoqxxmm** [comment]
嗯。窝们的UI给窝的视效

**Comment by airyland** [comment]
如果上线给个地址看看？或者不涉及机密的话发些参考图，我也借鉴借鉴。

**Comment by maoqxxmm** [comment]
噗 过阵子应该会上线 现在还非常简陋

**Comment by maoqxxmm** [comment]
@airyland 已提交PR 顺便还改了一个小地方
