### ISSUE TITLE
localhost可以访问 ip不能访问

### ISSUE THREAD

**Issue by Grolia** [airyland/vux#2261]
为什么新创建的项目现在用本机的ip替代localhost不能访问到项目了，提示无法访问此网站。之前是可以的，我打开其它项目这样操作也是可以的。因为我要这样用手机进行测试，我看了一下config文件，里面不同了，但是不知道怎么改，求指教

**Comment by wg5945** [comment]
try

    "dev": "webpack-dev-server --host 0.0.0.0 --inline --progress --config build/webpack.dev.conf.js",

**Comment by primewang** [comment]
这样操作后，同网络的其他手机，或者电脑，访问时显示空白

**Comment by Grolia** [comment]
试过了，不行

**Comment by wg5945** [comment]
试试看电脑上使用ip能否正常访问

如果电脑能正常访问，手机空白的，并且是ios11以下系统的

把webpack.config.js中

`devtool: '#eval-source-map'`

改成

`devtool:'inline-source-map'`

**Comment by Grolia** [comment]
现在根据文档里面的步骤创建vux项目，在build文件夹下是没有webpack.config.js这个文件的




发自网易邮箱大师
在2017年12月07日 16:45，万刚 写道：

试试看电脑上使用ip能否正常访问

如果电脑能正常访问，手机空白的，并且是ios11以下系统的

把webpack.config.js中

devtool: '#eval-source-map'

改成

devtool:'inline-source-map'
