### ISSUE TITLE
set start-date in DateTime but not working

### ISSUE THREAD

**Issue by Penggggg** [airyland/vux#2263]
> version
- vux: ^2.6.5
- vue: ^2.5.2

> Expect
set start-date in <datetime> that would get a limitation in Year、Month 、Date.

> 期望
在 <datetime> 设置 start-date 后，对年份、月份、日份进行限制

> Happend
set start-date in <datetime> that would get a limitation in Year、Month except for Date. In Date block. When i set **start-date="2017-11-30"**， i can still choice Date which is before 30 when the Month is 11.

> 实际
在 <datetime> 设置 start-date 后，对年份、月份进行了限制，除了日份。当我设置了 **start-date="2017-11-30"**，我依然能够在11月份中的日份上，选择30号以前的日期。

**Comment by airyland** [comment]
并不能重现，请给出可重现代码或者 repo。

**Comment by Penggggg** [comment]
抱歉，请求取消该issue。问题已找到。打扰您的工作了，抱歉。
@airyland

**Comment by heyideal** [comment]
您好，请问怎样设置end-date为当前日期？
