### ISSUE TITLE
是否能帮忙看看jest下测试的问题

### ISSUE THREAD

**Issue by Jiiiiiin** [airyland/vux#2264]
### 初次使用jest，不知道是否是自己的原因，但是感觉应该是vue-test-utils本身对应嵌套引入的集成问题，不知道老大有没有时间看看；

+ 在集成vue官方推荐的vue-test-utils时候报错，集成方式直接参考：https://vue-test-utils.vuejs.org/zh-cn/guides/testing-SFCs-with-jest.html和对应的官方示例，测试代码如下：

    - 报错日志：对于报错import，已经根据 [为 Jest 配置 Babel](https://vue-test-utils.vuejs.org/zh-cn/guides/testing-SFCs-with-jest.html)进行设置了。

```cmd
jiiiiiin@jiiiiiins-MacBook-Pro  ~/Documents/WebstormProjects/vue-viewplus   dev ●  npm run test

> vue-viewplus@0.0.3 test /Users/jiiiiiin/Documents/WebstormProjects/vue-viewplus
> jest

 FAIL  test/util-funcs.test.js
  ● Test suite failed to run

    /Users/jiiiiiin/Documents/WebstormProjects/vue-viewplus/node_modules/vux/index.js:5
    import Actionsheet from './src/components/actionsheet/index.vue'
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/vp/util-funcs.js:1:324)
      at Object.<anonymous> (test/util-funcs.test.js:1:120)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.891s
Ran all test suites.
```
- 测试代码

```js
import {utilIs} from '../src/vp/util-funcs'

/* eslint-disable no-undef */
describe('util-funcs suite', () => {
  it('utilIs 测试常规类型检查', () => {
    expect(utilIs('String', 'abc')).toBe(true)
  })
})

```
- 待测试的代码，引入了vux，其实也可以不用，只是做一个示例：

```js
// ** 在这里引入的vux**
import { base64 } from 'vux'
import MixinPlugin from '../util/mixin-plugin'

export const modelName = 'util-funcs'

/**
 * 常用工具函数模块
 */
let plugin = {
  utilIs(type, val) {
    return Object.prototype.toString.call(val) === `[object ${type}]`
  },
  utilBase64Encode(plain) {
    return base64.encode(plain)
  },
  utilBase64Decode(cipher) {
    return base64.decode(cipher)
  }
}

export default plugin

export const install = function (Vue) {
  MixinPlugin.mixin(Vue, plugin, modelName)
}

```

**Comment by graysheeep** [comment]
babel配置问题 不是vux问题就关了

**Comment by airyland** [comment]
最好建个 repo 来看看。

**Comment by Jiiiiiin** [comment]
@airyland 以前没有建过repo，我新建了一个针对该问题的分支[问题报告](https://gitee.com/zhaojinos/vue-viewplus/tree/feature%2Fvux-repo/)

跑test脚本之后就可以重现：

![jietu20171206-150224](https://user-images.githubusercontent.com/8840636/33648831-955a4034-da96-11e7-8757-7bc605183a3f.jpg)

如果你有时间，麻烦帮忙看看，我们在一个银行app开发的项目重度使用vux，十分感谢你们的项目，也有一些代码想看看能不能贡献到项目中，比如：

- 针对【CellFormPreview】组件，我们扩展了一下属性

![jietu20171206-150852](https://user-images.githubusercontent.com/8840636/33649095-7aeab53e-da97-11e7-971b-4dca22e1e3e4.jpg)

**Comment by Jiiiiiin** [comment]
@airyland 目前我的做法是自己写了一个mock模拟vux就可以了，因为这个测试其实并不十分依赖vux，依赖vux的那部分，可以mock跳过，参考了[jest-localstorage-mock](https://www.npmjs.com/package/jest-localstorage-mock)的思路。

**Comment by Jiiiiiin** [comment]
暂时解决问题 ：）
[vue-viewplus 掩耳盗铃一下](https://gitee.com/zhaojinos/vue-viewplus/commit/0edc0bc6f356b6edb27d69540b0b96476a2766e6)

**Comment by airyland** [comment]
针对 cell-form-preview 的问题，其实可以在返回数据时做一个转换。selector 组件已经有这个配置，有时间可以来贡献，出于统一组件规范，这里的属性要使用 `value-map`。

   https://github.com/airyland/vux/blob/6baf7b22b7078f6119c1df9c74668f4044fa4003/src/components/selector/metas.yml#L56-L60

**Comment by Jiiiiiin** [comment]
@airyland 谢谢指点！

**Comment by wolfstark** [comment]
@Jiiiiiin 请问单元测试问题解决了，遇到同样的问题

**Comment by Jiiiiiin** [comment]
@wolfstark 自能自己mock vux的依赖代码，在执行对应的测试之前，或者手动将依赖从对应的vux源码中import进去，在执行测试用例之前，因为构建的原因我觉得，所以才会有vux-loader

**Comment by baixiaoyu2997** [comment]
@Jiiiiiin 

大佬有没有实例代码可以看看啊，英语不太好，实在没搞懂应该怎么mock，多谢

**Comment by smm5120** [comment]
同求详细一些回答，我也是遇到了一样的问题

**Comment by MiniArc** [comment]
google搜到这里来的，这个问题还是没一个暂时可行的方案吗？

**Comment by mice33** [comment]
一模一样的问题。。有解决方案了吗

**Comment by ariesjia** [comment]
jest.conf.js
```jsos
{
  .....
  transformIgnorePatterns: [
    "node_modules/(?!(vux)/)"
  ],
  setupFiles: ["xxxxxxx/setup.js"],
  .....
}
```

setup.js
```js
const Vue = require('vue')

Vue.config.productionTip = false

var noop = function() {}
if(!Vue.prototype.$t) {
  Vue.prototype.$t = noop
}

jest.mock('vux-xscroll/build/cmd/xscroll.js', () => {})
jest.mock('vux-xscroll/build/cmd/plugins/pulldown', () => {})
jest.mock('vux-xscroll/build/cmd/plugins/pullup', () => {})
```
