### ISSUE TITLE
Confirm 在IOS UC浏览器下 输入框依然难以获取焦点！！！

### ISSUE THREAD

**Issue by DaDaDaDaDaBocai** [airyland/vux#2266]
Confirm 在IOS UC浏览器下 输入框依然难以获取焦点！！！
V2.7.3 貌似没有把全部浏览器都修复

**Comment by airyland** [comment]
没有精力，UC 的问题不会作为主要问题去解决。

加多个感叹号只会影响维护者心情并不会让问题得到解决。欢迎来 PR，问题先关闭了。
