### ISSUE TITLE
Confirm 在IOS UC浏览器下 输入框依然难以获取焦点！ V2.7.3没有修复完，官网Demo 一样有问题

### ISSUE THREAD

**Issue by DaDaDaDaDaBocai** [airyland/vux#2267]
Confirm 在IOS UC浏览器下 输入框依然难以获取焦点！！！
V2.7.3 修复完依然存在问题

**Comment by airyland** [comment]
Duplicate of #2266 
上个 issue 回复你了，你还想发一条有意思？
