### ISSUE TITLE
【新手】怎么都找不到router写在哪，然后不知道transition怎么实现的。

### ISSUE THREAD

**Issue by tfciw** [airyland/vux#2268]

**Comment by tfciw** [comment]
transition 已经搞定，看的router的文档

**Comment by airyland** [comment]
router 看 vue-router 文档。demo 的 router 是有预处理的，不要参照 demo。

**Comment by tfciw** [comment]
好的，蟹蟹~，初学，捣鼓了demo一天了，有点慌了，文档都没看完，来问些白痴问题
