### ISSUE TITLE
关于 ViewBox 组件scrollTo指定位置的问题

### ISSUE THREAD

**Issue by Tyrone2333** [airyland/vux#2269]
我在`home`组件的`watch`里观察` $route `对象,当 从列表到具体文章时保存之前的滚动距离,当从文章退回列表跳转到之前的位置.我将滚动距离保存在`home`组件的`data`里(home是一个`view-box`嵌套`router-view`的组件).当我退回时使用`this.$refs.viewBox.scrollTo(this.states.scrollTop)`并不总是有效,经常都是回到顶部,请问这是怎么回事?
<pre>
`
        watch: {
            $route(to, from) {
                let scrBody = this.$refs.viewBox.getScrollBody()
                let scrTop = this.$refs.viewBox.getScrollTop()
//                从列表到具体文章时保存之前的滚动距离
                if (to.name == "read_article" && from.name == "article") {
                    console.warn("从列表到具体文章" + scrTop)
                    this.states.scrollTop = scrTop
                }
//                从文章退回列表跳转到之前的位置
                if (to.name == "article" && from.name == "read_article") {
                    console.warn("从文章退回列表 this.states.scrollTop: " + this.states.scrollTop)
                    this.$refs.viewBox.scrollTo(this.states.scrollTop)
                }
            },
        },
`
</pre>

**Comment by airyland** [comment]
问题应该不在于这个函数，而在于内容渲染，建议你 setTimeout 执行。

**Comment by Tyrone2333** [comment]
@airyland 是因为内容还没出来就滚动不到的原因?

**Comment by airyland** [comment]
目测是，你可以测试一下

**Comment by Tyrone2333** [comment]
@airyland setTimeout 延时`0`确实可以实现,但有个问题就是页面会一闪然后再到之前的位置

**Comment by airyland** [comment]
这个一闪的问题建议对内容使用 keep-alive，activated 时设定滚动距离。参考 demo，并不会出现一闪的问题。
