### ISSUE TITLE
建议给pannel组件增加slot

### ISSUE THREAD

**Issue by buliwangzhu** [airyland/vux#2270]
可以给pannel组件增加slot吗？想用他实现商城的商品列表功能

**Comment by airyland** [comment]
1.列表可以用 form-preview
2.提需求时请写清楚你想要什么 slot

**Comment by tangMr1234** [comment]
@airyland  希望能在panel里使用swipeout的功能

**Comment by airyland** [comment]
@tangMr1234 直接在 slot=body 区域写 swipeout。

**Comment by qianli8080** [comment]
希望多几个type样式，比如图片在右，内容在左
