### ISSUE TITLE
Vue warn: Method "_init" conflicts

### ISSUE THREAD

**Issue by hukaibaihu** [airyland/vux#2273]
![image](https://user-images.githubusercontent.com/9410341/33542062-0c8cf1ee-d897-11e7-9a89-037166d2dd54.png)

vux/src/components/previewer/index.vue, line 86:

![image](https://user-images.githubusercontent.com/9410341/33542098-3856bb98-d897-11e7-9ff5-092dd34cd5ee.png)

**Comment by airyland** [comment]
升级版本吧，这个问题很久前应该处理了。
