### ISSUE TITLE
XDialog点击关闭窗口的问题

### ISSUE THREAD

**Issue by kevinchung1026** [airyland/vux#2274]
关于XDialog点击关闭窗口的问题，pc端可以一次关闭，移动端需要点击两次才能关闭，我甚至两个属性同时写上，都不能实现点击一次，关闭窗口--- :show.sync="show"  v-model="show"，求解？

**Comment by airyland** [comment]
我相信你已经看到了 issue template 的说明并且故意忽略了它。
点击是点击什么元素，关闭逻辑是怎么操作，这些都不说明，代码不上，如何解决？

![image](https://user-images.githubusercontent.com/559179/33588411-4f50ee08-d938-11e7-947b-8902cf473189.png)
