### ISSUE TITLE
XAddress组件的地址数据源不兼容int类型

### ISSUE THREAD

**Issue by zhangli0625** [airyland/vux#2276]
今天用了XAddress组件，发现从服务端拉取的地址库中的parent字段和value字段都是int数字类型，在切换省市县的时候js报错，对照了ChineseData的数据结构，就是这两个字段的数据类型不同而已。能否兼容int类型的数据源呢？
从服务端拉取的data数据结构片段
`{name
:
"房山区",
parent
:
110100,
value
:
110111}`

报错的代码：
`this.$set(this.currentValue, i, list[0].value)`
报错提示：Uncaught TypeError: Cannot read property 'value' of undefined

**Comment by airyland** [comment]
进入底层 Picker 只能为 string，不限定字符意味着要兼容用户同时使用数字和字符串混合的情况，可能会引入更多问题，目前没有计划处理。你可以获取到数据后转换为字符串。
