### ISSUE TITLE
win10 npm install 报错

### ISSUE THREAD

**Issue by lajiaoge** [airyland/vux#2277]
E:\vue\vx10>npm install

> node-zopfli@2.0.2 install E:\vue\vx10\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.9.2 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

win10 的系统 每次 都是报这个错误

**Comment by airyland** [comment]
npm 问题和 VUX 无关，请到相关 repo 提问。

**Comment by DusuWen** [comment]
@lajiaoge 同样的问题
