### ISSUE TITLE
Alert component：设置按钮文字的属性为ButtonText not button-text

### ISSUE THREAD

**Issue by siyinglili** [airyland/vux#2278]

**Comment by airyland** [comment]
写清楚你遇到什么问题再重开 `当前` issue。

**Comment by siyinglili** [comment]
文档中设置按钮文字内容的属性名写错了，现在文档给的是button-text ，应该是ButtonText

2017-12-06 16:33 GMT+08:00 Airyland <notifications@github.com>:
