### ISSUE TITLE
Selector 组件在ios上有时会出现闪退现象

### ISSUE THREAD

**Issue by JJBreak** [airyland/vux#2281]
selector组件在ios中，点击组件后有时会出现    Selector的下拉框出现，但是马上又闪退。

**Comment by airyland** [comment]
没有重现过。如果你是在微信里，被微信安全提示影响，这个无法解决。如果是其他情况应该是系统的问题和组件无关，selector 也只是改了原生  select 的样式而已。

**Comment by yuf-git** [comment]
我使用"vux": "^2.9.2"也遇到了这个问题

**Comment by xiongtianci** [comment]
如果selector的value值是空的话IOS会有闪退现象
