### ISSUE TITLE
Checker 组件放在Tab中出现点击事件bug

### ISSUE THREAD

**Issue by JJBreak** [airyland/vux#2282]
把两个结构一样的checker放在不同的Tab中，第一个有on-item-click，第二个没有on-item-click事件。  
   切换到另一个Tab时，点击没有on-item-click事件的checker会触发前面一个on-item-click的事件。

![image](https://user-images.githubusercontent.com/33922798/33658814-f097dcf0-dab8-11e7-8751-68e9861278c9.png)
![image](https://user-images.githubusercontent.com/33922798/33658826-ff4dd858-dab8-11e7-97eb-3cf4caac360a.png)

第一个有事件，第二个没有定义事件，但是从第一个tab切换到第二个tab的时候点击checker-item就会触发前面tab中的事件。

**Comment by airyland** [comment]
为什么说代码问题不上代码，让维护者照你描述来写个 demo 帮重现？

**Comment by JJBreak** [comment]
<template>
	<div>
		<x-header :left-options="{showBack: true , backText: ''}">编辑</x-header>
		<div class="main-wrap-fb">
			<group>
				<div style="width: 100%;overflow:scroll;-webkit-overflow-scrolling:touch;">
					<tab v-model="workSelTabIndex" prevent-default @on-before-index-change="onItemClick">
						<tab-item>问题评定</tab-item>
						<tab-item>质量意见</tab-item>
					</tab>

				</div>
			</group>

			<template v-if="showTabContent1">

				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">严重故障</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model1">
							<checker-item value="1" @on-item-click="change">是</checker-item>
							<checker-item value="0" @on-item-click="change">否</checker-item>
						</checker>
					</div>
				</div>
				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">补发备件</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model2">
							<checker-item value="1" @on-item-click="change">是</checker-item>
							<checker-item value="0" @on-item-click="change">否</checker-item>
						</checker>
					</div>
				</div>
				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">是否直接关闭</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model3">
							<checker-item value="1" @on-item-click="change">是</checker-item>
							<checker-item value="0" @on-item-click="change">否</checker-item>
						</checker>
					</div>
				</div>
				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">产品类型</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo1-item" selected-item-class="demo2-item-selected" v-model="model4">
							<checker-item value="1" @on-item-click="change">自研</checker-item>
							<checker-item value="0" @on-item-click="change">外购</checker-item>
						</checker>
					</div>
				</div>

			</template>
			<template v-if="showTabContent2">

				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">是否同意安排备件</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model5">
							<checker-item value="1" disabled>是</checker-item>
							<checker-item value="0" disabled>否</checker-item>
						</checker>
					</div>
				</div>
				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">是否更换其他型号</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model6">
							<checker-item value="1" disabled>是</checker-item>
							<checker-item value="0" disabled>否</checker-item>
						</checker>
					</div>
				</div>
				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">是否回收</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model7">
							<checker-item value="1" disabled>是</checker-item>
							<checker-item value="0" disabled>否</checker-item>
						</checker>
					</div>
				</div>
			</template>

			</group>

		</div>
	</div>
</template>
<script>
	import { Toast, XHeader, Group, Cell, XInput, Selector, Datetime, XTextarea, Checker, CheckerItem, XButton, Popup, Search, Box, Tab, TabItem, FormPreview, Flexbox, FlexboxItem } from 'vux'

	export default {
		components: {
			Toast,
			XHeader,
			Group,
			Cell,
			XInput,
			Selector,
			Datetime,
			XTextarea,
			Checker,
			CheckerItem,
			XButton,
			Popup,
			Search,
			Box,
			Tab,
			TabItem,
			FormPreview,
			Flexbox,
			FlexboxItem
		},
		data() {
			return {
				model1: '',
				model2: '',
				model3: '',
				model4: '',
				model5: '',
				model6: '',
				model7: '',
				workSelTabIndex: 0,
				numToken: 0,
				projPlanList: [],
				popNode: '',
				projectNode: '',
				popLeft: false,
				showContent2: true,
				showPopup1: false,
				showPopup3: false,
				member1: '',
				member2: '',
				title: '硬件故障问题',
				showTabContent1: true,
				showTabContent2: false,
			}
		},

		methods: {
			change() {
				alert(1)
			},
			onItemClick(index) {
				this.$nextTick(() => {
					this.workSelTabIndex = index
				})
				if(index == '0') {
					this.showTabContent1 = true
					this.showTabContent2 = false
				} else if(index == '1') {
					this.showTabContent1 = false
					this.showTabContent2 = true
				}
			},

		},

	}
</script>

**Comment by JJBreak** [comment]
排版的头部
<template>
	<div>
		<x-header :left-options="{showBack: true , backText: ''}">编辑</x-header>
		<div class="main-wrap-fb">
			<group>
				<div style="width: 100%;overflow:scroll;-webkit-overflow-scrolling:touch;">
					<tab v-model="workSelTabIndex" prevent-default @on-before-index-change="onItemClick">
						<tab-item>问题评定</tab-item>
						<tab-item>质量意见</tab-item>
					</tab>

				</div>
			</group>

**Comment by JJBreak** [comment]
写的头部x-header 和 tab 组件 自动帮我编译了！  很尴尬

**Comment by airyland** [comment]
请先搜索一下 markdown 怎么写多行代码。

**Comment by JJBreak** [comment]
<template>
	<div>
		<x-header :left-options="{showBack: true , backText: ''}">编辑</x-header>
		<div class="main-wrap-fb">
			<group>
				<div style="width: 100%;overflow:scroll;-webkit-overflow-scrolling:touch;">
					<tab v-model="workSelTabIndex" prevent-default @on-before-index-change="onItemClick">
						<tab-item>问题评定</tab-item>
						<tab-item>质量意见</tab-item>
					</tab>

				</div>
			</group>

			<template v-if="showTabContent1">

				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">严重故障</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model1">
							<checker-item value="1" @on-item-click="change">是</checker-item>
							<checker-item value="0" @on-item-click="change">否</checker-item>
						</checker>
					</div>
				</div>
				

			</template>
			<template v-if="showTabContent2">

				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">是否同意安排备件</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model2">
							<checker-item value="1" disabled>是</checker-item>
							<checker-item value="0" disabled>否</checker-item>
						</checker>
					</div>
				</div>
				
			</template>

			</group>

		</div>
	</div>
</template>
<script>
	import { Toast, XHeader, Group, Cell, XInput, Selector, Datetime, XTextarea, Checker, CheckerItem, XButton, Popup, Search, Box, Tab, TabItem, FormPreview, Flexbox, FlexboxItem } from 'vux'

	export default {
		components: {
			Toast,XHeader,Group,Cell,XInput,Selector,Datetime,
			XTextarea,Checker,CheckerItem,XButton,Popup,Search,
			Box,Tab,TabItem,FormPreview,Flexbox,FlexboxItem
		},
		data() {
			return {
				model1: '',
				model2: '',
				workSelTabIndex: 0,
				showTabContent1: true,
				showTabContent2: false,
			}
		},

		methods: {
			change() {
				alert(1)
			},
			onItemClick(index) {
				this.$nextTick(() => {
					this.workSelTabIndex = index
				})
				if(index == '0') {
					this.showTabContent1 = true
					this.showTabContent2 = false
				} else if(index == '1') {
					this.showTabContent1 = false
					this.showTabContent2 = true
				}
			},

		},

	}
</script>

**Comment by airyland** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by JJBreak** [comment]
不会 ！ 我分两段写吧

<template>
	
		<div class="main-wrap-fb">
			<group>
				<div style="width: 100%;overflow:scroll;-webkit-overflow-scrolling:touch;">
					<tab v-model="workSelTabIndex" prevent-default @on-before-index-change="onItemClick">
						<tab-item>问题评定</tab-item>
						<tab-item>质量意见</tab-item>
					</tab>

				</div>
			</group>

			<template v-if="showTabContent1">

				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">严重故障</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model1">
							<checker-item value="1" @on-item-click="change">是</checker-item>
							<checker-item value="0" @on-item-click="change">否</checker-item>
						</checker>
					</div>
				</div>
				

			</template>
			<template v-if="showTabContent2">

				<div class="weui-cell">
					<div class="weui-cell__hd"></div>
					<div class="vux-cell-bd vux-cell-primary">
						<p><label class="vux-label">是否同意安排备件</label></p>
						<span class="vux-label-desc"></span>
					</div>
					<div class="weui-cell__ft">
						<checker default-item-class="demo2-item" selected-item-class="demo2-item-selected" v-model="model2">
							<checker-item value="1" disabled>是</checker-item>
							<checker-item value="0" disabled>否</checker-item>
						</checker>
					</div>
				</div>
				
			</template>

			</group>

		</div>
</template>

**Comment by JJBreak** [comment]
<script>
	import { Toast, XHeader, Group, Cell, XInput, Selector, Datetime, XTextarea, Checker, CheckerItem, XButton, Popup, Search, Box, Tab, TabItem, FormPreview, Flexbox, FlexboxItem } from 'vux'

	export default {
		components: {
			Toast,XHeader,Group,Cell,XInput,Selector,Datetime,
			XTextarea,Checker,CheckerItem,XButton,Popup,Search,
			Box,Tab,TabItem,FormPreview,Flexbox,FlexboxItem
		},
		data() {
			return {
				model1: '',
				model2: '',
				workSelTabIndex: 0,
				showTabContent1: true,
				showTabContent2: false,
			}
		},

		methods: {
			change() {
				alert(1)
			},
			onItemClick(index) {
				this.$nextTick(() => {
					this.workSelTabIndex = index
				})
				if(index == '0') {
					this.showTabContent1 = true
					this.showTabContent2 = false
				} else if(index == '1') {
					this.showTabContent1 = false
					this.showTabContent2 = true
				}
			},

		},

	}
</script>

**Comment by airyland** [comment]
链接都给你，你还是直接说不会，抱歉，你还是自行解决吧。

![image](https://user-images.githubusercontent.com/559179/33704621-cbc393f8-daf2-11e7-8427-45cd3582a9b7.png)
