### ISSUE TITLE
演示不能看了，是我打开的方式不对吗？？

### ISSUE THREAD

**Issue by Fury-Life** [airyland/vux#2283]
演示不能看了，是我打开的方式不对吗？？

cnpm install vux --save

// vue-cli 已安装

vue init airyland/vux2 vux

cd vux

cnpm install 

npm run dev

然后只看到首页 点击没反应

**Comment by doommm** [comment]
我这边访问[demo](https://vux.li/demos/v2/?x-page=v2-doc-home)也会报错

> GET https://static.vux.li/demos/v2/static/css/app.5fb4182f5201c0d7ddd3dd701bc4f679.css net::ERR_INSECURE_RESPONSE
GET https://static.vux.li/demos/v2/static/js/vendor.4aa99e717d5d340c54ec.js net::ERR_INSECURE_RESPONSE
GET https://static.vux.li/demos/v2/static/js/app.333de29e55901b202530.js net::ERR_INSECURE_RESPONSE

**Comment by ghost** [comment]
果然不止我一个人这样

**Comment by heeryuy** [comment]
证书过期了

**Comment by Fury-Life** [comment]
怎么解决？那个国内的大神给解释解释。怎么弄？关键是弄到本地也是不行啊
