### ISSUE TITLE
v0.1.0 发布说明

### ISSUE THREAD

**Issue by airyland** [airyland/vux#229]
## Hello world

经过3个多月的开发，v0.1.0终于发布了。

这个版本`并不意味着基本没有bug`，而是意味着`整个组件库的组件设计规范和编码规范已经清晰`，可以明确地自我规范及更方便社区同学根据规范来提交PR，已经开发的组件的命名、属性、事件等已经相对稳定，不会出现大的变更。重大变更只会在大版本进行。对于每一个更改也将会更加谨慎。

当然最重要的是，`文档终于发布了`。

`vux.li`注册了3个多月，域名的`let's encrypt`证书在昨天刚好过期。现在项目的进度比原预计的还比较远，首要原因是时间精力确实不够。待办清单中还有超过100个大大小小的优化或者需求。项目开始时，小心翼翼地在README里写了`Not Production ready`，现在看来确实是正确的做法，毕竟中途接口属性事件改了又改，至少减少了点负罪心理。在没有特意做推广(3个月前在v2ex发了个贴)的情况下，3个月自然增长达到了 1500 star，真是件让人高兴又压力巨大的事。

## 一些规范

比较重要的规范包括(其他在可以在文档发布后查看)

+ 事件命名前缀 `on-`
+ 组件命名：若与原生同名，使用 `x-*`, 若有子组件，使用`*-item`
+ css 前缀 `vux-`

另外还有发布节奏的确定：
+ 每周三发布一个小版本。除周三外发布的都是`rc`版本。

目前的开发是需求驱动的，包括公司内部需求及其他同学的反馈，相信还有很多场景下的问题还没有暴露出来，希望有任何问题都可以提出来一起解决。

然后要说件特别重要的事：

欢迎PR，提bug，提建议
欢迎PR，提bug，提建议
欢迎PR，提bug，提建议

## 维护一个开源项目

维护一个开源项目是件十分耗时间精力的事，处理issue是件烦人的事。当然关闭issue是件很愉悦的事，半天关闭几个issue也确实酸爽，但是一部分同学至今还没有学会如何正确提一个问题，不提供任何细节或者相当不清晰。这确实很恼人，于是写了`issue template`, 结果部分同学直接忽略它了，而还有部分同学写了个标题，然后template一行没删就提交了，我只能`WTF` 😓 。所以很多时候并不是开源作者在issue上处理(看起来)很强硬，而是被逼成了这样，大家时间有限，issue多时确实没有时间去猜你的问题是啥，所以也请不要因为问题不清晰被我忽略或者直接关闭不高兴。

当然还有部分用户提了个issue就跑了，而我在提问题后几分钟就回复希望提供点细节。所以我加了个标签叫`inactive issue will be closed`，大意就是即使`你提完就跑我还等了你3天所以我关掉了你也不能怪我啊`  😹 。

在其他项目下还可以看到部分用户把issue当成论坛了，为了表扬直接发个issue标题就叫`赞`。。还有部分用户因为发现了问题能直接骂**公司技术居然这么烂，所以觉得维护一个中文项目真的是挺累，可能一开始我们就被归入`(绝对比不上国外的)国产项目`的分类了。。所以我们一开始就注释文档国际化吧，有部分同学就会直接问了，英文看不懂，为啥没有中文文档啊，国人的项目竟然没有中文文档。。好了，吐槽完了。

## 近期及未来计划

即将支持的是：
+ `WeUI` 样式拆分到各个组件，不再需要全局引入vux.css
+ `x-form`目前只支持`x-input`,并且没有发布到v0.1.0里，将在v0.1.1扩展到所有表单类组件发布
+ `datetime` 支持配置开始结束时间
+ 文档增加组件使用场景说明
+ More Real-world examples

在计划中还未进行的包括：

+ `vux-playground` 类`jsfiddle`在线编辑器
+ `vux-babel-plugin` 更方便引入组件和样式的babel插件
+ 逐步更改`Vue2.0`中不再支持的方法属性
+ 每个组件单独发布到`npm`, 方便部分只使用了很少组件的同学

## 升级到v0.1.0

> 大更改在v0.0.115之后就进行了，v0.1.0主要是目录结构更改

### 目录

+ `components`目录由`components/`移到`dist/components`
+ `vux.js`及`vux.css`从根目录转移到`dist/`目录
+ 增加`dist/styles`目录，放置样式文件(暂为空)

### 文档

开发的时候一直想着先开发再写文档，导致了后面这么多组件根本没时间(不想)写文档。拉了部分同学帮忙一起写文档，强迫自己一定要在v0.1.0的时候写完文档。这委屈了很多同学只能看着`demo`源码写代码，实在是对不起啊。

## 感谢
感谢给我发过红包的各位土豪。
感谢发过PR提过issue的各位同学。

[lichunqiang](https://github.com/lichunqiang)
[graysheeep](https://github.com/graysheeep)
[fundon](https://github.com/fundon)
[Coffcer](https://github.com/Coffcer)
[donlzx](https://github.com/donlzx)
[blue5tar](https://github.com/blue5tar)
[unclay](https://github.com/unclay)
[tianyong90](https://github.com/tianyong90)
[flynntsc](https://github.com/flynntsc)
[iflamed](https://github.com/iflamed)
[waitfor9527](https://github.com/waitfor9527)
[maoqxxmm](https://github.com/maoqxxmm)

### 感谢开源项目

除了Vue 及 WeUI，组件部分代码及设计来自于以下开源项目或网站：

+ [FrozenUI](https://github.com/frozenui/frozenui)
+ [Ant Design](https://github.com/ant-design/ant-design)
+ Ant UI
+ [XScroll](https://github.com/huxiaoqi567/xscroll)
+ [Ionic](https://github.com/driftyco/ionic)
+ [SUI Mobile](https://github.com/sdc-alibaba/SUI-Mobile)
+ Spmjs.io (已下线)

## Donate

想支持鼓励的可以到README尾部找到coffee二维码 :) 

## Demo
[https://vux.li](https://vux.li)
![Vux](https://o3e85j0cv.qnssl.com/vux_qr_02.png)

**Comment by graysheeep** [comment]
Come on man! You are doing a great job!

**Comment by flynntsc** [comment]
Let's go on.

**Comment by lichunqiang** [comment]
keep moving!!!

**Comment by zhuewizz** [comment]
很期待你的文档，开源项目最重要的是文档

**Comment by DavidAlphaFox** [comment]
Come on man! You are doing a great job!
And I think vux is rellay a great UI library.

**Comment by xiaolongyuan** [comment]
哈哈  几点正式发布啊 准备升级了。。。

**Comment by julytian** [comment]
good job，guy! 期待文档说明

**Comment by ahonn** [comment]
good job : )

**Comment by Loyalsoldier** [comment]
建议尽快统一各个模块的 UI。

**Comment by airyland** [comment]
@Loyalsoldier  可以提下详细的建议

**Comment by liyufeng** [comment]
Good Job and thanks for your contribution.

**Comment by Jinjiang** [comment]
支持一下！

**Comment by graysheeep** [comment]
@Jinjiang 大神合影

**Comment by airyland** [comment]
@graysheeep 哈哈哈
@Jinjiang 合影留念一下

**Comment by xu6148152** [comment]
Great project, hoping it will be always maintained.

**Comment by fundon** [comment]
赞

**Comment by SkyeTang** [comment]
作者棒棒哒。我会长期关注的，真希望以后也能参与进来，尽一份力。

**Comment by stylehuan** [comment]
赞

**Comment by yizuierguo** [comment]
支持 最近正在用Vuejs开发，已经捐赠～
