### ISSUE TITLE
datetime 组件，设置compute-hours-function，弹出时小时值与绑定值不一致

### ISSUE THREAD

**Issue by koucxz** [airyland/vux#2296]
见[datetime演示页](https://vux.li/#/zh-CN/demos/datetime)
设置动态小时后，选择一个时间，再次打开小时为 0 ，而不是已选时间
![image](https://user-images.githubusercontent.com/24607191/33971319-d19809a6-e0b2-11e7-8f11-471a95e56e4e.png)
![image](https://user-images.githubusercontent.com/24607191/33971325-d71e0470-e0b2-11e7-8483-1a861f2baec2.png)

**Comment by koucxz** [comment]
小时选择00-09的值时可重现

**Comment by unclay** [comment]
下个版本修复
