### ISSUE TITLE
loading样式加载不正确，缺少demo中的class

### ISSUE THREAD

**Issue by kai-chan-cp** [airyland/vux#2297]
`<template>
  <div id="search">
      <div class="search_layout">
          <div class="se_qrcode"><i class="fa fa-camera"></i><p style="fontSize:12px;text-align:center" @click="qrcode">扫一扫</p></div>
          <input type="text" placeholder="输入商品编号或者防伪码流水号"/>
          <div class="se_btn">搜索</div>
          <loading  text="正在查询中" :show="loading" ></loading>
      </div>  
  </div>
</template>
<script>
import { Loading } from "vux";
export default {
  name:"search",
  data(){
    return{
      loading:true
    }
  },
  created(){
  },
  methods:{
    qrcode(){
        wx.scanQRCode({
            needResult: 1, // 默认为0，扫描结果由微信处理，1则直接返回扫描结果，
            scanType: ["qrCode","barCode"], // 可以指定扫二维码还是一维码，默认二者都有
            success: function (res) {
              var result = res.resultStr; // 当needResult 为 1 时，扫码返回的结果
              this.query(result.substring(44));
            }
        });
    },
    query(skucode){
        this.loading = true;
        this.$store.dispatch("queryCodeInfo",{skuCode,name:this.$store.state.name}).then(res=>{
          if(res.data.code==0){

          }else{
            this.loading = false;
          }
        }).cathc(err=>{
            this.loading = false;
        })
    }
  },
  components:{
    Loading
  }
}
</script>
<style scoped>
    .search_layout{
      overflow: hidden;
      color:#fff;
      background: #20a0ff;
      padding:.170667rem /* 10/58.5938 */ 0 .170667rem /* 10/58.5938 */ 0;
    }
    .search_layout div{
      float: left;
    }
    #search .se_qrcode{
        color:#d9d9d9;
        width: 14%;
        font-size:.341333rem /* 20/58.5938 */;
        height:  .512rem /* 30/58.5938 */;
        text-align: center;
    }
    #search input{
      float: left;
      height: .512rem /* 30/58.5938 */;
      outline: none;
      border:0px ;
      width: 70%;
      border-radius: 10px;
      padding-left: .1024rem /* 6/58.5938 */;
    }
    #search .se_btn{
        width: 14%;
        text-align: center;
        font-size: .273066rem /* 16/58.5938 */;
        height: .512rem /* 30/58.5938 */;
        line-height: .512rem /* 30/58.5938 */;
    }
    .fa-camera:before{
      line-height: .238933rem /* 14/58.5938 */;
    }
</style>`

**Comment by ckaiCp** [comment]
本来是格式化好的 代码，已提交就变样了，点击编辑应该是可以自动格式化好的。已经出现过两个这种情况了。第一次被莫名的调试好了，因为项目比较久远忘记怎么调试了。也可以能是我使用问题，希望能收到why，thanks

**Comment by airyland** [comment]
请先把代码格式好，markdown 里怎么写多行代码搜索一下就知道了。

缺少 demo 里的 class 是什么意思，哪个 class，加载不正确又是什么意思？

**Comment by kai-chan-cp** [comment]
判断错误吧,不是缺少class。loading组件布局采用了em布局，我这里采用了rem布局，导致父元素的font-size过大，样式错乱。@airland

**Comment by xsdlr** [comment]
@ckaiCp 
`.vux-loading {
    font-size: 16px;
  }`

**Comment by kufei88** [comment]
@xsdlr 谢谢你的答案
