### ISSUE TITLE
Previewer 当数据数组某一项的src值为空时bug

### ISSUE THREAD

**Issue by yuxianwen** [airyland/vux#2298]
我这边有一个业务场景是src为空的时候显示另外的东西，就是图片未上传时

显示的一个上传框 但是这个需要数组的src为空时做判断

当应用到 Previewer 因为有图片未上传数组的src肯定为空

这个时候bug就出现了 直接显示为空白没显示

而且这个时候点击空白处的时候会有报错，然后

一片黑，关不掉，只能刷新之

希望能优化调整一下，或者有解决方案

![_20171214153558](https://user-images.githubusercontent.com/10365081/33980596-8b54e9aa-e0e4-11e7-9536-e789335f51e2.png)

**Comment by airyland** [comment]
previewer 目的就是用来显示图片，不存在 src 的情况看起来没有处理的必要性，并没有计划支持在图片显示区域判断没有 src 时显示定义其他东西，这并不是常用场景。建议你直接指定一张提示图片。

**Comment by yuxianwen** [comment]
好吧，那只能暂时先指定一张没有图片时的图片了

关了。。。

**Comment by gy2986589** [comment]
动态获取的 图片 怎么设置这个插件
