### ISSUE TITLE
Actionsheet 使用 show-cancel 时 点击 cancel 报错

### ISSUE THREAD

**Issue by lynnnnnnnn** [airyland/vux#2299]
VM31055:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at VueComponent.emitEvent (437:70)

emitEvent (event, menu, item) {
      if (event === 'on-click-menu' && !/.noop/.test(menu)) {
        **console.log(typeof item) 为 undefined**
        this.$emit(event, menu, typeof item === 'string' ? item : JSON.parse(JSON.stringify(item)))
        this.$emit(`${event}-${menu}`)
        this.closeOnClickingMenu && (this.show = false)
      }
    },

**Comment by airyland** [comment]
请给出使用代码。看你上面发的并不能知道如何重现。

**Comment by JohnJiang900526** [comment]
这个问题我也遇到了，但是可以解决，点击取消，返回的key和item, key是cancel, item是undefined,
可以加个判断，如果item===undefined  return false, 这样就可以解决了！
