### ISSUE TITLE
datetimepicker初始化时日期和时间不是当前日期时间

### ISSUE THREAD

**Issue by Jeesoong** [airyland/vux#23]
![11](https://cloud.githubusercontent.com/assets/5194326/13627944/36e55670-e609-11e5-88af-3667110232ad.jpg)

问题如题如图，请问需要传初始化值吗？还有下午2点应该显示应显示为14点吧

**Comment by airyland** [comment]
Thanks. will fix it today.

**Comment by Jeesoong** [comment]
@airyland 3Q~
