### ISSUE TITLE
DatetimePlugins无法正常使用，已经定位到问题原因

### ISSUE THREAD

**Issue by lyh2668** [airyland/vux#2302]
[该Commits存在问题](https://github.com/airyland/vux/commit/6278a822789e40b2979273ef32502314699f5f76)
导致Datetime使用Plugin方式引入无法正常使用
具体问题见
- [Issues2249](https://github.com/airyland/vux/issues/2249)
- [Issues2226](https://github.com/airyland/vux/issues/2226)

删除的Datetime样式需要重新引入才能使DatetimePlugins正常使用
麻烦作者看一下在何处引入样式比较合适

**Comment by airyland** [comment]
should be already fixed.
