### ISSUE TITLE
scroller在图片列表情况下有时显示不全,最底部看不到

### ISSUE THREAD

**Issue by heiyun** [airyland/vux#2304]

**Comment by airyland** [comment]
![image](https://user-images.githubusercontent.com/559179/34031042-2efce15c-e135-11e7-86d3-5235fbdef16f.png)

**Comment by elina1201** [comment]
针对楼上的问题，我在scroller里面设置了height=“-100”，基本可以满足90%的手机匹配

**Comment by elina1201** [comment]
还有使用scroller做分页，并且逻辑里面还有tab切换效果时，当单页数据不满足每页展示的 总条数时，出现的下拉刷新等字样不好控制，我采用的方法：
                if(res.data.QueryResultTable.length < this.pageSize){
                    let oUndefined = document.getElementsByClassName('xs-plugin-pullup-container');
                    oUndefined[0].style.display="none";
                }else{
                    let oUndefined = document.getElementsByClassName('xs-plugin-pullup-container');
                    oUndefined[0].style.display="block";
                }
