### ISSUE TITLE
XImg 的offset貌似有问题

### ISSUE THREAD

**Issue by QThans** [airyland/vux#2309]
vue.esm.js?65d7:576 [Vue warn]: Invalid key "defaut" in validation rules object for prop "offset".
 报错如上

排查以后发现是ximg的问题  ximg去掉就不报错了。

**Comment by airyland** [comment]
目测有一个全局的验证属性和 ximg 属性冲突。自行排查其他插件问题。

**Comment by QThans** [comment]
打扰了  请问如何定位呢? 我搜索了一遍 没有找到其他的地方有offset
