### ISSUE TITLE
x-img为什么要在create时走一遍init，mounted时又走一遍

### ISSUE THREAD

**Issue by huangmin16** [airyland/vux#2314]

**Comment by lichunqiang** [comment]
历史原因。最早只是在`mounted`方法中执行`init`

但当存在路由过渡时立即执行init可能导致进入页面后不会正确加载图片的问题，所以引入了`delay`，但这不是最好的解决方案。

所以`2.5.4`之后引入了 `busPlugin`，由调用方来主动通知页面已经加载完成，从而执行`init`，这个版本之后推荐使用这种方式。

鉴于兼容性的问题，所以目前还是保留了原来的逻辑。
