### ISSUE TITLE
能否给一个tabbar的完整例子

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#232]
请问一下，如果我想所有大部分的应用页面都有一个tabbar，点击切换， 是不是每个页面都要放一个tabbar?

**Comment by airyland** [comment]
如果是用vue-router, 公用的tabbar放在router-view外面。

**Comment by hubinjie** [comment]
这样试过了，确实可以，需要将tabbar ,fixed 和底部，不过有一个问题是，如果router-view页面过长，滚动条会出现在tabbar右边

<scroller lock-x scrollbar-y>
    <router-view
      transition
      transition-mode="out-in"></router-view>
  </scroller>

router-view 内容就看不见了

**Comment by airyland** [comment]
不是很明白为什么router-view会不见。
