### ISSUE TITLE
Previewer 组件引用的 PhotoSwipe插件只会在图片全部下载完成后才会出现

### ISSUE THREAD

**Issue by mxq00812314** [airyland/vux#2321]
Previewer 组件引用的 PhotoSwipe插件会在图片全部下载完成后才会出现,  PhotoSwipe官方的插件, 会先打开插件,然后慢慢加载图片,  希望PhotoSwipe组件能先打开插件然后再加载图片

**Comment by airyland** [comment]
加载图片是因为没有设置宽高需要获取宽高，Previewer 是强制都需要预告设置宽高。你可以都设置宽高就可以避免加载再显示。
