### ISSUE TITLE
如何设置x-header的左侧按钮永远是drawer的呼出按钮

### ISSUE THREAD

**Issue by daiing** [airyland/vux#2323]
因为项目布局里，每页功能都是通过drawer里的菜单呼出，但是不需要返回，要换功能，都是通过再呼出菜单点击，怎么固定x-header的左侧按钮始终是drawer的呼出按钮？

**Comment by F-loat** [comment]
自己再封装一个组件，或者全局共用一个header都可以吧

**Comment by daiing** [comment]
我是全局公用一个xheader，但是好像左侧要么显示返回，要么就什么都不显示，希望能够自定义xheader的按钮啊，这样灵活多了

**Comment by Sapphire2k** [comment]
![image](https://user-images.githubusercontent.com/17328005/34348596-d122e192-ea46-11e7-8271-5f49611a672b.png)
这里的参数已经足够解决问题了吧？
如果你不想返回，设置阻止再自己自定义点击事件就OK了
