### ISSUE TITLE
x-header在ios上滑动消失问题

### ISSUE THREAD

**Issue by cinos1** [airyland/vux#2326]
使用x-header组件时，在pc浏览器中表现正常，但是在ios上，快速滑动时，header会消失
然而官方的demo没有这个问题，我仔细比较了代码，没找到区别，请指教，谢谢！
代码git地址：https://github.com/cinos1/vuxdemo.git
使用微信扫码后，标题在滑动时会消失

**Comment by Sapphire2k** [comment]
解决方案1:

请细看文档，

![image](https://user-images.githubusercontent.com/17328005/34316474-60d52eee-e7d1-11e7-9463-a3b7572c6690.png)

![image](https://user-images.githubusercontent.com/17328005/34316479-70f52810-e7d1-11e7-90e2-beb840eaa8d8.png)

解决方案2:

把XHeader移出ViewBox即可，

![image](https://user-images.githubusercontent.com/17328005/34316376-2baff7fa-e7cf-11e7-9c3a-2e9716e20351.png)
