### ISSUE TITLE
按说明生成umd文件，测试报错：Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by liu2010y** [airyland/vux#2327]
按官网https://vux.li/#/zh-CN/umd 生成umd文件，在项目中引入
页面使用代码片段：
>   ` <div id="demo"> ` 
>  `    <group> ` 
>   `     <cell title="Vue" :value="how"></cell> ` 
>   `   </group> ` 
>  `  </div> ` 
>   ` <script> ` 
>   ` Vue.component('group', vuxGroup) ` 
>   ` Vue.component('cell', vuxCell) ` 
>   ` new Vue({ ` 
>    `  el: '#demo', ` 
>    `  data: { ` 
>     `   how: 'Cool' ` 
>     ` } ` 
>  `  }) ` 
>   ` </script>` 

浏览器报错，错误信息：

> [Vue warn]: Failed to mount component: template or render function not defined.
> found in
> ` ---> <Group> `
>             ` <Root> `

**Comment by liu2010y** [comment]
不知道哪出问题了，求指导

**Comment by wg5945** [comment]
尽量使用webpack构建吧，umd形式的话会有很多未知错误

**Comment by cejpo001** [comment]
我也是碰到这个情况,请问你的这个问题解决了吗?

**Comment by liu2010y** [comment]
没，换框架了

在 2018-10-15 14:13:46，"cejpo001" <notifications@github.com> 写道：


我也是碰到这个情况,请问你的这个问题解决了吗?
