### ISSUE TITLE
xscroll 中内容替换后 Pullup 插件如何重置

### ISSUE THREAD

**Issue by bammoo** [airyland/vux#233]
### Version
0.0.118-rc3

### Android or iOS, which browser?
all

### Expected behavior
1、一个 list 页面用 xscroll 的 pullup 加载更多内容，没有更多时用事件或方法暂停 pullup 以使其不再响应手势。
2、当 xscroll 中的内容替换后，因为又有了加载更多内容的需要，调用事件或方法重启 pullup 让它重新响应手势。

### Actual behavior.
现在第 1 步是用 `pullup:done` 去掉 pullup。但是这样做不到第 2 步了。我看到 `pullup:done` 是直接 unplug 了 pullup 插件。

**Comment by bammoo** [comment]
因为项目用到，我现在是本地 hack 了一下：

### Scroller 组件的 events 添加

```js
'pullup:stop': function (uuid) {
  if (uuid === this.uuid) {
    this.pullup.stop()
  }
},
'pullup:restart': function (uuid) {
  if (uuid === this.uuid) {
    this.pullup && this.pullup.restart()
  }
}
```


### vue-xscroll pullup plugin.js 添加

```js
stop: function() {
  var self = this;
  var xscroll = self.xscroll;
  self.isLoading = false;
  self._changeStatus("stop");
  self.pluginDestructor()
  return self;
},
restart: function() {
  var self = this;
  var xscroll = self.xscroll;
  self.isLoading = false;
  self._changeStatus("default");
  self.render()
  return self;
}
```


如果可行，我可以提交 pr

**Comment by airyland** [comment]
@lichunqiang 似乎是你之前遇到的问题

**Comment by lichunqiang** [comment]
恩，确实这个是比较常见的场景。确实需要做处理，目前我的采取的是一个list只对应一个scroller，并只在初始化的情况下，判断是否卸载pullup，这样就把数据增多导致又需要上拉刷新给排除在外了，并不是很好。

@bammoo 我们可以先咨询下作者是否有处理办法，或者你提出的就是可行的

**Comment by airyland** [comment]
如果可行的话欢迎PR，然后在demo里加加个例子。

**Comment by bammoo** [comment]
@lichunqiang @airyland 好的。那就先等 xscroll 那边的作者反馈怎么处理再同步这边。

**Comment by jdfweb** [comment]
+1 on this!

**Comment by bammoo** [comment]
@airyland vux-xscroll 对应的 github repo 是哪个？我来 fork 一份修改吧。

**Comment by airyland** [comment]
@bammoo  https://github.com/vux-components/xscroll

**Comment by bammoo** [comment]
@airyland https://github.com/vux-components/xscroll/pull/1
