### ISSUE TITLE
<x-input autofocus="autofocus   "></ x-input>  控件的autofocus   在 Android  端无效 无法自动获取焦点

### ISSUE THREAD

**Issue by z575813129** [airyland/vux#2330]

**Comment by airyland** [comment]
x-input 并不支持所有原生 input 属性，所以并不能用 autofocus 属性。另一方面，移动端  autofocus 不同机型支持不一致，所以 x-input 组件不会做这个支持，如果有需要，copy x-input 源码进行修改。

**Comment by xiatouman** [comment]
为什么X-input 在移动端打开 需要点好几下才获取到焦点

**Comment by Mrcypress** [comment]
> 为什么X-input 在移动端打开 需要点好几下才获取到焦点

我在ios也遇到这个问题，Android倒是没有。 用focus方法ios也不能获取焦点。
