### ISSUE TITLE
vux生成模版后，npm i安装报错

### ISSUE THREAD

**Issue by Java-http** [airyland/vux#2339]
![image](https://user-images.githubusercontent.com/17530621/34335345-e98d599c-e988-11e7-9538-d976d831495d.png)
![image](https://user-images.githubusercontent.com/17530621/34335357-06879ecc-e989-11e7-90c9-6db52b400a5c.png)

win10，node v8.9.3 , npm v5.5.1,请问这是什么原因，求指导，谢谢！

**Comment by lichunqiang** [comment]
使用taobao源来安装试试。
```
npm install --registry=https://registry.npm.taobao.org
```
