### ISSUE TITLE
如何修改路由的跳转？

### ISSUE THREAD

**Issue by LiTao9410** [airyland/vux#2343]
我再router-view外层包了一个transition，如下
<transition :name="'vux-pop-' + (direction === 'forward' ? 'in' : 'out')" >
            <router-view class="router-view"></router-view>
</transition>
然后再css写如下：
.vux-pop-out-enter-active,
    .vux-pop-out-leave-active,
    .vux-pop-in-enter-active,
    .vux-pop-in-leave-active {
        will-change: transform;
        transition: all 500ms;
        width: 100%;
        height: 100%;
        top: 0;
        position: absolute;
        backface-visibility: hidden;
        perspective: 1000;
    }

    .vux-pop-out-enter {
        opacity: 0;
        transform: translate3d(-100%, 0, 0);
    }

    .vux-pop-out-leave-active {
        opacity: 0;
        transform: translate3d(100%, 0, 0);
    }

    .vux-pop-in-enter {
        opacity: 0;
        transform: translate3d(100%, 0, 0);
    }
用VUEX进行状态管理管理direction，
然后执行的时候direction改变了但是页面的跳转还是遵循 .vux-pop-in的，
看作者你的实例却可以实现平滑的页面跳转，想问下您是怎么做的？

**Comment by Sapphire2k** [comment]
👉[首页Demo](https://github.com/airyland/vux/blob/v2/src/App.vue)
