### ISSUE TITLE
x-input组件required为true时，is-type验证器信息错误bug

### ISSUE THREAD

**Issue by featnet** [airyland/vux#2346]
![image](https://user-images.githubusercontent.com/23646120/34357972-88c5bc2c-ea86-11e7-9f9b-97560ae56db0.png)
![image](https://user-images.githubusercontent.com/23646120/34357980-9972cefc-ea86-11e7-8c66-b2a9043027b8.png)

**先触发**required验证后，**再触发**is-type验证器时，验证不通过错误信息还是required的错误。

图2我是手动清空firstError就可以。

**Comment by wg5945** [comment]
和 #2348 是同一个问题，这个先关了
