### ISSUE TITLE
x-input required为true后 is-type验证提示信息错误

### ISSUE THREAD

**Issue by HEYEggplant** [airyland/vux#2348]
Vux UI version
^2.7.5

OS/Browsers version
win10

Vue version
^2.5.2

Reproduction
`
<x-input
        v-model="name"
        title="姓名"
        :required="true"
        :is-type="legalName"
        placeholder="请输入借款人姓名">
      </x-input>
`
`
legalName: (value) => {
          return {
            valid: nameReg.test(value),
            msg: '姓名格式错误'
          }
        }
`
Steps to reproduce

同时开启required验证和is-type验证

What is Expected?

当输入为空时，提示required验证错误提示
当输入不符合is-type验证时，错误提示信息应该更改为is-type的msg提示信息

What is actually happening?

当触发required验证后，再次触发is-type验证
提示错误信息msg仍为required验证的错误信息

**Comment by wg5945** [comment]
thx，下个版本修复
