### ISSUE TITLE
x-img 图片一直不能正常显示出来

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#235]
x-img 图片一直不能正常显示出来

**Comment by hugywin** [comment]
x-img图片一直不能正常显示的另一个问题。 vux-blazy ("version": "1.6.4") blazy.js 188行
if (!hasClass(ele, options.successClass) && (force || options.loadInvisible || (ele.offsetWidth > 0 && ele.offsetHeight > 0)))
!hasClass(ele, options.successClass) 这个条件不能成立, 大致读了下代码将hasClass 前面的非运算符去掉就可以了。 我知道我理解的是否正确
