### ISSUE TITLE
cell 里面的右箭头绘制，当经过rem转换之后，部分手机机型上下不对称

### ISSUE THREAD

**Issue by killdada** [airyland/vux#2350]
如图，
![qq 20171227175124](https://user-images.githubusercontent.com/16487810/34377947-84f14a8c-eb2e-11e7-9a27-45a617397f37.png)
![screenshot-1](https://user-images.githubusercontent.com/16487810/34377949-881722c2-eb2e-11e7-8dd5-c4ed89dc45bd.png)

**Comment by wg5945** [comment]
vux的样式基于weui，而weui本身就不支持rem，因此不建议将vux的组件转化为rem
