### ISSUE TITLE
npm run lint 之后进程不会自动退出

### ISSUE THREAD

**Issue by AlanWenhao** [airyland/vux#2351]
### 带来的问题
- 开发阶段执行 `npm run lint` 后短时间无法区分 `lint 完成？` or `正在lint？`
- 配置 pre-commit 时，eslint 不报错但是卡在当前进程，无法进行 commit

### 其他
或者是 pre-commit 有其他解决方案？:face_with_head_bandage:

**Comment by airyland** [comment]
eslint 和组件无关，如果你使用模板初始化，建议到相关 template 提问。

**Comment by MadratJerry** [comment]
``` javascript
  settings: {
    "import/resolver": {
      webpack: {
        config: "build/webpack.base.conf.js"
      }
    }
  },
```
试着注释掉eslintjs里的这段，目前发现是这段导致的

**Comment by AlanWenhao** [comment]
@crazymousethief 
是的，进程可以退出了，谢谢，这样看来可能是`eslint-import-resolver-webpack`？搞不懂。。。。
