### ISSUE TITLE
vux源代码clone后,将router改为history模式,运行在nginx下报错

### ISSUE THREAD

**Issue by lonelyleft** [airyland/vux#2353]
clone下源代码后仅在main.js文件下的第133行加入一行代码,现代码如下
`
const router = new VueRouter({
  mode: 'history',
  routes
})
`
然后命令行运行npm run bulid
结束后将/docs/demos/v2下的所有文件移动至nginx的html文件夹下
nginx配置如下
`
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       80;
        server_name  localhost;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
`
访问时,如果url的pathname只有一级或者没有,没有问题,但是假设有它有多级时,刷新页面将会报错
![image](https://user-images.githubusercontent.com/26218052/34397970-9246042a-ebb5-11e7-92f7-137c298a1141.png)
↑像这样的无论如何刷新都不会报错
![image](https://user-images.githubusercontent.com/26218052/34397987-b3a7b640-ebb5-11e7-9aa9-57990ca48982.png)
↑像这样的,在刷新前一切正常
![image](https://user-images.githubusercontent.com/26218052/34398001-ccbb533a-ebb5-11e7-85b2-ac3dcebf99cd.png)
↑刷新后
望解决

**Comment by airyland** [comment]
不负责解决 nginx 配置问题，相关配置搜索 vue-router 文档或者社区解决方案。
