### ISSUE TITLE
关于对话框多次展示，格式相同，内容不同问题

### ISSUE THREAD

**Issue by zhangjuanjuan01** [airyland/vux#2356]
你好，看了关于对话框的demo，发现每一行switch针对的confirm都是一个独立的，由于日常的开发中，我们经常根据逻辑来确定对话框显示的内容，比如：调接口成功会显示成功，调接口失败会提示错误信息，这种情况下，是如何来确定对话框和逻辑的关联的？是要提前为每一种情况绑定对话框吗？能否实现页面中只有一个confirm框，初始化的时候加载进去，后面去修改他的内容主要是body中的text内容，是通过自己操作dom来修改里面的内容吗？还是我们的插件有提供相关的参数设置？

**Comment by airyland** [comment]
用 ConfirmPlugin 调用。
如果你用组件形式，为什么要操作 dom，你把绑定 content 的数据修改不就动态修改提示内容了。

**Comment by zhangjuanjuan01** [comment]
我主要想实现的是这样，第一次调用的时候初始化把confirm加到当前的页面，然后后面的每次调用都是修改此confirm的元素。利用我们的组件需要进行额外的封装才能实现吗？还是通过某种调用方式可以实现？

**Comment by airyland** [comment]
为什么需要额外封装，你要修改内容就修改 content 区域绑定的 data。如果不明白，自行封装一个吧。
