### ISSUE TITLE
路由跳转后组件报错，需要重新刷新才会zhengc

### ISSUE THREAD

**Issue by fuyidaotang** [airyland/vux#2358]
从A页面路由跳转到B页面，B页面上有一个blur组件，跳转后blur组件不能正常运行，报错
vue.min.js:7 TypeError: Cannot read property '__ob__' of undefined
    at a.e.$destroy (vue.min.js:7)
    at destroy (vue.min.js:7)
    at m (vue.min.js:8)
    at m (vue.min.js:8)
    at a.__patch__ (vue.min.js:8)
    at a.e.$destroy (vue.min.js:7)
    at destroy (vue.min.js:7)
    at m (vue.min.js:8)
    at g (vue.min.js:8)
    at _ (vue.min.js:8)

还有一个swiper组件也是一样，A页面跳转到B页面的时候组件不能正常运行，一样的报错
我不是按照官网建议的那样加载组件
而是按照以下方式加载，就是为了避免打包文件太大

import Blur from 'vux/src/components/blur/index.vue'

import Swiper from 'vux/src/components/swiper/swiper.vue'
import SwiperItem from 'vux/src/components/swiper/swiper-item.vue'

以上两个问题都是刷新后就正常了，请帮我看下，谢谢！

**Comment by airyland** [comment]
无法重现，请帖  repo。

**Comment by fuyidaotang** [comment]
<template>
  <div class="shop_index">
    <div class="search">
      <input type="search" placeholder="搜索本店商品">
    </div>
    <swiper auto loop dots-position="center">
      <swiper-item :key="1"><a><img src="http://upload.hongdoujiao.com:8721/xiaotao//user/df52d163a3d8464cae41fa35ca909acc.jpg" alt=""></a></swiper-item>
      <swiper-item :key="2"><a><img src="http://upload.hongdoujiao.com:8721/xiaotao//user/df52d163a3d8464cae41fa35ca909acc.jpg" alt=""></a></swiper-item>
      <swiper-item :key="3"><a><img src="http://upload.hongdoujiao.com:8721/xiaotao//user/df52d163a3d8464cae41fa35ca909acc.jpg" alt=""></a></swiper-item>
      <swiper-item :key="4"><a><img src="http://upload.hongdoujiao.com:8721/xiaotao//user/df52d163a3d8464cae41fa35ca909acc.jpg" alt=""></a></swiper-item>
      <swiper-item :key="5"><a><img src="http://upload.hongdoujiao.com:8721/xiaotao//user/df52d163a3d8464cae41fa35ca909acc.jpg" alt=""></a></swiper-item>
    </swiper>
    <div class="bulletin">
      <div class="title"><img src="../../assets/images/announcement.png" alt=""></div>
      <div class="content"><marquee>今天星期四，回家看按电视，看到少林寺，想去试一试</marquee></div>
    </div>
    <div class="nav">
      <span class="active">全部</span>
      <span>最新</span>
      <span>热卖</span>
      <span>女鞋</span>
      <span>男鞋</span>
      <span>童鞋</span>
      <span>棉鞋</span>
      <span>皮鞋</span>
    </div>
    <list :list="shopList"></list>
    <tabbar>
      <tabbar-item>
        <img slot="icon" src="../../assets/images/home_fill.png">
        <span slot="label">首页</span>
      </tabbar-item>
      <tabbar-item>
        <img slot="icon" src="../../assets/images/talk.png">
        <span slot="label">豆友说</span>
      </tabbar-item>
      <tabbar-item>
        <img slot="icon" src="../../assets/images/live.png">
        <span slot="label">直播</span>
      </tabbar-item>
      <tabbar-item link="/my">
        <img slot="icon" src="../../assets/images/mine.png">
        <span slot="label">我的</span>
      </tabbar-item>
    </tabbar>
  </div>
</template>
<style lang="less" rel="stylesheet/less" type="text/less">
  @base:25rem;
  div.shop_index{
    width:100%;
    div.search{
      width:100%;
      background: #fff;
      position: fixed;
      top:0;
      text-align: center;
      height:45/@base;
      line-height:36/@base;
      z-index: 999;
      input{
        width:80%;
        height:30/@base;
        line-height:30/@base;
        background: none;
        border:1px solid #f1f1f1;
        border-radius:15/@base;
        text-align: center;
        outline: none;
      }
    }
    div.vux-slider{
      margin-top:45/@base;
      div.vux-swiper{
        height:200/@base!important;
        div.vux-swiper-item{
          a{
            display: block;
            width:100%;
            img{
              width:100%;
              height:100%;
            }
          }
        }
      }
      .vux-indicator{
        > a{
          .vux-icon-dot.active{
            background-color: #fff;
          }
        }
      }
    }
    div.bulletin{
      width:96%;
      height:18/@base;
      padding:11/@base 2%;
      background: #fff;
      display:box;
      display:-webkit-box;
      display:-moz-box;
      >div.content{
        box-flex:1;
        -moz-box-flex: 1;
        -webkit-box-flex: 1;
        marquee{
          width:100%;
          font-size: 14/@base;
          font-family: "PingFang SC";
          color:#333;
          display: block;
        }
      }
      div.title{
        width:71/@base;
        height:18/@base;
        line-height:18/@base;
        border-right:1px solid #f1f1f1;
        img {
          width:61/@base;
          height:14/@base;
          margin-top:2/@base;
          display: block;
        }
      }
    }
    div.nav{
      width:100%;
      white-space:nowrap;
      overflow-y: auto;
      background: #fff;
      margin:10/@base 0;
      height:40/@base;
      span.active{
        color:#ff3657;
      }
      span{
        padding:10/@base 8/@base;
        background: #fff;
        margin-right:10/@base;
        font-size: 14/@base;
        color:#888;
        font-family: "PingFang SC";
      }
    }
    div.shop_list{
      margin-bottom:56/@base;
      overflow: hidden;
    }
    div.weui-tabbar{
      a:first-child{
        p.weui-tabbar__label{
          span{
            color:#ff3657;
          }
        }
      }
    }
  }
</style>
<script>
  import Swiper from 'vux/src/components/swiper/swiper.vue'
  import SwiperItem from 'vux/src/components/swiper/swiper-item.vue'
  import Tabbar from 'vux/src/components/tabbar/tabbar.vue'
  import TabbarItem from 'vux/src/components/tabbar/tabbar-item.vue'
  import List from '../../components/shopList.vue'
  export default {
    components: {
      Swiper,
      SwiperItem,
      List,
      Tabbar,
      TabbarItem
    },
    data(){
      return {
        banners:[''],
        shopList:[1,2,3,4,5,6]
      }
    }
  }
</script>
/*******************************以上为A页面****************************************/
<template>
  <div :class="['shop_detail',{hidden:buyShow}]">
    <x-header @on-click-more="showMenus = true"
              style="background-color:transparent;"
    >
      <img slot="right" src="../../assets/images/shopping_cart_white.png" style="fill:#fff;position:relative;left:-3px;">
    </x-header>
    <swiper auto loop dots-position="center">
      <swiper-item :key="1"><a><img src="http://upload.hongdoujiao.com:8721/xiaotao//user/df52d163a3d8464cae41fa35ca909acc.jpg" alt=""></a></swiper-item>
      <swiper-item :key="2"><a><img src="http://upload.hongdoujiao.com:8721/xiaotao//user/df52d163a3d8464cae41fa35ca909acc.jpg" alt=""></a></swiper-item>
      <swiper-item :key="1"><a><img src="../../assets/images/1.png" alt=""></a></swiper-item>
      <swiper-item :key="1"><a><img src="../../assets/images/1.png" alt=""></a></swiper-item>
      <swiper-item :key="5"><a><img src="http://upload.hongdoujiao.com:8721/xiaotao//user/df52d163a3d8464cae41fa35ca909acc.jpg" alt=""></a></swiper-item>
    </swiper>
    <div class="pro_header">
      <p class="name">2017春季新款女装 潮流女装 明星同款 巴黎时装周高定</p>
      <p class="price">￥1999.00</p>
      <div class="text">
        <span>运费：10.00</span><span>销量：25682件</span><span>库存：32652件</span>
      </div>
      <div class="tips">
        <span><img src="../../assets/images/shitidian.png" alt="">实体店认证</span><span><img src="../../assets/images/geren.png" alt="">实名认证</span>
      </div>
    </div>
    <tab active-color="#ff3657" bar-active-color="#ff3657">
      <tab-item @on-item-click="navChange" active-class="active" selected>商品详情</tab-item>
      <tab-item @on-item-click="navChange" active-class="active">用户评论</tab-item>
    </tab>
    <div class="pro_detail" v-show="active==0">
      <p>
        Chictopia的设计风格优雅而前卫，注重服装设计的原创精
        神。设计师将复古元素和现代简约设计巧妙的结合在一起，
        创造出一种精致并且经典的设计风格。设计师认为面料是
        影响服装设计的关键所在，因此对面料的运用有着独特的
        见解，而每一季由设计师亲自操刀设计的另类印花面料，
        更是品牌的一大特点，令Chictopia的设计在众多时装品牌
        中显得独一无二。
      </p>
      <img src="../../assets/images/2.png" alt="">
    </div>
    <div class="pro_star" v-show="active==1">
      <div class="all">
        <span>商品得分</span>
        <img src="../../assets/images/heart_red.png" alt="">
        <img src="../../assets/images/heart_red.png" alt="">
        <img src="../../assets/images/heart_red.png" alt="">
        <img src="../../assets/images/heart_red.png" alt="">
        <img src="../../assets/images/heart_gray.png" alt="">
        <span>4.0分</span>
      </div>
      <ul class="comment_list">
        <li>
          <div class="left">
            <img src="../../assets/images/3.png" alt="">
          </div>
          <div class="right">
            <div class="head">
              <span class="name">Mis Emma</span>
              <span class="start">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
              </span>
            </div>
            <p class="time">2016-12-10 16:00:00</p>
            <p class="content">超喜欢刘清扬设计的Chictopia，年轻时尚，非常适合现在的年轻人，个性不张扬，个性不张扬。</p>
          </div>
        </li>
        <li>
          <div class="left">
            <img src="../../assets/images/3.png" alt="">
          </div>
          <div class="right">
            <div class="head">
              <span class="name">Mis Emma</span>
              <span class="start">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
              </span>
            </div>
            <p class="time">2016-12-10 16:00:00</p>
            <p class="content">超喜欢刘清扬设计的Chictopia，年轻时尚，非常适合现在的年轻人，个性不张扬，个性不张扬。</p>
          </div>
        </li>
        <li>
        <div class="left">
          <img src="../../assets/images/3.png" alt="">
        </div>
        <div class="right">
          <div class="head">
            <span class="name">Mis Emma</span>
            <span class="start">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
                <img src="../../assets/images/heart_red.png" alt="">
              </span>
          </div>
          <p class="time">2016-12-10 16:00:00</p>
          <p class="content">超喜欢刘清扬设计的Chictopia，年轻时尚，非常适合现在的年轻人，个性不张扬，个性不张扬。</p>
        </div>
      </li>
      </ul>
    </div>
    <p class="title">其他商品(21)</p>
    <ul class="other_list">
      <li @click="routerDetail()">
        <div class="top"><img src="../../assets/images/3.png" alt=""><p class="num">已售85545</p></div>
        <div class="content">
          <p class="name">火爆朋友圈的小盒包 彩虹糖色 美国直邮</p>
          <p class="price">￥1699.00</p>
        </div>
      </li>
    </ul>
    <div class="btn">
      <button class="car" @click="goType='car';buyShow=true;">加入购物车</button>
      <button class="buy" @click="goType='buy';buyShow=true;">立即购买</button>
    </div>
    <popup v-model="buyShow" height="350px">
      <div class="buy_box">
        <p class="title">规格和数量</p>
        <div class="pro_box">
          <div class="left"><img src="../../assets/images/2.png" alt=""></div>
          <div class="content">
            <p class="name">BABYHOST 玩味个性 2017春夏纽约时装秀 柠檬黄高定女裙</p>
            <p class="num">库存 12034 件</p>
            <p class="price">￥1990.00</p>
          </div>
        </div>
        <div class="sku_box">
          <p class="title">颜色</p>
          <checker v-model="sku1" type="radio" selected-item-class="action_item">
            <checker-item value="1">黄色</checker-item>
            <checker-item value="2">黑色</checker-item>
            <checker-item value="3">白色</checker-item>
            <checker-item value="4">红色</checker-item>
            <checker-item value="5">紫色</checker-item>
          </checker>
          <p class="title">尺寸</p>
          <checker v-model="sku2" type="radio" selected-item-class="action_item">
            <checker-item value="1">S</checker-item>
            <checker-item value="2">M</checker-item>
            <checker-item value="3">L</checker-item>
            <checker-item value="4">XL</checker-item>
            <checker-item value="5">XXL</checker-item>
          </checker>
          <p class="title">数量</p>
          <x-number v-model="proNum" :min="1" :max="10" width="100px" align="left" @on-change="changeNum"></x-number>
        </div>
        <button class="buy_btn" v-if="goType=='buy'" @click="goBuy()">确认购买</button>
        <button class="car_btn" v-else>加入购物车</button>
      </div>
    </popup>
  </div>
</template>
<script>
  import Swiper from 'vux/src/components/swiper/swiper.vue'
  import SwiperItem from 'vux/src/components/swiper/swiper-item.vue'
  import XHeader from 'vux/src/components/x-header/index.vue'
  import Tab from 'vux/src/components/tab/tab.vue'
  import TabItem from 'vux/src/components/tab/tab-item.vue'
  import Popup from 'vux/src/components/popup/index.vue'
  import Checker from 'vux/src/components/checker/checker.vue'
  import CheckerItem from 'vux/src/components/checker/checker-item.vue'
  import XNumber from 'vux/src/components/x-number/index.vue'
  export default{
    data(){
      return {
        active:0,
        buyShow:false,
        sku1:'',
        sku2:'',
        proNum:1
      }
    },
    watch:{
      '$route':'getOtherDetail'
    },
    methods:{
      goBuy(){
        if(this.sku1!=='' && this.sku2!==''){
          this.$router.push({name:'actionOrder'});
        }else{
          this.$vux.toast.show({
            text: '请选择正确的规格',
            type:'text'
          })
        }
      },
      changeNum(num){
        console.log(num)
      },
      navChange(index){
        console.log(index)
        this.active=index;
      },
      getOtherDetail(){
        document.documentElement.scrollTop = document.body.scrollTop =0;
      },
      routerDetail(){
        this.$router.push({name:'shopDetail',query:{type:'1'}})
      }
    },
    components: {
      Swiper,
      SwiperItem,
      XHeader,
      Tab,
      TabItem,
      Popup,
      Checker,
      CheckerItem,
      XNumber
    },
  }
</script>
<style lang="less" rel="stylesheet/less" type="text/less">
  @base:25rem;
  div.hidden{
    overflow: hidden;
  }
  div.shop_detail{
    div.vux-slider{
      margin-top:-40/@base;
      div.vux-swiper{
        height:560/@base!important;
        div.vux-swiper-item{
          a{
            display: table;
            width:100%;
            line-height:560/@base;
            img{
              width:100%;
              vertical-align: middle;
            }
          }
        }
      }
    }
    div.vux-header{
      div.vux-header-left{
        color:#fff;
        a.vux-header-back{
          color:#fff;
        }
        div.left-arrow:before{
          border-color:#fff;
        }
      }
    }
    div.pro_header{
      width:96%;
      padding:2% 2% 0 2% ;
      background: #fff;
      margin-bottom:18/@base;
      div.tips{
        line-height:27/@base;
        padding:6/@base 0;
        span{
          margin-right:30/@base;
          font-family: PingFang-SC-Medium;
          font-size: 13/@base;
          color: #888888;
          img{
            width:12/@base;
            margin-right:10/@base;
            margin-top:-2/@base;
            vertical-align: middle;
          }
        }
      }
      p,span{
        font-family: PingFang-SC-Medium;
      }
      span{
        padding:6/@base;
      }
      p{
        font-size: 18/@base;
        line-height: 27/@base;
        padding:6/@base 0;
      }
      p.name{
        width:100%;
        color: #323232;
      }
      p.price{
        color: #ff3657;
      }
      div.text{
        border-top:1px solid #f1f1f1;
        border-bottom:1px solid #f1f1f1;
        display:box;
        display:-webkit-box;
        display:-moz-box;
        span{
          display: block;
          box-flex:1;
          -moz-box-flex:1;
          -webkit-box-flex: 1;
          font-size: 13/@base;
          line-height: 27/@base;
          color: #888888;
        }
      }
    }
    div.vux-tab {
      div.vux-tab-item{
        font-size: 14/@base;
      }
    }
    div.pro_detail{
      padding:20/@base 25/@base;
      background: #fff;
      font-size: 14/@base;
      img{
        max-width: 100%;
      }
    }
    div.pro_star{
      padding:14/@base;
      background: #fff;
      div.all{
        padding:18/@base 0;
        border-bottom:1px solid #f1f1f1;
        span{
          font-family: PingFang-SC-Medium;
          vertical-align: middle;
        }
        img{
          width:18/@base;
          vertical-align: middle;
        }
        span:first-child{
          font-size: 17/@base;
          margin-right:10/@base;
          color: #323232;
        }
        span:last-child{
          font-size: 14/@base;
          color: #888888;
          margin-left:10/@base;
        }
      }
      ul.comment_list{
        width:100%;
        li{
          padding:20/@base 10/@base 18/@base 14/@base;
          background-color: #fff;
          display: box;
          display:-webkit-box;
          display:-moz-box;
          border-bottom:1px solid #f1f1f1;
          div.left{
            width:40/@base;
            margin-right:10/@base;
            img{
              width:100%;
              height:40/@base;
              border-radius: 50%;
            }
          }
          div.right{
            box-flex:1;
            -webkit-box-flex: 1;
            -moz-box-flex: 1;
            div.head{
              overflow: hidden;
              margin-top:2/@base;
              span.name{
                float:left;
                font-family: PingFang-SC-Medium;
                font-size: 14/@base;
                color: #323232;
              }
              span.start{
                float:right;
                margin-top:-10/@base;
                img{
                  width:14/@base;
                }
              }
            }
            p.time{
              font-family: PingFang-SC-Medium;
              font-size: 12/@base;
              color: #888888;
            }
            p.content{
              font-family: PingFang-SC-Medium;
              font-size: 14/@base;
              line-height: 20/@base;
              color: #323232;
              margin-top:8/@base;
            }
          }
        }
      }
    }
    >p.title{
      width:92%;
      margin-top:10/@base;
      padding:12/@base 4%;
      font-family: PingFang-SC-Medium;
      font-size: 16/@base;
      color: #323232;
      background-color: #fff;
      border-bottom:1px solid #f1f1f1;
    }
    ul.other_list{
      padding:20/@base 14/@base;
      background-color: #fff;
      overflow: hidden;
      margin-bottom:45/@base;
      li{
        width:170/@base;
        div.top{
          width:100%;
          height:170/@base;
          border-radius: 6/@base 6/@base 0 0;
          overflow: hidden;
          position: relative;
          p.num{
            position: absolute;
            bottom:10/@base;
            width:82/@base;
            height:24/@base;
            left:0;
            background-image: url(../../assets/images/num_bg.png);
            background-size: 100% 100%;
            font-family: PingFang-SC-Medium;
            font-size: 12/@base;
            line-height: 24/@base;
            text-align: center;
            color: #ffffff;
          }
          img{
            width:100%;
            height:100%;
            vertical-align: bottom;
          }
        }
        div.content{
          width:100%;
          background-color: #f1f1f1;
          border-radius: 0 0 6/@base 6/@base;
          overflow: hidden;
          p.name{
            padding:10/@base 10/@base 0 10/@base;
            font-family: PingFang-SC-Medium;
            font-size: 12/@base;
            line-height:18/@base;
            color: #323232;
          }
          p.price{
            float:right;
            margin-right:10/@base;
            font-family: PingFang-SC-Medium;
            font-size: 15/@base;
            line-height: 18/@base;
            color: #ff3657;
            margin-bottom:10/@base;
          }
        }
      }
      li:nth-child(odd){
        float:left;
      }
      li:nth-child(even){
        float:right;
      }
    }
    div.btn{
      position: fixed;
      bottom:0;
      width:100%;
      display:box;
      display:-webkit-box;
      display:-moz-box;
      button{
        color:#fff;
        box-flex:1;
        -moz-box-flex: 1;
        -webkit-box-flex: 1;
        height:45/@base;
        display: block;
        border:none;
        outline:none;
      }
      button.car{
        background-color: #fc6f86;
      }
      button.buy{
        background-color: #ff3657;
      }
    }
    div.vux-popup-dialog{
      background-color:#fff;
      div.buy_box{
        p.title{
          width:96%;
          padding:16/@base 2%;
          font-family: PingFang-SC-Medium;
          font-size: 14/@base;
          color: #323232;
          border-bottom:1px solid #f1f1f1;
        }
        div.pro_box{
          display:box;
          display:-webkit-box;
          display:-moz-box;
          padding:10/@base 14/@base;
          div.left{
            width:90/@base;
            height:90/@base;
            margin-right:10/@base;
            img{
              width:100%;
              height:100%;
            }
          }
          div.content{
            box-flex:1;
            -webkit-box-flex: 1;
            -moz-box-flex: 1;
            p.name{
              font-family: PingFang-SC-Medium;
              font-size: 14/@base;
              line-height: 22/@base;
              margin-bottom:5/@base;
              color: #323232;
            }
            p.num{
              font-family: PingFang-SC-Medium;
              font-size: 12/@base;
              color: #888888;
              margin-bottom:5/@base;
            }
            p.price{
              font-family: PingFang-SC-Medium;
              font-size: 18/@base;
              color: #ff3657;
            }
          }
        }
        div.sku_box{
          p.title{
            font-family: PingFang-SC-Medium;
            font-size: 12/@base;
            color: #888888;
            padding:4/@base 14/@base;
            border:none;
            width:50%;
          }
          div.vux-checker-box{
            padding:0 14/@base;
            margin-bottom:10/@base;
            div.vux-checker-item{
              padding:7/@base 10/@base;
              font-family: PingFang-SC-Medium;
              font-size: 14/@base;
              color: #323232;
              border:1px solid #000;
              border-radius: 4/@base;
              margin-right:10/@base;
              margin-bottom:10/@base;
            }
            div.vux-checker-item.action_item{
              color:#fff;
              background-color: #ff3657;
              border:1px solid #ff3657;
            }
          }
        }
        div.weui-cell{
          .vux-number-selector svg{
            fill:#ff3657;
          }
          .vux-number-selector.vux-number-disabled svg{
            fill:#ccc;
          }
        }
        div.weui-cell:before{
          border:none;
        }
        >button{
          display: block;
          width:80%;
          margin:20/@base auto;
          height:45/@base;
          color:#fff;
          background-color: #ff3657;
          border-radius: 22.5/@base;
          border:none;
          outline:none;
        }
      }
    }
  }
</style>
/**************************************以上为B页面*******************************/

**Comment by fuyidaotang** [comment]
https://github.com/fuyidaotang/test/tree/dev/newMobile/src/view/product

**Comment by fuyidaotang** [comment]
已解决，谢谢

**Comment by yayunfeng** [comment]
怎么解决的那
