### ISSUE TITLE
BusPlugin没有挂载到this上

### ISSUE THREAD

**Issue by fsx950223** [airyland/vux#2361]
``` js
import { BusPlugin } from 'vux'
Vue.use(BusPlugin)
console.log(this.$vux)//undefined
```
结果是$vux未挂载

**Comment by lichunqiang** [comment]
```
console.log(this.$vux)//undefined
```
在什么位置调用的？  `this` 这个是？

**Comment by airyland** [comment]
this 是 vm，怎么可能在 window 全局有个 this.$vux 呢，你非要这样调用就用 Vue.$vux 吧。

**Comment by fsx950223** [comment]
代码中连prototype都没挂上，this能调用到？？

**Comment by fsx950223** [comment]
你们就这么处理问题的？？

**Comment by lichunqiang** [comment]
@fsx950223 您先别生气，静下心来，回答下我的问题。

**Comment by fsx950223** [comment]
this实在SFC里调用的

**Comment by lichunqiang** [comment]
恕我才疏学浅，`SFC` 是个啥。。

**Comment by fsx950223** [comment]
你给我说说你写在Vue上，this怎么调用，别人就一定会引用其他plugin是吧

**Comment by lichunqiang** [comment]
> this 是 vm，怎么可能在 window 全局有个 this.$vux 呢，你非要这样调用就用 Vue.$vux 吧

这个解释您看了吗

**Comment by fsx950223** [comment]
我说了this是在.vue里调用的 ok??

**Comment by fsx950223** [comment]
SFC:single file component

**Comment by fsx950223** [comment]
vue官网上有

**Comment by lichunqiang** [comment]
受教了，但是你的挂在了prototype上了，你的代码就出来了吗

**Comment by fsx950223** [comment]
是啊 如果只调用busplugin 之前会爆$vux undefined

**Comment by lichunqiang** [comment]
```
<template>
  <div>hello {{name}}</div>
</template>
<script>
import Vue from 'vue'
import { BusPlugin } from 'vux'

Vue.use(BusPlugin)

console.log(this.$vux)

export default {
  data () {
    return {
      name: 'test'
    }
  },
  mounted: function () {
    console.log(this.$vux)
  }
}
</script>
```
这是测试代码，但还是undefined

**Comment by fsx950223** [comment]
我刚提了个pr被关了 里面有解决

**Comment by lichunqiang** [comment]
就是用了你的代码

**Comment by fsx950223** [comment]
哦 既然你也发现问题那么你们自己解决吧

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Pixel 发送_

**Comment by airyland** [comment]
代码一开始就不挂完整就别来责骂了。pr 也不是正确的处理方式，vux 插件使用的是 mixin 方式。
影响您情绪，请您慢走。
