### ISSUE TITLE
.weui-tabbar__item.weui-bar__item_on .weui-tabbar__label颜色值

### ISSUE THREAD

**Issue by Samsara0329** [airyland/vux#2364]
想更换想要的颜色值，#1296DB，但是文档颜色配置vriable.less没有tabbar_label的颜色可选，求赐教，颜色配置文档已详细读完，依然找不到解决方案，谢谢。

**Comment by Samsara0329** [comment]
.weui-bar__item_on{
    p.weui-tabbar__label{
        span{

            color: $main_blue !important;
        }
    }
}
已通过此方法解决，若作者有更好办法，有空可以指出下，谢谢

**Comment by lichunqiang** [comment]
有吧。`tabbar-text-active-color`

https://github.com/airyland/vux/blob/v2/src/styles/variable.less#L24

**Comment by Samsara0329** [comment]
没有我想要的颜色，如果引用的话，是直接@tabbar-text-active-color么

**Comment by lichunqiang** [comment]
https://vux.li/#/zh-CN/README?id=%E9%A2%9C%E8%89%B2%E9%85%8D%E7%BD%AE

**Comment by yuiopt** [comment]
貌似都是问这个激活时的颜色设置，@tabbar-text-active-color，激活时的颜色可以设置，请问未激活时的颜色如何设置？另外，这种颜色设置都是全局生效，如果想只在当前vue文件生效如何处理？
