### ISSUE TITLE
sticky组件Bug修复建议

### ISSUE THREAD

**Issue by dongj0316** [airyland/vux#2365]
项目中有2个keep-alive的页面使用了sticky（超过2个没测过），问题在安卓下，history模式，页面跳转滚动处理scrollBehavior: () => ({ y: 0 })

**1**、在第一个页面滚动触发sticky效果后，切换到第二个页面（有sticky）再切回来，这时候class名vux-fixed依然存在

![image](https://raw.githubusercontent.com/dongj0316/issues/master/images/index-bug1.png)

这是正常的效果

![image](https://raw.githubusercontent.com/dongj0316/issues/master/images/index.png)

**2**、这时候刷新一下，切换到第二个页面滚动触发fixed效果，然后切到第一个页面滚动，发现不能触发sticky的效果了

![image](https://raw.githubusercontent.com/dongj0316/issues/master/images/index-bug2.png)

然后我对源码做了如下更改
https://github.com/airyland/vux/blob/fdc71bcd481f71ee48880ac5b92b140b4e6a6a5a/src/components/sticky/sticky.js#L48

`if (distance > navOffsetY) {`

https://github.com/airyland/vux/blob/fdc71bcd481f71ee48880ac5b92b140b4e6a6a5a/src/components/sticky/sticky.js#L61

```
if (nav.classList.contains('vux-fixed')) {
  // 问题1的情况
  const top = getTop()
  // 因为这时候nav元素是fixed定位状态，获取外围撑高度的div的offsetTop
  navOffsetY = document.querySelector('.sticky-fill').offsetTop - offset
  // 判断是否需要移除vux-fixed类名
  if (top < navOffsetY) {
    nav.classList.remove('vux-fixed')
  }
} else {
  navOffsetY = nav.offsetTop - offset
}
scrollBox.e = scrollHandler
scrollBox.addEventListener('scroll', scrollHandler)
```

https://github.com/airyland/vux/blob/fdc71bcd481f71ee48880ac5b92b140b4e6a6a5a/src/components/sticky/index.vue#L11

```
data () {
  return {
    initTimes: 0
  }
}
```

https://github.com/airyland/vux/blob/fdc71bcd481f71ee48880ac5b92b140b4e6a6a5a/src/components/sticky/index.vue#L14

```
activated () {
  // 第一次触发created钩子时不执行
  if (this.initTimes > 0) {
    this.bindSticky()
  }
  this.initTimes++
}
```

然后我的问题解决了

**Comment by lichunqiang** [comment]
可以PR
