### ISSUE TITLE
checker和xinput怎么一起组合？

### ISSUE THREAD

**Issue by daiing** [airyland/vux#2369]
xinput都是有标题的，checker没有标题，放在一起很违和啊？请问checker和input一起的界面，如何组合才整齐一点？

**Comment by wg5945** [comment]
1、首页demo里面，cell组件有个折叠的效果，可以把checker放里面
2、使用popup-picker替代

**Comment by daiing** [comment]
这都不算好的解决方案，既然开发出这个控件，那不如完善一下，能和form表单的其他组件能组合在一起，否则用处不大了吗？

**Comment by wg5945** [comment]
好吧，水平有限，如果您有好的解决方案的，欢迎pr
