### ISSUE TITLE
XAddress 组件有一条多余的上边线

### ISSUE THREAD

**Issue by hooraygith** [airyland/vux#2371]
如图所示：

![20180103191548](https://user-images.githubusercontent.com/11362506/34518531-b3905c2a-f0ba-11e7-9ca4-8d5cd989d091.png)

当在 XAddress 组件是 Group 组件的第一的子组件时，应该没有边线

**Comment by wg5945** [comment]
你指的是.vux-cell-box:before这个样式么，观察很细致

**Comment by hooraygith** [comment]
就是.vux-cell-box:before这个样式。

这样修改不够吧，vux-cell-box 外层还有个空div：

![20180104095842](https://user-images.githubusercontent.com/11362506/34547878-38935b74-f139-11e7-8dc9-1a9ecb42d3d4.png)

**Comment by wg5945** [comment]
这个没什么影响吧，只是个空节点

现在address仅仅是对popup-picker做了一层封装，这里是留个根div是为了方便以后扩展其他内容？

**Comment by hooraygith** [comment]
![image](https://user-images.githubusercontent.com/11362506/35804784-22c45c0a-0ab4-11e8-888b-1150f0ea1435.png)

x-address 不是 group 第一个子组件时， 这个样式还是有问题，多套了层div：

![image](https://user-images.githubusercontent.com/11362506/35804824-4fd5c008-0ab4-11e8-963a-797653dc5aaf.png)

需要去掉 components/x-address/index.vue 最外层的 div

**Comment by lichunqiang** [comment]
不需要吧？我印象中vue好像需要要一个根dom包裹。况且不会有什么影响

**Comment by hooraygith** [comment]
vue好像需要要一个根dom包裹，是指vue模板template标签里只能有一个子元素吧

所有的weui-cells的直接子元素都应该有weui-cell这个class，用这个 class 控制这个边线。这样就可以去掉x-address自己的边线

**Comment by wg5945** [comment]
恩，是这样，之前没注意 - -

**Comment by WilliamLin1990** [comment]
![image](https://user-images.githubusercontent.com/1336875/36337371-c4177186-13cf-11e8-82f8-fa62618e8d0b.png)
我现在这样使用的话就少了上边线了 @wg5945 
`
<cell title="产品类型" :value="type2" is-link @click.native="showPopup=true" value-align="left"></cell>
      <x-address title="省份城市" v-model="province_city" raw-value :list="addressData"
                 value-text-align="left"></x-address>
`

**Comment by anselwong** [comment]
@wg5945 @WilliamLin1990 +1

暂时解决方式是去掉源码的外层div
