### ISSUE TITLE
样式

### ISSUE THREAD

**Issue by shj0612** [airyland/vux#2376]
我的项目用到的rem，在首页的时候dialog间距会有问题。我的是按照 100* (clientWidth / 375) 算的html的高度。
![image](https://user-images.githubusercontent.com/24514444/34552362-f3fe04aa-f15b-11e7-99b0-c39c2d27b3f7.png)

**Comment by airyland** [comment]
VUX 本身不内置支持 rem，换算出现的问题，要么你提出 VUX 可以帮忙进行源码修改的诉求，要么上一个 repo 可以快速重现你的问题。快速处理的方式是直接进行样式覆盖。

**Comment by ScarlettMuxi** [comment]
你好，在scss中 使用/deep/ 覆盖 weui-dialog的样式 在我本地是好的，在同事哪里样式没有被覆盖，环境一样，代码一样

**Comment by wangbadanaaa** [comment]
我也遇到了，直接样式覆盖吧。

**Comment by wangbadanaaa** [comment]
样式覆盖吧，用flex布局
