### ISSUE TITLE
（小问题）swiper组件图片引用错误

### ISSUE THREAD

**Issue by hi-zhaoyeqing** [airyland/vux#2378]
swiper 组件源码第120行：
120：   img: 'https://static.vux.li/demo/5.jpg',
应该为
120：   img: 'https://static.vux.li/demo/3.jpg',

**Comment by airyland** [comment]
没有错，这里本意是为了测试使用一个不存在的 5.jpg 图片，会使用 3.jpg 作为 fallback 图片显示。

**Comment by hi-zhaoyeqing** [comment]
嗯，好的，谢谢！还以为是错了！
