### ISSUE TITLE
Demo checkicon页面打不开

### ISSUE THREAD

**Issue by mymmoonoa** [airyland/vux#2389]
https://vux.li/demos/v2/?x-page=v2-doc-home#/demo
的checkicon 打不开，一直显示加载中状态。手机端、PC端，WiFi、联通4G都有试验。
检查一下

**Comment by airyland** [comment]
https://vux.li/demos/v2/#/component/check-icon
并没有发现问题。

**Comment by chumysummer** [comment]
check-icon可以修改样式和颜色吗，因为自己的项目里面是方形蓝色的

**Comment by mymmoonoa** [comment]
@chumysummer 
如果组件有提供可以修改你需要实现样式的props属性，你直接传递即可。
如果没有的话，你可以通过浏览器debug，观测实现样式的和颜色所使用的class。然后你加个override的class样式即可。
例如：(下面是代码假设)
vux组件原始样式
```
.vux-class-a {
  color: red；
  ...
}
```
你只需要在vux组件上添加vux-override的class
然后在公共的css文件中添加代码
```
.vux-override .vux-class-a {
  color: urcolor; /*你要的颜色*/
  ...
}
```
以上是方法，你可以边调试便实现。
