### ISSUE TITLE
confirm组件中的input问题

### ISSUE THREAD

**Issue by yoguang** [airyland/vux#2390]
在使用confirm组件时遇到这样一个问题: 组件中的input标签不能在iphone手机自动获取焦点,如何解决,或者提供关闭自动获取焦点的功能;谢谢!
 补全代码
   <div v-transfer-dom>
      <confirm v-model="openConfirm"
      title="确认"
      show-input
      :input-attrs="{type: 'text'}"
      placeholder="意见"
      @on-cancel="onCancel"
      @on-confirm="onConfirm"
      @on-show="onShow"
      @on-hide="onHide">
      
      </confirm>
    </div>

**Comment by Web-of-Dancer** [comment]
补全代码

**Comment by airyland** [comment]
和组件无关，iOS 本身就无法自动获取焦点，无法支持。

**Comment by yoguang** [comment]
@airyland 谢谢!那如何让他不自动获取焦点呢?

**Comment by airyland** [comment]
没看明白，不能实现自动焦点，为什么要实现不自动获取焦点？

**Comment by excellnn** [comment]
这个问题是这样的：
在安卓微信里面，如果confirm组件里面有input输入框，在confirm弹出且input获得焦点键盘弹出的情况下，如果把微信切换到后台，再切换回来。这个时候键盘隐藏了，但是input的焦点还是没有失去，点击input，键盘无法弹出。

**Comment by excellnn** [comment]
希望作者 @airyland  可以看下，不要这么着急地下结论。还有一个相同的问题#2033

**Comment by airyland** [comment]
@excellnn #2033 的问题和你这个不一样，那是 iOS 特定布局下导致的问题。你这个问题我没有重现，最好给个重现环境。

**Comment by daiing** [comment]
在微信浏览器里就是这样，其他手机浏览器都行
