### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by 2413052180** [airyland/vux#2395]
npm run dev时报错，按照官网给出的`npm install --registry=https://registry.npm.taobao.org` 和 不使用淘宝源直接使用 `npm install` 都不行，一切都按照官网上步骤来做，未改过任何代码，安装依赖无报错
当前环境

系统：win10
node：6.11.3
npm：3.10.10

报错信息如下
![image](https://user-images.githubusercontent.com/13171956/34722650-a79f14f2-f582-11e7-8709-3e41448647a0.png)

**Comment by airyland** [comment]
先升级 node 版本试试。

**Comment by 2413052180** [comment]
试过了，也不行，出问题的电脑是家里的电脑，今天上午在公司电脑上运行正常，然后把代码拷贝到家里电脑发现可以正常运行了，系统、node、npm版本都是一样的。。。

**Comment by airyland** [comment]
这个问题我没办法重现，只能自己有空时再对比检查一下，先关闭了。

**Comment by 2413052180** [comment]
好的，谢了哈。
