### ISSUE TITLE
建议升级weixin jssdk 版本到 1.3.0

### ISSUE THREAD

**Issue by lycooe** [airyland/vux#2396]
现在还是使用的1.2.0
我想支持 微信小程序 只有1.3.0才能支持

自己引入1.3.0 会导致和 原1.2.0 冲突

希望升级一下 谢谢

**Comment by lichunqiang** [comment]
[yanxi-me/weixin-js-sdk](https://github.com/yanxi-me/weixin-js-sdk) 目前还没做升级，目前看起来维护者已经不在活跃维护了。看有人已经提出升级到3.0

@airyland 怎么看。

**Comment by airyland** [comment]
看起来只能自己维护一份了。。

**Comment by shoyuf** [comment]
please update to [jweixin-1.3.2.js](https://res.wx.qq.com/open/js/jweixin-1.3.2.js)
[yanxi-me/weixin-js-sdk](https://github.com/yanxi-me/weixin-js-sdk) already updated
