### ISSUE TITLE
datetime、flexbox等挺多组件在手机火狐浏览器都有问题

### ISSUE THREAD

**Issue by liniu** [airyland/vux#24]
datetime、flexbox等挺多组件在手机火狐浏览器都有问题，在电脑火狐浏览器也有问题

**Comment by airyland** [comment]
还没在火狐上测试 要再过一两周 我先找我走丢的狗。。

**Comment by liniu** [comment]
Flexbox 已经修复。 DatetimePicker 日期时间出不来，address picker popup-picker 无法滚动，还有selector，  tab，switch，search 还需要测试下，加油，你的这些组件很棒。

**Comment by airyland** [comment]
@liniu 还在测试中，要花点时间，原来只在Safari上开发测试。

**Comment by airyland** [comment]
vux依赖于weui, 而weui在火狐下存在比较多的兼容问题，考虑到火狐的用户数很少，并且看weui的issue基本没有火狐的兼容反馈，最大的问题是兼容成本巨大(目前来说，个人时间精力完全不够，如果有兼容的PR随时欢迎)，因此暂时放弃了火狐的兼容 🐶

**Comment by iflamed** [comment]
支持放弃火狐，精力应该花在最大效益的地方

发自 刘兵 的 iPhone
