### ISSUE TITLE
文档的应用vux.css是否位置需要更正一下 

### ISSUE THREAD

**Issue by bulolo** [airyland/vux#240]
https://vuxjs.gitbooks.io/vux/content/install/vue.html
文档内应用的vue.css位置是否需要改成  
@import '~vux/dist/vux.css';
而非
@import '~vux/vux.css';

### Version
版本号 0.1
### Android or iOS, which browser?
All
### Your Codes 

``` html
<style>
@import '~vux/vux.css';
</style>

文档应用的是否应该改为  
@import '~vux/dist/vux.css';
```

**Comment by airyland** [comment]
谢谢反馈。
