### ISSUE TITLE
在使用x-input type=‘number’ 时，输入1.1.1（连续多个点）之后 程序会出错 导致无法正常取值

### ISSUE THREAD

**Issue by zhangdengchao** [airyland/vux#2403]
<x-input type='number'></x-input>
![image](https://user-images.githubusercontent.com/30650183/34822307-6e046ac8-f701-11e7-93d8-4cc2c1cdadd8.png)
![image](https://user-images.githubusercontent.com/30650183/34822330-897321aa-f701-11e7-98e2-4634dbff61e5.png)

**Comment by coolfirewang** [comment]
请问问题解决了吗？
