### ISSUE TITLE
 单击’X-Input输入框‘无效，必须双击，而且控制台还会报以下错错误

### ISSUE THREAD

**Issue by zzlw** [airyland/vux#2405]
单击输入框无效，必须双击，而且控制台还会报以下错错误

浏览器控制台错误代码如下
```
Unable to preventDefault inside passive event listener due to target being treated as passive. See
```

# 项目仓库地址：     [https://github.com/zzlw/dudu_vote_vue.git](https://github.com/zzlw/dudu_vote_vue.git)

**Comment by doommm** [comment]
请把代码贴出来
