### ISSUE TITLE
PopupPicker联动显示的时候不可以自定义每一列所占用的宽度

### ISSUE THREAD

**Issue by Horzen** [airyland/vux#2412]
![image](https://user-images.githubusercontent.com/32396611/34925353-bfa4348c-f9e3-11e7-88ba-f66fce841068.png)
如图所示的PopupPicker。联动显示的时候，左列为市区，右列为辖区。想让左列的宽度窄一些，而右列宽一些。但左右两列的class完全一致，导致不能自定义调节，还有什么办法来调节么？

**Comment by airyland** [comment]
试试属性 `column-width`，文档应该有说明。

**Comment by Horzen** [comment]
可以了  谢谢。
