### ISSUE TITLE
XImg组件内的 props->offset->default单词写错啦！！导致报错，

### ISSUE THREAD

**Issue by Alex-CZL** [airyland/vux#2413]
XImg组件内的 props->offset->default单词写错啦！！导致报错！应该是default，但是源码里的是defaut

**Comment by Alex-CZL** [comment]
错误内容：[Vue warn]: Invalid key "defaut" in validation rules object for prop "offset".
解决方案：手动改源码，，，毕竟是单词写错了（但是这不是长久之计）。

**Comment by airyland** [comment]
v2.7.6 版本就已经修正了。

https://github.com/airyland/vux/blob/56d04b67e912551495ee73824c53b29f10d0b2d5/src/components/x-img/index.vue#L66-L69
