### ISSUE TITLE
XInput required 如果不填写直接验证返回 true

### ISSUE THREAD

**Issue by newbeea** [airyland/vux#2415]
XInput required 如果不填写，就是不进入输入框，直接验证返回 true
官方 demo https://vux.li/#/zh-CN/demos/x-input
![image](https://user-images.githubusercontent.com/1249059/34970709-e4ee9af2-fab0-11e7-942c-5e4ce09f6d7b.png)

**Comment by cnshenliang** [comment]
@newbeea @airyland 
我也遇到了这个问题，全新的表单，如果焦点从未进入过表单元素，直接提交时验证直接返回 true 。
我自己修改了代码，x-input/index.vue 中的第 183 行，
原来的代码：
    if (this.required && typeof this.currentValue === 'undefined') {
      this.valid = false
    } 
修改为：
    if (this.required && !this.currentValue) {
      this.valid = false
    }
问题就解决了，不知道改的对不对，还请作者确认！谢谢！

**Comment by wangshantao** [comment]
我也遇到这个问题

**Comment by wushaojun315** [comment]
@cnshenliang      你好，我想知道焦点没进入过的表单input，提交的时候怎样会自动校验呀？    是需要把x-input放在form表单中吗？

**Comment by ycg000344** [comment]
@wushaojun315 同问，如果有解决方法， 劳请告知，谢谢。
