### ISSUE TITLE
请问tab-item的宽度可以自适应么

### ISSUE THREAD

**Issue by KarnaughK** [airyland/vux#2417]
![image](https://user-images.githubusercontent.com/13878673/35024373-147c0506-fb7a-11e7-89ee-5bfd63ed5911.png)

比如这个 厢货 的item和其他的一样宽。。。宽的一匹。。。好像也没看到有自适应的功能。。。求解

**Comment by KarnaughK** [comment]
![image](https://user-images.githubusercontent.com/13878673/35024395-2f27221e-fb7a-11e7-8457-4188a2893fe4.png)

**Comment by ranxin001** [comment]
我这默认就是自适应的...你知道怎么解决这个吗？让它可以滚动
<img src="http://www.cnwif.cn/my_staticFile/images/aaa.png">

**Comment by Subwin** [comment]
@bobodegithub 更新vux版本

**Comment by airyland** [comment]
暂无计划实现自定义宽度，如果需要只能自己实现。

**Comment by soopxin** [comment]
![image](https://user-images.githubusercontent.com/15920906/43635875-079aa648-9743-11e8-9cc3-32e53be6d316.png)
当数据很多的时候，加载选中的样式，下划线很短

**Comment by Aliujiayu** [comment]
老哥，这个宽度自适应怎么处理的，麻烦加下微信YX5592259有偿解决，或者能帮忙提供下其他插件
