### ISSUE TITLE
使用search组件的时候vue.js会报错

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#242]
v.0.1版本出现这个问题，复现代码可见：[jsfiddle调试地址](https://jsfiddle.net/auf2ua0p/1/#&togetherjs=G2RnBImudt)

报错信息：
`vue.js:1018 [Vue warn]: Invalid expression. Generated function body:  @scope.emit('on-submit',scope.value)`

**Comment by dangyuluo** [comment]
jsfiddle的console里报错挺多的，需要好好找一下图中的错误
<img width="723" alt="screen shot 2016-06-05 at 14 57 33" src="https://cloud.githubusercontent.com/assets/4816327/15804058/e4566970-2b2d-11e6-8afb-03f615f92a45.png">

**Comment by airyland** [comment]
It's a typo problem. Fixed now.
