### ISSUE TITLE
npm install过程中报的错

### ISSUE THREAD

**Issue by JhoneDrangon** [airyland/vux#2423]
根据Vux的文档进行了操作
vue init airyland/vux2 wechat
cd wechat
npm install --registry=https://registry.npm.taobao.org 
然后就开始报下面的这些错误了，我的node v8.9.1   npm 5.6.0  使用的是Vue 2.9.2  vue-cli  2.9.2
![image](https://user-images.githubusercontent.com/17637905/35078422-2d7fc1fa-fc3d-11e7-89ef-251fc88205cb.png)
请大神帮我看一下，这是怎么回事

**Comment by nyaapass** [comment]
先全局装这个包, 可以少报点错:

https://github.com/felixrieseberg/windows-build-tools

但是 node-zopfli 下载403的那个问题没法解决, 不过似乎没啥影响

**Comment by nyaapass** [comment]
@JhoneDrangon 关于 node-zopfli 下载403的问题, 下班回去拿 Mac 试了一下, 不知道 Windows 行不行

参考这个 [Issue](https://github.com/peterbraden/node-opencv/issues/463#issuecomment-260166761), 可以选择自己从源码编译 (前提是 build-tools 要装好), 然后:

`npm install node-zopfli --build-from-source --no-save` (`--no-save` 使其不加入依赖)

最后再 `npm install`, 就没有403报错了

**Comment by airyland** [comment]
参考上面 @nyaapass  同学的意见，因为是  npm 下载的问题，无 vux 无关，需要到相关 repo 反馈，这里先关闭了。我安装过程中倒没遇到这种情况。
