### ISSUE TITLE
vux 官网 demo 页面在 Android 4.4 预装 Chrome 上白屏

### ISSUE THREAD

**Issue by nyaapass** [airyland/vux#2430]
- 白屏页面: https://vux.li/demos/v2/#/demo
- Android 版本: 4.4 (官方原生出厂镜像, 什么都没动过)
- Chrome 版本: 30.0.1599.105 (4.4 预装版本)
- 设备型号: Google Nexus 7 (2012 WiFi)

请问一下这会是什么原因, 如果项目 (Cordova 的那种形式) 需要兼容 Android 4.4 [(vue 最低兼容到 4.4)](https://github.com/vuejs/vue/issues/6567#issuecomment-328549186)

是不是不太适合用 vux?

**Comment by airyland** [comment]
不确定原因，建议 clone 下 vux 本地运行，在页面上添加  window.onerror 看弹出什么错误。理论上 vue 兼容到 4.4 的话，vux 仅仅是组件库兼容应该一致。
