### ISSUE TITLE
Search组件，onSubmit时获取不到input的值

### ISSUE THREAD

**Issue by zhaoxiong123** [airyland/vux#2432]
`<search @on-submit="onSubmit" :auto-fixed="autoFixed" @on-focus="onFocus" @on-cancel="onCancel"></search>`

**Comment by zhaoxiong123** [comment]
vux\src\components\search\index.vue
LINE 10

**Comment by airyland** [comment]
第一个参数是 input 值。或者直接用 v-model 绑定直接从绑定值获取。
