### ISSUE TITLE
gitigonre

### ISSUE THREAD

**Issue by Suntgr** [airyland/vux#2438]
.DS_Store
node_modules/
<<<<<<< HEAD
dist/
npm-debug.log
yarn-error.log
=======
/dist/
>>>>>>> vuejs-templates-master
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Editor directories and files
.idea
.vscode
*.suo
*.ntvs*
*.njsproj
*.sln

**Comment by lichunqiang** [comment]
想表达什么

**Comment by Suntgr** [comment]
这是用vue init airyland/vux2 projectPath，你们的模板生成的全新项目的gitignore文件，里面的有冲突。
