### ISSUE TITLE
Rater不支持自定义最小和最大分值，并且更改样式后会被立即覆盖

### ISSUE THREAD

**Issue by Horzen** [airyland/vux#2439]
![qzpcvxnlcnncag9yemvuxefwcerhdgfcum9hbwluz1xeaw5nvgfsa1w4nzc1otq0nvxjbwfnzuzpbgvzxdjgnzm0nze5ltq3rkutngzims1bqtc4luy4mjlgmdm5oeuwmi5wbmc](https://user-images.githubusercontent.com/32396611/35271035-c5862732-006b-11e8-87f9-6f95b09fd298.png)
当前需求：最低分值是1分，可是组件支持的最低值是0.当用户点击0分后，在js中更改样式为红色，不生效。定位原因是被覆盖掉。
解决办法是：使用两个Rater，一个只有1颗星，并且disabled，另一个只有4颗星，可用。
但是这样不太好。希望能够支持自定义Rater的最低分值或者最高分值。

**Comment by RoseEnd** [comment]
我也有同样的需求，看了源码，只需要在watch中修改如下代码即可
```js
currentValue (val) {
        if (val < 1) this.currentValue = 1;
      this.updateStyle()
      this.$emit('input', val)
    },
```
希望作者大大能够增加一个最小值的prop

**Comment by wg5945** [comment]
下个版本支持
