### ISSUE TITLE
ios 微信和safari浏览器input标签输入出现空白情况

### ISSUE THREAD

**Issue by morongs** [airyland/vux#2443]
微信浏览器或safari浏览器，遍历表单元素，第一个表单元素输入框正常，后面几个**被<group>标签包围的文本框或者<x-input>生成的文本框，无论中英文，均出现输入空白、删除显示延迟情况。未被group包围的input则正常输入。**

测试出问题的IOS系统版本：ios 11 、ios 10

代码结构如下：
``` html
<div v-for="item in data">
    <input type="text" name="input1" value="1">
    <group label-margin-right="2.2em" label-width="5em" label-align="left">
           <input type="text" name="input2" value="2">
           <x-input
            type="text"
            title="姓名"
            placeholder="请填写"
            text-align="left"
            v-model="submitData.name">
          </x-input>
    </group>
</div>
```
name="input1" 输入正常， name="input2"输入出现空白，x-input生成的标签输入空白。

具体手机显示效果如下：
![bug](https://user-images.githubusercontent.com/8064956/35376775-82ca3cc6-01e7-11e8-9447-7bdd2090b91b.gif)

**Comment by Sapphire2k** [comment]
这个问题多半是因为使用了：`-webkit-overflow-scrolling: touch`

1、需要一个个排查，`-webkit-overflow-scrolling: touch`最好只写在`body`。

2、
```
input、textarea {
  -webkit-transfrom: translateZ(0px);
  position: relative;
}
```
👆这个组合有奇效～

**Comment by Jiunsr** [comment]
@Sapphire2k 是的，写上这两个就解决了，可是这里 transform 写成 transfrom了。😂
