### ISSUE TITLE
Range不支持双边拖动进行范围选择；FlexBox没有宽度自适应功能

### ISSUE THREAD

**Issue by Horzen** [airyland/vux#2447]
![screenshot_1](https://user-images.githubusercontent.com/32396611/35422170-4287b5b2-0282-11e8-98d5-ea0a868223e1.jpg)
如图所示，
1.当前Range组件还不支持双边拖动进行范围选择；
2.当前组件中还没有类似于frameWork7里碎片一样的组件，或者说FlexBox还不支持宽度按照内容自适应

**Comment by airyland** [comment]
1. range 暂时不支持，可能会重写或者引入社区已有的组件
2.flex 的简单布局直接写样式就行了，flexbox 主要用于固定比例的场景。
