### ISSUE TITLE
clocker组件倒计时退出页面后还在执行

### ISSUE THREAD

**Issue by zjtt** [airyland/vux#2449]
clocker组件倒计时退出页面后还在执行，我想做一个60分钟的倒计时，放在created生命周期里面，渲染页面的时候已经过去了几秒怎么办？还有我退出页面再次进来的时候倒计时还是上次执行后的时间

**Comment by airyland** [comment]
已经过去了几秒，说明你 mounted 时间长吧，你就在 mounted 里执行吧。退出时已经 destroy 了理论上不会再运行了，你是不是用了 keep-alive？

**Comment by zjtt** [comment]
1.clocker组件绑定的time字符串在created时必须有一个初始值要不然会报错，我试了在created时绑定初始值在mounted时再改变值还是不行
2.我没有用keep-alive
3.我最后采用了Countdown组件计时秒数，在computed中写一个方法把秒数转化为分和秒显示在页面另外的地方，然后把Countdown组件display:none,算是实现了倒计时

**Comment by zjtt** [comment]
使用Countdown组件的start属性可以控制在mounted时再开始倒计时，clocker没有start属性

**Comment by airyland** [comment]
初始化时没有要求初始值，源码里若没有值就已经直接 return 了，若报错也请帖出报错信息。

https://github.com/airyland/vux/blob/21dc9a683852aa309d503cd468f3339ea091155d/src/components/clocker/index.vue#L37-L40

还是给出完整使用代码吧，谢谢。

**Comment by zjtt** [comment]
代码： data () {
        return {
            page_data:{
                xxtime:'',

<clocker :time="page_data.xxtime"></clocker>

 mounted(){
        this.page_data.xxtime = '2017-10-11 23:11';
    }

报错：
vue.esm.js?65d7:578 [Vue warn]: Error in callback for watcher "time": "TypeError: Cannot read property 'remove' of undefined"

found in

---> <Clocker> at E:\work\mine\coding\HYW\vue-cli-multi-page\node_modules\vux\src\components\clocker\index.vue
