### ISSUE TITLE
关于使用Sticky组件，无法配合其他滚动插件实现sticky效果

### ISSUE THREAD

**Issue by Cyran777** [airyland/vux#2451]
@airyland sticky组件还是非常好用的，但没法在这个页面使用其他滚动插件，希望能在这个组件中，暴露一个方法，能配合其他滚动插件，来控制vux-fixed类名

**Comment by airyland** [comment]
如果使用其他滚动插件，sticky 应该是这些滚动插件内置的功能了。如果仅仅是想添加 vux-fixed 类名，直接操作 className 应该就可以了。

**Comment by Cyran777** [comment]
@airyland 哦，好的，谢谢解答，那有没有推荐的scroll插件？

**Comment by airyland** [comment]
看 awesome-vue 相关的组件，或者考虑下 better-scroll 维护也比较活跃。
