### ISSUE TITLE
swiper快速滑动时，提示点没有立即响应，在滑动结束后才响应

### ISSUE THREAD

**Issue by TothingWay** [airyland/vux#2452]

**Comment by huchun666** [comment]
我也出现这种问题

**Comment by Xiao-bin** [comment]
请问这个问题解决了吗

**Comment by futurehu** [comment]
同样的问题

**Comment by Dorsey-CN** [comment]
有人已经解决这个问题了吗

**Comment by CallMeHunter** [comment]
![image](https://user-images.githubusercontent.com/31719446/48240728-d3ddbe80-e40e-11e8-8bea-ef995e464170.png)
修改源码, 删除掉watch里面current对象的emit方法, , 添加上面的代码, on-index-change就可以及时切换之后立马改变, 目前没发现问题

**Comment by yh-sunshine93** [comment]
> 有人已经解决这个问题了吗

swiper.js里面的me.touchmoveHandler方法最后 增加
let cb = me._eventHandlers.swiped
cb && cb.apply(me, [me._prev % me.count, me._current % me.count])
强制回调事件
