### ISSUE TITLE
loading组件的建议

### ISSUE THREAD

**Issue by heiyun** [airyland/vux#2455]
建议设置一个时间属性控制loading组件隐藏的最大时间间隔,而不必再写定时器延时关闭的代码

**Comment by airyland** [comment]
控制 loading 显示后特定时间后自动关闭？

**Comment by heiyun** [comment]
对的因为一般都是获取到数据时去关闭loading框,但有时接口请求不到数据,也没手动让其关闭的话这个loading会一直转,导致页面无法操作,所以可以设置一个最长显示时间,到时间后如果仍然没数据也让它关闭.

**Comment by airyland** [comment]
从逻辑上讲，这是业务的问题，异常情况应该做操作而不是让组件忽略问题直接关闭。

**Comment by heiyun** [comment]
是的，只是觉得如果加入这个会更方便使用 523603119 邮箱：523603119@qq.com 签名由 网易邮箱大师 定制 在2018年01月30日 19:27，Airyland 写道： 从逻辑上讲，这是业务的问题，异常情况应该做操作而不是让组件忽略问题直接关闭。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by koucxz** [comment]
在我的项目中，我用了axios，每次发请求时调用

    this.$vux.loading.show();

请求成功时当然要hide，同时，设置 timeout ，请求超时或连接服务器失败时，在axios的拦截其中设置

    axios.interceptors.response.use(
        error => {
            if (error instanceof Error) {
                // console.log(error.message);
                VueThis.$vux.loading.hide();
                switch (error.message) {
                    case "Network Error":
                        VueThis.$vux.toast.show({text: '网络错误', type:'warn'});
                        error.message = "服务器连接错误，请检查网络设置";
                        break;
                    case "timeout of 60000ms exceeded": //配合axios.defaults.timeout使用
                        VueThis.$vux.toast.show({text: '网络错误', type:'warn'});
                        error.message = "请求超时，请重新请求";
                        break;
                }
                return Promise.reject(error.message);
            }
        }
    );

希望对你有所帮助

**Comment by airyland** [comment]
考虑了一下，暂时不会支持。有必要的话你可以直接封装一个函数来实现。

**Comment by lilywang711** [comment]
@koucxz 如果是用在 nuxt 中，怎么获取到 vue 实例呢，才能绑定$vux.toast

**Comment by lxl757266307** [comment]
在 拉起微信支付前使用 loading  移动端，下单成功，希望 loading消失，但是 各种办法试过了 ，就是不行，必须得支付完成 才能消失。这个 功能需要优化

**Comment by zuorichongxian** [comment]
> 你好,请问代码里的VueThis怎么获取
