### ISSUE TITLE
search组件模糊搜索时，搜索结果不能展示

### ISSUE THREAD

**Issue by Horzen** [airyland/vux#2456]
search组件的配置如下：
<search v-model="value" 
:placeholder="search" 
position="absolute" 
:autoFixed="false" 
ref="search" 
@on-submit="onSubmit" 
@result-click="resultClick" 
@on-change="getResult" 
:results="results"></search>

其中results为查询服务器获得的数据，见下图console中的数组。当进行模糊搜索的时候，能查到结果却不能正常显示，而点击结果列表的时候，却能正常获取到数据。查看样式，发现多了一个display：none的style。而官网示例中没有该样式。那么是否是该样式导致的呢？
![screenshot_1](https://user-images.githubusercontent.com/32396611/35557479-39585d14-05e0-11e8-928a-3102deb8cf84.jpg)

**Comment by Horzen** [comment]
下方的loc，Bruh不是结果集，只是下层页面。请忽略

**Comment by airyland** [comment]
auto-fixed 为 false 时不会显示结果。

**Comment by Lindazwl** [comment]
search组件，结果展示出来了，有什么方法能够实现结果下拉加载的吗？？？因为后台返回的数据不是全部搜索结果的数据，需要对列表进行下拉加载才能展示，
