### ISSUE TITLE
Sticky在本地失效了

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#246]
### Version
The latest version.
### Android or iOS, which browser?
Chrome desktop, responsive developing mode. 
### Your Codes 
Demo codes are enough. 

在本地编译好最新版本的vux之后，发现在chrome移动设备模式下，sticky无法使搜索框置顶。
Safari的responsive mode倒是可以置顶。

**Comment by airyland** [comment]
因为sticky用了直接判断safari版本是否原生支持，所以在chrome行为不一致是对的。
