### ISSUE TITLE
调试模式下TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by leixuesong** [airyland/vux#2462]
项目可以运行，控制台有红色警告，初步发现是locale应该为null。不知道怎么处理
vuex-i18n.min.js中
// split locale by - to support partial fallback for regional locales
// like de-CH, en-UK
var localeRegional = locale.split('-');

**Comment by airyland** [comment]
vuex-i18n 和 vux 无关。理论上你需要设置一个默认语言。
