### ISSUE TITLE
ios11上Drawer组件侧滑会闪两次

### ISSUE THREAD

**Issue by jaqen404** [airyland/vux#2466]
IOS版本：11.2.5
官网demo：https://vux.li/demos/v2/
点击左上角，侧滑组件会闪两次，回去时也会闪两次。
Android和比11低的版本IOS不会出现。

**Comment by airyland** [comment]
如果会闪，大概所有 transition 样式都会闪，建议重启下手机试试？

**Comment by jaqen404** [comment]
重启可以了，果然重启可以解决一大部分问题
