### ISSUE TITLE
组件中在script 块 用src="./login.js" 导入JS，提示控件加载有问题，请问怎么弄？

### ISSUE THREAD

**Issue by qu28** [airyland/vux#2468]
组件中在script 块 用src="./login.js" 导入JS，提示控件加载有问题，请问怎么弄？

控制台提示：如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader

邮箱:qu28@qq.com

**Comment by airyland** [comment]
没有代码，无力重现，请自行解决。
