### ISSUE TITLE
脚手架默认代码，把JS代码独立出来就有问题了。

### ISSUE THREAD

**Issue by qu28** [airyland/vux#2469]
都是默认加脚手架代码，就只是把JS独立出来了，方便开发和调试，但是会提示
![qq 20180204141559](https://user-images.githubusercontent.com/11346615/35774828-38fb3402-09b6-11e8-8cef-2fd31bc412f9.png)

![qq 20180204141352](https://user-images.githubusercontent.com/11346615/35774814-ebed36f6-09b5-11e8-8610-3374e88aa59f.png)

**Comment by airyland** [comment]
升级 vux-loader 到最新。
