### ISSUE TITLE
关于vuex路由动画的实现

### ISSUE THREAD

**Issue by lyj505** [airyland/vux#2474]
首先项目没有使用vux框架....但是在模仿路由动画的时候出现了问题
首先在main.js里面
注册路由钩子
`(router.beforeEach),`
主要问题是, 因为当钩子执行前，组件实例还没被创建,所以导致动画过去了之后,组件还未渲染完毕,当
组件渲染完毕了之后页面有明显的浮动,体验很差,和vux路由实现的流畅度完全不可比。。。
然后看了一下vux 路由的transition上有一个  
`@after-enter="$vux.bus && $vux.bus.$emit('vux:after-view-enter') `,
我本地跑vux的时候,把他屏蔽了,,,动画依然顺畅,想请教一下作者,,,如何实现的这个问题,
其实我感觉要么是在所有组件加载完之后执行路由动画,要么是在所有组件加载完之前执行路由动画,
请教~~~

**Comment by airyland** [comment]
逻辑都在 main.js 里，逻辑仅仅是改变 router-view 上的  transition name，至于 $vux.bus 只是为了通知部分渲染组件在页面切换成功后执行。

**Comment by lyj505** [comment]
对的,看来要实现一个bus,当页面切换成功去通知部分组件执行了。。。刚才测试了一下,写了个settimeout 延迟渲染部分组件就可以解决这个问题

**Comment by airyland** [comment]
看你描述不清楚你如何实现动画的，可能和 demo 实现不一样。demo 里简单判断了是前进还是后退，赋值不同的 transition name。

https://github.com/airyland/vux/blob/43430d0bef384b3f5663fe39b82b286f92795643/src/App.vue#L199-L202

issue 先关闭了，有问题再补充。
