### ISSUE TITLE
你好，datepicker与XInput同时使用会导致placeholder和value值无法显示

### ISSUE THREAD

**Issue by wuzhoubo** [airyland/vux#2475]
当datepicker与XInput组件同时使用时，会导致placeholder和value都无法显示
```
<group title="填写预约信息" class="weui-cells_form">
        <x-input title="预约部门" class="weui-vcode" placeholder='填写预约办事的部门' label-width="5em">
        </x-input>
        <datetime
            v-model="value1"
            @on-change="change"
            title="预约日期"
            placeholder="请选择"
            @on-cancel="log('cancel')"
            @on-confirm="log('confirm')"
            @on-hide="log('hide', $event)"></datetime>
</group>
```
如图
![image](https://user-images.githubusercontent.com/18018764/35839808-8607023a-0b2d-11e8-9855-ee9f1dfb24fd.png)
据我观察是在XInput组件中，这里将font-size设置为了0导致此问题
![image](https://user-images.githubusercontent.com/18018764/35839871-c64d1cbc-0b2d-11e8-94f1-5fa29c250412.png)
![image](https://user-images.githubusercontent.com/18018764/35840344-99e7ed5c-0b30-11e8-9f32-8d8442be3320.png)
解决办法在timepicker组件中添加这个样式就解决了
![image](https://user-images.githubusercontent.com/18018764/35840449-5f1fd878-0b31-11e8-89c7-2139edef2bc0.png)
希望修复

**Comment by airyland** [comment]
`weui-cells_form` 类名不推荐使用，下个版本使用 slot=right-full-height 显示验证码。
