### ISSUE TITLE
请问inline-calender里的show-last-month

### ISSUE THREAD

**Issue by yuy1guo** [airyland/vux#2479]
设置为false之后仍然可以显示上个月的日期，这个设置起的作用具体是？

**Comment by airyland** [comment]
补充代码，截图。

**Comment by yuy1guo** [comment]
```
<template>
      <InlineCalendar :disable-past="disablePast"></InlineCalendar>
</template>
<script>
import { InlineCalendar } from 'vux'
export default {
    data(){
        return {
            disablePast:true,
        }
    },
    components: {
        InlineCalendar
    }
}
</script>
```
我已经设置了不能显示前面的月份
为什么点击月份选择，还是出现了1月的？
那这个限制主要是限制的什么，不能点击么？
[iamge](http://ww1.sinaimg.cn/large/0060lm7Tly1fo7vd1k84ij308j08t0sx.jpg)

**Comment by airyland** [comment]
你题目写的是 show-last-month 代码用的是 disable-past，分不清你到底想问什么。
disable-past 实现的仅仅是当前月份的上一个月的日期不能点击，目前不会阻止跳到上一个月。
