### ISSUE TITLE
请问一下flexbox-item 如何自动换行？

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#248]
请问一下flexbox-item 如何自动换行？
例如
`<flexbox >`
`    <flexbox-item >1</flexbox-item >`
`    <flexbox-item >1</flexbox-item >`
`    <flexbox-item >1</flexbox-item >`
`    <flexbox-item >1</flexbox-item >`
`    <flexbox-item >1</flexbox-item >`
`    <flexbox-item >1</flexbox-item >`
`    <flexbox-item >1</flexbox-item >`
`</flexbox>`

如何三个一行，超出自动第二行？

**Comment by hubinjie** [comment]
我试了一下，用CSS可以

`.vux-flex-row{
    flex-wrap: wrap;
  }`

不知道有没有更好的方法

**Comment by graysheeep** [comment]
@hubinjie flexbox一个就是一行吧，要3个一行那只能多个flexbox了

**Comment by hubinjie** [comment]
因为我要用一个 v-for出来，所以能自动换行是最好的，不然判断比较麻烦

**Comment by graysheeep** [comment]
@hubinjie 
<flexbox v-for="n in list.length / 3">
</flexbox>

**Comment by graysheeep** [comment]
手动写一下也不麻烦吧
```
<flexbox v-for="n in list.length / 3">
   <flexbox-item v-for="m in 3">
     list[n * 3 + m]
   </flexbox-item>
</flexbox>
```

**Comment by hubinjie** [comment]
哈哈，茅塞顿开
