### ISSUE TITLE
tab组件，点击到屏幕最左或最右时，tabItem自动位移的需求

### ISSUE THREAD

**Issue by kevinchung1026** [airyland/vux#2483]
RT
现在需要手动滑动来查看左右超出屏幕的tabItem，有没有计划丰富下这个自动位移的功能？

**Comment by airyland** [comment]
计划中。

**Comment by skyshirt** [comment]
这个可以啊。现在还在用swiper或scroll模拟呢。期待这个功能

**Comment by airyland** [comment]
#2553 已经支持

**Comment by skyshirt** [comment]
@airyland 这个功能什么时间更新？

**Comment by liuchuanyang65** [comment]
这个功能以及更新了吗？怎么使用？

**Comment by chenglla** [comment]
如果默认选项超出屏幕之外，能不能让它自动滑动到当前屏幕看得见的地方？现在默认选中的选项超出屏幕的话，当前屏幕看不到

**Comment by niunai2016** [comment]
> 如果默认选项超出屏幕之外，能不能让它自动滑动到当前屏幕看得见的地方？现在默认选中的选项超出屏幕的话，当前屏幕看不到

我也想知道
