### ISSUE TITLE
根据快速入门安装完项目npm run  build 不能正常运行。但是npm run dev 可以。

### ISSUE THREAD

**Issue by git-cncoder** [airyland/vux#2485]
您好。 我安装官网的快速入门的步骤。安装并通过（运行的是最新的版本，今天跑的。没有修改其他内容） 
npm run dev 运行起来了，此项目。但我通过 npm run  build 之后放在网站根目录下面。访问，发现出现了如下问题。  项目不会正常运行了，或者说是不能router路由了。
在build 过程中，没有报错误。
![build不能正常运行，dev可以](https://user-images.githubusercontent.com/22268505/36068920-279319cc-0f1b-11e8-9933-ecfb941dcdbb.png)

**Comment by airyland** [comment]
没看明白你说的如下问题是什么。

**Comment by git-cncoder** [comment]
通过文档中代码运行，`npm run dev `浏览器可以正常访问。
```
npm install vue-cli -g // 如果还没安装
vue init airyland/vux2 projectPath

cd projectPath
npm install --registry=https://registry.npm.taobao.org
npm run dev
```
![npm run dev](https://user-images.githubusercontent.com/22268505/36081066-05c225bc-0fd5-11e8-9c28-aa9b4181f31e.png)
然后，我执行  `npm run build` 将生成的dist文件夹 复制到本地网站根目录下访问，却无法正常访问，是配置导致无法运行或访问路径不对造成的吗？  初始化项目之后没有改变代码。
![npm run build](https://user-images.githubusercontent.com/22268505/36081269-40b945fe-0fd7-11e8-82e7-6945d0e673d8.png)

**Comment by tempscript** [comment]
js 路径问题，所有没加载出。最根本问题是本地服务器根目录应该在dist 里面

**Comment by git-cncoder** [comment]
谢谢您的解决。如果可以不限制根目录就好了。可以创建多个项目。

**Comment by airyland** [comment]
部署的目录问题和 VUX 无关了。你可以修改 webpack 的配置 static 改为 ./static 应该可以实现本地预览。

**Comment by git-cncoder** [comment]
的确是这样的， 谢谢您了。 记笔记了~
