### ISSUE TITLE
Grid组件的建议

### ISSUE THREAD

**Issue by heiyun** [airyland/vux#2488]
九宫格组件建议增加属性控制是否显示分割线

**Comment by xfworld** [comment]
@airyland  底部的分割线是否也能给一个选项，来进行控制？ after

**Comment by airyland** [comment]
@xfworld 为什么不显示底部？

**Comment by xfworld** [comment]
@airyland  网格都没有了，只剩图标了，感觉会看一些
我目前直接用scoped 重写了css，很笨的搞法 ^_^

**Comment by airyland** [comment]
@xfworld 这种情况直接用 flexbox 就可以了，否则 grid 就没有存在的必要了。 grid 其实就是有网格线的 flexbox。

**Comment by xfworld** [comment]
@airyland  嗯，好，后面我自己在优化下，还真没想到

**Comment by robot-nan** [comment]
请问可以增加 icon 的样式变量吗？

**Comment by FWS-86** [comment]
可不可以结合badge使用？

**Comment by alreadytaken1990** [comment]
可不可以让label显示两行

**Comment by limnQQ** [comment]
支持修改icon的大小么

**Comment by igouz** [comment]
能不能再grid-item 加个badge这样的插槽？
