### ISSUE TITLE
vux + nuxt.js 目前可以兼容了吗?

### ISSUE THREAD

**Issue by vmvz** [airyland/vux#2490]
看到之前的issue, 有没有人尝试成功配置好 vux+nuxt.js.

Nuxt.js 实在太好用了

**Comment by wg5945** [comment]
![image](https://user-images.githubusercontent.com/5310295/36081456-02699ab2-0fda-11e8-96f6-2e768cef19ce.png)
前两天作者的原话 💪💪💪

**Comment by vmvz** [comment]
@wg5945 关键是如何在nuxt项目如何导入vux?

我尝试从 nuxt 和 ele 等 issue里面, 甚至 csdn帖子, 找各种经验, 发现都是如何导入Element的经验, 没有vux. 模仿Element导入,还是报错.

**Comment by wg5945** [comment]
报错应该不会吧，按照Element那一套应该可以正常渲染，但是貌似会有组件重复打包的问题，webpack配置还是有问题，等作者大大写一个呗 😔

**Comment by vmvz** [comment]
@wg5945 谢谢你了, 我只能等作者大大写文档了. 

新项目,急着等着用了.

**Comment by vmvz** [comment]
@airyland 能否告知 这个文档大约什么时候出来吗? 谢谢

@wg5945 你说不会报错,能否先告诉我你是如何配置的? 谢谢... 我今晚又试了一次, 还是错误(我自己本来是后端程序员,最近学vue这些的,)

**Comment by Zenfeder** [comment]
@airyland  请问现在有nuxt.js配置vux.js的文档了吗？

**Comment by Zenfeder** [comment]
@vmvz 你好， vux+nuxt.js有配置成功吗？

**Comment by vmvz** [comment]
@zenfeder 我没有。再等作者文档。

**Comment by Zenfeder** [comment]
@vmvz 我也是google了好几圈都没搜到解决办法

**Comment by vmvz** [comment]
@Zenfeder 我各种尝试都不行。 iview容易。

怪自己水平啦，哈哈。

你要是研究出来，告诉我

**Comment by Zenfeder** [comment]
@vmvz iview和element-ui我也都试过没问题
嗯，希望倒腾出来的小伙伴可以在这分享下经验，感谢～

**Comment by vmvz** [comment]
@Zenfeder 怎么样,有没有尝试成功呀. 最近我就在等这个了

**Comment by Zenfeder** [comment]
@vmvz 那天以后就没尝试了，在搞其他东西😄

**Comment by qiange920** [comment]
@vmvz @Zenfeder nuxt+vux你们现在倒腾出来了吗

**Comment by Zenfeder** [comment]
@qiange920 没倒腾了，坐等大佬出文档哈哈

**Comment by vmvz** [comment]
@wg5945 看来不少人关注呀，有没有进一步消息？ 谢谢
@qiange920 我也没有折腾做来， 在等文档

**Comment by airyland** [comment]
在 nuxt 提交个 vux 例子的 pr https://github.com/nuxt/nuxt.js/pull/2976 可以先参考一下。

**Comment by vmvz** [comment]
@Zenfeder @qiange920 老大发了例子,来试试吧
