### ISSUE TITLE
如何使用vue-test-utils+ tape 对使用了vux模块的组件进行单元测试？

### ISSUE THREAD

**Issue by yangdm2015** [airyland/vux#2491]
直接使用表现出的问题是报错不能识别vux代码中的import 语法，貌似是直接运行了vux包中的index.js。
我在编写组件的时候是利用webpack+vux-loader按需加载vux的组件，但在tape中直接测试引用了vux的组件时，报错如下：
`import Actionsheet from './src/components/actionsheet/index.vue'

^^^^^^
SyntaxError: Unexpected token import
`

**Comment by Richar-Dada** [comment]
@yangdm2015 我也遇到同样的问题 解决了吗
