### ISSUE TITLE
在使用“统一引入less(sass)变量”，运行时出现“Syntax Error: Unclosed block”

### ISSUE THREAD

**Issue by MaJiaXuan** [airyland/vux#2494]
试了几遍，目录下是有variable.less文件的，查不出哪里语法出问题了。。以下是错误信息：
error  in ./src/components/HelloWorld.vue

Syntax Error: Unclosed block
    at <anonymous>

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-656039f0","scoped":true,"hasInlineConfig":false}!./node_modules/px2rem-loader?{"remUnit":75}!./node_modules/vux-loader/src/style-loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/HelloWorld.vue 4:14-420 13:3-17:5 14:22-428
 @ ./src/components/HelloWorld.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

/*{
      name: 'style-parser',
      fn: function (source) {
        return "@import '../common/css/variable.less'\n" + source // 你可以根据this.resourcePath 来确定是否要引入以及引入的相对路径
      }
    }*/
把以上这段代码注释掉即运行正常

![qq 20180221001657](https://user-images.githubusercontent.com/24503453/36435408-8c9a0e7e-169c-11e8-9d0c-b327354c18cd.png)

**Comment by airyland** [comment]
帖上 variable.less 的代码。

**Comment by MaJiaXuan** [comment]
@airyland 
![qq 20180221110626](https://user-images.githubusercontent.com/24503453/36461219-48d8bf0e-16f7-11e8-9923-1624c3c3eb96.png)

**Comment by greedying** [comment]
要贴代码而不是图片

**Comment by airyland** [comment]
目测是你 import 这一句少了分号吧。

**Comment by MaJiaXuan** [comment]
@airyland 确实少了分号，但是又出现另外一个问题，找不到variable.less文件
![qq 20180228215917](https://user-images.githubusercontent.com/24503453/36791387-a4f0f410-1cd2-11e8-8086-ed4b8b717b10.png)

Module build failed: Error: Failed to find '../common/css/variable.less'
  in [
    C:\Users\94006\Desktop\music\node_modules\vux\src\components\inline-desc,
        C:\Users\94006\Desktop\music\node_modules\vux\src\components\divider,
        C:\Users\94006\Desktop\music\node_modules\vux\src\components\scroller,
        C:\Users\94006\Desktop\music\node_modules\vux\src\components\drawer,
        C:\Users\94006\Desktop\music\src
  ]
    at resolveModule.catch.catch (C:\Users\94006\Desktop\music\node_modules\postcss-import\lib\resolve-id.js:35:13)
    at <anonymous>
![qq 20180228220008](https://user-images.githubusercontent.com/24503453/36791424-c243dbe0-1cd2-11e8-91c1-26b522a5041d.png)

**Comment by airyland** [comment]
通过 this.resourcePath 判断是不是项目源码而不是 vux 源码再加上 @import。

**Comment by MaJiaXuan** [comment]
@airyland 如果想要同时做样式里面的px替换和统一引入Less(Ssaa)，要怎么写？两个功能参数name都是style-parser，试过两个name是style-parser，则会报同名的错误

**Comment by airyland** [comment]
只支持一个，要和逻辑合并到一个函数内写。

**Comment by MaJiaXuan** [comment]
@airyland 你能不能写个合并到一起的给我...

**Comment by MaJiaXuan** [comment]
@airyland 搞定了，最开始的错误是没加分号，后来是改对了，又发现另外一个问题，引入的路径，最后才用path的方式引入就OK了，附带图

**Comment by MaJiaXuan** [comment]
![qq 20180301211152](https://user-images.githubusercontent.com/24503453/36846494-d6963534-1d95-11e8-9bdb-deb4626340c5.png)
