### ISSUE TITLE
confirm组件存在点击问题，对于长文本无法改变光标位置

### ISSUE THREAD

**Issue by daledelv** [airyland/vux#2497]
且在ios系统下的钉钉软件内打开时，存在兼容问题，极难点选，点击区域存在向上偏移问题，原因未知。解决方案如下：
vux/src/components/confirm/index.vue文件，第十八行
```
 <div v-else class="vux-prompt" @touchstart.prevent="setInputFocus">
          <input class="vux-prompt-msgbox" v-bind="inputAttrs" v-model="msg" :placeholder="placeholder" ref="input"/>
        </div>
```
修改为
`<input v-else class="vux-prompt-msgbox" v-bind="inputAttrs" v-model="msg" :placeholder="placeholder" ref="input"/>`
问题解决，望反馈。

**Comment by airyland** [comment]
fixed via #2509
