### ISSUE TITLE
请问一下Scroller 滚动条是如何重置的

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#250]
Scroller 里面的内容是动态出现的，当内容加载完毕后，有没有可能重新刷新一下滚动条内容区域的高度，出现滚动条，现在发现滚动条高度不准

**Comment by lichunqiang** [comment]
在 `pulldown:reset` 和 `pullup:reset` 之后，内部会帮你重新reset的。

当然，可以通过下面的方法进行手动重置：

```
//template
<scroller v-refs:scroller >

//js
this.$refs.scroller.reset();

```

**Comment by airyland** [comment]
补充一下，需要在this.$nextTick里执行以保证DOM已经更新完毕，尤其在for in循环时

https://vuxjs.gitbooks.io/vux/content/layout/scroller.html
