### ISSUE TITLE
日期组件 如果填写了start-date 当前月在二月份 且start-date 的day>28 会出现日期空白

### ISSUE THREAD

**Issue by yuanye824** [airyland/vux#2500]
datetimepicker.js
show 方法里面
const valueMap = self.valueMap = parseDate(config.format, value || config.value)
这样计算出来的
这段代码我觉得应该可以改下parseDate(config.format, config.startDate || value || config.value)
应该是先以起始时间计算当前月的天数 
或者修改
max = Math.min(max, maxDay) 这个方法
不知道对不对
希望作者有时间看下 谢谢

**Comment by yuanye824** [comment]
我是有两个日期组件 第一个控制第二个的start-date的值

**Comment by airyland** [comment]
请直接给出代码方便重现。

**Comment by yuanye824** [comment]
<flexbox class="inline-box no-after datetime" :gutter="0">
              <flexbox-item :span="5/11">
                <datetime v-model="data.beginDate" format="YYYY-MM-DD" placeholder="开始日期" confirm-text="确认" cancel-text="取消"
                          clear-text="清空" @on-clear="clearValue(index, 'beginDate')" :icon-type="errors.has('beginDate'+index) ? 'error' : ''" :name="'beginDate'+index"
                          novalidate v-validate data-vv-rules="required" data-vv-as="日期" :start-date="timeTableBeginTime" :end-date="data.endDate">
                </datetime>
              </flexbox-item>
              <flexbox-item :span="1/11" style="text-align: center; background: #f6f6f6"><span class="label-title">-</span></flexbox-item>
              <flexbox-item :span="5/11">
                <datetime v-model="data.endDate" format="YYYY-MM-DD" placeholder="结束日期" confirm-text="确认" cancel-text="取消"
                          clear-text="清空" @on-clear="clearValue(index, 'endDate')" :icon-type="errors.has('endDate'+index) ? 'error' : ''" :name="'endDate'+index"
                          novalidate v-validate data-vv-rules="required" data-vv-as="日期" :start-date="data.beginDate">
                </datetime>
              </flexbox-item>
            </flexbox>

**Comment by yuanye824** [comment]
<flexbox class="inline-box no-after datetime" :gutter="0">
              <flexbox-item :span="5/11">
                <datetime v-model="data.beginDate" format="YYYY-MM-DD" placeholder="开始日期" confirm-text="确认" cancel-text="取消"
                          clear-text="清空" @on-clear="clearValue(index, 'beginDate')" :icon-type="errors.has('beginDate'+index) ? 'error' : ''" :name="'beginDate'+index"
                          novalidate v-validate data-vv-rules="required" data-vv-as="日期" :start-date="timeTableBeginTime" :end-date="data.endDate">
                </datetime>
              </flexbox-item>
              <flexbox-item :span="1/11" style="text-align: center; background: #f6f6f6"><span class="label-title">-</span></flexbox-item>
              <flexbox-item :span="5/11">
                <datetime v-model="data.endDate" format="YYYY-MM-DD" placeholder="结束日期" confirm-text="确认" cancel-text="取消"
                          clear-text="清空" @on-clear="clearValue(index, 'endDate')" :icon-type="errors.has('endDate'+index) ? 'error' : ''" :name="'endDate'+index"
                          novalidate v-validate data-vv-rules="required" data-vv-as="日期" :start-date="data.beginDate">
                </datetime>
              </flexbox-item>
            </flexbox>

**Comment by yuanye824** [comment]
``` html
<flexbox class="inline-box no-after datetime" :gutter="0">
  <flexbox-item :span="5/11">
    <datetime
      v-model="data.beginDate"
      format="YYYY-MM-DD"
      placeholder="开始日期"
      confirm-text="确认"
      cancel-text="取消"
      clear-text="清空" @on-clear="clearValue(index, 'beginDate')" :icon-type="errors.has('beginDate'+index) ? 'error' : ''" :name="'beginDate'+index"
      novalidate v-validate data-vv-rules="required" data-vv-as="日期" :start-date="timeTableBeginTime" :end-date="data.endDate">
    </datetime>
  </flexbox-item>
  <flexbox-item :span="1/11" style="text-align: center; background: #f6f6f6"><span class="label-title">-</span></flexbox-item>
  <flexbox-item :span="5/11">
    <datetime
      v-model="data.endDate"
      format="YYYY-MM-DD"
      placeholder="结束日期"
      confirm-text="确认"
      cancel-text="取消"
      clear-text="清空" @on-clear="clearValue(index, 'endDate')" :icon-type="errors.has('endDate'+index) ? 'error' : ''" :name="'endDate'+index"
      novalidate v-validate data-vv-rules="required" data-vv-as="日期" :start-date="data.beginDate">
    </datetime>
  </flexbox-item>
</flexbox>
```

**Comment by ychzh2000** [comment]
v-model 赋初值就行,默认代码去当前月最大日期
