### ISSUE TITLE
module.exports = 是否应该统一成 export default 

### ISSUE THREAD

**Issue by lion-git** [airyland/vux#2503]
![](http://oxjberyvw.bkt.clouddn.com/WechatIMG4813.jpeg)

这些地方的 module.exports = 语法应该统一成 export default ，不然在最新的 vue-cli@3.0 生成的项目中使用会报错 Cannot assign to read only property 'exports' of object '#'

**Comment by airyland** [comment]
在处理中了#2449

**Comment by lichunqiang** [comment]
#2499 处理了一些

**Comment by lion-git** [comment]
最新版本什么时候更新呀~~大神~~~

**Comment by airyland** [comment]
@lion-git 发了个版本，如果有需要的修改的可以发个 pr。

**Comment by zhangyongz** [comment]
请问vue-cli3.0中怎么配置 vux-loader

**Comment by rwjCxgsy** [comment]
修改了的版本是多少啊，最新版本也报错

**Comment by husky-wdy** [comment]
大神们，这个问题还报错是什么原因呀，折腾一天了。我也是用vue-cli 3.0构建的项目，源文件里面的module.exports =也统一成了export default，可还是报错。
