### ISSUE TITLE
全局引入组件，样式重复问题

### ISSUE THREAD

**Issue by zjf710** [airyland/vux#2506]
这样引入组件
```javascript
import Vue from 'vue';
import {
  Group,
  GroupTitle,
  Cell,
  Popup,
  XInput,
  XButton,
  Search,
  CheckIcon,
  WechatPlugin,
  ToastPlugin,
  LoadingPlugin
} from 'vux';

Vue.component('xButton', XButton);
Vue.component('group', Group);
Vue.component('groupTitle', GroupTitle);
Vue.component('cell', Cell);
Vue.component('xInput', XInput);
Vue.component('popup', Popup);
Vue.component('search', Search);
Vue.component('checkIcon', CheckIcon);
```
有很多重复的样式
![image](https://user-images.githubusercontent.com/18107501/36652430-b6a12eae-1ae9-11e8-86ff-95ab7d158989.png)

如何解决呢？

**Comment by airyland** [comment]
dev 模式下会重复，production 下打包会进行冗余压缩，只要 vux-loader 配置了 duplicate-style

**Comment by zjf710** [comment]
```javascript
vuxLoader.merge(webpackConfig(env), {
    options: {},
    plugins: [
      'vux-ui',
      'duplicate-style'
    ]
  })
```
打包之后还是会有冗余样式（都是以嵌入式样式生效的）
![image](https://user-images.githubusercontent.com/18107501/36655768-aab845da-1aff-11e8-805e-d36017b17e0b.png)

**Comment by airyland** [comment]
你是使用了路由组件异步加载？

**Comment by zjf710** [comment]
没有使用

**Comment by airyland** [comment]
css extract 没有配置？

**Comment by zjf710** [comment]
```javascript
plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production')
      }
    }),
    new webpack.BannerPlugin('版权所有，翻版必究'),
    new HtmlWebpackPlugin({
      template: `${__dirname}/index.html` // new 一个这个插件的实例，并传入相关的参数
    }),
    new webpack.optimize.UglifyJsPlugin(),
    new ExtractTextPlugin('style_[hash].css', { allChunks: true })
  ]
```
我这么配置的

**Comment by airyland** [comment]
建个可以重现的 repo 来看看。

**Comment by zjf710** [comment]
[https://github.com/zjf710/vueMobileAdmin](https://github.com/zjf710/vueMobileAdmin)
这里，PS：官方的例子也有样式冗余的情况。
![image](https://user-images.githubusercontent.com/18107501/37203606-34cd471c-23c9-11e8-8104-df903cb2e739.png)

**Comment by airyland** [comment]
目测是构建配置问题，可能是从某个版本的 vue-loader 开始导致的配置失效问题，待检查。

**Comment by airyland** [comment]
线上 demo 构建生成的 css 文件有重复是 webpack 配置千万的。demo 因为使用了异步加载路由文件，因此出现 style 标签有样式重复是正常的。正常非异步路由并没有重现到重复样式的情况，如果有问题麻烦建个 repo 重现。
