### ISSUE TITLE
页面快速滑动时出现空白

### ISSUE THREAD

**Issue by hthmh** [airyland/vux#2507]
比如说官网例子中的cell页，上下快速滑动时，滑到顶部或底部时，内容得停顿一下才能显示，cell条数比较多的时候比较明显，inlineCalendar页快速滑动时顶部的年份和月份那一行也显示的比较迟
chrome模拟和ios好像没问题，我测试的安卓（小米5X）很明显，自己单独写个li列表滑动没有这个问题

**Comment by Tyrone2333** [comment]
你好我也有这个问题,请问你解决没有,这是我的代码:
```
  html, body {
        height: 100%;
        width: 100%;
        // 注释一群 overflow: hidden,chrome 字体瞬间清晰,也解决了滑动时上下白边的问题
        /*overflow-x: hidden;*/
    }
```
虽然注释了 `overflow: hidden` 可以解决空白的问题,但是滑动时候外面的`ViewBox`会跟着跑
