### ISSUE TITLE
安装最新版本的less 3.0.1 会导致vux报错 但是降级之后，就恢复正常了。报错如下

### ISSUE THREAD

**Issue by Susanping** [airyland/vux#2508]
Can't resolve './fn' in 'E:\项目\vetify\node_modules\vux\src\styles\weui\base'
      in E:\项目\vetify\node_modules\vux\src\styles\weui\base\reset.less (line 1, column 0)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-04c2046b","scoped":false,"hasInlineConfig":false}!./node_modules/vux-loader/src/after-less-loader.js!./node_modules/less-loader/dist/cjs.js?{'modifyVars':{'theme-color':'#FFA635','dialog-button-text-primary-color':'@theme-color','search-bg-color':'@theme-color','tabbar-text-active-color':'@theme-color','header-background-color':'@theme-color','header-text-color':'white','header-arrow-color':'white','cell-font-size':'16px','cell-body-label-color':'@theme-color','checklist-icon-active-color':'@theme-color','button-primary-bg-color':'@theme-color','button-primary-active-bg-color':'@theme-color','border-color':'#D9D9D9','border-color-light':'#eee','disable-color':'#878D99','search-cancel-font-color':'#fff','check-icon-color-checked':'@theme-color','success-color':'#67C23A','warm-color':'#EB9E05','danger-color':'#FA5555','fc-title':'#2D2F33','fc-main':'#5A5E66','fc-gray':'#878D99','fc-light':'#B4BCCC','large-icon-size':'45px','default-icon-size':'35px','small-icon-size':'25px','font-large':'18px','font-main':'16px','font-minor':'14px','font-small':'12px'},'sourceMap':true}!./node_modules/vux-loader/src/style-loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-1380 13:3-17:5 14:22-1388
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js

**Comment by KeborKing** [comment]
你降到了那个版本？

**Comment by Susanping** [comment]
"less": "^2.7.3",

**Comment by KeborKing** [comment]
谢谢啦！我退回2.7.3也好了

**Comment by airyland** [comment]
less 3.0 有严重的兼容问题，导致路径出错，目前只能降级。

**Comment by zwdgit** [comment]
也可以升级less-loader，我当前的配置：
"less": "^3.8.1",
"less-loader": "^4.1.0",
