### ISSUE TITLE
IOS下地址组件在二级路由页面会显示不正确

### ISSUE THREAD

**Issue by asscarecrow** [airyland/vux#2510]
版本： ios 11.2.6, vux 2.7.9
问题描述： 主要是XAddress在一级route页面的时候渲染没问题，二级route页面渲染的时候就会出现渲染错误。这个问题在Android下面不会出现，在用桌面端调试的时候也不会出现，就是做真机测试的时候会出现。
问题截图：
![img_1085](https://user-images.githubusercontent.com/7657941/36717270-654d76d0-1bd8-11e8-8333-c8f8cc93aa1f.png)

关键代码：
route.js
```
// 渲染正常
   {
      path: 'my/account',
      component: myAccount
    },
// 渲染不正常，如上面截图
    {
      path: 'my',
      component: myHome,
      // alias: 'my/account',
      children: [
        {
          path: 'account',
          meta: {
            title: '我的账户'
          },
          component: myAccount
        },
```
myHome.vue
```
<view-box ref="viewBox" :class="bg">
    
    <router-view></router-view>
  </view-box>
```
myAccount.vue
```
    <group title="" class="address">
      <x-address title="地区" :list="ChinaAddressV4Data" ></x-address>
    </group>
```

我猜测应该是router-view的局部更新跟XAddress组件的内部处理有关，但又实在是找不出具体原因，只能把问题抛出。

**Comment by airyland** [comment]
该问题因为无法重现暂时关闭，欢迎提供可重现 repo 再重开。
