### ISSUE TITLE
Bug:Swiperout菜单滚屏时闪现, 附：视频和图片

### ISSUE THREAD

**Issue by thinkido** [airyland/vux#2512]
手机中数据多很容易重现,  qq:4077725
图片 http://cdn.7dtime.com/time_tlog/2018-02-28_cd879b62aa5.jpg
视频 http://cdn.7dtime.com/time_tlog/2018-02-28_cd879b62aa5.mp4

**Comment by alreadytaken1990** [comment]
我也是同样的问题，不过只出现在ios上

**Comment by alreadytaken1990** [comment]
这个是因为css里面有3dtransfrom， ios会硬件加速导致父组件脱离，在父层加上 transform:translate3d(0px, 0px, 0px); 即可解决问题
