### ISSUE TITLE
页面所有点击操作都会出现整体页面抖动（Android,IOS）

### ISSUE THREAD

**Issue by feily-os** [airyland/vux#2515]
测试环境为：Android 8.0（华为），7.0（小米），6.0（vivo），IOS 11( 7P), 10(6) ，APP内置X5
页面点击事件触发时，整体页面向右下位移 。大概像素为 top + 10px; left + 10px;
页面使用了过渡效果 (transition), 禁用了keep-alive. 目前无法确定原因。

**Comment by airyland** [comment]
官网 demo？如果不是，请给出 demo。

**Comment by feily-os** [comment]
不是官方demo。demo的话。需要裁剪内容。明天才上传吧

**Comment by feily-os** [comment]
这几天要发吧版，实在没时间弄个Demo，我把问题关闭了，后面我弄好Demo在另开。
