### ISSUE TITLE
使用vux+es6，通过cordova打包成android APP，在android5.1的华为手机上显示空白

### ISSUE THREAD

**Issue by userpengke** [airyland/vux#2516]
我们的hybrid APP开发框架采用的是vux+es6来编写的。通过cordova打包android APP，添加的是android @7.0.0的平台，安装到android 8.0的系统的Honor 9能够正常显示。安装到android5.1的Honor 7显示的是一片空白。安装到android6.0的红米4A上也能够正常显示，但是在android6.0的android原生模拟器上也是显示的空白。后面cordova修改android平台为6.3.4，还是出现上述情况。后来又尝试通过HBuilder打包，亦是如此！！！是不是vux框架开发的移动APP会导致未知的兼容性问题？如果是，请问有什么解决办法？谢谢！！！

**Comment by airyland** [comment]
空白一般是 js 语法不兼容。看你描述你并未尝试调试错误，建议你加上 `window.onerror` 来观察错误输出。检查是否用了 promise(比如依赖了 axios) 而没有引入相应 polyfill。

**Comment by userpengke** [comment]
对哦，项目中用了axios + promise，我们是web前端的新手，请问要如何引入polyfill呢？望指教，谢谢！

**Comment by airyland** [comment]
![image](https://user-images.githubusercontent.com/559179/36942322-53d8d036-1faa-11e8-927d-900b6618e66a.png)
