### ISSUE TITLE
popup-picker组件 show-name 无法显示name

### ISSUE THREAD

**Issue by ShineLam** [airyland/vux#2518]
`<group><popup-picker :title="" :data="relList" v-model="relSel" @on-change='relChange' placeholder="请选择" show-name></popup-picker></group>`

data如下：
`relList: [
        [{
          name: '本人',
          value: '1'
        }, {
          name: '父亲',
          value: '2'
        }, {
          name: '母亲',
          value: '3'
        }, {
          name: '家长',
          value: '4'
        }]
      ],relSel: []`

版本：
` "vue": "^2.5.13",
    "vux": "^2.7.9",
    "vux-loader": "^1.2.1"`

我想要选择后把对应value的数字字符串拿到传给后台，其他都是正常的，也没有报错
我想要选择后显示的name ，不写show-name的话直接显示的是value, 
问题是写show-name的话 选择后没有显示任何东西
烦请帮我看下是数据结构问题呢 还是哪里的写法有问题

**Comment by airyland** [comment]
`问题是写show-name的话 选择后没有显示任何东西` 啥意思？

**Comment by ShineLam** [comment]
![qq20180303-215224](https://user-images.githubusercontent.com/18389901/36935060-351670b8-1f2d-11e8-9912-8e717175021a.jpg)

没有写show-name是正常显示value对吧

写了show-name显示是这样 没有东西
![qq20180303-215014](https://user-images.githubusercontent.com/18389901/36935034-efd49a98-1f2c-11e8-9660-59fce4d3e738.jpg)
![qq20180303-215029](https://user-images.githubusercontent.com/18389901/36935038-ff70931c-1f2c-11e8-8eba-a6254c862fec.jpg)

**Comment by ShineLam** [comment]
我直接把demo的代码拷贝进项目 也是同样的问题

**Comment by ShineLam** [comment]
跟#1880一样 他的value为number 但是我的是string呀

**Comment by ShineLam** [comment]
好像没办法拿到name呀

**Comment by ShineLam** [comment]
getNameValues() 也拿不到name呀 可不可以抽点点时间帮我看下 这个如果解决不了 没办法使用呀

**Comment by ShineLam** [comment]
找到原因了 应该是自定义array的find方法跟vux有冲突

**Comment by airyland** [comment]
为什么要覆写  Array.prototype.find 方法？

**Comment by leo-lai** [comment]
同样的问题，也不是楼主的原因

**Comment by airyland** [comment]
@leo-lai 这样提问题除了浪费你我时间没有什么意义，删除了。

**Comment by linxuesia** [comment]
我之前也是这个问题，但是我是因为value的值我用的是数字，改成字符串就能正常显示了

**Comment by fu527018818** [comment]
我也碰到了同样的问题，解决是在on-change时 vm.$set 重新更新一下。。。

**Comment by linhouxian** [comment]
value 写成string类型就不会出现这种change的时候name无法显示了;
