### ISSUE TITLE
重新git clone 之后， server 不能启动。

### ISSUE THREAD

**Issue by bluemsn** [airyland/vux#252]
$ npm run dev                                                                         ‹ruby-2.1.2›

> vux@0.1.0 dev /Users/xxxx/workspace/github/vx/vux
> node build/dev-server.js

Listening at http://localhost:8080/
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 10.32.92.129:8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.2.4
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! vux@0.1.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vux@0.1.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by airyland** [comment]
端口占用了。

**Comment by bluemsn** [comment]
@airyland 端口未被占用，亲~换了端口依然报错

**Comment by airyland** [comment]
注意dev-server.js listen的是0.0.0.0，你改成127.0.0.1试试吧。

**Comment by bluemsn** [comment]
@airyland 换了， 127.0.0.1 或者 localhost: 都是一样的错误，，， 可能我的系统有问题吧。 看了node所有的进程， 也没有发现其它的node进行额~ 难道我要重启电脑？？？ ？
纠结，想提个pr 会这么难额~

**Comment by airyland** [comment]
明显你电脑有问题。重启吧。

**Comment by glenlzk** [comment]
@airyland 实在不好意思，同样问一个比较弱智的问题，git clone之后，npm run dev， 报了一个错误，
啥都没做，就是启动不了，npm run build也报类似的错，非常抱歉占用您宝贵的时间，打扰了。

 ERROR  Failed to compile with 1 errors                                 18:19:23

Module build failed: Error: ENOENT: no such file or directory, open 'D:\demo\vux
\src\demos\D:\demo\vux\src\demos\countdown\basic.vue'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at glob.sync.filter.map.one (D:\demo\vux\build\vux-config.js:79:27)
    at Array.map (<anonymous>)
    at Object.fn (D:\demo\vux\build\vux-config.js:66:12)
    at D:\demo\vux\node_modules\vux-loader\src\js-loader.js:43:32
    at Array.forEach (<anonymous>)
    at Object.module.exports (D:\demo\vux\node_modules\vux-loader\src\js-loader.
js:38:23)
