### ISSUE TITLE
Previewer自定义按钮，如何做到点击后不会隐藏

### ISSUE THREAD

**Issue by hezhiwen940420** [airyland/vux#2520]
遵从文档在一组轮播图片做了自定义按钮，但点击一次后就隐藏，这样到下一张图片的时候，需要拖动一下才显示，这样就很尴尬，请问可以让他一直显示么，上代码：
![1](https://user-images.githubusercontent.com/36944348/37017405-8918aa3a-214b-11e8-8c22-1dda9e572cdc.png)
![2](https://user-images.githubusercontent.com/36944348/37017415-8ee23684-214b-11e8-9e45-e8cb161686d5.png)
![3](https://user-images.githubusercontent.com/36944348/37017431-99476946-214b-11e8-809f-314954827f53.png)

根据文档，去找options，photoswipe的设置也没找到好的方法。

**Comment by airyland** [comment]
`tapToToggleControls: false` 应该可以解决。

**Comment by w274585790** [comment]
问题解决了吗?

**Comment by code-admin** [comment]
请问是在 options  配置 tapToToggleControls: false 吗？

**Comment by hezhiwen940420** [comment]
我options 配置如下 timeToIdle: false,
        tapToToggleControls: false,
        fullscreenEl: false,
        zoomEl: false,
        shareEl: false,
        counterEl: true,
        arrowEl: false,
        preloaderEl: false,
        captionEl: false,

**Comment by code-admin** [comment]
设置了
options:{
 zoomEl: false,
}
（安卓app里面） 自定义下载图标 会出发 缩放 效果（浏览器模式情况下都是正常都）
