### ISSUE TITLE
XTextarea组件可以加个disable属性吗？

### ISSUE THREAD

**Issue by zqinmiao** [airyland/vux#2522]
XTextarea组件可以加个disable属性吗？只有readonly属性的话，在ios上按住区域两秒会出现光标，并唤起一点软键盘。
效果如下图：
![image](https://user-images.githubusercontent.com/12278003/37144263-72c1c2ea-22f8-11e8-9e12-24f069ba5eda.png)

**Comment by Deelout** [comment]
麻烦封装个上传组件，谢谢
