### ISSUE TITLE
Datetime 的一些建议

### ISSUE THREAD

**Issue by freedomlang** [airyland/vux#2524]
#### 问题
1、只能需要依赖format 和初始化的值，来控制DatetimePicker 所显示的数据类型：只显示选择日、小时、分的话，需要配置format 和一个初始化的值来实现。
2、现在on-change 得到的值是根据我们传入的format 来格式化的，但有时候我们需要返回的一个完整的时间：YYYY-MM-DD HH:mm:ss

#### 建议
1、增加prop 控制DatetimePicker 显示的选择项
2、on-change 的值返回一个对象，里面包含格式化的值和未格式化的值「完整的」

**Comment by SunXuezeng** [comment]
Datetime 的年月日现在2000~2030时间如何配置更多的年月日的时间

**Comment by airyland** [comment]
1. `增加prop 控制DatetimePicker 显示的选择项`，其实没看懂，也许你需要举个实际例子便于理解。也欢迎 pr 来完善。

2. 对于返回的对象, on-change 暂时不会修改参数和类型，这是个 break change，实际上用 new Date 或者 其他工具直接解析一下返回的字符串值就可以得到 Date 对象了。
