### ISSUE TITLE
Previewer在使用的时候报错：[Vue warn]: Error in getter for watcher "imgs"

### ISSUE THREAD

**Issue by Horzen** [airyland/vux#2526]
代码如下：
![image1](https://user-images.githubusercontent.com/32396611/37268175-9f02917c-25ff-11e8-89a7-ea4be8a197f2.png)
![image2](https://user-images.githubusercontent.com/32396611/37268176-a074025c-25ff-11e8-9e06-6b2f6ac80605.png)
![image3](https://user-images.githubusercontent.com/32396611/37268177-a137a964-25ff-11e8-8983-75aeb2d476db.png)
页面报错如下：
![image4](https://user-images.githubusercontent.com/32396611/37268203-b3ec8c0a-25ff-11e8-8538-3fb4e2ea3ea0.png)
点击图片后报错如下：
![image5](https://user-images.githubusercontent.com/32396611/37268216-be83695e-25ff-11e8-80c6-2dbf27a29ad0.png)

哪里出错了呢？求赐教。不胜感激~

**Comment by airyland** [comment]
如何正确提 issue:

1.不要帖代码截图
2.不要帖代码截图
3.不要帖代码截图
4.代码涉及到了业务逻辑，comment.photos 也没有说明示例数据，如果是因为这个不符合文档要求的，不是浪费彼此时间？

**Comment by Horzen** [comment]
好的吧，那我重新提一个。

**Comment by airyland** [comment]
issue 可以编辑后 reopen，请不需要重新创建。
