### ISSUE TITLE
alert组件slot元素的事件不触发问题

### ISSUE THREAD

**Issue by Camellia55** [airyland/vux#2528]
alert组件中嵌入一个子组件，通过v-if控制一开始不显示，当v-if为true显示子组件，点击alert的“确定”按钮，未能触发子组件methods中定义的事件；
代码如下：
父组件：
```js
<div v-transfer-dom>  
    <alert v-model="show" v-if="show" @on-hide="trace()">
        <agreement ref="agreement"></agreement> 
    </alert>
</div>
import agreement from "./agreement"
methods:{
    trace(){      
        this.$refs["agreement"].setTrace();
    }
}
```
子组件(agreement.vue)：
``` vue
<template>
<div> 
    <p>测试用的</p>
</div>
</template>
methods:{  
    setTrace(){
        alert("无法触发");
    }
}

**Comment by airyland** [comment]
1.你说的子组件在 v-if 里，on-hide 里 alert 已经被关闭，确定此时该 ref 还存在？
2.aler 是写错了
3.代码麻烦格式化，这根本不耗费任何时间，只是打几个符号。

**Comment by Camellia55** [comment]
有可能是ref的时候就不存在了，我看看；
不过诡异的一点是：我用confirm组件的话，confirm的on-confirm就能通过refs触发子组件中定义的方法；

**Comment by airyland** [comment]
https://segmentfault.com/markdown

**Comment by airyland** [comment]
假如你连函数都无法调用到，那么 ref 这一句调用必定也报错了，没看 console?
