### ISSUE TITLE
Previewd多组图片预览，放大及缩小的动画总是从第一组图片的位置开始

### ISSUE THREAD

**Issue by chenheng0910** [airyland/vux#2530]
```javascript
<template>
   <div class="imgList">
        <ul>
          <li class="first-item" v-for="(items, index) in information.container.imgList" v-bind:class="{ onePic: isOne }">
            <img class="previewer-demo-img" :src="items.src" alt="" @click="show(index)">
          </li>
        </ul>
        <div v-transfer-dom>
          <previewer ref="previewer" :list="information.container.imgList" :options="options"></previewer>
        </div>
      </div>
</template>

<script>
  import {Previewer, TransferDom} from 'vux'

  export default {
    directives: {
      TransferDom
    },
    components: {
      Previewer
    },
    methods: {
      show (index) {
        this.$refs.previewer.show(index)
      }
    },
    data() {
      return {
        options: {
          getThumbBoundsFn (index) {
            // find thumbnail element
            let thumbnail = document.querySelectorAll('.previewer-demo-img')[index];
            // get window scroll Y
            let pageYScroll = window.pageYOffset || document.documentElement.scrollTop;
            // optionally get horizontal scroll
            // get position of element relative to viewport
            let rect = thumbnail.getBoundingClientRect();
            // w = width
            return {x: rect.left, y: rect.top + pageYScroll, w: rect.width}
            // Good guide on how to get element coordinates:
            // http://javascript.info/tutorial/coordinates
          }
        }
        }
      }
    }
  }
</script>
```
-------------
由于页面的整体布局限制，这里的 ‘information’ 是一个Object，所以不能传index进来， 拜托@airyland 帮忙看一下

**Comment by airyland** [comment]
就上面的代码看的话，我只看到一组图片。

**Comment by chenheng0910** [comment]
是的，这是一个子组件，父级是这样的：
```
<div v-for="(item, i) in recommendArr">
          <div class="activityBanner" v-if="item.dataType === '1'">
            <activityCardOne :dataList="item"></activityCardOne>
          </div>
          <div v-if="item.dataType === '2'">
            <comCard :buildList1="item"></comCard>
          </div>
 </div>
```

**Comment by chenheng0910** [comment]
页面布局限制的原因，我把循环写到了外面

**Comment by airyland** [comment]
正是循环导致了你的问题。

``` js
let thumbnail = document.querySelectorAll('.previewer-demo-img')[index];
```

这一句无法局限到当前子组件，建议你为子组件生成一个唯一的 id，限制到当前组件内图片。

**Comment by airyland** [comment]
再考虑了下，还可以更简单

`this.$el.querySelectorAll('.previewer-demo-img')[index]`

**Comment by chenheng0910** [comment]
ok，多谢了，我测试一下先。

**Comment by chenheng0910** [comment]
@airyland 多谢，问题完美解决了 。稍后贴上代码。

**Comment by chenheng0910** [comment]
```
<template>
   <div class="imgList">
        <ul>
          <li class="first-item" v-for="(items, index) in information.container.imgList" v-bind:class="{ onePic: isOne }">
            <img class="previewer-demo-img" :src="items.src" alt="" @click="show(index)">
          </li>
        </ul>
        <div v-transfer-dom>
          <previewer ref="previewer" :list="information.container.imgList" :options="options(ind)"></previewer>
        </div>
      </div>
</template>
<script>
  import {Previewer, TransferDom} from 'vux'

  export default {
    directives: {
      TransferDom
    },
    components: {
      Previewer
    },
    methods: {
      show (index) {
        this.$refs.previewer.show(index)
      },
      options (ind) {
        let that = this;
        return {
          getThumbBoundsFn (index) {
            // find thumbnail element
             let thumbnail = that.$el.querySelectorAll('.previewer-demo-img')[index];
            // get window scroll Y
            let pageYScroll = window.pageYOffset || document.documentElement.scrollTop;
            // optionally get horizontal scroll
            // get position of element relative to viewport
            let rect = thumbnail.getBoundingClientRect();
            // w = width
            return {x: rect.left, y: rect.top + pageYScroll, w: rect.width}
            // Good guide on how to get element coordinates:
            // http://javascript.info/tutorial/coordinates
          }
        }
      }
    }
  }
</script>
```
------
这里的 options (ind) 是随便传一个参数，只为了后面methods里面可以改变this的指向问题。

**Comment by bennyli519** [comment]
```
      <!-- 图片 -->
      <div class="m-pics">
        <div class="pic-wrapper" v-for="(i,index) in momentsList.DynamicAlbumList">
            <!-- <img v-gallery="item.Id" :src="i.FileCode" alt=""> -->
             <img class="previewer-demo-img" :src="i.FileCode"  @click="show(index)">
        </div>
        <div v-transfer-dom>
          <previewer :list="item.DynamicAlbumList" ref="previewer" :options="options(ind)" ></previewer>
        </div>
      </div>
import { Previewer, TransferDom } from 'vux'
  export default {
    name: 'DnamicMoments',
    directives: {
      TransferDom
    },
    components: {
      Previewer
    },
    data () {
      return {
        momentsList: [//实时动态
            {
                DynamicAlbumList: [
                  {
                    DynamicId: 17630,
                    FileCode: "https://attachment.met365.com/activity/o_1c3vnv94a1o9d9rp1cjn1fof3sbb.jpg?Expires=1556351948&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=POqm%2FDP%2BOvH0IjQJS5K1GIMM0Z8%3D&x-oss-process=style%2Factivity-large",
                    Id: 16251,
                    OriginalFileCode: "https://attachment.met365.com/activity/o_1cc08odlh12cl1s24d42j7s1f9cb.jpg?Expires=1556351947&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=CrcTlyoEM8MCLCgFZfxI%2BBxB1JI%3D",
                  },
                ]
            },
            {
                DynamicAlbumList: [
                  {
                    DynamicId: 17630,
                    FileCode: "https://attachment.met365.com/activity/o_1cc08odlh12cl1s24d42j7s1f9cb.jpg?Expires=1556351947&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=Dbdl%2BVSuagUhs5%2Brtu1vbadxW5Q%3D&x-oss-process=style%2Factivity-large",
                    Id: 16251,
                    OriginalFileCode: "https://attachment.met365.com/activity/o_1cc08odlh12cl1s24d42j7s1f9cb.jpg?Expires=1556351947&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=CrcTlyoEM8MCLCgFZfxI%2BBxB1JI%3D",
                  },
                  {
                    DynamicId: 17630,
                    FileCode: "https://attachment.met365.com/activity/o_1cc08ojf182d10gf1uuk6e7cl7g.jpg?Expires=1556351948&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=gdJQUXaSnLXyOJOsqnhs3ZXd9Dc%3D&x-oss-process=style%2Factivity-large",
                    Id: 16251,
                    OriginalFileCode: "https://attachment.met365.com/activity/o_1cc08ojf182d10gf1uuk6e7cl7g.jpg?Expires=1556351948&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=JBKOJECAQob5iIXzFanYVLMTWYs%3D",
                  }
                ],
            },
            {
                DynamicAlbumList: [
                  {
                    DynamicId: 17630,
                    FileCode: "https://attachment.met365.com/activity/o_1cc08odlh12cl1s24d42j7s1f9cb.jpg?Expires=1556351947&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=Dbdl%2BVSuagUhs5%2Brtu1vbadxW5Q%3D&x-oss-process=style%2Factivity-large",
                    Id: 16251,
                    OriginalFileCode: "https://attachment.met365.com/activity/o_1cc08odlh12cl1s24d42j7s1f9cb.jpg?Expires=1556351947&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=CrcTlyoEM8MCLCgFZfxI%2BBxB1JI%3D",
                  },
                  {
                    DynamicId: 17630,
                    FileCode: "https://attachment.met365.com/activity/o_1c711nit8q4e3o11km54861v82b.jpg?Expires=1556351948&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=eaQ06SjNwxGnGDqny3ua5UCS%2F%2B4%3D&x-oss-process=style%2Factivity-large",
                    Id: 16251,
                    OriginalFileCode: "https://attachment.met365.com/activity/o_1cc08ojf182d10gf1uuk6e7cl7g.jpg?Expires=1556351948&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=JBKOJECAQob5iIXzFanYVLMTWYs%3D",
                  },
                  {
                    DynamicId: 17630,
                    FileCode: "https://attachment.met365.com/activity/o_1c711nit8q4e3o11km54861v82b.jpg?Expires=1556351948&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=eaQ06SjNwxGnGDqny3ua5UCS%2F%2B4%3D&x-oss-process=style%2Factivity-large",
                    Id: 16251,
                    OriginalFileCode: "https://attachment.met365.com/activity/o_1cc08odlh12cl1s24d42j7s1f9cb.jpg?Expires=1556351947&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=CrcTlyoEM8MCLCgFZfxI%2BBxB1JI%3D",
                  },
                  {
                    DynamicId: 17630,
                    FileCode: "https://attachment.met365.com/activity/o_1c711nit8q4e3o11km54861v82b.jpg?Expires=1556351948&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=eaQ06SjNwxGnGDqny3ua5UCS%2F%2B4%3D&x-oss-process=style%2Factivity-large",
                    Id: 16251,
                    OriginalFileCode: "https://attachment.met365.com/activity/o_1cc08ojf182d10gf1uuk6e7cl7g.jpg?Expires=1556351948&OSSAccessKeyId=mzjdvqt60KqNK6Xh&Signature=JBKOJECAQob5iIXzFanYVLMTWYs%3D",
                  }
                ],
            },
        ], 
        myMomentsList: [], //我的动态
      }
    },
    created(){
      //插入(评论展示状态)字段
      this.momentsList.forEach((v,k)=>{
       this.momentsList[k].showComment = false
      })
      console.log(this.momentsList)
  
    },
    methods: {
       options (ind) {
        let that = this;
        return {
          getThumbBoundsFn (index) {
            // find thumbnail element
             let thumbnail = that.$el.querySelectorAll('.previewer-demo-img')[index];
            // get window scroll Y
            let pageYScroll = window.pageYOffset || document.documentElement.scrollTop;
            // optionally get horizontal scroll
            // get position of element relative to viewport
            let rect = thumbnail.getBoundingClientRect();
            // w = width
            return {x: rect.left, y: rect.top + pageYScroll, w: rect.width}
            // Good guide on how to get element coordinates:
            // http://javascript.info/tutorial/coordinates
          }
        }
      },
      show (index) {
        console.log(this.$refs.previewer)
        this.$refs.previewer.show(index)
      },
      //评论
      toggleComment(item){
        item.showComment = !item.showComment;
        let list = this.momentsList;
        this.momentsList = Object.assign([], list);
        console.log(this.momentsList)
        console.log(item.showComment)
      },
      //点赞
      toggleFavorite(item){
        item.IsLike = !item.IsLike;
        if(item.IsLike){
          item.LikeTimes++;
        }else{
          item.LikeTimes--;
        }
      }
    }
  }
</script>
```
求救~~~试了一天了 没啥效果。如果写死的话是可以实现一个previewr对应一个options。但是如果是循环该怎么实现呢。类似微信朋友圈图片那种效果。。

**Comment by chenheng0910** [comment]
@jerryli519 你的这种循环可以参考下issues#1948

**Comment by chenheng0910** [comment]
[https://github.com/airyland/vux/issues/1948]( )

**Comment by Breezes1993** [comment]
<template>
	<div class="contentDiv">
		<ul>
			<li v-for="(list,index) in lists " class="deallist" v-bind:key="list.CODE_VAL">
				<p>{{list.ATTR_NAME}}</p>
				<div>
					<img v-if="list.switchOn"  src="../../../assets/img/securityCheckImg/switchOn.png" class="switch" @click="switchAction(list)"/>
					<img v-else src="../../../assets/img/securityCheckImg/switchOff.png" class="switch" @click="switchAction(list)"/>
					<img src="../../../assets/img/securityCheckImg/camera.png" class="camera" @click="clickPhoto($event,index)"/>
					<div>
						<img v-if="list.photoList.length>0" @click="showImg(index)" :src="list.photoList[0].src" class="photo"/>
						<img v-else  @click="showImg(index)"  src="../../../assets/img/securityCheckImg/photo.png" class="photo"/>
						<p v-if="list.photoList.length==0" class="photoNum">0</p>
						<p v-else class="photoNum">{{list.photoList.length}}</p>
					</div>
				</div>
			</li>
		</ul>
		
		<previewer ref="previewer" :list="previewerList" :options="options">
		
		</previewer>
		<div>
			<img class="previewer-demo-img" v-for="(item, index) in list" :src="item.src" width="100" @click="show(index)">
			<div v-transfer-dom>
			<previewer :list="list" ref="previewer2" :options="options" @on-index-change="logIndexChange"></previewer>
			</div>
		</div>
	</div>
</template>

<script>
	import { addScRstDtl, delScRstDtl, getPhotoList} from "@/utils/securityProjectService"
	import { takePhoto,PhotoType } from "@/utils/public"
	import { Previewer,TransferDom } from 'vux'
	export default {
		props:{
			lists: {
				type: Array,
				required: true
			}
		},
		directives: {
			TransferDom
		},
		components: {
			Previewer
		},
		data: function(){
			return {
				list: [{
					msrc: './static/img/100.jpg',
					src: './static/img/100.jpg',
					w: 800,
					h: 400
				},
				{
					msrc: './static/img/100.jpg',
					src: './static/img/100.jpg',
					w: 1200,
					h: 900
				}, {
					msrc: './static/img/100.jpg',
					src: './static/img/100.jpg'
				}],
				previewerList: [],
				options: {
					isClickableElement: function (el) {
						return /previewer-delete-icon/.test(el.className)
					},
					getThumbBoundsFn (index) {
						// find thumbnail element
						let thumbnail = document.querySelectorAll('.previewer-demo-img')[index]
						// get window scroll Y
						let pageYScroll = window.pageYOffset || document.documentElement.scrollTop
						// optionally get horizontal scroll
						// get position of element relative to viewport
						let rect = thumbnail.getBoundingClientRect()
						// w = width
						return {x: rect.left, y: rect.top + pageYScroll, w: rect.width}
						// Good guide on how to get element coordinates:
						// http://javascript.info/tutorial/coordinates
					}
				},
			}
		},
		mounted() {	
			let _this = this;
			console.log("mouted的lists"+ JSON.stringify(_this.lists));
			// _this.lists.forEach(element => {
			// 	element.BUSY_NO = element.ATTR_CODE;
			// });
			// var app_no = localStorage.getItem("APP_NO");
			// var cons_no = localStorage.getItem("CONS_NO");
			// getPhotoList(_this.lists,app_no,cons_no,PhotoType.securityProjectDtl,function(data){
			// 	// _this.lists.splice(0,0);
			// 	_this.lists = JSON.parse(JSON.stringify(data));
			// 	_this.lists.forEach(element => {
			// 		_this.$set(element,"photoList",element.photoList);
			// 	});
			// })
			// console.log(1)
		},
		methods: {
			logIndexChange (arg) {
				console.log(arg)
			},
			show (index) {
				this.$refs.previewer2.show(index)
			},
			showImg(index) {
				let _this = this;
				console.log(_this.lists[index]);
				console.log(_this.previewerList);
				_this.previewerList = [];
				_this.lists[index].photoList.forEach(element => {
					_this.previewerList.push(element);
				});
				console.log(_this.previewerList);
				_this.$nextTick(function(){
					if(_this.previewerList.length>0){
						_this.$refs.previewer.show(0);
					}
					
				});
				
			},
			switchAction:function(list){
				var _this = this;
				//需要APP_NO CONS_NO 获取对应的TS_DTL，再获取SC_PDTL_ID
				//SC_PDTL_ID SC_RST_ID(服务端给的值，本地不处理) SC_RST_NO(11+任务编号+日期时分秒)
				if(list.switchOn){
					//删除一条SECURITY_SC_RST_DTL隐患信息记录
					delScRstDtl(list.ATTR_CODE,function(msg){
						_this.$vux.toast.text(msg);
					})
				}else{
					//新增一条—SECURITY_SC_RST_DTL隐患信息记录s
					addScRstDtl(list,function(successCall){
						console.log(successCall);//successCall是中文，结果信息
					});
				}
				this.$set(list, 'switchOn', !list.switchOn);

			},
			deleScRsDtl: function(){

			},
			changeLidt: function(val) {
				this.lists = val;
			},
			clickPhoto: function(thisTake,index){
				// console.log(thisTake);
				takePhoto(localStorage.getItem("APP_NO"),localStorage.getItem("CONS_NO"),PhotoType.securityProjectDtl,this.lists[index].ATTR_CODE,function(successCall){
					$(thisTake.target).parent().parent().find(".photo").attr("src",successCall.path);
					lists[index].photoList.push({"src":"file://"+successCall.path});
				},function(errorCall){
					console.log("失败！")
					console.log(errorCall);
				});
			}

		}
	}
</script>

<style scoped lang="less">
	.contentDiv {
		.deallist {
			border-bottom: 1px solid #D9DAEB;
			height: 1.1111rem;
			background-color: white;
			display: flex;
			justify-content: space-between;
			align-items: center;
			padding-left: 0.2083rem;
			p {
				font-size: 0.3888rem;
				color: #444444;
			}
			div {
				display: flex;
				align-items: center;
				.switch {
					width: 1.2777rem;
					height: 0.8333rem;
				}
				.camera {
					width: 0.5rem;
					height: 0.5rem;
					margin-left: 0.4166rem;
				}
				div {
					.photo {
						width: 0.5rem;
						height: 0.5rem;
						margin-left: 0.4166rem;
					}
					.photoNum {
						margin-left: -0.2083rem;
						margin-top: -0.2777rem;
						margin-right: 0.1666rem;
						font-size: 0.2777rem;
						display: flex;
						align-items: center;
						justify-content: center;
						color: white;
						width: 0.3888rem;
						height: 0.3888rem;
						background: url(../../../assets/img/securityCheckImg/photoNum.png) no-repeat center;
						background-size: 0.3888rem 0.3888rem;
					}
				}
			}
		}
	}
</style>


预览的图片的previewd只会出现一次。。。

**Comment by Breezes1993** [comment]
`<template>
	<div class="contentDiv">
		<ul>
			<li v-for="(list,index) in lists " class="deallist" v-bind:key="list.CODE_VAL">
				<p>{{list.ATTR_NAME}}</p>
				<div>
					<img v-if="list.switchOn"  src="../../../assets/img/securityCheckImg/switchOn.png" class="switch" @click="switchAction(list)"/>
					<img v-else src="../../../assets/img/securityCheckImg/switchOff.png" class="switch" @click="switchAction(list)"/>
					<img src="../../../assets/img/securityCheckImg/camera.png" class="camera" @click="clickPhoto($event,index)"/>
					<div>
						<img v-if="list.photoList.length>0" @click="showImg(index)" :src="list.photoList[0].src" class="photo"/>
						<img v-else  @click="showImg(index)"  src="../../../assets/img/securityCheckImg/photo.png" class="photo"/>
						<p v-if="list.photoList.length==0" class="photoNum">0</p>
						<p v-else class="photoNum">{{list.photoList.length}}</p>
					</div>
				</div>
			</li>
		</ul>
		
		<previewer ref="previewer" :list="previewerList" :options="options">
		
		</previewer>
		<div>
			<img class="previewer-demo-img" v-for="(item, index) in list" :src="item.src" width="100" @click="show(index)">
			<div v-transfer-dom>
			<previewer :list="list" ref="previewer2" :options="options" @on-index-change="logIndexChange"></previewer>
			</div>
		</div>
	</div>
</template>

<script>
	import { addScRstDtl, delScRstDtl, getPhotoList} from "@/utils/securityProjectService"
	import { takePhoto,PhotoType } from "@/utils/public"
	import { Previewer,TransferDom } from 'vux'
	export default {
		props:{
			lists: {
				type: Array,
				required: true
			}
		},
		directives: {
			TransferDom
		},
		components: {
			Previewer
		},
		data: function(){
			return {
				list: [{
					msrc: './static/img/100.jpg',
					src: './static/img/100.jpg',
					w: 800,
					h: 400
				},
				{
					msrc: './static/img/100.jpg',
					src: './static/img/100.jpg',
					w: 1200,
					h: 900
				}, {
					msrc: './static/img/100.jpg',
					src: './static/img/100.jpg'
				}],
				previewerList: [],
				options: {
					isClickableElement: function (el) {
						return /previewer-delete-icon/.test(el.className)
					},
					getThumbBoundsFn (index) {
						// find thumbnail element
						let thumbnail = document.querySelectorAll('.previewer-demo-img')[index]
						// get window scroll Y
						let pageYScroll = window.pageYOffset || document.documentElement.scrollTop
						// optionally get horizontal scroll
						// get position of element relative to viewport
						let rect = thumbnail.getBoundingClientRect()
						// w = width
						return {x: rect.left, y: rect.top + pageYScroll, w: rect.width}
						// Good guide on how to get element coordinates:
						// http://javascript.info/tutorial/coordinates
					}
				},
			}
		},
		mounted() {	
			let _this = this;
			console.log("mouted的lists"+ JSON.stringify(_this.lists));
			// _this.lists.forEach(element => {
			// 	element.BUSY_NO = element.ATTR_CODE;
			// });
			// var app_no = localStorage.getItem("APP_NO");
			// var cons_no = localStorage.getItem("CONS_NO");
			// getPhotoList(_this.lists,app_no,cons_no,PhotoType.securityProjectDtl,function(data){
			// 	// _this.lists.splice(0,0);
			// 	_this.lists = JSON.parse(JSON.stringify(data));
			// 	_this.lists.forEach(element => {
			// 		_this.$set(element,"photoList",element.photoList);
			// 	});
			// })
			// console.log(1)
		},
		methods: {
			logIndexChange (arg) {
				console.log(arg)
			},
			show (index) {
				this.$refs.previewer2.show(index)
			},
			showImg(index) {
				let _this = this;
				console.log(_this.lists[index]);
				console.log(_this.previewerList);
				_this.previewerList = [];
				_this.lists[index].photoList.forEach(element => {
					_this.previewerList.push(element);
				});
				console.log(_this.previewerList);
				_this.$nextTick(function(){
					if(_this.previewerList.length>0){
						_this.$refs.previewer.show(0);
					}
					
				});
				
			},
			switchAction:function(list){
				var _this = this;
				//需要APP_NO CONS_NO 获取对应的TS_DTL，再获取SC_PDTL_ID
				//SC_PDTL_ID SC_RST_ID(服务端给的值，本地不处理) SC_RST_NO(11+任务编号+日期时分秒)
				if(list.switchOn){
					//删除一条SECURITY_SC_RST_DTL隐患信息记录
					delScRstDtl(list.ATTR_CODE,function(msg){
						_this.$vux.toast.text(msg);
					})
				}else{
					//新增一条—SECURITY_SC_RST_DTL隐患信息记录s
					addScRstDtl(list,function(successCall){
						console.log(successCall);//successCall是中文，结果信息
					});
				}
				this.$set(list, 'switchOn', !list.switchOn);

			},
			deleScRsDtl: function(){

			},
			changeLidt: function(val) {
				this.lists = val;
			},
			clickPhoto: function(thisTake,index){
				// console.log(thisTake);
				takePhoto(localStorage.getItem("APP_NO"),localStorage.getItem("CONS_NO"),PhotoType.securityProjectDtl,this.lists[index].ATTR_CODE,function(successCall){
					$(thisTake.target).parent().parent().find(".photo").attr("src",successCall.path);
					lists[index].photoList.push({"src":"file://"+successCall.path});
				},function(errorCall){
					console.log("失败！")
					console.log(errorCall);
				});
			}

		}
	}
</script>

<style scoped lang="less">
	.contentDiv {
		.deallist {
			border-bottom: 1px solid #D9DAEB;
			height: 1.1111rem;
			background-color: white;
			display: flex;
			justify-content: space-between;
			align-items: center;
			padding-left: 0.2083rem;
			p {
				font-size: 0.3888rem;
				color: #444444;
			}
			div {
				display: flex;
				align-items: center;
				.switch {
					width: 1.2777rem;
					height: 0.8333rem;
				}
				.camera {
					width: 0.5rem;
					height: 0.5rem;
					margin-left: 0.4166rem;
				}
				div {
					.photo {
						width: 0.5rem;
						height: 0.5rem;
						margin-left: 0.4166rem;
					}
					.photoNum {
						margin-left: -0.2083rem;
						margin-top: -0.2777rem;
						margin-right: 0.1666rem;
						font-size: 0.2777rem;
						display: flex;
						align-items: center;
						justify-content: center;
						color: white;
						width: 0.3888rem;
						height: 0.3888rem;
						background: url(../../../assets/img/securityCheckImg/photoNum.png) no-repeat center;
						background-size: 0.3888rem 0.3888rem;
					}
				}
			}
		}
	}
</style>`
预览的图片的previewd只会出现一次。。。

**Comment by Breezes1993** [comment]
有人遇到过，第一次显示previewd可以显示，第二次就没反应了吗

**Comment by azhengyongqin** [comment]
@chenheng0910  请问这个方法是哪里来的 `getThumbBoundsFn(index)`,为什么我一直报这个方法未定义:
![image](https://user-images.githubusercontent.com/18138282/50627704-b9881300-0f6f-11e9-8651-8c27b7578af6.png)

**Comment by kinder1995** [comment]
你的options为什么是写在methods里面的？另外options传进来的ind又是什么？

**Comment by kinder1995** [comment]
淘宝评价那样的功能你们知道怎么实现吗？搞了好久没搞出来~
