### ISSUE TITLE
vux 在安卓4.4 webview 页面样式问题(该系统下自带浏览器 打开vux demo页面同样出现)

### ISSUE THREAD

**Issue by xiaowanhashi** [airyland/vux#2531]
环境(安卓4.4 , 自带浏览器和内嵌到app的webview页面)

问题：
  1.页面有关css3的样式显示错乱，包括rotate translate等失效
  2.Actionsheet  组件会默认显示且无法关闭 
  3.所有的弹出层都没有遮罩
  4.很多固定定位的元素位置都会偏移
跑vux的官网 demo页面会遇到同样的问题 不知道作者有没有做这块的兼容，

**Comment by airyland** [comment]
Android 4.4 不至于这么渣。微信里呢？

**Comment by xiaowanhashi** [comment]
微信里面正常  
![Uploading 199546764811285297.jpg…]()

![Uploading 708093919314817760.jpg…]()

**Comment by xiaowanhashi** [comment]
![_20180312173520](https://user-images.githubusercontent.com/16890800/37275863-4af531cc-261b-11e8-8aa5-05a99dbfdecd.jpg)
![_20180312173530](https://user-images.githubusercontent.com/16890800/37275886-58064734-261b-11e8-8ffc-6ba40020ea73.jpg)

**Comment by iesuchengdezuipiezi** [comment]
cool

**Comment by airyland** [comment]
目测应该是在 vue-loader 某个版本后，autoprefix 规则和压缩规则不生效了，待检查。

**Comment by airyland** [comment]
合并到 #2506

**Comment by airyland** [comment]
检查 package 里的 browsers，如果过高，修改为下面配置试试。

``` json
"browserslist": [
    "iOS >= 7",
    "Android >= 4.1"
 ]
```
