### ISSUE TITLE
建议添加删除所有cookie功能

### ISSUE THREAD

**Issue by xieyuanbin1** [airyland/vux#2533]
cookie工具中没有删除所有功能，只能单个删除

**Comment by airyland** [comment]
其实获取 document.cookie 循环一下 remove 就行了，删除所有 cookie 不是通用需求，暂时不会添加。

1.出于安全性考虑，现在 web 应用一般 cookie 都是 http(s) only，js 并无法获取
2.我们并不想不小心删除谷歌统计，百度统计的统计 cookie

建议通过请求服务端接口来实现。
