### ISSUE TITLE
页面引入组件时报"./node_modules/vux/src/mixins/uuid.js里语法是es6语法ie不兼容，请问怎么解决啊

### ISSUE THREAD

**Issue by one-dragon** [airyland/vux#2534]
/***/ "./node_modules/vux/src/mixins/uuid.js":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony default export */ __webpack_exports__["a"] = ({
  created() {
    this.uuid = Math.random().toString(36).substring(3, 8);
  }
});

**Comment by airyland** [comment]
1. 不支持 pc 更不会支持 ie
2. es6 语法会被 babel 转换成一般浏览器兼容的代码，假如出错，请先检查自己项目配置。
