### ISSUE TITLE
checker组件的问题

### ISSUE THREAD

**Issue by moRanou** [airyland/vux#2535]
您好，辛苦了，我想问问，动态生成的双层循环checker组件可以加默认选项吗，也就是checker-item是循环生成的，然后我外层的checker也是循环遍历生成的，这样的话怎么样也设置不到默认选项，有什么办法吗？
 真的很不好意思

**Comment by airyland** [comment]
no code no help.

**Comment by moRanou** [comment]
<checker v-for="item in goodsInfoList.propertys" :key="item.id" class="ul" radio-required default-item-class="li" selected-item-class="li_selected">
                <p>{{item.name}}</p>
                <checker-item :value="list" @on-item-click="onItemClick" v-for="(list, index) in item.list"  :key="list.id">
                  {{list.name}}
                </checker-item>
              </checker>
不好意思，打扰了，这是我的代码，正如您现在所看见的，我现在是双层循环，然后我想用v-model去控制初始选项，但选不了

**Comment by airyland** [comment]
这是 vue 的使用问题和 vux 没什么关系。在 goodsInfoList.propertys 每一项里添加一个 value 属性用以绑定就行了吧。`v-model="item.value"`

代码请格式化，谢谢。
