### ISSUE TITLE
是否考虑结合mpvue,推出小程序版本的VUX

### ISSUE THREAD

**Issue by tuhe32** [airyland/vux#2537]
是否考虑结合mpvue,推出小程序版本的VUX

请大家先学习如何格式多行代码：https://segmentfault.com/markdown, 不要浪费维护者时间，否则账号将被 block 无法再提 issue。

**Comment by airyland** [comment]
暂无计划。

**Comment by LiangFuzhi** [comment]
若果适配mpvue那就厉害了。

**Comment by greedying** [comment]
同样在调研这方面。

**Comment by jinggoing** [comment]
似乎跟mpvue不兼容，引入后编译有问题

**Comment by Jiiiiiin** [comment]
还是适配 vue-cli3比较急吧。
