### ISSUE TITLE
link属性bug

### ISSUE THREAD

**Issue by huangmin16** [airyland/vux#2538]
使用link时无法跳转当前路由下的子路由,如 从/home 下跳转到/home/first,路由跳转，页面无响应

**Comment by airyland** [comment]
明显无此限制，先确定你父子路由功能写正确了。因为这完全可能是由于你在父页面里没有写 router-view 导致子路由没渲染出来，排查方法是你直接打开 /home/first 看是不是和 /home 一模一样。

**Comment by huangmin16** [comment]
首先router-view写了，然后直接打开 /home/first的确无反应，但是使用$router.replace跳转是可以的

**Comment by huangmin16** [comment]
然后我从home下用link跳转到login是可以的

**Comment by airyland** [comment]
直接打开路由无反应说明不是 link 的 bug 了，link 本身也就是调用 $route.push 而已。按照你说的，估计 $router.push 跳转也是没反应的。检查业务逻辑吧，如果一个组件被重用了，而你没有根据参数做相应处理是不会有变化的。

**Comment by huangmin16** [comment]
好的，感谢您的帮助。
