### ISSUE TITLE
component range out of max

### ISSUE THREAD

**Issue by cxjava** [airyland/vux#254]
访问demo的最新版本 https://vux.li/#!/component/range

demo 最新版本

android chrome 51.0.2704.81

No Code

期望：range滑动到了最大值，那么页面应该显示最大值
实际：页面的值超过了最大值100

![qq 20160607104713](https://cloud.githubusercontent.com/assets/802316/15844653/b4959b3a-2c9e-11e6-90c6-ece2635e11a2.png)

**Comment by airyland** [comment]
有注意到，是由于左侧数字变化时，影响了右侧的宽度，导致有问题。
