### ISSUE TITLE
作者提供的vue2模板在Windows下无法通过nginx配置本地域名访问？

### ISSUE THREAD

**Issue by TheSixer** [airyland/vux#2542]
配置本地域名访问需要加端口号，并且在webpack配置中加上disableHostCheck: true

**Comment by airyland** [comment]
webpack 开发配置、nginx 配置和 vux 并没有关系。
并不知道你的需求，但是开发模式下没有必要使用域名访问，所谓的加端口号在项目相关配置里是可以改成 80 的。
