### ISSUE TITLE
官网的demo 出错了，微信等app都显示错误

### ISSUE THREAD

**Issue by kson34** [airyland/vux#2547]
扫码后好多事例都是出错，尤其是时间的控件，好几天了

**Comment by airyland** [comment]
我看 datetime 是正常的，哪些出错？

**Comment by bobevans-commits** [comment]
[demo全部错了]([url](url)) 
![image](https://user-images.githubusercontent.com/23229377/37692723-70295c44-2cf5-11e8-9bca-babc81b6f497.png)

**Comment by kson34** [comment]
IPHONE 7plus IOS 10.3.3 Safari 官网demo 在IOS全白屏，微信正常。
