### ISSUE TITLE
alert组件可以有两个按钮吗

### ISSUE THREAD

**Issue by qiwanshu** [airyland/vux#2548]
请大家先学习如何格式多行代码：https://segmentfault.com/markdown, 不要浪费维护者时间，否则账号将被 block 无法再提 issue。

**Comment by qiwanshu** [comment]
学习的过程中发现alert组件只有一个按钮模式，但是现在需要有两个按钮，类似取消 确定这样，点击不同的按钮进行不同的操作，求帮助

**Comment by lichunqiang** [comment]
[confirm](https://vux.li/demos/v2/#/component/confirm) 不行么
