### ISSUE TITLE
popup组件与其他input组件交互不流畅的问题

### ISSUE THREAD

**Issue by killdada** [airyland/vux#2549]
当在手机端先点击一个input的时候，键盘弹起，然后点击 一个按钮打开popup的时候，popup先显示出来，同时键盘存在，然后键盘再消失，这个过渡视觉效果有点差。。目前想到的做法是延迟若干毫秒展示这个popup，大概就是键盘消失需要的时间。。这里还应该判断键盘是否已经展开，展开的时候才设置延迟。。键盘是否展开，键盘消失需要的时间目前应该可以试着用cordova插件去实现。不过觉得都有点麻烦，有没有比较好一点思路处理？

**Comment by airyland** [comment]
键盘如何消失这个是浏览器的处理，popup 并不能知道有没有打开键盘。cordova 插件是 app 端的，本身也不能作为 web 端的解决文案。

在什么场景下，会在键盘弹出时再点击一个按钮打开 popup?

**Comment by killdada** [comment]
![qq 20180322102238](https://user-images.githubusercontent.com/16487810/37747618-13f9bd1c-2dbb-11e8-8076-1641bd884e02.png)
谢谢你的回答，点击银行卡号之后，再点击开户银行会打开一个popup,app是基于cordova的，我这边自己实现吧，就是想问问有没有其他好点的思路。再次谢谢你

**Comment by Jiiiiiin** [comment]
真不理解这个需求

**Comment by Jiiiiiin** [comment]
我们也是用vux实现的一个手机银行APP，自建的jsbridge方案，目前处于内测阶段，安卓分下载地址  https://fir.im/45cw?release_id=5ab24ce4ca87a86dd431daf1

webview会后期进一步调优，感觉vux已经做的很良心了，大家还是不要把自己的业务放到这里比较好。:grinning:

**Comment by airyland** [comment]
针对你所说的场景，就我接触过的应用，目前都能做到根据卡号识别银行，如果能少一步选择会更友好。我的思路是如果不能完美解决这个交互那就把这个交互干掉。。

**Comment by Jiiiiiin** [comment]
根据卡bin，你自己检索，或者集成ocr扫卡功能。
