### ISSUE TITLE
vux2.X构建时出现错误，开发模式下正常运行

### ISSUE THREAD

**Issue by ap13147** [airyland/vux#2552]
ERROR in ./src/main.js
Module build failed: TypeError: Cannot read property 'useVuxUI' of undefined
    at Object.module.exports (C:\weixin-vue\node_modules\vux-loader\src\js-loader.js:12:25)

在网上没有搜到类似问题，我的怎么会这样，配置问题？

**Comment by weiweiwei256** [comment]
可以试试,我是开发时不行.找了好久.
引入   plugins
     new webpack.optimize.CommonsChunkPlugin({
        name: "vendors",
        // filename: 'assets/js/vendors.js',
        chunks: chunks, // The constant chunks is used here  //['app', 'home', 'detail']的公共引用部分
        minChunks: chunks.length
      }),

const chunks =["app"]
 entry: { "app": "./.studio/runtime/main.js" },
