### ISSUE TITLE
用着好好的重启就报这个  删除node-modules再装还是不行

### ISSUE THREAD

**Issue by infyzz** [airyland/vux#2554]
` error  in ./src/components/global/realnameUpload.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Volumes/dev/witkey/web/webapp2/node_modules/_extract-text-webpack-plugin@2.1.2@extract-text-webpack-plugin/loader.js:25:9)

 @ ./src/components/global/realnameUpload.vue 4:2-522
 @ ./node_modules/_babel-loader@7.1.4@babel-loader/lib!./node_modules/_vux-loader@1.2.2@vux-loader/src/script-loader.js!./node_modules/_vux-loader@1.2.2@vux-loader/src/script-loader.js!./node_modules/_vue-loader@13.7.1@vue-loader/lib/selector.js?type=script&index=0!./src/views/ucenter/realname/index.vue
 @ ./src/views/ucenter/realname/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://192.168.88.66:8080 webpack/hot/dev-server ./src/main.js
`

**Comment by airyland** [comment]
这个问题和 webpack 相关，先搜索下报错，目测问题是你修改了 webpack 配置造成的。

**Comment by infyzz** [comment]
很奇怪 就是突然出现的

**Comment by airyland** [comment]
就上面的信息无法提供任何帮助，请建 repo 重现。
