### ISSUE TITLE
popup在ios的webview中问题

### ISSUE THREAD

**Issue by whitetrident** [airyland/vux#2555]
很奇怪，在安卓中没有问题，项目中有多次使用到，就是说在其他页面都是没有问题的，但是在ios中出现下面情形：
![image](https://user-images.githubusercontent.com/29626161/37820439-912c87d2-2ebb-11e8-98b0-0fffbf9e48a7.png)
感觉在这个组件渲染的时候，把遮罩后放上去了，改弹层的层级，没有效果，后面只能不显示遮罩。

**Comment by airyland** [comment]
这么提 issue 是觉得我可以在看到截图无法重现的情况下就帮你猜原因？麻烦您从维护者的角度稍微考虑一下，麻烦您提 issue 时稍微看一下提示。

![image](https://user-images.githubusercontent.com/559179/37821504-b9acf540-2ebe-11e8-8671-f0dbbf7532e8.png)
