### ISSUE TITLE
stricky吸顶，距离还有很远就吸顶了，怎么设置触发吸顶的位置啊

### ISSUE THREAD

**Issue by ranxin001** [airyland/vux#2559]
版本：2.8.0以上

代码：
<img src='http://www.cnwif.cn/my_staticFile/images/dsadsa.png' />

不懂这个吸顶怎么了。。。。
<img src='http://www.cnwif.cn/my_staticFile/images/cadsa.png' />

**Comment by airyland** [comment]
代码不要截图。有必要的东西请说明，比如是否真的用了 view-box 组件，并且 offset 到底绑定了什么值?补充后重开。
