### ISSUE TITLE
address组件的问题

### ISSUE THREAD

**Issue by renjian93** [airyland/vux#256]
### 0.1.0-rc2

address组件，取消确定按钮没有效果，因为是双向绑定数据所以不管确认取消值都会改变。而且这个组件可以默认为空吗，现在所有默认值为第一个地址。实际使用中地址可能是非必填的，可能为空。

**Comment by airyland** [comment]
建议已收

**Comment by zhuqiuyang** [comment]
如果能在使用Address组件时，能自己修改AddressChinaData，就更好了。
因为不同业务需求 对地理位置的要求可能稍有不同，这样只改数据就可以了。

**Comment by airyland** [comment]
@zhuqiuyang 并没有限制一定需要用Vux内置的地址数据，list属性是可以自由赋值的，只要按照一样的格式就可以。

**Comment by zhuqiuyang** [comment]
@airyland  是的，so cool。我刚才试了一下才发现，可以手动设置column值，子列的parent属性对应父列的value就可以联动，是这样吗。

**Comment by airyland** [comment]
@zhuqiuyang 是的，Address依赖于Picker，你可以看下Picker的例子。

**Comment by zhuqiuyang** [comment]
@airyland 好的，正在学习，谢谢啦~
