### ISSUE TITLE
官网demo 在IOS 10的浏览器会打不开，IOS8&9的浏览器会很多变形

### ISSUE THREAD

**Issue by kson34** [airyland/vux#2560]
官网demo 在IOS 10的浏览器会打不开，IOS8&9的浏览器会很多变形，微信和支付宝都正常
IPHONE 6plus IOS 8 Safari
![img_3185](https://user-images.githubusercontent.com/17976520/37858830-a6bec800-2f45-11e8-92b2-493260eeb682.JPG)
IPHONE 6plus IOS 9 Safari
![img_3186](https://user-images.githubusercontent.com/17976520/37858831-a715d118-2f45-11e8-8e34-01fce814b249.JPG)
IPHONE 7plus IOS 10.3.3 Safari
![img_3179](https://user-images.githubusercontent.com/17976520/37858832-a776bbfe-2f45-11e8-8efa-d5c0b478e909.PNG)

**Comment by heyunjiang** [comment]
我也发现了同样的问题

**Comment by Jiiiiiin** [comment]
在安卓mate9 8.0内核版本的chrome浏览器上面运行感觉明显卡顿，我也一直想反馈，是不是可以优化一下(ಡωಡ)hiahiahia
是less的锅么？

**Comment by airyland** [comment]
iOS 低版本仅仅是 demo 构建的 autoprefix 配置问题，已经修复了。

iOS10 打不开无法判断问题，至少 iOS 11 是完全正常的。

@Jiiiiiin 和 less 没关系，最终还是编译成 css，Android 和 iOS 的渲染性能差距还是挺大的。
