### ISSUE TITLE
请更新下脚手架中的compression-webpack-plugin插件，以解决node-zopfli源死掉的问题

### ISSUE THREAD

**Issue by jevian-ma** [airyland/vux#2561]
应该有不少用户提出直接使用脚手架快速搭建vux工程失败，是由于node-zopfli.s3.amazonaws.com这个关于node-zopfli这个源死掉了。
我通过依赖关系发现node-zopfli是被compression-webpack-plugin的0.3.2版本所依赖的。因此您可以在package.json中去掉compression-webpack-plugin这个插件（本来就是在打包编译的文件为压缩文件才需要的，默认设置为false，正常根本就用不到他。）或是将这个插件的版本更新到目前的最新版本1.1.11，也不存在依赖关系。
目前的默认配置，如果没有一点package阅读能力，完全解决不了，并且官方都更新到1.1.11了，您却使用的是0.3.2，也不能怪npm官方不维护node-zopfli.s3.amazonaws.com这个源了啊。

**Comment by airyland** [comment]
谢谢建议，已经移除。
