### ISSUE TITLE
sticky吸顶，距离顶部还有很远就吸顶了

### ISSUE THREAD

**Issue by ranxin001** [airyland/vux#2562]
我想知道stricky能不能设置指定位置固定顶部？我看文档没有看到。

**Comment by airyland** [comment]
`再次`希望你能给个 repo 来说明你的问题而不是这样提 issue。
文档提供了 offset 来指定距离顶部多少高度 fixed。

**Comment by pencil2014** [comment]
离顶部很远就吸住了

![Uploading image.png…]()
