### ISSUE TITLE
sticky-----bug建议

### ISSUE THREAD

**Issue by ranxin001** [airyland/vux#2564]
之前我遇到的bug是：
页面刷新后，向下滚动，离sticky标签元素还有很远的距离，就开始吸顶了，但是切换路由回来后，再往下滚动，就正常了。

看了下sticky.js源码，问题出在源码36行：获取nav.offsetTop这个数值上。

我的页面上有很多元素是自动高度的图片，在网络不佳的情况下，图片的高度默认是0，

所以，刷新的时候nav.offsetTop数值获取的       是图片还未加载的高度，这远小于原来宽度！

所以，还未到滚动到sticky标签元素的位置就开始吸顶了。

解决办法：

1、把sticky标签元素的顶部所有图片标签加上固定高度，这样就算图片没加载出来也能获取到正确的offsetTop。

2、在 mounted阶段做一个setTimeout，调用this.$refs.sticky.bindSticky();   （！！不过定时器时间无法确定，得更具实际情况来，时间设得太小，这个offsetTop还是有可能不对。）

**Comment by airyland** [comment]
从 sticky 组件角度来讲 ，它并不能知道何时是正确的绑定时机，所以这个问题也并不能算 bug，只能在业务里保证尺寸或者重新绑定。

第一种方法可能可能比较麻烦，需要事先知道所有图片的尺寸比例用以占位。
第二种是合适的方法，但它要求有正确的绑定时机，我的建议是监听 img 加载方法，每个图片加载后触发一个事件，监听该事件来调用 bindSticky 方法。当然也可以用粗暴的方法，多次setTimeout(2s, 3s, 5s)来解决。

你的建议和 sticky 组件逻辑实现无关，但是这部分可以写入到文档提醒有相关疑问的用户。

**Comment by lwj1426282929** [comment]
指定了scroll-box 为滚定容器元素的id， 在ios下正常， 但在安卓机型下不生效
