### ISSUE TITLE
打包后IOS 访问 selector组件的placeholder属性在不显示

### ISSUE THREAD

**Issue by brahmachen** [airyland/vux#2565]
在开发环境，使用IOS访问，显示placeholder，点开后placeholder也作为第一个选项显示，功能没问题。但是打包后，就不显示placeholder了，点开选项后默认选第一个选项点完成，selector选择不上。
版本：
`
"vux": "^2.8.0",
"vux-loader": "^1.2.1",
`

**Comment by airyland** [comment]
`点开选项后默认选第一个选项点完成，selector选择不上` 这个似乎是 Safari 一直以来的问题。组件里实际之前做过处理，没有值时会 append 一个空值在第一位，强制用户需要拉到第一个值这样就能正确选择到。

至于你说的打包后有问题，不知道能如何重现。

**Comment by brahmachen** [comment]
我尝试重现一下

**Comment by brahmachen** [comment]
现在有一个奇怪的现象，之前用 jenkins在linux服务器上自动打包发布，就会有问题，在windows本地用手动打包发布的方式，就没有问题。
我可以暂时手动发布，避免这个问题

**Comment by QiuQiongLong** [comment]
@brahmachen  现在只要重新安装了依赖就会出现selector，之前安装的依赖打包不会出现，所以本地手动打包就不会出现，但是你删除依赖重新安装就会出现了，但是现在你重新安装依赖就会出现问题，我这边尝试过，降低版本也无法解决。

**Comment by airyland** [comment]
目测这是 vue 高版本的问题，你可以确认下版本并且降到 2.5.2 测试，并且使用 yarn 进行版本锁定，避免本地用低版本打包用了高版本。

**Comment by DLtmac** [comment]
最新版本的 iOS点击确定按钮 没有默认值
