### ISSUE TITLE
loading without text

### ISSUE THREAD

**Issue by Suntgr** [airyland/vux#2566]
loading 组件，以plugin形式调用，在未设置text情况下，为何会有默认的文字“加载中”？
我希望不添加文字，只要图标，所以把text设置成空字符串，但是图标不居中了，如下图：
![image](https://user-images.githubusercontent.com/15276065/37895704-b0b5de90-3114-11e8-86fb-c79ef5862cb8.png)
如果直接修改样式，会影响到其他我需要text的情况。
请问我该怎么做？

**Comment by airyland** [comment]
目前是会显示文字区域的，下个小版本支持不显示文字。
