### ISSUE TITLE
switch的警告

### ISSUE THREAD

**Issue by transtone** [airyland/vux#257]
```vue.common.js?e881:1014 [Vue warn]: Prop "value" expects a two-way binding type. (found in component: <switch>)```

用了switch之后，控制台出现了这样的警告。源码：

```     
 <switch title="省流量浏览" inline-desc='开启后，非wifi环境下省略或缩小图片' :value="true" ></switch>
```

但 vux.li 的示例没有这样的警告。

**Comment by airyland** [comment]
请使用双向绑定, 开发环境下是有警告的。
