### ISSUE TITLE
使用postcss-px2rem 后引入XAddress Picker等组件编译报错

### ISSUE THREAD

**Issue by Richar-Dada** [airyland/vux#2576]
我的项目是使用flexible.js做适配,构建的时候使用postcss-px2rem转换为rem,当我在项目中引入XAddress/Picker组组件后编译报错

报错信息:
failed to find 'scroller.css'
failed to find 'vux-modal.css'

版本信息: 
"vux": "^2.8.1", "vux-loader": "^1.2.6"

解决办法:
我查看源码发现引入less文件没问题,引入css就有
于是我把css文件都改成less, 编译成功
不太明白底层原理,希望作者大大确认一下

**Comment by Richar-Dada** [comment]
构建设置那需要打开usePostCSS

**Comment by BolinWang** [comment]
@Richar-Dada 我也遇到了同样的问题，请问是怎么解决的呢？

**Comment by nightmaring** [comment]
我使用flexible.js + px2rem-loader 是没问题的
