### ISSUE TITLE
iphonex下面所有dialog 异常

### ISSUE THREAD

**Issue by killdada** [airyland/vux#2578]
@media screen and (min-width: 1024px)
.weui-dialog {
    width: 35%;
}

审查元素发现iphonex下面这个生效，导致宽度不正常了

**Comment by airyland** [comment]
iphoneX 812px 达不到你代码的 1024px，在 Chrome 里调试也不会出现你所说的问题。审查截图给一个？

http://stephen.io/mediaqueries/iphonex/

**Comment by killdada** [comment]
![qq 20180331160757](https://user-images.githubusercontent.com/16487810/38161218-601d56ba-34fd-11e8-85fc-b85e2a722848.png)
![qq 20180331160754](https://user-images.githubusercontent.com/16487810/38161221-675dfccc-34fd-11e8-9ac9-dfb6793e856f.png)

可能是我们使用了rem的原因，然后对一些样式在iphonex也进行了适配，改了meta，然后审查的时候min-width到达了那个值，暂时我这边加了个样式修复了下

**Comment by airyland** [comment]
关于 rem 适配导致的这个问题有什么建议？因为组件默认使用的 px，如果兼容这种场景暂时没有什么想法。

**Comment by killdada** [comment]
目前还是用户自己处理吧，自己写media
@iphonex: ~"only screen and (device-width: 375PX) and (device-height: 812PX) and (-webkit-device-pixel-ratio: 3)";
@media @iphonex {
}

**Comment by caoleia** [comment]
@media screen and (min-width: 1024px) {
    .weui-dialog {
        width: 80% !important;
    }
}
我是直接覆盖了样式
