### ISSUE TITLE
Adress组件两级联动如何实现。

### ISSUE THREAD

**Issue by zhuqiuyang** [airyland/vux#258]
### Version
vux@0.1.1-rc3
### Steps to reproduce the problem
![image](https://cloud.githubusercontent.com/assets/14734729/15885685/61cabdf2-2d8b-11e6-9a8c-2036e05e2de6.png)

Adress 组件现在是三级联动，如何实现两级联动，就是只有省市地址。
因为没有picker组件的文档，光看Address组件的话，不知如何实现。
学习中，能否给个例子。
如果有实现的源码，能否给一份，学习一下。

**Comment by airyland** [comment]
只保留省市，不需要区对吧？

**Comment by zhuqiuyang** [comment]
恩恩  是的。

**Comment by airyland** [comment]
后面Address会提供一个选项只显示两级。也可以自己用popup picker封装，参考 src/demos/Popup-picker.vue

**Comment by zhuqiuyang** [comment]
好的，我看一下，3q~
