### ISSUE TITLE
【文档】新文档界面建议征集

### ISSUE THREAD

**Issue by airyland** [airyland/vux#2580]
一直没有时间更新文档界面，无法直面调查问卷 n 多的吐槽，这几天有时间稍微修改了一下，测试地址在此 https://doc.vux.li/

欢迎来提建议。

## 布局

- [ ] 小屏下收起侧边栏
- [ ] toc

**Comment by vmvz** [comment]
这会文档在线的 无法访问了

**Comment by wangshantao** [comment]
在分辨率1600*900下的显示效果不是很好
![_20180410092534](https://user-images.githubusercontent.com/14883268/38531150-26e1db54-3ca1-11e8-8c19-d7a26e77a279.png)

**Comment by airyland** [comment]
改个版本花了大量时间还是在问卷里被骂了n次，也不见有人来贡献更新，还是算了，大家爱用不用吧。两年多的时间，抱怨文档说明不清楚的人有的是，能发 pr 来反馈的人是个位数。开源不是做外包，辞职后花大半个月在修 bug ，即使我已经知道在国内做开源没什么意义但是还是坚持到现在，心累。
