### ISSUE TITLE
checklist max Error

### ISSUE THREAD

**Issue by alexqdjay** [airyland/vux#259]
### Android or iOS, which browser?
all
### Your Codes 

``` html
<!--put your code here-->
```

### Expected behavior and actual behavior.

checklist 关于max校验

当options是async时,ready肯定没有options.total，所以那个max一直是0
源代码:
```html
if (this.max) {
      if (this.max > total) {
        this.max = total
      }
    } else {
      this.max = total
    }
```

### Steps to reproduce the problem
能否：以设置为准，或者监听options的变化去冲洗设置获取total来设置max

**Comment by airyland** [comment]
的确定是个问题，将尽快修复。

**Comment by alexqdjay** [comment]
response so fast

**Comment by graysheeep** [comment]
@alexqdjay 来个PR啊钱都督

**Comment by airyland** [comment]
@graysheeep @alexqdjay  貌似有基情
