### ISSUE TITLE
Radio组件给他绑定一个点击事件，第一次点击取不到v-model绑定的值

### ISSUE THREAD

**Issue by XhpGit** [airyland/vux#2592]
请大家先学习如何格式多行代码：https://segmentfault.com/markdown, 不要浪费维护者时间，否则账号将被 block 无法再提 issue。

**Comment by airyland** [comment]
点击事件可能先于表单值改变，所以点击事件触发时不一定能获取到值。在 this.$nextTick() 后获取。

**Comment by XhpGit** [comment]
恩恩，应该是这样，用watch监听解决了

**Comment by XhpGit** [comment]
建议文档可以备注下这个地方，让新手跳过这个坑

**Comment by lys88** [comment]
解决这个问题的具体代码能够贴一下？小白求问
