### ISSUE TITLE
address组件异步加载数据

### ISSUE THREAD

**Issue by sandysong** [airyland/vux#26]
希望address组件支持从后台异步加载数据，可以将list作为组件参数传给组件

**Comment by airyland** [comment]
剥离数据在开发计划中，但是要求参数格式和目前的统一。

**Comment by sandysong** [comment]
试了一下，虽然可以通过list传数据进去，但是父组件是异步从server端取list的，初始化的时候会报错：
`Uncaught TypeError: Cannot read property 'value' of undefined`
`Uncaught TypeError: Cannot read property 'name' of undefined`

**Comment by airyland** [comment]
传进去是数据还是空的？

**Comment by airyland** [comment]
传进去是数据还是空的？

**Comment by sandysong** [comment]
我是在父组件的created钩子里异步从server端加载数据，然后设置到父组件的data.list里，address组件的list和父组件data.list绑定。这样用对么？

**Comment by airyland** [comment]
这样的话，address组件一开始会没有数据，初始化失败。如果你用vue-router的话，可以使用 `data` 钩子来在compile组件前进行数据获取

http://vuejs.github.io/vue-router/zh-cn/pipeline/data.html

我也在考虑支持异步设置 list 和 value，但是可能出现用户操作时list还没有获取成功的情况

**Comment by sandysong** [comment]
data钩子估计也不行，异步请求最终都一样

**Comment by airyland** [comment]
这样子能保证在组件初始化前数据已经获取到了。

**Comment by sandysong** [comment]
我知道了，我尝试一下

**Comment by sandysong** [comment]
试了一下，貌似在data钩子调用前就js报错了

**Comment by airyland** [comment]
添加  waitForData: true 呢

**Comment by sandysong** [comment]
异步取数据写在data钩子里，然后为组件加上v-if="!$loadingRouteData"解决了

**Comment by airyland** [comment]
@sandysong :+1: 这种思路不错。
