### ISSUE TITLE
建议：文档里面没提的一点，但新手很可能会撞墙。

### ISSUE THREAD

**Issue by VinceXie** [airyland/vux#260]
文档里面完全没有提到vux css的引入。我尝试按照文档上的官方文档走了一遍流程，但发现样式全部没有。

对照例子，其实需要在根节点加入@import '~vux/dist/vux.css'样式组件才能正常使用。

或许，我走的流程不对或眼不好遗漏了？希望vux越做越好。

**Comment by airyland** [comment]
检查过了，安装文档都有写vux.css。你是看哪里的文档？
https://vuxjs.gitbooks.io/vux/content/install/vue.html

**Comment by airyland** [comment]
如果文档漏写了，可以PR哦。https://github.com/vuxjs/vux-doc
