### ISSUE TITLE
ios11上，Sticky快速上下滑动时，Sticky疯狂闪动

### ISSUE THREAD

**Issue by tangMr1234** [airyland/vux#2601]
在uc或者hbuilder中，官方的demo上下滑动时不停的闪动，并且出现消失，等滚动结束再出现

**Comment by airyland** [comment]
UC 的 webview 及 hybrid 打包的 webview 会无法实时响应 onscroll 事件，暂时无法解决，建议暂时使用 disabled 来禁用。

**Comment by tangMr1234** [comment]
@airyland   uc升级过几次后  目前我的版本11.9.1071， ios版本11.4（15F5079a）,在uc上用正常不闪动了，自己使用试的，官方的Sticky禁用了没有测试
