### ISSUE TITLE
x-input被键盘遮挡

### ISSUE THREAD

**Issue by xiaolei335** [airyland/vux#2604]
如果x-input靠近页面下方的话，输入的时候弹出手机软键盘，会将x-input遮挡住。

在官方的Demo里，这个问题同样存在
https://vux.li/demos/v2/?x-page=v2-doc-home#/component/x-input

**Comment by airyland** [comment]
请说明重现环境谢谢。

**Comment by xiaolei335** [comment]
你好，在android手机上会出现这种情况，ios是正常的。

在魅族pro6 plus手机上，在自带浏览器或微信里打开页面
https://vux.li/demos/v2/?x-page=v2-doc-home#/component/x-input

点击靠页面下方的input，系统软键盘弹出，input会被遮挡

**Comment by xiaolei335** [comment]
目前我的解决办法是在App.vue里加入了一段代码解决，但是比较尴尬，不完美

``` js
window.addEventListener("resize", function () {
  if (document.activeElement.tagName == "INPUT" || document.activeElement.tagName == "TEXTAREA") {
    window.setTimeout(function () { 
      document.activeElement.scrollIntoViewIfNeeded();
    },0);
  }
})
```

**Comment by airyland** [comment]
尴尬之处是什么，是说功能能实现，但是这样全局处理不和谐？

**Comment by xiaolei335** [comment]
对的，这个应该是vux框架自带就应该解决的，目前键盘遮挡的情况在android手机上非常普遍，大家应该都存在这种问题，比较影响用户体验

**Comment by xiaoningtongxue** [comment]
@airyland 加了给出的那段代码，在iphone7-ios11.12下依然不能解决问题。

**Comment by againForget** [comment]
这个问题有解决办法了么

**Comment by Jiiiiiin** [comment]
这是webview 和android应用层面应该解决的问题

**Comment by Newgar** [comment]
我的也有这种情况~~点击input框 弹出键盘后  input框就被顶到上面去了,页面也给我翻到了最下面~~  然后还有一个 从input框失去焦点的时候,如果点击的部位有group 那么 也会翻页到最下面~~~.
安卓手机  都这样
苹果没试

**Comment by easy868** [comment]
iphone x 键盘刚弹起后是正常，不到一秒钟输入框就会下移，被键盘遮挡

**Comment by Vera6** [comment]
iphone 系统为13的，键盘弹起时，光标不能自动focus，会错位。APP用的是uiwebview，而且滚动也滚动不到最底部。输入框一点光标就错位。
