### ISSUE TITLE
关于popup-picker初始化显示问题

### ISSUE THREAD

**Issue by ivandy** [airyland/vux#2605]
此组件在初始化的时候会闪一下然后才显示展示的横栏框，影响体验效果

**Comment by airyland** [comment]
这个问题尝试解决过，没找到解决方法。除非把遮罩层去掉。

**Comment by ivandy** [comment]
今天又看了下，好像没有这个问题了，是解决了吗？




| |
杜恒
邮箱：livendy0312@163.com
|

签名由 网易邮箱大师 定制

在2018年04月09日 22:46，Airyland 写道：

这个问题尝试解决过，没找到解决方法。除非把遮罩层去掉。

**Comment by airyland** [comment]
并没有，不过有时候似乎就会正常。

**Comment by airyland** [comment]
合并到 #2239
