### ISSUE TITLE
安卓原生浏览器报错

### ISSUE THREAD

**Issue by wangbaolongbbl** [airyland/vux#2609]
![1](https://user-images.githubusercontent.com/16952323/38469188-37d60e90-3b83-11e8-9eea-f45548afae18.jpg)
华为emui4.01引入vux组件就有问题

**Comment by airyland** [comment]
看不出和 vux 有什么关系？ 上面 warning 是 vue-router，下面 error 没有任何信息。
建议你先把 vue-router 的问题修复再看看。

**Comment by wangbaolongbbl** [comment]
我擦擦，找到问题了，破安卓原生浏览器。
`<flow-line is-done :line-span="30" :is-done="status=='password'"></flow-line>`
多写了一次重复属性。。就报错导致整个启动不了
