### ISSUE TITLE
Scroller + XImg  只能显示第一屏的图片

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#261]
`  <scroller lock-x scrollbar-y use-pulldown use-pullup v-ref:scroller enable-horizontal-swiping>`
`     <div v-for="src in list" style="background-color:yellow;text-align:center;">`
`       <span style="font-size:20px;">Loading</span>`
`       <x-img :src="src" @on-success="success" @on-error="error" class="ximg-demo" error-class="ximg-error" :offset="-300"></x-img>`
`     </div>`
`   </scroller>`

如果不加scroller是可以正常显示的，加了只能演示第一屏，请问如何处理？

**Comment by hubinjie** [comment]
有一个商品列表需求，然后需要有上拉和下拉功能 ，所以就用到了 scroller， 然后结合 x-img 希望图片可以 按需加载， 弄了很久，一直没有解决～

**Comment by airyland** [comment]
scroller是特殊的容器，需要在scroller里处理lazyload。下个版本支持。

**Comment by hubinjie** [comment]
请问一下版本大约是啥时候发布？

**Comment by airyland** [comment]
@hubinjie 我刚已经处理好了，明天发布一个rc版本，大概后天发布0.1.1

**Comment by hubinjie** [comment]
真牛，感谢

**Comment by hubinjie** [comment]
我再弱问一下句，如果外面是一个
`<scroller v-ref:scroller>`
`<mycompent v-for="1 in 80"></mycompent>`
`</scroller>`

mycompent里面是
`<span>title</span>`
`<x-img :src="src"   @on-success="success" @on-error="error" class="ximg-demo" error-class="ximg-error" :offset="300"></x-img>`
`</scroller>`

像这种是如何用的？

**Comment by airyland** [comment]
@hubinjie 看不懂你问的是什么，不同组件用slot来嵌套，组件该怎么用就怎么用。

**Comment by hubinjie** [comment]
```
<template>
  <div class="search">
    <div class="search-bar">
      <search @result-click="resultClick" @on-change="getResult" :results="results" :value.sync="value" placeholder="搜索商品名称" cancel-text="取消"></search>
    </div>
    <scroller class="has-search-bar"  lock-x scrollbar-y enable-horizontal-swiping v-ref:scroller v-if="categories" height="600px" >
      <div class="cats">
        <spinner type="crescent" v-if="!categories" slot="value"></spinner>
        <group  title-color="#04be02"   v-for="cat in categories">
          <cell :title="cat.name" :value="'现已有'+cat.count+'种商品'" >
            <span class="demo-icon" slot="icon">&#xe61b;</span>
          </cell>
        
          <div class="weui_grids">
           <div v-for="item in cat.list">
             <div class="weui_grid">
              <m-h-category :scroller="$refs.scroller"  :title="item.name" :url="item.url" :src="item.img" ></m-h-category>
             </div>
           </div>
          </div>
       </group>
     </div> 
   </scroller>
  </div>
</template

```

里面的MHCategory 是我自己做的，然后，我在MHCategory是这样写的

```
<template>
    <a class="mh-category" href="#" v-link="url">
      <span style="font-size:20px;">Loading</span>
      <x-img :src="src"   @on-success="success" @on-error="error" class="ximg-demo" error-class="ximg-error" :offset="300"></x-img>
      <div class="mh-category-title">{{title}}</div>
    </a>
</template>
```

我看这次在XImg加了一个叫 :scroller="$refs.scroller" 

请问一下，像这种情况是如何传给子组件中？

我尝试在MHCategory中加了一个属性
```
props: {
    scroller: Object
}
```
同时也将里面的XImg改成这样
` <x-img :src="src" :scroller="scroller"  @on-success="success" @on-error="error" class="ximg-demo" error-class="ximg-error" :offset="300"></x-img>`

浏览器就卡死崩溃了，不知道是不是这样用的

**Comment by airyland** [comment]
卡死崩溃也有报错吧。
这个版本还没有发布，你直接用的是源码？

**Comment by hubinjie** [comment]
我看你们解决了，所以就把XIMG 源码复制了一份出来，试了一下

**Comment by soulkiller** [comment]
新版本确实解决了 大赞 今天正好遇到了
