### ISSUE TITLE
希望能发布一个离线文档

### ISSUE THREAD

**Issue by 565784135** [airyland/vux#2611]
最近官网经常性抽风，正在开发的我心脏受不了啊

**Comment by tangMr1234** [comment]
好像现在官网又挂了

**Comment by wangbaolongbbl** [comment]
+1
实时开发者 - -！

**Comment by airyland** [comment]
新版刚上线请给点耐心，不然就本地 clone 源码运行吧。除非不更新了，否则本地与最新 demo 不同步会有一堆浪费时间的 issue。
