### ISSUE TITLE
如何打包指定VUX模块到dist？

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#262]
最近在老项目上使用Vux，由于历史原因无法做到demo那样的单页app，前后端耦合程度挺大，因此选择requirejs按需载入。
现在的问题是，每个页面上可能用到七八个vux组件，因此如果引入dist/components中的各index.js，会发起很多请求。

个人对于前端工程不甚了解，想请教应当如何配置，才可以使npm只打包指定模块的js和css（如group, cell和badge三者），谢谢。

**Comment by airyland** [comment]
看看 build/webpack.npm.base.conf.js, 然后把 /src/components/index.js 修改一下，只保留你要的组件，
`webpack --progress --hide-modules --colors --config build/webpack.npm.conf.js`

**Comment by dangyuluo** [comment]
好巧，刚读源码看到这里。谢谢。 
------------------ Original ------------------
