### ISSUE TITLE
tab组件多选项的时候，导致底部bar高度塌陷

### ISSUE THREAD

**Issue by lancerfox** [airyland/vux#2621]
vux@"^2.8.1",
![111](https://user-images.githubusercontent.com/16282919/38592361-34c6fd6c-3d6e-11e8-9b3a-47ab0bb1a972.png)
![22222](https://user-images.githubusercontent.com/16282919/38592366-38b566c0-3d6e-11e8-9580-d0c8b2bd211d.png)
组件可以滑动，但是底部Bar塌陷下去
用chrome查看dom
![666](https://user-images.githubusercontent.com/16282919/38592430-98c35e1e-3d6e-11e8-8ae8-b8930e33319e.png)
点击取消height：44px;恢复正常

**Comment by airyland** [comment]
demo 同样的代码并不能重现。

**Comment by liuliuboy** [comment]
我这也出出现同样问题

**Comment by liuliuboy** [comment]
![1](https://user-images.githubusercontent.com/22977943/38981275-955030f2-43f1-11e8-8cf4-ceb62fc0b974.png)
我是这样解决的，修改组件tab.vue

**Comment by airyland** [comment]
麻烦帖一下可以重现的代码。

**Comment by liuliuboy** [comment]
` <Tab :line-width="2" active-color='#F56C02' v-model="listIndex" :custom-bar-width="getListWidth">
        <TabItem ctive-class="active-border" v-for="(item, key) in tabList" :key="key" :selected="listIndex === key">{{item}}</TabItem>
      </Tab>`

`import {Tab, TabItem, Swiper, SwiperItem} from **'vux';`

`tabList: ['推荐', '手机品牌日', '智能', '电视', '电脑', '全面屏', '生活周边', '盒子'],`

"vux": "^2.9.0"， "vue": "^2.5.2",

在谷歌浏览器测试， 版本 64.0.3282.140

**Comment by suntruck** [comment]
1) global div { box-sizing: border-box }
2) five tab items in the tab vue.
******
When I comment global _div { box-sizing: border-box }_
The issue is fixed.

**Comment by superjiangs** [comment]
请问下，大家是如何解决的？ 怎么没看明白是怎么解决的呢？

**Comment by alicksnake22** [comment]
2.9.2版本里面，我也有相同问题，tab数量多到可滚动的时候，横杆上移了

**Comment by alicksnake22** [comment]
@airyland 我用了2.9.2版本依旧会塌陷，原因已经找到，是因为我使用了postcss-px-to-viewport插件来开发移动webapp，我在里面配置为忽略vux开头的css类的转换，但是tab里面有一个类名为scrollable，所以并没有忽略到，导致scrollable的padding-bottom被转为vw，造成塌陷，不知道这个scrollable能否改为vux-scrollable之类的？
