### ISSUE TITLE
x-input：v-modle的值在watch里面用replace替换值时页面元素的值未更新的问题

### ISSUE THREAD

**Issue by baidan** [airyland/vux#2622]
问题描述：v-modle的值在watch里面用replace替换值时页面元素的值未更新的问题，主要目的是使用正则替换值。
实际效果：monthlyIncome 实例中挂载的数据正常，但是页面元素的值未更新；而不使用组件的code正常显示。

         html:

        <div class="form-wrap">
           <group>
              <x-input 
                title="月收入"
                type="text" 
                v-model="monthlyIncome"
                placeholder="请输入您的月收入">
              </x-input>
              <span>{{monthlyIncome}}</span>
          </group>
        </div>

        <input
          type="text"
          maxlength="6"
          v-model="code"
        >
         <span>{{code}}</span>
       
        script:      
     
         data() {
             return {
                 monthlyIncome: "",
                 code: "",
              };
            },

           watch: {
               monthlyIncome(newVal) {
                       this.monthlyIncome = newVal.replace(/[^\d]/g, "");
               },
                code(newVal) {
                     this.code = newVal.replace(/[^\d]/g, "");
                }
            }

https://s1.ax1x.com/2018/04/11/CkNfTx.jpg
![image](https://s1.ax1x.com/2018/04/11/CkNfTx.jpg)

**Comment by airyland** [comment]
主要问题在于 model 绑定的值并没有变化，不能触发内部值更新。

7777j  => 7777
7777jj => 7777

暂时可以这么处理，直接更新内部值：

``` js
this.$refs.input.currentValue =
```

**Comment by baidan** [comment]
明白了，感谢！

**Comment by baidan** [comment]
这样的话， v-model就无法使用了，只能用 :value 绑定，失去意义了。

**Comment by baidan** [comment]
这种方法需要手动的去触发一下：
@on-change="inputCheck"
 ref="mref"

watch: {
    monthlyIncome(newVal,oldVal){
        this.monthlyIncome = newVal.replace(/[^\d]/g, "");
    }
  }, 

methods:{
   inputCheck(value) {
          this.$refs.mref.currentValue = value.replace(/[^\d]/g, "");      
    },
}

**Comment by AboyL** [comment]
这个问题请教了滴滴的黄轶的。在一次nextTick后更新数据就好了

**Comment by Ethan-2016** [comment]
watch: {
monthlyIncome(newVal,oldVal){
this.replaceFn();
}
},

methods:{
replaceFn() {
this.$nextTick(function() {
	this.monthlyIncome = this.monthlyIncome.replace(/[^\d]/g, "");
});
