### ISSUE TITLE
为什么vux地址下的图片不能被移动端访问？

### ISSUE THREAD

**Issue by Qunc** [airyland/vux#2623]
比如vux文档demo里出现过的https://static.vux.li/demo/2.jpg，https://static.vux.li/demo/3.jpg这种图片地址。
在手机上或者“PC端上的移动端模式”下面访问这种图片地址会直接404，是什么原因？

**Comment by airyland** [comment]
为什么你要访问这些图片？demo 里这些图片地址都已经更新成其他图床地址。

如果你是本地调试组件库代码，那么 pull 下新的代码。

这些图片被删除是因为这些都是个人支付的放置于付费 cdn (为了 demo 访问足够快)的图片，不少第三方组件开发者写 demo 都直接用这些地址，造成了损失，而这个组件库得到的捐赠的量远远小于每年域名服务器cdn费用所需要的。

**Comment by swordYWQ** [comment]
同样的问题，并不需要使用这些图片，但由于使用了swiper组件，项目加载时会报图片404的错误，我看了这些图片是在vux包的yml文件中写入的，为什么它们会在项目初始化时加载
