### ISSUE TITLE
结合Nuxt使用的编译问题

### ISSUE THREAD

**Issue by Blueeye1015** [airyland/vux#2625]
在结合Nuxt使用的时候发现编译完的代码中，部分组件没有被babel编译。貌似Nuxt自带的babel配置也没对vux生效，导致会出现一些兼容性问题。

以下是跑了nuxt中的example后编译出的结果，`nuxt.config.js`没有做修改：

![image](https://user-images.githubusercontent.com/4958807/38624801-8c2a35f2-3ddb-11e8-88f7-4e0d5a6be58e.png)

想请教一下应该如何修改配置文件。

**Comment by airyland** [comment]
你按照 https://github.com/nuxt/nuxt.js/tree/dev/examples/with-vux 这个配置的吗？

**Comment by Blueeye1015** [comment]
嗯是的，不过我把`import`改成`require`了。其他都没改动

**Comment by airyland** [comment]
添加 .babelrc
