### ISSUE TITLE
x-number  的事件demo 应为on-change 而不是 change

### ISSUE THREAD

**Issue by bulolo** [airyland/vux#263]
https://vuxjs.gitbooks.io/vux/content/form/x-number.html
x-number 事件demo错误
### Version
0.1
### Android or iOS, which browser?
all
### Your Codes 

``` html
<group>
  <x-number title="Number" :value=0 :min=0 :max=10 @change="change"></x-number>
</group>
应该是
<group>
  <x-number title="Number" :value=0 :min=0 :max=10 @on-change="change"></x-number>
</group>
```

demo中基本上都是用change。但文档是on-change ，需要修正一下

**Comment by ibufu** [comment]
还有x-input也是

**Comment by airyland** [comment]
@ibufu 哪个文件？

**Comment by ibufu** [comment]
https://github.com/airyland/vux/blob/master/src/components/x-input/index.vue
https://github.com/airyland/vux/blob/master/src/demos/Input.vue
我看源码里没有发射on-change事件，但是demo里@on-change了
@airyland

**Comment by airyland** [comment]
@ibufu The event is emited by a mixin https://github.com/airyland/vux/blob/master/src/libs/base.js
