### ISSUE TITLE
Datetime组件     on-confirm事件     怎么拿到当前选中的时间（当前value）      

### ISSUE THREAD

**Issue by jiayuu** [airyland/vux#2632]
请大家先学习如何格式多行代码：https://segmentfault.com/markdown, 不要浪费维护者时间，否则账号将被 block 无法再提 issue。

**Comment by airyland** [comment]
值是异步设定的，所以目前你需要在 this.$nextTick 之后获取当前绑定的值。在下个版本支持在 on-confirm 参数里附带。

**Comment by igouz** [comment]
ios 页面，滑动选择日期的时候，会让背部vue-scroller一起滚动。
