### ISSUE TITLE
在group中使用selector和demo显示效果不一样的issue

### ISSUE THREAD

**Issue by feng9217** [airyland/vux#2633]
请大家先学习如何格式多行代码：https://segmentfault.com/markdown, 不要浪费维护者时间，否则账号将被 block 无法再提 issue。

1. placeholder 无法显示
2. value的值不显示
PS: 以上两点 placeholder / v-bind:placeholder 两种方法都试了
![image](https://user-images.githubusercontent.com/6224010/38689332-e91fbba6-3ead-11e8-986a-0b6ccbf703ae.png)

3. 初始化 .vue文件时自动打印(在没有写任何生命周期钩子调用函数前提下)v-model的值只返回Boolean, 且为 true
![image](https://user-images.githubusercontent.com/6224010/38689349-f70121ba-3ead-11e8-9215-79a0ba3479a9.png)

4. 关于 direction 的用法
5. 选好值了以后 默认是左对齐?? 如下图, 除了使用 padding-left 改变其位置 还能如何使其改变对齐方式??
![image](https://user-images.githubusercontent.com/6224010/38689278-c3ad0914-3ead-11e8-8883-b0cd0c68422d.png)
 
附上代码:

     <selector
        placeholder="请选择价格"
        v-model="design_price"
        title="设计价格"
        :options="designprice"
        class="select-item"
        @on-change="getDesignprice"
        :value="design_price">
      </selector>

      <selector
        :title="sptitle"
        :placeholder="default_title"
        v-model="super_price"
        :options="designprice"
        class="select-item"
        @on-change="getSuperprice"
        :value="super_price">
      </selector>

再附上代码地址, 望大大帮忙解惑(.vue文件完整代码 没引用在线库)
https://jsfiddle.net/mmx38qxw/1467/

**Comment by feng9217** [comment]
使用的是 vue init airyland/vux2 模板
版本信息: 
![image](https://user-images.githubusercontent.com/6224010/38690064-c7dba5fc-3eaf-11e8-8ab9-00954f5d4c74.png)

**Comment by airyland** [comment]
使用的 vue 实际版本是哪个

**Comment by feng9217** [comment]
2.9.3

在线地址应该是 https://jsfiddle.net/mmx38qxw/1468/ 带上了css

**Comment by airyland** [comment]
Vue 新版的问题，可以降级或者等这两天 VUX 小版本。

**Comment by feng9217** [comment]
好的 感谢 ~
坐等小版本

**Comment by qingyl** [comment]
这个问题我帮你解决了 在源代码里把value的数组位置内容换一下，以为你默认是布尔值所以就出现了这个问题，不过我还没看懂为啥要用上数组来

**Comment by feng9217** [comment]
这个在 vux 2.9.0 版本中已经OK了

**Comment by DLtmac** [comment]
vux2.9.4还有placeholder不显示问题
