### ISSUE TITLE
npm下载的vux2.8.1不包含InlineXSwitch 文档是有的

### ISSUE THREAD

**Issue by XavierShi** [airyland/vux#2636]
![image](https://user-images.githubusercontent.com/16569751/38720398-b1bc8b50-3f28-11e8-937e-2ff206dfdd9a.png)
![image](https://user-images.githubusercontent.com/16569751/38720445-de7cc916-3f28-11e8-836e-5e57c6275d27.png)
![image](https://user-images.githubusercontent.com/16569751/38720460-e98d72a6-3f28-11e8-8a7a-10da44a8ca0f.png)

npm下载的vux2.8.1不包含InlineXSwitch 文档是有的

**Comment by airyland** [comment]
下个版本。
