### ISSUE TITLE
使用airyland/vux2生成的项目 build之后assets文件夹下的图片没有生成需要如何配置啊

### ISSUE THREAD

**Issue by shenzhirong** [airyland/vux#2637]
![image](https://user-images.githubusercontent.com/5197159/38722120-756bad8c-3f2f-11e8-90db-1a5b8165d603.png)
请问使用的图片如何一起被打包出来

**Comment by XavierShi** [comment]
图片太小被webpack打包成base64了，要么改loader那儿的limit大小 要么把图片放在static文件夹

**Comment by shenzhirong** [comment]
那为什么build之后 访问页面 图片是404呢

**Comment by shenzhirong** [comment]
那为什么build之后 访问页面 图片是404呢

**Comment by airyland** [comment]
无论静态文件放在 assets 目录或者 static 目录最终都会被成功打包，也有可能是 base64。至于所谓的 404 问题，问题过于马虎无法解答。
