### ISSUE TITLE
Datetime组件建议 : on-change事件应该是切换日期就会触发然后返回当前value，而不是切换完 还需点击确认才会触发。on-confirm事件应该支持返回当前选中value。on-clear事件：当我触发on-clear事件后再次点开时间组件时不应该是我的上一次选中的时间 ，我已经clear了应该对我的时间做些改变，比如换成 “请选择”。

### ISSUE THREAD

**Issue by jiayuu** [airyland/vux#2639]
请大家先学习如何格式多行代码：https://segmentfault.com/markdown, 不要浪费维护者时间，否则账号将被 block 无法再提 issue。

**Comment by airyland** [comment]
1. datetime 是需要 confirm 的，用户有年月日三列要选，选了第一列年就 on-change  的意义是什么？此时值并不是用户预期的，也不是需求所预期的。如果你有特殊场景，也请直接说明清楚。

2.已经修复了，下个版本。

3.没看明白，如果清空了值，显不显示 placeholder 取决于你有没有配置 placeholder。

4.请把内容分点写到内容里，而不是这样写在标题，看着相当难受。
