### ISSUE TITLE
请问Alert组件有没有支持定制样式的计划？

### ISSUE THREAD

**Issue by kfperfect** [airyland/vux#2640]
请大家先学习如何格式多行代码：https://segmentfault.com/markdown, 不要浪费维护者时间，否则账号将被 block 无法再提 issue。

我在项目中用到Alert组件，title部分会有默认“padding: 1.3em 1.6em 0.5em”属性，在我的项目里top会特别高，到时alert顶部有大片空白，请问以后会不会考虑支持一些style参数定制？比如字体、字号、margin、padding之类的。非常感谢！

**Comment by airyland** [comment]
看起来直接样式覆盖就可以了。当然这个值是可以改成 less 变量配置的，可以来 pr。

**Comment by kfperfect** [comment]
非常感谢！我是一个新手，了解的东西太有限，您说的我先研究一下。再次感谢！

**Comment by airyland** [comment]
下个版本仅会支持 gap(padding-left padding-right) ，其他样式只能自己覆盖之，该 issue 关闭。

**Comment by kfperfect** [comment]
收到，非常感谢！
