### ISSUE TITLE
[Bug Report] 从github直接npm install vux库报错(库文件不完整)

### ISSUE THREAD

**Issue by jack87918** [airyland/vux#2642]
### VUX version
2.8.1

### OS/Browsers version
Windows/Chrome

### Vue version
2.5.17-beta.0

### Code

```html
npm install git://github.com/airyland/vux.git
```

### Steps to reproduce
1. 使用 npm install git://github.com/airyland/vux.git 尝试安装vux
2. 尝试引用vux并用nodejs运行，发现文件缺失:
Cannot find module '\node_modules\vux\src\components\map.json'

### What is Expected?
直接从github地址(对比从npmjs上安装)，执行npm install:
1. npm install vux
2. npm install git://github.com/airyland/vux.git
两种方法下载的vux类库的文件相同并是完整的

### What is actually happening?
使用从github下载，install后的包文件不完整

**Comment by airyland** [comment]
默认安装了 master 分支，需要指定 v2 分支

``` bash
npm install git://github.com/airyland/vux.git#v2
```

**Comment by jack87918** [comment]
使用v2分支之后可以了，谢谢。
