### ISSUE TITLE
[Feature Request] 用vue vux打包成原生app时，涉及weui-mask的组件怎么样能让遮罩覆盖住手机顶部状态栏？

### ISSUE THREAD

**Issue by NinjaJin** [airyland/vux#2650]
### Existing Component
是

### Component Name
XDialog

### Description
用vue vux打包成原生app时，涉及weui-mask的组件怎么样能让遮罩覆盖住手机顶部状态栏？

**Comment by airyland** [comment]
这是 hybrid 打包实现相关的支持，无法从页面组件层面做到，可以查阅你所使用的 hybrid 相关技术文档。
