### ISSUE TITLE
[Bug Report] popup-radio的弹出框右边有黑边。

### ISSUE THREAD

**Issue by jikoy** [airyland/vux#2651]
### VUX version
2.9.0

### OS/Browsers version
微信浏览器

### Vue version
2.5.17-beta.0

### Code

```html
无
```

### Steps to reproduce
看发行包的demo即可。Demo/popup-radio

### What is Expected?
右侧颜色一致

### What is actually happening?
右侧黑边

**Comment by jikoy** [comment]
也可能是进度条，但不应该有进度条出来啊？？

**Comment by airyland** [comment]
不能重现，请告知具体系统、浏览器并且附上截图。

**Comment by unclay** [comment]
安卓4.4.2微信重现
