### ISSUE TITLE
PC端的适配

### ISSUE THREAD

**Issue by yanyiheng13** [airyland/vux#2655]
### Existing Component
是

### Component Name
已有组件

### Description
你好我想问一下demo在pc端打卡是适配的，但按照流程创建的项目在pc打开显示的比较小  不适配如何处理

**Comment by airyland** [comment]
viewport meta 加了吗？假如你按照脚手架来应该不会有这种情况。
 https://doc.vux.li/zh-CN/install/manual-usage.html

**Comment by yanyiheng13** [comment]
不好意思  自己是个新手  之前做的安卓，现在顺带做点h5，还是没发现问题，下面是webpack的一些配置
'use strict'
const path = require('path');
const utils = require('./utils');
const config = require('../config');
const vueLoaderConfig = require('./vue-loader.conf');
const vuxLoader = require('vux-loader');
const webpack = require('webpack');

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

let webpackConfig = {
  context: path.resolve(__dirname, '../'),
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    }
  },
  module: {
    rules: [
      ...(config.dev.useEslint ? [{
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter'),
          emitWarning: !config.dev.showEslintErrorsInOverlay
        }
      }] : []),
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.sass$/,
        loaders: ['style', 'css', 'sass']
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}

module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui', 'progress-bar', 'duplicate-style', {
    name: 'less-theme',
    path: 'src/styles/theme.less'
  }
  ]
});

**Comment by yanyiheng13** [comment]
不好意思，没有找到问题，之前做的安卓，现在顺带做点h5，h5水平不好，下面是webpack的一些配置。
```
'use strict'
const path = require('path');
const utils = require('./utils');
const config = require('../config');
const vueLoaderConfig = require('./vue-loader.conf');
const vuxLoader = require('vux-loader');
const webpack = require('webpack');

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

let webpackConfig = {
  context: path.resolve(__dirname, '../'),
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    }
  },
  module: {
    rules: [
      ...(config.dev.useEslint ? [{
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter'),
          emitWarning: !config.dev.showEslintErrorsInOverlay
        }
      }] : []),
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.sass$/,
        loaders: ['style', 'css', 'sass']
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}

module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui', 'progress-bar', 'duplicate-style', {
    name: 'less-theme',
    path: 'src/styles/theme.less'
  }
  ]
});

```

**Comment by yanyiheng13** [comment]
手机上这样
![1524020626 1](https://user-images.githubusercontent.com/7472565/38909754-9923e466-42f8-11e8-923a-b732935f9b82.jpg)
pc上这样
![image](https://user-images.githubusercontent.com/7472565/38909775-b791f46a-42f8-11e8-8553-5959c47b915d.png)

**Comment by airyland** [comment]
webpack 配置应该是没问题的。不过你这样子就比较奇怪了，用 chrome 切换到手机模式正常吗？

**Comment by yanyiheng13** [comment]
用chrome切换到手机正常  上面的截图就是

**Comment by airyland** [comment]
确认下 head 里的 viewport 设置在否

``` html
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
```

**Comment by yanyiheng13** [comment]
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">这个是有的   我按照教程  快速创建了项目   还是一样的情况

**Comment by yanyiheng13** [comment]
你们的demo在pc打开没一点问题

**Comment by airyland** [comment]
额，判断不了问题也许直接建个 Github repo 来重现才能找到问题了。

**Comment by yanyiheng13** [comment]
嗯嗯
