### ISSUE TITLE
能不能把支持ssr跟不支持ssr的组件区分一下

### ISSUE THREAD

**Issue by jjskay** [airyland/vux#2656]
实际项目用的nuxt，部分组件引入直接就报错，原因是在server端的时候没有window上的api导致在server端render的时候报错，能不能将支持与不支持ssr的组件标明，避免出现用了之后才知道不支持ssr，或者干脆全部支持ssr

**Comment by airyland** [comment]
报错不帖错，无用 issue，浪费时间。组件尽力支持 ssr，如果不支持，请帖错反馈，而不是在怀疑只是部分支持。不如你把全部组件用一遍来帮 VUX 区分一下？
