### ISSUE TITLE
tab组件

### ISSUE THREAD

**Issue by zsjbsn** [airyland/vux#2661]
当有很多item的时候（我的是6个），改变绑定的index来自动实现切换的时候，底部的横线偏离item很多。

**Comment by airyland** [comment]
Please don't ignore issue template.

**Comment by wg5945** [comment]
demo里面我试了下，貌似并不能复现你的问题，提供一个复现代码吧

**Comment by zsjbsn** [comment]
原因是tab不能动态的添加item，一次性加载所有item的话，就没有这个问题了

**Comment by liutoby** [comment]
怎样删除tabitem下面的bar
