### ISSUE TITLE
[Feature Request] InlineCalendar日期永远是1-30号吗

### ISSUE THREAD

**Issue by Qunc** [airyland/vux#2667]
### Existing Component
是

### Component Name
InlineCalendar

### Description
请问一下InlineCalendar日期永远是1-30号吗，我设置了start-date和end-date和render-month都没有用，请问这个是写死的1-30号吗，还是我漏设置了什么属性呢？
代码如下：
  <div id="sign-in" class="nofooter">
  	
  	<app-header class="left right"></app-header>
  	
    <div class="main-header" v-if="!isInlineCalendar">
	    <div class="box-tab">
	    	<tab :line-width="2" custom-bar-width="60px" bar-active-color="#f03b13">
	        <tab-item @click.native="" selected>我的</tab-item>
	        <tab-item @click.native="">团队考勤</tab-item>
	      </tab>
	    </div>
	  </div>
    
    <inline-calendar
		  ref="calendar"
		  @on-change="onChange"
		  @on-view-change="onViewChange"
		  class="inline-calendar-demo"
		  :show.sync="show"
		  v-model="value"
		  start-date="2018-02-01"
		  end-date="2018-02-02"
			render-month="[2018,2]"
		  :show-last-month="showLastMonth"
		  :show-next-month="showNextMonth"
		  :highlight-weekend="highlightWeekend"
		  :return-six-rows="return6Rows"
		  :hide-header="true"
		  :hide-week-list="hideWeekList"
		  :replace-text-list="replaceTextList"
		  :weeks-list="weeksList"
		  :render-function="()=>{
        return '<div style=\'font-size:13px;color:#7cbd31;\'>已签</div>'
      }"
		  :disable-past="disablePast"
		  :disable-future="disableFuture"
		  :disable-weekend="disableWeekend"
		  :disable-date-function="disableDateFunction"
		  v-if="isInlineCalendar">
	  </inline-calendar>
		
		<div class="wrap-signIn">
			<div class="location-txt">
				<span class="iconfont icon-address dib"></span>
				<span class="txt dib">南山区高新南一道</span>
			</div>
			<div class="btn-signIn">签到</div>
		</div>
  </div>
截图如下：
![3](https://user-images.githubusercontent.com/20222755/38981213-6a58f9e2-43f1-11e8-8285-8e23e7d32760.png)

![2](https://user-images.githubusercontent.com/20222755/38980798-5d9a27fe-43f0-11e8-97c5-b5b998247c8b.png)

**Comment by airyland** [comment]
先确认是不是，再问为什么。
代码呢，截图呢，如何重现呢，这位同学？

**Comment by airyland** [comment]
`render-month="[2018,2]"` 绑定一个数组而不是绑定一个字符串 `:render-month="[2018,2]"`

**Comment by Qunc** [comment]
谢谢作者的耐心解答
