### ISSUE TITLE
[Feature Request] toast 、alert 等组件只能通过 this.$vux.toast .show 的形式调用吗？

### ISSUE THREAD

**Issue by lwzhang** [airyland/vux#2669]
### Existing Component
是

### Component Name
toast

### Description
toast 、alert 等组件只能通过 this.$vux.toast .show 的形式调用吗？如果我想在某个 js 文件（如 utils.js）中使用 toast ，我该怎么使用呢？

**Comment by airyland** [comment]
Alert 是支持 AlertModule 调用的，见 https://doc.vux.li/zh-CN/components/alert.html

``` js
import { AlertModule } from 'vux'

AlertModule.show({
  title: 'VUX is Cool',
  content: this.$t('Do you agree?'),
  onShow () {
    console.log('Module: I\'m showing')
  },
  onHide () {
    console.log('Module: I\'m hiding now')
  }
})
```

**Comment by lwzhang** [comment]
@airyland toast 有打算实现单独调用吗？

**Comment by lwzhang** [comment]
@airyland 像 toast 、loading 单独调用还是比较多的。

**Comment by laienshun** [comment]
相同的需求

**Comment by well-monkey** [comment]
请问怎么做呢？

**Comment by well-monkey** [comment]
toast loading  需求

**Comment by Musiker1114** [comment]
@airyland 很需要，像toast，loading 很多地方要单独调用，比如请求拦截器，在当前版本能有办法单独使用吗

**Comment by franticwind** [comment]
toast 目前还能怎么搞？
