### ISSUE TITLE
引入XIcon报错

### ISSUE THREAD

**Issue by Nikkolast88** [airyland/vux#2671]
]<script>
import { ButtonTab, ButtonTabItem, XIcon } from "vux";
export default {
  components: {
    ButtonTab,
    ButtonTabItem,
    XIcon
  }
};
</script>`
`<div class="left"><XIcon type="ios-ionic-outline"></XIcon>
      <div class="logo"><img src="../assets/images/logo.png" alt="uokobo" srcset=""></div>
   </div>`
报错
`This dependency was not found:

* vux/undefined in ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Index.vue, ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Index.vue`

**Comment by airyland** [comment]
文档错误了。XIcon 不需要引入，直接使用即可。
