### ISSUE TITLE
[Feature Request] 如何在nuxt中使用ChinaAddressV4Data

### ISSUE THREAD

**Issue by WilliamLin1990** [airyland/vux#2680]
### Existing Component
是

### Component Name
XAddress

### Description
现在不知怎么使用ChinaAddressV4Data的数据，使用js import数据后，出现
![_LANJW92OD5JQPE5NCOQ8X4.png](https://i.loli.net/2018/04/23/5adcb60d01249.png)

**Comment by airyland** [comment]
这是个 bug，可以先使用 2.9.1-rc.1。
