### ISSUE TITLE
[Feature Request] 建议grid组件加上show-td-borders属性

### ISSUE THREAD

**Issue by johisen** [airyland/vux#2683]
### Existing Component
是

### Component Name
grid

### Description
grid组件已有show-lr-borders属性，能否把show-td-borders属性也加上，这样可以控制是否显示上下边框，多行的只针对最外边框即可。

**Comment by airyland** [comment]
使用场景？并且是 `lr` 并不是 `tr`，你所说的 `td` 没理解是要隐藏哪些边线。

**Comment by johisen** [comment]
我使用的场景是一个简化的九宫格，只有两行两列，td是top&down的缩写，我想隐藏的是上下边框，目前这个grid这个组件只能隐藏左右边框。

**Comment by johisen** [comment]
使用td不够准确，使用tb更好点，tb = top&bottom。我想要的效果是能控制这个grid组件的上下左右和内部的边框都可以控制是否显示

**Comment by Tiramisu1** [comment]
我也想隐藏grid-item上下的边框 但是改变不了下边框 我发现是在item里面.weui-grid:after 中加了一个border-bottom的样式 可以怎么设置都取消不了  请问哪位有什么处理办法么
