### ISSUE TITLE
[Bug Report] xcroll

### ISSUE THREAD

**Issue by whenevery** [airyland/vux#2688]
### VUX version
2.9.0

### OS/Browsers version
all

### Vue version
2.5.16

### Code

```html
beforeDestroy () {
    if (this.pullup) {
      if (this._xscroll) this._xscroll.unplug(this.pullup)
      this.pullup.pluginDestructor()
    }
    if (this.pulldown) {
      if (this._xscroll) this._xscroll.unplug(this.pulldown)
      this.pulldown.pluginDestructor()
    }
    window.removeEventListener('orientationchange', this.handleOrientationchange, false)
    if (this._xscroll) this._xscroll.destroy()
    this._xscroll = null
  }
```

### Steps to reproduce
使用插件进入页面 如果第一个路由判断是否登录
未登录时跳转登录页面 
销毁之前页面的过程中 销毁到xscroll时 
由于页面还未进行加载 xscroll 还未生成 直接进行销毁会报错

### What is Expected?
xscroll销毁时进行存在性判断

### What is actually happening?
没有判断直接调用销毁方法 导致组件销毁失败 页面出错

**Comment by airyland** [comment]
如文档所写，该组件已经废弃，不再维护，请使用社区其他组件。
