### ISSUE TITLE
生产和开发环境下如何正确引入组件及css？

### ISSUE THREAD

**Issue by zhuqiuyang** [airyland/vux#269]
### Version
0.1.1-rc3
### Android or iOS, which browser?
both
### Steps to reproduce the problem
1. 第一个问题，按照文档中的第二种方式引入，在vux文件夹下没有此文件。如下图:
![image](https://cloud.githubusercontent.com/assets/14734729/16000020/20eff6ae-317c-11e6-8a47-75a0a2d4469f.png)
和

2. 第二个问题，按照文档中第一种方式引入，less提示找不到文件。
```
import PopupPicker from 'vux/src/components/popup-picker'
import Group from 'vux/src/components/group'
import Picker from 'vux/src/components/picker'
import XButton from 'vux/src/components/x-button'

@import '~vux/dist/vux.css';
```
装过less-loader和添加过配置
![image](https://cloud.githubusercontent.com/assets/14734729/16000069/6bce1372-317c-11e6-974c-e82ea34484d0.png)；
在npm run dev时报如下错误:
![image](https://cloud.githubusercontent.com/assets/14734729/16000084/8995b202-317c-11e6-9e5b-15ac0409593f.png)

模板用的都是vue-cli 的webpack版本。
指导一下，谢谢啦~

**Comment by airyland** [comment]
1. I forgot to update css path.
2. Vue's webpack template doesn't include less-loader, so you have to install it yourself.

**Comment by zhuqiuyang** [comment]
i have already install less-loader，but no ues.
![image](https://cloud.githubusercontent.com/assets/14734729/16000390/bad1dd80-317e-11e6-8ebe-c698ecffc62e.png)

also have errors:
![image](https://cloud.githubusercontent.com/assets/14734729/16000400/cba3a51c-317e-11e6-83ac-d16824abb908.png)

**Comment by zhuqiuyang** [comment]
ok ,thank you very much.
it's run ok.
last question,what's the differences between import Components form src/ and dist/

**Comment by airyland** [comment]
@zhuqiuyang
 Using src/component/*.vue will reduce the js bundle size after building and you don't need to include each component's style.

**Comment by zhuqiuyang** [comment]
@airyland oh,it's cool. I know.

**Comment by exoticknight** [comment]
@zhuqiuyang 
使用 src 引入还是出现问题，你是怎么解决的？
