### ISSUE TITLE
address的popup被mask盖住

### ISSUE THREAD

**Issue by sandysong** [airyland/vux#27]
如果有父div并且没有设置z-index的话，在微信下popup-picker会被mask盖住，建议把picker-dialog给append到body后面

**Comment by airyland** [comment]
@sandysong Hi，能否补下代码，我暂时还没重现这种情况

**Comment by sandysong** [comment]
代码有点乱，把address放在一个position: absolute;的父div下面。picker-dialog会被插入到这个父div里面，然后微信浏览器会按照父div的z-index来显示picker-dialog，就被mask盖住了。不过直接append到body后面也有问题，最后我还是把父div的position属性改掉了解决这个问题。

**Comment by liu121027** [comment]
我估计也遇到了同样问题，我是做后端了，还在想办法怎么解决。。。。地址弹出层后手机端没法滚动

**Comment by liu121027** [comment]
我初始化地址是[北京市，北京市，海淀区] 第二列不是默认北京市，并且第二列和第三列数据相同，导致js报错，如果我选择的海南省，第二列是海口市，第三列是海口市对应的区， 如果选了三亚市后，数据中没有区的选择，导致结果是亚市+海口市的区

**Comment by liu121027** [comment]
我这边父div 含有-webkit-overflow-scrolling: touch; 导致地址不能滑动选择

**Comment by airyland** [comment]
这种情况比较特殊。暂时关闭。如果有解决方案欢迎PR。
@liu121027 不同的问题请新开一个issue。
