### ISSUE TITLE
按照教程安装出错

### ISSUE THREAD

**Issue by JianleiZhang** [airyland/vux#270]
按照[教程](https://vuxjs.gitbooks.io/vux/content/install/vue.html)做了好多次，手动安装了less-loader，最后运行npm run build还是报错：
`ERROR in static/js/vendor.87142eb27d7b36910be3.js from UglifyJs
Unexpected token: keyword (function) [./~/vux/src/libs/router.js:1,0]`

**Comment by airyland** [comment]
webpack 配置 babel loader了吗？

**Comment by JianleiZhang** [comment]
`    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /node_modules/
      },
`
默认是这样的

**Comment by airyland** [comment]
教程里的添加loader这一步做了吗？

**Comment by JianleiZhang** [comment]
没有，我试试……

**Comment by JianleiZhang** [comment]
问题解决。

**Comment by JianleiZhang** [comment]
我本来以为{ test: /\.js$/, loader: 'babel', include: projectRoot, exclude: /node_modules/ }默认对所有js做了babel loader。

**Comment by airyland** [comment]
:smile: 教程的步骤都是必需的。其实你认真看一下node_modules的js默认都会被babel忽略。。

**Comment by JianleiZhang** [comment]
我之前是用vue init webpack-simple my-project初始化项目的，解决了前面几个问题，反而忽略了教程里的步骤。
webpack.config.js需要添
`  resolve: {
    extensions: ['', '.js', '.vue'],
    alias: {
      'src': path.resolve(__dirname, '../src')
    }
  },`
