### ISSUE TITLE
[Feature Request] InlineCalendar日历“过去的日期”和”未来的日期”的规律是什么？存放这个数据的数组在哪？

### ISSUE THREAD

**Issue by Qunc** [airyland/vux#2701]
### Existing Component
是

### Component Name
InlineCalendar

### Description
InlineCalendar日历“过去的日期”和”未来的日期”的规律是什么？或者有没有一个数组专门存放这个数据呢？在哪里可以看到？
由于能力有限我翻了很久的源码也没找到。render-function属性函数里面有一个data.formatedDate，可那无法实现我要做的需求。
我要做的是一个签到功能，需要拿到当月的所有日期（包括过去和未来日期），用以传给后端获取当月的签到记录，并且显示在InlineCalendar日历上面。卡在这个问题上折腾了好多天，求帮助

**Comment by airyland** [comment]
文档里有 `getDates` 函数可以获取。根据 `isLastMonth: true` `isNextMonth` 可以筛选是否为当月、上一月，下一月日期。
