### ISSUE TITLE
[Feature Request] vux的tabbar可以像切换tabbar文字颜色一样切换<img slot='icon' src="">的src吗

### ISSUE THREAD

**Issue by ZingerBees** [airyland/vux#2705]
### Existing Component
是

### Component Name
tabbar

### Description
tabbar-item的字体颜色会根据点击项改变，能否增加新特性，点击tabbar-item让<img slot='icon' src="">的src也可以改变？

**Comment by airyland** [comment]
使用 `slot:icon-active ` 来实现切换。

**Comment by ZingerBees** [comment]
万分感谢

**Comment by 1960665027** [comment]
跳转link，icon-active无反应，要点击两次才切换效果

**Comment by xiaoyoutongzhi** [comment]
初学,卡在这了,请问怎么解决的?

**Comment by 1960665027** [comment]
把src设成函数，监听点击的事件，js动态改变src路径


来自 魅蓝 Note6

-------- 原始邮件 --------
发件人：xiaoyoutongzhi <notifications@github.com>
时间：2018年8月7日 17:19
收件人：airyland/vux <vux@noreply.github.com>
抄送：1960665027 <18276061387@163.com>,Comment <comment@noreply.github.com>
主题：Re: [airyland/vux] [Feature Request] vux的tabbar可以像切换tabbar文字颜色一样切换<img slot='icon' src="">的src吗 (#2705)

**Comment by xyy547491937** [comment]
> 跳转link，icon-active无反应，要点击两次才切换效果


这个问题解决了吗，我现在也遇上这种问题了，每一个都得点击两侧
