### ISSUE TITLE
tab组件btn如何与下面内容联动

### ISSUE THREAD

**Issue by wulucxy** [airyland/vux#271]
### Version
0.0.117

### Android or iOS, which browser?
all

### Your Codes 

``` html
<!--put your code here-->
```

### Expected behavior and actual behavior.
tab组件btn如何与下面内容联动，目前demo里面只有上面btn的切换效果，并没有实现与内容的联动，
参考[链接](https://8.wacai.com/finance/h5/detail-jdb.action?productCode=Z20160526200206363&navTitle=%E6%9C%88%E8%96%AA%E5%AE%9D&need_zinfo=1)这里tab切换的需求

**Comment by wulucxy** [comment]
@airyland 大大看下

**Comment by airyland** [comment]
tab-item 绑定@click 事件，根据需要显示下面对应的内容。

**Comment by wulucxy** [comment]
@airyland 感觉这块需要改进下，这样做不符合组件封装的原则

**Comment by mlyknown** [comment]
@wulucxy  弱弱的问下组件封装的原则是什么，有好文的链接么~~

**Comment by airyland** [comment]
会改进的。不过你说的组件封装的原则是？tab 和 内容是两个完全独立的组件，组件互相独立，可以自由组合，理论上可以接口上作支持来联结，但不应该因为有这个需求就直接绑定在一起吧，那样太业务相关了，不能通用。

**Comment by wulucxy** [comment]
@airyland 一般选项卡功能至少具备tab索引和内容联动吧，现在左右tab索引在变，这个在业务场景里面确实无法应用。希望后面考虑加上去

**Comment by airyland** [comment]
@wulucxy tab-item可以直接绑定@click事件，你完全可以自由扩展呀，点击某个tab-item 激活某个content-container。

**Comment by airyland** [comment]
计划中Tab只会做到在tab上暴露index属性可以双向绑定，以及emit一个index-change的事件。

**Comment by airyland** [comment]
![tab-swiper](https://cloud.githubusercontent.com/assets/559179/16046346/b12d029a-327e-11e6-9525-8da92e5427b9.gif)

**Comment by wulucxy** [comment]
@airyland 请问这个demo在哪里

**Comment by airyland** [comment]
@wulucxy demo发布中，网络糟糕还没成功。

**Comment by airyland** [comment]
@wulucxy 访问https://vux.li demo里的Tab。

**Comment by wulucxy** [comment]
@airyland 看到了。谢谢

**Comment by transtone** [comment]
https://github.com/airyland/vux/issues/230
