### ISSUE TITLE
[Feature Request] IphoneX适配

### ISSUE THREAD

**Issue by wwz348627642** [airyland/vux#2710]
### Existing Component
是

### Component Name
Toast

### Description
因为iphoneX底部的智能导航问题，
官方给出了  env(safe-area-inset-bottom) 或者 constant(safe-area-inset-bottom) 方案解决，
ps: 使用该属性前，需设置view-port:
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, viewport-fit=cover">
导致所有使用fixed定位的组件且出现在页面底部的，都需要添加该属性，
把位置往上挪动, 如 
.toast { 
   position: fixed;
   bottom: 0;
   margin-bottom:  env(safe-area-inset-bottom);
   margin-bottom:  constant(safe-area-inset-bottom)
 }

**Comment by wwz348627642** [comment]
相关需要修改的
/* 兼容iphoneX */
.vux-toast-bottom {
	margin-bottom: constant(safe-area-inset-bottom);
	margin-bottom: env(safe-area-inset-bottom);
}

.vux-popup-dialog {
	margin-bottom: constant(safe-area-inset-bottom);
	margin-bottom: env(safe-area-inset-bottom);
}

.weui-actionsheet {
	margin-bottom: constant(safe-area-inset-bottom);
	margin-bottom: env(safe-area-inset-bottom);
}

**Comment by airyland** [comment]
贫穷使我无法做 iphoneX 适配，欢迎 PR 😄

**Comment by Sapphire2k** [comment]
给大神众筹一部😜

**Comment by chengjs** [comment]
@airyland 说的很有道理。😄

**Comment by Jiiiiiin** [comment]
iphonex 适配 在于状态栏和faceid，也就是说在于客户端oc那边吧，我们最近上线的云南农信手机银行进行了适配，前端好像不用做什么的。呵呵
