### ISSUE TITLE
从2.3.1更新到最新版本运行报错

### ISSUE THREAD

**Issue by tangqi9** [airyland/vux#2716]
升级vux版本的时候，运行后报错：
error  in ./~/vux/src/plugins/wechat/index.js；
wechat文件并没有改动过
![tim 20180503110708](https://user-images.githubusercontent.com/28030865/39568387-ad97331e-4ef4-11e8-823e-fb4517d0edac.png)

**Comment by airyland** [comment]
不按 issue template 来，没有其他环境信息，无法重现。
