### ISSUE TITLE
[Bug Report]  get-parent-prop.js

### ISSUE THREAD

**Issue by lilong7676** [airyland/vux#2720]
### VUX version
2.9.1-rc.1

### OS/Browsers version
macOS / chrome 66.0.3359.139

### Vue version
2.5.16

### Code

```html
export default function (self, name) {
  if (self.$parent && self.$parent[name]) {
    return self.$parent[name]
  }
  if (self.$parent && self.$parent.$parent && self.$parent.$parent[name]) {
    return self.$parent.$parent[name]
  }
}
```

### Steps to reproduce
应修改  if (self.$parent && self.$parent[name]) 
为 if (self.$parent && self.$parent[name] !== undefined)

修改 if (self.$parent && self.$parent.$parent && self.$parent.$parent[name])
为 if (self.$parent && self.$parent.$parent && self.$parent.$parent[name] !== undefined)

防止获取到parentProp的值为 0 或其他 false 值时判断错误问题。

### What is Expected?
请参考 重现步骤。

### What is actually happening?
请参考 重现步骤。

**Comment by airyland** [comment]
thanks for feedback.
