### ISSUE TITLE
插件调用，引入插件出错

### ISSUE THREAD

**Issue by xiazhaowei** [airyland/vux#2721]
在 main.js 中引入插件

import { AlertPlugin, ToastPlugin } from 'vux'

报一下错误

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/popup-picker/index.vue
Module not found: Error: Can't resolve '../inline-desc' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/popup-picker'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/popup-picker/index.vue 7:0-40
 @ ./~/vux/src/components/popup-picker/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-switch/index.vue
Module not found: Error: Can't resolve '../inline-desc' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/x-switch'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-switch/index.vue 3:0-40
 @ ./~/vux/src/components/x-switch/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-textarea/index.vue
Module not found: Error: Can't resolve '../inline-desc' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/x-textarea'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-textarea/index.vue 4:0-40
 @ ./~/vux/src/components/x-textarea/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-input/index.vue
Module not found: Error: Can't resolve '../inline-desc' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/x-input'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-input/index.vue 6:0-40
 @ ./~/vux/src/components/x-input/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/check-icon/index.vue
Module not found: Error: Can't resolve '../icon' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/check-icon'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/check-icon/index.vue 3:0-27
 @ ./~/vux/src/components/check-icon/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/checklist/index.vue
Module not found: Error: Can't resolve '../icon' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/checklist'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/checklist/index.vue 5:0-27
 @ ./~/vux/src/components/checklist/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/color-picker/index.vue
Module not found: Error: Can't resolve '../icon' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/color-picker'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/color-picker/index.vue 3:0-27
 @ ./~/vux/src/components/color-picker/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/datetime/index.vue
Module not found: Error: Can't resolve '../icon' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/datetime'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/datetime/index.vue 3:0-27
 @ ./~/vux/src/components/datetime/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/step/step-item.vue
Module not found: Error: Can't resolve '../icon' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/step'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/step/step-item.vue 3:0-27
 @ ./~/vux/src/components/step/step-item.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/timeline/timeline-item.vue
Module not found: Error: Can't resolve '../icon' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/timeline'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/timeline/timeline-item.vue 3:0-27
 @ ./~/vux/src/components/timeline/timeline-item.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-input/index.vue
Module not found: Error: Can't resolve '../icon' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/x-input'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-input/index.vue 4:0-27
 @ ./~/vux/src/components/x-input/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/checklist/index.vue
Module not found: Error: Can't resolve '../tip' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/checklist'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/checklist/index.vue 4:0-25
 @ ./~/vux/src/components/checklist/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/datetime/index.vue
Module not found: Error: Can't resolve '../group' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/datetime'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/datetime/index.vue 5:0-29
 @ ./~/vux/src/components/datetime/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/datetime-range/index.vue
Module not found: Error: Can't resolve '../popup-picker' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/datetime-range'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/datetime-range/index.vue 4:0-42
 @ ./~/vux/src/components/datetime-range/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-address/index.vue
Module not found: Error: Can't resolve '../popup-picker' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/x-address'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/x-address/index.vue 5:0-42
 @ ./~/vux/src/components/x-address/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/datetime-view/index.vue
Module not found: Error: Can't resolve '../datetime' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/datetime-view'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/datetime-view/index.vue 3:0-35
 @ ./~/vux/src/components/datetime-view/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/inline-x-number/index.vue
Module not found: Error: Can't resolve '../x-number' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/inline-x-number'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/inline-x-number/index.vue 3:0-34
 @ ./~/vux/src/components/inline-x-number/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/popup-picker/index.vue
Module not found: Error: Can't resolve '../picker' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/popup-picker'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/popup-picker/index.vue 3:0-31
 @ ./~/vux/src/components/popup-picker/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/popup-radio/index.vue
Module not found: Error: Can't resolve '../radio' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/popup-radio'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/popup-radio/index.vue 7:0-29
 @ ./~/vux/src/components/popup-radio/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/tabbar/tabbar-item.vue
Module not found: Error: Can't resolve '../badge' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/tabbar'
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/tabbar/tabbar-item.vue 4:0-29
 @ ./~/vux/src/components/tabbar/tabbar-item.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/vux/src/plugins/alert/util.js
Module not found: Error: Can't resolve '../../components/alert' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/plugins/alert'
 @ ./~/vux/src/plugins/alert/util.js 3:0-52
 @ ./~/vux/src/plugins/alert/index.js
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/vux/src/components/flexbox/index.js
Module not found: Error: Can't resolve './flexbox' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/flexbox'
 @ ./~/vux/src/components/flexbox/index.js 1:0-32
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/picker/index.vue
 @ ./~/vux/src/components/picker/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/vux/src/components/flexbox/index.js
Module not found: Error: Can't resolve './flexbox-item' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/flexbox'
 @ ./~/vux/src/components/flexbox/index.js 2:0-41
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/picker/index.vue
 @ ./~/vux/src/components/picker/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

ERROR in ./~/vux/src/components/swiper/index.js
Module not found: Error: Can't resolve './swiper-item' in '/Users/xiazhaowei/Downloads/grove_app/node_modules/vux/src/components/swiper'
 @ ./~/vux/src/components/swiper/index.js 2:0-39
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vux/src/components/week-calendar/index.vue
 @ ./~/vux/src/components/week-calendar/index.vue
 @ ./~/vux/index.js
 @ ./www/src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./www/src/main.js

**Comment by xiazhaowei** [comment]
我的  配置为
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: [{
      name: 'vux-ui'
    },
    {
      name: 'js-parser'
    }
  ]
})

**Comment by airyland** [comment]
https://doc.vux.li/zh-CN/faq/cannot-resolve-inline-desc.html
