### ISSUE TITLE
v-chart模块无法使用，提示找不到模块

### ISSUE THREAD

**Issue by koukouzaki** [airyland/vux#2725]
### VUX version
2.9.0

### OS/Browsers version
win10/chrome

### Vue version
2.5.2

### Code

```html
import {  VChart, VTooltip, VLine, VScale } from 'vux'，

components: {
    VChart,
    VTooltip,
    VLine,
    VScale
  },
```

### Steps to reproduce
根据网站上的例子一模一样加载的。

### What is Expected?
能否可以提供如何能正确使用v-chart组件的步骤。

### What is actually happening?
页面中按照例子，加载了v-chart的内容，但是提示模块没找到，查询node_modules/vux/src/components下，没有x-chart，与github上的components里的不一致。使用常规的npm安装、淘宝镜像安装、yarn安装，都没有此文件夹。
直接下载github的文件覆盖，又会有其他错误……

**Comment by airyland** [comment]
这个组件在明天发布。

**Comment by lgphp** [comment]
还没发布啊

**Comment by extreming** [comment]
v-chart好像只是有文档，现在还不能用，还是会提示找不到模块

**Comment by tong-zhou** [comment]
为啥还有这个问题？是哪里配置出错了嘛？
