### ISSUE TITLE
[Feature Request] xdialog的样式问题

### ISSUE THREAD

**Issue by halfing** [airyland/vux#2726]
#
![cpyck ovxlwencxxs j0mw](https://user-images.githubusercontent.com/18585482/39671964-58c11a14-5154-11e8-8d1b-4acdcdc0fc95.png)
![vs hp1xf2 67 ykxb_2e](https://user-images.githubusercontent.com/18585482/39671966-61291eb8-5154-11e8-8e20-9aa545278b95.png)

 generated by https://doc.vux.li/issue-generator DO NOT REMOVE -->

### Existing Component
是

### Component Name
xdialog

### Description
发现相同项目下，两个人机子打开就是两种样式[图片][图片]

**Comment by airyland** [comment]
请上传图片。

**Comment by airyland** [comment]
样式不一致一般是版本不一致，请使用 yarn 锁版本。
