### ISSUE TITLE
XHeader 与 PopupPicker 样式冲突

### ISSUE THREAD

**Issue by loerise** [airyland/vux#273]
### Codes 

``` html
<x-header :left-options="{showBack: true}">预约</x-header>
<group>
  <popup-picker :title="'车型分类'" :data="carType" :value.sync="carTypeValue"></popup-picker>
  <popup-picker :title="'费用预算'" :data="costBudget" :value.sync="costBudgetValue"></popup-picker>
</group>
```

#### PopupPicker 的 dom 层级为

div.picker-dialog >
  div.vux-container >
    div.vux-header
  
其中第三级的 classname 为 "vue-header"
与 XHeader 的 dom 结构第一级 div.vux-header 的 classname 相同

导致 PopupPicker 弹出层上方的 "取消、完成" 按钮背景颜色与 XHeader 的背景颜色一样，而原本应该是灰色

### 图片链接
![问题截图](https://ooo.0o0.ooo/2016/06/15/5761042376ef4.png)

**Comment by airyland** [comment]
#245 已经修复，这两天会有新版本发布。
