### ISSUE TITLE
[Bug Report] nuxt里引用vux时，import Actionsheet from './src/components/actionsheet/index.vue' 报错  请问vux-loader如何配置

### ISSUE THREAD

**Issue by kuangyazhou** [airyland/vux#2738]
### VUX version
2.9.0

### OS/Browsers version
win10 64位 /chrome 60

### Vue version
2.5.0

### Code

```html
nuxt里引用vux时，import Actionsheet from './src/components/actionsheet/index.vue' 报错  请问vux-loader如何配置
```

### Steps to reproduce
nuxt里引用vux时，import Actionsheet from './src/components/actionsheet/index.vue' 报错  请问vux-loader如何配置

### What is Expected?
正确引用vux

### What is actually happening?
vux无法引用

**Comment by WilliamLin1990** [comment]
不是用demo了吗，按那个demo来，把actionsheet的引入写到plugins/vux-components.js，没问题

**Comment by kuangyazhou** [comment]
@WilliamLin1990  你好，能贴出示例代码么，我按照demo的配置，无法运行

**Comment by WilliamLin1990** [comment]
@kuangyazhou 在vux-components.js中: 
`import Actionsheet from 'vux'
Vue.component('actionsheet', Actionsheet)`

**Comment by kuangyazhou** [comment]
ok。。。感谢~

**Comment by aaawhz** [comment]
没用啊
