### ISSUE TITLE
[Feature Request] InlineCalendar是否可以禁止选择所有日期?

### ISSUE THREAD

**Issue by Qunc** [airyland/vux#2739]
### Existing Component
是

### Component Name
InlineCalendar

### Description
InlineCalendar是否可以禁用选择所有日期?或者怎么让on-select-single-date事件只执行一个return false呢？

我的使用场景只是把日历当作纯展示来用，展示当天是否已签到。所以不想要有默认的选中之后的效果。

之前是改源码直接删除对应的事件来解决这个问题的，但是后面项目当中又用到了Calendar组件，需要用到选择日期的效果，所以希望能得到其他的解决办法，谢谢

**Comment by wenjiangs** [comment]
设置属性 disable-date-function 返回 false 就行了，最后修改下样式
`<inline-calendar
          v-model="selectDate"
          :hide-header="true"
          :disable-date-function="disableFunc"
        ></inline-calendar>`

`disableFunc(e) {
      return true;
    }`
