### ISSUE TITLE
你好，有提供加载更多的组件么

### ISSUE THREAD

**Issue by EasonShen1989** [airyland/vux#2745]

**Comment by doommm** [comment]
如果不需要下拉加载的话是不是直接做一个按钮到列表末尾就好了？
需要下拉加载的话请考虑采用其它库，比如`better-scroll`，vux的`scroller`已经不维护了

**Comment by EasonShen1989** [comment]
vux的scroller能用么？

**Comment by unclay** [comment]
scroller不维护了，有load-more的ui组件，可以自己写滚动加载逻辑
