### ISSUE TITLE
2.9弹窗出现时动画效果错误

### ISSUE THREAD

**Issue by keepeye** [airyland/vux#2746]
### VUX version
0.1.0

### OS/Browsers version
chrome65

### Vue version
2.5.2

### Code

```html
    <group>
      <cell title="绑定微信" is-link @click.native="bindWx">
        {{ user.nickname || '立即绑定'}}
      </cell>
      <x-switch title="是否接收" :value="user.subscribe_offline_alarm" :value-map="[0, 1]" prevent-default @on-click="onClick"></x-switch>
    </group>


   onClick:

onClick (newVal, oldVal) {
      let app = this
      if (this.user.openid === '') {
        this.$vux.confirm.show({
          content: '开通此功能需要绑定微信',
          confirmText: '立即绑定',
          onConfirm () {
            app.gotoBindWx()
          }
        })
        return
      }
```

### Steps to reproduce
当group中出现cell组件的时候，弹窗组件 confirm alert出现效果变成了旋转出现，查看编译后的css发现，.vux-dialog-enter-active 类使用的 animation被编译成了 animation:a  ，而 @keyframe a 是一个cell组件带来的loading旋转动画应该，很奇怪。
降回2.8以后没这个问题了。

### What is Expected?
弹窗正常出现

### What is actually happening?
旋转出现

**Comment by huiliangShen** [comment]
我也有这个问题，不知道楼上怎么解决的？

**Comment by keepeye** [comment]
@huiliangShen 降级，老版本没这个问题

**Comment by huiliangShen** [comment]
@keepeye 我昨天发现了问题原因。。并不是版本问题导致旋转，是因为cssnao 压缩css代码 把动画名称改成了a，匹配到其他组件的动画上去了。版本2.9 还是没问题的。

**Comment by laienshun** [comment]
cssnao 的配置加个这个就可以取消转换了，
"postcss-reduce-idents": false

**Comment by huiliangShen** [comment]
是的，我后来看了下文档，配置了这个属性。或者 preset: "default" 也可以，默认就不开启了

**Comment by FrankRoc** [comment]
看[这个问题 ](https://github.com/airyland/vux/issues/3101)
