### ISSUE TITLE
[Feature Request] Calendar怎么限定只能双选

### ISSUE THREAD

**Issue by Qunc** [airyland/vux#2747]
### Existing Component
是

### Component Name
Calendar

### Description
Calendar怎么限定只能双选？能不能提供一下解决办法呢，比如在源码的哪个方法里面限定？看了很久源码，但个人能力有限，急需这个功能。希望能够得到帮助，谢谢！

**Comment by unclay** [comment]
源码可以这里改，但不建议改源码

https://github.com/airyland/vux/blob/8cc829907301e9efb2070833cfdcd5e461a14dce/src/components/inline-calendar/index.vue#L393

改为

```js
if (this.currentValue.length < 2) {
  this.currentValue.push(_currentValue)
}
```
