### ISSUE TITLE
[Feature Request] x-textarea方法updateAutosize怎么调用啊，示例源码中也没有

### ISSUE THREAD

**Issue by zoujian3820** [airyland/vux#2749]
### Existing Component
是

### Component Name
x-textarea

### Description
x-textarea方法updateAutosize怎么调用啊，示例源码中也没有，直接this.$vux.xtextarea.updateAutosize()会报错，
console.log(this.$vux)发现没有x-textarea这个属性

**Comment by zoujian3820** [comment]
好了，找到调用方法了，直接调用组件方法就行了this.$refs.textarea.updateAutosize()

**Comment by wsh0521** [comment]
但是我打印this.$refs.textarea.updateAutosize()出来是undefined ，代码也没有执行呀

**Comment by ZhuChenn** [comment]
<group :title="group2title">
        <x-textarea v-model="summary" :max="200" name="description" placeholder="请输入今天工作总结"
                    autosize ref="textarea"></x-textarea>
      </group>

this.$refs.textarea.updateAutosize()
我这样使用，报错，打印是  undefined
请问是什么原因？
