### ISSUE TITLE
可以提个用Swiper.js代替wechatui swiper方案的PR么

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#275]
发现目前使用的wechatui swiper方案比较简陋，最大的bug是，如果swiper高度太高，手指按在swiper区域的时候，是无法上下滑动的。

不知道是否接受改用Swiper.js方案的PR。
http://idangero.us/swiper

**Comment by airyland** [comment]
目前就是希望体积比较小。其实上下滑动我没有去测试，因为一直都是对左右滑动做了一些修改没有测试是否对上下滑动有影响。你提到的这个有关注过，不过体积接近80k, 用于普通的轮播有点大材小用，我更希望做成新的组件，让用户可以根据需求来选择，而不是替代。所以如果有兴趣的话可以PR一个名为`x-swiper`的新组件。:smile:
