### ISSUE TITLE
[Bug Report] 如果我还是在swiper里嵌套了scroller

### ISSUE THREAD

**Issue by ghostNv** [airyland/vux#2751]
### VUX version
2.9.1

### OS/Browsers version
window 7    Chrome

### Vue version
2.5.17-beta.0

### Code

```html
  let data = {
              type: 1,
              pageNum: 1,
              pageSize: 10
            };
            this.$http.get('zhyw/news',{params: data}).then((resp) => {
                this.zcList = this.zcList.concat(resp.data.data.list);
              this.$nextTick(() => {
                this.$refs.scroller1.donePullup();
                this.$refs.scroller1.reset();
              })
            });


  <scroller lock-x  use-pulldown use-pullup :pulldown-config="{content:'下拉刷新',downContent:'下拉刷新',upContent:'释放刷新',loadingContent:'加载中'}" :pullup-config="{content:'',upContent:'',downContent:'上拉加载',loadingContent:'加载中'}" @on-pullup-loading="loadMore1"  @on-pulldown-loading="refresh2" ref="scroller2" :scroll-bottom-offst="200">
           
```

### Steps to reproduce
我现在想实现上拉加载更多，现在数据已经成功加载到（测试用数据，没有做判断），但是页面静止滚动，有没有什么方法么，这个问题已经很多天了，我也试过直接在scroller里，外面不包过swiper，但是，在设置了上述配置之后，还是无法滚动，想知道为什么？

### What is Expected?
我现在想实现上拉加载更多，现在数据已经成功加载到（测试用数据，没有做判断），但是页面静止滚动，有没有什么方法么，这个问题已经很多天了，我也试过直接在scroller里，外面不包过swiper，但是，在设置了上述配置之后，还是无法滚动，想知道为什么？

### What is actually happening?
数据加载没有问题，单页面无法滚动。

**Comment by airyland** [comment]
scroller 已经废弃，文档也写了不支持 swiper + scroller 的使用，那么问题只能自己解决了，抱歉。
