### ISSUE TITLE
support vue cli 3.0 ?

### ISSUE THREAD

**Issue by fanyongfeng** [airyland/vux#2752]
新版的cli 里面，配置都在vue.config.js里面， vuex-loader 应该怎么设置呢

**Comment by fanyongfeng** [comment]
configureWebpack: config => {
		vuxLoader.merge(config, {
			plugins: ['vux-ui']
		});
	},
不能return 出来！！

**Comment by fanyongfeng** [comment]
??? 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。

**Comment by peanutYu** [comment]
请问这个问题解决了吗

**Comment by Jiiiiiin** [comment]
关注

**Comment by mqhe2007** [comment]
关注，这个解决了吗？

**Comment by fanyongfeng** [comment]
只能按需 引入   import { xx } from 'vux'    不然会把所有的打包进去

**Comment by wkl007** [comment]
同，我也碰到一样的问题 @fanyongfeng ，说如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。

**Comment by zhangyt93** [comment]
请问有解决方案了吗？同遇到一样的问题

**Comment by wkl007** [comment]
vue-cli 3.0正式版已出，希望可以出了3.0安装配置说明，谢谢

**Comment by xiongsongsong** [comment]
我也遇到了，求在vue.config.js中的配置写法。

**Comment by sunny15100** [comment]
同求

**Comment by xiongsongsong** [comment]
用有赞的vant，麻烦更少 @wkl007  @sunny15100

**Comment by airyland** [comment]
#3430
