### ISSUE TITLE
v-chart 报错

### ISSUE THREAD

**Issue by qiaohengshan** [airyland/vux#2753]
ERROR  Failed to compile with 1 errors                                                                                           18:17:42

 error  in ./node_modules/_vux@2.9.1@vux/src/components/v-chart/mixin.js

Module parse failed: Unexpected token (18:6)
You may need an appropriate loader to handle this file type.
|     this.$parent.set(this.chartName, {
|       shape: defaultShapeMap[this.chartName] || '',
|       ...this.$props,
|       ...camelAttrs(this.$attrs)
|     })

**Comment by airyland** [comment]
语法报错，babel 没配置对，请检查。

**Comment by hongsige1989** [comment]
咋改 babel啊

**Comment by shen-lan** [comment]
大兄弟解决了吗？

**Comment by FANZHETWO** [comment]
不行，安装了 "babel-polyfill": "^6.26.0",  还是报错

**Comment by FANZHETWO** [comment]
有没有安装好vux-loader  并在build/webpack.base.conf.js 配置好相关代码？  https://doc.vux.li/zh-CN/install/npm.html

**Comment by amwihtfei** [comment]
同样的问题，这个vux-loader 是1.2.9版本的，应该是目前最新版本；求指定解决
