### ISSUE TITLE
关于popover的一个使用问题

### ISSUE THREAD

**Issue by mitboy1983** [airyland/vux#2754]
用popover实现了一个点击以后出现排序的多个选择内容，当我点击一个排序内容时候，能否实现让 popover这个弹出的内容框自动关闭。

可能我不应该用popover来实现这个功能，但是css确实太菜，看这个组件刚好能满足就用了

望懂的朋友指点一下

![image](https://user-images.githubusercontent.com/31514741/39961572-a629fb74-566b-11e8-90ff-751dcb83b706.png)

比如我点上面弹出的 一个 排序选项 然后这个弹出框自动的关闭掉，现在是点了 以后 这个弹出的东东还在

**Comment by fanyongfeng** [comment]
短解 的办法是 点击之后 直接去修改 这个popover 对应的 css

**Comment by fanyongfeng** [comment]
或者你还可以基于作者的 popover 实现一份自己的，传入 一个 visible props  自己控制visible 来实现 隐藏和展示
