### ISSUE TITLE
Popup，v-transfer-dom一引用这个组件就报错

### ISSUE THREAD

**Issue by linheqin** [airyland/vux#2755]
跟着教程走，引用这两个组件就报错  
client?b989:161 [WDS] Errors while compiling. Reload prevented.
errors @ client?b989:161
onmessage @ socket.js?6add:41
EventTarget.dispatchEvent @ sockjs.js?cb5d:170
(anonymous) @ sockjs.js?cb5d:883
SockJS._transportMessage @ sockjs.js?cb5d:881
EventEmitter.emit @ sockjs.js?cb5d:86
WebSocketTransport.ws.onmessage @ sockjs.js?cb5d:2957
client?b989:167 ./node_modules/_css-loader@0.28.11@css-loader?{"sourceMap":false}!./node_modules/_vue-loader@13.7.1@vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-c475e54e","scoped":false,"hasInlineConfig":true}!./node_modules/_vux-loader@1.2.8@vux-loader/src/after-less-loader.js!./node_modules/_less-loader@2.2.3@less-loader?{"sourceMap":false}!./node_modules/_vux-loader@1.2.8@vux-loader/src/style-loader.js!./node_modules/_vue-loader@13.7.1@vue-loader/lib/selector.js?type=styles&index=0!./node_modules/_vux@2.9.1@vux/src/components/popup/index.vue
Module build failed: Error: Failed to find '../../styles/vux-modal.css'
  in [
    E:\project\yunsd_restaurant

**Comment by airyland** [comment]
虽然我想帮你解决问题，但是你故意忽略了 issue template，请你再看看 issue template? 再看看项目首页的提示？。这类问题也缺失可重现 repo，显然项目配置了其他东西，但是没有写出来，所以无法解决。

**Comment by linheqin** [comment]
resolve: {
  extensions: ['', '.js', '.vue', '.json']
}

**Comment by linheqin** [comment]
我跟你的操作去配置了呀

**Comment by linheqin** [comment]
而且还是用vux2.0的模板的
