### ISSUE TITLE
[Bug Report] x-number在ios上，键盘中没有小数点

### ISSUE THREAD

**Issue by tinder1024** [airyland/vux#2760]
### VUX version
2.9.1

### OS/Browsers version
ios

### Vue version
2.5.17-beta.0

### Code

```html
<x-number></x-number>
```

### Steps to reproduce
直接使用x-number组件，在ios中，点击数字，弹出键盘

### What is Expected?
可以输入小数点

### What is actually happening?
键盘中无小数点，只能输入0-9

**Comment by bboyjing** [comment]
可以尝试在mounted中修改pattern： `this.$refs.***.$el.children[1].children[0].children[1].setAttribute('pattern','-?[0-9]*')`

**Comment by qixianchuan** [comment]
我是在直接在页面上的js修改下input number的pattern
