### ISSUE TITLE
[Feature Request] marquee组件只有上下滚，能否增加左右滚动

### ISSUE THREAD

**Issue by kuangyazhou** [airyland/vux#2762]
### Existing Component
是

### Component Name
marquee marquee-item

### Description
marquee目前只提供竖向滚动方式，当内容过多时，单行无法显示，希望能提供横向滚动方案

**Comment by wg5945** [comment]
我之前写过一个横向滚动的demo，可以参考下 https://github.com/wg5945/vue-marquee-tips
