### ISSUE TITLE
[Feature Request] 请问可以单独获取省一列，然后再获取市，最后获取区吗？

### ISSUE THREAD

**Issue by MiaoJiHui** [airyland/vux#2764]
### Existing Component
Yes

### Component Name
x-address

### Description
现在省市区的数据都是一起显示在x-address组件中的。
因为我们后端的接口都是分开的三个，所以我只能先请求省接口，获取所有省的列表。
然后再根据省id，获取所有市列表。以此类推 区列表。
请问作者，这种方式有办法可以解决吗？看了以往issures好像都没有类似的。

**Comment by unclay** [comment]
可以按照地址的数据结构格式，每次请求完接口重组数据就可以

**Comment by MiaoJiHui** [comment]
重组数据是没问题。关键需要请求的接口数太多了，最后我们让后台重新给了一个所有省市区的数据接口。

**Comment by MiaoJiHui** [comment]
还是好好和后台协商吧。
