### ISSUE TITLE
vux 之<x-icon>图标报错

### ISSUE THREAD

**Issue by VictorChan006** [airyland/vux#2765]
**Module build failed: Error: ENOENT: no such file or directory, open 'F:\项目\test\node_modules\vux\src\icons\undefined.svg'**

![vux](https://user-images.githubusercontent.com/38485905/40156879-8c33d13e-59ce-11e8-862b-d390c58efa13.PNG)

**Comment by WilliamLin1990** [comment]
x-icon 的 type 所指定的icon不存在，该icon 应该在node_modules/vux/src/icons中

**Comment by VictorChan006** [comment]
并不是，我看过这个文件夹，里面确实有我用的type 对应的svg

**Comment by unclay** [comment]
无法判断问题，可以贴上无业务逻辑的demo

**Comment by airyland** [comment]
连代码都不帖的 issue 无法处理。

**Comment by lujiajian666** [comment]
<x-icon :type=" true? 'ios-circle-filled' : 'ios-circle-outline'" size="30"></x-icon>
 像这种就会报undefined.svg的错误
