### ISSUE TITLE
[Bug Report] 在使用button-tab时，怎么修改他的默认样式。比如边框颜色，item的背景颜色

### ISSUE THREAD

**Issue by ghostNv** [airyland/vux#2768]
### VUX version
2.9.1

### OS/Browsers version
window 7 Chrome

### Vue version
2.5.17-beta.0

### Code

```html
 <button-tab height="35">
                <button-tab-item >全部</button-tab-item>
                <button-tab-item >已读</button-tab-item>
                <button-tab-item>未读</button-tab-item>
              </button-tab>
```

### Steps to reproduce
如何修改默认的样式

### What is Expected?
样式只能使用默认的

### What is actually happening?
实现自定义的样式

**Comment by unclay** [comment]
可通过自定义主题样式更改，里面就包含了button-tab
主题配置：[https://doc.vux.li/zh-CN/development/theme.html](url)
button-tab样式变量：https://doc.vux.li/zh-CN/components/button-tab.html
