### ISSUE TITLE
使用view-box布局保存页面位置问题

### ISSUE THREAD

**Issue by haowenwan** [airyland/vux#2769]
从列表进到详情页再返回到列表页时keepAlive，无法保存已经滚动的高度，都是从顶部开始

**Comment by unclay** [comment]
看文档：[https://doc.vux.li/zh-CN/components/view-box.html](url)
如果你想保存滚动距离，推荐使用vuex实现，在特定path对scrollBody监听scroll事件，并获取滚动距离保存到vuex的state里。示例可以参考vux源码的App.vue
