### ISSUE TITLE
flexbox 重新设计

### ISSUE THREAD

**Issue by transtone** [airyland/vux#277]
现在的 flexbox 没有除开 css 之外的太多功能，样式也不齐全。用起来十分的不便。是否可以参考 auicss 的 flex 设计（ http://auicss.com/?m=Home&c=Document#AUIFlex ）重新设计一下？

**Comment by airyland** [comment]
样式不齐全？

**Comment by transtone** [comment]
https://github.com/liulangnan/aui/blob/master/css/aui-flex.css 这里的功能有些没有吧：
flex-direction，justify-content 等等，用库就是不想自己写。

**Comment by airyland** [comment]
那只是加个样式支持，不叫重新设计吧。

**Comment by transtone** [comment]
赞，这么快就加上了。

有个小疑问请教一下，vuejs应该是有 autoprefixer 功能的，但flex里还是添加了prefixList选项，是基于什么考虑呢？

**Comment by airyland** [comment]
@transtone 之前似乎是因为构建后样式有点问题，后面看看取消后是不是构建正常，是的话就删除这个处理。
