### ISSUE TITLE
[Feature Request] vux可以与lavas集成吗

### ISSUE THREAD

**Issue by q759410559** [airyland/vux#2770]
### Existing Component
是

### Component Name
Toast

### Description
lavas和vux组件集成没问题，但集成类型Toast这样的插件，就报SyntaxError: Unexpected token import 这样的错，有没有什么好的解决方法？

**Comment by unclay** [comment]
目测可能babel配置问题，可以检查下webpack

**Comment by wangxingkang** [comment]
@q759410559 请问解决了吗，vuxLoader 是如何配置的。
