### ISSUE TITLE
table组件

### ISSUE THREAD

**Issue by lsw1990** [airyland/vux#2782]
### VUX version
2.9.1

### OS/Browsers version
window

### Vue version
2.5.17-beta.0

### Code

```html
<tab bar-active-color="#668599" :line-width="1">
      <tab-item>已发货</tab-item>
      <tab-item selected>未发货</tab-item>
      <tab-item>全部订单</tab-item>
      <tab-item>全部订单</tab-item>
      <tab-item>全部订单</tab-item>
    </tab>

```

### Steps to reproduce
官方示例就有这个问题，https://doc.vux.li/zh-CN/components/tab.html，官方示例问题tab，"设置bar颜色"那个tab

### What is Expected?
能够对齐

### What is actually happening?
不能都对齐

**Comment by airyland** [comment]
请写对组件名字。
请描述清楚, 什么叫不能都对齐。
文档链接错误，这个你也应该能注意到，请修正。

编辑，补充信息后【reopen】当前 issue。
