### ISSUE TITLE
[Feature Request] dateFormat工具使用了RegExp非标准语法

### ISSUE THREAD

**Issue by Blueria** [airyland/vux#2785]
### Existing Component
否

### Component Name
dateFormat

### Description
看了一下dateFormat工具的源码，发现里面使用了RegExp非标准语法
参考：[RegExp.$1-$9](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n)
虽然浏览器都支持，但直接在生产环境使用真的好吗？

**Comment by airyland** [comment]
欢迎 pr
