### ISSUE TITLE
请问在源码中的app.vue中如下变量是在哪里定义的，另外在项目中我想使用如下形式定义link该如何实现

### ISSUE THREAD

**Issue by lxglife** [airyland/vux#2789]
![image](https://user-images.githubusercontent.com/10628640/40416481-f826fe6c-5eaf-11e8-9535-ba88369d3200.png)
![image](https://user-images.githubusercontent.com/10628640/40416532-1bc4a720-5eb0-11e8-9cb5-e3acabf82daf.png)

**Comment by wg5945** [comment]
可以先了解下vuex的实现
