### ISSUE TITLE
如何使用PopupPicker里的OnHide事件？

### ISSUE THREAD

**Issue by JianleiZhang** [airyland/vux#279]
请问组件内部事件如何使用，有demo吗？

**Comment by airyland** [comment]
popup-picker 目前并没有on-hide事件。用于什么场景？

**Comment by JianleiZhang** [comment]
`@click="onHide(false)">取消</flexbox-item>`
`@click="onHide(true)">完成</flexbox-item>`

`  onHide (type) {
      this.show = false
    }`

源码里有绑定onHide事件。

**Comment by airyland** [comment]
有绑定，但是没有$emit，因此外部不能使用。

**Comment by JianleiZhang** [comment]
我准备在用户选择后触发状态改变，用vuex。

**Comment by JianleiZhang** [comment]
那只能拷贝一份到自己的src里然后修改onHide事件吗？

**Comment by airyland** [comment]
v0.1.1 会支持。

**Comment by JianleiZhang** [comment]
谢谢
