### ISSUE TITLE
[Bug Report] alert弹窗需提供单独的点击事件，而非on-hide事件

### ISSUE THREAD

**Issue by Camellia55** [airyland/vux#2795]
### VUX version
2.9.1

### OS/Browsers version
2.7.7

### Vue version
2.5.17-beta.0

### Code

```html
<alert v-on:hide="doSomething()"></alert>
```

### Steps to reproduce
如果不点击alert组件的确认键，直接点击回退，也会执行doSomething()方法。。主要是我的doSomething是跳转另一个页面的，所以一回退就跳转。

### What is Expected?
alert组件增加on-alert事件，跟on-hide区分开

### What is actually happening?
alert只提供了on-hide事件

**Comment by wangshantao** [comment]
从你的需求来看，用comfirm组件会不会好些

**Comment by Camellia55** [comment]
但是从业务逻辑来看，我只能用alert组件，用户只有一个选择。有解决方法吗？

**Comment by unclay** [comment]
我也觉得comfirm好点，让comfirm支持隐藏取消按钮即可

**Comment by unclay** [comment]
下版本confirm支持showCancelButton和showConfirmButton
