### ISSUE TITLE
Range，增加激活/失焦或touchstart/touchend事件

### ISSUE THREAD

**Issue by sailstar** [airyland/vux#2804]
想用range做个拉动验证激活码，激活range时弹出激活码图片，失焦时隐藏图片。但些组件未提供相应事情回调，有什么办法可以增加。

**Comment by unclay** [comment]
下个版本支持

**Comment by sailstar** [comment]
这么快有响应，还以为是我昨天没认真看文档呢....已经在做替代方案了，看来不用改了。另外，[#2606 Range，on-change事件的意思是](https://github.com/airyland/vux/issues/2606)：on-change事件是在拉动时立即触发的，能不能在手移开后再触发，或者增加一个。

**Comment by unclay** [comment]
看下commit，已经加了touchstart和touchend，你说的那个手离开触发的应该可以用touchend

**Comment by sailstar** [comment]
好的谢谢

**Comment by sailstar** [comment]
测试了@on-touchstart和@on-touchend好像无效

**Comment by sailstar** [comment]
2.9.2

**Comment by unclay** [comment]
看了下官网demo是有的，你重新检查下，如果确定有问题，可以贴下重现代码

**Comment by nicoleXue1** [comment]
设置最小值为0 最大值为100 步长为10 但是30拖一下 就变成 41了
