### ISSUE TITLE
问个蠢问题，不用vue文件只用js和html怎么配置vux

### ISSUE THREAD

**Issue by jlcool** [airyland/vux#2805]
Existing Component

是

Component Name

x-button

Description

想把现有项目配置上vux，怎么不用vue文件只用js和html怎么配置vux

**Comment by unclay** [comment]
与vux无关
可以用umd格式，但已不推荐

**Comment by jlcool** [comment]
就是不想用umd格式，用webpack

**Comment by unclay** [comment]
用webpack的话可以直接参考文档
https://doc.vux.li/zh-CN/install/npm.html
