### ISSUE TITLE
[Bug Report] fastclick与x-textarea等input元素冲突

### ISSUE THREAD

**Issue by NinjaJin** [airyland/vux#2806]
### VUX version
2.3.4

### OS/Browsers version
webapp

### Vue version
2.5.17-beta.0

### Code

```html
<x-textarea v-model="reason" placeholder="具体原因" :height="100" :max="100" :show-counter="false"></x-textarea>
```

### Steps to reproduce
移动端在有fastclick的情况下，操作input框需要按差不多1秒才能focus，轻触不响应。不要fastclick正常但是会有延迟。怎样能兼顾。谢谢~

### What is Expected?
移动端在有fastclick的情况下，操作input框需要按差不多1秒才能focus，轻触不响应。不要fastclick正常但是会有延迟。怎样能兼顾。谢谢~

### What is actually happening?
移动端在有fastclick的情况下，操作input框需要按差不多1秒才能focus，轻触不响应。不要fastclick正常但是会有延迟。怎样能兼顾。谢谢~

**Comment by NinjaJin** [comment]
vux升级到2.9.1好像已经没有出现了

**Comment by huanmo222** [comment]
我用的2.8.0版本, 也有这个问题, 要点2次才能获得焦点, 后面就把fastclick禁用了. 最新的版本还没有用过, 不知道好了没

**Comment by caozhong1996** [comment]
应该删除fastclick这个插件，有很多的坑，不要使用
