### ISSUE TITLE
在tab-item等需要点击的组件中，推荐使用vue-touch插件

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#281]
目前tab-item的代码如下：
### Your Codes 

``` html
<div class="vux-tab-item" :class="[selected ? activeClass : '', {'vux-tab-selected': selected}]" :style="style" @click="onItemClick">
    <slot></slot>
</div>
```
可以看到是在监听元素的click事件，这就牵扯到了移动设备上300ms的问题。vue-touch插件完整封装了hammer.js,能够有效处理tap事件，同时增加了各种swiper手势，我觉得可以在需要点击操作的时候引入vue-touch，优化体验。

**Comment by airyland** [comment]
已经使用了fastclick，还会有延迟？

**Comment by dangyuluo** [comment]
额，是的。感觉点击有点迟钝。回头我做个页面测试一下。

**Comment by dangyuluo** [comment]
![1466179970](https://cloud.githubusercontent.com/assets/4816327/16157090/b7afef2a-34e9-11e6-9cc1-20c449fc3002.png)
你可以用微信扫这个二维码看一下，可能会要求授权信息。如果打不开的话请刷新两次就好。

**Comment by airyland** [comment]
fastclick需要在main.js中手动引入。

https://github.com/airyland/vux/blob/master/src/main.js#L82

**Comment by dangyuluo** [comment]
哦哦有着么一说，没有注意到。我去研究一下。
