### ISSUE TITLE
[Bug Report] x-input用mask格式化后从中间修改数据光标会跳到右边

### ISSUE THREAD

**Issue by huanmo222** [airyland/vux#2810]
### VUX version
2.8.0

### OS/Browsers version
chrome

### Vue version
2.5.2

### Code

```html
        <x-input 
          title="购票卡号" 
          required
          :is-type="judgeCreditCardNo" 
          v-if="isHandFill"
          :show-clear="false" 
          placeholder="本人刷卡购票卡号" 
          :max=19  
          mask="9999 9999 9999 9999"
          v-model="FdTCase.creditCardNo"
        >
        </x-input>
```

### Steps to reproduce
x-input用mask格式化后从中间修改数据光标会跳到右边
原始数据1234 5678:
    1. 当在1-8之间的任何地方再输入一个数字, 光标就会跳到最右边.
    2. 当光标定位到4后面, 删除4, 也会跳到最右边.

### What is Expected?
在中间修改数据时, 光标可以定位到当前的位置.

### What is actually happening?
在中间修改数据时, 光标会跳动到最右侧.

**Comment by unclay** [comment]
下版本更新

**Comment by chenyimin1314** [comment]
我遇到一个问题 就是 x-input v-model值 ios可以拿到 安卓就获取不到 什么原因呢

**Comment by kevinchung1026** [comment]
> 我遇到一个问题 就是 x-input v-model值 ios可以拿到 安卓就获取不到 什么原因呢

我今天也遇到这个问题

**Comment by pp344** [comment]
> 我遇到一个问题 就是 x-input v-model值 ios可以拿到 安卓就获取不到 什么原因呢

今天也遇到了，只好退版本2.9.0。是number类型在安卓微信上就会出现这个问题

**Comment by hzc315579049** [comment]
这个问题修复了..但是这个修复带来了另外一个问题: value变了之后..会因为碰了selection而自动触发input的focus事件。某些场景下很难受..

**Comment by wangatong** [comment]
2.9.2版本怎么还会出现光标问题

**Comment by letear** [comment]
最新版本2.9.4修复这个问题了吗
