### ISSUE TITLE
[Bug Report] 不能打断点调试

### ISSUE THREAD

**Issue by tangyuhui** [airyland/vux#2813]
### VUX version
2.9.1

### OS/Browsers version
win10

### Vue version
2.5.16

### Code

```html
无
```

### Steps to reproduce
按照vux的步骤，搭建一个新项目，将devtool改为source-map, 打开控制台，代码没有格式化，好似还被压缩过一般，不能打断点，另外，html部分也被抽走了。

### What is Expected?
期待跟vue-cli webpack新建的项目一样，能够打断点调试

### What is actually happening?
不能调试，且代码被压缩过，没有格式化显示

**Comment by looyo** [comment]
这两天我也遇到不能打断点的问题。 我是用vscode +debugger for chrome 。尝试了很多办法，还是不能。

我的问题记录在这边 
https://segmentfault.com/q/1010000016409752
