### ISSUE TITLE
vuex popup 再iphone6 input 会出现错误的情况！！！！！！！！！！！！

### ISSUE THREAD

**Issue by yehoan** [airyland/vux#2814]

**Comment by airyland** [comment]
1. 如果你希望得到帮助，管理好你的情绪
2. 如果你希望得到帮助，请尊重 issue template
3. 如果你希望得到帮助，请写对 vux，最好写对 iPhone
4. 如果你希望得到帮助，请说明清楚
5. 浪费时间，fuck you.
