### ISSUE TITLE
npm install vux@0.1.1-rc3

### ISSUE THREAD

**Issue by dancingalone** [airyland/vux#282]
npm 安装 vux rc3的版本 安装完成后

michael@Michaels-MacBook-Pro:~/Workspaces/commercial/join_us/joinus_portal$ npm install vux@0.1.1-rc3
vue-hackernews@1.0.0 /Users/michael/Workspaces/commercial/join_us/joinus_portal
+-- babel-runtime@6.9.2  extraneous
+-- file-loader@0.8.5  extraneous
+-- vue-validator@2.1.1  extraneous
+-- vuex@0.6.3  extraneous
`-- vux@0.1.1-rc3  invalid

运行 npm run dev 提示无法找到相关的component

**Comment by airyland** [comment]
确认node_modules里面有没有vux。上面也并没有npm run dev的找不到component的报错信息，请补充，谢谢。

**Comment by transtone** [comment]
好久没更新了，一直是 rc3 ，一些新的bug修复用不上

**Comment by dancingalone** [comment]
@airyland node_modles 里面有 vux 文件夹，文件夹下也有文件。

启动后的报错信息如下：

Module not found: Error: Cannot resolve module 'vux/components/tabbar' in /Users/michael/Workspaces/commercial/join_us/joinus_portal/src/components
resolve module vux/components/tabbar in /Users/michael/Workspaces/commercial/join_us/joinus_portal/src/components
  looking for modules in /Users/michael/Workspaces/commercial/join_us/joinus_portal/node_modules
    resolve 'file' or 'directory' components/tabbar in /Users/michael/Workspaces/commercial/join_us/joinus_portal/node_modules/vux
      resolve file
        /Users/michael/Workspaces/commercial/join_us/joinus_portal/node_modules/vux/components/tabbar doesn't exist
        /Users/michael/Workspaces/commercial/join_us/joinus_portal/node_modules/vux/components/tabbar.webpack.js doesn't exist
        /Users/michael/Workspaces/commercial/join_us/joinus_portal/node_modules/vux/components/tabbar.web.js doesn't exist
        /Users/michael/Workspaces/commercial/join_us/joinus_portal/node_modules/vux/components/tabbar.js doesn't exist
        /Users/michael/Workspaces/commercial/join_us/joinus_portal/node_modules/vux/components/tabbar.json doesn't exist
      resolve directory
        /Users/michael/Workspaces/commercial/join_us/joinus_portal/node_modules/vux/components/tabbar doesn't exist (directory default file)
        /Users/michael/Workspaces/commercial/join_us/joinus_portal/node_modules/vux/components/tabbar/package.json doesn't exist (directory description file)




经过检查，发现在 node_modules 下面的vux 目录下面没有 components 目录，这个目录在dist 目录下面，所以在 webpack 的配置文件中用 
 resolve: {
        alias: {
            'vux/components': 'vux/dist/components/'
        }
    }



再次运行，提示

vue.common.js:1019[Vue warn]: Unknown custom element: <tabbar> - did you mean <tabbar>? HTML is case-insensitive, remember to use kebab-case in templates

**Comment by airyland** [comment]
从0.1.0开始，文件都位于dist目录下。

**Comment by airyland** [comment]
直接把import的组件console出来，如果是空，说明配置的alias可能有问题，不要用vux/components用vux-components呢。

**Comment by lichunqiang** [comment]
看文档，如果有问题再议：https://vuxjs.gitbooks.io/vux/content/install/vue.html
