### ISSUE TITLE
页面A>页面B，返回A页面时页面回到顶部，并未停留在上次浏览的位置

### ISSUE THREAD

**Issue by timBen9527** [airyland/vux#2827]
页面A>页面B，返回A页面时页面回到顶部，并未停留在上次浏览的位置

**Comment by airyland** [comment]
这个非组件控制，需要自行实现，或者参考 vue-router 的 scroll behavior https://router.vuejs.org/guide/advanced/scroll-behavior.html#async-scrolling

**Comment by Sapphire2k** [comment]
嵌套路由也很好用~
https://router.vuejs.org/zh/guide/essentials/nested-routes.html

**Comment by timBen9527** [comment]
@airyland 按照这种方法试过，无法使用，布局使用的是viewbox，能举个例子吗？
