### ISSUE TITLE
建议增加转场动画效果

### ISSUE THREAD

**Issue by wulucxy** [airyland/vux#283]
### Version
0.1 

### Your Codes 

``` html
<!--put your code here-->
```

### Expected behavior and actual behavior.
vux非常棒，组内同事反馈已经和native相差无几。不过在目前vux不提供转场动画效果，这点方面和native还是有一定差距，建议下个版本考虑增加进来

**Comment by wulucxy** [comment]
@airyland 大大有这个计划么

**Comment by wulucxy** [comment]
@airyland 是的，就是遇到了transform和fixed元素的天坑，想看看你们怎么解决

**Comment by airyland** [comment]
哈哈 有成果可pr 其实后面考虑用淡入淡出的效果替代，类似于京东金融加载的效果，不过新版本看不到了

**Comment by LiangFuzhi** [comment]
说的是类似app的页面转场动画么？我实现了。

**Comment by airyland** [comment]
@LiangFuzhi 给个demo看看

**Comment by LiangFuzhi** [comment]
`<template>
  <div>
    <router-view :transition="transitionName" keep-alive></router-view>
  </div>
</template>

<script>
export default {
  name: "app",
  attached() {
    this.$router.beforeEach((transition)=> {
      if (transition.to.path === '/forbidden') {
        transition.abort()
      } else {
        if(window.afterEnter){
          if(this.record)
          // if(!transition.from.level||transition.to.level>transition.from.level||transition.to.path=="/login"){
          if(!this.contains(transition.to.path,transition.from.path)){
            this.transitionName="popIn"
          }else {
            this.transitionName="popOut"
          }
          setTimeout(()=> {
            transition.next()
          }, 0)
        }
      }
    })
  },
  data() {
	   return {
       transitionName: 'popIn',
       record:[]
     }
  },
  methods: {
    contains(to_path,form_path){
      if(this.array_remove(to_path)){
        this.array_remove(form_path,true)
        return true
      }
      this.record.push(to_path)
      return false;
    },
    array_remove(val,remove){
      if(this.record.length!=1){
        for (var i = 0; i < this.record.length; i++) {
            if (this.record[i] == val) {
              if(remove){
                this.record.splice(i,1);
              }
              return true
            }
        }
      }
      return false;
    }
  }
}
</script>

<style>
/*app页面切换动画*/
.popOut-transition, .popIn-transition {
  -webkit-animation-duration: 0.3s;
          animation-duration: 0.3s;
  -webkit-animation-fill-mode: both;
          animation-fill-mode: both;
}

.popOut-enter,
.popOut-leave,
.popIn-enter,
.popIn-leave {
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
}

.popOut-enter {
	z-index: -1;
	-webkit-animation-name: popInLeft;
          animation-name: popInLeft;
}
.popOut-leave {
	-webkit-animation-name: popOutRight;
          animation-name: popOutRight;
}

.popIn-enter {
	-webkit-animation-name: popInRight;
          animation-name: popInRight;
}
.popIn-leave {
	-webkit-animation-name: popOutLeft;
          animation-name: popOutLeft;
}
@-webkit-keyframes popInLeft {
  from {
    -webkit-transform: translate3d(-50%, 0, 0);
            transform: translate3d(-50%, 0, 0);
    visibility: visible;
		-webkit-filter: brightness(0.9);
	  filter: brightness(0.9);
  }
  to {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
						-webkit-filter: brightness(1);
					  filter: brightness(1);
  }
}
@keyframes popInLeft {
  from {
    -webkit-transform: translate3d(-50%, 0, 0);
            transform: translate3d(-50%, 0, 0);
    visibility: visible;
		-webkit-filter: brightness(0.9);
	  filter: brightness(0.9);
  }
  to {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
						-webkit-filter: brightness(1);
					  filter: brightness(1);
  }
}
@-webkit-keyframes popOutLeft {
  from {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
		-webkit-filter: brightness(1);
		filter: brightness(1);
  }
  to {
    visibility: hidden;
    -webkit-transform: translate3d(-50%, 0, 0);
            transform: translate3d(-50%, 0, 0);
		-webkit-filter: brightness(0.9);
		filter: brightness(0.9);
  }
}
@keyframes popOutLeft {
  from {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
		-webkit-filter: brightness(1);
	  filter: brightness(1);
  }
  to {
    visibility: hidden;
    -webkit-transform: translate3d(-50%, 0, 0);
            transform: translate3d(-50%, 0, 0);
		-webkit-filter: brightness(0.9);
		filter: brightness(0.9);
  }
}

@-webkit-keyframes popInRight {
  from {
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
    visibility: visible;
  }
  to {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
  }
}
@keyframes popInRight {
  from {
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
    visibility: visible;
  }
  to {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
  }
}
@-webkit-keyframes popOutRight {
  from {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
  }
  to {
    visibility: hidden;
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
  }
}
@keyframes popOutRight {
  from {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
  }
  to {
    visibility: hidden;
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
  }
}

</style>
`

**Comment by LiangFuzhi** [comment]
`<template>
  <div>
    <router-view :transition="transitionName" keep-alive></router-view>
  </div>
</template>

<script>
export default {
  name: "app",
  attached() {
    this.$router.beforeEach((transition)=> {
      if (transition.to.path === '/forbidden') {
        transition.abort()
      } else {
        // if(window.afterEnter){
          // if(!transition.from.level||transition.to.level>transition.from.level||transition.to.path=="/login"){
          if(!this.contains(transition.to.path,transition.from.path)){
            this.transitionName="popIn"
          }else {
            this.transitionName="popOut"
          }
          setTimeout(()=> {
            transition.next()
          }, 0)
        }
      // }
    })
  },
  data() {
	   return {
       transitionName: 'popIn',
       record:[]
     }
  },
  methods: {
    contains(to_path,form_path){
      if(this.array_remove(to_path)){
        this.array_remove(form_path,true)
        return true
      }
      this.record.push(to_path)
      return false;
    },
    array_remove(val,remove){
      if(this.record.length!=1){
        for (var i = 0; i < this.record.length; i++) {
            if (this.record[i] == val) {
              if(remove){
                this.record.splice(i,1);
              }
              return true
            }
        }
      }
      return false;
    }
  }
}
</script>

<style>
</style>
`

**Comment by LiangFuzhi** [comment]
/*app页面切换动画*/
.popOut-transition, .popIn-transition {
  -webkit-animation-duration: 0.3s;
          animation-duration: 0.3s;
  -webkit-animation-fill-mode: both;
          animation-fill-mode: both;
}

.popOut-enter,
.popOut-leave,
.popIn-enter,
.popIn-leave {
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
}

.popOut-enter {
	z-index: -1;
	-webkit-animation-name: popInLeft;
          animation-name: popInLeft;
}
.popOut-leave {
	-webkit-animation-name: popOutRight;
          animation-name: popOutRight;
}

.popIn-enter {
	-webkit-animation-name: popInRight;
          animation-name: popInRight;
}
.popIn-leave {
	-webkit-animation-name: popOutLeft;
          animation-name: popOutLeft;
}
@-webkit-keyframes popInLeft {
  from {
    -webkit-transform: translate3d(-50%, 0, 0);
            transform: translate3d(-50%, 0, 0);
    visibility: visible;
		-webkit-filter: brightness(0.9);
	  filter: brightness(0.9);
  }
  to {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
						-webkit-filter: brightness(1);
					  filter: brightness(1);
  }
}
@keyframes popInLeft {
  from {
    -webkit-transform: translate3d(-50%, 0, 0);
            transform: translate3d(-50%, 0, 0);
    visibility: visible;
		-webkit-filter: brightness(0.9);
	  filter: brightness(0.9);
  }
  to {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
						-webkit-filter: brightness(1);
					  filter: brightness(1);
  }
}
@-webkit-keyframes popOutLeft {
  from {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
		-webkit-filter: brightness(1);
		filter: brightness(1);
  }
  to {
    visibility: hidden;
    -webkit-transform: translate3d(-50%, 0, 0);
            transform: translate3d(-50%, 0, 0);
		-webkit-filter: brightness(0.9);
		filter: brightness(0.9);
  }
}
@keyframes popOutLeft {
  from {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
		-webkit-filter: brightness(1);
	  filter: brightness(1);
  }
  to {
    visibility: hidden;
    -webkit-transform: translate3d(-50%, 0, 0);
            transform: translate3d(-50%, 0, 0);
		-webkit-filter: brightness(0.9);
		filter: brightness(0.9);
  }
}

@-webkit-keyframes popInRight {
  from {
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
    visibility: visible;
  }
  to {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
  }
}
@keyframes popInRight {
  from {
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
    visibility: visible;
  }
  to {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
  }
}
@-webkit-keyframes popOutRight {
  from {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
  }
  to {
    visibility: hidden;
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
  }
}
@keyframes popOutRight {
  from {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
  }
  to {
    visibility: hidden;
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
  }
}

**Comment by airyland** [comment]
@LiangFuzhi 看代码你是还判断了前进后退吗？

**Comment by LiangFuzhi** [comment]
是的，还记录了浏览记录

**Comment by LiangFuzhi** [comment]
我用vue+vue-router+hbuilder的mui实现了单页面app

**Comment by airyland** [comment]
@LiangFuzhi 可以发出来学习学习么 :smile:

**Comment by LiangFuzhi** [comment]
链接: http://pan.baidu.com/s/1kUAANUB 密码: m3v5

**Comment by LiangFuzhi** [comment]
还有一些坑，还在改
