### ISSUE TITLE
[Bug Report] 请问如何设置v-chart 的canvas的宽高

### ISSUE THREAD

**Issue by KoreSamuel** [airyland/vux#2831]
### VUX version
2.9.1

### OS/Browsers version
mac 10.13.4/ chrome 66

### Vue version
2.5.17-beta.0

### Code

```html
无
```

### Steps to reproduce
无

### What is Expected?
期望能够设置canvas宽高

### What is actually happening?
无

**Comment by KoreSamuel** [comment]
查看源码可以设置width，不过直接处理成px了

**Comment by Jeffrey1029** [comment]
在手机端直接处理成px难道没有问题吗？

**Comment by maotingting** [comment]
同问，我强制写了个函数改变宽高，虽然起作用，但是一直报错，说没有width和height这两个属性
