### ISSUE TITLE
group,cell组件建议

### ISSUE THREAD

**Issue by heiyun** [airyland/vux#2847]
希望增加属性可以去掉默认的上下分割线,多数情况ui图是没有这些线的,css样式覆盖很不方便

**Comment by wg5945** [comment]
vux样式基于weui，微信的风格就是如此，实际上大多数ui是有分割线的，如果不需要的话，可以自行设置全局样式进行覆盖

**Comment by lutop** [comment]
组件样式配置不够灵活，不少地方需要样式覆盖，不是很方便
