### ISSUE TITLE
如何路由注册目录存放?

### ISSUE THREAD

**Issue by zsping1989** [airyland/vux#2849]
如何组件可依据目录分类存放?
![default](https://user-images.githubusercontent.com/11209094/41197591-bdab4294-6c96-11e8-975b-db09fc6f2266.png)

**Comment by zsping1989** [comment]
我这个路径有问题么???
![default](https://user-images.githubusercontent.com/11209094/41197772-658aa5d2-6c9b-11e8-93df-e731575143bd.png)

**Comment by cryingbat** [comment]
看你这截图，明显不是路径的问题，而是loader的问题啊，检查一下你的loader配置对了没。

**Comment by airyland** [comment]
不建议使用 vux 项目来作为你的项目模板，因为你看到的路由列表是有特定规则的，你需要手动修改 vux-loader 的根据路由 json 列表生成正确 router 路由的逻辑。https://github.com/airyland/vux/blob/v2/build/vux-config.js
