### ISSUE TITLE
[Bug Report] 使用 

### ISSUE THREAD

**Issue by lvjh** [airyland/vux#2865]
### VUX version
2.9.2

### OS/Browsers version
android

### Vue version
2.5.17-beta.0

### Code

```html
cordova run android

在手机上面显示的微信字体图标（比如：weui-tabbar__icon vux-center）是个x 的图标：

```

### Steps to reproduce
cordova run android

### What is Expected?
可以正常显示图标内容

### What is actually happening?
显示x图标

**Comment by Dragana1090** [comment]
Ich

**Comment by lvjh** [comment]
您好， 感谢您的回答，可以具体点吗？
