### ISSUE TITLE
[Bug Report] 使用vux-loader之后所有vue组件script标签内的代码都会执行两次

### ISSUE THREAD

**Issue by ghost** [airyland/vux#2868]
### VUX version
2.9.2

### OS/Browsers version
MacOS Chrome

### Vue version
2.5.16

### Code

```html
<template>
  <div id="app">
    hello world
  </div>
</template>

<script>
console.log('重复执行测试')
export default {
  name: 'App'
}
</script>

```

### Steps to reproduce
1. 通过vue-cli的webpack模版初始化一个空项目
2. 在App.vue的<script>标签内添加console.log('重复执行测试')
3. npm run dev将项目跑起来，在浏览器控制台查看，只打印了一行“重复执行测试”
4. 安装vux和vux-loader,按照文档配置webpack,https://doc.vux.li/zh-CN/vux-loader/install.html
5. 重新执行npm run dev将项目跑起来，在浏览器控制台查看，会打印两次“重复执行测试”

### What is Expected?
vue组件script标签内的代码只会执行一次

### What is actually happening?
vue组件script标签内的代码执行了二次

![image](https://user-images.githubusercontent.com/28668354/41633484-c44a4572-7471-11e8-8fb8-198d2c6bd3f0.png)

**Comment by weimingming** [comment]
我也遇到的同样的问题，求答案

**Comment by ghost** [comment]
@weimingming @airyland 我在vux-loader仓库也提了这个问题，求解答

**Comment by GzhiYi** [comment]
The same.

**Comment by Eurkidu** [comment]
`vux-loader` 的问题, 自己项目里面临时修改了下 `vux-loader` 的源代码解决了, 还是希望作者能修复下

具体见https://github.com/airyland/vux-loader/issues/65#issuecomment-438939326
