### ISSUE TITLE
Rater能支持半格吗？

### ISSUE THREAD

**Issue by shakerjim** [airyland/vux#2871]

**Comment by Sapphire2k** [comment]
`Rater`支持小数，你可以自定义要显示的值再传入显示即可。

**Comment by wansj** [comment]
看了源码后尝试了一下，确实能显示半格，但必须修改currentValue属性，而且必须在Rater创建以后再修改，太不友好了，给value传的值在被赋值给currentValue之前被parseInt处理了，既然打算支持半格显示，为什么不parseFloat呢？

**Comment by DaDiaoShuai** [comment]
> 看了源码后尝试了一下，确实能显示半格，但必须修改currentValue属性，而且必须在Rater创建以后再修改，太不友好了，给value传的值在被赋值给currentValue之前被parseInt处理了，既然打算支持半格显示，为什么不parseFloat呢？

+1 确实有这个问题 这一块跟之前比就是在value的值类型灵活了啊
