### ISSUE TITLE
[Bug Report] XAddress 组件处于 Popup 组件里面弹出时会导致没有黑色遮罩

### ISSUE THREAD

**Issue by gbldsz** [airyland/vux#2878]
### VUX version
2.9.0

### OS/Browsers version
win10/chrome66

### Vue version
2.5.17-beta.0

### Code

```html
<popup v-model="edit" height="100%">
            <div class="popup1">
                <group label-width="4.5em" label-margin-right="2em" label-align="right">
                    <x-address title="居住地" v-model="address" raw-value :list="addressData" value-text-align="right" label-align="justify"></x-address>
                </group>
            </div>
        </popup>
```

### Steps to reproduce
弹出popup之后，点击选择xAddress，

### What is Expected?
希望在popup里面的xAddress弹出有遮罩

因为 popup和xAddress使用的同一个遮罩class:vux-popup-mask vux-popup-show
然后因为层级关系导致遮罩在popup之下

### What is actually happening?
popup里面的xAddress弹出，会没有遮罩，

**Comment by ianho7** [comment]
你好，请问这个问题您解决了吗？

**Comment by gbldsz** [comment]
> 你好，请问这个问题您解决了吗？

没有，把xAddress提出来了。不放在popup里面

**Comment by ianho7** [comment]
> > 你好，请问这个问题您解决了吗？
> 
> 没有，把xAddress提出来了。不放在popup里面

好的谢谢
