### ISSUE TITLE
在手机上打开非常小，就像打开电脑的网站

### ISSUE THREAD

**Issue by lingeng** [airyland/vux#288]
### Android Chrome and Wechat browser(on Nexus 6p)

![image](https://cloud.githubusercontent.com/assets/1768488/16290688/18eb1908-3932-11e6-88a8-2148f07737aa.png)

手机上查看情况如图，请问是配置有问题还是？

**Comment by airyland** [comment]
手机页面开发第一点是设置viewport

``` html
<meta name=viewport content="width=device-width,initial-scale=1,user-scalable=0">
```

**Comment by lingeng** [comment]
谢谢！问题解决
