### ISSUE TITLE
[Bug Report] 打包后文件太大了，只引一个popup-picker，就600多KB了

### ISSUE THREAD

**Issue by longjxchina** [airyland/vux#2882]
### VUX version
2.9.2

### OS/Browsers version
WIN10

### Vue version
2.5.2

### Code

```html
import { PopupPicker } from "vux";
```

### Steps to reproduce
import { PopupPicker } from "vux";

### What is Expected?
文件小

### What is actually happening?
打包后大小：634kb

**Comment by unclay** [comment]
参考这个 https://doc.vux.li/zh-CN/faq/vux-build-issue.html

**Comment by longjxchina** [comment]
移除了sourcemap还有200多了
