### ISSUE TITLE
tab-bar 使用:link切换页面出现没有存留浏览的位置

### ISSUE THREAD

**Issue by timBen9527** [airyland/vux#2884]
![image](https://user-images.githubusercontent.com/38236663/41828834-11b6000c-786a-11e8-97cb-3c8c4627772e.png)

切换到消息的时候，没有保留首页的浏览位置。

**Comment by timBen9527** [comment]
使用了keepAlive，跳转详情是是正常的，但使用tab切换页面就不行。

**Comment by timBen9527** [comment]
![image](https://user-images.githubusercontent.com/38236663/41829007-e82b08c6-786a-11e8-9e40-7fe716784281.png)

**Comment by airyland** [comment]
tabbar 没有任何相关处理也无法处理跳转时的浏览位置，跳转也是直接使用的 vue-router 的 push 方法。

你直接写个 router-link 或者直接用 $router.push 来跳转效果应该是一样的，位置需要自行处理。
