### ISSUE TITLE
[Bug Report] 在vue-cli 3.0 中该如何引入vux 进行配置？

### ISSUE THREAD

**Issue by xiaojingyuaner** [airyland/vux#2885]
### VUX version
2.9.2

### OS/Browsers version
mac

### Vue version
2.5.17-beta.0

### Code

```html
在vue-cli 3.0 中该如何引入vux 进行配置？
```

### Steps to reproduce
在vue-cli 3.0 中该如何引入vux 进行配置？

### What is Expected?
在vue-cli 3.0 中该如何引入vux 进行配置？

### What is actually happening?
在vue-cli 3.0 中该如何引入vux 进行配置？

**Comment by KnorienChang** [comment]
https://segmentfault.com/a/1190000014586699
