### ISSUE TITLE
建议新增 checklist 样式

### ISSUE THREAD

**Issue by transtone** [airyland/vux#289]
checker里面的上拉选择(花鸟鱼虫那个)样式挺漂亮的，可惜只能单选，可以做成多选加到 checklist 的样式里面吗？

**Comment by airyland** [comment]
checker里中有计划增加多选的。
“做成多选加到 checklist 的样式”这句不理解

**Comment by transtone** [comment]
不好意思，我个人理解：checker是单选的demo，checklist是多选的demo。做成多选之后自然要加一个demo到checklist里啦。

**Comment by wulucxy** [comment]
支持checker增加多选功能，+1

**Comment by wulucxy** [comment]
@airyland 太棒了，一早起来就发现有issue被解决了，+10086个赞
