### ISSUE TITLE
[Bug Report]fastclick bug

### ISSUE THREAD

**Issue by 107295472** [airyland/vux#2897]
VUX version
2.9.2

OS/Browsers version
win 2016

Vue version
2.5.17-beta.0

Code
<x-button @click.native="submitForm" type="primary">注册</x-button>

    submitForm: function() {
      if (this.$refs.captcha.valid) {
        AlertModule.show({
          content: "成功"
        });
      }
    }
![20180702115735](https://user-images.githubusercontent.com/6436116/42146180-c968d34e-7df8-11e8-9346-8e41631d95bf.png)

**Comment by shaomingming008** [comment]
修复了吗
