### ISSUE TITLE
Datetime组件如何禁选当天之前的日期？

### ISSUE THREAD

**Issue by syy1992** [airyland/vux#2900]
Datetime组件如何禁选当天之前的日期？

**Comment by Sapphire2k** [comment]
👉 [参考Datetime-文档](https://doc.vux.li/zh-CN/components/datetime.html)

可以用`start-date`来限制起始日期~

**Comment by yt5213969** [comment]
start-date 我按照格式写的 会报错 @syy1992  你有这个问题吗
