### ISSUE TITLE
2.9.2 x-input 绑定不到值，安卓微信环境有问题，IOS和谷歌浏览器都没有问题

### ISSUE THREAD

**Issue by wangnian94** [airyland/vux#2903]
2.9.2 x-input 绑定不到值，安卓微信环境有问题，IOS和谷歌浏览器都没有问题

**Comment by kiddkyd2** [comment]
我也发现了。只要是type=number，就不行。删掉type，或者用tel就可以。
PC可以，安卓不行。ios没试。

我的demo是
`<x-input title="联系电话" type="number" required :is-type="isMobile" v-model="form.userMobile"></x-input>`

**Comment by ghost** [comment]
在锤子手机上也发现了这个问题， 去掉type="number"就可以了

**Comment by LNyears** [comment]
最近升级，我也遇到了只要加了type=number，不管data初始值为null或空窜都不行动态绑不上值。删掉type，或data初始值置为number类型就可以。
版本2.9.2。
