### ISSUE TITLE
x-header 在 Safari 下右边总是缺几个像素

### ISSUE THREAD

**Issue by soffchen** [airyland/vux#291]
Chrome 下似乎没事

详见截图

![截图](http://c.ip.cn/pb-FJYFGmCuKo.png)

**Comment by airyland** [comment]
咦？

**Comment by soffchen** [comment]
我搞错了，sorry

**Comment by soffchen** [comment]
因为你的 demo 写了     body {padding-right:5px;}  没注意，哈哈。
