### ISSUE TITLE
怎么全局安装vux2模板

### ISSUE THREAD

**Issue by kiddkyd2** [airyland/vux#2920]
安装官网教程
`npm install vue-cli -g # 如果还没安装
vue init airyland/vux2 projectPath

cd projectPath
npm install --registry=https://registry.npm.taobao.org # 或者 cnpm install 或者  yarn
npm run dev #  或者  yarn dev`

其中倒数第二行，我想全局安装这些东西，不想每个项目都down一堆库，所以在后面加了一个-g，

结果运行后提示错误

`npm WARN F:\work\myproject\app\myproject\node_modules\vux is not a child of C:\Users\Administrator\AppData\Roaming\npm
npm ERR! path F:\work\myproject\app\myproject\node_modules\vux
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'F:\work\myproject\app\myproject\node_modules\vux' -> 'F:\work\myproject\app\myproject\node_modules\.vux.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
`

为何呢。。。？

**Comment by airyland** [comment]
npm 使用方法请查看文档。
