### ISSUE TITLE
[Bug Report] previewer组件的关闭该怎样实现

### ISSUE THREAD

**Issue by Neror1** [airyland/vux#2926]
### VUX version
2.9.2

### OS/Browsers version
ios、Andriod/wechat browser

### Vue version
2.5.2

### Code

```html
previewer组件
```

### Steps to reproduce
当点开previewer组件后点击安卓的物理返回键或者ios中微信扫码后微信的浏览器下方的返回键，直接转到上一级路由

### What is Expected?
想要点击返回时关闭previewer组件

### What is actually happening?
直接跳至上一级路由

**Comment by Sapphire2k** [comment]
通过配置`Previewer-opitons-history`，可以实现返回关闭组件，无需做其他处理，代码如下👇：
```
<previewer
  :options="{
    history: true,
    ...
  }"></previewer>
```

**Comment by Neror1** [comment]
@Sapphire2k 解决了，多谢大佬

**Comment by gdmec07140512** [comment]
popup组件也存在这样的问题，有解决方案吗？

**Comment by caozhong1996** [comment]
鉴于时间过去太久，我将关闭这个issue，还需要帮助的话请重开issue，谢谢!
