### ISSUE TITLE
[Bug Report] 关于input框赋值后，自动滚动到最后一个赋值的Input的问题

### ISSUE THREAD

**Issue by hongtongtong** [airyland/vux#2928]
### VUX version
2.9.2

### OS/Browsers version
IOS 10

### Vue version
2.5.17-beta.0

### Code

```html
通过watch获取值，计算后赋值于另外的input框
```

### Steps to reproduce
通过watch获取值，计算后赋值于另外的input框

### What is Expected?
被赋值的输入框，值自动改变，而屏幕不自动滚动到最后赋值的input框

### What is actually happening?
被赋值的输入框，值自动改变，但屏幕总是会跳到那个被赋值的input框，这样就造成假如赋值是第一个字段，里面就会跳到那个被赋值的字段

**Comment by jane-** [comment]
我也遇到这个问题， 设置的步长为6  input 输入比6小的值，会变成6  但是我要输入11 。  我第一次输入1的时候，它就变成6了， 输入第二个数字变成 61 ， 我觉得这个应该是监听了keyup时间， 应该换一个
