### ISSUE TITLE
[Bug Report] x-input组件在锤子手机浏览器和微信中获取不到值

### ISSUE THREAD

**Issue by ghost** [airyland/vux#2930]
### VUX version
2.9.2

### OS/Browsers version
手机型号为锤子SM919 安卓版本为6.0.1

### Vue version
2.5.2

### Code

```html
<x-input title="产次" v-model.trim="CC" placeholder="请填写产次" text-align="right" type="number"></x-input>
```

### Steps to reproduce
无

### What is Expected?
获取正确的值

### What is actually happening?
获取的值为空

**Comment by jeremy16601** [comment]
解决了吗
