### ISSUE TITLE
[Feature Request] 希望增加文档说明

### ISSUE THREAD

**Issue by DrugsZ** [airyland/vux#2933]
### Existing Component
是

### Component Name
check-icon

### Description
我在使用`check-icon`组件时,有需求需要修改选中状态下的颜色,在文档中并未体现配置颜色,于是我在源码中寻找,看到选中显示使用的是icon组件,于是通过icon组件的样式配置中将`@icon-success-color`配置为我需要的颜色,但是并未起效,于是我通过开发者工具中的样式在源码中搜索,最后在check-icon的源码中找到,修改选中状态下颜色的样式变量为`@check-icon-color-checked`,但是在文档中并未体现,所以希望在文档中能够更新一下,同时对各位维护者的贡献表示感谢与敬意!

**Comment by caozhong1996** [comment]
鉴于时间过去太久，我将关闭这个issue，还需要帮助的话请重开issue，如果你已经知道如何解决也请提交对应的pr，谢谢!
