### ISSUE TITLE
在原有elementUI项目中，添加Vux，报错：Module parse failed: Unexpected token (3:0) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by ghost** [airyland/vux#2935]
在现有element-ui 项目中 引用 vux，按照教程，修改了webpack.base.conf.js 加上了vux-loader;然后添加了less less-loader，运行报错！
错误：
` error  in ./src/pages/pc/doct_award_master/add.vue

Module parse failed: Unexpected token (3:0)
You may need an appropriate loader to handle this file type.
| import { render, staticRenderFns } from "./add.vue?vue&type=template&id=11deac61"
| import script from "./add.vue?vue&type=script&lang=js"
> ../../../../node_modules/vux-loader/src/script-loader.js!export * from "./add.vue?vue&type=script&lang=js"
| 
| 

 @ ./src/router/index.js 267:15-58
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js

 error  in ./src/pages/pc/doct_award_dict/add.vue

Module parse failed: Unexpected token (3:0)
You may need an appropriate loader to handle this file type.
| import { render, staticRenderFns } from "./add.vue?vue&type=template&id=12b1da35"
| import script from "./add.vue?vue&type=script&lang=js"
> ../../../../node_modules/vux-loader/src/script-loader.js!export * from "./add.vue?vue&type=script&lang=js"
| 
| 

 @ ./src/router/index.js 217:15-56
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js`

代码文件：

`<template>
  <el-form :model="addForm" :rules="rules" ref="addForm" label-width="130px" v-loading="loading" size="mini">
    <el-form-item label="考试标题" prop="examTitle">
      <el-col :span="5">
        <el-input v-model="addForm.examTitle"></el-input>
      </el-col>
    </el-form-item>
    <el-form-item label="考试总人数" prop="examPersonCount">
      <el-col :span="5">
        <el-input v-model="addForm.examPersonCount"></el-input>
      </el-col>
    </el-form-item>
    <el-form-item label="考试时长(分钟计)" prop="examTime">
      <el-col :span="5">
        <el-input v-model="addForm.examTime"></el-input>
      </el-col>
    </el-form-item>
    
    <el-form-item>
      <el-button type="primary" @click="submitForm('addForm')">保存</el-button>
      
      <el-button @click="$router.back()">返回</el-button>
    </el-form-item>
  </el-form>
</template>

<script>
  export default {
    data() {
      return {
        sourceDictList: [],
        addForm: {
          examTitle: '',
          examPersonCount: 50,
          checkInCount: 0,
          examTime: 120,
          examSubjectCount: 100,
          examCode: '',
          miExamPersonState:0,
          createUser: '',
          updateUser: '',
          createDate: '',
          updateDate: ''
        },
        rules: {
          examTitle: [
            {required: true, message: '请输入考试标题', trigger: 'blur'},
          ],
          examTime: [
            {required: true, message: '请输入考试时长(分钟计)', trigger: 'blur'},
          ]
        },
        loading: false,
      };
    },
    async created() {
      this.addForm.createUser = this.$store.state.userInfo.id;
      this.addForm.updateUser = this.$store.state.userInfo.id;
    },
    methods: {
      submitForm(formName) {
        this.$refs[formName].validate((valid) => {
          if (valid) {
            this.loading = true;
            this.$axios.post('/miExamMaster/insertMiExamMaster', this.addForm).then(response => {
              this.loading = false;
              this.$message({
                showClose: true,
                message: response.data.msg,
                type: response.data.type
              });
              this.resetForm(formName);
            });
          } else {
            return false;
          }
        });
      },
      resetForm(formName) {
        this.$refs[formName].resetFields();
      }
    }
  }
</script>
`

配置文件：
`'use strict'
const path = require('path')
const utils = require('./utils')
const config = require('../config')
const vueLoaderConfig = require('./vue-loader.conf')
const VueLoaderPlugin = require('vue-loader/lib/plugin')

function resolve(dir) {
  return path.join(__dirname, '..', dir)
}

**const webpackConfig** = {
  plugins: [
    new VueLoaderPlugin()
  ],
  context: path.resolve(__dirname, '../'),
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      '@': resolve('src'),
    }
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  },
  node: {
    // prevent webpack from injecting useless setImmediate polyfill because Vue
    // source contains it (although only uses it if it's native).
    setImmediate: false,
    // prevent webpack from injecting mocks to Node native modules
    // that does not make sense for the client
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty'
  }
}

**const vuxLoader = require('vux-loader')

module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [{
    name: 'vux-ui'
  }]
})**

-------------------------------------------------------------------------------------------------------------------
  "dependencies": {
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "element-ui": "^2.4.3",
    "normalize.css": "^8.0.0",
    "vue": "^2.5.16",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    **"vux": "^2.9.2"**
  },
  "devDependencies": {
    "autoprefixer": "^8.6.5",
    "babel-core": "^6.26.3",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-plugin-transform-vue-jsx": "^3.7.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^3.2.0",
    **"less": "^2.7.3",
    "less-loader": "^4.1.0",**
    "mini-css-extract-plugin": "^0.4.1",
    "node-notifier": "^5.2.1",
    "optimize-css-assets-webpack-plugin": "^4.0.3",
    "ora": "^2.1.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.1.0",
    "postcss-loader": "^2.1.5",
    "postcss-url": "^7.3.2",
    "rimraf": "^2.6.2",
    "semver": "^5.5.0",
    "shelljs": "^0.8.2",
    "uglifyjs-webpack-plugin": "^1.2.7",
    "url-loader": "^1.0.1",
    "vue-loader": "^15.2.4",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    **"vux-loader": "^1.2.9",**
    "webpack": "^4.15.1",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4",
    "webpack-merge": "^4.1.3",
    "yaml-loader": "^0.5.0"
  },
  "engines": {
    "node": ">= 8.0.0",
    "npm": ">= 6.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 11"
  ]
}

`

**Comment by chinaguopeng** [comment]
同问这个问题，配置都差不多

**Comment by lerit** [comment]
我也是跟你一样，之前element-ui，现在引入这个vux。
貌似是vue-loader版本太高？

**Comment by 18626328976** [comment]
问下解决了吗？

**Comment by snowlotus** [comment]
同样遇到该问题，请问大家现在有思路了吗？

**Comment by MorLQ** [comment]
看一下是不是vue-loader版本太高了，我之前装了15.0+版本，不行，退到14.2.2版本就OK了；主要是看了https://segmentfault.com/a/1190000014586699?utm_source=tag-newest博主的文章，里面有具体解决思路

**Comment by 18945168** [comment]
> 看一下是不是vue-loader版本太高了，我之前装了15.0+版本，不行，退到14.2.2版本就OK了；主要是看了[https://segmentfault.com/a/1190000014586699?utm_source=tag-newest博主的文章，里面有具体解决思路](https://segmentfault.com/a/1190000014586699?utm_source=tag-newest%E5%8D%9A%E4%B8%BB%E7%9A%84%E6%96%87%E7%AB%A0%EF%BC%8C%E9%87%8C%E9%9D%A2%E6%9C%89%E5%85%B7%E4%BD%93%E8%A7%A3%E5%86%B3%E6%80%9D%E8%B7%AF)

按这个方式解决了问题，还有一点就是     vue-loader/lib/plugin    这个loader 不要使用了

**Comment by 18626328976** [comment]
收到，谢谢您回复我




------------------ 原始邮件 ------------------
发件人: "Leslie"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 晚上11:59
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "yaozheng"<297235499@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [airyland/vux] 在原有elementUI项目中，添加Vux，报错：Module parse failed: Unexpected token (3:0) You may need an appropriate loader to handle this file type. (#2935)



 
看一下是不是vue-loader版本太高了，我之前装了15.0+版本，不行，退到14.2.2版本就OK了；主要是看了https://segmentfault.com/a/1190000014586699?utm_source=tag-newest博主的文章，里面有具体解决思路
  
按这个方式解决了问题，还有一点就是     vue-loader/lib/plugin    这个loader 不要使用了
