### ISSUE TITLE
[Bug Report] XInput 551行 监听currentValue 将值修改为null的时侯  出现null of length 错误

### ISSUE THREAD

**Issue by kdzxiaoli** [airyland/vux#2937]
### VUX version
2.9.2

### OS/Browsers version
mac 

### Vue version
2.5.17-beta.0

### Code

```html
vue.esm.js?efeb:591 [Vue warn]: Error in callback for watcher "currentValue": "TypeError: Cannot read property 'length' of null"
```

### Steps to reproduce
first:  v-model="value"
second: this.value = null

### What is Expected?
应该有判空

### What is actually happening?
没有判空

**Comment by alicksnake22** [comment]
同样的问题，置null后输入第一个字符会报错，然后该次输入无法触发绑定，输入第二个字符即可成功触发

**Comment by alicksnake22** [comment]
置空是常用操作，但是置null后就会报错，导致后面无法再双向绑定
