### ISSUE TITLE
sticky底部固定

### ISSUE THREAD

**Issue by transtone** [airyland/vux#294]
sticky是否可以做成像[ ant.design 的固钉](http://ant.design/components/affix) 一样可以任意指定位置固定？

**Comment by airyland** [comment]
移动端有这个需求场景？

**Comment by transtone** [comment]
tabbar不就是固定到底部的吗，还有商城购买按钮等。

**Comment by airyland** [comment]
sticky解决的需求不是固定，是原来不在顶部，触及到顶部后动态固定在顶部。

移动端除了固定在顶部，底部，还有固定在中间的需求？

**Comment by airyland** [comment]
tabbar是一直固定在底部，和sticky真没有什么关系。况且用css就可以解决了。

**Comment by transtone** [comment]
页面太长了，往下拉会出现“返回顶部”等按钮。
![1 pic](https://cloud.githubusercontent.com/assets/46688/16297769/d1bf1a10-3964-11e6-8de7-ba9a75ea34df.jpg)

虽然css本就可以解决，这不是想省点事吗，就像 box 一样。

**Comment by airyland** [comment]
这个需求可以理解，但是和上面的tabbar不是同一个需求。这个写个js不是更简单更少代码吗，滑动距离超过多少时就显示。。

**Comment by transtone** [comment]
好吧，sticky本身不是也可以写个js来实现么。已经说了，不是想偷懒么：）

**Comment by airyland** [comment]
这个跟sticky真不是同一个东西呀。。要实现你这个需要你那个返回顶部先放在页面某个位置才能用sticky来实现吧，但是你怎么事先知道应该放哪个位置。。
