### ISSUE TITLE
[Feature Request] InlineXNumber 建议新增相关事件

### ISSUE THREAD

**Issue by wangq2008** [airyland/vux#2946]
### Existing Component
是

### Component Name
InlineXNumber 

### Description
现有的InlineXNumber  步进组件没有事件，在购物车场景时，当点加按钮时，就触发新增购物车事件，减到0时，移除购物车。现有的组件没有任何事件，我觉得不够完善

**Comment by liping1994** [comment]
还有一场景是  
每次数目加减都需要请求后台数据  现在请求太频繁了  上一次还在请求 这一次就又开始了

**Comment by liping1994** [comment]
1 楼可以监听 value 的变化 如果为0就可以移除购物车

**Comment by liping1994** [comment]
不好意思 我可以自己加监听事件 没得事情了
