### ISSUE TITLE
[Feature Request] 请问checklist组件中title可以直接绑定中文吗

### ISSUE THREAD

**Issue by zhangchenpan** [airyland/vux#2957]
### Existing Component
是

### Component Name
checklist

### Description
          <checklist title="sex" ref="sex" :readonly="readonly" :options="sexs" v-model="beneficiary.sex" :max="1" :min="1"></checklist>
这么写报错:Invalid prop: type check failed for prop "value". Expected Array, got String.

请问有解决办法吗

**Comment by unclay** [comment]
标题和错误没啥关联阿，titile可以直接绑定中文，至于错误beneficiary.sex 必须是一个数组，你应该是用了字符

**Comment by zhangchenpan** [comment]
2022年在回头看18年提的问题,真是傻啊
