### ISSUE TITLE
[Bug Report] Picker 和 PopupPicker 引入报错（其他的不会）

### ISSUE THREAD

**Issue by xilongCN** [airyland/vux#2958]
### VUX version
2.9.2

### OS/Browsers version
win10/ chrome 67.0.3396.99

### Vue version
2.5.2

### Code

```html
import { PopupPicker } from 'vux'

export default {
  components: {
    PopupPicker
  }
}
```

### Steps to reproduce
直接引入 就报错

### What is Expected?
能够使用 PopupPicker

### What is actually happening?
使用项目运行报错

**Comment by unclay** [comment]
这边试了不会报错
你那边是报什么错

**Comment by xilongCN** [comment]
https://github.com/airyland/vux/issues/2576
https://github.com/airyland/vux/issues/2694
你好，老哥，我发现是因为引入了  postcss-px2rem 这个插件引起的，把插件换成 postcss-plugin-px2rem 就好了，上面那两个 链接 是之前有人提交过的 错误
感谢，感谢
