### ISSUE TITLE
地址选择在scroller有问题

### ISSUE THREAD

**Issue by LiangFuzhi** [airyland/vux#296]
因为scroller用到了    transform: translateX(0px) translateY(-111px) translateZ(0px) scale(1, 1);  导致地址选择    position: fixed;不生效，应该在点击地址选择时在scroller上添加transform:none;选完在删除transform:none

**Comment by airyland** [comment]
Scroller建议用来显示列表不适用于添加各种组件，尤其是触摸相关的

**Comment by LiangFuzhi** [comment]
还有一种解决方法，就是把弹窗的组件需要弹出的那一部分生成在body下一级，类似模态窗的遮罩层。这样基本上所有的组件都可以用在Scroller，因为我想实现在app里所有页面都类似ios原生的页面可以弹性的下拉或上拉。

**Comment by airyland** [comment]
scroller是个特殊的容器，不建议有交互组件在里面。各个组件应该是独立的，不然可能要在scroller上加上一堆代码来兼容所有组件。

使用scroller也需要谨慎，一些情况下没必要用到scroller。你的需求场景是？

**Comment by LiangFuzhi** [comment]
我想实现ios原生app那种每个页面都可以滚动到顶部或底部都可以继续拉，然后回弹这个效果

**Comment by airyland** [comment]
@LiangFuzhi 就为了这个效果么。。iOS上默认就有这个效果了吧。

**Comment by LiangFuzhi** [comment]
我做的这个app都是h5做的，需要自己实现。

**Comment by airyland** [comment]
因为scroller确实无法做到无副作用，所以还是不建议这样做。建议找找其他轻量实现   :sweat_smile:

**Comment by LiangFuzhi** [comment]
好，现在暂时不做这个效果

**Comment by airyland** [comment]
感觉这种效果应该在封装该页面的App上来完成
