### ISSUE TITLE
[Feature Request] 如何不使用webpack等打包工具使用vux

### ISSUE THREAD

**Issue by qinghechaoge** [airyland/vux#2969]
### Existing Component
否

### Component Name
没有组件

### Description
文档中说 

Webpack 如果你直接使用 vux2 模板，你可以暂时不用了解。当你需要自定义一些配置时自然就能很快了解了。

但是我没有找到 vux2 模板 的文档

**Comment by caozhong1996** [comment]
目前这部分文档已经过时，之后会再更新一波。
