### ISSUE TITLE
tabbar导航选项如何与每个单页关联

### ISSUE THREAD

**Issue by SevonWang** [airyland/vux#297]
你好 我在用VUX做UI 不知道tabbar底部导航的选项如何与每个单页关联，刚接触VUX，帮忙解答！非常感谢
![image](https://cloud.githubusercontent.com/assets/17562819/16330056/41b40d76-3a19-11e6-8c67-8c83873c853c.png)

**Comment by airyland** [comment]
可以在tabbar-item上使用`link`属性定义链接
文档： https://vuxjs.gitbooks.io/vux/content/layout/tabbar.html
例子参照： https://github.com/airyland/vux/blob/master/src/demos/TabbarLink.vue
