### ISSUE TITLE
[Bug Report] vue-cli3.0引入后报错

### ISSUE THREAD

**Issue by zh-mead** [airyland/vux#2970]
### VUX version
2.9.2

### OS/Browsers version
mac

### Vue version
2.5.16

### Code

```html
 error  in ./src/views/home/home.vue

Module parse failed: Unexpected token (3:0)
You may need an appropriate loader to handle this file type.
| import { render, staticRenderFns } from "./home.vue?vue&type=template&id=39f87be5&"
| import script from "./home.vue?vue&type=script&lang=js&"
> ../../../node_modules/vux-loader/src/script-loader.js!export * from "./home.vue?vue&type=script&lang=js&"
|
|

 @ ./src/router/router.js 23:11-50
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.212.4:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

### Steps to reproduce
vue-cli3.创建项目，引入vu想，配置vue.config.js为const vuxLoader = require('vux-loader')
module.exports = {
    configureWebpack: config => {
        vuxLoader.merge(config, {
            options: {},
            plugins: ['vux-ui']
        })
    }
}

然后提示就上面的错误

### What is Expected?
支出为啥错了，问题的决绝办法

### What is actually happening?
自己也尝试去搜，去github上看之前的issue，但是没有找到解决的办法

**Comment by wangjunwei531** [comment]
我的操作是，执行
```
$ cnpm i vue-loader -D
```
给我下载了一个"vue-loader": "^14.2.3",
然后就正常运行了

**Comment by whirly77cai** [comment]
> 我的操作是，执行
> 
> ```
> $ cnpm i vue-loader -D
> ```
> 给我下载了一个"vue-loader": "^14.2.3",
>

> ### VUX version
> 2.9.2
> 
> ### OS/Browsers version
> mac
> 
> ### Vue version
> 2.5.16
> 
> ### Code
> ```
>  error  in ./src/views/home/home.vue
> 
> Module parse failed: Unexpected token (3:0)
> You may need an appropriate loader to handle this file type.
> | import { render, staticRenderFns } from "./home.vue?vue&type=template&id=39f87be5&"
> | import script from "./home.vue?vue&type=script&lang=js&"
> > ../../../node_modules/vux-loader/src/script-loader.js!export * from "./home.vue?vue&type=script&lang=js&"
> |
> |
> 
>  @ ./src/router/router.js 23:11-50
>  @ ./src/main.js
>  @ multi (webpack)-dev-server/client?http://192.168.212.4:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
> ```
> 
> ### Steps to reproduce
> vue-cli3.创建项目，引入vu想，配置vue.config.js为const vuxLoader = require('vux-loader')
> module.exports = {
> configureWebpack: config => {
> vuxLoader.merge(config, {
> options: {},
> plugins: ['vux-ui']
> })
> }
> }
> 
> 然后提示就上面的错误
> 
> ### What is Expected?
> 支出为啥错了，问题的决绝办法
> 
> ### What is actually happening?
> 自己也尝试去搜，去github上看之前的issue，但是没有找到解决的办法

我也遇到这个问题，请问你现在解决了吗？

**Comment by zhengmiaohua** [comment]
有没有大哥解决了的
