### ISSUE TITLE
升级到0.1.1后，css的问题

### ISSUE THREAD

**Issue by bluefox1688** [airyland/vux#298]
我把项目从0.0.16版本升级到0.1.1后，css全部都失效了，之前是使用@import '~vux/vux.css';来导入css，现在我需要怎么处理？能把css导进来

**Comment by airyland** [comment]
@import '~vux/dist/vux.css';

**Comment by bluefox1688** [comment]
回复好神速呀，我还以为我看错了
好了，谢谢，如果要把css拆分到各组件，这个目前有解决方案吗？

**Comment by airyland** [comment]
在进行中。现在是0.1.1争取在0.1.4之前搞定，那么就完全不需要这样手动引入冗余代码了。

**Comment by bluefox1688** [comment]
恩恩，非常期待
