### ISSUE TITLE
[Bug Report] @vue/cli vue-cli 3.x Module parse failed: Unexpected token (3:0) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by heystar** [airyland/vux#2988]
### VUX version
2.9.2

### OS/Browsers version
Mac Windows / Chrome

### Vue version
2.5.16

### Code

```html
configureWebpack: config => {
        require('vux-loader').merge(config, {
            options: {},
            plugins: ['vux-ui']
        })
 }
```

### Steps to reproduce
const vuxLoader = require('vux-loader')

module.exports = {
configureWebpack: config => {
        require('vux-loader').merge(config, {
            options: {},
            plugins: ['vux-ui']
        })
 }
}

### What is Expected?
正常加载loader

### What is actually happening?
Module parse failed: Unexpected token

**Comment by hank2718** [comment]
关注中，也是这个问题

**Comment by lanlanmingyue** [comment]
同样的问题，关注中

**Comment by maoliang2271** [comment]
我也是

**Comment by prosaically** [comment]
我的无法加载，报错：You may need an appropriate loader to handle this file type.，你能给个你的配置吗？

**Comment by EricLiuCN** [comment]
不知道你用的是什么，我是用的是laravel框架，在package.json文件中把
"vue-loader": "^13.3.0",
"vue-template-compiler": "^2.5.2"
应该是版本太高了 这两项的版本换成这两个 亲测通过。
吃了没文化的亏，爬坑到现在。记录一下

**Comment by eightHundreds** [comment]
> 不知道你用的是什么，我是用的是laravel框架，在package.json文件中把
> "vue-loader": "^13.3.0",
> "vue-template-compiler": "^2.5.2"
> 应该是版本太高了 这两项的版本换成这两个 亲测通过。
> 吃了没文化的亏，爬坑到现在。记录一下

我这边也是版本太高了
但是vue-loader 13不适合webpack4,我降低到 vue-loader 14 就行了

**Comment by eightHundreds** [comment]
> 不知道你用的是什么，我是用的是laravel框架，在package.json文件中把
> "vue-loader": "^13.3.0",
> "vue-template-compiler": "^2.5.2"
> 应该是版本太高了 这两项的版本换成这两个 亲测通过。
> 吃了没文化的亏，爬坑到现在。记录一下

我这边也是版本太高了
但是vue-loader 13不适合webpack4,我降低到 vue-loader 14 就行了

**Comment by caozhong1996** [comment]
see #3778
