### ISSUE TITLE
这是一个神奇的BUG

### ISSUE THREAD

**Issue by fanchaot** [airyland/vux#2990]
![image](https://user-images.githubusercontent.com/32870484/43455044-463d4cd8-94f1-11e8-8be7-0b98794ad7d4.png)

这是一个神奇的BUG

**Comment by liu874396180** [comment]
这是一个幻觉~~

**Comment by fanchaot** [comment]
我vw vh 布局   我自己并无法改变窗口的高度    感觉从源码改 一动而变全身  有没有什么比较好的解决方法

**Comment by caozhong1996** [comment]
时间太久，如果还需要帮助请重开issue
