### ISSUE TITLE
[Feature Request] 官方文档的改进建议

### ISSUE THREAD

**Issue by fralonra** [airyland/vux#2991]
### Existing Component
是

### Component Name
文档

### Description
（未找到合适的issue模板，如有不妥请指出）

以下是依我个人浏览文档的体验提出的一些建议：
1. 目前切换页面时，如果前一页面有滚动，则新页面也会滚动至相同高度，建议打开新页面时不滚动，用户体验会比较好
2. 组件页面，右侧的预览浮窗有时会遮挡住文字，例如 Actionsheet 文档 (https://doc.vux.li/zh-CN/components/group.html) 。建议修改样式使文字不会被遮挡

**Comment by caozhong1996** [comment]
这个版本不做太多额外改动了，谢谢
