### ISSUE TITLE
datetime组件 readonly无效

### ISSUE THREAD

**Issue by baixiaoyu2997** [airyland/vux#2992]
VUX version
2.9.2

OS/Browsers version
chrome

Vue version
 68.0.3440.75

Code
test.vue
---------------------------start-----------------------------------

<template>
  <div class="createOrder">
    <group>
      <datetime title="下单日期"   v-model="editOrderForm.ORDER_TIME" placeholder="请选择" :end-date="ORDER_TIME_END" :readonly="editpage"></datetime>
    </group>
  </div>
</template>

<script>

export default {
    data() {
        return {
            editPage:true
        };
    },
};
</script>
------------------------------end--------------------------------
Steps to reproduce
点击datetime组件

What is Expected?
点击不显示

What is actually happening?
readonly无效

**Comment by tt1262360978** [comment]
唉，我也readonly失效
