### ISSUE TITLE
vue-cli 3.0 i18n error

### ISSUE THREAD

**Issue by tapqr** [airyland/vux#2999]
### 项目所有的依赖
`
"dependencies": {
    "vue": "^2.5.16",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-rc.5",
    "@vue/cli-plugin-eslint": "^3.0.0-rc.5",
    "@vue/cli-plugin-unit-mocha": "^3.0.0-rc.5",
    "@vue/cli-service": "^3.0.0-rc.5",
    "@vue/test-utils": "^1.0.0-beta.20",
    "chai": "^4.1.2",
    "cssnano": "^4.0.3",
    "cssnano-preset-advanced": "^4.0.0",
    "less": "^3.8.0",
    "less-loader": "^4.1.0",
    "node-sass": "^4.9.0",
    "postcss-aspect-ratio-mini": "^0.0.2",
    "postcss-cssnext": "^3.1.0",
    "postcss-px-to-viewport": "^0.0.3",
    "postcss-viewport-units": "^0.1.4",
    "postcss-write-svg": "^3.0.1",
    "sass-loader": "^7.0.1",
    "vue-template-compiler": "^2.5.16",
    "vux": "^2.9.2"
  }
`

错误信息
` 
error  in ./node_modules/vux/src/components/inline-calendar/index.vue?vue&type=custom&index=0&blockType=i18n

Module parse failed: Unexpected token (74:7)
You may need an appropriate loader to handle this file type.
week_day_0:
   en: Su
->   zh-CN: 日
week_day_1:
   en: Mo

 @ ./node_modules/vux/src/components/inline-calendar/index.vue?vue&type=custom&index=0&blockType=i18n 1:0-213 1:229-232 1:234-444 1:234-444
 @ ./node_modules/vux/src/components/inline-calendar/index.vue
 @ ./node_modules/vux/index.js
 @ ./node_modules/_cache-loader@1.2.2@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.0.0-beta.4@babel-loader/lib!./node_modules/_vue-loader@15.2.6@vue-loader/lib??vue-loader-options!./src/views/home/Index.vue?vue&type=script&lang=js&
 @ ./src/views/home/Index.vue?vue&type=script&lang=js&
 @ ./src/views/home/Index.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.1.5@webpack-dev-server/client?http://10.200.11.27:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
`

**Comment by gendseo** [comment]
请问你解决这个问题了吗？

**Comment by tapqr** [comment]
没去研究，换成mint-ui了。

**Comment by yoage** [comment]
@compasss  mint-ui 兼容吗？

**Comment by tapqr** [comment]
@yoage 兼容。

**Comment by sessplus** [comment]
先安装 npm install vue-i18n --save
在main.js中import vuei18n from 'vue-i18n' 
Vue.use(vuei18n)

@compasss @gendseo @yoage

**Comment by yexk** [comment]
@gengshaojing  我试了下不行呀。你怎么处理的?？
```
"dependencies": {
    "less": "^3.8.1",
    "less-loader": "^4.1.0",
    "vue": "^2.5.17",
    "vue-i18n": "^8.1.0",
    "vux": "^2.9.2",
    "vux-loader": "^1.2.9"
  },
```
我安装了这些。。

**Comment by jennydaman** [comment]
Run

```sh
npm i @kazupon/vue-i18n-loader --save 
```

In vue.config.js

```javascript
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('i18n')
      .resourceQuery(/blockType=i18n/)
      .type('javascript/auto')
      .use('i18n')
      .loader('@kazupon/vue-i18n-loader')
  }
};
```
