### ISSUE TITLE
组件显示状态问题

### ISSUE THREAD

**Issue by LiangFuzhi** [airyland/vux#300]
例如地址选择组件
`<address title="地址" :value.sync="value" :show.sync="show" :list="addressData" placeholder="请选择地址"></address>`

show是我修改了源码props从子组件传上来的。

也就是说希望下一版本能够在所有的弹窗组件加上show。

**Comment by LiangFuzhi** [comment]
我需要根据收尾状态处理其他逻辑

**Comment by airyland** [comment]
如果你`所有的弹窗组件`指的是popup相关的，那么设计上`show`是组合组件的内部逻辑属性，不会暴露出来，只会支持事件。而popup, popup-picker 已经实现了emit @on-hide @on-show事件。

**Comment by LiangFuzhi** [comment]
简单说吧，就是地址现在没有确认和取消事件。😁

**Comment by LiangFuzhi** [comment]
地址选择组件没有取消和确认事件，我需要根据显示状态做其他逻辑

**Comment by airyland** [comment]
我也是这个意思。但是不会把show暴露出来，而是用已有事件来支持。

**Comment by LiangFuzhi** [comment]
嗯嗯，那么下个版本能加上么？

**Comment by airyland** [comment]
Yes.

**Comment by LiangFuzhi** [comment]
可以加个qq或微信吗？
有什么问题可以直接问你。或者提意见。

我的qq：1051548233

:grin::grin:
