### ISSUE TITLE
[Bug Report] 为什么 组件的边框样式通过 :before 和 :after 来实现?

### ISSUE THREAD

**Issue by axetroy** [airyland/vux#3000]
### VUX version
2.7.7

### OS/Browsers version
MacOS

### Vue version
2.5.17

### Code

```html
...
```

### Steps to reproduce

导致现在要修改框架的组件很麻烦

难受

### What is Expected?
.

### What is actually happening?
.

**Comment by tapqr** [comment]
+1
确实很难受。

**Comment by lc-soft** [comment]
- 直接用 border 会增加元素尺寸
- `::before` 样式中有 `transform: scaleY(.5);`，估计是为了让 1px 边框在手机上看起来不那么粗
