### ISSUE TITLE
[Bug Report] previewer 关闭预览后，更新 :list 会报错

### ISSUE THREAD

**Issue by shuhu-fe** [airyland/vux#3005]
### VUX version
2.9.2

### OS/Browsers version
mac os/chrome

### Vue version
2.5.16

### Code

```html
    <div v-transfer-dom>
        <Previewer
            ref="previewer"
            // 动态 list
            :list="previewList"
            :options="options"
            @on-close="onPreviewClose"
        />
    </div>

    data () {
        return {
            pictureList: [],
            options: {
                loop: false
            }
        }
    },

    computed: {
        previewList () {
            const previewList = this.pictureList.map(item => {
                return {
                    src: item.src,
                    w: item.w,
                    h: item.h
                }
            })

            return previewList
        }
    },
    methods: {
        // 关闭预览之后，调用 onRemove 删除 previewList 中的一个元素，就会报错
        onRemove (index) {
            this.pictureList.splice(index, 1)
        },
    }
```

### Steps to reproduce
1. 预览图片【正常】
2. 关闭预览【正常】
3. 删除 list 一个元素【报错】。如下：
vconsole.min.js:11 [Vue warn]: Error in callback for watcher "imgs": "TypeError: Cannot read property 'beforeChange' of null"

found in

---> <Previewer> at node_modules/vux/src/components/previewer/index.vue

### What is Expected?
不报错

### What is actually happening?
报错
vconsole.min.js:11 [Vue warn]: Error in callback for watcher "imgs": "TypeError: Cannot read property 'beforeChange' of null"

found in

---> <Previewer> at node_modules/vux/src/components/previewer/index.vue

**Comment by SaltedFishYuto** [comment]
解决了吗

**Comment by shuhu-fe** [comment]
> 解决了吗

是个 bug...

1. 改源码：

- https://github.com/airyland/vux/pull/3150/files
- https://github.com/airyland/vux/pull/3011/files

2. 不改源码。也可以在 @on-close 事件中加一句：

` onPreviewClose () { this.$refs.previewer.photoswipe = null},`
