### ISSUE TITLE
scroller能否支持更多xscroll方法

### ISSUE THREAD

**Issue by LiangFuzhi** [airyland/vux#301]
scroller组件能否提供scroll-to功能？

我看到xscroll有这个功能[http://xscroll.github.io/demos/scroll-to.html](http://xscroll.github.io/demos/scroll-to.html)

**Comment by LiangFuzhi** [comment]
能否提供暂停滚动和恢复滚动

**Comment by airyland** [comment]
可以取得ref，调用_xscroll的方法。xscroll方法很多没法都作为组件属性出来。

**Comment by airyland** [comment]
或者你也可以直接引用xscroll模块来实现比较复杂的需求。

**Comment by LiangFuzhi** [comment]
ref在哪里可以可以取？

**Comment by airyland** [comment]
请查看vue文档。

**Comment by LiangFuzhi** [comment]
可以了
`this.$refs.scroller._xscroll.scrollTo(0,100,1000)`
可以加个qq么？

**Comment by airyland** [comment]
qq不用于代码相关的交流。可以加入bearychat, https://vux.bearychat.com
