### ISSUE TITLE
swiper的标题如果太长，会和小圆点重合

### ISSUE THREAD

**Issue by terranc** [airyland/vux#302]
### Version
0.1.1

### Android or iOS, which browser?
all

![qq 20160627104922](https://cloud.githubusercontent.com/assets/224353/16367327/d31b5868-3c54-11e6-8564-00967608e65c.png)

标题自动截断+...或者小圆点和标题放两行呗

**Comment by lichunqiang** [comment]
enhancement pr is welcome :+1:

**Comment by airyland** [comment]
这个我来处理，这里加多一个prop: `dotsClass` 这样无论是想自定义位置,其他样式都可以实现了。
因为无法判断dot的宽度，因此也无法做截断，即使可以，右边特别多时，左边文字就基本显示不了了。

**Comment by terranc** [comment]
@airyland 一般直接把标题当做100%来看待的，而右边特别多的情况应该有节操的开发者不会搞出5个以上的圆点吧，只能考虑正常人的需求了。。。

**Comment by airyland** [comment]
其实有的，我们有个打卡活动，会有21个点。。

**Comment by terranc** [comment]
@airyland 说明设计师在偷懒。。我还是觉得出现5个以上的圆点，应该是交互/视觉上除了问题。

**Comment by airyland** [comment]
不是设计的问题，是活动本身要求21天。如果不用swiper，就要用timline，比较费空间。

**Comment by terranc** [comment]
@airyland 打卡，不是应该设计成下面一个日历，点击对应日期，上面的banner切换吗？而且即便是swiper，每个item都有title？想象不出它的模样，哈。。

**Comment by airyland** [comment]
对的，改天给你看看哈。是既有日历，又有swiper。。

**Comment by terranc** [comment]
其实我觉得最省事的就是title和圆点分两行显示，提供属性设置是否需要显示圆点，让黑色渐变稍微拉高一点，虽然浪费点空间，但通用了。
