### ISSUE TITLE
[Bug Report] x-input 无法通锅点击input部分来触发focus光标

### ISSUE THREAD

**Issue by qifengwangye** [airyland/vux#3023]
### VUX version
2.9.2

### OS/Browsers version
win7 x64 chrome 67

### Vue version
2.5.17

### Code

```html
<x-input title="必须输入2333" :is-type="be2333" placeholder="I'm placeholder"></x-input>
```

### Steps to reproduce
点击x-input的title才能触发input的焦点事件，直接点击input部分是无法触发focus光标

### What is Expected?
点击input部分即可正确触发input的光标

### What is actually happening?
点击x-input的title才能触发input的焦点事件，直接点击input部分是无法触发focus光标

**Comment by qifengwangye** [comment]
在官方的api文档里面的例子就是不能通过点击input来正确触发光标，这个都没有人提过吗

**Comment by rujptw** [comment]
能否考虑支持点击input部分即可正确触发input的光标的功能呢
