### ISSUE TITLE
Swiper组件配置支持v-link

### ISSUE THREAD

**Issue by cyio** [airyland/vux#303]
### Version
0.1.1-rc3
### Android or iOS, which browser?
both
### Your Codes 

``` js
const demoList =
[{
  url: '',
  img: '',
  title: ''
}]
```

### Expected behavior and actual behavior.

在项目中使用`vue-router`，希望swiper的地址跳转配置能支持`v-link`

**Comment by airyland** [comment]
参考tabbar-item的link属性, 使用libs下面的router工具函数
