### ISSUE TITLE
[Bug Report] X-input在iOS下，赋值会自动focus

### ISSUE THREAD

**Issue by liuzz1024** [airyland/vux#3030]
### VUX version
2.9.2

### OS/Browsers version
Mac OS & iOS11

### Vue version
2.5.17

### Code

```html
<html代码>
  <x-input 
   title="A类产品"
  :value='Aclass'
  @on-blur='numTurn'
  ref='input1'
  text-align="right" 
  placeholder="请输入金额"></x-input>
<html代码>

<script代码>
    numTurn(val){
      this.Aclass = numberComma(val);
      this.$refs.input1.blur();
    }
</script>
```

### Steps to reproduce
1、使用X-input的@on-blur事件，在失去焦点的时候自动把输入的金额用numberComma()进行千分符的分割，然后进行赋值
2、尝试在失去焦点的numTurn()当中写<主动失去焦点>的代码，此方法无效。。。
3、在安卓系统上，X-input在赋值之后，是会自动失去焦点的。

### What is Expected?
在iOS下，给X-input的value赋值，失去焦点。

### What is actually happening?
在iOS下，给X-input的value赋值之后，没有失去焦点，反而自动focus了

**Comment by emondora** [comment]
这个版本的 x-input 问题不少，可能和这部分有一定关系。https://github.com/airyland/vux/commit/8547e740abf8bc2e750f15c033254e8ec98c2bcb

**Comment by myway42** [comment]
碰到了一样的问题，有没有好的解决方法？

**Comment by shengsheng10086** [comment]
请问解决了吗？

**Comment by easy868** [comment]
是存在这个问题，赋值后显示了清除按钮

**Comment by LiangFuzhi** [comment]
> 这个版本的 x-input 问题不少，可能和这部分有一定关系。[8547e74](https://github.com/airyland/vux/commit/8547e740abf8bc2e750f15c033254e8ec98c2bcb)

由老哥提醒 找到了问题原因是 selection 而做出如下 曲线救国的方式：
``` js
import XInput from 'vux/src/components/x-input/index.vue'
let currentValueFnStr = XInput.watch.currentValue.toString()
// function缺失
if (currentValueFnStr.indexOf('function') !== 0) {
  currentValueFnStr = `function ${currentValueFnStr}`
}
// build时拿到的代码被压缩
currentValueFnStr = currentValueFnStr.replace(/this\.\$refs\.input\.selectionStart!==(.*?)&&/, (data) => {
  return `(${data}this.isFocus)&&`
})
// dev环境
currentValueFnStr = currentValueFnStr.replace(/\((.*?)\$refs\.input\.selectionStart !== selection/, (data, inputThis) => {
  return `${data} && ${inputThis}isFocus`
})
currentValueFnStr = `${currentValueFnStr};currentValue.apply(this, arguments)`
XInput.watch.currentValue = function () {
  // eslint-disable-next-line no-eval
  eval(currentValueFnStr)
}

```
原因是在ios设置selectionStart或selectionEnd会自动聚焦

**Comment by dufan1994** [comment]
今天用了另外一种方法解决的，设置disabled为true就不会自动获取焦点，然后设置一个定时器值改变之后立即把disabled属性设置为false

**Comment by fanaoxue** [comment]
X-input组件问题太多了，不顾还好，找了了大佬帮我解决问题，谢谢楼上的大佬！

**Comment by fanaoxue** [comment]
不行不行，打完包上测试环境，x-iput的blur事件不能触发了

**Comment by caozhong1996** [comment]
鉴于时间过去太久，我将关闭这个issue，还需要帮助的话请重开issue，如果你已经知道如何解决也请提交对应的pr，谢谢!

**Comment by KID-joker** [comment]
vux 2.11.1还存在该问题：ios赋值后会自动聚焦
调试发现应该是[selectionStart](https://github.com/airyland/vux/blob/f9f97d41d10206bd5eeddd9a0c75265d7b6a3cb5/src/components/x-input/index.vue#L558-L560)的问题
@caozhong1996 大佬可以抽空看一下，或者告知一下这段代码的用意
