### ISSUE TITLE
[Bug Report] x-input 有setTimeout操作DOM，如果有v-if="false" 的情况下，会报错，找不到DOM

### ISSUE THREAD

**Issue by axetroy** [airyland/vux#3045]
### VUX version
2.9.2

### OS/Browsers version
chrome

### Vue version
2.5.17

### Code

```html
<x-input v-if="false"/>
```

### Steps to reproduce
v-if 会把dom给移除掉

而setTimeout里面的操作DOM，会获取不到DOM

### What is Expected?
对于DOM的操作应该是同步的，在mounted中执行

### What is actually happening?
在setTimeout中操作

**Comment by axetroy** [comment]
相关代码:

https://github.com/airyland/vux/blob/e14858309925f0173fd4ba157a833ca819d29730/src/components/x-input/index.vue#L365

**Comment by axetroy** [comment]
![1](https://user-images.githubusercontent.com/9758711/44218786-09c32c00-a1ad-11e8-8371-8cfb35fe1364.png)

**Comment by emondora** [comment]
我貌似也是遇到过类似的问题，但不是在setTimeout里面触发的，而且比这个更严重的问题是，VUX 2.9.2的x-input，在安卓微信里的this.$refs.xxInput.valid会有问题，而iOS微信里面没有这个问题。

**Comment by zhaohuwei** [comment]
这个问题，我提交了个PR，作者还没合并，你可以自己项目改下（ #2886 ）
