### ISSUE TITLE
[Feature Request] 给search组件的一个建议

### ISSUE THREAD

**Issue by Suntgr** [airyland/vux#3047]
### Existing Component
是

### Component Name
search

### Description
search组件中能否添加一个type属性，在搜索固定类目，如编号等值为数字情况下，希望type='number'，以便于自动弹出数字键盘。

**Comment by kevinchung1026** [comment]
1. 找到文件`vux/src/components/search/index.vue`，修改源码
2. 将`type="search"`改为`:type="type"`
3. 往`js`中的`props`增加 `type:  {type: String, default: 'search'}`
4. 在业务代码中，`search`增加属性`type="number"`即可

我也提PR了~
