### ISSUE TITLE
安卓使用弹窗组件闪烁

### ISSUE THREAD

**Issue by lixinxiaobai** [airyland/vux#305]
发现安卓机型使用vux的弹窗组件，比如popup组件的时候，会有一瞬间的闪烁，感觉不是特别流畅，这个有办法修复吗

**Comment by airyland** [comment]
低端机？

**Comment by lixinxiaobai** [comment]
不算低端啊，但是也不高端， 乐视1S，包括红米3， 都是八核的，不过刚才把.vux-popup-mask 0.2秒的transition去掉表现的好一点了

**Comment by airyland** [comment]
如果默认把动画去掉，那么Android和iOS都会没有动画。调用组件时手动加上的话还是会导致你的这个问题。这个问题似乎之前也有其他人提过了，你的建议呢？

你们的建议呢  @graysheeep  @lichunqiang @unclay

**Comment by airyland** [comment]
或者有没有优化动画性能的方法?

**Comment by LiangFuzhi** [comment]
闪烁问出现在微信吧！微信内置的浏览器很卡的

**Comment by airyland** [comment]
iOS的safari是没问题的，微信更新到Blink后性能理论上也应该不会太差。我有点觉得是现在手机硬件性能低。

**Comment by graysheeep** [comment]
@airyland popup的动画没必要去掉吧，现在的机器性能也足够了。我觉得alert那个动画没什么必要……

**Comment by airyland** [comment]
@graysheeep 😓 貌似我又看错了，昨天看的时候以为是dialog的动画。。
