### ISSUE TITLE
[Bug Report] 【兼容性问题】x-input标签上on-change事件在魅族mx6设备上不生效。

### ISSUE THREAD

**Issue by wangsj-github** [airyland/vux#3052]
### VUX version
2.7.4

### OS/Browsers version
魅族MX6,andrioid版本：6.0

### Vue version
2.5.17

### Code

```html
<x-input title="银行账号：" v-model="data.bankAccount" type="number" placeholder="请输入银行卡号" text-align="right" placeholder-align="right" @on-change='changeBankNo(data,index)'>
</x-input>
```

### Steps to reproduce
在魅族MX6,andrioid版本：6.0手机上，打开自己做的一个SPA小demo，将代码中的x-input标签的type属性设置为number类型，然后再次通过手机访问，即可复现。

### What is Expected?
on-change事件可以正常监听到输入框中的值。

### What is actually happening?
on-change事件监听不到输入框中的值。

**Comment by mrzzcn** [comment]
[2918](https://github.com/airyland/vux/issues/2918)
