### ISSUE TITLE
icon如何应用自定义图片？谢谢

### ISSUE THREAD

**Issue by yumazhe** [airyland/vux#3059]

**Comment by gendseo** [comment]
如果你使用 x-icon 组件的话，可以使用本地图片svg资源，
存在于    {项目名称}\node_modules\vux\src\icons\

将图标svg名称换成 x-icon 中的 type 属性值名称，详情使用方法请看 https://doc.vux.li/zh-CN/components/x-icon.html


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
