### ISSUE TITLE
cell的类panel样式

### ISSUE THREAD

**Issue by transtone** [airyland/vux#306]
panel组件的三种样式都不错，看有时候想将panel和cell混用却很麻烦，可否将panel的样式引入cell，或者将panel由列表调整为单个，这样组合使用也好，列表循环也好，就都方便了。

**Comment by airyland** [comment]
panel的样式引入cell不科学。panel为多个item时得多加3个子组件，也好像比较繁琐的样子。
panel和cell混用，给个例子？

**Comment by wulucxy** [comment]
@airyland 请问panel和card的应用场景有什么区别，光从demo上看不出来

**Comment by airyland** [comment]
panel是预定义好了图文的结构和样式。card是自由组合。

**Comment by airyland** [comment]
需求不明晰。如果组件满足不了，建议自己编写。
