### ISSUE TITLE
vux 不兼容vue-loader 15.x.x版本

### ISSUE THREAD

**Issue by prosaically** [airyland/vux#3060]
使用vue-loader 155.x.x以上版本会出现以下错误：
`Module parse failed: Unexpected token (3:0) You may need an appropriate loader to handle this file type.`
使用Vue.use()报错也是版本兼容问题。
希望今后能够提供兼容支持，谢谢！

**Comment by gendseo** [comment]
参见 https://segmentfault.com/a/1190000014586699

**Comment by Jiiiiiin** [comment]
@airyland 有没有计划呢？

**Comment by sessplus** [comment]
vue-loader 版本太高
yarn add vue-loader@14.2.2 -D
or
npm install vue-loader@14.2.2 -D

**Comment by panhezeng** [comment]
被坑了，这个项目感觉已经被废弃了。当初设计过于非主流，和element ui，有赞vant ui等方式都不一样，非要自己搞个vux-loader，而不是采用babel-plugin-import方式，又不没有提供cdn使用方式。
vux-loader的方式过于侵入，过于依赖vue-loader，造成了vue vue loader 大版本升级后，项目开发者已经无力升级

**Comment by panhezeng** [comment]
个人项目果然得慎用啊。

**Comment by airyland** [comment]
@panhezeng 

别动不动就个人项目个人项目慎用，如果曾给你带了方便那么至少先表达下感谢。

另一方面，你也是社区的一部分，你是否有来贡献一下或者看一下如何升级呢？你抱怨开发者无力升级，自己是否看过源码尝试改造呢。

用 vux-loader 正是为了开发者方便而不是为了制造麻烦。这实际上是种超前的设计，hack 的方式是因为在当时 vue-loader 以及 webpack 的设计不利于扩展。事实上开发之初已经能预想到这两个库会逐渐变得可扩展，而它们现在的版本已经足以不需要 hack 而直接改配置了。
