### ISSUE TITLE
ERROR in ./~/.npminstall/vux/0.1.1-rc3/vux/src/components/steps/index.js

### ISSUE THREAD

**Issue by clarence1993** [airyland/vux#307]
### Version
^0.1.1-rc3
### Your Codes 
![image](https://cloud.githubusercontent.com/assets/8635986/16379200/b87cc3d6-3ca2-11e6-81e3-56520fadedbe.png)

``` html
<!--put your code here-->
```
ERROR in ./~/.npminstall/vux/0.1.1-rc3/vux/src/components/steps/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./step in /opt/app/static/VACRM/H5/node_modules/.npminstall/vux/0.1.1-rc3/vux/src/components/steps
 @ ./~/.npminstall/vux/0.1.1-rc3/vux/src/components/steps/index.js 3:12-29
### Steps to reproduce the problem
![Uploading image.png…]()

**Comment by airyland** [comment]
图片未上传完成，麻烦再上传一次。

**Comment by lichunqiang** [comment]
你的为啥是大写的? `Step.vue
`

**Comment by airyland** [comment]
这个组件还没有添加到demo里，上次想到一个问题还没解决，中间横线无法100%宽度。

**Comment by clarence1993** [comment]
文件里面引用是小写的./step，文件名实际上是大写的Step.vue,mac的开发没问题，在centos上部署的时候是报错了，找不到，改成一样的就好了

**Comment by lichunqiang** [comment]
下载最新的release呢，是不是人为改的？

**Comment by airyland** [comment]
感觉可能确实是版本库或者发布时有问题。

**Comment by lichunqiang** [comment]
恩，目前最新的release是小写的，没问题
