### ISSUE TITLE
 @click.native 点击事件冒泡，解决不了

### ISSUE THREAD

**Issue by jiudan** [airyland/vux#3070]
<group >
          <cell is-link :data-id="item.id"  :title="item.village_name" :inline-desc='item.shop_address' v-for="(item, index) in dataArr" @click.native.stop="storeSelectTap" :data-index="index" ></cell>
</group>

解决不了事件冒泡，获取不了 data-id

**Comment by jiudan** [comment]
<group >
          <cell is-link :data-id="item.id"  :title="item.village_name" :inline-desc='item.shop_address' v-for="(item, index) in dataArr" @click.native.stop="storeSelectTap" :data-index="index" ></cell>
        </group>

**Comment by jiudan** [comment]
`<group >
          <cell is-link :data-id="item.id"  :title="item.village_name" :inline-desc='item.shop_address' v-for="(item, index) in dataArr" @click.native.stop="storeSelectTap" :data-index="index" ></cell>
        </group>`

**Comment by jiudan** [comment]
父元素才有data-id，子元素没有data-id， 安装vux，自己看下，.stop 无效

**Comment by jiudan** [comment]
事件参数传id，能获取到id了，但还是想方法解决冒泡的问题，因为还有提交默认事件，很多场景

**Comment by chengjs** [comment]
能发给我你的代码嘛？

**Comment by jiudan** [comment]
`<template>



        <div class="weui-cells vux-no-group-title" data-layout="2">
            <div class="weui-cell vux-tap-active weui-cell_access" :data-id="item.id" :data-index="index" v-for="(item, index) in dataArr" v-on:click.stop="storeSelectTap(index)">
              <div class="weui-cell__hd"></div> 
              <div class="vux-cell-bd vux-cell-primary" >
                <p><label class="vux-label" >{{item.village_name}}</label> </p> 
                <span class="vux-label-desc" ><span class="vux-badge">{{item.range}}km</span> {{item.shop_address}}</span>
              </div> 
              <div class="weui-cell__ft">  </div> 
            </div>
        </div>



</template>


<script>
import { Group, Cell, CellBox , Badge, Scroller } from 'vux'
//import BMap from 'BMap';
export default {

  name:'storeList',

  components: {
    Cell, 
    CellBox, 
    Group, 
    Badge,
    Scroller
  },

  data () {
    return {
      dataArr: []
    }
  },
`
