### ISSUE TITLE
不能在属性上做判断，小程序可以，vue不可以

### ISSUE THREAD

**Issue by jiudan** [airyland/vux#3073]
怎么在标签上 判断？
 怎么判断，在v-for里面
:data-stockstate="item.cart_num <= 0"

或者只能遍历json，给json增加新属性做判断了
‘’data.data.data.forEach(v =>{
    v.stockstate1=v.cart_num <= 0 ? 0 : 1;
    v.stockstate2=v.cart_num>=v.goods_stock ? 0 : 1;
 });‘’

**Comment by Sapphire2k** [comment]
@jiudan 可以做判断的

`:data-stockstate="item.cart_num <= 0 ? 0:1"`

你确定不是子组件的属性接收类型有误导致的？

还有这里是Vux，不是Vue

**Comment by jiudan** [comment]
谢谢，可以判断，就是不能有0 和 false ， 判断改成 :data-stockstate="item.cart_num <= 0 ? 1:2" 就可以了
