### ISSUE TITLE
在main.js全局按需引用后，webpack还是把整个项目打入

### ISSUE THREAD

**Issue by wangrunrun** [airyland/vux#3079]
![image](https://user-images.githubusercontent.com/26536267/44977277-368f8580-af9a-11e8-81b6-936c43be99c0.png)
![image](https://user-images.githubusercontent.com/26536267/44977325-4f983680-af9a-11e8-995b-473f77408a00.png)

**Comment by qinouz** [comment]
我页遇到了 这个 问题

**Comment by caozhong1996** [comment]
see #3778
