### ISSUE TITLE
[Bug Report] Tab 当Tab宽度不是100%的情况下 bar的位置不正确 

### ISSUE THREAD

**Issue by zhaoqinghao** [airyland/vux#3089]
### VUX version
2.7.1

### OS/Browsers version
mac / chrome

### Vue version
2.5.12

### Code

```html
  <tab class="tab">
.tab{
  width: 680px;
}


源码错误位置  ：window.innerWidth 此处不应该用innerWidth,应该用tab的真实宽度
 barLeft () {
      if (this.hasReady) {
        const count = this.scrollable ? (window.innerWidth / this.$children[this.currentIndex || 0].$el.getBoundingClientRect().width) : this.number
        return `${this.currentIndex * (100 / count)}%`

```

### Steps to reproduce
  <tab class="tab">
tab不占全屏
.tab{
  width: 680px;
}

### What is Expected?
底部跟随bar会偏移，越到后边偏移越多

### What is actually happening?
不会偏移

**Comment by fuerpeng** [comment]
同上,遇到这个问题,希望早点修复

**Comment by zhaoqinghao** [comment]
可以暂时在代码中自己进行纠正
点击时
offsetBar(index) {
      // 修正选中
      try {
        let barRect = document.getElementsByClassName('bar-tab')[0].getBoundingClientRect()
        let itemRect = document.getElementsByClassName('vux-tab-item')[index].getBoundingClientRect()
        let barWidth = barRect.width
        let itemWr = barWidth / itemRect.width
        let vuxInkBar = document.getElementsByClassName('vux-tab-ink-bar')[0]
        let lt = index * (100 / itemWr) + '%'
        let rt = (itemWr - index - 1) * (100 / itemWr) + '%'
        vuxInkBar.style.left = lt
        vuxInkBar.style.right = rt
      } catch (e) {
      }
    }

**Comment by mzcc666GtHb** [comment]
@on-item-click 在这里面调用这个方法吗？ 但是你这个有问题
let colet barRect = document.getElementsByClassName('bar-tab')[0].getBoundingClientRect()

**Comment by zhaoqinghao** [comment]
> @on-item-click 在这里面调用这个方法吗？ 但是你这个有问题
> let colet barRect = document.getElementsByClassName('bar-tab')[0].getBoundingClientRect()
从新看下

**Comment by iijx** [comment]
第一句的class名写错了吧！应该是：
let barRect = document.getElementsByClassName('vux-tab')[0].getBoundingClientRect()
