### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('[object Object]') contains HTML space characters, which are not valid in tokens.

### ISSUE THREAD

**Issue by zjhr** [airyland/vux#309]
![1](https://cloud.githubusercontent.com/assets/16950097/16402593/eee67e1c-3d1f-11e6-9904-98a7fb6a8126.png)
![3](https://cloud.githubusercontent.com/assets/16950097/16402662/6a0945c0-3d20-11e6-8837-73c50ca041e8.png)
![2](https://cloud.githubusercontent.com/assets/16950097/16402664/70154702-3d20-11e6-970c-93f5aae6a3e6.png)

大大，求助，本来想用一下vux学习一下用法的，学学人家的demo写一个注册和登录的，可是开始遇到问题了，昨天6点遇到，我就弄了9点都没解决，我引用了4个组件，Group，Box，xButton，xInput，后来
发现一直报图上面那个错，然后我一直找原因，发现注释掉”x-button“和”x-input“那些html后，就没那种错误了，这是怎么回事呢？感觉有不像vux的问题，错误好像报的是路由。。。不过有点无语

**Comment by airyland** [comment]
Vue和Vue-router版本多少

**Comment by zjhr** [comment]
"vue": "^1.0.17",
"vue-router": "^0.7.11"

**Comment by airyland** [comment]
Vue更新到最新试试

**Comment by zjhr** [comment]
好的，我去试一下

**Comment by zjhr** [comment]
无语。。居然真的是版本问题，谢谢airyland大大鼎力相助(*^__^*)
