### ISSUE TITLE
[Bug Report] Swiper 手机翻转方向后 高度不会根据宽高比自动调整。

### ISSUE THREAD

**Issue by li-zhe** [airyland/vux#3093]
### VUX version
2.9.2

### OS/Browsers version
android/华为自带浏览器 10.8.7.4733

### Vue version
2.5.17

### Code

```html
 <swiper auto style="padding: .375rem .75rem;" :loop="true" :aspect-ratio="300/800"  dots-class="custom-bottom" dots-position="center" >
        <swiper-item v-for="(item, index) in carousels" :key="index"><img :src="fullPath(item.cover)"></swiper-item>
</swiper>
```

### Steps to reproduce
手机打开自动旋转功能  
浏览器打开对应页面   
90°旋转手机

### What is Expected?
swiper 的高度可以随着屏幕旋转，根据设置的宽高比 自适应

### What is actually happening?
swiper 的高度 不会随着屏幕旋转而改变。

**Comment by chengjs** [comment]
你可以使用前端meta强制不让翻转啊。swiper是计算了，不是你想这个能够跟着变就变。你可以监听下window。重新渲染下数据，应该会好

**Comment by Jiiiiiin** [comment]
肯定需要捕获时机手动渲染呀乾杯 []~（￣▽￣）~*

**Comment by caozhong1996** [comment]
目前人手精力不够，帮助当前使用者解决bug更为重要，由于时间过去太久，暂时关闭此issue，还需要帮助的话请重开issue，谢谢🙏
