### ISSUE TITLE
[Feature Request] 请问loading组件有没有类似element UI 中loading组件的service方式调用

### ISSUE THREAD

**Issue by Reyfang** [airyland/vux#3095]
### Existing Component
是

### Component Name
Loading

### Description
请问loading组件有没有类似element UI 中loading组件的service方式调用，就是类似于下方代码调用方式：

import  { Loading } from 'vux'

Loading.service({
  show: true
});

Loading.hide();

**Comment by greedying** [comment]
支持。具体见文档

**Comment by Sapphire2k** [comment]
https://doc.vux.li/zh-CN/components/loading.html

![image](https://user-images.githubusercontent.com/17328005/45272058-9f688780-b4dd-11e8-9f0a-4471b9766de2.png)
