### ISSUE TITLE
ie11以下浏览器报错。。

### ISSUE THREAD

**Issue by peirancao** [airyland/vux#31]
用的 webpack ie11浏览器以下版本报语法错误

`/***/ },
/* 11 */
/***/ function(module, exports, __webpack_require__) {

	eval("!function(e,t){ true?module.exports=t():\"function\"==typeof define&&define.amd?define([],t):\"object\"==typeof exports?exports.vux=t():e.vux=t()}`

**Comment by airyland** [comment]
你说的是PC端么，vux不考虑PC兼容性哦

**Comment by peirancao** [comment]
嗯 知道的 我只是顺手给你提了个issues 习惯了 看到 bug 就来了。。

**Comment by peirancao** [comment]
本来就没打算在pc端用它 :)

**Comment by airyland** [comment]
@peirancao Hi，我用ie11没有重现，具体是怎么操作的呢？

**Comment by peirancao** [comment]
ie10
