### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by zjhr** [airyland/vux#310]
![1](https://cloud.githubusercontent.com/assets/16950097/16405578/4be17dc2-3d3b-11e6-9e86-95bc8d0958fc.png)
![2](https://cloud.githubusercontent.com/assets/16950097/16405597/7a32e986-3d3b-11e6-8f4f-e3c7a4120922.png)
@airyland 大大，又是我。。。今天你说的那个更新了vue后，xbutton确实可以了，可是xinput引用后就报错，错误和之前不同，好像是那个import uuidMixin from './mixin_uuid'出了问题，一开始以为是bebal问题，后来更新到最新也是不行

**Comment by airyland** [comment]
在webpack配置中添加babel loader

https://vuxjs.gitbooks.io/vux/content/install/vue.html

**Comment by zjhr** [comment]
好的，我试一下

**Comment by zjhr** [comment]
可以了，谢谢airyland(*^__^*) ，问个题外话，你是广州哪里的？招不招前端？

**Comment by airyland** [comment]
:smile: 信息港。后面可能会有计划，你可以先发份简历给我。

**Comment by zjhr** [comment]
好啊，我先了解一下(*^__^*)

**Comment by zjhr** [comment]
是科韵路那里？

**Comment by airyland** [comment]
yes

**Comment by zjhr** [comment]
不错啊，去那里向您拜师学艺(*^__^*) ，等我抽空完成一下简历先，再投给你，话说你们那边有多少前端的？有没有团队？在这了说这些应该没问题吧。。。

**Comment by airyland** [comment]
等我们招人时再具体聊。

**Comment by zjhr** [comment]
好啊，airyland大大有没有qq啊，想加你一下

**Comment by airyland** [comment]
用这个 https://vux.bearychat.com
