### ISSUE TITLE
[Bug Report] 脚手架程序配合ngrok访问特别慢

### ISSUE THREAD

**Issue by maxzhou0** [airyland/vux#3103]
### VUX version
2.9.2

### OS/Browsers version
windows7 64 chrome 68

### Vue version
2.5.17

### Code

```html
发现用localhost和ngrok访问有区别，ngrok每次访问会多出一个app.js?_txxx 的文件下载，有600多k，导致页面加载很慢，有办法解决吗？
```

### Steps to reproduce
访问
http://939d8e87.ngrok.io/#/

### What is Expected?
和localhost一样，不要加载另外的app.js文件

### What is actually happening?
加载了

**Comment by Jiiiiiin** [comment]
真是什么都干文呀乾杯 []~（￣▽￣）~*
