### ISSUE TITLE
[Bug Report] vscode Debugger for Chrome 插件无法正确打断点调试vue文件中的代码

### ISSUE THREAD

**Issue by looyo** [airyland/vux#3109]
### VUX version
2.9.2

### OS/Browsers version
win10/chrome  69.0.3497.92（正式版本） （64 位）

### Vue version
2.5.2

### Code

```html
任务代码按重新步骤都可以复现问题
```

### Steps to reproduce
1、使用如下步骤开始一个vux工程
npm install vue-cli -g # 如果还没安装
vue init airyland/vux2 projectPath

cd projectPath
npm install --registry=https://registry.npm.taobao.org # 或者 cnpm install 或者  yarn
npm run dev #  或者  yarn dev
2、设置工程参数
.vscode/launch.json 内容如下：
{

    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8088/hotel",
            "webRoot": "${workspaceFolder}"  // 改为${workspaceFolder}/src  跟踪不上任何断点
        }
    ]
}

config/index.js 中的部分配置如下
 devtool: 'eval-source-map', // 换成 source-map 也不行
    cacheBusting: false,
    cssSourceMap: true

3、创建一个vue文件 ，设置断点，执行npm run dev 启动服务
4、使用vscode 中的插件lanch到chrome 浏览器，vscode中脚本执行停留的地方不是预先设置好的断点位置。

### What is Expected?
能得到回答：是否vux不支持这种模式的调试

### What is actually happening?
目前我找遍了vue工程在 vscode debugger for chrome 模式下的调试参数设置的方法 都不奏效。而那些方法在我的vue工程中是奏效的。

**Comment by stalkercn** [comment]
vscode的问题可以去vscode那里发issue  vux项目中并不包含调试器

**Comment by looyo** [comment]
> vscode的问题可以去vscode那里发issue vux项目中并不包含调试器

你这个是vux 官方给我回复吗？我还并不认为你给出的建议有指导价值。

我只是想在这边和有同样使用vux方式的朋友探讨一下这个问题。
事实上类似问题并非我一个人遇到。 类似问题 在  https://github.com/airyland/vux/issues/2813

**Comment by caozhong1996** [comment]
目前人手精力不够，帮助当前使用者解决bug更为重要，由于时间过去太久，暂时关闭此issue，如果有解决方案也欢迎pr，还需要帮助的话请重开issue，谢谢🙏
