### ISSUE TITLE
Address和Tabbar冲突

### ISSUE THREAD

**Issue by moxuandeng** [airyland/vux#311]
### Version
0.1.1-rc3
### Android or iOS, which browser?
iOS
### Your Codes 

``` html
<body>
  <div id=app, class=h100>
    <div class="weui_tab">
      <div class="weui_tab_bd">
        <group>
          <cell></cell>
          ...
          <cell></cell>
        </group>
        <group>
          <address></address>
    </group>
      </div>
      <TABBAR>
    </div>
  </div>
</body>
```
![img_3899](https://cloud.githubusercontent.com/assets/9334080/16407288/8e7027ce-3d45-11e6-9756-77fee3d83450.PNG)

如上代码, 地址选择器无法正常使用, 会被遮罩层挡住. 不加tabbar的话就没啥问题

**Comment by airyland** [comment]
tabbar不应该会影响popup。你修改了popup的z-index? 遮罩z-index是100， popup是101，怎么还会被挡住？

**Comment by LiangFuzhi** [comment]
发样式看看

**Comment by moxuandeng** [comment]
没有添加过自定义样式, 试过在Chrome和几个Android中能正常显示

**Comment by airyland** [comment]
在本地测试了下，确实在iPhone有问题，在Chrome模拟器上是正常的。

**Comment by airyland** [comment]
问题应该是`.weui_tab_bd`上的样式 `-webkit-overflow-scrolling: touch;` 导致的
https://benfrain.com/z-index-stacking-contexts-experimental-css-and-ios-safari/

去掉会正常，但是滚动会很不流畅。那么可能只能这样处理，popup弹出时，将`-webkit-overflow-scrolling`设置为`auto`，关闭时更改回来。具体怎么处理得再考虑一下。

**Comment by LiangFuzhi** [comment]
这个我也发现有这个问题，所以在页面全部不用overflow

**Comment by airyland** [comment]
@LiangFuzhi  跟上次你提的 #296 是同个问题？

**Comment by LiangFuzhi** [comment]
目测是，在iOS用了元素内滚动会导致元素内绝对位置失效，之前那个我是动态修改样式的，发了一个兼容代码的

**Comment by airyland** [comment]
现在的处理方法是添加一个预定义的类名 `vux-fix-safari-overflow-scrolling`
`<div class="weui_tab_bd vux-fix-safari-overflow-scrolling">`

**Comment by linhaobin** [comment]
点击遮罩关闭时会将-webkit-overflow-scrolling设置为touch，如果点取消或完成没有设置为touch

**Comment by airyland** [comment]
@linhaobin 明天小版本解决。

**Comment by zht110227** [comment]
如果-webkit-overflow-scrolling样式的div，例如viewBox组件，里面是个滚动列表，还包含一个fixed的元素，滚动列表的时候，safari浏览器会出现问题，下半截出现空白，同时fixed的元素被覆盖。
