### ISSUE TITLE
[Feature Request] 关于校验功能的期待

### ISSUE THREAD

**Issue by looyo** [airyland/vux#3110]
### Existing Component
否

### Component Name
Calendar  PopupPicker  XInput

### Description
我现在用vux 2.9.2 开发一些简单的移动端页面。关于各种输入组件的校验特性不知道是否有计划？
Xinput虽然支持 is-type，并且用户可以自定义，但是验证行为似乎只能焦点离开组件时发生。
我觉得验证功能至少需要支持如下几点：
1、每个组件验证可以通过方法由开发者在适当的时候触发。
2、form提交的时候，也可以批量对form中所有组件进行验证。
3、验证不通过，可以通过红色！来提醒用户，用户点击红色！可以看到详情
4、象 Calendar  PopupPicker （目前我只用了这么几种）  以及其他组件都应该支持校验。
5、组件默认提供的校验规则至少包含是否必填，长度要求。还需要支持用户自定义的校验实现，并且这种自定义的校验还可以依赖远端来实现的。

**Comment by Jkarel** [comment]
很期待，比如cell值的验证。 适用于弹出页面选择数据后回填模型的场景。 一个表单不可能只有x-input 各种类型的输入都需要统一验证，

**Comment by adophp** [comment]
期待

**Comment by caozhong1996** [comment]
see #3782
