### ISSUE TITLE
[Bug Report] x-input在2.9.2版本中重新赋值null时会报错

### ISSUE THREAD

**Issue by 877080915** [airyland/vux#3111]
### VUX version
2.9.2

### OS/Browsers version
Windows 10 /  chrome 69.0.3497.92（正式版本） （64 位）

### Vue version
2.5.17

### Code

```html
<x-input placeholder="输入" v-model="vinNo"></x-input>
```

### Steps to reproduce
在挂载函数mounted() 中重新为vinNo赋值为null，此时页面会即会抛出异常。因数据是绑定行为，所以数据库返回数据难免会存在返回null情况。从而导致很多页面抛异常。
例如：
data() {
    return {
        vinNo: ""
    }
},
mounted() {
    this.vinNo = null;//重新赋值null
},
异常：
[Vue warn]: Error in callback for watcher "currentValue": "TypeError: Cannot read property 'length' of null"

found in

---> <XInput> at F:\l…………等

### What is Expected?
赋值null时不抛异常，能像2.9.0版本一样可以正常显示空值

### What is actually happening?
抛有异常：
[Vue warn]: Error in callback for watcher "currentValue": "TypeError: Cannot read property 'length' of null"

found in

---> <XInput> at F:\l…………等

**Comment by gendseo** [comment]
如果换成 this.vinNo = '' 能不能行呢

**Comment by gendseo** [comment]
我的想法很简单， 如果是 x-input 组件，那么他是会监听 length 的，传一个空对象肯定会报错了

**Comment by 877080915** [comment]
换成this.vinNo = ''可以，但是这样数据库的数据是不固定的，需要处理的方式就很不科学，而且2.9.2之前的版本就可以接受null值，不报错。

**Comment by 877080915** [comment]
而且查询三方接口，其他网站的接口就无法处理到。接口量大的话就非常不科学。

**Comment by lwm98** [comment]
+1
