### ISSUE TITLE
x-input,type=number在华为手机畅玩5A上获取到的是string类型

### ISSUE THREAD

**Issue by easy868** [airyland/vux#3119]
<x-input placeholder="输入折扣，例：8折输入0.8" type="number" :debounce="500" v-model="discount" @on-blur="discountBlur">
            <span class="text-gray" slot="label">折扣：</span>
          </x-input>
   discountBlur() {
        this.$vux.toast.text(typeof this.discount)
      }
弹出string；
EMUI 4.1.3，安卓6.0

**Comment by pititkai** [comment]
你输入数据，也是获取空字符串吧？

**Comment by alterhu2020** [comment]
这是个千年老bug了，https://github.com/airyland/vux/pull/3084
