### ISSUE TITLE
querystring warning

### ISSUE THREAD

**Issue by MAOBI63** [airyland/vux#3120]
# @vue/cli V3

 WARNING  Compiled with 2 warnings                                                                                                                                                                                14:47:58

 warning  in ./node_modules/vux/src/plugins/locale/index.js

"export 'default' (imported as 'querystring') was not found in '../../tools/querystring'

 warning  in ./node_modules/vux/index.js

"export 'default' (reexported as 'querystring') was not found in './src/tools/querystring/index.js'

**Comment by Haixing-Hu** [comment]
same error, any solution?
