### ISSUE TITLE
用vux ios会卡屏整个页面都不能动，有解决方法吗？

### ISSUE THREAD

**Issue by 110pkl** [airyland/vux#3121]
问题：用vux单页面应用 在 ios 微信浏览器上有时整个页面会卡住不能滑动，求解决方案

**Comment by 110pkl** [comment]
![295624728178788042](https://user-images.githubusercontent.com/15032385/45811908-f3a31100-bd00-11e8-9e9d-0d75548e7983.jpg)

**Comment by caozhong1996** [comment]
时间太久，如果还需要帮助请重开issue
