### ISSUE TITLE
无法找到export错误

### ISSUE THREAD

**Issue by dylanLii** [airyland/vux#3128]
无法在main.js import vux插件
如 import { AlertPlugin } from 'vux';
vue.use(AlertPlugin )
会报 exports is not defined 
在这个文件node_modules/vux/src/tools/querystring/index.js

**Comment by dylanLii** [comment]
在配置vue-cli3.0
中出错的

**Comment by nan1010082085** [comment]
vux\index.js  所有含有tools路径全部注掉，工具函数自写 就不会报错了。 
亲测

**Comment by nan1010082085** [comment]
注掉以下两个抛出。 就能正常在cli3使用
// import LocalePlugin from './src/plugins/locale/index.js'
export {
 // LocalePlugin,
}
如果不行 请找到node_modules\vue\src\plugins\locale
注掉 // import querystring from '../../tools/querystring'
      // search query, then cookie, then defaultLocal, then navigator
      // const queryRs = querystring.parse()
      // if (queryRs.locale) {
      //   return queryRs.locale
      // }

**Comment by alterhu2020** [comment]
测试发现可以只注释以下六行代码即可(都是在node_modules/vux/index.js文件中)解决Vue Cli3遇到的问题:
```
// import querystring from './src/tools/querystring/index.js'
// import LocalePlugin from './src/plugins/locale/index.js'
// import Range from './src/components/range/index.vue'
export {
 // LocalePlugin,
// querystring,
 // Range,
}
```

**Comment by hwbrzzl** [comment]
> 测试发现可以只注释以下六行代码即可(都是在node_modules/vux/index.js文件中)解决Vue Cli3遇到的问题:
> 
> ```
> // import querystring from './src/tools/querystring/index.js'
> // import LocalePlugin from './src/plugins/locale/index.js'
> // import Range from './src/components/range/index.vue'
> export {
>  // LocalePlugin,
> // querystring,
>  // Range,
> }
> ```

亲测有效，thanks！

**Comment by ouzhenlin** [comment]
亲测注释可以用，但是会提示 index.js?366f:3 VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。 

这有关系吗
