### ISSUE TITLE
switch in firefox...

### ISSUE THREAD

**Issue by musicformellons** [airyland/vux#313]
### Version
0.1.1
### Android or iOS, which browser?
Firefox, mmmh, seems not supported...?! Any suggestions how to solve this would be appreciated though.

### Your Codes 
When running the switch demo I do not get the switch image, but a html checkmark, see attached image.

### Expected behavior and actual behavior.
Expected: normal switch.
Actual: html checkmark.

### Steps to reproduce the problem
Run switch demo in firefox.
![screenshot from 2016-06-29 14-16-09](https://cloud.githubusercontent.com/assets/10334123/16451705/ea09eccc-3e04-11e6-8f0b-fedb70a0af96.png)

**Comment by airyland** [comment]
Sorry to tell you Vux currently does not support Firefox because few people use it.

**Comment by musicformellons** [comment]
Thanks for your swift reply. Firefox covers 16%...:
http://www.w3schools.com/browsers/browsers_stats.asp

Any idea what could be causing the issue?

**Comment by lichunqiang** [comment]
https://github.com/weui/weui/issues/392

**Comment by airyland** [comment]
Few pepole use Firefox on mobile in China actually...

**Comment by musicformellons** [comment]
Yes, which means the % is even higher outside of China!  

So it is a weui issue. Thanks.

**Comment by lichunqiang** [comment]
so we are sorry for this. 

Closed the issue, If you have any other problem, we are so happy to make a  discussion together

**Comment by musicformellons** [comment]
Cool, thanks.

**Comment by graysheeep** [comment]
@airyland I am firefox user..

**Comment by airyland** [comment]
@graysheeep PC & Mobile?
