### ISSUE TITLE
打包一直报错

### ISSUE THREAD

**Issue by franklin-repo** [airyland/vux#3134]
开发环境能正常使用，打包就报错

ERROR in static/js/app.6cd93c79519d3be930fd.js from UglifyJs
Unexpected token: punc (() [./~/vux/src/components/cell/index.vue:50,2][static/js/app.6cd93c79519d3be930fd.js:774,9]

"vux": "^2.5.7"
"vux-loader": "^1.1.5",

ERROR in static/js/app.6cd93c79519d3be930fd.js from UglifyJs
Unexpected token: punc (() [./~/vux/src/components/cell/index.vue:50,2][static/js/app.6cd93c79519d3be930fd.js:774,9]

ERROR in static/js/vendor.80ba961390ca194880fb.js from UglifyJs
Invalid assignment [./~/vux/src/libs/clean-style.js:1,15][static/js/vendor.80ba961390ca194880fb.js:568,71]

**Comment by caozhong1996** [comment]
时间太久，如果还需要帮助请重开issue
