### ISSUE TITLE
看到 x-number组件源码中有reset focus blur等方法这些如何使用啊

### ISSUE THREAD

**Issue by zoeblow** [airyland/vux#3145]
看到 源码中有reset focus blur 等方法这些如何使用啊

`
reset (value = '') {
      this.dirty = false
      this.currentValue = value
      this.firstError = ''
      this.valid = true
    },
focus () {
      this.$refs.input.focus()
    },
    blur () {
      this.$refs.input.blur()
    },
`

**Comment by caozhong1996** [comment]
目前人手精力不够，帮助当前使用者解决bug更为重要，由于时间过去太久，暂时关闭此issue，还需要帮助的话请重开issue，谢谢🙏
