### ISSUE TITLE
[Feature Request] 【需求】请问有计划出一个小程序版本的VUX吗？

### ISSUE THREAD

**Issue by zhaohuwei** [airyland/vux#3152]
### Existing Component
否

### Component Name
VUX for MP

### Description
vux是基于weui开发的，并且规范十分符合小程序的风格。所以希望出一个支持小程序版的vux，包括但不限于微信小程序，支付宝小程序。
估计您的时间比较紧张，单独开发小程序版本的vux不太现实。
所以这里建议，能否由您牵头，开一个小程序版的vux项目，由我们广大用户来完成”web版==》小程序版“的迁移与适配工作，感谢！

**Comment by Yvan0329** [comment]
支持

**Comment by caozhong1996** [comment]
后续有如此打算，感兴趣的话可以保持关注或者直接参与，谢谢
