### ISSUE TITLE
[Bug Report] 请教在umd模式下使用,按组件JS引用报错,而引用所有的JS不报错

### ISSUE THREAD

**Issue by cejpo001** [airyland/vux#3157]
### VUX version
2.9.2

### OS/Browsers version
win7

### Vue version
2.5.17

### Code

```html
官方实例<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>scripts</title>
  <link rel="stylesheet" href="../dist/vux.min.css">
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
</head>
<body>
  <div id="demo">
    <group>
      <cell title="Vue" :value="how"></cell>
    </group>
  </div>

  <script src="../dist/components/group/index.js"></script>
  <script src="../dist/components/cell/index.js"></script>

  <script>
  Vue.component('group', vuxGroup)
  Vue.component('cell', vuxCell)
  new Vue({
    el: '#demo',
    data: {
      how: 'Cool'
    }
  })
  </script>
</body>
</html>
```

### Steps to reproduce
报错信息vue.js:597 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Vcell>
       <Root>

### What is Expected?
报错信息vue.js:597 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Vcell>
       <Root>

### What is actually happening?
报错信息vue.js:597 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Vcell>
       <Root>

**Comment by cejpo001** [comment]
补充下说明: VUX的组件丰富,也很漂亮,所以想在现有的项目上使用这些组件,因为现在的项目是C# MVC模式开发的,使用webpack的话,就要把现有项目全改成webapi的形式,改成较大,所以就只想引用组件的JS,现在按照https://doc.vux.li/zh-CN/install/umd.html生成和使用,上面的例子都是报 [Vue warn]: Failed to mount component: template or render function not defined.错误,不知道如何解决?,请指导..谢谢

**Comment by fjarcticfox** [comment]
同样报错。

**Comment by anyunfei** [comment]
我把vue.js改成引用vue.min.js  不报错了  但是引用的组件也显示出不来~~
