### ISSUE TITLE
请问什么时候可以支持webpack4.0

### ISSUE THREAD

**Issue by yorsal** [airyland/vux#3161]

**Comment by zzc5464** [comment]
现在导入还是有些问题，我这边是降级处理。。
"vue": "^2.5.17",
    "vue-loader": "^14.2.2",
    "vue-router": "^3.0.1",
    "vue-template-compiler": "^2.5.17",
    "vux-loader": "^1.2.9",
    "webpack": "^4.21.0",
    "webpack-cli": "^3.1.2",

**Comment by liuxfu** [comment]
同问

**Comment by Lynn-cc** [comment]
正准备用来着，看到文档没有写，过来一查，居然还没支持？？so？？？

**Comment by dailijian** [comment]
已经在迁移组件库，很久没更新了

**Comment by dailijian** [comment]
我这周升级到 webpack4

**Comment by devbian** [comment]
> 我这周升级到 webpack4

迁移到哪个组件库了？

**Comment by caozhong1996** [comment]
see #3778
