### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by hjh1126123** [airyland/vux#3163]
> ../tools/querystring

```
var QueryString = exports;
```
> error ::  exports is not defined.

> 该怎么办呢?

> 环境: cli 3.x

**Comment by karidyang** [comment]
参见 https://github.com/airyland/vux/issues/3128

**Comment by hjh1126123** [comment]
@karidyang 感谢

**Comment by caozhong1996** [comment]
这个问题应该已经修复，还需要帮助请重开issue，谢谢
