### ISSUE TITLE
tab 安卓机切换，红条残留

### ISSUE THREAD

**Issue by ColdXu** [airyland/vux#318]
### Version
0.1.1版本
### Android or iOS, which browser?
Android
### Your Codes 

``` html
<!--put your code here-->
```

### Steps to reproduce the problem
![img](http://url.hoop8.com/pRB)
tab组件在安卓机，动画切换后红条会残留在一侧。

**Comment by airyland** [comment]
机型？ 在几台Android机上都没发现问题。

**Comment by ColdXu** [comment]
华为机型，但其他安卓机是可以的，最后把动画关了

**Comment by airyland** [comment]
所以是动画导致的？手头没有这个机型，如果你能调试下问题发个PR最好了 :smile:

**Comment by unclay** [comment]
具体是华为什么机型，  我看看这边有没有  @airyland  Android or iOS, which browser?  这个可以要求详细点：ios or android，系统型号，浏览器类型，浏览器型号

**Comment by airyland** [comment]
@unclay ok。我刚找到一个比较新的华为，测试是没有问题的。

**Comment by airyland** [comment]
没有更多信息，无法定位问题，关闭了。

**Comment by caojiahui123** [comment]
你好，您的这个问题在ios 从uiwebview切换到wkwebview，出现了您发布的这个问题，我这边调试是屏蔽了tab切换时的动画，就好了，如果不修改前端代码，ios内部处理，您这边有什么好的解决方法吗？
