### ISSUE TITLE
[Bug Report] x-input组件onfocus时组件销毁抛错

### ISSUE THREAD

**Issue by DanielZongZZ** [airyland/vux#3183]
### VUX version
2.9.2

### OS/Browsers version
win10

### Vue version
2.5.17

### Code

```html
focusHandler ($event) {
      this.$emit('on-focus', this.currentValue, $event)
      this.isFocus = true
      // this.scrollIntoView(500)
      // this.scrollIntoView(5000)
      setTimeout(() => {
        this.$refs.input.scrollIntoViewIfNeeded(false)
        // this.$refs.input.scrollIntoViewIfNeeded()
      }, 1000)
      // $event.target.
    },
```

### Steps to reproduce
我在onfocus事件中跳转了路由导致x-input销毁，x-input内部onfocus定时器无法获取x-input的dom导致scrollIntoViewIfNeeded上下文对象undefined

### What is Expected?
if ( this.$refs.input) {
  this.$refs.input.scrollIntoViewIfNeeded(false)
}

### What is actually happening?
 this.$refs.input.scrollIntoViewIfNeeded(false)

**Comment by liujun5230** [comment]
我也遇到了这个问题，具体表现为：

点击x-input组件（此时触发了x-input组件的onfocus事件），在x-input获得焦点1000毫秒以内，跳转路由，则会出现这个错误。x-input获得焦点1000毫秒以后再跳，则不会有这个错误。

实在没办法了，最后解决的办法是：
把focusHandler 方法里的setTimeout的延迟时间从1000改成100了。。。
