### ISSUE TITLE
我遇到一个问题 就是 x-input v-model值 ios可以拿到 安卓就获取不到 什么原因呢

### ISSUE THREAD

**Issue by sniper52237** [airyland/vux#3186]
我也是，什么情况  type=email时， android下 v-model竟然没有拿到值？请问解决了吗

**Comment by David2k13** [comment]
我的是type-number拿不到值

**Comment by sniper52237** [comment]
> 我的是type-number拿不到值
嗯  type-number也拿不到

**Comment by caozhong1996** [comment]
这个问题应该已经修复，还需要帮助请重开issue，谢谢
