### ISSUE TITLE
x-input点好几次才能进入编辑状态，捕获到焦点，

### ISSUE THREAD

**Issue by Chenberg** [airyland/vux#3188]
### VUX version
2.9.2

### OS/Browsers version
所有

### Vue version
2.5.17

### Code

```html
<group class="group-psw">
          <x-input title="" placeholder="请输入8-20位密码" v-model="pass" type="password">
            <i slot="label" class="fa fa-unlock-alt" aria-hidden="true"></i>
          </x-input>
        </group>
```

### Steps to reproduce
x-input点击不到焦点，需要点击前面的label才能捕获，点击输入区不起作用，我们应用中输入框前面不加title的，只是在框里用placeholder提示输入，现在的问题就是很难点击到

### What is Expected?
点击输入框的任何部分都可以捕获到焦点

### What is actually happening?
点击输入框捕获不到焦点，到处乱点才能点到

**Comment by gouflv** [comment]
应该是和 FastClick.js 有冲突

**Comment by rujptw** [comment]
> 应该是和 FastClick.js 有冲突

是不是class加上needClick,去除就可以了呢

**Comment by rujptw** [comment]
我也遇到这个问题，给x-input 加上needsclick类名即可，gouflv ，谢了

**Comment by yuxianwen** [comment]
加  needsclick 没用的  要改fastclick 插件 

参考这个commit 

[https://github.com/betterTry/fastclick/commit/342a6641500c40b7167ef7f21439d29fc6e21263](https://github.com/betterTry/fastclick/commit/342a6641500c40b7167ef7f21439d29fc6e21263)

**Comment by caozhong1996** [comment]
目前不推荐使用fastclik了，坑太多，禁用用户缩放即可达到fastclick的效果
