### ISSUE TITLE
Address IOS下灰色背景遮住选择器

### ISSUE THREAD

**Issue by ColdXu** [airyland/vux#319]
### Version
0.1.1版本
### Android or iOS, which browser?
IOS
### Your Codes 

``` html
<!--put your code here-->
```

### Steps to reproduce the problem
Address IOS下灰色背景遮住选择器，无法进行选择。

**Comment by airyland** [comment]
麻烦补充完整信息。是否使用了100%body高度的布局？

**Comment by lichunqiang** [comment]
https://github.com/airyland/vux/issues/311 是不是这个问题？

**Comment by LiangFuzhi** [comment]
ios这个问题好麻烦，要写一堆兼容，最好的办法就是把地址选择生成在<router-view></router-view>下一级或者body下一级

**Comment by airyland** [comment]
这个不需要一堆兼容呀，下个版本的处理方法是就是加个一个类名就ok了。

**Comment by LiangFuzhi** [comment]
这个css类写了什么？

**Comment by airyland** [comment]
@LiangFuzhi  https://github.com/airyland/vux/commit/ae5530a6f8917219f793eb6bd0c5ba0f28e52343

**Comment by unclay** [comment]
感觉这个问题应该改个层级就行了吧

**Comment by airyland** [comment]
不，层级在scrolling-overflow:touch 下是失效的。

**Comment by ColdXu** [comment]
感谢个位，你们提供的方法我都在试

**Comment by ColdXu** [comment]
是层级问题，把组件提上来一层就可以了

**Comment by airyland** [comment]
你这问题和另一个问题估计还真不是同一个问题，基本没有细节。

**Comment by hldzlk** [comment]
遇到相同问题,如下结构会出现问题    这边直接把阴影<a>放上去了
```
<body>
  <ul>
    ...地址列表
  </ul>
  <div style="position:fixed">
    <address></address>
  </div>
  <a class="picker-mask show" href="javascript:void(0)"></a>
</body>
```

**Comment by airyland** [comment]
@hldzlk 为何要为address加上一层fixed div?

**Comment by hldzlk** [comment]
### 因为这样子：
这个是地址列表页   
我直接把   （添加/编辑地址功能）  放在这个页面了
在地址列表点其中一个地址编辑    直接弹出这个fixed div 来编辑地址
不加fixed  用absolute    列表太长超出1屏幕  fixed div的一部分就会在屏幕外
### 暂时用的处理方式：
我这种情况改&lt;address&gt;  好像不是很方便
还是用absolute  编辑页出来时  用v-if把地址列表去掉,防止超出1屏
(若遇到相同情况，项目急着上，可以参考下)
### 追加问题:
地址编辑页做成新页面  大家页面间怎么传数据的  url？  localstorage,sessionstorage？  redux这类数据框架？  vue有自己的方式么？

**Comment by airyland** [comment]
@hldzlk Vuex
