### ISSUE TITLE
[Bug Report] DateTime组件对中文日期格式支持有问题

### ISSUE THREAD

**Issue by SukiSama01** [airyland/vux#3195]
### VUX version
2.9.2

### OS/Browsers version
Win10

### Vue version
2.5.17

### Code

```html
<datetime title="时间" format="YYYY年MM月" ></datetime>
```

### Steps to reproduce
打开日期控件，选中一个日期，比如“2018年08月”（此时控件显示2018年08月）；
再次打开日期控件，没有选中刚刚选择的“2018年08月”，而且选中了默认日期。
备注：util.js中parseDate 方法不支持中文格式的处理。同时，这个方法中的短横线“-”在ios下可能引起bug。

### What is Expected?
选中的“2018年08月”

### What is actually happening?
选中的“2018年10月”（即当前日期）

**Comment by Sapphire2k** [comment]
@SukiSama01 如果只是显示需要的话可以使用[`display-format`](https://doc.vux.li/zh-CN/components/datetime.html)
