### ISSUE TITLE
vue-cli3.0引入vux报错

### ISSUE THREAD

**Issue by git-ysz** [airyland/vux#3197]
在我用vue3.0脚手架的项目中，如果在main.js中import {……} from "vux"控制台会报错，在vscode中会提示我找不到该模块。但是我在.vue文件的里面引入则不会，可以正常使用。vue-loader我已经降到14了，请问有和我碰到相同问题的么？求指教！谢谢！

**Comment by git-ysz** [comment]
找到原因了！谢谢

**Comment by fieai** [comment]
老哥,我也碰到这个问题了,你是怎么解决的

**Comment by lonlie** [comment]
@git-ysz ，求解啊！

**Comment by zhengmiaohua** [comment]
这个逼，找到原因也不说哈

**Comment by git-ysz** [comment]
![image](https://user-images.githubusercontent.com/31951432/49264710-57c51c80-f48a-11e8-8fba-2bea11a24f9f.png)

**Comment by git-ysz** [comment]
想要在vue3.0+，js文件里引用vux需要按照图示的方式引入。 @zhengmiaohua

**Comment by git-ysz** [comment]
@zhengmiaohua 为什么别人有问题会虚心给我发邮件请教，你却邮件骂我？

**Comment by zjun2** [comment]
哈哈哈 楼上真逗。。。。
https://segmentfault.com/a/1190000014586699
解决办法:
yarn add vue-loader@14.2.2 -D
or
npm install vue-loader@14.2.2 -D
不要客气。虽然能运行了 但是会有一堆的警告，并且前台会有一个提示说vue-loader没生效，导致第一次加载会加载所有vux的组件
