### ISSUE TITLE
[Bug Report] vue cli3 配合vux使用,以plugin形式调用时会报exports is not defined

### ISSUE THREAD

**Issue by fieai** [airyland/vux#3200]
### VUX version
2.9.2

### OS/Browsers version
chrome

### Vue version
2.5.17

### Code

```html
import Vue from 'vue'
import  { ToastPlugin } from 'vux'
Vue.use(ToastPlugin)
```

### Steps to reproduce
我在封装axios时,需要加一个loading动画,用到Toast组件,然后import进去就会报这个 exports is not defined

### What is Expected?
希望有解决方法

### What is actually happening?
现在还没解决这个问题

**Comment by ouzhenlin** [comment]
我也是这样的问题，你解决了吗

**Comment by fieai** [comment]
还没解决
