### ISSUE TITLE
x-header的小问题

### ISSUE THREAD

**Issue by linyunchow** [airyland/vux#3209]
<x-header  left-options.showBack=false></x-header> 这样操作为什么达不到想要的效果 title 就可以设置 是什么原因呢

**Comment by linyunchow** [comment]
<x-header left-options.showBack=false></x-header>

**Comment by linyunchow** [comment]
左括号x-header  left-options.showBack=false  右括号 左括号/x-header右括号

**Comment by Sapphire2k** [comment]
@linyunchow 你说的应该是这个？

`<x-header :left-options="{showBack: false}"></x-header>`

**Comment by caozhong1996** [comment]
鉴于时间已经过去太久，还需要帮助请重开issue，谢谢
