### ISSUE TITLE
scroller组件的height属性如果不设置成固定值，上拉加载提示语看不到

### ISSUE THREAD

**Issue by aplusgain** [airyland/vux#321]
1、npm版本为3.8.6，node版本为v5.11.0，vux版本0.1.1

2、iOS9.3.2 微信内置浏览器6.3.22

3、Codes

``` html
<scroller lock-x scrollbar-y use-pullup :pullup-config="pullupConfig2" use-pulldown :pulldown-config={content:'下拉刷新',downContent:'下拉刷新',upContent:'松开刷新',loadingContent:'刷新中...'} @pullup:loading="loadMore" @pulldown:loading="refresh" v-ref:scroller>
      <div class="box2">
        <panel :list="list" :type="type"></panel>
      </div>
      </scroller>
```

问题
scroller组件的height只有设置成固定值，比如500px，上拉加载时才能看见提示语。

**Comment by lichunqiang** [comment]
是不是动态修改数据了？需要手动调用 `reset` 方法

**Comment by airyland** [comment]
如果不是设置成固定值，那么你是怎么设置的？

**Comment by aplusgain** [comment]
对，修改数据了，调用了 `this.$nextTick(() => {
          this.$broadcast('pullup:reset', uuid)
        })`

没有设置height，或者设置成100%

**Comment by aplusgain** [comment]
![1](https://cloud.githubusercontent.com/assets/11243019/16516721/2305171a-3fac-11e6-97b1-52519755a192.png)
![2](https://cloud.githubusercontent.com/assets/11243019/16516723/25919bc0-3fac-11e6-9785-c4208d36ce27.png)

第二张图，上拉刷新后，不停留在最下面，而且滚动到上面了。

**Comment by lichunqiang** [comment]
那你得在获取到数据之后调用 `reset`

**Comment by aplusgain** [comment]
好像是我看错了，scroller的height设置成100%是可以的
