### ISSUE TITLE
cli3.0项目不能全局注册组件

### ISSUE THREAD

**Issue by ouzhenlin** [airyland/vux#3211]
我是用cli3.0创建的项目，按照文档注册一些全局组件 可是报错
比如我用toast 在main.js
import  { ToastPlugin } from 'vux'
Vue.use(ToastPlugin)

// 默认参数
Vue.use(ToastPlugin, {position: 'top'})
然后就报错
Uncaught ReferenceError: exports is not defined
不知道有没有遇到，要怎么解决？

**Comment by quanmingmin** [comment]
同样遇到这个问题！
在node_modules/vux/index.js文件中)解决Vue Cli3遇到的问题:

    // import querystring from './src/tools/querystring/index.js'
    // import LocalePlugin from './src/plugins/locale/index.js'
    // import Range from './src/components/range/index.vue'
    export {
     // LocalePlugin,
    // querystring,
     // Range,
    }
解决报错的问题后，又出现另外一个坑！组件不能按需加载了！
VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。

VUX应该更新一版了

**Comment by quanmingmin** [comment]
全使用了另外一种方式解决全局引用的问题。
//import { AlertPlugin, ToastPlugin ,ConfirmPlugin,LoadingPlugin } from 'vux'
import AlertPlugin from 'vux/src/plugins/alert'
import ToastPlugin from 'vux/src/plugins/toast'
import ConfirmPlugin from 'vux/src/plugins/confirm'
import LoadingPlugin from 'vux/src/plugins/loading'
Vue.use(AlertPlugin)
Vue.use(ToastPlugin)
Vue.use(ConfirmPlugin)
Vue.use(LoadingPlugin)
