### ISSUE TITLE
[Bug Report] XHeader组件设置preventGoBack: true，导航生效，但是安卓物理返回键仍然 可以返回上一页

### ISSUE THREAD

**Issue by wufeng168** [airyland/vux#3216]
### VUX version
2.9.2

### OS/Browsers version
安卓5.1.1

### Vue version
2.5.17

### Code

```html
<x-header v-else slot="header" style="z-index:502;" :left-options="{preventGoBack: true}">

```

### Steps to reproduce
1.点击导航左边的返回按钮不能返回到上一页，达到预期
2.点击安卓手机的物理返回键返回到上一页，达不到预期

### What is Expected?
当loading的时候禁止返回，接口调用完成后再取消禁止返回

### What is actually happening?
点击物理返回键仍然返回到上一页了

**Comment by Sapphire2k** [comment]
@wufeng168 安卓物理键相当于浏览器返回，只能自己手动在路由守卫`beforeRouteLeave`里拦截
