### ISSUE TITLE
[Bug Report] x-input设置属性type为number时，iOS正常，Android机型上出现错误

### ISSUE THREAD

**Issue by MiWi-Lin** [airyland/vux#3218]
### VUX version
2.9.2

### OS/Browsers version
微信H5

### Vue version
2.5.2

### Code

```html
 <x-input ref="phoneNum" name="phoneNum" title="新手机号" placeholder="请输入新手机号" v-model="phoneNum" keyboard="number" type="number" is-type="china-mobile" required :max="11"></x-input>
```

### Steps to reproduce
Android微信中，输入手机号，超过11位

### What is Expected?
正常触发相关valid验证或change回调

### What is actually happening?
抛出错误，提示在x-input组件中Error in callback for watcher "currentValue"....
message: "Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection."
name: "InvalidStateError"
stack: "Error: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection. at a.currentValue

将type改为tel正常，在vux 2.8.1版本上type为number也正常，此次更新了2.9.2之后Android上就出错了

**Comment by linsywu** [comment]
同样遇到此问题，安卓升级到v2.9.2, x-input类型为number的时候失效

**Comment by X-Jagger** [comment]
同样的问题。。
