### ISSUE TITLE
v0.1.2发布概要

### ISSUE THREAD

**Issue by airyland** [airyland/vux#322]
本周三应该发布的v0.1.2跳票到下周三(0706)，处理完以下任务：

+ [x] `Swiper` 支持loop, 非list模式同样支持显示dots. By @unclay Review @airyland
+ [x] 增加 `x-swiper` 满足更复杂的需求。By @xingangsun  Review @lichunqiang 
+ [x] 为vue-cli增加`vuxjs/webpack`模板，支持`vue-router`，方便用户快速上手 @airyland
+ [x] 完全拆分WeUI样式，reset部分手动添加或者引入 @airyland

**Comment by wulucxy** [comment]
给各位大大点赞

**Comment by WilliamDu1981** [comment]
谢谢你们的辛勤劳动

**Comment by WilliamDu1981** [comment]
今天发布哦，期待

**Comment by WilliamDu1981** [comment]
@airyland 新版发布了吗？从npm安装没有看到呢

**Comment by lichunqiang** [comment]
没有
