### ISSUE TITLE
官方什么时候完美支持 vue-cli 3

### ISSUE THREAD

**Issue by fengerwoo** [airyland/vux#3222]
官方什么时候完美支持 vue-cli 3 ？大概计划时间

**Comment by ccj-mlp** [comment]
同问

**Comment by wxxcarl** [comment]
同问，新项目没法用了

**Comment by taixiangfei** [comment]
我把使用vux的老项目用cli3重构，然后还是报错找不到vux-loader，百度找了方法试了也没解决

**Comment by Nomia** [comment]
vue-cli 3见我的issue #3226

**Comment by touxing** [comment]
期待支持cli3,

**Comment by zjun2** [comment]
反馈这么多 时间过了这么久了也不更新 真让人捉急。后悔用了vux。早知道用有赞团队出的了

**Comment by zjun2** [comment]
https://segmentfault.com/a/1190000014586699
解决办法:
yarn add vue-loader@14.2.2 -D
or
npm install vue-loader@14.2.2 -D
不要客气。虽然能运行了 但是会有一堆的警告，并且前台会有一个提示说vue-loader没生效，导致第一次加载会加载所有vux的组件

**Comment by touxing** [comment]
@410919244  这样虽然可以运行开发，但是打包的是时候，就是你想哭的时候。

**Comment by zjun2** [comment]
@touxing 是的，打包起码10分钟。而且体积大，一堆警告

**Comment by caozhong1996** [comment]
see #3778
