### ISSUE TITLE
[vue-cli 3]一万多的star，为什么上手体验这么差？

### ISSUE THREAD

**Issue by Nomia** [airyland/vux#3226]
vuecli版本：vue-cli 3.1.3
项目创建：  vue create demo-project

安装vux：npm install --save vux
编译命令: npm run serve
出现问题：less-loader找不到
解决方案：安装less-loader  `npm install less-loader` ^4.1.0
出现问题：less找不到
解决方案：安装less `npm install less` ^2.7.3
继续出现问题：如图

![image](https://user-images.githubusercontent.com/1707818/48526863-121e2680-e8c4-11e8-8fd6-739baca146d3.png)

然后继续去找文档，vux的`安装`页面底部发现：
![image](https://user-images.githubusercontent.com/1707818/48527193-5231d900-e8c5-11e8-9e25-6cc5e47563c3.png)
文档为什么把两个版本的安装放一起夹杂这说呢？？？分两个页面介绍或者分成两块介绍会不会更少误导，更少误操作？？？

由于我不是使用的webpack模板创建的项目，而是`vue create my-project`创建的，自然也就没有`build/webpack.base.config.js`
所以我在`vue.config.js`文件这样写：
![image](https://user-images.githubusercontent.com/1707818/48527315-b5bc0680-e8c5-11e8-915c-2eafc2d476dd.png)
有没有看起来很不友好，我指vux-loader的接入方式。为什么不能直接给个plugin让我放到plugins数组里就好了？

接下来，编译：`npm run serve`:
出现警告
![image](https://user-images.githubusercontent.com/1707818/48527379-ea2fc280-e8c5-11e8-8c62-8b9d6a35af0e.png)

这是我遇到的问题和误解的简化版本，由于vux这个repo有14k的star，建议主要维护人将文档多做优化，首先让不同的安装过程顺畅，减少开发人员的头痛，增加大家的信任(用element-ui的时候，任何实习生或非实习生，任何电脑设备，没有任何阻碍误解)

**Comment by airyland** [comment]
并未适配 vue-cli 3

**Comment by Nomia** [comment]
那官方文档以及github仓库主页上应该在最最明显的地方标明：
`vux暂未适配vue-cli 3，请勿折腾，不然会掉很多头发` 
@airyland

**Comment by Nomia** [comment]
![image](https://user-images.githubusercontent.com/1707818/48527717-0d0ea680-e8c7-11e8-8743-12f42c776a6b.png)
这个是仓库的requirements

**Comment by Nomia** [comment]
![image](https://user-images.githubusercontent.com/1707818/48527751-27488480-e8c7-11e8-806c-6971c483d756.png)
这个是中文文档里面的安装介绍
两处都没提过vue-cli 3的兼容问题

**Comment by airyland** [comment]
因为有几个月没空维护了，稍后补上。

**Comment by Nomia** [comment]
![image](https://user-images.githubusercontent.com/1707818/48527854-81e1e080-e8c7-11e8-8d05-9fe3e8cf342d.png)
这是编译警告后，打开页面报出的错误。

**Comment by Nomia** [comment]
这里发表在issue里，方便其他vue-cli 3的人查看

**Comment by agileago** [comment]
vue-cli3中必须使用vue-loader14.2.2,可以跑起来，但是打包应用的时候css被打包到了js文件里面去了，并且js里面css文件未压缩，导致包体积挺大的，@airyland 尽快支持一下vue-cli3吧

**Comment by ZTrainWilliams** [comment]
@Nomia  按照你的用法，出现以下问题：
[Vue warn]: Failed to mount component: template or render function not defined.
而使用
``` javascript
module.exports = {
    configureWebpack: config => {
        require('vux-loader').merge(config, {
            options: {},
            plugins: ['vux-ui']
        })
    }
}
```
出现以下报错：
``` javascript
You may need an appropriate loader to handle this file type.
| import { render, staticRenderFns } from "./Home.vue?vue&type=template&id=fae5b
ece&"
| import script from "./Home.vue?vue&type=script&lang=js&"
> ../../node_modules/vux-loader/src/script-loader.js!export * from "./Home.vue?v
ue&type=script&lang=js&"
```
增加'vue-loader@15.4.2'无用

**Comment by agileago** [comment]
@ZTrainWilliams 现在运行起来必须使用 vue-loader@14.2.2, 但打包的时候会有问题

**Comment by ZTrainWilliams** [comment]
> @ZTrainWilliams 现在运行起来必须使用 vue-loader@14.2.2, 但打包的时候会有问题

任然引发其他问题：Cannot redefine property: $router
看来只能不考虑vue-cli3.0用vux了。

**Comment by agileago** [comment]
@ZTrainWilliams 我觉得应该是你那边那里写错了，我这里运行起来都是ok的

**Comment by travelk** [comment]
这个项目告诉我 star数和项目质量是没关系的 我觉得能火的主要原因是因为weui 和名字起的好

**Comment by Nomia** [comment]
@travelk 这项目还是帮人省了不少功夫的

**Comment by hehuangz** [comment]
人家费心费力开源项目已经很棒棒了，使用体验算是我目前使用的vue移动端ui框架中最好的，只是还没有兼容vue-cli@3.x，多点鼓励少点喷，社区会越来越好的

**Comment by zjun2** [comment]
更新一下啊 这么多人反馈的问题
https://segmentfault.com/a/1190000014586699
解决办法:
yarn add vue-loader@14.2.2 -D
or
npm install vue-loader@14.2.2 -D
不要客气。虽然能运行了 但是会有一堆的警告，并且前台会有一个提示说vue-loader没生效，导致第一次加载会加载所有vux的组件
