### ISSUE TITLE
主题定制诉求

### ISSUE THREAD

**Issue by xmm228** [airyland/vux#3230]
目前的主题定制配置文件无法满足有业务需求，比如dataTime组件弹出来的时间选择整体的北京是黑蓝色，目前不知道这种北京颜色修改如何解决
除了修改源码是否有其他合适的解决的方案呢？

**Comment by airyland** [comment]
列出你需要的所有样式详情，帮你加到主题设置里。

**Comment by xmm228** [comment]
目前需要的是整体的北京颜色为#001434，主要包含dataTIme弹出的时间选项背景颜色、PopupPicker弹出的背景颜色，还有tab切换整体的背景颜色，均为#001434，可能说的不太明白，就是我们设计的视觉稿所有的有背景颜色均为#001434 ，字体为白色，能快速的搞定这个奇葩的需求吗？非常感谢

**Comment by xmm228** [comment]
感觉vux真的是非常牛逼的开源，提交了issues就秒回，良心，比某些大公司的开源强太多，支持加油！

**Comment by xmm228** [comment]
请问修改背景颜色的这个问题可以解决吗？请作者百忙不吝赐教谢谢
