### ISSUE TITLE
文档推荐

### ISSUE THREAD

**Issue by wulucxy** [airyland/vux#325]
[mint-ui的文档](http://mint-ui.github.io/docs/#!/zh-cn)做的非常赞，vux是不是也可以考虑下。

**Comment by airyland** [comment]
会考虑

**Comment by airyland** [comment]
在Vux和Mint-UI之间你会选择哪个？还是两个都用？

**Comment by wulucxy** [comment]
@airyland 主要用vux，vux覆盖不到的用mint-ui
