### ISSUE TITLE
是否增加一个表格组件

### ISSUE THREAD

**Issue by hanyou** [airyland/vux#326]
现在屏幕越来越宽了，除了使用list，是否增加一个table组件

### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```

**Comment by airyland** [comment]
屏幕宽也不能放3列以上的表格吧

**Comment by lichunqiang** [comment]
局限性太大了，况且没在移动端看到过用表格的

**Comment by airyland** [comment]
有表格需求的直接用`<table>`标签就可以解决了，暂时Vux不考虑表格组件。

**Comment by unclay** [comment]
哈哈  这个我到是用过，公司的oa基于微信开发的，报表也想在手机看，我也是基于table扩展了下一些weui的风格进去用

**Comment by justnowanna** [comment]
@hanyou @airyland @lichunqiang @unclay @fundon 想问一下楼上各位，移动端表格都是用什么解决方案呢？另外看到`Scroll`组件不再维护了，如果使用`list`，还能实现下拉刷新等功能吗？望答复。

**Comment by jirongjun** [comment]
https://www.uisdc.com/mobile-design-form-design
能否实现这样的表格？
