### ISSUE TITLE
在ios手机微信6.7.4版本上有bug

### ISSUE THREAD

**Issue by jermyLin** [airyland/vux#3268]

**Comment by jermyLin** [comment]
在ios手机微信6.7.4版本上input框和textarea框输入文字后点确认或者取消按钮有bug,会出现卡住，点击无反应，多点几次又正常

**Comment by chatugpt** [comment]
https://developers.weixin.qq.com/community/develop/doc/0000a83566cd0091a7b7d074a51000

如果页面中包含了fixed 定位的输入框，就会出现这个问题，6.7.4之前的版本都没问题
