### ISSUE TITLE
Search 组件建议

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#327]
1. 输入内容这块在IOS上面要点两下或者多下才能输入，体验不好
2. 建议增加cancel后的事件

**Comment by airyland** [comment]
iPhone 6s上重现不了点两次才能输入的情况

**Comment by hubinjie** [comment]
奇怪我要点两次，我也是6s,第一次是自动置顶，第二次才是输入，有时候第二次要重重按才可以。
另外我如果我直接  :value.sync="keyword" 赋初值也是不会显示的，我现在是从另外一个页面转到第二个页面传了一个keyword进来，我现在是做法是直接也将placeholder也赋一个值

**Comment by airyland** [comment]
@hubinjie 测了下，关于focus的问题，Safari下没问题，微信下有问题。

**Comment by hubinjie** [comment]
@airyland 对头，我确实是在微信里面试的

**Comment by GirlSmileToMe** [comment]
@airyland 文档里没有search组件说明，能不能添加一下，不知道怎么用

**Comment by JianleiZhang** [comment]
Android系统的微信端表现正常
