### ISSUE TITLE
[Bug Report] x-input type=number 一些Android浏览器 v-model 没有值

### ISSUE THREAD

**Issue by btshj** [airyland/vux#3271]
### VUX version
2.9.2

### OS/Browsers version
android browser

### Vue version
2.5.17

### Code

```html
 <x-input title="金额" v-model="form.amount" :type="numberInputType" text-align="right" ></x-input>
```

### Steps to reproduce
android 某些浏览器 该input 输入值,但是form.amount没有值.经过跟踪,是因为input type=number 时,不支持selectionStart. 有些浏览器会阻断后续代码的运行,导致this.$emit('input', this.maskValue(newVal))不被执行.但是有些浏览器,又会继续执行后续代码.

### What is Expected?
避免上述现象发生.增加try catch????

### What is actually happening?
避免上述现象发生.增加try catch????

**Comment by littlewords** [comment]
oppo机必现

**Comment by AshaLiu** [comment]
我手头是vivo x20A 也是这个原因 
这个原因还是挺严重的

**Comment by caozhong1996** [comment]
请更新2.9.4
