### ISSUE TITLE
[Bug Report] onImgError 

### ISSUE THREAD

**Issue by EnergySUD** [airyland/vux#3272]
`onImgError (item, $event) {
      this.$emit('on-img-error', JSON.parse(JSON.stringify(item)), $event)
      if (item.fallbackSrc) {
        $event.target.src = item.fallbackSrc
      }
    },`
当 fallbackSrc 也为404的时候，然后该img一直访问这404的图片链接。

**Comment by caozhong1996** [comment]
目前人手精力不够，帮助当前使用者解决bug更为重要，由于时间过去太久，暂时关闭此issue，如果有解决方案也欢迎pr，还需要帮助的话请重开issue，谢谢🙏
