### ISSUE TITLE
[Bug Report] x-chart更新data后不渲染

### ISSUE THREAD

**Issue by kuangyazhou** [airyland/vux#3274]
### VUX version
2.9.2

### OS/Browsers version
macos mojave/chrome 70

### Vue version
2.5.17

### Code

```html
 <v-chart :data="data" ref='chart1'>
            <v-line series-field="type" />
          </v-chart>

this.$http
        .get("h5/bussiness")
        .then(({ data }) => {
          this.data.push(data.data);
          this.$refs.chart.rerender();
          // console.log(this.data);
        })
        .catch(err => {
          console.log(err);
        });
```

### Steps to reproduce
异步请求后更新data。xchart不会重新渲染

### What is Expected?
chart正常显示

### What is actually happening?
chart为空白

**Comment by kuangyazhou** [comment]
已解决。。vux  cli用的2.2.0版本。。。。。作者求更新

**Comment by h3n5** [comment]
@kuangyazhou  这样应该也可以 
this.$nextTick(() => {
        this.$refs.chart.rerender()
 })
