### ISSUE TITLE
tab 切换时如何让下面的组件回到顶部

### ISSUE THREAD

**Issue by xiaodanit** [airyland/vux#3279]
tab 切换时如何让下面的组件回到顶部

          <tab active-color='#005cbf'>
            <tab-item 
            :selected="currentTab==index" 
            v-for="(item ,index) in tabs" 
            :key="index"
            @on-item-click="changeTab"
            >
            {{item}}
            </tab-item>
          </tab>
        </div>
      
        <section v-if="hasorder" class="contant"  ref="tab">
                <div  v-for="(item,index) in orderlist" 
                :key="index" >
                  <cell-box class="nobordercell" 
                 :border-intent="false"
                >
                <div style="width:100%">
                     
                     <div class="cardheader"  >
                              <div class="align-right">运单号：{{item.billcode}}</div>
                               <div class="ciclestatus">{{(item.trackStatus)}}</div>
                       
                     </div>
                               <div class="orderitem">
                                 <p>{{item.sendCustomer}}<span class="send">寄往</span>{{item.receiverCustomer}}</p>
                                    <p>寄出时间：{{item.sendDate}}</p>
                               </div>
                    <div class="orderbtn">
                        <button  class="othbtn" @click="follow(item.billcode)">运单追踪</button> <button @click="detail(item)" class="def-btn">详情</button>
                    </div>
                </div>
                
                </cell-box>
           
                </div>
                
              
           
        </section>

**Comment by caozhong1996** [comment]
目前人手精力不够，帮助当前使用者解决bug更为重要，由于时间过去太久，暂时关闭此issue，还需要帮助的话请重开issue，谢谢🙏
