### ISSUE TITLE
[Bug Report] 安卓x-input 输入框 获得焦点时并没有定位到可视区域

### ISSUE THREAD

**Issue by Sprite-FFF** [airyland/vux#3287]
### VUX version
2.9.2

### OS/Browsers version
安卓

### Vue version
2.5.18-beta.0

### Code

```html
<x-input class="cell-item" type="number" v-model="form.auctionTrading.ReservePrice" :placeholder="pricePlaceholder">
        <span slot="label" class="w-label">
              <span class="dot-tip">*</span>竞价基准价</span>
        <span slot="right">元/吨</span>
 </x-input>
```

### Steps to reproduce
页面有很多输入框时 点击靠上面的输入框 获得焦点之后 键盘弹起 获得焦点的输入框并不会滚动到可视区域 而是被遮挡住 官方Demo里也会有这个问题 不知道为什么没人注意么

### What is Expected?
键盘弹起 输入框应该定位在可是区域内 

### What is actually happening?
键盘弹起之后 输入框向上滚动后 并没有滚动到可视区域

**Comment by jinchaoxiang** [comment]
同样2.9.2有这个问题

**Comment by xieqian-xq** [comment]
是的，我也遇到了这个问题。
1、经过多番测试之后，发现，如果父元素没有加 `overflow` 的话，网页是可以自动滚动至可视区域的；
2、但如果加了`overflow`之后，则网页无法自动滚至可视区域。

经过多番查找，及看了`x-input`的源代码，发现有这两个`scrollIntoView`和`scrollIntoViewIfNeeded` api：
最后艰难决定，舍弃了`x-input`和`view-box`组件，自己布局，自己滚动至可视区域。

如下是解决的方案：
~~~
const h = document.body.scrollHeight;
window.onresize = function() {
    if (document.body.scrollHeight < h) {
        setTimeout(() => {
            document.activeElement.scrollIntoView({ behavior: "smooth" });
        });
    }
};
~~~

**Comment by gdmec07140512** [comment]
一样的问题

**Comment by ahjsrhj** [comment]
将x-input源码中
```
window.addEventListener('resize', this.scrollIntoView)
window.removeEventListener('resize', this.scrollIntoView)
```
这几行注释即可

**Comment by fewiki** [comment]
建议 加一个 resize时scrollIntoView的开关，默认滚动顶部，可能会有header，会被遮挡

**Comment by maroon1** [comment]
源码中画蛇添足的给每个x-input添加了在触发resize事件时调用scrollIntoViewIfNeeded的逻辑，导致页面高度变化时，页面会滚动到最后一个x-input
```javascript
  mounted () {
    window.addEventListener('resize', this.scrollIntoView)
  },
  methods: {
    scrollIntoView (time = 0) {
      // alert('scroll into view')
      if (/iphone/i.test(navigator.userAgent)) {
        // return
      }
      if (document.activeElement.tagName === 'INPUT' || document.activeElement.tagName === 'TEXTAREA') {
        // alert('will scroll')
        setTimeout(() => {
          // alert(this.$refs.input.length)
          this.$refs.input.scrollIntoViewIfNeeded(true)
        }, time)
      }
    },
```

**Comment by webthen** [comment]
// fixed ios12+    
document.body.addEventListener('focusout', () => {
      if (/(iPhone|iPad|iPod|iOS)/i.test(navigator.userAgent)) {
        // 软键盘收起的事件处理
        setTimeout(() => {
          const scrollHeight = document.documentElement.scrollTop || document.body.scrollTop || 0
          window.scrollTo(0, Math.max(scrollHeight - 1, 0))
        }, 100)
      }
    })

**Comment by webthen** [comment]
// fixed ios12+
document.body.addEventListener('focusout', () => {
      if (/(iPhone|iPad|iPod|iOS)/i.test(navigator.userAgent)) {
        // 软键盘收起的事件处理
        setTimeout(() => {
          const scrollHeight = document.documentElement.scrollTop || document.body.scrollTop || 0
          window.scrollTo(0, Math.max(scrollHeight - 1, 0))
        }, 100)
      }
 })
