### ISSUE TITLE
[Bug Report] x-input 组件设置type="number" 报错 stack: "Error: Failed to read the 'selectionStart' property from 'HTMLInputElement'

### ISSUE THREAD

**Issue by andyqier88** [airyland/vux#3288]
### VUX version
2.2.0

### OS/Browsers version
安卓微信浏览器

### Vue version
2.2.2

### Code

```html
<x-input placeholder="发送验证码"  v-model="yzmTexts"  type="number">
                    <p slot="right" type="primary" mini class="yzm-btn" @click="sendYZM">
                         {{yzmIsSend ? yzmTimer   '秒后再次发送' : '发送验证码'}} 
                    </p>
 </x-input>
```

### Steps to reproduce
x-input 组件 设置 type="number" 
去掉设置type 正常

### What is Expected?
no error

### What is actually happening?
message: "Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection."
name: "InvalidStateError"
stack: "Error: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection.

**Comment by Adele0** [comment]
你解决了吗？我也有同样的报错。我添加一个@keyup.native事件，正则匹配似乎就没有这样的报错了

**Comment by caozhong1996** [comment]
这个问题应该已经修复，还需要帮助请重开issue，谢谢
