### ISSUE TITLE
view-box 怎么实时监听滚动条的位置有。。。

### ISSUE THREAD

**Issue by zhaoxm469** [airyland/vux#3294]
let box = this.$refs.viewBox.$el;
        console.log(box.$el)
        // this.$refs.viewBox.scroll = function ()
        box.addEventListener('scroll', () => {
            console.log(this.$refs.viewBox.scrollTop)
        }, false)

我这样监听一直报错 ， 不知道什么问题。。

**Comment by xdoer** [comment]
滚动的不是this.$refs.viewBox.$el，而是这其中包裹的一个类名为xs-container的div。。所以你监听不到box的滚动，只能调用ViewBox中getScrollTop函数来获得滚动高度。

**Comment by vampireXia** [comment]
我也有这个问题 想监听viewbox的滚动 但是addEventListener无效

**Comment by zhaoxm469** [comment]
谢谢
