### ISSUE TITLE
[Bug Report] v-html里的x-img可以懒加载吗？

### ISSUE THREAD

**Issue by xlkit456852** [airyland/vux#3300]
### VUX version
2.9.2

### OS/Browsers version
WIN10/Chrome 70.0.3538.110

### Vue version
2.5.20

### Code

```html
<div id="rich_text" v-html="rich_text" ></div>


```

### Steps to reproduce
我在后端把富文本的html中img标签都替换成了<x-img src="xxx"></x-img>，但前端执行时好像没有触发到懒加载，应该是因为v-html的缘故（把x-img放到正常的标签里是可以显示的）。有什么方法可以重新触发v-html里的图片懒加载呢？

### What is Expected?
重新触发v-html里的图片懒加载

### What is actually happening?
v-html里的图片未触发懒加载

**Comment by caozhong1996** [comment]
不行，v-html不会被模版编译器解析
