### ISSUE TITLE
[Bug Report] 同页面存在Xicon和base64的时候，如果base64体积过大（十多KB），base64会报net::ERR_INVALID_URL

### ISSUE THREAD

**Issue by mrHanYu** [airyland/vux#3305]
### VUX version
2.9.2

### OS/Browsers version
win10/chrome71.0.3573.0

### Vue version
2.5.21

### Code

```html
<x-icon type="ios-arrow-left" size="20"></x-icon>
<img src="data:image/png;base64,iVBORw0KG..." alt=""/>
```

### Steps to reproduce
只要上述代码在同一组件出现，并且base64过大就会报错

### What is Expected?
无论base64多大都不会报错

### What is actually happening?
使用的时候图片9.7K转base64之后就会报错

**Comment by jewelcai** [comment]
同样碰到这个问题  怎么解决？
