### ISSUE TITLE
[Bug Report] qrcode生成带logo的二维码

### ISSUE THREAD

**Issue by grainXianSen** [airyland/vux#3306]
### VUX version
2.9.2

### OS/Browsers version
微信浏览器

### Vue version
2.5.21

### Code

```html
暂无
```

### Steps to reproduce
无

### What is Expected?
生成带logo的二维码，并在微信中长按可识别

### What is actually happening?
无法生成dailogo的二维码

**Comment by airyland** [comment]
暂无直接支持 logo 的功能计划。你可以将 logo 定位到二维码中间。
