### ISSUE TITLE
关于结构的两点建议

### ISSUE THREAD

**Issue by charleslo1** [airyland/vux#331]
1.建议将 reset(normalize.css) / weui css / 1px / 原子类 等零散通用的 css/js 放在一个 core 核心模块统一管理【注：目前整体引入有基础样式，按需引用的时候没有基础样式，也没有基础样式的引用入口】
2.对基础组件和扩展组件进行分类管理，这样可以根据不同情况按需引导加载，同时也避免因组件膨胀而导致查找困难。

// 整体加载
import 'vux';

// 分级加载
import 'vux/core';                        // 核心模块
import 'vux/ui';                            // 基础组件库（通过 index.js 引导）
import 'vux/ui-extends';              // 扩展组件库（通过 index.js 引导）

// 按需加载
import 'vux/core';
import Tabbar from 'vux/ui/tabbar';
import Flexbox from 'vux/ui/flexbox';
import XInput from 'vux/ui/x-input';
import Circle from 'vux/ui-extends/circle';

**Comment by airyland** [comment]
分级加载难道不是增加了复杂度？在Vux没有所谓的核心模块，基本库，扩展组件库这些概念。

如果你有关注开发计划的话，就知道WeUI样式会拆分到各个组件，不需要手动引入。这是最合适的方式，css不会变成模块的方式来引入。

`同时也避免因组件膨胀而导致查找困难`? 很多UI库所引来的奇奇怪怪的分类才是困难的来源吧，A认为这是基本组件，B认为这是扩展组件，C认为这应该独立就叫布局组件，D认为这应该就只是个CSS组件，官方是另一个概念，那么引入时就更困难了。我明明就需要记个名字来引入，现在我需要记个和我意识里可能不一样的分类名。

Vux只会推荐按需加载，如果你要分类，那么完全可以自己在项目里写几个分类入口分别引入，这是最自由的方式。

**Comment by charleslo1** [comment]
嗯嗯，有道理，可能我的想法还不够成熟，受教了。
