### ISSUE TITLE
[Bug Report] 当sticky缓存keepalive时，出现的bug

### ISSUE THREAD

**Issue by chavesgu** [airyland/vux#3310]
### VUX version
2.9.2

### OS/Browsers version
macOs/chrome最新

### Vue version
2.5.21

### Code

```html
<div style="height: 44px;">
      <Sticky
        ref="sticky"
        :offset="50"
        :check-sticky-support="false"
        scroll-box="course"
      >
        <Tab></Tab>
      </Sticky>
</div>
```

### Steps to reproduce
当切换到其他路由，当前路由会被缓存 keepalive，再回来触发sticky的activited时，源码中的getFillElem方法报错，
以下是报错内容，
Cannot read property 'nodeType' of null
    at getFillElem (sticky.js?b1bf:56)

### What is Expected?
不应该报错

### What is actually happening?
由于当前Sticky元素的nextSibling为null，所以查找nodeType这个键会报错

**Comment by chavesgu** [comment]
![报错信息](/user/guchunwen/desktop/12345.png)

**Comment by wzz0720** [comment]
你这个问题解决了吗

**Comment by chavesgu** [comment]
> 你这个问题解决了吗

在sticky标签下面加一个空的div兄弟元素，display none 就可以了
