### ISSUE TITLE
[Bug Report] 调用Vue.use(ConfirmPlugin)报错 $t 方法找不到

### ISSUE THREAD

**Issue by chavesgu** [airyland/vux#3313]
### VUX version
2.9.2

### OS/Browsers version
macOS/chrome

### Vue version
2.5.21

### Code

```html
Vue.use(ConfirmPlugin)
```

### Steps to reproduce
vue引用plugin的confirm，控制台报错找不到$t方法 在vux/src/components/confirm/index.vue

### What is Expected?
不应该报错

### What is actually happening?
报错了，找不到$t方法

**Comment by chavesgu** [comment]
@airyland

**Comment by zzlhr** [comment]
$t()是翻译的方法，如果没有多语言需求可以去掉

**Comment by chavesgu** [comment]
不是我写的，。，。他confirm组件里面写的

**Comment by chenlang0311** [comment]
一看就没怎么看文档的，你需要引入Iin18才能使用$t()方法的

**Comment by chavesgu** [comment]
> 一看就没怎么看文档的，你需要引入Iin18才能使用$t()方法的

你脑子有病是不是   作者组件里面写的$t方法  还要我自己引入国际化？

**Comment by chenlang0311** [comment]
http://www.mamicode.com/info-detail-2393458.html
麻烦去看下

**Comment by chavesgu** [comment]
> http://www.mamicode.com/info-detail-2393458.html
> 麻烦去看下

vuex-i18n是vux自动携带安装那又如何  一样报错

**Comment by airyland** [comment]
vux-loader 没有配置正确。这个字符会被替换掉的。
