### ISSUE TITLE
[Bug Report] 当x-input的type为“number”,可能会出现无法获取value的情况，限于某些安卓机型(华为P20、努比亚、及其他安卓8系统机型)

### ISSUE THREAD

**Issue by hzc315579049** [airyland/vux#3314]
### VUX version
2.9.2

### OS/Browsers version
Android 8.1.0

### Vue version
2.5.21

### Code

```html
let selection = this.$refs.input.selectionStart
let direction = newVal.length - oldVal.length
selection = this._getInputMaskSelection(selection, direction, this.maskValue(newVal))
this.lastDirection = direction
this.$emit('input', this.maskValue(newVal))
// #2810
this.$nextTick(() => {
  if (this.$refs.input.selectionStart !== selection) {
    this.$refs.input.selectionStart = selection
    this.$refs.input.selectionEnd = selection
  }
  if (this.currentValue !== this.maskValue(newVal)) {
    this.currentValue = this.maskValue(newVal)
  }
})
```

### Steps to reproduce
在上述提到的机型中，使用number  x-input，输入一些内容，在watch组建内的currentValue时，上述代码会报错:"Uncaught InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection."

### What is Expected?
number类型的x-input能正确获取到值

### What is actually happening?
number类型的x-input在接收其子组件emit的值时发生了错误，从而无法取到正确的值

**Comment by caozhong1996** [comment]
请更新2.9.4
