### ISSUE TITLE
popup-picker 能否支持添加点击事件？或者怎么实现

### ISSUE THREAD

**Issue by xingyemeng** [airyland/vux#3315]
`list1: [['小米', 'iPhone', '华为', '情怀', '三星', '其他', '添加新型号']],`
给popup-picker的数据，在滑动到“添加新型号”这一项时，可以直接点击添加一个

**Comment by zzlhr** [comment]
通过vue watch监听 popup-picker 的value,
```
if(value === '添加新型号'){
    // 通过x-dialog 进行添加
    ...
   // reload list1
}
```

**Comment by xingyemeng** [comment]
> 通过vue watch监听 popup-picker 的value,
> 
> ```
> if(value === '添加新型号'){
>     // 通过x-dialog 进行添加
>     ...
>    // reload list1
> }
> ```

 嗯，这是挺好的方法，但是如果我想要在点击“添加新型号”这一选项时才弹出dialog，可以实现吗

**Comment by zzlhr** [comment]
# 通过watch监听popup-picker 的value
```
watch:{
      // popup-picker绑定的value
      value(val){
            if(val === '添加新型号'){
                // 通过x-dialog 进行添加
                ...
               // reload list1
            }
      }
}
```

**Comment by xingyemeng** [comment]
> # 通过watch监听popup-picker 的value
> ```
> watch:{
>       // popup-picker绑定的value
>       value(val){
>             if(val === '添加新型号'){
>                 // 通过x-dialog 进行添加
>                 ...
>                // reload list1
>             }
>       }
> }
> ```

明白了，谢谢您 @zzlhr
