### ISSUE TITLE
vux 使用group 创建cell 之后，想设置这个group是圆角的，有办法设置吗？

### ISSUE THREAD

**Issue by AlexYangLe** [airyland/vux#3319]
代码：
<div class="group-div">
      <group class="group-item">
        <cell class="cell-model" :title="$t('Address')" is-link>
        <img class="cell-icon" slot="icon"  src=""></img>
        </cell>
        <cell class="cell-model" :title="$t('FAQ')" is-link>
          <img class="cell-icon" slot="icon"  src=""></img>
        </cell>
      </group>
      <group class="group-item">
        <cell class="cell-model" :title="$t('Address')" is-link>
        <img class="cell-icon" slot="icon"  src=""></img>
        </cell>
        <cell class="cell-model" :title="$t('FAQ')" is-link>
          <img class="cell-icon" slot="icon"  src=""></img>
        </cell>
      </group>
      <group class="group-item">
        <cell class="cell-model" :title="$t('Address')" is-link>
        <img class="cell-icon" slot="icon"  src=""></img>
      </cell>
        <cell class="cell-model" :title="$t('FAQ')" is-link>
          <img class="cell-icon" slot="icon"  src=""></img>
        </cell>
      </group>
    </div>

style：
.group-div{
    postition:absolute;
    height:102rem/@px;
    margin-top:200rem/@px;
    margin-left:3%;
    width:94%;
    border-radius:15px;
    border-color:#000;
    border: none;
    .group-item{
      margin-top:-12rem/@px;
      border-radius:15px;
      border: none;
      .cell-model{
        font-size:16px;
        text-align:left;
        margin-left:-2rem/@px;
        background:white;
        border-radius:15px;
        .cell-icon{
          display:block;
          width:20rem/@px;
          height:50%;
          margin-right:15px;
        }
      }
    }
这么设置完但是group外面不起作用，是不是不能设置？
<img width="275" alt="image" src="https://user-images.githubusercontent.com/4382838/50397197-b2137d80-07a9-11e9-9733-10fdc0e645be.png">

**Comment by zhangshichun** [comment]
```
.weui-cells{
border-radius: 10px;
}
```

**Comment by caozhong1996** [comment]
鉴于时间已经过去太久，还需要帮助请重开issue，谢谢
