### ISSUE TITLE
disabled switch has same look

### ISSUE THREAD

**Issue by musicformellons** [airyland/vux#332]
The default switch and the disabled switch have the same look. I would expect to have a more grayed out version when disabled!? 

![screenshot from 2016-07-05 14-53-55](https://cloud.githubusercontent.com/assets/10334123/16585323/97763a86-42c0-11e6-9953-2b71dbe677ae.png)

**Comment by airyland** [comment]
Did you test on mobile?

**Comment by musicformellons** [comment]
Now I did..., looks the same. See picture for browser version.
![screenshot_20160705-150603](https://cloud.githubusercontent.com/assets/10334123/16585655/4c90796c-42c2-11e6-8789-d81c5e0306ba.png)

**Comment by lichunqiang** [comment]
@musicformellons I had created an issue about this issue to weui.

Let's waiting the result, if the weui will not accept this request, we will try to find out how we resolve this problem.

**Comment by lichunqiang** [comment]
The easy way is to change the opacity i think.
```
input.weui_switch[disabled] {
    opacity: .6;
}
```
:mask:

**Comment by musicformellons** [comment]
Yes, that works fine! Thanks.

**Comment by airyland** [comment]
Close this issue for the moment and we will keep track of the related issue: https://github.com/weui/weui/issues/419

**Comment by musicformellons** [comment]
Great, thx.
