### ISSUE TITLE
[Bug Report] ios12环境下confirm输入框中唤起键盘后再收起键盘页面布局错位, 无法点击到confirm中的按钮

### ISSUE THREAD

**Issue by CinseYoung** [airyland/vux#3321]
### VUX version
2.9.2

### OS/Browsers version
ios12

### Vue version
2.5.17

### Code

```html
<confirm 
v-model="showPrompt" 
ref="password" 
show-input 
title="请输入您的登录密码" 
:close-on-confirm="closeOnConfirm" 
@on-confirm="onConfirm" 
:input-attrs="{type:'password'}">
 </confirm>
```

### Steps to reproduce
在微信7.00版本的公众号网页中  confirm组件中输入内容后点击ios键盘上的"完成"键收起键盘,这时候再点击confirm组件上的按钮就会出现错位,类似的popup组件也有此问题

### What is Expected?
点击屏幕对应的区域应该准确回馈

### What is actually happening?
页面错位后点击按钮会触发其它位置的事件

**Comment by xietianyao** [comment]
这是ios微信6.7.4的一个BUG，我这里目前解决方案是，监听输入框的失去焦点事件 然后让页面滚动到当前输入框的位置

**Comment by CinseYoung** [comment]
请问怎么滚动到当前输入框位置呢? 我目前是通过window.scroll(0,0);实现滚动的,但是解决不了页面错位的问题

**Comment by ianho7** [comment]
你好，请问解决了吗？

**Comment by CinseYoung** [comment]
没有解决 = =

**Comment by martin-odun** [comment]
对，也有遇到这个问题 ，
我是这样处理的 ：
document.body.addEventListener('focusout', function () {
        window.scrollTo(0,0);
})
