### ISSUE TITLE
【popup-picker 】组件BUG，如果是key value的形式绑定data，value如果是数字，选中后，show-name无效，无法显示name。

### ISSUE THREAD

**Issue by softshield** [airyland/vux#3323]
【popup-picker 】组件BUG，如果是key value的形式绑定data，value如果是数字，选中后，show-name无效，无法显示name。

**Comment by kinder1995** [comment]
number要转换成字符串   value.toString()
文档有写啊

![tim 20181228154449](https://user-images.githubusercontent.com/18692424/50507226-8d741a00-0ab7-11e9-92aa-6ba298d030d8.png)

**Comment by softshild** [comment]
好的，谢谢

**Comment by softshield** [comment]
> number要转换成字符串 value.toString()
> 文档有写啊
> 
> ![tim 20181228154449](https://user-images.githubusercontent.com/18692424/50507226-8d741a00-0ab7-11e9-92aa-6ba298d030d8.png)

嗯 这个没细看，谢谢
