### ISSUE TITLE
[Bug Report] xinput type="number"在手机运行时无法响应v-model属性

### ISSUE THREAD

**Issue by liguChen** [airyland/vux#3325]
### VUX version
2.9.2

### OS/Browsers version
IOS 12.0/Android 8.0/Android 9.0自带浏览器

### Vue version
2.5.20

### Code

```html
<template>
  <div>
    <group title="type='number'">
      <x-input title="测试type" v-model="testValue" type="number"></x-input>
    </group>
    testValue: {{ testValue }}
  </div>
</template>
<script>
import { XInput, Group } from 'vux'
export default {
  components: {
    XInput,
    Group
  },
  data () {
    return {
      testValue: ‘’,
    }
  }
}
</script>
```

### Steps to reproduce
在输入框输入数据

### What is Expected?
输入不合法数据，除了字母e的非数字字符时，检验不通过，不做反应。
输入合法数据，数字或字母e，通过v-model属性将输入数据绑定到testValue变量中

### What is actually happening?

1. 在PC端Google Chrome调试时可以出现期待行为
2. 在移动Android系统的浏览器使用时，输入不合法数据时，出现期待行为；输入合法数据时，不会响应v-model将输入数据绑定到testValue变量中。
3. 在移动IOS系统的浏览器使用时，输入合法数据时，会响应v-model属性，输入不合法数据时同样会响应v-model属性，将除了字母e的非数字字符同样绑定到testValue变量中

**Comment by zhyf08** [comment]
我也遇到这个问题，电脑上用chrome测试正常，IOS上也没问题，就只在安卓上不正常，不得已将vux降到2.7.9才可以

**Comment by zhyf08** [comment]
经测试，type="tel"时也有问题，我的package.json版本配置如下：

  "dependencies": {
    "fastclick": "^1.0.6",
    "jquery": "^3.3.1",
    "js-cookie": "^2.2.0",
    "vue": "^2.5.21",
    "vue-router": "^3.0.2",
    "vuex": "^3.0.1",
    "vux": "^2.9.2",
    "vux-loader": "^1.2.9",
    "whatwg-fetch": "^2.0.4"
  },

别的不改动，只要将vux降到2.7.9就正常

**Comment by zhyf08** [comment]
我把2.9.2版中node_modules\vux\src\components\x-input文件夹删掉，然后把2.7.9版的对应文件夹复制过来，貌似也正常
