### ISSUE TITLE
项目vue-cli3.0 使用vux报错，使用了Confirm这个或者Alert报错

### ISSUE THREAD

**Issue by yuanshuijiao** [airyland/vux#3326]
* ../x-dialog in ./node_modules/_babel-loader@8.0.4@babel-loader/lib!./node_modules/_vux-loader@1.2.9@vux-loader/src/script-loader.js!./node_modules/_vux-loader@1.2.9@vux-loader/src/script-loader.js!./node_modules/_vue-loader@14.2.3@vue-loader/lib/selector.js?type=script&index=0!./node_modules/_vux@2.9.2@vux/src/components/confirm/index.vue, ./node_modules/_babel-loader@8.0.4@babel-loader/lib!./node_modules/_vux-loader@1.2.9@vux-loader/src/script-loader.js!./node_modules/_vue-loader@14.2.3@vue-loader/lib/selector.js?type=script&index=0!./node_modules/_vux@2.9.2@vux/src/components/confirm/index.vue

**Comment by xsw911213** [comment]
我也是使用这个报错了，也已经按照官方文档配置了vux-ui

**Comment by iamziyue** [comment]
`vue.config.js` 中：
``` js
module.exports = {
  publicPath: '/globalhotel',
  configureWebpack: config => {
    vuxLoader.merge(config, { options: {}, plugins: ['vux-ui', 'duplicate-style'] })
  }
}
```

引入 `Confirm` 需要用源码方式：
``` js
import ConfirmPlugin from 'vux/src/plugins/confirm'
Vue.use(ConfirmPlugin)
```
