### ISSUE TITLE
如何修改vux grid-item的内置样式

### ISSUE THREAD

**Issue by zhoutengshen** [airyland/vux#3332]
以下需求：
![image](https://user-images.githubusercontent.com/26021548/50532459-818a6580-0b54-11e9-8609-f8da5d6f2a0c.png)
按公司需求，我需要在单个页面里面调整 grid-item组件里面p标签的magin-top，还有里面img图标的大小

**Comment by ZhikunHuang** [comment]
[https://blog.csdn.net/zgpeterliu/article/details/81287262](https://blog.csdn.net/zgpeterliu/article/details/81287262)，请看这条连接
