### ISSUE TITLE
【项目中出现的www.9miao.com】咋整？

### ISSUE THREAD

**Issue by chengjs** [airyland/vux#3334]
### 心慌

> 现在的技术很牛的不一定心善，有可能缺心，网上那么多栗子，今天突然看到项目下面多了一个网址，心里很慌啊，咋回事了？next()

### 上代码

```html
<div id="kfzsbox" style="position: absolute;">
    <div class="kfzs-mleft"></div>
    <div class="kfzs-mbody"></div>
    <div class="kfzs-mfoot">www.9miao.com</div>
</div>
```

### 重现场景

```
1、安装vux模板
2、npm run dev
3、在浏览器中打开
4、window的朋友按F12，mac的按 ait+com+i 
5、找到最后面的dom节点就可以发现了
```

### ❤️慌不慌？

> 还以为是其他的npm下载的插件了，原来是vux的锅，差点甩错了锅

**Comment by weapp-studio** [comment]
**如何确定你甩锅给 vux 不是甩错呢？**

1.模板 repo 在这里 https://github.com/airyland/vux2 是否源码里有你提到的网址呢？

2.如何确定不是你的网络问题呢？是否被劫持了？

3.如何确定不是你的浏览器插件问题呢？你直接打开页面源码是否看到你说的代码呢，如果没有，动态插入的代码和 vux 有半毛钱关系？

4.是否有 Google 过，看到类似的问题呢，我真没能力做到为所有网站插入这样一段代码。
![image](https://user-images.githubusercontent.com/44454391/50556405-ae38ab80-0d13-11e9-9ff1-203061636a8e.png)


**在你不确定问题时就甩锅给我，还讽刺我“现在的技术很牛的不一定心善，有可能缺心”，说实话缺心的是你。**

**Comment by kasuganosoras** [comment]
这位兄弟，请你在提 Issues 前，多进行下测试，换个浏览器，换个设备测试
不要什么都没搞清楚就瞎提 Issues，否则只会闹笑话

从 V2EX 过来的

**Comment by chengjs** [comment]
没钱翻墙，谷歌不了，心慌啊

**Comment by chengjs** [comment]
尴尬，对不起。哈哈哈
