### ISSUE TITLE
在popup中的address，点击address的取消和完成会关闭父级的mask

### ISSUE THREAD

**Issue by yiling-e0** [airyland/vux#334]
在popup中的address，点击address的取消和完成会关闭父级的mask

**Comment by airyland** [comment]
在popup里嵌套address，这不推荐啊，在popup再弹popup这个没有考虑过。

**Comment by unclay** [comment]
@djh1994  不推荐使用多层popup
@airyland   #205  之前好像处理过多个popup的问题，发现hideOnBlur的功能忘记做了
