### ISSUE TITLE
打包优化——其他项目下直接打包vux场景

### ISSUE THREAD

**Issue by keepgoingwm** [airyland/vux#335]
### Version

非npm包，源码打包相关
### Android or iOS

不涉及
### Your Codes 

vux作为依赖直接在其他项目node_modules下webpack打包时，js文件的loader会因为'nested node_modules'问题而失效，原因是loaders.exclude中的正则匹配匹配到上层node_modules。
> [http://stackoverflow.com/questions/31675025/how-to-exclude-nested-node-module-folders-from-a-loader-in-webpack](http://stackoverflow.com/questions/31675025/how-to-exclude-nested-node-module-folders-from-a-loader-in-webpack)

+ 原代码
``` javascript
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel!eslint',
        exclude: /node_modules/    // here
      },
```
+ 建议
``` javascript
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel!eslint',
        exclude: new RegExp(path.resolve(__dirname, '../').split(path.sep).pop() + '[\\\\\\\/]' + 'node_modules')
      },
```

### Expected behavior and actual behavior.

涉及build目录下build-components.js、webpack.base.conf.js、webpack.npm.base.conf.js
优化一下exclude参数以方便直接在其他项目下编译调试vux场景
### Steps to reproduce the problem

在node_modules目录下放置vux代码目录，然后执行npm run xbuild

**Comment by airyland** [comment]
你是指在某项目的node_modules下放vux目录，然后在vux目录进行npm run xbuild?

**Comment by keepgoingwm** [comment]
是的，有的时候会直接用源码替换npm安装的文件，修改编译，进行调试

**Comment by airyland** [comment]
@keepgoingwm 其实为什么不直接import vue文件，这样不用进行xbuild？

**Comment by keepgoingwm** [comment]
@airyland 自身的项目没有相应的Loader，比如vux的样式用的less的Loader
当然如果不需要额外编译时，直接使用vue文件比较好用

**Comment by airyland** [comment]
@keepgoingwm

**Comment by keepgoingwm** [comment]
@airyland 按webpack的说明，exclude参数的输入是个绝对路径，然后正则匹配，应该是要匹配到上一级的node_modules的，我这边就是这个原因。你是Linux环境吗，我是Windows下，按理说不应该有差异，后面我再试试
webpack: 1.13.1

**Comment by keepgoingwm** [comment]
@airyland 0.1.2分组件引用，感觉我们调试的最优方式也要变了，先关闭了
