### ISSUE TITLE
popup-picker iOS8.2 样式问题

### ISSUE THREAD

**Issue by wenlong0703** [airyland/vux#3350]
popup-picker组建，在iOS8.2下样式如图，（完成按钮在取消的下方）用户发过来的图，找不到机器重现，有遇到的朋友帮忙看怎么解决的
![wechatimg303](https://user-images.githubusercontent.com/4222060/50823885-030d9f00-1370-11e9-924a-2073e92a8a9b.jpeg)

**Comment by caozhong1996** [comment]
鉴于时间过去太久，且现在兼容Ios8已无太大意义，所以关闭这个isuue，如果还需要帮助请重开issue，谢谢
