### ISSUE TITLE
[Bug Report] PopupPicker苹果兼容问题bug

### ISSUE THREAD

**Issue by qq1994** [airyland/vux#3353]
### VUX version
2.9.2

### OS/Browsers version
iphone6sp iphonex

### Vue version
2.5.21

### Code

```html
 <popup-picker title="最高学历学习形式" :data="pickerArry.xxxs" v-model="formOpt.zgxxxs" show-name >
  <template slot="title" slot-scope="props">
         <span style="vertical-align:top;">最高学历学习形式<i class="need">*</i></span>
 </template>
 </popup-picker>
```

### Steps to reproduce
点击popup-picker弹出来了，但是点击“取消”跟“完成”都不能关闭弹窗，且没有反应。但是滑动一下选项或者滑动一下mask后面的页面，在点击取消跟完成弹框就可以关闭了。我以为试mask遮罩的问题，但是我取消了mask还是这样的情况。我有操作的视频

### What is Expected?
可以正常关闭弹窗，点击完成或取消按钮有反应

### What is actually happening?
点击取消或完成按钮没有反应

**Comment by Haixing-Hu** [comment]
遇到同样的问题
只在iphone8 的微信浏览器中出现

**Comment by pititkai** [comment]
同样出现这个问题，比如在输入文本输入文字，再点击这个popup-picker，“完成”和“取消”失效了。麻烦工作组人员，看看是不是一下问题
1.失焦导致的问题。
2.components\popup-header\index.js文件中的方法，$emit(‘on-click-right’)
