### ISSUE TITLE
请问下大神，有考虑弄数据分页吗

### ISSUE THREAD

**Issue by Webjiacheng** [airyland/vux#3364]
请问下大神，有考虑弄数据分页吗，因为有时订单这些数据太多，如果一次全部加载出来的话不太友好

**Comment by WilliamLin1990** [comment]
我使用了vue-infinite-loading来做这个分页

**Comment by caozhong1996** [comment]
现在主要精力在于维护现有功能，这个版本不考虑再添加新的feature了
