### ISSUE TITLE
[Bug Report] input组件失焦问题

### ISSUE THREAD

**Issue by scout927** [airyland/vux#3367]
### VUX version
2.9.2

### OS/Browsers version
iOS

### Vue version
2.5.22

### Code

```html
。
```

### Steps to reproduce
。

### What is Expected?
在input组件上能一直输入

### What is actually happening?
目前的input组件只要对绑定的值有操作，比如change事件或者计算，就会输一次失去焦点一次，望解决

**Comment by triggerlife** [comment]
是的，我也也到这种情况了，我版本还是2.9.2。输入一次自动失去焦点

**Comment by yuerdev** [comment]
我也是，安卓是ok的，ios会有这个问题，

**Comment by dongwenxu** [comment]
有什么解决办法么？ 朋友
