### ISSUE TITLE
vue引用vux并适配vm时，弹出框的动画旋转问题

### ISSUE THREAD

**Issue by pianaiqianduan** [airyland/vux#3373]
vue引用vux库，并适配vm时出现问题。我已经解决vux中的样式不转换vm的问题，其他样式都没有问题，就是弹出框弹出和收起的时候总是旋转。望解答

**Comment by pianaiqianduan** [comment]
vw

**Comment by LeesonVictor** [comment]
> vue引用vux库，并适配vm时出现问题。我已经解决vux中的样式不转换vm的问题，其他样式都没有问题，就是弹出框弹出和收起的时候总是旋转。望解答

大神，怎么实现让vux中的样式不转换的啊

**Comment by caozhong1996** [comment]
目前人手精力不够，帮助当前使用者解决bug更为重要，由于时间过去太久，暂时关闭此issue，如果有解决方案也欢迎pr，还需要帮助的话请重开issue，谢谢🙏
