### ISSUE TITLE
[Bug Report] 导入weui.js后confirm不居中

### ISSUE THREAD

**Issue by yuzifu** [airyland/vux#3376]
### VUX version
2.9.2

### OS/Browsers version
Mac10.14/Chrome71

### Vue version
2.5.21

### Code

```html
<template>
  <div>
    <group title="协议内容">
      <cell-box v-for="(item, index) in termsList" :key="index">
        <h3>{{index   1}}.</h3>
        <p class="terms_item">{{item}}</p>
      </cell-box>
    </group>

    <div class="weui-btn-area">
      <x-button type="primary" @click.native="argeeTerms">同意</x-button>
    </div>
  </div>
</template>

<script>
import 'weui'
import weui from 'weui.js'

export default {
  data () {
    return {
      termsList: [ ]
    }
  },
  methods: {
    argeeTerms: function () {
      this.$vux.confirm.show({
        title: '提示',
        content: '确定删除该文件？',
        onConfirm () {

        }
      })
    }
  }
}
</script>
```

### Steps to reproduce
单击页面的“同意”按钮，弹出confirm对话框，但位置不居中，出现在偏左的位置，如果是在手机上浏览，'取消'按钮会被遮住。
如果把import 'weui'以及import weui from 'weui.js'两句移除，confirm对话框是居中的。

导入weui.js的原因是我要使用它提供的gallery来配合uploader。

### What is Expected?
confirm对话框在屏幕居中。

### What is actually happening?
confirm对话框在屏幕偏左的位置显示。

**Comment by airyland** [comment]
样式冲突的问题需要你添加一个 class 覆盖 vux confirm 组件的样式。

**Comment by yqun** [comment]
弹框不居中需要修改confirm样式吗

**Comment by amoter999** [comment]
> 

加一个class类名，如果是使用纯js的话，怎么添加类名？
