### ISSUE TITLE
sticky 不能和 scroller 同时用

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#338]
### Version

v0.1.1
### Android or iOS

全部版本

> For Android issues, please specify the brand, model and browser
### Your Codes

``` html
<scroller>
   <div>
      <br/>
    <br/>
    <br/>
    <sticky>
      <tab :line-width="1">
        <tab-item selected>正在正映</tab-item>
        <tab-item>即将上映</tab-item>
      </tab>
    </sticky>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>  
  </div>
</scroller>

```
### Steps to reproduce the problem

如果用上scroller ，sticky 就失效了

**Comment by NicoCoco1163** [comment]
In XScroll.js, provided a configuration field - 'stickyElements'

```
  // props
  stickyElements: {
    type: String,
    default: '.vux-sticky' // Better to think of '.vux-fixed'
  },
  ...
  // new XScroll() in ready()
  stickyElements: this.stickyElements,
```

it works for me :)

**Comment by airyland** [comment]
@NicoCoco1163 is right. Scroller will add prop:stickyElements to support sticky element.

**Comment by airyland** [comment]
@NicoCoco1163 As I test, XScroller doesnot behavior as I expected when I add `stickyElements` prop, how did you make it, any demo for testing?

**Comment by scoolwang** [comment]
this.$refs.scrollername._xscroll.userConfig.stickyElements = '.vux-sticky'

**Comment by ya00la** [comment]
其实是scroller不支持css的fixed

**Comment by airyland** [comment]
scroller会调整成list-view，因此这个问题暂不会解决。

**Comment by Racaly** [comment]
@airyland 按照 NicoCoco1163 ，修改后确实生效，但是我的sticky在页面的中间，当页面开始滚动时，顶部立即出现sticky，而事实时sticky这时并没有到达顶部，所以页面上出现了两个

**Comment by hujindo123** [comment]
@Racaly  请问你是怎么配置的呢 我怎么找不到那个配置的地方
