### ISSUE TITLE
[Bug Report] x-input组件type=number/tel在某些安卓机上watch不到value值的变化

### ISSUE THREAD

**Issue by benbenlu** [airyland/vux#3380]
### VUX version
2.8.0

### OS/Browsers version
OPPO A83（android7.1.1）

### Vue version
2.6.0-beta.1

### Code

```html
<template>
  <x-input title='人数' type="number" :max='3' 
     v-model='attendNum' placeholder='填写活动人数'
     placeholder-align='left'>
   </x-input>
</template>
<script>
   export default {
      data () {
          attendNum: ''
       },
      watch: {
          attendNum: function (val) {
              alert('val', val)
           }
      }  
    }
</script>
```

### Steps to reproduce
在引入vux组件的项目中，运行以上代码，v-model值无法watch到。在某些安卓机上，如OPPO A83 安卓 7.1.1上以及其他安卓机上都会出现。

### What is Expected?
watch的时候，能够监控到v-model值的变化

### What is actually happening?
v-model值无法watch到

**Comment by fhw** [comment]
同样遇到这个问题，我这边是微信v7.0.3，type=number出现selectionStart的报错，放到chrome里面运行没有问题

**Comment by erekook** [comment]
同样遇到,在小米6和vivo xplay6遇到过

**Comment by caozhong1996** [comment]
请更新到2.9.4
