### ISSUE TITLE
[Feature Request] x-address能否实现仿京东地址选择的样式

### ISSUE THREAD

**Issue by karma-sun** [airyland/vux#3382]
### Existing Component
是

### Component Name
x-address

### Description
x-address能否实现仿京东地址选择的样式

**Comment by caozhong1996** [comment]
目前人手精力不够，帮助当前使用者解决bug更为重要，由于时间过去太久，暂时关闭此issue，如果有解决方案也欢迎pr，还需要帮助的话请重开issue，谢谢🙏
