### ISSUE TITLE
现在vue-cli 升级成3.0以上版本webpack.base.conf.js已经没有了，哪位大佬知道要怎么改呢？

### ISSUE THREAD

**Issue by w316431585** [airyland/vux#3383]
![qq 20190129112830](https://user-images.githubusercontent.com/46295716/51882247-32388e80-23b9-11e9-87c3-0abb626d39d7.jpg)
现在用3.0以上版本脚手架要怎么写入这个呢？哪位大佬知道？

**Comment by w316431585** [comment]
我自己研究出来了就在vue.config.js里面 添加

> 
configureWebpack: config => {
    require('vux-loader').merge(config, {
      plugins: [
        'vux-ui',
        'progress-bar',
        'duplicate-style',
        {
          name: 'less-theme',
          path: 'src/assets/styles/vux_theme.less',
          options: {
            cssProcessorOptions: {
              safe: true,
              zindex: false,
              autoprefixer: {
                add: true,
                browsers: [
                  'iOS >= 7',
                  'Android >= 4.1'
                ]
              }
            }
          }
        }
      ]
    })
  }
> 
就ok了

**Comment by Castleeee** [comment]
能总结一下步骤吗，我一直弄不好。网上资料好像不是很多

**Comment by w316431585** [comment]
使用新版本的cli脚手架工具没有webpack了。你不是要自己创建一个vue.config.js文件

**Comment by airyland** [comment]
关于 vue-cli 3 的支持在测试中，合并到这里 #3430 讨论。
