### ISSUE TITLE
[Bug Report] iphone6 IOS8.3(12F70) 组件样式错乱

### ISSUE THREAD

**Issue by jinchaoxiang** [airyland/vux#3391]
### VUX version
2.9.2

### OS/Browsers version
iphone6 IOS8.3(12F70)

### Vue version
2.5.13

### Code

```html
Cell组件和Tab组件
```

### Steps to reproduce
官方Demo

### What is Expected?
官方 Tab组件 以及Cell样式正常

### What is actually happening?
官方 Tab组件 以及Cell样式错乱

**Comment by airyland** [comment]
iPhone6 搭配 iOS 8.3 有点迷，错乱请提供一下截图。
