### ISSUE TITLE
[Bug Report] Previewer在微信小程序内嵌webview长按会隐藏导致无法保存和发送给朋友

### ISSUE THREAD

**Issue by alicksnake22** [airyland/vux#3396]
### VUX version
2.9.2

### OS/Browsers version
微信小程序内嵌webview

### Vue version
2.6.6

### Code

```html
Previewer在微信小程序内嵌webview长按会隐藏导致无法保存和发送给朋友
```

### Steps to reproduce
1、previewer组件内嵌在小程序webview
2、点击放大查看
3、长按后微信弹出发送给朋友和保存图片
4、松手后previewer组件缩小隐藏导致无法保存和发送给朋友

### What is Expected?
松手后previewer组件不隐藏

### What is actually happening?
松手后previewer组件缩小隐藏导致无法保存和发送给朋友

**Comment by chenquan1992** [comment]
兄弟，请问你解决了吗？同问
