### ISSUE TITLE
组件x-address运行时报错，显示如下图

### ISSUE THREAD

**Issue by hufei1** [airyland/vux#3403]
warning  in ./node_modules/_vux@2.6.5@vux/src/components/x-address/index.vue

(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.

**Comment by hufei1** [comment]
@airyland

**Comment by airyland** [comment]
升级 vux 版本或者 vux-loader 版本。
