### ISSUE TITLE
[Bug Report] x-input click 与 blur 事件冲突

### ISSUE THREAD

**Issue by Breezes1993** [airyland/vux#3405]
### VUX version
2.9.2

### OS/Browsers version
win10,chrome72.0.3626.109(F12 Pixel ios的设备没问题),node 10.8.0,

### Vue version
2.5.2

### Code

```html
x-input组件的index.vue 
clear事件和onBlur事件

```

### Steps to reproduce
npm install vue-cli -g # 如果还没安装
vue init airyland/vux2 projectPath
使用x-input，显示clear图标，输入内容，点击clear图标。

### What is Expected?
会先触发onblur 之后 clear能够执行

### What is actually happening?
会先触发onblur 之后 clear没有执行

**Comment by Breezes1993** [comment]
vuex版本2.2.0

**Comment by Breezes1993** [comment]
onBlur ($event) {
      this.setTouched()
      this.validate()
      setTimeout(() => {
        this.isFocus = false
        this.$emit('on-blur', this.currentValue, $event)
      }, 0)
    }
onBlur事件加个延时，就运行正常了

**Comment by caozhong1996** [comment]
see #3778
