### ISSUE TITLE
popup：pop-mask会盖在popup之上

### ISSUE THREAD

**Issue by GirlSmileToMe** [airyland/vux#341]
### code:

```html
<popup :show.sync="showPopup" height="100%">
      <header class="bar bar-header bar-light">
        <button class="button button-icon back-button"
                @click="showPopup=false">
          <i class="icon icon-keyboard_arrow_left"></i>
        </button>
        <h1 class="title">确认定单</h1>
      </header>
      <div class="scroll-content overflow-scroll has-header">

      </div>
    </popup>
```
![popup01](https://cloud.githubusercontent.com/assets/6104369/16641272/77c8bf02-4431-11e6-8f91-758efcf56b0a.jpg)
![popup02](https://cloud.githubusercontent.com/assets/6104369/16641273/77f05594-4431-11e6-928b-dcb07b555195.jpg)

**Comment by unclay** [comment]
我这边重现不了
`.vux-popup-dialog position: fixed; z-index: 101;`
`.vux-popup-mask.vux-popup-show position: fixed; z-index: 100;`
两个都是固定定位，dialog层级一直大于mask层级，不应该会出现的问题的

**Comment by WilliamDu1981** [comment]
@unclay 跟dialog的父容器定位有关系吗。view-container view scroll-content都是用的绝对定位

**Comment by unclay** [comment]
那试下把绝对定位去掉呢

**Comment by unclay** [comment]
@WilliamDu1981   我在外面加了两层绝对定位也没关系，你看看是不是其他地方影响到了，或者发个完整demo看看

**Comment by WilliamDu1981** [comment]
@unclay 你访问一下 [我的服务器](http://45.78.10.69/),用户名是:admin,密码是:123456,在产品页点购买，然后添加到购物车，然后到购物车，选一个商品，点结算，就可以看到了

**Comment by WilliamDu1981** [comment]
@unclay 你访问一下 [我的服务器](http://45.78.10.69/),用户名是:admin,密码是:123456,在产品页点购买，添加到购物车，然后到购物车，选一个商品，点结算，就可以看到了

**Comment by unclay** [comment]
好吧  我之前写错了 难怪看不到问题，  你先把你的view-container的z-index设置为101用着先，我再看看有什么好办法处理这个问题先

**Comment by airyland** [comment]
@WilliamDu1981 避免在issue暴露ip等服务器信息，可以加入bearychat后私信发送给管理员。

**Comment by WilliamDu1981** [comment]
@airyland :smile: 不怕，这是我自己的服务器，只是用来给你们演示的。
@unclay 可以考虑把popup,toast,alert写成服务，如：
```js
import  Toast form 'toast'

var toast=new Toast(option);
toast.show();

//或者

Toask.show(option);

//再或者

Toast(option);
```

**Comment by WilliamDu1981** [comment]
我自己写了个简单的
```js
<template>
  <div class="modal-backdrop active" transition="slide-up">
    <div class="modal-backdrop-bg"></div>
    <div class="modal-wrapper">
      <div class="modal">
        <slot></slot>
      </div>
    </div>
  </div>

</template>
<script type="text/ecmascript-6">
  import Vue from 'vue';
  import _ from 'lodash';
  var body = document.querySelector('body');
  Vue.component('Modal', {
    el(){
      return document.createElement('div');
    },
    init(){
      let option = this.$options;
      option.template = option.template.replace('<slot></slot>', option.slot);
      option.container = option.container || body;
    },
    destroyed(){
      console.info('modal destroyed')
    },
    methods: {
      open(){
        var container=this.$options.container;
        container.classList.add('modal-open');
        this.$appendTo(container);
      },
      close(callback){
        if(!_.isFunction(callback)){
          callback=_.noop;
        }
        this.$options.container.classList.remove('modal-open');
        this.$remove(callback);
      }
    }
  });

  export default Vue.component('Modal');
</script>
```

**Comment by airyland** [comment]
这其实不是很Vue啊。
组件内部调用Vue也有点奇怪。

之前有想过，可以更Vue一点的

``` js
Vue.use(Toast(options))

// 在任一组件里可以
this.$toast.show(someoptions)
```

**Comment by unclay** [comment]
toast和alert还好一点  基本都是单层， popup现在见过几个需要多层场景，多层才是问题

**Comment by airyland** [comment]
所以如果需要支持这种方式，只能处理简单常用的

**Comment by WilliamDu1981** [comment]
@airyland toast alert confirm可以考虑做成这种的 :smile:

**Comment by airyland** [comment]
想了想，其实把popup放到绝对定位的元素外面应该就正常了？因为链接不能访问，我忘了具体的情况是怎样的了。

``` html
<div>
  POPUP
  OTHER
</div>
```
写成下面这样

``` html
<div></div>
POPUP
```

**Comment by airyland** [comment]
在最近的版本将支持PopupPicker的显示控制，针对这种absolute定位里面的popup问题可以这样解决。
#461 
https://github.com/airyland/vux/blob/master/src/demos/Issue461.vue

**Comment by GirlSmileToMe** [comment]
@airyland 是下面这个意思吗：
```html
<body>
    <app></app>
    <popup></popup>
</body>
```

把popup写在绝对定位元素外面，这太局限了，原因如下：
我是学ionic，仿原生app的效果的，所以从root element开始，就是绝对定位了。而popup的逻辑，是在子视图里面，到顶层view已经隔了好几层了。要放在绝对定位元素的外面，就得是body的子元素才能办到。
或者是我没有看懂你的意思
