### ISSUE TITLE
datatime插件IOS上切换时间格式 显示为NULL

### ISSUE THREAD

**Issue by henry881126** [airyland/vux#3411]

**Comment by henry881126** [comment]
最后自己搞了几个插件，逻辑上 不碰 时间的的这  -

**Comment by airyland** [comment]
没有代码并且无法重现。在有提供进一步的可重现代码前关闭了。

**Comment by yipjianbo** [comment]
兄弟，解决了吗？也有同样的问题

**Comment by yipjianbo** [comment]
```
this.$vux.datetime.show({
        value: vm.chooseYearMonth, // 其他参数同 props
        cancelText: '取消',
        confirmText: '完成',
        clearText: '请选择日期',
        // 只使用到年和月
        format: 'YYYY/MM',
        // 2019/05
        endDate: vm.currentYearMonth,
        // 2019/04
        startDate: vm.registerYearMonth,
        onHide () {
          console.log('关闭时间弹窗')
        },
        onShow () {
          console.log('打开时间弹窗')
        },
        onConfirm (value) {
          // null/05
          console.log('选择的时间是>>>>>>>>', value)
        }
      })
```

-- ios

--- 打开组件后，1.年份那栏没有出现；2. 月份那栏应该只有4和5这两个月份吧，但是展示出来是1-12；

--- 选择确定后，因为年份没有出现，返回值为 null/月份；

--- 在ios上和oppo手机上有兼容问题，取消键右边出现了返回箭头；

安卓手机基本没事；

**Comment by yipjianbo** [comment]
```
this.$vux.datetime.show({
        value: '', // 其他参数同 props
        cancelText: '取消',
        confirmText: '完成',
        clearText: '请选择日期',
        format: 'YYYY-MM',
        endDate: '2019-01-01',
        startDate: '2019-02-01', 
        onHide () {
        },
        onShow () {
        },
        onConfirm (value) {
          console.log('选择的时间是>>>>>>>>', value)
        }
      })
```
有一种情况在ios也会出现，当format: 'YYYY-MM';只要年月时，endDate和startDate仍然必须要传YYYY-MM-DD,（我传的是YYYY-MM）不然就会出现空白，点击确定后返回的空白值为null；

**Comment by henry881126** [comment]
在同一datetime组件上动态切换format的格式会出现这个问题，ios的兼容问题吧。 我在工作中解决这个问题就直接逻辑切换datetime组件了，没碰format的逻辑。我是一个小码农。996你懂的




------------------ 原始邮件 ------------------
发件人: "Ray Yip"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 下午4:13
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "钱亨利"<910114761@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [airyland/vux] datatime插件IOS上切换时间格式 显示为NULL (#3411)



this.$vux.datetime.show({         value: '', // 其他参数同 props         cancelText: '取消',         confirmText: '完成',         clearText: '请选择日期',         format: 'YYYY-MM',         endDate: '2019-01-01',         startDate: '2019-02-01',          onHide () {         },         onShow () {         },         onConfirm (value) {           console.log('选择的时间是>>>>>>>>', value)         }       })  
有一种情况在ios也会出现，当format: 'YYYY-MM';只要年月时，endDate和startDate仍然必须要传YYYY-MM-DD,（我传的是YYYY-MM）不然就会出现空白，点击确定后返回的空白值为null；
