### ISSUE TITLE
[Bug Report] x-input组件中的清除icon，在安卓下点击无效

### ISSUE THREAD

**Issue by vueProgrammer** [airyland/vux#3415]
### VUX version
2.9.2

### OS/Browsers version
所有安卓系统下

### Vue version
2.6.9

### Code

```html
<x-input :show-clear="false" title="银行卡号"  placeholder="请输入卡号" mask="" v-model.trim="cardNo"
               text-align="right" placeholder-align="right" show-clear>
      </x-input>
```

### Steps to reproduce
安卓下添加show-clear属性，出现的清除icon点击无效，不执行清除功能，ios下正常。

### What is Expected?
x-input中的清除icon，在安卓下点击清空input中的value值。
经过测试，将源码对应的@click.native事件修改为@touchend.native事件即可修复该问题，由于业务打包时会重新下载官方库，所以本地修改源码的方式并不能解决该问题，其他方式修复代价大于实际效果，希望可以尽快修复该问题。

### What is actually happening?
x-input中的清除icon，在安卓下点击无效。

**Comment by guohuihot** [comment]
用了这个框架真是入坑了

**Comment by vueProgrammer** [comment]
> 用了这个框架真是入坑了

不兼容webpack4，vue-loader14.0也不兼容，难受的一批

**Comment by kxjhwbb** [comment]
同无效，安卓、浏览器点清除按钮都无效，使用webpack3打包dev也一样

**Comment by Riemann66l** [comment]
可以在slot=right上面重写clear按钮，事件上可以直接调用x-input的clear方法

**Comment by rujptw** [comment]
> 可以在slot=right上面重写clear按钮，事件上可以直接调用x-input的clear方法

能否给个例子呢，谢谢

**Comment by qinyuanqiblog** [comment]
我的是ios 和安卓都不行，望大佬们有空赶紧解决下哈~😃

**Comment by qinyuanqiblog** [comment]
https://github.com/qinyuanqiblog/vux-bug  例子如上，别的不会用哈， 只会用github了， 大佬见谅~ 😃

**Comment by leixu2txtek** [comment]
```javascript
<x-input
        ref="input"
        :max="20"
        :show-clear="false"
        v-model="info"
        placeholder="姓名、手机号、身份证号、SN码"
        class="search-input"
        @on-enter="getBindDwellerList">
        <span slot="right">
          <icon
            v-show="info.length > 0"
            type="clear"
            @click.native="()=>{ $refs['input'].reset() }"></icon>
          <icon
            type="search"
            @click.native="getBindDwellerList"></icon>
        </span>
      </x-input>
```

**Comment by yourVictor** [comment]
引用的组件源码改下以下两个地方就可以了
```
    focusHandler ($event) {
      this.$emit('on-focus', this.currentValue, $event)
-     this.isFocus = true
+     setTimeout(() => {
+      this.isFocus = true
+     }, 10);
      // this.scrollIntoView(500)
      // this.scrollIntoView(5000)
      setTimeout(() => {
        // 因为有1秒的延迟，如果切换了页面，input已经不存在，所以加个判断
        !this.$refs.input || this.$refs.input.scrollIntoViewIfNeeded(false)
        // this.$refs.input.scrollIntoViewIfNeeded()
      }, 1000)
      // $event.target.
    },
    onBlur ($event) {
      this.setTouched()
      this.validate()
-    this.isFocus = false
+     setTimeout(() => {
+       this.isFocus = false
+     }, 10);
      this.$emit('on-blur', this.currentValue, $event)
    },
```

**Comment by YouquanWang** [comment]
我在 x-input.vue 125行  加了@touchstart.native="clear"  试着可以了

**Comment by Riemann66l** [comment]
解决思路有很多
1、重写clear按钮 可以在slot=right上面重写clear按钮，事件上可以直接调用x-input的clear方法
2、引入fastclick插件 （可能会引发输入框触发不灵敏的问题）
3、修改组件源码，将clear按钮触发的事件类型改成touchstart事件

**Comment by rujptw** [comment]
好的，谢谢



------------------ 原始邮件 ------------------
发件人: "Riemann66l"<notifications@github.com>; 
发送时间: 2019年8月10日(星期六) 中午11:20
收件人: "airyland/vux"<vux@noreply.github.com>; 
抄送: "random"<2609274343@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [airyland/vux] [Bug Report] x-input组件中的清除icon，在安卓下点击无效 (#3415)




解决思路有很多
 1、重写clear按钮 可以在slot=right上面重写clear按钮，事件上可以直接调用x-input的clear方法
 2、引入fastclick插件 （可能会引发输入框触发不灵敏的问题）
 3、修改组件源码，将clear按钮触发的事件类型改成touchstart事件

**Comment by zb95120** [comment]
想问一下回退到哪个版本是正常的？
