### ISSUE TITLE
Scroller  的位置如何重置

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#342]
有一个场景是这样

TAB + Scroller 
TAB 有按销量 + 价格 排序

默认是按销量
已经拉取了十页数据

然后再按价格排序

结果 Scroller 里面看不到任何内容，需要上提一下才可以回头最上面

请问一下这个滚动位置如何回到顶部？

**Comment by hubinjie** [comment]
按价格排序，只会显示十条，原来销量内容已经有了100条，所以里面的xs-container 的 translateY很大了，然后现在只有十条，所以内容看不见了。需要手动滚动条 0

**Comment by lichunqiang** [comment]
http://xscroll.github.io/node_modules/xscroll/doc/XScroll.html#scrollTop

看你的描述，你应该在获取数据之后 进行 `reset`

**Comment by hubinjie** [comment]
请问一下，如何调用通过scroller调用  XScroll.scrollTop ?

**Comment by hubinjie** [comment]
OK，我试了一下可以了
`
 this.$refs.scroller._xscroll.scrollTop(0)
`

**Comment by gdutwyg** [comment]
@lichunqiang  我有一个scroller问题， https://github.com/airyland/vux/issues/2077

**Comment by wang1048076313** [comment]
this.$refs.scroller._xscroll.scrollTop(0) 页面确实滚动到顶部了，但里面的xs-container 的 translateY依旧很长，这是个问题，怎么重载
