### ISSUE TITLE
x-number 报错Unable to preventDefault inside passive event listener due to target being treated as passive. 不知道什么原因

### ISSUE THREAD

**Issue by hull123** [airyland/vux#3423]
![1553739221(1)](https://user-images.githubusercontent.com/19661300/55124733-388d8180-5142-11e9-8d12-c39c081b78e0.png)
使用x-number时一直报错 不知道什么原因 百度搜也没有搜到答案，就跑到这来请教了

**Comment by hull123** [comment]
![image](https://user-images.githubusercontent.com/19661300/55124794-78546900-5142-11e9-90aa-e106f023fcf8.png)
这是我的代码 刚刚忘了上传了

**Comment by gouflv** [comment]
#3188

**Comment by hull123** [comment]
我添加了class="needsclick" 还是同样的报错

**Comment by caozhong1996** [comment]
目前不推荐使用fastclik了，坑太多
