### ISSUE TITLE
引入popus时报错

### ISSUE THREAD

**Issue by Sunjian584970824** [airyland/vux#3426]

**Comment by Sunjian584970824** [comment]
Cannot assign to read only property 'exports' of object '#<Object>'；
node_modules\_vux@2.9.2@vux\src\libs\passive_supported.js目录下更改为export default passiveSupported 就不报错了，但是不敢改。。。。

**Comment by knight2018** [comment]
我也是这个报错···已经改为export了，目前还没炸

**Comment by xujun333** [comment]
你们解决了吗？为什么我用popus还是报错

**Comment by knight2018** [comment]
> 你们解决了吗？为什么我用popus还是报错

目前来说，只要是因为commonjs和es6冲突所引发问题，按照上面所述是可以解决的。当然前提你得保证你本地node——modules当中没有commonjs代码了

**Comment by xujun333** [comment]
我改成export default passiveSupported  但是还是报错，

**Comment by xujun333** [comment]
依懒里面也没有CommonJS

**Comment by knight2018** [comment]
> 依懒里面也没有CommonJS

所以你现在的报错是什么

**Comment by xujun333** [comment]
error  in ./node_modules/_vux@2.9.3@vux/src/components/popup/index.vue

Module build failed: Error: Failed to find '../../styles/vux-modal.css'
  in [
    D:\工作文件总\昆山管线\XJJGAPP\XJJGAPP\vue
  ]
    at resolveModule.catch.catch (D:\工作文件总\昆山管线\XJJGAPP\XJJGAPP\vue\node_modules\_postcss-import@11.1.0@postcss-import\lib\resolve-id.js:35:13)

 @ ./node_modules/_vue-style-loader@3.1.2@vue-style-loader!./node_modules/_css-loader@0.28.11@css-loader?{"sourceMap":true}!./node_modules/_vue-loader@13.7.3@vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-d6f0ddb8","scoped":false,"hasInlineConfig":true}!./node_modules/_vux-loader@1.2.9@vux-loader/src/after-less-loader.js!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js?{'modifyVars':{'header-background-color':'#4794ff','tabbar-text-active-color':'#fdc200','cell-default-arrow-color':'#666','button-tab-default-text-color':'#666','weuiTextColorGray':'#666','button-primary-bg-color':'transparent','button-global-border-radius':'@button-global-height/2','button-global-font-size':'28px','button-global-height':'76px','weuiCellHeight':'70px','button-global-margin-top':'30px','cell-default-arrow-width':'10px','weuiCellGapH':'20px','search-placeholder-font-color':'#999'},'sourceMap':true}!./node_modules/_vux-loader@1.2.9@vux-loader/src/style-loader.js!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=styles&index=0!./node_modules/_vux@2.9.3@vux/src/components/popup/index.vue 4:14-1044 13:3-17:5 14:22-1052
 @ ./node_modules/_vux@2.9.3@vux/src/components/popup/index.vue
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@2.11.5@webpack-dev-server/client?http://localhost:8082 webpack/hot/dev-server ./src/main.js


说是未找到css文件 当时我在文件夹上找到了这个css

**Comment by knight2018** [comment]
> error in ./node_modules/_vux@2.9.3@vux/src/components/popup/index.vue
> 
> Module build failed: Error: Failed to find '../../styles/vux-modal.css'
> in [
> D:\工作文件总\昆山管线\XJJGAPP\XJJGAPP\vue
> ]
> at resolveModule.catch.catch (D:\工作文件总\昆山管线\XJJGAPP\XJJGAPP\vue\node_modules_postcss-import@11.1.0@postcss-import\lib\resolve-id.js:35:13)
> 
> @ ./node_modules/_vue-style-loader@3.1.2@vue-style-loader!./node_modules/_css-loader@0.28.11@css-loader?{"sourceMap":true}!./node_modules/_vue-loader@13.7.3@vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-d6f0ddb8","scoped":false,"hasInlineConfig":true}!./node_modules/_vux-loader@1.2.9@vux-loader/src/after-less-loader.js!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js?{'modifyVars':{'header-background-color':'#4794ff','tabbar-text-active-color':'#fdc200','cell-default-arrow-color':'#666','button-tab-default-text-color':'#666','weuiTextColorGray':'#666','button-primary-bg-color':'transparent','button-global-border-radius':'@button-global-height/2','button-global-font-size':'28px','button-global-height':'76px','weuiCellHeight':'70px','button-global-margin-top':'30px','cell-default-arrow-width':'10px','weuiCellGapH':'20px','search-placeholder-font-color':'#999'},'sourceMap':true}!./node_modules/_vux-loader@1.2.9@vux-loader/src/style-loader.js!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=styles&index=0!./node_modules/_vux@2.9.3@vux/src/components/popup/index.vue 4:14-1044 13:3-17:5 14:22-1052
> @ ./node_modules/_vux@2.9.3@vux/src/components/popup/index.vue
> @ ./src/main.js
> @ multi ./node_modules/_webpack-dev-server@2.11.5@webpack-dev-server/client?http://localhost:8082 webpack/hot/dev-server ./src/main.js
> 
> 说是未找到css文件 当时我在文件夹上找到了这个css

目前没有遇到过这种问题，如果是个例，请检查下代码是否正确。如果都不行，那就检查配置吧

**Comment by xujun333** [comment]
我也怀疑我代码错误 所以特意创了个文件 将官网的代码全部复制上去，还是报错

**Comment by kuang0101** [comment]
> 我也怀疑我代码错误 所以特意创了个文件 将官网的代码全部复制上去，还是报错

我也报这个错，你是怎么解决的？
