### ISSUE TITLE
[Bug Report] selector 无反应

### ISSUE THREAD

**Issue by feng-ran** [airyland/vux#3431]
### VUX version
2.9.2

### OS/Browsers version
Android 9  小米8

### Vue version
2.5.20

### Code

```html
 <group title="流程类别">
              <selector @on-change="selectChange()" style="font-size:18px" placeholder="点击限定类别" :value-map="['code_value', 'code_name']" :options="appTypeList" v-model="appType">
              </selector>
            </group>
```

### Steps to reproduce
使用Android 自带的浏览器组建打开带有selector 的vue 页面，点击页面无反应。

### What is Expected?
使用Android 自带的浏览器组建打开带有selector 的vue 页面，点击页面下面应该弹出选择框

### What is actually happening?
使用Android 自带的浏览器组建打开带有selector 的vue 页面，点击页面无反应。控制台也不报错

**Comment by airyland** [comment]
访问 demo 是否正常

**Comment by feng-ran** [comment]
不知道如何使用android自带浏览器组建打开demo，但是使用手机自带浏览器和其他浏览器是没问题的。用android 9 自带浏览器不好用。
