### ISSUE TITLE
[Bug Report] 关于表单 输入框输完，关闭软键盘后，页面自动跳转到最底部。（安卓下）

### ISSUE THREAD

**Issue by yangying2** [airyland/vux#3436]
### VUX version
2.2.0

### OS/Browsers version
安卓

### Vue version
2.5.2

### Code

```html
官方例子x-input
```

### Steps to reproduce
首先填输入2333这个文本框，输入完后关闭安卓机的软键盘，页面自动滚动到最底部

### What is Expected?
页面不应该滚动到最底部

### What is actually happening?
页面自动滚动到最底部

**Comment by zmjm** [comment]
遇到同样问题，两组input中间有两个x-textarea，当输入上面一组input激活软键盘，输入完成关闭键盘，页面就会滚动到下面一组input的位置
