### ISSUE TITLE
[20190409]关于 VUX 的维护和发展

### ISSUE THREAD

**Issue by airyland** [airyland/vux#3439]
VUX 已经恢复正常节奏的维护和更新，积压的 issue 和 pr 也会逐步处理掉。

有比较长的时间没有维护这个项目，表示抱歉。从去年开始从原来公司离职成为独立开发者，成立了公司，组建了工作室，业务范围主要是**小程序开发和电商系统的定制**。在努力恰饭养家糊狗的时段实在是难以抽空出来维护，毕竟不能依靠微小的捐赠来生存。

回头看的话 VUX 的代码并不优秀甚至还有点乱，不过一路折腾过来还是方便了一些使用者。当然坑是有的，也很难在各种条件下解决掉。一个 UI 库也很难满足开发者的所有需求。

在文档左侧可以看到实时运行 vux-loader 的机器数量(匿名统计)，目前每天大概有 8k 台机器在运行，实时在线机器数量在 1.5k 左右。也算一个小成就了。

![image](https://user-images.githubusercontent.com/559179/55782579-2d8e0600-5adf-11e9-946f-3c6c65db3a61.png)

挺长的时间里不敢去看问卷提交的记录，因为里面不少看了压力巨大而且可能会影响心情。

其实如果有实践过相关的开发就可以理解为什么有些组件不支持/无法完美支持某些功能，但是很难要求开发者去考虑，所以很多时候变成了组件库的锅。

文档会慢慢优化，毕竟要达到细致的程序确实需要时间考虑和编写。

我只能说在开源后的至少 800 个日夜里我们(包括参与维护的同学)尽力了。我们并没有因为维护这个库提高了生活质量，相反付出了不少时间精力。规划中是有不少改进或者新的功能的，只是时间精力确实有限难以安排。

我们欣慰于解决了一些同学的问题，也遗憾于无法满足所有开发者的需求。

![image](https://user-images.githubusercontent.com/559179/55782905-db99b000-5adf-11e9-95f9-80ef9e8c2cc9.png)

用同学反映 vux-loader 过于 hack，导致维护上的麻烦。vux-loader 开发初衷是为了减少配置成本，而当初在开发的时候 vue-loader 和 webpack 并没有相关的接口或者扩展可以满足需求，于是使用了相对依赖 vue-loader 的方式，这导致每次 vue-loader 发布大版本，vux-loader 都需要做一次维护。

值得高兴的是最近重新维护 vux-loader 时发现已经不需要使用 hack 的方式了。 目前的 vue-loader 和 webpack 已经可以使用标准的 webpack 配置方式来实现当初 vux-loader 绕了一圈才实现的功能。当初设想的高级功能也可以在近期逐步实现。

如上面所说，近半年业务都是小程序相关，而行业内的组件库总有这些那些没有满足业务的设计或者配置，因此在规划一套新的小程序 UI 组件。和 VUX 的开发方式一样，先开发我们内部需要的组件，再扩充外部反馈需要的组件，这样的产出会更贴近业务需求。

另外补充下：

如果以公司名义捐赠 >= 1000 可以开具普通发票，对公账号请邮箱联系 i#mao.li。

如有业务合作/需求可联系 we#weapp.design，工作室网站是：https://weapp.design/

**Comment by kevinchung1026** [comment]
欢迎回来~

**Comment by Estelle00** [comment]
欢迎回家~

**Comment by bobevans-commits** [comment]
欢迎回来~

**Comment by ghost** [comment]
欢迎归来~

**Comment by xjsaber** [comment]
欢迎归来~

**Comment by co-kevin** [comment]
欢迎回来~

**Comment by yangmeijuan** [comment]
欢迎回来~

**Comment by saxon-yc** [comment]
期待回归

**Comment by Zenquan** [comment]
期待回归

**Comment by hl-dt** [comment]
刚刚使用vux重构完一个前端项目，项目非常接地气和顺手，点赞！
“目前的 vue-loader 和 webpack 已经可以使用标准的 webpack 配置方式来实现当初 vux-loader 绕了一圈才实现的功能。”
---这也是目前很多其他Vue组件库的问题，都需要plugin来支持高级功能（说的就是某蚂蚁design）
能否简单讲讲目前如何在不使用vux-loader的情况下使用？

**Comment by qinyuanqiblog** [comment]
欢迎回来~强势围观~强势蹲坑~

**Comment by qinyuanqiblog** [comment]
欢迎回来，强势围观，强势蹲坑~

**Comment by ghost** [comment]
今天vux网站好像有点问题

**Comment by yangjinzzz** [comment]
vux的官网好像是有点问题了哦 ,

**Comment by jfklg** [comment]
欢迎回来 一直在用 感谢

**Comment by shixx106** [comment]
谁能帮我解答一下啊，我下载了vux 的源码，但是 项目跑不起来 说我 Cannot find module './src/routes.json'，无法自动生成 routes.json 文件，谁能帮我解答一下，问题出在那里

**Comment by maoqxxmm** [comment]
Welcome back~

**Comment by KevinFan520** [comment]
欢迎回来~

**Comment by agileago** [comment]
真高兴

**Comment by agileago** [comment]
现在都是用`vant`顶着，期待`vux`的更新

**Comment by zouzg** [comment]
一度对vux失去了信心，既然回来了，可以一起大家把这个完善的更好。

**Comment by xiaoqiuGit** [comment]
期待更新3.0

**Comment by HaoChenxin** [comment]
期待

**Comment by liuxfu** [comment]
期待

**Comment by waet** [comment]
期待

**Comment by ghost** [comment]
更新进行中吗？又好久没消息了

**Comment by CodLee** [comment]
期待ing~

**Comment by aaawhz** [comment]
欢迎滚回来

**Comment by Gardent** [comment]
欢迎回来~

**Comment by lively-qcy** [comment]
> 现在都是用`vant`顶着，期待`vux`的更新

vant比这个好太多了吧。这么久不更新 谁还等呢
