### ISSUE TITLE
[Bug Report] ios 系统输入法弹出问题

### ISSUE THREAD

**Issue by feng-ran** [airyland/vux#3442]
### VUX version
2.9.3

### OS/Browsers version
ios 11.4

### Vue version
2.6.10

### Code

```html
<group title="名称:">
            <x-input v-model="temp.matterName" placeholder="请输入名称">
              <span v-show="true" slot="label" class="error">*</span>
            </x-input>
          </group>
<group title="业务概述">
            <x-textarea placeholder="请输入业务概述" v-model="temp.memo"></x-textarea>
</group>
```

### Steps to reproduce
点击输入框，弹出输入法，点击输入法中的 完成/Done。
再次点击输入框的时候，输入法不弹出来，必须按住大概0.5秒左右才能弹出输入法。

### What is Expected?
点击输入框，能弹出输入法

### What is actually happening?
必须按住大概0.5秒左右才能再次弹出输入法。

**Comment by hongxb** [comment]
似乎是微信升级的缘故。
不过目前发现原生input点一下可立即唤起输入法

**Comment by mogugit** [comment]
这个问题就是因为focus() 失效（目前发现是ios10以上会有这个问题），导致输入法无法弹出，这其实是ios的安全机制使用单纯的js 是无法调用的，必须要用户手动触发点击事件才能调起输入法，还有就是比较low的解决办法就是提示用户点击label 来调起输入法；

**Comment by huangming1994** [comment]
这个有后续吗

**Comment by huangming1994** [comment]
@feng-ran 暂时可以用@click.native 绑定个focus事件 让点击的时候也focus
