### ISSUE TITLE
[Bug Report] @on-click-clear-icon事件无效

### ISSUE THREAD

**Issue by hbjiankely** [airyland/vux#3443]
### VUX version
2.9.3

### OS/Browsers version
chrome70.0.3510.2      firefox 66.0.1

### Vue version
2.6.10

### Code

```html
<template>
  <div class="input-compontent">
    <div class="header-common">
      <x-header :left-options="{backText: ''}">input</x-header>
    </div>
    <group>
      <x-input
        title="姓名"
        v-model="value"
        type="text"
        placeholder="请输入姓名"
        @on-click-clear-icon="handleClear"
        @on-blur="blurChange"
        is-type="validFrom"
      ></x-input>
    </group>
  </div>
</template>
<script>
import { XHeader, XInput, Group } from 'vux'
export default {
  data () {
    return {
      value: ''
    }
  },
  methods: {
    handleClear () {
      console.log('clear')
    },
    blurChange () {
      console.log('blur')
    }
  },
  components: {
    XHeader,
    XInput,
    Group
  }
}
</script>

```

### Steps to reproduce
输入内容，点击X号，事件不执行
猜测是因为先执行blur事件，叉号隐藏了，导致点击不到叉号

### What is Expected?
可以执行

### What is actually happening?
不执行

**Comment by chenchaoc** [comment]
2.9.0后好像x-input的清空都有问题,暂时回退到2.8.1了...

**Comment by chenchaoc** [comment]
下面的兄弟方法比我的好，在组件源码上修改onBlur事件
      this.setTouched()
      this.validate()
      let timer = setTimeout(() => {
         this.isFocus = false
         clearTimeout(timer)
       }, 10)
      this.$emit('on-blur', this.currentValue, $event)

**Comment by super0211** [comment]
同问

**Comment by Lottid** [comment]
按照大佬指示，已经改源码了

**Comment by shuqiu** [comment]
> 在组件源码上 onBlur事件加上最后一个暂时解决了
> this.setTouched()
> this.validate()
> this.isFocus = false
> this.$emit('on-blur', this.currentValue, $event)
> 加上下面这一行👇👇👇
> **this.isFocus = true**

这个方法有一个问题的，就是出现x后，再移开鼠标，x依旧会显示

**Comment by chenchaoc** [comment]
> > 在组件源码上 onBlur事件加上最后一个暂时解决了
> > this.setTouched()
> > this.validate()
> > this.isFocus = false
> > this.$emit('on-blur', this.currentValue, $event)
> > 加上下面这一行👇👇👇
> > **this.isFocus = true**
> 
> 这个方法有一个问题的，就是出现x后，再移开鼠标，x依旧会显示

好像是的...那就等bug修复了，暂时先用2.8.1

**Comment by Lottid** [comment]
> > 在组件源码上 onBlur事件加上最后一个暂时解决了
> > this.setTouched()
> > this.validate()
> > this.isFocus = false
> > this.$emit('on-blur', this.currentValue, $event)
> > 加上下面这一行👇👇👇
> > **this.isFocus = true**
> 
> 这个方法有一个问题的，就是出现x后，再移开鼠标，x依旧会显示

let timer = setTimeout(() => {
   this.isFocus = false;
   clearTimeout(timer);
}, 10);

再加个定时器

**Comment by nrthyrk** [comment]
The order of events in non-iOS devices is: `mousedown -> blur -> mouseup -> click`, so using `mousedown` instead of `click` in non-iOS and keeping `click` in iOS will solve this issue . Please see my PR.

**Comment by halfvim** [comment]
> The order of events is: `mousedown -> blur -> mouseup -> click`, so using `mousedown` instead of `click` will solve this issue. Please see my PR.

I also noticed that in iOS, this order is not correct. I've modified the code to detect device.

**Comment by worldflyingct** [comment]
https://blog.csdn.net/weixin_43122106/article/details/90293097

**Comment by worldflyingct** [comment]
https://blog.csdn.net/weixin_43122106/article/details/90293097
这里有完美解决方案。
