### ISSUE TITLE
[Bug Report] Loading组件bug

### ISSUE THREAD

**Issue by GHKevins** [airyland/vux#3446]
### VUX version
2.9.3

### OS/Browsers version
win10/chrome73.0

### Vue version
2.5.20

### Code

```html
1、router中commit loading
router.beforeEach(function (to, from, next) {
  store.commit(VUX_LOADING, {isLoading: true});

2、
service.interceptors.request.use(
  config => {
      if(!$vux.loading.isVisible()){//判断loading是否还存在，如果存在则不显示新的loading
        store.commit(VUX_LOADING, {isLoading: true});
      }
```

### Steps to reproduce
1、浏览器请求某个路由url
2、页面初始化，加载数据
3、router中提交了一次显示loading
4、axios请求中提交了一次显示loading

### What is Expected?
只显示一个loading，loading无错位

### What is actually happening?
loading 中间的花型图案，错位了，而且是从右往左显示出来了

**Comment by GHKevins** [comment]
http://1.z9ls.com/t6/701/1555150584x2890174010.png
截图地址

**Comment by airyland** [comment]
检查下是否有样式冲突？

**Comment by GHKevins** [comment]
> 检查下是否有样式冲突？

好的，楼主，这是https://graph.baidu.com/resource/10162edcf4e99e6a1f5d601555293587.jpg
截图，我检查下样式，thx

**Comment by GHKevins** [comment]
> 检查下是否有样式冲突？

楼下，这是我制作的gif动画，
https://graph.baidu.com/resource/101e01e3617b0a2ae9f6301555295376.jpg
实际情况和这个一样，花型图案，从右往左一直在移位（花型图案，我加了绿色背景色）

**Comment by airyland** [comment]
你给截图并不能让我看到有什么样式冲突，需要你自行检查样式。
