### ISSUE TITLE
X-Button组件最好不要占用type属性

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#345]
### Version
All
### Android or iOS
All

### Your Codes 

``` html
<x-button :mini='true' :plain='true' type="default" text="扫一扫" @click="scan('weidian')"><i class='icon-qrcode scan'></i></x-button>
v.s.
<x-button :mini='true' :plain='true' type="button" text="扫一扫" @click="scan('weidian')"><i class='icon-qrcode scan'></i></x-button>
```

### Expected behavior and actual behavior.
在Html规范中，button元素的行为默认为submit，如果想禁止点击button后提交表单，应当指定`type='button'`，但type属性已经被X-Button元素指定为组件参数，无法指定button效果。因此建议更改type名称为其他，如level

**Comment by airyland** [comment]
x-button已经不是原生button了，它本身没有实现原生submit的行为，而理论上也不需要完全遵循原生button的。组件x-button, x-input这样命名就是为了区分于原生组件，只会实现部分原生的属性和行为。

这个更改会影响到所有已经使用的用户并且命名实际也没什么问题，所以针对你的情况建议不要用x-button, 直接写标签更方便。

https://weui.io/#/button

**Comment by dangyuluo** [comment]
哦原来是这么想的
