### ISSUE TITLE
苹果X系列的手机点击input要点好几次才出来键盘，只存在苹果X系列的手机，苹果X系列的有很多小的bug，弹窗弹出来一下子自动关闭了，能排查下嘛？

### ISSUE THREAD

**Issue by PengMengShan** [airyland/vux#3452]

**Comment by mogugit** [comment]
8p input获取焦点 也有这个问题双击或者点击label才能生效？ 安卓们目前没有发现这个问题

**Comment by shixx106** [comment]
谁能帮我解答一下啊，我下载了vux 的源码，但是 项目跑不起来 说我 Cannot find module './src/routes.json'，无法自动生成 routes.json 文件，谁能帮我解答一下，问题出在那里

**Comment by hy20160705** [comment]
我也出现这个问题了 楼上老哥解决了吗
机型 IPhone XR ios12.2
vux2.9.2
1. input框多次点击没有效果，获取不到焦点
2. input框弹出来之后会覆盖调pop中的输入框 pop没有被顶上去
3. input框弹出后 下面的内容被出现向下平移的情况
还会出现popup弹窗出来之后 页面被拉下来一半
附图
[
![WechatIMG7083](https://user-images.githubusercontent.com/20507858/61106529-09f8a400-a4b0-11e9-9a17-aed215b09ca8.jpeg)
![WechatIMG7084](https://user-images.githubusercontent.com/20507858/61106535-0f55ee80-a4b0-11e9-957b-ffc8a6cb3e80.jpeg)
![WechatIMG7085](https://user-images.githubusercontent.com/20507858/61106609-488e5e80-a4b0-11e9-86a1-669ec6b4fb5d.jpeg)

附上我的代码


     ` <div v-transfer-dom>
      <popup
        v-model="showEdit"
        @on-hide="popupClose()"
        position="bottom"
        style="background:#fff"
      >
        <div class="edit-div">
          <h3 style="text-align:center;padding:0.2rem;border-bottom: 1px solid #eee;">价格调整</h3>
          <div style="line-height:1rem;padding:0.5rem 0">
            <div style="text-align:center;">
              <span>液源地：</span>
              <input
                type="text"
                v-model="editInfo.liquidFactoryName"
                disabled
              >
            </div>
            <div style="text-align:center;">
              <span>最近更新时间：</span>
              <input
                type="text"
                class="time-input"
                :value="editInfo.changeTime | changeTime"
                disabled
              >
            </div>
            <div style="text-align:center;">
              <span>今日价格：</span>
              <input
                ref="todayRef"
                style="border:1px solid #eee;"

                v-model="editInfo.buyPrice"
                @on-focus="onFocus"
                @on-blur="onBlur"
              >
            </div>
            <div style="text-align:center;">
              <span>明日价格：</span>
              <input
                style="border:1px solid #eee;"
                type="number"
                v-model="editInfo.tomorrowBuyPrice"
              >
            </div>
            <div style="display:flex;margin-top:0.6rem;justify-content:space-around">
              <XButton
                @click.native="showEdit=false;"
                style="width:2.6rem;height:0.8rem;font-size:14px"
              >取消</XButton>
              <XButton
                @click.native="sureChange()"
                style="width:2.6rem;height:0.8rem;font-size:14px;background:#007aff;color:#fff;margin-top:0"
              >确认修改</XButton>
            </div>
          </div>
        </div>
      </popup>
    </div> `

**Comment by shaomingming008** [comment]
你好我的iphone x微信端页面也出现这个问题  多次点击才会有焦点 
请问你是怎么解决的

**Comment by hy20160705** [comment]
> 你好我的iphone x微信端页面也出现这个问题 多次点击才会有焦点
> 请问你是怎么解决的

我这边排查出来的原因是第三方的FastClick导致的 你看看你有没有用到这个

**Comment by hy20160705** [comment]
> > 你好我的iphone x微信端页面也出现这个问题 多次点击才会有焦点
> > 请问你是怎么解决的
> 
> 我这边排查出来的原因是第三方的FastClick导致的 你看看你有没有用到这个

我这边改了fastclick的源码
![image](https://user-images.githubusercontent.com/20507858/66972885-9b3b7000-f0c8-11e9-85b8-c982565f478a.png)

**Comment by shaomingming008** [comment]
好的  已经解决  thx

**Comment by caozhong1996** [comment]
是否使用了fastclick？如果有的话，现在已经不推荐使用这个插件了，有很多的坑，鉴于时间过去太久，我将关闭和这个issue，还需要帮助的话请重开issue，谢谢!
