### ISSUE TITLE
Calendar组件 引入的时候props报错

### ISSUE THREAD

**Issue by juxiu** [airyland/vux#3454]
![image](https://user-images.githubusercontent.com/27055802/56454915-b849ed00-638a-11e9-879b-829075d5b08b.png)

**Comment by juxiu** [comment]
已解决

**Comment by MonsterGoGoGo** [comment]
请问是如何解决的？

**Comment by MonsterGoGoGo** [comment]
> 已解决

请问方便分享一下解决办法吗，我遇到了同样的问题

**Comment by juxiu** [comment]
![image](https://user-images.githubusercontent.com/27055802/56778312-49481a80-6808-11e9-960b-949b6ebeae08.png)
刚看到
.babelrc文件中 配置如图

**Comment by MonsterGoGoGo** [comment]
> ![image](https://user-images.githubusercontent.com/27055802/56778312-49481a80-6808-11e9-960b-949b6ebeae08.png)
> 刚看到
> .babelrc文件中 配置如图

谢谢

**Comment by MonsterGoGoGo** [comment]
> ![image](https://user-images.githubusercontent.com/27055802/56778312-49481a80-6808-11e9-960b-949b6ebeae08.png)
> 刚看到
> .babelrc文件中 配置如图

最重要的是那个stage-2或者配置成stage-0也可以，没圈上哈哈
