### ISSUE TITLE
可以在HTML里面直接引入vux库吗，后台码农一枚

### ISSUE THREAD

**Issue by FlyArtist** [airyland/vux#3456]
如题，可以用link.src和script.src引入吗

**Comment by FurryWolfX** [comment]
不可以

**Comment by shixx106** [comment]
谁能帮我解答一下啊，我下载了vux 的源码，但是 项目跑不起来 说我 Cannot find module './src/routes.json'，无法自动生成 routes.json 文件，谁能帮我解答一下，问题出在那里

**Comment by LiCeline** [comment]
完全不可以, 依赖loader
