### ISSUE TITLE
真想@ 作者，你放在githup 上的vux 源码根本运行不起来啊，生成路由的文件一直报错，compile.js文件也报错，能麻烦解答下吗

### ISSUE THREAD

**Issue by shixx106** [airyland/vux#3468]

**Comment by airyland** [comment]
请问 issue template 您看了吗？

![image](https://user-images.githubusercontent.com/559179/56942546-f21ab080-6b4d-11e9-840d-1677aa6536b9.png)

您先尊重规则，我才能给予帮助。

希望您能认真提一下问题，“一直报错”，“compile.js文件也报错”，这样的描述只是在浪费大家时间。您怎么运行的，重现步骤给一下很花时间？让维护者来猜来重现？

**Comment by shixx106** [comment]
不好意思，感觉自己鲁莽了，我拉下来项目之后，然后执行代码cnpm install -g phantomjs-prebuilt   然后执行yarn  再执行  yarn dev  再执行  npm run doc:build  就有了下面的报错信息


undefined:1
['format:{hash:9f73763424617817aefadc20c2f82d8cf344509d,authorName:airyland,authorEmail:airyland@qq.com,date:2018-04-29T
02:06:29+08:00},' 'format:{hash:a492017e414682adaf39d8c9a5c8d47b39ea17d6,authorName:jiangling,authorEmail:ftium4@gmail.c
om,date:2018-04-29T22:16:02+08:00},' 'format:{hash:bf7cb9ac9fc5ac375faaa4e533d624f85e9f5d64,authorName:jiangling,authorE
mail:ftium4@gmail.com,date:2018-04-29T22:05:59+08:00},' 'format:{hash:9060fa49c80c8221f74aa698ce120d133c49d259,authorNam
e:zhangzicao,authorEmail:729300423@qq.com,date:2018-04-19T08:55:19+08:00},' 'format:{hash:73355be393cc35995a362afa4f45ea
bacef69129,authorName:airyland,authorEmail:airyland@qq.com,date:2018-04-16T20:47:00+08:00},' 'format:{hash:90694e5cbd838
7508f9e35e0ac64d455c7c5b281,authorName:airyland,authorEmail:airyland@qq.com,date:2018-04-16T03:38:45+08:00},' 'format:{h
ash:09cb46c0f180ab8f4b8a41d58041f8ae272f310a,authorName:airyland,authorEmail:airyland@qq.com,date:2017-11-22T10:41:24+08
:00},' 'format:{hash:e7146d09d030587a17df77629b059

SyntaxError: Unexpected token ' in JSON at position 1
    at JSON.parse (<anonymous>)
    at components.map.forEach.one (C:\vux\docs\component-contributors.js:26:14)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\vux\docs\component-contributors.js:19:54)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vux@2.9.4 doc:build: `node build/build-docs.js && node docs/component-contributors && node docs/compile`
麻烦大神指点下
