### ISSUE TITLE
导航栏能整体拉宽吗？如果设置x-header的高度，只有下方会拉长，里面的内容还是原来的样子

### ISSUE THREAD

**Issue by zhangshaohao** [airyland/vux#3476]

**Comment by zhangshaohao** [comment]
=
![snipaste_20190507_102222](https://user-images.githubusercontent.com/32889619/57267267-057bcd80-70b2-11e9-970f-f924bae3369d.png)

**Comment by kevinchung1026** [comment]
啥需求需要这么高的头部导航栏？这明显是浪费手机上宝贵的可视面积。。。

**Comment by kevinchung1026** [comment]
啥需求需要这么高的头部导航栏？这明显是浪费手机上宝贵的可视面积。。。

**Comment by zhangshaohao** [comment]
因为运行在ipod上，返回按钮比较难点击，现在才用单独把按钮放大解决问题

**Comment by kevinchung1026** [comment]
哦！那你把头部的样式重写一下吧，能覆盖掉组件原有样式即可
