### ISSUE TITLE
网站文档中组件部分能否为每个组件写几句简短的描述

### ISSUE THREAD

**Issue by ifu25** [airyland/vux#3478]
如题，部分组件之前没用过，光看英文名也不知道是个什么控件，随便 Demo 可以看效果，但不说是做什么的还得猜一会，不太方便。

如：`Swipeout`，这个我没用过，看了下不知道干什么用。

**Comment by kevinchung1026** [comment]
都熟悉一遍，多看几眼图标icon，多用用就知道了😝

**Comment by caozhong1996** [comment]
目前人手精力不够，帮助当前使用者解决bug更为重要，由于时间过去太久，暂时关闭此issue，如果还需要帮助请重开issue，谢谢🙏
