### ISSUE TITLE
[Bug Report] XTextarea的title可否不能被删除

### ISSUE THREAD

**Issue by wuqingfeng234** [airyland/vux#3479]
### VUX version
2.9.4

### OS/Browsers version
chrome 74.0.3729.131

### Vue version
2.6.10

### Code

```html
无
```

### Steps to reproduce
1、给XTextarea设置title设置值如"xxxxx"
2、页面上XTextarea的title属性展示为"xxxxx"
3、页面上可以删除XTextarea的title内容"xxxxx"

### What is Expected?
页面上可以删除XTextarea的title内容

### What is actually happening?
页面上不可以删除XTextarea的title内容

**Comment by kevinchung1026** [comment]
你这个需求，其实将`<x-Input>`（标题部分）和`<x-textarea>`（正文部分）一起使用（demo中有示例），是不是更合理一点？
