### ISSUE TITLE
0.1.2版本升级日志

### ISSUE THREAD

**Issue by lagolas** [airyland/vux#348]
0.1.2升级了哪些东西？
[更新]在这里--> #322

**Comment by xiaolongyuan** [comment]
是啊 没有升级日志

**Comment by lichunqiang** [comment]
稍安勿躁，会放出来的

**Comment by aplusgain** [comment]
升级了之后，样式怎么全乱了。需要改其他什么吗？

**Comment by QingWei-Li** [comment]
#322

**Comment by airyland** [comment]
如果升级后有问题不清楚怎么操作的，可以回退一下版本。详细的文档编辑中。

**Comment by moxuandeng** [comment]
升级0.1.2后, 需要自己引入weui了是吗

**Comment by airyland** [comment]
@moxuandeng 并不是。

**Comment by moxuandeng** [comment]
@airyland 升级了之后样式有些乱了, 引入weui的css之后又可以了

**Comment by airyland** [comment]
@lagolas @xiaolongyuan @aplusgain @moxuandeng 
请参照发布日志: https://github.com/airyland/vux/releases/tag/v0.1.2

**Comment by xiaolongyuan** [comment]
@airyland  该如何引入样式呢 ？ 

全局 
```
import 'vux/dist/styles/reset.css'
import 'vux/dist/styles/1px.css'
```

报错

```
ERROR in Cannot find module 'less'
 @ ./~/.npminstall/vux/0.1.2/vux/src/styles/reset.less 4:14-135 13:2-17:4 14:20-141

ERROR in Cannot find module 'less'
 @ ./~/.npminstall/vux/0.1.2/vux/src/styles/1px.less 4:14-133 13:2-17:4 14:20-139
```

**Comment by lichunqiang** [comment]
> npm install less less-loader --save-dev

**Comment by airyland** [comment]
1.css语法是 @import 不是 import
2.安装less, less-loader

**Comment by xiaolongyuan** [comment]
@lichunqiang 

已安装

![image](https://cloud.githubusercontent.com/assets/3142363/16679783/c7d04aa6-451c-11e6-83b2-61dbeb404a47.png)

**Comment by xiaolongyuan** [comment]
@airyland  修改一下

我是在 main.js中引入

```
import 'vux/src/styles/reset.less'
import 'vux/src/styles/1px.less'
```

**Comment by xiaolongyuan** [comment]
@airyland  继续安装less 后 不报错了  但是 组件并没有样式
![image](https://cloud.githubusercontent.com/assets/3142363/16679854/73dc5aa6-451d-11e6-9146-a07315828560.png)
![image](https://cloud.githubusercontent.com/assets/3142363/16679869/94018630-451d-11e6-8d76-1d4d83996833.png)

**Comment by airyland** [comment]
已经废弃 vux.css 所以不要这样引入，而且这样引入打包体积是整个vux库。请单个引入。

``` js
import Group from 'vux/src/components/group'
```

**Comment by xiaolongyuan** [comment]
原来如此 我改成新版的

组件的颜色没办法改变么？

**Comment by airyland** [comment]
@xiaolongyuan 你当然可以覆盖样式。
