### ISSUE TITLE
swiper不能支持移动端ipad么

### ISSUE THREAD

**Issue by YuFy1314** [airyland/vux#3487]
![普通手机下的显示效果正常](https://user-images.githubusercontent.com/24446694/57995151-1e916f00-7af3-11e9-9124-7658a3f859d7.png)

![ipad等大屏幕移动端显示不正常, 不兼容](https://user-images.githubusercontent.com/24446694/57995144-120d1680-7af3-11e9-8606-3e589f0ab6d2.png)

**Comment by wanghui159753** [comment]
这个是他初始化计算错误导致的，在组件顶层元素设置下宽带可以解决

**Comment by YuFy1314** [comment]
> 这个是他初始化计算错误导致的，在组件顶层元素设置下宽带可以解决

噢噢  在包裹这个插件的最外层元素上设置个宽度就好使了?
