### ISSUE TITLE
tab建议

### ISSUE THREAD

**Issue by lagolas** [airyland/vux#349]
tab能否做成可选左右滑动切换的

**Comment by airyland** [comment]
将tab放一个横向的scroller里就可以左右滑动了。

**Comment by airyland** [comment]
还是你指的是对应内容区域滑动切换？这也是支持的。看tab demo。

**Comment by lagolas** [comment]
就是像微信那样，在“微信”界面向左滑切换到“通讯录”，再向左滑切换到“发现”，再向左滑切换到“我”

**Comment by airyland** [comment]
https://vux.li/#!/component/tab

**Comment by lagolas** [comment]
@airyland  这个我看到了，貌似有bug，在手机上滑不了的，貌似在电脑上打开能滑动。
手机是安卓5.1 华为手机 微信最新版

**Comment by airyland** [comment]
在几台机子上测试都没问题，如果滑动不了，那么应该轮播图也不能滑动吧？

**Comment by lagolas** [comment]
轮播能滑动，这个tab滑动的，有一个现象，就是滑动的时候内容里面的文字切换了，上面的bar没跟着动，

**Comment by lagolas** [comment]
就是那个 “精选”“美食”“电影”“酒店”“外卖”，这个滑动的时候，里面的文字变动了，但是没有左右滑的效果，只是单纯的文字变换，上面的bar也不动

**Comment by airyland** [comment]
点击其他tab，会有bar左右滑动的效果吗？

**Comment by lagolas** [comment]
滑动都没有效果的

**Comment by lagolas** [comment]
swiper组件的效果正常

**Comment by lagolas** [comment]
scrollbar里面的左右滑动上下滑动也都正常

**Comment by lagolas** [comment]
只有tab的左右滑动没效果，所以才纳闷为什么没有这一块

**Comment by lagolas** [comment]
华为畅享5 安卓5.1 微信6.3.18
