### ISSUE TITLE
[Bug Report] input聚焦之后，页面滚动导致看不到聚焦的input

### ISSUE THREAD

**Issue by baihemax** [airyland/vux#3492]
### VUX version
2.9.4

### OS/Browsers version
安卓/微信浏览器

### Vue version
2.6.10

### Code

```html
<x-input placeholder="请输入电话"
style="width:100px;padding-left: 0px;"
:show-clear="false" 
:max="11"
mask="99999999999"
v-model="contact1Phone"
placeholder-align="right" 
text-align="right"></X-input>
         
```

### Steps to reproduce
https://vux.li/demos/v2/?x-page=v2-doc-home#/
点击input框即可重现，官方demo也有这个问题

### What is Expected?
input聚焦之后，使聚焦的input处于页面中间

### What is actually happening?
input聚焦之后，页面滚动导致看不到聚焦的input

**Comment by s641135196** [comment]
我也遇到这个问题了， 就是在x-input输入文字会滚动到最底端，导致看不到文本框，  官官的例子有同样的问题。 你解决子吗
