### ISSUE TITLE
[Feature Request] swipeout-button能否增加一个disabled

### ISSUE THREAD

**Issue by ceemomx** [airyland/vux#3493]
### Existing Component
是

### Component Name
swipeout-button

### Description
有的时候需要划出的菜单部分按钮禁用，是否能在swipeout-button加一个disabled属性

**Comment by kevinchung1026** [comment]
1. 找到文件`vux/src/components/swipeout/swipeout-button.vue`，修改源码
2. `<button>`标签新增`:disabled="disabled"`，另外`:style`内部新增`opacity: disabled ? '0.4' : '1'`
3. 往`js`中的`props`增加 `disabled:  {type: Boolean, default: false}`
4. 在业务代码中，`swipeout-button`增加属性`:disabled` 绑定给你的判断条件即可

我也提PR了~

**Comment by ceemomx** [comment]
> 1. 找到文件`vux/src/components/swipeout/swipeout-button.vue`，修改源码
> 2. `<button>`标签新增`:disabled="disabled"`，另外`:style`内部新增`opacity: disabled ? '0.4' : '1'`
> 3. 往`js`中的`props`增加 `disabled:  {type: Boolean, default: false}`
> 4. 在业务代码中，`swipeout-button`增加属性`:disabled` 绑定给你的判断条件即可
> 
> 我也提PR了~

哈 谢了 不过因为是多人一起开发 修改源码的方式 有点麻烦，暂时是根据业务内容用v-if来判断显示不显示
不过还是希望A神能增加这个功能

**Comment by caozhong1996** [comment]
下版本添加
