### ISSUE TITLE
如何设置指定日期不可以选择？

### ISSUE THREAD

**Issue by doujiaomifan** [airyland/vux#3496]
比如设置：2019-05-27,2019-04-09,2019-03-08  这三天不能选择，

使用场景：用户查询流水时候，如果哪天没有数据，就设置哪天的日期不可以选择，谢谢，请加上这个功能吧，需求量很大的

**Comment by kevinchung1026** [comment]
Datetime 组件吗？
compute-days-function 可以动态设置日期列表，将无数据的日期过滤掉
