### ISSUE TITLE
[Bug Report] 关于 【如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件】 的问题

### ISSUE THREAD

**Issue by ngxlua** [airyland/vux#3498]
### VUX version
2.9.4

### OS/Browsers version
OSX 10.12 

### Vue version
2.6.10

### Code

```html
import { AjaxPlugin } from "vux"
```

### Steps to reproduce
1. 根据官方文档使用脚手架
2. 引入 wechatplugin 

### What is Expected?
解决提示：

如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件....

### What is actually happening?
始终提示 【如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件】

我参阅了历史 issue 未能解决问题

**Comment by ngxlua** [comment]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/31426367/58482859-c82acd00-8191-11e9-8445-b2b7e79089c1.png">


期待回复， 感谢作者

**Comment by gogoJava** [comment]
遇到同样问题

**Comment by 849511441** [comment]
要不就只有局部引用，要不就是在main.js 引用用绝对路径 import AjaxPlugin  from    "vux/src/plugs/..." 这样

**Comment by caozhong1996** [comment]
see #3778
