### ISSUE TITLE
v0.1.3 概要

### ISSUE THREAD

**Issue by airyland** [airyland/vux#350]
+ [x] 针对多个用户对`tabbar`和`vuex`使用的疑惑，提供参考demo
+ [x] 放出`step`组件(@graysheep 很久前已经合并，但并未显示在demo里)
+ [x] <del>修复v0.1.2 Popup引入的popup关闭卡顿问题  #351 </del> 无法重现
+ [x] <del>修复Safari上Toast的问题  #352 </del> 无法重现

其他等想到再补充..

**Comment by WilliamDu1981** [comment]
:+1:

**Comment by zhonggedan** [comment]
good

**Comment by zhonggedan** [comment]
大神哥哥 “ 针对多个用户对tabbar和vuex使用的疑惑，提供参考demo”  这个啥时候出？ 如饥似渴了

**Comment by hubinjie** [comment]
啥时候发布v0.1.3呢？

**Comment by agileago** [comment]
@airyland 

1 . 弹出组件是否需要加上一个`prop` `disable-scroll` 禁用背景滚动？ 这个功能需求应该相当普遍
(在背景mask阻止一下`touchmove`事件)

2. message功能觉得不应该是一个`vue` 组件,应该是一个`util`，就像`ant-design`里面的message组件，直接提供一个message对象，提供一些方法，这样更加的灵活，比如 
```javascript
import message from 'message'

message.show(content, duration, callback)
```

**Comment by airyland** [comment]
@agileago 
1.可以尝试来个PR
2.见 #391 这样处理是为了命名空间统一，方便管理，也不需要每个路由都引入一次

**Comment by agileago** [comment]
message组件用起来真的很难受， 比如在实例化`App`组件之前可能会检查一些参数正确性，这个时候需要用到message组件进行提示，在一些小表单验证的时候需要message的时候... 所以我觉得message组件应该学习`ant-design`的做法 [message](http://ant.design/components/message),这样符合常规使用，第一条我提个pr
