### ISSUE TITLE
[Bug Report]Tab Component 异步加载数据vfor渲染tab-item报错

### ISSUE THREAD

**Issue by Indomi** [airyland/vux#3500]
### VUX version
2.2.0

### OS/Browsers version
5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36

### Vue version
2.5.2

### Code

```html
<template>
<tab active-color="#f86093" custom-bar-width="50px">
        <tab-item v-for="(item, idx) in menuHeader" :key="idx" :selected="activeMenu === idx" @on-item-click="handleMenuChange">{{ item }}</tab-item>
</tab>
</template>

```

### Steps to reproduce
created钩子函数内请求后端改变menuHeader的值，然后控制台报错

### What is Expected?
正确渲染顶部tab栏

### What is actually happening?
未渲染页面，控制台报错 [Vue warn]: Error in render: "TypeError: Cannot read property 'length' of undefined"

**Comment by kevinchung1026** [comment]
tab 标签上写个 v-if="menuHeader.length" 试试
