### ISSUE TITLE
在iOS手机上，同一个页面中有多个x-input 和多个 popup-picker 时，输入框聚焦时，键盘输入的内容不显示

### ISSUE THREAD

**Issue by wangfeng211** [airyland/vux#3503]
在iOS手机上，同一个页面中有多个x-input 和 多个popup-picker或者x-address，input输入框聚焦时，键盘输入的内容在x-input 上不显示

**Comment by jiangtu93** [comment]
遇到同样的问题，是在ipod上出现，除了输入内容在x-input上不显示，且无法scrollintoview自动调整到可视区域

**Comment by jiangtu93** [comment]
参考bug 3287 已解决
