### ISSUE TITLE
popup-picker控件在收起时停顿了100毫秒

### ISSUE THREAD

**Issue by camxi** [airyland/vux#351]
### Version
0.1.2

### Android or iOS

iOS 9.1.3 微信浏览器 / iPhone6

### Your Codes 

-

### Steps to reproduce the problem
github上提供的版本的popup-picker在点击“完成”收起时，停顿了100毫秒左右，而且有个黑色块闪现了一下。但在线的demo (https://vux.li/#!/demo) 里的popup-picker就没这个问题。

**Comment by airyland** [comment]
Hi，在iPhone6s下重现不了停顿和黑色块闪现的问题，需要相关代码或者demo方便排查。
