### ISSUE TITLE
[Bug Report] swiper点击跳转链接地址无效

### ISSUE THREAD

**Issue by YuFy1314** [airyland/vux#3513]
### VUX version
2.9.4

### OS/Browsers version
windows10/谷歌 74.0.3729.169（正式版本） （64 位）

### Vue version
2.5.2

### Code

```html
在页面中引入swiper, 别的功能都好使, 
<swiper loop auto :aspect-ratio="180/360" :class="'swiperBox'" :list="urlList" dots-position="center" :show-dots="false"></swiper>

urlList: [], // 轮播图数据

数据里面是按照官方文档写的
{
url:
img:
title:
}
```

### Steps to reproduce
在url里面写入百度链接(www.baidu.com)之后, 
在页面中点击图片跳转之后地址变成这样了:
点击之前的地址:http://192.168.0.18:8080/#/home
点击之后的地址:http://192.168.0.18:8080/#/www.baidu.com
url被限制在了当前项目路径下

### What is Expected?
点击图片跳转去百度
地址不会被限制

### What is actually happening?
地址被限制在当前路径下

**Comment by kevinchung1026** [comment]
url拼接有问题吗？

**Comment by YuFy1314** [comment]
> url拼接有问题吗？

点击跳转我需要的是www.baidu.com而不是http://192.168.0.18:8080/#/www.baidu.com
我已经通过vue路由的方式解决了

**Comment by JiangBei007** [comment]
你路径写成  http://www.baidu.com或者https://www.baidu.com
不能直接写成  www.baidu.com

**Comment by YuFy1314** [comment]
> 你路径写成 [http://www.baidu.com或者https://www.baidu.com](http://www.baidu.com%E6%88%96%E8%80%85https://www.baidu.com)
> 不能直接写成 [www.baidu.com](http://www.baidu.com)

该问题已解决, 多谢告知
