### ISSUE TITLE
[Bug Report] previewer组件支持标题显示

### ISSUE THREAD

**Issue by m2maomao** [airyland/vux#3515]
### VUX version
2.9.4

### OS/Browsers version
mac/chrome

### Vue version
2.6.10

### Code

```html
```

### What is actually happening?
我也遇到了同样的问题，图片上面需要显示标题，而组件只提供了before,after,都是在顶部显示的，更要命的是标题可以点击跳转到其他页面，我看photoswipe支持html但是previwer只支持src传图，下个版本会支持吗？

**Comment by kevinchung1026** [comment]
这个需求，用`slot`就能实现，我在原 demo 上写的，代码如下：
```
<previewer :list="list" ref="previewer" :options="options" @on-index-change="logIndexChange">
  <template slot="button-before">
    <a href="https://vux.li">我是标题</a>
  </template>
</previewer>
```
样式自己调整，`href`自己定义即可
