### ISSUE TITLE
官网有问题吗？

### ISSUE THREAD

**Issue by nalone** [airyland/vux#3516]
1. https://doc.vux.li/issue-generator/ 这个地址无法访问，可能很慢，算了不打开了
2. 在官网的如何提交 issues ，并没有写怎么提交，找了半天只能来这里反馈了
![图片](https://user-images.githubusercontent.com/1676764/59169333-765c4c80-8b6c-11e9-99fe-5aa246d0051d.png)

3. 官网的图片怎么都是破图？换了好些网络环境，都是如此，一直在用vux.li，本想贡献点钱，感觉这个项目是不是要挂了，图都是破的，又犹豫了
![图片](https://user-images.githubusercontent.com/1676764/59169305-59277e00-8b6c-11e9-9dd5-e3cbba273350.png)

**Comment by kevinchung1026** [comment]
1、链接我这边能正常打开
2、如果能打开 https://doc.vux.li/issue-generator/#/zh-CN 就能正确提交issue
3、图片缺失的问题，我也有。但在 Chrome 里面右键审查元素，又能单独打开图片链接，然后刷新一下官网页面，图片就正常显示了
