### ISSUE TITLE
[Feature Request] popup-picker 区分开关闭 和 取消  

### ISSUE THREAD

**Issue by gwshawsh** [airyland/vux#3517]
### Existing Component
是

### Component Name
component/popup-picker 

### Description
popup-picker  无法区分取消操作和关闭操作。点击遮罩和关闭都能隐藏popup-picker ，但是业务场景往往需要区分关闭 和取消操作。例如： 右上角按钮代表确认，左上角按钮代表撤销，点遮罩代表不操作。

**Comment by kevinchung1026** [comment]
目前只支持：

`@on-hide` | (closeType) `true`表示`confirm`(选择确认), `false`表示其他情况的关闭 | 弹窗关闭时触发
-- | -- | --
