### ISSUE TITLE
XInput 清除按钮点击不生效

### ISSUE THREAD

**Issue by MsAbby** [airyland/vux#3519]
<group>
          <x-input title="我的邮箱"  placeholder="选填 @qq.com" v-model="emailAddress" ref="emailAddress" @on-click-clear-icon="clearEmailAddress" value-text-align="right" name="email" is-type="email" max="64" placeholder-align="right" text-align="right"></x-input>
</group>
清除按钮点击后就消失了，没有任何反应

**Comment by kevinchung1026** [comment]
https://github.com/airyland/vux/issues/3415#issuecomment-493285893

**Comment by worldflyingct** [comment]
https://blog.csdn.net/weixin_43122106/article/details/90293097
这里有完美解决方案。
