### ISSUE TITLE
loading +  toast 同时用 toast 显示不正常

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#352]
loading + toast 

微信端 

先显示LOADING  文字是‘加载中...’
然后加载数据完了，
再显示 toast 文字是‘已经没有了 ’  type = 'text'

然后你会发现在这个toast的文字 显示在loading中的 加载中...的位置, 下面的图标也是没有的，是一个正方形外观

整体上显示很比别扭

模拟器上面是正常的

**Comment by airyland** [comment]
请说明 版本 手机平台 型号。

**Comment by hubinjie** [comment]
版本v.0.1.2
手机平台：IOS 9.X  安卓 4.4.2 
微信
<img src="http://m.meihu365.com/uploadfile/QQ20160711-0@2x.png">

**Comment by airyland** [comment]
本地无法重现。需要提供下版本，组件的加载方式，代码。

**Comment by airyland** [comment]
Hi 如果看到审查一下相应的样式，看是哪个样式影响到
