### ISSUE TITLE
Cell组件title 传模板字符串失效

### ISSUE THREAD

**Issue by ghost** [airyland/vux#3523]
要提交 issue 的库：VUX
Issue 类别：Bug
项目版本：2.9.4
操作系统版本 / 浏览器版本：win10 / chrome  74.0.3729.169
Vue 版本：2.6.10
代码：
`<group label-width="5em" gutter="0" title-color="blue">
     <cell :title="``<span style='color:red;'>* </span> ${'随便'}``" is-link></cell>
</group>`

重现步骤：粘贴上述代码即可
期待的行为：页面上出现红色*
实际的行为：直接把代码显示出来了
解决办法：
修改Cell组件第18行代码，将
`<slot name="title">{{ title }}</slot>
改为
<slot name="title">
  <label v-html="title"></label>
</slot>`

**Comment by kevinchung1026** [comment]
你这个需求不用改组件源码，这么写就行：
```
<group label-width="5em" gutter="0" title-color="blue">
  <cell is-link>
    <span slot="title">
      <span style="color:red;">*</span>随便
    </span>
  </cell>
</group>
```

**Comment by ghost** [comment]
收到，谢谢，已经按照模板里在placeholder加必填字那么处理了，看着清爽些------------------ 原始邮件 ------------------
发件人: "Kevin"<notifications@github.com>
发送时间: 2019年6月17日(星期一) 下午5:47
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "Teeeeeequila"<3211314336@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [airyland/vux] Cell组件title 传模板字符串失效 (#3523)



你这个需求不用改组&#x4EF6;源码，这么写就行：
 <group label-width="5em" gutter="0" title-color="blue">   <cell is-link>     <span slot="title">       <span style="color:red;">*</span>随便     </span>   </cell> </group>  
&mdash;

**Comment by YZBGitHub** [comment]
别的组件的title支持这种占位标签，<i class='vux-blank-full'></i>。
但是cell 的title不支持这种方式，页面上会直接显示 成字符串 <i class='vux-blank-full'></i>

**Comment by YZBGitHub** [comment]
@Teeeeeequila
