### ISSUE TITLE
checker

### ISSUE THREAD

**Issue by siny-yao** [airyland/vux#3526]
### VUX version
2.9.4

### OS/Browsers version
Windows10/chrome 75.0.3770.90  

### Vue version
2.5.20
2.6.10

### Code

```html
     <checker v-model="period" default-item-class="vux-checker-default" selected-item-class="vux-checker-selected"
              disabled-item-class="vux-checker-disabled">
              <checker-item :value="titem" v-for="(titem,tindex) in periods" :key="tindex" :disabled="titem.disabled"
                @on-item-click="selectedTime">{{titem.value}}</checker-item>
</checker>
```

### Steps to reproduce
1.在checker-item上动态绑定disabled属性

### What is Expected?
disabled=true时checker-item不能被点击

### What is actually happening?
disabled=true时checker-item有disabled相关css，但依旧能被点击

**Comment by kevinchung1026** [comment]
请提供一下你的数据

**Comment by siny-yao** [comment]
> 请提供一下你的数据

 peroids:[
        {
          disabled: false,
          key: '12121',
          value: '第一期'
        },
        {
          disabled: true,
          key: '12122',
          value: '第二期'
        },
        {
          disabled: true,
          key: '12123',
          value: '第三期'
        },
         {
          disabled: true,
          key: '12124',
          value: '第四期'
        }
      ]

**Comment by kevinchung1026** [comment]
用你的数据，后面三个都选不中，点击的话，period也不会监听到，这个没问题啊

**Comment by siny-yao** [comment]
> 用你的数据，后面三个都选不中，点击的话，period也不会监听到，这个没问题啊

问题出在给checker-item绑定的事件上
我给checker绑定了一个值period
给checker-item绑的定了@on-item-click事件
当设置disabled=true时，点击disabled状态的item，依旧能够在控制台输出value的值
并且我发现disabled=false的时候控制台输出log中value和period值不一样，period总是上一个选中的item的value值
因为我做的是上下联动的效果，所以有问题

**Comment by kevinchung1026** [comment]
> 当设置disabled=true时，点击disabled状态的item，依旧能够在控制台输出value的值

@on-item-click事件，是当前项被点击时触发，和disabled的值无关

> 并且我发现disabled=false的时候控制台输出log中value和period值不一样，period总是上一个选中的item的value值

可点击的item在选中时是打印同步的话，加个`nextTick`就行了，比如：
```
    selectedTime (itemValue, itemDisabled) {
      console.log('itemValue: ' + itemValue.value)
      this.$nextTick(() => {
        console.log('period: ' + this.period.value)
      })
    }
```

**Comment by siny-yao** [comment]
> > 当设置disabled=true时，点击disabled状态的item，依旧能够在控制台输出value的值
> 
> @on-item-click事件，是当前项被点击时触发，和disabled的值无关
> 
> > 并且我发现disabled=false的时候控制台输出log中value和period值不一样，period总是上一个选中的item的value值
> 
> 可点击的item在选中时是打印同步的话，加个`nextTick`就行了，比如：
> 
> ```
>     selectedTime (itemValue, itemDisabled) {
>       console.log('itemValue: ' + itemValue.value)
>       this.$nextTick(() => {
>         console.log('period: ' + this.period.value)
>       })
>     }
> ```

原来是这样，我以为设置disabled的时候是不会触发点击事件的，问题解决了，谢谢
