### ISSUE TITLE
[Bug Report] toast 字体颜色变成黑色

### ISSUE THREAD

**Issue by asasdasasd** [airyland/vux#3528]
### VUX version
2.9.4

### OS/Browsers version
macOS 10.14/微信开发者工具

### Vue version
2.6.10

### Code

```html
import {AlertPlugin, WechatPlugin,ToastPlugin} from 'vux'

Vue.use(ToastPlugin, {position: 'middle'})

this.$vux.toast.text(“test”)

```

### Steps to reproduce
代码引入之后，this.$vux.toast.text(“test”)文字是黑色的，很难看

### What is Expected?
toast文字为白色

### What is actually happening?
toast文字为黑色

**Comment by kevinchung1026** [comment]
没有复现哦，我这还是白字灰底

**Comment by asasdasasd** [comment]
@kevinchung1026 问题找到了，文字颜色被全局样式覆盖了，不过全局样式怎么会覆盖局部的

**Comment by kevinchung1026** [comment]
全局样式的选择器优先级更大导致的吧？

**Comment by asasdasasd** [comment]
@kevinchung1026 全局的优先级怎么会高于局部的，这该怎么调？

**Comment by caozhong1996** [comment]
目前人手精力不够，帮助当前使用者解决bug更为重要，由于时间过去太久，暂时关闭此issue，如果还需要帮助请重开issue，谢谢🙏
