### ISSUE TITLE
v-pie怎么显示提示文字

### ISSUE THREAD

**Issue by huangxiangxiang-todo** [airyland/vux#3531]

**Comment by kevinchung1026** [comment]
你是想要这个？

提示信息 | Tooltip | 当鼠标悬停在某个点上时，会以提示框的形式显示当前点对应的数据的信息，比如该点的值，数据单位等，帮助用户从图表中获取具体的数据信息。
-- | -- | --

**Comment by kevinchung1026** [comment]
https://antv.alipay.com/zh-cn/f2/3.x/demo/component/tooltip-custom.html

**Comment by huangxiangxiang-todo** [comment]
是f2饼图中的pie-label，不知道怎么显示出来！
https://www.yuque.com/antv/f2/pie-label

**Comment by huangxiangxiang-todo** [comment]
> https://antv.alipay.com/zh-cn/f2/3.x/demo/component/tooltip-custom.html
是f2饼图中的pie-label，不知道怎么显示出来！
https://www.yuque.com/antv/f2/pie-label

**Comment by kevinchung1026** [comment]
需要自己封装哦，用 v-charts 吧，简单高效
https://v-charts.js.org/#/pie
