### ISSUE TITLE
vux初学请教 swiper中p标签隐藏不掉

### ISSUE THREAD

**Issue by weycm** [airyland/vux#3534]
![image](https://user-images.githubusercontent.com/37738255/59892405-76c9d280-940b-11e9-873f-44ecbef5d7cb.png)

**Comment by weycm** [comment]
![image](https://user-images.githubusercontent.com/37738255/59893055-230cb880-940e-11e9-842c-44a8f35090fb.png)

**Comment by kevinchung1026** [comment]
你的需求是隐藏图片左下角的文字吧？
如果是的话，图片列表的 title 字段不写就行了
