### ISSUE TITLE
Selector 组件支持on-selected事件

### ISSUE THREAD

**Issue by heyangjiedd** [airyland/vux#3536]
selector仅支持on-change，导致在设置初始值时触发该事件。

**Comment by kevinchung1026** [comment]
`selector`组件初始化时，如果`v-model`监测的变量初始值为空字符串，就不会触发`on-change`事件，否则都会触发。
不过你具体的业务场景和需求是啥？

**Comment by heyangjiedd** [comment]
需要给selector赋一个列表里面的值而不触发on-change事件。业务场景是用户手动选择触发业务逻辑，自动赋值不触发业务逻辑。刚才查看了您写的源码，是用watch监听触发的on-change。可以把触发on-change条件改成了select标签的change事件触发，已解决问题。谢谢您的回复。




------------------ 原始邮件 ------------------
发件人: "Kevin"<notifications@github.com>;
发送时间: 2019年6月24日(星期一) 中午11:09
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "贺杨杰"<1059320200@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [airyland/vux] Selector 组件支持on-selected事件 (#3536)




selector组件初始化时，如果v-model监测的变量初始值为空字符串，就不会触发on-change事件，否则都会触发。
 不过你具体的业务场景和需求是啥？

**Comment by kevinchung1026** [comment]
> 业务场景是用户手动选择触发业务逻辑，自动赋值不触发业务逻辑。

那`v-model`监测的变量初始值设为空字符串就好了

**Comment by heyangjiedd** [comment]
比如说，表单编辑，初始值不为空的。






------------------ 原始邮件 ------------------
发件人: "Kevin"<notifications@github.com>;
发送时间: 2019年6月24日(星期一) 中午11:26
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "贺杨杰"<1059320200@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [airyland/vux] Selector 组件支持on-selected事件 (#3536)



 
业务场景是用户手动选择触发业务逻辑，自动赋值不触发业务逻辑。
  
那v-model监测的变量初始值设为空字符串就好了
