### ISSUE TITLE
[Bug Report] checker样式不出来？

### ISSUE THREAD

**Issue by Bobzhangfighting** [airyland/vux#3544]
### VUX version
2.9.4

### OS/Browsers version
谷歌

### Vue version
2.6.10

### Code

```html
 <p>发票抬头</p>
            <checker v-model="dataList" radio-required default-item-class="defalut-class" selected-item-class="selected-class">
                <checker-item value="person"><span>个人</span></checker-item>
                <checker-item value="company"><span>公司</span></checker-item>
            </checker>
```

### Steps to reproduce
没有圆圈圈出来，只有个人公司并排在一起

### What is Expected?
期待radio圆圈圈出来

### What is actually happening?
radio圆圈圈就是出不来

**Comment by kevinchung1026** [comment]
`default-item-class="defalut-class" selected-item-class="selected-class"`，这里的自定义样式你是怎么写的？
