### ISSUE TITLE
关于popup-picker 组件缺少样式问题

### ISSUE THREAD

**Issue by ww33331000** [airyland/vux#3545]
popup-picker 控件缺少样式如下：
.vux-cell-box:not(:first-child):before {
    right:0px!important;
    width: unset!important;
}

缺少该样式导致在为微信端自带浏览器展示的时候可以向右拖动。

**Comment by kevinchung1026** [comment]
本来就没有问题啊

**Comment by ww33331000** [comment]
看一下我的截图，我修改的是.vux-cell-box:not(:first-child):before  的样式，如果没有加就会出现底下的border向右边突出一点，在微信自带浏览器上才看得到，pc上浏览器的手机模式是看不出来的。对比一下.vux-cell-box:not(:first-child):before 的样式才知道少了什么。


![2](https://user-images.githubusercontent.com/40596815/60229221-bf7c0280-98c7-11e9-9837-580a7a220477.png)
![3](https://user-images.githubusercontent.com/40596815/60229223-c0149900-98c7-11e9-8739-aeef3a1982e6.png)
![1](https://user-images.githubusercontent.com/40596815/60229224-c0149900-98c7-11e9-8f7b-9cca0e810e51.png)

**Comment by kevinchung1026** [comment]
没有代码，复现不了你的问题

**Comment by ww33331000** [comment]
<template>
  <div>
    <div>
      <popup-picker :title="'a'" :show-name="true" :data="list" v-model="value"  @on-hide="onHide"  :placeholder="'请选择'"></popup-picker>
      <popup-picker :title="'b'" :show-name="true" :data="list" v-model="value"  @on-hide="onHide"  :placeholder="'请选择'"></popup-picker>
      <popup-picker :title="'c'" :show-name="true" :data="list" v-model="value"  @on-hide="onHide"  :placeholder="'请选择'"></popup-picker>
      <popup-picker :title="'d'" :show-name="true" :data="list" v-model="value"  @on-hide="onHide"  :placeholder="'请选择'"></popup-picker>
      <x-input :required="true" title="证件号码：" mask="999999999999999999" :show-clear="false" v-model="cardVal" :min="8" :max="18" :should-toast-error="false" placeholder="请输入证件号码"></x-input>
      <x-input :required="true" title="姓名：" v-model="nameVal" :max="4" :show-clear="false" is-type="china-name" placeholder="请输入姓名" :should-toast-error="false" ></x-input>
      <x-input :required="true" title="手机号：" mask="99999999999" :show-clear="false" v-model="phoneVal" :max="11" :min="11" :should-toast-error="false" placeholder="请输入手机号"></x-input>
    </div>
  </div>
</template>

<script>
import { PopupPicker, XInput, Group, XButton } from 'vux'
import { setTimeout } from 'timers';
 export default ({
      data() {
        return {
          isLock: false, // 是否锁定按钮
          list: [[ // 小区
            {
              name: '天马佳园',
              value: '1',
              parent: 0
            },
            {
              name: '胪雷新城',
              value: '2',
              parent: 0
            },
            {
              name: '永南佳园',
              value: '3',
              parent: 0
            },
            {
              name: '大唐世家',
              value: '4',
              parent: 0
            },
            {
              name: '上城国际',
              value: '5',
              parent: 0
            },
            {
              name: '阳光城',
              value: '6',
              parent: 0
            }
          ]],
          value: [], // 选择器选中值
          nameVal: '', // 姓名
          phoneVal: '', // 电话
          cardVal: '', // 证件号
        }
      },
      components: {
        PopupPicker,
        XInput,
        Group,
        XButton
      },
      methods: {
        onHide0(closeType) { // 弹窗关闭发生事件，closeType === true则表示是点击完成关闭的
          if (closeType === true) {
            console.log(this.value1)
            // 级联下一个选项
          }
        }
    }
  })
</script>
<style>
</style>

**Comment by ww33331000** [comment]
[a.txt](https://github.com/airyland/vux/files/3333207/a.txt)
例子比较简单。就是多个pop-picker放一起的时候就会出现，

**Comment by kevinchung1026** [comment]
官方demos就是多个放一起的，你在微信里打开并没有问题，是不是你改了容器宽度？
https://vux.li/demos/v2/#/

**Comment by ww33331000** [comment]
额，刚刚试了一下，应该是和x-input一起使用的时候有啥比较难发现的冲突吧。。拿掉x-input就不会出现这种情况，如果还没法定位那我这边也没啥办法了，只能当作比较神奇的现象了。。。

**Comment by kevinchung1026** [comment]
> 官方文档：`x-input`只能在`Group`中使用

你试试用`Group`作外层容器或只包含`x-input`

**Comment by ww33331000** [comment]
刚刚试了一下，用group将它们都包裹起来可以解决这个问题，但是应该是group包含的 .weui-cells 样式有一条overflow:hidden;来限制的。本质的问题还是存在，即这两个组件一起使用就会出现这个问题。最好能够像我最开始的时候提到的那样，对比一下.vux-cell-box:not(:first-child):before  和.weui-cells:before两个样式，这两个样式所要的效果应该是相同的。
![image](https://user-images.githubusercontent.com/40596815/60245768-d8001300-98ef-11e9-856a-4e763487af8a.png)

**Comment by kevinchung1026** [comment]
根据自己需求，复写样式也行。
PS：`vux`一般和`vue`搭配使用，我居然看到了`jQuery`！
