### ISSUE TITLE
[Bug Report]  Popup set position  v-model绑定的值如果放在vuex 中，点击遮罩隐藏会报错

### ISSUE THREAD

**Issue by hushuishui** [airyland/vux#3547]
### VUX version
2.9.4

### OS/Browsers version
chrome

### Vue version
2.6.10

### Code

```html
      <popup
        v-model="this.$store.state.popup.show"
        :position="this.$store.state.popup.pos"
        should-scroll-top-on-show
        :class="{'success': this.$store.state.popup.show}"
      >
        <p>{{this.$store.state.popup.text}}</p>
      </popup>
 state: {
    inlineLoading: {
      show: false
    },
    popup: {
      show: true,
      pos: 'top',
      text: "成功啦~"
    }
  },
```

### Steps to reproduce
v-model 绑定的值放在vuex 中，点击遮罩隐藏会报错，

### What is Expected?
 能把 v-model 绑定的值放在vuex 中 ，点击遮罩不会出现类型报错

### What is actually happening?
v-model 绑定的值放在vuex 中 ，点击遮罩会出现类型报错[Vue warn]: Error in v-on handler: "TypeError: Cannot read property '$store' of null"

**Comment by kevinchung1026** [comment]
试试绑定在`data`里的变量上，然后这个变量指向`vuex`
