### ISSUE TITLE
[Bug Report] demo 无图片

### ISSUE THREAD

**Issue by qianshankun** [airyland/vux#3549]
### VUX version
2.9.4

### OS/Browsers version
win10

### Vue version
2.6.10

### Code

```html
demo 无图片
```

### Steps to reproduce
demo 无图片

### What is Expected?
demo  有图片

### What is actually happening?
demo  有图片

**Comment by kevinchung1026** [comment]
哪个demo？

**Comment by qianshankun** [comment]
https://vux.li/demos/v2/#/


------------------ 原始邮件 ------------------
发件人: "Kevin"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 上午9:38
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "一、天"<87127035@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [airyland/vux] [Bug Report] demo 无图片 (#3549)




哪个demo？

**Comment by kevinchung1026** [comment]
估计是图片服务器挂了

**Comment by qianshankun** [comment]
好的。挂了好几天了。还以为这个vux 没人维护了。麻烦给处理下。




------------------ 原始邮件 ------------------
发件人: "Kevin"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 上午9:52
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "一、天"<87127035@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [airyland/vux] [Bug Report] demo 无图片 (#3549)




估计是图片服务器挂了

**Comment by kevinchung1026** [comment]
这要作者来维护了，不过图片不显示不影响学习和使用 :)

**Comment by qianshankun** [comment]
好的谢谢。




------------------ 原始邮件 ------------------
发件人: "Kevin"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 上午9:57
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "一、天"<87127035@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [airyland/vux] [Bug Report] demo 无图片 (#3549)




这要作者来维护了，不过图片不显示不影响学习和使用 :)
