### ISSUE TITLE
[Feature Request] swiper 阻止手势滑动操作

### ISSUE THREAD

**Issue by 2017lhy** [airyland/vux#3553]
### Existing Component
是

### Component Name
swiper

### Description
要禁用手势操作，自己修改了swiper的源码 添加阻止手势滑动操作，添加一个属性 touchable

swipe.js 中 添修改

1、this._default中添加 touchable: true,
`this._default = 
{
      container: '.vux-swiper',
      item: '.vux-swiper-item',
      direction: 'vertical',
      activeClass: 'active',
      threshold: 50,
      duration: 300,
      auto: false,
      loop: false,
      **touchable: true,**
      interval: 3000,
      height: 'auto',
      minMovingDistance: 0
    }`

2、在 _bind 方法中的 touchstartHandler、touchmoveHandler、touchendHandler事件里添加 if (!this._options.touchable) return;
`me.touchstartHandler = (e) => {
      if (!this._options.touchable) return;
      me.stop()
      me._start.x = e.changedTouches[0].pageX
      me._start.y = e.changedTouches[0].pageY
      me._setTransition('none')
      me._isMoved = false
    }
    me.touchmoveHandler = (e) => {
      if (!this._options.touchable) return;
      if (me.count === 1) {
        return
      }
    me.touchendHandler = (e) => {
      if (!this._options.touchable) return;
      if (me.count === 1) {
        return
      }`

swiper.vue 中修改
1、在new Swiper 中添加 touchable: this.touchable
`      this.swiper = new Swiper({
        container: this.$el,
        direction: this.direction,
        auto: this.auto,
        loop: this.loop,
        interval: this.interval,
        threshold: this.threshold,
        duration: this.duration,
        height: this.height || this._height,
        minMovingDistance: this.minMovingDistance,
        imgList: this.imgList,
        touchable: this.touchable
      })`

添加props
`    touchable: 
{
      type:Boolean,
      default: true
    }
`

    使用时绑定 touchable = false 就屏蔽手势
`<swiper direction="vertical" :interval=2000 :show-dots="false" loop :touchable="false">`

**Comment by kevinchung1026** [comment]
去提PR😬
