### ISSUE TITLE
Previewer组件大图在安卓微信内长按无法保存，photoswipe的dome在微信上打开是可以的，Previewer组件封装时有什么设置影响了这个功能

### ISSUE THREAD

**Issue by expanding** [airyland/vux#3554]

**Comment by kevinchung1026** [comment]
> 注意，当你自定义添加按钮时，需要在 photoswipe 选项设置 clickable 元素，否则点击将没有响应

> 建议为所有图片定义尺寸
> PhotoSwipe 本身要求设置宽高，Previewer 组件会尝试对没有设置宽高的图片先加载再显示，可能会造成性能问题或者宽带浪费。 相关 issue:#2321
