### ISSUE TITLE
[Bug Report] 在安卓手机输入框的删除按钮点击没反应

### ISSUE THREAD

**Issue by LiangFuzhi** [airyland/vux#3555]
### VUX version
2.9.4

### OS/Browsers version
安卓手机

### Vue version
2.6.10

### Code

```html
在x-input.vue
onBlur ($event) {
      this.setTouched()
      this.validate()
      // this.isFocus = false
      this.$emit('on-blur', this.currentValue, $event)
    }
改为
onBlur ($event) {
      setTimeout(() => {
        this.setTouched()
        this.validate()
        this.isFocus = false
        this.$emit('on-blur', this.currentValue, $event)
      }, 0)
    }

focus () {
        this.$refs.input.focus()
    }
改为
focus () {
      setTimeout(() => {
        this.$refs.input.focus()
      }, 0)
    }
就能解决
```

### Steps to reproduce
在安卓手机微信操作输入框，点击清空图标

### What is Expected?
正常使用

### What is actually happening?
点击清空没反应

**Comment by kevinchung1026** [comment]
目前要自己修改下源码，已经有人提PR了

**Comment by LiangFuzhi** [comment]
`<x-input class="input"
      v-model="value"
      ref="input"
      @on-enter="search"
      @on-focus="onFocus"
      @on-blur="onBlur"
      placeholder="请输入关键词">
        <icon slot="label" class="input-icon" type="search"></icon>
      </x-input>

onFocus () {
      setTimeout(() => {
       this.$refs.input.isFocus = true
      }, 0)
    },
    onBlur () {
      this.$refs.input.isFocus = true
      setTimeout(() => {
        this.$refs.input.isFocus = false
      }, 0)
    }`

不改源码的解决方案

**Comment by kevinchung1026** [comment]
> `<x-input class="input"
> v-model="value"
> ref="input"
> @on-enter="search"
> @on-focus="onFocus"
> @on-blur="onBlur"
> placeholder="请输入关键词">
> 
> onFocus () {
> setTimeout(() => {
> this.$refs.input.isFocus = true
> }, 0)
> },
> onBlur () {
> this.$refs.input.isFocus = true
> setTimeout(() => {
> this.$refs.input.isFocus = false
> }, 0)
> }`
> 
> 不改源码的解决方案

多人协同开发时，这样更好。
不过，定时器最少16ms，即使你写的是0，所以改成20，可以好看点~🤣

**Comment by easy868** [comment]
问题+1

**Comment by caozhong1996** [comment]
see #3778
