### ISSUE TITLE
Scroller组件,配置的是pullup，但pulldown时，也会改变upContent内容

### ISSUE THREAD

**Issue by WilliamDu1981** [airyland/vux#356]
### 0.1.2
本来配置的是pullup，但是向下拉时，组件也改变了提示文本的内容，变为:继续拉
是本来就这样设计的，还是算bug
``` html
<scroller height="100%"
                  :lock-x="true"
                  v-ref:scroller
                  :use-pullup="true"
                  @pullup:loading="onPullup"
                  :pullup-config="pullUpConfig">
          <div>
          <product-item v-for="item of products"

          @onbuy="onBuy"
          @click="onProductItemClick(item)"
          :product="item">
          </product-item>
          </div>
        </scroller>
```

```js
export const pullUpConfig={
  content: '上拉加载更多',
  pullUpHeight: 60,
  height: 40,
  autoRefresh: false,
  downContent: '松开进行加载',
  upContent: '继续拉',
  loadingContent: '加载中...'
};
```

**Comment by WilliamDu1981** [comment]
@airyland 还有一个问题，加载的时机，应该是出现松开进行加载时，才会加载，但现在是只要往上拉了，不管多少距离，一松马上加载

**Comment by lichunqiang** [comment]
没看你开启`use-pulldown`

**Comment by WilliamDu1981** [comment]
@lichunqiang 我不需要pulldown啊，我只要上拉加载，难道也要开启么

**Comment by lichunqiang** [comment]
> 但是向下拉时，组件也改变了提示文本的内容

你的意思是，没有开启pulldown，但是下拉的时候，`pulldown`的内容变成你说得`:继续拉` 了？

**Comment by WilliamDu1981** [comment]
@lichunqiang 对，没有开启，是Pullup的内容变了

**Comment by lichunqiang** [comment]
@WilliamDu1981 http://xscroll.github.io/node_modules/xscroll/doc/PullDown.html

`content` 是初始化后默认的文字，而 `upContent` 应该是用户在上拉过程中展示的，当用户释放后也会展示这个

**Comment by WilliamDu1981** [comment]
@lichunqiang 这个我明白，我说的问题是，pulldown的时候，改变了pullup的upcontent

**Comment by lichunqiang** [comment]
哦，那就是插件的正常的行为，当操作滚动条的时候就会设置成`upContent` 的内容

**Comment by WilliamDu1981** [comment]
好吧，但我觉得这个应该是有问题的，pullup的upcontent因就是pull up的时候改变,pulldown只能改变pulldown content才对，你觉得呢

**Comment by lichunqiang** [comment]
其实我觉得你设置成`content = upContent` 就好，这样就不会产生疑惑。至于为啥这样实现的就得问下`xscroller` 的作者了 - -！ 问题先关闭了

**Comment by WilliamDu1981** [comment]
@lichunqiang thank you.设置成一样确实可以解决这个问题
