### ISSUE TITLE
[Bug Report] 文档为什么挂了?

### ISSUE THREAD

**Issue by bleakwind** [airyland/vux#3565]
### VUX version
2.9.4

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Code

```html
文档挂了, 打不开了...
```

### Steps to reproduce
https://doc.vux.li/zh-CN/components/flexbox.html

### What is Expected?
请耐心至少维护好文档, 不要让我们的选择成为后悔的一件事...

### What is actually happening?
请不要让我们失望...

**Comment by djroad** [comment]
支持！
