### ISSUE TITLE
x-input  页面无法复位

### ISSUE THREAD

**Issue by xc435031168** [airyland/vux#3566]
x-input 点击弹出虚拟键盘后页面会上移一部分,键盘输入完成后页面不会恢复到原来的位置.
使用的是AlertPlugin

**Comment by xc435031168** [comment]
![微信图片_20190716171334](https://user-images.githubusercontent.com/19319810/61282429-e0ac8080-a7ed-11e9-8407-85a922afa370.jpg)
![2](https://user-images.githubusercontent.com/19319810/61282434-e4400780-a7ed-11e9-9fc7-6f18c5a18453.jpg)
![3](https://user-images.githubusercontent.com/19319810/61282439-e7d38e80-a7ed-11e9-9079-3b45b0614a89.jpg)

**Comment by StonePang** [comment]
我在微信浏览器里面也出现了这个问题，求解决方案
