### ISSUE TITLE
PC官网

### ISSUE THREAD

**Issue by airyland** [airyland/vux#358]
目前还没有PC官网，也没有一个项目的一个总体介绍，另外也没有专业设计来做一个比较ok的。。

暂时初步设想是：
+ [ ] 组件的清晰分类(布局组件，表单组件，CSS util)及搜索功能
+ [ ] 统一的Change log查看页面

其他的欢迎提出建议

**Comment by WilliamDu1981** [comment]
这个可以有，支持，具体可以参考vue的官网，我觉得做的比较好，能很快找到想要的内容

**Comment by zhonggedan** [comment]
vue官网做的不好，讲解太表面了。 学不到啥东西

**Comment by airyland** [comment]
@zhonggedan Vue官网文档算业界良心了吧。。

**Comment by zhonggedan** [comment]
好是很好，但是如果想更进一步学习就有点不合适了。

**Comment by airyland** [comment]
@zhonggedan 其实你这么想，我们也没法回你了 :sweat: 。。这个话题就不要再这里继续讨论了。

**Comment by duruitang** [comment]
@zhonggedan 你是把官网当文档看了吧，哈哈

**Comment by fuchao2012** [comment]
开发一个类似于 https://material.angularjs.org/latest/ 的网站，开发的时候算我一个哦（：

**Comment by zzzeep** [comment]
我建议目前阶段暂时不要考虑开发PC官网，应该把精力集中在v1.0.0开发，完成之后，再开一个官网repo

**Comment by shmy** [comment]
加油哦！
