### ISSUE TITLE
在使用Picker的时候，无法展现成设计稿样式

### ISSUE THREAD

**Issue by jserck** [airyland/vux#3587]
### Existing Component
是

### Component Name
Picker

### Description
在使用Picker的时候发现移动距离（item高度）是34px，但是设计稿的item是108px,无法自己修改，可能是没有找到方法

**Comment by yuxianwen** [comment]
**谷歌审查元素(检查)可以查到然后用自定义样式覆盖掉的，我一般都是这么做的**
