### ISSUE TITLE
使用dialog组件时，模板交互都正常，但是关闭按钮样式没有加载进来

### ISSUE THREAD

**Issue by senyawang** [airyland/vux#359]
npm 3.9.5

vux @0.1.1

环境配置  gulp + webpack + vue +vux

参照：https://github.com/airyland/vux/blob/master/src/demos/Dialog.vue

由于npm 安装在node_modules下使用的话会报错，所以复制到了 src 目录下使用相对路径

header.vue 内容如下

<template>
  <div>

    <x-header style="background-color:#000;" :left-options="{showBack: false}">
         <a slot="left">Close</a>
         with right link
        <a slot="right" @click="show=true">Feedback</a></x-header>
    
    <dialog :show.sync="show" class="dialog-demo">
      <p class="dialog-title">I'm a Dialog.</p>
      <div class="img-box">
        <img src="http://ww3.sinaimg.cn/mw690/bf9485d5gw1f5pzi5ua5fj20zk0qowsg.jpg" style="max-width:100%">
      </div>
      <span class="vux-close" @click="show=false"></span>
    </dialog>

  </div>
</template>

<script>
import { XHeader, Dialog, XButton, Group, Switch } from '../../vux/src/components'

export default {
  components: {
    XHeader,
    Dialog,
    XButton,
    Group,
    Switch
  },
  data () {
    return {
      show: false
    }
  }
}
</script>

浏览器渲染结果如下：

![Uploading 693306D9-8B7A-4337-9DD5-8AFA7EAE2A8A.png…]()

问题如上，请问为什么关闭按钮的样式没有加载进来， 难道样式文件只能全局引入吗？

**Comment by airyland** [comment]
截图没有上传完成。
关闭样式属于css工具的一部分，需要手动引入，demo我忘了更新。

**Comment by senyawang** [comment]
手动引入是指需要全局引入vux.css 还是可以手动按需引入组件的样式

**Comment by airyland** [comment]
现在的样式已经不需要vux.css了。你只需要引入reset，这里需要close样式，那么需要引入src/styles/close.less

**Comment by senyawang** [comment]
好了，谢谢了
