### ISSUE TITLE
[Bug Report] 在不支持es6语法的浏览器上打开vux会报错

### ISSUE THREAD

**Issue by xueyj123** [airyland/vux#3592]
### VUX version
2.9.4

### OS/Browsers version
chrome-45

### Vue version
2.6.10

### Code

```html
vue-cli-3-example官方代码
```

### Steps to reproduce
vue-cli-3-example打包后会出现es6的语法，在低版本浏览器上会报错

### What is Expected?
vue-cli-3-example打包后会出现es6的语法，在低版本浏览器上会报错

### What is actually happening?
vue-cli-3-example打包后会出现es6的语法，在低版本浏览器上会报错

**Comment by skcwiiur** [comment]
看看这个 https://www.jianshu.com/p/5242c8a99a5d

**Comment by xueyj123** [comment]
@skcwiiur 好的，我试试，谢谢

**Comment by qiuyu303** [comment]
你好，请问有解决吗？
