### ISSUE TITLE
dialog组件中`v-show="show" :transition="dialogTransition"`的使用引起Vue报错

### ISSUE THREAD

**Issue by keepgoingwm** [airyland/vux#361]
### Version

0.1.2
Vue Version: 1.0.21

### Android or iOS

不涉及

### Your Codes 

``` html
<template>
  <div class="weui_dialog_alert" v-show="show" :transition="maskTransition">
    <div class="weui_mask" @click="hideOnBlur && show=false"></div>
    <div class="weui_dialog" v-show="show" :transition="dialogTransition">
      <slot></slot>
    </div>
  </div>
</template>
```
dialog组件中`v-show="show" :transition="dialogTransition"`的使用引起Vue报错：
Invalid expression. Generated function body:  scope.hideOnBlur&&scope.show=false

### Expected behavior and actual behavior.

修改使用方式

### Steps to reproduce the problem

页面引用dialog组件，在浏览器环境运行页面

**Comment by airyland** [comment]
这个已经修复了，不是你说的那个地方，是mask相关的js有问题。
https://github.com/airyland/vux/commit/b16a5c49ea16a75c9d3d9f8c6641c07a98200eaa

**Comment by keepgoingwm** [comment]
@airyland 好的
