### ISSUE TITLE
cell 插槽

### ISSUE THREAD

**Issue by Lkkpower** [airyland/vux#3617]
建议支持图标字体插槽，而不是单一的图片
![image](https://user-images.githubusercontent.com/24646979/66533337-26ef5280-eb45-11e9-9ef2-a358ebd0754e.png)

**Comment by airyland** [comment]
这个 slot 并不限制具体的标签内容，你完全可以插入 svg，iconfont 等内容。上面你的截图只是一个例子。

**Comment by Lkkpower** [comment]
嗯，看到了，已经实现了；谢谢
