### ISSUE TITLE
scroller组件在ios13上滚动到底部时onScroll方法的兼容性问题

### ISSUE THREAD

**Issue by xiaoxiaofei788** [airyland/vux#3618]
scroller组件在ios13上滚动到底部时onScroll方法的pos.top异常很厉害，从正常的比如500，突变为-1，基本上无法使用了，滚动组件在ios13上问题很大

**Comment by xiaoxiaofei788** [comment]
<template>
  <div class="car-custom" >
      <scroller style="overflow: visible!important;" lock-x scrollbar-y use-pullup height="100%" :disablePullup="true" 
        @on-scroll="onScroll" v-model="status" ref="scroller">
        <div class="scroller-container" >
          <div class="li"  v-for="(item,index) in list">{{item.a}}</div>
        </div>
      </scroller>
  </div>
</template>

<script>
import {Scroller} from 'vux'
export default {
  components: {
    Scroller,
  },
  name: 'carCustom',
  props:["initTabStyle"],
  data () {
    return {
      status: {
        pullupStatus: 'default',
        pulldownStatus: 'default'
      },//控件配置
     list:[{
       a:1
     },{
       a:1
     },{
       a:1
     },{
       a:1
     },{
       a:1
     },{
       a:1
     },{
       a:1
     },{
       a:1
     },{
       a:1
     },{
       a:1
     },{
       a:1
     },{
       a:1
     }]
    }
  },
  computed: {
  },

  activated(){
    let self=this;
  },
    watch: {
  },
  beforeDestroy:function(){
   
  },
  beforeRouteLeave (to, from, next) {
    next();
  },
  mounted: function() {
    let self=this;
   
  },
  methods: { 
    // 滚动方法
    onScroll(pos){
        let self = this;
        console.log(pos.top)
    },
  }
}
</script>
<style lang="scss" scoped>
.car-custom{
  .li{
    height: 100px;
    background: red;
    margin: 6px 0;
  }
   
}
</style>
简单的demo如上

**Comment by airyland** [comment]
这个插件在很久前就已经被废弃了，建议寻找其他还在持续迭代的组件来替代。

**Comment by zhaiminqian** [comment]
遇到同样问题，在ios13上滚动条滚动完自动弹回去顶部了

**Comment by xiaoxiaofei788** [comment]
https://blog.csdn.net/sllailcp/article/details/102502452，看看这个链接参考下吧

在 2019-12-04 14:14:36，"京城女女" <notifications@github.com> 写道：


遇到同样问题，在ios13上滚动条滚动完自动弹回去顶部了

**Comment by zhaiminqian** [comment]
非常感谢，已经用博客里说的方法解决了，改了一下组件里的正则就好使了。

**Comment by jialudev** [comment]
> 非常感谢，已经用博客里说的方法解决了，改了一下组件里的正则就好使了。

链接404了，碰到同样问题，能不能解释下怎么处理的。

**Comment by XyyF** [comment]
> > 非常感谢，已经用博客里说的方法解决了，改了一下组件里的正则就好使了。
> 
> 链接404了，碰到同样问题，能不能解释下怎么处理的。

https://blog.csdn.net/sllailcp/article/details/102502452

链接不带后面的文字
