### ISSUE TITLE
cell模块怎么循环输出

### ISSUE THREAD

**Issue by sunhongjian** [airyland/vux#362]
<group v-for="item in items" >
        <cell title="{{item.title}}" is-link v-link="'vue-router'">
        </cell>
    </group>
<script>
import { Cell, Group } from 'vux'
export default {
  components: {
    Cell,
    Group
  },
  data() {
    return{
      items: [
        {title: 'linux 入门教程'},
        {title: 'javascript 入门教程'},
        {title: 'jquery 入门教程'},
        {title: 'node 入门教程'}
      ]
    }
  }
}
</script>
这样写不行

**Comment by airyland** [comment]
既然是循环cell，v-for应该用在cell上

**Comment by sunhongjian** [comment]
用在v-for上也输出不了

**Comment by airyland** [comment]
先学会提问吧，“不行”，“输出不了”这些描述帮忙不了解决问题。

**Comment by sunhongjian** [comment]
<template>
  <div>
    <group>
        <cell v-for="item in items" title="{{item.title}}" is-link v-link="'vue-router'">
        </cell>
    </group>
  </div>
</template>

<script>
import { Cell, Group } from 'vux'
export default {
  components: {
    Cell,
    Group
  },
  data() {
    return{
      items: [
        {title: 'linux 入门教程'},
        {title: 'javascript 入门教程'},
        {title: 'jquery 入门教程'},
        {title: 'node 入门教程'}
      ]
    }
  }
}
</script>

<style>
@import '~vux/vux.css';
</style>
这是全部代码

**Comment by sunhongjian** [comment]
<cell v-for="item in items" title="{{item.title}}" is-link v-link="'vue-router'">
        </cell>

import { Cell, Group } from 'vux'
export default {
  components: {
    Cell,
    Group
  },
  data() {
    return{
      items: [
        {title: 'linux 入门教程'},
        {title: 'javascript 入门教程'},
        {title: 'jquery 入门教程'},
        {title: 'node 入门教程'}
      ]
    }
  }
}
这样写不对吗

**Comment by airyland** [comment]
组件属性赋值用 `:title="item.title"`

**Comment by airyland** [comment]
你说的输出不了是什么表现？

**Comment by sunhongjian** [comment]
就是出来4个空cell

**Comment by airyland** [comment]
赋值姿势错误，试试我上面说的。

**Comment by sunhongjian** [comment]
还是不行报错
[Vue warn]: Invalid expression. Generated function body:  {{scope.item.title}}

**Comment by airyland** [comment]
确定是 `title="{{item.title}}"` 不是 `:title="{{item.title}}"`?

**Comment by sunhongjian** [comment]
我用的:title="{{item.title}}"报错

**Comment by airyland** [comment]
本来就不是这样用的，组件属性不能用{{}}来赋值

`:title="item.title"`

**Comment by sunhongjian** [comment]
好啦,我刚学,耽误您时间了
