### ISSUE TITLE
ios中使用微信打开项目，如果页面内容超过100vh,那么存在popup-picker会让页面变为空白

### ISSUE THREAD

**Issue by clrockrock** [airyland/vux#3620]
nginx 404 连接不能访问

使用微信的开发者工具没有问题。
在iphonex ios13,2中也是好的。
在iphone 6 ios12.4.1中出现白屏。发现与**popup.js**中**document.body.appendChild(this.divMask)**这句有关。
样式vux-popup-mask导致页面被遮挡显示为空白。
百度搜索了一些问题，其中有修改源码，将上一局变为
**document.querySelector('.vux-popup-dialog').after(this.divMask)**
或者在body中设置：**-webkit-overflow-scrolling: auto;**
两种方式都不太好
第一种源码修改涉及线上打包不可取。
第二种使ios中页面滚动变得不流畅。

**希望作者可以提供一个更好的方式。谢谢**

**Comment by airyland** [comment]
麻烦提供一个简单的 demo 代码，包括样式和 vux 的代码调用。

**Comment by clrockrock** [comment]
非常抱歉回复晚了。

本来是想写一个demo的 ，但是公司的开发进度赶，没来得及，而且不知道该如何提供,是不是要单独写一个工程。

昨天晚上出现这样的问题，我看到了你为了兼容ios在代码中做了overflowScrolling中auto和touch的切换
`new Popup({
    onOpen(){}
    onClose(){}
})`

并且在iPhoneX 13.2中可以实现以及执行。
但是在iphone6 12.4中这段代码并没有执行，追踪源码没有找到问题。
于是我手动在页面先设置为auto让页面显示出来，2秒后在设置为touch避免滚动卡顿
beforeCreate () {
    document.body.style.webkitOverflowScrolling = 'auto'
  },
  created () {
    getPatientRecord().then(res => {
      
      }
      setTimeout(() => {
        document.body.style.webkitOverflowScrolling = 'touch'
      }, 2000)
    })
  }
这种方式实现了效果，但是在体验上有两个问题，
1.页面在显示picker时，背景是白色的，并不会想正常的显示透明可以看到原有的页面。
2.在picker消失是，页面显示会存在几百ms的延时，这也许和源码中setTimeOut相关。

我给公司的测试说了这两个问题，他们暂时可以接受。

另外：由于此前测试人员提出了ios中滚动不顺畅，其他开发人员在app.vue中直接给body增加了
body {
  background: #fff;
  font-size: 14px;
  /** 傻x苹果手机滑动会卡顿 需加这个样式*/
  -webkit-overflow-scrolling: touch;
}

**Comment by gh0sthx** [comment]
遇到了同样的问题，页面内容等于100vh，也会出现这个问题 。iphone X
