### ISSUE TITLE
PopupPicker组件show-name模式下初始化问题

### ISSUE THREAD

**Issue by Likeag6xx** [airyland/vux#3622]
您好！请问PopupPicker组件show-name模式下初始化显示值需要给v-model绑定什么样的数据形式？？
试过list :[{
              name: "平烤炉",
              parent: 0,
              value: "49f46823a0144b78b4ddbe707e3f3f22"
          }, {
              name: "平烤炉",
              parent: "49f46823a0144b78b4ddbe707e3f3f22",
              value: "49f46823a0144b78b4ddbe707e3f3f22"
            }]
这样的数据形式，很明显行不通；请帮忙解答，谢谢

**Comment by airyland** [comment]
无论是否 show-name，值应该是按照直接值赋予，['49f46823a0144b78b4ddbe707e3f3f22']

但你上面给的代码并不是 v-model 的绑定值，而是列表的 data 数据。
