### ISSUE TITLE
【solved】scroller component inside ios13 after scrolling animation end list always go back to top

### ISSUE THREAD

**Issue by lfjs** [airyland/vux#3623]
hey，my dear developer！after ios13 upgrade more and more people find issue in scroller component
i find one solution and i wish that can keep scroller live long and prosper
here is main issue：
![QQ图片201910161411201](https://user-images.githubusercontent.com/16173591/66893586-fe71c780-f020-11e9-9af3-4ad3bbd1407f.png)
![QQ截图20191016140923](https://user-images.githubusercontent.com/16173591/66893584-fe71c780-f020-11e9-9f68-ab7eda897c90.png)
![QQ图片2019101614112011](https://user-images.githubusercontent.com/16173591/66893587-ff0a5e00-f020-11e9-94ea-4c4fe8f85adf.png)
after `.match（） ‘window.getComputedStyle(this.container)[transform]’`
the `'matrix'` returned could contain number like `‘-3.1415926e-16’`
but original regexp split that into 2 pieces
so i split `‘matrix(1, 0, 0, 1, 0, -25)’` by `.split(",")` then  number like `‘-3.1415926e-16’` can finally be matched into one string
`transY[5]` now can match the correct element not ‘1’ anymore :)
`var transY = window.getComputedStyle(this.container)[transform].match(/[\d|-].*\d/)[0].split(",");`

**Comment by lfjs** [comment]
also function `getScrollLeft` need a fix

**Comment by airyland** [comment]
The scroller component was deprecated for a long time. I suggest you search for a replacement in Vue community.

**Comment by lfjs** [comment]
没办法了、、项目迭代已经太深了、、、换插件改动量太大了、、、、目前采用的scroller私有化解决的
