### ISSUE TITLE
vue cli3构建项目：VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。

### ISSUE THREAD

**Issue by webbruin** [airyland/vux#3627]

**Comment by webbruin** [comment]
如何解决

**Comment by airyland** [comment]
哪个版本的 vux-loader

**Comment by rever4433** [comment]
> 哪个版本的 vux-loader

1.0.58有这个问题

**Comment by airyland** [comment]
使用这个 @vux/loader，参照 https://github.com/airyland/vux/tree/v2/packages/vue-cli-3-example

**Comment by webbruin** [comment]
@airyland 
![1573020057(1)](https://user-images.githubusercontent.com/28708365/68272242-f811c100-009d-11ea-99c3-95cdcdacfc3f.jpg)

**Comment by webbruin** [comment]
@airyland VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
还是报这个

**Comment by luohong123** [comment]
> @airyland VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
> 还是报这个

我也出现这个问题
```
"devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/register": "^7.6.2",
    "@commitlint/cli": "^8.2.0",
    "@commitlint/config-conventional": "^8.2.0",
    "@types/node": "^12.12.3",
    "@vue/cli-plugin-babel": "^4.0.0",
    "@vue/cli-plugin-eslint": "^4.0.0",
    "@vue/cli-service": "^4.0.0",
    "@vux/loader": "^2.0.0-rc4",
}
```
vue.config.js 
```
module.exports = {
configureWebpack: config => {
    require('@vux/loader').merge(config, {
      plugins: ['vux-ui', {
          name: 'less-theme',
          path: 'src/theme.less'
      }],
      name: name,
      resolve: {
        alias: {
          '@': resolve('src')
        }
      }
    });
  },
}
```
按照这个链接的解决方法后，未解决

**Comment by gottayan** [comment]
> > @airyland VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
> > 还是报这个
> 
> 我也出现这个问题
> 
> ```
> "devDependencies": {
>     "@babel/core": "^7.6.4",
>     "@babel/register": "^7.6.2",
>     "@commitlint/cli": "^8.2.0",
>     "@commitlint/config-conventional": "^8.2.0",
>     "@types/node": "^12.12.3",
>     "@vue/cli-plugin-babel": "^4.0.0",
>     "@vue/cli-plugin-eslint": "^4.0.0",
>     "@vue/cli-service": "^4.0.0",
>     "@vux/loader": "^2.0.0-rc4",
> }
> ```
> 
> vue.config.js
> 
> ```
> module.exports = {
> configureWebpack: config => {
>     require('@vux/loader').merge(config, {
>       plugins: ['vux-ui', {
>           name: 'less-theme',
>           path: 'src/theme.less'
>       }],
>       name: name,
>       resolve: {
>         alias: {
>           '@': resolve('src')
>         }
>       }
>     });
>   },
> }
> ```
> 
> 按照这个链接的解决方法后，未解决

解决方式： https://juejin.im/post/5e78a4e85188255dd31ebd55

**Comment by gottayan** [comment]
> @airyland VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
> 还是报这个

解决办法： https://juejin.im/post/5e78a4e85188255dd31ebd55

**Comment by yan695432** [comment]
> > @airyland VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
> > 还是报这个
> 
> 解决办法： https://juejin.im/post/5e78a4e85188255dd31ebd55

按照大佬你的解决方案，./node_modules/vue-loader/lib/runtime/componentNormalizer.js
Module build failed: Error: ENOENT: no such file or directory, open 'D:\WorkArea\开发源码\hjt-app\hjt-src-app2\node_modules\vue-loader\lib\runtime\componentNormalizer.js' 会出现这个提示

**Comment by he426100** [comment]
按上面的链接做了还是有警报
