### ISSUE TITLE
按vue-cli3里的example使用vux-loader报错

### ISSUE THREAD

**Issue by orchids-li** [airyland/vux#3642]
**VUX version**

2.9.2

**Vue version**

2.6.6

**@vux/loader version**

2.0.0-rc4

**Code**

`import { AlertPlugin } from 'vux'`

**What is Expected?**

正常使用alert组件

**What is actually happening?**

报如下错误：
`./src/main.js
Module not found: Error: Can't resolve 'vux/src/plugins/alert/index.js // COMMENT' in 'D:\projects\src'`

编译后的main.js
`var _COMMENT = _interopRequireDefault(require("vux/src/plugins/alert/index.js // COMMENT"));`
编译后为什么多了//COMMENT这个注释，导致引入失败

**Comment by xiaozhanghui** [comment]
我遇到了同样的问题

**Comment by caozhong1996** [comment]
> 我遇到了同样的问题

你有使用新版本的vux-loader吗
