### ISSUE TITLE
文档是按什么节奏跟进？

### ISSUE THREAD

**Issue by dingyiming** [airyland/vux#365]
https://vuxjs.gitbooks.io/vux/content/form/cell.html

我在这边看的文档，然后发现很多组件在demo中有，在文档中没有说明到，请问vux文档是按什么节奏跟进的？希望能完善下，非常感谢！

**Comment by dingyiming** [comment]
demo的源码在那边有吗？ 如果有demo源码也是挺好的

**Comment by lichunqiang** [comment]
demo的代码就在 `src/demos` 下

**Comment by airyland** [comment]
没有什么节奏，有时间就完善，开发修bug优先。。

**Comment by dingyiming** [comment]
好的谢谢
