### ISSUE TITLE
控制台会输出错误信息:Invalid expression. Generated function body:  scope.hideOnBlur&&scope.show=false

### ISSUE THREAD

**Issue by WilliamDu1981** [airyland/vux#366]
### 0.1.2
加载时页面出现错误,我自己的代码里，没有写过，好像是dialog组件里的，见下图：
![qq 20160713115132](https://cloud.githubusercontent.com/assets/6104369/16791355/c77bb504-48f0-11e6-80fb-be42d0398241.jpg)

**Comment by airyland** [comment]
开发上已经修复了，还未发布。

**Comment by WilliamDu1981** [comment]
@airyland 什么时候更新，这个错误不影响程序运行吧

**Comment by airyland** [comment]
不影响
