### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by zuing** [airyland/vux#3662]
新建项目的时候，运行npm install 的时候就报错了

![1](https://user-images.githubusercontent.com/2221736/72742002-cd86cd00-3be3-11ea-96d3-10f74c81c903.jpg)
![1579537153134](https://user-images.githubusercontent.com/2221736/72742015-d37cae00-3be3-11ea-818f-5b6c75526ee3.jpg)

**Comment by caozhong1996** [comment]
看起来和vux无关，先关闭了，谢谢
