### ISSUE TITLE
多个X-input（x -textarea）在安卓上任意一个获取焦点都会定位到当前页面最后一个x-input处

### ISSUE THREAD

**Issue by zRa1ny** [airyland/vux#3667]
X-input 的mounted周期里面在window上注册了一个resize事件，通过这个事件滚动到该x-input的位置，但是如果我页面上个使用的多个x-input，当一个页面input（textarea）获取到焦点，在安卓上，小键盘弹出，改变了高度，触发resize，导致所有的x-input的事件内触发，最终定位到最后一个x-input进入视窗而不是当前点击这一个，请问这个能怎么解决一下？

>   pull request 已经提交了
>   解决方案  修改input组件中scrollView方法中 
 this.$refs.input.scrollIntoViewIfNeeded(true)   ==》 document.activeElemen=== this.$refs.input && this.$refs.input.scrollIntoViewIfNeeded(true)
之前没点进来查看，延迟了好久，希望我的方法能对大家有所帮助~

**Comment by liujun5230** [comment]
只能自己处理一下了。那个代码改起来也容易。处理完，push一下做贡献吧。估计作者是没精力了来处理了。大家一起组个团，切一个版本，来发展和维护这个项目吧。😄哈哈

**Comment by fangzongwu** [comment]
@liujun5230 这个怎么改呀

**Comment by chen1243624551** [comment]
> 只能自己处理一下了。那个代码改起来也容易。处理完，push一下做贡献吧。估计作者是没精力了来处理了。大家一起组个团，切一个版本，来发展和维护这个项目吧。😄哈哈

能请教下怎么改吗？

**Comment by zRa1ny** [comment]
> 只能作者处理没了了。大家一起组个团，切一个版本，来发展和维护这个项目吧。😄哈哈
可以加下互相交流，有群吗

**Comment by zRa1ny** [comment]
> @ liujun5230这个怎么改呀

没解决可以参考一下，有点晚了不好意思~

**Comment by zRa1ny** [comment]
> > 只能作者处理没了了。大家一起组个团，切一个版本，来发展和维护这个项目吧。😄哈哈
> 
> 能请教下怎么改吗？

没解决可以参考一下，有点晚了不好意思~
