### ISSUE TITLE
popup共用一个遮罩，这种操作真是无解了

### ISSUE THREAD

**Issue by burro630** [airyland/vux#3670]
如题，比如一个popup是侧滑筛选布局，内部的popup-picker和popup-radio 效果不行。为啥这种没人优化呢。而且x-dialog没有给一些可选的动画效果。一个原生开发者开发体验，和安卓团队、ios团队提供组件的实用性没法比。 真心希望有人能完全参照ios或者安卓的原生组件体验和适用性来开发，否则总是井底之蛙

**Comment by airyland** [comment]
是啊，你要么不使用，要么来贡献一下来达到你理想的状态，而不是来这里纯粹表达情绪。
说不行当然是容易的。
抱歉，我们确实是井底之蛙，没空帮您优化。

**Comment by alianggitok** [comment]
> 是啊，你要么不使用，要么来贡献一下来达到你理想的状态，而不是来这里纯粹表达情绪。 说不行当然是容易的。 抱歉，我们确实是井底之蛙，没空帮您优化。

这不是败rp么？你说用户情绪化表达的时候，你自己也一样啊，要么别搞，要搞就好好搞，不然就毁灭吧，反正你们也没当回事，就是闹着玩的
