### ISSUE TITLE
> @airyland VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。

### ISSUE THREAD

**Issue by yan695432** [airyland/vux#3682]
> @airyland VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
> 还是报这个

解决办法： https://juejin.im/post/5e78a4e85188255dd31ebd55

_Originally posted by @gottayan in https://github.com/airyland/vux/issues/3627#issuecomment-603643420_

**Comment by he426100** [comment]
你这个办法没用啊，照着做了还是有那个提示

**Comment by caozhong1996** [comment]
see #3778
