### ISSUE TITLE
x-input icon-clear 不生效

### ISSUE THREAD

**Issue by qiaodeye** [airyland/vux#3685]
"vux": "^2.9.4"
"vux-loader": "^1.2.9"
"fastclick": "^1.0.6",

谢谢
清除按钮不生效，作者有回应过这个问题吗？ @

**Comment by colinmorgan** [comment]
我发现当使用了:equal-with=""的时候，清除图标不会出现。

**Comment by Microanswer** [comment]
我也遇到了相同的问题，但由于不影响业务功能，这个问题已经出现了几个月了。

**Comment by Microanswer** [comment]
### 一、解决

以前一直没有决定细心下来解决这个问题，刚刚进入 x-input 组件看了源代码，发现这个清除图标的显示判断里面有 isFocus ，意味着只有当input框有焦点的时候才会显示，而当我们点击那个清除图标时，input就会在我们的 按下(touchdown) 时刻就失去焦点，导致清除图标被隐藏，从而导致清除按钮的点击事件根本不会触发，也就意味着没有清除效果了。

只要把`x-input`源代码:
```html
<!-- .....省略代码... -->
<div class="weui-cell__ft">
    <icon type="clear" v-show="!hasRightFullHeightSlot && !equalWith && showClear && currentValue !== '' && !readonly && !disabled && isFocus" @click.native="clear"></icon>
    <!--  .....省略代码...  -->
```
里面的 `&& isFocus` 去除掉，使其不根据焦点来显示这个清楚图标，这样就可以清除了。


### 二、效果

**修改前**
![modify_before](http://filetest.microanswer.cn/modify_before.gif)

**修改后**
![modify_after](http://filetest.microanswer.cn/modify_after.gif)

### 三、注意

源代码添加了 isFocus 作为清除按钮的显示依据说明它有一定的用途，目前移除这个判断暂未发现后遗症，但不排除在更复杂的应用场景出现各种后遗症，故此，这个解决方案还需开发者们综合考量自身情况后再采取。

> 顺便一提，[Microanswer的网站](https://www.microanswer.cn/?from=github_vux_issues_3685) 期待你的支持！
