### ISSUE TITLE
使用datetime-view时传入end-date的数值为变量时会报错

### ISSUE THREAD

**Issue by lzxzlx** [airyland/vux#3697]
<datetime-view v-model="value2" ref="datetime" :format="format" :end-date="endDate"></datetime-view>
 :end-date="endDate" 的值为变量时会报 [VUX] Datetime prop:end-date 必须为 YYYY-MM-DD 格式
![image](https://user-images.githubusercontent.com/40168718/81662201-cffd8300-946f-11ea-8968-bc1835afb13d.png)
<datetime-view v-model="value2" ref="datetime" :format="format" end-date="2020-05-12"></datetime-view>
 end-date="endDate" 的值为正常的字符串时 不会报错

**Comment by lzxzlx** [comment]
`<datetime-view v-model="value2" ref="datetime" :format="format" :end-date="endDate"></datetime-view> `会报错
`<datetime-view v-model="value2" ref="datetime" :format="format" end-date="2020-05-12"></datetime-view> 不会报错`

**Comment by airyland** [comment]
示例代码请帖完整，endDate 初始值是什么？
请补充完整后 reopen。
