### ISSUE TITLE
datetime Nan 异常

### ISSUE THREAD

**Issue by joveth** [airyland/vux#3699]
使用datetime的时候部分机型 出现Nan问题，最开始格式是YYYY-MM-DD，发现Nan问题后，换成YYYY/MM/DD 格式，还是会出现这个问题，不知道具体出现的原有，不好重现

代码：
`   

     <datetime :title="'预约时间选择'" :min-hour="minhour" :max-hour="maxhour"
                                      :minute-list="minutelist"
                                      :format="format"
                                      year-row="{value}年" month-row="{value}月" day-row="{value}日"
                                      hour-row="{value}点"
                                      minute-row="{value}分"
                                      :start-date="startdate" :end-date="enddate" placeholder="请选择预约时间"
                                      v-model="pretime"></datetime>

`

问题：

![image](https://user-images.githubusercontent.com/6395299/81813560-3363df80-955a-11ea-9b66-7dd10fdc5f35.png)

**Comment by airyland** [comment]
部分机型，比如什么机型？
另外把例子写完整吧。
