### ISSUE TITLE
使用cell 去做下拉,点击title 展示数据

### ISSUE THREAD

**Issue by zhangchenpan** [airyland/vux#3705]
这个是代码
<group v-for="(item, index) in navData" :key="index">
   <cell
         :title="`${item.title}(${item.size})`"
         :border-intent="false"
          is-link
          :arrow-direction="secondaryNodeShow ? 'up' : 'down'"
          @click.native="secondaryNode(item, index)">
     </cell>
</group >
<template v-if="secondaryNodeShow ">
 </template>

**Comment by zhangchenpan** [comment]
想要的结果:
点击title 展示title下的数据
目前的效果:
点击title 同级的title也跟着展示出来了

**Comment by ZcpDream** [comment]
<group v-for="(item, index) in navData" :key="index">
   <cell
         :title="`${item.title}(${item.size})`"
         :border-intent="false"
          is-link
          :arrow-direction="secondaryNodeShow ? 'up' : 'down'"
          @click.native="secondaryNode(item, index)">
     </cell>
</group >
