### ISSUE TITLE
Clocker组件的time属性，不支持变量?

### ISSUE THREAD

**Issue by isunkui** [airyland/vux#371]
### Version
0.1.2

### Your Codes 

``` html
        <clocker time="expire" slot="value">
          <span>%H : %M . %S</span>
        </clocker>
```
```js
export default {
    data () {
      return {
        expire: '2016-07-13 20:00'
      }
    }
}
```

### Expected behavior and actual behavior.
控制台抛出的异常：Uncaught Error: Couldn't cast `expire` to a date object.
导致页面重定向

**Comment by airyland** [comment]
Vue组件属性赋值不是这样写的亲， `:time="expire"`

**Comment by isunkui** [comment]
好的感谢提醒，但是按照你上面的写法，没有得到预期的值.
> * 第一个得到的是00 : 00 . 0
> * 第二个写法是正常的预期结果

```
<clocker :time="expire" slot="value">
  <span>%H : %M . %S</span>
</clocker>
<clocker time="2016-07-13 20:54" slot=value">
  <span>%H : %M . %S</span>
</clocker>
```
```js
export default {
    data () {
      return {
        expire: '2016-07-13 20:54'
      }
    }
}
```

**Comment by isunkui** [comment]
@airyland

**Comment by airyland** [comment]
不能重现。你确定你本机时间小于你设定的时间？

**Comment by isunkui** [comment]
谢谢你，我的问题已解决，跟我expire初始值为0有关

**Comment by airyland** [comment]
现在确实不支持动态设置time，已经在下版本支持。

**Comment by isunkui** [comment]
上面那个问题好像还是没有完全解决，还是有几率出现出现00 : 00 . 00，请问现有的Clocker组件如何动态的设置time，避免这个问题呢，实在不行的话，只能自己动手去实现个了。 @airyland

**Comment by airyland** [comment]
下个版本。有几率出现这个我重现不了。

**Comment by monkeySmoke** [comment]
如果时间是重vuex getter过来的不能正常显示

**Comment by wysitu** [comment]
请问一下。
clocker在iOS下失效，是否是正常。
代码如下：
```
<clocker :time="expire" slot="value">
  <span>%H : %M . %S</span>
</clocker>
```
变量expire是经过接口获取，再赋值到data当中。
经测试，安卓手机，PC浏览器都可以生效。唯独iOS打开的时候后，时间还是显示 %H : %M . %S。

**Comment by yan919** [comment]
IOS不支持时间格式是以 “-”的分隔符，具体请自己查看一下 @wysitu

**Comment by wysitu** [comment]
@monkeySmoke 
哦，谢谢提点。这个坑还真没注意。找到解决办法了。
