### ISSUE TITLE
网站都打不开，写的什么垃圾

### ISSUE THREAD

**Issue by theecn** [airyland/vux#3715]
写的什么垃圾库，网站都打不开，怎么看组件

**Comment by liujun5230** [comment]
能打开网站呀。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "一杯二锅头"<notifications@github.com&gt;; 
发送时间: 2020年7月22日(星期三) 中午1:41
收件人: "airyland/vux"<vux@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [airyland/vux] 网站都打不开，写的什么垃圾 (#3715)





 
写的什么垃圾库，网站都打不开，怎么看组件

**Comment by theecn** [comment]
可能我昨天网络有点问题吧 试了三台电脑都不行

**Comment by liujun5230** [comment]
https://vux.li &nbsp;&nbsp;


能打开的，一般很少遇到打不开的情况。


这个框架出来得比较早，还不错了，毕竟人家也说了“维护靠个人”。


我拿它来学习怎么像他一样封装一个框架出来，它这个代码写得还挺容易看懂的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "一杯二锅头"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 上午9:55
收件人: "airyland/vux"<vux@noreply.github.com&gt;; 
抄送: "自强不息"<3141235825@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [airyland/vux] 网站都打不开，写的什么垃圾 (#3715)





 
可能我昨天网络有点问题吧 试了三台电脑都不行
