### ISSUE TITLE
webpack4.44.0 + vue2.6.11 + vux2.9.0  构建成功，访问页面发现无法挂载vue组件

### ISSUE THREAD

**Issue by YiShengYouNi** [airyland/vux#3721]
webpack:  ^4.44.0
vue:  ^2.6.11
vux : ^2.9.0
vue-loader:  ^14.2.2
vux-loader:  ^1.2.9

在main.js 中 

const app = new Vue({
  router,
  store,
  i18n,
  render: h => h(App), // render挂载
}).$mount('#app')

构建成功，不报错。

通过浏览器访问时，发现 index.html 挂载 Vue组件的位置，输出了如下内容：

**Comment by LSYUN** [comment]
```
"webpack": "4.44.1",
"vue": "2.6.11",
"vue-loader": "14.2.4",
"vux": "2.9.4",
"vux-loader": "1.2.9",
```
我的报错是：
```
Error: Cannot find module 'vue-loader/lib/plugin'
Require stack:
- xxx\build\webpack.dev.conf.js
- xxx\node_modules\webpack-cli\bin\utils\convert-argv.js
- xxx\node_modules\webpack-dev-server\bin\webpack-dev-server.js
```

**Comment by 1959555480** [comment]
注意看文档
暂未适配 vue-cli@3.x，请注意。

vue@^2.3.0(for .sync modifier)
webpack@^2.0
node@^7.6(development)
