### ISSUE TITLE
tab和swiper组合使用时，高度怎么才能100%？

### ISSUE THREAD

**Issue by aplusgain** [airyland/vux#373]
1、npm版本为3.9.3，node版本为v6.2.1，vux版本0.1.2

2、iOS9.3.2 微信内置浏览器6.3.22

3、Codes

``` html
<template>
  <div>
    <tab :line-width=2 active-color='#fc378c' :index.sync="index">
      <tab-item class="vux-center" :selected="demo2 === item" v-for="item in list2" @click="demo2 = item">{{item}}</tab-item>
    </tab>
    <swiper :index.sync="index" height="100%" :show-dots="false">
      <swiper-item v-for="item in list2">
        <div class="tab-swiper vux-center">{{item}} Container</div>
      </swiper-item>
    </swiper>
</template>

<script>
import { Tab, TabItem, Swiper, SwiperItem } from 'vux/src/components'
const list = () => ['精选', '美食', '电影', '酒店', '外卖']
export default {
  components: {
    Tab,
    TabItem,
    Swiper,
    SwiperItem
  },
  data () {
    return {
      list2: list(),
      index: 0
    }
  }
}
</script>

<style lang="less">
.tab-swiper {
  background-color: #fff;
  height: 100%;
}
</style>
```

tab和swiper组合使用时，设置了height为100%不起效果。

**Comment by aplusgain** [comment]
@airyland 帮忙看下呢，这个问题要怎么解决的啊？

**Comment by aplusgain** [comment]
这个问题还有人可以回复下吗？现在我不清楚是组件暂时不支持还是我用的有问题，如果是组件暂时不支持，我就想其他办法了。 大大们，看到了麻烦抽空回复下呢。

**Comment by airyland** [comment]
因为看issue暂时不知道是什么问题只能在有空的时候本地重现了。如果你能知道是组件的bug还是你的使用问题，这个问题能处理得更快。。

**Comment by aplusgain** [comment]
好的，感谢回复，我再研究下

**Comment by Lofanmi** [comment]
@airyland 我也碰到这个问题 正在排查..

**Comment by Lofanmi** [comment]
@airyland .vux-slider>.vux-swiper>.vux-swiper-item 官方的demo是样式是相对定位, 而且float:left, 自己复制了官方的例子, 发现是绝对定位

**Comment by Lofanmi** [comment]
@airyland 是这个commit的问题, 你看看 08c7af0415419701be28f95f71707e8f61d4554e

**Comment by airyland** [comment]
@Lofanmi 这是为了实现灵活的滑动控制，支持循环才做的更改。

**Comment by airyland** [comment]
这里只能是手动计算需要的高度并赋值给swiper。页面高度也不是100%的，所以你设置100%其实是没有基准的。。

**Comment by zhonggedan** [comment]
swiper height 设置为100% 确实不生效

**Comment by janchengwang** [comment]
tabitem 只能跟swiper一起使用吗，可不可以向tabbar一样有一个link，可以配置路由切换

**Comment by airyland** [comment]
@janchengwang 如果你看过demo就知道不是必须和swiper使用了。tab-item的作用就是同页面切换，不支持跳到其他页面。你可以监听点击事件自己处理。

**Comment by janchengwang** [comment]
router-link的默认样式可以去除吗
`<tab-item active-class="active-1" :selected="selectItem === 'used'" @click="selectItem = 'used'"><router-link :to="'/me/coupons/used'">已使用</router-link></tab-item>`
我这样写的话就已使用就会带有蓝色的超链接的样式，会覆盖掉active-class

**Comment by airyland** [comment]
@janchengwang 不要在issue提无关问题。

router-link不是vux的组件，vue-router的。请到相关repo提issue。
