### ISSUE TITLE
vue-cli3配置vux-loader后启动项目报错vue.esm.js?a026:628 [Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by susielbz** [airyland/vux#3733]
vue-cli3配置vux-loader后启动项目报错 vue.esm.js?a026:628 [Vue warn]: Failed to mount component: template or render function not defined.
found in
---> <App> at src/App.vue
       <Root>
参考配置文档https://www.cnblogs.com/dudu123/p/10207215.html
配置部分：
configureWebpack: config => {
        require('vux-loader').merge(config, {
            options: {},
            plugins: ['vux-ui']
        })
    }
这部分注释掉就不报这个错误了，但是_vm.$t is not a function的问题又出现了，请问遇到过这个情况吗，应该怎么去处理呢

**Comment by jianfei0220** [comment]
请问有解决吗？

**Comment by susielbz** [comment]
我忘记了是啥了，不好意思



在 2021-07-22 15:04:32，"张建飞" ***@***.***> 写道：

请问有解决吗？

**Comment by caozhong1996** [comment]
> 请问有解决吗？

请查看置顶的issue
