### ISSUE TITLE
radio组件不管点击哪个，一直选中的是第一个;

### ISSUE THREAD

**Issue by liyan888** [airyland/vux#3736]
radio组件不管点击哪个，一直选中的是第一个;

项目使用组件库：cube-u（1.12.31）i以及vux（2.9.2）;
出现现象：去年年底的项目(之前并没有发现这个问题)，然后最近准备测试维护，发现radio出现bug;
怀疑原因：将radio组件的源码放在项目中使用；  去掉label上的weui-cells_radio的样式和input上的weui-check的样式后，radio的绑定值可以变化；否则radio的邦定值一直是第一个；

**Comment by caozhong1996** [comment]
由于时间应该过去太久，所以关闭此issue，还需要帮助请重开issue，谢谢
