### ISSUE TITLE
popup-picker

### ISSUE THREAD

**Issue by Homebrew1** [airyland/vux#3739]
![image](https://user-images.githubusercontent.com/50045583/98185704-2394e900-1f48-11eb-81da-4b470c0a3772.png)

如果绑定的值为name和id,在选择之后,怎么取值到v-model上呢
![image](https://user-images.githubusercontent.com/50045583/98185744-37404f80-1f48-11eb-89d5-5b7e23ae585a.png)
上面怎么显示的是1呢,怎么改不掉呢

**Comment by Homebrew1** [comment]
demo怎么都不全呢

**Comment by Homebrew1** [comment]
值必须是value,不能是id吗

**Comment by nodous** [comment]
他定义的是value取值 也有监听事件 完全可以自己控制
