### ISSUE TITLE
当vue使用lib-flexible/flexible适配页面时 vux组件有很多不适配的样式

### ISSUE THREAD

**Issue by nodous** [airyland/vux#3746]
总之很不好看 但是移动端又需要去适配不同的手机  如何处理或者方法 请教一下 
vux是个人维护 可能没人回答了 很可惜

**Comment by caozhong1996** [comment]
> 
> 
> 总之很不好看 但是移动端又需要去适配不同的手机  如何处理或者方法 请教一下 
> 
> vux是个人维护 可能没人回答了 很可惜

你可以把对应的样式做调整然后提pr，我会通知作者及时发版的
