### ISSUE TITLE
Android 手机 Alert和Confirm中的弹框提示出现垂直方向占据全屏

### ISSUE THREAD

**Issue by songpeng-inspur** [airyland/vux#3747]
以下两种方式都会存在问题，（可能其他版本也存在问题）

1. 系统版本EMUI10.1.0 手机自带浏览器 ；
2. 微信版本7.0.20 微信直接打开；

还原方式：访问https://vux.li/demos/v2/#/demo ，Alert和Confirm中的弹框提示出现垂直方向占据全屏现象。

**Comment by 1462219314** [comment]
补充uc edge 夸克都会出现该bug

**Comment by caozhong1996** [comment]
将会在下个版本修复，有兴趣提交pr吗？

**Comment by caozhong1996** [comment]
#2220
