### ISSUE TITLE
今天官网说明文档怎么访问不了？

### ISSUE THREAD

**Issue by Lucoding00** [airyland/vux#3750]
今天官网说明文档怎么访问不了？

**Comment by xienb** [comment]
网站挂了

**Comment by xienb** [comment]
有没有离线的呢

**Comment by Lucoding00** [comment]
没有，能否发一份呢，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;谢宁波&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月24日(星期天) 下午5:10
收件人:&nbsp;&quot;airyland/vux&quot;<vux@noreply.github.com&gt;;
抄送:&nbsp;&quot;Lucoding00&quot;<1622489569@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [airyland/vux] 今天官网说明文档怎么访问不了？ (#3750)

**Comment by Lucoding00** [comment]
没有，请问可以给我发一份嘛，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airyland/vux"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 下午5:10
收件人:&nbsp;"airyland/vux"<vux@noreply.github.com&gt;;
抄送:&nbsp;"叶枯过，落下"<1622489569@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [airyland/vux] 今天官网说明文档怎么访问不了？ (#3750)





 
有没有离线的呢

**Comment by eJayYoung** [comment]
@airyland 官方网站502了，请求恢复

**Comment by chenmo00000** [comment]
@airyland  502 Bad Gateway 网站打不开了

**Comment by qq330047743** [comment]
访问不了 看不了文档很难受

**Comment by hujie532356684** [comment]
502 Bad Gateway  请求恢复

**Comment by xuncai-tech** [comment]
到目前为止还是不行

**Comment by Lucoding00** [comment]
https://www.wenjiangs.com/docs/vux     这个说明文档还可以访问

**Comment by airyland** [comment]
抱歉，服务器故障，已经恢复。
