### ISSUE TITLE
vue-cli3配置vuxLodader后报错Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by gaochenweb** [airyland/vux#3759]
vue-cli3配置vuxLodader后报错Failed to mount component: template or render function not defined
configureWebpack: config => {
    vuxLoader.merge(config, {
      options: {},
      plugins: ["vux-ui"]
    });
  }
请问有人遇到过这个问题麽

**Comment by tailer-zhang** [comment]
configureWebpack: config => {
        require('@vux/loader').merge(config, {
            name: name,
            plugins: ['vux-ui', {
                name: 'less-theme',
                path: 'src/assets/css/theme.less'
            }]
        })
    },

用这个配置看看

**Comment by caozhong1996** [comment]
感觉是你引入文件错误，能提供下最小复现代码吗

**Comment by cherryCQ** [comment]
> vue-cli3配置vuxLodader后报错Failed to mount component: template or render function not defined
> configureWebpack: config => {
> vuxLoader.merge(config, {
> options: {},
> plugins: ["vux-ui"]
> });
> }
> 请问有人遇到过这个问题麽

我也遇到了，按照这个配置就会抱这个错，楼主解决了吗？

**Comment by caozhong1996** [comment]
> > vue-cli3配置vuxLodader后报错Failed to mount component: template or render function not defined
> > configureWebpack: config => {
> > vuxLoader.merge(config, {
> > options: {},
> > plugins: ["vux-ui"]
> > });
> > }
> > 请问有人遇到过这个问题麽
> 
> 我也遇到了，按照这个配置就会抱这个错，楼主解决了吗？

周末发个版，你到时候再看看

**Comment by caozhong1996** [comment]
see #3778
