### ISSUE TITLE
swiper能不能禁止swiper左右滑动

### ISSUE THREAD

**Issue by tw1997** [airyland/vux#376]
1、npm版本为3.6.0，node版本为v5.6.0，vux版本0.1.2

2、Google Chrome 版本 48.0.2564.97

**tab 和 swiper组合使用的时候 能不能禁止swiper左右滑动？**

**Comment by airyland** [comment]
什么场景需要禁止左右滑动？

**Comment by tw1997** [comment]
因为几个swiper-item中内容高度不固定，而swiper 组件上面好像只能设置一个统一的高度，我就在tab-item的click事件中就动态改变swiper的高度。但是这样滑动的高度就不会改。所以我就想索性把swiper左右滑动给关掉。

**Comment by airyland** [comment]
那么其实你把swiper直接用普通div替换掉就行了，tab点击时切换到相应div。。

**Comment by airyland** [comment]
没有了滑动的swiper就不是swiper了 :sweat: 
高度不固定我们考虑考虑 @unclay

**Comment by tw1997** [comment]
非常感谢！！如果用普通div  点击tab的时候下面就不会滑动切换了。自己实现又麻烦。(￣▽￣)"　。如果能解决高度不固定问题就更好了。

**Comment by airyland** [comment]
由于组件现在定位的实现，高度不固定暂无法支持，先关闭。
