### ISSUE TITLE
$vux.datetime.show 打开二次选择时间

### ISSUE THREAD

**Issue by 1014470807** [airyland/vux#3764]
$vux.datetime.show打开一次选择开始时间 在 $vux.datetime.show 打开一次选择结束时间 第二次打开不生效

**Comment by caozhong1996** [comment]
能提供下代码复现吗？

**Comment by 1014470807** [comment]
selectStartDate() {
        const me = this
        this.$vux.datetime.show({
          cancelText: '取消',
          confirmText: '确定',
          format: 'YYYY-MM-DD HH:mm',
          value: '2017-05-20 18',
          clearText: '开始日期',
          startDate: '',
          endDate: moment().subtract(46, 'days').format('YYYY-MM-DD'),
          onConfirm (val) {
            me.form.startDate = val.substring(0, 10)
            me.form.endDate = moment(me.form.startDate).add(45, 'days').format('YYYY-MM-DD')
            me.selectEndDate()
            console.log('plugin confirm', val)
          }
        })
      },
      selectEndDate() {
        const me = this
        this.$vux.datetime.show({
            cancelText: '取消',
            confirmText: '确定',
            format: 'YYYY-MM-DD HH:mm',
            value: '2017-05-20 18',
            clearText: '结束日期',
            required: true,
            startDate: moment(this.form.startDate).add(1, 'days').format('YYYY-MM-DD'),
            endDate: moment(this.form.startDate).add(45, 'days').format('YYYY-MM-DD'),
            onConfirm (val) {
              me.form.endDate = val.substring(0, 10)
              const date = me.form.startDate + '~' + me.form.endDate
              me.params.dateValue = date
              me.$nextTick(() => {
                me.reload()
              })
              console.log('plugin confirm', val)
            },
            onCancel (val) {
              me.form.startDate = ''
              me.form.endDate = ''
            }
          })
      },
selectEndDate后来用settimeout包住延迟1S后执行就行 不然也不能使用

**Comment by caozhong1996** [comment]
根据你提供的代码，并没有发现问题，控制台是否有报错呢？

**Comment by 1014470807** [comment]
> 根据你提供的代码，并没有发现问题，控制台是否有报错呢？

你没发现this.$vux.datetime.show( 包含一个再次打开的this.$vux.datetime.show 打不开吗 第二次的那个是没法打开的

**Comment by caozhong1996** [comment]
> > 根据你提供的代码，并没有发现问题，控制台是否有报错呢？
> 
> 你没发现this.$vux.datetime.show( 包含一个再次打开的this.$vux.datetime.show 打不开吗 第二次的那个是没法打开的
由于是同一个实例。确实会存在你说的这种现象，由于动画的原因，延迟600ms即可，效果也在接受范围之内。
