### ISSUE TITLE
具名插槽solt值不渲染

### ISSUE THREAD

**Issue by quanmingmin** [airyland/vux#3767]
<div class="vux-popup-header-right" @click="$emit('on-click-right')">
      <slot name="right-text">{{ rightText }}</slot>
    </div>

不知道为什么这种具名插槽，值都渲染不出来了！不知道为有什么东西会影响到！

**Comment by caozhong1996** [comment]
仅仅一个 {{ rightText }} 是无法判断问题的，需要帮助的话请提供最小复现代码，谢谢

**Comment by quanmingmin** [comment]
![image](https://user-images.githubusercontent.com/18203214/120739883-b587c300-c524-11eb-9ce3-6f8a67027452.png)

**Comment by quanmingmin** [comment]
这里边，取消，与确认只要是以这种slot出现的，都渲染不了。组件内使用的时候，我看到你们是用scope，属性值进行传值的，这种用法，其实看明白！

**Comment by quanmingmin** [comment]
<div class="vux-popup-header-right" @click="$emit('on-click-right')">
      <slot name="right-text">{{ rightText }}</slot>
    </div>

**Comment by quanmingmin** [comment]
![image](https://user-images.githubusercontent.com/18203214/120740255-760da680-c525-11eb-8816-6abf343940a8.png)

**Comment by quanmingmin** [comment]
![image](https://user-images.githubusercontent.com/18203214/120740388-aead8000-c525-11eb-875f-b88ee2025f3e.png)

**Comment by caozhong1996** [comment]
还是没太明白的你的意思，你是指在你的项目中正常使用，但是vux组件内部的slot不能显示吗？还是建一个最小复现仓库吧

**Comment by quanmingmin** [comment]
是的。VUX本身的设置没有修改过。
