### ISSUE TITLE
具名插槽solt，数据无法渲染！

### ISSUE THREAD

**Issue by quanmingmin** [airyland/vux#3768]
![image](https://user-images.githubusercontent.com/18203214/120767850-30190880-c54e-11eb-9e67-e18e2b8195b2.png)
![image](https://user-images.githubusercontent.com/18203214/120768205-7b331b80-c54e-11eb-9145-b8e602060c46.png)
![image](https://user-images.githubusercontent.com/18203214/120768282-8c7c2800-c54e-11eb-8a77-a5580067dc68.png)

**Comment by quanmingmin** [comment]
具名插槽的用法是不是有问题？用了一个props去直接传值？

**Comment by caozhong1996** [comment]
> 具名插槽的用法是不是有问题？用了一个props去直接传值？

1.popup-picker默认的left-text和right-text都是空字符，请查看你是否传入了正确的props，没有的话自然就是空的。
2.没有看到具名插槽不能这么使用。
3.你一直不贴自己的代码，谁能帮你呢？
4.请不要重复提交issue。

**Comment by quanmingmin** [comment]
没有单独再传值。不传应该有默认值。代码有贴不知道是升级哪个包后就出了问题



---原始邮件---
发件人: "Che ***@***.***&gt;
发送时间: 2021年6月4日(周五) 晚上6:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [airyland/vux] 具名插槽solt，数据无法渲染！ (#3768)




  
具名插槽的用法是不是有问题？用了一个props去直接传值？
  
1.popup-picker默认的left-text和right-text都是空字符，请查看你是否传入了正确的props，没有的话自然就是空的。
 2.没有看到具名插槽不能这么使用。
 3.你一直不贴自己的代码，谁能帮你呢？
 4.请不要重复提交issue。

**Comment by quanmingmin** [comment]
![image](https://user-images.githubusercontent.com/18203214/120792465-269c9a00-c568-11eb-95a6-4cc714ee641c.png)
这段是本地使用代码

**Comment by caozhong1996** [comment]
![image](https://user-images.githubusercontent.com/26522151/120794924-687b0f80-c56b-11eb-9479-c0078df30a57.png)
看起来并不是vux的问题，可以使用vue-devtools查看popup-picker下的popup-header组件，leftText和rightText是否传入正确的值

**Comment by quanmingmin** [comment]
可以确定这两个值是已经传过来了的，只是放在插槽solt里边后不渲染了。



---原始邮件---
发件人: "Che ***@***.***&gt;
发送时间: 2021年6月4日(周五) 晚上7:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [airyland/vux] 具名插槽solt，数据无法渲染！ (#3768)




 

 看起来并不是vux的问题，可以使用vue-devtools查看popup-picker下的popup-header组件，leftText和rightText是否传入正确的值

**Comment by quanmingmin** [comment]
我本地吧solt去掉就可以了

--------------原始邮件--------------
发件人："quanmingmin ***@***.***&gt;;
发送时间：2021年6月4日(星期五) 晚上7:57
收件人："airyland/vux" ***@***.***&gt;;
抄送："quanmingmin ***@***.***&gt;;"Your activity ***@***.***&gt;;
主题：Re: [airyland/vux] 具名插槽solt，数据无法渲染！ (#3768)
-----------------------------------

 

 可以确定这两个值是已经传过来了的，只是放在插槽solt里边后不渲染了。 
 
 
 
 ---原始邮件--- 
 发件人: "Che ***@***.***&amp;gt; 
 发送时间: 2021年6月4日(周五) 晚上7:34 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [airyland/vux] 具名插槽solt，数据无法渲染！ (#3768) 
 
 
 
 
   
 
  看起来并不是vux的问题，可以使用vue-devtools查看popup-picker下的popup-header组件，leftText和rightText是否传入正确的值

**Comment by caozhong1996** [comment]
不能复现你说的情况，看起来貌似和vux没有关系，抱歉，不能帮到你。
