### ISSUE TITLE
编译生成的组件目录不一致

### ISSUE THREAD

**Issue by tomoyuen** [airyland/vux#378]
### 部分组件目录缺失样式
conponents
|——box
|——tabbar-item
|——tab-item

能不能做到就算组件内不含样式，也能编译产出一个空的样式文件，来保持一致的目录结构呢?
- component
 - index.js
 - style.css

**Comment by airyland** [comment]
额。有部分确实是没有样式，父子组件，样式只在父子组件。
对你造成了什么问题？

**Comment by tomoyuen** [comment]
我通过[babel-plugin-component](https://github.com/QingWei-Li/babel-plugin-component)插件加载vux模块的时候，插件会自动索引样式文件，所以缺少样式的组件样式模块就会找不到，导致报错

**Comment by airyland** [comment]
也有考虑用这个模块来实现简单一点的import，看配置是可以配置不带style的？

**Comment by airyland** [comment]
不对。问题的关键是你已经是用webpack来开始了呀，从0.1.2开始你从src直接import就行了，不需要引入style了。

**Comment by tomoyuen** [comment]
- 将style设置为false之后就不会加载组件下的样式
- 你是说引入@import全局的样式么？但是我只想要一些需要的组件样式，而且随着vux组件越来越多，样式文件肯定会变得更大的。

**Comment by airyland** [comment]
不是的。现在的.vue形式的组件自带样式。没有额外样式依赖了。

**Comment by tomoyuen** [comment]
引入源码目录下的组件，是包含样式了，可是又需要各种loader去处理sass，less，用dist目录下的组件更方便吧。
还有就是`import { Tab, TabItem } from 'vux/src/components/tab';`这样导入组件，不知道为什么报Unexpected token import的错误。

**Comment by airyland** [comment]
只要两步
- 看文档配置loader
- 安装less less-loader

Done
