### ISSUE TITLE
x-textarea 换行后占两个字符，怎样改才能只占一个字符

### ISSUE THREAD

**Issue by 18567000780** [airyland/vux#3784]
像elementui一样换行占一个字符

**Comment by caozhong1996** [comment]
可以具体说一下吗

**Comment by 18567000780** [comment]
> 可以具体说一下吗
https://doc.vux.li/zh-CN/components/x-textarea.html
https://element.eleme.cn/#/zh-CN/component/input
我想要element ui中的这种占一个字符的效果
就是我限制了3000个字符，点击enter换行时它占了两个字符，我需求是只要求占一个字符

**Comment by caozhong1996** [comment]
这个应该是历史遗留问题，以前有一些浏览器在textarea中使用回车换行是 \r\n 所以计算回车要算两个 #420
但是现在应该都是 \n 了，我晚上处理发版吧

**Comment by caozhong1996** [comment]
已经发到 2.10.1 版本

**Comment by 18567000780** [comment]
好的，谢谢了
