### ISSUE TITLE
构建中找不到 timeline-item 组件

### ISSUE THREAD

**Issue by yanmingsohu** [airyland/vux#3785]
版本 2.9.6
运行命令 `npm run xbuild` 之后
在 dist/components 目录中以及子目录中不存在 `timeline-item` 组件.

这个组件在构建时被遗漏?

**Comment by caozhong1996** [comment]
看了一下是由于对应的metas.yml文件配置错误导致，着急用可以在 vux_component_list.json 文件暂时添加

`"items": [
      "timeline",
      "timeline-item"
 ],`

再次运行 npm run xbuild 即可，晚些时间我再重新处理发版

![impicture_20210729_122556](https://user-images.githubusercontent.com/26522151/127431459-4a2657ed-2172-4d37-9071-2c9e1684bdd9.png)
