### ISSUE TITLE
怎样改变cell点击时的高亮颜色？

### ISSUE THREAD

**Issue by Damocs0921** [airyland/vux#3789]
为了适配深色模式，我们把cell的背景色改成了黑色，但点击/长按时依然会出现浅色的高亮，应该如何修改颜色或去除高亮？

<img width="376" alt="截屏2021-08-04 下午6 11 51" src="https://user-images.githubusercontent.com/7037269/128164378-21026784-9afd-4df6-ba43-3b4b2b9210ce.png">

**Comment by caozhong1996** [comment]
.vux-tap-active:active  

移动端的触摸样式变化都是active伪类，这个样式在 src/styles/tap.less 下

**Comment by caozhong1996** [comment]
有两个样式需要你手动覆盖

`.vux-tap-active:active`  和  `.weui-cell_access:active` 

![impicture_20210805_174519](https://user-images.githubusercontent.com/26522151/128329687-50088eb1-3478-4819-b89c-51c5b2cbb1de.png)

移动端触摸式的样式都是active伪类
