### ISSUE TITLE
Scroller组件，当一个列表滚动一定高度之后，这时重新请求数据渲染，内容会看不见，需要滚动一下才会出现

### ISSUE THREAD

**Issue by GirlSmileToMe** [airyland/vux#379]
### Version:0.1.2
Scroller组件，当一个列表滚动一定高度之后，这时重新请求数据渲染，列表内容会看不见，需要滚动一下才会出现,已经调用了scroller.reset

**Comment by airyland** [comment]
上代码吧。

**Comment by GirlSmileToMe** [comment]
@airyland 代码之前上过，还是看效果吧。[敢不敢点我](http://45.78.10.69/);任何一个列表，你多加载几页，然后，点左上角菜单，选另一个分类，重新加载数据，然后就可以看到了

**Comment by airyland** [comment]
你这个情况比较特殊，属于scroller内容变少的情况，而且按照这个操作应该是要返回顶部。
安装下`0.1.3-rc1`, 试一下

``` js
this.$nextTick(() => {
  this.$refs.scroller.reset({
    top: 0
  })
})
```

**Comment by GirlSmileToMe** [comment]
@airyland 能不能提供更多的接口来操控scroller，比如滚动到指定位置，可以开启持续触发滚动事件等

**Comment by airyland** [comment]
@GirlSmileToMe xscroll方法比较多，不会都暴露出来，你可以取得ref的_xscroll对象来调用。具体查看xscroll文档

**Comment by GirlSmileToMe** [comment]
@airyland 原来如此，thank you :smile:

**Comment by flftfqwxf** [comment]
遇到同样的问题，试试先

**Comment by raferXu** [comment]
重新请求数据渲染，列表内容会看不见，需要滚动一下才会出现.这个都是怎么解决的？

**Comment by parox2014** [comment]
> 重新请求数据渲染，列表内容会看不见，需要滚动一下才会出现.这个都是怎么解决的？

这个问题应该已经修复了吧，都两年了，我已经忘 了，时间太长
