### ISSUE TITLE
进程过段时间就退出

### ISSUE THREAD

**Issue by newTechAccount** [airyland/vux#3805]
我对前端不是很熟悉，这几天尝试vux写了个用例，还蛮方便的
但是碰上个问题：
1、在测试机用nohup npm run dev &跑起来后，此时访问一切正常；
2、过段时间，进程就自动退出了。nohup.out我有打印出来，并没有错误
不知是什么原因，或者有没有日志可以查看

**Comment by newTechAccount** [comment]
或者是否是因为我的启动指令不对？

**Comment by caozhong1996** [comment]
这个应该和Vux没有关系，抱歉
