### ISSUE TITLE
h5 xInput title显示undefined

### ISSUE THREAD

**Issue by CHxxxx** [airyland/vux#3808]
![image](https://user-images.githubusercontent.com/27722694/150298788-e0814bba-2fb0-4c61-b13d-177ed743aee7.png)
<div class="ques__input">
								<x-input :show-clear="false" title="型号规格" placeholder="请输入" v-model="jbxx.jbxx2"></x-input>
							</div>

**Comment by caozhong1996** [comment]
光有截图是没办法的，能提供最小复现吗
