### ISSUE TITLE
VueCompilerError: v-html will override element children.

### ISSUE THREAD

**Issue by gezigezi9707** [airyland/vux#3809]
vue3项目在使用vux的时候报错：VueCompilerError: v-html will override element children.，我看了下源码，发现一个插槽写在了含有v-html指令的标签里面，请问为什么要这样写呢？
![企业微信截图_3c28681c-30fb-4dc1-a632-7b6478fd18c0](https://user-images.githubusercontent.com/61898290/151503736-54cff588-645a-461a-a216-a62ae605d60f.png)

**Comment by caozhong1996** [comment]
目前没有支持vue3，请不要在vue3中使用
