### ISSUE TITLE
tab和swiper联动的，tab-item从第一个开始时swiper宽度有问题

### ISSUE THREAD

**Issue by yanghao0825** [airyland/vux#3812]
tab和swiper联动时，tab-item从第一个开始时swiper-item获取的宽度异常，导致页面错位

**Comment by eJayYoung** [comment]
有没有最小复现的demo，可以用codesandbox，你这样描述也没办法排查

**Comment by yanghao0825** [comment]
是我用了自适应高度的问题吧

**Comment by yanghao0825** [comment]
应该是我用了自适应高度的问题导致的
<swiper-item :style='index==0?{position: "static"}:""'>
        9999
  </swiper-item>

<style lang="less">
.vux-slider > .vux-swiper{
  height: auto !important;
}
</style>
