### ISSUE TITLE
Flexbox子元素受内容影响宽度不等分

### ISSUE THREAD

**Issue by zhonggedan** [airyland/vux#382]
vux：0.12
npm，nodejs：最新的

1px那个demo运行起来正常，但是唯独在华为畅玩5s上出现问题：网格内容长度不同的情况下对不齐，android5.1的系统。
[http://group.store.qq.com/qun/Y30pB.aX4kIFUX9zJosd1Q!!/V3tMB*AFUO6iFcWMeIO/800?w5=575&h5=744&rf=viewer_421](http://group.store.qq.com/qun/Y30pB.aX4kIFUX9zJosd1Q!!/V3tMB*AFUO6iFcWMeIO/800?w5=575&h5=744&rf=viewer_421)

**Comment by airyland** [comment]
话说issue格式稍微编辑一下吧。。

**Comment by airyland** [comment]
又是`华为`。。
如果不用组件用flexbox，设置flex为1时也会这样吗？

**Comment by airyland** [comment]
试一下
``` css
.vux-flexbox .vux-flexbox-item {
  width: 0%;
}
```
看能不能解决？

**Comment by zhonggedan** [comment]
.vux-flexbox .vux-flexbox-item {
  width: 0%;
}  解决了， 但是上下每个小块跟边框的上下距离变得很近，很拥挤，这也是个问题。 总之就是跟其他手机显示有差异。

**Comment by zhonggedan** [comment]
可以将就一下的

**Comment by zhonggedan** [comment]
.vux-flexbox .vux-flexbox-item {
        width: 0%;
        padding-top: 1em;
        padding-bottom: 1em;
    }


手动设置padding-top  padding-bottom ，又会影响在其他手机上的 效果。

**Comment by airyland** [comment]
https://isux.tencent.com/flexbox.html

> 在旧版的规范中，使用比例伸缩布局时，子元素的内容长短不同会导致无法“等分”，这个时候，我们需要给子元素设置一个“width:0%”来解决问题。

**Comment by zhonggedan** [comment]
谢了
