### ISSUE TITLE
Vux官网不显示样式预览

### ISSUE THREAD

**Issue by bbsGod** [airyland/vux#3827]

**Comment by happydan** [comment]
这是来自1977130605邮箱的自动回复邮件。我将尽快给您回复。

**Comment by eJayYoung** [comment]
demo站点的SSL证书过期了，待修复
可以使用[备用站点](http://vux.cmtspace.cn/zh-CN/)，from [issue 3818](https://github.com/airyland/vux/issues/3818)

**Comment by airyland** [comment]
已经修复。
