### ISSUE TITLE
最新的scroller中使用swiper高度计算会出问题

### ISSUE THREAD

**Issue by x007xyz** [airyland/vux#383]
官网示例没有问题，但是拷贝最新的库查看demo，scroller中使用swiper，高度计算有问题，无法滚动到底。

**Comment by airyland** [comment]
官网目前没有更新最新demo，待确认。

**Comment by airyland** [comment]
并没有发现问题。如果你本地还有问题，帖上代码看看。

**Comment by x007xyz** [comment]
commoit:cb42818e41a6a33f3849e531933b94c8165c1b57 [cb42818]已经解决这这个问题，当天就解决了没有看到。
