### ISSUE TITLE
swiper绑定到计算属性上不显示？

### ISSUE THREAD

**Issue by vincentism** [airyland/vux#384]
首先请求api，获得一个数据，通过计算属性将其处理成适合的格式，swiper是绑定到这个计算属性上的，这样并没有任何显示，是因为swiper的绑定比计算属性要早？如何解决呢

**Comment by vincentism** [comment]
@airyland

**Comment by airyland** [comment]
上代码吧。你是异步设置list吗？

**Comment by vincentism** [comment]
html
`            <swiper :list="activity" auto></swiper>
`
script
`data: function() {
        return {
            activity: [],
        ｝
  },
  computed: {
list: function() {
            var temp = []
            var length = this.activity.length
            for (var i = 0; i < length; i++) {
                temp.push({
                    url: 'https://lab.zhiyoula.com/store/' + this.activity[i].id,
                    img: this.activity[i].thumb,
                    title: this.activity[i].name
                })
            }
            return temp
        }
}       
 ...

`

**Comment by vincentism** [comment]
怎么异步设置呢，我直接就
`            <swiper :list="activityList" auto></swiper>
`
请求api获得要展示的数据是在ready里，根据得到的数据计算一个computed属性，上面的activityList就是computed属性

**Comment by airyland** [comment]
为什么附了代码又删除，还关闭了issue？

**Comment by vincentism** [comment]
额，打着字还没打完不小心按到了快捷键直接comment了- -!

**Comment by airyland** [comment]
如果你不上代码我也猜不出你什么问题。不要在来回沟通上浪费彼此时间。

**Comment by vincentism** [comment]
sorry。如果swiper直接绑定到data里的某个组织好的数据，swiper是成功显示的，我的代码大概如下

html
`            <swiper :list="list" auto></swiper>
`

script
```
data: function() {
           return {
                activity: []
            }
        },
    computed: {
            list: function() {
                var temp = []
                var length = this.activity.length
                for (var i = 0; i < length; i++) {
                    temp.push({
                        url: this.host + this.activity[i].id,
                        img: this.activity[i].thumb,
                        title: this.activity[i].name
                    })
                }
                return temp
            }
        },
    ready: function() {
            var activityData = {
                url: this.url,
                method: 'get'
            }
            this.requestData('getActivity', activityData)
            this.activity = result  // 在requestData内部获得result，同时赋值给this.activity，这一步成功赋值
    }
```

**Comment by JianleiZhang** [comment]
你这里组件初始化后因为activity是空的，所以计算出来的temp也是空的也就是[],swiper无法初始化[]这种情况，即使后来请求来的数据生成正确的格式。

**Comment by airyland** [comment]
原因是你没有设定高度，也没有设置显示比例，导致进入了高度auto的逻辑，但是由是为了支持循环轮播定位变成了absolute，所以高度为0就没显示出来了。如果你审查下元素，其实已经渲染出来了。所以如果一开始说明清楚`不显示`的具体情况就容易解决了。

#434
