### ISSUE TITLE
divider组件两边的横线没有上下居中

### ISSUE THREAD

**Issue by zhonggedan** [airyland/vux#388]
vux：0.12 
问题是两个：
1、width: 0%  解决了平分问题，之后出现了图中上边距为0的情况，手动设置 padding-top: 0.06em;
        padding-bottom: 0.06em; 也不一定生效（确实是不一定生效）。

.vux-flexbox .vux-flexbox-item {
                      width: 0%;
        padding-top: 0.1em;
        padding-bottom: 0.1em;
    }

2、<divider>  组件两边横线的问题，如图看得很清楚。

两个问题都只发生在华为畅玩5s手机上，其他手机正常

不知道怎么发图，图片连接如下：
http://group.store.qq.com/qun/Y30pB.aX4kIFUX9zJosd1Q!!/V3tMB*AFQW3iVeUhQ0i/800?w5=492&h5=533&rf=viewer_421

**Comment by graysheeep** [comment]
@zhonggedan 建议丢掉华为手机

**Comment by airyland** [comment]
备份下你上面的图片。
![image](https://cloud.githubusercontent.com/assets/559179/17285200/e610c3f8-57f3-11e6-893b-493bfd696211.png)

因为找不到这个机型，也重现不了，所以如果你能帮忙排查下发个PR最好了。
