### ISSUE TITLE
Should not use relative path

### ISSUE THREAD

**Issue by lichunqiang** [airyland/vux#39]
https://github.com/airyland/vux/blob/master/src%2Fcomponents%2Fscroller%2Findex.vue#L12-L14

这里是不是不要用相对路径...

```
import XScroll from 'vux-xscroll/build/cmd/xscroll.js'
import Pulldown from 'vux-xscroll/build/cmd/plugins/pulldown'
import Pullup from 'vux-xscroll/build/cmd/plugins/pullup'
```

这样可好

**Comment by airyland** [comment]
是有问题，当时在开发时发现直接这样写路径识别有问题，暂时就使用这种形式。

**Comment by lichunqiang** [comment]
因为我现在是以submodule的形式在使用你的内裤，这会导致我就无法运行了，现在改了，没发现什么问题？ 还是很隐蔽的问题吗？

**Comment by airyland** [comment]
等我测试下，理想情况确实不应该用相对路径。做个调查，你是用于个人项目还是公司项目呢？

**Comment by lichunqiang** [comment]
个人的单子，主要是不是专业前端手。

**Comment by airyland** [comment]
直接使用路径测试没问题，可能当时我依赖安装有问题。

**Comment by lichunqiang** [comment]
:+1:
