### ISSUE TITLE
怎么能在panel组件中给底部添加事件

### ISSUE THREAD

**Issue by sunhongjian** [airyland/vux#390]
现在panel组件中demo的foot部分是查看更多并跳转到一个链接,能不能让这个跳转链接变成监听点击事件并执行某个方法,不太会改造,望指点

**Comment by airyland** [comment]
不指定footer.url, 直接监听`on-click-footer`事件。
https://github.com/airyland/vux/blob/master/src/components/panel/index.vue#L56-L59

**Comment by sunhongjian** [comment]
`  ready: function () {
    this.$on('on-click-footer', function () {
      console.log('成功触发');
    });
  },
`
我这么写不对,望指点
