### ISSUE TITLE
#390 补充

### ISSUE THREAD

**Issue by sunhongjian** [airyland/vux#392]
我vue基础不太好,望大神再指点一下
我的代码,没跑通
`  ready: function () {
    this.$on('on-click-footer', function () {
      console.log('成功触发');
    });
  },`

**Comment by airyland** [comment]
1.vue基础不好不应该来vux解决吧
2.不要重新开issue
3.针对问题，vux的事件触发都不是dispatch, 而是emit, 只能在组件本身监听
`<panel @on-click-footer="somemethod"></panel>`
