### ISSUE TITLE
我感觉是不是可以增加theme的功能，不局限于只有微信的绿色主题。

### ISSUE THREAD

**Issue by arden** [airyland/vux#394]
今天看了一下这个库，感觉非常强大，但是有时候可能并不太喜欢微信这种绿色的主题风格，我想估计很多用户也会有这个需求，可能会需要其它主题如：黑色风格等等，是不是可以增加让用户自定义主题的功能。

**Comment by airyland** [comment]
目前不支持，还没研究过如何做合适，并且你是第一个提这个建议的，可能后面会考虑一下。目前可以fork之后通过修改styles下的weui样式变量来实现(不保证能统一替换颜色)。

**Comment by terranc** [comment]
@airyland 我的一个意见是vux不要继承weui的样式，因为weui的样式都有基于less和sass的版本，开发者在项目中另行引入即可，vux的每个组件里只引入vux特有的一些差异化的样式即可，这样即便要换theme，直接去改weui的样式便可（vux的差异化样式里很少与theme相关的，至少配色什么的应该没有吧）。

**Comment by airyland** [comment]
@terranc vux不是继承，是直接使用weui的less源码。之前为什么要分拆weui的样式就是因为用户不想要重复不必要的css代码，让用户自行引入又回到这个问题了。后面有点看不明白，不引入weui代码，如何更改weui样式，不引入less的variable如何实现全局theme?

**Comment by terranc** [comment]
@airyland 我看vux里面也放了一份weui的less，说个这样的情况，我们现在项目用了vux，但某些组件是自己封装的，因为vux是按需加载weui的样式，而我们的组件并没有把weui拉到项目按需加载，因此现在还是的import weui.css，然后vux按需加载，这个情况应该很多项目都会有吧，这样一来vux按需加载省下的流量只是用到的vux组件中和weui差异化的部分。

如果需要更改theme，项目引用的当然也还是weui的less，我的意思用weui官方的源，并非一定是直接导入css。

**Comment by deanwong** [comment]
@airyland 目前也有这种需求，通过手工调整weUI的less是否可以达到？

**Comment by airyland** [comment]
@deanwong 理论上可以，但是现在这样做就得自己fork一份修改
