### ISSUE TITLE
how to get value by chinese in Address Component

### ISSUE THREAD

**Issue by YeomanYang** [airyland/vux#395]
### Android or iOS
both

### Description
When I use Address components,I found the data type is number.So I use the function 'value2name' in Vux to get the chinese address.But now,I want to get the value by chinese address.I try the function 'name2value' in Vux,it didn't work.
so I want to know how can I get the value by chinese address?

### Your Codes 

``` html
<!--put your code here-->


### Expected behavior and actual behavior.

### Steps to reproduce the problem

**Comment by airyland** [comment]
Please explain "it did't work" and reopen this issue.
