### ISSUE TITLE
popup-picker重新赋值后，无法选中默认值

### ISSUE THREAD

**Issue by geraldlrh** [airyland/vux#398]
如官方demo: https://vux.li/#!/component/popup-picker
先点重新赋值 -> 点上面的手机机型，可以看到默认选中了「小米1」-> 点完成 -> 没有应用到上面的cell，还是iPhone

**Comment by eshion** [comment]
同样遇到+1,希望能修复

**Comment by lichunqiang** [comment]
chrome请使用手机模拟器，我这儿没发现你所说的问题

**Comment by geraldlrh** [comment]
@lichunqiang 我就是用的模拟器

**Comment by lichunqiang** [comment]
![1](https://cloud.githubusercontent.com/assets/2433916/16939208/097e110c-4db2-11e6-893d-b5959f54093f.gif)

**Comment by geraldlrh** [comment]
@lichunqiang 点开后不能滑，就默认第一个
