### ISSUE TITLE
Address 组件 中的省市区 在vue-router返回上一页然后刷新一下，再点进来报错为 Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by dingyiming** [airyland/vux#403]
Address 组件 中的省市区 在vue-router返回上一页然后刷新一下，再点进来报错为 `Cannot read property 'appendChild' of null`
![image](https://cloud.githubusercontent.com/assets/12537013/16944114/b57e7d88-4dd1-11e6-8347-987d3467ffd5.png)

![image](https://cloud.githubusercontent.com/assets/12537013/16944351/b25c5318-4dd2-11e6-82e5-1430883c6619.png)

![image](https://cloud.githubusercontent.com/assets/12537013/16944361/c2bb8986-4dd2-11e6-8896-e2b917450fc9.png)

## 动态截图 
* 正常刷新没报错
* 返回后直接再进来没报错
* 返回后刷新一下，再进来报错了，然后只是在引入了address地址组件才报错，注释掉，就没这个情况了 
![1](https://cloud.githubusercontent.com/assets/12537013/16944530/9c8559ee-4dd3-11e6-8c23-5629c845d685.gif)

## 补充个debug
![2](https://cloud.githubusercontent.com/assets/12537013/16944978/9dac003c-4dd5-11e6-8f69-cda95776adc8.gif)

**Comment by lichunqiang** [comment]
你这个让人很头疼，不按照套路来，给这么点信息很难定位，需要花很多时间来复现，能不能提供多点的信息，

**Comment by dingyiming** [comment]
谢谢

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/16945143/7dd5d69c-4dd6-11e6-8120-46607eaf8fc6.png)

发现是这个问题，在<router-view></router-view> 里用了 transition

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/16945487/d8635be2-4dd7-11e6-8775-f20302c17eeb.png)
![aexo h_dg5275qp pgbxbyr](https://cloud.githubusercontent.com/assets/12537013/16945490/d9cb87e8-4dd7-11e6-9e11-456b28a3d620.png)
__container 为 null
调用了null 的appendChild所以报错

**Comment by cheneywan** [comment]
同样遇到这个问题，，虽然似乎并没有什么影响，但最后怎么解决的？总不能为此不用 transition 了吧？
