### ISSUE TITLE
x-input中min和max属性类型错误bug

### ISSUE THREAD

**Issue by kevinlvhsl** [airyland/vux#411]
```
x-input(
            :value.sync="inputValue",
            min=2,
            max=11,
            show-clear=true,
            is-type="{{checkType}}")
```
min=2 和max=11
会报：`Invalid prop: type check failed for prop "max". Expected Number, got String. (found in component: <x-input>)`
是不是在判断的时候弄错了？

**Comment by airyland** [comment]
`:min=2`
`:max=11`

**Comment by kevinlvhsl** [comment]
谢谢。    is-type  验证不通过的时候， 怎么获取验证结果？
