### ISSUE TITLE
如何做出如下效果

### ISSUE THREAD

**Issue by zhaoxiang051405** [airyland/vux#412]
## 期望效果

![img_0254](https://cloud.githubusercontent.com/assets/12930222/17016552/35d0fb78-4f62-11e6-8b71-8c4351bb76d1.PNG)

## 问题说明：

我试看了demo的全部内容，发现当前框架是我发现的组件较为全面的一个，但是却很遗憾没有找到上图所示的效果！所以在这里询问下！

**Comment by airyland** [comment]
已经开发实现了类似的`swipeout`组件，暂时未测试发布。

其实在web里做这个操作挺奇怪，除非发布成App。

**Comment by lichunqiang** [comment]
#139
目前没有组件，如果有能力和兴趣的话，欢迎PR.

**Comment by airyland** [comment]
Moved to #139

**Comment by zhaoxiang051405** [comment]
目前做个手机端的后台管理系统这样的需求很需要，不然那么多按钮实在不知道怎么放！

**Comment by airyland** [comment]
不一定需要都显示出来啊，右边加一个操作按钮，点击后用actionsheet展示操作菜单也是可以的。

**Comment by zhaoxiang051405** [comment]
![qq 20160721165735](https://cloud.githubusercontent.com/assets/12930222/17017037/4494efaa-4f64-11e6-94a1-caf23f152b96.jpg)

禁用和删除用`swipeout`然后点击删除后出现`actionsheet`提示是否确定删除！直接单击那个记录出现`actionsheet`提示授权给哪个组，目前我的思路是这样，当然确认是否删除可以用`confirm`！个人习惯吧~还是谢谢你们的辛勤劳动，给我们提供这个UI框架！

**Comment by airyland** [comment]
你上面这个图看起来很PC啊 
就移动端的交互来说，人性一点应该是统一交互，如果用actionsheet，在当前操作里建议一直用actionsheet。
actionsheet也可以当confirm用， actionsheet里有删除，禁用，授权这些菜单，点击删除后再出现第二actionsheet有个红色的确定和取消。

**Comment by zhaoxiang051405** [comment]
对啊，上图是我的PC版本的截图，最新想拓展一个手机端的版本！所以就问问，在你们没有放出`swipeout`的情况下，你的思路确实是一个非常棒的解决方案！谢谢~

**Comment by graysheeep** [comment]
我也觉得在web上做这个操作其实挺奇怪的，还真不如右边放三个点，点击后弹出操作菜单

**Comment by mitboy1983** [comment]
swipeout 不是已经有这个效果了么？ 我前几天正好做到这个，已经实现了！

**Comment by SmallJune** [comment]
我想问下 swipeout 组件能否判断它的状态， 打开或关闭状态
