### ISSUE TITLE
number-roller宽度自动计算的问题

### ISSUE THREAD

**Issue by wancy86** [airyland/vux#415]
number-roller宽度如果使用自动计算，当数字从99变成100时会自动变为3位，但是如果从100变为99时，计算的宽度从3变成了2，但是显示上还是3位，只是第一位用0填充了。

**Comment by airyland** [comment]
如果不是这样填充，突然第一位不见了也不好吧，然后从2到3位也没法平滑变化吧。你的意思是，直接把第一位删掉？从2到3位时再跳出来么？

**Comment by airyland** [comment]
其实建议是预估最大的位数。
