### ISSUE TITLE
calendar组件禁止选未来时间

### ISSUE THREAD

**Issue by moxuandeng** [airyland/vux#416]
calendar组件有个属性```disable-past```可以禁止选过去的时间, 是否考虑增加个属性禁止选未来的时间呢?  或者```start-date```与```end-date```能和value一样传入关键字```TODAY```来表示当日.

虽然自己计算出当日的日期赋值给end-date, 也能满足需求, 不过没有组件直接提供来的方便

**Comment by airyland** [comment]
可以。这个没什么开发成本，下个版本支持。
