### ISSUE TITLE
vux.li这个demo的源码能否开放出来?

### ISSUE THREAD

**Issue by outman2008** [airyland/vux#417]
帮助文档写得不是很示例完善,好多没有示例代码
vux.li 的例子很多,这个项目能否开源??
不胜感谢!!!

**Comment by lichunqiang** [comment]
`src/demos` 下面就是所有源码，在本地 `npm run dev` 即可在本地看

**Comment by whjspdi** [comment]
@outman2008 那个例子就是vux/src/demo

**Comment by outman2008** [comment]
谢谢了,初来乍到不认识路.抱歉
最好能在首页上提一句,找了好久....
