### ISSUE TITLE
无法解决scroller 在keep-alive 缓存 切换页面后重置问题

### ISSUE THREAD

**Issue by yhZhouYh** [airyland/vux#419]
this.$nextTick(() => {
            console.log(this.$refs)
            this.$els.tabbox.style = 'width:' + 1.6 * this.selectList.length + 'rem'
            this.$refs.scroller.reset()
          })

在vue-router 中调用如上函数， 滑动父盒子宽度通过获取数据列表长度自定义，首次加载可以正确滑动，切换页面keep-alive 切换回来，虽然执行了 但是并不能滑到指定位置

**Comment by airyland** [comment]
要滑到指定位置可以取得scroller ref的_xscroll对象来使用[XScroll](http://xscroll.github.io/)的方法

**Comment by yhZhouYh** [comment]
不是指定位置， 意思是滑不到底， 滑过去 又回到起始位置， 就跟没设置宽度类似

**Comment by hubinjie** [comment]
```
route: {
      data (transition) {
        this.$refs.scroller.reset()
    }
}
```
试一下

**Comment by airyland** [comment]
最后解决了吗？本地重现不了，需要你贴完整代码。
