### ISSUE TITLE
x-textarea字数统计异常

### ISSUE THREAD

**Issue by kevinlvhsl** [airyland/vux#420]
在统计字数的时候将回车符也统计进去了，而显示字数的时候没有计算进去。
PS： max是500，统计字数确实469，输入不足500字时，就不能再继续输入录入了。(469/500)
将回车符加进去了。 希望将显示的地方也计算加进去。

**Comment by kevinlvhsl** [comment]
```
x-textarea(
            placeholder="填写备忘信息",
            name="content",
            :max="500",
            :value.sync="content",
            :height="180",
            :show-counter="true"
          )
```

**Comment by lichunqiang** [comment]
http://www.bennadel.com/blog/161-ask-ben-javascript-replace-and-multiple-lines-line-breaks.htm

**Comment by kevinlvhsl** [comment]
@airyland  这个问题改吗？

**Comment by airyland** [comment]
改。下个版本。

**Comment by kevinlvhsl** [comment]
有时候需要在每次输入的时候监听一个change或者keyup之类的事件。
