### ISSUE TITLE
npm install vux  0.12dist/vue.css中无reset等样式

### ISSUE THREAD

**Issue by xingmolu** [airyland/vux#421]
### npm 安装
npm install vux
版本号：0.12

### 问题描述
1. `dist/vue.css`  中无reset等样式，但是git代码库里的`dist/vue.css` 里刚开始就是reset样式
2. 如果dist/vue.css中是完整的样式，那 `import Cell from 'vux-components/cell'` 又会导入cell的样式，导致样式冗余，请问怎么解决呢？

**Comment by airyland** [comment]
下个版本vux.css 才会有reset。如果你引入vux.css 请使用dist/components下的组件 如果你从src引入请引入reset
