### ISSUE TITLE
group + validator + x-input时的不便之处。

### ISSUE THREAD

**Issue by terranc** [airyland/vux#422]
**起因：**
在用其它validator时希望输入框初始状态时时没有`.weui_cell_warn`的，黑色文字；
在输入框失去焦点或者表单提交时验证是否需要添加`.weui_cell_warn`，并且让label也一并红色。
版本: `v0.1.2`

**现状：**
按照Demo的做法如果要让label变红，则给组件添加`class=weui_cells_form`，否则无法变成红色label。
但一旦添加该`class`，就会在初始状态label就是红色的（因为初始状态`valid`认为是`false`）。

**想法：**
- 是否需要添加一个`isForm=true`的属性来决定weui_cells是否需要添加`.weui_cells_form`？
- `input`组件的`.weui_cell_warn`是否在初始状态下不要添加上去
- `weui_cell_ft`里的icon能否从v-show改为v-if，避免有两个`.weui_icon weui_icon_warn`
- 不要强制要求vux必须搭配自带的validator（因为validator应该没那么快做到很完善），希望能够开放`x-input`,'x-textarea`等组件里`cell`的`valid`属性，可供外部设置，来决定`cell`是否需要标红

**Comment by lichunqiang** [comment]
1. 感觉必要性不大，毕竟只有在配合x-input的时候才有使用
2. 这个可以在组件内去掉默认在`ready`的时候对`required`的检查，交给用户自己来处理 @airyland 
3. 处于性能考虑？毕竟会是频繁的切换状态操作
4. 当然可以拿到 `this.$refs.input.valid = false`

**Comment by airyland** [comment]
@lichunqiang 去掉对required的检查会导致从ref取得的valid不正确吧。required为true时，即使我没有填写valid也是true。感觉这会导致使用者的检测逻辑有问题吧？

**Comment by terranc** [comment]
实践下来：
1、因为vux的封装，已经差不多忘了weui的cell需要些什么class了，既然其他的class都已不再去关心，唯独这个class需要记忆，而且是和控件表现逻辑相关的，希望还是考虑一下。
2、我的理解是初始化的时候不需要去检测valid吧。
3、是`v-show`还是`v-if`我只是提出一下，只是希望最好能避免两个`.weui_icon_warn`，比如使用者如果应用里出现了需要去操作这里的dom（虽然不是推荐的做法，但不能强制使用者一定不会引用个jq什么的来写一些补充逻辑吧），就不好选哪个，还得去关心vux内部的判断逻辑。
4、开始以为valid是只读的，测试了可以。
