### ISSUE TITLE
Tab+swiper 怎么组合使用

### ISSUE THREAD

**Issue by songhlc** [airyland/vux#425]
您好：我看到https://vux.li/?x-page=github_readme#!/component/tab 
里有一个tab＋swiper的例子。我在vux-doc里没有看到 swiper相关的介绍。想请问一下tab切换时触发swiper内容改变应该怎么写，我看源码里swiper.js里 通过transform做了一个动画效果，麻烦给点指导。
PS：https://vux.li上的代码有相关源码吗？在哪能看到？

**Comment by airyland** [comment]
给tab-item绑定click事情，改变swiper-item内容。
/src/demo

**Comment by songhlc** [comment]
我看swiper.vue源码发现了 直接props传入index就可以了 谢谢
