### ISSUE TITLE
建议：input 和 textarea 验证is-type 字段可以允许用户传自己写的正则表达式

### ISSUE THREAD

**Issue by kevinlvhsl** [airyland/vux#427]
is-type 字段： 当前默认提供的type比较少，不能满足大部分用户需求。
建议：可以允许用户传自己写的正则表达式，这样验证起来不需要再来写其他验证。

**Comment by airyland** [comment]
在考虑中，既然可以传正则，那也得可以自己传错误提示信息。也得允许用户不使用默认的验证条件，所以考虑起来实际挺复杂。

**Comment by airyland** [comment]
2.0 允许is-type传入function，以及更为灵活的禁用内置验证然后手动显示成功或者失败icon。
