### ISSUE TITLE
npm run dev错误

### ISSUE THREAD

**Issue by nihaibao** [airyland/vux#429]
npm-debug.log文件：
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vux@0.1.3-rc2~predev: vux@0.1.3-rc2
6 silly lifecycle vux@0.1.3-rc2~predev: no script for predev, continuing
7 info lifecycle vux@0.1.3-rc2~dev: vux@0.1.3-rc2
8 verbose lifecycle vux@0.1.3-rc2~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vux@0.1.3-rc2~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ellipsis/Apps/caoyao/node_modules/.bin:/usr/local/bin:/Users/ellipsis/.composer/vendor/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/go/1.6/bin
10 verbose lifecycle vux@0.1.3-rc2~dev: CWD: /Users/ellipsis/Apps/caoyao
11 silly lifecycle vux@0.1.3-rc2~dev: Args: [ '-c', 'node build/dev-server.js' ]
12 silly lifecycle vux@0.1.3-rc2~dev: Returned: code: 1  signal: null
13 info lifecycle vux@0.1.3-rc2~dev: Failed to exec dev script
14 verbose stack Error: vux@0.1.3-rc2 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid vux@0.1.3-rc2
16 verbose cwd /Users/ellipsis/Apps/caoyao
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error vux@0.1.3-rc2 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the vux@0.1.3-rc2 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vux package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vux
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vux
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by airyland** [comment]
不确定是什么问题，试试改变dev-server里的商品试试

**Comment by GirlSmileToMe** [comment]
node版本是不是太高了

**Comment by airyland** [comment]
另外也试试把监听的地址0.0.0.0改成127.0.0.1试试

**Comment by simon82** [comment]
我也遇到同样的问题。源码下载后什么也没改动，运行npm run dev就出现几千个错误。
部分出错信息：
 ✘  http://eslint.org/docs/rules/indent                       Expected indentation of 6 space characters but found 8                         
  /Users/simon/Documents/workspace/vux-project/src/components/x-swiper/swiper.dom.js:3513:9
          return window.Swiper;
           ^

  ✘  http://eslint.org/docs/rules/semi                         Extra semicolon                                                                
  /Users/simon/Documents/workspace/vux-project/src/components/x-swiper/swiper.dom.js:3513:29
          return window.Swiper;
                               ^

  ✘  http://eslint.org/docs/rules/semi                         Extra semicolon                                                                
  /Users/simon/Documents/workspace/vux-project/src/components/x-swiper/swiper.dom.js:3514:7
      });
         ^


✘ 3953 problems (3953 errors, 0 warnings)


Errors:
  2121  http://eslint.org/docs/rules/indent
  1329  http://eslint.org/docs/rules/semi
   183  http://eslint.org/docs/rules/no-trailing-spaces
   118  http://eslint.org/docs/rules/brace-style
    69  http://eslint.org/docs/rules/spaced-comment
    18  http://eslint.org/docs/rules/one-var
    15  http://eslint.org/docs/rules/padded-blocks
    14  http://eslint.org/docs/rules/space-before-function-paren
    10  http://eslint.org/docs/rules/no-multi-spaces
    10  http://eslint.org/docs/rules/curly
     8  http://eslint.org/docs/rules/no-multiple-empty-lines
     7  http://eslint.org/docs/rules/space-infix-ops
     7  http://eslint.org/docs/rules/key-spacing
     7  http://eslint.org/docs/rules/space-unary-ops
     7  http://eslint.org/docs/rules/no-unused-vars
     6  http://eslint.org/docs/rules/keyword-spacing
     6  http://eslint.org/docs/rules/no-undef
     5  http://eslint.org/docs/rules/no-mixed-spaces-and-tabs
     5  http://eslint.org/docs/rules/space-in-parens
     3  http://eslint.org/docs/rules/space-before-blocks
     2  http://eslint.org/docs/rules/semi-spacing
     1  http://eslint.org/docs/rules/block-spacing
     1  http://eslint.org/docs/rules/comma-spacing
     1  http://eslint.org/docs/rules/no-unneeded-ternary

ERROR in ./src/components/range/range/lib/lib/matches-selector.js

  ✘  http://eslint.org/docs/rules/no-undef  'Element' is not defined  
  /Users/simon/Documents/workspace/vux-project/src/components/range/range/lib/lib/matches-selector.js:11:13
  var proto = Element.prototype
               ^


✘ 1 problem (1 error, 0 warnings)


Errors:
  1  http://eslint.org/docs/rules/no-undef
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  21.8 kB       0       
webpack: bundle is now VALID.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! vux@0.1.2 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vux@0.1.2 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/simon/Documents/workspace/vux-project/npm-debug.log

**Comment by airyland** [comment]
@simon82 这能是一样的错误吗。。

**Comment by simon82** [comment]
楼主上面那个问题应该是端口问题，我改了端口以后终于成功搭建成功。谢谢 @airyland

**Comment by nihaibao** [comment]
谢谢楼上各位 端口换了可以了 我也没发现别进程占用8080呀

**Comment by airyland** [comment]
@nihaibao 这个可能是我的错，ip是直接监听了0.0.0.0可能造成了冲突，现在已经是默认监听127.0.0.1了。
