### ISSUE TITLE
scroller在vue-router返回时的定位问题

### ISSUE THREAD

**Issue by JianleiZhang** [airyland/vux#431]
在scroller里上下滑动后，如果点击跳转到下一页然后返回，这时scroller会显示最上面的数据而不是之前滑动的位置。请问如何定位到之前的位置？

**Comment by airyland** [comment]
你可以取得该组件ref的_xscroll对象来调用相应的方法。具体查看xscroll文档

**Comment by JianleiZhang** [comment]
vue-router里可以设置保存状态：
`<router-view keep-alive></router-view>`

[https://github.com/vuejs/vue-router/issues/328](url)
