### ISSUE TITLE
Toast组件 提醒后，无法点击其他元素

### ISSUE THREAD

**Issue by ColdXu** [airyland/vux#433]
### Version
0.1.1

### Android or iOS
Android

### Your Codes 

``` html
<toast :show.sync="HeadImgsuccess" :time="1000">上传成功</toast>
```

### Expected behavior and actual behavior.
toast显示消失后，其他元素就无法点击，项目中所有页面都有这种情况发生。

**Comment by ColdXu** [comment]
ios 和 android都有这种情况

**Comment by ColdXu** [comment]
同时纠正下问题，并不是所有页面元素无法点击触发，
toast启用并关闭后，vux关联的表单无法点击触发

**Comment by airyland** [comment]
这种情况看起来像是mask没有隐藏的情况，需要你帮忙看下是不是.weui_mask_transparent样式被其他的什么样式覆盖或者有什么特别的样式存在。

**Comment by veryinf** [comment]
这个问题确认存在，.weui_mask_transparent 没有正确隐藏。在demo中多点击几次也会重现

**Comment by airyland** [comment]
似乎我无法重现， @ColdXu  @veryinf 能否告诉我应该怎么修复 :sweat_smile:
