### ISSUE TITLE
Swiper的list初始化为[{}]会去请求一个图片地址

### ISSUE THREAD

**Issue by JianleiZhang** [airyland/vux#434]
会去请求http://localhost:8080/undefined，查找下来是swiper的原因，或者说我初始化的方式不对。

我是在vuex里初始化这个list的，然后actions里去请求数据，整理后将list重新赋值。

**Comment by airyland** [comment]
如果是空数据，应该是空数组，为什么要加一个空的Object?

**Comment by JianleiZhang** [comment]
我试过用空的数组去初始化，无法成功加载这个组件。

**Comment by airyland** [comment]
空数组里没有显示出来任何东西这是正常的逻辑吧。你的无法成功加载是啥意思？

**Comment by airyland** [comment]
动态更新list是支持的，如果不行，请上代码看看。

**Comment by JianleiZhang** [comment]
代码分得很散，我写个测试例子看看。目前看是即使重新赋值了，组件也不会出现。

**Comment by JianleiZhang** [comment]
`<template>
  <div>
    <swiper :list="list"></swiper>
  </div>
</template>

<script>
import Swiper from 'vux-components/swiper'
export default {
  components: {
    Swiper,
  },
  data () {
    return {
      list: []
    }
  },
  ready () {
    this.list =
      [{
	url: 'javascript:',
	img: 'http://7xqzw4.com2.z0.glb.qiniucdn.com/1.jpg',
	title: '如何手制一份秋意的茶？'
      }, {
	url: 'javascript:',
	img: 'http://7xqzw4.com2.z0.glb.qiniucdn.com/2.jpg',
	title: '茶包VS原叶茶'
      }, {
	url: 'javascript:',
	img: 'http://7xqzw4.com2.z0.glb.qiniucdn.com/3.jpg',
	title: '播下茶籽，明春可发芽？'
      }]
  }
}
</script>`

上面代码无法成功加载组件，但是改成list: [{}]则成功加载组件,但会去请求http://localhost:8080/undefined

**Comment by JianleiZhang** [comment]
还不怎么会用github，代码格式无法保存。

**Comment by airyland** [comment]
```` html `

**Comment by airyland** [comment]
其实如果你告诉我你说的`无法成功加载`是因为高度被设成auto导致没有显示出来，这个问题可以几分钟内就解决了。。

**Comment by JianleiZhang** [comment]
谢谢，可以显示了。
