### ISSUE TITLE
建议：能添加一个侧滑栏的功能吗？

### ISSUE THREAD

**Issue by wanghaixu** [airyland/vux#435]
看完这个UI库后，很激动，很兴奋。功能很强大，很实用，在此表达一下膜拜。
***但一直没找到一个常用的侧滑栏的功能，有点失望。这个功能还是很多项目用到的。
如果可以，希望下一次版本能出现这个组件，再次感谢热爱贡献的你们！。

**Comment by airyland** [comment]
#139  计划中
