### ISSUE TITLE
x-header的showBack如何在后退到第一页时隐藏

### ISSUE THREAD

**Issue by JianleiZhang** [airyland/vux#436]
我知道`showBack: true`可以隐藏，但是Google了很久都没有想到如何判断已经后退到第一页，求指教。

**Comment by lichunqiang** [comment]
判断url可以吧

**Comment by JianleiZhang** [comment]
但是如果第二次经过这个url的情况下，回退会有问题吧。

**Comment by fundon** [comment]
这个应该属于业务逻辑了。

**Back** 的逻辑看页面情况了，还有页面中的 tabs, 这些倒是可以给 route 添加属性来判断。

**Comment by JianleiZhang** [comment]
我倒是没想的这么复杂，就想搞个变量，go的时候+1,back的时候-1,跳转的时候判断一下这个变量。

**Comment by airyland** [comment]
@JianleiZhang 实际上已经复杂了，从技术上讲，并不能精确地知道当前是forward还是back。

**Comment by JianleiZhang** [comment]
那基本上是不可行了，只能从业务逻辑上考虑了。
