### ISSUE TITLE
build/build-styles.js无作用

### ISSUE THREAD

**Issue by wulucxy** [airyland/vux#437]
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```

### Steps to reproduce the problem
在master分支上执行`npm run xbuild`只有，build-styles并没有将styles下面的文件拷贝到dist目录下。

PS：找到原因了，因为我是直接把整个dist目录删掉了，找不到styles目录，node就无法写入文件了，在执行`npm run xbuild`之前，先`mkdir dist/styles`就解决了。

不过建议还是增加一个目录是否存在的判断，否则像我这样不明真相的群众就需要去查看源代码了

@airyland

**Comment by airyland** [comment]
已经修复，感谢反馈
