### ISSUE TITLE
初学者，能否出一个文档搭建vux.li这个demo的过程

### ISSUE THREAD

**Issue by simon82** [airyland/vux#438]
您好，研究了很久，通过vue-cli项目引用.vue组件(推荐)的方式安装vux，但根据目前文档的叙述，自己还是不能把vux.li这个demo搭建起来。只能搭起Vue.js app的Hello World的网页。
能否出一个教程，帮助初学者入门，把vux.li这个demo搭建起来。谢谢

**Comment by airyland** [comment]
vux.li的代码都在src里的main.js 和 demos里

**Comment by simon82** [comment]
我说一下我的步骤吧，麻烦您看看是否正确。
1. vue init webpack vux-project
2. cd vux-project
3. npm install
4. npm install vux
5. npm install less less-loader --save-dev
以上5步都是文档上写的，项目会生成如下结构
vux-project - |
                     - | node-modules
                     - | build
                     - | config
                     - | src
                     - | static
                     - index.html
6. npm run dev， 这时访问localhost:8080就会显示vue.js app Hello World的网页
接下来该怎么搭vux.li站点呢？
把您指的src目录覆盖上述vux-project/src目录，npm run dev，不行
然后我又把整个vux-master的内容放到vux-project中，npm run dev，不行

还请多多指点，谢谢

**Comment by airyland** [comment]
这其实跟vux无关了，按照vue-loader的文档来，使用vue-router做路由来切换不同页面就行了。

**Comment by simon82** [comment]
还是没能部署成功。
我下载了vux-0.1.2源码，然后运行npm run dev，就出现一千多个错误。请问一下是什么原因呢？谢谢
 ✘  http://eslint.org/docs/rules/indent                       Expected indentation of 6 space characters but found 8                         
  /Users/simon/Documents/workspace/vux-project/src/components/x-swiper/swiper.dom.js:3513:9
          return window.Swiper;
           ^

  ✘  http://eslint.org/docs/rules/semi                         Extra semicolon                                                                
  /Users/simon/Documents/workspace/vux-project/src/components/x-swiper/swiper.dom.js:3513:29
          return window.Swiper;
                               ^

  ✘  http://eslint.org/docs/rules/semi                         Extra semicolon                                                                
  /Users/simon/Documents/workspace/vux-project/src/components/x-swiper/swiper.dom.js:3514:7
      });
         ^


✘ 3953 problems (3953 errors, 0 warnings)


Errors:
  2121  http://eslint.org/docs/rules/indent
  1329  http://eslint.org/docs/rules/semi
   183  http://eslint.org/docs/rules/no-trailing-spaces
   118  http://eslint.org/docs/rules/brace-style
    69  http://eslint.org/docs/rules/spaced-comment
    18  http://eslint.org/docs/rules/one-var
    15  http://eslint.org/docs/rules/padded-blocks
    14  http://eslint.org/docs/rules/space-before-function-paren
    10  http://eslint.org/docs/rules/no-multi-spaces
    10  http://eslint.org/docs/rules/curly
     8  http://eslint.org/docs/rules/no-multiple-empty-lines
     7  http://eslint.org/docs/rules/space-infix-ops
     7  http://eslint.org/docs/rules/key-spacing
     7  http://eslint.org/docs/rules/space-unary-ops
     7  http://eslint.org/docs/rules/no-unused-vars
     6  http://eslint.org/docs/rules/keyword-spacing
     6  http://eslint.org/docs/rules/no-undef
     5  http://eslint.org/docs/rules/no-mixed-spaces-and-tabs
     5  http://eslint.org/docs/rules/space-in-parens
     3  http://eslint.org/docs/rules/space-before-blocks
     2  http://eslint.org/docs/rules/semi-spacing
     1  http://eslint.org/docs/rules/block-spacing
     1  http://eslint.org/docs/rules/comma-spacing
     1  http://eslint.org/docs/rules/no-unneeded-ternary

**Comment by airyland** [comment]
根目录下有 .eslintignore文件吗？

**Comment by simon82** [comment]
我在复制文件时，隐藏文件（诸如.eslintignore等）没有被复制到，所以造成上面的错误，谢谢大神的解答。

**Comment by airyland** [comment]
如果你是想在本地运行demo, 直接clone就好。
