### ISSUE TITLE
单独引用后还是出现 样式重复问题

### ISSUE THREAD

**Issue by yhZhouYh** [airyland/vux#439]
.weui_cells {
    margin-top: 1.17647059em;
    background-color: #FFFFFF;
    line-height: 1.41176471;
    font-size: 17px;
    overflow: hidden;
    position: relative;
}

.weui_cells {
    margin-top: 1.17647059em;
    background-color: #FFFFFF;
    line-height: 1.41176471;
    font-size: 17px;
    overflow: hidden;
    position: relative;
}

**Comment by yhZhouYh** [comment]
import Group from 'vux/src/components/group'
  import Cell from 'vux/src/components/cell'
引入方式

**Comment by yhZhouYh** [comment]
去掉源文件下任意一个/*@import '../../styles/weui/widget/weui_cell/weui_cell_global';*/ 显示正常 没有重复现象

**Comment by airyland** [comment]
这个主要是这样引用的时候webpack loader并不会自动进行合并，需要手动处理一下，参考这里：
https://github.com/airyland/vux/blob/master/build/nano-css.js
目前没有更好的方法。

**Comment by yhZhouYh** [comment]
cli 生成的项目。 在哪里加。。cssnano 操作

**Comment by airyland** [comment]
你可能要稍微改装一下，用fs模块到你的build目录下搜索一下css文件处理。然后添加到package.json里的scripts里的build后面， `&& node build/nano-css.js`

**Comment by yhZhouYh** [comment]
嗯。小白 生成的css带上了版本出 我需要正则匹配到这个文件是么

**Comment by airyland** [comment]
小白是谁。。

**Comment by xiaolongyuan** [comment]
@airyland  最终的 打包 是 
![image](https://cloud.githubusercontent.com/assets/3142363/17282031/e1919aca-57d3-11e6-9ad9-0fa7038f8e3d.png)

这段代码有什么意义 

```
const cssnano = require('cssnano')
const fs = require('fs')
const path = require('path')

const code = fs.readFileSync(path.resolve(__dirname, '../dist/vux.css'))
cssnano.process(code.toString(), {zindex: false}).then(function (result) {
  fs.writeFileSync(path.resolve(__dirname, '../dist/vux.css'), result.css)
})
```

**Comment by airyland** [comment]
看看cssnano的文档呗，主要是去除重复样式代码。

**Comment by yhZhouYh** [comment]
@airyland 小白是我。。。我太不会写正则匹配到这个文件。。

**Comment by xiaolongyuan** [comment]
fs 是哪个库？

**Comment by airyland** [comment]
参照我上面的, copy过去用就行了。

**Comment by xiaolongyuan** [comment]
@airyland 谢了 要安装那些依赖呢

**Comment by airyland** [comment]
这个就没必要一个一个说了，都在代码里。

**Comment by whwnow** [comment]
有个疑问，weui里面是有部分reset的css代码。
我只引用vux的css的时候好像没带着，是说我还得自己写上rest的css代码么？

**Comment by greedying** [comment]
感谢，已经用上了
