### ISSUE TITLE
common-nano-css中路径问题

### ISSUE THREAD

**Issue by wg5945** [airyland/vux#442]
### Version
0.1.2
### Android or iOS

ALL

### Your Codes 

vux/build/common-nano-css.js这个文件中
``` html
let PATH = path.join(__dirname, '../', process.argv[2]) || 'dist/static'
```
这里指向的应该是css文件夹吧，而不应该是static文件夹，应改为
``` html
let PATH = path.join(__dirname, '../', process.argv[2], 'css') || 'dist/static/css'
```

还有用到let的话，头部不是应该应该加上
``` html
"use strict";
```
的么，我用的webstorm

**Comment by airyland** [comment]
额 因为我是在static下，你可以发个pr

**Comment by wg5945** [comment]
我直接用的是vuxjs/webpack，怎么文件夹还会不一样的哈~~
