### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export 问题出现在src/libs/router.js

### ISSUE THREAD

**Issue by lili520** [airyland/vux#444]
使用vuxjs模板的模板， vue init vuxjs/webpack vux， 然后把package.json和less lessloader模块都安装了, npm run dev运行之后就报错 Uncaught SyntaxError: Unexpected token export，错误来源：vux@0.1.2/src/libs/router.js 
![image](https://cloud.githubusercontent.com/assets/4424015/17325903/b39cdd60-58e0-11e6-9cb0-d9ebf09fd1f1.png)
麻烦大神们给看一下这是啥问题，谢谢！

**Comment by airyland** [comment]
你调用了什么组件导致的？

**Comment by jxunx** [comment]
@lili520 没有加这个吧？
``` JavaScript
      {
        test: /vux.src.*?js$/,
        loader: 'babel'
      },
```

**Comment by lili520** [comment]
@airyland 默认模板代码，没有改动过，默认调用的是HelloFromVux.vue里面的group和cell。

**Comment by lili520** [comment]
@jxunx 默认的vuxjs/webpack模板里面自带的有这个。。。

**Comment by jxunx** [comment]
我有一个用 vuxjs/webpack 模板，不会自动加那一段

**Comment by lili520** [comment]
@jxunx 我刚才又init了一个 vuejs/webpakc 模板，里面是自带的有`{
        test: /vux.src.*?js$/,
        loader: 'babel'
      },`
那你有发现是什么问题导致的吗？

**Comment by jxunx** [comment]
@lili520 没 orz

**Comment by airyland** [comment]
@lili520 没有什么思路，你打包一份代码到我邮箱吧。

**Comment by lili520** [comment]
@airyland 好的，已发你邮箱，谢谢。感觉也有可能是开发环境的问题，但具体我也找不到问题出在哪里了。

**Comment by lili520** [comment]
@airyland @jxunx 确定是开放环境的问题，以前安装的node是官方的v4.4.7 pkg版本，然后我把这个卸载后用nvm安装了node 5.5.0版本的，没有再出现这个问题。

**Comment by airyland** [comment]
泪牛满面。
