### ISSUE TITLE
tabbar 高亮选中Tab图片的优化方法

### ISSUE THREAD

**Issue by ryli** [airyland/vux#445]
tabbar插件貌似没有提供高亮选中选中Tab图片的功能。
想了一个方便的通过CSS解决的方法：
```
.weui_tabbar_icon img {
  filter: grayscale(1);
  -webkit-filter: grayscale(1);
}
.weui_tabbar_item.weui_bar_item_on .weui_tabbar_icon img {
  filter: initial;
  -webkit-filter: initial;
}
```
效果：
![image](https://cloud.githubusercontent.com/assets/4973519/17332135/470710d8-5900-11e6-957d-420a162473d5.png)

**Comment by airyland** [comment]
这个做法ok。但是这里大家可能需求样式不一样，在vux上不能这样统一设定，更建议大家自行覆盖样式。

**Comment by Leega0** [comment]
android4.4以下的都不管不顾了么

**Comment by lichunqiang** [comment]
@Leega0 请说明的你的问题，最好新开issue来讨论
