### ISSUE TITLE
建议：完善一下文档

### ISSUE THREAD

**Issue by wanghaixu** [airyland/vux#448]
问题一：demo中有的实例而文档中却没有找到，比如：搜索组件
问题二：希望能注明一下引用了哪个组件的js,css
问题三：希望能给出组件之间组合的规则

**Comment by airyland** [comment]
问题二是什么意思？

**Comment by wanghaixu** [comment]
中文文档中组件只给出了，dom结构。

**Comment by wanghaixu** [comment]
当然，我现在是知道怎么使用了，但新人不一定知道。

**Comment by airyland** [comment]
你说的我依然理解不了。
