### ISSUE TITLE
x-img 在子元素的滚动中使用, bLazy 的 container配置

### ISSUE THREAD

**Issue by cx-emerge** [airyland/vux#449]
`x-img` 在子元素的滚动中使用, `x-img` 的 `bLazy` 的 `container`配置项默认为`window`,如何修改为指定元素
[x-img](https://github.com/airyland/vux/blob/master/src/components/x-img/index.vue)
[blazy blog](http://dinbror.dk/blog/blazy/?ref=github)

### Version
- Vue v1.0.26
- Vux v0.1.2

### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` jade
// .l-main 为子滚动元素
.l-main
	x-img(
		@on-error="xImgOnError",
		:src="'/storages' + product.savepath + product.image",
		:offset="-100"
	)
```

**Comment by airyland** [comment]
暂时无法支持，需要为组件加相关属性。暂时的话你可以直接使用blazy来实现你的需求。

**Comment by cx-emerge** [comment]
好的,谢谢
