### ISSUE TITLE
vux.li 无法正常显示网页

### ISSUE THREAD

**Issue by iflamed** [airyland/vux#45]
Console error:

Uncaught Error: Cannot find module "!!vue-html-loader!./../../node_modules/.npminstall/vue-loader/8.2.1/vue-loader/lib/selector.js?type=template&index=0!./Calendar.vue"

**Comment by airyland** [comment]
可能早上Dev发布有问题 我呆会确认下

**Comment by zhipenglin** [comment]
vux.li 无法正常显示网页+1

**Comment by airyland** [comment]
已经重新发布，感谢反馈。
