### ISSUE TITLE
popup有联动时，滚动选择时会抖动

### ISSUE THREAD

**Issue by wg5945** [airyland/vux#450]
### Version
官网demo
### Android or iOS
IOS
> For Android issues, please specify the brand, model and browser

### Steps to reproduce the problem
官网sample [https://vux.li/?x-page=github_readme#!/component/address](https://vux.li/?x-page=github_readme#!/component/address) 
在ios微信浏览器，选择地址时会出现闪屏，Safari中出现向下抖动，android没有试验，不知道是不是改了什么东西了

**Comment by airyland** [comment]
已经修复
