### ISSUE TITLE
简单的测试, settimeout 在微信里面竟然不显示, 电脑浏览器没问题

### ISSUE THREAD

**Issue by shenfakuan** [airyland/vux#451]
`
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="__VUX__/vux.css" media="screen" title="no title" charset="utf-8">
    <title>say</title>
</head>
<body>
    <div id="demo">
        <group>
            <switch title="Toggle" :value.sync="show" @on-change="change"></switch>
        </group>
        <loading :show="show" :text="text1"></loading>
    </div>
    <script src="__VUE__/vue.js"></script>
    <script src="__VUX__/vux.js"></script>
    <script src="__VUX__/components/group/index.js"></script>
    <script src="__VUX__/components/switch/index.js"></script>
    <script src="__VUX__/components/loading/index.js"></script>
    <script type="text/javascript">
        Vue.component('group', vuxGroup);
        Vue.component('switch', vuxSwitch);
        Vue.component('loading', vuxLoading);
        var vm = new Vue({
            el: '#demo',
            data () {
                return {
                    show: false
                }
            },
            methods: {
                change: function (val) {
                    setTimeout(() => {
                        this.show = false
                    }, 1000)
                }
            }
        });
    </script>
</body>
</html>
`

**Comment by airyland** [comment]
js基础

``` js
methods: {
            change: function (val) {
               var _this = this
                setTimeout(() => {
                    _this.show = false
                }, 1000)
            }
        }
```

**Comment by airyland** [comment]
什么不显示？

**Comment by shenfakuan** [comment]
@airyland  貌似是 没有解析

**Comment by shenfakuan** [comment]
![246034545980549915](https://cloud.githubusercontent.com/assets/3233646/17393499/8b5db0d2-5a56-11e6-8d4c-464014470c0f.jpg)
![746215373422172050](https://cloud.githubusercontent.com/assets/3233646/17393500/8b950654-5a56-11e6-9426-ad38b461812c.jpg)
![qq 20160804151106](https://cloud.githubusercontent.com/assets/3233646/17393502/8bbb70fa-5a56-11e6-91f5-f5bde4b012ba.png)
![qq 20160804151556](https://cloud.githubusercontent.com/assets/3233646/17393501/8bba3924-5a56-11e6-80bf-8feedc036832.png)

只要 加上 
                    setTimeout(() => {
                        
                    }, 1000)

手机端 就不解析了, 电脑端没问题

**Comment by airyland** [comment]
不解析已经就不是vux的问题了，你确定你的运行环境支持箭头函数？没有报错？

**Comment by shenfakuan** [comment]
@airyland 真个真的不是vux 的问题, 我只用 vue 写一个 settimeout 箭头这种的,电脑上就没问题,微信(包括其他手机浏览器)里面就不行了,是不是 这个箭头手机端不支持呢?

**Comment by airyland** [comment]
@shenfakuan 一般都需要构建的，建议用vue-loader构建后，es2015基本都兼容。

**Comment by shenfakuan** [comment]
@airyland  不是做前端的,这个好痛苦呀

**Comment by hidoos** [comment]
@shenfakuan es2015写起来很爽，不过浏览器的支持还需要时间，所以需要把代码转换一下。有个网站叫做[caniuse](http://caniuse.com/),你可以在这个网站查询各种浏览器对js某个特性的支持情况。
