### ISSUE TITLE
Alert组件一直报错

### ISSUE THREAD

**Issue by NeilJee** [airyland/vux#452]
你好，我初次使用VUX。
在使用过程里其他都OK，当用到ALERT组件的时候。
一直报错
vue.common.js?e881:1019[Vue warn]: Invalid expression. Generated function body:  scope.hideOnBlur&&scope.show=false

找了很久都没找到问题，请问这是什么原因引起的？

多谢

**Comment by airyland** [comment]
Sorry 我的错 这个不影响使用 已经修复 下个版本就没这个报错了
