### ISSUE TITLE
demo 在IOS/Android 的微信/UC 浏览器上使用【address】控件会闪烁

### ISSUE THREAD

**Issue by IssaTan1990** [airyland/vux#457]
### Version
vux.li 的demo，不太清楚版本问题
### Android or iOS
Andorid 和 IOS都有
IOS 为Iphone5s, 系统版本9.3.3,  wechat 版本6.3.23
Andorid 为华为Mate7, 系统版本MT7-CL00V100R001C92B128SP05, UC版本11.0.0.818

### 描述
这是个真机才有的bug，我在微信web 开发者工具中模拟不出来。
在华为机中发现其实是整个 vux-picker 缩下去了。

**Comment by airyland** [comment]
华为的这个缩下去有截图吗？

**Comment by airyland** [comment]
闪烁的已经修复，华为的只在UC有问题？

**Comment by IssaTan1990** [comment]
【滑动时闪烁】这个问题在UC 上也修复了。
现在在华为UC 中唤起【address】时会有个红色的类似按钮形状的一闪而过，不知道什么原因... 
IOS 暂时没发现这个问题。

**Comment by airyland** [comment]
Address似乎没有红色的元素在。

**Comment by IssaTan1990** [comment]
我check 了另外一台酷派的UC 似乎也存在这个问题，至于红色，会不会是demo address 中最后一项 -> 错误的地址将不能正确渲染?

**Comment by airyland** [comment]
那只有一个console, 难道UC会显示出来。。
![image](https://cloud.githubusercontent.com/assets/559179/17472532/fad5feae-5d7d-11e6-9c85-cb95c3cdad84.png)

**Comment by airyland** [comment]
感谢反馈，确实是多了个red的样式，但是在常用机子里没有显示，于是被忽略了。
