### ISSUE TITLE
previewer组件的一点小问题

### ISSUE THREAD

**Issue by tw1997** [airyland/vux#459]
1、npm版本为3.6.0，node版本为v5.6.0，vux版本0.1.2

2、Google Chrome 版本 48.0.2564.97

一个页面使用了previewer组件。
点开previewer组件的图片，然后关闭，再点击a标签路由跳转 就会报错。而且页面也跳转不走。

报错信息：
Uncaught TypeError: Cannot read property 'destroy' of null          ---photoswipe.js?9c08:426

起初以为是我自己的问题，后来发现 提供的Demo上面也有同样的问题。所以问一下。

**Comment by airyland** [comment]
#454
