### ISSUE TITLE
在swiper中使用popup-picker的时候，无法选择滚动条

### ISSUE THREAD

**Issue by liu7923032** [airyland/vux#461]
### Version
0.1.2
### Android or iOS
ios and andorid
> For Android issues, please specify the brand, model and browser

### Your Codes 

 ```
     <swiper  height="500px" :show-dots="false">
       <swiper-item height="500px">
          <popup-picker title="TEST" :data="docTypeList" :value.sync="docType"></popup-picker>
       </swiper-item>
    </swiper>
```

```

## 异常
popup-picker的滚动条被遮盖住了，无法选择
### Steps to reproduce the problem

**Comment by airyland** [comment]
问一下，在swiper里用popup-picker是什么场景？

**Comment by liu7923032** [comment]
我在使用tab 标签的时候，有一个标签下面的内容都是表单信息

**Comment by airyland** [comment]
swiper里开发时没考虑到各种各样的嵌套。
复杂的交互新router里操作会比较安全。

**Comment by liu7923032** [comment]
嗯，我在重新设计一个页面吧，作者有时间可以看看bug

**Comment by airyland** [comment]
在一个absolute定位的div里使用popup就会有这个问题，可以这样解决：
``` html
<swiper-item height="500px" style="z-index:101;">
```
但是依然存在其他问题，比如点击遮罩无法关闭，因为点击的实际上是swiper-item, 而上下滑动选择和左右滑动两个手势同时存在会有问题。

所以如果确实要在swiper里做选择操作，可以把popup-picker放到外部，对于值和打开操作做一个映射即可。
具体参考：
https://vux.li/#!/issue/461
https://github.com/airyland/vux/blob/master/src/demos/Issue461.vue
