### ISSUE TITLE
Theme && i18n

### ISSUE THREAD

**Issue by airyland** [airyland/vux#462]
在v1.0(大概再过几个小版本)将正式支持组件样式全局自定义。在原有的微信风格上提供1-2个额外主题，再也不用担心太微信绿了。

主题切换和覆写使用webpack loader支持，同时支持全局组件文案国际化(i18n)配置，`en`及`zh-CN`

当前进行中:
- [x] Range

**Comment by kevinlvhsl** [comment]
我上次用就是重新将primary的颜色都覆盖了一次，   好辛苦。 期待。。

**Comment by airyland** [comment]
#Move to #715
