### ISSUE TITLE
sticky：如果tab元素不在首屏，tab-item元素将不会固定在顶部

### ISSUE THREAD

**Issue by zzzeep** [airyland/vux#464]
### Your Codes 

``` html

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

    <sticky>
      <tab :line-width=1>
        <tab-item :selected="demo4 === item" v-for="item in list4" @click="demo4 = item">{{item}}</tab-item>
      </tab>
    </sticky>
```

### Expected behavior and actual behavior.
问题出在sticky上，如果tab元素在页面下面（不在首屏），则下拉之后，tab-item元素将不会固定在顶部，IOS 出现此问题， Android 正常

**Comment by zzzeep** [comment]
@airyland 已经做过测试：如果tab元素在页面首屏，则 IOS、Android都正常，否则 IOS异常，Android正常

**Comment by zzzeep** [comment]
这里可能有更详细的说明 https://github.com/filamentgroup/fixed-sticky

**Comment by airyland** [comment]
按照你的代码，在iPhone上不能重现。你的代码下面也没有足够的占位让tab可以滚动到最上面。

**Comment by zzzeep** [comment]
试试这样：
````
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <sticky>
      <tab :line-width=1>
        <tab-item :selected="demo4 === item" v-for="item in list4" @click="demo4 = item">{{item}}</tab-item>
      </tab>
    </sticky>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
```

**Comment by airyland** [comment]
试过了，正常。

**Comment by airyland** [comment]
![issue464](https://cloud.githubusercontent.com/assets/559179/17454787/e73608ca-5bd5-11e6-8fbc-f9d670f91ba1.gif)

**Comment by zzzeep** [comment]
请用chrome控制台测试一下就知道了 http://www.atool.org/temp/20160806010739349.png

**Comment by zzzeep** [comment]
因为 css3 position:sticky 在一些情况下（依赖父级元素）是不工作的，可能单纯的一行代码，不能复现这个问题

**Comment by airyland** [comment]
所以你说的不是真机，而是模拟器么。
因为sticky是先检测了系统版本来判断是否要用js来支持，而chrome上模拟环境下虽然版本正确，但是实际并不支持，于是就这样了，真机是正常的。

**Comment by airyland** [comment]
https://github.com/airyland/vux/blob/master/src/components/sticky/sticky.js#L4-L8
