### ISSUE TITLE
ios系统，键盘处于激活状态下，popup-picker组件会出现滑动bug

### ISSUE THREAD

**Issue by Baiang** [airyland/vux#468]
键盘处于激活状态下，popup-picker组件会滑动到键盘高度后，等键盘消失后，再滑动到底部

**Comment by airyland** [comment]
并不能重现。激活状况下，点击popup-picker, 键盘正常收下。请说明机型浏览器。

**Comment by Baiang** [comment]
设备iphone6s plus 浏览器uc，其它浏览器测试正常

**Comment by airyland** [comment]
iPhone6s UC无法重现。键盘是如何处于激活状态的，再打开popup-picker的，给个demo页面或者代码。

**Comment by Baiang** [comment]
iPhone5s ios9.3系统，微信自带浏览器中也会出现这种问题。
点击输入框，键盘激活的情况下，再点击popup-picker组件就会出现这种问题
