### ISSUE TITLE
datetime组件初始化问题

### ISSUE THREAD

**Issue by yiling-e0** [airyland/vux#469]
datetime组件和其他组件不一样，会在JS被载入时初始化。
导致我在head中引入js文件，组件报错“Cannot read property 'appendChild' of null”。

目前我只能通过将datetime单独拿出来打包，然后在body后引入解决。

**Comment by airyland** [comment]
单独拿出来打包？

**Comment by yiling-e0** [comment]
恩 其他组件我是用到的都打包在一个js里

**Comment by airyland** [comment]
给个最简单的重现代码吧

**Comment by yiling-e0** [comment]
<head>
  <script src="app.js"></script>
</head>
<body>
  <group>
    <datetime title="Birthday"></datetime>
  </group>
</body> //这样写点击就会报Cannot read property 'appendChild' of null



<body>
  <group>
    <datetime title="Birthday"></datetime>
  </group>
<script src="app.js"></script>
</body> //这样就可以了

**Comment by yiling-e0** [comment]
```
<head>
  <script src="app.js"></script>
</head>
<body>
  <group>
    <datetime title="Birthday"></datetime>
  </group>
</body>

``` 这样引入组件,点击组件的时候报错“Cannot read property 'appendChild' of null”。

放到body下引入就没问题

**Comment by airyland** [comment]
你这个代码我也运行不了吧。

**Comment by yiling-e0** [comment]
额 因为我自己打包出来的JS 有些组件不好拓展我直接改的源码再打包出来的,
我看了下这个组件,貌似会在被引入时就初始化  但是我在head引入的话dom还没加载完成  所以就报错了

**Comment by airyland** [comment]
如果你说的是引入datetime.js会报错，我试了下，直接复制到console里执行是不会报错的。
https://github.com/airyland/vux/blob/master/dist/components/datetime/index.js

**Comment by yiling-e0** [comment]
因为console里执行dom已经被载入了 所以没问题
可能我表达不到位，我的情况是dom没加载完成前引入造成的

**Comment by yiling-e0** [comment]
报错是  点击组件的时候报的错，不是引入后报的

**Comment by airyland** [comment]
Fixed on v0.1.3-rc7
