### ISSUE TITLE
popup-picker BUG

### ISSUE THREAD

**Issue by outman2008** [airyland/vux#471]
### Version

v0.1.2
mac OS X 10.10.5
Google Chrome 52.0.2743.116 (64-bit)
### Your Codes

``` html
<template>
  <popup-picker title="选择班级" :data="classList" :columns="1" :value.sync="selectClass" show-name></popup-picker>
</template>
<script>
export default {
   data() {
       return {
        classList: [],
        selectClass: [],
      }
    },
   created() {
      this.classList = [{
         name:"2019届5班",
         value:"1"
      },{
         name:"2019届4班",
         value:"2"
      }]
      this.selectClass=['2']
    },
}
</script>
```
### Expected behavior and actual behavior.

初始化时 popup-picker 没有数据,AJAX 请求回数据后绑定到 data 上
界面能够显示,但是控制台报错:
index.vue?9278:65 Uncaught TypeError: Cannot read property 'value' of undefined
跟踪代码发现:
vux-master/src/components/picker/index.vue
65行: _this.value.$set(i, data[i][0].value || data[i][0]) 报错
### Steps to reproduce the problem

picker/index.vue 源代码片段:

``` js
render (data, value) {
      this.count = this.data.length
      const _this = this
      if (!data || !data.length) {
        return
      }
      let count = this.data.length
      // set first item as value
      if (value.length < count) {
        for (let i = 0; i < count; i++) {
          _this.value.$set(i, data[i][0].value || data[i][0])
        }
      }
```
估计是这个组件 render (data, value) 方法里面的变量data引用混乱的问题,
局部变量定义了个 data 这个和全局变量 this.data 造成了混淆

**Comment by airyland** [comment]
整理一下代码吧。

**Comment by outman2008** [comment]
不好意思,好像是另外的原因引起的,
数据项不能为 INT 型 ?
如下:value 项为字符串类型不会出错
[{
          name: '2014年',
          value: '2014'
        }, {
          name: '2015年',
          value: '2015'
}]
改为 
[{
          name: '2014年',
          value: 2014
        }, {
          name: '2015年',
          value: 2015
}]
点击选中的时候, 则会报错:  Uncaught TypeError: Cannot read property 'name' of undefined

**Comment by outman2008** [comment]
之前的问题 index.vue?9278:65 Uncaught TypeError: Cannot read property 'value' of undefined
确定是由于data为空, columns="1" 引起的
最好能在组件内部判断下 data 为空时 强制 columns=0
目前只能在组件绑定时这样写:  :columns="(myList && myList.length>0)?1:0" 临时解决这个问题

**Comment by airyland** [comment]
这部分文档等我去完善，column>0表示联动。如果不是联动没有必要设置column。但是非联动可能不支持{name: NAME, value: VALUE}的data形式

**Comment by outman2008** [comment]
非联动的数据形式是怎么样的??
能统一格式最好,简单的功能花了我很多时间去看文档
需要看很多文档的 API 就不太友好

**Comment by airyland** [comment]
其实现在是没有文档，再稍等几天。。现在就是简单的数组值 [['1', '2']] 这样子的。
会统一起来。

**Comment by outman2008** [comment]
简单数值这种不能满足需求,类似 select 一般都是显示name,取值用id  
联动不联动,我倒是还没用到

**Comment by airyland** [comment]
目前picker不支持的话，自己写个函数转换一下值也不复杂。

**Comment by yhZhouYh** [comment]
@outman2008 最后数据结构是怎么定义的 我这边 可以显示，但是貌似每次点完成后都显示第一个

**Comment by yuanxj1024** [comment]
我也遇到该问题，不过情形略有不同。

给popup-picker 的数据时字符数组，初始化还好。

但是当该笔popup-pikcer的数据时，默认没有选中数据第一个，那我就指定一个值时报错.

**Comment by bluesky4485** [comment]
我也遇到这个问题了，不过更神奇的是一样的代码，我本机是可以正常显示popup-picker的，但是同事机器上就是显示不出来，报跟楼主同样的错误。

**Comment by 736008081** [comment]
在popup-picker或者address的控件中 如果默认的value没有在list表中就会报value没找到错误 可以去修改下自己引入的vux源码加判空操作 满足当前的需求，还是期待作者能修复吧

**Comment by airyland** [comment]
@736008081 为什么会出现value不在list中的这种情况呢？既然是默认当然是要保证在list中吧。

**Comment by 736008081** [comment]
@airyland vux里面的城市dataList列表 跟其他端的城市列表数据库不一样 或者 城市数据库更新 一些旧的城市数据在dataList里面找不到

**Comment by airyland** [comment]
@736008081  数据已经根据最新的统计局数据更新一个版本了。
