### ISSUE TITLE
有计划用rem  替换px 更好的适配移动端么?

### ISSUE THREAD

**Issue by sun314cn** [airyland/vux#474]
@airyland 
如题~ 辛苦了~

**Comment by airyland** [comment]
因为依赖于WeUI， WeUI并没有实施rem，因此暂时并没有这个计划。组件比较多，实施起来也复杂。可以通过webpack插件之类的进行px转换，但是不保证没有问题，因为涉及到组件尺寸什么的计算。

**Comment by sun314cn** [comment]
@airyland thx a lot!
