### ISSUE TITLE
Scroller组件里的reset方法的疑问

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#478]
### Version

0.1.3
### Android or iOS

ALl

> For Android issues, please specify the brand, model and browser

具体问题所在请见：[scroller组件源码：](https://github.com/airyland/vux/blob/master/src/components/scroller/index.vue#L117-L119)
### Expected behavior and actual behavior.

我正在用scroller组件做聊天页面，准备做下拉刷新功能。在将Ajax获得的新的聊天数据压入$vm变量后，肯定是要调用xScroll的resetSize方法来调整新scroller容器的高度。同时还要根据当前页面滑动的不同位置，来判断是否需要滑动至底部或者保留原始位置。

问题在于，Vux.scroller组件内的reset方法中，使用了JS 原生的setTimeout方法来通知XScroll刷新，虽然没有给定时间，但依旧是个异步方法。这导致了，在我调用$vm.$refs.scroller.reset()后的下一行，XScroll对象还没有得到刷新，其的containerHeight仍然是旧的。不是很明白这么设计的原因在哪里。

另，renderTo方法是什么？好像没有在官方文档里看到。推荐的是resetSize()。
### 解决方法

`setTimeout(() => {
        this._xscroll && this._xscroll.renderTo()
      })`
替换成：

`
this._xscroll && this._xscroll.resetSize()
`

**Comment by airyland** [comment]
为什么要调整组件高度？

**Comment by dangyuluo** [comment]
用户体验的一种吧，如果你仔细观察微信在获取更久之前的聊天记录的时候，会发现当现有聊天记录都看完后，再向上拉取，现有消息的位置不会变化，只是在上部新增了更久之前的消息。这种感觉比较流畅。

我觉得这只能通过xscroll.scrollTop()方法实现，记录下拉取新消息之前的消息容器高度和当前xscroll偏移量，在页面刷新后再回到这个位置。这也就是为什么我对刷新前后消息容器的高度有一定要求的原因。

**Comment by airyland** [comment]
不知是不是我们对消息容器的高度理解不一样，即使微信的聊天记录消息容器，高度也是一个固定值。是内部的内容高度随着消息数量有所变化。

**Comment by dangyuluo** [comment]
哦，应该是这么回事。我指的是scroller内部元素的高度，经常可以达到几千像素。

**Comment by airyland** [comment]
我得再看一下，目前scroller问题比较多，而且scroller有点被滥用导致了更多的问题。
你的需求可以先通过取得ref的_scroller对象调用需要的XScroll方法。

**Comment by dangyuluo** [comment]
是的我目前正在这么做，效果还不错。xscroll是个好东西，不逊于iScroller。

**Comment by airyland** [comment]
https://github.com/airyland/vux/issues/221 有遇到性能问题吗？

**Comment by dangyuluo** [comment]
在三星i9300上测试了一下，没有什么卡顿。

**Comment by dingyiming** [comment]
请问，在异步加载数据和图片的过程中，时常会因为图片加载比较滞后，造成scroller的reset在异步加载完数据就reset了，没有考虑到图片的高度，用什么办法能更好地把握住reset的时机?

**Comment by airyland** [comment]
@dingyiming 给图片或者图片容器定高度

**Comment by dingyiming** [comment]
异步加载的图片没法定高度怎么办？

**Comment by airyland** [comment]
@dingyiming 你总得有个固定比例吧，根据宽度算个高度可以吧，scroller原来就是设计用来加载列表数据的。

**Comment by dangyuluo** [comment]
我使用的是监听IMG的load事件，`@load='img_loaded'`, 

`img_loaded: function(){
        v.$refs.scroller._xscroll.resetSize();
},`
