### ISSUE TITLE
router-view设置成keep-alive后，横竖屏切换会导致Scroller滑动失效

### ISSUE THREAD

**Issue by aplusgain** [airyland/vux#482]
1、npm版本为3.9.3，node版本为v6.2.1，vux版本0.1.2

2、iOS9.3.2 微信内置浏览器6.3.22

3、Codes
**官方例子，只是router-view加了keep-alive**

操作步骤如下：
![1](https://cloud.githubusercontent.com/assets/11243019/17613381/1ae94854-608f-11e6-9897-20612ba1df42.gif)

**Comment by airyland** [comment]
在2.0中，只要在页面组件的`activated`hook里执行reset就可以。

``` js
activated () {
    this.$refs.scroller.reset()
  }
```
