### ISSUE TITLE
Search组件这样用是否合适

### ISSUE THREAD

**Issue by JianleiZhang** [airyland/vux#485]
我的Search组件：
```html
<search @on-submit="search(value)" :value.sync="value"></search>
```
准备将result展示在该组件外面。
不过这样需要on-submit设置isFixed=false。
所以我想问一下是否适用这种情况？

**Comment by airyland** [comment]
？展示在组件外面？

**Comment by JianleiZhang** [comment]
恩，如何结果很多的话需要分页。

**Comment by JianleiZhang** [comment]
还有一个考虑是on-submit事件是在已经确定value的情况下发送的。肯定要将value处理后展示出来吧？

**Comment by airyland** [comment]
sorry, 看不懂。value是双向绑定的，你想怎么处理跟组件无关了。

**Comment by JianleiZhang** [comment]
比如，我搜索小明，我在Search组件里输入小明，然后点击搜索按钮，on-submit触发获取结果，然后我想要搜索框收起来以展示小明的详细信息。
