### ISSUE TITLE
radio控件问题

### ISSUE THREAD

**Issue by ericwang1902** [airyland/vux#49]
我用了radio控件，使用的是demo的代码，但显示不了选择项。

**Comment by airyland** [comment]
麻烦上个代码 现在我想象不出是什么问题

**Comment by ericwang1902** [comment]
@airyland 谢谢你回复。
我用的就是这里的代码。
https://github.com/airyland/vux/blob/master/src/demos/Radio.vue

页面显示上，选项显示不出来。

**Comment by airyland** [comment]
因为我自己demo是正常的，出错得看具体情况了。你确认你从npm安装下来，还是直接clone下来用的？ 调试窗口报什么警告或者错误。

**Comment by airyland** [comment]
demo里面的调用方式不适用于从npm下载安装。

**Comment by ericwang1902** [comment]
没有，不是直接运行的demo，我在开发的时候，直接用的那段代码，其他控件都可以的。
没有报错。

**Comment by airyland** [comment]
你打包整个代码给我吧。这个没有具体的代码排查不了。

**Comment by ericwang1902** [comment]
好的，我晚点上传到github。

**Comment by airyland** [comment]
你打包发到我邮箱也可以  i@mao.li

**Comment by ericwang1902** [comment]
@airyland 给您发过去了，谢谢！

**Comment by airyland** [comment]
运行你的代码我这边是正常的：

![image](https://cloud.githubusercontent.com/assets/559179/14007611/534597fc-f1b3-11e5-852c-3fc94ea1451d.png)

**Comment by ericwang1902** [comment]
@airyland 已经邮件发您了，麻烦您看下。

**Comment by airyland** [comment]
@ericwang1902 我这边重现到了，我晚上再debug一下是具体什么问题。

可以加入简聊，更方便讨论

https://jianliao.com/page/invite/f7c555307e

**Comment by ericwang1902** [comment]
@airyland 已经加了，谢谢！

**Comment by airyland** [comment]
升级到 vux@0.0.104 --dev 可以解决

**Comment by airyland** [comment]
问题在于vue-html-loader 依赖的html-minifier 会把 label标签里的内容清空。
