### ISSUE TITLE
在lazy load的时候，引用vux组件最终生成js文件过大

### ISSUE THREAD

**Issue by choufeng** [airyland/vux#490]
1. 基于webpack的vue项目中测试，使用了vue-router的lazy load 
`import { Group, Cell } from 'vux-components'`
引用组件和不引用组件，生成的文件大小多了近900k
是否我使用方法有误？

[图1：lazy load](https://vgy.me/e3D9M4.png)

[图2：import的结果](https://vgy.me/GWxuk9.png)
[图3：没有import的结果](https://vgy.me/SMv2H0.png)

**Comment by airyland** [comment]
请将组件分别从src/components引入。你这是从dist/vux.js整个引入了，很快会有webpack plugin支持将你上面的引用自动转换为单个分别引入。

**Comment by Maopy** [comment]
@airyland 请问 Webpack plugin 出了没？
