### ISSUE TITLE
ios系统下，popup-picker组件在滑动时，背景渐变样式会出现闪烁BUG

### ISSUE THREAD

**Issue by Baiang** [airyland/vux#494]
`.scroller-content {
            z-index: 1
            }`z-index在部分浏览器中会发生重绘，这里应该改成-1就可以

**Comment by Baiang** [comment]
但是在安卓下面就有另外的重绘BUG

**Comment by lichunqiang** [comment]
为什么给关了

**Comment by Baiang** [comment]
习惯性动作，感觉可以关掉-。-！
