### ISSUE TITLE
x-swiper的bug

### ISSUE THREAD

**Issue by luxueyan** [airyland/vux#495]
1.红米手机的上面的微信内置浏览器，貌似不支持string的新方法 startWith 会报错的，建议提示项目需要使用的pollyfill 方法罗列出来
2.如果 x-swiper-item 的数据是ajax异步请求回来的，swiper设置了 loop属性，:slides-per-view="3"，在$nextTick中我手动update , this.$refs.xswiper.swiper.update(true) 可是回导致swiper出问题，无法循环不说，只要滑动就跳到第一个item

**Comment by airyland** [comment]
XSwiper 依赖于 http://www.idangero.us/swiper/ 体积过大，考虑分拆出去。建议自己引入，现在的封装太浅。

**Comment by luxueyan** [comment]
好吧，之后自己折腾折腾
