### ISSUE TITLE
tabbar 组件使用的问题

### ISSUE THREAD

**Issue by 317365887** [airyland/vux#497]
根据中文文档说明使用底部导航的功能，参考https://vuxjs.gitbooks.io/vux/content/layout/tabbar.html地址代码

界面不显示，JS报错为：“Uncaught TypeError: Cannot set property 'selected' of undefined”

**Comment by airyland** [comment]
上代码，谢谢。

**Comment by 317365887** [comment]
<router-view></router-view>
<div>
  <tabbar>
    <tabbar-item>
      <img slot="icon" src="https://o84lhz5xo.qnssl.com/master/src/assets/demo/icon_nav_button.png">
      <span slot="label">Wechat</span>
    </tabbar-item>
    <tabbar-item show-dot>
      <img slot="icon" src="https://o84lhz5xo.qnssl.com/master/src/assets/demo/icon_nav_msg.png">
      <span slot="label">Message</span>
    </tabbar-item>
    <tabbar-item selected>
      <img slot="icon" src="https://o84lhz5xo.qnssl.com/master/src/assets/demo/icon_nav_article.png">
      <span slot="label">Explore</span>
    </tabbar-item>
    <tabbar-item>
      <img slot="icon" src="https://o84lhz5xo.qnssl.com/master/src/assets/demo/icon_nav_cell.png">
      <span slot="label">News</span>
    </tabbar-item>
  </tabbar>
</div>

**Comment by 317365887** [comment]
代码就你是 文档里面那个 我直接复制的 什么都没改

**Comment by 317365887** [comment]
![image](https://cloud.githubusercontent.com/assets/8263888/17729658/d6ca3f36-6497-11e6-99a9-0c8ec667d7b8.png)

**Comment by airyland** [comment]
版本什么的也要说明吧

**Comment by 317365887** [comment]
不好意思，第一次用你的VUX。  版本0.1.3-rc9

**Comment by airyland** [comment]
完整一点的，包括 import 的代码呢

**Comment by 317365887** [comment]
![image](https://cloud.githubusercontent.com/assets/8263888/17729949/219dfc54-6499-11e6-87af-cf0138625165.png)

**Comment by airyland** [comment]
嗯。。。路径似乎都是错的吧。

**Comment by airyland** [comment]
``` js
// import from dist
import Tabbar from 'vux/dist/components/tabbar'
import Tabbar from 'vux/dist/components/tabbar-item'

// or import from src
import { Tabbar, TabbarItem } from 'vux/src/components/tabbar'
```

**Comment by 317365887** [comment]
恩 我懂了， 谢谢了 ， 真是打扰你了 。原来是dist 和src 引用的问题， 我一直在看src里面的东西

**Comment by airyland** [comment]
也是文档没有及时更新导致的。过些天会全部更新一遍。
