### ISSUE TITLE
Toast以插件方式如何调用？

### ISSUE THREAD

**Issue by LS1231** [airyland/vux#498]
### Version
"vux": "^0.1.3-rc9"
### Android or iOS
iOS
> For Android issues, please specify the brand, model and browser

**Comment by airyland** [comment]
相关的代码还未发布。这周内发布。
https://github.com/airyland/vux/blob/master/src/main.js#L93
https://github.com/airyland/vux/blob/master/src/demos/Toast.vue#L43-L56
