### ISSUE TITLE
range控件快速左右滑动有残留的bug

### ISSUE THREAD

**Issue by 91yuan** [airyland/vux#503]
手机：Nubia z5smini 
浏览器：微信内嵌浏览器
操作步骤：
 1.通过微信扫一扫，进入示例网页
 2.进入range页
 3.选择任一控件，快速左右滑动，当从右向左滑动时，会有拖动残影。从左向右滑不会有。
请了解

**Comment by graysheeep** [comment]
系统浏览器有这个问题么

**Comment by 91yuan** [comment]
系统浏览器没有这个问题
