### ISSUE TITLE
默认配置下引入Popup等带有js文件的组件有错误。

### ISSUE THREAD

**Issue by oraluben** [airyland/vux#505]
### Version
vux@0.1.3-rc10

### Your Codes 

``` html
import Popup from 'vux/src/components/Popup'
```

### Expected behavior and actual behavior.
期望行为：页面正常显示
实际行为：编译不报错，但在浏览器中打开提示`Uncaught SyntaxError: Unexpected token export`。

经过检查，发现js文件中的`export default popupDialog`被原样复制到了编译后的代码中，并没有被babel处理。而在`import Popup from 'vux/src/components/Popup'`所在的vue文件中的`export default`被良好地翻译为了`module.exports`，可以被浏览器解析。

目前在本地通过将`export default`替换为`module.exports`绕过了问题，想问一下是不是在配置上对这部分代码有额外的要求。

### Steps to reproduce the problem
vue-cli默认配置下的webpack模板，使用npm安装默认版本vux

**Comment by airyland** [comment]
加个webpack loader配置吧。https://vuxjs.gitbooks.io/vux/content/install/vue.html
或者使用 `vuxjs/webpack`模板。

**Comment by oraluben** [comment]
对照了`vuxjs/webpack`，增加了`vux-loader`之后就可以正常使用了，可否在文档里写一下？

**Comment by airyland** [comment]
上面就是文档链接。vux-loader只是上面文档配置的快捷方式。

**Comment by oraluben** [comment]
检查了一下，是我疏忽了，`loader`里的js的配置项排除了`/node_modules/`的文件，改为
``` javascript
loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/
      },
      {
        test: /vux.src.*?js$/,
        loader: 'babel'
      },
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.css/,
        loader: 'style!css'
      }
    ]
```
之后正常了。

感谢回复。
