### ISSUE TITLE
swiper组件在添加了loop 属性后，轮播一遍之后，图片的点击事件就失效了

### ISSUE THREAD

**Issue by ya00la** [airyland/vux#507]
### Version
 "vux": "^0.1.3-rc9",   
### iOS

> 手机上只用ios测试过，在电脑chrom浏览器手机模式下测试也一样失效，浏览器版本（ 52.0.2743.116 (64-bit)）

### Your Codes 

``` html
<swiper :list="list" auto loop dots-position="center"></swiper>
```

### Expected behavior and actual behavior.
正常情况下图片在轮播时，只要点击图片都 会跳转到图片指定的url地址,
但现在添加loop循环播放后，图片在轮播了一遍后，再点击图片，没有任何反应，点击事件失效了

**Comment by airyland** [comment]
@unclay 目前的实现是把item remove再移动位置，导致事件失效，我试了下不remove而是直接操作item似乎没有问题，你看看有没有什么隐患。

**Comment by litoxy** [comment]
`    <swiper :list="home_recommend_list" auto loop ></swiper>
`
home_recommend_list ajax 动态获取后遍历 生成 url 
如果加上Loop  再次点击无效 

  "version": "2.2.1"

**Comment by airyland** [comment]
@lllito 重开 issue 吧。帖完整可测试代码。
