### ISSUE TITLE
按照readme安装，到npm run dev 出错

### ISSUE THREAD

**Issue by vance-liu** [airyland/vux#513]
node v4.5.0+
首先是这样的 npn run dev，占8080端口后报错，同npm run dev -- --host 127.0.0.1 --port 8085

![image](https://cloud.githubusercontent.com/assets/9456694/17850468/ee4d4152-688f-11e6-83e6-5c28627408ff.png)
看图片可以发现，两条命令都是占8080端口，可以看到错误应该是来自eslint检测
其次，修改代码后，webpack building......卡住了，ctrl+c，再npm run dev，不要意思端口占用报错，还kill不死了。。。
最后，希望大大更新下关于vue-cli init这边的东西吧

**Comment by airyland** [comment]
你选了哪个风格的eslint？

**Comment by airyland** [comment]
vue-cli 并不支持这样改变端口，README中的 -- --port 是vux本身的命令。你直接在项目的config/index.js里改。

**Comment by vance-liu** [comment]
恩，今天搞了下，使用airbnb eslint是没有问题的，上面的问题是使用f eslint出现的，修改代码后webpack building...... 卡住了
