### ISSUE TITLE
x-textarea autosize

### ISSUE THREAD

**Issue by transtone** [airyland/vux#517]
可否给 x-textarea 加上随内容自动增加行高的 autosize 功能？
已有的 vue autosize 方案：
* https://github.com/mage3k/vue-autosize
* https://github.com/vue-comps/vue-textarea
* https://github.com/egoist/vue-autosize-textarea
* https://github.com/syropian/vue-input-autosize

**Comment by airyland** [comment]
移动端有大量文本输入的需求？

**Comment by transtone** [comment]
没有大量文本，只是想像微博回复一样，刚开始只有一行，当文字多的时候在自动增高。

**Comment by airyland** [comment]
非十分常用的需求，因此建议自行引入`autosize`实现，Demo参考： https://github.com/airyland/vux/commit/4b3a323a63131c2861343793e87b654fa8a4d605#diff-68f302e30383bbe8621021bf07df3a7bR33

**Comment by transtone** [comment]
非常感谢，此demo已完全满足需求了。
