### ISSUE TITLE
使用cnpm更新vux时，vux的loader无效

### ISSUE THREAD

**Issue by yeahTibbers** [airyland/vux#521]
也不能说是bug
如图，cnpm更新的vux组件的package.json会增加一个"_from": "vux@0.1.3",

![qq 20160824114519](https://cloud.githubusercontent.com/assets/10751521/17917578/464e48fe-69f0-11e6-9aa0-c043ff2ec8c1.png)

这会导致vux官方提供的
{
  test: /vux.src.*?js$/,
  loader: 'babel'
}
代码无效，无法babel
![qq 20160824113638](https://cloud.githubusercontent.com/assets/10751521/17917618/a88b3482-69f0-11e6-8b57-c993cdda1587.png)

解决方法是使用npm官方源重新更新vux，或者改loader的正则

**Comment by airyland** [comment]
试试我拆到模块里的loader呢

https://github.com/vuxjs/webpack/blob/master/template/build/webpack.base.conf.js#L50
