### ISSUE TITLE
pullup组件，pullup:done后，如何pullup:reset

### ISSUE THREAD

**Issue by purewater2011** [airyland/vux#524]
有个场景应用：
1.初始化页面加载，拉到底，都刷新完成，pullup:done.
2.通过筛选条件，得到的结果，页面就无法上拉刷新了。pullup:reset是没有效果的。
可否有其它办法？

**Comment by lichunqiang** [comment]
可以使用 `pullup:disable` 和 `pullup:enable` 来控制
