### ISSUE TITLE
xHeader组件leftOptions没有preventGoBack属性

### ISSUE THREAD

**Issue by wurenjie1125** [airyland/vux#525]
### Version
0.1.3

### Android or iOS
iOS
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
      <x-header style="background-color:#f9f9f9" :left-options="{showBack: true,backText:'返回'}" leftOptions.preventGoBack = "true"   @on-click-back="hidepop" :right-options="{showMore: true}"  @on-click-more="showMenus = true">新求助</x-header>
 hidepop(){
        console.log(this.popshow);
        this.popshow = false;
      }

```

### Expected behavior and actual behavior.
预期：阻止返回上一页，执行hidepop方法
实际：浏览器跳转，点击返回没有执行on-click-back

此外，我在组件源码中，console leftOptions，发现并没有preventGoBack属性。

Object {__ob__: Observer}
__ob__
:
Observer
backText
:
(...)
get backText
:
reactiveGetter()
set backText
:
reactiveSetter(newVal)
showBack
:
(...)
get showBack
:
reactiveGetter()
set showBack
:
reactiveSetter(newVal)
__proto__
:
Object

**Comment by airyland** [comment]
leftOptions 是一个object，不能单独拿出来。。
