### ISSUE TITLE
Datetime组件，动态改变maxYear或者minYear不起作用

### ISSUE THREAD

**Issue by lihaoqi1991** [airyland/vux#527]
### Version
"version": "0.1.3"
### Android or iOS
IOS
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
<group title="specified min-year and max-year">
            <datetime :value.sync="value4" placeholder="Please select" :min-year=minYear :max-year=maxYear
                      format="YYYY-MM-DD HH:mm" @on-change="change" title="years after 2000"></datetime>
</group>
<group title="button">
            <x-button @click="reset" type="primary">Reset Max Year</x-button>
</group>

data () {
            return {
                minYear: 2000,
                maxYear: 2010
            }
},
methods: {
            reset () {
                this.maxYear = 2040
            }
}
```

### Expected behavior and actual behavior.
根据某些条件需要重新设置Datetime组件的maxYear或者minYear，我直接在你的Demo上做了个简单的修改试了下，发现不起作用，看了源代码，组件datetime在ready()做了初始化，所以导致的问题，想问一下，将来是否会添加动态改变maxYear或者minYear的代码

**Comment by airyland** [comment]
暂时不支持。你可以为datetime设置一个状态值ifShow， v-if="ifShow", 在maxYear minYear设置后再把ifShow设为true，这样重新渲染应该会正确。

**Comment by lihaoqi1991** [comment]
`
data () {
            return {
                minYear: 2000,
                maxYear: 2010,
                ifShow: true
            }
},
methods: {
            reset () {
                this. ifShow = false
                this.maxYear = 2040
                this. ifShow = true
            }
}
`
上述代码不能成功，但是我设成2个方法，点击第一个方法执行ifShow=false，第二个方法执行this.maxYear = 2040;this.ifShow = true, 可以成功，有没有在一个方法中可以实现这个效果的？
