### ISSUE TITLE
vux中的地区选择component，在安卓系统下的微信浏览器出现加载延迟严重

### ISSUE THREAD

**Issue by 85636682** [airyland/vux#53]
我开发的spa，在安卓微信浏览器下，加载很慢，然后通过浏览器的timeline，发现加载延迟严重的文件里面，有地区选择的数据，在我的项目里，就只有vux里面有这种component。我觉得把地区选择这么庞大的数据放在文件里，会很影响加载速度的。

**Comment by airyland** [comment]
可以独立加载需要的组件的哦。

**Comment by 85636682** [comment]
@airyland 我没加载过这个组件，他是把所有都编译到js文件里了，当我系统加载这个JS文件时，非常耗时

**Comment by airyland** [comment]
在components/下每个组件都有单独的js文件的，不要直接使用vux.js这个文件。

**Comment by 85636682** [comment]
谢谢，按照局部加载。但是如果这样，地区选择的控件在移动端就用处不大了！

**Comment by airyland** [comment]
@85636682 表示完全看不明白为什么只调用这个组件就用处不大了 :dog:
