### ISSUE TITLE
使用vue-router跳转，popup-picker组件出现Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by purewater2011** [airyland/vux#530]
页面首页，包含popup-picker组件。
页面详情，头部设置v-link跳转到首页。
从页面详情进入页面首页，提示Cannot read property 'value' of undefined。
已经绑定了popup-picker的vaule，打印绑定的值也是正常的。

**Comment by lichunqiang** [comment]
给的信息太少，况且还得搭建你所说的环境。

1. 希望可以自己定位问题在哪儿，这也是对自己技术的一个很好提升
2. 实在找不到，可以搭建一个简易能浮现的的工程，方便大家找问题
