### ISSUE TITLE
点击返回时，saveScrollPosition不起作用

### ISSUE THREAD

**Issue by jinmarcus** [airyland/vux#531]
当进入一张页面后，如果页面比较长，从该页面进入另一张页面，再点返回后，
应该是回到上页的当前位置，但是却回到了上一个页面的顶部。
不能记录滚动条ScrollPosition的位置。
window.scrollY和window.scrollTo也都失效了。

临时解决办法是：
html,
body{ width: 100%; height: 100%; overflow-x: hidden;}
把以上代码删掉，再把顶部和底部导航都改为fixed就能解决了
但是点击返回，就会出现闪屏的状况，效果也不是很好。

**Comment by airyland** [comment]
看你描述，你并没有用到vux任何组件，跟vux没关系，请到vue相关社区提问。

**Comment by jinmarcus** [comment]
// save position for demo page
let demoScrollTop = 0
function saveDemoScrollTop () {
  demoScrollTop = window.scrollY
  console.log(demoScrollTop)
}

router.beforeEach(function (transition) {
  if (transition.to.fullPath !== '/demo') {
    window.removeEventListener('scroll', saveDemoScrollTop, false)
  }
  if (/\/http/.test(transition.to.path)) {
    let url = transition.to.path.split('http')[1]
    window.location.href = `http${url}`
  } else {
    if (/\/demo\/component\/\w+/.test(transition.to.path)) {
      router.go({
        replace: true,
        path: transition.to.path.replace('/demo', ''),
        append: false
      })
    } else {
      transition.next()
    }
  }
})

router.afterEach(function (transition) {
  if (transition.to.path !== '/demo') {
    window.scrollTo(0, 0)
  } else {
    window.removeEventListener('scroll', saveDemoScrollTop, false)
    // if from component page
    if (demoScrollTop && /component/.test(transition.from.path)) {
      setTimeout(function () {
        window.scrollTo(0, demoScrollTop)
      }, 100)
    }
    setTimeout(function () {
      window.addEventListener('scroll', saveDemoScrollTop, false)
    }, 1000)
  }
})

官方源码里，这段代码，作用应该是保存滚动条位置的，但是我运行时，并未能起到作用，window.scrollY的值永远都是0。

**Comment by jinmarcus** [comment]
按照源码的表达的意思
if (demoScrollTop && /component/.test(transition.from.path)) {
setTimeout(function () {
window.scrollTo(0, demoScrollTop)
}, 100)
}
这段的意思应该是，如果demoScrollTop有值，或者component调用组件页面时，则讲滚动条滚动到当前的位置，但是在vux.li的demo页面里，无论哪个组件的演示页面，点击返回后，始终都是回到顶部的，按道理应该回到上一页的最后的滚动条的位置才合理，这是否是一个bug呢？我现在想解决的就是这个问题。

**Comment by airyland** [comment]
不是bug。布局改成100%宽高，这段代码无效了。

**Comment by jinmarcus** [comment]
对，所以我将100%去掉后，就可以使用了，但是效果就没有100%的好。是否就没有解决的办法了呢。

**Comment by jinmarcus** [comment]
如果用户在一张页面里，点击一个连接，然后想返回接着看，此时就跳到顶部了，然后又要往下拉，这样感觉体验不是很好。

**Comment by airyland** [comment]
改变容器的scrollTop就可以，你可以试下在demo列表页面下拉一段距离，然后点击顶部中间title
https://github.com/airyland/vux/blob/master/src/App.vue#L62

**Comment by jinmarcus** [comment]
这个我也试过了，这个可以改变当前容器的scrollTop，不过点击返回这东西是跟history走的，应该不是一个东西。如果实在不行，我看还是只能去掉高的100%，采用上下fixed来做了。

**Comment by airyland** [comment]
fixed在移动端坑比较多啊

**Comment by jinmarcus** [comment]
如果没办法解决返回这个问题，我觉得用户体验也不好，一张非常长的页面，不能点其中一个连接，返回就到顶部了，这样，如果以内容展示为目的的单页，会崩溃的。
