### ISSUE TITLE
使用Address组件问题

### ISSUE THREAD

**Issue by 317365887** [airyland/vux#536]
在demo中的Address.vue 中 加载组件是
import { Group, Address, AddressChinaData, XButton, Cell } from '../components'
import value2name from '../filters/value2name'

我想加载dist里面的Address组件，那AddressChinaData这个数据在哪加载，在dist/components/address 没见文件。

还有value2name 这个加载 
我是import value2name from 'vux/src/filters/value2name' 这样子写的
但是报错
Uncaught SyntaxError: Unexpected token import

value2name这个文件能在dist里面加载不？

**Comment by airyland** [comment]
已经用webpack就全部从src加载吧，那个报错请配置babel loader
https://vuxjs.gitbooks.io/vux/content/install/vue.html

**Comment by 317365887** [comment]
恩，问题解决了！谢谢

**Comment by 317365887** [comment]
恩，问题解决了！谢谢

**Comment by sclchic** [comment]
AddressChinaData这个数据在哪里还是没找到
