### ISSUE TITLE
picker数据源的关联问题

### ISSUE THREAD

**Issue by yeahTibbers** [airyland/vux#539]
版本0.13rc9

使用picker组件时，如果第一列数据的value为纯数据的话，后面滑动将报错

js数组如下

`
[{
          name: 'test1',
          parent: 0,
          value: 1
        }, {
          name: 'test2',
          parent: 0,
          value: 2
        }, {
          name: 'test3',
          parent: 0,
          value: 3
        }, {
          name: 'test4',
          parent: 1,
          value: 4
        }, {
          name: 'test5',
          parent: 1,
          value: 5
        }, {
          name: 'test6',
          parent: 3,
          value: 6
        }]
`
![qq 20160829191234](https://cloud.githubusercontent.com/assets/10751521/18049791/008515ec-6e1d-11e6-936c-1396e5f7c7bc.png)
![qq 20160829191251](https://cloud.githubusercontent.com/assets/10751521/18049793/0086368e-6e1d-11e6-82ad-8aa86f2e62d3.png)
![qq 20160829191309](https://cloud.githubusercontent.com/assets/10751521/18049792/0085db62-6e1d-11e6-82c9-20df417a03fc.png)

**Comment by airyland** [comment]
底层实现无法保存类型，value强制需要字符串。

**Comment by yeahTibbers** [comment]
如果是强制使用字符串的情况下，是否这行代码中的one.parent === 0不需要用全等号，因为既然该组件已规定parent为字符型，若从后台拿数据，也会将数据集中的parent做字符处理，这时候用全等号就无法识别第一列，是否可以考虑改为“==”？
https://github.com/airyland/vux/blob/master/src/components/picker/chain.js#L20

**Comment by airyland** [comment]
这里用数字主要是防止用户确实用数字了，我更倾向于再加一句， `==='0' `
