### ISSUE TITLE
微信webview路由有点问题

### ISSUE THREAD

**Issue by Jevirs** [airyland/vux#54]
进入demo，点击返回无法返回父菜单，直接退出浏览器

**Comment by airyland** [comment]
微信？Android?

**Comment by progrape** [comment]
https://github.com/weui/weui/issues/26 是不是这个问题？

**Comment by airyland** [comment]
@progrape 目测是的，微信的iOS客户端同学有没有处理进度呀？

**Comment by progrape** [comment]
请用 hash 的方式来代替，初步判断是 UIWebView 的缺陷

**Comment by airyland** [comment]
@progrape :sweat_smile:  ok.

**Comment by airyland** [comment]
@progrape 无法完全解决。在只有两级的页面返回是正常的，如果存在三级，比如weui的tabbar那么返回，那么同样会出现 weui/weui#26 所提到的问题：

> 在third界面时，用幕边缘左滑返回会短暂闪过first的画面，然后才显示second，
> 但此时，再次幕边缘左滑返回，直接退出了webview（本应显示first）。

**Comment by airyland** [comment]
Closed. Will be updated when the issue is solved.
