### ISSUE TITLE
picker组件是否有必要设定默认选项

### ISSUE THREAD

**Issue by yeahTibbers** [airyland/vux#540]
是否有必要为picker设定默认选项，比如当选择地区时三级联动，选到广东省时后面两列自动定位到广州市荔湾区，如果能为picker设定默认选项，用户就能在省市区三级自由选择所需要的层级，不需要的层级为默认选项“未选择”
![111](https://cloud.githubusercontent.com/assets/10751521/18054753/a73b6c8c-6e37-11e6-9261-45d0b59d0855.png)

**Comment by airyland** [comment]
sorry, 看不懂你表达的是什么意思。

**Comment by yeahTibbers** [comment]
不好意思，表达能力可能不过关
![111](https://cloud.githubusercontent.com/assets/10751521/18072364/33d10d98-6e90-11e6-8d28-111d05fb2769.png)

 如上图，在市这一列和区这一列中，每列都增加一个未选择
以实际使用场景，搜索各地区内容为例子，现在的popup-picker组件，如果是省市区，用户永远都会能选到区这一级，因为用户再省一级中选择广东后，市就自动定位到广州，区就定位到荔湾区，当用户想单独搜索整个广州市或者广东省的话，就挺麻烦的了，如果增加一个“未选择”就能很好地解决这个问题

**Comment by airyland** [comment]
你这是想设置默认值，但是又不想设置全部？不知道这用于什么场景。
如果你是想让用户自己选择省，那就不要设置就好了啊，用户自己选 。
如果想让用户选择选择市，即使当前在深圳市，用户选择广州市和用户从未选择到选择广州市有什么不同。

**Comment by yeahTibbers** [comment]
因为现在的组件是精确到最后一列，即区这一列的，如果用户只是想搜索广东省，那么市和区这两列用户就不用选，默认为“未选择“就行了，但是现在的组件无法做到这点，因为一旦选择省，就直接选定第一行的市和第一行的区了。
当然，这种场景下，不修改picker组件的解决方案是有的，即做三个选择器，想搜索省就点省级选择器，以此类推，但是失去了picker的联级效果，用户需要点击选择与确定，这样的操作会操作三遍。
或者换一个应用场景
用户在商城使用picker组件选择需要搜索的分类

**Comment by airyland** [comment]
复杂化了。现在的交互跟你所说的交互成本没多大差别。另外两列不设，用户更容易犯错，意味着用户此时点击确定按钮必须提示他必须正确选择才能确定。暂时没有这样设置的计划。但是你完全可以在popup-picker基础上实现你要的需求，address也是基于popup-picker来做的。
