### ISSUE TITLE
vux例子代码address中，在Android 的uc浏览器中使用fixed的z-index会失效

### ISSUE THREAD

**Issue by lee134134134** [airyland/vux#543]
出现这种问题的手机有红米1s   红米note   小米3    小米4     三星note2     三星note3   三星s4  华为p8   华为荣耀   魅族m2 note  oppo R7+   vivo  Y23L。

但是其他同样使用popup组件的例子  比如日期等都能正常使用。

**Comment by airyland** [comment]
如果你是说address的demo的话，拿了两台小米的机子测试并没有问题。
