### ISSUE TITLE
scroller组件中使用css的fixed属性没效

### ISSUE THREAD

**Issue by ya00la** [airyland/vux#544]
### Version

"vux": "^0.1.3-rc9",
### Android or iOS

手机上只用ios测试过，在电脑chrom浏览器手机模式下测试也一样失效，浏览器版本（ 52.0.2743.116 (64-bit)）
### Your Codes

``` html
  <scroller v-ref:projectScroller lock-x>
    <div class="index-wrap">
      <div style="height:2000px;background:#888383;">
        <div style="position:fixed;top:0;width:100%;background:#000;height:100px"></div> 
      </div>
    </div>
  </scroller>
```
### Expected behavior and actual behavior.

当没有滚动时，当前的定位是正确的，当滚动后，css的fixed就失效了，也会随滚动条滚动，
正常情况下，fixed的定位是相对于浏览器窗口的定位，所以它的定位不应该随滚动条滚动，应该一直保持相对浏览器的定位

**Comment by airyland** [comment]
复杂交互不要用scroller。scroller只是为了展示内容用。
