### ISSUE TITLE
tab 组件 报错  Unknown custom element: <tab> - did you mean <tab>? HTML is case-insensitive, remember to use kebab-case in templates.

### ISSUE THREAD

**Issue by gggso** [airyland/vux#545]
使用 import { Tab, TabItem } from 'vux/dist/components/tab' 引入 tab的时候会报如下错误 
[Vue warn]: Unknown custom element: <tab> - did you mean <tab>? HTML is case-insensitive, remember to use kebab-case in templates.
[Vue warn]: Unknown custom element: <tab-item> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
但是使用 import { Tab, TabItem } from 'vux' 就没问题  不回报错 好奇怪啊。。

**Comment by gggso** [comment]
@airyland 帮看下

**Comment by airyland** [comment]
没有这个用法。dist下都是平行组件，请直接从src引入。
``` js
import Tab from 'vux/dist/components/tab'
import TabItem from 'vux/dist/components/tab-item'
```

``` js
import { Tab, TabItem } from 'vux/src/components/tab'
```

从`vux`引入，是引入vux.js当然没问题。你看看dist的文件结构就知道了。
