### ISSUE TITLE
考虑废弃被错误使用以及滥用的scroller

### ISSUE THREAD

**Issue by airyland** [airyland/vux#546]
scroller只是为了实现一个可滚动容器，场景更适合展现列表数据，而不是把所有内容都塞进去。但是大部分用户就是这样直接使用了，导致了scroller有一堆issue。因为scroller的实现，定位样式在里面有各种问题，实在不想为了组件在scroller里能使用而各种hack。在Android低端机上还有性能问题。

累感不爱，不想维护这个组件了。

考虑功能收缩成listview，部分同学只是为了loadmore使用了scroller，这个完全可以用另外的组件来解决。

**Comment by unclay** [comment]
主要滥用太频繁了，什么场景都用。。

**Comment by ya00la** [comment]
个人觉得如果在api上写明白适用性和乱使用会出现的问题，估计太家使用的时侯也就会谨慎点

**Comment by nicefan** [comment]
的确，主要是xscroll，手快速一滑滚动到底部竟然也会触发加载更多，说好的上拉然后松开才加载呢~~
其实我只想要下拉加载更多的功能，才用了scroller ，能有个简单些的就好了

**Comment by airyland** [comment]
@nicefan 是有考虑独立提供pullup pulldown的，不依赖scroller.

**Comment by P0RUNGA** [comment]
我不如自己写,用了还浪费我时间.

**Comment by airyland** [comment]
@P0RUNGA 哦，你厉害那你写去啊，我维护不还浪费我时间。
