### ISSUE TITLE
在传统架构下Web应用中，如何解决页面未加载完之前的内容混乱？

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#547]
这个问题不是Vux的，所以就不加相关描述了。总之对于非单页应用的每一个页面，在首屏完全加载之前，浏览器的工作有：
1)获取页面HTML文档内容
2)使用AMD加载器，加载所需要的JS资源。或许还有CSS资源。
3)加载完成后初始化Vue+vux，达到所要效果。

但是目前的网络状况下，第二步往往会消耗过多时间，导致页面内容暂时错位或显示不全，如文末图所示。可能浏览器缓存能起到一定作用，但是并不能有很大起色。

不知道如果对于传统架构下的Web应用，有没有相关问题的推荐解决方法？

![qq20160830-0 2x](https://cloud.githubusercontent.com/assets/4816327/18111375/3a0f29c6-6eed-11e6-9633-824b3918f3bd.png)

**Comment by lichunqiang** [comment]
个人观点：

1. css首先得在head中或者body最前加载吧
2. 在配合上 http://vuejs.org/api/#v-cloak  应该差不多了

**Comment by airyland** [comment]
为什么不合并压缩js？

**Comment by dangyuluo** [comment]
@airyland 我真希望这个项目能从头接手，那样我就能采用现代前端工程的开发模式了。可是现在项目情况比较复杂，只能用老旧的引入方式。不过好在客户也比较保守。

**Comment by airyland** [comment]
加个加载loading状态吧。

**Comment by dangyuluo** [comment]
@airyland 嗯，下一步想这么做。

**Comment by airyland** [comment]
合并压缩在任何架构下都能做，用v-cloak隐藏未编译模板，加上loading状态应该就差不多了。
