### ISSUE TITLE
Build version dd772ed，在浏览器里报 DEV is not defined（附问题定位）

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#548]
### Version
dd772ed  
### Android or iOS
All
> For Android issues, please specify the brand, model and browser

一直用的0.1.2，最近想使用以下最新版的popover功能，因此clone了最新版并进行编译。但是正常引入吼，在浏览器里问题如下：
![qq20160830-1 2x](https://cloud.githubusercontent.com/assets/4816327/18112600/d43154f8-6ef6-11e6-8064-157dbe9327e7.png)

经查找，问题出现在`src/components/index.js`第150行：
```javascript
if (DEV) { // eslint-disable-line
  const { getMetas } = require('../../build/build-metas')
  const metas = getMetas(vux)
  if (window.fetch) {
    window.fetch('http://localhost:8899/api/doc', {
      method: 'POST',
      body: JSON.stringify(metas),
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      }
    })
  }
}
```
不太清楚这个DEV变量是做什么用的，在浏览器里可能会引起报错。

**Comment by lichunqiang** [comment]
https://github.com/airyland/vux/blob/master/build/webpack.dev.conf.js#L22

**Comment by dangyuluo** [comment]
@lichunqiang Yep, find it. 但是如何解决呢？老旧项目实际上没有用到Webpack。
另，自行编译到dist目录的命令是 `npm run xbuild`么？
谢谢。

**Comment by lichunqiang** [comment]
都在README里面的吧...
https://github.com/airyland/vux/blob/master/README.md#development-setup

**Comment by dangyuluo** [comment]
@lichunqiang 不好意思，但是实际上浏览器中DEV is not defined问题并没有得到解决。不知道可否赐教？

**Comment by lichunqiang** [comment]
... 直接用build下的组件

**Comment by airyland** [comment]
不知道你是什么情况下出现的报错，npm run dev是不会报错的，使用dist下的模块也不可能报错。

**Comment by dangyuluo** [comment]
其实我一直在用的是 npm run xbuild 来从最新一次提交构建，是我方法不对么？
------------------ Original ------------------
