### ISSUE TITLE
如何用v-for循环为x-number的参数value赋值？

### ISSUE THREAD

**Issue by Van-jue** [airyland/vux#549]
### 具体描述
本人用vux做电商页面，在购物车列表中用到了x-number表单组件，循环购物车商品数量列表给x-number参数value赋值失败（首先排除{{item.num}}不存在的可能）
### 页面代码
```html
<div  v-for="(index,item) in checkList" > 
    <group>
        <x-number :value={{item.num}} title="数量" :fillable=false  :min=1  :step=1  @on-change="changeNum" ></x-number> 
    </group>
</div>
```
双花括号{{}} 并没有突出加黑显示 ，赋值失败

**Comment by airyland** [comment]
`:value="item.num"`

**Comment by Van-jue** [comment]
@airyland  这样写也不对，已经有试过 
页面加载完后值为空，点击 ‘+‘ 号出现NAN类型

页面加载完成：

![image](https://cloud.githubusercontent.com/assets/10445436/18122088/4c71948e-6f9a-11e6-8cbb-5c0b6477f32c.png)
点击后：

![image](https://cloud.githubusercontent.com/assets/10445436/18122020/05d5e214-6f9a-11e6-83c7-4fe99868f3ad.png)

**Comment by airyland** [comment]
你确定你的item.num是数字？

**Comment by Van-jue** [comment]
表字段是int类型的，抱歉之前回答的有点晚了

**Comment by airyland** [comment]
给个checkList的数据

**Comment by Van-jue** [comment]
checkList
![image](https://cloud.githubusercontent.com/assets/10445436/18122384/c0ade784-6f9b-11e6-8c45-354d7490d8d9.png)

**Comment by airyland** [comment]
你的num是字符串吧。

**Comment by Van-jue** [comment]
我知道了，虽然存的是int类型查出来的是string类型，需要把num先转为int类型在传参过去，谢谢你
