### ISSUE TITLE
支持ios safari 么？

### ISSUE THREAD

**Issue by fangsj** [airyland/vux#553]
我在ios safari打开demo，只显示空白页，我之前一个版本是可以打开的
谢谢！

**Comment by airyland** [comment]
并不会。请确认网络正常。

**Comment by zeroskeay** [comment]
ios10  iphone6 plus  网络状况良好  微信扫描demo二维码，正常，使用safari 打开 显示空白页

**Comment by fangsj** [comment]
你用隐私模式了么？隐私模式好像打不开的


原始邮件
发件人:skeaynotifications@github.com
收件人:airyland/vuxvux@noreply.github.com
抄送:fangsj1033595695@qq.com; Authorauthor@noreply.github.com
发送时间:2016年10月20日(周四) 11:01
主题:Re: [airyland/vux] 支持ios safari 么？ (#553)


ios10 iphone6 plus 网络状况良好 微信扫描demo二维码，正常，使用safari 打开 显示空白页

**Comment by zeroskeay** [comment]
确实开启了隐私模式 谢谢答复

**Comment by airyland** [comment]
我这边正常测试是没问题的，隐私模式下似乎localStorage有问题，我demo里没有做相关处理。

**Comment by zeroskeay** [comment]
关闭了 无痕访问  然后 正常显示出来了
