### ISSUE TITLE
Address 组件可能造成内存溢出

### ISSUE THREAD

**Issue by sun314cn** [airyland/vux#555]
<address title="二级省市" :value.sync="value3" raw-value :list="addressData"></address>
这段代码昨天还是正常可以使用的,今天过来浏览器直接报内存溢出 崩溃,路由无法跳转.
一下是浏览器报错代码:
vue-router.js?2e68:1553 Uncaught RangeError: Maximum call stack size exceeded
使用版本0.1.3,麻烦大神确认.
去掉<address> 代码,路由正常跳转

**Comment by airyland** [comment]
先检查你改了什么吧，听你描述更像你更改了什么导致的。如果你不能确认出错是哪个文件哪一行你的出错信息没有任何用处。

**Comment by sun314cn** [comment]
`<address :title="address_title" :value.sync="data.address_item" placeholder="省、市、区"></address>`
这段代码  我再检查一下

**Comment by sun314cn** [comment]
问题找到了,跟您反应一下:
原因是我在目标页面中 给当前vue命名为
`export default {
  name: 'Address'
}`
此name的名称跟组件的命名相同,所以造成了内存溢出的 bug
具体为什么会这样,暂时还不清楚

**Comment by airyland** [comment]
感觉是组件循环引用了。
