### ISSUE TITLE
datetime的bug

### ISSUE THREAD

**Issue by ivan403704409** [airyland/vux#559]
datetime 的value在初始时写死 '2016-09-06 10:00:00'时，点击显示datetime是没问题，
但是在初始化后再次更改 value（不是点击datime组件修改时间）时， 点击显示datetime，还是显示之前的值，而没有监听value的变化更新视图

**Comment by airyland** [comment]
暂不支持。

**Comment by ivan403704409** [comment]
@airyland 
临时更改 vux/src/components/datetime/datetimepicker.js  line:118，在显示时处理了一下，
` // self.show(self.value);`
`self.show( output.innerHTML.replace(/^(\s+)?/, '').replace(/(\s+)$/, '') || self.value);`
