### ISSUE TITLE
swiper

### ISSUE THREAD

**Issue by bulolo** [airyland/vux#56]
```
<template>
  <div>
    <swiper :list="list" :auto=true></swiper>
  <div>
</template>

<script>
import {Swiper} from 'vux'
export default {
  components: {
    Swiper
  },
  data: function () {
    return {
      list: [{
        url: 'http://mp.weixin.qq.com/s?__biz=MzAxNjU0MDYxMg==&ampmid=400385458&ampidx=1&ampsn=78f6b8d99715384bdcc7746596d88359&ampscene=19#wechat_redirect',
        img: 'http://7xqzw4.com2.z0.glb.qiniucdn.com/1.jpg',
        title: '如何手制一份秋意的茶？'
      }, {
        url: 'http://mp.weixin.qq.com/s?__biz=MzAxNjU0MDYxMg==&ampmid=400160890&ampidx=1&ampsn=29ef02af25793a11a3f6aec92bfb46c1&ampscene=19#wechat_redirect',
        img: 'http://7xqzw4.com2.z0.glb.qiniucdn.com/2.jpg',
        title: '茶包VS原叶茶'
      }, {
        url: 'http://mp.weixin.qq.com/s?__biz=MzAxNjU0MDYxMg==&ampmid=400094682&ampidx=1&ampsn=8231a2053b772b2108784fccc254d28c&ampscene=19#wechat_redirect',
        img: 'http://7xqzw4.com2.z0.glb.qiniucdn.com/3.jpg',
        title: '播下茶籽，明春可发芽？'
      }]
    }
  }
}
</script>

<style>

</style>

```

[HMR] Vue component hot reload shim applied.
vue.common.js?e881:986[Vue warn]: Unknown custom element: <swiper> - did you mean <swiper>? HTML is case-insensitive, remember to use kebab-case in templates.
Failed to parse SourceMap: data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiIxMi5qcyIsInNvdXJjZVJvb3QiOiIifQ==

**Comment by airyland** [comment]
vux not vue?

**Comment by airyland** [comment]
use ``` html for better code review.

**Comment by bulolo** [comment]
![image](https://cloud.githubusercontent.com/assets/10026498/14041679/4726e696-f2ae-11e5-89f1-2230a6a04460.png)

**Comment by bulolo** [comment]
抱歉 vux写成vue,改正过来了。用了```，造成麻烦不好意思。
之前用了swiper 没问题。刚更新完，变成这样。

**Comment by airyland** [comment]
@bulolo 目测又是打包时vue-loader依赖的html-minifier处理出问题了。得等我重新发布一次包。或者你直接引用.vue文件。

**Comment by airyland** [comment]
在明天发布的v0.0.105中修复

**Comment by bulolo** [comment]
并没有修复，试了一下，依然出问题

**Comment by airyland** [comment]
@bulolo 因为还没有发布出去

**Comment by bulolo** [comment]
0.0.105还是木有修复。。

**Comment by airyland** [comment]
@bulolo  可以的呀

https://vux.li/api/v1/demo.html?components=Swiper&template=%3Cdiv%3E%0D%0A%20%20%3Cswiper%20%3Alist%3D%22list%22%20%3Aauto%3Dtrue%3E%3C%2Fswiper%3E%0D%0A%3Cdiv%3E&style=&script=export%20default%20%7B%0D%0A%20%20data%3A%20function%20()%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20list%3A%20%5B%7B%0D%0A%20%20%20%20%20%20%20%20url%3A%20%27http%3A%2F%2Fmp.weixin.qq.com%2Fs%3F__biz%3DMzAxNjU0MDYxMg%3D%3D%26ampmid%3D400385458%26ampidx%3D1%26ampsn%3D78f6b8d99715384bdcc7746596d88359%26ampscene%3D19%23wechat_redirect%27%2C%0D%0A%20%20%20%20%20%20%20%20img%3A%20%27http%3A%2F%2F7xqzw4.com2.z0.glb.qiniucdn.com%2F1.jpg%27%2C%0D%0A%20%20%20%20%20%20%20%20title%3A%20%27%E5%A6%82%E4%BD%95%E6%89%8B%E5%88%B6%E4%B8%80%E4%BB%BD%E7%A7%8B%E6%84%8F%E7%9A%84%E8%8C%B6%EF%BC%9F%27%0D%0A%20%20%20%20%20%20%7D%2C%20%7B%0D%0A%20%20%20%20%20%20%20%20url%3A%20%27http%3A%2F%2Fmp.weixin.qq.com%2Fs%3F__biz%3DMzAxNjU0MDYxMg%3D%3D%26ampmid%3D400160890%26ampidx%3D1%26ampsn%3D29ef02af25793a11a3f6aec92bfb46c1%26ampscene%3D19%23wechat_redirect%27%2C%0D%0A%20%20%20%20%20%20%20%20img%3A%20%27http%3A%2F%2F7xqzw4.com2.z0.glb.qiniucdn.com%2F2.jpg%27%2C%0D%0A%20%20%20%20%20%20%20%20title%3A%20%27%E8%8C%B6%E5%8C%85VS%E5%8E%9F%E5%8F%B6%E8%8C%B6%27%0D%0A%20%20%20%20%20%20%7D%2C%20%7B%0D%0A%20%20%20%20%20%20%20%20url%3A%20%27http%3A%2F%2Fmp.weixin.qq.com%2Fs%3F__biz%3DMzAxNjU0MDYxMg%3D%3D%26ampmid%3D400094682%26ampidx%3D1%26ampsn%3D8231a2053b772b2108784fccc254d28c%26ampscene%3D19%23wechat_redirect%27%2C%0D%0A%20%20%20%20%20%20%20%20img%3A%20%27http%3A%2F%2F7xqzw4.com2.z0.glb.qiniucdn.com%2F3.jpg%27%2C%0D%0A%20%20%20%20%20%20%20%20title%3A%20%27%E6%92%AD%E4%B8%8B%E8%8C%B6%E7%B1%BD%EF%BC%8C%E6%98%8E%E6%98%A5%E5%8F%AF%E5%8F%91%E8%8A%BD%EF%BC%9F%27%0D%0A%20%20%20%20%20%20%7D%5D%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D

**Comment by bulolo** [comment]
![image](https://cloud.githubusercontent.com/assets/10026498/14310510/ca93c4b2-fc14-11e5-8f84-21c8ad02e8e7.png)

**Comment by airyland** [comment]
是否已经引入了样式？

**Comment by bulolo** [comment]
https://github.com/airyland/vux/blob/master/src/demos/Swiper.vue
我把这个全部复制过来。然后改动
import { Swiper, GroupTitle, SwiperItem, XButton } from '../components/'
改为
import { Swiper, GroupTitle, SwiperItem, XButton } from 'vux'
![image](https://cloud.githubusercontent.com/assets/10026498/14311030/e6f8d6da-fc17-11e5-8c46-83e436990f28.png)

**Comment by bulolo** [comment]
@import '~vux/vux.css';
加了这句好了。额。抱歉 马虎。非常感谢！

**Comment by airyland** [comment]
:sweat_smile:
