### ISSUE TITLE
在ios5和ios6上，flexBox设置的 span无效，所有box被均分了

### ISSUE THREAD

**Issue by zhangbing609** [airyland/vux#562]
### `Version`

 "vux": "^0.1.1"
### Android or iOS

ios5 与 ios6 
### 问题描述

在ios5和ios6上，flexBox设置的 span无效，所有box被均分了，测试的是官方页面：
[https://vux.li/#!/component/flexbox](url) 
### 测试结果.

[http://ac-dwhkbfjm.clouddn.com/28f4ccb7f4438801.png](url) 

![filehelper_1473319639390_65](https://cloud.githubusercontent.com/assets/469726/18341162/49a088fe-75db-11e6-9687-c73b54f3b819.png)

**Comment by airyland** [comment]
已经快出iOS10了，5跟6也太低版本了

**Comment by zhangbing609** [comment]
刚刚又找了一个 phone6  ios8.3的手机测试，依然如上图所示，这种大部分人还是在用的。

**Comment by airyland** [comment]
@zhangbing609 我好不容易找到一个iPhone4, 一看都已经升级到iOS9了。。为什么用户不想升级系统。。 :cry:

**Comment by airyland** [comment]
@zhangbing609  iOS8 的我测试了下新版本是没问题的，估计是demo站点的 autoprefix 配置有问题。

``` js
 browsers: ['last 7 versions']
```
