### ISSUE TITLE
demo列表的问题

### ISSUE THREAD

**Issue by wangbagang** [airyland/vux#569]
以前用sui的时候在路由切换的时候会保存上个页面的状态，比如示例列表我滑动到第20条的时候，切换到另外一个页面再切换回来还是在第20条的位置，但是我发现你的demo示例列表每次返回到列表都会从第一条开始，不会停留在我点击的位置。详细可以比较sui的demo和你的demo。

**Comment by airyland** [comment]
hash模式无法保存滚动位置，需要自己处理，demo没有处理而已。不同的两个库也没什么好比较的。
