### ISSUE TITLE
说些遇到的问题

### ISSUE THREAD

**Issue by GloriaCHL** [airyland/vux#57]
这个项目中的组件有些挺好的。因为没全部用过所以不敢说全部都好。比如下拉刷新那个组件，从demo里打开没问题，但重新刷新后就会变得无限刷新，根本停不下来。
另外，组件可以做到单个引用么？有些组件是可以，例如group、cell这种，直接把引用路径写到项目里的components就可以引用，但比较复杂点的组件貌似不行，比如picker、address这些。这个项目体积挺大的，项目代码跟自己写的代码加起来体积看着有点肉疼。所以，如果可以做到需要什么再从项目中引入什么的话会更好的。

**Comment by airyland** [comment]
单个引用看README

**Comment by airyland** [comment]
下拉刷新的问题我去重现一下看是什么问题。

**Comment by GloriaCHL** [comment]
那就有劳了︿(￣︶￣)︿

**Comment by airyland** [comment]
@GloriaCHL 我这边无法重现你所说的无限刷新的问题，麻烦提供下重现环境和步骤
