### ISSUE TITLE
监听scroller的滚动

### ISSUE THREAD

**Issue by yzuoran** [airyland/vux#572]
怎么样监听scroller组件内的滚动事件，滚动时内部是translatY值变化，用原生js监听scroll无效，我的需求是监听scroller内部元素滚动并获取元素的距顶距离，希望能帮忙解决，谢谢

**Comment by yuluhuang** [comment]
https://github.com/vuejs/vue/issues/1909
http://codepen.io/Dafrok/pen/KdLmZM

**Comment by ChristianYeap** [comment]
我也发现了这个问题，作者在main.js里有专门写
`window.addEventListener('scroll', saveDemoScrollTop, false)`
多次尝试测试修改都没有反应的，刚想来提问，就看到你发的

**Comment by 736008081** [comment]
这个问题 也困扰了我好久 后面发现 其实 你可以去看下xscroll 在修改vux的源码来满足自己的需求 scroller的源码里面加上这个this._xscroll.on('scroll', (e) => {
        this.$emit('onscroll', this._xscroll.getScrollTop())
      })   在你使用的地方用@onscroll，其实 多看下源码和理解作者的思路可以解决很多问题

**Comment by Sakuyakun** [comment]
@736008081 除了修改源码外还有其他的方法吗？

**Comment by 736008081** [comment]
@Sakuyakun 修改源码 编译打包后放到服务器是一样的 或者 你把作者的scroller源码拷出来写成自己的组件
