### ISSUE TITLE
微信浏览器中,在软键盘打开的情况下datetime与popup-picker激活时出现闪屏

### ISSUE THREAD

**Issue by lsvih** [airyland/vux#573]
您好：

在(且仅在)微信浏览器中，当页面中既需要文本输入又需要选择输入时，如果先将焦点定于文本框(软键盘弹出)，再点击popup-picker或datetime时页面会闪动。
问题重现网页:(请用微信打开)[http://123.56.200.45/tmp/index.html](http://123.56.200.45/tmp/index.html)

原因大概是微信浏览器中软键盘打开时页面的高度被挤压了，popup和datetime组件都使用了position:fixed属性，因此.vux-popup-dialog与.dp-container会先出现在软键盘上方，软键盘关闭后才跳到页面底部造成页面闪动。

我的临时解决办法:设置position:absolute，将popup与datetime组件放在顶端节点下.

希望您能看看这个问题

**Comment by graysheeep** [comment]
@lsvih android6.0.1正常

**Comment by lsvih** [comment]
@graysheeep thx,刚刚试了IOS9.x IOS10.x不正常
