### ISSUE TITLE
bug: popup-picker 动态设置列表数据存在的问题

### ISSUE THREAD

**Issue by ZoeyYoung** [airyland/vux#574]
### Version 0.1.3

更改 popup-picker 列表时会触发 `onPickerChange`, 源代码如下：

```
onPickerChange (val) {
  if (JSON.stringify(this.value) !== JSON.stringify(val)) {
    // if has value, replace it
    if (this.value.length) {
      const nowData = JSON.stringify(this.data)
      if (nowData !== this.currentData && this.currentData !== '[]') {
        this.value = getObject(val)
      }
      this.currentData = nowData
    } else { // if no value, stay quiet
      // if set to auto update, do update the value
    }
  }
  this.$emit('on-shadow-change', getObject(val))
}
```

假设切换列表前的数据为:

```
[['小米', 'iPhone', '华为', '情怀', '三星', '其他', '不告诉你']]
```

 `this.value` 为 `['iPhone']`

切换后为:

```
[['小米', 'iPhone', '华为', '情怀', '三星', '其他', '不告诉你', '我是push条目']]
```

此时 `this.value` 仍为 `['iPhone']`

根据判断this.value的值未改变，那么 `this.data` 就不会变赋值给 `this.currentData`，直到第一次改变 `this.value` 值的时候才触发了设置 `this.currentData = nowData`

期望的情况是第一次切换选项时其实只改变 `this.tempValue`

实际是第一次切换的时候同时改变了 `this.value`, 并且这个时候才设置了`this.currentData = nowData`**（=》存在问题的地方）**

<img width="400" alt="2016-09-13_1138" src="https://cloud.githubusercontent.com/assets/1754066/18460833/7fc74b00-79a7-11e6-8e8c-c5464b9bca8f.png">

正常情况下：

<img width="370" alt="default" src="https://cloud.githubusercontent.com/assets/1754066/18460753/dd5033be-79a6-11e6-8bdb-6b959e213cfb.png">

后面再切换`this.value`时由于 `nowData === this.currentData` 不会再改变 `this.value`（这时候是正常的）

理解了下代码的意图应该是要在 `this.value` 不存在于新列表的情况下更新 `this.value`, 而只要this.data有变更就应该赋值给`this.currentData`，修改后代码如下：

```
onPickerChange (val) {
  const nowData = JSON.stringify(this.data)
  if (nowData !== this.currentData && this.currentData !== '[]') {
    this.currentData = nowData
    if (JSON.stringify(this.value) !== JSON.stringify(val)) {
      // if has value, replace it
      if (this.value.length) {
        this.value = getObject(val)
      } else { // if no value, stay quiet
        // if set to auto update, do update the value
      }
    }
  }
  this.$emit('on-shadow-change', getObject(val))
}
```

PS：因为比较难描述~没有提PR~可能有没考虑到的地方~

**Comment by airyland** [comment]
@lichunqiang @unclay  你们能看懂么？ :sweat_smile:

**Comment by lichunqiang** [comment]
> 根据判断this.value的值未改变，那么 this.data 就不会变赋值给 this.currentData

这个理解错了吧？`JSON.stringify(this.value) !== JSON.stringify(val)` 这个改变后肯定为true吧...

PS: 一知半解中...

**Comment by airyland** [comment]
目测和#554 同个问题。已经merged.
