### ISSUE TITLE
tab-item

### ISSUE THREAD

**Issue by nieyulin112** [airyland/vux#575]
<img width="1280" alt="2016-09-13 5 59 58" src="https://cloud.githubusercontent.com/assets/7320972/18474984/435704e4-79f7-11e6-82e2-d8ae2acd92cf.png">
如上图所示，图中的三个tab－item在那个文件可以找到谢谢！

**Comment by airyland** [comment]
你是说底部的tabbar吧，组件目录里有。demo的相关代码在 https://github.com/airyland/vux/blob/master/src/App.vue#L14
