### ISSUE TITLE
address 还有日期组件，在pc微信客户端里打开就无法使用了

### ISSUE THREAD

**Issue by docikaci** [airyland/vux#576]
如题：
vux不支持PC打开吗？

**Comment by airyland** [comment]
请使用chrome的手机模拟功能测试

**Comment by docikaci** [comment]
@airyland 不是模拟测试，有些微信里的页面，可以在PC微信客户端里打开，组件就没法使用了，
如图：使用后面使用chrome 模拟手机没有问题。 但是微信客户端里打开就不行了

![image](https://cloud.githubusercontent.com/assets/7788102/18503515/d02985b6-7a8f-11e6-9b80-50c0ede9c1cc.png)

**Comment by docikaci** [comment]
滑不动。。

**Comment by airyland** [comment]
这个无法解决。建议引导到手机上操作，毕竟是移动端UI，不可能去完全兼容PC操作。
