### ISSUE TITLE
popup-picker 三级联动怎么赋初始值

### ISSUE THREAD

**Issue by liuxingchi** [airyland/vux#579]
### Version
最新版本
### Android or iOS
ios
> For Android issues, please specify the brand, model and browser

### Your Codes 
`<popup-picker title="选择省市" :data="addressData" :columns="3" :value.sync="addressValue" show-name></popup-picker>`

``` html
<!--put your code here-->
```

### Expected behavior and actual behavior.
popup-picker 三级联动的话，怎么赋初始值呢，就那个addressValue格式是什么样的呢，看demo里没有这种的赋值

**Comment by graysheeep** [comment]
不是demo最下面就有个3级联动么

**Comment by liuxingchi** [comment]
@graysheeep 我看那个demo里没有写怎么赋初值呢

**Comment by liuxingchi** [comment]
今天试了一下，又可以了
