### ISSUE TITLE
script的方式引入，怎么一次引入所有组件

### ISSUE THREAD

**Issue by liwei1991** [airyland/vux#586]
使用script的方式引入 ，需要一个个的去引入js文件么，能一次引入所有组件吗，新手勿怪，谢谢

**Comment by airyland** [comment]
移动端，你确定要一次性引入。。实际是用不到这么多组件的。请按需使用。

**Comment by liwei1991** [comment]
一个个的引入好麻烦的呀，有没有提供一个js会自动注册到 Vue 里。同时全局暴露了 ELEMENT 对象

**Comment by airyland** [comment]
目前不考虑这种不友好的方式，有一天你应该会觉得体积太大，加载太慢。另外用webpack吧，别一个个这样引入了。

**Comment by liwei1991** [comment]
现在项目都是多页面的应用，我感觉用webpack 也很麻烦啊，而且迭代频繁，页面太多。难道方式不对么，有好的方法，请指教 多谢

**Comment by airyland** [comment]
@liwei1991 页面越多用webpack开发效率才高。
