### ISSUE TITLE
一个天大的误会：Vux并非微信应用号项目

### ISSUE THREAD

**Issue by airyland** [airyland/vux#587]
昨晚开始，不知道是什么原因，不少人以为Vux是微信应用号的一个demo项目，导致不少人加我微信，也给我转了捐赠(十分感谢，到手就不退了 😃 )。但是Vux目前是基于WeUI的UI库，并非微信应用号相关的东西，因为我也没有应用号内测资格，所以还不清楚具体细节。

非Vux特意做的推广，本人价值观十分纯正，特此声明～

**Comment by AngusFu** [comment]
哈哈哈  在一个 500 人的前端群中看到有人提了

**Comment by brianzhang** [comment]
在前端之颠看到了

**Comment by lichunqiang** [comment]
囧

**Comment by rdmclin2** [comment]
微博看到尤大大在推vux做微信应用了:smile:

**Comment by martint028** [comment]
需要上架审核什么的么，类似AppStore

**Comment by Acathur** [comment]
在多条新闻里看到Vux Demo截图，颇为震惊，刚准备来issue求证，便发现了此条信息😀

**Comment by unclay** [comment]
哈哈 @airyland  等内测完，看看能否结合小程序来开发

**Comment by chenshuox** [comment]
大家似乎都很期待微信应用号，出来不晓得是个什么东西

**Comment by ymm8505** [comment]
不过 界面确实不错哦~

**Comment by tomoyuen** [comment]
品玩上发的文章有vux的截图：[为什么微信深夜发布的“小程序”引动了开发者的大地震](http://www.pingwest.com/hello-world-wechat-h5-apps/)

**Comment by graysheeep** [comment]
这波宣传很到位

**Comment by acs1899** [comment]
目测要火

**Comment by golhoon** [comment]
哈哈 笑死我了。在很多群都看到。

**Comment by BelinChung** [comment]
从目前的消息来看，可能小程序并非运行在 webview 上面。而是跟 RN 类似，使用 JS 作为描述语言转换成内置的原生组件。

**Comment by zhEdward** [comment]
移动开发越加白热化

**Comment by airtayork** [comment]
哥们，你可以在demo的首页加一行说明。。。

**Comment by zyong812** [comment]
哈哈哈

**Comment by HanFighting** [comment]
大家好，我是InfoQ的编辑尾尾，业余时间来运营 前端之巅 社区，昨晚激动+失眠，分享了很多内容到前端之巅的社区以及我的朋友圈里，包括Vux。

或许是我一起转发过去的缘故？虽然我神马都木有说。。但是造成了误会实在抱歉！已经发文说明了情况：

[《刷爆朋友圈的“微信应用号事件”始末及相关资料整理》](http://mp.weixin.qq.com/s?__biz=MzIwNjQwMzUwMQ==&mid=2247484263&idx=1&sn=62b1af865c843a00ca34cbb857120d66&chksm=972361a5a054e8b3755bc8a86f92abb4e485ebc6d577e8955fd69cf683a5fa6120bf66bd06e0&scene=1&srcid=09223n6kjmvbQ0BzoEAafnXj#rd)

感谢大家支持，也希望大家能够谅解这次造成的误会！

**Comment by kuange** [comment]
看吧,这几天star数量会骤增! 哈哈

**Comment by weichengwu** [comment]
二话不说先续一星

**Comment by leizongmin** [comment]
此帖必火

**Comment by MarkStray** [comment]
抓住楼上元凶一只

**Comment by MrBeen1113** [comment]
star剧增

**Comment by rdmclin2** [comment]
早上看是3打头，现在都4了

**Comment by chenshuox** [comment]
VUX 非常棒，必须火起来！

**Comment by lovecn** [comment]
star+1

**Comment by chown9835** [comment]
非常棒的一個項目，支持！

**Comment by 1025623017** [comment]
# 上个星期用VUX完成了几个模块，支持~

**Comment by watonyweng** [comment]
一不小心Star了，当然会继续关注Vux

**Comment by fritx** [comment]
如何把vue/vux，或者部分用法，应用到现有的小程序中？

**Comment by zkk765696946** [comment]
感觉可以给微信加一个 解析包 感觉就能用vue了

**Comment by XatMassacrE** [comment]
支持支持~
