### ISSUE TITLE
swiper 高度设置问题，为什么在getHeight中要parseInt？

### ISSUE THREAD

**Issue by xingoxu** [airyland/vux#590]
https://github.com/airyland/vux/blob/master/src/components/swiper/index.vue
  
line 74: 
```javascript
const hasHeight = parseInt(this.height, 10);
```
  
既然已经暴露了height，css的height属性就应该完全由使用者决定，现在这样的设定导致height属性只能使用以数字开头的单位，不能使用calc属性。
  
我知道swiper也被用来制作图片轮播，现在这样做的话，单页面tab+swiper，tab固定高度44px，swiper就无法设置高度了，除非使用css important，否则也无法覆盖element style。
  
所以想知道po主当时写这个组件使用parseInt的想法是怎样的，谢谢po主

**Comment by airyland** [comment]
组件基于具体业务，业务上并没有用其他单位的需求，因此就直接用px了。考虑是基于业务的，不可能考虑到所有情况，增加了复杂性。
