### ISSUE TITLE
popup-picker 在浏览器出现滚动条的情况下会出现错乱，选择会失效

### ISSUE THREAD

**Issue by jinjl** [airyland/vux#592]
vux:0.1.3
vue:1.0.26
浏览器：Andriod 百度浏览器

问题描述：页面出现滚动条，触发picker，会出现popup-picker样式错乱，选择功能无效。

**Comment by airyland** [comment]
百度浏览器没有用过。。内核是同Android内置的吗，是的话提供一下Android版本。

**Comment by jinjl** [comment]
找到原因了，是因为页面出现滚动条，弹出picker的按钮不在首屏会出现这种情况，在弹出picker之前将页面的滚动条禁止了就可以了。
