### ISSUE TITLE
安装失败 node版本6.2.0 npm版本3.8.9

### ISSUE THREAD

**Issue by jcto** [airyland/vux#593]
$ npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! shasum check failed for C:\Users\opg\AppData\Local\Temp\npm-10548-922eb1ad\registry.npmjs.org\vux\-\vux-0.1.3.tgz
npm ERR! Expected: 3b5a164353c7ad8a084989e75e3fe65987c8384c
npm ERR! Actual:   450f489da7a6ec8bb857bd3eb074f1ba4e612329
npm ERR! From:     https://registry.npmjs.org/vux/-/vux-0.1.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by airyland** [comment]
换cnpm试试。或者加上代理试试。
