### ISSUE TITLE
swipe在只有两个滚动内容的时候，不能无缝循环滚动

### ISSUE THREAD

**Issue by acmeid** [airyland/vux#596]
我看代码里面写着是必须是滚动内容必须大于等于3个，才能无缝循环滚动。
这个是否可以优化一下，使得两个滚动内容也可以无缝循环滚动？

**Comment by airyland** [comment]
召唤 @unclay

**Comment by unclay** [comment]
无缝滚动是通过移动dom来实现的，前后都有dom视觉上才不会断开，今晚我再看看是否可以多复制两个dom来实现这个功能
