### ISSUE TITLE
Popup-picker 如何在二联非联动列表中使用name-value对？

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#598]
### Version

0.13
### Android or iOS

all

> For Android issues, please specify the brand, model and browser
### Your Codes

``` html
<popup-picker :data="filter_2" :value.sync="filter_2_value" 
:show.sync="filter_2_show" :show-cell="false" v-ref:filter_2></popup-picker>
```

``` javascript
new Vue({
    data:{
        filter_2_value:['', ''],
        filter_2: [
            [
                {name: '全部', value: ''},{name: '相关性', value: 'relative'}, {name: '入驻时间', value: 'time_asc'}, {name: '新店推荐', value: 'time_desc'}, {name: '店铺评价', value: 'rate_desc'}, {name: '评价数', value: 'ratecount_desc'}
            ], 
            [
                {name: '全部', value: ''},{name: '相关性', value: 'relative'}, {name: '入驻时间', value: 'time_asc'}, {name: '新店推荐', value: 'time_desc'}, {name: '店铺评价', value: 'rate_desc'}, {name: '评价数', value: 'ratecount_desc'}
            ]
        ],
    }
})
```
### Expected behavior and actual behavior.

可以看出，通过data绑定，将这个popup picker的值绑定到了一个变量`filter_2_value`上，但是该变量获取的是`value`的值。
我尝试用`this.$refs.filter_2.getNameValues();`去取`name`数值，但是报错找不到name。
应该怎么正确的使用呢？谢谢。

**Comment by dangyuluo** [comment]
我看了下，问题应该出在文件 value2name.js  第七行上。

```javascript
import map from 'array-map'
import find from 'array-find'

export default function (value, list) {
  let rs = map(value, (one, index) => {
    return find(list, item => {
      return item.value === one
    })
  })
  return map(rs, one => {
    return one.name
  }).join(' ').replace('--', '')
}
```

对于单列的popuppicker来说，`value`应该是一个单纯包含该value的数组，如：`value=["store_owner", __ob__: bt]`，而`list`应当是n个item对象，每个item对象都有name和value属性。

但是对于多咧popuppicker来说，如果还是调用这个函数的话，e就变成了`e = ["全部", "相关性", __ob__: bt]`，多了第二列的内容。而此时，`list`则变成了array[array[obj1, obj2...], array[obj1, obj2...]]. 这时每个`item`就取不到`value`属性，而应该再向底循环一层进行判断相等。

**Comment by enicn** [comment]
我也碰到了同样的问题，做出了一个简单的修复，给你参考一下
`import map from 'array-map'
import find from 'array-find'

export default function (value, list) {
  let rs
  rs = map(value, (one, index) => {
    if (list.length && Object.prototype.toString.call(list[0]) === '[object Array]') {
      return find(list[index], item => {
        return item.value === one
      })
    } else {
      return find(list, item => {
        return item.value === one
      })
    }
  })
  return map(rs, one => {
    return one.name
  }).join(' ').replace('--', '')
}`
