### ISSUE TITLE
Blur组件图片无法显示完全

### ISSUE THREAD

**Issue by SevenOutman** [airyland/vux#599]
### Version

npm 0.1.3

### Android or iOS

Chrome模拟器

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
    <div class="blur-image-box">
        <blur :blur-amount="10" :url="imgSrc" :height="imgHeight"></blur>
    </div>
    <script>
        export default {
            ....
            data() {
                return {
                    imgSrc: 'http://voez.sevenoutman.com/voez/cover/85/750',
                    imgHeight: window.innerWidth * 0.5625
                }
            }
        }
    </script>
```

### Expected behavior and actual behavior.

图片是 750*422 的 16:9 比例，于是将 `height` 设为 `window.innerWidth * 9 / 16` ，并且给 `.blur-image-box` 设置了正确的样式。

渲染出来的结果，`.blur-image-box` 和 `blur` 的根元素都是宽 375 高 211，但里面的 svg 和 image 虽然都设置了 `width=375` `height=211` 但在检查器里显示宽 525 高 295.31 ，并且 `blur` 只显示了原图的一部分。

**Comment by airyland** [comment]
让图片边缘一部分不会显示出来，是为了避免因svg的实现方式出现难看的边缘样式。
如果为了100%显示，建议直接使用css3的blur滤镜。
