### ISSUE TITLE
npm install总是报几个deprecated警告

### ISSUE THREAD

**Issue by SuHeran** [airyland/vux#600]
### Version
node v5.0.0
npm 3.10.3

### Your Codes 

``` 
<!--put your code here-->
npm install -g vue-cli
vue init webpack my-project
cd my-project
npm install
```

### Expected behavior and actual behavior.
预期正常下载node_modules文件，但每次都报以下几个警告
```
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

在下载的时候也总会暂停下载（暂停时的百分比不定）

我也尝试按照警告提示在my-project目录下来升级minimatch、graceful-fs等上面警告和提示替换的文件
```
npm install minimatch
```
或
```
npm ls -g minimatch
```
删除node_modules，重新执行```npm install```命令，还是之前一样的情况

**Comment by SuHeran** [comment]
还有一点，我想知道使用vux对node、npm的版本有没有要求啊，我开始用的node6.6.0、npm3.10.3，也是出现上面的问题，总是警告和下载不动，特意降低了node的版本到5.0.0，npm还是最高版本3.10.3，还是没有解决

**Comment by airyland** [comment]
目测上面大部分不是vux的依赖，可能是vue-loader相关的依赖。vux没有版本要求，但是vue-loader和webpack可能有，这个我也不确定。上面只是WARN, 应该不影响正常运行的。

**Comment by SuHeran** [comment]
但就是下载不了
```
Receiving...
  [----------------------------------------] x%
```
x的取值范围总是在0<x<100这个范围，就是到不了100%，以前在公司的时候```npm install```从来没出现过这种情况。
谢谢你即使的回复😁

**Comment by unclay** [comment]
试试用淘宝源

**Comment by SuHeran** [comment]
但就是下载不了
```
Receiving...
  [----------------------------------------] x%
```
x的取值范围总是在0<x<100这个范围，就是到不了100%，以前在公司的时候```npm install```从来没出现过这种情况。
谢谢你即使的回复😁

**Comment by SuHeran** [comment]
@unclay 谢了，我的电脑一直处于翻墙状态下的，网速一直也不错，之所以没用cnpm就是因为这些可能不是最新版本，也不是和npm直接同步，所以从来未曾用过

**Comment by airyland** [comment]
cnpm现在基本貌似是10分钟同步一次，所以和npm应该是同步的。我有遇到的情况时是windows下会有你上面无法下载的情况出现，而在Mac上是完全正常。有时候换换网络又好了。

**Comment by yuguo97** [comment]
$ npm install jquery
kuiguo1991@1.0.0 C:\Users\Administrator
`-- jquery@3.1.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch                                                                                                               okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                               1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                                                                               )
npm WARN kuiguo1991@1.0.0 No description
npm WARN kuiguo1991@1.0.0 No repository field.
哪里错了?
