### ISSUE TITLE
x-header组件可以动态的修改right slot吗

### ISSUE THREAD

**Issue by lianer** [airyland/vux#603]
我有个项目设计所有页面公用一个header组件，并设参数v-ref:header。

每个页面通过this.$root.$refs.header.title去重设标题或其他参数。

但我不知道如何重设right slot，并且还要实现点击事件，我现在暂时还没有找到解决办法。

![](http://kano.guahao.cn/vd73311393)

**Comment by airyland** [comment]
这种场景当然是直接用vuex来管理

**Comment by lianer** [comment]
我不知道vuex还能管slot…
