### ISSUE TITLE
vux的demo中后退的问题

### ISSUE THREAD

**Issue by digname** [airyland/vux#606]
demo的组件列表下拉以后，然后点击某一个组件进入，然后后退返回到demo的组件列表，这时候列表返回到顶部了，而不是之前下拉滚动的位置，这个怎么解决？非常感谢！

**Comment by Chyroc** [comment]
＋1

**Comment by songhlc** [comment]
@digname 不知道你说的这个可以不可以解决
```
const router = new VueRouter({
  saveScrollPosition: true
})
```

**Comment by digname** [comment]
@songhlc 
不行，加了：
`  history: true,
  saveScrollPosition: true,`
demo运行起来还是不行。

**Comment by dmm33** [comment]
+1

**Comment by airyland** [comment]
主要是100%布局的影响，新版会重写demo页面，因此关闭当前issue了。
