### ISSUE TITLE
vux的swiper好像没命名空间的概念，所以swiper嵌套swiper就各种问题

### ISSUE THREAD

**Issue by 569835014** [airyland/vux#607]
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```

**Comment by airyland** [comment]
1. 给出代码
2.移动端不应该有这种嵌套swiper的奇怪需求
3.各种问题请明确，否则对解决问题没有任何帮助

请完善信息后重开issue。
