### ISSUE TITLE
npm 版本Style.vue缺少weui.min.css

### ISSUE THREAD

**Issue by agileago** [airyland/vux#61]
刚才更新了一下vux，我单独引入了Style.vue，报找不到weui.min.css错，发现npm的版本没有assets目录

**Comment by airyland** [comment]
抱歉，样式引用已经修改了引用方式，现在是直接引用 vux.css。

**Comment by ph2-cst** [comment]
`"vux": "0.0.111"`
同样问题 
panel没有样式

**Comment by airyland** [comment]
@ph2-cst 不要在已经关闭的issue里评论，会被忽略掉的。你怎么引用样式的？

**Comment by ph2-cst** [comment]
sorry 我以为会重新打开

 `require('vux/vux.css')` 就可以了

只是看example没有发现要引入css
tab用自己的css，所以之前没发现
所以为什么有的组件里面写css，有的一点css都没有
