### ISSUE TITLE
请教x-input 代码疑问

### ISSUE THREAD

**Issue by huike1989** [airyland/vux#615]
x-input 中使用到  base.js  文件，想请问下大神 

computed: {
    dirty () {
      console.log(!this.prisine)
      return !this.prisine
    }
  }
这个 dirty 的具体作用是什么呢？小弟百思不得其解，望百忙之中帮忙答疑，非常感谢。

**Comment by lichunqiang** [comment]
类似于angular表单验证时的 `$dirty`

属性类	|  | 	描述
-----------|-------|-----
$valid |	ng-valid |	Boolean  告诉我们这一项当前基于你设定的规则是否验证通过
$invalid |	ng-invalid	| Boolean  告诉我们这一项当前基于你设定的规则是否验证未通过
$pristine |	ng-pristine |	Boolean  如果表单或者输入框没有使用则为True
$dirty	| ng-dirty | 	Boolean  如果表单或者输入框有使用到则为True

**Comment by huike1989** [comment]
thx, 终于明白了。
