### ISSUE TITLE
各位打包出来的vux项目js多大才算正常？

### ISSUE THREAD

**Issue by hubinjie** [airyland/vux#617]
### Version
0.1.3-rc9

### Android or iOS

> For Android issues, please specify the brand, model and browser

如题？

**Comment by Maopy** [comment]
@hubinjie 你的多大？

**Comment by hubinjie** [comment]
@Maopy 小项目加起来在800K左右，内容多的有超过1M

**Comment by lichunqiang** [comment]
这个没有一个固定的标准吧....

**Comment by Maopy** [comment]
@hubinjie 你是把所有组件全打进去了？我引用了10个组件左右吧 vux的大小大概在 100K 也是感觉略微偏大

**Comment by agileago** [comment]
单组件引用会极大减小体积的，剩下就是跟你业务相关的，不过放到cdn上gzip之后都会变得很小的

**Comment by airyland** [comment]
如果没有scroller, preview组件的话，应该不大。
