### ISSUE TITLE
按照教程上的配置webpack，vue+   vue-router  中按需引入 vux 无法引入   

### ISSUE THREAD

**Issue by echozhangzy8888** [airyland/vux#618]
index.vue:3Uncaught Error: Cannot find module "-!babel-loader!./../../../../vue-loader/lib/selector.js?type=script&index=0!./index.vue"

～～～
module: {
        loaders: [
            { test: /\.vue$/, loader: 'vue' },
            { test: /vux.src.*?js$/,loader: 'babel'},
            { test: /\.js$/, loader: 'babel', exclude: /node_modules/ },
            { test: /\.css$/, loader: 'style!css!autoprefixer' },
            { test: /\.scss$/, loader: ExtractTextPlugin.extract('style', 'css!sass') },
            { test: /\.(gif|jpg|png)\??.*$/, loader: 'url-loader?limit=9999' },
            { test: /\.(html|tpl)$/, loader: 'html-loader' },
            { test: /\.less$/, loader: ExtractTextPlugin.extract('style', 'css!less') },
            { test: /\.(woff|woff2|svg|eot|ttf)\??.*$/, loader: "url?name=fonts/[hash:8].[name].[ext]&limit=10000" },
        ]
    },
    // 转es5
    babel: {
        presets: ['es2015'],
        plugins: ['transform-runtime']
    },
    resolve: {
       
        extensions: ['', '.js', '.vue'],

        alias: {
            'vux-components': 'vux/src/components/',
            'filter': path.join(__dirname, './src/filters'),
            'components': path.join(__dirname, './src/components')
        }
    },
～～～

**Comment by airyland** [comment]
组件调用代码呢？

**Comment by echozhangzy8888** [comment]
hao le 发现降低 一个 vux版本  同时 src目录 改为dist 别名里 alias 就ok

**Comment by airyland** [comment]
不建议使用dist的umd。最好直接引用.vue的组件代码。

**Comment by echozhangzy8888** [comment]
嗯 是引用 dist目录里 .vue的组件
