### ISSUE TITLE
src/components/panel/index.vue

### ISSUE THREAD

**Issue by zlab** [airyland/vux#619]
### Version 0.1.3

``` html
v-for="item in list"  v-if="type === '1'"
```

vue.common.js?e881:1137
[Vue warn]: <div v-for="item in list" v-if="type === '2'">: 
Using v-if and v-for on the same element is not recommended - consider filtering the source Array instead. (found in component: <panel>)

**Comment by zlab** [comment]
![qq 20161013141634](https://cloud.githubusercontent.com/assets/2288630/19338444/a946e07a-914f-11e6-8acd-07697c6cf579.png)

**Comment by lichunqiang** [comment]
提示感觉已经很清晰了吧。

根据`type` 来改变 `list` 的数据

**Comment by zlab** [comment]
Using v-if and v-for on the same element is not recommended

**Comment by zlab** [comment]
Using v-if and v-for on the same element is not recommended
这是来自vue的警告

**Comment by zlab** [comment]
不要随便关闭好吗

**Comment by lichunqiang** [comment]
> Using v-if and v-for on the same element is not recommended

看明白这个是什么意思没？

**Comment by zlab** [comment]
> v-for="item in list"  v-if="type === '1'"

这段代码不是我写的，是vux的panel组件里的！！！

> Using v-if and v-for on the same element is not recommended

**Comment by lichunqiang** [comment]
那还真不好意思，你提的问题真看不出来。没提到panel组件，没按issue template来，下次劳烦写的尽量详细！

**Comment by airyland** [comment]
大家不要激动啊，目测这是vue新版本的一个 v-if v-for的使用建议，但是我还不明白用意，容我花点时间研究一下。

**Comment by yanglang1987500** [comment]
@airyland 估计要在外层套一个容器以使用v-if，提示说不建议两个东西用在一个元素上。。PS： 我们最近用了vue2.0，一直在等待Vux2.0哈~

**Comment by airyland** [comment]
vue2并不会继续有这个警告因此关闭这个issue了。
