### ISSUE TITLE
vux在vue2.0下的问题

### ISSUE THREAD

**Issue by 317365887** [airyland/vux#620]
app.js
`import Tabbar from 'vux/dist/components/tabbar'
import TabbarItem from 'vux/dist/components/tabbar-item'

export default {
  components: {
    Tabbar,
    TabbarItem
  }
}
`

谷歌报错
vue.common.js?e881:2611[Vue warn]: You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build. 
(found in component <tabbar>)
![image](https://cloud.githubusercontent.com/assets/8263888/19429648/67189248-9483-11e6-915d-b4efb38f1bcc.png)

**Comment by airyland** [comment]
not vue2.0 yet

**Comment by 317365887** [comment]
有升级到vue2.0的打算不

**Comment by airyland** [comment]
#609
