### ISSUE TITLE
bug with tabs

### ISSUE THREAD

**Issue by saopang** [airyland/vux#621]
机型：中兴nubia z11mini
系统：NX529J_CNCommon_V1.36
安卓：android 5.1.1
微信：6.3.27
qq浏览器：7.0.0.2740

but：在iphone6的ios10.0.2经测试没有问题

tabs出现以下显示问题：
怀疑是动画引起的，不带动画的直接切换没有问题
![image](https://cloud.githubusercontent.com/assets/11707936/19462850/115183d4-9522-11e6-97c6-3bf94fa0e81b.png)
![image](https://cloud.githubusercontent.com/assets/11707936/19462848/0fef1ace-9522-11e6-9a84-ac2772118e0e.png)
![image](https://cloud.githubusercontent.com/assets/11707936/19462851/11d13fe8-9522-11e6-84ca-6b796695342b.png)

**Comment by airyland** [comment]
以前有其他人反馈过，但是我找到的Android机都重现不了。
