### ISSUE TITLE
tab

### ISSUE THREAD

**Issue by zhonggedan** [airyland/vux#622]
npm：3.8.9

```
<tab>
            <tab-item :selected="demo1 === '11111'" @click="demo1 = '11111'">1111</tab-item>
            <tab-item :selected="demo1 === '22222'" @click="demo1 = '22222'">22222</tab-item>
            <tab-item :selected="demo1 === '333333'" @click="demo1 = '33333'">33333</tab-item>
            <tab-item :selected="demo1 === '44444'" @click="demo1 = '4444'">444</tab-item>
        </tab>
```

```
<script>
    import { Tab,TabItem } from 'vux/src/components/Tab'
    export default{
        components: {
            Tab,
            TabItem,

        },
        data () {
            return {
                demo1: '11111',
                demoDisabled: 'A',
                index: 0
            }
        }
    }
</script>
```

基本就是复制的代码，但是运行起来报错
vue.common.js?e881:2611 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "selected" 
(found in component <tab-item> at E:\space_ws\weixinx\node_modules\vux\src\components\Tab\tab-item.vue)

顺便小声的问一下：Tab只能组合swiper用吗？  另：demo中Tab的例子不懂，可否提供一个更加直观的让新手理解一下。

**Comment by zhonggedan** [comment]
初始化webpack这样搞安装的是vue1：
vue init webpack#1.0 mynewproject

这样好像是vue2：
vue init webpack mynewproject

所以会乱七八糟的报错

**Comment by airyland** [comment]
正在支持Vue2。因此目前会有各种报错。
