### ISSUE TITLE
主题颜色的诉求

### ISSUE THREAD

**Issue by saopang** [airyland/vux#623]
个人非常喜欢现在Vux的配色，也灰常感谢大神的开源。
但身处金融公司，大家都知道金融公司对绿色非常的反感（参照股市）
而且不同公司的主题色都不一样，是否会预留一个配置文件，作为全局颜色的更换
mint-ui的蓝色，以及金融公司惯用的土豪金，面向女性社区的少女粉，建议适配

**Comment by airyland** [comment]
现在配色是WeUI的配色。1.0会有一份less变量配置可用，大概11月初。

**Comment by astarring** [comment]
对的，这个我也需要，不知airyland兄的1.0版本什么时候发布？
