### ISSUE TITLE
Dialog组件的使用

### ISSUE THREAD

**Issue by agileago** [airyland/vux#624]
在实际业务中使用 dialog组件的时候，遇到了一些样式上的问题， 由于dialog组件是相对于window，fixed的，但我们在写业务中是把dialog组件放到业务组件内，导致dom结构是业务组件包含dialog，假如业务组件中样式里面含有 `transform` 或者其他css属性，会导致fixed元素定位失败，变成absolute，这个时候如果有滚动条会导致bug出现，官方推荐把dialog放到根组件内，通过事件去控制dialog，这会失去很多便利性， 我在想有没有可能 dialog组件还是放在业务组件内，但是他的dom结构是放在body下面的，比如

业务组件a

``` html
<div>
<input v-model="money">
<dialog v-transclude="body">
  <div>{{ money }}</div>
</dilog>
</div>
```

dialog是在组件A中，但实际渲染到dom的时候,dialog组件是在body下面，提供一个`v-transclude`的指令去实现，这样就完美解决 控制便利性与样式冲突的问题， @airyland 你觉得呢？

**Comment by airyland** [comment]
这个想法我在popup-picker那边考虑过，移动到body下确实可以解决一部分定位问题。你自己有实现了这个directive吗？

**Comment by agileago** [comment]
我自己在下面尝试过，功能可以实现，但总觉得实现起来有点太容易了
```javascript
Vue.directive('transclude', {
   inserted (el) {
     document.body.appendChild(el)
   }
})
```
使用了这个指令之后测试一切ok，当然应该有些case没有考虑到，但我总觉得不应该这么简单...

**Comment by agileago** [comment]
这个应该深入到vue2的源码中，才能看出又没有那些潜在的问题

**Comment by agileago** [comment]
@airyland  今天抽空测试了一下，感觉没什么大问题

```javascript
Vue.directive('transclude', {
  inserted (el) {
    el.originParent = el.parentNode
    document.body.appendChild(el)
  },
  unbind (el) {
    el.originParent.appendChild(el)
  }
})
```
需要有一点注意的是 挪移到body下面的元素不能是组件的根元素，需要有一个占位元素
比如 `Dialog.vue`

```
<template>
  <span>
    <div v-transclude>
      <!-- Dialog 的结构 -->
    </div>
 </span>
</template>
```

这样Dialog主要结构挪移到`body`下面了，但是还剩下一个`span`的占位元素在那里保证Vue的处理逻辑不会出错

测试demo https://jsfiddle.net/agileago/xmvgprzL/

**Comment by agileago** [comment]
@airyland  在这里给你提一下一个建议就不开新issue了， `package.json`中加入一个`main`字段，让IDE找到这个库的入口好给智能提示，现在webstorm不给智能提示，这样在写
```
import {} from 'vux'
```
就有提示了

**Comment by airyland** [comment]
2.x没有main入口文件。。

**Comment by agileago** [comment]
搞一个啊，这样在引入vux组件的时候就有提示了，更舒爽了

**Comment by airyland** [comment]
不知道IDE能智能到什么程序，即使有main入口，也是直接import的.vue文件。

**Comment by agileago** [comment]
就是这个样子，我在vux的目录下面新建了个`index.js`，然后我在业务组件就有智能提示了
![image](https://cloud.githubusercontent.com/assets/11799110/22181816/35ed01fc-e0cf-11e6-94b4-8ab2f946340c.png)
![image](https://cloud.githubusercontent.com/assets/11799110/22181812/26f3f930-e0cf-11e6-8838-c9a362c33b39.png)

**Comment by airyland** [comment]
那可以，这个我可以用脚本来自动生成文件。

**Comment by agileago** [comment]
谢谢了，你不用webstorm么？他有很强大的智能提示的，特别是针对es6

**Comment by airyland** [comment]
:sweat_smile: 我基本只用sublimetext，不怎么依赖提示。

**Comment by agileago** [comment]
那得敲不少代码，我是个懒人...😂

**Comment by airyland** [comment]
试下 v2.1.0-rc.15

**Comment by agileago** [comment]
@airyland  太棒了！👍👍👍👍👍👍
![image](https://cloud.githubusercontent.com/assets/11799110/22183050/732d345e-e0ef-11e6-821a-935aeaed43ed.png)

**Comment by airyland** [comment]
看一下这个测试是不是完全符合你的需求：

https://vux.li/demos/v2/#/issue/624

**Comment by agileago** [comment]
非常棒，thanks your work！
