### ISSUE TITLE
vux 链接打不开

### ISSUE THREAD

**Issue by MAYDAY1993** [airyland/vux#627]
### Expected behavior and actual behavior.
下面网址中有如下图的三个没加相应的href属性 导致不能点击查看详情 在这个页面也没有向后翻页的箭头
https://vuxjs.gitbooks.io/vux/content/about/playground.html
![image](https://cloud.githubusercontent.com/assets/14831051/19507306/ad9222ac-9604-11e6-828c-b65ddb84c691.png)
另外问一下 swiper里面的‘是否描述梦曾’是什么意思啊
![image](https://cloud.githubusercontent.com/assets/14831051/19507407/3e0f3018-9605-11e6-90f9-d38aec7dbb88.png)

### Steps to reproduce the problem
https://vuxjs.gitbooks.io/vux/content/about/playground.html

**Comment by airyland** [comment]
gitbook某个版本的默认theme改成这样了，因为完全重写文档，所以这里暂时不改了。那里的文字应该是：是否显示描述遮罩。

**Comment by MAYDAY1993** [comment]
那新的文档是正在重写还是已经写好了呢 目前看vux的文档还是看这个链接的么 @airyland

**Comment by airyland** [comment]
80%，对目前文档还是这里。
