### ISSUE TITLE
怎么自由扩展search等等组件？

### ISSUE THREAD

**Issue by docikaci** [airyland/vux#628]
我想扩展search组件，增加获取焦点事件，点击input click事件，点击input延时获取焦点（延时弹出虚拟键盘）

如果我本地修改了 同事那边怎么更新呢
npm install 每次都是拉取的最新的，岂不是一点都不能修改源码了？

非常感谢！！

**Comment by airyland** [comment]
你可以直接把search源码拎到你们代码里，按照需求修复。
