### ISSUE TITLE
x-textarea 在ios9+ 不能输入，点击无光标出现

### ISSUE THREAD

**Issue by wanghaixu** [airyland/vux#630]
### Version

"vux": "^0.1.3-rc4",
### Android or iOS

IOS

> For Android issues, please specify the brand, model and browser
### Your Codes

``` html
<div style="width:100%;overflow:hidden;">
                <swiper :index.sync="currentStep" height="430px" :show-dots="false">
                    <swiper-item v-for="i in adviserStepList">
                        <div style="height:430px">
                            <h3>内容</h3>
                            <div class="adviser-content">
                                <x-textarea :value.sync="adviserTextContent[currentStep]" :height="200" :max="250" placeholder="请填写内容"></x-textarea>
                            </div>
                        <cell title="怎么写？" class="tran" primary="content">
                            <i class="icon" slot="icon">&#xe606;</i>
                        </cell>
                    </div>
                </swiper-item>
            </swiper>
        </div>
```
### Expected behavior and actual behavior.

预期行为：【Android ，ios】  可以输入内容
实际行为： Android 正常，ios不能输入，点击无光标出现。

**Comment by MissHoya** [comment]
我也是

**Comment by MengKeShang** [comment]
try to add textarea css class style like this:
.weui-textarea{  /*or your own textarea css class*/
    -webkit-user-select:  auto; /*webkit浏览器*/  
    -khtml-user-select:  auto; /*早期浏览器*/  
    -moz-user-select:  auto;/*火狐*/  
    -ms-user-select:  auto; /*IE10*/  
    user-select:  none;
}

**Comment by MengKeShang** [comment]
try to add textarea css class style like this:
.weui-textarea{ 
    -webkit-user-select: auto;
    -khtml-user-select: auto; 
    -moz-user-select: auto;
    -ms-user-select: auto; 
    user-select: none;
}

**Comment by MengKeShang** [comment]
try to add textarea css class style like this:
.weui-textarea{
-webkit-user-select: auto;
-khtml-user-select: auto;
-moz-user-select: auto;
-ms-user-select: auto;
user-select: auto;
}
