### ISSUE TITLE
vue init vuxjs/webpack my-project mo

### ISSUE THREAD

**Issue by dtchris** [airyland/vux#631]
vue init vuxjs/webpack my-project 

package.json  安装时
"vue": "^2.0.1",
怎么样安装才能切换到vue 1.0版本
### Android or iOS

> For Android issues, please specify the brand, model and browser
### Your Codes

``` html
<!--put your code here-->
```

**Comment by dtchris** [comment]
创建项目后 在package.json中改变vue版本安装 还是不能切换

**Comment by zhonggedan** [comment]
vue init vuxjs/webpack#1.0  my-project
