### ISSUE TITLE
tab+swiper的 swiper的高度如何设置成100%不生效？

### ISSUE THREAD

**Issue by zhonggedan** [airyland/vux#632]
vux：0.13

```
<!--suppress ALL -->
<template>
    <div>
        <tab :line-width=1 :index.sync="index">
            <tab-item class="vux-center"   @click="index=0">普及版</tab-item>
            <tab-item class="vux-center"   @click="index=1">成长版</tab-item>
        </tab>
        <swiper :index.sync="index"  :show-dots="false" @on-index-change="this.index=index">
            <swiper-item>
                <div class="tab-swiper">
                11111111111111111
                </div>
            </swiper-item>
            <swiper-item>
                <div class="tab-swiper">

                </div>
            </swiper-item>

        </swiper>
    </div>
</template>

<script>
    import { Tab, TabItem } from 'vux/src/components'
    export default{
        components: {
            Tab,
            TabItem,
        },
        data () {
            index:0

        },
        methods:{
            add:function () {

            }
        }
    }

</script>

<style>

</style>
```

默认为180px，设为100p%无效，所以只能显示部分内容，有解决办法吗？

**Comment by liu7923032** [comment]
可以通过 window.screen.height获取设备的高度，接着再created() 设置 swiper的 :height=‘’ 高度就好了

**Comment by sarices** [comment]
就算按照屏幕设置了高度，但是如果本身内容超出了高度了呢？加滚动组件？感觉这个组件设置的很不合理，tab应该增加一个tab-content组件

**Comment by terrence386** [comment]
我也遇到同样的问题

**Comment by airyland** [comment]
只能手动设置宽度。

组件的height就是直接设置style的height属性。首先从基本css布局上考虑一下什么情况下height:100%高度能实现你想要的100%高度。。

然后你要实现100%那么你要告诉组件你相对于哪个容器100%，相对父容器么，那么你也不同样得手动设置这个父容器的100%高度是多少，如果想跟viewport一样高，那么还得设置htm body 为100%。当然你要设置成fixed:100%这个也可以。如果你说计算一下内容高度呀，那么我还得计算一下每个swiper-item高度多少，因为每个swiper-item高度还不一致，合理的情况是要取最高的，不然高一点的可能内容就看不完整了。但是你的内容还可能是异步的，我在初始化时根本不知道有多高，那么你得告诉我最终渲染好了，我再去更新高度。。。

想起来都挺累，其他场景就不说了。所以不是组件设计问题，也不是不合理。你们感受一下上面各种情况。

所以这个高度只能手动按照像素来设置，组件实在无法知道具体场景。

对于上面说的内容超过高度的问题，理论上设置屏幕高度然后使用overflow:scroll来滚动不就可以滚动了。大部分场景根本不需要scroller。

另外tab+swiper适用于简单场景，即高度固定无复杂操作的场景，手机页面不适合复杂的内容滑动。swiper默认功用是轮播图。

当然欢迎pr来解决这个问题。

**Comment by zhengoogle** [comment]
height="100%"作用在内层div，需要外层div设置style="height: 100%;"
<Swiper height="100%"
            style="margin-top: 5px;height: 100%;">
