### ISSUE TITLE
我提取了vux的blur组件放到vue2中，好像没效果

### ISSUE THREAD

**Issue by hopkinson** [airyland/vux#641]
![image](https://cloud.githubusercontent.com/assets/13248613/19801966/ee21a672-9d33-11e6-95a6-594121a9e1a5.png)
还是我自己开发错误？

**Comment by hezhongfeng** [comment]
#609 
使用之前看看版本

**Comment by hc24** [comment]
现在vux基于vue1.0的，不过文档没有用明确依赖的vux1.0，建议明确。后来者各种踩坑

**Comment by hezhongfeng** [comment]
```
compatible with Vue@^1.0.24 (not yet support Vue@2.0)
```

**Comment by hc24** [comment]
我的意思是文档里面未提https://vuxjs.gitbooks.io/vux/content/

**Comment by hezhongfeng** [comment]
好吧，你赢了，你可以at作者把文档明确下
我也等2.x版本呢

**Comment by hinadong** [comment]
blur是使用SVG实现的，跟vue版本应该关系不大，你看下你重写的时候SVG用没用对，跟VUE2的关系不是太大
