### ISSUE TITLE
scroller组件先pullup多页数据后，再手动pulldown，部分dom没有更新

### ISSUE THREAD

**Issue by chenjiangsong** [airyland/vux#642]
重现步骤：
1.先上拉刷新多页数据，页面正确插入多个dom，同时滚动到底部5226px的位置
![image](https://cloud.githubusercontent.com/assets/14155079/19804662/4fd4e3ee-9d42-11e6-967c-29c489030c7a.png)
2.保持页面不动，再进行区域选择，将会调用pulldown的方法（因为和下拉刷新页面的逻辑一样，所以直接调用pulldown）
![image](https://cloud.githubusercontent.com/assets/14155079/19804664/550f5ace-9d42-11e6-874e-b755ed13b6b2.png)
**3.pulldown方法正确调用，页面也更新，但是之前被多页数据撑开的dom并没有更改，还停留在5226px的位置，划到顶部之后，页面才显示正常**
![image](https://cloud.githubusercontent.com/assets/14155079/19804667/58339cb0-9d42-11e6-9572-5e0fd8c3fe89.png)

**Comment by airyland** [comment]
没有看到具体代码，不过这种情况下使用reset方法设置位置为顶部进行重置应该可以解决。

``` js
reset({
 top: 0
})
```
