### ISSUE TITLE
component/tab组件选择tab标签时需要双击或是三击才能跳转到对应的标签

### ISSUE THREAD

**Issue by seric705** [airyland/vux#647]
1. npm项目版本号："version": "0.1.3",
2.git clone https://github.com/airyland/vux.git后的项目，在chrome浏览器开发者模式移动端设备尺寸（比如iphone6尺寸）和iphone7手机微信打开该组件页面存在标题描述问题，Safari没有，其中图一为跳转到tab组件页面，第二张图为第一次点击 “全部订单” tab后的效果，第三张图为第二次点击“全部订单”tab后的效果，精选美食电影酒店外卖那个tab需要三击才能跳转到点击的标签
![img_0434](https://cloud.githubusercontent.com/assets/19522109/19928503/a79ff280-a139-11e6-9360-6ecfbd540ee3.PNG)
![img_0435](https://cloud.githubusercontent.com/assets/19522109/19928523/b83c36e4-a139-11e6-8783-706fd4d5c0e6.PNG)
![img_0436](https://cloud.githubusercontent.com/assets/19522109/19928549/d35a1676-a139-11e6-81aa-f78bddc56395.PNG)

**Comment by hinadong** [comment]
我也遇到这样的问题，怎么解决的？

**Comment by wtyang** [comment]
没有任何评论就关闭了？
