### ISSUE TITLE
cell组件,link无法动态的赋值，能否支持v-router {name:'test',params:{}}格式的路由？

### ISSUE THREAD

**Issue by liu7923032** [airyland/vux#65]
### Your Codes 

``` html
<!--put your code here-->
```

**Comment by airyland** [comment]
cell组件的link其实我是想直接去掉的。因为假设没有使用vue-router，那么就不能编译v-link，vue-router 的 v-link可以写在任何元素上，因此你可以直接把v-link写在cell上。

**Comment by airyland** [comment]
上面说的有误，目前因为cell为片段组件，所以v-link会赋值失败。我修改一下。

**Comment by airyland** [comment]
在明天发布的v0.0.105中修复
