### ISSUE TITLE
scroller里面点击事件会触发2次

### ISSUE THREAD

**Issue by Helloooooooooo** [airyland/vux#651]
如题，暂时的情况是：
<button @click="submit">提交</button>

在chrome的pc模式下,
scroller里面的button点击事件，
点击会触发2次事件，而chrome移动端模式下是正常的。(浏览器版本：Chrome/55.0.2883.28)
不知道是bug，还是我个人的问题。

**Comment by hinadong** [comment]
设置prevent-default = true 就可以了，就不会出现点击二次了

**Comment by Helloooooooooo** [comment]
@hinadong
你好，谢谢回答。
你的意思是设置scroller的:prevent-default="true"吗，我尝试了还是有这样的问题

**Comment by airyland** [comment]
在pc非模拟器情况下确实会出现这样的情况，和xscroll的内部实现有关，由于vux针对的是移动端，因此这个可以暂时忽略。有空的时间我们再研究一下。

**Comment by w2819** [comment]
@airyland 请问这个问题修复了吗，我也遇到这个问题了，请告知一下版本

**Comment by airyland** [comment]
@327326724 版本用最新版本，另外，scroller 已经不维护了。
