### ISSUE TITLE
vux-tab 横竖屏切换后和对应容器错乱bug

### ISSUE THREAD

**Issue by docikaci** [airyland/vux#652]
![image](https://cloud.githubusercontent.com/assets/7788102/20036358/930f1584-a441-11e6-8551-d96db29e7fb6.png)

![image](https://cloud.githubusercontent.com/assets/7788102/20036361/9e98ae88-a441-11e6-95c1-7e58952318e8.png)

用chrome模拟可以复现，以官网demo为例，切换横竖屏，tab和内容就对应不上了。
手机上 iPhone 5 ios8.2  以官网demo为例，切换横竖屏，稳定复现

**Comment by airyland** [comment]
2.0版本测试已没有这个问题。
