### ISSUE TITLE
Cell中value slot和is-link共存会导致错位

### ISSUE THREAD

**Issue by dangyuluo** [airyland/vux#653]
### Version
0.1.3
### Android or iOS
All
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<group title="use slot for complexed content">
      <cell title="slot content" is-link>
        <div slot="value">
          <span style="color: green">Hi, I'm Vux.</span>
        </div>
      </cell>
    </group>
```

### Expected behavior and actual behavior.
应该是文字和右侧箭头平齐。
### Steps to reproduce the problem
<img width="387" alt="screen shot 2016-11-06 at 09 35 03" src="https://cloud.githubusercontent.com/assets/4816327/20038618/c639d328-a404-11e6-947e-822fff40a4d3.png">

**Comment by graysheeep** [comment]
目前不支持这种情况，如果想让字和箭头共存，用<Cell value="Hi, Im Vux" is-link></Cell>
