### ISSUE TITLE
上传组件

### ISSUE THREAD

**Issue by znau** [airyland/vux#654]
weui 里有个上传组件 
https://weui.io/#uploader   什么时候集成一个上传组件。

**Comment by Jeffliu** [comment]
这个特性的实现，会直接放到支持 vue2 的版本之后吗？

**Comment by zlab** [comment]
自己写

**Comment by airyland** [comment]
duplicate issue #682

**Comment by wxingheng** [comment]
@znau @Jeffliu 
一个完美的补充，包含完整的演示demo   [vux-uploads](https://github.com/wxingheng/vux-uploads)
