### ISSUE TITLE
集合vuex大型工程时出现的问题

### ISSUE THREAD

**Issue by ac51300696** [airyland/vux#657]
如何在其他action文件中引用this

**Comment by airyland** [comment]
理论上 Vux 不会影响你使用 Vuex。如果你遇到问题，可以上具体代码再 Reopen。

**Comment by ac51300696** [comment]
我看到的demo里面是这样的
load (uuid) {
      setTimeout(() => {
        this.$broadcast('pulldown:reset', uuid)
      }, 2000)
    }

然后我把这个method放到action里，再配合mutation里面添加更多数据可是在action里面不能使用 this.$broadcast('pulldown:reset', uuid)

具体代码：
components：
methods:mapActions([
        'load'
      ])
    ,
action：
export const load = ({ commit },indexlist) => {
  index.getArticle((indexlist) => {
    commit(types.ADD_TO_LIST, { indexlist : indexlist })
    
  },indexlist)
  this.$broadcast('pulldown:reset', indexlist)
  
}
重点就是就是this.$broadcast找不到，uuid是能传递过来的
