### ISSUE TITLE
vux结合vuex时出现的问题

### ISSUE THREAD

**Issue by ac51300696** [airyland/vux#658]
我看到的demo里面是这样的
load (uuid) {
setTimeout(() => {
this.$broadcast('pulldown:reset', uuid)
}, 2000)
}

然后我把这个method放到action里，再配合mutation里面添加更多数据，可是在action里面不能使用 this.$broadcast('pulldown:reset', uuid)

具体代码：
components：
methods:mapActions([
'load'
])
,
action：
export const load = ({ commit },indexlist) => {
index.getArticle((indexlist) => {
commit(types.ADD_TO_LIST, { indexlist : indexlist })

},indexlist)
this.$broadcast('pulldown:reset', indexlist)

}
重点就是就是this.$broadcast找不到，uuid是能传递过来的

**Comment by airyland** [comment]
vux2.0.0 废弃了broadcast方法以及uuid，因此不会再出现这个问题。
