### ISSUE TITLE
vue2.0的支持什么时候好 啊  上次说十一月十一号

### ISSUE THREAD

**Issue by KellerLong** [airyland/vux#660]
公司项目弄好友段时间了 (VUE2.0出来一周就开始用了....)组件目前都是自己封装的  效率较低 想引用第三方组件,  最终选择了vux  并计划11/11日引入(开始说最迟这个时间公布2.0的支持),  然而却发现vux 依然不支持2.0

**Comment by hc24** [comment]
追新是要付出代价滴，更何况是超前……
公司项目还是以稳妥为主。

**Comment by Caijt** [comment]
毕竟是单人的项目，受影响程序很大，哪天不维护了也是有可能的

**Comment by qcdys** [comment]
@KellerLong 
我用了mint-ui 一但vux2.0 出来后、 我会加班加点的给替换掉

**Comment by wg5945** [comment]
@qcdys 

mint-ui的效果和weui比还是差一点的，等等吧~~

**Comment by cenkai88** [comment]
@wg5945 确实，效果差而且实现很奇怪，看了一下swiper竟然不是用translate而是用display

**Comment by Caijt** [comment]
@qcdys mint里没有select控件，你怎么解决的

**Comment by foxgty** [comment]
mint sucks

**Comment by huangzhenxian** [comment]
好像好多人都是一样

**Comment by fuchao2012** [comment]
fuck mint-ui. 最基本的框架都搭建不起来。。。搞个 card 还得自己写。。。造轮子是痛苦低效的。

**Comment by Caijt** [comment]
每天来给点压力。。

**Comment by nextdooroldwang** [comment]
pc端用的饿了么的element-ui，用的是vue2.0的。马上要开始做移动端项目了，也是用vue2.希望能赶上用vux，关注很长时间了。加油加油

**Comment by huangzhenxian** [comment]
每天来给点压力。。

**Comment by tofuxb** [comment]
@nextdooroldwang 跟你一样pc也是用element-ui。。现在要开始移动端了，可惜vux跳票了

**Comment by huangzhenxian** [comment]
给了作者一杯小杯开发

**Comment by XieShangxu** [comment]
来问问作者目前啥进度，好有个心理准备啊

**Comment by BIGN0** [comment]
看来都很期待2.0啊

**Comment by haiyangJ** [comment]
期待支持2.0

**Comment by cenkai88** [comment]
各位急用的可以考虑自己改源码，我试着改了几个发现改来自用的话其实并不难。

**Comment by xinlc** [comment]
求支持2.0

**Comment by greedying** [comment]
自己改代码当然可以了，如果兄台改好了，记得pr一下，说不定作者采用了

**Comment by nicklv** [comment]
@cenkai88 可以把升级的项目开源吗？大家可以每人升级一两个组件，说不定一两个星期也就升级完了。

**Comment by iqiuye** [comment]
求支持2.0

**Comment by airyland** [comment]
抱歉啊各位，这两个多月事情太多，公司压力巨大，所以确实是没有精力更新，并非弃坑了。现在回来更新了，一定会在2017前发布 :grinning: 。

**Comment by NexusLee** [comment]
饿？现在有2.0的版本了吗

**Comment by cenkai88** [comment]
@nicklv 全改实在没时间，做了个彩色图标组件大家看看吧。https://github.com/cenkai88/vue-svg-icon

**Comment by lipandeng** [comment]
期待支持vue2.0版本，还有几天就2017年了

**Comment by iqiuye** [comment]
不会是农历吧~~

**Comment by neil-mao** [comment]
我来点个赞
