### ISSUE TITLE
selector组件在 iOS 的微信中选择无效的问题

### ISSUE THREAD

**Issue by hc24** [airyland/vux#661]
### iOS 微信中，对selector首条记录选取无效，如图
![image](https://cloud.githubusercontent.com/assets/9858863/20296220/85bb8638-ab44-11e6-8449-f5f44dd8a94a.png)

直接点击完成，数据“总经理”没有设置到调入部门框，如果滑动下面选择，再点完成，则可设置成功。目前安卓无此问题。

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
 <template v-if="item.type=='ORG'">
     <selector :title="item.label+':'" :options="orgOptions" :value.sync="item.value"></selector>
  </template>

//orgOptions是方法，获取的数据格式是按照官方文档[{key,value},{...}]的形式

```

**Comment by hc24** [comment]
官方demo中也存在这个问题，第一条点击省份，显示当前选取‘广东’，点击完成，省份依然显示为空

**Comment by brahmachen** [comment]
此问题在ios中依然存在，vux版本是最新版本
