### ISSUE TITLE
x-number没有双向绑定的效果

### ISSUE THREAD

**Issue by qq447665722** [airyland/vux#662]
### Version
![image](https://cloud.githubusercontent.com/assets/14967427/20341142/ce6a3a88-ac1f-11e6-9c78-51c05201bf78.png)

### Android or iOS
html5

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<template>
  <x-number name="listen" title="" :value="number" :min="0" @on-change="change"></x-number>
</template>

<script>
  import { XNumber } from 'vux'
  export default {
    data(){
      return {
        number: 10
      };
    },
    methods: {
      change (val) {
        console.log('change', this.number)
      },
    },
    components: {
      XNumber
    }
  }
</script>
```

### Expected behavior and actual behavior.
x-number如果做数据双向绑定?

### Steps to reproduce the problem
![image](https://cloud.githubusercontent.com/assets/14967427/20341186/0d4ba9e4-ac20-11e6-8ac8-29fe7bd32b89.png)
点击10次后
![image](https://cloud.githubusercontent.com/assets/14967427/20341194/1759c66e-ac20-11e6-8ba4-508d4b57505c.png)
没有双向绑定的效果

**Comment by seric705** [comment]
<x-number name="listen" title="" :value="number" :min="0" @on-change="change"></x-number>
中的":value"改成":value.sync"就可以了

**Comment by lichunqiang** [comment]
正如 @seric705 所说， 不过  `val` 已经是当前的值了。

**Comment by qq447665722** [comment]
谢谢各位
