### ISSUE TITLE
官网popup，ios环境下无法使用。

### ISSUE THREAD

**Issue by purewater2011** [airyland/vux#663]
官网示例。
在ios环境下，访问popup，弹出框也是灰色的。
其它环境（android,chrome）都是好用的。

**Comment by unclay** [comment]
弹出框的遮罩层就是透明灰，我这边ios是好的，是什么型号，什么浏览器

**Comment by yanghuayi** [comment]
这个问题我也用到过的，你的问题是不是popup弹出层在遮罩层下面的？？原因是因为滚动元素和mask遮罩层在同一级，vux框架默认把遮罩层放在body标签下的，你可以更改一下源码，把mask遮罩层放在popup同级下，这个问题就可以解决

**Comment by yanghuayi** [comment]
或者你滚动元素设置为body，html，不是body里面的元素，这样也可以解决问题，如果出现固定顶部这样，建议用第一种方法

**Comment by airyland** [comment]
我这边重现不了，麻烦补充下测试环境重开issue。

**Comment by Benbzhou** [comment]
+1

**Comment by Benbzhou** [comment]
我也遇到了 不过是因为自己操作的问题  	<div v-transfer-dom></div>包裹后解决 没包裹在ios就会出现popup弹出层在遮罩层下面

**Comment by Benbzhou** [comment]
我也遇到了 不过是因为自己操作的问题 v-transfer-dom div 

包裹后解决 没包裹在ios就会出现popup弹出层在遮罩层下面

**Comment by smltui** [comment]
在 ios环境下，遮罩层在弹窗之上，安卓和谷歌是没问题的。

**Comment by smltui** [comment]
![image](https://user-images.githubusercontent.com/46661898/61867130-1269c980-af09-11e9-9196-e2fdd535199c.png)
遮罩层在弹框之上，使用v-transfer-dom div ，依旧这样

**Comment by smltui** [comment]
![image](https://user-images.githubusercontent.com/46661898/61867231-4cd36680-af09-11e9-823d-d1732bb3bcdc.png)
这是弹窗组件

**Comment by Benbzhou** [comment]
https://doc.vux.li/zh-CN/directives/v-transfer-dom.html  你看下你引入没




------------------ 原始邮件 ------------------
发件人: "smltUI"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 晚上6:24
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "Benb周"<1132924449@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [airyland/vux] 官网popup，ios环境下无法使用。 (#663)





 这是弹窗组件

**Comment by smltui** [comment]
![image](https://user-images.githubusercontent.com/46661898/61867893-cc156a00-af0a-11e9-8b14-eff981ef8a84.png)
![image](https://user-images.githubusercontent.com/46661898/61867907-d8012c00-af0a-11e9-9542-e8f36017321f.png)
引入了

**Comment by Benbzhou** [comment]
就知道你引入方式 错了 我给了你 链接的啊  你看看




------------------ 原始邮件 ------------------
发件人: "smltUI"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 晚上6:35
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "Benb周"<1132924449@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [airyland/vux] 官网popup，ios环境下无法使用。 (#663)





 
 引入了

**Comment by smltui** [comment]
要全局引入吗，
![image](https://user-images.githubusercontent.com/46661898/61868563-367ada00-af0c-11e9-978d-74c7db7ee2db.png)，还是这个地方呢？大佬

**Comment by Benbzhou** [comment]
根据需求 多看官网  你现在ios  应该可以了






------------------ 原始邮件 ------------------
发件人: "smltUI"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 晚上6:45
收件人: "airyland/vux"<vux@noreply.github.com>;
抄送: "Benb周"<1132924449@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [airyland/vux] 官网popup，ios环境下无法使用。 (#663)




要全局引入吗，
 ，还是这个地方呢？大佬
