### ISSUE TITLE
使用scroller加载更多时加载成功后窗口长度没变，导致数据显示不全。

### ISSUE THREAD

**Issue by Ljiawen** [airyland/vux#671]
### Version
version": "0.1.3
### Android or iOS
not
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` 
<scroller lock-x scrollbar-y use-pullup use-pulldown  @pullup:loading="loadMore" @pulldown:loading="refresh" :pullup-status.sync="pullupStatus" v-ref:scroller>
      <div v-for="i in n" id="box2">
        <p >placeholder {{i}}</p>
      </div>
      <!--pullup slot-->
      <div slot="pullup" class="xs-plugin-pullup-container xs-plugin-pullup-up" style="position: absolute; width: 100%; height: 40px; bottom: -40px; text-align: center;">
        <span v-show="pullupStatus === 'default'"></span>
        <span class="pullup-arrow" v-show="pullupStatus === 'down' || pullupStatus === 'up'" :class="{'rotate': pullupStatus === 'up'}">↑</span>
        <span v-show="pullupStatus === 'loading'"><spinner type="ios-small"></spinner></span>
      </div>
    </scroller>
```

**Comment by Ljiawen** [comment]
[http://g.recordit.co/PMUQDenCyq.gif](url)

**Comment by Ljiawen** [comment]
详细查看动图
[http://g.recordit.co/PMUQDenCyq.gif](url)

**Comment by Ljiawen** [comment]
![image](https://cloud.githubusercontent.com/assets/14226516/20474239/aa48d76a-b000-11e6-8cd8-e5e968ad94ed.png)

**Comment by Ljiawen** [comment]
![pmuqdencyq](https://cloud.githubusercontent.com/assets/14226516/20474400/3afb7a92-b001-11e6-9757-983b5676a041.gif)

**Comment by lichunqiang** [comment]
在更新数据回调中手动reset下试

```
this.$nextTick(() => {
	this.$refs.scroller.reset({
	  top: 0
	})
})
```

**Comment by Ljiawen** [comment]
类似于这样吗
`loadMore (uuid) {
      setTimeout(() => {
        this.n += 5
        this.$nextTick(() => {
          this.$refs.scroller.reset()
          this.$broadcast('pullup:reset', uuid)
         
        })
      }, 2000)
    },`

**Comment by Ljiawen** [comment]
我的方法代码中已经加入了还是不行的
```
loadMore (uuid) {
     setTimeout(() => {
        this.n += 5
        this.$nextTick(() => {
          this.$refs.scroller.reset()
          this.$broadcast('pullup:reset', uuid)
        })
      }, 2000)
    },
```

**Comment by geoffreyzhao** [comment]
我的解决办法是给scroller设定高度，;height="value"   value值是动态计算出来的，document.documentElement.clientHeight - tabbar高度，可以在data中直接写；为防止height为0 ，也可以在ready生命周期中附上值

**Comment by airyland** [comment]
scroller是创建一个高度固定的容器，内部可滚动，因此高度除非你手动设置，否则不会变化。
