### ISSUE TITLE
vux什么时候可以做一个选择图片的组件

### ISSUE THREAD

**Issue by SunweiCalvin** [airyland/vux#682]
什么时候可以有一个选择图片的组件（类似微信朋友圈选图片），支持多选，带预览。

**Comment by leo-lai** [comment]
顶一下

**Comment by airyland** [comment]
WeUI有uploader组件，但是交互复杂，涉及到上传逻辑、预览、可能还要压缩，这个需求容易出bug，难以设计灵活接口，还可能是个无底洞，因此暂时不打算支持。

https://vux.li/demos/v2/#/component/uploader

**Comment by wxingheng** [comment]
一个完美的补充，包含完整的演示demo   [vux-uploads](https://github.com/wxingheng/vux-uploads)
