### ISSUE TITLE
panel组件提示Using v-if and v-for on the same element is not recommended - consider filtering the source Array instead.

### ISSUE THREAD

**Issue by Jesn** [airyland/vux#686]
提示： [Vue warn]: <a v-for="item in list" v-if="type === '1'">: Using v-if and v-for on the same element is not recommended - consider filtering the source Array instead. (found in component: <panel>)

我把官网的Demo复制过去也是提示这个，请问我是不是少加了什么

**Comment by leo-lai** [comment]
警告而已，已经解释很清楚了

**Comment by lichunqiang** [comment]
这个应该是使用了vue2.0之后才产生的warning吧

**Comment by airyland** [comment]
2.1目前没有这个警告，因此关闭了。
