### ISSUE TITLE
能出一个使用文档API吗？

### ISSUE THREAD

**Issue by mirrorpal** [airyland/vux#69]
自己用起来好费劲，demo也没有代码，各组件也没有具体说明。求出一版文档API。

**Comment by airyland** [comment]
正在努力编写中。
demo没有代码？

**Comment by mirrorpal** [comment]
https://vux.li/demo/  我的意思是demo都是集成的，看不到具体怎么调用，才学完vue表示直接看这么太难了。

**Comment by airyland** [comment]
@mirrorpal 在vux代码的 src/demos 里就是源码了，很易读的。

**Comment by mirrorpal** [comment]
哦，看到了，的确。没注意这个文件。谢谢

**Comment by airyland** [comment]
#71 文档相关的我先关掉，写完了在 #71 中更新。

**Comment by mirrorpal** [comment]
嗯。好的
