### ISSUE TITLE
mobile responsive fail 響應失敗

### ISSUE THREAD

**Issue by red010182** [airyland/vux#690]
===========更新問題==========

改用vue 1.0.28還是失敗

環境： 
OSX 10.11.6
Chrome: Version 54.0.2840.98 (64-bit)
vue 1.0.28
vux 0.1.3

```
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="./vux/dist/vux.css">  <!-- vux 0.1.3 -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js"></script>
</head>
<body>
<div id="demo">
  <group>
    <cell title="vue" value="cool"></cell>
  </group>
</div>

<script src="vux/dist/components/group/index.js"></script>
<script src="vux/dist/components/cell/index.js"></script>

<script>
// register components
Vue.component('group', vuxGroup)
Vue.component('cell', vuxCell)

new Vue({
  el: '#demo'
})
</script>

</body>
</html>
```
<img width="461" alt="screen shot 2016-12-09 at 1 05 43 am" src="https://cloud.githubusercontent.com/assets/2116935/21019583/03e793de-bdac-11e6-89de-e95e89985a28.png">

看來似乎不是vue 2.x版本問題，有誰知道原因嗎？

=============== 以下是原始問題 =================

vue 2.0.4

我按照[官方文件](https://vuxjs.gitbooks.io/vux/content/install/vue.html)安裝，也有設置

```
<style>
@import '~vux/dist/vux.css';
</style>
```

但是在chrome或是iPhone模擬器上，看到的畫面卻是

<img width="604" alt="screen shot 2016-12-08 at 1 17 17 pm" src="https://cloud.githubusercontent.com/assets/2116935/20998495/34cdb6d0-bd49-11e6-9d50-f10c6d2f0252.png">

這看起來是沒有responsive的。我如果把chrome控制台的「toggle device toolbar」(手機模式)打開，就會變成以上畫面，但如果把手機模式關閉，藉由調整瀏覽器視窗，將寬度縮到320，頁面會是正常有responsive的

<img width="389" alt="screen shot 2016-12-08 at 1 26 01 pm" src="https://cloud.githubusercontent.com/assets/2116935/20998589/e44182d6-bd49-11e6-8855-8f50c5ccd5bb.png">

CSS看起來似乎也有載入，例如下圖是圖一Cell的樣式
<img width="530" alt="screen shot 2016-12-08 at 1 27 26 pm" src="https://cloud.githubusercontent.com/assets/2116935/20998621/20aaafe0-bd4a-11e6-8f96-65b89a8a2ffc.png">

請問這樣正常嗎？

webpack.config.js設置
```
     {
        test: /vux.src.*?js$/,
        loader: 'babel'
      },
```

package.json 各種loader
```
"css-loader": "^0.25.0",
"file-loader": "^0.9.0",
"json-loader": "^0.5.4",
"less": "^2.7.1",
"less-loader": "^2.2.3",
"style-loader": "^0.13.1",
"vue-loader": "^9.7.0",
"vue-router": "^2.0.0",
"webpack": "^2.1.0-beta.25",
"babel-core": "^6.0.0",
"babel-loader": "^6.0.0",
"babel-plugin-component": "^0.6.0",
"babel-preset-es2015": "^6.0.0",
```

**Comment by wg5945** [comment]
not yet support Vue@2.0

**Comment by lh8725473** [comment]
not yet support Vue@2.0

**Comment by red010182** [comment]
@wg5945 @lh8725473 感謝回答，但似乎不是Vue@2.0問題，改用Vue 1.0.28一樣失敗，能幫我看一下嗎？我已更新問題。

**Comment by wg5945** [comment]
add

    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes">

**Comment by lichunqiang** [comment]
应该在header中加入下面的meta试试

```
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
```

**Comment by red010182** [comment]
@wg5945 @lichunqiang 搞定了！感謝兩位前輩！！謝謝
