### ISSUE TITLE
countup已被迁移到countup.js，依赖可以改过来了

### ISSUE THREAD

**Issue by Zenser** [airyland/vux#692]
### Expected behavior and actual behavior.
package.json和countup组件可以修改了，不然用不了
`countUp.min.js?397a:1Please adjust your project dependencies: CountUp is now maintained under "countup.js". The repo you are currently using under the npm package name "countup" is deprecated.`

**Comment by lichunqiang** [comment]
应该不会影响现在的使用, 待看看 从  1.6 升级到 1.7 有没有BC

**Comment by lichunqiang** [comment]
hi @Zenser Updated. Pls have a try~, if have any problem , pls let me known.

**Comment by Zenser** [comment]
@lichunqiang no problem, thanks~
