### ISSUE TITLE
scroller组件Horizontal方式时，能否根据上下滑动距离和左右滑动距离，判断是否页面整体上下或者scroller组件左右滑动

### ISSUE THREAD

**Issue by seric705** [airyland/vux#694]
Scroller组件，如何实现上下滑动距离大于左右滑动距离时，页面整体默认上下滚动；上下滑动距离小于左右滑动距离时，页面scroller组件左右滑动，页面上下不滑动

**Comment by ChristianYeap** [comment]
同感，我也遇到了这个棘手的问题。

**Comment by wg5945** [comment]
这个估计你要去 xscroll 提issues了 ^_^

[传送门](https://github.com/huxiaoqi567/xscroll/issues)

**Comment by seric705** [comment]
@ChristianYeap 在使用scroller组件时加上 :prevent-default="false"就可以了
分析：自己把vux-xscroller的代码研究了下，是scroller组件在touchstart时执行了e.preventDefault导致不能上下滑动，scroller有个参数prevent-default置false就可以不执行这个操作

**Comment by airyland** [comment]
这个判断的使用场景是什么？

**Comment by 736008081** [comment]
如果是垂直的Scroller嵌套水平的Scroller 水平的那个Scroller佳哥stop-propagation 如果是swiper或者其他的嵌套在垂直滚动里面 自己去v-on:touchstart v-on:touchend v-on:touchmove监听这三个事件 在调用stopScroller(event){event.stopPropagation()} 多看下源码 和自己分析下 原理就是阻止冒泡
