### ISSUE TITLE
使用previewer组件时，报组件import进来的两个css路径有问题

### ISSUE THREAD

**Issue by wqQudian** [airyland/vux#695]
'#'号部分是因为保密协议，和谐掉了，谢谢~
ERROR in ./~/photoswipe/dist/default-skin/default-skin.png
Module parse failed: /Users/####/fe/app/####/node_modules/photoswipe/dist/default-skin/default-skin.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)

**Comment by lichunqiang** [comment]
```
$ npm  list | grep url
| +-- postcss-normalize-url@3.0.7
| | +-- is-absolute-url@2.0.0
| | `-- normalize-url@1.8.0
| +-- encodeurl@1.0.1
| +-- parseurl@1.3.1
| | `-- url2@0.0.0
| | `-- relateurl@0.2.7
+-- url-loader@0.5.7
| | +-- url@0.10.3
```

是不是本地没有安装 `url-loader`

**Comment by wqQudian** [comment]
多谢！的确没有安装~

**Comment by wqQudian** [comment]
还有一个问题，使用swiper组件搭配swiper-item时，给swiper组件传入index，无法定位到index所指向的那一页，就好像index不起作用。看了下源码，感觉这一块的逻辑好像有点问题，但是也想不出合适的解决办法，还请多多指教！谢谢！ 另附一段引用的代码，如下
<swiper class="swiper" :auto="false" :show-dots="false" :index="2" height="100%">
	<template v-for="item in detail" v-if="detail&&detail[$index].photo.length">
		<swiper-item v-for="it in detail[$index].photo" track-by="$index" >
			<img :src="cdn+it" class="img-item">
		</swiper-item>	
	</template>
</swiper>

**Comment by airyland** [comment]
第二个问题在vux2.0.0解决了，请在元旦后升级。
