### ISSUE TITLE
有没有计划更新一下 WeUI 的控件样式？

### ISSUE THREAD

**Issue by langqixu** [airyland/vux#699]
WEUI 版本近期更新了蛮多版本，很多控件比如绿色线框按钮样式都有更新，控件也增加了不少，不知道有没有计划同步更新过来。

**Comment by airyland** [comment]
会在更新到vue2.x后同步过来。

**Comment by spiritelf** [comment]
大概什么时候啊？

**Comment by Yunfeng** [comment]
别着急。

**Comment by langqixu** [comment]
升级 WeUI 目前有相对确定的计划吗？方便我们产品制定计划，麻烦了。

**Comment by airyland** [comment]
新组件添加了form-preview, loadmore, grid，upload不做封装， 还有其他咩？

**Comment by airyland** [comment]
合并到 #724
