### ISSUE TITLE
slot="icon" 这个是怎么用的？

### ISSUE THREAD

**Issue by spiritelf** [airyland/vux#700]
#  `<span class="demo-icon" slot="icon" style="color:#F70968"> &#xe633;  </span> `

**Comment by spiritelf** [comment]
都没人关注啊

**Comment by greedying** [comment]
这个自己看文档吧

**Comment by spiritelf** [comment]
没看懂这个用法。有链接吗?

**Comment by greedying** [comment]
请先学习下vue





在 2016-12-19 14:28:28，"spiritelf" <notifications@github.com> 写道：


没看懂这个用法。有链接吗?

**Comment by vu-ji** [comment]
[`使用-Slot-分发内容`](https://cn.vuejs.org/v2/guide/components.html#使用-Slot-分发内容)

**Comment by spiritelf** [comment]
看过这个，这个不是用在自定义组件上吗？  用在html 元素span上是什么意思？  ？ 在哪里挂载？

**Comment by spiritelf** [comment]
home.vue 里的这一段
·
 <div class="center">
      <svg style="width:60px;height:60px;" version="1.1" id="图形" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="1024px" height="1024px" viewBox="0 0 1024 1024" enable-background="new 0 0 1024 1024" xml:space="preserve"><path class="svgpath" data-index="path_0" fill="#35495e" d="M512 816.64 51.2 985.6l460.8-947.2 460.8 947.2L512 816.64 512 816.64zM509.44 207.36 189.44 862.72l317.44-117.76L506.88 207.36 509.44 207.36zM509.44 207.36" /></svg>

      <h1 class="vux-title" style="display:none;">
        <span class="demo-icon" slot="icon" style="font-size:60px;color:#35495e;display: block;">&#xe637;</span>
      </h1>
      <p class="vux-notice">v{{version}}</p>
    </div>·

**Comment by airyland** [comment]
slot是组件内部提供给调用组件的人来自定义内容的插槽，详细参考 Vue 文档。
