### ISSUE TITLE
在使用swiper组件搭配swiper-item时，给swiper组件传入index，无法定位到index所指向的那一页

### ISSUE THREAD

**Issue by wqQudian** [airyland/vux#703]
您好，我还有一个问题，在使用swiper组件搭配swiper-item时，给swiper组件传入index，无法定位到index所指向的那一页，就好像index不起作用。看了下源码，感觉这一块的逻辑好像有点问题，但是也想不出合适的解决办法，还请多多指教！谢谢！ 另附一段引用的代码，如下
`<swiper class="swiper" :auto="false" :show-dots="false" :index="2" height="100%">
	<template v-for="item in detail" v-if="detail&&detail[$index].photo.length">
		<swiper-item v-for="it in detail[$index].photo" track-by="$index" >
			<img :src="cdn+it" class="img-item">
		</swiper-item>	
	</template>
</swiper>`

**Comment by ritsuyan** [comment]
同，好像:index没什么用

**Comment by ritsuyan** [comment]
好像swiper-item不行
老哥你解决了吗

**Comment by wqQudian** [comment]
@ritsuyan 没有解决，组件内监听了index的变化，无论一开始传进去的是几，最后都会被置为0，监听index的watch函数一直在触发

**Comment by ritsuyan** [comment]
@wqQudian  或许可以在ready里给它重置成我们想要的东西？？？

**Comment by airyland** [comment]
Fixed in v2.0.0
