### ISSUE TITLE
swiper动态切换数据的时候会出现错误，详细如下

### ISSUE THREAD

**Issue by zhangsamhong** [airyland/vux#709]
```html
<style scoped>
	
</style>

<template>
	<swiper :list="gallery" loop auto dots-position="center" :show-desc-mask="false" :aspect-ratio="480/480" dots-class="dots-my-orange" @touchstart.stop @touchend.stop></swiper>

	<button @click="replaceData">replace</button>
</template>

<script>
	import Swiper from 'vux/src/components/swiper'
	import SwiperItem from 'vux/src/components/swiper-item'

	export default{
		components: {
			Swiper,
			SwiperItem
		},
		data() {
			return {
				gallery:[
					{url:"javascript:",img:"http://qgshop.b0.upaiyun.com/2016/11/19/08/51/08/upload_5c9462e857fe02a61f646f4780982d2f.jpg"},
					{url:"javascript:",img:"http://qgshop.b0.upaiyun.com/2016/11/19/08/51/09/upload_9410a7ed11a3bb4df232940e4a70d909.jpg"},
					{url:"javascript:",img:"http://qgshop.b0.upaiyun.com/2016/11/19/09/50/54/upload_0ecb4b46d3b998be77536bc012ade862.jpg"}],
				rdata:[
					{url:"javascript:",img:"http://qgshop.b0.upaiyun.com/2016/11/16/03/24/55/upload_5c9462e857fe02a61f646f4780982d2f.jpg"},
					{url:"javascript:",img:"http://qgshop.b0.upaiyun.com/2016/11/16/03/24/55/upload_9410a7ed11a3bb4df232940e4a70d909.jpg"},
					{url:"javascript:",img:"http://qgshop.b0.upaiyun.com/2016/11/16/03/24/56/upload_5c9462e857fe02a61f646f4780982d2f.jpg"},
					{url:"javascript:",img:"http://qgshop.b0.upaiyun.com/2016/11/16/03/24/56/upload_9410a7ed11a3bb4df232940e4a70d909.jpg"},
					{url:"javascript:",img:"http://qgshop.b0.upaiyun.com/2016/11/16/03/24/56/upload_5c9462e857fe02a61f646f4780982d2f.jpg"}
				]
			}
		},
		methods: {
			replaceData() {
				this.gallery = this.rdata;
			}
		}
	}
</script>
```
当切换数据的时候会有如下错误信息，不知道如何解决这个问题，求赐教
vue.common.js:1344 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at remove (vue.common.js:1344)
    at vue.common.js:1188
    at applyTransition (vue.common.js:1216)
    at removeWithTransition (vue.common.js:1187)
    at Fragment.singleRemove [as remove] (vue.common.js:3935)
    at Directive.remove (vue.common.js:4442)
    at Directive.diff (vue.common.js:4255)
    at Directive.update (vue.common.js:4161)
    at VueComponent._update (vue.common.js:8501)
    at Watcher.run (vue.common.js:3447)
remove @ vue.common.js:1344
(anonymous) @ vue.common.js:1188
applyTransition @ vue.common.js:1216
removeWithTransition @ vue.common.js:1187
singleRemove @ vue.common.js:3935
remove @ vue.common.js:4442
diff @ vue.common.js:4255
update @ vue.common.js:4161
_update @ vue.common.js:8501
Watcher.run @ vue.common.js:3447
runBatcherQueue @ vue.common.js:3186
flushBatcherQueue @ vue.common.js:3156
nextTickHandler @ vue.common.js:447
vue.common.js:3416 Uncaught (in promise) Error: [vue] async stack trace
    at Watcher.update (vue.common.js:3416)
    at Dep.notify (vue.common.js:2118)
    at VueComponent.reactiveSetter [as list] (vue.common.js:2409)
    at vue.common.js:6338
    at vue.common.js:6307
    at withoutConversion (vue.common.js:2208)
    at processPropValue (vue.common.js:6306)
    at updateProp (vue.common.js:6337)
    at VueComponent.parentWatcher.parentWatcher.Watcher.twoWay (vue.common.js:6506)
    at Watcher.run (vue.common.js:3447)

**Comment by airyland** [comment]
vue1还是vue2?

**Comment by zhangsamhong** [comment]
vue1的

**Comment by yanghuayi** [comment]
同意遇到这个问题，好像是v-for循环重新渲染时候移除元素，找不到父级元素

**Comment by airyland** [comment]
@yanghuayi Vux@2.x ?
