### ISSUE TITLE
API文档正在努力编写中 :fire: 

### ISSUE THREAD

**Issue by airyland** [airyland/vux#71]
因为模块比较多，计划在两周内写完。 :fire:

**Comment by dongweizhao** [comment]
大神加油，我现在都是在看源码，期待API文档

**Comment by airyland** [comment]
@dongweizhao :smiley:

**Comment by erguotou520** [comment]
你好，最近一直在学习和使用vue，希望能帮上点忙。不知道文档在哪边制作？wiki？gh-page？还是新开仓库，希望能帮忙书写文档。另外关于playground也有一点想法，也希望能帮上忙。如有需要请联系

**Comment by erguotou520** [comment]
你好，最近一直在学习和使用vue，希望能帮上点忙。不知道文档在哪边制作？wiki？gh-page？还是新开仓库，希望能帮忙书写文档。另外关于playground也有一点想法，也希望能帮上忙。如有需要请联系

**Comment by airyland** [comment]
@erguotou520 playground 我完成了一个很简单的功能，主要用于根据代码把栗子嵌入文档。文档用gitbook ，我先写些基本的，下周直接放到Github协作。关于playground 的可以直接到playground的issue讨论讨论呀

**Comment by erguotou520** [comment]
@airyland 其实关于doc我更希望使用vue doc(目前好像还没有)来完成。这样不仅仅是一个项目可以用，vue的都可以用

**Comment by airyland** [comment]
@erguotou520 没了解过vue-doc，自动生成文档这个我也写过，提取文件的prop列表和类型自动生成，但是，如果prop的描述我想支持中英文就无解了，一些说明我也不能都写在代码里，会很杂。

**Comment by erguotou520** [comment]
@airyland 希望先给出文档和playground的仓库，我好帮忙

**Comment by githubxun** [comment]
太好了，不过话说能否先把写好的挂出来吗？可以应对一下

**Comment by airyland** [comment]
@githubxun 快了 周末基本的就写完了

**Comment by githubxun** [comment]
我表示、我是来吹文档的！

**Comment by airyland** [comment]
@githubxun :sweat_smile:

**Comment by githubxun** [comment]
@airyland 今天能一睹文档的芳容吗？

**Comment by airyland** [comment]
@githubxun 基本的大概可以写完

![image](https://cloud.githubusercontent.com/assets/559179/14408100/448d2158-ff19-11e5-9c21-ac1577319605.png)

**Comment by fundon** [comment]
@airyland 👍

**Comment by airyland** [comment]
Moved to #104
