### ISSUE TITLE
windows环境下报listen eacces 127.0.0.1:8080

### ISSUE THREAD

**Issue by KingST1230** [airyland/vux#717]
后台服务是tomcat，端口8080，启动后台后，再启动node，会报这个错误。改动：dev-server.js文件Line47行的appDev.listen(8080,......。网上找了下，也有人遇到过这个问题，但没找到解决方案。请问这个你们知道如何解决吗？万分感谢。

**Comment by simon82** [comment]
可以换个监听端口，使用命令：npm run dev -- --host localhost --port 8081

**Comment by KingST1230** [comment]
后台也换成8081吗？这样试过了，不行。单纯换前台的，无法监听到后台了。@simon82，你的环境是如何配置的？另外这和tomcat有关系吗？

**Comment by simon82** [comment]
前台服务和后台服务用不同的端口，前台，在html页面里面通过ajax调用后台的api。

**Comment by KingST1230** [comment]
@simon82，不要嫌我啰嗦哦，问下，这种方式下，后台设置允许前台服务端口访问后台端口吗？因为单纯的访问属于跨域了。

**Comment by KingST1230** [comment]
@simon82，万分感谢您，后台设置跨域访问后，前台可以访问了。感谢您的思路！！！感谢
