### ISSUE TITLE
你好，请问发布了支持vue2.0了吗？

### ISSUE THREAD

**Issue by wonghoman** [airyland/vux#718]
你好，请问发布了支持vue2.0了吗？

**Comment by simon82** [comment]
还没有吧，请参考：【草稿】vux@2.0 更新指南https://github.com/airyland/vux/issues/715

**Comment by a807460184** [comment]
暂时还没有，作者在努力更新中...

**Comment by iqiuye** [comment]
😑

**Comment by airyland** [comment]
代码是处理完了，在处理的主要是一直使我痛苦万分的文档编写。
