### ISSUE TITLE
用Cordova封装hybrid app的性能能接受吗？

### ISSUE THREAD

**Issue by xiaohui-zhangxh** [airyland/vux#723]
打算用vux框架给客户弄个商城类hybrid app，不知道适不适合？主要是怕弄个出来之后，用户体验很差就麻烦了。

各位朋友，如果有vue已经上线的app推荐下最好，我可以体验下。

**Comment by airyland** [comment]
没有封装过，理论上体验一般，也不会太差，毕竟也有不少 hybrid 项目(ionic)是使用 Angular的，而 Vue 并不比 Angular 性能差。
不过在 iOS 上应该会比较流畅，Android 不同机型体验差别可能挺大。

**Comment by hongliming** [comment]
有个叫车速拍的是用vue搞得app.

**Comment by huangzhenxian** [comment]
不差  不过我的项目是企业项目  不能给你看  安卓加 crosswalk 会更流程 但是 有所牺牲  看你取舍

**Comment by xiaohui-zhangxh** [comment]
非常感谢楼上三位兄弟，只要Android机用户体验能接受就好。@huangzhenxian，能不能分享下为性能而优化，遇到了哪些坑。比如为了优化顶部状态栏，是否有考虑用原生组件

**Comment by Sapphire2k** [comment]
android  目前刚踩坑，不了解cordova如何使用。。都是直接嵌入到app webview。。最大的难题是 安卓返回按钮 & 安卓过渡动画 CSS兼容性太差了

**Comment by huangzhenxian** [comment]
@xiaohui-zhangxh 性能优化 看什么场景吧 我的优化全部都是js调优   我没考虑原生的组件 ，不过cordova有一个微软开源的插件 用xml直接生成原生组件的 例如导航什么用原生的  细的我还没了解 其实我测试了用4.2安卓版本 加入 crosswalk 流畅程度也是蛮高的，还包括十几个插件还有推送插件什么在里面，不过好像有缺点 ，感觉比较费电 坑的话 第一次踩还是蛮多的 最好预备多点时间 但是部署完后  往后的开发就比较轻松了，而且目前有热更新静态资源的插件（这个我还在准备踩，最近没时间），更新的时候免去了ios这货的审核 （除非你要加入新的cordova插件才需要重新打包发布 ） ios审核会是一个坑  有些插件 你会不知道用了哪些模块  而app审核是需要提前说明的  得去看插件源码

**Comment by iflamed** [comment]
大家可以看看我们现在的APP，手办酱，目前的版本是用了vux的，android 和 iOS都是基于Cordova做的，我们自己也定制了部分Cordova插件。

发自 刘兵 的 iPhone

**Comment by xiaohui-zhangxh** [comment]
@iflamed 刚测试了下，iOS很流程，小米4速度也不错。请问场景切换没有动画效果，是为了优化速度吗？定制的插件能否分享一下？

@huangzhenxian 热更新很有用，可以随时更新页面显示样式。希望兼容性不会有啥问题

在此，对各位提供的经验分享，再次表示感谢

**Comment by iflamed** [comment]
@xiaohui-zhangxh  因为用了vue-router，在页面切换的时候dom 树其实也卸载了。加上切换动画效果之后，必然会先停顿一下，等dom树渲染完成然后才能执行切换效果。所以视觉感觉上其实还是有点卡顿的效果。所以我们就没有加这个效果，也没有去尝试过。当然加上这个切换效果应该也还是有优化的空间。更好的体验其实你可以参考一下framework7-vue。

我比较擅长PHP 开发，所以定制的插件基本也都是改改，修修BUG。可以看看fork 或者 star的一些cordova 相关的库。我们APP 里面最重要的还是android 图片选择器的定制，以及微博分享图片的修改。不过这俩都是基于别人的repo 做的修改。

最近会完全写一个cordova-huawei-push 的库，到时候可以完全开源出来。

这里给大家一点建议吧：
1. Cordova for ios 最好直接使用wkwebview
2. Cordova for android 可以直接使用crosswalkwebview，编译出来文件大点也没有多大关系
3. Android App 的推送，可以使用极光／个推+小米推送+华为推送
4. 热更新最好自己建立一个更新服务器，类似于code-push 的就可以。国内直接用code-push 是很不可靠的。(参考：https://github.com/lisong/code-push-server)
5. 更多的性能优化，其实还是在javascript 里面，然后尽量减少dom 树节点，图片最好使用background的方式显示
6. 一下子想不了多少，有问题可以随时@我，cordova 用好了，其实也还是不错的

**Comment by huangzhenxian** [comment]
@iflamed 感谢

**Comment by xiaohui-zhangxh** [comment]
@iflamed 非常感谢，你提供的这些提示非常有用。

**Comment by vFire** [comment]
@iflamed 
试了一下手办酱，体验不错啊，完全可以接受！
顺便再请教一下，下拉刷新如何用js触发，就是不是靠手拖拽，我看到手办酱的几个信息类栏目都用了~

**Comment by iflamed** [comment]
@vFire 下拉刷新，显示效果还是用的translate3D，触发方式依然是监控的scroll postion。具体你可以用浏览器的手机模式访问手办酱网站就明白了。

**Comment by cy920820** [comment]
@iflamed  你们app h5部分用的是vue去构建的？ 还有就是 app的 底部tab是h5部分还是原生的，以及顶部的页面标题栏，是用什么做的？ 刚接触cordova，想将vue打造的单页发布跨平台app，请指教

**Comment by iflamed** [comment]
@Cui-y app 的tab 和header 都是 vue 构建的。里面的一些涉及原生操作“图片选择器”就是用的原生的。主体界面都是vue，html 构建。

**Comment by cy920820** [comment]
> @Cui-y app 的tab 和header 都是 vue 构建的。里面的一些涉及原生操作“图片选择器”就是用的原生的。主体界面都是vue，html 构建。

老铁，很高兴您能回答，还有一个问题，你们的hybrid app 只用了cordova框架去构建么，其他的框架呢？比如 Ionic

**Comment by iflamed** [comment]
只用了Cordova，一部分原生库参考了ionic的选择。

发自 刘兵 的 iPhone

**Comment by cy920820** [comment]
> 只用了Cordova，一部分原生库参考了ionic的选择。 发自 刘兵 的 iPhone
> […](#)
> On Oct 17, 2018, at 4:40 PM, Cui Yang ***@***.***> wrote: @Cui-y app 的tab 和header 都是 vue 构建的。里面的一些涉及原生操作“图片选择器”就是用的原生的。主体界面都是vue，html 构建。 老铁，很高兴您能回答，还有一个问题，�你们的hybrid app 只用了cordova框架去构建么，其他的框架呢？比如 Ionic — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

老铁， 你们用到的比较方便的原生库能不能推荐几个 ，例如我发现你们的app里通过左滑来返回上级页面，类似这种的库，推荐一下吧，或者说哪里有类似的资源汇总，请告知，感谢！！

**Comment by iflamed** [comment]
@Cui-y 返回上级的操作没有用什么库，是前端自己js写的操作。 我们这边用到的一些cordova 插件你可以参考一下。

```xml
<?xml version="1.0" encoding="UTF-8"?>
    <plugin name="cordova-plugin-whitelist" spec="~1.2.2" />
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="cordova-plugin-code-push" spec="~1.8.2-beta" />
    <plugin name="cordova-plugin-camera" spec="~2.2.0" />
    <plugin name="cordova-plugin-console" spec="~1.0.3" />
    <plugin name="cordova-plugin-device" spec="~1.1.2" />
    <plugin name="cordova-universal-links-plugin" spec="~1.2.0" />
    <plugin name="cordova-plugin-customurlscheme" spec="~4.2.0">
        <variable name="URL_SCHEME" value="" />
        <variable name="ANDROID_SCHEME" value="" />
        <variable name="ANDROID_HOST" value="" />
        <variable name="ANDROID_PATHPREFIX" value="/" />
    </plugin>
    <plugin name="TalkingData" spec="https://github.com/TalkingData/TalkingData-Analytics-SDK-Cordova-Plugin.git" />
    <plugin name="jpush-phonegap-plugin" spec="~2.2.4">
        <variable name="API_KEY" value="" />
    </plugin>
    <plugin name="cordova-plugin-qqsdk" spec="~0.4.1">
        <variable name="QQ_APP_ID" value="" />
    </plugin>
    <plugin name="cordova-plugin-weibosdk" spec="~0.3.5">
        <variable name="WEIBO_APP_ID" value="" />
    </plugin>
    <plugin name="cordova-plugin-wechat" spec="~1.3.0">
        <variable name="WECHATAPPID" value="" />
    </plugin>
    <plugin name="cordova-plugin-imagepicker" spec="~1.1.0" />
    <plugin name="cordova-plugin-file-transfer" spec="~1.5.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="~1.5.0" />
    <plugin name="cordova-plugin-file" spec="~4.2.0" />
    <plugin name="cordova-plugin-actionsheet" spec="~2.3.1" />
    <plugin name="cordova-plugin-appavailability" spec="~0.4.2" />
    <plugin name="cordova-plugin-globalization" spec="~1.0.4" />
    <plugin name="cordova-plugin-apprate" spec="~1.2" />
    <plugin name="cordova-plugin-app-version" spec="~0.1.9" />
    <plugin name="mx.ferreyra.callnumber" spec="https://github.com/Rohfosho/CordovaCallNumberPlugin.git" />
    <plugin name="com.verso.cordova.clipboard" spec="https://github.com/VersoSolutions/CordovaClipboard" />
    <plugin name="cordova-plugin-safariviewcontroller" spec="~1.4.6" />
    <plugin name="com.darktalker.cordova.screenshot" spec="https://github.com/gitawego/cordova-screenshot.git" />
    <plugin name="cordova-plugin-x-socialsharing" spec="~5.1.3" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="~2.1.0">
        <variable name="XWALK_VERSION" value="21+" />
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
        <variable name="XWALK_MODE" value="embedded" />
        <variable name="XWALK_MULTIPLEAPK" value="true" />
    </plugin>
    <plugin name="cordova-save-image-gallery" spec="https://github.com/agomezmoron/cordova-save-image-gallery.git" />
    <plugin name="info.protonet.imageresizer" spec="https://github.com/protonet/cordova-plugin-image-resizer.git" />
    <plugin name="cordova-plugin-mipush" spec="https://github.com/iflamed/mipush-cordova-plugin.git">
        <variable name="PACKAGE_NAME" value="" />
        <variable name="MI_PUSH_APP_KEY" value="" />
        <variable name="MI_PUSH_APP_ID" value="" />
    </plugin>
    <plugin name="cordova-huawei-push" spec="~0.3.1">
        <variable name="APPID" value="" />
        <variable name="PACKAGENAME" value="" />
    </plugin>
    <plugin name="cordova-plugin-alipay-v2" spec="~0.0.3">
        <variable name="APP_ID" value="" />
    </plugin>
    <plugin name="cordova-plugin-alibaichuan">
        <variable name="APPKEY" value="" />
    </plugin>
    <plugin name="cordova-plugin-app-launcher" spec="https://github.com/nchutchind/cordova-plugin-app-launcher.git" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.1" />
</xml>
```

**Comment by cy920820** [comment]
> @Cui-y 返回上级的操作没有用什么库，是前端自己js写的操作。 我们这边用到的一些cordova 插件你可以参考一下。
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
>     <plugin name="cordova-plugin-whitelist" spec="~1.2.2" />
>     <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
>     <plugin name="cordova-plugin-code-push" spec="~1.8.2-beta" />
>     <plugin name="cordova-plugin-camera" spec="~2.2.0" />
>     <plugin name="cordova-plugin-console" spec="~1.0.3" />
>     <plugin name="cordova-plugin-device" spec="~1.1.2" />
>     <plugin name="cordova-universal-links-plugin" spec="~1.2.0" />
>     <plugin name="cordova-plugin-customurlscheme" spec="~4.2.0">
>         <variable name="URL_SCHEME" value="" />
>         <variable name="ANDROID_SCHEME" value="" />
>         <variable name="ANDROID_HOST" value="" />
>         <variable name="ANDROID_PATHPREFIX" value="/" />
>     </plugin>
>     <plugin name="TalkingData" spec="https://github.com/TalkingData/TalkingData-Analytics-SDK-Cordova-Plugin.git" />
>     <plugin name="jpush-phonegap-plugin" spec="~2.2.4">
>         <variable name="API_KEY" value="" />
>     </plugin>
>     <plugin name="cordova-plugin-qqsdk" spec="~0.4.1">
>         <variable name="QQ_APP_ID" value="" />
>     </plugin>
>     <plugin name="cordova-plugin-weibosdk" spec="~0.3.5">
>         <variable name="WEIBO_APP_ID" value="" />
>     </plugin>
>     <plugin name="cordova-plugin-wechat" spec="~1.3.0">
>         <variable name="WECHATAPPID" value="" />
>     </plugin>
>     <plugin name="cordova-plugin-imagepicker" spec="~1.1.0" />
>     <plugin name="cordova-plugin-file-transfer" spec="~1.5.1" />
>     <plugin name="cordova-plugin-inappbrowser" spec="~1.5.0" />
>     <plugin name="cordova-plugin-file" spec="~4.2.0" />
>     <plugin name="cordova-plugin-actionsheet" spec="~2.3.1" />
>     <plugin name="cordova-plugin-appavailability" spec="~0.4.2" />
>     <plugin name="cordova-plugin-globalization" spec="~1.0.4" />
>     <plugin name="cordova-plugin-apprate" spec="~1.2" />
>     <plugin name="cordova-plugin-app-version" spec="~0.1.9" />
>     <plugin name="mx.ferreyra.callnumber" spec="https://github.com/Rohfosho/CordovaCallNumberPlugin.git" />
>     <plugin name="com.verso.cordova.clipboard" spec="https://github.com/VersoSolutions/CordovaClipboard" />
>     <plugin name="cordova-plugin-safariviewcontroller" spec="~1.4.6" />
>     <plugin name="com.darktalker.cordova.screenshot" spec="https://github.com/gitawego/cordova-screenshot.git" />
>     <plugin name="cordova-plugin-x-socialsharing" spec="~5.1.3" />
>     <plugin name="cordova-plugin-crosswalk-webview" spec="~2.1.0">
>         <variable name="XWALK_VERSION" value="21+" />
>         <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
>         <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
>         <variable name="XWALK_MODE" value="embedded" />
>         <variable name="XWALK_MULTIPLEAPK" value="true" />
>     </plugin>
>     <plugin name="cordova-save-image-gallery" spec="https://github.com/agomezmoron/cordova-save-image-gallery.git" />
>     <plugin name="info.protonet.imageresizer" spec="https://github.com/protonet/cordova-plugin-image-resizer.git" />
>     <plugin name="cordova-plugin-mipush" spec="https://github.com/iflamed/mipush-cordova-plugin.git">
>         <variable name="PACKAGE_NAME" value="" />
>         <variable name="MI_PUSH_APP_KEY" value="" />
>         <variable name="MI_PUSH_APP_ID" value="" />
>     </plugin>
>     <plugin name="cordova-huawei-push" spec="~0.3.1">
>         <variable name="APPID" value="" />
>         <variable name="PACKAGENAME" value="" />
>     </plugin>
>     <plugin name="cordova-plugin-alipay-v2" spec="~0.0.3">
>         <variable name="APP_ID" value="" />
>     </plugin>
>     <plugin name="cordova-plugin-alibaichuan">
>         <variable name="APPKEY" value="" />
>     </plugin>
>     <plugin name="cordova-plugin-app-launcher" spec="https://github.com/nchutchind/cordova-plugin-app-launcher.git" />
>     <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
>     <plugin name="cordova-plugin-statusbar" spec="^2.4.1" />
> </xml>
> ```

老铁  有一个问题，你是怎么处理更新的， 是使用hot-code-push方案么，还是怎么样，这块哪一个更新机制体验比较好一点呢，你们是怎么做的呢，我看到的是 hot-code-push 这个插件已经不维护了

**Comment by iflamed** [comment]
客户端用的这个库：cordova-plugin-code-push，服务器端是基于开源代码自建的。

发自 刘兵 的 iPhone

**Comment by cy920820** [comment]
> 客户端用的这个库：cordova-plugin-code-push，服务器端是基于开源代码自建的。 发自 刘兵 的 iPhone
> […](#)
> On Nov 2, 2018, at 6:47 PM, Cui Yang ***@***.***> wrote: @Cui-y 返回上级的操作没有用什么库，是前端自己js写的操作。 我们这边用到的一些cordova 插件你可以参考一下。 <?xml version="1.0" encoding="UTF-8"?> <plugin name="cordova-plugin-whitelist" spec="~1.2.2" /> <plugin name="ionic-plugin-keyboard" spec="~2.2.1" /> <plugin name="cordova-plugin-code-push" spec="~1.8.2-beta" /> <plugin name="cordova-plugin-camera" spec="~2.2.0" /> <plugin name="cordova-plugin-console" spec="~1.0.3" /> <plugin name="cordova-plugin-device" spec="~1.1.2" /> <plugin name="cordova-universal-links-plugin" spec="~1.2.0" /> <plugin name="cordova-plugin-customurlscheme" spec="~4.2.0"> <variable name="URL_SCHEME" value="" /> <variable name="ANDROID_SCHEME" value="" /> <variable name="ANDROID_HOST" value="" /> <variable name="ANDROID_PATHPREFIX" value="/" /> </plugin> <plugin name="TalkingData" spec="https://github.com/TalkingData/TalkingData-Analytics-SDK-Cordova-Plugin.git" /> <plugin name="jpush-phonegap-plugin" spec="~2.2.4"> <variable name="API_KEY" value="" /> </plugin> <plugin name="cordova-plugin-qqsdk" spec="~0.4.1"> <variable name="QQ_APP_ID" value="" /> </plugin> <plugin name="cordova-plugin-weibosdk" spec="~0.3.5"> <variable name="WEIBO_APP_ID" value="" /> </plugin> <plugin name="cordova-plugin-wechat" spec="~1.3.0"> <variable name="WECHATAPPID" value="" /> </plugin> <plugin name="cordova-plugin-imagepicker" spec="~1.1.0" /> <plugin name="cordova-plugin-file-transfer" spec="~1.5.1" /> <plugin name="cordova-plugin-inappbrowser" spec="~1.5.0" /> <plugin name="cordova-plugin-file" spec="~4.2.0" /> <plugin name="cordova-plugin-actionsheet" spec="~2.3.1" /> <plugin name="cordova-plugin-appavailability" spec="~0.4.2" /> <plugin name="cordova-plugin-globalization" spec="~1.0.4" /> <plugin name="cordova-plugin-apprate" spec="~1.2" /> <plugin name="cordova-plugin-app-version" spec="~0.1.9" /> <plugin name="mx.ferreyra.callnumber" spec="https://github.com/Rohfosho/CordovaCallNumberPlugin.git" /> <plugin name="com.verso.cordova.clipboard" spec="https://github.com/VersoSolutions/CordovaClipboard" /> <plugin name="cordova-plugin-safariviewcontroller" spec="~1.4.6" /> <plugin name="com.darktalker.cordova.screenshot" spec="https://github.com/gitawego/cordova-screenshot.git" /> <plugin name="cordova-plugin-x-socialsharing" spec="~5.1.3" /> <plugin name="cordova-plugin-crosswalk-webview" spec="~2.1.0"> <variable name="XWALK_VERSION" value="21+" /> <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" /> <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" /> <variable name="XWALK_MODE" value="embedded" /> <variable name="XWALK_MULTIPLEAPK" value="true" /> </plugin> <plugin name="cordova-save-image-gallery" spec="https://github.com/agomezmoron/cordova-save-image-gallery.git" /> <plugin name="info.protonet.imageresizer" spec="https://github.com/protonet/cordova-plugin-image-resizer.git" /> <plugin name="cordova-plugin-mipush" spec="https://github.com/iflamed/mipush-cordova-plugin.git"> <variable name="PACKAGE_NAME" value="" /> <variable name="MI_PUSH_APP_KEY" value="" /> <variable name="MI_PUSH_APP_ID" value="" /> </plugin> <plugin name="cordova-huawei-push" spec="~0.3.1"> <variable name="APPID" value="" /> <variable name="PACKAGENAME" value="" /> </plugin> <plugin name="cordova-plugin-alipay-v2" spec="~0.0.3"> <variable name="APP_ID" value="" /> </plugin> <plugin name="cordova-plugin-alibaichuan"> <variable name="APPKEY" value="" /> </plugin> <plugin name="cordova-plugin-app-launcher" spec="https://github.com/nchutchind/cordova-plugin-app-launcher.git" /> <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" /> <plugin name="cordova-plugin-statusbar" spec="^2.4.1" /> </xml> 老铁 有一个问题，你是怎么处理更新的， 是使用hot-code-push方案么，还是怎么样，这块哪一个更新机制体验比较好一点呢，你们是怎么做的呢，我看到的是 hot-code-push 这个插件已经不维护了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

老铁 我主要是负责前端实现， 像您说的 自建更新服务器这个，是怎么一个原理呢，我应该如何跟后端人员去沟通这个事情呢

**Comment by iflamed** [comment]
https://github.com/lisong/code-push-server 你和你们后端工程师看看这个就可以了。

发自 刘兵 的 iPhone

**Comment by cy920820** [comment]
> https://github.com/lisong/code-push-server 你和你们后端工程师看看这个就可以了。 发自 刘兵 的 iPhone
> […](#)
> On Nov 2, 2018, at 6:47 PM, Cui Yang ***@***.***> wrote: @Cui-y 返回上级的操作没有用什么库，是前端自己js写的操作。 我们这边用到的一些cordova 插件你可以参考一下。 <?xml version="1.0" encoding="UTF-8"?> <plugin name="cordova-plugin-whitelist" spec="~1.2.2" /> <plugin name="ionic-plugin-keyboard" spec="~2.2.1" /> <plugin name="cordova-plugin-code-push" spec="~1.8.2-beta" /> <plugin name="cordova-plugin-camera" spec="~2.2.0" /> <plugin name="cordova-plugin-console" spec="~1.0.3" /> <plugin name="cordova-plugin-device" spec="~1.1.2" /> <plugin name="cordova-universal-links-plugin" spec="~1.2.0" /> <plugin name="cordova-plugin-customurlscheme" spec="~4.2.0"> <variable name="URL_SCHEME" value="" /> <variable name="ANDROID_SCHEME" value="" /> <variable name="ANDROID_HOST" value="" /> <variable name="ANDROID_PATHPREFIX" value="/" /> </plugin> <plugin name="TalkingData" spec="https://github.com/TalkingData/TalkingData-Analytics-SDK-Cordova-Plugin.git" /> <plugin name="jpush-phonegap-plugin" spec="~2.2.4"> <variable name="API_KEY" value="" /> </plugin> <plugin name="cordova-plugin-qqsdk" spec="~0.4.1"> <variable name="QQ_APP_ID" value="" /> </plugin> <plugin name="cordova-plugin-weibosdk" spec="~0.3.5"> <variable name="WEIBO_APP_ID" value="" /> </plugin> <plugin name="cordova-plugin-wechat" spec="~1.3.0"> <variable name="WECHATAPPID" value="" /> </plugin> <plugin name="cordova-plugin-imagepicker" spec="~1.1.0" /> <plugin name="cordova-plugin-file-transfer" spec="~1.5.1" /> <plugin name="cordova-plugin-inappbrowser" spec="~1.5.0" /> <plugin name="cordova-plugin-file" spec="~4.2.0" /> <plugin name="cordova-plugin-actionsheet" spec="~2.3.1" /> <plugin name="cordova-plugin-appavailability" spec="~0.4.2" /> <plugin name="cordova-plugin-globalization" spec="~1.0.4" /> <plugin name="cordova-plugin-apprate" spec="~1.2" /> <plugin name="cordova-plugin-app-version" spec="~0.1.9" /> <plugin name="mx.ferreyra.callnumber" spec="https://github.com/Rohfosho/CordovaCallNumberPlugin.git" /> <plugin name="com.verso.cordova.clipboard" spec="https://github.com/VersoSolutions/CordovaClipboard" /> <plugin name="cordova-plugin-safariviewcontroller" spec="~1.4.6" /> <plugin name="com.darktalker.cordova.screenshot" spec="https://github.com/gitawego/cordova-screenshot.git" /> <plugin name="cordova-plugin-x-socialsharing" spec="~5.1.3" /> <plugin name="cordova-plugin-crosswalk-webview" spec="~2.1.0"> <variable name="XWALK_VERSION" value="21+" /> <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" /> <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" /> <variable name="XWALK_MODE" value="embedded" /> <variable name="XWALK_MULTIPLEAPK" value="true" /> </plugin> <plugin name="cordova-save-image-gallery" spec="https://github.com/agomezmoron/cordova-save-image-gallery.git" /> <plugin name="info.protonet.imageresizer" spec="https://github.com/protonet/cordova-plugin-image-resizer.git" /> <plugin name="cordova-plugin-mipush" spec="https://github.com/iflamed/mipush-cordova-plugin.git"> <variable name="PACKAGE_NAME" value="" /> <variable name="MI_PUSH_APP_KEY" value="" /> <variable name="MI_PUSH_APP_ID" value="" /> </plugin> <plugin name="cordova-huawei-push" spec="~0.3.1"> <variable name="APPID" value="" /> <variable name="PACKAGENAME" value="" /> </plugin> <plugin name="cordova-plugin-alipay-v2" spec="~0.0.3"> <variable name="APP_ID" value="" /> </plugin> <plugin name="cordova-plugin-alibaichuan"> <variable name="APPKEY" value="" /> </plugin> <plugin name="cordova-plugin-app-launcher" spec="https://github.com/nchutchind/cordova-plugin-app-launcher.git" /> <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" /> <plugin name="cordova-plugin-statusbar" spec="^2.4.1" /> </xml> 老铁 有一个问题，你是怎么处理更新的， 是使用hot-code-push方案么，还是怎么样，这块哪一个更新机制体验比较好一点呢，你们是怎么做的呢，我看到的是 hot-code-push 这个插件已经不维护了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

 老铁 采用了code-push去更新，但是 发现并没有生效。 首先有两个问题 ：
1.  config.xml中 添加的 CodePushServerUrl 的value值 是 production 还是staging
2. 更新策略的代码可否共享一下， 加载的位置是在vue 根组件的生命周期中 监听deviceready 还是可以直接写在html 行内脚本中 
 谢谢了

**Comment by iflamed** [comment]
这个需要你自己看文档了，不记得太清楚


发自 刘兵 的 iPhone

**Comment by cy920820** [comment]
> 这个需要你自己看文档了，不记得太清楚 发自 刘兵 的 iPhone
> […](#)
> On Nov 4, 2018, at 7:26 PM, Cui Yang ***@***.***> wrote: https://github.com/lisong/code-push-server 你和你们后端工程师看看这个就可以了。 发自 刘兵 的 iPhone … On Nov 2, 2018, at 6:47 PM, Cui Yang ***@***.***> wrote: @Cui-y 返回上级的操作没有用什么库，是前端自己js写的操作。 我们这边用到的一些cordova 插件你可以参考一下。 老铁 有一个问题，你是怎么处理更新的， 是使用hot-code-push方案么，还是怎么样，这块哪一个更新机制体验比较好一点呢，你们是怎么做的呢，我看到的是 hot-code-push 这个插件已经不维护了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. 老铁 采用了code-push去更新，但是 发现并没有生效。 首先有两个问题 ： config.xml中 添加的 CodePushServerUrl 的value值 是 production 还是staging 更新策略的代码可否共享一下， 加载的位置是在vue 根组件的生命周期中 监听deviceready 还是可以直接写在html 行内脚本中 谢谢了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

老铁 @iflamed  最近发现cordova-plugin-code-push 这套方案不是很稳定啊，经常发生回滚，你们那边有遇到类似的情况吗，尤其是ios端，回滚之后就一直显示提示更新，然后进度条卡死，我翻了大概两天的资料，官方那边也表示无法查找回滚的具体原因

你们还在用这套更新方案么，还是说有更好的替代方案

**Comment by iflamed** [comment]
没有这个问题哟。我们这个运行了两年了吧，中间发布过很多次版本。

发自 刘兵 的 iPhone

**Comment by cy920820** [comment]
> 没有这个问题哟。我们这个运行了两年了吧，中间发布过很多次版本。 发自 刘兵 的 iPhone
> […](#)
> On Nov 8, 2018, at 2:44 PM, Cui Yang ***@***.***> wrote: 这个需要你自己看文档了，不记得太清楚 发自 刘兵 的 iPhone … On Nov 4, 2018, at 7:26 PM, Cui Yang ***@***.***> wrote: https://github.com/lisong/code-push-server 你和你们后端工程师看看这个就可以了。 发自 刘兵 的 iPhone … On Nov 2, 2018, at 6:47 PM, Cui Yang ***@***.***> wrote: @Cui-y 返回上级的操作没有用什么库，是前端自己js写的操作。 我们这边用到的一些cordova 插件你可以参考一下。 老铁 有一个问题，你是怎么处理更新的， 是使用hot-code-push方案么，还是怎么样，这块哪一个更新机制体验比较好一点呢，你们是怎么做的呢，我看到的是 hot-code-push 这个插件已经不维护了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. 老铁 采用了code-push去更新，但是 发现并没有生效。 首先有两个问题 ： config.xml中 添加的 CodePushServerUrl 的value值 是 production 还是staging 更新策略的代码可否共享一下， 加载的位置是在vue 根组件的生命周期中 监听deviceready 还是可以直接写在html 行内脚本中 谢谢了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. 老铁 最近发现cordova-plugin-code-push 这套方案不是很稳定啊，经常发生回滚，你们那边有遇到类似的情况吗，尤其是ios端，回滚之后就一直显示提示更新，然后进度条卡死，我翻了大概两天的资料，官方那边也表示无法查找回滚的具体原因 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

@iflamed  老铁
 cordova-android/ios 版本分别是多少的 ？
以及plugin-code-push的版本呢
我想试一下你的那些版本

**Comment by iflamed** [comment]
具体就不清楚了，两年前的项目了吧。你现在用起来应该比我之前的库好用才对。

发自 刘兵 的 iPhone

**Comment by owen4comes** [comment]
@iflamed 让我醍醐灌顶~感谢~
