### ISSUE TITLE
为何不升级weui版本？

### ISSUE THREAD

**Issue by OYsun** [airyland/vux#724]
看了vux2的源码，发现vue是升级到2.0，但是weui版本依然是0.4x的，为什么不升级weui的版呢？（https://github.com/airyland/vux/issues/699 ）我觉得升级weui到1.0后，可以优化很多代码，举个例子，比如cell组件中`weui-cell__bd`采用自适应布局，无需`weui-ell_primary`，这样你就不用对这个css类做相关计算属性了，也不用暴露一个`primary`属性接口

**Comment by airyland** [comment]
部分升级了。涉及太多。不能一次升级完。

**Comment by airyland** [comment]
升级完了 :sweat_smile: ，将在下周的 2.1.0 正式版本发布。
