### ISSUE TITLE
更新2.0后无法运行

### ISSUE THREAD

**Issue by wuxushun** [airyland/vux#725]
今天更新vux-2后   引入组件报错：

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module not found: Error: Cannot resolve module 'vux' in /Users/macmini/develop/news-reading/src
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 7:11-25

刚入门对webpack配置不是很了解，麻烦作者看一下问题~感激不尽

**Comment by airyland** [comment]
代码是怎么引入vux模块的？

**Comment by wuxushun** [comment]
import { Tab } from 'vux'  @airyland

**Comment by LaiXuechao** [comment]
跟我遇到得问题一样

**Comment by Blueeye1015** [comment]
@airyland vux-loader的版本是`^1.0.11`

稍微看了一下源码，感觉是vux-loader中获取`vuxMaps`的时候获取不到传了空对象回去。目前我本地直接粗暴的用path引用了vux中的`map.json`完成了构建 😂

**Comment by airyland** [comment]
@Blueeye1015 webpack 2 并没有完全测试过 :sweat: 
@wuxushun @LaiXuechao 你们都是webpack2？

**Comment by LaiXuechao** [comment]
我的是webpack 1.14.0 @airyland

**Comment by wuxushun** [comment]
"webpack": "^1.13.2", @airyland

**Comment by airyland** [comment]
这么判断很难找到问题，去除一些无关代码，打包发我邮箱我调试看看。

**Comment by jueduizone** [comment]
我看上面也是找不到`module`，我这边`install`成功后，但是提示`module`不存在
![image](https://cloud.githubusercontent.com/assets/16284115/21843456/fee31d06-d825-11e6-99c3-6a7bf2f49f4a.png)

**Comment by airyland** [comment]
建议直接用文档里的 airyland/vux2 来初始化新的项目。升级因为大家配置不一样会有比较复杂的情况出现，我会一一解决。

**Comment by jhyes** [comment]
import {XX , YY} from 'vux' 是可以的。
import {
  XX , 
YY } 
from 'vux'  --报错

**Comment by guntertien** [comment]
ERROR  Failed to compile with 2 errors
These dependencies were not found in node_modules:
* vux
* vux

Did you forget to run npm install --save for them?
> Listening at http://localhost:8080
每次都是这个错误

**Comment by jueduizone** [comment]
用airyland/vux2初始化项目后，可以正确运行，也可以打开默认的vux页面，console也无报错。
但是奇怪的是编辑页面，还是提示Module不存在，按照IDE的提示自动安装后，就不提示了，但是如：`from 'vux'`改成`from 'vux11'` 再改回来，还是提示不存在。
另外node_moules里的vux目录结构如下，跟我早前用的差别比较大，请确认：

<img width="190" alt="default" src="https://cloud.githubusercontent.com/assets/16284115/21872787/8abeafaa-d8a5-11e6-84f3-61a4d81d69c9.png">

**Comment by unclay** [comment]
@jueduizone 你用npm2吗

**Comment by jueduizone** [comment]
@unclay npm -v ==> 3.8.9

**Comment by jueduizone** [comment]
按照官网初始化了了工程，能正常编译运行，但App.vue里的less引入（默认的）报错如下，看着恶心，能解决么…
![image](https://cloud.githubusercontent.com/assets/16284115/21877985/f47fc946-d8c9-11e6-99ed-8cfa3fe4a09a.png)

**Comment by iqiuye** [comment]
我用tabbar的demo代码试了一下，也是报这个错，我不是用 airyland/vux2 来初始化新的项目，因为我不是做SPA

**Comment by janchengwang** [comment]
Uncaught Error: Cannot find module "vux",已经安装了vux,webpackmodule目录下也有vux目录，但是引入的时候就是报错。引入是按照文档引入的。

**Comment by airyland** [comment]
vux需要vux-loader配合使用。可以使用vux2模板。
如果cnpm安装后出错，使用npm试。
如果还不行，麻烦**打个包发我邮箱**。
