### ISSUE TITLE
vux 2

### ISSUE THREAD

**Issue by chengfei602** [airyland/vux#726]
Property or method "index" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <tabbar-item> at D:\vue2\project\node_modules\vux\src\components\tabbar\tabbar-item.vue)

**Comment by LaiXuechao** [comment]
我也遇到了這个问题

**Comment by airyland** [comment]
上下代码，可能我demo里忽略了什么使用情况。

**Comment by LaiXuechao** [comment]
![image](https://cloud.githubusercontent.com/assets/22734724/21840677/b1e37d54-d819-11e6-8ff0-ebd1b7716d09.png) @airyland

**Comment by chengfei602** [comment]
就是例子的代码
本来想加链接路由的，一直报这个错。

**Comment by airyland** [comment]
来来来，更新到 vux@2.0.4 和 vux-loader@1.0.15 再看看

**Comment by chengfei602** [comment]
更新后，不报错了

**Comment by LaiXuechao** [comment]
你加链接有效果吗 @chengfei602

**Comment by chengfei602** [comment]
链接现在还不起作用。再试

**Comment by murmurwoodz** [comment]
你们都是哪个版本，为什么我这里x-circle、x-switch等好几个组件引用目录都拼错了(已经更新 2.0.4)
address、address-china的代码也不存在
是index.js出错了么
而且css里找不到@tab-active-font-color  这个是哪里定义的 首页的主题样式表也没有啊

**Comment by airyland** [comment]
链接问题更新到 vux@2.0.5，要开始飙版本号了。

**Comment by chengfei602** [comment]
![image](https://cloud.githubusercontent.com/assets/14965023/21842921/cf545a7a-d823-11e6-96db-3d15555b6e82.png)
![image](https://cloud.githubusercontent.com/assets/14965023/21842952/06e3ae46-d824-11e6-9958-876db9780015.png)
tabbar-item.vue 中的 event :'on-item-click'  根本就没有起作用,走不到 go函数

**Comment by airyland** [comment]
2.0.5版本已经更新了。

**Comment by chengfei602** [comment]
选中 的状态没有，没更新2.0.4还有，选中字体变成绿色的，就链接不起作用。现在没有啦，还有就是show-dot 就没见起作用。

**Comment by LaiXuechao** [comment]
更新到2.0.5，链接可以用，但是show-dot和当前选中tabbar-item没有效果，还有文档這个地方是不是写错了 @airyland 
![image](https://cloud.githubusercontent.com/assets/22734724/21872107/8bca5024-d8a1-11e6-8597-afa96fa8ab63.png)
