### ISSUE TITLE
blue组件在ios下色彩失真

### ISSUE THREAD

**Issue by xiaochong44** [airyland/vux#727]
###  iOS
blue组件在IOS上显示不正常，色彩显示发白，安卓没有问题

**Comment by airyland** [comment]
blur?

**Comment by xiaochong44** [comment]
是的，报歉打错字了，这个问题一直存在。1.0版本就有

**Comment by xiaochong44** [comment]
![img_1930](https://cloud.githubusercontent.com/assets/25057951/21882653/732a3e9a-d8e6-11e6-9034-f1c253d33d85.png)

**Comment by airyland** [comment]
![image](https://cloud.githubusercontent.com/assets/559179/22172840/aab6cbc8-dfec-11e6-981d-a94022920c9d.png)

似乎只有你有这个问题，因为没有其他人反馈，所以我觉得这是个硬件问题，建议直接用 css3 的blur filter实现。
