### ISSUE TITLE
vux 2 tab css 错误

### ISSUE THREAD

**Issue by chengfei602** [airyland/vux#728]
client.js?7955:119 [HMR] bundle has errors:
./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-108bb1ca!./~/less-loader!./~/vux-loader/src/style-loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/vux/src/components/tab/tab.vue
Module build failed: variable @tab-active-font-color is undefined
 @ D:\vue2\project\node_modules\vux\src\components\tab\tab.vue (line 131, column 9)
 near lines:
   .vux-tab .vux-tab-item.vux-tab-selected {
     color: @tab-active-font-color
     border-bottom: 3px solid @tab-text-active-color;
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-108bb1ca!./~/less-loader!./~/vux-loader/src/style-loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/vux/src/components/tab/tab.vue 4:14-277 13:2-17:4 14:20-283

@tab-active-font-color这个没有

**Comment by foreverpw** [comment]
+1

**Comment by hajiwon1023** [comment]
+1

**Comment by greedying** [comment]
+1
