### ISSUE TITLE
上传组件和九宫格

### ISSUE THREAD

**Issue by LaiXuechao** [airyland/vux#729]
weui 里有个上传组件和九宫格，作者能不能集成进来？

**Comment by spiritelf** [comment]
就是啊，怎么没

**Comment by airyland** [comment]
上传组件其实不知道怎么封装，提供什么接口，涉及到上传逻辑比较复杂。可以给个建议。

**Comment by airyland** [comment]
上传交互逻辑复杂，决定不做封装，请自行引入样式使用。

https://vux.li/demos/v2/#/component/uploader
https://github.com/airyland/vux/blob/v2/src/demos/Uploader.vue

**Comment by wxingheng** [comment]
@airyland @spiritelf @jsonviewer  我整理了一个完整的上传组件（包含服务端）的演示
一个完美的补充，包含完整的演示demo   [vux-uploads](https://github.com/wxingheng/vux-uploads)
