### ISSUE TITLE
生成组件的umd文件,使用引入script的方式进行开发

### ISSUE THREAD

**Issue by MaxSherry** [airyland/vux#730]
在线等生成组件的umd文件,使用引入script的方式进行开发,希望尽快提供,谢谢

**Comment by airyland** [comment]
会尽快提供一个build脚本，但是不会生成umd文件在vux版本库里。

**Comment by airyland** [comment]
征求一下build的文件结构意见，下面哪种方便？

### 第一种文件夹形式

``` 
alert
  --- index.js
  --- index.css
confirm
  --- index.js
  --- index.css
```
对于父子组件， 有两个文件夹

## 第二文件形式

```
alert.js
alert.css
confirm.js
confirm.css
```

对于父子组件，有两个js文件，一个css文件。

**Comment by xxsser** [comment]
引入方式的话，我觉得第二种方便一点。

**Comment by MaxSherry** [comment]
建议使用第一种方式,一来延用1.0版本的形式,二来,对于项目用不到的组件,可以很快的从中剔除,有用的都以文件夹的形式存在,比较清晰明了

**Comment by MaxSherry** [comment]
![e5581d67-bb19-4b84-9eed-75343f1dbf4f](https://cloud.githubusercontent.com/assets/3919535/21920632/5acda780-d99d-11e6-895b-1f39364dbcea.jpg)


npm install
npm run build

执行报错

**Comment by airyland** [comment]
不要心急，还没完全搞定。今天完成。

**Comment by OpenUCD** [comment]
支持增加引用.js，.css来开发

**Comment by joneqian** [comment]
第一种吧，管理方便，引用也直观！！

**Comment by Hogg222** [comment]
第一种简洁明了 坐等更新

**Comment by airyland** [comment]
参考这里进行构建：

 https://github.com/airyland/vux/tree/v2/docs/zh-CN#组件-umd-文件
