### ISSUE TITLE
vux@2.0.5下的 x-input 设置右对齐后，错误提示icon 与input框没间距

### ISSUE THREAD

**Issue by YYmmlin** [airyland/vux#732]
![image](https://cloud.githubusercontent.com/assets/12744546/21879756/c7135ac0-d8d5-11e6-9826-dc386f35cfc9.png)

**Comment by YYmmlin** [comment]
还有个问题
![image](https://cloud.githubusercontent.com/assets/12744546/21879839/3f50e4e4-d8d6-11e6-9851-9f0262fe14dc.png)
查看了prop文件
![image](https://cloud.githubusercontent.com/assets/12744546/21879879/76b98774-d8d6-11e6-9844-a3d3eaacd01f.png)
确实没写customSlotFn、replaceTextList

**Comment by airyland** [comment]
你指的是这个间隙？

![image](https://cloud.githubusercontent.com/assets/559179/22143149/f3a0ee68-df33-11e6-98cf-314232608560.png)

**Comment by wengcd** [comment]
@airyland `x-input` 设置 `type="number"` 貌似没作用

**Comment by airyland** [comment]
@wengcd 检查是否为最新版本。

另外，不要在issue下提跟当前issue不相关的问题。

**Comment by wengcd** [comment]
@airyland 好吧…… 都是`x-input`我就提了，我`npm update`过了
