### ISSUE TITLE
vux 2项目最后运行的页面，#app消失不见了

### ISSUE THREAD

**Issue by greedying** [airyland/vux#737]
###描述
官方 airyland/vux2 生成的项目，run dev之后，#app 容器的id消失，由 
```html
<div id="app">
````
变成
```html
<div>
```
试验了下， 如果加一个class什么的，也会消失； 但是wget得到的index.html里面#app还是存在的，所以应该是js给去掉的。   

vue官方的project没这个问题。

### Version
2.0.5
### Android or iOS
微信浏览器、chrome都是，应该和系统没关系

### Your Codes 
``` html
npm install vue-cli -g 
vue init airyland/vux2 project
cd project
npm install
npm run dev
```
### Expected behavior and actual behavior.
因为这个会影响一些样式什么的， 我这里通过hack的方式解决了，但希望保留
我记得提过，刚才找了下没找到，神奇

**Comment by airyland** [comment]
你指的vue官方是？
我试了下确实id="app"是不见了。但是vux2模板里貌似没有做任何处理。

**Comment by airyland** [comment]
可以先这样解决，mount的id修改

``` js
new Vue({
  router,
  render: h => h(App)
}).$mount('#app-mount')
```

``` html
<div id="app-mount"></div>
```

修改 App.vue 

``` html
<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>
```

**Comment by greedying** [comment]
@airyland 
我指的是vue-cli上推荐的项目模板，https://github.com/vuejs-templates/webpack

```html
 npm install -g vue-cli
vue init webpack my-project
cd my-project
npm install
npm run dev
```
我也没有具体去看代码，只是推测是页面运行的时候，js给处理掉的。
不过这个问题也不大，我是因为使用vux之前版本的时候，用#app写了很多样式。其他人大概没太大影响

**Comment by greedying** [comment]
恩，其实我就是这么解决的

···html
    <div id="app">
      <div id="app-container"></div>
    </div>
```

```js
  new Vue({
     router: getRouter(Vue),
     render: h => h(App)
  }).$mount('#app-container')
```
```html
html, body, #app, #app>div {
  height: 100%;
  width: 100%;
}
```

**Comment by airyland** [comment]
目测这是vue `render` 函数的特性，会把用以mount的div直接替换掉。暂时只能按照上面说的解决。

**Comment by greedying** [comment]
应该不是。render函数，应该在所有vue2都这样，但是上面说了，vue提供的模板，#app是存在的

**Comment by airyland** [comment]
你试下加上vue-router试试看是不是挂载点就消失了呢。因为可以肯定的是vux2只是fork自官方加了一些依赖。

**Comment by greedying** [comment]
恩，好的，谢谢~ 我抽空试下

**Comment by greedying** [comment]
应该是这个问题。我还没去试，但是通过 在App.vue中写上#app，解决了这个问题。 就这样
