### ISSUE TITLE
import vux module not found error

### ISSUE THREAD

**Issue by iqiuye** [airyland/vux#744]
我用npm 4.0.5装的"vux": "^2.0.11"
但是`import { Tabbar, TabbarItem } from 'vux';`
这行代码在gulp的时候提示
`ERROR in ./~/.0.2.2@buble-loader?{"objectAssign":"Object.assign"}!./~/.10.0.2@vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Test.vue`
`Module not found: Error: Can't resolve 'vux' in '/Users/user/dirname/projectname/resources/assets/js/components'`
 `@ ./~/.0.2.2@buble-loader?{"objectAssign":"Object.assign"}!./~/.10.0.2@vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Test.vue 25:0-40`
 `@ ./resources/assets/js/components/Test.vue`
 `@ ./resources/assets/js/app.js`
不知道是怎么了，phpstorm也提示module is not installed.
但是我明明安装了，并且在package.json和node_modules目录也找到了vux

**Comment by airyland** [comment]
看到Test.vue 并没有经过 vux-loader。而新版需要和vux-loader使用。

```
var vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(originaWebpackConfig, {
plugins: [{
  name: 'vux-ui'
}]
})
```

**Comment by zscumt123** [comment]
你好，我也遇到了这个问题，而且我的webpack配置中也配置了vux-loader,
![image](https://cloud.githubusercontent.com/assets/17904663/21953157/a9b29752-da6a-11e6-8223-506ab483e07e.png)

**Comment by airyland** [comment]
@zscumt123 贴下你的import 代码，我看下是否vux-loader解析有问题。

**Comment by zscumt123** [comment]
我知道原因了，我用了“vux”，其实要用‘vux’,对吧！谢谢！

**Comment by airyland** [comment]
@zscumt123 果然是这个问题，我是按照eslint standard来的，我会更新vux-loader兼容双引号。

**Comment by zscumt123** [comment]
@airyland 嗯嗯，vue-cli里面的默认配置是单引号，我按照自己的习惯改了配置，改成了双引号，辛苦!

**Comment by zscumt123** [comment]
@airyland 你好，xInput组件怎么生成密码输入框呢？是加入type="password"属性吗？

**Comment by unclay** [comment]
@zscumt123 是的，是加入type="password"属性，目前有点问题，迟点更新

**Comment by Sioxas** [comment]
你好，我也遇到了这个问题，而且我的webpack配置中也配置了vux-loader，引用时也用的单引号
![import_vux](https://cloud.githubusercontent.com/assets/9740581/21960808/a21edc72-db31-11e6-8948-3e4108d536e5.png)
![vux-bug](https://cloud.githubusercontent.com/assets/9740581/21960809/a2415d6a-db31-11e6-995d-ddb3bc38412d.png)

**Comment by airyland** [comment]
@Sioxas 更新vux-loader到最新版。
