### ISSUE TITLE
vux-loader与babel配合使用

### ISSUE THREAD

**Issue by nannan9507** [airyland/vux#747]
在vux文档中，使用vux-loader下：
配置babel-loader以正确编译Vux的js源码（通过配置vux-loader实现）
plugins: [{
  name: 'vux-ui'
}]
可是就这样，在vue中import还是编译会报错通不过

以前还有个vuxLoader.getBabelLoader的方法，现在调用这个方法被移除了
请问现在vux有什么能经过babel去编译的最佳实践吗？

**Comment by airyland** [comment]
没有问题了？

**Comment by nannan9507** [comment]
谢谢，解决了。配置是正确的，我不小心在vue那儿把node_modules exclude 了，自己犯了个蠢
