### ISSUE TITLE
找不到vue-loader!vux-loader

### ISSUE THREAD

**Issue by lvchangqi** [airyland/vux#751]
![2017-01-15 20-58-41](https://cloud.githubusercontent.com/assets/15379292/21962673/89aea246-db66-11e6-8fb3-ce9f21ab1ccb.png)

**Comment by airyland** [comment]
看起来比较诡异，能否去掉业务代码，保留最简单的打包一份给我研究一下。

**Comment by junxiachen2** [comment]
我也遇到了这种情况，求解

**Comment by airyland** [comment]
麻烦更新 `vux-loader` 到`1.0.24`试试。
