### ISSUE TITLE
_vm.$t is not a function

### ISSUE THREAD

**Issue by yaqi2015** [airyland/vux#752]
![image](https://cloud.githubusercontent.com/assets/11505520/21962729/1ff1160c-db68-11e6-9ddc-29ef001d3ce1.png)

使用loading组件，项目报错，查看源码发现使用了$t，请问下这个怎么安装

**Comment by airyland** [comment]
是否配置 vux-loader 了？

**Comment by yaqi2015** [comment]
根据vue init airyland/vux2 project 初始化的项目
![image](https://cloud.githubusercontent.com/assets/11505520/21962830/c0b42236-db69-11e6-8d90-2ddb68b7fc6f.png)
dependence里面也有配置它

**Comment by yaqi2015** [comment]
是什么问题呢？我重新测试了还是一样的

**Comment by airyland** [comment]
是用cnpm安装？

**Comment by yaqi2015** [comment]
已经解决了，升级了下node，然后npm重新install就没有问题了。可能是cnpm或者node版本低导致

**Comment by janchengwang** [comment]
我也出现了，你是哪个版本的node

**Comment by lancerfox** [comment]
我也是 出现了这个问题

**Comment by airyland** [comment]
目测更新node版本，使用npm --registry=https://registry.npm.taobao.org 应该可以解决。可以贴下你们的node版本，cnpm版本，我尝试重现看一下。

**Comment by linsywu** [comment]
node版本v6.9.1下出现上述问题，使用loading也是报错：
![image](https://cloud.githubusercontent.com/assets/15061856/23737989/4437d64e-04d1-11e7-8130-bfe9fa171b6c.png)
代码如下：
`<template>
  <div class="container" id="list-container">
    <div class="list-group">
      <movie-item 
          v-for="movieObj in movieList"
          v-bind:movie="movieObj"></movie-item>
    </div>
    <loading :show="isShow"></loading>
  </div>
</template>

<script>
import { Loading } from 'vux'
export default {
  name:'index',
  components: {
    Loading 
  },
  data(){
    return {
      isShow:true,
      movieList:[]
    }
  },
  created:function(){
    var url = this.HOST + '/movie/in_theaters'
    this.$http.get(url).then(res => {
      this.movieList = res.data.subjects;
    },res => {
      console.info('调用失败');
    });
  }
}
</script>`

**Comment by airyland** [comment]
@linsywu 重装依赖。

**Comment by xiaobinwu** [comment]
重新安装依赖，使用npm install安装

**Comment by Z-wave** [comment]
npm太太太慢了

**Comment by wg5945** [comment]
尝试yarn

并且设置淘宝源

yarn config set registry https://registry.npm.taobao.org

**Comment by wonderjar** [comment]
这确实是个比较奇葩的问题。我出现的这个问题看起来是cnpm install其中有一些error，但没有影响install的最终结果还是success。我升级了node，node-gyp，又开VPN，再重新npm install，然后就好了。。。

**Comment by liuestc** [comment]
@linsywu 我也是这个问题，重装很多次依赖了，vux-loader也配置了，可还是不行？你解决了么，我的node版本是6.9.2

**Comment by linsywu** [comment]
@liuestc 我是翻墙后使用npm直接安装解决的

**Comment by yuemeimei** [comment]
@airyland 
![image](https://user-images.githubusercontent.com/23489614/28160713-a067db0a-67f3-11e7-96ca-35be7ba2da9d.png)

**Comment by yuemeimei** [comment]
@airyland 
![image](https://user-images.githubusercontent.com/23489614/28160894-228293a0-67f4-11e7-8e69-877dc1c3093f.png)

![image](https://user-images.githubusercontent.com/23489614/28160912-2b5de63c-67f4-11e7-9072-dfed82ec222d.png)
这是webpack 的配置  有误吗？
