### ISSUE TITLE
vux@2.0: XAddress 组件快速点击导致样式异常

### ISSUE THREAD

**Issue by phyng** [airyland/vux#756]
### Version
https://vux.li/#/zh-CN/demos/x-address 对应的版本

### Steps to reproduce the problem
问题地址: https://vux.li/#/zh-CN/demos/x-address
重现步骤: 重复快速双击选择地址的 cell，地址选择器就变成内联而不是弹出形式了
问题截图：
<img width="456" alt="jietu20170116-112713" src="https://cloud.githubusercontent.com/assets/5717770/21970257/8cec99d0-dbdf-11e6-9a33-003838ab75b2.png">

**Comment by xxsser** [comment]
@airyland  
此问题+1
不只是XAddress 应该是popup的问题，我使用popup重复点击也会触发这种bug

正常情况
![image](https://cloud.githubusercontent.com/assets/6001042/21979501/0be98902-dc1a-11e6-83b0-3d2daf3d63c3.png)


错误情况
![image](https://cloud.githubusercontent.com/assets/6001042/21979482/fa9bdd6c-dc19-11e6-83df-12cc0018dd84.png)

**Comment by airyland** [comment]
暂时没什么解决思路，欢迎pr。
