### ISSUE TITLE
vux is seeking for main contributors

### ISSUE THREAD

**Issue by airyland** [airyland/vux#76]
因为一个人时间精力有限，目前开发进度比较慢，测试也缺少时间。希望有2-3个人来一起协作开发。希望有UI细节强迫症，代码强迫症，有热情有耐心和有时间可以帮助测试完善项目。

初期开发以发PR的形式参与，在一定时间后将直接加入项目协作者名单，可以更加方便地维护项目。

发issue提(有效，有用，有趣)建议, 发PR改进项目即报名。

**Comment by lichunqiang** [comment]
:coffee:

**Comment by fundon** [comment]
+1

**Comment by erguotou520** [comment]
有几个问题
1.我是要在dev分支开发然后提交前执行`build`,`xbuild`,`test`?
2.因为开发工具为`WebStorm`一类，可以添加`.idea`的ignore么？
3.我运行`npm run dev`会报错，因为代码中有`ES6`的语法，如果不编译启动不了，如何解决？

**Comment by airyland** [comment]
@erguotou520 
1.不需要。如果没有写test的话不需要执行npm test
2.编辑器每个人可能不一样，可能要你自己添加一下
3.npm run dev 会报错肯定有问题，webpack已经把ES6编译成es2015了，你把错误帖出来看看

**Comment by erguotou520** [comment]
@airyland 
![image](https://cloud.githubusercontent.com/assets/7945757/14375094/38a75c08-fd90-11e5-9797-b761b22d0ecb.png)

**Comment by airyland** [comment]
@erguotou520 更新node版本至最新

**Comment by graysheeep** [comment]
报名！

**Comment by graysheeep** [comment]
@erguotou520 或者在packagejson的dev命令上加上--harmony 就是node --harmony build/dev-server.js

**Comment by susan-github** [comment]
组件不是分开导入，而是从vux import的话。XInput还有其他一些组件没办法用，是我打开方式有问题么？XButton又是可以的`
**js**
import { Group, Cell, XButton, XInput } from 'vux'
    export default {
        name: 'HomeView',
        components: {
            Group,
            Cell,
            XButton,
            XInput
        }
    }
**html**
<div>
        <group>
            <cell title="vue" value="cool"></cell>
            <x-button type="primary">primary</x-button>
        </group>
        <x-input title="message" placeholder="I'm placeholder"></x-input>
    </div>
**Error**
vue.common.js?e881:987 [Vue warn]: Unknown custom element: <x-input> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by airyland** [comment]
@susan-github 麻烦另开issue。这里不是issue讨论区。
