### ISSUE TITLE
vux 官方demo 下载后运行有点小问题

### ISSUE THREAD

**Issue by ChristianYeap** [airyland/vux#760]
npm install 之后提示 1  error , global_locales.yml is not found ?
确实也没有找到这个文件，求解...

**Comment by airyland** [comment]
这个已经补充完整了，git pull 一下。

**Comment by ChristianYeap** [comment]
直接下zip包的香菇蓝受

在 2017-01-16 17:39:28，"Airyland" <notifications@github.com> 写道：


这个已经补充完整了，git pull 一下。
