### ISSUE TITLE
引入loading组件报错

### ISSUE THREAD

**Issue by MaxSherry** [airyland/vux#761]
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
	<script src="/static/js/lib/vue/vue.js"></script>
	<script src="/static/js/lib/vue/vux/components/loading/index.min.js"></script>
</head>
<body>
<div id="app"></div>
<script>
	
</script>
</body>
</html>
```

![50ac85a7-e6c2-4822-8925-dc0d02a7544e](https://cloud.githubusercontent.com/assets/3919535/21980330/dd5b61b0-dc1d-11e6-973c-5cf4c261d4e7.jpg)

 无任何其它代码,直接引入后就报错

**Comment by airyland** [comment]
引入代码呢？

**Comment by MaxSherry** [comment]
不好意思些错了标题，是引入loading组件。
不过引入popup-picker组件，把代码中的loading换成popup-picke组件也报类似的错误。

**Comment by airyland** [comment]
本地完全正常。你可能打包有问题。先试下npm run dev 看有没有报错。

**Comment by MaxSherry** [comment]
npm run dev 执行没有报错.
我把项目下的node_modules目录删了,重新
npm install
npm run build-components

引入这个组件还是报错

**Comment by MaxSherry** [comment]
```
<template>
  <div class="weui_loading_toast" v-show="show">
    <div class="weui_mask_transparent"></div>
    <div class="weui_toast" :style="{ position: position }">
      <i class="weui-loading weui-icon_toast"></i>
      <p class="weui_toast_content">{{ text || 'loading' }}<slot></slot></p>
    </div>
  </div>
</template>
```

我把源码中的`{{ $t(text) || $t('loading') }}`改成`{{ text || 'loading' }}`,再重新npm run build-components,之后就没有报错了.
初步判断是这个`{{ $t(text) || $t('loading') }}`编译的时候语法没有通过,请帮忙解决一下,在线等,谢谢

**Comment by airyland** [comment]
进入node_modules/vux-loader/src/template-loader.js  在第59行到70行为变量替换逻辑，你console一下是否进了这个逻辑。

**Comment by MaxSherry** [comment]
是进入了这个逻辑,npm run build-components,的时候有输出打印`return b`之前打印也有输出

**Comment by airyland** [comment]
额，如果已经进了逻辑，应该是已经被正确替换掉了。

**Comment by MaxSherry** [comment]
编译后的src\components\loading\index.vue.vux.js 文件中显示并没有替换掉

**Comment by MaxSherry** [comment]
你那里引用loading的js文件没有报错? 好奇怪.....

**Comment by airyland** [comment]
这是我同样用命令构建出来的文件。

https://github.com/airyland/vux-dist

**Comment by MaxSherry** [comment]
郁闷了,你构建出来的文件我试了,没问题

**Comment by airyland** [comment]
要不你打个包给我吧。暂时判断不了问题。

**Comment by airyland** [comment]
找到问题了，Windows 上的问题。我调试一下。

**Comment by MaxSherry** [comment]
噢,好的,刚把打包文件发你邮箱里了,辛苦了,谢谢

**Comment by airyland** [comment]
git pull 下，更新vux-loader到 1.0.26 应该ok。

**Comment by MaxSherry** [comment]
谢谢,OK了

**Comment by yuemeimei** [comment]
我引用的comfirm  也是报$t 不是一个function
![image](https://user-images.githubusercontent.com/23489614/28158970-090d30f2-67ee-11e7-8da6-5eb8b0b281d3.png)
![image](https://user-images.githubusercontent.com/23489614/28159015-2667dc92-67ee-11e7-842e-ea7f5be4f185.png)

**Comment by yuemeimei** [comment]
![image](https://user-images.githubusercontent.com/23489614/28159204-d35239f2-67ee-11e7-854e-b11a8683234a.png)
这是我的 vux-loader  是不是下载错了

**Comment by airyland** [comment]
@yuemeimei 
问题不是这么提的。
看过文档了吗？vux-loader 在 webpack 里配置了吗？给个截图不给版本没有任何用处，请自行解决吧。

**Comment by yuemeimei** [comment]
@airyland 看过文档了，也根据你们上面所描述的把node_module删了，改用npm 下载，但是还是报$t的错，
![image](https://user-images.githubusercontent.com/23489614/28159915-28ac886a-67f1-11e7-925b-86f9db5364a7.png)在webpack 里面已经配置好了

**Comment by yuemeimei** [comment]
@airyland  这是html中的
![image](https://user-images.githubusercontent.com/23489614/28160090-b543e2f0-67f1-11e7-93b3-87bf9b3e1069.png)

**Comment by airyland** [comment]
@yuemeimei 你又没有使用 i18n，为什么要用 `$t('Show')` 这种代码？
