### ISSUE TITLE
_vm.$t is not a function 问题；

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [airyland/vux#762]
使用$t的组件都会出现这个错误，项目是使用vue-cli，然后后期加入vux框架的，然后组件配了一下webpack；在官方的vue-cli webpack.base.conf.js 
module.exports = { } 改成一个 var webpackConfig = {};
然后加入
`module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [{
    name: 'vux-ui'
  }]
})`
代码？
其他组件可以使用，但是用到带$t的组件就报错；

**Comment by airyland** [comment]
如果vux正确配置是不会出现这个问题的。可以去除各种业务代码打个包给我看看，这样能快速解决。

**Comment by LIANGWEIBIAO** [comment]
代码地址：
https://github.com/LIANGWEIBIAO/lxjjj
然后打开
http://localhost:8080/module/designer.html#/
或者
http://localhost:8080/module/load.html

**Comment by airyland** [comment]
你并没有使用i18n相关的库，因此不存在$t函数。

`:title="$t('中国')"`

=>

`title="中国"`

https://github.com/LIANGWEIBIAO/lxjjj/blob/master/src/module/designer/Selectstyle.vue#L9

**Comment by LIANGWEIBIAO** [comment]
`<tab-item  @click="showSwiper" class="vux-center"  v-for="item in list2" >{{item}}<i class="icon iconfont icon-daosanjiao"></i></tab-item>  `
给tab-item 标签添加事件没有效果，给其他像swiper标签添加就有效果

**Comment by airyland** [comment]
@click.native

**Comment by huangzhenxian** [comment]
cnpm 背锅   用npm
