### ISSUE TITLE
scroller组件内容和滚动条不同步的问题

### ISSUE THREAD

**Issue by zscumt123** [airyland/vux#765]
![image](https://cloud.githubusercontent.com/assets/17904663/22010247/02029cf4-dcc3-11e6-80e8-11a4217757fb.png)

参照官网的demo写的，文档底部已经没有内容了，但是滚动条才到一半，需要在滚动好久才能到底部，这个应该怎么解决

**Comment by airyland** [comment]
贴个完整代码。
