### ISSUE TITLE
vux2 版本号2.0.15， Scroller组件的下拉刷新，设置pulldown完成不起作用，两种方式都试过。

### ISSUE THREAD

**Issue by chengfei602** [airyland/vux#766]
文档说明：pulldown和pullup 调用完成一样
![image](https://cloud.githubusercontent.com/assets/14965023/22010263/1131549a-dcc3-11e6-9f4c-2fc933d33730.png)

代码
![image](https://cloud.githubusercontent.com/assets/14965023/22010316/5d0cfb30-dcc3-11e6-82cd-b2113b1f6d1d.png)
![image](https://cloud.githubusercontent.com/assets/14965023/22010317/5d349884-dcc3-11e6-9afa-b46dea372772.png)
效果
![image](https://cloud.githubusercontent.com/assets/14965023/22010325/6e72c652-dcc3-11e6-9d6d-21d11011cc1d.png)
一直是这样，代码里两种方式都调用还是不行。

**Comment by airyland** [comment]
你的getData是异步的吧

**Comment by chengfei602** [comment]
getData是异步的，原则是在getData的回调中，调用this.status.pulldownStatus = 'default'或者this.$refs.scroller.donePulldown()完成。

现在是直接屏蔽掉getData方法，不加载数据，调用this.status.pulldownStatus = 'default'或者this.$refs.scroller.donePulldown()完成也是不成功的。一直在正在加载数据。。

**Comment by airyland** [comment]
上个文字版代码吧。

**Comment by airyland** [comment]
参照demo代码： https://github.com/airyland/vux/blob/v2/src/demos/Pulldown.vue
如果还不行，上完整的文字代码。事实上我怀疑你this指向不对。
