### ISSUE TITLE
version:"2.0.15"  引用weui.less 提示weui_grid路径错误

### ISSUE THREAD

**Issue by maoqinglin** [airyland/vux#768]
version:"2.0.15"   直接引用weui.less 报错

weui.less 第38行
// grid
@import "./widget/weui_grid/weui_grid";  这个使用的下滑线，

而widget目录下使用的是weui-grid里写的是-（中横下）；
请作者核对下，是不是有这个问题，谢谢

**Comment by airyland** [comment]
感谢反馈，因为逐步升级到weui新版，路径也改了，但是一般是用不到这个文件的，所以忽略了。在v2.1.0-rc.4修复了。
