### ISSUE TITLE
使用cnpm install，项目报vue.common.js?caed:2225 Uncaught TypeError: _vm.$t is not a function(…)

### ISSUE THREAD

**Issue by yaqi2015** [airyland/vux#771]
hello，发现使用cnpm install安装的依赖，项目启动成功，但是引入loading组件就会报错，使用npm就没有这个问题。这个能解决么，npm install 非常慢

**Comment by unclay** [comment]
这个跟vux没啥关系，不过你启动不了具体是什么呢，cnpm install安装是否报错了？

**Comment by murmurwoodz** [comment]
你需要--registry=https://registry.npm.taobao.org
普通npm也可以挂

**Comment by AngusLean** [comment]
搜搜 cnpm

**Comment by yaqi2015** [comment]
@murmurwoodz 都知道cnpm了，肯定registry了。而且不引入loading或者某些组件是没有问题的。$t我看到loading组件源码里面调用了。

**Comment by huangzhenxian** [comment]
用vue-cli 搭建的？  cnpm install会报错的  我是翻墙 用npm install才行的

**Comment by yaqi2015** [comment]
@huangzhenxian 是的，用npm install没有问题的，在家npm install太慢，然后改用的cnpm 然后项目就会报错。你用的哪个翻墙工具？

**Comment by huangzhenxian** [comment]
@yaqi2015  用Green  收费的 也不怎么好用 有很多翻墙免费的 只是嫌麻烦

**Comment by yaqi2015** [comment]
@huangzhenxian o

**Comment by airyland** [comment]
参考 @murmurwoodz 更新registry的方法。cnpm会导致出问题，但是本地重现不了所以具体还不清楚是什么问题。方便的话帖下node版本，cnpm版本，我尝试重现下看下是啥问题。
