### ISSUE TITLE
this.$vux弹窗插件形式怎么调用不了

### ISSUE THREAD

**Issue by iqiuye** [airyland/vux#773]
插件形式调用toast，alert..的时候
`this.$vux.toast.show`
`this.$vux.alert.show`
this.$vux显示为 undefined要怎么弄?
我用的umd

**Comment by yaqi2015** [comment]
你灭有import AlertPlugin插件吧

**Comment by iqiuye** [comment]
@yaqi2015 我用的umd方式
`Vue.component('toast', vuxToast)`

**Comment by yaqi2015** [comment]
![image](https://cloud.githubusercontent.com/assets/11505520/22052312/66a2f26e-dd84-11e6-9c5c-083edbb9beee.png)

**Comment by iqiuye** [comment]
@yaqi2015 大哥啦...我是用umd方式，和你那种不同

**Comment by lichunqiang** [comment]
应该是 `Vue.use(AlertPlugin)` 吧

**Comment by iqiuye** [comment]
我详细描述了一下，我使用script方式出现的问题#780
