### ISSUE TITLE
vux并不适配低分辨率的手机，比如华为分辨率720X1280

### ISSUE THREAD

**Issue by sallyFishKun** [airyland/vux#775]
**vux并不适配低分辨率的手机，比如华为720X1280，**
###这个问题能否解决？
### "vux": "^2.0.2",
### Android or iOS
Android  iOS都存在
> For Android issues, please specify the brand, model and browser
### 安卓 HUAWEI TAG-TL00
 ###HUAWEI自带浏览器。版本10.2.0108
### Your Codes 
不适配1
![img_20170118_112132 jpg](https://cloud.githubusercontent.com/assets/22462221/22050187/9af3f33a-dd73-11e6-9ced-175a44e4236e.JPG)
正确对比图

![img_20170118_112343 jpg](https://cloud.githubusercontent.com/assets/22462221/22050317/c9834678-dd74-11e6-9841-0097c83625ea.JPG)

不适配2
![img_20170118_112112 jpg](https://cloud.githubusercontent.com/assets/22462221/22050212/d154c846-dd73-11e6-9242-f48c4c5a8d1f.JPG)
正确对比图
![img_20170118_112302 jpg](https://cloud.githubusercontent.com/assets/22462221/22050222/e3882dd2-dd73-11e6-9e1b-54024dafb064.JPG)

不适配的组件目前有  Search, Card, Cell,Tab,TabItem,Sticky,等。或者有可能全部都不行

``` html
<!--put your code here-->
```

### Expected behavior and actual behavior.
`希望能解决这个问题。
### Steps to reproduce the problem

**Comment by lichunqiang** [comment]
是说使用内置浏览器，因为是基于weui的，估计会有兼容问题。在微信浏览器里是不是正常的？

**Comment by sallyFishKun** [comment]
是的。苹果5s不管是微信浏览器还是内置浏览器都有问题。

**Comment by airyland** [comment]
将autoprefix的设置从 `last 2 versions` => `last 7 versions`
