### ISSUE TITLE
scroller 的 pullup 怎么触发？ @pullup:loading="changeList" 这样子触发不到

### ISSUE THREAD

**Issue by jank2014** [airyland/vux#779]
<scroller lock-x scrollbar-y :height="swiperHeight" ref="scroller2" :use-pullup="true" @pullup:loading="changeList">
            
 </scroller>

**Comment by lichunqiang** [comment]
新版改成 了 `on-pullup-loading`

**Comment by jank2014** [comment]
刚刚看了源码 谢谢了

**Comment by lichunqiang** [comment]
Closed...
