### ISSUE TITLE
grid-item, label问题

### ISSUE THREAD

**Issue by LaiXuechao** [airyland/vux#781]
![image](https://cloud.githubusercontent.com/assets/22734724/22091529/2ef6ad5c-de32-11e6-88ed-c6e72e28b957.png)

如果在grid-item上不设置label prop,只添加label slot 无法显示label，看了下源码是不是v-if="label"的问题？
![image](https://cloud.githubusercontent.com/assets/22734724/22091557/6bfc86c2-de32-11e6-9367-48b2175d368f.png)

还有能不能在grid-item上增加event: on-item-click

**Comment by airyland** [comment]
Done in 2.0.17

**Comment by LaiXuechao** [comment]
grid-item文档中没有增加events: on-item-click @airyland

**Comment by airyland** [comment]
欢迎直接PR。文档位于每个组件目录的metas.yml里。
