### ISSUE TITLE
x-input，popup-picker，对齐问题

### ISSUE THREAD

**Issue by LaiXuechao** [airyland/vux#782]
![image](https://cloud.githubusercontent.com/assets/22734724/22091725/536190fc-de33-11e6-86d5-82aac7fc4143.png)

1.x-input的title值字数不一致时，value值会不对齐。
2.popup-picker的选中值文字能不能设置左对齐、右对齐。
3.x-input的type设置成password，还是显示数字，不显示圆点或星号

**Comment by airyland** [comment]
1和3在最新版本是支持的。

一直没有人关注到group分组的对齐功能。。

``` js
<group label-width="4em" label-margin-right="2em" label-align=“right”>
```

**Comment by airyland** [comment]
https://vux.li/demos/v2/#/component/group

![image](https://cloud.githubusercontent.com/assets/559179/22105412/d17dce7e-de7e-11e6-939b-c880f525b2ce.png)

第二点更新到 v2.1.0-rc.3
