### ISSUE TITLE
在基于nuxt的应用中vux不能通过import使用

### ISSUE THREAD

**Issue by xpcode** [airyland/vux#785]
我想基于Nuxt搭建一个同构应用，并且使用Vux，过程中碰到 Not find Module 'vux'，如果这两个能很好的结合起来，简直是神器啊

Nuxt: https://cn.nuxtjs.org/

**Comment by airyland** [comment]
暂时不能，vux是调用时构建，理论上需要做一个转换器。等2.0稳定后再研究。

**Comment by leftjs** [comment]
强烈建议适配nuxt v1.0，nuxt 1.0将整合pwa 等等... 好想兼得

**Comment by yonggao** [comment]
+1

**Comment by airyland** [comment]
最近研究一下 😄

**Comment by airyland** [comment]
我测试了下，并没有出现` Not find Module 'vux'`的错误，只有$t函数的报错。

**Comment by leftjs** [comment]
能否贴上代码参考参考

**Comment by airyland** [comment]
单个路径引入可以，import 多个就不行了，要完全适配nuxt还有不少东西要做，而且并没有看到nuxt有预处理的hook。:sweat:

**Comment by airyland** [comment]
Move to #1346
