### ISSUE TITLE
如果同时使用popup和actionsheet组件，在iphone手机上会显示异常

### ISSUE THREAD

**Issue by lizhengjun1982** [airyland/vux#787]
我做了一个应用页面，类似微信朋友圈，同时使用了popup和actionsheet组件，popup作为点评使用，actionsheet作为评论内容的上下文菜单，在android手机上测试没有问题，在iphone手机上就显示异常，在个别android手机上也异常。

iphone手机的异常现象时，点击点评，本来只有popup里的内容显示出来，结果actionsheet里的内容也显示了，而且还挡在了前面。

在android小米手机里的异常现象是，第一次点击点评操作OK，第二次再点评时，发现屏幕整个被蒙住了，也看不到点评框里的内容。

实在没有办法，找不到原因，最后想到把actionsheet给去掉，发现竟然都好了。

**Comment by airyland** [comment]
iPhone哪个机型， 小米哪个机型。为了方便重现麻烦贴个代码。
