### ISSUE TITLE
我建议不要修改组件的名字，要不之前集成的都会有问题

### ISSUE THREAD

**Issue by fanly** [airyland/vux#79]
### Your Codes 

``` html
<!--put your code here-->
```

**Comment by airyland** [comment]
现在还没发布正式版，改名字也不是想改就改，在会出问题的情况下改名避免可能出现的问题应该可以理解吧，希望在正式版本前能形成规范。

**Comment by fundon** [comment]
话说本地开发 不是指定了 版本号，除非是直接用 master

**Comment by airyland** [comment]
@fundon 看不明白什么意思。本地开发？从npm安装下来就是最新版本了，直接用master又是什么意思？
