### ISSUE TITLE
如何在项目中使用vux？不是用npm install vux吗？不能这样用？

### ISSUE THREAD

**Issue by wonghoman** [airyland/vux#790]
如何在项目中使用vux？不是用npm install vux吗？不能这样用？

**Comment by airyland** [comment]
看文档再提问。不能用也得上报错信息。

**Comment by wonghoman** [comment]
@airyland Module not found: Error: Cannot resolve module 'vux' in D:\xxxx\src\views
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!

**Comment by airyland** [comment]
2.0要配合vux-loader使用，文档上也有写了。你不使用vux2模板就需要自己配置。

https://github.com/airyland/vux2/blob/master/template/build/webpack.base.conf.js#L110-L119

https://vux.li/#/?id=-%E6%89%8B%E5%8A%A8%E4%BD%BF%E7%94%A8

**Comment by wonghoman** [comment]
@airyland 你好，这个项目https://github.com/airyland/vux2，下载下来install的时候报错，是哪里问题？


D:\temp\vux2-master\template>npm install
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wonghoman\\AppDa
ta\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v4.0.5
npm ERR! file D:\temp\vux2-master\template\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '{' at 9:36
npm ERR!     "build": "node build/build.js"{{#unit}},
npm ERR!                                    ^
npm ERR! File: D:\temp\vux2-master\template\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     D:\temp\vux2-master\template\npm-debug.log
