### ISSUE TITLE
vux checklist能实现反选功能吗？

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [airyland/vux#791]
`change (val) {
         this.value1 = [0];
   },
`当多选列表改变状态的时候让全部选择清空，改变v-model="value1" 并不能同步数据； 看到文档中写了一个定时器，才能异步操作，作者有什么思路能使用chyecklist实现，反选功能；

**Comment by airyland** [comment]
看这里，并不存在你说的要异步操作的问题。反选自己遍历值设置就可以了。

https://vux.li/#/zh-CN/demos/checklist
