### ISSUE TITLE
引入   x-number  报错

### ISSUE THREAD

**Issue by huangzhenxian** [airyland/vux#796]
![image](https://cloud.githubusercontent.com/assets/8416974/22111901/044e914a-de9c-11e6-8942-07dfedb3bb55.png)

版本：
vux  2.1.0-rc.4 

问题来源：
引入 x-number 就出现这个问题  页面我昨晚是 2.0.5的时候没这个问题 今天vux升级 2.1.0-rc.4 就出现 就出现这个问题  页面我昨晚是 2.0.5的时候没这个问题 今天vux升级 2.1.0-rc.4 就出现

**Comment by airyland** [comment]
贴下代码，x-number这两天并没有代码更新。

**Comment by F-loat** [comment]
> $t是Demo的i18n使用的翻译函数，一般情况下可以直接使用字符串

去掉$t就好了

**Comment by huangzhenxian** [comment]
<x-number title="参与人数" v-model="form.count" ></x-number>
我换 x-input 就没事  $t 是哪个库的？ 是我删了一些库了吗

**Comment by airyland** [comment]
翻译函数。引入时会被替换。你可以用npm install 重新安装一次依赖如果还有问题的话。

**Comment by cjc2011** [comment]
请问最后怎么解决的   昨晚遇到了同样的问题  
![error](https://cloud.githubusercontent.com/assets/17289716/22628511/10df8c08-ec10-11e6-835c-04fd4f74b021.png)
![code](https://cloud.githubusercontent.com/assets/17289716/22628512/12e87d66-ec10-11e6-8848-633eb9a9a78e.png)

**Comment by airyland** [comment]
@cjc2011 请参照文档。
https://vux.li/#/?id=%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
