### ISSUE TITLE
引入swiper出错 Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Richar-Dada** [airyland/vux#797]
### Version
"vux": "^2.1.0-rc.2"

### Android or iOS
都存在
> For Android issues, please specify the brand, model and browser

### Your Codes 

import Swiper from 'vux/src/components/swiper'

``` html
<!--put your code here-->
```

### Steps to reproduce the problem
引入直接报错

**Comment by airyland** [comment]
新版本没有这个用法 。

https://vux.li/#/zh-CN/components?id=swiper
https://vux.li/#/zh-CN/upgrade-to-2?id=swiper-%E5%BC%95%E5%85%A5%E8%B7%AF%E5%BE%84%E5%8F%98%E5%8C%96

**Comment by Richar-Dada** [comment]
用上面的新方式 还是报错

import Swiper from 'vux/src/components/swiper/swiper'

报错是swiper.js里的 export default Swiper

**Comment by airyland** [comment]
确定配置了vux-loader了吗？

**Comment by Richar-Dada** [comment]
npm install 了

**Comment by airyland** [comment]
不，我是说webpack里配置了吗？

**Comment by Richar-Dada** [comment]
loaders: [
      {
        test: /\.vue$/,
        loader: 'vue',
        plugins: [{
          name: 'vux-ui'
        }]
      },
      {
        test: /\.js$/,
        loader: 'babel',
        include: [
          path.join(projectRoot, 'src')
        ],
        plugins: [{
          name: 'vux-ui'
        }],
        query: {
          presets: ['es2015']
        },
        exclude: /node_modules/
      },
这里？

**Comment by airyland** [comment]
汗，我确定我文档并没有写这么个用法。vux-loader都没引入。。

https://vux.li/#/zh-CN/README?id=安装使用webpack

**Comment by airyland** [comment]
汗，我确定我文档并没有写这么个用法。vux-loader都没引入。。

https://vux.li/#/zh-CN/README?id=安装使用webpack

**Comment by Richar-Dada** [comment]
我这边看到的文档没有配置代码的
