### ISSUE TITLE
popup-picker报错"labelWidth" is not defined

### ISSUE THREAD

**Issue by lsbrucelincoln** [airyland/vux#799]
早上把vux升级到2.1.0-rc.4
然后就报错了
vue.common.js?e881:521
[Vue warn]: Property or method "labelWidth" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <popup-picker> at G:\vue\lawSuperWe\node_modules\vux\src\components\popup-picker\index.vue)

**Comment by airyland** [comment]
try v2.1.0-rc.6

**Comment by lsbrucelincoln** [comment]
好快，辛苦啦
