### ISSUE TITLE
cell怎么绑定事件？

### ISSUE THREAD

**Issue by GloriaCHL** [airyland/vux#80]
cell这个组件怎么在它上面绑定@click事件？按普通的做法写上去貌似没作用。cell里加个slot倒是可以绑在slot上，但我想绑在cell上。

**Comment by airyland** [comment]
直接按照vue方法绑定在cell上就行了。

``` html
 <cell title="My Account" value="Protected" @click="fn"></cell>
```

**Comment by airyland** [comment]
https://vux.li/api/v1/demo.html?components=Cell&template=%3Ccell%20title%3D%22My%20Account%22%20value%3D%22Protected%22%20%40click%3D%22click%22%3E%3C%2Fcell%3E&style=&script=export%20default%20%7B%0D%0A%20%20methods%3A%20%7B%0D%0A%20%20%20%20click%3A%20function%20()%20%7B%0D%0A%20%20%20%20%20%20alert(%27click%27)%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D

**Comment by janchengwang** [comment]
vue2.0 
`<cell is-link @click="choosePic">
		        <img slot="icon" width="48" style="display:block;margin-right:8px;" src="https://o3e85j0cv.qnssl.com/tulips-1083572__340.jpg">
		     </cell>`
没有效果，我是想点击cell,然后显示actionsheet

**Comment by airyland** [comment]
@janchengwang  vue2.0在组件上绑定点击事件要使用 @click.native

**Comment by janchengwang** [comment]
@airyland ok, 好了
