### ISSUE TITLE
生成UMD文件时候，BOX组件并无生成

### ISSUE THREAD

**Issue by jktantan** [airyland/vux#800]
1. 使用NPM的版本是4.0.5
2. 使用npm run build-components的方式进行UMD文件的生成
3. 生成完之后，对比了下SRC目录下的components，发现BOX这个组件并无在dist目录下出现。
4. 对比SRC下的COMPONENT目录中的组件数量，发现SRC下有77个组件目录，但是dist中生成出来的只有66个

**Comment by airyland** [comment]
因为一部分组件仅仅是demo的快捷方式或者依赖，不是正式组件。
