### ISSUE TITLE
panel里怎么增加自定义内容？

### ISSUE THREAD

**Issue by spiritelf** [airyland/vux#802]

**Comment by airyland** [comment]
你想在哪里增加自定义内容？

**Comment by spiritelf** [comment]
除了定义的四个属性外的其他内容？

**Comment by airyland** [comment]
额，即使我想增加slot你也得告诉你想在哪个位置加吧。

**Comment by spiritelf** [comment]
比如实现类似卡片效果  
![image](https://cloud.githubusercontent.com/assets/8556186/22141473/319ac59c-df2d-11e6-90a3-438b68c3a2a3.png)

**Comment by airyland** [comment]
@spiritelf 这个太业务相关了啊，从panel扩展不合理，样式也需求不一样，因为布局不复杂，建议根据需求自己写。

**Comment by spiritelf** [comment]
@airyland  根据weui
？

**Comment by airyland** [comment]
怎么实现是你的事情了。不在issue讨论范围内。
