### ISSUE TITLE
i18n 配置 的示例程序哪里可以看到？

### ISSUE THREAD

**Issue by spiritelf** [airyland/vux#803]

**Comment by airyland** [comment]
看demo源码。

**Comment by brandonxiang** [comment]
@spiritelf webpack上加plugin，main.js要加store吗？

**Comment by airyland** [comment]
@brandonxiang https://vux.li/#/zh-CN/vux-loader?id=i18n

**Comment by brandonxiang** [comment]
大神，我看过文档，但是我觉得说明得并不充分

**Comment by airyland** [comment]
@brandonxiang 你这么表述，事实上我也不知道你觉得哪里不充分了，你可以PR一下更新下文档。
