### ISSUE TITLE
Scroller组件 下拉长度问题

### ISSUE THREAD

**Issue by huangzhenxian** [airyland/vux#808]
版本 rc.9
问题：
{
  content: 'Pull Up To Refresh',
  pullUpHeight: 60,
  height: 40,
  autoRefresh: false,
  downContent: 'Release To Refresh',
  upContent: 'Pull Up To Refresh',
  loadingContent: 'Loading...',
  clsPrefix: 'xs-plugin-pullup-'
}
中   
 pullUpHeight: 60,
  height: 40,
有什么用？ 怎么设置都无效的  我自己在Scroller 加了

![image](https://cloud.githubusercontent.com/assets/8416974/22153920/4332719c-df64-11e6-96ee-07629de45ee6.png)

**Comment by airyland** [comment]
上完整代码方便重现

**Comment by huangzhenxian** [comment]
![image](https://cloud.githubusercontent.com/assets/8416974/22154714/943c6b3a-df67-11e6-9d1d-dc62f7165703.png)

**Comment by huangzhenxian** [comment]
pullUpHeight: 60,
height: 40,

这两个怎么设置都无效   现在下拉一碰到底部就加载  拉都拉不住  这两个值的字面意思不是设置下拉的距离的吗
