### ISSUE TITLE
日期插件问题

### ISSUE THREAD

**Issue by mirrorpal** [airyland/vux#81]
月份选择变成偶数变换，具体表现为4-6-8.
日期选择pc chrome模拟手机可以选择日期，但是我用iphone6(ios 9.3 safari)和小米note(安卓5.1 微信X5)日期选择不了，我看demo用的zepto，我也使用的是zepto库，请问是否还需要其他库的引用
http://1.airpal.applinzi.com/ 这个是测试地址

**Comment by airyland** [comment]
看到了确实有问题，chrome可以点击，手机下有问题。
然后calendar本身是没有依赖zepto的。

**Comment by airyland** [comment]
move to #104
