### ISSUE TITLE
iPhone5 IOS8.1.3 整体样式错乱

### ISSUE THREAD

**Issue by wg5945** [airyland/vux#811]
### Version
2.1.0-rc.9
### Android or iOS
IOS8.1.3 iPhone5

> For Android issues, please specify the brand, model and browser

整体样式错乱

![1](https://cloud.githubusercontent.com/assets/5310295/22172584/1c5d6964-dfe6-11e6-8b49-82ef4d0e9309.png)

![2](https://cloud.githubusercontent.com/assets/5310295/22172585/234a2c76-dfe6-11e6-9ff1-77c2b8933f7e.jpg)

**Comment by airyland** [comment]
错乱也得上个截图。

**Comment by wg5945** [comment]
@airyland 我网络好像有问题，之前图片上传一直失败~~麻烦看下呢~~

**Comment by airyland** [comment]
现在刷新看看呢，怀疑是autoprefix的配置问题，更新重新构建了下。

**Comment by wg5945** [comment]
首页正常了，但是Demo页还是有问题
![qq 20170121152643](https://cloud.githubusercontent.com/assets/5310295/22172912/1a24d206-dfee-11e6-8ec2-b27109d5e521.jpg)

**Comment by airyland** [comment]
再次强加了前缀，现在呢，flex-wrap支持可能有问题。

**Comment by wg5945** [comment]
demo list 页面还是这样

但是我看flexbox的demo是好的

**Comment by airyland** [comment]
其他页面没问题对吧

**Comment by wg5945** [comment]
是的

**Comment by airyland** [comment]
更新了下布局，有空再看看

**Comment by wg5945** [comment]
大神威武~~已经正常显示了~~

还有个问题
flexbox在iPhone5 IOS8.1.3上span无效，麻烦再看下呢
![image](https://cloud.githubusercontent.com/assets/5310295/22173663/f9cb9140-e004-11e6-99dc-67e7d3f84bc7.png)

**Comment by airyland** [comment]
泪流满面，手头上没有iOS8的机子

**Comment by wg5945** [comment]
这个问题应该是1时代遗留下来的，适配还是要做的啊~~

**Comment by airyland** [comment]
那么只能判断下是否支持新特性，退化成百分比宽度了

**Comment by wg5945** [comment]
这个应该是可以兼容的吧，晚上我来搞一下~~

**Comment by wg5945** [comment]
ios7，8我都测试过了，应该可以兼容了

**Comment by airyland** [comment]
这个比较奇怪，合理来说autoprefix应该会处理才对。
