### ISSUE TITLE
x-input clear按钮只能触发一次focus事件

### ISSUE THREAD

**Issue by greedying** [airyland/vux#816]
### Version
2.1.0-rc.12

### Android or iOS
全部
### Your Codes 
vux.li demo

### Expected behavior and actual behavior.
希望两点，
1、clear能每次都focus x-input
2、focus属性能够提供对外触发的接口

### Steps to reproduce the problem
点击clear按钮，只能触发一次focus，因为focus初始为false，第一次clear，focus赋值为true，触发watch。但是之后，再次clear，focus仍然是true，所以不会触发watch。代码如下

```javascript
focus (newVal) {
    if (newVal) {
        this.$refs.input.focus()
     }
}
```

**Comment by airyland** [comment]
欢迎 PR

**Comment by greedying** [comment]
(⊙o⊙)…，最新代码又把focus function去掉了，没法主动触发input的focus状态了 - -

**Comment by greedying** [comment]
还是自己写一个input框吧- -  %>_<%
