### ISSUE TITLE
popup-picker组件data更新时，数据不会更新

### ISSUE THREAD

**Issue by minh8023** [airyland/vux#82]
如题。
```
data: [{
     name: '中国',
     value: 'china',
     parent: 0
}]
```
再push一个进去，弹出来层数据不会变。
我只是打个比方，实际我的data来源于后台数据，弹出层只能弹出一次了。第二次弹出就无数据了。

**Comment by airyland** [comment]
对，现在是一次性绑定，不过也即将支持动态赋值

**Comment by minh8023** [comment]
好的吧。回复好快啊，3q。

**Comment by wjs** [comment]
@minh8023  v0.0.110 好像还是没有修复，看源码是 created 里面弄成了一次性绑定。所以如果想动态改变数据的话，可以在 popup-picker 上加一个 v-if ， 然后每次改变数据之前， v-if 弄成 false， 数据改变之后 v-if 变成 true，然后就生效了 😄

**Comment by GeeBar** [comment]
@wjs  没...没看懂。怎么操作的？按你的方法没成功啊

**Comment by GeeBar** [comment]
@wjs  你的方法可以异步操作data 但是result取值怎么办？
