### ISSUE TITLE
sticky组件在红米手机无法固定在顶部

### ISSUE THREAD

**Issue by greedying** [airyland/vux#822]
### Version
npm：v2.1.0-rc-15
### Android or iOS
红米手机，android 6.0.1， 微信浏览和红米自带浏览器

### Your Codes 
vux.li demo 

### Expected behavior and actual behavior.
不太清楚sticky具体支持哪些版本；希望尽可能实现

### Steps to reproduce the problem
手机打开vux.li demo 即可

**Comment by airyland** [comment]
原因是demo使用了100%布局导致滚动容器不是window因此不起作用。
内部实现上不支持sticky特性的会使用scroll事件兼容，因此基本没有兼容问题。

**Comment by jzYuchn** [comment]
@Airyland 我的红米5p也没有效果，但是chrome模拟器，iPhone上都可以，不知道找到原因没？
