### ISSUE TITLE
无法找到vux模块

### ISSUE THREAD

**Issue by 317365887** [airyland/vux#825]
错误提示
This dependency was not found in node_modules:

* vux

Did you forget to run npm install --save for it?

错误呈现过程
通过快速入门把项目创建好，然后运行了npm install , 然后运行npm run dev 项目是可以看到vux的那个界面，然后我把我自己的代码放进去，代码结构如下

在control.js代码里面，代码内容如下
import * as appTypes from '../../store/modules/app/mutation-types'
import { Group, Cell } from 'vux'

export default {
  name: 'home',
  data () {
    return {
      'msg': '哈哈'
    }
  },
  created () {
    // 组件创建完后获取数据，
    // 此时 data 已经被 observed 了
    this.fetchData()
  },
  watch: {
    // 如果路由有变化，会再次执行该方法
    '$route': 'fetchData'
  },
  methods: {
    fetchData () {
      var that = this;
      this.$store.dispatch('appStartLoading');
      this.msg = this.$route.params.id;
      setTimeout(function(){
        that.$store.commit(appTypes.APP_FINISH_LOADING);
      },3000);
    }
  }
}

如果我去掉import { Group, Cell } from 'vux' 就可以正常运行，如果加上的话 就会提示 无法找到vux模块

**Comment by 317365887** [comment]
无法上传图片。醉了

**Comment by 317365887** [comment]
刚才又测试了下 我把js 写在.vue文件下就可以调用得到 如果我把js代码另外放到一个.js文件里面然后在.vue文件里面引用这个文件就不行了

**Comment by airyland** [comment]
更新 vux-loader 到 1.0.31
