### ISSUE TITLE
build-components缺少了swiperItem子组件

### ISSUE THREAD

**Issue by huangzhenxian** [airyland/vux#827]
1.版本：rc.15
2.问题：umd文件生成   build-components  的时候 没有swiperItem子组件可以引入 我目前只能全部引入一个500k的 vux.min.js来临时处理这个问题

**Comment by airyland** [comment]
我的错，其实你可以稍微修改一下build-components文件的。

**Comment by huangzhenxian** [comment]
@airyland 我还看不懂代码  例如那些 touch什么我都不知道他的作用 我百度也找不到文档
