### ISSUE TITLE
修改webpack.base.conf文件后 单元测试跑不通了

### ISSUE THREAD

**Issue by Richar-Dada** [airyland/vux#828]
### Version
"vuex": "^2.0.0",
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 
var path = require('path')
var config = require('../config')
var utils = require('./utils')
const vuxLoader = require('vux-loader')
var projectRoot = path.resolve(__dirname, '../')

var env = process.env.NODE_ENV
// check env & config/index.js to decide whether to enable CSS source maps for the
// various preprocessor loaders added to vue-loader at the end of this file
var cssSourceMapDev = (env === 'development' && config.dev.cssSourceMap)
var cssSourceMapProd = (env === 'production' && config.build.productionSourceMap)
var useCssSourceMap = cssSourceMapDev || cssSourceMapProd

webpackConfig ={....} //省略webpack配置

module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [
    {
      name: 'vux-ui'
    }
    ]
})
``` html
<!--put your code here-->
```

### Steps to reproduce the problem
在webpack.base.conf加入了引入vux2的的配置代码,单元测试就跑不通.
报错信息:24 01 2017 11:21:27.958:ERROR [config]: Invalid config file!

**Comment by airyland** [comment]
这个报错简洁到没有排查的线索。可以去掉大部分无关代码打外包发我研究一下。

**Comment by Richar-Dada** [comment]
怎样发你  发你邮箱？ @airyland

**Comment by airyland** [comment]
i@mao.li

**Comment by Richar-Dada** [comment]
代码已经发你邮箱了 @airyland

**Comment by airyland** [comment]
翻了邮箱似乎没找到
