### ISSUE TITLE
scroller组件中规定内容必须是一个div，并且只能有一个div ，我在里面加了cell组件，向上拉的加载，感觉怪怪的

### ISSUE THREAD

**Issue by 317365887** [airyland/vux#830]
``` html
<scroller @on-pullup-loading="pullupHeandle" @on-pulldown-loading="pulldownHeandle" :value="scrollStatus" lock-x scrollbar-y  ref="scroller" :use-pulldown="usePullDown" :use-pullup="usePullUp" :pulldown-config="pulldownConfig" :pullup-config="pullupConfig">
  <div>
    <group title="cell demo">
      <cell v-for="i in datas" title="item" :value="i"></cell>
    </group>
  </div>
</scroller>
```

**Comment by 317365887** [comment]
如果只是简单的p元素在里面，上拉滚动加载还是可以看到比较好的 上拉加载 -  释放开始加载 - 加载中。这些提示，换成cell组件就不行了

**Comment by 317365887** [comment]
文档的这句话
反之，则调用方法 enalbePullup 或者设置pullupSatatus为enabled

enablePullup 方法名是这个 ，文档写错了

**Comment by 317365887** [comment]
pullupHeandle () {
      console.log('pullupHeandle');

      var that = this;
      that.datas += 5;
      that.$nextTick(() => {
        that.$refs.scroller.reset()
      })

      that.$refs.scroller.donePullup()

      if (that.datas > 40) {
        that.$refs.scroller.disablePullup();
      }

    }
上拉刷新的回调是这样子的，就一直托不上去了

**Comment by airyland** [comment]
学习下markdown语法稍微格式化代码吧。

**Comment by 317365887** [comment]
代码应该是没问题的，都是按照你文档的，现在主要是上拉加载 一直拉不到底，滚动条一上拉就滚回原来的地方

**Comment by airyland** [comment]
作为作者没有责任每次都帮issue格式代码。

![image](https://cloud.githubusercontent.com/assets/559179/22251552/1b5c31ec-e286-11e6-8ae5-491e89e5739b.png)

=>

![image](https://cloud.githubusercontent.com/assets/559179/22251574/41acb628-e286-11e6-89db-a4e7d0c05f34.png)
