### ISSUE TITLE
Scroll组件拖不到底

### ISSUE THREAD

**Issue by 317365887** [airyland/vux#832]
绑定了@on-pullup-loading="pullupHeandle"后就拖不到底了。
`pullupHeandle (e) {
      console.log('pullupHeandle');

      var that = this;
      that.datas += 5;
      that.$nextTick(() => {
        that.$refs.scroller.reset()
      })

      that.$refs.scroller.donePullup()

      if (that.datas > 40) {
        that.$refs.scroller.disablePullup();
      }

    },`

**Comment by airyland** [comment]
贴方便重现的完整代码并注意格式化。
