### ISSUE TITLE
loadmore 能否提供插件调用的形式？

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#835]
如题

**Comment by airyland** [comment]
提供插件调用的都是不需要指定位置的组件，而loadmore不一样，他不是页面提示，一般用v-show更方便控制吧。

**Comment by jsonviewer** [comment]
有时候需要在vuex的action中加载完数据关闭loadmore，插件形式关闭会不会方便一些？否则是不是要用vuex来管理显示或者关闭的這个状态？

**Comment by airyland** [comment]
要插件调用不可避免要指定操作el，这已经不vue了，可以用vuex控制，也可以直接指定一个id，操作这个组件样式，要隐藏就display none，简单方便。

**Comment by huangyanxiong01** [comment]
v-show 无法控制显示隐藏与显示
