### ISSUE TITLE
$parent.index值为-1的解决方案

### ISSUE THREAD

**Issue by nannan9507** [airyland/vux#836]
我做了一个tabbar-item，但在选择selected时出现了一个问题：
```
      <tabbar>
        <tabbar-item v-for="item in paperbar.barList" :link="item.link" :selected="$route.path === item.url">
          <span slot="label">{{ item.title }}</span>
        </tabbar-item>
     </tabbar>
```
阅读了tabbar-item.vue的源码，:class="{'weui_bar_item_on': $parent.index === currentIndex}"，
当页面刷新的时候，$parent.index值为-1，而currentIndex第一个为0，
所以在页面上刷新的时候，tabbar-item设置了selected却无法显示为选中状态。
但在点击以后才会改变$parent.index的值为currentIndex。
请问是有什么最佳实践或者解决方案嘛？

**Comment by airyland** [comment]
版本是哪个？

**Comment by nannan9507** [comment]
vux 2.0.11

**Comment by F-loat** [comment]
@nannan9507 这个我之前提的pr修复了应该，你更新试试 #776

**Comment by nannan9507** [comment]
3q，我试试看解决了就关闭

**Comment by nannan9507** [comment]
换了最新的2.0.17, 可问题还是没有解决，$parent.index 依旧为-1

**Comment by F-loat** [comment]
@nannan9507 新版不是已经2.1.0-rc.15了

**Comment by F-loat** [comment]
或者你按照我那个pr自己改下试试

**Comment by nannan9507** [comment]
可以了，谢谢，我就是直接npm install vux，没有去查询vux最新版。
问题解决了3q
