### ISSUE TITLE
hello,address怎么去掉inline-desc

### ISSUE THREAD

**Issue by QiDa-007** [airyland/vux#838]
hello,address怎么让红色方框的不显示
![image](https://cloud.githubusercontent.com/assets/11505520/22409935/90d583f2-e6cc-11e6-8fec-4a5fdf28b098.png)

下面是代码：
<x-address title='地区' placeholder='请选择收件人地区'  v-model="form.receiverCity"  :list="addressData"></x-address>

**Comment by airyland** [comment]
检查是否为最新2.1.0-rc.x版本。
