### ISSUE TITLE
popup-picker 低分辨率出现滚动条后有问题

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#840]
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<template>
  <div>
    <x-header class="header-fixed" :left-options="{showBack: true}">
      隐患详情
      <a slot="right" @click="submit">
        <svg class="svg-icon header-right-icon" aria-hidden="true">
          <use xlink:href="#icon-check"></use>
        </svg>
      </a>
    </x-header>
    <div class="info-content">
      <group title="基本信息" labelWidth="4em" label-margin-right="1em" >
        <uploader :thumbnails="thumbnails" style="padding-left: 10px" @on-button-click="add" @on-item-click="showPreviewer" @on-delete-click="deleteImage">
        </uploader>
        <x-input title="上报人" readonly v-model="user.realname"></x-input>
        <popup-picker title="隐患类别" :data="categories" v-model="selectedCategory" value-text-align="left" @on-change="change"></popup-picker>
        <x-input title="隐患部位" required placeholder="必填" v-model="position" ref="position"></x-input>
      </group>
      <group title="详情描述">
        <x-textarea placeholder="请填写详细信息(必填)" :height="200" :rows="8" v-model="description" required ref="description"></x-textarea>
      </group>
    </div>
    <actionsheet v-model="show" :menus="menus" @on-click-menu="click" show-cancel></actionsheet>
    <previewer :list="images" ref="previewer" :options="options"></previewer>
    <progress-bar :percent="progressBarValue" v-if="progressBarSwitch"></progress-bar>
  </div>
</template>
```

### Steps to reproduce the problem
低分辨率，加上popup-picker控件出现滚动条，会如图1所示。去掉后正常，如图2所示，没有出现滚动条加上popup-picker控件，正常，如图3
![image](https://cloud.githubusercontent.com/assets/22734724/22449842/891517e6-e79d-11e6-8451-3df758b13791.png)

![image](https://cloud.githubusercontent.com/assets/22734724/22449335/8c4eaf2e-e79a-11e6-856a-2a14b7edeec9.png)
![image](https://cloud.githubusercontent.com/assets/22734724/22449325/78606994-e79a-11e6-8802-c6c635002acd.png)

**Comment by airyland** [comment]
如果屏幕高度小 ，出现滚动条不是正常的么？你的textarea也比较高。
看截图觉得你还是没描述清楚，“出现滚动条后有问题”，有什么问题？

**Comment by jsonviewer** [comment]
你看图一和图二样子不一样  背景的颜色变成灰色了，基本信息和详情描述那里，图一
控制台有一条错误 
![image](https://cloud.githubusercontent.com/assets/22734724/22449735/f2234dbc-e79c-11e6-9ff4-56e5c9c2d867.png)

**Comment by airyland** [comment]
只有scroller组件依赖了hammer，看你代码并没有调用scroller的样子？

**Comment by jsonviewer** [comment]
這个页面没有使用scroller组件

**Comment by airyland** [comment]
无法重现，如果你只是chrome模拟器里有问题，而真机没问题，那么就不是VUX组件的问题了。

**Comment by jsonviewer** [comment]
@airyland 经真机测试，没有出现上述问题。
出现两个新的问题。
1、popup-picker 显示后，自身上也有个遮罩层，无法滑动内容，如图1
2、popup-picker 在有滚动条后，并不能显示全，是不是popup-picker是从正文而不是可见区域的底部弹出的，如图2

autoprefixer:
` browsers: ['last 7 versions']`

mounted时设置了scroller的高度：
`mounted() {
      this.scrollerH = '${document.documentElement.clientHeight - 46}px';
    }`

代码：
```
<div>
    <x-header :left-options="{showBack: true}">
      隐患详情
      <a slot="right" @click="submit">
        <svg class="icon" aria-hidden="true">
          <use xlink:href="#icon-check"></use>
        </svg>
      </a>
    </x-header>
    <scroller lock-x scrollbarY :height="scrollerH" :bounce="false" ref="scroller">
      <div>
        <group title="基本信息" labelWidth="4em" label-margin-right="1em">
          <uploader :thumbnails="thumbnails" style="padding-left: 10px" @on-button-click="add" @on-item-click="showPreviewer" @on-delete-click="deleteImage">
          </uploader>
          <x-input title="上报人" readonly v-model="user.realname"></x-input>
          <popup-picker title="隐患类别" :data="categories" v-model="selectedCategory" value-text-align="left" @on-change="change"></popup-picker>
          <x-input title="隐患部位" required placeholder="必填" v-model="position" ref="position"></x-input>
        </group>
        <group title="详情描述">
          <x-textarea placeholder="请填写详细信息(必填)" :height="200" :rows="8" v-model="description" required ref="description"></x-textarea>
        </group>
        <actionsheet v-model="show" :menus="menus" @on-click-menu="click" show-cancel></actionsheet>
        <previewer :list="images" ref="previewer" :options="options"></previewer>
        <progress-bar :percent="progressBarValue" v-if="progressBarSwitch"></progress-bar>
      </div>
    </scroller>
  </div>
```
![screenshot_20170207-090956](https://cloud.githubusercontent.com/assets/22734724/22673720/c7b80340-ed16-11e6-9b05-254055932755.png)
![screenshot_20170207-090946](https://cloud.githubusercontent.com/assets/22734724/22673748/f360f2ae-ed16-11e6-8956-6545e6d87599.png)

**Comment by airyland** [comment]
额，之前不是说没有使用scroller吗。你这里完全没有必要使用scroller组件，scroller只是设计用来用来显示列表数据的。

**Comment by jsonviewer** [comment]
之前那个确实没加scroller,在真机上没问题了。
现在用scroller是因为内容超了以后，xheader也会滚动，所以就用了个scroller
![image](https://cloud.githubusercontent.com/assets/22734724/22677105/1efaaedc-ed2b-11e6-8aa5-66819f826ea7.png)

xheader设置fixed,加上样式style="position: fixed;width: 100%;z-index:888;margin-top: -11px，可以打到效果，是应该這么使用吗？
```    
<x-header :left-options="{showBack: true}" style="position: fixed;width: 100%;z-index:999;margin-top: -11px">
      隐患详情
      <a slot="right" @click="submit">
        <svg class="icon" aria-hidden="true">
          <use xlink:href="#icon-check"></use>
        </svg>
      </a>
    </x-header>
```
![image](https://cloud.githubusercontent.com/assets/22734724/22677223/f446321e-ed2b-11e6-9b9b-bd354cad0945.png)

**Comment by airyland** [comment]
xheader如何定位的，如果你用fixed定位还会滚动？

**Comment by jsonviewer** [comment]
麻烦再看一下我的上一条回复 @airyland

**Comment by airyland** [comment]
`margin-top: -11px` 这一个设置很诡异啊。理论上应该是跟顶部对齐。

**Comment by jsonviewer** [comment]
```
  <div>
    <x-header :left-options="{showBack: true}" style="position: fixed;width: 100%;z-index:999;">
      隐患详情
    </x-header>
    <group title="基本信息" labelWidth="4em" label-margin-right="1em">
      <uploader :thumbnails="thumbnails" style="padding-left: 10px" @on-button-click="add" @on-item-click="showPreviewer" @on-delete-click="deleteImage">
      </uploader>
      <x-input title="上报人" readonly v-model="user.realname"></x-input>
      <popup-picker title="隐患类别" :data="categories" v-model="selectedCategory" value-text-align="left" @on-change="change"></popup-picker>
      <x-input title="隐患部位" required placeholder="必填" v-model="position" ref="position"></x-input>
    </group>
    <group title="详情描述">
      <x-textarea placeholder="请填写详细信息(必填)" :height="200" :rows="8" v-model="description" required ref="description"></x-textarea>
    </group>
    <group title="详情描述">
      <x-textarea placeholder="请填写详细信息(必填)" :height="200" :rows="8" v-model="description" required ref="description"></x-textarea>
    </group>
    <group title="详情描述">
      <x-textarea placeholder="请填写详细信息(必填)" :height="200" :rows="8" v-model="description" required ref="description"></x-textarea>
    </group>
  </div>
```
不设置margin-top会有一条缝隙
![image](https://cloud.githubusercontent.com/assets/22734724/22678243/a8eb5b52-ed33-11e6-9934-e9f4ca07bff6.png)


目前我是這么解决的, xheader上加top:0,其他代码放到一个div里，并在div上加样式style="position: relative; top:46px"，不知道多加一个div這样是不是好的实现方式，还是不加div在第一个groud上写margin-top？
```
  <div>
    <x-header :left-options="{showBack: true}" style="position: fixed;width: 100%;z-index:999;top: 0;">
      隐患详情
    </x-header>
    <div style="position: relative; top:46px">
      <group title="基本信息" labelWidth="4em" label-margin-right="1em" >
        <uploader :thumbnails="thumbnails" style="padding-left: 10px" @on-button-click="add" @on-item-click="showPreviewer" @on-delete-click="deleteImage">
        </uploader>
        <x-input title="上报人" readonly v-model="user.realname"></x-input>
        <popup-picker title="隐患类别" :data="categories" v-model="selectedCategory" value-text-align="left" @on-change="change"></popup-picker>
        <x-input title="隐患部位" required placeholder="必填" v-model="position" ref="position"></x-input>
      </group>
      <group title="详情描述">
        <x-textarea placeholder="请填写详细信息(必填)" :height="200" :rows="8" v-model="description" required ref="description"></x-textarea>
      </group>
    </div>
</div>
```
![image](https://cloud.githubusercontent.com/assets/22734724/22678428/f872f530-ed34-11e6-9472-c434af6800ce.png)

**Comment by airyland** [comment]
能审查到这个间隙是哪里导致的么

**Comment by jsonviewer** [comment]
找了找并没有找到
![image](https://cloud.githubusercontent.com/assets/22734724/22680350/6588c8f4-ed42-11e6-9473-e964478831bb.png)

![image](https://cloud.githubusercontent.com/assets/22734724/22680372/7ee7a090-ed42-11e6-86eb-21b6bf54bc77.png)

**Comment by airyland** [comment]
body, html 样式呢，看情况也不是x-header造成的。清除其他代码，直接写一个fixed元素是不是也有间隙？

**Comment by jsonviewer** [comment]
找到原因了，去掉.weui_cells_title的margin-top属性，就可以了。fixed，下面的元素设置margin-top貌似会一起移动
![image](https://cloud.githubusercontent.com/assets/22734724/22719219/67388c8c-eddf-11e6-9675-d14c514c659d.png)

**Comment by airyland** [comment]
但是它这里是margin-top，应该不会影响到fixed定位才对。

**Comment by jsonviewer** [comment]
我也觉得很纳闷，因为我刚开始在group上直接用margin-top，xheader的高度，xheader也跟着移动了,在一个在线html网站测了下，好事是会移动
![qq 20170208155647](https://cloud.githubusercontent.com/assets/22734724/22728151/5906909a-ee17-11e6-8557-40994b457aef.png)
![qq 20170208155701](https://cloud.githubusercontent.com/assets/22734724/22728156/5d78e6dc-ee17-11e6-928e-d6375de8daba.png)

**Comment by airyland** [comment]
`top:0;` 呢

**Comment by jsonviewer** [comment]
top:0；可以
![image](https://cloud.githubusercontent.com/assets/22734724/22728231/ce1a281a-ee17-11e6-8df5-3b0a414456f5.png)

**Comment by airyland** [comment]
但是你上面的vux调用代码里是有top:0的，也是会有间隙？

![image](https://cloud.githubusercontent.com/assets/559179/22728288/13e16d4a-ee18-11e6-84c9-8145fa3ee03e.png)

**Comment by jsonviewer** [comment]
没。。我之前用margin-top：-11px，你不是觉得诡异吗，后来用top:0了，图片是没设置margin-top：会有间隙，现在设置top:0，没别的问题了
![image](https://cloud.githubusercontent.com/assets/22734724/22728380/88289e58-ee18-11e6-8218-9eaeafe32882.png)

**Comment by airyland** [comment]
所以就没问题啦。
