### ISSUE TITLE
toast显示时如何处理用户按返回键仍然显示的问题

### ISSUE THREAD

**Issue by liutao0532** [airyland/vux#841]
当执行
`      this.$vux.toast.show({
        text: 'Loading',
        time: 88888,
      });`
的时候 用户点击手机上的返回按键，会调到前一页。这个完全没问题，但是打开的toast仍然还在，请问这个如何处理，谢谢

**Comment by airyland** [comment]
在vue-router的afterEach hook 进行关闭。

**Comment by liutao0532** [comment]
谢谢，这么晚了还在线 辛苦了 新年快乐 还有另一个问题 ，我在发一个issues吧 ;)

**Comment by airyland** [comment]
在高铁上刷微博 😃
