### ISSUE TITLE
表单页与列表页数据交互问题

### ISSUE THREAD

**Issue by liutao0532** [airyland/vux#842]
你好，我的表单提交页面 多个字段都是由不同的列表点选设置的，目前在代码实现上，我用的是popup的形式打开list，选择后在关闭，因为会有多个字段访问不同list，导致一个vue文件特别庞大，有没有什么好的解决方案呢？？谢谢

**Comment by airyland** [comment]
具体数量多少？

**Comment by liutao0532** [comment]
目前表单里是有6个需要点击打开list选择的字段。而且每个list还需要支持筛选，代码就特别特别多了

**Comment by airyland** [comment]
组件调用代码应该不多，你说的是数据列表代码多？

**Comment by liutao0532** [comment]
就是所有代码都写在一个vue文件里了，你的意思是把popup弹出的list代码写在单独的vue里？

**Comment by airyland** [comment]
如果每个List都是十几行以上，一般放到外面json或者js文件进行引入，而实际上更多的情况是list是从服务端引入的。

**Comment by liutao0532** [comment]
是的，list数据都是从服务端获取的，list代码包括列表html 筛选html和对应的脚本 这还只是一个list 多个就list都放到一个vue文件里就很复杂了。
之前有考虑过把list文件单独封装成vue，但好像没有实现选择的三部曲
1：表单里打开封装的list 2：在封装的list里选择并关闭 3：表单接收封装list选中的值
这个有demo可以看看吗 谢谢

**Comment by airyland** [comment]
你说的这个demo看得不是很明白，比较像业务逻辑，目前没有这个。给个具体的截图或者应用交互可能比较好理解。具体开发中，代码量并不是衡量代码质量的指标，更重要的是清晰的代码结构和可维护性，因此如果目前能满足需求并且维护起来没有任何困难，我觉得是没有什么问题的。
