### ISSUE TITLE
关于组件ViewBox的两个问题

### ISSUE THREAD

**Issue by howyhuang** [airyland/vux#843]
版本
"vux": "^2.0.13"
"vue": "^2.1.0",

使用viewBox遇到两个问题请教下。
1.   this.$refs.viewBox.getScrollBody is not a function
2.  Cannot read property 'removeEventListener' of undefined
我参考vux的demo的app.vue文件
源码： this.box = this.$refs.viewBox.getScrollBody()
不清楚this.box是怎么来的，
然后导致this.box.addEventListener('scroll', this.handler, false)找不到啊
![image](https://thumbnail0.baidupcs.com/thumbnail/b438ff4c4ff5c913a6ca81ddcc791b00?fid=3543456737-250528-843097497828219&time=1486314000&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-iLmpg3GGfKNeVU4Hc%2BDaTnu%2F8hg%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=836347770717827623&dp-callid=0&size=c710_u400&quality=100)

![images](https://thumbnail0.baidupcs.com/thumbnail/c3ec8eeb66a97eb27ed5afd9ca61f41a?fid=3543456737-250528-627430284305066&time=1486314000&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-CBLHR9QFnl%2FNrL%2F7AJW2yvbphsk%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=836387261871743654&dp-callid=0&size=c710_u400&quality=100)

**Comment by airyland** [comment]
请确认图片上传完整再提交issue，谢谢。

**Comment by howyhuang** [comment]
大神能否抽空帮忙看下viewBox 我使用这组件遇到的问题
this.box = this.$refs.viewBox.getScrollBody()
不清楚 这个this.box

**Comment by airyland** [comment]
更新VUX版本。

**Comment by howyhuang** [comment]
问题已解决
我这样创建项目vue init airyland/vux2 project
然后升级"vux": "^2.0.17" "vux-loader": "^1.0.35",
view-box 这个组件下面没有如下代码 要自己手动去node_modules添加下就好了

<script>
export default {
  methods: {
    scrollTo (top) {
      this.$refs.viewBoxBody.scrollTop = top
    },
    getScrollTop () {
      return this.$refs.viewBoxBody.scrollTop
    },
    getScrollBody () {
      return this.$refs.viewBoxBody
    }
  }
}
</script>

**Comment by airyland** [comment]
@howyhuang 最新版本已经是2.1.0-rc.x了。
