### ISSUE TITLE
怎样修改路径：/app.js

### ISSUE THREAD

**Issue by losgithub** [airyland/vux#844]
快速入门的测试页面中，index页面使用<script type="text/javascript" src="/app.js"></script>。我使用nginx代理访问，无法访问/app.js。这个/app.js怎么把根目录去掉，改为app.js？

**Comment by airyland** [comment]
构建后并不会存在app.js这一文件，至少是带hash的，该issue非vux问题，请到相关repo提问。

**Comment by losgithub** [comment]
npm run build没有问题。npm run dev是怎么自动加上这行的：<script type="text/javascript" src="/app.js"></script>

**Comment by airyland** [comment]
部署时使用build文件，你并不需要知道dev时是怎么加上这行的，如果你想深入了解的话，参考webpack文档。

**Comment by F-loat** [comment]
使用的是vue-cli的webpack模板的话，修改 `config/index.js` 中 `dev` 的 `assetsPublicPath` 配置即可，或者配置下 `proxyTable` 做转发应该也可以

``` javascript
dev: {
  env: require('./dev.env'),
  port: 8080,
  assetsSubDirectory: 'static',
  assetsPublicPath: '/',
  proxyTable: {},
}
```
