### ISSUE TITLE
Hello:LoadingPlugin插件导入报错,vux版本是2.0.15

### ISSUE THREAD

**Issue by QiDa-007** [airyland/vux#845]
![image](https://cloud.githubusercontent.com/assets/11505520/22557045/2ebfdcd2-e9a4-11e6-9e05-0b4d426aae0f.png)

依赖版本：
![image](https://cloud.githubusercontent.com/assets/11505520/22557141/82a85a9a-e9a4-11e6-98a0-04b8d94bb22d.png)

**Comment by airyland** [comment]
升级到最新的2.1.0-rc版本。可以通过 npm info vux 查看版本。
