### ISSUE TITLE
i18n warning  

### ISSUE THREAD

**Issue by chengfei602** [airyland/vux#847]
warning  in ./~/vux/src/components/loading/index.vue

Loader for custom block type "i18n" not found in webpack configuration

 warning  in ./~/vux/src/components/popup-picker/index.vue

Loader for custom block type "i18n" not found in webpack configuration

**Comment by airyland** [comment]
已了解，vue-loader 新版本的警告，今天将解决。

**Comment by losgithub** [comment]
只是提示，不耽误运行测试
