### ISSUE TITLE
使用<快速入门>的方式新建项目,单元测试跑不了

### ISSUE THREAD

**Issue by Richar-Dada** [airyland/vux#848]
### Version
"vux": "^2.0.13",
### Android or iOS
all
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```

### Steps to reproduce the problem
1. 使用开始<快速入门>方式开始一个项目
2. npm install 安装依赖
3. npm test 出现报错 

** 难道大家都不用写单元测试吗

**Comment by airyland** [comment]
贴下报错信息

**Comment by Richar-Dada** [comment]
你新建一个就行 两行命令的事  而且我已经发过代码去你邮箱了

**Comment by Richar-Dada** [comment]
@airyland

**Comment by Richar-Dada** [comment]
测试跑起来了,但是还是有问题噢! @airyland 

03 02 2017 17:35:16.842:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
03 02 2017 17:35:16.844:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
03 02 2017 17:35:16.875:INFO [launcher]: Starting browser PhantomJS
03 02 2017 17:35:19.820:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket Hka2AcR-llWgsslZAAAA with id 46275388
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Use of reserved word 'import'
  at webpack:///test/unit/specs/Hello.spec.js:1:0 <- index.js:168

PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.124 secs / 0 secs)

**Comment by airyland** [comment]
karma.conf.js的36行，修改：

``` js
if (/^babel/.test(loader.loader) && typeof loader.include === 'object') {
```
https://github.com/airyland/vux2/blob/master/template/test/unit/karma.conf.js#L36

**Comment by wolfstark** [comment]
@airyland 就在今天，我使用vux的快速入门webpack模板在依赖vux组件时jest单元测试不能运行
![image](https://user-images.githubusercontent.com/15010463/33699306-49983568-db4d-11e7-9936-b113fc5f8b6f.png)
