### ISSUE TITLE
vux 1.0 版本的文档希望还是保留

### ISSUE THREAD

**Issue by wqj97** [airyland/vux#849]
之前一个项目是使用Vux 1.0开发的, 暂时不打算更新2.0.
维护的时候发现官网上已经找不到1.0版本的文档了
希望还是照顾一下1.0版本, 在文档中给个1.0版本文档的链接

**Comment by airyland** [comment]
0.x 版本文档不完整，并且已经不再维护。
 https://vuxjs.gitbooks.io/vux/content/

**Comment by wqj97** [comment]
谢谢!!
