### ISSUE TITLE
vux在android4.4.x下的问题

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#850]
### Android or iOS

> For Android issues, please specify the brand, model and browser
联想s920、HTC ONE M8，android版本 4.4.2；华为畅玩4X ，android版本4.4.4；
cordova封装应用 版本6.4.0
### Your Codes 

``` html
<!--put your code here-->
<template>
  <div>
    <x-header :left-options="{showBack: true}">
      隐患详情
      <a slot="right" @click="submit">
        <svg class="icon" aria-hidden="true">
          <use xlink:href="#icon-check"></use>
        </svg>
      </a>
    </x-header>
    <group title="基本信息" labelWidth="4em" label-margin-right="1em">
      <uploader :thumbnails="thumbnails" style="padding-left: 10px" @on-button-click="add" @on-item-click="showPreviewer" @on-delete-click="deleteImage">
      </uploader>
      <x-input title="上报人" readonly v-model="user.realname"></x-input>
      <popup-picker title="隐患类别" :data="categories" v-model="selectedCategory" value-text-align="left" @on-change="change"></popup-picker>
      <x-input title="隐患部位" required placeholder="必填" v-model="position" ref="position"></x-input>
    </group>
    <group title="详情描述">
      <x-textarea placeholder="请填写详细信息(必填)" :height="200" :rows="8" v-model="description" required ref="description"></x-textarea>
    </group>
    <actionsheet v-model="show" :menus="menus" @on-click-menu="click" show-cancel></actionsheet>
    <previewer :list="images" ref="previewer" :options="options"></previewer>
    <progress-bar :percent="progressBarValue" v-if="progressBarSwitch"></progress-bar>
  </div>
</template>
```

### Expected behavior and actual behavior.
actionsheet组件v-if设置为false，也会显示；插件形式调用alert,confirm,loading，不居中显示；返回图标顺时针旋转90°。這几个问题在android 5.0以上不会出现。ps：左侧的返回图标可不可以自定义，比如用iconfont，只是图标自定义，执行的事件还是默认的
### Steps to reproduce the problem
![screenshot_2017-02-04-09-59-10-417](https://cloud.githubusercontent.com/assets/22734724/22614690/a5c7c200-eac0-11e6-95cc-3c25ac2f2af8.jpeg)
![screenshot_2017-02-04-09-41-04-869](https://cloud.githubusercontent.com/assets/22734724/22614581/cc93034c-eabe-11e6-948e-0871a8bdd0a5.jpeg)

**Comment by airyland** [comment]
你的autoprefix配置是什么

**Comment by jsonviewer** [comment]
`  vue: {
    loaders: utils.cssLoaders({ sourceMap: useCssSourceMap }),
    postcss: [
      require('autoprefixer')({
        browsers: ['last 2 versions']
      })
    ]
  }`
是這个吗？就是用vue-cli建立的项目

**Comment by airyland** [comment]
你直接把`2`改成`7`试试

**Comment by jsonviewer** [comment]
改成7以后没问题了 谢谢
