### ISSUE TITLE
建议直接使用 weixin-js-sdk 以跟踪最新的微信官方版本，现在已经是 1.2.0 啦

### ISSUE THREAD

**Issue by bugyak** [airyland/vux#853]
https://github.com/yanxi-me/weixin-js-sdk

**Comment by airyland** [comment]
咦，官方还是1.0.0

https://mp.weixin.qq.com/wiki

**Comment by airyland** [comment]
看到了，微信的文档真是，不知道要怎么吐槽了。。

**Comment by airyland** [comment]
Done on v2.1.0-rc.25
