### ISSUE TITLE
loadingPlugin插件使用报错

### ISSUE THREAD

**Issue by zbjcool** [airyland/vux#862]
"vux":"^2.1.0-rc.27"
"vux-loader": "^1.0.35"

main.js
`import  { LoadingPlugin } from 'vux'
Vue.use(LoadingPlugin)`

npm 报错

`Uncaught SyntaxError: Unexpected token import
    at Object.<anonymous> (index.ceb05ba….min.js:533)
    at __webpack_require__ (vendors.js:586)
    at fn (vendors.js:110)
    at eval (eval at <anonymous> (index.ceb05ba….min.js:403), <anonymous>:35:12)
    at Object.<anonymous> (index.ceb05ba….min.js:403)
    at __webpack_require__ (vendors.js:586)
    at fn (vendors.js:110)
    at Object.<anonymous> (index.ceb05ba….min.js:6)
    at __webpack_require__ (vendors.js:586)
    at webpackJsonpCallback (vendors.js:22)`

vux-loading已经正确引入。请问这是什么原因，loadingPlugin如何使用？

**Comment by airyland** [comment]
请帖上完整报错信息后 reopen issue。连哪个文件哪一行报错都没有。

**Comment by airyland** [comment]
你如果用webpack的话，为什么看不到哪个文件在哪一行报错，而是一个带hash的index.min.js文件。

**Comment by zbjcool** [comment]
```
import Array2stringFilter from './src/filters/array2String.js'
import FormatTimeFilter from './src/filters/format-time.js'
import FriendlyTimeFilter from './src/filters/friendly-time.js'
import Name2valueFilter from './src/filters/name2value.js'
```
我是使用webpack，第一行报错

**Comment by airyland** [comment]
你配置 vux-loader 到webpack配置了吗

**Comment by zbjcool** [comment]
配置了，其他组建使用正常，我按照教程使用plugin的时候，出现这个错误
```
module.exports = vuxLoader.merge(webpackConfig, {
    options: {},
    plugins: [
        {
            name: 'vux-ui'
        }
    ]
})
```

**Comment by airyland** [comment]
入口这一段是用不到的，不知道你为什么调用到了这里。

``` js
import Array2stringFilter from './src/filters/array2String.js'
import FormatTimeFilter from './src/filters/format-time.js'
import FriendlyTimeFilter from './src/filters/friendly-time.js'
import Name2valueFilter from './src/filters/name2value.js'
```

**Comment by zbjcool** [comment]
我checkout 老的分支，老的分支里面vux是老的版本，然后就正常了。
老版本vux：
    "vux": "^2.1.0-rc.2",
    "vux-loader": "^1.0.35"
