### ISSUE TITLE
Xaddress 引入报错 

### ISSUE THREAD

**Issue by leecz** [airyland/vux#864]
### Version
vue-cli 最新，使用了 webpack 2.2.1
vux 最新
先使用 webpack 模板，然后手动加入的 vux ，其他用到的组件都 ok。

### Android or iOS
all browser

### Your Codes 

```js
import { XAddress, ChinaAddressData } from 'vux'
```

### 问题
引入 Xaddress  就会报错，
` Cannot assign to read only property 'exports' of object '#<Object>'`
应该是新版本的 webpack 和 xaddress 的依赖库 scroller js 有冲突。

**Comment by airyland** [comment]
try v2.1.0-rc.28

**Comment by leecz** [comment]
更新好快，我前天安装 才 rc.24。。。
谢谢！
