### ISSUE TITLE
x-input 验证问题

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#865]
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
    <group labelWidth="4em" label-margin-right="1em">
      <x-input title="密码" type="password" placeholder="请输入6~20位密码" required :min="6" :max="20" v-model="password" ref="password"></x-input>
      <x-input title="确认密码" type="password" placeholder="请确认输入" v-model="confirmPassword" required :min="6" :max="20" :equal-with="password" ref="confirmPassword"></x-input>
    </group>
```

### Steps to reproduce the problem
1、使用equal-with以后，第一个xinput输入值以后，第二个xinput为空，带有required，通过this.$refs.confirmPassword.valid获取到的值为true
2、xinput，type为password时能否在显示clear icon的位置显示个图标，可以切换明文和圆点，如图
![image](https://cloud.githubusercontent.com/assets/22734724/22639929/6494e0de-ec8b-11e6-820f-3744a2ba85e9.png)
![image](https://cloud.githubusercontent.com/assets/22734724/22639933/691a3212-ec8b-11e6-8164-a9c6389f50ab.png)

**Comment by airyland** [comment]
因为VUX不提供图标，所以你可以自己使用`slot=right`来实现。
https://github.com/airyland/vux/blob/5c05a7edfdaaed608ca282c4b8388e1ba0914ca7/src/demos/Issue865.vue#L6
