### ISSUE TITLE
vux checklist 当最大值为1时候的建议

### ISSUE THREAD

**Issue by lmasdata** [airyland/vux#866]
<img width="339" alt="qq20170207-150813 2x" src="https://cloud.githubusercontent.com/assets/8501594/22681292/5ab36bfa-ed47-11e6-9054-d40c04c73c02.png">
当选择【男】，再想选择【女】的时候，必须把【男】取消才能选，是不是当在只能选择一个的时候可以自动切换，而不是先取消后再选择。

**Comment by airyland** [comment]
那你应该用`Radio`组件而不是多选组件吧。

**Comment by airyland** [comment]
源码修改这个交互需要直接修改表单值，导致表单验证流程有问题，因此暂不支持。
