### ISSUE TITLE
x-input，max和onchange

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#868]
1、x-input现在设置max，字符数超过以后还能继续输入，能否在input上加入maxlength属性。
2、能否增加一个onchange事件，在input内容改变时，调用。目前我是用watch方法监听v-model。

**Comment by jsonviewer** [comment]
@airyland on-change，在x-input使用v-model的情况下，会执行两次。

**Comment by airyland** [comment]
我的错，其实本来是在mixin里支持的了。`v2.1.0-rc.33`
