### ISSUE TITLE
toast

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#870]
通过插件形式调用toast如果改变过type和width值，在其他地方再次调用，不是默认样式。需要指定type和width這个是正常的吗？

**Comment by airyland** [comment]
同时只会在body插入一个实例，因此如果多次调用，之前的参数会保留。

**Comment by jsonviewer** [comment]
ok

**Comment by F-loat** [comment]
感觉重新调用的时候重置为默认属性好一点，大多数情况下使用默认属性就足够了，但是当前的设定导致修改一次属性后，即使想要使用默认属性，也需要显式设置
