### ISSUE TITLE
webpack2 报错

### ISSUE THREAD

**Issue by transtone** [airyland/vux#871]
```js 
export default plugin
module.exports = plugin
```
貌似webpack2不允许这样混用。

```js 
export default plugin
// module.exports = plugin
```
这样就可以了。

https://github.com/webpack/webpack/issues/4039
https://github.com/ElemeFE/element/issues/2677

**Comment by airyland** [comment]
当时加上`module.exports`是因为umd打包有问题，我测试一下。

**Comment by transtone** [comment]
现在的代码
```js
module.exports = plugin
```
还是报错：`Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

保留 `export default plugin` 正常不报错。

**Comment by airyland** [comment]
`export default plugin` 会导致umd打包出来的文件需要使用 `.default`来调用。略麻烦。
