### ISSUE TITLE
eslint error

### ISSUE THREAD

**Issue by wg5945** [airyland/vux#872]
### Version
Latest
### Android or iOS
ALL
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```

### Expected behavior and actual behavior.
刚刚的更新 
[https://github.com/airyland/vux/commit/f45b0a9cb261bc50c75d6ac3785f5ecf5aa1e977](url)
eslint报错，请更新下格式

**Comment by airyland** [comment]
done.
