### ISSUE TITLE
x-input 相关

### ISSUE THREAD

**Issue by muei** [airyland/vux#875]
*vux@^2.0.13*
- password类型不支持
- 不支持disabled属性
- 希望password类型支持开关可见密码

**Comment by airyland** [comment]
vux 并没有 2.1.2版本，你大概是把vux和vuex混淆了 :sweat_smile: 

1.支持的
2.骚等
3.自行加上slot=right实现

**Comment by JohannLai** [comment]
您好，password 类型测试后发现渲染的结果还是type=text

**Comment by airyland** [comment]
看下node_modules下vux/package.json的版本号。

**Comment by JohannLai** [comment]
你好，是vux@^2.0.13

**Comment by airyland** [comment]
版本过低了。安装vux@^2.1.0-rc.32吧。
用`npm info vux` 查看最新版本。

**Comment by muei** [comment]
哈哈 我傻叉了  看花眼copy错了

**Comment by JohannLai** [comment]
刚好我review了一下看到了把那个text 改为了pasword
it work！
