### ISSUE TITLE
XButton 缺少原生默认类型

### ISSUE THREAD

**Issue by muei** [airyland/vux#878]
如果在`form`里面，`form`绑定了提交事件, 多个`XButton` 点击事件均会触发`form`.
当然也有方法解决, 比如`x-button`绑定为`@click.prevent`. 但还是希望有原生类型的支持

**Comment by airyland** [comment]
看不大明白，什么是原生类型？现在XButton渲染出来不就是button么。

**Comment by muei** [comment]
指定`button`的`type`, `submit` 或者 'button'

**Comment by airyland** [comment]
使用`action-type`指定。v2.1.0-rc.35
