### ISSUE TITLE
文档细节改进

### ISSUE THREAD

**Issue by zhyc9de** [airyland/vux#879]
自己的不熟练，希望给新手踩个坑
在confirm组件中，[文档](https://github.com/airyland/vux/blob/f35b6351decf9c47f72a1c773c546bd4e1e44f47/src/components/confirm/metas.yml#L26)并没有详尽给出按钮属性如何设置

一开始以为是`confirm-text`、`cancel-text`，后来看了源码才知道，应该使用`confirmText`、`cancelText`

**Comment by lichunqiang** [comment]
`confirm-text` 和 `cancel-text` 是以组件形式引入的时候设置方式.

当然如果以plugin的方式就是后者了，其实看文档中的props就可以。

**Comment by zhyc9de** [comment]
是的，其实是我自己对vue不熟= =||
