### ISSUE TITLE
可能是fastclick引起的点击事件BUG

### ISSUE THREAD

**Issue by graysheeep** [airyland/vux#88]
RT，发生在我自己的项目上。跟你一样加了fastclick防止0.3s的点击延迟，无意之间发现会有一定概率发生一个比较严重的BUG，在有按钮（button或者a）的界面上下快速拖动页面，然后整个页面的按钮点击事件会失效。之后在你的项目上测试了一下发现也会有这个问题存在，去掉fastclick后一切正常。非常非常妖怪，不过概率不大就是了只要不无聊到去上下拖动页面。

**Comment by airyland** [comment]
在哪个浏览器，哪个页面可以重现？

**Comment by graysheeep** [comment]
@airyland 微信浏览器，重现比较难因为我很难描述，等我某一天录个视频发给你。

**Comment by airyland** [comment]
这个问题导致了客户端的back不能用，而safari里正常怀疑是客户端问题，暂时没有其他人反馈先关闭之。

**Comment by docikaci** [comment]
@graysheeep 有滚动时，然后特别快速点击，是不是可以稳定复现
