### ISSUE TITLE
selector组件的placeholder属性在ios中不显示

### ISSUE THREAD

**Issue by lmasdata** [airyland/vux#880]
### Version
2.1.0-rc.23
### Android or iOS
ios 10.0.1
> For Android issues, please specify the brand, model and browser

### Your Codes 
 
``` html
<selector placeholder="请选择部门" title="当前部门" :options="orgnalist" v-model="orgna" ref="orgnaref" required></selector>
```
selector组件的placeholder属性，在ios手机10.0.1版本中并没有显示出来，安卓中则无此问题

**Comment by brahmachen** [comment]
此问题在ios上仍然存在，版本是最新版本

**Comment by brahmachen** [comment]
2.8.0依然有这个问题
