### ISSUE TITLE
表单组件selector中的options，提交表单时，选中的options不能携带其他信息

### ISSUE THREAD

**Issue by alinnnnnn** [airyland/vux#882]
### Version
"vux": "^2.0.11"；

### My Codes 

``` html
//当表单提交时，无法携带option的id
    <group> 
        <selector v-model="formData.roleval" title="岗位" :options="formData.roleList"></selector> 
    </group>
```

``` js
 data(){
     return{
         formData{
            roleval:'',

            roleList:［｛id：1，value:'人事部'｝，｛id：2，value: '财务部'｝，｛id:3，value:'技术部'｝，｛id:4,value:'其他'｝］
//这样的数据格式读不了

            roleList:['人事部', '财务部'，'技术部'，'其他']  //这样的数据格式才能读取
      }
  }   
}
```

### Expected behavior and actual behavior.
预期行为：
表单selector里我想给每个options携带id，当表单提交时，提交selector选中options的id。［｛id：1，value:'人事部'｝，｛id：2，value: '财务部'｝，｛id:3，value:'技术部'｝，｛id:4,value:'其他'｝］。

实际行为：
表单组件selector的:options仅能获取单维数组格式，且被选中options，无法携带其他信息。规定数据格式为：['人事部', '财务部'，'技术部'，'其他'] 。

**Comment by airyland** [comment]
对于需要键值对的场景，组件规定使用`key=>value`的形式。

https://vux.li/#/zh-CN/components?id=selector
