### ISSUE TITLE
发现 Datetime 组件 的一个问题

### ISSUE THREAD

**Issue by Rookiewan** [airyland/vux#884]
这两天开发一个业务场景，需要两个用户输入出生日期，就用了 Datetime 组件，然后 发现如果两个人的生日相同，第二个人直接确定不会触发 on-change 事件，看了源码发现是用 计算属性 来触发事件的，所以会出现这种问题。如果是用两个组件是没有问题，只是提一下。

**Comment by airyland** [comment]
看不明白。一个组件怎么给两个人同时操作？如果值相同，当然是不会触发`on-change`事件了，如果你只是取值，取 `v-model` 上的值就行了。
