### ISSUE TITLE
Calendar 组件报错

### ISSUE THREAD

**Issue by YYmmlin** [airyland/vux#887]
图片上传不了 我发报错代码
`vue.common.js?e881:521 [Vue warn]: Property or method "replaceTextList" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <calendar> at E:\work\fund\node_modules\vux\src\components\calendar\index.vue)warn @ vue.common.js?e881:521warnNonPresent @ vue.common.js?e881:1439get @ vue.common.js?e881:1480render @ index.vue?590a:46Vue._render @ vue.common.js?e881:3096(anonymous function) @ vue.common.js?e881:2464get @ vue.common.js?e881:1661run @ vue.common.js?e881:1730flushSchedulerQueue @ vue.common.js?e881:1544(anonymous function) @ vue.common.js?e881:473nextTickHandler @ vue.common.js?e881:422
vue.common.js?e881:521 [Vue warn]: Property or method "customSlotFn" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <calendar> at E:\work\fund\node_modules\vux\src\components\calendar\index.vue)`

**Comment by airyland** [comment]
版本过低，请更新。

**Comment by YYmmlin** [comment]
我直接 npm install vux -save  返回是@2.0.17 然后还 npm update vux  , npm vux -v 是3.10.10 ,还报错，我应该还要如何更新呢？

**Comment by airyland** [comment]
不存在 npm vux -v 这样的命令，你这是查看 npm 版本。 npm info vux 查看版本吧，现在已经到2.1.0-rc.x了。

**Comment by YYmmlin** [comment]
哦哦！好的，问题没有了
