### ISSUE TITLE
x-input组件的focus事件无效

### ISSUE THREAD

**Issue by wg5945** [airyland/vux#888]
### Version
v2.1.0-rc.43
### Android or iOS
All

官网demo中x-input组件的focus事件无效

从源码上来看@focus,@blur是类似于vue-focus的写法，不过从代码里没有发现相关引用或类似实现

**Comment by airyland** [comment]
<del>对，一会添加。</del>

**Comment by airyland** [comment]
确认了一下，代码里是有`on-focus`事件的。你是想监听on-focus还是其他处理？

**Comment by wg5945** [comment]
`<x-input title="focus-handler" placeholder="focus me!" :show-clear="true" @focus="onFocus"></x-input>
`
这个里面onFocus方法貌似不能触发，你那边可以？

**Comment by airyland** [comment]
`@on-focus` , vux组件的事件都是`on-`前缀

**Comment by wg5945** [comment]
恩，请更新下demo代码
