### ISSUE TITLE
DEMO在魅族手机中存在显示问题

### ISSUE THREAD

**Issue by ZoeBai** [airyland/vux#889]
### Version
v2.1.0-rc.41
### Android or iOS
Android
MEIZU PRO 6
微信webview v6.5.4 

###demo问题
- 用微信浏览器访问在线demo，点击Inline-Calendar进不去，chrome devTools显示报错
``` 
Cannot assign to read only property 'exports' of object '#<Object>'
```
- 直接clone github代码，```npm install```, ```npm run dev```在本地运行， 则Blur, Clocker, Inline-Calender, Ranger, Rater, X-Circle均出现上述问题（代码下载时间是今天2017-02-10，未看到明确标示的版本）

- 在线demo在魅族PRO 6上用weixin webview打开必现排版错位。表现为：打开的一瞬间为正常排版，然后排版错位，基本上每个组件都出现了该问题，在有cell的页面中尤其明显。附图如下：
![](https://ww4.sinaimg.cn/large/006tNc79gy1fclgv1f3goj30k00zkabb.jpg)
![](https://ww1.sinaimg.cn/large/006tNc79gy1fclgtoue6tj30k00zkwgo.jpg)
![](https://ww3.sinaimg.cn/large/006tNc79gy1fclgw1p0dqj30k00zktas.jpg)
![](https://ww3.sinaimg.cn/large/006tNc79gy1fclgwaxiu6j30k00zkmyt.jpg)
![](https://ww4.sinaimg.cn/large/006tNc79gy1fclgxdru8dj30k00zkdgw.jpg)
用chrome打开则显示正常

**Comment by airyland** [comment]
- [x] Cannot assign to read only property 'exports' of object '#<Object>' 这个问题已经全部修复了。

**Comment by airyland** [comment]
不了解魅族，没有魅族的机子 ，理论上微信浏览器内核应该是一致的。上面的错位都很离谱，在小米的机子上目测也没有这个问题。

`表现为：打开的一瞬间为正常排版，然后排版错位`，这个看起来是系统问题而非组件问题。

**Comment by ZoeBai** [comment]
是的。小米机型没发现有此问题。刚刚用魅族mx5打开demo，同样有上述显示问题。比如cell组件，主观上感受是cell里内容与cell框分离。上下滑动时，cell框正常滚动，cell中内容fix在显示屏上（倒存在一个位移能使cell与其中的内容正确框住）。

**Comment by airyland** [comment]
你打开weui.io 示例看看呢

**Comment by ZoeBai** [comment]
weui.io显示正常


来自 魅族 PRO 6

-------- 原始邮件 --------
发件人：Airyland <notifications@github.com>
时间：周五 2月10日 18:32
收件人：airyland/vux <vux@noreply.github.com>
抄送：ZoeBai <baifengyi_xjtu@163.com>,Author <author@noreply.github.com>
主题：Re: [airyland/vux] DEMO在魅族手机中存在显示问题 (#889)

**Comment by airyland** [comment]
帮忙再试试，目测是过渡动画导致的问题，在Chrome非模拟状态下可以重现。

**Comment by ZoeBai** [comment]
果然已经好了！厉害~


来自 魅族 PRO 6

-------- 原始邮件 --------
发件人：Airyland <notifications@github.com>
时间：周六 2月11日 10:58
收件人：airyland/vux <vux@noreply.github.com>
抄送：ZoeBai <baifengyi_xjtu@163.com>,Author <author@noreply.github.com>
主题：Re: [airyland/vux] DEMO在魅族手机中存在显示问题 (#889)
