### ISSUE TITLE
"$t" is not defined

### ISSUE THREAD

**Issue by ericwang1902** [airyland/vux#893]
使用vux新手，在开始使用时，出现这个错误：
![image](https://cloud.githubusercontent.com/assets/7867163/22861289/67743024-f150-11e6-921d-e527cf05cf49.png)

**Comment by airyland** [comment]
如果你是用cnpm安装的，换成npm安装。

**Comment by liaotup** [comment]
@airyland 还是不行 用npm 重装依赖 vux-loader也装了 都不行

**Comment by airyland** [comment]
@liaotup 
首先确实你自己代码确实没有使用 $t 这个多语言函数。
然后按照文档来
![image](https://cloud.githubusercontent.com/assets/559179/24033299/314f8002-0b27-11e7-9d43-f8fc4cf8f3f0.png)

**Comment by liaotup** [comment]
@airyland 
![image](https://cloud.githubusercontent.com/assets/10844117/24034566/b2c7a02e-0b2c-11e7-9a86-2683249409ce.png)
确定我的代码没有使用$t 已根据文档来了几遍无果.  打开源码发现 formpreview 组件使用了三处$t，我应该如何处理
![image](https://cloud.githubusercontent.com/assets/10844117/24034602/e5b5e68a-0b2c-11e7-8457-cd69937787c6.png)

**Comment by liaotup** [comment]
在源码删除引用后，结果正了。 应该是您们发布的时候不小心带上了。  让我发个Issue好不好。  哈

**Comment by airyland** [comment]
源码没关系的，源码的 $t 会被 vux-loader 处理掉。

**Comment by liaotup** [comment]
这样 我是不是要配置一下 vux-loader?

**Comment by airyland** [comment]
@liaotup 难道你没有用 vux-loader，我好想砍死你。

**Comment by liaotup** [comment]
![image](https://cloud.githubusercontent.com/assets/10844117/24034837/e6350d24-0b2d-11e7-9219-056b4757cb27.png)
我只install了

**Comment by liaotup** [comment]
好吧 我欠你一刀 @airyland

**Comment by airyland** [comment]
@liaotup 再看看文档。虽然我不认识你，但是我宣布跟你绝交。

**Comment by liaotup** [comment]
@airyland  居然成功了   哈 我发誓我有看文档的  可能看太快了 没看 vux-loader  为表歉意 我要向组积捐款   你看能不能取消绝交的宣布
