### ISSUE TITLE
如何与移动端自适应方案相结合，比如lib-flexible

### ISSUE THREAD

**Issue by erguotou520** [airyland/vux#898]
是否有考虑过？
或者vux本身提供这样的自适应方案？

**Comment by airyland** [comment]
样式依赖于 WeUI，而 WeUI 是 px 像素，非 rem 尺寸。因为本身产品业务上没有这个需求，因此暂未打算做。理论上你可以使用 postcss 等工具进行 px2rem 的转换。

**Comment by erguotou520** [comment]
我刚发issue的时候准备加上“虽然项目依赖于WeUI的，但是...”，后来还是删了，看下你这边是否有方案的 😃

**Comment by erguotou520** [comment]
已经加上postcss方案
```
require('postcss-plugin-px2rem')({
  rootValue: 37.5,
  selectorBlackList: ['html'],
  mediaQuery: true,
  propBlackList: ['font-size']
})
```

**Comment by zhump** [comment]
@erguotou520  这样会影响我正常页面的样式 37.5 是weui自己一个理想的数字 跟实际不符

**Comment by erguotou520** [comment]
@zhump 开始做的时候就应该全局规划好
