### ISSUE TITLE
scroller使用pulldown刷新，第一页的高度超过屏幕高度，第一页不能向下滑动。

### ISSUE THREAD

**Issue by codingwangxiansen** [airyland/vux#904]
我使用VUX2.0的scroller组件时，实现下拉刷新数据的过程中，我的第一页加载的初始数据本身的高度就是大于页面高度的，所以进去之后要能向下滚动，但是现在进去之后完全不能滚动，下拉加载过一次数据之后才能滚动，请问有没有什么办法可以进去之后就可以向下滚动的？

**Comment by airyland** [comment]
这类问题都是没有reset导致的。你确定你内容超过一页的话，确认下你有没有在数据加载后 reset。

**Comment by F-loat** [comment]
``` javascript
this.$nextTick(() => {
  this.$refs.scroller.reset();
});
```
数据加载完成后要等页面渲染好了再reset

**Comment by cm060210216** [comment]
2.1.0 版本，测试发现，当scroller 中的第一个div如果设置class,或者style，比如设置背景色，将会导致reset失效。
