### ISSUE TITLE
scroller的onscroll问题

### ISSUE THREAD

**Issue by jsonviewer** [airyland/vux#908]
on-scroll事件，在scroll组件第一次加载没有发生滚动的时候会执行？

**Comment by airyland** [comment]
应该不会，demo页面有一个例子加载后并没有看到触发了on-scroll事件。你是怎么用的？

**Comment by jsonviewer** [comment]
```
    mounted() {
      this.$nextTick(() => {
        this.$refs.scroller.reset({
          top: this.top,
        });
      });
    },
```
onScroll的时候记录position的top值，mounted的时候把這个值赋值回去，实现滚动位置记录

**Comment by airyland** [comment]
感觉是你这个操作的`on-scroll`操作产生的问题，reset 会触发 on-scroll。

**Comment by airyland** [comment]
你可以试试先检查 ref._xscroll.getScrollTop() 是不是为0，this.top 是不是为0, 为0时就不reset了。

**Comment by jsonviewer** [comment]
我在onscroll里通过vuex保存top值 再次进入页面时通过mounted里的语句重现滚动条位置 这时onscroll会执行一次 position参数的top是0，再次通过vuex设置top值 这时  第三次进入页面时 就回到最顶部了 保存正确位置信息一次

**Comment by jsonviewer** [comment]
```
methods: {
  onScroll(position) {
     this.setTop(position.top);
  }
}
```

**Comment by jsonviewer** [comment]
使用keep-alive解决了
