### ISSUE TITLE
import 插件的时候报错

### ISSUE THREAD

**Issue by chenguose** [airyland/vux#910]
### Version
2.1.0-rc.48
### Android or iOS
browser
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
import Vue from 'vue'
import { sync } from 'vuex-router-sync'
import App from './App.vue'
import store from './store'
import router from './router'
//解决点击延迟
const FastClick = require('fastclick')
FastClick.attach(document.body)
//关联路由和store
sync(store, router)
//引入插件 下面那句代码 编译会出现index.js?102c:3 Uncaught SyntaxError: Unexpected token import(…)错误,如果注释了就没问题了
import { LoadingPlugin} from 'vux'
Vue.use(LoadingPlugin)
//生成入口
var vm=new Vue({
  el: '#app',
  store,
  created: function () {
  },
  watch: {
  },
  template: '<App/>',
  components: { App}
})
```

### Expected behavior and actual behavior.
index.js?102c:3 Uncaught SyntaxError: Unexpected token import(…)，报了这个错。请问怎么解决。

**Comment by airyland** [comment]
就你给的线索而言，没有解决方法。

**Comment by chenguose** [comment]
我是手动引入vux，按照文档那样做。代码如下：

`import Vue from 'vue'
import { sync } from 'vuex-router-sync'
import App from './App.vue'
import store from './store'
import router from './router'
//解决点击延迟
const FastClick = require('fastclick')
FastClick.attach(document.body)
//关联路由和store
sync(store, router)
//引入插件  下面那句代码 编译会出现index.js?102c:3 Uncaught SyntaxError: Unexpected token import(…)错误,如果注释了就没问题了
import { LoadingPlugin} from 'vux'
//生成入口
var vm=new Vue({
  el: '#app',
  store,
  created: function () {
  },
  watch: {
  },
  template: '<App/>',
  components: { App}
})`

**Comment by chenguose** [comment]
奇怪的是，我在我的main.js引入就报错，但是在app.vue就正常。
