### ISSUE TITLE
使用计算属性获取ref值的问题

### ISSUE THREAD

**Issue by lmasdata** [airyland/vux#911]
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<x-input title="联系电话" name="phone" placeholder="请输入联系电话" v-model="phone" ref="phoneref" required></x-input>

computed: {
      disable() {
          console.log(this.$refs.phoneref)
      }
    }
```

控制台打印出的值为undefined，
但是this.refs是有值的
![image](https://cloud.githubusercontent.com/assets/8501594/22920293/5a0a9466-f2cf-11e6-8f89-3a97fe3d84c4.png)

**Comment by lmasdata** [comment]
vux 的版本是2.1.0-rc.37

**Comment by airyland** [comment]
这跟vux没关系了，vue@2.x ref 不是响应性的，不适合用于计算属性。

**Comment by lmasdata** [comment]
Thanks
