### ISSUE TITLE
device插件，按照Vue习惯，是否应该是Vue.device？ 

### ISSUE THREAD

**Issue by greedying** [airyland/vux#912]
### Version
v2.1.0-rc.48
### Android or iOS
不区分

### Your Codes 

```javascript
    Vue.$device = {
      isAndroid,
      isIpad,
      isIpod,
      isIphone,
      isWechat
    }
```

### Expected behavior and actual behavior.
vue-router的使用方式，是 Vue.router和 this.$router
vue-resource是 Vue.http 和 this.$htttp
于是我使用 Vue.device，发现无效，看代码才知道是Vue.$device.

不清楚router和resource的命名方式是不是Vue的惯例。

**Comment by airyland** [comment]
这个暂时没有规范。
按照你说的按其他插件的做法确定是`Vue.device`比较合适。现在兼容一下在rc版本中该插件上两种写法都支持，然后在正式版本中移除和文档中提示只支持`Vue.device`。

明天小版本解决。
