### ISSUE TITLE
手动引入vux，在main.js出现异常

### ISSUE THREAD

**Issue by chenguose** [airyland/vux#913]
### Version
2.1.0-rc.48
### Android or iOS
browser
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
//在 main.js 中只有下面一句代码，引入插件
import { LoadingPlugin} from 'vux'
```
编译后在pc浏览器上面就报：
Uncaught SyntaxError: Unexpected token import(…)

webpack.base.conf.js文件已经按要求加上
``` html
const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [
    {
      name: 'duplicate-style'
    },
    {
      name: 'vux-ui'
    }
  ]
})
```
我试过在App.vue引入，没报错。

**Comment by airyland** [comment]
不确定你的问题，你确定你 webpack 里配置了`babel`解析 js了?
我直接从 vue 的 webpack 模板引用 vux 也没有报错。

**Comment by airyland** [comment]
可以把其他业务代码删掉，保留入口和配置，打包一份发我邮箱。

**Comment by chenguose** [comment]
可以了，我新建了一个vue模板，引进去就可以了。谢谢！
