### ISSUE TITLE
引入swiper组件报错

### ISSUE THREAD

**Issue by RenShine** [airyland/vux#914]
我的vux和vue等版本信息
`"vue": "^2.1.10",
    "vue-router": "^2.2.0",
    "vux": "^2.1.0-rc.48",
    "vux-loader": "^1.0.35"`

我的报错信息

![image](https://cloud.githubusercontent.com/assets/6385962/22922841/2f2f4d30-f2da-11e6-8b15-520ddfc4714b.png)

我的代码：

template:

`  <Swiper :list="imgList" show-desc-mask="false" auto="true" loop="true"> </Swiper>`

js：

```import SearchFromCity from 'components/SearchFromCity';
  import { Swiper} from 'vux';
  export  default {
      name: 'home',
      components: {
          SearchFromCity,
          Swiper
      },
      data() {
          return {
             //轮播图list
             imgList: [],

          }
      },
      methods: {
          search(result) {
               //点击搜索按钮后触发该事件
          }
      }
  }
```

**Comment by airyland** [comment]
不是 vux 的问题，仔细看报错，vue2规定template下只能有一个根元素，你用一个 div 包起来吧。
