### ISSUE TITLE
group-title组件内缺少样式

### ISSUE THREAD

**Issue by Kyncc** [airyland/vux#916]
### 版本RC48

[group-title](https://github.com/airyland/vux/blob/v2/src/components/group-title/index.vue)

### 问题

样式是从group组件带过来的
得引入group和group-title一起才行

**Comment by airyland** [comment]
这个组件其实是想废弃的。感觉比较鸡肋。

**Comment by Kyncc** [comment]
别啊 能少写点CSS 感觉可以做内部标题 Orz
