### ISSUE TITLE
新手，根据官网安装了vue init airyland/vux2 project，在App.vue中引用vux组件，js报错

### ISSUE THREAD

**Issue by zhump** [airyland/vux#919]
代码如下：
![image](https://cloud.githubusercontent.com/assets/7962067/22935163/ad822bf8-f30c-11e6-8e9e-2b86adfa527e.png)
保存信息如下：
![image](https://cloud.githubusercontent.com/assets/7962067/22935182/c3e3a926-f30c-11e6-897f-f7c167fe8848.png)
但是从components/HelloFromVux.vue中引用vux组件，是不会报错的，这是为什么，我需要做哪些配置吗

**Comment by airyland** [comment]
看清楚错误，这是eslint错误。你引入了Tabbar变量却没有使用。

**Comment by zhump** [comment]
我又折腾了一下 export default  一下 好了，不好意思啊 ，，，
