### ISSUE TITLE
Group 组件

### ISSUE THREAD

**Issue by mice33** [airyland/vux#926]
vux:2.1.0-rc.28

![image](https://cloud.githubusercontent.com/assets/4945433/22965695/c20c3932-f399-11e6-96d7-acc869982bd6.png)

如图， 怎么能让 weui_cells 生成 scoped 标识 

`
<template>
    <div>
        <group class="loginFrom" label-width="120px" label-margin-right="40px" label-align="right">
            <x-input title="姓名" name="username" placeholder="请输入真实姓名"></x-input>
            <x-input title="手机号" name="username" placeholder="请输入11位手机号"></x-input>
            <x-input title="身份证号" name="username" placeholder="请输入身份证号"></x-input>
        </group>
    </div>
</template>

<script>
    import { XInput, Group, XButton, Cell } from 'vux';

    export default {
        components: {
            XInput,
            XButton,
            Group,
            Cell
        }
    };
</script>

<style scoped lang="less">
    .loginFrom {
        .weui_cells {
            &:after {
                display:none;
            }

            &:before {
                display:none;
            }
        }

        .weui_cell {
            &:before {
                display:none;
            }
        }
    }
</style>

`

**Comment by airyland** [comment]
非vux问题，更像是vue-loader的问题。
