### ISSUE TITLE
x-input只支持type="text",怎么没有type="tel"or type="number"？

### ISSUE THREAD

**Issue by winglau14** [airyland/vux#930]
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```

**Comment by winglau14** [comment]
update

**Comment by airyland** [comment]
type=number是支持的。如果你不能使用说明你vux版本太低。

**Comment by airyland** [comment]
下个小版本支持 `tel`

**Comment by winglau14** [comment]
2.1.0-rc.28这是我用的版本
