### ISSUE TITLE
同样的代码 window下是好的，mac上报错显示不出来，求教？

### ISSUE THREAD

**Issue by zhump** [airyland/vux#931]
![image](https://cloud.githubusercontent.com/assets/7962067/22976347/63f41d48-f3c5-11e6-838e-93ffe996f433.png)
![image](https://cloud.githubusercontent.com/assets/7962067/22976408/af5d4fca-f3c5-11e6-8ddf-b10bb53ff9fe.png)

**Comment by airyland** [comment]
用npm重新安装依赖。cnpm可能会有问题。

npm install --registry=https://registry.npm.taobao.org

**Comment by zhump** [comment]
果然可以了 多谢
