### ISSUE TITLE
XButton 的 click 事件无法触发

### ISSUE THREAD

**Issue by raxxarr** [airyland/vux#935]
### Version
^2.1.0-rc.48
### Android or iOS
Chrome
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
x-button(plain, type='primary', text='登录', @click='submit($event)')
...
methods: {
    submit () {
      console.log('click')
  }
}
```

### Expected behavior and actual behavior.
没触发 submit 事件

**Comment by airyland** [comment]
vue2 规定组件上的点击使用 `click.native`

**Comment by raxxarr** [comment]
自己没弄明白，多谢
