### ISSUE TITLE
china_address.json 数据缺失

### ISSUE THREAD

**Issue by bradliu** [airyland/vux#938]
china_address.json 缺少 "九龍城區", "花地瑪堂區", .... 的父级地址810000(香港), 820000(澳門)

**Comment by airyland** [comment]
内置地址特意不包含特别行政区，一般用不到。。

**Comment by bradliu** [comment]
@airyland 嗯, 导入的时候发现找不到他们子级区域的parent.

**Comment by zhump** [comment]
哪里有全部的数据，包含特别行政区的？
我感觉。。楼主@airyland 这样做。。是不是有点那啥了。很多场景是需要的。比如出游，保险，店面地址，等等。。。
而且这边城市选择应该可以优化，目前的城市数据太大了，其实没必要有value，parant，直接用嵌套表明层级就好了。
从300k 可以节省到 45k 左右。
http://www.light7.cn/dist/js/light7-city-picker.js

**Comment by airyland** [comment]
@zhump 
可 pr。自己需求并不会用到，因此也不会特意加。
列表数据可以自定义，或者用 popup-picker 封装一个即可。

设计时认为，扁平比嵌套更方便生成和检索结构化数据，尤其是多级数据的场景下。
