### ISSUE TITLE
scroller列表显示不全

### ISSUE THREAD

**Issue by ericwang1902** [airyland/vux#939]
![image](https://cloud.githubusercontent.com/assets/7867163/23020233/14e04a94-f481-11e6-82ae-7a15d3f1c718.png)
![image](https://cloud.githubusercontent.com/assets/7867163/23020238/193b2686-f481-11e6-92e4-5222b03b7875.png)
 for循环是到50，而列表最多显示到18，上拉到底可以看到50，但是回弹之后还是18；如果设置 bounce=false，就直接显示的是18。
请问这是bug吗？

**Comment by zhonggedan** [comment]
@ericwang1902  这个问题 我也发现 ，不管在哪里调用reset() 都没有效果，请问你解决了吗？
