### ISSUE TITLE
scroller里面嵌套swiper滚动的问题

### ISSUE THREAD

**Issue by nowui** [airyland/vux#94]
现在的问题是左右滑动swiper的时候，scroller能上下滑动。我想实现只能一个方向的滑动应该怎么实现呢？谢谢了！

代码如下：

**Comment by airyland** [comment]
不要完全忽略issue template直接提issue, 代码应该写在在 ``` html 里

**Comment by nowui** [comment]
<scroller lock-x scrollbar-y style="width:100%;height:100%;">
            <div class="box2">
                <swiper  :list="list" direction="horizontal" auto></swiper>
                <p v-for="i in 80">占位 {{i}}</p>
            </div>
        </scroller>

**Comment by nowui** [comment]
还有就是swiper怎么实现无限循环呢

**Comment by airyland** [comment]
swiper 是很轻量的实现，暂时没有支持这一个。可能这个更适合你的需求：https://github.com/nolimits4web/Swiper

**Comment by airyland** [comment]
我重现了你说的情况，在scroller里嵌套swiper比较奇怪，手势确实会冲突。把swiper放到scroller外面呢？

**Comment by nowui** [comment]
我找到一个例子：http://1.airpal.applinzi.com/#
我就是想实现它里面的功能，就是页面有一个下拉刷新功能，然后里面还有一个swiper

**Comment by wenxiangtune** [comment]
我觉得无限循环最好支持一下，不然上下自动滚动时，有切换的BUG。

**Comment by airyland** [comment]
@wenciangtune 你们问的不是同一个问题 swiper暂时不支持上下滑动 复杂的考虑直接用另外的Swiper项目
