### ISSUE TITLE
switch应该搞个true-text/false-text，这个比inline-desc属性好

### ISSUE THREAD

**Issue by erguotou520** [airyland/vux#941]
还有true-value/false-value，类似vue里的语法
如果因为weui的样式问题而不好加的话另说

**Comment by airyland** [comment]
没计划

**Comment by erguotou520** [comment]
好吧 目前看来只能css hack了

**Comment by airyland** [comment]
这两个都复杂化了，值规定只有true, false，这是规范，太宽松容易出问题。移动端不适合还在按钮上再加文字，按钮的样式表意已经足够了。

**Comment by erguotou520** [comment]
性别 男/女切换的场景，虽然可以通过改变title
