### ISSUE TITLE
scroller的pullupStatus在筛选条件改变后无法重置

### ISSUE THREAD

**Issue by w2819** [airyland/vux#942]
如题，进入页面上拉加载新数据，上拉到最后一页设置pullupStatus为disabled，更改筛选条件，重置pullupStatus为default，上拉刷新依旧不可用。

**Comment by airyland** [comment]
你已经设为disabled，难道不应该先enabled?

**Comment by w2819** [comment]
哦哦，我理解错了，谢谢
