### ISSUE TITLE
关于页面切换延迟显示loading

### ISSUE THREAD

**Issue by wg5945** [airyland/vux#943]
### Version
2.1.0-rc.51
### Android or iOS
All

帮助文档中说：

> 如果你觉得在加载比较快时Loading组件一闪而过体验也不大好，那么你可以延迟设置loading=false。

1、这边应该是延迟设置loading=true吧？

2、如果延迟设置loading=true

` setTimeout(() => {
  store.commit('updateLoadingStatus', {isLoading: true})
}, 20)
`

如果加载较快，有可能先进入router.afterEach，致使先执行loading=false，然后再loading=true，这时候loading就不会消失了，是否还需要再设定一个状态标记是否进入router.afterEach？

**Comment by airyland** [comment]
一闪而过就是关闭快了，为什么要设置loading=true?

**Comment by wg5945** [comment]
不是关闭的情况下，是指页面之前的切换

现在每个页面进入都会有loading，对于大部分加载比较快的情况下不希望出现这个loading，只是希望在加载比较慢的情况下才出现

**Comment by airyland** [comment]
我们说的是同一件事件，你这个实际上复杂化了。你希望加载慢时才出现loading，但是这个加载时间无法评估，就会出现你说的情况。文档中指的是无论快慢都延迟一会再关闭loading，这是最简单实用的方式。

按你的想法的话，你可以再加个标识来标识是否已经进入新路由，如果是那么在延迟逻辑里就不commit了。
