### ISSUE TITLE
【公告】VUX 在 2.1.0 正式版本升级到 WeUI@1.x，使用了类名进行样式覆盖的同学请注意

### ISSUE THREAD

**Issue by airyland** [airyland/vux#945]
WeUI 从 1.x 版本变更了命名规范(BEM)，所以如果你当前使用了类名来做样式覆盖，升级到 2.1.0 时需要根据 WeUI 文档进行类名修改。

但是比较推荐的做法是使用`vux-loader`提供的`less-theme`插件进行全局变量定义，这样能保证在各种升级过程中样式覆盖都不会受影响。

如果你需要的`less`变量暂未提供，可以在本issue提出。

**Comment by Kyncc** [comment]
大概在什么时候会发呢？

**Comment by guntertien** [comment]
把github上的vux 2.0的图标换成那个金黄色的，现在还是黑色的那个。嘿嘿😝

**Comment by w2819** [comment]
#932 出了个新问题，替换单位做法，@import进来的less文件没有做替换

**Comment by airyland** [comment]
@327326724 明确一点，什么是import进来的文件？

**Comment by w2819** [comment]
vux组件里面import的less文件。比如alert组件里面的`'../../styles/weui/widget/weui_tips/weui_dialog'`这个文件还是被转化了

**Comment by airyland** [comment]
@327326724 我不知道你怎么配置 的，after-less-parser 就是为了处理这部分less的文件。事实上几乎每个组件都是import的less代码，如果有问题的话是所有组件都会被转化，而我上次已经测试过并没有这个问题。

**Comment by w2819** [comment]
```js
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: [
    {
      name: 'vux-ui'
    },
    {
      name: 'duplicate-style'
    },
    // {
    //   name: 'less-theme',
    //   path: 'src/styles/theme.less'
    // },
    {
      name: 'after-less-parser',
      fn: function (source) {
        console.log(source)
        if  (this.resourcePath.replace(/\\/g, '/').indexOf('/vux/src/components') > -1) {
          source = source.replace(/px/g, 'PX')
        }
        return source
      }
    },
    {
      name: 'style-parser',
      fn: function (source) {
        if (this.resourcePath.replace(/\\/g, '/').indexOf('/vux/src/components') > -1) {
          source = source.replace(/px/g, 'PX')
        }
        return source
      }
    }
  ]
})
```
inline-calendar这个组件样式是写在组件内的，这个组件显示正常，但是alert这种import的less文件还是被转化了

**Comment by airyland** [comment]
代码不是这样逐行加格式化的。。你没用过 ``` js 这样的多行写法吗。。

vux-loader版本号多少

**Comment by 327326724** [comment]
没用过，不好意思，我改一下，是我版本的问题，麻烦了···

**Comment by 327326724** [comment]
"vux-loader": "^1.0.39",版本是对的，确实被转化了

**Comment by 327326724** [comment]
vux-loader版本是对的，验证过了，确实被转化了

**Comment by w2819** [comment]
vux-loader版本是`"vux-loader": "^1.0.39",`，alert组件确实被转化了，麻烦再看一下

**Comment by airyland** [comment]
@327326724 你上个审查元素的截图，我今天有空再测试一下。

**Comment by 327326724** [comment]
![Uploading aa.png…]()

**Comment by w2819** [comment]
图片实在是上传不上来，一直失败。
我把css贴一下
```css
.weui_dialog_ft {
    position: relative;
    line-height: 2.1rem;
    margin-top: 1rem;
    font-size: 0.85rem;
    display: flex;
}
```
变成这样了，calendar的没有被转化

**Comment by w2819** [comment]
有空看下吗？不好意思，实在是着急发布···谢谢了

**Comment by greedying** [comment]
不错。看来我的上传组件也要同步更新了

**Comment by airyland** [comment]
@327326724 我理解你很急，但是我并没有义务挤时间来给你加急解决问题。有问题希望自己先调试。事实上我再次测试了下并没有任何问题。

![image](https://cloud.githubusercontent.com/assets/559179/23244338/6877425a-f9bf-11e6-99e9-bf1237d60827.png)

**Comment by w2819** [comment]
麻烦了。我用的vue init airyland/vux2 projectPath初始化的工程，配置后确实是翻译了。我先看看是不是webpack哪里影响了

**Comment by airyland** [comment]
@327326724 跟你道个歉，你的问题是因为没有使用less-theme的变量功能导致vux-loader不会append一个after-less-parser的处理插件。而我测试时的本地模板都是带less-theme功能的，因此一直都是正常的，当然如果你去调试一下vux-loader应该也可以发现这个bug。你可以升级到 vux-loader@1.0.42测试，有问题再反馈。

**Comment by w2819** [comment]
没事哦，谢谢帮我解决了问题，我对webpack没有深入的了解，所以vux-loader这些插件我也不是很会调试

**Comment by jianchengwang** [comment]
之前使用airyland/vux2初始化项目，vux版本是2.0.1的，然后现在想更新到2.1.1-rc.4，需要进行什么操作，package.json哪些包需要进行配置升级 @airyland

**Comment by airyland** [comment]
@janchengwang 直接升级 vux 就行。只是组件内类名规范变了，如果你没有使用组件内部类名来进行样式覆盖完全没影响。

**Comment by jianchengwang** [comment]
ERROR  Failed to compile with 1 errors

 error  in ./~/vux/src/styles/1px.less

Module build failed: Unknown word (23:5)

  21 | .vux-1px {
  22 |   &:before {
> 23 |     .setLine();
     |     ^
  24 |   }
  25 | }
  26 | 
` 
我出现这个错误 @airyland

**Comment by jianchengwang** [comment]
现在好了，之前
` <style>
@import '~vux/src/styles/1px.less';`
现在
` <style lang="less">
@import '~vux/src/styles/reset.less';
@import '~vux/src/styles/1px.less';`
就好了
