### ISSUE TITLE
Actionsheet的小建议。

### ISSUE THREAD

**Issue by wuchuguang** [airyland/vux#950]
我是看着vux成长的。但最近才开始使用vux，感谢开源这么好的库。

Actionsheet组件使用起来，觉得可以如下改进。
props:menus,
类型 兼容Array,因为Object对于menus实在太单一了。
兼容了Array,
我们menus = [
{label:"标题",value:"值",type:  'primary | success | warning | danger | info | default text' , disabled:true | default false  }
]

谢谢。

**Comment by airyland** [comment]
Array 类型可以支持，但是这些`primary | success | warning | danger | info | default text`属于过度分类，只会支持类似button的primary,warn,default, info。

**Comment by airyland** [comment]
在 v2.1.0 支持。
