### ISSUE TITLE
x-button点击事件不响应

### ISSUE THREAD

**Issue by 0xfnzero** [airyland/vux#951]
vux版本: 2.1.0-rc.51
浏览器: pc端chrome，iOS微信端
问题: x-button按钮点击事件无法响应，html原生按钮却可以
代码如下:
![2304b3d3-31fd-46d5-a133-1f306d224e85](https://cloud.githubusercontent.com/assets/2081812/23092604/4bea8a3e-f609-11e6-9d7b-3701f193b811.png)

**Comment by airyland** [comment]
😓  
Vue2 规定组件点击事件使用 @click.native
