### ISSUE TITLE
Search组件输入为空时点击cancel不触发事件on-cancel

### ISSUE THREAD

**Issue by kangfenmao** [airyland/vux#955]
### Version
2.1.0-rc.51

### Android or iOS
iOS，Chrome

### Codes 

```
<search
        @on-change="getResult"
        @on-touch="showHotSearchs"
        @on-cancel="hideHotSearchs"
        @on-submit="setKeywords"
        :placeholder="keywords"
        :results="suggestions"
        v-model="searchInput">
</search>
```

### Steps to reproduce the problem
* 点击搜索框
* 点击取消按钮后on-cancel没有被触发

**Comment by airyland** [comment]
试了下无法重现，源码中只要点击cancel按钮就必定触发on-cancel

**Comment by linsywu** [comment]
![image](https://cloud.githubusercontent.com/assets/15061856/23935371/a8291f8c-0986-11e7-9115-4b065298b8c8.png)
![image](https://cloud.githubusercontent.com/assets/15061856/23935391/bdc9d73c-0986-11e7-83c4-3db51123e6a4.png)
![image](https://cloud.githubusercontent.com/assets/15061856/23935392/bf26a2c2-0986-11e7-80d4-b21614ee61c5.png)
使用search组件，  on-cancel和on-focus事件都没有响应？

**Comment by airyland** [comment]
@linsywu 你看到的版本号不是精确的版本号，进入 node_modules/vux/package.json 看

**Comment by linsywu** [comment]
@airyland 
![image](https://cloud.githubusercontent.com/assets/15061856/23938303/ba705a60-0996-11e7-96fe-2a61de15e48d.png)
 这个版本的，貌似就只有那两个事件不行，别的都是可以的

**Comment by airyland** [comment]
@linsywu 直接升级到最新的 rc 版本吧。
