### ISSUE TITLE
vux的scroller部分属性没有立即更新问题

### ISSUE THREAD

**Issue by musclejack** [airyland/vux#957]
版本 "vux": "^2.1.0-rc.28"

scroller组件里，
`<scroller` lock-x scrollbar-y 
                height="-98px" ref="scroller"
                :use-pulldown = "usePullDown"
                :use-pullup = "usePullUp"
                :pulldown-config = "pullDownConfig"
                :pullup-config = "pullUpConfig"
                @on-pulldown-loading = "onPulldown"
                @on-pullup-loading = "onPullup"
                >
</scroller>`
这些属性只在第一次传入的时候使用，源码是mounted的时候使用过一次
并不能实现改变父组件的值就更新相应的方法
带来的不便主要是不能随时改变props的值来获取相应的状态
如： ：use-pullup 一开始为true，可以下拉加载，然后我加载到数据库没消息了，我设置为false，这时候还是可以下拉加载

**Comment by airyland** [comment]
目前可以使用 disablePullup 和 enablePullup 函数来设置。

**Comment by airyland** [comment]
scroller是个很耗性能的组件，大部分属性能不响应就不做响应了。

**Comment by musclejack** [comment]
这两个函数好像没有文档，然后其实做一下判断而已，性能不会很明显的吧

**Comment by musclejack** [comment]
认真看了下源码，发现了这两个函数

**Comment by musclejack** [comment]
问题可关闭
