### ISSUE TITLE
Tab组件是否能支持上下两排（或者同一排可以滑动选择）在同一个tab内管理？

### ISSUE THREAD

**Issue by Ignorantforce** [airyland/vux#960]
![image](https://cloud.githubusercontent.com/assets/22272002/23116050/677f01c8-f783-11e6-8669-b0ef127163be.png)
如图所示，因为tag较多，一排4个中文字符的话，极限其实是5个tag，不知道是否能支持上下两排在同一个tab或者在同一排但是支持滑动呢？

**Comment by airyland** [comment]
外层div设置overflow:scroll就行了。内部自己设置一个足够长的宽度就可以滑动了。

https://github.com/airyland/vux/blob/v2/src/demos/Tab.vue#L12-L13

**Comment by Ignorantforce** [comment]
@airyland 非常感谢作者这么快就给了回应，你这个例子我之前已经看过了，当时用了DEMO的代码看了下效果，并且隐藏了滚动条（-webkit-scrollbar{width:0px}），这是我当前的选择方案。
我的原意可能是想说 vux能否本身支持多排 或者 当 tab比较多的话会自动能滑动选择。
PS：我是一个后端开发人员，所以对前端这些不是很明白。

**Comment by airyland** [comment]
一个tab多排就不美观了。
你说的自动滑动选择是什么意思？

**Comment by Ignorantforce** [comment]
大概意思是 假如目前有5个tab的时候（每个tab包含4个中文）是刚刚好，假如tab增加到6个或者更多个的时候，vux本身会自适应把这个tab变成可滑动这样子（也就是你说手工在外层div加个overflow:scroll）。

总之谢谢你了。

**Comment by airyland** [comment]
实际上不行，因为要计算总宽度，那么屏幕宽度要计算，文字宽度要计算，而用户想要的间隙也不确定，所以更适合用户端去判断和实现。

**Comment by Ignorantforce** [comment]
好的，了解了
