### ISSUE TITLE
XNumber 样式问题

### ISSUE THREAD

**Issue by leecz** [airyland/vux#961]
### Version
"vue": "^2.1.10",
"vux": "^2.1.0-rc.51"

### Android or iOS
Chrome Pc

### Your Codes 

``` html
    <group>
      <x-number title="数量" :value="1" :min="1"></x-number>
    </group>
```

### Expected behavior and actual behavior.
样式错乱，与 Demo 的不一致

**Comment by airyland** [comment]
Sorry, 难以凭空想象如何错乱。

**Comment by leecz** [comment]
![xnumber-style](https://cloud.githubusercontent.com/assets/4048165/23123246/94b3aec2-f7a2-11e6-8562-0303bd065c37.jpeg)
就像这样

**Comment by leecz** [comment]
你是 7 * 24 吗？回答好快，👍

**Comment by airyland** [comment]
怀疑有样式冲突，你审查一下相应元素的样式看看

**Comment by leecz** [comment]
有不一样，
这是demo的元素：
![demo-number](https://cloud.githubusercontent.com/assets/4048165/23125391/6e9c302e-f7ac-11e6-89a5-3617adac489d.jpeg)

这是我的代码生成的元素：
![my-code-html](https://cloud.githubusercontent.com/assets/4048165/23125400/7dbf6a1c-f7ac-11e6-9a55-33983670f39b.jpeg)

感觉我的代码生成的和x-number 的源码结构一致，不知道为什么会和 demo 的不同

**Comment by airyland** [comment]
这应该不是原因。。因为线上demo是最新代码，2.1.0将要发布。
你看看a和svg有没有样式影响。

**Comment by leecz** [comment]
更新了 2.1.0 还是有这个问题，
感觉可能跟浮动有关，不知道是不是没有清除浮动的原因。
然后有个疑问，这里为什么会用到 浮动？用flex应该更方便吧

**Comment by airyland** [comment]
@leecz 历史实现原因。因为demo是没问题的，所以还是你本地样式冲突导致的。

**Comment by leecz** [comment]
好吧，这就尴尬了。。。

**Comment by leecz** [comment]
找到原因了， 跟 reset 有关，

我的代码里有这段：

```js
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```

不过不知道具体是在哪里改变了 box-sizing ，哎。。。

**Comment by leecz** [comment]
```html
  <x-number title="数量" :value="1" :min="1"  style="box-sizing: content-box;"></x-number>
```
这样 hack 了下，解决问题。

**Comment by jjjachyty** [comment]
@leecz  我加了还是没变 一样的错位

**Comment by leecz** [comment]
@jjjachyty 额，默认是不用加的，如果你有类似我上面那种 reset ，就可能要加了。

**Comment by jjjachyty** [comment]
@leecz  我加了 reset 修改了原生 样式 把字体改小了

**Comment by leecz** [comment]
嗯，你要根据实际情况来吧，理解那些代码，修改这些全局的东西，影响是很大的，要小心。

**Comment by jjjachyty** [comment]
@leecz 未修改原生的 我是拷贝出来改的 放到scoped里面了
