### ISSUE TITLE
scroller组件筛选时内容高度变化，调用reset仍然是原高度

### ISSUE THREAD

**Issue by sixiakun** [airyland/vux#962]
vux 2.0.13
chrome模拟开发，iPhone模拟
初始获取数据，使用了pullup，![image](https://cloud.githubusercontent.com/assets/20946763/23122497/66c9870a-f79f-11e6-9ef9-e155c0347c96.png)
更换筛选条件，获取的只有一个数据，调用了
![image](https://cloud.githubusercontent.com/assets/20946763/23122566/ab40d6fe-f79f-11e6-825a-3c050bed5dd5.png)，还是有很长的滚动条
![image](https://cloud.githubusercontent.com/assets/20946763/23122582/bfcaf6e0-f79f-11e6-85b0-213f3ae9b4a8.png)，请问是有重新计算高度的方法吗

**Comment by airyland** [comment]
就你上的代码而言，并不能确定你是否正确地在数据获取到后才进行reset。

**Comment by sixiakun** [comment]
代码未优化，写的有点乱，不过确实是获取后调用的，请指点。。
methods:{
      hideFilter (cond,subm) {
        this.$emit('hideFilter')
        if(subm) $.extend(this.condition, cond)
        this.offset = 0;
        this.showLd = true;
        this.hasNext = true;
        this.$refs.list.enablePullup()
        this.loadData(this.reset(true),true)
      },
      getDefault () {
        this.$http.get('/merp.h5/api/base/warehouse/default').then(res=>{
          this.condition.warehouses = res.data.id;
          this.loadData()
        })
      },
      loadData (reset,notAdd) {
        this.$http.get('/merp.h5/api/stock/list/item',{
          params:{
            category: this.condition.category||null,// 分类
            brand: this.condition.brand||null,// 品牌
            warehouses: this.condition.warehouses,// 仓库
            storageName: null,
            keyword: null,
            offset: this.offset,
            limit: 20,
            // 只显示预警
            warn: false,
            _s:this.$store.state.session
          }}).then(res=>{
            if(!res.data.datas[0]){
              this.showErr = true
              this.errMsg = '没有数据'
            }
            this.showLd = false;
            if(notAdd) this.data = res.data.datas
            else this.data = this.data.concat(res.data.datas);
            this.offset += res.data.limit;
            if(!res.data.hasNext){
              this.$refs.list.disablePullup()
              this.hasNext = false
            }
            if (reset) reset()
          }).catch(err=>{
            this.showErr = true
            this.errMsg = err;
          })
      },
      infiniteData(){
        this.loadData(this.reset)
      },
      reset(backT){
        if(backT)this.$nextTick(()=>{
          this.$refs.list.reset({top:0})
        });
        else{
          this.$refs.list.donePullup()
          this.$nextTick(this.$refs.list.reset);
        }
      }

**Comment by airyland** [comment]
代码也太没有可读性了，自行格式化吧。


<pre>``` js</pre>
<pre>``` </pre>

**Comment by sixiakun** [comment]
不会用markdown，有点苦逼，一个个空格敲上去。。，请指点
methods:{
&nbsp; hideFilter (cond,subm) {
&nbsp; &nbsp; this.$emit('hideFilter')
&nbsp; &nbsp; if(subm) $.extend(this.condition, cond)
&nbsp; &nbsp; this.offset = 0;
&nbsp; &nbsp; this.showLd = true;
&nbsp; &nbsp; this.hasNext = true;
&nbsp; &nbsp; this.$refs.list.enablePullup()
&nbsp; &nbsp; **this.loadData(this.reset(true),true)**
&nbsp; },
&nbsp; getDefault () {
&nbsp; &nbsp; this.$http.get('/merp.h5/api/base/warehouse/default').then(res=>{
&nbsp; &nbsp;&nbsp;  this.condition.warehouses = res.data.id;
&nbsp; &nbsp;&nbsp;  this.loadData()
&nbsp; &nbsp; })
&nbsp; },
&nbsp; loadData (reset,notAdd) {
&nbsp; &nbsp; this.$http.get('/merp.h5/api/stock/list/item',{
&nbsp; &nbsp; params:{
&nbsp; &nbsp; &nbsp; category: this.condition.category||null,// 分类
&nbsp; &nbsp; &nbsp; brand: this.condition.brand||null,// 品牌
&nbsp; &nbsp; &nbsp; warehouses: this.condition.warehouses,// 仓库
&nbsp; &nbsp; &nbsp; storageName: null,
&nbsp; &nbsp; &nbsp; keyword: null,
&nbsp; &nbsp; &nbsp; offset: this.offset,
&nbsp; &nbsp; &nbsp; limit: 20,
&nbsp; &nbsp; &nbsp; // 只显示预警
&nbsp; &nbsp; &nbsp; warn: false,
&nbsp; &nbsp; &nbsp; _s:this.$store.state.session
&nbsp; &nbsp; }}).then(res=>{
&nbsp; &nbsp; &nbsp; if(!res.data.datas[0]){
&nbsp; &nbsp; &nbsp;&nbsp;  this.showErr = true
&nbsp; &nbsp; &nbsp; &nbsp; this.errMsg = '没有数据'
&nbsp; &nbsp;&nbsp;  }
&nbsp; &nbsp; &nbsp; this.showLd = false;
&nbsp; &nbsp; if(notAdd) this.data = res.data.datas
&nbsp; &nbsp; else this.data = this.data.concat(res.data.datas);
&nbsp; &nbsp; &nbsp; this.offset += res.data.limit;
&nbsp; &nbsp; &nbsp; if(!res.data.hasNext){
&nbsp; &nbsp; &nbsp; &nbsp; this.$refs.list.disablePullup()
&nbsp; &nbsp;&nbsp;  this.hasNext = false
&nbsp; &nbsp&nbsp; ; }
&nbsp; &nbsp; &nbsp; **if (reset) reset()**
&nbsp; &nbsp; }).catch(err=>{
&nbsp; &nbsp;&nbsp;  &nbsp; this.showErr = true
&nbsp; &nbsp;&nbsp;  &nbsp; this.errMsg = err;
&nbsp; &nbsp; })
&nbsp; },
&nbsp; infiniteData(){
&nbsp; &nbsp; this.loadData(this.reset)
&nbsp; },
&nbsp; reset(backT){
&nbsp; &nbsp; if(backT)this.$nextTick(()=>{
&nbsp; &nbsp; &nbsp; **this.$refs.list.reset({top:0})**
&nbsp; &nbsp; });
&nbsp; &nbsp; else{
&nbsp; &nbsp; &nbsp; this.$refs.list.donePullup()
&nbsp; &nbsp; &nbsp; this.$nextTick(this.$refs.list.reset);
&nbsp; &nbsp; }
&nbsp; }

**Comment by sixiakun** [comment]
试了下 ，第一次数据少高度还是那么高，再请求数据少的就没有那么高了
