### ISSUE TITLE
用了线上最新的 2.1 RC 51，cell 列表跑版

### ISSUE THREAD

**Issue by langqixu** [airyland/vux#963]
![wechatimg512](https://cloud.githubusercontent.com/assets/423731/23137442/fabec97e-f7dc-11e6-961d-773780e120a0.jpeg)

如图所示。cell组件value过长时，会导致左侧跑版。

**Comment by airyland** [comment]
cell内容过长也许就说明你这不适合放cell里展示。。

**Comment by airyland** [comment]
决定出一个很简单的组件`cell-box`，和`cell`相比只提供箭头，其他完全自定义，一定程序上比`card`更为自由和灵活。
