### ISSUE TITLE
有没有考虑加入wepayui的组件

### ISSUE THREAD

**Issue by dmm33** [airyland/vux#964]
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
```

**Comment by airyland** [comment]
大部分就是 WeUI 组件，其他的考虑一下在下个版本加。

**Comment by dmm33** [comment]
太好了，wepayui里面有很多支付的界面我们在用，很分散，在集中在这里就更好了。感谢作者。
