### ISSUE TITLE
Android 4.4.2/4.3 页面空白

### ISSUE THREAD

**Issue by luckyWK** [airyland/vux#966]
vux版本：2.1.0-rc51

在android 4.4.2下发现页面空白问题

测试android 4.4.4 没有问题

android 4.3 下也空白

![image](https://cloud.githubusercontent.com/assets/6001042/23154196/8ccc5024-f847-11e6-96e0-c6f7471ad96b.png)

**Comment by airyland** [comment]
应该是promise 在4.4 下不支持。demo 没有上polyfill导致的。刷新再试试。
