### ISSUE TITLE
使用Tabbar的时候报异常，Cannot find module "../badge"。

### ISSUE THREAD

**Issue by Ignorantforce** [airyland/vux#968]
是通过 最简单的webpack-simple引入Vux。
按照首页引导安装更新，目前为止使用了一些其他组件都可以正常显示，刚刚引入tabbar的时候报异常。
![image](https://cloud.githubusercontent.com/assets/22272002/23194563/ca2ee240-f8e9-11e6-9ef3-55251c4930f0.png)

vux版本：2.1.0-rc.48
----------------------------------
使用快速入门推荐的模板初始化项目的话，tabbar可以正常使用。

**Comment by airyland** [comment]
webpack 配置 extension没？应该缺少.vue了，你可以对比下webpack模版

**Comment by airyland** [comment]
``` js
resolve: {
    extensions: ['.js', '.vue', '.json'],
```

**Comment by Ignorantforce** [comment]
好的，谢谢！原因是缺少了你说的。
