### ISSUE TITLE
日期选择，各种滑动支持PC微信浏览器吗？

### ISSUE THREAD

**Issue by docikaci** [airyland/vux#969]
基于微信的开发很难不让用户在PC微信浏览器打开啊？

![image](https://cloud.githubusercontent.com/assets/7788102/23195282/701631e2-f8ed-11e6-9d16-d108abcdc3d1.png)
![image](https://cloud.githubusercontent.com/assets/7788102/23195289/81b90528-f8ed-11e6-8ae0-b3820988c272.png)

**Comment by docikaci** [comment]
兼容下能选就行    绝逼完美了

**Comment by airyland** [comment]
暂时不支持。精力有限，欢迎PR。
