### ISSUE TITLE
input表单maxlength属性设置

### ISSUE THREAD

**Issue by Ge-yuan-jun** [airyland/vux#97]
工作中需要用到`input`表单的`maxlnegth`属性，看了一下您的源码，`prop`中设置了`max`以及`min`属性，会有提示，但是不能防止用户继续键入字符。我能否提一个建议，加上`maxlength`属性设置。
好几次表单验证，产品都提出超过一定字符后不能键入新的字符这个需求 

``` html
<input class="weui_input" :type="type" :maxlength='maxlength' :pattern="pattern" placeholder="{{placeholder}}" v-model="value" @blur="blur" v-el:input/>
```

**Comment by airyland** [comment]
max 即 maxlength

**Comment by Ge-yuan-jun** [comment]
好的，我明白您的意思了。你这边是比较“弹性”的设置，比较适合公用。我打算自己在您的代码上面自己加上`maxlength`属性

**Comment by dsonet** [comment]
@airyland 这里的min,max不太符合直觉思维。总是会认为这两个是限定数字范围的。
而input本身有minlength 和maxlength, 做长度限定则使用那两个属性更合理。
