### ISSUE TITLE
datetime组件可以增加配置将年月日放到一起滚动吗？

### ISSUE THREAD

**Issue by w2819** [airyland/vux#970]
增加一个配置将年月日放到一起滚动，类似mobiscroll插件增加`dateWheels: '|MM dd DD|',`配置

**Comment by airyland** [comment]
没明白你说的。给个示例页面？

**Comment by w2819** [comment]
不知道为啥，图片上传不上去，一直失败

**Comment by w2819** [comment]
https://demo.mobiscroll.com/v3/datetime#demo=datetime

**Comment by airyland** [comment]
你是指支持鼠标滚轮滑动么？

**Comment by w2819** [comment]
年月日三个滚轮合并到一起

**Comment by airyland** [comment]
终于明白了，是指单栏里`年月日`合并在一起。

**Comment by w2819** [comment]
嗯嗯，很多出行类的项目都是用的这种
