### ISSUE TITLE
Datetime

### ISSUE THREAD

**Issue by ada012** [airyland/vux#972]
![wechatimg44](https://cloud.githubusercontent.com/assets/8544506/23154032/b0c2d5c6-f846-11e6-9009-4be32097573c.jpeg)

"vux": "^2.1.0-rc.48"
 "vux-loader": "^1.0.36"

弹出框除了当前选中的应该都是阴影虚幻的吧

**Comment by airyland** [comment]
不大明白你的阴影虚幻是什么意思？

来个你认为合适的样式截图？

**Comment by ada012** [comment]
@airyland 
![image](https://cloud.githubusercontent.com/assets/8544506/23196586/7c5c4f88-f8f5-11e6-84c0-6ebe1bc5a484.png)

**Comment by airyland** [comment]
demo 并不能重现。
