### ISSUE TITLE
升级webpack2.x后,build/utils.js 中的cssLoader和styleLoader还能兼容吗?

### ISSUE THREAD

**Issue by zWingz** [airyland/vux#974]
按道理说.webpack2.0应该是不支持webpack1.0中loader的语法
但这里引用了cssLoader和styleLoader却是webpack1.0的语法.
因为我最近也升级了webpack2.0,但我是需要修改cssLoader和styleLoader才能跑起来.

**Comment by airyland** [comment]
你可以直接参考官方模板：https://github.com/vuejs-templates/webpack/tree/master/template/build
