### ISSUE TITLE
import { dateFormat } from 'vux' 

### ISSUE THREAD

**Issue by ZLJASON** [airyland/vux#975]
### 问题：
1.页面 import { dateFormat } from 'vux'
2.npm run dev 后页面正常访问，日期格式化工具无效
3.控制台输出
This dependency was not found in node_modules:

* ../tools/date/format.js

Did you forget to run npm install --save for it?

**Comment by airyland** [comment]
更新vux后是否有重新npm run dev?

**Comment by ZLJASON** [comment]
有

**Comment by airyland** [comment]
那么打开node_modules/vux 能不能在源码里找到这个文件？

**Comment by ZLJASON** [comment]
我是直接下载后npm install后，在扩展插件（插件文件使用import { dateFormat } from 'vux'），所以node_modules下没有vux。插件的标签都生效，导入其他格式方法可以正常运行

**Comment by airyland** [comment]
不明白你说的扩展插件是什么意思 ❓

**Comment by ZLJASON** [comment]
直接在src/components/下面新建组键（新建的vue文件中使用import { dateFormat } from 'vux'），在map.json中添加路径映射。

早上我试了，直接在src/components/actionsheet/index.vue 下面添加import { dateFormat } from 'vux'在npm run dev 同样出现。是不是webpack.config 哪里的路径配置有问题

**Comment by airyland** [comment]
我还是弄不明白你到底怎么使用的，你是直接在源码中import? 还是新建项目来引用vux?
在源码中一般不会出现使用import from vux 而是直接相对路径。

**Comment by airyland** [comment]
在新建项目调用 dateFormat 并不能重现。直接使用vux2的模板或者对比一下配置吧。
