### ISSUE TITLE
建议Radio组件添加icon slot

### ISSUE THREAD

**Issue by zhengtulymGh** [airyland/vux#979]
建议Radio组件添加icon slot

**Comment by airyland** [comment]
因为列表是赋值而不是类似于 radio-item 的子组件，无法用slot设置，但是可以考虑为列表项加上 `icon` 属性。

**Comment by lingyunzhu** [comment]
Radio现在支持icon了么，列表项加上 icon 属性不起作用
{
        icon: 'http://dn-placeholder.qbox.me/110x110/FF2D55/000',
        key: '004',
        value: '线下支付'
      }

**Comment by airyland** [comment]
@lingyunzhu 版本太低了吧。

**Comment by lingyunzhu** [comment]
谢谢，我更新下

**Comment by lingyunzhu** [comment]
@airyland 更新后icon起作用了，但像这样<radio  :options="payways" value="支付宝" v-model="payway"></radio> 用value设置的默认值不起作用了
