### ISSUE TITLE
 PopupPicker在子节点层级不同的情况下，没有显示全

### ISSUE THREAD

**Issue by lmasdata** [airyland/vux#980]
数据中有两个根节点A，B
A节点下有两级子节点
B节点下有四级子节点
最后渲染出的数据只有两级。

**Comment by airyland** [comment]
你这样说相当难理解。贴数据吧。
原则上要求自己保证数据是完整的列数的。

**Comment by lmasdata** [comment]
数据：
![image](https://cloud.githubusercontent.com/assets/8501594/23291495/069291cc-fa94-11e6-93c5-74b06c8b93fe.png)
因为城市项目总共有两层，导致别墅项目也显示了两层，数据中有四层

![image](https://cloud.githubusercontent.com/assets/8501594/23291547/4de8b7a4-fa94-11e6-81d8-d7cd68532cf1.png)

**Comment by airyland** [comment]
请上文字数据再重开，不要截图好吗，这样怎么方便重现？
