### ISSUE TITLE
datetime显示问题

### ISSUE THREAD

**Issue by 0xfnzero** [airyland/vux#981]
运行例子，日期控件的箭头不在一行的最后面，和日期值紧紧在一起
运行系统：iOS
版本：2.1.0-rc.50
![image](https://cloud.githubusercontent.com/assets/2081812/23252926/8986f78c-f9ed-11e6-92d6-a3888d397cfa.png)

**Comment by airyland** [comment]
iOS 几？

**Comment by fengjiankang** [comment]
在demo上显示正常，在我项目上箭头紧紧挨在日期之后

**Comment by airyland** [comment]
如果同个机子demo正常，检查一下是不是项目样式冲突了。

**Comment by 0xfnzero** [comment]
我把vux版本更新到 "vux": "^2.1.0-rc.48" 就是正常的，
我下载的demo运行也不正常，版本是：
"name": "vux",
"version": "2.1.0-rc.51",

**Comment by airyland** [comment]
datetime近期基本没有更新。你上面截图的样式和vux demo样式也不一致。iOS你也并没有指出哪个版本，所以还有问题你大概要自己检查一下了。我重现不了。

**Comment by Garfield-yin** [comment]
2.1.0-rc.50版本样式冲突。

**Comment by fengjiankang** [comment]
Yes, 确实样式有冲突

**Comment by airyland** [comment]
@godfrey-yin @fengjiankang 话说倒是提供一下细节，话说一半对别人没有任何帮助也解决不了问题。

**Comment by Garfield-yin** [comment]
当使用2.1.0-rc.50版本的datetime组件时，cell组件会出现如上图(第一个帖子)所示的的情况。
最新版本2.2.1-rc.7中，datetime 嵌套 cell,会出现如下样式问题：

![aa](https://cloud.githubusercontent.com/assets/12005405/25176549/0995abbc-2531-11e7-88d3-85528242eeef.jpg)

```
    <group title="计划开始日期">
        <datetime v-model="2017-04-19" @on-change="startDateChange"   :title='current_start_date'>
            <cell title="2017-04-19" is-link ></cell>
        </datetime>
    </group>
```

**Comment by airyland** [comment]
@godfrey-yin 图片没有传成功

**Comment by Garfield-yin** [comment]
@airyland 好了。

**Comment by Garfield-yin** [comment]
@airyland 目前是这样解决：
```
    <group title="计划开始日期">
        <datetime style="width:100%;" v-model="current_start_date" @on-change="startDateChange"   :title='current_start_date' confirm-text='确认' cancel-text='取消'>
            <cell style="width: 100%;right: 15px;height: 4px;" :title="current_start_date" is-link ></cell>
        </datetime>
    </group>

```

**Comment by airyland** [comment]
@godfrey-yin 源码里哪一行样式产生的冲突？

**Comment by fengjiankang** [comment]
我设置了应用的默认字体，应该是和datetime的字体样式起冲突了，去掉以后就解决了
