### ISSUE TITLE
升级到最新版的vux2.1 vux-loader 1.0.41 , 自定义theme.less失效

### ISSUE THREAD

**Issue by marsal1212** [airyland/vux#982]
"vue": "^2.1.10",
    "vux": "^2.1.0",
    "vux-loader": "^1.0.41",
    "webpack": "^2.2.1"

**_webpack.base.conf.js_**
const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [
    {
      name: 'vux-ui'
    },
    {
      name: 'less-theme',
      path: 'src/common/style/theme.less'
    },
    {
      name: 'duplicate-style',
      events: {
        done: function () {
          console.log('done!')
        }
      }
    }
  ]
})

**_theme.less_** 
@tabbar-text-active-color: #f5c305;

@header-background-color: #B72712;

跑起来之后 .weui-tabbar__icon内的颜色还是#09BB07这个默认颜色。

**Comment by airyland** [comment]
今天会发个小版本解决。
