### ISSUE TITLE
请问有配合tabBar一起使用的组件吗？

### ISSUE THREAD

**Issue by hezhongfeng** [airyland/vux#984]
前些日子在使用`mint-ui`的时候使用过其中的[tab-container](http://mint-ui.github.io/docs/#!/zh-cn2/tab-container)和底部的tabBar一起使用，用来实现tab的切换
在vux中没找到类似的组件
请问在vux中推荐怎么使用tabBar?例子中并没有实现各个tab之间的切换
谢谢

**Comment by airyland** [comment]
没有。tabbar只负责导航，你自己绑定点击tabbar-item的事件去显示对应的div就行了。

**Comment by hezhongfeng** [comment]
好哒
