### ISSUE TITLE
XButton show-loading issue

### ISSUE THREAD

**Issue by malaimoo** [airyland/vux#986]
version：最新的2.1.0
platform: mac chrome 56
使用
```
    <x-button show-loading type="warn">确定</x-button>

```
头部 spiner 无法显示。
感觉是这个加载图片显示不出来。

```
    background-image: url(data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' …255,255,.03)' rx='5' ry='5' transform='rotate(-30 -5.98 65)'/%3E%3C/svg%3E);
```

**Comment by airyland** [comment]
打开demo页面，如果正常说明是你使用问题。检查是否有样式冲突。

**Comment by christlee1989** [comment]
这个确实有问题，如果你单独引入的xbutton，那么就需要再引入loading控件，因为weui-button.less文件里没有引入weui-loading.less，所以没有weui-loading这个类。
import {XButton,Loading } from 'vux'；
只需要引入Loading，加载loading的样式就可以了

**Comment by airyland** [comment]
明白了，就是loading样式没有引入。今天发个小版本解决。
