### ISSUE TITLE
tab 组件宽度超出视图约1px 导致页面可左右拖动。

### ISSUE THREAD

**Issue by shamoq** [airyland/vux#995]
### Version
 npm:  3.10.9
"vux": "^2.1.0-rc.48"
### Android or iOS
iphone5s
> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<!--put your code here-->
<template>
  <div style="background: #fff;padding-top: 15px;">
    <tab v-model="tabIndex">
      <tab-item selected >tab1</tab-item>
      <tab-item >tab2</tab-item>
      <tab-item >tab3</tab-item>
    </tab>
  </div>
</template>

```

### Expected behavior and actual behavior.
期望页面默认不允许左右拖动。
手机上加载该组件后，发现页面可以左右拖动，猜测是某组件的宽度超过了，经过排查，发现是tab组件宽度超了。
### Steps to reproduce the problem
1. 加载该组件，在iphone5s safari浏览器上发现可左右拖动。
2. 给tab增加样式 width = 99% 即可解决该问题

**Comment by airyland** [comment]
chrome, safari 上能不能重现？

**Comment by shamoq** [comment]
感谢你的回复，问题是可以重现的，浏览器上选取元素，可以看到其宽度超了一点点，在手机上的表现则是页面可左右拖动，我晚点去掉不相关代码，写个demo重现试试。
demo地址： http://files.cnblogs.com/files/codealone/demo.zip
昨天测试的时候在ipad上是无法拖动的，顺便试了下5s横屏的时候，也是无法拖动的，只有竖屏就有问题，不知道这些信息能否给你少许帮助，再次感谢。

**Comment by airyland** [comment]
在6s上测试不出问题。如果只是5s有问题，那上面的 width = 99% 也不是个好方法。因为我并没有5s机器无法进行调试。你上面说在在浏览器上选取元素能重现是如何知道超了的，我看tab总宽度和屏幕宽度完全一致。

**Comment by a304885433** [comment]
嗯，宽度好像是一样的，可能是我上次看错了。最后只能提供2个图，看看能不能给点帮助吧。
![image](https://cloud.githubusercontent.com/assets/3955567/23328951/9344d61e-fb68-11e6-9c66-159f35dadae5.png)
![image](http://images.cnblogs.com/cnblogs_com/codealone/953502/t_F8D5DD9EA12F1E8A72C29BD92CF1BBBB.jpg)
确认了下，不是我代码的问题，官方demo也会这样，我的5s是4.7寸屏，这个问题也不是什么大问题吧。

**Comment by airyland** [comment]
你可以试一下在上级加个overflow:hidden 试试，因为没有5s，暂时无法重现。

**Comment by shamoq** [comment]
嗯，下午有点事不在电脑前，刚刚试了你说的方案，可以解决。
