### ISSUE TITLE
关于uploader 组件的实现

### ISSUE THREAD

**Issue by greedying** [airyland/vux#997]
因为vux不会实现uploader组件，原因见[#682](https://github.com/airyland/vux/issues/682)

 我个人简单实现了部分功能，作为vux没有实现uploader的补充，欢迎使用。

 vux-uploader作为vux的补充，使用的时候，需要你的项目首先使用vux 2.*版本

(点此进入vux-uploader)[github : https://github.com/greedying/vux-uploader]

还有很多复杂些的功能没有实现，欢迎fork，star和PR

**Comment by airyland** [comment]
看到入口是引用.vue文件，你好像没有需要说明如何配置babel编译你的main.js文件

**Comment by greedying** [comment]
因为是对vux的补充，所以使用这个组件的人，肯定已经配置过环境了。

**Comment by airyland** [comment]
上个demo会更好，组件成熟后直接merge进vux也是可以的。

**Comment by greedying** [comment]
恩，我来是想提个pr的，不过看之前的issue，感觉你不会同意，所以单独做了个项目。

有时间再写demo吧，学习各种配置以及写文档的的时间远超出了我的预期，导致我这边现在时间比较紧。

其实做成依赖vux，一方面是因为是对vux的补充，另外一方面，也是提升使用门槛

**Comment by airyland** [comment]
合并到 #139

**Comment by wxingheng** [comment]
@greedying  一个完美的补充，包含完整的演示demo   [vux-uploads](https://github.com/wxingheng/vux-uploads)
