### ISSUE TITLE
InlineCalendar调用render-function报无限循环错误

### ISSUE THREAD

**Issue by w2819** [airyland/vux#999]
[Vue warn]: You may have an infinite update loop in a component render function. 
(found in <InlineCalendar> at D:\aa\node_modules\vux\src\components\inline-calendar\index.vue)

`:render-function="buildSlotFn"`
```js
buildSlotFn (line, index, data) {
        let temp = '';
        data.disabled = true;
        for (let m = 0; m < this.skuList.length; m++) {
          let newValTemp = this.skuList[m], startupTime, sMonth, sTime;
            if (newValTemp.startupTime) {
              startupTime = newValTemp.startupTime.replace(/-/g, '\/')
              sMonth = new Date(startupTime).getMonth();
              sTime = new Date(startupTime).getDate();
              if (sMonth == data.month && sTime == data.day) {
                temp = '¥' + newValTemp.price
                data.disabled = false
                data.id = newValTemp.id
                break
              }
            }  
        }
        return temp;
      },
```

发现组件内，render函数会执行多次，是不是这个造成的

**Comment by airyland** [comment]
`data.disabled = true` 这一句很可疑，这里不能直接修改data。

**Comment by w2819** [comment]
确实，注视掉了就没有报错，但是1.0的时候这么写是没有问题的，升级后就有这个问题。日期上面有对应的价格，没有价格的日期是不让用户选择的，所以还是存在修改disabled这个需求

**Comment by 327326724** [comment]
select方法里面可以设置一个回调么，需要用child这个参数做一些回调

**Comment by airyland** [comment]
我在demo上试了下，修改data.disabled并不会出现报错。

**Comment by w2819** [comment]
只要有循环，无论是在循环里面还是外面，有这句`data.disabled = true`就会报错，下面的设置为false不会

**Comment by airyland** [comment]
即使我加个循环测试也重现不了。

**Comment by airyland** [comment]
暂时没有适当的方法无副作用来修改data, 建议直接用选择元素的形式来设置 disabled.

``` js
document.querySelector("[data-date='2017-02-15']").classList.add('is-disabled')
```

**Comment by w2819** [comment]
好的

**Comment by luguiqing** [comment]
document.querySelector("[data-date='2017-02-15']").classList.add('is-disabled')
这个如果变月份了，但是这个类还在，会影响其他的日期的样式。（就是同个p元素，换了内容，但还是原来的p元素，原来的类名你没及时清掉的话，还是会影响其他日期的）

**Comment by airyland** [comment]
@luguiqing 拜托这位大哥把问题说清楚，组件根本没有 p 元素。

**Comment by luguiqing** [comment]
` document.querySelector("[data-date='2017-09-24']").classList.add('is-disabled')`
假设我通过这个添加了一个is-disabled的类， 我切换到10月份时，在同样的位置10月29号，也会有原来加给9月24号的is-disabled这个类。。你没有移除掉它。如果使用data.disabled = true，就不会出现10月29号这个td元素上也有is-disabled这个类。

ps: 用这两个方式让具体日期添加了is-disabled这个类后，还是可以选择的啊？！目前我用很笨的方法，通过on-chang监听，然后匹配不可选的日期，手动pop掉。

**Comment by luguiqing** [comment]
@airyland 谅解，大哥你有空的话试试？

**Comment by airyland** [comment]
@luguiqing render-function 已经不推荐使用，用 slot:each-day 定义每一项吧。功能职责上讲，DOM 上的样式属性谁加就谁来移除，组件内部不能知道也不应该去移除 dom 上的类名或者属性。组件也提供了事件 on-view-change 在切换时可以做一些操作。

**Comment by luguiqing** [comment]
@airyland 
`<inline-calendar
                v-model="value1"
                @on-change="time1"
                ref="calendar"
                :render-function="buildSlotFn"
                @on-view-change="monthChange">
                <p slot="each-day">44</p>
            </inline-calendar>`
文档没讲。百度不到。并不知道怎么用（原谅我看源码没看懂）。
ps document.querySelector("[data-date='2017-02-15']").classList.add('is-disabled'),要自己维护样式，就是因为你建议用这个才觉得差评的。

**Comment by airyland** [comment]
@luguiqing 这是一个2月份的 issue，距今有半年之久，信息早已过期，如果你觉得不合适有更合适的建议可以新开 issue 来建议。
